### ISSUE TITLE
Form checkbox fields not responding to click as expected

### ISSUE THREAD

**Issue by ckoch-cars** [phoenixframework/phoenix_live_view#1001]
### Environment

* Elixir version (elixir -v): 1.10.3
* Phoenix version (mix deps): 1.5.3
* Phoenix LiveView version (mix deps): 0.13.3
* NodeJS version (node -v): 12.13.1
* NPM version (npm -v): 6.12.1
* Operating system: OSX (Mojave 10.14.6)
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, Firefox, Safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Problem description

In another project, I ran into an issue where a checkbox field on a form would respond inconsistently to clicks. When changing a checkbox state, and then changing another field, the state of both the current field and the previous field would occasionally become intertwined.

Example: 
If I click`field A` (the checkbox  for `field A` would change) and then click  `field B` (the checkbox for `field A`  and the checkbox for `field B` would both toggle) 
If I then click `field C`  (the checkbox for `field B`  and the checkbox for `field C` would both toggle) 

It was not entirely clear where the underlying issue lay. In attempting to isolate the issue in a repo, I was able to reproduce a similar but slight different (and possibly related issue) of checkboxes requiring an extra click for the visible state of the. checkbox to update. 

Form checkboxes appear to require double input in order for the checked state to update on the page. The checkbox validation fires twice. Inspecting the forms params, it appears the checkbox (checked) value is set the first time the checkbox is clicked, but the checked state of the html object does not update. Occasionally, there's a briefly noticeable stutter on the page, but the checkbox remains unchecked. Clicking the checkbox again sets the visible state to checked and the checkbox (checked) value remains "true".

### Actual behavior

Given a checkbox in a form on a LiveView page, the checkbox checked state does not respond as expected. 
(when unchecked and form state has the checkbox unchecked)
  a single click has no visible change to the checkbox, but the form change event fires and hits live view. A second click causes the checkbox (visible) state to change
(when checked and form state has the checkbox checked)
  a single click has no visible change to the checkbox, but the form change event fires and hits live view. A second click causes the checkbox (visible) state to change
(when checkbox visible state has changed from the form state [IE checked to unchecked])
  a single click changes the checkbox state and fires the LiveView change event. 

### Expected behavior

Normal checkbox behavior
(when unchecked, a single click checks the checkbox regardless of form state)
(when checked, a single click unchecks the checkbox regardless of form state)

### Example 
https://github.com/ckoch-cars/Demo-LiveView-Bug
Readme describes setup and steps to reproduce the issue.

**Comment by chrismccord** [comment]
This is working as expected. In your example, you are setting the checked state on the server via:

```
      <%= checkbox f, :email_checkbox, checked: !!Map.get(@changeset.changes, :email) %>
```

But when you click on the checkbox, the `changeset.changes` will be `%{}`. So it makes sense in this case that the check would not be maintained when clicked because you immediately unset it on the server. Entering text in the email input then allows the input to be checked because there are now changes.changes.email present. Thanks!

**Comment by ckoch-cars** [comment]
@chrismccord  I'm not sure I understand. (The main reason for setting the checkbox based on `changeset.changes` is to provide some kind of initial state.) If the checkbox is getting set on the server why would it ever be checkable?  Wouldn't the server set the state every time until the is a change to the related field? 

In the example, the checkbox appears to not get checked on the first click, but the the second click does check the box and a third click unchecks it. 

Admittedly tying a checkbox to a separate form field, may be (slightly) abusing the intention of the checkbox, but it still seems like there could be some way to set a checkbox based on server-side or user input. 

Thank you for any thoughts you care to offer

**Comment by sajanbasnet75** [comment]
@ckoch-cars  How did you solve this ?

**Comment by BryanJBryce** [comment]
@sajanbasnet75 @ckoch-cars Try removing the `checked:` or `value:` from your form and instead when you set the initial changeset on the form give `:email_checkbox` an initial value of `true`
