### ISSUE TITLE
Resizable textareas reset their size after input

### ISSUE THREAD

**Issue by cbrewster** [phoenixframework/phoenix_live_view#1011]
### Environment

* Elixir version (elixir -v): `1.10.0`
* Phoenix version (mix deps): `1.5.3`
* Phoenix LiveView version (mix deps): `0.13.3`
* NodeJS version (node -v): `v14.3.0`
* NPM version (npm -v): `6.14.4`
* Operating system: `macOS 10.15.4`
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox, Safari, 
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

If you resize a resizable textarea inside a form in a live view, the size will reset when you type in the textarea or any other form elements.

The browser adds inline styles to the textarea which override the width/height when resizing and it looks like live view removes these styles which resets the size of the live view.

```html
<%= f = form_for @changeset, "#",
  id: "task-form",
  phx_target: @myself,
  phx_change: "validate",
  phx_submit: "save" %>
    <%= textarea f, :description %>
    <%= submit "Save", phx_disable_with: "Saving..." %>
</form>
```

![textarea-resize-issue](https://user-images.githubusercontent.com/9086315/85619963-52a56080-b620-11ea-9267-41ca853ac70b.gif)

### Expected behavior

Typing in resized textareas does not cause the size of the textarea to be reset.

**Comment by chrismccord** [comment]
There's no good way for us to distinguish a style change on the client like this from any other client code. We could force the s style to be maintained, but then you would not be able to override it from the server. Your best bet today is to add a hook:


```eex
  <%= textarea f, :body, phx_hook: "MaintainAttrs", data_attrs: "style" %>
```

```javascript
Hooks.MaintainAttrs = {
  attrs(){ return this.el.getAttribute("data-attrs").split(", ") },
  beforeUpdate(){ this.prevAttrs = this.attrs().map(name => [name, this.el.getAttribute(name)]) },
  updated(){ this.prevAttrs.forEach(([name, val]) => this.el.setAttribute(name, val)) }
}
```

Thanks!

**Comment by TheArrowsmith** [comment]
Here's a simpler version that worked for me, since the only attribute of my textarea(s) that users are able to adjust is their height:

```javascript
const MaintainStyles = {
  beforeUpdate() { this.prevHeight = this.el.style.height; },

  updated() { this.el.style.height = this.prevHeight; }
}

export default MaintainStyles;
```

**Comment by cobusb** [comment]
T

> Here's a simpler version that worked for me, since the only attribute of my textarea(s) that users are able to adjust is their height:
> 
> ```js
> const MaintainHeight = {
>   beforeUpdate() { this.prevHeight = this.el.style.height; },
> 
>   updated() { this.el.style.height = this.prevHeight; }
> }
> 
> export default MaintainHeight;
> ```

this is a great solution, but I found it needs to be combined with a phx-debounce to prevent push_navigate/push_patch events from hanging/crashing.

**Comment by ponychicken** [comment]
```js
const liveSocket = new LiveSocket("/live", Socket, {
  longPollFallbackMs: 2500,
  params: { _csrf_token: csrfToken },
  hooks: Hooks,
  dom: {
    onBeforeElUpdated: (fromEl, toEl) => {
      if (fromEl.tagName === "TEXTAREA") {
        toEl.style.height = fromEl.style.height;
      }
    },
  },
});
```
I am using this hook to fix all textareas in one go. @chrismccord would you be open to a MR that includes this in core?
