### ISSUE TITLE
Missing releases section on Github

### ISSUE THREAD

**Issue by shankardevy** [phoenixframework/phoenix_live_view#1015]
On https://github.com/phoenixframework/phoenix_live_view, the releases section is missing.

<img width="398" alt="Screenshot 2020-06-26 at 7 56 50 AM" src="https://user-images.githubusercontent.com/2011812/85814071-ab8d0a00-b782-11ea-911e-c75d9f7d41f0.png">

**Comment by josevalim** [comment]
I added a link to hex.pm, the best place to check for releases.
