### ISSUE TITLE
Bad markup when layout is not specified in router

### ISSUE THREAD

**Issue by bobwaycott** [phoenixframework/phoenix_live_view#1019]
### Environment

* Elixir version (elixir -v): **1.10.3**
* Phoenix version (mix deps): **1.5.3**
* Phoenix LiveView version (mix deps): **0.13.3**
* NodeJS version (node -v): **12.16.0**
* NPM version (npm -v): **6.13.4**
* Operating system: **macOS**
* Browsers you attempted to reproduce this bug on (the more the merrier): **Safari, Firefox, Chrome, Brave**
* Does the problem persist after removing "assets/node_modules" and trying again? **Yes**

### Actual behavior

When adding `LiveView` to an existing Phoenix application, and updating that existing application to approximate as closely as possible to a newly generated app with the `--live` flag, invalid/unexpected markup is generated when a `layout` *is not* set at the router level, and the `LiveView` instead opts for setting its own layout in either the `AppWeb.live_view/0` macro or in the `LiveView` module itself.

#### Two ways to produce invalid markup

**1.** In `app_web.ex`, a `live_view/0` macro is added with the following definition:

```elixir
def live_view do
  quote do
    use Phoenix.LiveView, layout: {AppWeb.Live.LayoutView, "app.html"}
    unquote(live_view_helpers())
  end
end
```

**2.** In `my_live.ex`, a `LiveView` module is defined like so:

```elixir
defmodule AppWeb.Live.MyLive do
  use Phoenix.LiveView, layout: {AppWeb.Live.LayoutView, "app.html"}
  ...
end
```

In either case above, we are using a `live` route in the router, like so:

```elixir
live "/", AppWeb.Live.MyLive
```

The resulting markup at render moves the *entire contents* of the `<head>` tag **into** the `<body>` tag, inside a `<div>` tag that is not part of the `app.html` template, and has some `phx-` attributes set on it. Here is a screenshot of the resulting markup:

<img width="412" alt="no-router-layout" src="https://user-images.githubusercontent.com/196710/86035794-e4d7ab00-ba0a-11ea-9f5d-b8bfa41b0767.png">

#### Producing expected markup

**1.** Add a root layout in a pipeline for the `live` route in `router.ex`:

```elixir
pipeline :mylive do
  ...
  plug :put_root_layout, {AppWeb.Live.LayoutView, :app}
  ...
end
```

**2.** Set a layout on the `live` route directly:

```elixir
live "/", AppWeb.Live.MyLive, layout: {AppWeb.Live.LayoutView, :app}
```

In both cases, the resulting markup matches the template and looks as expected:

<img width="523" alt="with-router-layout" src="https://user-images.githubusercontent.com/196710/86036212-8c54dd80-ba0b-11ea-91ef-090dc590ba0e.png">

### Expected behavior

I would expect that markup to not get mangled when opting to set the layout in the `live_view` macro or on the `LiveView` module directly instead of at the router level.

I've read through the docs, and I'm led to believe that it should be valid to omit setting layouts at the router level, and opt for setting them at the `LiveView` module/macro directly, when you don't want to use a `root` layout *plus* a `live` layout, and when you need the live layout to be entirely separate from the rest of an existing application.

**Comment by josevalim** [comment]
This is intentional. We cannot make the whole HTML document live. You need to wrap it rather with a router layout or a root layout.

We need to improve the docs to make it clear at least one of them is necessary.

**Comment by bobwaycott** [comment]
Thanks, José! I had a feeling this wasn't an accident, but wanted to file the issue because I recently [had a conversation on the ElixirForum](https://elixirforum.com/t/liveview-livereload-socket-failing-to-connect-on-live-routes/32299/6) with another dev who encountered the same issue, and the docs weren't spelling out the necessity of providing a layout in the router—but we stumbled upon noticing the markup was not matching our expectations, which led me to realizing this was happening.
