### ISSUE TITLE
Nested live components gets skipped when live patched back

### ISSUE THREAD

**Issue by jayjun** [phoenixframework/phoenix_live_view#1033]
### Environment

* Elixir version (elixir -v): 1.10.3
* Phoenix version (mix deps): 1.5.3
* Phoenix LiveView version (mix deps): 0.13.3
* NodeJS version (node -v): 14.2.0
* NPM version (npm -v): 6.14.4
* Operating system: macOS
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome 83.0.4103.116, Firefox 78.0.1, Safari 13.1.1
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

![nested_skipped](https://user-images.githubusercontent.com/4433966/86531839-3eeadb80-bef7-11ea-9675-91bd831567ed.gif)

Sample repo: https://github.com/jayjun/live_view_nested_skipped

1. In this live view, `FooComponent` nests `BarComponent`.
2. Clicking _Show Bar Component_ live patches to show `BarComponent`.
3. Clicking _Close_ in `BarComponent` live patches back to root route.
4. Clicking _Show Bar Component_ again does not show `BarComponent`. `BarComponent`’s container is marked with `data-phx-skip`.

### Expected behavior

I expect `BarComponent` to show after clicking _Show Bar Component_ again.

**Comment by josevalim** [comment]
Please give master a try. We have many fixes related to components merged. Remember to nuke `node_modules` after updating.

**Comment by jayjun** [comment]
Works on master! Feel free to close.
