### ISSUE TITLE
Channels MatchError: Missing `assign_new`

### ISSUE THREAD

**Issue by novaugust** [phoenixframework/phoenix_live_view#1036]
### Environment

* Elixir version (elixir -v): 1.9.4
* Phoenix version (mix deps): 1.5.3
* Phoenix LiveView version (mix deps):0.13.3
* NodeJS version (node -v): 10.16.0
* NPM version (npm -v):6.13.0
* Operating system:ubuntu
* Browsers you attempted to reproduce this bug on (the more the merrier): 
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:

### Actual behavior

Getting a match error on the following stack trace
```
** (MatchError) (... snip ...)
(phoenix_live_view) lib/phoenix_live_view/channel.ex:610: Phoenix.LiveView.Channel.verified_mount/5
(phoenix_live_view) lib/phoenix_live_view/channel.ex:43: Phoenix.LiveView.Channel.handle_info/2
```

In comparing what's expected and what's on the right hand side, the missing expected key is `assign_new` (whereas `assigned_new` is there).

Related to #428 - this happens when the client is running an old version of the code and the server bumps its version up.

### Expected behavior

This happens once for a user and moves on. I currently have a few thousand reports of this error on an app with only hundreds of users

**Comment by novaugust** [comment]
Seeems related to #428 in that it's the same region of code breaking things. But if it's automatically fixing things via an `outdated` message, I'd expect the error to go away - it is not doing that.

**Comment by josevalim** [comment]
We have recently added token versioning, so this is no longer errors the next time we change the encoded payload. Once you see it happening, you can also change the LV salt and redeploy. This will force everyone to cleanly upgrade too. Thanks!
