### ISSUE TITLE
Probably a bug with change tracking the variables

### ISSUE THREAD

**Issue by DaTrader** [phoenixframework/phoenix_live_view#1049]
### Environment

* Elixir version (elixir -v): 1.10.3
* Phoenix version (mix deps): 1.5.3
* Phoenix LiveView version (mix deps): 0.14.0
* NodeJS version (node -v): 12.14.1
* NPM version (npm -v): 6.13.4
* Operating system: Linux Mint
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox, Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

A block of code in my template that looks like the one below only reaches the 'unless is_nil( var_c)' line when rendered for the first time. On each subsequent template render, the data-c attribute value remains unchanged despite the fact that when inspecting @some_data assign in the with clause, it clearly shows that the value changes each time the template is rendered.

`
```
<div class="some_class"
     id="some_unique"
     ..
     <%= with %{ a: var_a, b: var_b, c: var_c} <- @some_data do %>
        ..
       <%= unless var_a == :failure && !var_b do %>
         <%= unless is_nil( var_c) do %>
          data-c="<%= var_c %>"
         <% end %>
       <% end %>
       ..
     <% end %>
     ..
     phx-hook="SomeHook">

````

### Expected behavior

The value var_c in  the data-c attribute should be rendered when it changed from the last time as it did on LV v0.7.1, but now on v0.13.2 and v0.14.0 it no longer does.

If this is not a bug, but the intended behavior as described under change tracking, then somebody please explain to me what I am doing wrong as the variables are specified solely in the with clause as required by the LiveView docs.

TIA

**Comment by josevalim** [comment]
Can you please provide a minimum LiveView that reproduces the issue?

**Comment by DaTrader** [comment]
Unfortunately, I can't. I just upgraded from 0.7.1 to 0.13.2 then to 0.14.0, so no.

**Comment by DaTrader** [comment]
I mean, I can give it a try and go back to 0.10.0 then cut in half from there to 0.8.0 or 0.12.0 etc. Do you need me to do that?

**Comment by DaTrader** [comment]
Btw, I just prepended the real life analogue to @some_data assign before each of the variables (there are more of them in the real code) and when accessing them as members of the assigned map it all works ok as expected.
But I must say I am not comfortable with it because unlike in this particular case where I can do it (it looks very verbose though). in numerous other places all over my templates I use variables in a similar fashion and use them in nested comprehensions and clauses and it will be simply impossible to prepend an assign before them to make them work like I did in this simple case.

**Comment by josevalim** [comment]
I mean, it can be a single file that you can isolate on separate project that reproduces the issue. Otherwise there isn’t much we can do.

**Comment by josevalim** [comment]
The LV example I am asking can run on v0.14, not worried about the previous versions. :)

**Comment by DaTrader** [comment]
I see. Ok, will do.

**Comment by DaTrader** [comment]
@josevalim 

Please download the following branch of the modified Chris McCord's Chirp app:
https://github.com/DaTrader/chirp_modified/tree/change_tracking_bug

Once installed, go to localhost:4000/posts url and then inspect the first post in the browser and you will see I put the original div with posts within this div with id="holder". Click on the like of the first post as many times as you like and you will see that nothing changes in the "holder" div. If you downgrade LV to v0.12.0 you will see the expected changes of the data-print attribute (a make_ref string). Also, if you prepend each of the variables (index.html.leex file, lines 14 to 19) with @some_data. it will work on 0.14.0 as well, and that's our issue here.

So, the answer to what I thought was your original question above (I was tired yesterday so misread what you wrote) is that the latest version of LV that works properly and does not have this bug is 0.12.x.

Best,

Damir
