### ISSUE TITLE
LiveComponent target reference as LiveComponent.CID breaks non-eex templates

### ISSUE THREAD

**Issue by mattdb** [phoenixframework/phoenix_live_view#1054]
## Background

#964 introduced a struct when a LiveComponent references its `@myself` assign in order to make using the value incorrectly more clear. It integrates with existing code by implementing `to_iodata` for the struct, so a template directly inserting `@myself`

## Problem

Some templating languages have syntax that doesn't allow dynamic substitution at _all_ points within the template. Specifically, I am using slime. If I want to use a dynamic value within a tag attribute, this is [done via string interpolation](https://github.com/slime-lang/slime#attributes):

```slim
a.edit-button href="#" phx-click="start-edit" phx-target="#{@myself}"
```

Because the reference goes through a string before being escaped/"safeified", 0.14.0 blew up several of my views with fairly cryptic error messages. (`protocol String.Chars not implemented for %Phoenix.LiveComponent.CID`) I recognize this is in part a limitation of a non-default template syntax, but it seems like we are stealth-adding another requirement for template languages.

I definitely appreciate the goal behind this change. I have worked around this for the time being by either converting templates/sigils to eex or referencing a target with a selector of my own. 

## Questions/Suggestions

1. Perhaps we could make the accidental alignment of component targets and database IDs or similar (the original source of the change -- #895) far less likely by having `@myself` emit the component's actual DOM ID (or similar)? `"phx-FiB90HIFOo992IfB-2-0"`  seems unlikely to be matching any database IDs.
2. While having `@myself` be a struct instead of a string _did_ raise an error when it seemed as though I may have been using it incorrectly, I submit that the error message given was not particularly friendly. I was eventually able to track down the where and why, but it certainly could have been more obvious. I guess the question is, is the goal to provide more safety for experienced devs, or to help guide the less experienced towards the correct usage? If the latter, it feels like the error message could be friendlier. IMO, getting a message like `expected at least one result but got none in query: ... where: p0.id == ^"phx-FiB90HIFOo992IfB-2-0"` would honestly be more clear than the protocol not implemented message, it immediately raises the question of "why I am I passing that in as an ID?". That said, I do understand that a struct does offer cleaner detection of misuse, I just wish the error could be clearer.

**Comment by josevalim** [comment]
We could implement to_string for the cid struct, I don’t see an issue with that. PR please?

I really don’t think we should use UUIDs Or similar for them though. It means payloads will get much bigger.

**Comment by mattdb** [comment]
> We could implement to_string for the cid struct, I don’t see an issue with that. PR please?
I'll be happy to do that. Although implementing to_string would mean not detecting most issues where misused `@myself` goes through a server -> client -> server round trip. It does appear that the original motivating issue was with a task handler, so having to_string would not impact detecting that style of error. Just checking that that seems OK with everyone, it'd be fine with me.

> I really don’t think we should use UUIDs Or similar for them though. It means payloads will get much bigger.
Fair enough.

**Comment by josevalim** [comment]
I am not worried about the server->client->server roundtrip because those won't be detected by `@myself` when using the built-in template. The goal of the struct is to avoid accidents with Elixir code itself. So to_string is fine. :)
