### ISSUE TITLE
Reevaluate if inputs should be overridden only when not focused

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix_live_view#106]
Today, we keep the client input as long as it is focused but this can lead to a race condition when we submit a event and press TAB before we get the server response.

The debounce work and/or increased latency may make those issues more apparent so we have to try things out. I believe the focus behaviour was added when working on the autocomplete, so we have to validate the approaches.

**Comment by kuon** [comment]
My experience shows that it is bad practice to change input value while focused, so I think the current behaviour is good for many apps.

I think the correct thing to do would be to store the user change as an event, and when the server response comes back, look if there is one of those change event waiting, if yes, keep the input untouched and re-issue a `phx_change` event.

**Comment by DarkMarmot** [comment]
Currently, I can clear an input during the phx-submit event. For things like multiselect controls that generate breadcrumb selections, the inability to clear a focused input field forces one to resort to JS. I would love an override for this behavior somehow.

**Comment by josevalim** [comment]
Covered by #569.
