### ISSUE TITLE
CloudFront issue

### ISSUE THREAD

**Issue by ream88** [phoenixframework/phoenix_live_view#1086]
Another day, another AWS CloudFront issue 😞:

```
LiveView session was misconfigured or the user token is outdated.

1) Ensure your session configuration in your endpoint is in a module attribute:
    @session_options [
      ...
    ]
2) Change the `plug Plug.Session` to use said attribute:
    plug Plug.Session, @session_options
3) Also pass the `@session_options` to your LiveView socket:
    socket "/live", Phoenix.LiveView.Socket,
      websocket: [connect_info: [session: @session_options]]
4) Define the CSRF meta tag inside the `<head>` tag in your layout:
    <%= csrf_meta_tag() %>
5) Pass it forward in your app.js:
    let csrfToken = document.querySelector("meta[name='csrf-token']").getAttribute("content");
    let liveSocket = new LiveSocket("/live", Socket, {params: {_csrf_token: csrfToken}});
```

I'm seeing this error in the logs of a Heroku app behind CloudFront. I checked all the steps mentioned here and as the app was created with `mix phx.new --live` all is properly configured. I think the problem is that CloudFront likes to remove and/or cache certain HTTP headers to improve performance, and because of this the WebSocket fails to connect to the host. Any ideas which headers I should whitelist?

EDIT:

Just to clarify, using the domain `app-name.herokuapp.com` provided by Heroku works fine, it fails when visiting the app via `app-name.io`, so the issue is clearly CloudFront.

**Comment by chrismccord** [comment]
We don't use a header for the WebSocket csrf. Can you recreate this yourself or is this something you only occasionally see in the logs? For example, if you have old browser tabs open yourself or by other users containing outdated tokens, then they would keep trying to reconnect and producing the error.

**Comment by ream88** [comment]
Just got it working. I basically just copied the CF distribution settings from another app which uses an older version of LiveView, however it seems nowadays we need cookies to be forwarded to make LiveView work. Hence `@session_options [store: :cookie]`!

So for future-me and others, if you have LiveView behind a CloudFront distribution ensure the following is set:

![Screen Shot 2020-07-21 at 17 55 36](https://user-images.githubusercontent.com/14321/88077394-84f0a200-cb7b-11ea-92e6-3a5a4bfa2b13.png)

**Comment by chrismccord** [comment]
Ah good find! We *do* use the cookie header so that has to be there to read the cookie session :) Glad you got things sorted
