### ISSUE TITLE
`render_change/2` prepends a newline to unchanged textarea values

### ISSUE THREAD

**Issue by aaronrenner** [phoenixframework/phoenix_live_view#1088]
### Environment

* Elixir version (elixir -v): 1.10.3
* Phoenix version (mix deps): 1.5.4
* Phoenix LiveView version (mix deps): 0.14.2
* NodeJS version (node -v): 10.16.0
* NPM version (npm -v): 6.9.0
* Operating system: Mac OS 10.15.6
* Browsers you attempted to reproduce this bug on (the more the merrier): Safari, but error occurs in the test suite
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: no

### Actual behavior

When I have a form with a `textarea` and call `render_change/2` without making any changes, the existing value in the textarea has a `\n` prepended to it. Here's an example test case:

```elixir
defmodule MyAppWeb.FormLiveTest do
  use MyAppWeb.ConnCase

  import Phoenix.LiveViewTest

  test "renders the same data after multiple render change events", %{conn: conn} do
    {:ok, view, _html} = live(conn, "/form")

    assert view
           |> element("form")
           |> render_change(%{"customer" => %{"name" => "Aaron"}}) =~
             ~s|<pre class="result">Aaron</pre>|

    # This assertion fails
    assert view
           |> element("form")
           |> render_change(%{"customer" => %{}}) =~
             ~s|<pre class="result">Aaron</pre>|
  end
end
```

And here's the test failure

```
  1) test renders the same data after multiple render change events (MyAppWeb.FormLiveTest)
     test/my_app_web/live/form_live_test.exs:6
     Assertion with =~ failed
     code:  assert view |> element("form") |> render_change(%{"customer" => %{}}) =~ ~s"<pre class=\\"result\\">Aaron</pre>"
     left:  "<main role=\"main\" class=\"container\"><p class=\"alert alert-info\" role=\"alert\" phx-click=\"lv:clear-flash\" phx-value-key=\"info\"></p><p class=\"alert alert-danger\" role=\"alert\" phx-click=\"lv:clear-flash\" phx-value-key=\"error\"></p><form action=\"#\" method=\"post\" phx-change=\"validate\"><input name=\"_csrf_token\" type=\"hidden\" value=\"EkEfFDF-fHwEMF8-fQ8TIBwAASMiIz0pBxOWh-NKvegO4ByiEFbBXWGl\"/><label for=\"customer_name\">Name</label><textarea id=\"customer_name\" name=\"customer[name]\">\n\nAaron</textarea><button type=\"submit\">Submit</button></form><pre class=\"result\">\nAaron</pre></main>"
     right: "<pre class=\"result\">Aaron</pre>"
     stacktrace:
       test/my_app_web/live/form_live_test.exs:14: (test)



Finished in 0.09 seconds
1 test, 1 failure

Randomized with seed 47045

ExUnit Compilation exited abnormally with code 1 at Wed Jul 22 13:08:15
```

### Expected behavior

The value of the `textarea` field should not change if no changes are sent to the server.

### Additional info

I created an app that can be used to recreate the issue here: https://github.com/aaronrenner/live_view_textarea_test_helper_bug

I believe this issue is isolated to the test helpers because I don't see this behavior happening in the browser.

**Comment by josevalim** [comment]
Good find. The root cause is this: https://github.com/phoenixframework/phoenix_html/blob/master/lib/phoenix_html/form.ex#L852

We should strip a single newline if it immediately follows the textarea. It should (hopefully) be an easy fix. :)

**Comment by aaronrenner** [comment]
Ah, I see. Just to confirm, the newline should be stripped in `Phoenix.LiveViewTest` and there shouldn't need to be any changes to `phoenix_html`.

From what I can tell, it seems like the change may need to be made in this area of the code:

https://github.com/phoenixframework/phoenix_live_view/blob/0dc7d41d85c1c74ddb2bded75131291651d0f3d2/lib/phoenix_live_view/test/client_proxy.ex#L790-L806

I'll see about putting together some tests and a PR for it later in the week.

**Comment by josevalim** [comment]
Yup. More precisely, this line: https://github.com/phoenixframework/phoenix_live_view/blob/0dc7d41d85c1c74ddb2bded75131291651d0f3d2/lib/phoenix_live_view/test/client_proxy.ex#L838

There is already a comprehensive element suite, perhaps we can use that. 👍

**Comment by josevalim** [comment]
@aaronrenner I was improving coverage in this area and i took the opportunity to tackle this one too! :D

**Comment by aaronrenner** [comment]
@josevalim Thank you!

**Comment by jwilger** [comment]
It seems like maybe this is occuring again when using the 1.7.0-rc.2 release candidate of phoenix (live_view 0.18.11).
