### ISSUE TITLE
Nested component in liveview's layout is not updated on assigns change

### ISSUE THREAD

**Issue by syfgkjasdkn** [phoenixframework/phoenix_live_view#1089]
### Environment

* Elixir version (elixir -v): 1.10.4
* Phoenix version (mix deps): 1.5.4
* Phoenix LiveView version (mix deps): 0.14.2
* NodeJS version (node -v): v14.5.0
* NPM version (npm -v): 6.14.5
* Operating system: macos
* Browsers you attempted to reproduce this bug on (the more the merrier): chrome, safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: ~~no~~ yes

### Actual behavior

In a live view with a layout of the form:

```
- layout.html.leex
  - perent_component.ex 
    - nested_component.ex
      - value that's not updated
  - live view's @inner_content
```

`value` in the nested component is not being updated when it is changed from the liveview.

### Reproduction

https://github.com/syfgkjasdkn/no-layout-update

#### Steps:

- visit http://localhost:4000, you'll be redirected to http://localhost:4000/1 and the `1` at the top of the page would be plain text, and [`2`]() would be a link
- click [`2`]() to be redirected to http://localhost:4000/2
- `1` stays as plain text, [`2`]() stays a link

Recording: https://www.dropbox.com/s/zq3g2kpbeb1z5tt/no-layout-update.mp4?dl=0

### Expected behavior

[`1`]() at the top of the page becomes a link, `2` becomes plain text as in phoenix live view v0.13.3.

**Comment by josevalim** [comment]
> Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: no

To be clear, you mean "yes", right? The problem persists after removing node_modules?

**Comment by syfgkjasdkn** [comment]
@josevalim ah, sorry, Yes, the problem persist.
