### ISSUE TITLE
assign_new/3 does not rebuild the originally shared assign on connected mount

### ISSUE THREAD

**Issue by balexand** [phoenixframework/phoenix_live_view#1091]
### Environment

* Elixir version (elixir -v): Elixir 1.10.4 (compiled with Erlang/OTP 23)
* Phoenix version (mix deps): 1.5.4
* Phoenix LiveView version (mix deps): 0.14.2
* NodeJS version (node -v): v10.21.0
* NPM version (npm -v): yarn 1.22.4
* Operating system: MacOS 10.15.6
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, Safari, Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Code

Using an empty Phoenix project created with `mix phx.new example --no-ecto --live`, I've changed the following:

```elixir
# lib/example_web/router.ex
pipeline :browser do
  ...
  plug ExampleWeb.AssignMyValue
end
```

```elixir
# lib/example_web/controllers/assign_my_value.ex
defmodule ExampleWeb.AssignMyValue do
  @behaviour Plug

  import Plug.Conn

  @impl true
  def init([]), do: []

  @impl true
  def call(conn, []) do
    assign(conn, :my_value, "from plug")
  end
end
```

```elixir
# lib/example_web/live/page_live.ex
defmodule ExampleWeb.PageLive do
  use ExampleWeb, :live_view

  @impl true
  def mount(_params, _session, socket) do
    {:ok, assign_new(socket, :my_value, fn -> "from live view" end)}
  end
end
```

```html
<%# lib/example_web/live/page_live.html.leex %>
<div>
  <%= @my_value %>
</div>
```

Here's a complete project: https://github.com/balexand/example_bug

### Actual behavior

When the live view is mounted in a disconnected state, the HTML includes the value "from plug". After the live socket connects then the value is immediately replaced with "from live view".

### Expected behavior

The [docs for `Phoenix.LiveView.assign_new/3`](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#assign_new/3) say:

> On connected mount, assign_new/3 will be invoked, and the LiveView will use its session to rebuild the originally shared assign.

I would expect `my_value` to have the original value of "from plug" on both the disconnected mount and on the connected mount.

**Comment by chrismccord** [comment]
The behavior you are seeing is as specified. Note that the docs are saying you can use the minimal session data to rebuild the "original" value, such as fetching current_user form a user_id in the cookie session. If you think the docs could be clear, please send a PR. Thanks!
