### ISSUE TITLE
Commits for 0.14.3 are missing?

### ISSUE THREAD

**Issue by davydog187** [phoenixframework/phoenix_live_view#1096]
https://diff.hex.pm/diff/phoenix_live_view/0.14.2..0.14.3

I can see that 0.14.3 was published, but I'm not seeing the relevant code checked into `master`. At first, I was worried that there was a malicious publish going on. I'm sure it was just a local publish.

It would be helpful to check this code checked in for consumers. Thank you!

**Comment by chrismccord** [comment]
Done. Thanks ❤️❤️❤️🐥🔥

**Comment by seb3s** [comment]
Hi Chris,
It seems that the tag is missing in the github repository. Would be nice to add it as well if it is possible
Cheers
