### ISSUE TITLE
Liveviews receiving old session instead of updated version

### ISSUE THREAD

**Issue by shadowRR** [phoenixframework/phoenix_live_view#1104]
### Environment

* Elixir version (elixir -v): 1.10.2
* Phoenix version (mix deps): 1.5.4
* Phoenix LiveView version (mix deps): 0.14.4
* NodeJS version (node -v): 10.16.2
* NPM version (npm -v): 6.4.1
* Operating system: Windows 10
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox /Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

Using a Plug, i am setting a variable (the current path using `path_info` in Plug.Conn) into the session, using `put_session`, with the relevant part of the plug call here:
```
def call(conn, _opts) do
    path = "/" <> Enum.join(conn.path_info, "/")
    put_session(conn, :path, path)
end
```

This plug is used in a pipeline on the router: 
```
pipeline :mypipeline do
    plug :browser
    plug Nav.SetPathSession
end
```

The `:plug_session` is properly updated and contains the updated value on each call to the router. On first load, the `mount` callback in my LiveView receive the proper data from the 2nd parameter (the session). But on subsequent calls to the router, the updated session (with the new path) isn't provided, instead, my LiveView's are receiving the old session (constantly the first one that was provided on first load).

### Expected behavior

I would expect the provided session to always be up-to-date, has i'm using this data to assign an `active` css class in my navbar. I am missing something in the session behavior ?

**Comment by chrismccord** [comment]
Can you put together a minimal example application that reproduces the issue? Thanks!

**Comment by shadowRR** [comment]
> 
> 
> Can you put together a minimal example application that reproduces the issue? Thanks!

Yep. Here you go:
[Issue Reproduction](https://github.com/shadowRR/phoenix-liveview-session-issue)

The example app contains two LiveViews. Each of them has a link to the other one (`live_redirect`), and each `mount` calls inspects the values in the session parameter. The session `path` parameter is updated using the `setPathSession` plug (in the Plugs folder), which is in turn used on the `:browser` pipeline. When i navigate between the pages, the plug updates the session, but the session received in the `mount` calls always have the parameter received on the first call.

**Comment by josevalim** [comment]
Hi @shadowRR! `live_redirect` completely bypasses the Plug pipeline, it is done within the same websocket connection, so any change done during the plug pipeline will not take effect as it isn't executed. In this case, you would want to use a regular redirect.

**Comment by shadowRR** [comment]
Hello @josevalim! I'm not sure i understand. The regular `redirect` isn't available in LiveViews, since it's expecting a `Plug.Conn` which i don't have. Or am i missing something ?

**Comment by josevalim** [comment]
LV has its own redirect: https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html?#redirect/2

**Comment by shadowRR** [comment]
Oh ! I completely missed that one. Thank you, working perfectly now 😊
