### ISSUE TITLE
LiveView 0.14.0 seems to break forms created by phx.gen.live for umbrella applications

### ISSUE THREAD

**Issue by vinodkumark369** [phoenixframework/phoenix_live_view#1120]
### Environment

* Elixir version (elixir -v): 1.10.4 (compiled with Erlang/OTP 22)
* Phoenix version (mix deps): 1.5.4
* Phoenix LiveView version (mix deps): 0.14.0
* NodeJS version (node -v): 12.8.3
* NPM version (npm -v): 6.14.6
* Operating system: Docker Image elixir:1.10.4 (Host Ubuntu 18.04.5)
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox (79.0), Chromium (84.0.4147.105)
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior
After upgrading to LiveView from 0.13.3 to 0.14.0 (or above), the modal form generated using phx.gen.live does not work. When clicking the "New" button nothing happens and the log contains the following error:

> [error] GenServer #PID<0.565.0> terminating
>  (Protocol.UndefinedError) protocol Phoenix.HTML.Safe not implemented for %Phoenix.LiveComponent.CID{cid: 2} of type Phoenix.LiveComponent.CID (a struct). 
> 
> This protocol is implemented for the following type(s): Decimal, Phoenix.LiveView.Comprehension, Phoenix.LiveView.Rendered, Phoenix.LiveView.Component, DateTime, List, Phoenix.HTML.Form, Time, Integer, Atom, NaiveDateTime, BitString, Float, Tuple, Date

    (phoenix_html 2.14.2) lib/phoenix_html/safe.ex:1: Phoenix.HTML.Safe.impl_for!/1
    (phoenix_html 2.14.2) lib/phoenix_html/safe.ex:15: Phoenix.HTML.Safe.to_iodata/1
    (phoenix_html 2.14.2) lib/phoenix_html/tag.ex:98: anonymous fn/2 in Phoenix.HTML.Tag.tag_attrs/1
    (elixir 1.10.4) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix_html 2.14.2) lib/phoenix_html/tag.ex:96: Phoenix.HTML.Tag.tag_attrs/1
    (phoenix_html 2.14.2) lib/phoenix_html/tag.ex:52: Phoenix.HTML.Tag.tag/2
    (phoenix_html 2.14.2) lib/phoenix_html/tag.ex:217: Phoenix.HTML.Tag.form_tag/2
    (phoenix_html 2.14.2) lib/phoenix_html/form.ex:263: Phoenix.HTML.Safe.Phoenix.HTML.Form.to_iodata/1
    (live_demo_web 0.1.0) lib/live_demo_web/live/person_live/form_component.html.leex:3: anonymous fn/2 in LiveDemoWeb.PersonLive.FormComponent.render/1
    (phoenix_live_view 0.14.0) lib/phoenix_live_view/diff.ex:307: Phoenix.LiveView.Diff.traverse/6
    (phoenix_live_view 0.14.0) lib/phoenix_live_view/diff.ex:532: Phoenix.LiveView.Diff.render_component/9
    (phoenix_live_view 0.14.0) lib/phoenix_live_view/diff.ex:478: anonymous fn/5 in Phoenix.LiveView.Diff.render_pending_components/6
    (elixir 1.10.4) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    (stdlib 3.12.1) maps.erl:232: :maps.fold_1/3
    (phoenix_live_view 0.14.0) lib/phoenix_live_view/diff.ex:453: Phoenix.LiveView.Diff.render_pending_components/6
    (phoenix_live_view 0.14.0) lib/phoenix_live_view/diff.ex:117: Phoenix.LiveView.Diff.render/3
    (phoenix_live_view 0.14.0) lib/phoenix_live_view/channel.ex:553: Phoenix.LiveView.Channel.render_diff/2
    (phoenix_live_view 0.14.0) lib/phoenix_live_view/channel.ex:428: Phoenix.LiveView.Channel.handle_changed/4
    (stdlib 3.12.1) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib 3.12.1) gen_server.erl:711: :gen_server.handle_msg/6

### Expected behavior
A modal form should be shown when the button is clicked.

### How to reproduce?

 `mix phx.new live_demo --umbrella --live`
 `mix ecto.create`
 `mix deps.unlock phoenix_html phoenix_live_view phoenix_live_dashboard`
  Update phoenix_live_view version to `"== 0.14.0"` or `"~>0.14"`
 `mix deps.get`
 `mix deps.compile`
  `rm -rf node_modules`
 `npm install`
 `mix phx.gen.live Persons Person persons name`
 `mix ecto.migrate`
 `mix phx.server`

Goto `localhost:4000/persons`
Press button `New Person`
Nothing happens and error is logged in server console.
Goto `localhost:4000/persons/new`
Error is displayed in browser.

`mix deps.unlock phoenix_html phoenix_live_view phoenix_live_dashboard`
Update phoenix_live_view version to `"~> 0.13.3"`
`mix deps.get`
`mix deps.compile`
`rm -rf node_modules`
`npm install`
`mix phx.server`
**Everything works as expected.**

The issue is not present for normal phoenix application (mix phx.new <app_name> --live).

**Comment by josevalim** [comment]
Just to be sure, can you delete the `_build` directory after you upgrade to v0.14.4 and see if it fixes it? The protocol is definitely there, it just seems it is not being picked up. In any case, this does reveal a bug in Elixir, so I will investigate, thanks!

**Comment by vinodkumark369** [comment]
Yes I tried it, and after deleting _build folder it is picking up the protocol. Thanks for pointing out.
But I was wondering why this behaviour is specific to umbrella application only.

**Comment by josevalim** [comment]
It shouldn't happen, definitely a bug. Quick question: where are you running `mix phx.server` from? the umbrella root? or the `_web` app?

**Comment by vinodkumark369** [comment]
From umbrella root.

**Comment by josevalim** [comment]
I have a fix for Elixir that will be included in the next version. Thanks for the report!
