### ISSUE TITLE
no function clause matching in Phoenix.LiveView.Diff.to_iodata/3

### ISSUE THREAD

**Issue by 50kudos** [phoenixframework/phoenix_live_view#1125]
### Environment

* Elixir version (elixir -v): 1.10.3
* Phoenix version (mix deps): 1.5.3
* Phoenix LiveView version (mix deps): a6a7e7718df54dc2c71ef90081f360a018d1d9be (latest master at time this issue written)
* NodeJS version (node -v): 13.7.0
* NPM version (npm -v): 6.14.5
* Operating system: MacOS 10.14.6 
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox 79.0b7 (64-bit)
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior
There exists possible corrupt state when live component does recursive call to itself, where there is only dynamic without static part.

![Screen Shot 2020-08-21 at 7 35 28 AM](https://user-images.githubusercontent.com/2753398/90839998-60d5db80-e348-11ea-9ebc-33a230fe91d9.png)

### Expected behavior
Calling live component recursively should always produce stuff that match `to_iodata/3`.

---
Note: I can't make a mimic example of real code, but the log above is its simplest data produced by real code. If it's still hard to identify problem, I'll try to make a generic form of it. (I know it's painful!)

**Comment by josevalim** [comment]
Hi @50kudos, I was not able to reproduce this locally. Can you please provide a single file or an app that shows the issue you are running into? Thank you.
