### ISSUE TITLE
<%= render ... %> cause page to hang and server to be killed

### ISSUE THREAD

**Issue by tcoopman** [phoenixframework/phoenix_live_view#1130]
### Environment

* Elixir version (elixir -v): Elixir 1.10.4 (compiled with Erlang/OTP 23)
* Phoenix version (mix deps): 1.5.4
* Phoenix LiveView version (mix deps): 0.13.3
* Operating system: linux

### Actual behavior

Create a new project with:

```bash
mix phx.new foo --live --no-ecto --app foo
```

run `mix phx.server` and go to `http://localhost:4000`

now open a editor and edit: `lib/foo_web/live/page_live.html.leex` and add to the top of the file: `<%= render "bla.html" %>`.

You get the error `no case clause matching: "bla.html"`in `Phoenix.LiveView.Engine.fetch_assign!/2`
(I'm not sure if this the expected behavior, but this is not the bug)

When you now change the `page_live.html.leex` and remove everything but `<%= render "bla.html" %>`. So this is the `page_live.html.leex` file:

```elixir
`<%= render "bla.html" %>`
```

When you surf to the page, the page will not load, the beam will use a huge amount off cpu and ram and on my OS gets killed after a short while: `“mix phx.server” terminated by signal SIGKILL (Forced quit)`

### Expected behavior

I would expect this not to hang, but show a meaningful error.

### Other remarks

Using `<%= render "bla.html" %>` in `lib/foo_web/templates/layout/root.html.leex` results in a more sensible error:

```
Could not render "bla.html" for FooWeb.LayoutView, please define a matching clause for render/2 or define a template at "lib/foo_web/templates/layout/*". The following templates were compiled:
...
```

and it's not possible to trigger the bug in these templates.

**Comment by josevalim** [comment]
You are calling the LiveView `render` function recursively, which is why you get an infinity loop. We can remove the infinity loop in this case in favor of an exception, *but* the code won't ever work. :)

**Comment by tcoopman** [comment]
Ok, reading https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#module-colocating-templates it's clear why it's an infinite loop.

Sorry for the noise

**Comment by josevalim** [comment]
No noise, i think this can be a common pitfall, so removing the infinity loop will certainly help!
