### ISSUE TITLE
input_value returning an inconsistent type and is not rendering / removing

### ISSUE THREAD

**Issue by daveli** [phoenixframework/phoenix_live_view#1132]
### Environment

* Elixir version (elixir -v): 1.10.4
* Phoenix version (mix deps): 1.5.4
* Phoenix LiveView version (mix deps): 0.14.4
* NodeJS version (node -v): 12.16.1
* NPM version (npm -v): 6.14.4
* Operating system: MacOS
* Browsers you attempted to reproduce this bug on (the more the merrier):  Firefox, Chrome and Microsoft Edge (Chromium) 
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

👋 I'm currently running into some issue with [input_value](https://hexdocs.pm/phoenix_html/Phoenix.HTML.Form.html#input_value/2). It seems to be returning an inconsistent type when dealing with a boolean and based on that not render / remove.

Model:
```
schema "foo" do
  field(:bar, :boolean, default: false)
end
```

Template:
```
<%= checkbox f, :is_recurring %>
<%= if input_value(f, :bar) do %>
  # Do something.
<% end %>
```

On initial render the value seems to be a boolean (read: the default value), but when sending the unchecked value it changes to a binary, this makes sense as it then sends the binary value "false" as described [here](https://hexdocs.pm/phoenix_html/Phoenix.HTML.Form.html#checkbox/3-options). This is however "confusing" when you want to use input_value to conditionally render a part of the template in Phoenix Live View. Since the value changes to a binary the check in the template won't work any more.

To add to the "confusion" when the default value starts as `true` it does work toggling the checkbox and the template is beeing added / removed.

**Comment by josevalim** [comment]
This is correct behavior. input_value is going to look at parameters and return them if any, so there is no guarantee you will receive the original data value. Instead of using inpit_value, you should look at the processed value in the changeset. We can improve the docs here though.

**Comment by daveli** [comment]
Coolio! I will use a something based on `Ecto.Changeset.get_field` to conditionally render.
