### ISSUE TITLE
Button value not passed to LiveView event when submitting form

### ISSUE THREAD

**Issue by robinvdvleuten** [phoenixframework/phoenix_live_view#1133]
### Environment

* Elixir version (elixir -v):

```
Erlang/OTP 23 [erts-11.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.10.3 (compiled with Erlang/OTP 22)
```

* Phoenix version (mix deps): 1.5.4
* Phoenix LiveView version (mix deps): 0.14.4
* NodeJS version (node -v): 12.13.0
* NPM version (npm -v): 6.14.8
* Operating system: macOS
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

When I have a form like the following with multiple submit buttons (in my app it's more complex than this, simplified it for understanding my issue).

```eex
<%= f = form_for @changeset, Routes.form_path(@socket, :update), [phx_submit: :submit] %>
  <button name="action" type="submit" value="add">Add</button>
  <button name="action" type="submit" value="remove">Remove</button>
  <button type="submit">Save</button>
</form>
```

Whenever I press one of the "action" buttons, I never get the action value passed to the event handler in LiveView. With a normal HTTP form and Phoenix, this works as expected.

### Expected behavior

I expect the correct action value to be passed to my event handler in LiveView. 

Why did I ran into this issue? I have a form where an user can add and remove groups of input elements. But when I remove or add a group through `phx-click`, the other groups input values get cleared. So I figured that if I use submit buttons with an action value, I also have the form state so upon rerendering, the changeset contains all the correct values to recreate the input elements.

**Comment by josevalim** [comment]
Unfortunately there is no way in JavaScript to access which button was submitted. The information is simply not available. See #511 and #184.

**Comment by Jayshua** [comment]
@josevalim I did a quick step-through on the Live View code and it looks like you're listening to the submit event which has some info about the [button that was clicked](https://developer.mozilla.org/en-US/docs/Web/API/SubmitEvent/submitter).

I haven't tested this code at all, but do you think something similar to [these changes might work](https://github.com/Jayshua/phoenix_live_view/commit/ff23d303757b1bc37db09256b4f71f56801c3a0e)?

**Comment by mcrumm** [comment]
The `submitter` property does not appear to have wide support: https://developer.mozilla.org/en-US/docs/Web/API/SubmitEvent/submitter#browser_compatibility

**Comment by Jayshua** [comment]
I keep running into this issue so I want to leave a possible solution here for anyone who finds it in the future.

This code detects clicks on the form submit button and insert a hidden input element with the same name & value of the submit button. The value of the hidden input is included in the submitted form data.

```js
document.addEventListener("click", event => {
	if (event.target.matches("form[phx-submit] button[type=submit][name]")) {
		let hiddenInput = document.createElement("input");
		hiddenInput.type = "hidden";
		hiddenInput.name = event.target.name;
		hiddenInput.value = event.target.value;
		event.target.closest("form").appendChild(hiddenInput);
	}
});
```

**Comment by osahady** [comment]
you can use phx-hook on a form 

`
<script>
  let Hooks = {}
  Hooks.MultiSubmitForm = {
      mounted() {
          this.el.addEventListener("submit", (event) => {
              let phxEvent = event.submitter.getAttribute("phx-submit");
              event.target.setAttribute("phx-submit", phxEvent);
          }, true);
      }
  }
</script>

<.simple_form :let={f} for={:som_name} id="some_id" phx-hook="MultiSubmitForm">
  <.button phx-submit="action1">save </.button>
  <.button phx-submit="action2">remove</.button>
</.simple_form>
`
and then in liveview you handle_event for action1 and action2

`
def handle_event("action1", _params, socket), do: {:noreply, socket}

def handle_event("action2", _params, socket), do: {:noreply, socket}
`
