### ISSUE TITLE
provide auto formatting for JavaScript files

### ISSUE THREAD

**Issue by breunigs** [phoenixframework/phoenix_live_view#1138]
Like with Elixir, it would be convenient to use a JS autoformatter. At least with Visual Studio Code, the default JS settings do not match live view's coding style. Additionally, there appear to be multiple JS formatters with incompatible configuration options. Looking at the already used node modules, it seems that `webpack-cli` pulls in `prettier` which sounds promising, but I have no idea how to activate it.

Any auto-format would be terrific already. Editor integration is something I can solve on my own, as long as there's some agreement on project level what formatter should be used, the styles, or if it's intentional to not use one.

**Comment by josevalim** [comment]
Hi @breunigs, we understand the importance of auto formatting, that's why we have added one for Elixir, so we will discuss internally and hopefully migrate to one that we like. Given this is not really a bug in the project though, we will close this issue. Thanks!
