### ISSUE TITLE
a textarea's value is being replaced on phx-change while having focus, but a text input is not

### ISSUE THREAD

**Issue by thojanssens** [phoenixframework/phoenix_live_view#1139]
### Environment

* Elixir version (elixir -v):
> Erlang/OTP 22 [erts-10.7] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1]
> Elixir 1.10.2 (compiled with Erlang/OTP 21)
* Phoenix version (mix deps):
> 1.5.4
* Phoenix LiveView version (mix deps):
> 0.14.4
* NodeJS version (node -v):
> v12.16.1
* NPM version (npm -v):
> 6.14.2
* Operating system:
> Windows 10
* Browsers you attempted to reproduce this bug on (the more the merrier): 
> Chrome 85
> Firefox 80
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:
> Yes

### Actual behavior

I cannot replace a text input when it has focus on `phx-change`, as expected, but apparently a textarea's value is being replaced while it has focus.

From the doc it says:
> For any given input with focus, LiveView will never overwrite the input's current value, even if it deviates from the server's rendered updates.

For me a textarea is also a form of input.

```
defmodule MyApp.PageLive do
  use MyApp, :live_view

  def mount(_params, _session, socket) do
    {:ok, assign(socket, query: "")}
  end

  def render(assigns) do
    ~L"""
    <section class="phx-hero">
      <form phx-change="suggest">
        This is the value of @query: "<%= @query %>"<br>
        <textarea name="q"><%= @query %></textarea>
      </form>
    </section>
    """
  end

  def handle_event("suggest", %{"q" => query}, socket) do
    {:noreply, assign(socket, query: Integer.to_string(Enum.random(1..100)))}
  end
end
```

In the example code above, whenever I type a letter in the textarea, it is being replaced by a random number. If I replace the textarea by a text input, the value won't change.

### Expected behavior

Text input and text area behave the same way.

**Comment by josevalim** [comment]
Can you please fill in all of the information that we request when opening an issue? Thank you.

**Comment by thojanssens** [comment]
I edited the issue including all the information requested.

**Comment by josevalim** [comment]
Beautiful, I can reproduce it too! :+1:
