### ISSUE TITLE
click handler called twice with Alpine.js

### ISSUE THREAD

**Issue by dvic** [phoenixframework/phoenix_live_view#1140]
### Environment

* Elixir version (elixir -v):

```
Erlang/OTP 22 [erts-10.7] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.10.4 (compiled with Erlang/OTP 22)
```

* Phoenix version (mix deps): 1.5.4
* Phoenix LiveView version (mix deps): 0.14.4
* NodeJS version (node -v): v12.18.1
* NPM version (npm -v): 6.14.6
* Operating system: macOS Catalina 10.15.6
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, Firefox, Safari
* Does the problem persist after removing "assets/node_modules" and trying again? yes

### Actual behavior

**Sample app that demonstrates the problem** https://github.com/dvic/liveview_alpine_playground/tree/alpinejs-click-twice

Not sure if this is working as intended or it's a bug in LiveView, AlpineJS, or both, but with a LiveView controlled `ul`, the handlers for the AlpineJS `@click` handlers are called twice if they have a parent scope.

```elixir
  @impl true
  def mount(_params, _session, socket) do
    if connected?(socket) do
      Process.send_after(self(), :add, 1000)
    end

    {:ok, assign(socket, items: [])}
  end

  @impl true
  def handle_info(:add, socket) do
    {:noreply, socket |> assign(items: [DateTime.utc_now() | socket.assigns.items])}
  end

  @impl true
  def render(assigns) do
    ~L"""
      <div x-data>
        <ul>
          <li id="fixed_item" @click="item_clicked($event)">
            <div><span>the fixed item</span></div>
          </li>
          <%= for {_, idx} <- @items |> Enum.with_index() do %>
          <li id="item_<%= idx %>" @click="item_clicked($event)">
            <div><span>alpinejs on click li (this one calls the handler twice)</span></div>
          </li>
          <li x-data id="item_<%= idx %>_scope" @click="item_clicked($event)">
            <div><span>alpinejs on click li with x-data on li</span></div>
          </li>
          <li id="item_<%= idx %>_native" onClick="item_clicked(event)">
            <div><span>native on click li</span></div>
          </li>
          <% end %>
        </ul>
      </div>
    """
  end
```

In this example, as you can see in the above code, items 2, 3, and 4 appear after 1 second. 
![image](https://user-images.githubusercontent.com/1214337/92603270-653e4600-f2af-11ea-898a-701a6acfbe10.png)

Here is what the console looks like if I click all items in order:

![image](https://user-images.githubusercontent.com/1214337/92603469-a33b6a00-f2af-11ea-8b76-80ea0bd87bc9.png)

As you can see, the item `alpinejs on click li (this one calls the handler twice)` is called twice. The weird thing is that a AlpineJS `@click` with a `x-data` scope on it and native `onClick` (item 4) do work properly.

### Expected behavior
The AlpineJS click handler should be called once instead of two times per click.

**Comment by dvic** [comment]
Forgot to mention, the JS setup is as follows:

![image](https://user-images.githubusercontent.com/1214337/92604283-a1be7180-f2b0-11ea-8630-4c9962bd7976.png)

**Comment by chrismccord** [comment]
This seems to be strictly an Alpine issue since we only register our click listeners top-level on window. You might want to start on that side and see if you can isolate with the provided markup without LV. Also, since you are prepending the items, using the index to build the DOM id will cause `li`'s to be swapped as they go, which may be your issue. Try using an ID based on the item itself. Thanks!

**Comment by dvic** [comment]
Alright, I'll take it to Alpine.js and see if I can find out more. One LV related question though, I added some logging to the `onBeforeElUpdated` calllback, it shows the following:

![image](https://user-images.githubusercontent.com/1214337/92613596-6c6b5100-f2bb-11ea-9b3a-93fc28511491.png)

Is it correct that the callback is called twice? The first time the elements are not the *same* but they are *equal*.

The callback is defined as

![image](https://user-images.githubusercontent.com/1214337/92613748-9886d200-f2bb-11ea-9a6e-7f554a1a50c1.png)

**Comment by dvic** [comment]
@chrismccord I tried the unique ID based approach, it does not fix the problem. I also created an isolated JS-only approach (click on a button that replaces a ul with a new list). With this approach, Alpine.JS is working just fine. The only thing I don't understand: I don't have to call Alpine.clone for it to work. Why do we have to call this in the first place with LV? This code is available on the same branch.

Because of the behaviour above I thought I might have found it if the `Alpine.clone` was buggy somehow (the `onBeforeElUpdated` being called twice) but this is also not the issue.

Will be looking more into this, thanks anyways for the prompt response 🙂

**Comment by dvic** [comment]
**An update** the issue is definitely within `Alpine.clone`, because if I remove it, the problem disappears, the click handlers keep working. But then I'm wondering, why is this call even needed? Or is it just coincidence that it works for this example code?

**Comment by dvic** [comment]
**another update** for people landing on this issue: the problem also exists with [Livewire](https://laravel-livewire.com/), it's a confirmed bug probably between Alpine and Morphdom (which both Phoenix LiveView and Livewire use)

**Comment by dvic** [comment]
I can confirm that Alpine v2.8.1 solves this issue (see https://github.com/alpinejs/alpine/pull/1058/files)

**Comment by MeterSoft** [comment]
steel have issue in v2.8.2

this code call once
```
<div class="relative h-full mr-2 lg:mr-5"
     x-data="{ notificationsDropdown: false }"
     x-on:click="notificationsDropdown = true; $dispatch('notificationsOpened', {}); console.log(44444)"
>

    <%# ----- notification bell ---- %>
    <div role="button"
         id="notifications_button"
         class="relative h-full px-2 flex items-center justify-center"
         title="Notifications"
         aria-haspopup="listbox"
         aria-expanded="false"
         aria-labelledby="notifications_list_new notifications_list_earlier notifications_button"
    >
```
but when move click more down it stop works.

```
<div class="relative h-full mr-2 lg:mr-5"
     x-data="{ notificationsDropdown: false }"
>

    <%# ----- notification bell ---- %>
    <div role="button"
         id="notifications_button"
         class="relative h-full px-2 flex items-center justify-center"
         title="Notifications"
         aria-haspopup="listbox"
         aria-expanded="false"
         aria-labelledby="notifications_list_new notifications_list_earlier notifications_button"
         x-on:click="notificationsDropdown = true; $dispatch('notificationsOpened', {}); console.log(44444)"
    >
```

**Comment by f-liva** [comment]
Same here, I get click events called twice

**Comment by smappio** [comment]
I also have the issue with Alpine v3.10.2 but only with Safari, I didn't reproduced using Chrome, Edge.

**Comment by dvic** [comment]
I just bumped the deps on my [reproduction repo](https://github.com/dvic/liveview_alpine_playground/tree/alpinejs-click-twice) (alpine 3.10.2 and liveview 0.17.11) and I can't reproduce it anymore, so for this usecase it seems solved.
