### ISSUE TITLE
"Cannot convert component" with comprehensions

### ISSUE THREAD

**Issue by mikepc** [phoenixframework/phoenix_live_view#1142]
https://github.com/phoenixframework/phoenix_live_view/issues/505

This issue was closed as "Working as intended" but that is absolutely no help to the uninitiated. The error states explicitly:

> Components are also allowed inside Elixir's special forms, such as
> `if`, `for`, `case`, and friends.
> 
```elixir
          <%= if assigns[:current_user] do  %>
              <%= live_component(@socket, DemoWeb.Account.Avatar) %>
          <% end %>
```

I understand this is not supported, but surely there is a more robust explanation that can give some guidance as to how to accomplish the intended outcome.

**Comment by josevalim** [comment]
It was not closed because it was worked as intended. It was closed because we fixed the issue, which you could see in the linked commit.

If you are still running into issues, then please do a proper bug report fill in all of the information in the template and we can take a look at it.
