### ISSUE TITLE
render_submit test helper not working for hidden field

### ISSUE THREAD

**Issue by dvic** [phoenixframework/phoenix_live_view#1145]
### Environment

* Elixir version (elixir -v): Elixir 1.10.4 (compiled with Erlang/OTP 23)
* Phoenix version (mix deps): 1.5.4
* Phoenix LiveView version (mix deps): 0.14.4
* NodeJS version (node -v):v12.18.3
* NPM version (npm -v): 6.14.6
* Operating system: MacOS
* Browsers you attempted to reproduce this bug on (the more the merrier): n/a
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

I'm trying to use `render_submit` with a hidden field, as explained in #988 and it's posting an empty value for the hidden field. 

**Example repo**: https://github.com/dvic/lv-forms-helper-bug

Result (I added the logger warn message):
![image](https://user-images.githubusercontent.com/1214337/93396879-b71b3900-f878-11ea-9ef6-35d30e80c931.png)

### Expected behavior
The parameter `name` should have been set to *some name* in the above example.

Am I missing something here or is this a bug?

**Comment by josevalim** [comment]
When you inspect the hidden field in the browser, does it have a value?

**Comment by josevalim** [comment]
Btw, here is an example that shows hidden input being submitted: https://github.com/phoenixframework/phoenix_live_view/blob/master/test/phoenix_live_view/integrations/elements_test.exs#L427 with template: https://github.com/phoenixframework/phoenix_live_view/blob/master/test/support/live_views/elements.ex#L59

So is perhaps something else at play here.

**Comment by dvic** [comment]
🤦‍♂️ never mind, I found it. I was doing: 

```elixir
      {:ok, _, html} =
        index_live
        |> form("#project-form", project: %{category_id: 42})
        |> render_submit(%{name: "some name"})
        |> follow_redirect(conn, Routes.project_index_path(conn, :index))
```

but it should be of course `render_submit(project: %{name: "some name"})`!

I took the comment 
https://github.com/phoenixframework/phoenix_live_view/issues/988#issuecomment-646586166 and the resulting docs https://github.com/phoenixframework/phoenix_live_view/pull/993/files#diff-44465e9bafa682561dd804d3bfad5abfR475-R481 a bit too literal 🙂 (both examples directly set `hidden_value`).

I will prepare a PR to update that part of the doc because it's not correct currently:
```elixir
assert view
      |> form("#term", user: %{name: "hello"})
      |> render_submit(%{"hidden_value" => "example"}) =~ "Name updated"
```

should be

```elixir
assert view
      |> form("#term", user: %{name: "hello"})
      |> render_submit(%{user: %{"hidden_value" => "example"}}) =~ "Name updated"
```
