### ISSUE TITLE
Towards better for comprehension support for change tracking and diffs

### ISSUE THREAD

**Issue by ssboisen** [phoenixframework/phoenix_live_view#1150]
So I've been working with Phoenix Live View and like it a lot, great work and thank you!

However I've encountered some surprising behavior around for comprehensions and the diff send from the server to the client. Having looked through the issue tracker I see that these are known limitations. My question is if it's on the horizon to improve for comprehensions support?

The current limitations which I've encountered and how I see them possibly solved (obviously there are probably challenges to actual implementation that I don't realize):

 *If I misunderstood something and the information I present is wrong, I'm sorry!*

### Changes to properties of maps inside lists are not tracked sufficiently
**Description**: With an assign x which is a list of maps with properties y and z when you have a template with a for comprehension over x and use the y property inside the for comprehension template - if the z property changes, but the y does not, the diff with y property is send to the client even though it did not change. 

**The problem here is**: it is not tracked exactly which properties of a map inside a for comprehension is used and the algorithm is thus unable to ignore changes to properties not used in the for comprehension.

**Current workaround**: Currently a work around is to have an additional assign which is used in the template and which only contain properties which are used inside the for comprehension. This is somewhat bothersome to maintain, but it does solve the problem.

**Solution**: Store as part of the change tracking which properties are actually used inside the for comprehension, and use this information when checking for changes to the list.

### Changes to lists are no expressed as individual elements
**Description**: With an assign **x** which is a list that is used in a for comprehension, if an element is added, removed or changed in **x** the whole list is send to the client instead of only the part that changed.

**The problem here is**: The algorithm is unable to express in the diff that an element should be inserted, updated or removed from the dom.

**Current workaround**: A partial work around to this already exists by using the `phx-update` feature however it relies of usage of `temporary_assigns` which complicates matters and which exists for another use case: large sets of data. It's also only partial as `phx-update` currently (from what I understand) is unable to remove. Additionally there's no workaround for only expressing in the diff elements that changed and not those that didn't which means the diff currently includes the full list.

**Solution**: The diff should be able to express changes to elements based on their `id`, the `id` could be chosen based on the id of the top most html tag inside the for comprehension (similarly how `phx-update` require such an html tag id). With this in place the diff should be able to express insert, change and remove, e.g.:

```
[
  ["remove", "id-1"], //element with id-1 was removed
  ["change", "id-2", [ diff expression for the actual template values ]], //element with id-2 changed
  ["insert", ["id-2", "id-4"], [ actual template values ]], //element with id-4 was inserted after id-2
  ["change", "id-3", [ diff expression for the actual template values ]], //element with id-3 changed
]
```

I hope you find this useful even though you probably already know this and have good reasons why this is not how the current implementation is. I would like to understand where the challenges lies with making the necessary changes to accommodate this improved change tracking and diffing. I would like to contribute a PR if you think it's actually a feasible solution.

**Comment by josevalim** [comment]
This is a fantastic write up. You are correct on all counts.

Unfortunately this problem is very hard to solve organically because a list can change in any way and computing which and what part of the list changed is expensive. Therefore, to track it, we would need to give IDs to each individual item in the comprehension. Luckily, this is precisely what LiveComponents are about, so you can get all of the benefits you have asked for by using `live_component` inside the comprehension - as long as you pass an id. :)

**Comment by josevalim** [comment]
Also note that LiveView on the server doesn't know if you are giving something as a DOM ID. For example, if you do `<div id="<%= ... %>">`, it doesn't know you are IDing a div. Doing so would require us to parse incomplete HTML5, which would be a very complex effort by itself.

**Comment by ssboisen** [comment]
Thanks for the quick reply Jose! It makes a lot of sense wrt the DOM ID not being tracked, I had thought about whether if would be necessary to have another way to express a key selection function. I weren't exactly sure how the change tracking and template pipeline looked - if the template compilation information would be available to the change tracking.

Sounds fantastic that live components would solve these problems, looking forward to trying it out!

**Comment by ssboisen** [comment]
Just tried it, works great using live components!

I think the fact that the full sparse list is still included in the diff is a nice trade of between the complexity and computation-overhead of tracking changes in diffs to individual elements like I suggested and the additional payload size that the sparse list brings. Very nice engineering! :)

**Comment by josevalim** [comment]
Fantastic. I will go ahead and close this one then. :) Thank you!
