### ISSUE TITLE
"(FunctionClauseError) no function clause matching in Phoenix.LiveView.Diff.to_iodata/3" - no static or dynamic parts causing crash

### ISSUE THREAD

**Issue by jakeva** [phoenixframework/phoenix_live_view#1152]
### Environment

* Elixir version (elixir -v): 1.10.4
* Phoenix version (mix deps): 1.5.2
* Phoenix LiveView version (mix deps): 0.14.4
* NodeJS version (node -v): 14.11.0
* NPM version (npm -v): 6.14.8
* Operating system: bitwalker/alpine-elixir-phoenix docker image
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

The behavior I'm describing I have not been able to reproduce on my macOS dev environment, only in production which I realize might make this very difficult but I'm willing to try anything. I've cloned master and done some debugging but haven't gotten anywhere.

Viewing a page with recursive `live_component`s results in the following (cleaned up) stack trace:

` 
Request: GET /posts
    ** (FunctionClauseError) no function clause matching in Phoenix.LiveView.Diff.to_iodata/3
    ** (exit) an exception was raised:
        (phoenix_live_view 0.14.4) lib/phoenix_live_view/diff.ex:75: Phoenix.LiveView.Diff.one_to_iodata/6
        (phoenix_live_view 0.14.4) lib/phoenix_live_view/diff.ex:75: Phoenix.LiveView.Diff.one_to_iodata/6
        (phoenix_live_view 0.14.4) lib/phoenix_live_view/diff.ex:39: Phoenix.LiveView.Diff.to_iodata(%{
            0 => "<a data-phx-link=\"patch\" data-phx-link-state=\"push\" href=\"/posts/3/show/edit\">Edit</a>", 
            1 => "<a data-confirm=\"Are you sure?\" href=\"#\" phx-click=\"delete_post\" phx-value-id=\"3\">Delete</a>"
          }, 
          %{
            1 => %{
              0 => %{d: [[%{0 => 2, :s => ["", ""]}], [%{0 => 3, :s => ["", ""]}]], s: ["", ""]}, 
              :s => ["", ""]
            }, 
            2 => %{
              0 => "post-2", 
              1 => %{
                0 => %{
                  0 => "<a href=\"#\" phx-click=\"collapse\" phx-value-id=\"2\">\n     </a>", 
                  :s => ["\n  ", "\n"]
                }, 
                :s => ["", "\n"]
              }, 
              2 => %{
                0 => "Foo bar", 
                :s => ["    <h2 class=\"pure-u-4-5\">\n", "    </h2>\n"]
              }, 
              3 => "Foo bar", 
              4 => 4, 
              :s => ["<div class=\"post-container\" id=", ">\n", "  &nbsp;\n", "  <pre class=\"pure-u-4-5\">\n", "  </pre>\n", "</div>\n"]
            }
        }, #Function<4.10054525/2 in Phoenix.LiveView.Diff.to_iodata/1>)
        (phoenix_live_view 0.14.4) lib/phoenix_live_view/diff.ex:62: Phoenix.LiveView.Diff.to_iodata/3
        (phoenix_live_view 0.14.4) lib/phoenix_live_view/diff.ex:62: Phoenix.LiveView.Diff.to_iodata/3
        (phoenix_live_view 0.14.4) lib/phoenix_live_view/diff.ex:75: Phoenix.LiveView.Diff.one_to_iodata/6
        (phoenix_live_view 0.14.4) lib/phoenix_live_view/diff.ex:80: Phoenix.LiveView.Diff.many_to_iodata/5
        (phoenix_live_view 0.14.4) lib/phoenix_live_view/diff.ex:75: Phoenix.LiveView.Diff.one_to_iodata/6
`

Trying to clean up the formatting, the first argument to `to_iodata` is 

`
%{
            0 => "<a data-phx-link=\"patch\" data-phx-link-state=\"push\" href=\"/posts/3/show/edit\">Edit</a>", 
            1 => "<a data-confirm=\"Are you sure?\" href=\"#\" phx-click=\"delete_post\" phx-value-id=\"3\">Delete</a>"
          }
` which has no `:s` or `:d` keys, which seems to be the problem.

The issue goes away if a conditional or a recursive component call is removed. 

The templating code is the `PostLive.Post` that triggers this unfortunate result looks like this (I've tried to focus the code that seems to cause the issue):

`
      ...

    ## If this if check is removed, the issue disappears
    <%= if @post.creator_id == @current_user.id do %>
        <small><%= live_patch "Edit", to: Routes.post_show_path(@socket, :edit, @post) %></small>
        &nbsp;
        <small><%= link "Delete", to: "#", phx_click: "delete_post", phx_value_id: @post.id, data: [confirm: "Are you sure?"] %> 
        </small>
        &nbsp;
    <% end %>
    </div>
    <%= if Post.has_children?(@post) do%>
      &nbsp;
      &nbsp;
       <%= if not @collapse do %>
          <%= for child_post <- @children do %>
             <%= if MyAppWeb.PostLive.Post.should_render?(child_post) do %>
                <div class="child-post">
                   <%= live_component(
                       @socket,
                       MyAppWeb.PostLive.Post,
                           id: "post_#{child_post.id}",
                          post: child_post,
                          current_user: @current_user,
                          reply_to: @reply_to,
                          collapse: @collapse
                       )
                  %>
               </div>
             <% end %>
           <% end %>
         <% end %>
       <% end %>
`

The live component at the end is a recursive call to render the same component, as there should be nested instances of this component. In addition to removing the check higher up, if this recursive call is removed the error goes away. It seems like there is some way to trigger a conflict in child components regarding the

`
    <%= if @post.creator_id == @current_user.id do %>
        <small><%= live_patch "Edit", to: Routes.post_show_path(@socket, :edit, @post) %></small>
        &nbsp;
        <small><%= link "Delete", to: "#", phx_click: "delete_post", phx_value_id: @post.id, data: [confirm: "Are you sure?"] %> 
        </small>
        &nbsp;
    <% end %>
` 

element which results in no static or dynamic parts, resulting in a `no function clause` exception for `to_io_data`

### Expected behavior

It should render without error.

**Comment by josevalim** [comment]
We would definitely need a minimal case to reproduce and fix this but note that we have fixed a bug for recursive components on master, soon to be 0.14.5, so it may be you are running into the same issue.

**Comment by jakeva** [comment]
Applying the use case provided there to my code, I can confirm it is the same bug and it does appear to be fixed on master. Looking forward to the next release, thanks!
