### ISSUE TITLE
Search Hex Packages doesn't work in newly created Phoenix app with --live enabled.

### ISSUE THREAD

**Issue by alaadahmed** [phoenixframework/phoenix_live_view#1154]
### Environment

* Elixir version (elixir -v): __1.10.4__
* Phoenix version (mix deps): __1.5.5__
* Phoenix LiveView version (mix deps): __0.14.6__
* NodeJS version (node -v): __14.11.0__
* NPM version (npm -v): __6.14.8__
* Operating system: __macOS 10.15.6__
* Browsers you attempted to reproduce this bug on (the more the merrier): __Chrome 85.0.4183.102__ & __Firefox 80.0.1__
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: __Yes__

### Actual behavior

Just created new phoenix app with `--live`, started server with `mix phx.server` and in the search field, I search for any dep that included in the application and __GenServer__ terminates, I restarted `phx.server` many times and sometimes it show loading status like forever until I close the tab in the browser and open new one. In new one the issue still exist, GenServer terminates when I click search for any package included in the app.
```


[error] GenServer #PID<0.575.0> terminating
** (CaseClauseError) no case clause matching: {:redirect, %{external: "https://hexdocs.pm/phoenix_live_view/0.14.6"}}
    (phoenix_live_view 0.14.6) lib/phoenix_live_view/channel.ex:460: Phoenix.LiveView.Channel.handle_redirect/5
    (stdlib 3.13.1) gen_server.erl:680: :gen_server.try_dispatch/4
    (stdlib 3.13.1) gen_server.erl:756: :gen_server.handle_msg/6
    (stdlib 3.13.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: %Phoenix.Socket.Message{event: "event", join_ref: "4", payload: %{"event" => "search", "type" => "form", "value" => "q=phoenix_live_view"}, ref: "9", topic: "lv:phx-FjbxLZHI5vjiXAFB"}
State: %{components: {%{}, %{}, 1}, join_ref: "4", serializer: Phoenix.Socket.V2.JSONSerializer, socket: #Phoenix.LiveView.Socket<assigns: %{flash: %{}, live_action: :index, live_module: FreshLiveWeb.PageLive, query: "phoenix_live_view", results: %{"phoenix_live_view" => '0.14.6'}}, changed: %{}, endpoint: FreshLiveWeb.Endpoint, id: "phx-FjbxLZHI5vjiXAFB", parent_pid: nil, root_pid: #PID<0.575.0>, router: FreshLiveWeb.Router, view: FreshLiveWeb.PageLive, ...>, topic: "lv:phx-FjbxLZHI5vjiXAFB", transport_pid: #PID<0.569.0>}
```

### Expected behavior
When I search for any dep in the search field and click Search button it should take me to dep's documentation on hexdocs.pm

**Comment by josevalim** [comment]
Thanks for the report. Closing in favor of the PR in #1153 !
