### ISSUE TITLE
assign_new/2?

### ISSUE THREAD

**Issue by anamba** [phoenixframework/phoenix_live_view#1158]
Would it be possible to get an `assign_new/2` (map/keyword list version)?

I have a case where I'm doing paging, so I set two assigns that are related to each other (a list of objects, plus a flag indicating whether there are more available to be fetched) and in order to make it work with `assign_new/3`, I had to assign a tuple. Then, to avoid creating variables in the template, I had to use `elem/1`.

Edit: After posting, I realized why this doesn't make sense, but let me think about it a little bit more and see if there's a simple alternative.

**Comment by josevalim** [comment]
@anamba there are two possible assign_new:

```elixir
assign_new(socket, foo: fn -> ... end, bar: fn -> ... end)
```

or:

```elixir
assign_new(socket, fn -> [foo: ..., bar: ...] end)
```

The first is just syntax sugar for the current syntax, so not really helpful. We could make it so invoke the functions if any assign changed but I think that can be confusing.

The issue with the second is how would we know when to invoke the function? The keys are returned only when we execute the function, so we can't distinguish it before.

Given that `assign_new` is just a convenience for `if+assign`, I think for more complex cases it is best to roll your own. :) Thanks for pinging though!

**Comment by anamba** [comment]
Thanks for reviewing @josevalim! I am playing with a couple of possible options and will open a PR if I end up really liking one of them. Otherwise, as you said, it is easy enough just to use if+assign.
