### ISSUE TITLE
Test helper doesn't inherit custom host of passed conn

### ISSUE THREAD

**Issue by LostKobrakai** [phoenixframework/phoenix_live_view#1161]
### Environment

* Elixir version (elixir -v): 1.11.0-rc.0
* Phoenix version (mix deps): 1.5.4
* Phoenix LiveView version (mix deps): 0.14.4
* NodeJS version (node -v): v12.16.0
* NPM version (npm -v):
* Operating system: Mac OS X
* Browsers you attempted to reproduce this bug on (the more the merrier): 
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:

### Actual behavior

```elixir
host = "#{subdomain}." <> Endpoint.config(:url)[:host]
conn = Phoenix.ConnTest.build_conn(:get, "http://#{host}/", nil)
conn = get(conn, Routes.app_manage_contacts_index_path(conn, :index, tenant))
{:ok, _view, _html} = live(conn)
```

This fails with `cannot invoke handle_params nor live_redirect/live_patch to "http://connect.localtest.me:4001/testtenant1601296112.0/manage/contacts_live" because it isn't defined in ConnectWeb.Router`. This is actually correct. The url should be `http://app.connect.localtest.me:4001`, but the liveview test helper doesn't use the host of the `conn`, but uses `endpoint.url()`.

### Expected behavior

This should work in tests like it does in dev/prod.

**Comment by josevalim** [comment]
Good catch, a PR is welcome!

**Comment by LostKobrakai** [comment]
I just tried replacing:
https://github.com/phoenixframework/phoenix_live_view/blob/master/lib/phoenix_live_view/test/live_view_test.ex#L285

With `Plug.Conn.request_url(conn)`. This fixes it for me locally, but it breaks all manner of tests for `phoenix_live_view`, which seems to have a bunch of assertions expecting `localhost:4000` instead of `www.example.com`. Should those assertions be changed?

**Comment by josevalim** [comment]
I think so, since the default is `www.example.com`?

**Comment by LostKobrakai** [comment]
I guess the best option would be not even depending on the default and explicitly creating a `conn` with a known host.
