### ISSUE TITLE
Infinity NProgress, when Re-login(gen_auth) on Brave browser.

### ISSUE THREAD

**Issue by Bogdan1001** [phoenixframework/phoenix_live_view#1164]
### Environment

* Elixir version (elixir -v): 1.10.4
* Phoenix version (mix deps): 1.5.4
* Phoenix LiveView version (mix deps): 0.14.4
* NodeJS version (node -v):v12.18.2
* NPM version (npm -v): 6.14.5
* Operating system: MacOS Catalina
* Brave
* Yes

I faced a problem. On two browsers, everything works ok (Firefox and Chrome), but on Brave, I noticed the following behavior I use gen_auth for authentication, the essence of the problem:
1. I register a new user
2. I log out
3. Log in back
4. NProgress infinity loading. There are no warning errors in the console; everything is clean. The app as a whole function correctly; the only visual thing with infinity loading NPrograss and only on the Brave browser.

**Comment by josevalim** [comment]
Can you please provide a sample application that reproduces the error? I just tried Brave on my LV app and gen.auth and it all worked fine. Thanks! :)

**Comment by Bogdan1001** [comment]
Yes of course
https://github.com/Bogdan1001/reproduce_nprogress_issue

my Brave browser version is  V1.14.84

Thank you!

**Comment by Bogdan1001** [comment]
So it is seems to be the issue somewhere in the layouts of controllers. 

I think I did there some mistakes, currently in the app is two layouts registration.html and root.html(app dashboard UI)

So I tried to split controllers UI by layouts with   `plug :put_layout, "root.html" `and `plug :put_layout, "registration.html"`

When I removed all these things and make it as the single layout the issue was disappeared.

Do you know why that behaviour was meat only in Brave browser? And in final how do I need to use layouts to ask gen_auth controllers use a different layouts?

**Comment by josevalim** [comment]
Well, browsers will unfortunately have all sorts of different behaviours. But in LV you have two layouts: the root layout and the live view layout. What can be happening is that you were nesting one layout inside the other. Making the usage consistent seems to solve it, so I recommend looking more closely at your layouts and which one is being used. Check this guide for more information: https://hexdocs.pm/phoenix_live_view/live-layouts.html

**Comment by Bogdan1001** [comment]
So I think I found the actual problem of the issue, in the root.html  I have:

```
<link phx-track-static
        rel="stylesheet"
        href="<%= Routes.static_path(@conn, "/css/app.css") %>" />
```

But my actual file was named as app.scss so Brave will not disconnect from socket and I found that this happens after re-login, if you are login and seat login I did not found that there are some issues.

The problem that an another browsers just load it, and in the console there are no error that the file name is not correct. 

Please if it possible try to reproduce it on your side to I ensure that it was the problem of the issue, a bit crazy day about it maybe I am not right.

**Comment by Bogdan1001** [comment]
Oh no it is not fixed. I really become too crazy. Sorry for the spammy messages.

Here is how socket end in the Brave. What I did to replace it?
1. Delete node_modules and isntall again same with deps build and etc.
2. Replaced root.html to the default(and used the single  root.html for all modules gen_auth and live_view) all another layouts was set to def too.
3. Clear Brave cookies and then re-install it.

![IMAGE 2020-09-29 23:34:48](https://user-images.githubusercontent.com/65122085/94612850-5d6d3280-02ac-11eb-8097-0c57a73237ee.jpg)


![IMAGE 2020-09-29 23:34:29](https://user-images.githubusercontent.com/65122085/94612821-521a0700-02ac-11eb-8015-86dac64a6705.jpg)

**Comment by Bogdan1001** [comment]
@joseva

so I just installed the fresh new Live VIew + gen_auth and after 1-3 retries with log in and log out the issue is happens.
https://github.com/Bogdan1001/reproduce_bug_with_brave here you can try to reproduce

**Comment by Bogdan1001** [comment]
and here is video https://streamable.com/6wg1ap

**Comment by Bogdan1001** [comment]
@josevalim I found at least one person who could re-produce the bug, can we re-open the issue?

**Comment by chrismccord** [comment]
Are there any specific javascript errors? If it's a websocket connection hanging, I don't believe there is anything to do on our side as it sounds like a Brave issue. Does a refresh of the page fix it?
