### ISSUE TITLE
Missing 0.14.7 commit

### ISSUE THREAD

**Issue by seb3s** [phoenixframework/phoenix_live_view#1168]
@chrismccord 
It seems you missed to push the 0.14.7 release commit to the master branch as I can't see it there.
Thanks,
Sébastien.

**Comment by seb3s** [comment]
Hi chris,
ok but then the @version "0.14.6" are wrong in the current master branch no ?

**Comment by chrismccord** [comment]
I don't follow?

**Comment by chrismccord** [comment]
If you'd like to depend on 0.14.7 from git, you can reference the tag. Master has breaking changes for 0.15 and won't be receiving the 0.14.7 patch. If we continue to patch 0.14, we'd make a v0.14 branch, but as this is pre 1.0, we don't plan to maintain such a branch.
