### ISSUE TITLE
Unexpected render behaviour with `push_event`

### ISSUE THREAD

**Issue by JonRowe** [phoenixframework/phoenix_live_view#1172]
Hello!

I encountered some unexpected behaviour, I moved an assign update to `push_event` to avoid re rendering the page every time I want to push some data to a hook, (its a map for what its worth, so theres no markup changed by this data), I expected this would save the render call, as the socket can just push the data down to the hook directly, but instead it seems that render is called, despite no public assigns changing (a cursory glance indicates that push_event may be implemented via private assigns, but I feel that this should not trigger render if theres been no user controlled assigns changing....)

### Environment

* Elixir version (elixir -v): 1.10.0 OTP22
* Phoenix version (mix deps): 1.5.5 
* Phoenix LiveView version (mix deps): 0.14.7
* NodeJS version (node -v): 14.6.0
* NPM version (npm -v): 6.14.7
* Operating system: OS X 10.15.7
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes

### Actual behaviour

A plain `handle_info/2` which calls `push_event` triggers `render/1`. e.g.

```
def handle_info(payload, socket), do: {:noreply, push_event(socket, "fromelixir", payload)}
```

### Expected behaviour

`render/1` is not called, as no assigns have changed

**Comment by chrismccord** [comment]
render will be called and change tracking takes place there. Any result will produce a diff of changes, or an empty diff, so this is working as expected. Thanks!

**Comment by JonRowe** [comment]
Hi @chrismccord thanks for the quick response, but it is entirely not clear why it is necessary to render the html to push an event over the channel to the hook, a minimal fix here would be to put a clear warning this will happen, as I'm now going to have to build in an extra channel and probably leverage pubsub to talk to my hook...

Would you accept a PR making this clear in the docs so in future people such as myself don't get confused and spend time on a solution that can never work? (I was trying to avoid render with this rework)

**Comment by josevalim** [comment]
@chrismccord I think might be a bug with how we are tracking events. We are putting them in the `changed` assigns, even though they are not actually rendered. It may be that our idea of putting private stuff in `changed` is not good after all. Maybe we should add a `private` field and clear stuff ourselves.

Regarding the empty diff, we are sending an empty diff but, because of stateful stuff in the client, I believe we render it anyway?
