### ISSUE TITLE
Slow rendering in Chrome for LiveView with select field

### ISSUE THREAD

**Issue by bjuretic** [phoenixframework/phoenix_live_view#1173]
### Environment
LiveView 0.14.7

### Actual behavior

Creating a simplest possible LiveView template with 
```
<select>
    <%= for {code, name} <- @countries do %>
    <option value="<%= code %>"><%= name %></option>
    <% end %>
</select>
```
... where @countries is the standard list of countries (250ish items), causes huge delay in rendering in Chrome on Linux (around 5 seconds to render any LiveView containing this data). Lowering the number of items in `@countries` lowers the time of rendering as expected.

Accessing the same URL in Firefox works as expected, view is rendered instantly.

Some details about the :
[potential bug](https://elixirforum.com/t/weird-slow-rendering-in-chrome-for-liveview-with-select-field/34740/2)

### Expected behavior

Should render fast, as 250 items in the select is pretty small amount of data.

**Comment by josevalim** [comment]
@bjuretic what happens if you do this:

```
<select>
    <%= Enum.map(@countries, fn {code, name} -> %>
    <option value="<%= code %>"><%= name %></option>
    <% end) %>
</select>
```

Also, can you please provide a single-file LiveView that reproduces the error? That will make it easier for us to reproduce it and track it.

**Comment by bjuretic** [comment]
Hello Jose, nice to meet you. :)

> @bjuretic what happens if you do this:
> 
> ```
> <select>
>     <%= Enum.map(@countries, fn {code, name} -> %>
>     <option value="<%= code %>"><%= name %></option>
>     <% end) %>
> </select>
> ```

If I leave the above inside `<select>` it works slow as before (in Chrome), if I remove `<select>` it renders `<options>` immediately/fast.

> Also, can you please provide a single-file LiveView that reproduces the error? That will make it easier for us to reproduce it and track it.

Here is the requested simplified single-file view to reproduce the issue:

```
defmodule BoardingWeb.TestLive do
  use BoardingWeb, :live_view

  @impl true
  def mount(_params, session, socket) do
    data = for n <- 1..250, do: {n, n}
    {:ok, assign(socket, %{data: data})}
  end

  def render(assigns) do
    ~L"""
    <select>
      <%= for {one, two} <- @data do %>
        <option value="<%= one %>"><%= two %></option>
      <% end %>
    </select>
    """
  end
end
```

**Comment by josevalim** [comment]
Nice meeting you too! 👋 

I have tried to reproduce this issue on a new Phoenix app and I cannot reproduce it on Chrome on macOS (nor in any browser). Looking online, people say this may be caused by typos in CSS rules. See this article for example: https://www.bitcraft.com.au/2014/03/31/select-drop-downs-slow-in-chrome/

So my suggestion is for you to remove all CSS and see if the error persists? If it doesn't, please audit your CSS rules. :)

**Comment by bjuretic** [comment]
You're right, it is a Chrome CSS issue. After removing the CSS it renders instantly. I don't know the problematic CSS style yet (it is not the :active issue from the linked article) but it is CSS for sure, so closing this. Thanks for the help!
