### ISSUE TITLE
onBeforeElUpdated not called on liveview container

### ISSUE THREAD

**Issue by syfgkjasdkn** [phoenixframework/phoenix_live_view#1175]
### Environment

* Elixir version (elixir -v): Elixir 1.10.4
* Phoenix version (mix deps): 1.5.5
* Phoenix LiveView version (mix deps): 0.14.7
* NodeJS version (node -v): v14.13.0
* NPM version (npm -v): 6.14.8
* Operating system: mac
* Browsers you attempted to reproduce this bug on (the more the merrier): chrome, safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

`onBeforeElUpdated` hook is not being called on a liveview `:container` element. I can prepare a repro if needed.

**Comment by josevalim** [comment]
Is the container ever updated? As far as I remember it stays the same once it is added to the page. Can you please expand which functionality would require the callback to be invoked? Thanks!

**Comment by syfgkjasdkn** [comment]
Hi @josevalim!

> Is the container ever updated?

The element is updated on the client. No patch is sent from the server though.

> Can you please expand which functionality would require the callback to be invoked?

I use `onBeforeElUpdated` to restore a JS library on an element. Please see: https://elixirforum.com/t/liveview-with-muuri-grid-would-phx-update-stop-ignore-make-sense/34312/7

**Comment by syfgkjasdkn** [comment]
I guess it's not that important to have `onBeforeElUpdated` run on a liveview container. The `cloneMuuri` approach that clones both the grid container and item elements seem to work fine. Thank you!
