### ISSUE TITLE
Changeset not updating on dataset change

### ISSUE THREAD

**Issue by D4no0** [phoenixframework/phoenix_live_view#1176]
Hello,
To not duplicate the question please refer to this question on [stackoverflow](https://stackoverflow.com/questions/64207329/changeset-not-updating-on-dropdown-data-update)

I was able to find a workaround, however I'm interested if this is a bug or there is a problem with the design I implemented?

**Comment by josevalim** [comment]
If you think this is a bug, then please fill in the issues templates with more information and a minimal reproduction sample. However, if it is a question, I would recommend using the Elixir Forum. In particular, it feels the code you wrote should work, as long as child_data is an assign.

**Comment by D4no0** [comment]
### Environment

* Elixir version (elixir -v): 1.10.3
* Phoenix version (mix deps):  1.5.4
* Phoenix LiveView version (mix deps): 0.14.7
* NodeJS version (node -v): 10.16.3
* NPM version (npm -v): 6.14.3
* Operating system: Ubuntu 20.04 focal (x86-64) 
* Browsers you attempted to reproduce this bug on (the more the merrier): firefox, chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: YES

### Actual behavior

Suppose I have the data:

```
data = [[key: 1, value: "1"], [key: 2, value: "2"] ,[key: 3, value: "3"]]
child_data = %{1: [key: 1, value: "exists"]}
```

And the html:

```
<%= select f, :corporation_id, data %>
<%= select f, :company_id, child_data[Ecto.changeset.get_field(@changeset, :corporation_id)] %>
```

My schema and changeset looks the following:

```
embedded_schema do
    field :corporation_id, :integer
    field :company_id, :integer
  end

def changeset(selected_org, attrs) do
    selected_org
    |> cast(attrs, [:corporation_id, :company_id])
    |> validate_required([:corporation_id, :company_id])
  end
```

The problem is the following: When I change the data of company the changeset does not get updated, the old id remains and it is still a valid changeset.

### Expected behavior

The validate event should be called with the `company_id` as nothing selected.

### Current Workaround

The hook:

```
Hooks.WorkaroundHook = {
  updated() {
    this.pushEvent("workaround", this.el.selectedIndex)
  }
}
```

And the handle:

  ```
def handle_event("workaround", index, socket) do
    # if changeset is valid and index is 0 add error to changeset
    {:noreply, socket}
  end
```
