### ISSUE TITLE
Patch not applied to child liveview

### ISSUE THREAD

**Issue by syfgkjasdkn** [phoenixframework/phoenix_live_view#1177]
### Environment

* Elixir version (elixir -v): Elixir 1.10.4
* Phoenix version (mix deps): 1.5.5
* Phoenix LiveView version (mix deps): 0.14.7
* NodeJS version (node -v): v14.13.0
* NPM version (npm -v): 6.14.8
* Operating system: mac
* Browsers you attempted to reproduce this bug on (the more the merrier): chrome, safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

Adding and removing a child liveview doesn't reset it. 

```elixir
  def handle_info({Dashboards, [:widget, :updated], widget}, socket) do
    socket = socket |> remove_widget(widget.id) |> add_widget(widget)
    {:noreply, socket}
  end
```
where widget is rendered as a child liveview

```elixir
  <%= for widget <- @widgets do %>
    <%= live_render @socket, WidgetLive,
      id: ["widget-", widget.id],
      session: build_auth_session(%{"widget_id" => widget.id}, assigns),
      container: widget_container(widget) %>
  <% end %>
```

### Expected

Adding and removing an element into/from assigns "resets" the child liveview.

**Comment by syfgkjasdkn** [comment]
Maybe there is a more manual way to "reset" a child liveview?

**Comment by syfgkjasdkn** [comment]
Updating from within a child liveview works but not always:

```elixir
def handle_info({Dashboards, [:widget, :updated], widget}, socket) do
    live_view_mod = live_view_mod(widget)
    socket = assign(socket, widget: widget, live_view_mod: live_view_mod)
    # TODO test there are no suprises
    {:ok, socket} = live_view_mod.mount(:not_mounted_at_router, nil, socket)
    {:noreply, socket}
  end
```

For example, I can update from a plain text widget to a mapbox map, but not the other way around. The client does receive the plain text widget markup though as shown by `liveSocket.enableDebug()`.

**Comment by josevalim** [comment]
Can you please provide a single file LiveView with everything necessary to reproduce the error? It is really hard to say what could be wrong based on a few snippets. Thank you.

**Comment by syfgkjasdkn** [comment]
Yeah, I'll prepare a repro. But in the meantime I wonder what's the recommended way to "reset" one of the child liveviews form the parent liveview?

**Comment by josevalim** [comment]
Oh, I see. Child live views are tracked by ID and this is documented behaviour. :) if the ID stays the same, they won't be reinvoked. So a way to reset them would be to have a counter. Instead of removing and adding, you would bump the counter and then do `id: ["widget-", widget.id, "-", widget.counter]`. :)
