### ISSUE TITLE
Proposal: Phoenix.LiveViewTest.open_browser/1 to inspect the html of view/element

### ISSUE THREAD

**Issue by leandrocp** [phoenixframework/phoenix_live_view#1178]
When working on some complex pages it's not rare to lose track of what's happening on the page and the diff doesn't always help either, especially on long html structures.

Other test libraries usually provide a way to render and inspect the current html, which I find very useful because you can see it easily and even inspect the html to help you out when writing/fixing tests.

So, in short, something like this would be welcome? https://github.com/leandrocp/phoenix_liveview_test_inspect

If the answer is no, I will keep working on that code as a separate lib :)

**Comment by josevalim** [comment]
:+1: from me. I used to love this feature when working on capybara.

**Comment by leandrocp** [comment]
Exactly, I also miss that feature :)

I'll send a PR to close this issue!

**Comment by josevalim** [comment]
Closing as we wait for PR. :)
