### ISSUE TITLE
Testing a live view rendered in a normal view

### ISSUE THREAD

**Issue by dustinfarris** [phoenixframework/phoenix_live_view#1182]
### Environment

* Elixir version (elixir -v): 1.10.4
* Phoenix version (mix deps): 1.5.6
* Phoenix LiveView version (mix deps): 0.13.0
* NodeJS version (node -v): 12.13.1
* NPM version (npm -v): 6.13.4
* Operating system: MacOS Catalina
* Browsers you attempted to reproduce this bug on (the more the merrier): Safari

### Actual behavior

Here's a minimal diff:
https://github.com/dustinfarris/phoenix_live_test_issue/compare/bug-1

In phx.server, this runs fine: visiting `/bug` will show a regular template rendered with the PageLive view rendered inside — and functioning as far as I can tell.

Both tests fail, however, with:

```
  1) test render (LiveTestBugWeb.BugControllerTest)
     test/live_test_bug_web/controllers/bug_controller_test.exs:6
     ** (KeyError) key :live_module not found in: %{layout: {LiveTestBugWeb.LayoutView, "app.html"}}
     code: {:ok, view, html} = live(conn, "/bug")
     stack6trace:
       (phoenix_live_view 0.13.0) lib/phoenix_live_view/test/live_view_test.ex:316: Phoenix.LiveViewTest.do_connect/6
       test/live_test_bug_web/controllers/bug_controller_test.exs:7: (test)



  2) test try this way (LiveTestBugWeb.BugControllerTest)
     test/live_test_bug_web/controllers/bug_controller_test.exs:11
     ** (KeyError) key :live_module not found in: %{layout: {LiveTestBugWeb.LayoutView, "app.html"}}
     code: {:ok, view, html} = live(conn)
     stacktrace:
       (phoenix_live_view 0.13.0) lib/phoenix_live_view/test/live_view_test.ex:316: Phoenix.LiveViewTest.do_connect/6
       test/live_test_bug_web/controllers/bug_controller_test.exs:13: (test)
```

### Expected behavior

I suspect this is user error on my part, so expected outcome would be documentation around testing normal views with nested live views, or documenting that this is not a supported pattern.

**Comment by josevalim** [comment]
Yeah, you want to use live_isolated, but the error message can definitely
be better.

**Comment by josevalim** [comment]
Apparently this has already been fixed! Don't forget to give the latest a try when filling bug reports as they may have been fixed. :) Thanks!

**Comment by dustinfarris** [comment]
Oh great, thanks!  FWIW I was just going with the version that gets installed with `--live`.  I have latest phoenix and didn't event think to check that there might be more recent versions of phoenix_live_view.

**Comment by josevalim** [comment]
Can it be your `mix phx.new` is out of date? :)

**Comment by dustinfarris** [comment]
Gah! it was.  🤦
