### ISSUE TITLE
Contents of a live component are removed on diff triggered by handle_info

### ISSUE THREAD

**Issue by bartblast** [phoenixframework/phoenix_live_view#1183]
### Environment

* Elixir version (elixir -v): 1.10.4
* Phoenix version (mix deps): 1.5.6
* Phoenix LiveView version (mix deps): 0.14.6 (same problem on 0.14.7)
* NodeJS version (node -v): 14.10.0
* NPM version (npm -v): 6.14.8
* Operating system: macOS Catalina 10.15.7
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome 86.0.4240.75 (Official Build) (x86_64), Firefox 81.0.2 (64-bit), Opera 71.0.3770.271,  Safari 14.0 (15610.1.28.1.9, 15610)
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

When handle_info which is triggered by another handle_event in the same live view (triggered by form submit) updates the state, the diff is incorrect, contents of a live component are removed and the root element of the component receives phx-skip attrib flag.

### Expected behavior

The live component is rendered correctly.

### How to reproduce

I created a very simple case in this repo: 
https://github.com/bartblast/phoenix_liveview_diff_problems

Steps:
* mix phx.server
* go to http://localhost:4000
* click the button
* the button contents disappear

Related files:
* lib/diff_problems_web/live/*

**Comment by josevalim** [comment]
A temporary solution for now is to change the ID of the component (you can keep a tick and bump the tick on the form submission) and make that part of the id.

**Comment by bartblast** [comment]
Hi @josevalim, I'm not sure I understand your comment - do you mean that the component id should change on each assign update? Also, I can see that you closed the issue with 597c5dd, does it mean it is fixed on master? If so, why then use the termporary solution?

**Comment by josevalim** [comment]
The solution is only in case you don’t want to upgrade to master. But master also definitely works!

**Comment by bartblast** [comment]
Got it, thanks for your work!
