### ISSUE TITLE
Can't re-render the Component contains [the LiveView with a stateful component inside]

### ISSUE THREAD

**Issue by leductam** [phoenixframework/phoenix_live_view#1189]
### Environment

* Elixir version (elixir -v): 1.11.1
* Phoenix version (mix deps): 1.5.6
* Phoenix LiveView version (mix deps): ~> 0.14.0
* NodeJS version (node -v): v13.9.0
* NPM version (npm -v): 6.14.8
* Operating system: Windows 10, MacOS Catalina 10.15.7
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox, Chrome, Safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior
The layout (There are some nested LiveViews for error isolation)

![LiveLayout](https://user-images.githubusercontent.com/3005538/96822261-deef5500-1453-11eb-90f2-1acbc37f1558.png)

[1] Click button "To TabLiveView"  -> then HeroLiveComponent changed template: rendered a button "Back to Hero Content" and live_render the TabLiveView -> TabLiveView render a stateful TabContentComponent.
[2] Click the button "Back To Hero Content" but can't back to hero content. This means HeroLiveComponent  can't re-render template and the TabLiveView is not leave out.

### Expected behavior
Can back to hero content when click the button "Back To Hero Content".

**Some notes remark that the issue is not appeared:**
1. If TabLiveView render a stateless TabContentComponent
2. **Use Phoenix LiveView 0.13.3**, so I'm not sure it is a bug or any updated docs from 0.14.0 to avoid this issue.

Please help to figure-out the issue or guide us the document to avoid its.
There is also a tiny repo to reproduce this issue: [https://github.com/leductam/live_layout]()

**Comment by chrismccord** [comment]
Please try master and report back. Thanks!

**Comment by leductam** [comment]
This issue is appeared with every versions from 0.14.0 (included master).

**Comment by josevalim** [comment]
Fixed in #1997. :)
