### ISSUE TITLE
protocol Phoenix.HTML.Safe not implemented for %Phoenix.LiveComponent.CID{cid: 1} of type Phoenix.LiveComponent.CID (a struct)

### ISSUE THREAD

**Issue by Abat** [phoenixframework/phoenix_live_view#1190]
### Environment

* Elixir version (elixir -v): **Elixir 1.10.3 (compiled with Erlang/OTP 21)** 
* Phoenix version (mix deps): **phoenix 1.5.6**
* Phoenix LiveView version (mix deps): **phoenix_live_view 0.14.7**
* NodeJS version (node -v): **v8.10.0**
* NPM version (npm -v): **3.5.2**
* Operating system: **Ubuntu 18.04.4 LTS**
* Browsers you attempted to reproduce this bug on (the more the merrier): **Chrome**
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: **yes**

### Actual behavior

I am trying to use **Targeting Component Events** functionality of PhoenixLiveComponent.

`<a href="#" phx-click="say_hello" phx-target="<%= @myself %>">
  Say hello!
</a>
`

I am seeing an error:

protocol Phoenix.HTML.Safe not implemented for %Phoenix.LiveComponent.CID{cid: 1} of type Phoenix.LiveComponent.CID (a struct). This protocol is implemented for the following type(s): Decimal, Phoenix.LiveView.Component, Phoenix.LiveView.Comprehension, Phoenix.LiveView.Rendered, Atom, BitString, Date, DateTime, Float, Integer, List, NaiveDateTime, Phoenix.HTML.Form, Time, Tuple

### Expected behavior

As described in **Targeting Component Events** of PhoenixLiveComponent.

**Comment by josevalim** [comment]
Hi @Abat! This seems to be an issue with your `_build`. Please try removing the `_build` directory and see if the problem persists.

**Comment by Abat** [comment]
Hi @josevalim! Indeed, that solved it. 

Thank you!

Maybe something like this should be added too :)

- Does the problem persist after removing "_build" and trying again? Yes/no:

**Comment by jdmarshall** [comment]
Hello from the future.

If you get this error with something like:

`
            phx-target={{ @myself }}
`

What you wanted was:

`
            phx-target={ @myself }
`
