### ISSUE TITLE
phx-target doesn't bind anymore to the liveview

### ISSUE THREAD

**Issue by Matsa59** [phoenixframework/phoenix_live_view#1192]
### Environment

* Elixir version (elixir -v): 1.10
* Phoenix version (mix deps): 2.14
* Phoenix LiveView version (mix deps): 0.14.7
* NodeJS version (node -v): 12.16.1
* NPM version (npm -v): 6.14.8
* Operating system: Mac OS X Catalina 10.15.7 
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

`phx-target` doesn't target the live view that should handle the event.

`static.html.ex`:

```html
<%= live_render(@conn, MyAppWeb.MyLiveView, %{}) %>

<button phx-target="#my-id" phx-click="event">Trigger event</button>
```

` MyAppWeb.MyLiveView`
```elixir
defmodule MyAppWeb.MyLiveView do
  def mount(...), do: ...
  def render(assigns), do: ... #render the file live.html.leex
  def handle_event("event", _, socket) do
    IO.puts("Event triggered")
    {:noreply, socket}
  end
end
```

`live.html.leex`
```html
<div id="my-id">
  ...
</div>
```

### Expected behavior

`MyAppWeb.MyLiveView` should handle the event. 

It was working on version `0.12.1` and I recently try in `0.13.3` and I works also. 
Breaks on version `0.14.0`

EDIT:  I don't know if it's linked but the same behaviour is observable with `phx-hook`.

**Comment by whitepaperclip** [comment]
@Matsa59 You should be able to use `use Phoenix.LiveView, container: {:div, id: "my-id"}`. This will apply a DOM ID to the root live view node and should accept events.
