### ISSUE TITLE
LiveView: loading bar gets stuck on long running task

### ISSUE THREAD

**Issue by alexgleason** [phoenixframework/phoenix_live_view#1193]
### Environment

* Elixir version (elixir -v): 1.10.4
* Phoenix version (mix deps): 1.5.3
* NodeJS version (node -v): v12.13.1
* NPM version (npm -v): 6.12.1
* Operating system: elementary OS 5.1.7 Hera

### Expected behavior
The loading bar finishes after long running tasks.

### Actual behavior
The loading bar gets stuck and never finishes.

![Screenshot from 2020-10-22 20-26-47](https://user-images.githubusercontent.com/3639540/96946195-471a5700-14a5-11eb-923d-3fc0f2f3b13c.png)

Simple test to reproduce this:

```elixir
@impl true
def handle_event("deploy", _, socket) do
  :timer.sleep(30 * 1000) # 30 seconds
  {:noreply, socket}
end
```

The websocket reply does come through as expected:

![Screenshot from 2020-10-22 20-31-53](https://user-images.githubusercontent.com/3639540/96946356-bd1ebe00-14a5-11eb-9884-08b91bc706d3.png)

**Comment by windowsdeveloperwannabe** [comment]
For me 30 seconds works pretty reliably, but anything longer than that, like 31 seconds, I get the same behavior. The changes received from the reply are also not applied to DOM, so I think it's not just progress bar but live view problem. With `enableDebug` on there is no update log either.

**Comment by josevalim** [comment]
Can you please verify if this issue happens with [topbar](https://buunguyen.github.io/topbar/)? Here is my setup:

```
topbar.config({
  barThickness: 3,
  barColors: { '1.0': '#0366D6' },
  shadowBlur: 0
})

window.addEventListener('phx:page-loading-start', info => {
  topbar.show()
})

window.addEventListener('phx:page-loading-stop', info => {
  topbar.hide()
})
```

**Comment by windowsdeveloperwannabe** [comment]
I made an example repo with a button for 29 second and 31 second replies which I hope is helpful: https://github.com/windowsdeveloperwannabe/long_running_view_event

For me the 29 second reply changes the DOM correctly. The 31 second reply can be seen from websocket frames correctly, but it is not applied to DOM and the progress bar is left running. The example also uses topbar.

**Comment by josevalim** [comment]
30s+ with no response is definitely enough to justify a force reload with jitter. Sounds good to me as long as we also log something.
