### ISSUE TITLE
Extracted code in a sub live view breaks AlpineJS behavior

### ISSUE THREAD

**Issue by Malian** [phoenixframework/phoenix_live_view#1209]
### Environment

* Elixir version (elixir -v): 1.11
* Phoenix version (mix deps): 1.5.6
* Phoenix LiveView version (mix deps): 0.14.8
* NodeJS version (node -v): v10.19.0
* NPM version (npm -v): 6.14.8
* AlpineJS version: 2.7.3
* Operating system: Ubuntu 20.04.1 LTS
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox, Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

**Link to a sample app** --> https://github.com/Malian/AlpineJsNestedLiveView

In my project I am trying to extract the sidebar to a sub live view. The sidebar is closed by default with an AlpineJs directive: `x-data="{open: false}"`. Before extracting the code to the sub live view, everything works as expected. I reproduce the behavior in the code below.

```elixir
defmodule AlpinejsNestedLiveViewWeb.PageLive do
  use AlpinejsNestedLiveViewWeb, :live_view

  def render(assigns) do
    ~L"""
    <h1>Main Live View</h1>
    <div x-data="{ open: false }">
      <h2 x-show="open">Should not be seen</h2>
    </div>
    """
  end
end
```
The generated page works as expected and does not show the `h2`.
![image](https://user-images.githubusercontent.com/553321/98377668-68527a00-2045-11eb-9480-94cd29e5f573.png)

In my app, I would like to extract the sidebar to a sublive view. I refactored the code above to extract the `h2` into a live view to simulate my app:
```elixir
defmodule AlpinejsNestedLiveViewWeb.PageLive do
  use AlpinejsNestedLiveViewWeb, :live_view

  def render(assigns) do
    ~L"""
    <h1>Main Live View</h1>
    <div x-data="{ open: false }">
      <%= live_render(@socket, NestedAlpineLive, id: "nested-apline") %>
    </div>
    """
  end
end

defmodule NestedAlpineLive do
  use AlpinejsNestedLiveViewWeb, :live_view

  def render(assigns) do
    ~L"""
      <h2 x-show="open">Should not be seen</h2>
    """
  end
end
```
Now, the behavior is not the same and the `h2` is visible.

![image](https://user-images.githubusercontent.com/553321/98377599-51ac2300-2045-11eb-8661-4c73494e4319.png)

**Link to a sample app** --> https://github.com/Malian/AlpineJsNestedLiveView

### Expected behavior

The expected behavior is that the `h2` should not be visible.
![image](https://user-images.githubusercontent.com/553321/98377668-68527a00-2045-11eb-9480-94cd29e5f573.png)

### What I already have tried?

* I tried to move the AlpineJS directive `x-data="{open: false}" to the live view container but the behavior still be the same
```elixir
      <%= live_render(@socket, NestedAlpineLive, id: "nested-apline", container: {:div, "x-data": "{ open: false }"}) %>
```
* I tried to move the directive into the live view. It works but it does not solve my issue as I need the `open` variable outside the sub live view but it conforts me that there is something wrong.

I hope I have given you enough information to understand and reproduce the "bug".

I would be happy to help you if you could direct me to the steps to fix the bug if it is a bug of course.

**Comment by mgibowski** [comment]
While broken AlpineJS in sub live view looks like a real issue that probably should be addressed, I will share my perspective on extracting code in such scenarios, which eliminates this kind of problem.

Declaring sub live view is not the only way to extract code from a live view. You could also create a live component (stateful or stateless) or just extract a piece of code into an `html.eex` snippet. 

Looking at what you described:
> In my project I am trying to extract the sidebar to a sub live view. The sidebar is closed by default with an AlpineJs directive: x-data="{open: false}". 

It doesn't seem like the extracted code needs to sit inside of a live view. In fact to me it seems a bit of an overkill. Every live view means a stateful component on server side, WebSocket communication channel, etc... Nothing of this is needed to display some static (from server-side point of view) block of code.

In such scenario I would rather put this code in a standard template.

So for example I would create such a module:

```elixir
defmodule AlpinejsNestedLiveViewWeb.SnippetsView do
  use AlpinejsNestedLiveViewWeb, :view

  def nested_alpine_h2 do
    ~E"""
        <h2 x-show="open">Should not be seen</h2>
    """
  end
end

```

and then in your LiveView just call: 
```eex
<%= AlpinejsNestedLiveViewWeb.SnippetsView.nested_alpine_h2 %>
```

I just tried it in your project and it works.
Other then that, you could also try extracting code to a stateless live component, which I think should work too.

**Comment by chrismccord** [comment]
We don't provide anything in particular for Alpine integration, other than the `dom` option for Alpine nodes to be able to clone themselves when the DOM is patched, so this is not on our side. Keep in mind you may need to provide a new ID on the Dom node if you need to dynamic update `x-data`. Closing as I don't believe there's anything for us to handle here. Thanks!

**Comment by Malian** [comment]
@mgibowski Thank you for your detailed reply! I fully agree with your conclusions.

To give you more context, I was experimenting new ways of managing layouts. I mainly take the idea from this forum [thread](https://elixirforum.com/t/liveview-with-complex-layouts/35242/18) and more precisely from this [comment](https://elixirforum.com/t/liveview-with-complex-layouts/35242/18).
