### ISSUE TITLE
unexpetced wrapping main in div

### ISSUE THREAD

**Issue by m0dh4x** [phoenixframework/phoenix_live_view#1213]
### Environment

* Elixir version (elixir -v): 1.11.1
* Phoenix version (mix deps): 1.5.6
* Phoenix LiveView version (mix deps): 0.14.8
* NodeJS version (node -v): 15.0.1
* NPM version (npm -v): 7.0.3
* Operating system: OSX Catalina
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox dev, Chrome, Safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior
In case of correct syntactical HTML i expected the `<main>` pure (i.e. for classless css), but it is wrapped in a `<div>`. In my opinion you do not want modify the self written html part in templates and this is why you wrap the `<main>` in a div to add phx-disconnect/phx-connected or phx-error class or is there another point why you do this? 

```html
<div data-phx-main="true" data-phx-session="....." data-phx-static="..." data-phx-view="PageLive" id="..." class="phx-connected" data-phx-root-id="...">
  <main role="main" class="container" data-container="true">
    <p class="alert alert-info" role="alert" phx-click="lv:clear-flash" phx-value-key="info"></p>
    <p class="alert alert-danger" role="alert" phx-click="lv:clear-flash" phx-value-key="error"></p>
  </main>
</div>
```

### Expected behavior

```html
<style>
 main[data-phx-connected="true"] {...} // somthing like this or add it do body?
</style>

<main data-phx-connected="true" data-phx-main="true" data-phx-session="....." data-phx-static="..." data-phx-view="PageLive" id="..." role="main" class="container" data-container="true" >
  <p class="alert alert-info" role="alert" phx-click="lv:clear-flash" phx-value-key="info"></p>
  <p class="alert alert-danger" role="alert" phx-click="lv:clear-flash" phx-value-key="error"></p>
</main>
```

**Comment by sorax** [comment]
yeah! would be great if live_view wouldn’t interfere with the html any more
a pull-request with the changes needed would be great

**Comment by josevalim** [comment]
Unfortunately LV has to control the container element but you can customize it. Please see the container option in the docs that allow you to change the tag and it’s attributes.
