### ISSUE TITLE
Feature suggestion: phx-update="list"

### ISSUE THREAD

**Issue by DaTrader** [phoenixframework/phoenix_live_view#1214]
### Environment

* Elixir version (elixir -v): 1.10.3
* Phoenix version (mix deps): 1.5.6
* Phoenix LiveView version (mix deps): 0.14.7
* NodeJS version (node -v): 12.14.1
* NPM version (npm -v): 6,13.4
* Operating system: Linux Mint
* Browsers you attempted to reproduce this bug on (the more the merrier):  Firefox, Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Y

### Actual behavior

Having a relatively large number of listed child elements (e.g. 200+) in a container, the client side JS is becoming increasingly and observably slow when required to apply diffs that are a result of element deletion and/or insertion even when the elements as such are properly compartmentalized into components and their internal content is not altered (re-rendered).

When analyzing the performance with dev tools, the LV JS scripting takes up ever more time to execute as new elements get added and is virtually the only reason behind the slow down.

The append/prepend approach is not applicable when element deletion is required and/or new elements get inserted at various positions between the existing elements.

### Expected behavior

My suggestion is to introduce a new phx-update value (a hint) named "list" which instructs LV to treat the changes in the container as if its children were a list, i.e. when missing element in detected, instruct JS to delete it from the DOM and when detecting new one(s) instruct JS to insert them correspondingly, instead of replacing the content of the container all together which, as noted before, with hundreds of child elements can become a very expensive client-side operation.

I am aware that this probably requires additional meta data passed to LV JS from its server counterpart, and that it may require a significant effort to accommodate but it is worth noting that this UC (e.g. editable lists, tables, etc.) is so common that I believe deserves special attention and treatment.

@chrismccord, @josevalim:
Please shed some light on whether this feature request may be considered in the future and if so, and, if possible, a hint on when it may be expected.

Thanks a lot!

**Comment by josevalim** [comment]
Hi @DaTrader, it is something we definitely discussed as phx-sort but, as typical in OSS development, there is no time frame for it unless you implement it yourself and submit it a PR.

Luckily, you can always implement missing features using hooks. For example, you may be able to achieve it using phx-update="append/prepend" with a hook that sorts the elements later according to your criteria.

We will close this for now as our focus on the issues tracker is to track issues themselves. Thank you.

**Comment by DaTrader** [comment]
Hi José,

Thanks for the quick reply and the advice regarding the use of hook in this case. I will definitely look into it as it may indeed be a solution for element insertions.

Is there anything you could suggest to get better performance with element deletion as well? 

Thanks,

Damir

**Comment by josevalim** [comment]
I would implement deletion by sending divs entries as `<div id="id-to-delete" phx-delete>`. This will be enough to set the element to empty and then the hook can find anything with phx-delete and remove it.

Something else you could do and it should speed up things today is to continue rendering it as a list but render each list entry as a component. The components are tracked individually which means re-rendering the list is fast (we only send the component IDs).

**Comment by DaTrader** [comment]
Thanks, will do that. It will require changes to my models (flagging for deletion instead of real deletion), but will do it for it seems the only way to go for now.

Btw, I am already rendering the elements as components and it did speed up the thing, but with hundreds of elements the classic replace is still slow client-side, so I guess I will have to implement those hooks as you suggested.

**Comment by DaTrader** [comment]
@josevalim 

Hi again, Jose

Just a follow up on all this optimization thing and your suggestion re phx-delete in your last comment above. I did all this and it works. But while debugging my own code at one point I saw these phx-delete elements rendered in the DOM html and they look exactly like this (before deleting them in JS):
`<div id="some id" phx-delete=""></div> [event]`

Two questions:
1. The element above is rendered as a component (just like the original that gets overwritten with this one for the purpose of deletion) and yet the phx-component="component id" is not rendered. Is this still ok? 
2. As you can see, it still has the original element's (the one with the same id that was overwritten by it) event listener attached to the element. Since the code is the shortest possible without the reference to the hook that the original element had - the hook that added the event listener to the now overwritten element which also takes care of removing it. 
Should I have the same hook reference in this phx-delete element as well so that LiveView takes care of invoking its destroyed callback which removes the event listener, since it is not done in the process of replacing the element?

Thanks,

Damir
