### ISSUE TITLE
Feature request: flash message clear itself after timeout

### ISSUE THREAD

**Issue by torepettersen** [phoenixframework/phoenix_live_view#1218]
Flash messages are a quite convenient way to display notifications. Would it be possible to add timeout option to `put_flash`, so that this message disappears after the timeout? This way users won't have to manually clear every notification.

**Comment by josevalim** [comment]
This is not something we may provide out of the box but we definitely want to provide callbacks that will make it easy for you to implement yourself. So keep checking :) thanks!
