### ISSUE TITLE
Form change tracking

### ISSUE THREAD

**Issue by mset** [phoenixframework/phoenix_live_view#1219]
### Environment

* Elixir version (elixir -v): Elixir 1.11.2 (compiled with Erlang/OTP 23)
* Phoenix version (mix deps): 1.5.6
* Phoenix LiveView version (mix deps): 0.14.8
* NodeJS version (node -v): v14.4.0
* NPM version (npm -v): 6.14.8
* Operating system: Linux Fedora 32
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome Version 86.0.4240.193 (Official Build) (64-bit)
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

I am new to LiveView and Phoenix but it seems to me that what I am seeing is not how things are intended to work, perhaps?

The short story:
When a liveview on the server responds to a form change by sending a phx_reply WS message, the message contains the markup of the whole form.

The long story: 
I used the mix live generator, created a simple schema as per the docs (`mix phx.gen.live Accounts User users name:string age:integer`), and started the server. When I navigate to the `/users/new` url, the modal with the form appears. When I type into the 'name' field, for instance, and watch the websocket communication with the server, I see the HTML markup for the whole form being returned to the browser in the phx_reply message upon every phx_change invokation. 

Is this expected? I have been under the impression that the change-tracking would identify the changed form field - an html input, in my case -  and send just the difference in the value of the field instead of sending the whole form.

I checked the markup for the form to ensure that it's not using the anonymous function with the <% end %>.

Perhaps I am doing something wrong or my expectation does not match how things are meant to behave.

**Comment by josevalim** [comment]
The way LiveView works is that, if it sees a variable in the template, we always render those particular parts. We are aware it is not ideal and we are discussing solutions to make the form rendering more robust, but this is expected behaviour for now. :) Good find, and welcome!

**Comment by mset** [comment]
Thank you for the quick response, José.
