### ISSUE TITLE
push_patch function fails when the URL is directly accessed in the test suite

### ISSUE THREAD

**Issue by plicjo** [phoenixframework/phoenix_live_view#1222]
### Environment

* Elixir version (elixir -v): 1.11.2
* Phoenix version (mix deps): 1.5.6
* Phoenix LiveView version (mix deps): 0.14.6
* NodeJS version (node -v): 14.5.0
* NPM version (npm -v): 6.14.8
* Operating system: Mac OSX Catalina
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yest
### Description
The test is failing on the following lines:
https://github.com/plicjo/assert_patched_bug_report/commit/c89cb41b1aa36cd3115a558563c08fd6f179e679#diff-43e64c656923d858bfecac3888cc73c37e09fcc0731c1217853a6ff37602918bR8
`{:ok, bug_report_live, _html} = live(conn, Routes.bug_report_path(conn, :index))`
`{:noreply, push_patch(socket, to: Routes.bug_report_path(socket, :index, %{foo: "bar"}))}`

This leads me to believe that `push_patch` doesn't play correctly with the `live` function in the test environment.

I've tested `push_patch` under the condition of performing an action on the page and it works fine. Visiting a url directly, expecting the location to change, appears to be buggy.

### Example Repo

Link to repo with reproduced bug: https://github.com/plicjo/assert_patched_bug_report

The commit with the change: https://github.com/plicjo/assert_patched_bug_report/commit/c89cb41b1aa36cd3115a558563c08fd6f179e679

### Actual behavior

The test fails with the following:
```
mix test
..

  1) test Bug Report when no params - patch url to include foo param (AssertPatchedBugReportWeb.PackageLiveTest)
     test/assert_patched_bug_report_web/live/bug_report_live_test.exs:7
     ** (MatchError) no match of right hand side value: {:error, {:live_redirect, %{flash: "SFMyNTY.g2gDdAAAAABuBgAjPELDdQFiAAFRgA.PNe-TJk1gjpe5AaYVtLQIxvFdA0RE_F_boCN9FmWzio", to: "/bug_report?foo=bar"}}}
     code: {:ok, bug_report_live, _html} = live(conn, Routes.bug_report_path(conn, :index))
     stacktrace:
       test/assert_patched_bug_report_web/live/bug_report_live_test.exs:8: (test)

```

### Expected behavior

The test should pass, as it performs the patch just fine in the development environment.

**Comment by josevalim** [comment]
The test is behaving correctly. That's because, on mount, a live_patch behaves like a redirect, since we cannot patch a LiveView that was not mounted yet. The JS client ignores this, because it is not interested in processes, but in tests `live` returns a reference to the LV process, which does not exist in this case.

**Comment by plicjo** [comment]
I see. Thank you.

**Comment by plicjo** [comment]
@josevalim How can I get this under test?

**Comment by josevalim** [comment]
Pattern match on the returned result:

    {:error, opts} = ...
    assert opts[:live_redirect] == ...

**Comment by plicjo** [comment]
@josevalim Ok, that makes sense. Cheers!

For anyone else landing on this issue, I got it under test with the following:

```elixir
describe "Bug Report" do
  test "when no params - patch url to include foo param", %{conn: conn} do
    {:error, {:live_redirect, %{to: location}}} = live(conn, Routes.bug_report_path(conn, :index))
    assert location == "/bug_report?foo=bar
  end
end
```

**Comment by plicjo** [comment]
Matching on an `{:error ...` tuple is a very lackluster developer experience, as you are just accepting an error.

I rewrote the test as a controller test and it's much more palatable:

```elixir
describe "Bug Report" do
  test "when no params - patch url to include foo param", %{conn: conn} do
    conn = get(conn, Routes.bug_report_path(conn, :index))
    assert redirected_to(conn) == "/bug_report?foo=bar"
  end
end
```

**Comment by josevalim** [comment]
Good call, I like the `get` approach too!
