### ISSUE TITLE
Unexpected LiveView behaviour?

### ISSUE THREAD

**Issue by diegonogueira** [phoenixframework/phoenix_live_view#1224]
Hi,

Could someone help me to clarify if it's a unexpected behaviour?

1- How can I use phx-change with select input field?

2- If a user is filling a form and have an internet fail, all fields would be empty. Any way to avoid this?

3- If I have a form with States>>Cities>>Neighborhood and I use phx-blur on my state field to load all state cities, I have again, all my fields empty, even the state field. Any way to avoid this?

Thanks,
Diego

**Comment by josevalim** [comment]
Please use the [ElixirForum](http://www.elixirforum.com) or StackOverflow for questions/help/feedback, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
