### ISSUE TITLE
Fresh LiveView app periodically crashes on Safari

### ISSUE THREAD

**Issue by alessandrousseglioviretta** [phoenixframework/phoenix_live_view#1228]
### Environment

* Elixir version (elixir -v): 1.11.0
* Phoenix version (mix deps): 1.5.0
* Erlang version: Erlang/OTP 23 [erts-11.1] [source] [64-bit] [smp:6:6] [ds:6:6:10] [async-threads:1] [hipe]
* Phoenix LiveView version (mix deps): 0.14.0
* NodeJS version (node -v): v14.12.0
* NPM version (npm -v): 6.14.8
* Operating system: macOS Catalina 10.15.7
* Browsers you attempted to reproduce this bug on (the more the merrier): Safari 14.0 (15610.1.28.1.9, 15610)
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

A fresh Phoenix LiveView periodically crashes: just create a LiveView app by `mix phx.new myapp --live` and start it with `iex -S mix phx.server`, load the page, put the browser tab in the background and wait some time. The browser will cycle through a few disconnect/reconnect and the view will periodically crash (see screenshot of the console). The issue does not seem to occur on Firefox 82.0.3.

### Expected behavior

No view crashes, possibly no disconnect/reconnect cycles, but that might be browser-specific.

![Screenshot 2020-11-17 at 11 57 23](https://user-images.githubusercontent.com/2053914/99386363-a4ea6500-28d2-11eb-880e-a345ef126d4d.png)

**Comment by josevalim** [comment]
Safari automatically closes WebSocket connections when it is in the background, unfortunately there is nothing we can do to avoid that, but Phoenix should always reconnect it for you.

Another option is for us to not try to reconnect until the user focuses on the page but I don't think that's what you asking. There is nothing we can do to stop the disconnects though.

**Comment by alessandrousseglioviretta** [comment]
> There is nothing we can do to stop the disconnects though.
That's what I thought, but what about the view crashing?

**Comment by josevalim** [comment]
The view will crash if it loses connection, that's why it reconnects. It is part of its regular recovery mechanism.

**Comment by alessandrousseglioviretta** [comment]
ok, all good then

**Comment by krns** [comment]
We discovered a similar behaviour with Chrome because of a Features called »Intensive throttling of Javascript timer wake ups« which was introduced July 2020 (see this article for further information: https://solace.community/discussion/694/client-websocket-disconnects-when-browser-is-minimized-or-not-in-focus-chrome).

Because Chrome throttles at a 1-minute (60 second) interval we increased the default timeout of 60 seconds to 75 seconds.
