### ISSUE TITLE
There is no unmount callback on Phoenix.LiveView

### ISSUE THREAD

**Issue by skylerparr** [phoenixframework/phoenix_live_view#123]
### Actual behavior
There is a callback to track when the socket has been `mount`ed, but there is no callback to be notified when the socket has been `unmount`ed. This makes cleaning up the user's session difficult (like committing unsaved work to a database when the user closes a browser tab, for example).

### Expected behavior
Have a callback for when the socket is unmounted.

```
def unmount(session, socket) do
  # clean up or post disconnect operation
  {:noreply, socket}
end
```

**Comment by skylerparr** [comment]
Looks like I can just use the terminate callback (https://github.com/phoenixframework/phoenix_live_view/blob/master/lib/phoenix_live_view.ex#L467). That'll work. Sorry for the pollution.

**Comment by chrismccord** [comment]
terminate only works if you are trapping exits, which you rarely want to do. To handle the view process going away, you'd handle it the same way you handle any other elixir process going away – you have another process monitor you. This should get you moving:

```elixir

defmodule MyLive do
  use Phoenix.LiveView

  def mount(_, socket) do
    LiveMonitor.monitor(self(), __MODULE__, %{id: socket.id})
  end

  def unmount(%{id: id}, _reason) do
    IO.puts("view #{id} unmounted")
    :ok
  end
end

defmodule LiveMonitor do
  use GenServer

  def monitor(pid, view_module, meta) do
    GenServer.call(pid, {:monitor, pid, view_module, meta})
  end

  def init(_) do
    {:ok, %{views: %{}}}
  end

  def handle_call({:monitor, pid, view_module}, _, %{views: views} = state) do
    Process.monitor(pid)
    {:reply, :ok, %{state | views: Map.put(views, pid, {view_module, meta})}}
  end

  def handle_info({:DOWN, _ref, :process, pid, reason}, state) do
    {{module, meta}, new_views} = Map.pop(state.views)
    module.unmount(reason, meta)
    {:noreply, %{state | views: new_views}}
  end
end
```

**Comment by akeating** [comment]
I like this solution, but it reveals another problem: mount appears to be called twice with the same socket id but with different pids. I believe I would need to be able to rely on a stable pid/socket_id combination to make this usable. Perhaps there's another perspective I should consider?
```
[info] GET /
[debug] Processing with PhoenixGenWeb.PageController.index/2
  Parameters: %{}
  Pipelines: [:browser]
mount session: %{}, socket.id: phx-9bGz7y4A, pid: #PID<0.515.0>   <=== mount called
monitor #PID<0.515.0> .  <=== monitor setup
:DOWN #PID<0.515.0> .  <=== ah, maybe that pid is already dead??
[info] Sent 200 in 114ms
view phx-9bGz7y4A unmounted
[info] CONNECT Phoenix.LiveView.Socket
  Transport: :websocket
  Connect Info: %{}
  Parameters: %{"vsn" => "2.0.0"}
[info] Replied Phoenix.LiveView.Socket :ok
mount session: %{}, socket.id: phx-9bGz7y4A, pid: #PID<0.528.0> . <=== mount called again, diff pid
monitor #PID<0.528.0> <=== this monitor appears to work
[info] Replied phoenix:live_reload :ok
```

**Comment by akeating** [comment]
ahh nvm, I see it's probably the initial render, followed by the socket connect, where mount/2 is called twice. I will work-around by ignoring the first time I see a given socket id.

**Comment by chrismccord** [comment]
You should use `connected?(socket)` to conditionally call the code path instead to avoid

**Comment by dhanson358** [comment]
Trying to follow this example and stumbling a bit... shouldn't the `LiveView#monitor` method be calling to it's own pid (aka `self()`), not the pid passed (which is of the socket connection)?  And does this assume the GenServer has already had `start_link` somewhere earlier in the app?  Or am I misunderstanding the GenServer relationship here? 

Appreciate any guidance, really enjoying tinkering with LiveView!

**Comment by dhanson358** [comment]
Right, I think what's throwing me is inside LiveMonitor#monitor when it calls `GenServer.call(pid, {:monitor, pid, view_module, meta})`.  That's calling {:monitor} back to the live view process, isn't it?  Instead, it should be invoking that on the PID coming back from the GenServer's `start_link`, shouldn't it?

**Comment by dhanson358** [comment]
That helped clarify those details for me a lot, thank you very much!  Working great now.

**Comment by juanpabloaj** [comment]
> terminate only works if you are trapping exits, which you rarely want to do. 

It's trapping exits a bad idea? why?

My question is because if I use the `unmount(reason, meta)` approach, do I have some option to get the last state of the socket  in `unmount`?

Thanks :)

**Comment by JasterV** [comment]
Why doesn't phoenix implement this? Why do we have to copy paste the monitor code of other users when it could be integrated in phoenix??

**Comment by trans** [comment]
What about using Javascript `beforeunload` event to trigger `pushEvent` hook?

**Comment by dmkenney** [comment]
Like @JasterV said, why do we want this to **NOT** be a part of Liveview? 

Take the following example:
- User is on a page with a form
- They edit the form
- The change pages (using live navigation)

I'd like to prevent the navigation and show a confirmation/dialog/etc - but to do it in Liveview is very roundabout. You can't do it in pure JS because there is no way to prevent the actual navigation. I can setup a Liveview hook to add a property on the socket, but no way (other than the supervisor method mentioned) to actual prevent the navigation. You can do a combo of Liveview hooks with JS hooks and listen for the phx:page-loading-start event. But I _feel_ like this should be easier.

I'm trying to genuinely understand this. Would love if @josevalim or anyone else with insights chimed in.

Thanks

**Comment by DavidRawk-Blake** [comment]
The monitor also becomes a problem, because sometimes the socket dies and the user didn't leave the page. The user goes to the bathroom, and the socket sits idle for a few minutes. Or a deploy happens while the user is on the page.
