### ISSUE TITLE
LiveView.Upload.update_progress requires is_binary for reason, but upchunk(guide suggested for external) returns a struct which fails.

### ISSUE THREAD

**Issue by ed-chung** [phoenixframework/phoenix_live_view#1231]
### Environment

* Elixir version (elixir -v): 1.10.4
* Phoenix version (mix deps):  1.5.6
* Phoenix LiveView version (mix deps): 0.15.0-dev branch: master
* NodeJS version (node -v): 12.18.3
* NPM version (npm -v): n/a
Yarn version: 1.22.4
* Operating system: Windows 7
* Browsers you attempted to reproduce this bug on (the more the merrier):  Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

When receiving an error from @Mux/Upchunk which is recommended in the uploads_external guide, the following exception is raised:
** (FunctionClauseError) no function clause matching in Phoenix.LiveView.Upload.update_progress/4
    (phoenix_live_view 0.15.0-dev) lib/phoenix_live_view/upload.ex:97: 

The error returned by upchunk is:
%{"error" => %{"attempts" => 5, "chunk" => 0, "message" => "An error occurred uploading chunk 0. No more retries, stopping upload"}} 

The function definition requires:
def update_progress(%Socket{} = socket, config_ref, entry_ref, %{"error" => reason})
      **when is_binary(reason)**

When calling is_binary on a struct
iex(1)> is_binary(%{"attempts" => 5, "chunk" => 0, "message" => "An error occured uploading chunk 0. No more retries, stopping upload"})
**false**

### Expected behavior

Pattern matching either needs to not guard on is_binary or pull "message" from reason.

**Comment by mcrumm** [comment]
Thanks for reporting!

**Comment by ed-chung** [comment]
Duh!  I don't know why I didn't even think about looking at the js code.  I just saw the elixir exception and thought the fix had to be in elixir.  Thanks for the quick fix.
