### ISSUE TITLE
Link to "External Uploads Guide" in uploads guide is broken

### ISSUE THREAD

**Issue by VirtualAirwaves** [phoenixframework/phoenix_live_view#1234]
Commit:  b87e5f829168911bb43d5bce6eb75847ed9e3bbd

There's a link on the bottom of this page

`https://github.com/phoenixframework/phoenix_live_view/blob/b87e5f829168911bb43d5bce6eb75847ed9e3bbd/guides/server/uploads.md`

that says

`For more information on implementing client-side, direct-to-cloud uploads, see the External Uploads guide.`

and the link goes to 

`https://github.com/phoenixframework/phoenix_live_view/blob/b87e5f829168911bb43d5bce6eb75847ed9e3bbd/guides/server/uploads-external.md `

which gets a 404

**Comment by josevalim** [comment]
The link will be correct. It is written so it works when published on ExDoc but it will fail from GitHub. Thanks!
