### ISSUE TITLE
Can't render the rest of the form when no DOM wrapping live_img_preview and <progress>

### ISSUE THREAD

**Issue by venusafe** [phoenixframework/phoenix_live_view#1237]
### Environment

* Phoenix LiveView version (mix deps): 0.15

### Actual behavior

`
SOMETHING BEFORE
<%= live_file_input @uploads.photo %> 
    <%= for entry <- @uploads.photo.entries do %>
      <%= live_img_preview entry, height: 80 %>
      <progress max="100" value="<%= entry.progress %>"/>
    <% end %>
THE REST OF THE FORM
`

![Screenshot 2020-11-21 at 12 10 10 PM](https://user-images.githubusercontent.com/61528293/99867218-9792ea80-2bf2-11eb-8a3d-1e466d414e40.png)
![Screenshot 2020-11-21 at 12 10 02 PM](https://user-images.githubusercontent.com/61528293/99867220-995cae00-2bf2-11eb-81d1-8280ffc57830.png)

When using live_img_preview & <progress> together without any DOM wrapping. The REST OF THE FORM will not render correctly. The result is fine when using live_img_preview alone even no dom wrapper. 

The following code would display result correctly.
`
SOMETHING BEFORE
<%= live_file_input @uploads.photo %> 
    <%= for entry <- @uploads.photo.entries do %>
      <div><%= live_img_preview entry, height: 80 %>
      <progress max="100" value="<%= entry.progress %>"/></div>
    <% end %>
THE REST OF THE FORM
`

Thank you very much.

**Comment by josevalim** [comment]
Can you please provide the complete LiveView? Or, in case this is a component, the component itself? Are there any messages in the browser console? Which browsers can you reproduce this on?

**Comment by venusafe** [comment]
Hello Jose, thank you for your prompt reply. 

Here is the git repository:
https://github.com/venusafe/liveview-upload-rendering-issue

The repository is using phx.new --live to generate and directly changed the lib/live/page_live.ex & page_live.html.leex.

I tried on liveview and live_component, they are both the same result in Chrome, Brave, Safari & Firefox on Mac. Haven't tried on Windows. 

Thank you.

**Comment by mcrumm** [comment]
Hi @venusafe! According to the MDN docs for the [`<progress>` element ](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress), both the opening and the closing tag are mandatory:

```elixir
<progress max="100" value="<%= entry.progress %>"></progress>
```

Add the closing tag, and the last progress element in your example will stop swallowing the additional form fields. :) Thanks!
