### ISSUE TITLE
After selecting upload file, "no uploads have been allowed" error occures.

### ISSUE THREAD

**Issue by pojiro** [phoenixframework/phoenix_live_view#1240]
### Environment

* Elixir version (elixir -v): 1.11.2
* Phoenix version (mix deps): 1.5.7
* Phoenix LiveView version (mix deps): 0.15.0
* NodeJS version (node -v): v14.15.1
* NPM version (npm -v): 6.14.8
* Operating system: Linux mint
* Browsers you attempted to reproduce this bug on (the more the merrier): chrome, version: 87.0.4280.66（Official Build） （64 bit）
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

I follow [the upload documentation](https://hexdocs.pm/phoenix_live_view/uploads.html) on LiveComponent (like https://www.phoenixframework.org/blog/phoenix-live-view-upload-deep-dive).

So I use allow_upload function on the component, but I select a file for uploading, GenServer is terminated by

```
** (ArgumentError) no uploads have been allowed
    (phoenix_live_view 0.15.0) lib/phoenix_live_view/upload.ex:165: Phoenix.LiveView.Upload.get_upload_by_ref!/2
    (phoenix_live_view 0.15.0) lib/phoenix_live_view/channel.ex:949: anonymous fn/3 in Phoenix.LiveView.Channel.maybe_update_uploads/2
    (stdlib 3.13.2) maps.erl:233: :maps.fold_1/3
    (phoenix_live_view 0.15.0) lib/phoenix_live_view/channel.ex:200: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 3.13.2) gen_server.erl:680: :gen_server.try_dispatch/4
    (stdlib 3.13.2) gen_server.erl:756: :gen_server.handle_msg/6
    (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

The code to reproduce the error is https://github.com/pojiro/live_view_upload_test .
The reproduction route is "/upload". Could you check it?

### Expected behaviour

The error should not occur.

**Comment by chrismccord** [comment]
You need to specify `phx-target="<%= @myself %>"` on the form in your `UploadComponent`. The validate (and save) events for the file/form events are going to the parent LiveView, where the upload is not allowed. Thanks!
