### ISSUE TITLE
Old docs version for 'live_title_tag' and 'static_change?'

### ISSUE THREAD

**Issue by PJport** [phoenixframework/phoenix_live_view#1243]
I'm updating my old LiveView pet project to the new  version and I believe the docs are still describing the old way not the new, at least when it comes to `live_title_tag assigns[:page_title]` and `<%= if assigns[:static_change] do %>`.
Programming is a hobby so I've never submitted a PR :)
If someone validates these maybe could submit a PR.
Thank you!

**Comment by josevalim** [comment]
Hi @PJport! Can you please tell us which docs? Otherwise we can't really assess if they are up to date or not. :)

**Comment by PJport** [comment]
In Modules - Phoenix.LiveView - Functions -` static_changed?/1`, it says that in our views we need to use: `<%= if @static_changed? do %>` but I thing it should be `@static_change` instead of `@static_changed?`.
For `live_title_tag` I believe it's not that the docs are wrong it's that in different places they use different values, for example, `@page_title`  (Guides - Updating the HTML document title section) and `assigns[:page_title]` (Guides - Installation - Layouts - `<%= live_title_tag assigns[:page_title] || "MyApp" %>`).
Maybe it would be useful the explain somewhere in the beginning of the guides that `@page_title` and `assigns[:page_title]` is the same (maybe listing other `@values`?
From my basic Elixir knowledge I would say these `@values` are Module constants declared by LiveView, but I remember when I started with Phoenix these `@values` seemed a little magic.
If this seem to basic or not making sense please ignore and close it :)

**Comment by josevalim** [comment]
Perfect feedback, thank you! :green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:
