### ISSUE TITLE
send_update from different pid

### ISSUE THREAD

**Issue by maennchen** [phoenixframework/phoenix_live_view#1244]
### Environment

* Elixir version (elixir -v): `1.11.2`
* Phoenix version (mix deps): `1.5.7`
* Phoenix LiveView version (mix deps): `0.15.0`
* NodeJS version (node -v): `12.18.3`
* NPM version (npm -v): `6.14.6`
* Operating system: `Ubuntu 20.04.1 LTS (Focal Fossa)`
* Browsers you attempted to reproduce this bug on (the more the merrier): Google Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

When using `send_update` from a different pid (for example in a `Task`), the update is delivered to the wrong pid. (Uses `send(self(), ...)` internally.)

### Expected behavior

Update arrives

### Possible Solutions

(I would provide a PR for any of those.)

* Allow to specify `pid` for `send_update`
* Allow to specify `socket` for `send_update` (`socket.root_pid`)

### Example Scenario (using [`surface`](https://github.com/msaraiva/surface))

<details>
  <summary>lock.ex</summary>

```elixir
defmodule AcmeWeb.Lock do
  @moduledoc """
  Lock Resource for Edit until a lock can be acquired
  """

  use AcmeWeb, :surface_live_component

  prop resource, :any, required: true

  slot default, required: true

  data lock_acquired, :boolean, default: false
  data lock_task, :module, default: nil

  @impl Phoenix.LiveComponent
  def update(%{__lock_acquired__: true} = _assigns, socket) do
    {:ok, assign(socket, lock_acquired: true)}
  end

  def update(assigns, socket) do
    socket =
      if not is_nil(socket.assigns.lock_task) do
        Task.shutdown(socket.assigns.lock_task)

        assign(socket, lock_task: nil)
      else
        socket
      end

    socket = assign(socket, assigns)

    socket =
      if socket.connected? do
        assign(socket,
          lock_task:
            Task.async(fn ->
              if :global.set_lock({socket.assigns.resource, socket.root_pid}) do
                send_update(socket, __MODULE__, id: socket.assigns.id, __lock_acquired__: true)

                # Max Lock Time
                Process.sleep(:timer.minutes(15))
              end
            end)
        )
      else
        socket
      end

    {:ok, socket}
  end

  @impl Phoenix.LiveComponent
  def render(assigns) do
    ~H"""
    <div>
      <slot
        :if={{ @lock_acquired }}
      />
      <div
        :if={{ not(@lock_acquired) }}
        class="alert alert-info"
      >
        <p>{{ gettext("Someone else is currently editing this resource. Wait until they finished their work.")}}</p>

        <div class="spinner-border" role="status">
          <span class="sr-only">{{ gettext("Acquiring Lock...") }}</span>
        </div>
      </div>
    </div>
    """
  end
end
```

</details>

<details>
  <summary>edit.sface</summary>

```twig
<AcmeWeb.Lock
  id={{ {:lock, Resource, @resource.uuid} }}
  resource={{ {Resource, @resource.uuid} }}
>
  <Form 
    for={{ @changeset }} 
    change="validate" 
    submit="save" 
    opts={{ autocomplete: "off", id: "resource-form" }}
  >
    ...
  </Form>
</AcmeWeb.Lock>
```
</details>

**Comment by chrismccord** [comment]
I will give this usecase some thought of providing a parent pid, but to get what you want, you need to send a message to the caller (or wait for the Task to finish and in the `handle_info` react to the result), then `send_update` from the LiveView process. Thanks!

**Comment by maennchen** [comment]
@chrismccord I could definitely do this in the `handle_info`. But this would also mean that I have to replicate that code into every live view that needs the locking behaviour instead of being able to provide it in an encapsulated component.

**Comment by chrismccord** [comment]
@maennchen I agree this would be nice to have. Can you send a PR that accepts the LV pid? Thanks!

**Comment by maennchen** [comment]
@chrismccord Sure, I'll open a PR tomorrow.

**Comment by maennchen** [comment]
@chrismccord Done (#1245)
