### ISSUE TITLE
Direct upload to S3: entry.error() not reporting any error

### ISSUE THREAD

**Issue by cblavier** [phoenixframework/phoenix_live_view#1250]
### Environment

* Elixir version (elixir -v): Elixir 1.11.1 (compiled with Erlang/OTP 22)
* Phoenix version (mix deps): 1.5.7
* Phoenix LiveView version (mix deps): 0.15.0
* NodeJS version (node -v): v12.12.0
* NPM version (npm -v): 6.14.5
* Operating system: Ubuntu
* Browsers you attempted to reproduce this bug on (the more the merrier):  chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

I'm using liveview to perform direct upload to S3.

The nominal case is working perfectly, but when trying error scenarios like a wrong S3 presigned url sent to browser:

- the http upload from JS fails
- then `entry.error()` is called
- we receive a `handle_progress/3` callback
- but there is nothing in the `UploadEntry` nor the `socket` that tells us the upload has actually failed.

```
%Phoenix.LiveView.UploadEntry{
  cancelled?: false,
  client_last_modified: nil,
  client_name: "tv.jpg",
  client_size: 39233,
  client_type: "image/jpeg",
  done?: false,
  preflighted?: false,
  progress: 0,
  ref: "0",
  upload_config: :photo,
  upload_ref: "phx-FkxM-P258XQEJZ2B",
  uuid: "6dac6658-0d77-430a-8663-f952aea057ea",
  valid?: true
}
```

Calling `entry.error("some message")` does not change anything. The message is lost to us

### Expected behavior

Receiving an `Phoenix.LiveView.UploadEntry` with an error flag? 
`valid?` false?

**Comment by chrismccord** [comment]
The upload errors will be populated with an `:external_client_failure` for the entry. You can read the errors by enumerating `@uploads.photo.errors`, which contains the entry ref and error information
