### ISSUE TITLE
Failed to execute 'readAsDataURL' on 'FileReader'

### ISSUE THREAD

**Issue by kuroda** [phoenixframework/phoenix_live_view#1251]
### Environment

* Elixir version (elixir -v): Elixir 1.11.2 (compiled with Erlang/OTP 23)
* Phoenix version (mix deps): 1.5.7
* Phoenix LiveView version (mix deps): 0.15.0
* NodeJS version (node -v): v12.20.0
* NPM version (npm -v): 6.14.8
* Operating system: Debian GNU/Linux 10
* Browsers you attempted to reproduce this bug on (the more the merrier): Google Chrome 87.0.4280.66
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

I am getting this eror from `phoenix_live_view.js`:

```
phoenix_live_view.js:586 Uncaught TypeError: Failed to execute 'readAsDataURL' on 'FileReader': parameter 1 is not of type 'Blob'.
    at Function.value (phoenix_live_view.js:586)
    at e.mounted (phoenix_live_view.js:556)
    at e.value (phoenix_live_view.js:3094)
    at eval (phoenix_live_view.js:2364)
    at eval (phoenix_live_view.js:1992)
    at Array.forEach (<anonymous>)
    at e.value (phoenix_live_view.js:1991)
    at eval (phoenix_live_view.js:2071)
    at Array.forEach (<anonymous>)
    at e.value (phoenix_live_view.js:2070)
```

I get this error when I do the following:

1. Show a form that includes a `live_file_input`.
2. Add an image file to this input on browser.
3. Hide that form without submitting the form.
4. Show again that form.

To _show_ and _hide_ the form, I use an HTML template like this:

```
<%= if @show_uploader do %>
  <form phx-submit="save" phx-change="validate">
    <%= live_file_input @uploads.avatar %>
    <button type="submit">Upload</button>
    <button type="button" phx-click-"close-uploader">Cancel</button>
  </form>
<% else %>
  <button type="button" phx-click-"open-uploader">Upload avatar</button>
<% end %>
```

and callbacks:

```
def handle_event("open-uploader", _params, socket) do
  {:noreply, update(socket, :show_uploader, fn _ -> true end}
end

def handle_event("close-uploader", _params, socket) do
  {:noreply, update(socket, :show_uploader, fn _ -> false end}
end
```

### Expected behavior

It should not emit such an error.

**Comment by chrismccord** [comment]
What is likely happening is one the form (and file input) is removed from the DOM, the reference to the user's file is gone, which is why we can't read it later. I think the only thing we can do in this case is throw away the user's selections. In the meantime, toggling `display: none` instead of toggling the DOM nodes should fix it

**Comment by kuroda** [comment]
@chrismccord

After some trial and error, my callbacks settled on something like this:

```elixir
def handle_event("open-uploader", _params, socket) do
  {:noreply, update(socket, :show_uploader, fn _ -> true end}
end

def handle_event("close-uploader", _params, socket) do
  {_completed, in_progress} = uploaded_entries(socket, :image)

  socket =
    Enum.reduce(in_progress, socket, fn entry, soc ->
      cancel_upload(soc, :image, entry.ref)
    end)

  {:noreply, update(socket, :show_uploader, fn _ -> false end}
end
```

At first, I tried toggling `display: none` as follows.

```html
<form phx-submit="save" phx-change="validate" 
  style="<%= if @show_uploader, do: "", else: "display: none" %>">
  <%= live_file_input @uploads.avatar %>
  <button type="submit">Upload</button>
  <button type="button" phx-click-"close-uploader">Cancel</button>
</form>
<button type="button" phx-click-"open-uploader"
  style="<%= if @show_uploader, do: "display: none", else: "" %>">Upload avatar</button>
```

It worked fine, but the entries in progress remained after I clicked the "Cancel" button and closed the form.

When I open the form again, an image is attached to the file input from the beginning, which is not I want.

What do you think of my solution?

**Comment by chrismccord** [comment]
Your solution is the way to go. I looked into this and you necessarily have to clean up after yourself if you are removing the form entirely form the DOM since we lose access to the users file reference, where meanwhile you have in progress entires on the server tracking those previously selected files. So the solution you gave is perfect in that you clean up your entries when you want to abandoned the form. Thanks!
