### ISSUE TITLE
Proposal: Support for multiple flash messages of the same type

### ISSUE THREAD

**Issue by mgibowski** [phoenixframework/phoenix_live_view#1254]
Currently LiveView inherits the limitation from Phoenix that on a page there could be only one flash message of some type at the time - function `live_flash/2` returns a single element. This is OK for regular server-side applications when sending a form will result in loading a new success page and in this scenario user would not make actions that result in two separate flash messages.

However, in typical SPA application it is common that flash messages are stored in a list, they appear as user does some actions on the page and disappear individually after some time out.

As far as I understand this type of UX is currently not possible with the built-in flash mechanism. It seems to me it would be good to have this option. WDYT?

**Comment by chrismccord** [comment]
A stored list should be implemented via regular assigns, where a flash is used for redirects w/ a message b/w live views and regular views. A "toast" style notification list can be as simple as updating an assign containing the list, and rendering the list in your LV.

**Comment by josevalim** [comment]
I am actually almost sure you can put whatever you want in flash... including a list. Or am I going crazy? What have you tried? Whenever you can, please fill in the issues template as it helps answers these questions.

But I agree with Chris that using assigns may work better here.

**Comment by mgibowski** [comment]
Thanks for comments!

> What have you tried?

At the moment I just settled with displaying a single notification. But if I decide to go ahead with toasts, I think I would just use assigns and custom hook events for clearing notifications - completely skipping built-in flash mechanism like Chris suggested.

I think storing a list inside of a message doesn't solve everything. Ideally each notification should disappear after some delay. As far as I understand, this is typically achieved by pushing an event "lv:clear-flash" from the client. But here the problem is that this event would clear the whole list at the same time...

> Whenever you can, please fill in the issues template as it helps answers these questions.

Sorry about that, I misunderstood the template is only for bugs and not necessary for other kind of issues.

**Comment by mgibowski** [comment]
Actually, José, you are right. This could be achieved by storing a list in a message. Just that cleaning particular message would need to be handled on the server after some delay. It is not necessary to use "lv:clear-flash" for that... Thanks!
