### ISSUE TITLE
Scroll restoration broken for native browser navigation

### ISSUE THREAD

**Issue by almielczarek** [phoenixframework/phoenix_live_view#1255]
### Environment

* Elixir version (elixir -v): 1.11.2
* Phoenix version (mix deps): 1.5.7
* Phoenix LiveView version (mix deps): 1.15
* NodeJS version (node -v): 12.19.0
* NPM version (npm -v): 6.14.8
* Operating system: NixOS
* Browsers you attempted to reproduce this bug on (the more the merrier): Chromium 87.0.4280.66 (Official Build) (64-bit)
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

When navigating away from a live view page via a normal anchor tag, scroll position is lost when using the browser's back button.

### Expected behavior

Scroll position should be maintained when using native navigation such as anchor tags.

### Possible solution

It looks like removing this line fixes my issue, but may cause issues for another use case I'm not thinking of: https://github.com/phoenixframework/phoenix_live_view/blob/e330343c5652ca83357fd05a3b9962ae3f9fe35b/assets/js/phoenix_live_view.js#L1122

Anyway, I'll open a PR. If it so happens that this will break others' code I'll be happy to help work on another solution.

**Comment by josevalim** [comment]
Closing in favor of PR. :)
