### ISSUE TITLE
live view not working with phoenix framework 1.4.2 

### ISSUE THREAD

**Issue by jimminababan** [phoenixframework/phoenix_live_view#126]
It seems, I need to downgrade the phoenix version to 1.4 to make it work.
I got error, 

Dependencies have diverged:
* phoenix (Hex package)
  the dependency phoenix in mix.exs is overriding a child dependency:

  > In mix.exs:
    {:phoenix, "~> 1.4.2", [env: :prod, repo: "hexpm", hex: "phoenix"]}

  > In deps/phoenix_live_view/mix.exs:
    {:phoenix, [env: :prod, git: "https://github.com/phoenixframework/phoenix.git", branch: "v1.4"]}

  Ensure they match or specify one of the above in your deps and set "override: true"
** (Mix) Can't continue due to errors on dependencies

**Comment by 50kudos** [comment]
> you need to `{:phoenix, github: "phoenixframework/phoenix", branch: "v1.4", override: true}`

By Chris: https://github.com/phoenixframework/phoenix_live_view/commit/dfc0e93d79f20d383d0ae5f92a634dbd512dcf60#r32890613

**Comment by josevalim** [comment]
Actually, let's leave it open for guidance.

**Comment by jimminababan** [comment]
yes, you are right, thank you.

So this is the solution for anyone use phoenix 1.4.2, make sure your phoenix dependencies written like this (file : mix.exs): 

      {:phoenix, "~> 1.4.0", override: true},

**Comment by josevalim** [comment]
It is actually better to depend on git, because it has important fixes on phoenix.js:

    {:phoenix, github: "phoenixframework/phoenix", branch: "v1.4", override: true}

**Comment by chrismccord** [comment]
Now that Phoenix 1.4.3 is out, this shouldn't be an issue and folks with `{:phoenix, "~> 1.4.x"}` will be all set :)
