### ISSUE TITLE
LiveViewTest: live_patch relative link not found in router

### ISSUE THREAD

**Issue by Softknobs** [phoenixframework/phoenix_live_view#1260]
### Environment

* Elixir version (elixir -v): 1.9.2
* Phoenix version (mix deps): 1.5.7
* Phoenix LiveView version (mix deps): 0.15.0
* NodeJS version (node -v): 12.13.0
* NPM version (npm -v): 6.12.0
* Operating system: Win 10 Pro 64 bits
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:

### Actual behavior

An error is thrown when triggering a live_patch with a relative path:

leex:
```
<%= live_patch to: "../items", class: "self-center", id: "items_view_back" do %>
```
when current path is, for example:
```
/me/appliances/model1/name1/items/123
```
and router.ex definition is:
```
  scope "/me", MyAppWeb do
    pipe_through :authenticated
    live "/appliances/:model/:name/items/:item", Me.MyAppLive, :item
  end
```
With the above code, valid `<a>` links are generated and functional within the LiveView with a "handle_params" callback. When using the application from the browser the link patches the view from `/me/appliances/model1/name1/items/123` to `/me/appliances/model1/name1/items` with no problem.

However, testing this with, for example (the same as above but within a test):
```
{:ok, view, html} = live(conn, "/me/appliances/model1/name1/items/123")
view
    |> element("#items_view_back")
    |> render_click
```
produces the following error:

```
 ** (ArgumentError) cannot invoke handle_params nor live_redirect/live_patch to "../items" because it isn't defined in MyAppWeb.Router
      (phoenix_live_view) lib/phoenix_live_view/utils.ex:287: Phoenix.LiveView.Utils.live_link_info!/3
      (phoenix_live_view) lib/phoenix_live_view/channel.ex:106: Phoenix.LiveView.Channel.handle_info/2
```

Changing the live_patch with a path that starts from the root works, for example:
```
<%= live_patch to: "/appliances/model1/name1/items", class: "self-center", id: "items_view_back" do %>
```
which  suggests the router configuration is correct.

### Expected behavior

It should be possible to test leex files with a`live_patch` containing a relative link.

**Comment by chrismccord** [comment]
Relative paths is nothing something that we currently support. You'll need to pass the entire path. Thanks!
