### ISSUE TITLE
LiveView + AlpineJS: Socket is always false and LiveView Process is unreachable

### ISSUE THREAD

**Issue by iToXiQ** [phoenixframework/phoenix_live_view#1262]
### Environment

* Elixir version (elixir -v): 1.11.2 
* Phoenix version (mix deps): 1.5.7 / 1.5.3
* Phoenix LiveView version (mix deps): 0.15.0 
* NodeJS version (node -v): 0.15.0 
* NPM version (npm -v): v14.8.0
* Operating system: macOS Big Sur 11.0
* Browsers you attempted to reproduce this bug on (the more the merrier): Safari , Google Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: 

### Installation Steps (http://blog.pthompson.org/liveview-tailwind-css-alpine-js-modal)

1. installed Alpinejs via "npm i alpinejs"
2. required "alpinejs" in app.js
3. modified the liveSocket in app.js to `let liveSocket = new LiveSocket("/live", Socket, {
  dom: {
    onBeforeElUpdated(from, to) {
      if (from.__x) {
        window.Alpine.clone(from.__x, to);
      }
    },
  },
  params: {
    _csrf_token: csrfToken,
  },
  hooks: Hooks,
});`

### Actual behavior

1. connected?(@socket) always returns false
2. It is not possible to send Messages to a running LiveView Process ( Process.send() or :timer.send_interval() ) or they aren't receiving the messages with handle_info()

This occurs only while the "let liveSocket" is modified. But the modifications is kinda needed elsewise alpine isn't working correctly inside LiveView.

### Expected behavior

Expected behavior would have been to communicate with the LiveView via Process.send()

Maybe im just trying to combine things that shouldn't be combined, but if anyone has a clue or fix for my issue I would be very grateful.

Thanks in advance

iToXiQ

**Comment by josevalim** [comment]
Hi @iToXiQ! It is hard to say what is wrong without a way to reproduce the issue. It seems this is more of a setup issue than a LiveView bug, so I would recommend going to ElixirForum or StackOverflow for more help. :) Thanks and good luck!
