### ISSUE TITLE
proposal: support custom form elements

### ISSUE THREAD

**Issue by dvic** [phoenixframework/phoenix_live_view#1264]
Are there any plans/thoughts on supporting `phx-submit` with inputs that are in the shadow dom (e.g., when using a web components framework like https://github.com/material-components/material-components-web-components)? If so, I could definitely work on this. If not, are there any best practices to tackle this problem? Did others encounter this problem?

**Comment by dvic** [comment]
I have investigated a bit and it seems that for my usecase (using the Material web component `mwc-textfield`) it would be enough to be able to configure the elements that are considered "inputs":

https://github.com/phoenixframework/phoenix_live_view/blob/5eae7ed93e29fa00b695b7e063f2426d63861f29/assets/js/phoenix_live_view.js#L2699 

If I could configure to have `mwc-textfield` included in this list, I think this would solve my problem. Thoughts? Is this configuration option something that would be considered adding to Liveview?

**Comment by dvic** [comment]
For anyone that's interested, I've come up with a solution: https://github.com/qdentity/phoenix_live_view/pull/1/files. Basically I can now do this:
![image](https://user-images.githubusercontent.com/1214337/102012639-d7f60c00-3d4b-11eb-8370-fc526df5da68.png)

and my `mwc-textfield` components work like inputs (i.e., they are taking into account on form submit and they trigger form change events).

If there's any interest I'm happy to open a PR.

**Comment by chrismccord** [comment]
your best route today is to populate a regular/hidden input and use `dispatchEvent(new Event("submit", {bubbles: true})` as required. Thanks!
