### ISSUE TITLE
LiveViewTest.file_input crashes with exit of UploadClient

### ISSUE THREAD

**Issue by mveytsman** [phoenixframework/phoenix_live_view#1269]
### Environment

* Elixir version (elixir -v): 1.11.2
* Phoenix version (mix deps): 1.5.7
* Phoenix LiveView version (mix deps): 0.15.0
* NodeJS version (node -v): N/A
* NPM version (npm -v) N/A
* Operating system: Linux
* Browsers you attempted to reproduce this bug on (the more the merrier): N/A
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: N/A

### Actual behavior

I've found that any LiveView test that exercises a file input and consumes the entries will crash when the `ClienProxy` process which is linked to the test, exits.

here's a test (using the setup from test/phoenix_live_view/upload_channel_test.exs) demonstrating the issue:

```elixir
      @tag allow: [accept: :any]
      test "client_proxy dies :(",
           %{lv: lv} do
        Process.flag(:trap_exit, true)
        avatar = file_input(lv, "form", :avatar, [%{name: "foo.jpeg", content: "123"}])
        assert render_upload(avatar, "foo.jpeg") =~ "100%"
        UploadLive.run(lv, fn socket ->
          Phoenix.LiveView.consume_uploaded_entries(socket, :avatar, fn _,_ -> end)

          {:reply, :ok, socket}
        end)

        proxy_pid = UploadLive.proxy_pid(lv)
        assert_receive {:EXIT, proxy_pid, {:shutdown, :closed}}

        assert render(lv)
      end
```

If we didn't have the trap exit there, running the test would fail with an angry message:
```
 ** (EXIT from #PID<0.254.0>) shutdown: :closed
``

**Comment by josevalim** [comment]
Thanks for the report!

Are you sure the proxy_pid is the one crashing? Add the pin operator on assert_receive to confirm.

It feels more like the upload channel itself terminates and that brings the test process down?

**Comment by mveytsman** [comment]
@josevalim you're absolutely right it's the upload channel! Thanks for spotting the bug in my test, I still make the mistake of forgetting to pin in pattern matches a lot :joy: 

Here's the fixed lines:

```elixir
upload_pid = avatar.pid
assert_receive {:EXIT, ^upload_pid, {:shutdown, :closed}}
```

One more thing to note, I can't reliably reproduce this, but I also have been seeing messages about an unhandled info for `:garbage_collect` from the upload client... Could be related?

**Comment by mveytsman** [comment]
Does this mean the solution is as simple as using `start` instead of `start_link` for the UploadClient?

**Comment by josevalim** [comment]
> @josevalim you're absolutely right it's the upload channel! Thanks for spotting the bug in my test, I still make the mistake of forgetting to pin in pattern matches a lot 😂

Elixir v1.11 warns on it btw. :)

> Does this mean the solution is as simple as using start instead of start_link for the UploadClient? Or do we need supervision?

I haven't looked into the code but I can do that if you need more input. Here is what I would do:

1. See how we start the ClientProxy
2. See how we start each liveview (as they are also channels and also linked)

Each test has a supervisor and we could start under it. Maybe we do it for one of the two above. :)

**Comment by mveytsman** [comment]
Closed in https://github.com/phoenixframework/phoenix_live_view/pull/1270
