### ISSUE TITLE
Form values, live_action, and current URL are reset after reconnection following a server restart

### ISSUE THREAD

**Issue by rosswilson** [phoenixframework/phoenix_live_view#1273]
### Environment

* Elixir version (elixir -v): `Elixir 1.11.2 (compiled with Erlang/OTP 23)`
* Phoenix version (mix deps): `1.5.7`
* Phoenix LiveView version (mix deps): `0.15.0`
* NodeJS version (node -v): `v15.4.0`
* NPM version (npm -v): `7.0.15`
* Operating system: Mac 10.15.7
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, Safari, and Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

I've prepared a small Live View project using `mix phx.gen.live`: https://github.com/rosswilson/chirp-recovery-bug that exhibits this issue.

Navigate to http://localhost:4000/posts/new where the modal is shown. Enter some text into the form Body field. Now quit the server (ctrl + c). Click somewhere within the modal (e.g. the form label) whilst the server is disconnected. Now restart the server.

Sometimes the modal is closed, the page stays on the `http://localhost:4000/posts/new` URL, but page _appears_ like its actually on the http://localhost:4000/posts index route.

When this happens I captured the following logs:

```
[info] Running ChirpWeb.Endpoint with cowboy 2.8.0 at 0.0.0.0:4000 (http)
[info] Access ChirpWeb.Endpoint at http://localhost:4000

webpack is watching the files…

[hardsource:6575fc37] Using 1 MB of disk space.
[hardsource:6575fc37] Tracking node dependencies with: package-lock.json.
[hardsource:6575fc37] Reading from cache 6575fc37...
Hash: 80e97a9102047a189b28
Version: webpack 4.41.5
Time: 191ms
Built at: 15/12/2020 16:22:16
                Asset       Size  Chunks             Chunk Names
       ../css/app.css   12.9 KiB     app  [emitted]  app
       ../favicon.ico   1.23 KiB          [emitted]  
../images/phoenix.png   13.6 KiB          [emitted]  
        ../robots.txt  202 bytes          [emitted]  
               app.js    360 KiB     app  [emitted]  app
Entrypoint app = ../css/app.css app.js
[0] multi ./js/app.js 28 bytes {app} [built]
    + 9 hidden modules
[info] CONNECTED TO Phoenix.LiveView.Socket in 88µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Parameters: %{"_csrf_token" => "PA1UNBdvZ0cRVwwjAXNhAC0FJyAKPH4nJBevgXQjyztveB24XWIp3P1s", "_mounts" => "3", "vsn" => "2.0.0"}
PostLive.Index mount assigns: %{flash: %{}, live_action: :new}
[debug] QUERY OK source="posts" db=2.7ms decode=3.0ms queue=1.2ms idle=410.1ms
SELECT p0."id", p0."body", p0."inserted_at", p0."updated_at" FROM "posts" AS p0 []
PostLive.Index handle_params assigns: %{flash: %{}, live_action: :new, posts: []}
PostLive.Index handle_params assigns: %{flash: %{}, live_action: :index, page_title: "New Post", post: %Chirp.Timeline.Post{__meta__: #Ecto.Schema.Metadata<:built, "posts">, body: nil, id: nil, inserted_at: nil, updated_at: nil}, posts: []}
FormComponent handle_event: validate, params: %{"body" => "ross wilson"}, assigns: %{action: :new, changeset: #Ecto.Changeset<action: nil, changes: %{}, errors: [body: {"can't be blank", [validation: :required]}], data: #Chirp.Timeline.Post<>, valid?: false>, flash: %{}, id: :new, myself: %Phoenix.LiveComponent.CID{cid: 2}, post: %Chirp.Timeline.Post{__meta__: #Ecto.Schema.Metadata<:built, "posts">, body: nil, id: nil, inserted_at: nil, updated_at: nil}, return_to: "/posts", title: "New Post"}
```

I think these three lines are interesting:

```
PostLive.Index handle_params assigns: %{flash: %{}, live_action: :new, posts: []}
PostLive.Index handle_params assigns: %{flash: %{}, live_action: :index, page_title: "New Post", post: %Chirp.Timeline.Post{__meta__: #Ecto.Schema.Metadata<:built, "posts">, body: nil, id: nil, inserted_at: nil, updated_at: nil}, posts: []}
FormComponent handle_event: validate, params: %{"body" => "ross wilson"}, assigns: %{action: :new, changeset: #Ecto.Changeset<action: nil, changes: %{}, errors: [body: {"can't be blank", [validation: :required]}], data: #Chirp.Timeline.Post<>, valid?: false>, flash: %{}, id: :new, myself: %Phoenix.LiveComponent.CID{cid: 2}, post: %Chirp.Timeline.Post{__meta__: #Ecto.Schema.Metadata<:built, "posts">, body: nil, id: nil, inserted_at: nil, updated_at: nil}, return_to: "/posts", title: "New Post"}

```

Upon server restart and the client-side reconnecting, the `handle_params` function was called with `live_action: :new` (expected). But then it's called again with `live_action: :index`. Finally, a `validate` is received by `handle_event`.

I've disabled code reloading and `phx-track-static` static file tracking.

### Expected behavior

Upon client reconnect after a server restart the modal should remain, with the form field values restored. I can see the client resending the `validate` event (part of the automatic form recovery mechanism).

Please do let me know how I can help debug this, I'm keen to help wherever I can.

**Comment by josevalim** [comment]
Hi @rosswilson, thanks for the report!

> Sometimes the modal is closed, the page stays on the http://localhost:4000/posts/new URL, but page appears like its actually on the http://localhost:4000/posts index route.

Do you mean sometimes the model is closed but sometimes it works as you expect? I am trying to understand what sometimes qualifies because, depend on it, it may actually be a race condition.

Can you please include the logs of what happens if you run with `liveSocket.enableDebug()` in your browser console?

**Comment by rosswilson** [comment]
> Do you mean sometimes the model is closed but sometimes it works as you expect?

Hey @josevalim, I could've been clearer there. Almost always though the modal is closed and the URL changes to http://localhost:4000/posts, when this happens I see the following two server logs:

```
PostLive.Index handle_params assigns: %{flash: %{}, live_action: :new, posts: []}
PostLive.Index handle_params assigns: %{flash: %{}, live_action: :index, page_title: "New Post", post: %Chirp.Timeline.Post{__meta__: #Ecto.Schema.Metadata<:built, "posts">, body: nil, id: nil, inserted_at: nil, updated_at: nil}, posts: []}
PostLive.Index handle_params assigns: %{flash: %{}, live_action: :index, page_title: "Listing Posts", post: nil, posts: []}
PostLive.Index handle_params assigns: %{flash: %{}, live_action: :index, page_title: "Listing Posts", post: nil, posts: []}
```

I clicked the New Post link, the modal showed and the URL changed to `/posts/new`. I entered a character in the `body` field, quit the server, clicked within the modal area, then restarted the server. The URL changed back to `/posts` and the modal disappeared. If I don't click within the modal when the server was quit then the form recovery mechanism works as expected (e.g. nothing changes in the UI).

This is what I captured from the browser side:

<img width="1240" alt="Screenshot 2020-12-15 at 19 00 55" src="https://user-images.githubusercontent.com/1176711/102260262-2223ec80-3f08-11eb-8cc1-daeb7f8d0711.png">

Unfortunately the `{c:{...}}` records are empty, probably related to them only being evaluated once expanded in the dev tools console.

In addition, then there's the issue where sometimes the URL will remain set to http://localhost:4000/posts/new. The modal has closed and the page title updated to Listing Posts but the URL didn't update. Unlike the above behaviour (where the URL _does_ change, yet still unexpectedly) this one is harder to reproduce.

**Comment by chrismccord** [comment]
Can you comment out the live reloader in your endpoint and retry? It doesn't explain the URL changing, but I want to rule out the page hard refreshing because of live reload making it seem like this is a LV bug, when it's just the live reloading telling the page to refresh. Webpack builds the bundles as soon as the endpoint boots, which will trigger a live reload. Let's start there. thanks!

**Comment by mveytsman** [comment]
The culprit is `phx-capture-click="close"` in the modal. 

The default CSS has 
```css
.phx-disconnected *{
  pointer-events: none;
}
```

this results in all click events inside the modal targeting the main container instead, and bubbling down to trigger closing the modal.

**Comment by rosswilson** [comment]
Thanks @mveytsman, that makes sense. I wonder if that's also related to the issue where the page URL remains at `/posts/new` - when I'm clicking _somewhere_ in the modal, perhaps I'm actually clicking through to the New Post link below the modal.
