### ISSUE TITLE
Do not wrap live template with own container

### ISSUE THREAD

**Issue by sntran** [phoenixframework/phoenix_live_view#128]
### Environment

* Elixir version (elixir -v): 1.7.4
* Phoenix version (mix deps): 1.4 branch
* NodeJS version (node -v): 10.13.0
* NPM version (npm -v): 6.4.1
* Operating system: macOS Mojave

### Actual behavior

When rendering a live view, the content of the template is wrapped with:

```html
<div
  id="phx-20gvOvqvFMA="
  data-phx-view="MyApp.MyLiveView"
  data-phx-session="SFMyNTY.g3QAAAACZAAEZGF0YW0AAACQZzNRQUFBQUVaQUFDYVdS">
  ...
</div>
```

While this is normal to have a mount point like this, in certain case, it breaks the HTML schematic.

For example, when the live view template is an `<aside>` inside the `<main>` element, when wrapped with `<div>`, the schematic is not accurate any more.

### Expected behavior

While removing the wrapper is not possible, it would be better if the user can specify the mount point. In my example, if I can tell Phoenix LiveView to use my `<aside>` instead of wrapping it, it will work for both LiveView and my schematic.

**Comment by sionide21** [comment]
What if a LiveView provided a callback to specify a tagname that defaults to `div`?

Then it could look something like:

```
defmodule MyLiveView do

  def tagname(), do: "aside"

  ...
end
```

and the template could change to

```
~L"""
  <main>
     <%= live_render(@socket, MyLiveView) %>
  </main>
"""
```
