### ISSUE TITLE
phx-no-feedback class not applied when page is live-patched

### ISSUE THREAD

**Issue by iwarshak** [phoenixframework/phoenix_live_view#1282]
### Environment

* Elixir version (elixir -v): Erlang/OTP 22 [erts-10.5.3] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]
Elixir 1.11.2 (compiled with Erlang/OTP 21)
* Phoenix version (mix deps): 1.5.7
* Phoenix LiveView version (mix deps): 0.15.0
* NodeJS version (node -v): v14.15.1
* NPM version (npm -v): 6.14.8
* Operating system: OSX
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:

### Actual behavior

When navigating to a form (via live_patch) which has an input with `phx_feedback_for: input_id(f, :name)`, the `phx-no-feedback` is *not* applied. 

But if you refresh this page, or do a normal `link` to it (or manually navigate to the page), the `phx-no-feedback` *IS* applied. 

This leads to unpredictable behavior if you are applying styles to these form elements.

I have a repo which you can use to see this quickly. https://github.com/iwarshak/phx-no-feedback-bug

1) visit http://localhost:3999/users
2) click the 'New User' link, and notice that the name field doesn't have the `phx-no-feedback` class
3) refresh this page and see that now it does have the `phx-no-feedback` class

**Comment by mveytsman** [comment]
@iwarshak thanks for the report! I can confirm that this is an issue -- I think it has to do with how the `discardError` method is called during morphdom patching - when patching it seems to only be called on the modal and not it's children while in a full mount it is called on every child.

I think this has something to do with it's use in `onBeforeNodeAdded` and `onBeforeElUpdated`, and the way morphdom traverses the tree...

**Comment by iwarshak** [comment]
@mveytsman Yes, I tracked it down to it: `onBeforeNodeAdded` gets called for the outer div containing the input, but it doesn't recurse into the contents of that div - which is I think similar to what you are saying

**Comment by chrismccord** [comment]
@mcrumm remind me, did we dig into this and fix this already or something related but different?

**Comment by chrismccord** [comment]
Derp, I see we reference this as closed. All fixed! ❤️❤️❤️🐥🔥
