### ISSUE TITLE
Proposal: allow live_component inside code block

### ISSUE THREAD

**Issue by torepettersen** [phoenixframework/phoenix_live_view#1287]
I wanted to create a modal with a searchable select dropdown inside it. The modal can be quite simple and only needs one argument, open or not. The select dropdown is a bit more complex and needs to be able to call the server on input, so I decided to make a live component for that. 

Simplified version:
```
<%= modal(open: true) do %>
  <%= live_component @socket, SearchSelectComponent %>
<% end %>
```

This throws the error: cannot convert component MyApplication.SearchSelectComponent with id :some_id to HTML.

Allowing this would make `live_componets` more useful, although I assume it might be complex since it is not already allowed.

**Comment by josevalim** [comment]
Unfortunately the limitations that make this hard to implement are intrinsic to how the current .leex engine works. We are working on removing those limitations, so it will be possible in the future, but it may take a while.

**Comment by torepettersen** [comment]
Thanks for the quick reply and the great work you are putting into Elixir and Phoneix :slightly_smiling_face:
