### ISSUE TITLE
Passing custom id attribute to live_file_input breaks the Javascript

### ISSUE THREAD

**Issue by plicjo** [phoenixframework/phoenix_live_view#1292]
### Environment

* Elixir version (elixir -v): 1.11.2
* Phoenix version (mix deps): 1.5.7
* Phoenix LiveView version (mix deps): 0.15.1
* NodeJS version (node -v): 14.15.2
* NPM version (npm -v): 6.14.10
* Operating system: Mac OS Catalina
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

Adding an `id` attribute on an out-of-the-box implementation of Live View Uploads to `live_file_input` causes the frontend to fail:

`<%= live_file_input @uploads.photo, id: "foo" %>` Fails with the following:
![Screen Shot 2020-12-23 at 3 55 48 PM](https://user-images.githubusercontent.com/7145362/103036267-5a927e80-4537-11eb-9962-ad29664b14f4.png)

`<%= live_file_input @uploads.photo %>` Works like a charm

### Expected behavior

You should be able to add an `id` attribute to the `options` list.
Notably, adding custom classes works just fine.

**Comment by chrismccord** [comment]
Thanks for the report! The id cannot be overridden as we must be able to find it based on the uploads information. We now raise if the is provided. Thanks!
