### ISSUE TITLE
form change event not fired after the first reconnect following a netsplit

### ISSUE THREAD

**Issue by sasa1977** [phoenixframework/phoenix_live_view#1294]
### Environment

* Elixir version: 1.11.2
* Phoenix version: 1.5.7
* Phoenix LiveView version: 0.15.1
* NodeJS version (node -v): 15.5.0
* NPM version (npm -v): 7.3.0
* Operating system: Ubuntu
* Browsers you attempted to reproduce this bug on (the more the merrier):  Firefox, Chromium
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

When I define a form with `phx-change="change"`, the change event is not fired after the first reconnect following a netsplit. Consequently, the form state is reset. The event is fired on subsequent reconnects, as long as the page is not refreshed.

I've also tried stopping/starting the server (turning off the `:code_reloader` option in dev.exs), and the behaviour is the same. Setting a custom `phx-auto-recover` also leads to the same behaviour (the recover event is not fired on first reconnect).

You can find the reproducable example [here](https://github.com/sasa1977/live_test), with instructions explained in the [readme](https://github.com/sasa1977/live_test#livetest), and the relevant code (LV + leex) residing in [lib/live_test_web/live](https://github.com/sasa1977/live_test/tree/develop/lib/live_test_web/live).

### Expected behavior

I expect the change event to be fired after every reconnect.

**Comment by chrismccord** [comment]
Thanks for the report Saša! Can you confirm the behaviour with a true network failure. The reproduction steps include calling `socket.disconnect()` and then socket.connect()`, which is a "clean" disconnect. We only recover when there is a failure on the socket. Calling disconnect yourself is not treated as a failure, so I need more info on whether you can trigger such a scenario on a failed websocket connection. Thanks!

**Comment by sasa1977** [comment]
Stopping/starting the server (`:code_reloader` is set to false in dev.exs) leads to the same behaviour: no change event after first restart and the form state is cleared, change event fired on subsequent restarts and the form state is preserved. Is that good enough?

**Comment by chrismccord** [comment]
Fixed in 0.15.2. Thanks!
