### ISSUE TITLE
open_browser doesn't display static paths when they are prefixed

### ISSUE THREAD

**Issue by mveytsman** [phoenixframework/phoenix_live_view#1295]
I hit a bug with our implementation of https://github.com/phoenixframework/phoenix_live_view/pull/1280

My endpoint in config.exs is configured with: `static_url: [path: "/static"]`

When I use `open_browser` in tests, it gives me this for my app.css: `file:///path/to/my/static/static/css/app.css` whereas I expect `file:///path/to/my/static/css/app.css`.

I ended up updating my test endpoint config to have `static_url: [path: "/"]` to work around this.

Am I right that `prefix_static_path` should delete the path you configured in your endpoint when building the static path? cc @mcrumm @leandrocp

**Comment by leandrocp** [comment]
@mveytsman thanks for reporting this bug, I believe the solution would be https://github.com/phoenixframework/phoenix_live_view/pull/1308. And in your test you probably could just remove the `static_url` config.

**Comment by mcrumm** [comment]
Good catch @mveytsman, and thank you for the fix @leandrocp! :)
