### ISSUE TITLE
Create Two Channel When using Live_render

### ISSUE THREAD

**Issue by leeduckgo** [phoenixframework/phoenix_live_view#1298]
### Environment

* Elixir version (elixir -v):
Elixir 1.9.1
* Phoenix version (mix deps):
phoenix 1.5.6
* Phoenix LiveView version (mix deps):
phoenix_live_view 0.15.0-dev
* NodeJS version (node -v):
v12.10.0
* NPM version (npm -v):
6.10.3
* Operating system:
Mac)S
* Browsers you attempted to reproduce this bug on (the more the merrier): 
Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:
Yes
### Actual behavior
```
  <%= if Plug.Conn.get_session(@conn, :current_user_id) do %>
    <%= live_render(@conn, SuperIssuerWeb.EvidencerLive) %>
  <% end %>
```
Using live_render() in .eex has created two LiveView.Channel and every action behaviour twice.
![image](https://user-images.githubusercontent.com/12784118/103476341-a5da4600-4def-11eb-9e28-761220c98d35.png)

### Expected behavior

Create only one Channel.

**Comment by josevalim** [comment]
If you remove the live_render, do you still have a channel? I believe the extra channel comes from “live_reload” and not LiveView.

**Comment by leeduckgo** [comment]
how can I disable the live_reload……I try it but not working.

**Comment by leeduckgo** [comment]
```
  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  # if code_reloading? do
  #   # socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
  #   # plug Phoenix.LiveReloader
  #   # plug Phoenix.CodeReloader
  #   plug Phoenix.Ecto.CheckRepoStatus, otp_app: :super_issuer
  # end
```

**Comment by leeduckgo** [comment]
I think that the reason is not the live_load because It's also happened in the prod env
