### ISSUE TITLE
Create Two Channel When using Live_render

### ISSUE THREAD

**Issue by leeduckgo** [phoenixframework/phoenix_live_view#1299]
https://github.com/phoenixframework/phoenix_live_view/issues/1298

It's not the problem of live_reload, because the problem is also happened in the prod env

**Comment by chrismccord** [comment]
can you verify you aren't double binding/executing your javascript which connections to LV? Easy check would be to console.log a message where you call `liveSocket.connect()`. Failing that, an example application which reproduces the issue would be helpful. Thanks!

**Comment by leeduckgo** [comment]
copy files to a new proj and it's oky now……
