### ISSUE TITLE
Impossible to use phx-blur with a changeset

### ISSUE THREAD

**Issue by nicolasblanco** [phoenixframework/phoenix_live_view#130]
Hello,

right now it looks like it's quite complicated or maybe not really possible to use a `form_for` with a single `changeset` and use `phx-blur` on single inputs to trigger validation errors. 

### Environment

* Elixir version (elixir -v): 1.8.1
* Phoenix version (mix deps): 1.4.2 master
* NodeJS version (node -v): 10.15.3
* NPM version (npm -v):
* Operating system: OS X

### Actual behavior

The `phx-blur` event is only receiving the single value of the input, so if you make a change on the changeset, you may lose the value of other inputs that are maybe not inside the changeset already.

### Expected behavior

It looks like we would need to be able to set `phx-blur` on the `form` directly. It would then binds a blur event on all inputs like `phx-change`.
This way it would be possible to have kind of the same code as using `phx-change` with a single function that would receive the whole form params each time a form input is losing the focus.

What do you think?

**Comment by chrismccord** [comment]
This usecase will be handle with `phx-debounce="blur"` inside the form, when #4 lands . Thanks!

**Comment by nicolasblanco** [comment]
@chrismccord : OK.
So just to understand, the `phx-blur` attribute is not meant to be used in a form attached to a changeset right?
Thanks.

**Comment by nicolasblanco** [comment]
I think I understand now the relationship with the future `phx-debounce` attribute which was not clear in my mind... Basically it looks like it will be possible to also trigger validation of the form after a certain amount of time has passed after the latest keystroke or change...

**Comment by brundozer** [comment]
> I think I understand now the relationship with the future `phx-debounce` attribute which was not clear in my mind... Basically it looks like it will be possible to also trigger validation of the form after a certain amount of time has passed after the latest keystroke or change...

With `phx-debounce="blur"`, validation will be triggered when the field loses the focus.
