### ISSUE TITLE
Connection issues on Firefox

### ISSUE THREAD

**Issue by Nicd** [phoenixframework/phoenix_live_view#1305]
### Environment

* Elixir version (elixir -v): 1.11
* Phoenix version (mix deps): 1.5.7
* Phoenix LiveView version (mix deps): 0.15.3
* NodeJS version (node -v): 12.13.0
* NPM version (npm -v): 6.12.1
* Operating system: macOS 10.14.6
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox 84.0.1, Chrome 87
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

In an empty new LV project (`mix phx.new test_app --live --no-ecto`), Firefox is unable to connect to LV for possibly tens of seconds. Sometimes it connects immediately, but many times it takes multiple failed connections until a connection is made. After that, the connection is made and everything is normal.

In Chrome this does not occur, the connection is made straight away.

The only hint is that the Firefox dev console spams errors:

```
Firefox can’t establish a connection to the server at ws://localhost:4000/live/websocket?_csrf_token=AzpBGSkjWgJ_cywIYXwLPCMLLA0YPkJFqq5wBj6p19fiW9htRGuznYzq&_track_static%5B0%5D=http%3A%2F%2Flocalhost%3A4000%2Fcss%2Fapp.css&_track_static%5B1%5D=http%3A%2F%2Flocalhost%3A4000%2Fjs%2Fapp.js&_mounts=0&vsn=2.0.0.
The connection to ws://localhost:4000/live/websocket?_csrf_token=AzpBGSkjWgJ_cywIYXwLPCMLLA0YPkJFqq5wBj6p19fiW9htRGuznYzq&_track_static%5B0%5D=http%3A%2F%2Flocalhost%3A4000%2Fcss%2Fapp.css&_track_static%5B1%5D=http%3A%2F%2Flocalhost%3A4000%2Fjs%2Fapp.js&_mounts=0&vsn=2.0.0 was interrupted while the page was loading.
```

In the terminal, no error is shown. GET requests are shown until the connection is made, then a single "CONNECTED TO" is logged.

Screenshots:

<img width="1215" alt="Screenshot 2021-01-05 at 22 56 12" src="https://user-images.githubusercontent.com/273137/103699549-c9e28680-4fab-11eb-88fb-e9417de8a4c7.png">

<img width="1252" alt="Screenshot 2021-01-05 at 22 55 58" src="https://user-images.githubusercontent.com/273137/103699571-d23ac180-4fab-11eb-94f6-d5ade65726f7.png">

### Expected behavior

Connection working normally like in Chrome.

**Comment by chrismccord** [comment]
We need more information to say what is happening here, but I don't believe it is an issue our side. If you can provide more insights I will reopen. Thanks!

**Comment by c4710n** [comment]
I have the same issue on：
+ Firefox Developer Edition 86.0b2 (64-bit) on macOS
+ Firefox 85 (64-bit) on macOS

Not only the demo provided by @Nicd , but also many sites written by LiveView, such as:
+ https://elixirstatus.com/
+ https://fullstackphoenix.com/tutorials/combine-phoenix-liveview-with-alpine-js

You can see the spinner provided by nprogress is spining again and again.


https://user-images.githubusercontent.com/59962222/106351869-e4ddb780-6319-11eb-84a6-d826322fc884.mp4

Maybe we should reopen this issue?

**Comment by c4710n** [comment]
I have the same issue on：
+ Firefox Developer Edition 86.0b2 (64-bit) on macOS
+ Firefox 85 (64-bit) on macOS

But everything was fine on:
+ Safari
+ Chrome

Not only the demo provided by @Nicd , but also many sites written by LiveView, such as:
+ https://elixirstatus.com/
+ https://fullstackphoenix.com/tutorials/combine-phoenix-liveview-with-alpine-js

You can see the spinner provided by nprogress is spining again and again.


https://user-images.githubusercontent.com/59962222/106352199-f4f69680-631b-11eb-96cd-82f46a4783ba.mp4


@chrismccord  Maybe we should reopen this issue?

**Comment by c4710n** [comment]
It seems like a Firefox problem.

# Check 1
I check whether my Firefox supports WebSocket by visiting http://websocketstest.com/. And, it shows:

<img width="1358" alt="Screen Shot 2021-01-30 at 10 18 00 PM" src="https://user-images.githubusercontent.com/59962222/106359072-1b7ff600-634b-11eb-8330-43e777a32231.png">


That's wired. After searching, I found a old [issue](https://bugzilla.mozilla.org/show_bug.cgi?id=713023) about Firefox. It said:

> Websockets: don't prefer SOCKS to HTTP proxy.

Then, I think that it should be a proxy problem. And, I found I am using a HTTP proxy, too.

# Check 2

After turning off HTTP proxy, I visited http://websocketstest.com/. And it shows:

<img width="1303" alt="Screen Shot 2021-01-30 at 10 25 21 PM" src="https://user-images.githubusercontent.com/59962222/106359074-20dd4080-634b-11eb-9711-952c2a4b8618.png">


Everything is fine.

# Check 3

In order to test the issue is triggered by HTTP proxy, I visited http://websocketstest.com/ with a SOCKS proxy. And, Everything is fine, too.


# Conclusion

**The issue that I described in above comment is triggered by a HTTP proxy. Nothing wrong with LiveView.**

For others meet the same problem with me, try to disable the HTTP proxy or use a SOCKS proxy for Firefox.

> Firefox, it's really hard to say 'love you'...

Last, sorry for the useless @ ;)

**Comment by Nicd** [comment]
I am not using any proxy, so the issues I see aren't explained by that.

**Comment by AdrianRibao** [comment]
I'm not using a proxy either and I also have this issue

**Comment by cheerfulstoic** [comment]
:-/ I'm experiencing this as well.  Both my LiveView app and the Phoenix LiveDashboard work in Chrome, but neither works in Firefox.  I wonder if I accidentally set some kind of setting?

**Comment by DavidOliver** [comment]
I got this in dev when Firefox's HTTPS-Only Mode was turned on. Turning that off and restarting the browser/reloading tabs allows live reload to work here.

**Comment by wanton7** [comment]
I had similar problems with Chrome. That WebSocket was very slow to connect. This was actually caused by IPv6. What fixed it for me was using 127.0.0.1 instead of localhost. Related StackOveflow question https://stackoverflow.com/questions/15135506/websocket-connection-setup-takes-a-relatively-long-time-is-this-normal

**Comment by georgfaust** [comment]
I am having the same problem.

**Comment by jessie-morris** [comment]
This is still happening for me.

**Comment by loics2** [comment]
Using `127.0.0.1` instead of `localhost`, as @wanton7 suggested, works for me, although I'm not sure of the reason. For me, the issue appears when I restart `mix phx.server`. Firefox can't seem to reconnect to the websocket anymore (it's not just slow, it never reconnects) until I restart Firefox.

**Comment by larshei** [comment]
Just ran into the same thing. Usually I am using Chrome, then realized other users in firefox had some differences in the UI (absolute positioned items had an offset, aspect-ratio of images was incorrect).

So I downloaded Firefox, opened the page and the websocket connection often times took 5-10 seconds to establish, even making the "we cant find the internet" flash message pop up.

switching from `localhost` to `127.0.0.1` seems to have improved to connection time to maybe a second (the topbar is still easily visible on page load)

**Comment by nilsfitnessportalen** [comment]
I am experiencing the same issue. Opening Firefox in private mode seems to resolve the issue and switching to 127.0.0.1 also seem to resolve the issue for me. I have tried changing all settings I could find in Firefox and see if I could find a way to reproduce the issue consistently. Does anybody have any suggestions for how to reproduce this?

**Comment by wanton7** [comment]
Could this be related to this could of year old bug https://bugzilla.mozilla.org/show_bug.cgi?id=1662694 ?

**Comment by loics2** [comment]
Shouldn't this issue be fixed with the recent long poll fallback work? I didn't have the chance to test that yet.

**Comment by nilsfitnessportalen** [comment]
Update:

I have been running with Bandit webserver for a week now and that resolves the issue according to my findings.

Instructions available in the Bandit README.
https://github.com/mtrudel/bandit

**Comment by loics2** [comment]
Can confirm, I've upgraded my app to Bandit, and it doesn't change anything.

**Comment by wanton7** [comment]
Is everyone only having this problem only using localhost or 127.0.0.1?
Found this from 2 years ago https://bugzilla.mozilla.org/show_bug.cgi?id=1662694

> Maybe related: I noticed some weird behavior when connecting multiple localhost websockets.
> 
> Have a websocket server listening on ws://localhost:5555.
> Connect two websockets, the first to ws://localhost:5554 (where there is no server) and the second to ws://localhost:5555.
> The first websocket will error and the second websocket will connect.
> Repeat this a few times. Eventually the first websocket gets delayed before it closes, but the weird thing is the second websocket won't connect until the first websocket closes!
> You can experiment here: https://jsfiddle.net/jezharmw/1/
> node websocket server code I used:
> 
> import { WebSocketServer } from 'ws'
> const wss = new WebSocketServer({ port: 5555 })
> 
> wss.on('connection', ws => {
>   console.log('client connected')
>   ws.on('message', data => console.log(data))
>   ws.on('close', () => console.log('close'))
>   ws.send('hello')
> })

There is a reference to another issue https://bugzilla.mozilla.org/show_bug.cgi?id=711793 that says this behavior is by design.

**Comment by loics2** [comment]
@wanton7 Yep, i'ts only on `localhost` and `127.0.0.1` for me.

This is maybe related to the bug you mentioned, but in my case I'm not sure the connection ends up working, last time I checked, it didn't after 8 minutes...
