### ISSUE TITLE
Proposal: Capture-click for forms

### ISSUE THREAD

**Issue by popo63301** [phoenixframework/phoenix_live_view#1315]
I'm thinking about implementing an event like `phx-capture-click` but more specifically for forms.

I want to implement a simple form to edit the title of something like in trello.
When I click the title, I toggle the form with 1 input autofocused.
When I click outside this input, it's automatically saved.

It would be great to implement this. What do you think ?

**Comment by chrismccord** [comment]
Please don't send proposals on the issue tracker. Try the forum first, or find me on slack or irc to discuss. Thanks!
