### ISSUE TITLE
LiveView crashes and reloads the page after a live_redirect

### ISSUE THREAD

**Issue by nicolasblanco** [phoenixframework/phoenix_live_view#1316]
### Environment

* Elixir version (elixir -v): 1.11.2
* Phoenix version (mix deps): 1.5.7
* Phoenix LiveView version (mix deps): 0.15.3
* NodeJS version (node -v): v15.5.0
* NPM version (npm -v): 7.3.0
* Operating system: OS X Big Sur
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, Safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

Hello,
this bug looks very related to this issue : https://github.com/phoenixframework/phoenix_live_view/issues/1293

The behaviour happening is exactly the same as in this issue that was triggering after a `push_redirect` but this time it's triggered after clicking on a `live_redirect` link : the new LV is mounted, then it crashes with a timeout reference from the previous one.

I'm really trying to find a way to reproduce this issue in a new app, will update if I manage.

Until then you can trigger it on my production site : https://moning.co

Just click on "ETFs" in the header from the home page, scroll down a bit, it will load a few items (infinite scrolling). Then just wait 10-15 seconds, the LV crashes and the page reloads.

When activating `liveSocket.enableDebug()`, the same kind of log as in #1293 happens.

The issue only happens after clicking on a different header link which is a `live_redirect`. When loading the page directly it's not happening.

Downgrading from 0.15.3 to 0.15.0 fixes the issue as in #1293.

### Expected behavior

The LV should not crash after the `live_redirect` 🙂

**Comment by chrismccord** [comment]
So this happens when you live_redirect then trigger an infinite scroll? How are you pushing the infinite scroll? Can you share that client and server code? thanks!

**Comment by nicolasblanco** [comment]
Yes, I confirm that it only happens after a `live_redirect` from the home page and after fetching some new elements in the page with the infinite scroll.

The issue does not happen when the page is loaded through a normal link or if I downgrade to 0.15.0.

The hook which is doing the Infinite scroll is:

```
Hooks.InfiniteScroll = {
  cursor() {
    return this.el.dataset.cursor;
  },
  mounted() {
    this.pending = this.cursor();

    window.addEventListener(
      "scroll",
      throttle(() => {
        if (this.pending == this.cursor() && scrollAt() > 60) {
          this.pending = null;
          console.log("Load more stocks...");
          this.pushEvent("load_more", {});
        }
      }, 1000)
    );
  },
  reconnected() {
    this.pending = this.cursor();
  },
  updated() {
    this.pending = this.cursor();
  },
};
```

**Comment by nicolasblanco** [comment]
@chrismccord helped me to find that I forgot to use `window.removeEventListener` on the window. This was accumulating events listeners and making calls on dead LVs.

**Comment by chrismccord** [comment]
While this was a bug in your hook, it makes sense for us to noop in a hook since user-land is much more likely to allow connected related pushes to slip thru. We now debug log that the push cannot be made and noop. Thanks!
