### ISSUE TITLE
External upload not finished when `consume_uploaded_entries` is called

### ISSUE THREAD

**Issue by lleger** [phoenixframework/phoenix_live_view#1320]
I'm working on implementing direct S3 uploads and noticed that when I call `consume_uploaded_entries` in the LV, the upload has not totally finished yet. This surprised me because [the docs say](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html?#consume_uploaded_entries/3):

> Raises when there are still entries in progress. Typically called when submitting a form to handle the uploaded entries alongside the form data. **For form submissions, it is guaranteed that all entries have completed before the submit event is invoked**. Once entries are consumed, they are removed from the upload.

*(emphasis mine)*

I took that to mean that the request had fully completed, so after calling `consume_uploaded_entries`, I updated the LV with the URL to the new image. The problem is that image URL 404s, since it turns out the request actually hadn't completed yet.

I think what's happening is that `entry.progress()` marks an upload `_isDone` in the sense that all bytes were sent to S3, but S3 hadn't yet responded, so the file wasn't available at the URL.

The guides [suggest an implementation which exhibits the issue](https://hexdocs.pm/phoenix_live_view/uploads-external.html#direct-to-s3):

```js
let xhr = new XMLHttpRequest()
onViewError(() => xhr.abort())
xhr.onload = () => xhr.status === 204 || entry.error()
xhr.onerror = () => entry.error()
xhr.upload.addEventListener("progress", (event) => {
  if(event.lengthComputable){
    let percent = Math.round((event.loaded / event.total) * 100)
    entry.progress(percent) // <- this will mark the upload entry's "_isDone" even if request isn't finished
  }
})

xhr.open("POST", url, true)
xhr.send(formData)
```

A workaround to this is to only return 99% to `entry.progress()` until `xhr.onload` which is triggered after the response is available, not just after the bytes are all transferred.

```js
const xhr = new XMLHttpRequest()
onViewError(() => xhr.abort())
xhr.onload = () =>
  xhr.status === 204 ? entry.progress(100) : entry.error()
xhr.onerror = () => entry.error()
xhr.upload.addEventListener("progress", (event) => {
  if (event.lengthComputable) {
    const percent = Math.min(
      Math.round((event.loaded / event.total) * 100),
      99,
    )
    entry.progress(percent)
  }
})

xhr.open(method, url, true)
xhr.send(formData)
```

I'm happy to PR an update to the guides, but this feels like a workaround, so I thought I'd open an issue first for discussion.

**Comment by chrismccord** [comment]
You are correct. I thought I had already updated the docs to correct the S3 example, but this is what it should be:

```
let Uploaders = {}
Uploaders.S3 = function(entries, onViewError){
  entries.forEach(entry => {
    let formData = new FormData()
    let {url, fields} = entry.meta
    Object.entries(fields).forEach(([key, val]) => formData.append(key, val))
    formData.append("file", entry.file)
    let xhr = new XMLHttpRequest()
    onViewError(() => xhr.abort())
    xhr.onload = () => xhr.status === 204 ? entry.progress(100) : entry.error()
    xhr.onerror = () => entry.error()
    xhr.upload.addEventListener("progress", (event) => {
      if(event.lengthComputable){
        let percent = Math.round((event.loaded / event.total) * 100)
        if(percent < 100){ entry.progress(percent) }
      }
    })
    xhr.open("POST", url, true)
    xhr.send(formData)
  })
}
```

Please send a PR! Thanks!

**Comment by lleger** [comment]
Opened #1321 with your snippet 👍
