### ISSUE TITLE
Docs: update the external file upload to the latest version of S3 library

### ISSUE THREAD

**Issue by happysalada** [phoenixframework/phoenix_live_view#1326]
### Environment

The documentation on S3 external file upload is a little stale.
The latest version of the library does not have the function referred to in the docs `sign_form_upload`
https://github.com/phoenixframework/phoenix_live_view/blob/master/guides/client/uploads-external.md

It does have another function named presigned_url though
https://github.com/ex-aws/ex_aws_s3/blob/master/lib/ex_aws/s3.ex#L988

This part of the docs should just be updated to make it easier to try it.
I haven't tested that the function I referenced is the right one, I should have time in the next few days

Here is the library in question
https://github.com/ex-aws/ex_aws_s3

### Actual behavior

Function referred to in the docs does not exist anymore

### Expected behavior

Docs should provide a ready to copy example for first testing at least.

**Comment by MarkZsombor** [comment]
For reference, I believe that the `sign_form_upload` is meant to come from a gist that Chris McCord put up with his video on uploads https://gist.github.com/chrismccord/37862f1f8b1f5148644b75d20d1cb073

That said, if the docs say "you can just use this code" it should be working code.
