### ISSUE TITLE
Feature: Arbitrary element replacement

### ISSUE THREAD

**Issue by DaTrader** [phoenixframework/phoenix_live_view#1327]
#### Desired behavior:
The ability to define a segregated container with, say, phx-update="cross-replace" containing the elements which LiveView then uses to replace elements with the corresponding ids in their respective appended/prepended containers within the same template. 
The "cross-replace" container is discarded once the operation is finished.
This is virtually the same feature that LiveView already does when replacing elements in an appended/prepended container, the only difference here being the support for cross-container replacement.

#### Purpose:
Use cases dealing with more than a single dimension of elements (e.g. a table/grid) typically require a more detailed element replacement then just having their top-dimension entries (e.g. rows) appended and then sorted in the JS code. With the majority of changes occurring at the level of a single element, it is suboptimal to have LiveView transfer the entire rows.

The reason why this feature cannot be done safely at an application level is hooks - the elements getting replaced require their hook related listeners removed by LV.

@josevalim Please share your thoughts on the matter even if you choose not to consider this enhancement request.

UPDATE: Another option is for client code to alter individual attributes of an element instead of having it replaced with the suggested feature, but the limitations here are substantial.

**Comment by josevalim** [comment]
Hi @DaTrader, for discussions or general feedback, it is better to use the ElixirForum or and similar. I can drop my thoughts there. Thanks.

**Comment by DaTrader** [comment]
Ok. Posted.
