### ISSUE TITLE
Multiple query selectors supported by phx-target but not on tests

### ISSUE THREAD

**Issue by sbacarob** [phoenixframework/phoenix_live_view#1328]
### Environment

* Elixir version (elixir -v): 1.10.2
* Phoenix version (mix deps): 1.5.7
* Phoenix LiveView version (mix deps): 0.13.0
* NodeJS version (node -v): v13.13.0
* NPM version (npm -v): 6.14.7
* Operating system: Manjaro
* Browsers you attempted to reproduce this bug on (the more the merrier): Issue on tests, not browser
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

I have a `LiveView` with a template that renders a `LiveComponent`. The `LiveComponent` has an event that is handled in different ways both by the component and the parent `LiveView`, for this, I use `phx-target` with one selector for the `LiveComponent` and one for the `LiveView` separated by a comma, as described in the last example of [this section](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveComponent.html?#module-targeting-component-events).

On the browser, the event gets dispatched to both views and handled successfully. However, when trying to simulate the event on tests using `render_*`, the test fails with message:

```elixir
** (ArgumentError) expected phx-target to return a single element, but got 2
```
I've created [this sample app](https://github.com/sbacarob/LV-phx-target-issue) that reproduces the issue. If you run `mix phx.server` and navigate to `localhost:4000` you can see a button, and if you click it, the click event gets handled by the root `LiveView` and by an embedded `LiveComponent` and each of them updates a `p` tag. But if you run `mix.test` you'll see the error mentioned above

### Expected behavior

Event should be dispatched to all components referenced by `phx-target`?

I've looked a little bit at the code of [lib/phoenix_live_view/test/client proxy.ex](https://github.com/phoenixframework/phoenix_live_view/blob/731dd6dde16033ae078269ac70d9063824c7609c/lib/phoenix_live_view/test/client_proxy.ex) and of [lib/phoenix_live_view/test/dom.ex](https://github.com/phoenixframework/phoenix_live_view/blob/597c5ddf8af2ca39216a3fe5a44c066774de3abd/lib/phoenix_live_view/test/dom.ex) and I think there are a couple of shortcomings.

1. Unless I'm missing something, I think only CID and DOM id are supported by `ClientProxy.maybe_cid/2` (and therefore by `handle_info({:sync_render_events...}...)`), whereas `phx-target` actually supports any query selector
2. `maybe_cid` gets the value of the `phx-target` attribute, and if it starts by `"#"`, it takes it as a selector, even though a comma might be in there. Then it calls `DOM.maybe_one/3` which fails if there's a comma because multiple elements will be found

I'm not sure if dispatching the event to multiple elements in the test should be supported, but given that `phx-target` actually supports it and that it's mentioned in the docs, I think it probably should. Same thing with using query selectors that are not a CID or a DOM id. I think it probably adds some complexity, as class and attribute selectors, unlike ids, may return multiple elements, but I think it could be a useful addition.

**Comment by josevalim** [comment]
Yes, it is supported on phx-target so we should support it on tests. Since you are exploring the code, a PR would be welcome, let me know if you have questions!

**Comment by sbacarob** [comment]
I'd be thrilled! I'll start working on it and let you know if anything comes up

**Comment by sbacarob** [comment]
Hi @josevalim so, I'm working on a solution that works but I'm not sure about the approach. Could you take a look and let me know if the approach seems right? https://github.com/phoenixframework/phoenix_live_view/compare/master...sbacarob:support-multiple-phx-target-in-tests the code I changed in the client proxy got a bit messy, but please consider it just a draft.
I believe there might be something that needs to be improved because if, for instance, you look at [this test](https://github.com/phoenixframework/phoenix_live_view/compare/master...sbacarob:support-multiple-phx-target-in-tests#diff-3d472263b1f10e989139973c01f3362b3fccb2d05f2ef4f375cff934776fac5dR217), you'll notice I had to call `render_click/2` and then `render/1` on the view, because otherwise, the resulting diff from `render_click/2` would not contain the updated text from the parent view. I can't really understand why yet, as the event **is** being handled by both targeted elements

**Comment by josevalim** [comment]
@sbacarob the issue is that you are sending multiple replies and the liveview test process will reply back as soon as it sees the first reply. So the `render(view)` forces it to sync. You will likely want to reply once when all events are handled.
