### ISSUE TITLE
New mix task to set up a basic live view, instead of 10+ manual steps

### ISSUE THREAD

**Issue by s6o** [phoenixframework/phoenix_live_view#133]
Wondering if the (basic) live view setup could be a mix task ?

The current manual list seems rather long:

## Step 1

```
def deps do
  [
    {:phoenix_live_view, github: "phoenixframework/phoenix_live_view"}
  ]
end
```

## Step 2
Once installed, update your endpoint's configuration to include a signing salt. You can generate a signing salt by running mix phx.gen.secret 32.

## Step 3
```
config :my_app, MyAppWeb.Endpoint,
   live_view: [
     signing_salt: "SECRET_SALT"
   ]
```

## Step 4
Update your configuration to enable writing LiveView templates with the .leex extension.

```
config :phoenix,
  template_engines: [leex: Phoenix.LiveView.Engine]
```

## Step 5
Next, add the LiveView flash plug to your browser pipeline, after :fetch_flash:
```

pipeline :browser do
  ...
  plug :fetch_flash
  plug Phoenix.LiveView.Flash
end
```

## Step 6
Then add the following imports to your web file in lib/my_app_web.ex:

```
def view do
  quote do
    ...
    import Phoenix.LiveView, only: [live_render: 2, live_render: 3]
  end
end

def router do
  quote do
    ...
    import Phoenix.LiveView.Router
  end
end
```

## Step 7
Next, expose a new socket for LiveView updates in your app's endpoint module.

```
defmodule MyAppWeb.Endpoint do
  use Phoenix.Endpoint

  socket "/live", Phoenix.LiveView.Socket

  # ...
end
```

## Step 8
Add LiveView NPM dependencies in your package.json.

```
{
  "dependencies": {
    "phoenix": "file:../deps/phoenix",
    "phoenix_html": "file:../deps/phoenix_html",
    "phoenix_live_view": "file:../deps/phoenix_live_view"
  }
}
```

## Step 9
Then install the new npm dependency.

`npm install --prefix assets`

## Step 10
Enable connecting to a LiveView socket in your app.js file.

```
import LiveSocket from "phoenix_live_view"

let liveSocket = new LiveSocket("/live")
liveSocket.connect()
```

## Step 11
Create lib/my_app_web/live directory

## Step 12
Finally, by convention live views are saved in a lib/my_app_web/live/ directory. For live page reload support, add the following pattern to your config/dev.exs:

```
config :demo, MyAppWeb.Endpoint,
  live_reload: [
    patterns: [
      ...,
      ~r{lib/my_app_web/live/.*(ex)$}
    ]
  ]
```

## Step 13
You can also optionally import the style for the default CSS classes in your app.css file.

`@import "../../deps/phoenix_live_view/assets/css/live_view.css";`

**Comment by josevalim** [comment]
Yes, it is on the roadmap. That's why there isn't even a release. Please be patient. :)

**Comment by niccolox** [comment]
I assume this means live_view generators are planned

**Comment by MichaelDimmitt** [comment]
Trying to be patient but excited about live_view generator tasks. 

Is there a way to view this on the Roadmap externally to check the progress?
1) A few months ago I explored live view into an existing Phoenix application to use server side validation for forms.

A few pain points led me to shelving the project:
1) Many changes went into creating a live view page or template.
2) Blogs were implementing the framework differently implementing live view for a few different reasons: clients broadcasted information, server side validation, server explaining its environment (thermometer), etc.

I think live view is really cool but I don't want my entire site to be live view I want it to be a mixture of live view and normal phoenix views, with the nice live_view separation of concern pattern that has emerged.

## Questions:
1) Is there a way to view this on the Roadmap externally to check the progress?
2) Would the phoenix live_view scaffold task land in the phoenixframework repo?
3) Or is there a tasks repo to watch?

**Comment by MichaelDimmitt** [comment]
Looks like they are working ❤️
At-least the starting scaffold is working, going to investigate further later today.

mix.phx.gen.live Timeline Posts post username body

It looks good in the video!
https://youtu.be/MZvmYaFkNJI

@s6o @niccolox
