### ISSUE TITLE
Can't type into form text inputs after live page update

### ISSUE THREAD

**Issue by dtip** [phoenixframework/phoenix_live_view#1332]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 23 [erts-11.1.7] [source] [64-bit] [smp:24:24] [ds:24:24:10] [async-threads:1]

Elixir 1.11.2 (compiled with Erlang/OTP 23)
```
* Phoenix version (mix deps):
```
* phoenix 1.5.7 (Hex package) (mix)
  locked at 1.5.7 (phoenix) 774cd644
* phoenix_ecto 4.2.1 (Hex package) (mix)
  locked at 4.2.1 (phoenix_ecto) 478a1bae
* phoenix_html 2.14.3 (Hex package) (mix)
  locked at 2.14.3 (phoenix_html) efd697a7
* phoenix_live_dashboard 0.4.0 (Hex package) (mix)
  locked at 0.4.0 (phoenix_live_dashboard) 8d52149e
* phoenix_live_reload 1.3.0 (Hex package) (mix)
  locked at 1.3.0 (phoenix_live_reload) 02c1007a
* phoenix_live_view 0.15.4 (Hex package) (mix)
  locked at 0.15.4 (phoenix_live_view) 35d78f3c
* phoenix_pubsub 2.0.0 (Hex package) (mix)
  locked at 2.0.0 (phoenix_pubsub) c52d948c
* phoenix_swoosh 0.3.2 (Hex package) (mix)
  locked at 0.3.2 (phoenix_swoosh) 3e2ac4e8
```
* Phoenix LiveView version (mix deps):
See above
* NodeJS version (node -v):
```
v14.15.4
```
* NPM version (npm -v):
```
6.14.10
```
* Operating system:
Ubuntu 20.04 + MacOS 10.15.7 (Catalina)
* Browsers you attempted to reproduce this bug on (the more the merrier): 
Firefox + Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:
Yes

#### Summary

After a live page update I'm not able to type into form text input boxes. If I refresh the page I can type into the boxes as expected.

#### Details

I have a few forms, all defined with
```
<% f = form_for :some_atom, "#", [phx_submit: "submit"] %>
...
</form>
```

If I navigate to the form with a live-update I'm not able to type into any text input boxes. The problem happens with `text_input` and `textarea` - always implemented using the Phoenix helpers. When I say "live-update" I mean all of: a `live_patch`, a `live_redirect` (both implemented with Phoenix helpers) and a template which contains something like:
```
<%= if @some_event_has_happened? do %>
... show form ...
<% else %>
... something else ...
<% end %>
```

After a page refresh I can type into the boxes.

#### Minimal repro app

I don't have this yet. I'm hoping I've done something stupid and one of the clever people here will know what off the top of their head. If not, I'll create a minimal app showing the problem.

### Expected behavior

Should be able to type into text input boxes after a live-update.

**Comment by josevalim** [comment]
Hi @dtip! Nothing comes to mind so we will most likely need a small LiveView example that reproduces it. :) Also make sure that the following is not happening: the fields are actually changing but you are resetting them on the server!

**Comment by dtip** [comment]
Thanks @josevalim. I've narrowed down the problem: we have a placeholder div which uses a `phx-hook` to dynamically load a couple of Javascript files and then creates an Unity engine WebGL2.0 instance (by messing with the DOM directly). The placeholder div has `phx-update="ignore"`. If I remove the placeholder div, the JS + Unity window is not loaded, and the problem disappears. Seems something is not playing nicely. Do you have any ideas for how to debug?

Need to do a bit more work to turn this into an example repo!

**Comment by josevalim** [comment]
Are the inputs inside the phx-update="ignore" ones? If so they indeed won't be updated. :)

**Comment by dtip** [comment]
Nope - the inputs are in a separate Liveview. If I first load the Liveview which loads Unity and then live_patch over to another view with a text input, the text input won't work.

**Comment by chrismccord** [comment]
It's really hard to say what is going on here without an example, but given the webGL hook and client DOM manipulation it sounds like that's where things are going wrong. At minimum we need to see the LiveView and the LiveView template. Thanks!

**Comment by sandeshsoni** [comment]
hey @dtip 
just adding thoughts based on my experience(mistakes)

When it is a form, I assume its a ModalComponent...

```elixir
<%= if @live_action in [:new_stall, :edit_stall] do %>
<%= live_modal @socket, MyWeb.UserDashboardLive.StallFormComponent,
    id: :new,
..........
    current_user: @current_user,
    action: @live_action,
    return_to: Routes.user_dashboard_index_path(@socket, :index)
    %>
<% end %>

```

I had faced "similar" issue but was unable to reproduce. It was a strange but silent bug/mistake.
There was a mistake in assigning `@ current_user` after login, so the values were missing.
When I logged out and logged id, it worked to me.

I want to say... check if any of value is nil that is troubling you...

**Comment by dtip** [comment]
The issue was actually a cheeky bit of non-liveview javascript grabbing keyboard input!
