### ISSUE TITLE
phx_leave doubles latency on live_redirect links

### ISSUE THREAD

**Issue by pierre-pretorius** [phoenixframework/phoenix_live_view#1334]
I'm really enjoying Phoenix live view thank you.  I run a global app/site where most users have a 100-200ms latency to the webserver.  To navigate through the site I generally use live_redirect to render links.  When you click a link, live view first sends a phx_leave event over the websocket.  Once that returns it sends a phx_join to navigate to the new page.  This means that when clicking any live_redirect link, you can expect the response to be at least double the latency.

In the example image below i have a 150ms - 200ms latency between me and the server (actual latency, not simulated via chrome).  Even though the server responds instantly, there is more or less 1s delay before the user sees the page they clicked on.

Normal live view interactions (not live_redirect) feel reasonably fast even with a 200ms latency.

### Environment

* Elixir version: Elixir 1.11.2 (compiled with Erlang/OTP 23)
* Phoenix version: 1.5.7
* Phoenix LiveView version: 0.15.3
* NodeJS version: v14.15.5
* NPM version: 6.14.11
* Operating system: Ubuntu 20.04 LTS
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome 87, Firefox 84
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

![image](https://user-images.githubusercontent.com/2392091/107867618-26777200-6e85-11eb-80db-0cf7083342d8.png)

### Expected behavior

When clicking a live_redirect link it doesn't perform a full request/response latency cycle before it starts requesting the page you intend to visit.  Perhaps a phx_leave_and_join event that performs both in a single request?

**Comment by chrismccord** [comment]
This is a known tradeoff. The perceived RTT latency is not the phx_lave, but us making an xhr request to sign a new session for the new LiveView, which must go through the plug pipeline. There may be ways to simulate a request through the plug pipeline, but it is path dependent and not trivial. If you have highly latent clients, regular links would avoid the extra round trip for initial page load, but of course you'll need the 2nd route trip for the websocket. Thanks!

**Comment by chrismccord** [comment]
We also may be able to pre-flight these requests, but it's not something we are tackling at the moment. If someone would like to give it a go, please let us know!

**Comment by pierre-pretorius** [comment]
Thank you for the response. I guess the same way the initial page load returns the LiveView with it's html dom, the xhr request could also return the html dom.

I'll see if I can make a PR for it. To be frank, I have to make a PR or abandon LiveView. Having a good way to navigate between views is a foundational requirement of a web app. Without it the rest doesn't really matter. Apps that don't have users with 100ms+ latency must be rare.

**Comment by chrismccord** [comment]
> Thank you for the response. I guess the same way the initial page load returns the LiveView with it's html dom, the xhr request could also return the html dom.

In this case, this is the same as going the regular link route, since we still need to attach a new channel to the HTML.

> I'll see if I can make a PR for it. To be frank, I have to make a PR or abandon LiveView. Having a good way to navigate between views is a foundational requirement of a web app. Without it the rest doesn't really matter. Apps that don't have users with 100ms+ latency must be rare.

If you go the regular link route, you're back at the same time to first byte/paint as everything else, but your interface will need the websocket upgrade trip before interaction happens. I understand the desire for minimized latency, but this is a bit hyperbolic. It's also not clear where your "1s latency" is coming from as 100-200ms RTT x 2 doesn't get us there so we'd need to know more about your real latency conditions and if the work on your LV mounts contributes to perceived latency.

**Comment by pierre-pretorius** [comment]
> In this case, this is the same as going the regular link route, since we still need to attach a new channel to the HTML.

Would be similar, except the CSS/JS isn't reloaded (almost like the advantage you get from turbolinks) and it wouldn't re-establish the websocket on HTTP level (HTTP 101).  But yes I agree it wouldn't be significantly different.

> It's also not clear where your "1s latency" is coming from as 100-200ms RTT x 2 doesn't get us there

You are right I did a lot more testing today and it's closer to 500ms instead of 1 second, which brings it closer to latency x2. Even with the 2x latency the websocket achieves a similar performance end result to the full request, which means better results will be achievable with the pre-flight enhancement you mentioned instead of optimizing the xhr request.

**Comment by josevalim** [comment]
To clarify, you should see this:

  1. We do an AJAX request which returns the new LiveView session in its response
  2. Once we get the session on the client, we send a command on the websocket to start the new LiveView

Chris and I have discussed an alternative solution to this problem - which takes a bit more development to implement but seems to be doable - which is to use message passing to trigger the redirect within the node/cluster. We will aim for something like this:

  1. We do an AJAX request, which will contact the current LiveView and ask it to start a new LiveView with the session (this is a fire-and-forget). We will still return the session.
  2. Once we get the session on the client:
      * If we were already redirected, because of the message to the current LiveView, there is nothing todo
      * Otherwise we send a command on the websocket to start the new LiveView (the transport will be the source of truth in case it is racing as the new LiveView may actually already be in flight)

In the best case scenario, this should cut the latency in half (so one regular RTT) and reduce the amount of requests in half compared to what we do today. The complexity is implementing a atomic replace channel operation on the transport but that should be doable.

**Comment by josevalim** [comment]
This is fixed on master with the new `live_session` stuff. Please read the CHANGELOG for more info.

**Comment by pierre-pretorius** [comment]
We have this change in production now, it's a massive performance improvement thank you.
