### ISSUE TITLE
phx-click fires before data confirm

### ISSUE THREAD

**Issue by willfore** [phoenixframework/phoenix_live_view#134]
### Environment

* Elixir version (elixir -v): Elixir 1.8.0 (compiled with Erlang/OTP 21)
* Phoenix version (mix deps): phoenix 1.4.2
* NodeJS version (node -v): v11.12.0
* NPM version (npm -v): NPM 6.7.0 || yarn 1.15.2
* Operating system: Mac OSX 10.14.3

### Actual behavior
When using data: [confirm: "something"] on a link that has phx-click bound to it. The phx-click event fires even when clicking cancel on the dialog.

`<%= link "Delete", to: "#", data: [confirm: "Are you sure?"], "phx-click": "delete", "phx-value": "#{row["file"]}", class: "button is-danger" %>`

### Expected behavior
When clicking cancel on the dialog box the phx-click event should not fire.

**Comment by chrismccord** [comment]
Note, you will need phoenix_html master as well, since there was an event propagation bug there as well. Thanks!

**Comment by willfore** [comment]
Thanks Chris!
