### ISSUE TITLE
Select value gets lost when 2 selects are on the page

### ISSUE THREAD

**Issue by sb8244** [phoenixframework/phoenix_live_view#1341]
### Environment

* Elixir version (elixir -v): `1.11.2`
* Phoenix version (mix deps): `1.5.7`
* Phoenix LiveView version (mix deps): `0.15.4` (original 0.15.3 but updated for test)
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, Safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:

### Actual behavior

I have multiple select boxes on the page, rendered with `select` helper and with unique IDs (verified in DOM). I first set select 1 to a value. I then set select 2. The changeset represents the correct data the entire time, but the UI switches select 1 back to the prompt.

### Expected behavior

When I change select 2, the first select should keep its value. Moreso, the value of select 1 should reflect the value of the changeset.

### Snippets

```
    <%= f = form_for(@changeset, "#", phx_submit: "create", phx_change: "update", phx_target: @myself) %>
      <%= hidden_input f, :provider %>
      <%= hidden_input f, :object_type %>

      <div class="m-t-7" id="link-type-field">
        <label class="inline-block">Which Clove type to link to?</label>
        <%= select :link_rule, :link_type,
                          link_type_options(),
                          prompt: "Select Link Type",
                          class: "p-3" %>
      </div>

      <%= if Ecto.Changeset.fetch_field!(f.source, :link_type) do %>
        <div class="m-t-7" id="link-condition-field">
          <label class="inline-block">Link Condition</label>
          <%= select :link_rule, :sync_record_field, sync_field_options(@sync_fields), prompt: "Select Synced Field", required: true, class: "p-3 max-w-300" %>
          <%= select :link_rule, :operator, operators(), prompt: "Operator", required: true, class: "p-3" %>
          <%= select :link_rule, :record_field, record_field_options(f.source), prompt: "Select Clove Field", required: true, class: "p-3 max-w-300" %>
        </div>
      <% end %>
...
```

In the above snippet, the group of 3 selects does not go into the changeset (will be processed externally and merged in as a param. The changeset looks like this after selecting a first option:

```
#Ecto.Changeset<
  action: nil,
  changes: %{
    hub_id: 1,
    link_type: "hub_organization",
    object_type: "Account",
    organization_id: 1,
    provider: "salesforce"
  },
  errors: [link_rule: {"can't be blank", [validation: :required]}],
  data: #Clove.HubModules.SyncEngine.Schema.LinkRule<>,
  valid?: false
>
```

and it looks like this after selecting an option in select 2:

```
#Ecto.Changeset<
  action: nil,
  changes: %{
    hub_id: 1,
    link_type: "hub_organization",
    object_type: "Account",
    organization_id: 1,
    provider: "salesforce"
  },
  errors: [link_rule: {"can't be blank", [validation: :required]}],
  data: #Clove.HubModules.SyncEngine.Schema.LinkRule<>,
  valid?: false
>
```

Notice no change, but the UI reflects a change:

https://user-images.githubusercontent.com/1231659/108618122-7906e000-73e9-11eb-91c3-fffe7ec9147f.mov

Here is the relevant DOM sections:

```
<div class="m-t-7" id="link-type-field">
    <label class="inline-block">Which Clove type to link to?</label>
    <select class="p-3" id="link_rule_link_type" name="link_rule[link_type]"><option value="" selected="">Select Link Type</option><option value="hub_organization">Organization</option><option value="hub_user">User</option></select>
  </div>
<div class="m-t-7" id="link-condition-field">
      <label class="inline-block">Link Condition</label>
      <select class="p-3 max-w-300" id="link_rule_sync_record_field" name="link_rule[sync_record_field]" required=""><option value="" selected="">Select Synced Field</option><option value="NumberOfEmployees">Employees — NumberOfEmployees</option><option value="Type">Account Type — Type</option><option value="Name">Account Name — Name</option><option value="Id">Account ID — Id</option></select>
      <select class="p-3" id="link_rule_operator" name="link_rule[operator]" required=""><option value="" selected="">Operator</option><option value="=">=</option></select>
      <select class="p-3 max-w-300" id="link_rule_record_field" name="link_rule[record_field]" required=""><option value="" selected="">Select Clove Field</option><option value="external_id">External ID</option><option value="email">Email</option></select>
    </div>
```

I tried wrapping the form sections in an ID'd div, but no luck.

I also checked the WS messages and I don't see anything that would indicate a change for select 1. This makes me think that it's something with the dom patching and not related to LiveView backend. For example, you can see the group of 3 in the following diff (makes sense since it's in an `if`), but select 1 is not present (it didn't change). However, the UI reflects a change.

![image](https://user-images.githubusercontent.com/1231659/108618325-24646480-73eb-11eb-879a-02d37dbc7e19.png)

**Comment by josevalim** [comment]
Because your selects are not using any variable, the value on the server never changes. So while the select is focused, we will keep what you selected on the client, but once you remove the focus and server sends new contents, it will send the old ones.

You need to either put the data on the changeset, and even if you are going to send it elsewhere, you split the data based on where you want to validate it, OR you need to store those values in custom assigns and do this:

      select :foo, :bar, value: ...

Otherwise the server never notices the change and will always reset it. )

**Comment by sb8244** [comment]
Ah I see now. I thought I had connected it to the form f but now see that I didn't. And the custom values will be handled with stored state. Thanks José!
