### ISSUE TITLE
Video doesn't show on iOS when rendered after live_redirect

### ISSUE THREAD

**Issue by karolsluszniak** [phoenixframework/phoenix_live_view#1342]
### Environment

* Elixir version (elixir -v): 1.11.1
* Phoenix version (mix deps): 1.5.7
* Phoenix LiveView version (mix deps): 0.15.4
* NodeJS version (node -v): v14.12.0
* NPM version (npm -v): 6.14.8
* Operating system: iOS 14.4
* Browsers you attempted to reproduce this bug on (the more the merrier): built-in iOS Safari, iOS Chrome 87.0
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

I have the `<video>` element that's supposed to replicate the GIF's behavior like below:

```
<video src="https://s3.amazonaws.com/.../video.mp4" autoplay muted playsinline loop></video>
```

It works fine - plays automatically - when:
- using any desktop browser including desktop Safari
- refreshing the page in iOS Safari

But if the element gets rendered without full page reload after live_redirect, it doesn't show - the `<video>` element is in DOM, displays as transparent block that takes default amount of space independent of actual video resolution.

If I call `document.querySelector('video').play()`, I get following error:

```
Unhandled Promise Rejection: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
```

What's interesting, the error is fixable (or rather hackable) by remounting video in React (and probably with plain JS too). Here's a LiveView hook that does so assuming that each video within it is wrapped in a `<div>`:

```js
import React from 'react'
import ReactDOM from 'react-dom'

const Video = ({ url }) => {
  return (
    <video src={url} autoPlay muted playsInline loop>
    </video>
  )
}

export default {
  mounted () {
    this.el.querySelectorAll('video').forEach(video => {
      const div = video.parentElement
      const url = video.getAttribute('src')
      ReactDOM.render(<Video url={url} />, div)
      this.videos.push(div)
    })
  },

  beforeDestroy () {
    this.videos.forEach(div => {
      ReactDOM.unmountComponentAtNode(div)
    })
  }
}
```

With this hook in place, video appears and autoplays as expected. This makes it seem like an issue specific to how Phoenix LiveView or morphdom inserts the new HTML. 

This is probably the same issue as in #436. That one was closed considered device specific by author, but I've tried on a few completely different iPhones and the issue persisted. I've also disabled all content blockers without success. Searched on Google without traces of similar issues. Therefore at this point - even if it is related to some iOS quirk - I don't see a better place to open the issue.

### Expected behavior

Video should appear and play after live redirect, just like it does after full page refresh.

**Comment by harmon25** [comment]
I am having similar issues with Safari and live navigations (live_redirects/live_patches) on `video` and also `img` tags, 

[Here is the site](https://beatconnect.com/) in question - if you have an iOS device or safari on desktop it is easy to reproduce.

After first load, click the logo which performs a `live_redirect` to the same page (/)- and all the images and videos disappear. 

My temporary work around is to just use plan anchor tags to navigate around, which is a bit of a bummer.

**Comment by karolsluszniak** [comment]
@harmon25 You can always recreate the element with js after LV mounts them - IMO it’s better than going back to plain links. You have React example above, for non-React app I’d try createElement either in LV hook or plugged to the after page load event.
