### ISSUE TITLE
use `phx-disable-with` with raw HTML?

### ISSUE THREAD

**Issue by c4710n** [phoenixframework/phoenix_live_view#1352]
When implementing a customized submit button(described in following image and link) for a form, I found that `phx-disable-with` blocks my way:
<img width="679" alt="Screen Shot 2021-02-28 at 9 11 35 PM" src="https://user-images.githubusercontent.com/59962222/109419681-99e2bd00-7a09-11eb-82f9-f59ef419927a.png">
(The live demo for the button can be found at [here](https://tailwindcss.com/docs/animation#spin).)

Above button requires that LiveView replaces button's content as HTML, but currently, it is replaced as text:
https://github.com/phoenixframework/phoenix_live_view/blob/11060451c3da4ae7bf8ee20b32478907de870e24/assets/js/phoenix_live_view.js#L2571

I am very glad to contribute this feature, but, before starting it, I wanna know:
+ Are there any considerations to implement it like this, such as security? 
+ Is it possible to implement this feature with `innerHTML`?

**Comment by josevalim** [comment]
It is not about security considerations but rather how to handle diffing inside the button, for example, you could say you want to ignore everything, but that may not fit everyone’s requirement, so for simplicity we only handle text.

Your options are:

1. use hooks
2. do any customization via CSS as the button gets a special class

**Comment by c4710n** [comment]
Thanks for your explanation. ;)
