### ISSUE TITLE
`mix phx.new demo --umbrella --live` does not create a demo liveview

### ISSUE THREAD

**Issue by Qqwy** [phoenixframework/phoenix_live_view#1353]
### Environment

* Elixir version (elixir -v):  Erlang/OTP 23 [erts-11.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] Elixir 1.11.3 (compiled with Erlang/OTP 23)

* Phoenix version (mix deps):
* Phoenix LiveView version (mix deps): 0.15.4
* `phx_new` mix archive version: 1.5.8
* Operating system: Linux Manjaro x64

### Situation

```bash
mix phx.new demo --umbrella --live
```

### Expected behavior

Initialize an umbrella application, where a `demo_web/lib/live` directory exists with some demo files, as well as the live_view-specific settings being added to `demo_web/lib/demo_web.ex`.

### Actual behavior

These directories/files are not created. It seems the `--live`-flag does nothing when used together with the `--umbrella`-flag.

**Comment by josevalim** [comment]
I cannot reproduce:

```
$ mix archive.install hex phx_new
$ mix phx.new demo --umbrella --live
$ rgrep "phoenix_live_view" demo_umbrella/apps/demo_web/
demo_umbrella/apps/demo_web//mix.exs:      {:phoenix_live_view, "~> 0.15.0"},
demo_umbrella/apps/demo_web//assets/js/app.js:import {LiveSocket} from "phoenix_live_view"
demo_umbrella/apps/demo_web//assets/package.json:    "phoenix_live_view": "file:../../../deps/phoenix_live_view",
```

The app booted fine too and I could play with LiveView on the home page.

**Comment by Qqwy** [comment]
I must have made a typo somewhere then... I am also not able to reproduce it anymore.
Apologies, and thank you for responding on such short notice :green_heart: !
