### ISSUE TITLE
Auto-recovery fails for forms inside components that are dynamically added/removed from DOM

### ISSUE THREAD

**Issue by deepankar-j** [phoenixframework/phoenix_live_view#1355]
### Environment

* Elixir version (elixir -v): **Elixir 1.11.2 (compiled with Erlang/OTP 21)**
* Phoenix version (mix deps): **1.5.8**
* Phoenix LiveView version (mix deps):  **v0.15.4** (also verified against latest commit SHA 11060451c3da from master)
* NodeJS version (node -v): **v14.16.0**
* NPM version (npm -v): **6.14.11**
* Operating system: **Mac OS**
* Browsers you attempted to reproduce this bug on (the more the merrier):  **Chrome**
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: **Yes**

#### Sample App
I've altered the phoenix_live_view_example app's "CRUD users with live pagination" app to demonstrate the issue.  You can find my fork of that app here.  Please see the **auto_recover_issue** branch.

https://github.com/chrismccord/phoenix_live_view_example/compare/master...deepankar-j:auto_recover_issue

#### Video 
I've also captured a video of the issue:  https://user-images.githubusercontent.com/49971671/110196318-4f967d00-7e09-11eb-8115-f85b22310054.mp4

#### Steps

1. Disable live_reload in app
2. Create a liveview page that dynamically shows and hides a live component using `<%= if ... do %>` based on some condition.
3. Add a form to the live component.  See the CRUD users app in the sample app above.
4. Click on the Edit (Component) link to edit a user and show the component
5. Type some text in field
6. Restart Phoenix server
7. Observe that the text is restored
8. Hide the live component
9. Show the live component again (could be for the same user or a different one)
10. Type some text in field
11. Restart Phoenix server
12. Observe that the text is **not** restored

### Expected behavior

Form auto-recovery should work the same regardless of whether a live component is add/removed from the DOM.

### Investigation Notes

Based on my investigation into the data sent over the websocket, the problem appears to stem from the fact that the "validate" event sent from the front-end references a `cid` (presumably the component ID), which corresponds to a value that the newly restarted backend can't find.  Here's the gist of the events:

- Page is loaded 
- Live component is shown, `cid = 1`
- User types text
- Server restarts, front-end looses connection
- Connection re-established, backend recreates live component with `cid = 1`
- Front-end sends "validate cid = 1" event sent to the backend
- Backend matches up validate event to live component
- Auto-recovery works as expected

Good so far 👍 

- User clicks link which hides live component
- Backend removes live component from DOM
- User clicks link to show live component again
- Backend shows live component with `cid = 2`
- Server restarts, front-end looses conneciton
- Connection re-established, backend recreates live component with **`cid = 1`**
- Front-end sends **"validate cid = 2"** event sent to the backend
- Backend can't match event to live component
- Auto-recovery for field fails

### Workaround

In my case, the live component being added and removed from the DOM resembles what I was trying to do with a modal in my production app.  A simple workaround is to not add/remove live components from the DOM.  However, I feel like this auto-recovery issue is still a bug because it seems valid to be able to add and remove live_components from the DOM dynamically.

**Comment by gcauchon** [comment]
_imho_ A better design to show/hide a component would be to leverage the browser to toggle visibility without relying on the server state.

Considering the network round trip, storing a Boolean flag in socket state feels like a huge overhead with no significant benefit.

I've personally been using AlpineJS for a few months with great success…

**Comment by deepankar-j** [comment]
> _imho_ A better design to show/hide a component would be to leverage the browser to toggle visibility without relying on the server state.
> 
> Considering the network round trip, storing a Boolean flag in socket state feels like a huge overhead with no significant benefit.
> 
> I've personally been using AlpineJS for a few months with great success…

Thanks @gcauchon.  

I did consider AlpineJS for my case.  It seems like it would work well for stateless modals and for easing out the showing/hiding of dialogs.  However, in my case I have a stateful modal.  So, I need to:
- fetch extra data when a the dialog is shown + create and store a changeset
- update the route so that the modal is linkable

Using AlpineJS would make the display of my stateful dialog a little more responsive, but it would have probably hidden this bug because I would have had to leave the live component in the DOM to let AlpineJS control its visibility.

That being said, I'll definitely explore leveraging AlpineJS for making my UI smoother.

**Comment by gcauchon** [comment]
It does make sense to leverage state in your use case then!

Just to be clear, even with my previous comment, investigating the reconnection issues is still important!

**Comment by chrismccord** [comment]
We cannot restore dynamically generated state for you, as is your case with the toggling of the component. You need to rebuild this state yourself on mount by storing the user toggling in more persistent storage, or as @gcauchon said, avoid dynamically building the state on the serve run the first place. Thanks!

**Comment by deepankar-j** [comment]
Thanks @chrismccord.  I can understand not wanting (or being able) to support state for dynamically added/removed components.  

What's troubling about this case is:

1.  Depending on the layout, auto-recovery can work if the developer only shows the dynamically added component once.  I think this can give a false sense of confidence that auto-recovery will work in general.
2. The [Recovery Following Crashes or Disconnects](https://hexdocs.pm/phoenix_live_view/form-bindings.html#recovery-following-crashes-or-disconnects) docs section doesn't explicitly state that auto-recovery for dynamically added/removed components isn't supported.

I think both issues warrant correction.  

**For Issue 1**

- Could dynamically added components be marked in the DOM in a special way such that auto-recovery doesn't work for the initially added component?  Also, it would be helpful to log a warning to the console.

**For Issue 2**

- Updating the docs to explicitly call out auto-recovery for dynamically added components not being supported.

I could help by submitting a PR, but I'd need some guidance on how to properly address Issue 1.

**Comment by josevalim** [comment]
I think we should do 2 anyway, regardless if we implement 1 or not. :) So a PR is welcome!

**Comment by deepankar-j** [comment]
Would someone be able to take a look at PR #1362 for updating the documentation?
