### ISSUE TITLE
Cannot test live file input in live component

### ISSUE THREAD

**Issue by philippeqd** [phoenixframework/phoenix_live_view#1357]
### Environment

* Elixir version (elixir -v): 1.11.3-otp-23
* Phoenix version (mix deps): 1.5.4
* Phoenix LiveView version (mix deps): 0.15.1
* NodeJS version (node -v): 14.15.4
* NPM version (npm -v): 7.5.6
* Operating system: macOS
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

I have a `live_file_input` inside a live component in which I also call `allow_upload` inside the `mount` function. Uploading files works perfectly in dev, however when I run the test below, I get an error that says that uploads are not allowed for photo. 

An example can be found here: https://github.com/philippeqd/test-live-input-bug

I found that the error is raised  because I surrounded my `<form>` with a `<div>`. When I remove the `<div>`, then the tests pass. I cannot figure out why this happens and I am wondering whether it has to do with my selector in the `file_input`. 

**Test:**
```
test "upload", %{conn: conn} do
    {:ok, view, _html} = live(conn, "/")

    assert file_input(view, "#logo-upload", :photo, [
             %{
               name: "test.jpg",
               content: File.read!("test/static/images/test.jpg"),
               type: "image/jpeg"
             }
           ])
           |> render_upload("test.jpg") =~
             "<progress max=\"100\" value=\"100\""
  end
```

**Failing example**
```
<div>
  <form id="logo-upload" phx-submit="save" phx-change="validate" phx-target="<%= @myself %>">
    <%= live_file_input @uploads.photo %>
    <button type="submit">Upload</button>
    <%= for entry <- @uploads.photo.entries do %>
      <progress max="100" value="<%= entry.progress %>" class="h-1 w-40"/>
    <% end %>
  </form>
</div>
```

**Output:**
`  ** (RuntimeError) no uploads allowed for photo`

However, when I remove the surrounding `<div>`, then the test passes. 

**Working example**
```
<form id="logo-upload" phx-submit="save" phx-change="validate" phx-target="<%= @myself %>">
  <%= live_file_input @uploads.photo %>
  <button type="submit">Upload</button>
  <%= for entry <- @uploads.photo.entries do %>
    <progress max="100" value="<%= entry.progress %>" class="h-1 w-40"/>
  <% end %>
</form>
```

### Expected behavior
As the file uploading in my live component works perfectly in Dev mode, I expected that uploading files would work in the tests as well. With or without the surrounding `<div>`.

**Comment by chrismccord** [comment]
Can you provide an example LiveView, component, and test case that reproduces the issue? Thanks!

**Comment by philippeqd** [comment]
@chrismccord Thank you, the repo containing an example can be found here: https://github.com/philippeqd/test-live-input-bug
