### ISSUE TITLE
phx-update="ignore" only ignores content but changes element attributes

### ISSUE THREAD

**Issue by vfsoraki** [phoenixframework/phoenix_live_view#1359]
I don't know if this is expected behavior or not, but I have an element like this to be used by Leaflet map:
```
<div id="content" class="md:mr-5 mt-5 md:mt-0 w-full" style="position: relative;" phx-hook="DashboardMap" phx-update="ignore">
```

I initialize Leaflet in `mounted` callback, and there are server events that update the map.

Leaflet initializes successfully and initial map is shown correctly, but after any update in state which results in dom change, map disappears.

I found out that Leaflet adds additional classes to its container, here `#content`. After a dom update by LV, these classes are removed and CSS from Leaflet is not applied anymore, hence disappearing map, although you can see that the DOM structure is still there.

It can be fixed by having another element as container inside `#content`, and I confirmed it works. 

But the question is is this expected behavior? Should LV reset classes after a dom update, even with `phx-update="ignore"`?

**Comment by josevalim** [comment]
Yes, this is intentional, especially because using phx-hook+phx-update=ignore is a common combo and you want to update the attributes for the hook.

**Comment by vfsoraki** [comment]
OK, good to know.

I read the docs many times just to find this out on my own. A mention in docs would be nice, don't you think?

I will make a PR.
