### ISSUE TITLE
Question about pitfalls and form helpers

### ISSUE THREAD

**Issue by nicklayb** [phoenixframework/phoenix_live_view#1363]
Hi guys, I was wondering about a contradiction in the documentation. I'm sorry if this is not the place for this, I couldn't find a better place.

The documatation talks about possible pitfalls [here](https://hexdocs.pm/phoenix_live_view/assigns-eex.html#liveeex-pitfalls) and metion that assigning variables won't be tracked like below 

```elixir
<% some_var = @x + @y %>
<%= some_var %>
```

However, the documentations uses the following Phoenix's pattern for form [here](https://hexdocs.pm/phoenix_live_view/form-bindings.html)
```elixir
<%= f = form_for @changeset, "#", [phx_change: :validate, phx_submit: :save] %>
```

What makes assigning `form_for` to a variable correct? Just trying to understand the difference

Thank you!

**Comment by josevalim** [comment]
You are correct. This means that whenever you use the `f` from `form_for` that particular element will always be rendered. So that code **has** the pitfall and hopefully we will include better approaches in the future.
