### ISSUE TITLE
File upload from destroyed component affecting next uploads

### ISSUE THREAD

**Issue by evaldobratti** [phoenixframework/phoenix_live_view#1364]
### Environment

* Elixir version (elixir -v): Elixir 1.10.2 (compiled with Erlang/OTP 21)
* Phoenix version (mix deps): 1.5.7
* Phoenix LiveView version (mix deps): 0.15.0
* NodeJS version (node -v): v12.18.3
* NPM version (npm -v): 6.14.6
* Operating system: Linux Mint
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

I have a multistep form that was developed using live components managing which one is currently visible via assigns.
One of the components has a live file upload that works as expected, but when navigating to the next form step, this
component gets replaced for another and when pressing back and trying to upload another file, the following errors occurs.

```
[error] GenServer #PID<0.856.0> terminating
** (RuntimeError) existing upload for file already allowed in another component (3)

If you want to allow simultaneous uploads across different components, pass a
unique upload name to allow_upload/3

    (phoenix_live_view 0.15.0) lib/phoenix_live_view/channel.ex:1035: Phoenix.LiveView.Channel.ensure_unique_upload_name!/2
    (phoenix_live_view 0.15.0) lib/phoenix_live_view/channel.ex:162: anonymous fn/7 in Phoenix.LiveView.Channel.handle_info/2
    (phoenix_live_view 0.15.0) lib/phoenix_live_view/diff.ex:191: Phoenix.LiveView.Diff.write_component/5
    (phoenix_live_view 0.15.0) lib/phoenix_live_view/channel.ex:1008: Phoenix.LiveView.Channel.write_socket/4
    (phoenix_live_view 0.15.0) lib/phoenix_live_view/channel.ex:159: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 3.7.1) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib 3.7.1) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib 3.7.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

The problem seems to that the live upload state is still kept, breaking on the next file upload when attempting to `allow_upload` with the same name of the previous destroyed component.

I checked some live socket messages and it seems that live view already cleans up some destroyed state, but the file upload seems not to be affected by this events.

![image](https://user-images.githubusercontent.com/1869525/110656283-92a47780-819e-11eb-8fb8-29f43c3e9c80.png)

I also tried using `disallow_upload` when pressing the continue buttom from my form, but it didn't work too.

### Expected behavior

Using the same name in `allow_upload` from a destroyed component should not affect the current component.

**Comment by sb8244** [comment]
This is happening to me as well. In my case `push_patch` is used to redirect to the new upload, while a sidebar allows for additional uploads. I'm digging in to see if I can locate anything else or workarounds here.

**Comment by DavidVII** [comment]
@sb8244 I've experienced something similar over the weekend. I attempted to use `disalow_upload`, but it didn't seem to have any effect.

I have a page that has multiple "UploadForm" components on it. Each component has a unique ID and would work with the first upload. However, subsequent uploads would result in the error described.

The way I got around it was by generating a unique name by using the components `cid` in the `mount` function.

```
def mount(socket, assigns) do
  upload_name = ~w(documents_#{socket.assigns.myself.cid})a |> hd()

  socket = socket |> allow_upload(upload_name, accept: ~w(.pdf))

  {:ok, assign(socket, upload_name: upload_name)}
end
```

You'll notice that I assigned an `upload_name` to the socket. This was useful in my case so that I could refer to the correct upload in my template: `@upload[@upload_name]`

Definitely feels like a workaround, but it works!

I was digging around the LiveView code a bit and while I wasn't able to determine a fix, I agree that there's a key that's not being cleaned up at the end of the component's lifecycle. The parent LiveView is somehow remembering the upload names of the child components.

**Comment by avergin** [comment]
> The way I got around it was by generating a unique name by using the components `cid` in the `mount` function.
> 
> ```
> def mount(socket, assigns) do
>   upload_name = ~w(documents_#{socket.assigns.myself.cid})a |> hd()
> 
>   socket = socket |> allow_upload(upload_name, accept: ~w(.pdf))
> 
>   {:ok, assign(socket, upload_name: upload_name)}
> end
> ```

One issue with this approach is that it dynamically generates atoms, and these will not be garbage collected. And currently, I think we cannot use strings as upload names.
