### ISSUE TITLE
Live View removes DOM elements inserted by JavaScript, even with phx-update="ignore"

### ISSUE THREAD

**Issue by ijt** [phoenixframework/phoenix_live_view#1367]
### Environment

* Elixir version (elixir -v):
Erlang/OTP 23 [erts-11.1.3] [source] [64-bit] [smp:6:6] [ds:6:6:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.11.2 (compiled with Erlang/OTP 23)

* Phoenix version (mix deps): 1.5.8
* Phoenix LiveView version (mix deps): 0.15.4
* NodeJS version (node -v): v15.8.0
* NPM version (npm -v): 7.5.0
* Operating system: Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64
* Browsers you attempted to reproduce this bug on (the more the merrier): Brave, Safari, Firefox, Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:

### Steps to reproduce
1. `git clone https://github.com/ijt/rantclub.git`
2. `cd rantclub`
3. `mix deps.get`
4. `mix ecto.setup`
5. `cd assets && npm install && cd ..`
6. `mix phx.server`
7. In a browser, visit http://localhost:4000/chats
8. Wait for smiley face to appear at the bottom.
9. Click New Chat
10. Enter a chat a click the Save button.

### Actual behavior

The smiley face disappears.

### Expected behavior

I expected the smiley face to stay there.

**Comment by ijt** [comment]
So this isn't really a bug?

**Comment by josevalim** [comment]
You submitted duplicate reports :) See #1368.

**Comment by ijt** [comment]
Oh, got it!
