### ISSUE TITLE
Live View removes DOM elements inserted by JavaScript, even with phx-update="ignore"

### ISSUE THREAD

**Issue by ijt** [phoenixframework/phoenix_live_view#1368]
### Environment

* Elixir version (elixir -v):
Erlang/OTP 23 [erts-11.1.3] [source] [64-bit] [smp:6:6] [ds:6:6:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.11.2 (compiled with Erlang/OTP 23)

* Phoenix version (mix deps): 1.5.8
* Phoenix LiveView version (mix deps): 0.15.4
* NodeJS version (node -v): v15.8.0
* NPM version (npm -v): 7.5.0
* Operating system: Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64
* Browsers you attempted to reproduce this bug on (the more the merrier): Brave, Safari, Firefox, Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Steps to reproduce
1. `git clone https://github.com/ijt/rantclub.git`
2. `cd rantclub`
3. `mix deps.get`
4. `mix ecto.setup`
5. `cd assets && npm install && cd ..`
6. `mix phx.server`
7. In a browser, visit http://localhost:4000/chats
8. Wait for smiley face to appear at the bottom.
9. Click New Chat
10. Enter a chat a click the Save button.

### Actual behavior

The smiley face disappears.

Before:

<img width="506" alt="Screen Shot 2021-03-14 at 1 08 06 PM" src="https://user-images.githubusercontent.com/15530/111080976-b29da900-84c6-11eb-9d9b-4faa2e652bbc.png">

After clicking New Chat and Save:

<img width="361" alt="Screen Shot 2021-03-14 at 1 08 29 PM" src="https://user-images.githubusercontent.com/15530/111080981-b5989980-84c6-11eb-84db-3d215ebda227.png">

### Expected behavior

I expected the smiley face to stay there.

**Comment by ijt** [comment]
Is something wrong with my bug report? If so, I'm sorry. I didn't mean to waste your time.

**Comment by ijt** [comment]
Is something wrong with my bug report? If so, I'm sorry. I didn't mean to waste your time.

**Comment by josevalim** [comment]
The report is good, I just closed the duplicated one. Also note you are sending duplicate comments, you probably want to check that. :)

**Comment by ijt** [comment]
@axelson pointed out on Slack that I needed to use `phx-hook` instead of an inline `<script>` tag. The following change made it work just fine:

In app.js:
```javascript
let Hooks = {}
Hooks.Smiley = {
    mounted() {
        this.el.innerHTML = '😃'
    }
}

let liveSocket = new LiveSocket("/live", Socket, {params: {_csrf_token: csrfToken}, hooks: Hooks})
```

and in `index.html.leex`, remove the `<script>` stuff and update the div like this:

```html
<div id="smiley" style="font-size: 80px" phx-hook="Smiley"></div>
```
