### ISSUE TITLE
LiveView throws Lighthouse "unload"-Warning

### ISSUE THREAD

**Issue by fschoenfeldt** [phoenixframework/phoenix_live_view#1373]
### Environment

* Elixir version (elixir -v): Elixir 1.10.4 (compiled with Erlang/OTP 23
* Phoenix version (mix deps): phoenix 1.5.7 (Hex package) (mix)
* Phoenix LiveView version (mix deps): phoenix_live_view 0.15.4 (Hex package) (mix)
* NodeJS version (node -v): v14.16.0
* NPM version (npm -v): 7.6.3
* Operating system: MacOS
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

![image](https://user-images.githubusercontent.com/4721311/111356271-7f0a7c80-8688-11eb-98c6-f9f491e7e970.png)

### Expected behavior

https://developers.google.com/web/updates/2018/07/page-lifecycle-api?utm_source=lighthouse&utm_medium=devtools#the-unload-event

To get my well-deserved 100% rating on lighthouse, I'd like to know why LiveView uses the old-fashioned "unload" listener and not another like mentioned in the above document.

**Comment by chrismccord** [comment]
We'd accept a PR that uses a well supported alternative. Thanks!
