### ISSUE TITLE
Liveview Patching Issue

### ISSUE THREAD

**Issue by addcninblue** [phoenixframework/phoenix_live_view#1375]
### Environment

* Elixir version (elixir -v): `Elixir 1.11.3 (compiled with Erlang/OTP 23)`
* Phoenix version (mix deps): `1.5.8`
* Phoenix LiveView version (mix deps): `0.15.4`
* NodeJS version (node -v): `v12.18.4`
* NPM version (npm -v): `6.14.6`
* Operating system: NixOS (Linux)
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

I'm creating a simple pomodoro application. When I click on any of the times on the webpage, only the time that was clicked on disappears and is replaced by the string "test".

### Expected behavior

The entire block of times should disappear and be replaced by the string "test".

### More Background

Here is the code: https://github.com/addcninblue/pomodoro

The relevant lines are 

https://github.com/addcninblue/pomodoro/blob/88959f325e24173adca557ada223939f96e49413/lib/pomodoro_web/live/room_live.html.leex#L20-L37.

The handler that handles when the times are clicked appears to be functioning correctly, since if the `if` block is changed to something simple (ie. just a `div`), the times are replaced by the `div`. However, it appears that when the items inside are too complicated, the items aren't being patched correctly.

This repo can be cloned and that website can be viewed at `localhost.../room/test`.

I am using Tailwind, if that changes anything.

Thanks!

Edit:

* Bumped versions to latest
* Some pictures:

Before time is clicked:
![image](https://user-images.githubusercontent.com/7519521/111434639-01ad2f00-86bd-11eb-8154-46ae00837a9b.png)

After time is clicked (notice the times are still there, but the one that's clicked has disappeared):
![image](https://user-images.githubusercontent.com/7519521/111434660-083ba680-86bd-11eb-8d90-2c9a7e226a8b.png)

If we remove the `div`s surrounding `"test"` in the `if` block (here the times disappear):
![image](https://user-images.githubusercontent.com/7519521/111434726-20abc100-86bd-11eb-8bc9-11962f1a9a55.png)

**Comment by josevalim** [comment]
Can you please update to latest LiveView first and let us know if it fixes the issue? Thank you.

**Comment by addcninblue** [comment]
Hey @josevalim! Thanks so much for all your work, and thanks so much for the really fast reply! I have just bumped up the version to 0.15.4, which I believe is latest. Unfortunately, it appears the issue still remains. I have taken some screenshots and uploaded them in the original post. Thanks again!

**Comment by gcauchon** [comment]
@addcninblue You have multiple DOM element with the same `id`.￼

**Comment by josevalim** [comment]
You have a bunch of duplicate IDs named start, that is causing the error. You should also see warnings on the browser console. :)

**Comment by josevalim** [comment]
@gcauchon you bet me to it, thanks! :heart:

**Comment by chrismccord** [comment]
The warnings only appear if you call `liveSocket.enableDebug()` in the js console

**Comment by addcninblue** [comment]
Ah gotcha! Thank you all so much :D
