### ISSUE TITLE
Scroll restoration on native navigation with live view inside regular templates

### ISSUE THREAD

**Issue by Abat** [phoenixframework/phoenix_live_view#1376]
### Environment

* Elixir version (elixir -v): **Elixir 1.11.2 (compiled with Erlang/OTP 23)**
* Phoenix version (mix deps): **phoenix 1.5.8**
* Phoenix LiveView version (mix deps): **phoenix_live_view 0.15.4**
* NodeJS version (node -v): **v14.15.1**
* NPM version (npm -v): **6.14.8**
* Operating system: **Ubuntu 18.04**
* Browsers you attempted to reproduce this bug on (the more the merrier): **Chrome, Firefox**
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: **no**

### Actual behavior

I have a `Page index` page which is rendered using a regular Phoenix controller and a template.

Inside `Page index template` I live_render `Posts list` which is a live view and each individual post is a live component.

When I click on one of the posts - an individual post is opened. Again, I use regular `Post show` template.
Inside that` Post show template` I live_render Post show live view with a post as a live_component.

When I go back to `Page index page` (using browser's back button) it does not restore scroll position and always renders at the top of the page.

htts://fuagra.net - what described above can be seen here.

### Expected behavior

Scroll position should be restored when pressing browser's back button.

I tried this flow using only live_view and live_components and scroll position is respected. But I loose meta tags for SEO and some other benefits of using regular phoenix controllers and templates.

There is also this pull request - https://github.com/phoenixframework/phoenix_live_view/pull/1256

I tried it, not sure it fixes it fully though. I've seen some strange behaviour from it.

Please help, this bug is really annoying UX wise.

**Comment by chrismccord** [comment]
please track #1256 for progress. Thanks!
