### ISSUE TITLE
Event targeting a Component is handled by the parent LiveView in Test

### ISSUE THREAD

**Issue by molenick-mov** [phoenixframework/phoenix_live_view#1377]
### Environment
Test
* Elixir version (elixir -v):
Elixir 1.10.4 (compiled with Erlang/OTP 22)
* Phoenix version (mix deps):
phoenix 1.5.8
* Phoenix LiveView version (mix deps):
phoenix_live_view 0.15.4
* NodeJS version (node -v):
v12.18.3
* NPM version (npm -v):
6.14.6
* Operating system:
macOS Big Sur 11.2.3 (20D91)
* Browsers you attempted to reproduce this bug on (the more the merrier): 
Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:
No

### Actual behavior
I have a stateful component with a link:
```
link(
  gettext("Delete"),
  to: "#",
  phx_target: @myself,
  phx_click: :delete_topic,
  phx_value_topic_id: topic.id,
  data: [
    confirm: gettext("Are you sure you want to delete \"%{description}\"?",
    description: topic.description)
  ]
)
```

In test, I create a LiveView and embed the component with it, then use render_click() to click the link.  Upon doing so, throws the following error: `(UndefinedFunctionError) function MyAppWeb.Test.LiveComponentHarness.handle_event/3 is undefined or private`.

Stacktrace:
```
     ** (EXIT from #PID<0.584.0>) an exception was raised:
         ** (UndefinedFunctionError) function MyApp.Test.LiveComponentHarness.handle_event/3 is undefined or private
             (retro 0.1.0) MyApp.Test.LiveComponentHarness.handle_event("Delete", %{}, #Phoenix.LiveView.Socket<assigns: %{component: MyApp.MyComponent, component_assigns: %{id: "topic-list-1", topics: [%MyApp.Resources.Resource{__meta__: #Ecto.Schema.Metadata<:loaded, "resource">, description: "some description", ...}]}, flash: %{}, live_action: nil}, changed: %{}, endpoint: MyAppWeb.Endpoint, id: "phx-Fm0xLBgSRmgQNwJB", parent_pid: nil, root_pid: #PID<0.588.0>, router: nil, view: MyAppWeb.Test.LiveComponentHarness, ...>)
             (phoenix_live_view 0.15.4) lib/phoenix_live_view/channel.ex:338: anonymous fn/3 in Phoenix.LiveView.Channel.view_handle_event/3
             (telemetry 0.4.2) [%APP_PATH%]/deps/telemetry/src/telemetry.erl:262: :telemetry.span/3
             (phoenix_live_view 0.15.4) lib/phoenix_live_view/channel.ex:203: Phoenix.LiveView.Channel.handle_info/2
             (stdlib 3.12.1) gen_server.erl:637: :gen_server.try_dispatch/4
             (stdlib 3.12.1) gen_server.erl:711: :gen_server.handle_msg/6
             (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

The LiveView I'm using in test looks like this:
```
defmodule MyAppWeb.Test.LiveComponentHarness do
  use MyAppWeb, :live_view

  @impl true
  def mount(_params, session, socket) do
    assigns = session["component_assigns"] |> Map.new(fn {k, v} -> {String.to_atom(k), v} end)

    socket =
      socket
      |> assign(:component, session["component"])
      |> assign(:component_assigns, assigns)

    {:ok, socket}
  end

  @impl true
  def render(assigns) do
    ~L"""
    <div>
    <%= live_component @socket, :"#{@component}", @component_assigns %>
    </div>
    """
  end
end
```

Here is my test that is generating the error:
```
defmodule MyAppWeb.ResourceListLiveTest do
  use MyAppWeb.ConnCase
  import Phoenix.LiveViewTest
  alias MyAppWeb.Test.LiveComponentHarness
  alias MyApp.Resources


  describe "render" do
    test "when there are resources, clicking delete deletes a resource", %{conn: conn} do
      {:ok, _resource} = Resources.create_resource(%{description: "some description"})

      {:ok, view, html} =
        live_isolated(conn, LiveComponentHarness,
          session: %{
            "component" => MyAppWeb.ResourceList,
            "component_assigns" => %{
              "id" => "resource-list-1",
              "resources" => Resources.list_resources()
            }
          }
        )

      assert view
             |> render_click("Delete") =~ "deleted"
    end
  end
end
```

When running `mix phx.server` and performing the same action in the browser, the Component receives the "delete_topic" message and everything works as expected.

### Expected behavior
When I run my test and I use render_click() to click the link in text, the Component specified as the action's phx-target handles the event.

As a related question - is there any good documentation on practices for unit testing components?  It's pretty clear how to integration and feature test them, but I haven't found much information on unit testing Components in isolation.  So far I've been successful using a test harness LiveView to load up the component and test it like it was a LiveView, but I'm wondering if there's a better approach.  Thanks!

**Comment by josevalim** [comment]
Hi @molenick-mov! can you please try to provide a test in our test suite that reproduces the error? It will make it easier for us to reproduce it.

Unfortunately we don't have many conveniences for unit testing components besides the render_component function, which just renders them, but does not handle any event.

**Comment by molenick-mov** [comment]
Thanks for the quick response @josevalim!  I'll try and contribute a test today that demonstrates this.

**Comment by molenick-mov** [comment]
@josevalim I was able to reproduce, my repo with the failing test is here:
https://github.com/molenick-mov/phoenix_live_view

The specific commit of the test is:
https://github.com/molenick-mov/phoenix_live_view/commit/2f461688b374ede90246fc010378bd32357dd348

**Comment by molenick-mov** [comment]
I noticed two other quirks that I haven't really had time to dig into, and can create new issues if necessary.  They are:

1. In test, using render_click() on a link with  `data: [confirm: "Are you sure you want to delete this"?"]` seems to immediately call the handle_event callback, without my test taking any additional action to confirm the action.  Maybe this is a convenience that render_click() provides?

2. In test, using render_click() on a link with a `phx_value_my_thing="1"` sends an empty param map to  the handle_event callback, instead of %{"my_thing" => "1"} as I would expect.

I don't know much about the innards of LiveView/LiveViewTest, but it seems like some combination of render_click()/live_isolated() is failing to forward attributes (phx-target, data, phx-value_*) set on the html element that is initiating the event.

**Comment by josevalim** [comment]
Sorry for the delay.

The current behaviour is correct. When you do `render_click(view, ...)`, you are directly sending the event to the view. In order to trigger the event through an element, and load its value and phx-target, you need to use the `view |> element("div#id") |> render_click()`.
