### ISSUE TITLE
Can `Phoenix.LiveViewTest.render_component/3` support block components?

### ISSUE THREAD

**Issue by matthewlehner** [phoenixframework/phoenix_live_view#1379]
We're using some stateless live components to encapsulate presentational concerns, however, we're unable to test these because the API for `Phoenix.LiveViewTest.render_component/3` doesn't match the API for `Phoenix.LiveView.Helpers.live_component/4`.

Following the LiveComponent docs, I've built a component that behaves something like this:

```elixir
defmodule WrapperComponent do
  use Phoenix.LiveComponent

  def render(assigns) do
    ~L"""
    <div class="presentational concerns">
      <div>Some navigation stuff, perhaps</div>
      <%= render_block(@inner_block, entry: entry) %>
    </div>
    """
  end
end
```

And that can be called from LiveViews, like this:

```eex
<% live_component @socket, ProductWrapperComponent, title: @title do %>
  <p>Other markup and stuff to do with the LiveView itself.</p>
<% end %>
```

Now, I don't know enough about the internals of how this all works to know if this is a non-trivial request, but I would love to be able to write tests in a similar manner:

```elixir
test "renders markup properly" do
  assert rendered = render_component(ProductWrapper, title: "a test title" do
    "some inner content that doesn't matter in the context of testing the component"
  end)
  
  assert rendered =~ "a test title"
end
```

**Comment by josevalim** [comment]
Please see #1271. :)
