### ISSUE TITLE
[Request for documentation/tutorial]: Complex layout with multiple shared/top-level components

### ISSUE THREAD

**Issue by dmitriid** [phoenixframework/phoenix_live_view#1383]
I've started this as a question/thread over at [Elixir forum](https://elixirforum.com/t/liveview-shared-layout-live-components-woes/38445). Now I've realised that if there's a good solution to this, it should be added to the documentation.

It's possible that currently Elixir doesn't provide a good way to solve this, but it's also possible it may in the future. And I hope my attempts will help other people.

Copy-pasted from Elixir forum with some modifications (I hope this is okay, and sorry for a wall of text):

# Intro: what and why

How to properly implement a reasonably complex layout that implements things like:

- `live_patch` for links
- `live_render`/`live_component` to embed various live components
- works across all views and controllers

The reason for such a layout is simple: imagine a CMS system. You may want to have:

- a sidebar with all the links to internal functionality: list all pages, edit a page, manage uploaded media, manage users. All these will be handled by different controllers. But you would still want a live_patch link to relevant pages

- in that same sidebar (or some other place like a sidebar to the right, or a footer, or a notification pop up) you want to place all manners of various things: your internal console, a list of things that are happening in the system (for example, you’re batch-processing a bunch of images and you want to see the status of the job even as you’re working on something else in the system) etc.

Examples of things that people may want from such a layout:

- Gmail shows the number of unread messages in the left sidebar. These numbers are updated regardless of whether you’re composing a new email, or reading an email

- Also Gmail: has a pop-up message composing window that’s available everywhere

- Elixir Forum. The avatar in the top-right corner will update if there are unread messages, you can click on it and see the list of unread messages. You can also search in the pop-out in the top-right corner. All this happens regardless of where you are in the forum.

And so on.

# The problem

The problem is: how to achieve all that?

**What follows is a description of my attempts to achieve that**

# The setup

So, let’s assume you have the following in your `router.ex`

```elixir
  pipeline :admin do
    plug :authenticate_user
    plug :put_root_layout, {CMS.LayoutView, :admin}
  end

  scope "/admin", CMSWeb do
    pipe_through [...all your other pipleines ..., :admin]
  end
```

You have the following in your `CMSWeb.AdminController`:

```elixir
defmodule CMSWeb.AdminController do
  use CMSWeb, :live_view
  use CMSWeb, :controller

def handle_params(_params, _uri, socket) do
  {:noreply, socket}
end

def mount(_params, _session, socket) do
  {:ok, Phoenix.LiveView.assign(socket, some_data: [])}
end

def render(assigns) do
    ~L"""... render your live data as you would..."""
end
You have the following in your CMSWeb.ProcessesView:

defmodule CMSWeb.ProcessesView do
  use CMSWeb, :live_view

 def render(assigns) do
    ~L"""... render live data ..."""
 end

 def mount(_params, _, socket) do
    ## You would also subscribe to a PubSub queue here, and have
    ## multiple handle_info callbacks to update the view
    {:ok, assign(socket, some_data: [])}
 end
```

# The layouts, the data flow and issues

The rendering of a page goes through these layers:

## 1. Root layout: can live render components, `live_patch` is "broken"

The root layout will be `template/lyout/admin.html.leex` (irrelevant code omitted for clarity):

```eex
<!DOCTYPE html>
<html lang="en">
  <head></head>
  <body>
     <%= live_patch "All pages", to: Routes.live_path(@conn, CMSWeb.AdminController) %>
     <%= live_render(@conn, CMSWeb.ProcessesView) %>

     <%= @inner_content %>
  </body>
```

`live_patch` in the root template is “broken” (aka works as expected). It works, it will do a `live_redirect`, but the underlying <a> tag will get a `phx-click-loading` class that is never cleared. The reason is described here: https://github.com/phoenixframework/phoenix_live_view/issues/956#issuecomment-641474100

`live_render` works beautifully. It does create a separate LiveView instance, but other than that everything works as expected.

However, there are issues with `live_flash`, see the section on `live_fash` below.

## 2. Live layout: inclusion of `live_render` ends up messing up `live_patch`

Let’s remove both `live_patch` and `live_render` from our root template, and add them to `template/layout/live.html.leex`:

```eex
<%= live_patch "All pages", to: Routes.live_path(@socket, CMSWeb.AdminController) %>
<%= live_render(@socket, CMSWeb.ProcessesView, id: "unique-id") %>

<%= @inner_content %>
```

First, the changes:

- `@conn` is no longer available, you use `@socket`
- `live_render` requires an `id` because the component is now rendered within the context of an existing LiveView
- 
Problems I encountered:

- if you include the `live_render` in this layout, all `live_patch` links get broken and do a full page reload instead of a live update. This even includes `live_patch` links rendered by LiveView inside `@inner_content`

- if you keep `live_render` in the root layout, no problem with live_patch, but then you can’t really have the layout you need

## 3. The controller/view

And the last step in the rendering is the actual view returned by your controller. The problem having a layout on this level is obvious:

- you need to copy-paste/include the layout in every separate view
- events sent to the live component will end up being sent to the currently active controller/view

# `live_flash`

Given all the setup above, here are the issues with `live_flash` that looks like this:

```eex
<p class="alert alert-info" role="alert"
   phx-click="lv:clear-flash"
   phx-value-key="info">aaa<%= live_flash(@flash, :info) %></p>
```

## `live_flash` in `admin.html.leex` doesn't trigger `phx-click`

It will display only once, which is a good thing. However, phx-click will not trigger, and the flash will not be cleared:

`admin.html.leex`:
```eex
<p class="alert alert-info" role="alert"
   phx-click="lv:clear-flash"
   phx-value-key="info">aaa<%= live_flash(@flash, :info) %></p>

<%= live_render(@conn, CMSWeb.ProcessView) %>
<%= @inner_content %>
```

## `live_flash` in `live.html.leex` will get displayed several times

Since putting `live_render` inside `live.html.leex` breaks `live_patch`, I tried to do the following:

`admin.html.leex`:
```eex
<%= live_render(@conn, CMSWeb.ProcessView) %>
<%= @inner_content %>
```

`live.html.leex`:
```eex
<p class="alert alert-info" role="alert"
   phx-click="lv:clear-flash"
   phx-value-key="info">aaa<%= live_flash(@flash, :info) %></p>
<%= @inner_content %>
```

Now, if you `put_flash`, it will display twice: once in the live_rendered component and one in the regular page. Which makes sense since it’s two LiveViews going through the same layout.

`phx-click` works, but you have to dismiss each flash separately.

---

I haven't found good solutions to this. Phoenix DashBoard partially mitigates this by using a PageBuilder, but that might not be a good solution for some people.

**Comment by josevalim** [comment]
Hi @dmitriid, the forum is indeed the best place to have this discussion. If there is a good solution to this, then someone can send a pull request to add it to the docs, but it is not particularly the job of the Phoenix team to find the solution for you. Thanks!
