### ISSUE TITLE
No way to get the current (relative) URL from a liveview/livecomponent

### ISSUE THREAD

**Issue by dealloc** [phoenixframework/phoenix_live_view#1389]
### Environment

* Elixir version (elixir -v): Elixir 1.11.3 (compiled with Erlang/OTP 23)
* Phoenix version (mix deps): phoenix 1.5.8
* Phoenix LiveView version (mix deps): 0.15.4
* NodeJS version (node -v): v15.11.0
* NPM version (npm -v): 7.6.3
* Operating system: Linux manjaro 5.9.16-1-MANJARO SMP PREEMPT Mon Dec 21 22:00:46 UTC 2020 x86_64 GNU/Linux
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior
In the generated lib/<app name>/templates/layout/live.html.leex I have my general application layout including the menu links.
They currently look something like this:
```elixir
<%= live_redirect to: Routes.page_path(@socket, :index), class: "link classes here" do %>
<!-- SVG icon here -->
</svg>
Home
<% end %>
```
I'd want to be able to mark the link referring to the page the user is currently on as 'active' (eg. add a class or attribute, ...).
For regular templates you would make a helper method in the view module and fetch the current URL from the `conn` variable. However in liveviews we have `socket` which, as far as I can tell, does not have a (convenient) way to get the current URL (relative or absolute, though relative would be the most convenient since the route helpers generate relative ones too).

### Expected behavior
A property on the socket, or a method that I can call passing in the socket to get the (preferably relative, but that's just my use case) URL.

I've been looking around in the documentation, the Elixir forums and even took a look at the source code of live_dashboard, but it seems that the best we currently have are workarounds (like storing the URL from `handle_params` but it just feels like this small bit is missing from liveviews.

**Comment by josevalim** [comment]
Yes, storing it from handle_params is the way to go. The reason why we don't store by default is because URLs can be get  large and storing them by default can be an issue when you want your LV to be as lightweight as possible. So it is opt-in!

**Comment by josevalim** [comment]
For example, if your goal is to see the active tab, maybe you normalize still in handle_params, instead of storing the whole URL. There are many approaches to take here.

**Comment by dealloc** [comment]
What I've currently done is in the `live_view/0` method in the generated <app name>_web file added something along the lines of this:
```elixir
      def handle_params(_params, uri, socket) do
        %URI{
          path: path
        } = URI.parse(uri)

        {:noreply, assign(socket, __path__: path)}
      end
```
(still need to clean that up and make sure that if handle_params is defined in the module I can override it etc)

**Comment by tadasajon** [comment]
I have an app with a left menu containing several tabs and I want to set one of them as "active" by adding a class to it.  This left menu is set in the `templates/layout/live.html.heex` file.  My layout leaves a large main space in which any of many different live views may be rendered, depending on which menu item the user clicks on.

Each live view has it's own `handle_params(params, uri, socket)` function, so I have to remember to set my left menu status in several different handle_params functions spread across all my different live views.  This appears to violate the principles of DRY code.

Suppose I want to make a minor adjustment to the way I deal with the active tab in my left menu -- I have to make this adjustment in a dozen or more different handle_params function, with more being added every month as the app grows in score.

It seems better to me to resort to using javascript to highlight the active menu item by just checking `window.location.pathname` than to have my elixir code duplicated in every LiveView.

Am I missing something?  How do you address my situation, @dealloc

**Comment by dealloc** [comment]
Same way I mentioned in my previous comment, when you generate your Phoenix project it generates a file lib/{project_name}_web.ex.
In that file is the method `live_view/0` which provides the code that's imported for all live views, so adding the code I wrote there should be available in all live_view without having to duplicate it everywhere.

**Comment by tadasajon** [comment]
@dealloc Thanks so much for taking the time to respond.  I have tried the approach you suggested, but I don't seem to be able to remove the code duplication.  So yes, I can add code in `my_app_web.ex` that will be available in all live views, but I still have to call that code from every single live view. 

Suppose I have 10 different live views, so I have 10 different `handle_params` functions.  Then suppose I put a function in `lib/my_app_web.ex` that is automatically imported in all 10 of my live views.  Don't I still have to adjust all 10 of my `handle_params` functions to call this code that I have automatically imported?

I want hook in at some point in the live view lifecycle that will be automatically *run* for every single live view.

**Comment by dealloc** [comment]
Oof, it's been a while since I dove into this part so this is from memory (read: here be dragons).
if I recall correctly, that handle_params method would automatically be imported into the liveview so you wouldn't need to manually call this code (unless you're overriding handle_params for other purposes in each of those liveviews, but then little can be done "automagically" I'd guess)

it was my understanding that handle_params is that hook?

**Comment by chrismccord** [comment]
@tadasajon use a server lifecycle hook introduced in 0.17 to accomplish. You want to avoid injecting code in every live view via the `live_view` function. Life-cycle hooks will allow you to define a `Nav` module or similar that can do the `handle_params` for all views of the same `live_session` in the router

**Comment by dealloc** [comment]
That's definitely a better solution, thanks @chrismccord!

**Comment by tadasajon** [comment]
@chrismccord Thanks for the tip.

For others who may come across this issue, here is what I came up with:

1. I set an `on_mount` hook in my `lib/my_app_web/router.ex` file:
```elixir
scope "/", MyAppWeb do
  pipe_through([:browser, :require_authenticated_user])

    live_session :quiz_maker, on_mount: MyAppWeb.LeftMenu do
      live "/widgets", WidgetLive.Index, :index
      live "/gadgets/new", GadgetLive.Index, :index
      live "/sprockets/:id/edit", SprocketLive.Index, :index
      live "/fasteners/:id", FastenerLive.Index, :index
  end
end
```

2.  I created a `lib/my_app_web/live/left_menu.ex` file as follows -- the `mount` function is the on_mount hook that is run.  When this hook is run, it sets another hook in turn -- on the handle_params method:
```elixir
defmodule MyAppWeb.LeftMenu do
  use MyAppWeb, :live_view

  def mount(params, session, socket) do
    socket =
      assign(socket,
        left_menu: [
          {"Widgets", Routes.widgets_index_path(socket, :index)},
          {"Sprockets", Routes.sprockets_index_path(socket, :index)},
          {"Gadgets", Routes.gadgets_question_index_path(socket, :index)},
          {"Fasteners", Routes.fasteners_index_path(socket, :index)}
        ]
      )

    socket =
      attach_hook(socket, :set_left_menu_active_path, :handle_params, fn
        _params, url, socket ->
          {:cont, assign(socket, left_menu_active_path: URI.parse(url).path)}
      end)

    socket = {:cont, socket}
  end
end
```

3. in my `lib/my_app_web/templates/layout/live.html.heex` file I set up my left menu as follows:
```eex
<div id="left-menu">
    <%= for {menu_txt, path} <- @left_menu do %>
        <div class={"left-menu-item #{if path == @left_menu_path_active, do: "active"}"}>
            <a class="menu-txt" href={path}> <%= menu_txt %> </a>
        </div>
    <% end %>
</div>
```
The only thing I am unclear about is that the[ docs for `Phoenix.LiveView.on_mount`](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#on_mount/1) say that the method must be named `on_mount`:

> The function within the given module, which must be named on_mount, will be invoked before both disconnected and connected mounts. 

But I could not get the code to work when I named the function `on_mount` and instead got it working with the method just named `mount`.  Any idea what is going on there, @chrismccord ?

**Comment by tadasajon** [comment]
> The only thing I am unclear about is that the docs for Phoenix.LiveView.on_mount say that the method must be named on_mount.

One final update -- I've figured out that the reason that the docs weren't aligning for me is that I was on LiveView version 0.16 and I was reading the docs for LiveView 0.17.4 -- I had rebuilt my project with `mix phx.new app` and I had not realized that Phoenix 1.6.2 uses LiveView 0.16 by default.

**Comment by ammmir** [comment]
I've been trying to also get some active tabs to work, but seems the lifecycle hooks aren't supported in live components: `lifecycle hooks are not supported on stateful components`. This is more difficult than it should be.

**Comment by sergiotapia** [comment]
This is definitely much harder to implement than it seems to be on the surface.

**Comment by sergiotapia** [comment]
Here's how I fixed this if you find yourself in this thread from Bing:

Create a new module to assign "current_uri" to your socket. I only set the path string to the assigns, since I don't want/need the whole URI enchilada.

```
defmodule GamedropWeb.SaveRequestUri do
  def on_mount(:save_request_uri, _params, _session, socket),
    do:
      {:cont,
       Phoenix.LiveView.attach_hook(
         socket,
         :save_request_path,
         :handle_params,
         &save_request_path/3
       )}

  defp save_request_path(_params, url, socket),
    do: {:cont, Phoenix.Component.assign(socket, :current_uri, URI.parse(url) |> Map.get(:path))}
end
```

Call this module from your router.ex:

```
live_session :current_user,
  on_mount: [
    {GamedropWeb.UserAuth, :mount_current_user},
    {GamedropWeb.SaveRequestUri, :save_request_uri}
  ] do
  live("/users/co.... *snip*
end
```

And then you can just call this from your liveview templates.

```
<.game_navigation current_uri={@current_uri} />
# "/game/pokemon-stadium/discussions"
```
