### ISSUE TITLE
Event gets send twice when using inputs_for

### ISSUE THREAD

**Issue by Awlexus** [phoenixframework/phoenix_live_view#139]
I'm not entirely sure of that is an issue with phoenix_html or phoenix_live_view, but I am getting strange results when using `inputs_for/3` in a live form. 

### Environment

* Elixir version (elixir -v):
Erlang/OTP 21
Elixir 1.8.1 (compiled with Erlang/OTP 20)
* Phoenix version (mix deps): 1.4.2
* NodeJS version (node -v): v11.10.1
* NPM version (npm -v): 6.7.0
* Operating system: 10.13.6

### Actual behavior

When changing a field inside inputs_for I can see that the event is submitted twice and received twice
![grafik](https://user-images.githubusercontent.com/8594605/55226671-d3a35b80-5215-11e9-8076-554684c22158.png)

### Expected behavior
Event gets send once

**Comment by alexgaribay** [comment]
@Awlexus what type of form fields (checkbox, select, etc) were triggering the duplicate event?
