### ISSUE TITLE
Proposal: `pushEvent` to myself

### ISSUE THREAD

**Issue by mveytsman** [phoenixframework/phoenix_live_view#1396]
It's natural to want to use `pushEventTo` inside a hook that's part of a component. `pushEventTo` takes a `selectorOrTarget` which is either a dom selector or an integer representing a cid. 

My experience is that I'm going to most likely want to push an event to the component that my hooked element is a part of. I ended up writing this: 
```javascript
this.pushEventTo(`[id="${this.el.id}"]`, ...)
```
which works fine but is not pretty or that obvious.

Some options I'm thinking of:
1. Pass the element itself: `pushEventTo(this.el,..)` 
2. Expose an `owner` or `myself` attribute to the hook that gives us the view or component that owns it.
3. Have a `pushEventToMyself` method.

What do you think?

**Comment by kelvinst** [comment]
> 1. Pass the element itself: pushEventTo(this.el,..)

Of the ones proposed, I prefer this one. I think I can open a PR for it if no one else is interested.

**Comment by narrowtux** [comment]
> Pass the element itself: pushEventTo(this.el,..)

that would also make it possible to push to the parent LiveComponent very easily, i.e. 

```javascript
pushEventTo(this.el.parentElement, ...)
```
