### ISSUE TITLE
LiveComponent appended instead of patched when parent changes

### ISSUE THREAD

**Issue by rkeulemans** [phoenixframework/phoenix_live_view#1398]
### Environment

* Elixir version (elixir -v): 1.11.3
* Phoenix version (mix deps): 1.5.8
* Phoenix LiveView version (mix deps): 0.15.4
* NodeJS version (node -v): v14.15.4
* NPM version (npm -v): 7.6.3
* Operating system: MacOS Big Sur 11.2.3
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Problem
I am trying to encapsulate conditional UI visibility state in a LiveComponent called GroupLive. When a button is clicked, the visible content of the group changes to one of the GroupItemLive LiveComponents.

### Actual behavior
While the code works as expected, the GroupItemLive components are not patched, but appended to the DOM.

### Expected behavior
Components are patched instead of appended to the DOM.

### Details
- Repo: https://github.com/rkeulemans/bug_demo

![Untitled](https://user-images.githubusercontent.com/15815946/114040388-d95fbd00-9883-11eb-878b-929dffa74530.gif)

Parent:
```elixir
defmodule BugDemoWeb.ParentLive do
  use BugDemoWeb, :live_view

  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  def render(assigns) do
    ~L"""
    <h1>Parent</h1>
    <%= for i <- 1..3 do %>
      <%= live_component @socket, BugDemoWeb.GroupLive, id: Integer.to_string(i) %>
    <% end %>
    """
  end
end
```

GroupLive:
```elixir
defmodule BugDemoWeb.GroupLive do
  use Phoenix.LiveComponent
  use Phoenix.HTML

  def mount(socket) do
    {:ok, assign(socket, selected_id: get_id(socket.assigns, 1))}
  end

  def render(assigns) do
    ~L"""
    <h3>Group <%= @id %></h3>
    <%= for i <- 1..3 do %>
    <button phx-click="toggle-group-item" phx-value-id="<%= i %>" phx-target="<%= @myself %>">Show <%= i %></button>
    <% end %>
    <%= for i <- 1..3 do %>
      <%= live_component @socket, BugDemoWeb.GroupItemLive, show: @selected_id == get_id(assigns, i), id: get_id(assigns, i)  %>
    <% end %>
    """
  end

  def get_id(assigns, item_id) do
    "#{assigns.myself.cid}-#{item_id}"
  end

  def handle_event("toggle-group-item", %{"id" => id}, socket) do
    {:noreply, assign(socket, selected_id: get_id(socket.assigns, id))}
  end
end
```

```elixir
GroupItemLive:
defmodule BugDemoWeb.GroupItemLive do
  use Phoenix.LiveComponent
  use Phoenix.HTML

  def mount(socket) do
    {:ok, socket}
  end

  def render(assigns) do
    ~L"""
    <div <%= unless @show do %> style="display: none;" <% end %>>
    <h5>Group Item <%= @id %></h5>
    </div>
    """
  end
end
```

**Comment by josevalim** [comment]
Correct. If you want to guarantee they are patched, then you most add the `id` attribute to them.

**Comment by rkeulemans** [comment]
Where exactly should I add an `id`? If I am correct, all used LiveComponents already have unique `id's.`

**Comment by josevalim** [comment]
Sorry, I double checked and I misunderstood the issue. The components are literally being added (i.e. duplicated) on the page. Is this correct?

**Comment by rkeulemans** [comment]
Correct.

**Comment by mcrumm** [comment]
Hi @rkeulemans - I did a little debugging, and if you run `liveSocket.enableDebug()` from your browser's dev console and then start clicking buttons, you will see many duplicate ID errors (for ids generated by LiveView).

Curiously however, if you add a single div that wraps everything in GroupLive, the errors disappear:

```
~L"""
<div>
  <h3>Group <%= @id %></h3>
  ...
</div>
"""
```

// @josevalim

**Comment by mcrumm** [comment]
Thanks for the clarification @josevalim - I would go so far as to say that all LiveComponents should have a single root element, but I realize there is no hard requirement for that to be true :)

**Comment by josevalim** [comment]
A heads up: we are introducing HEEx/.heex/~H templates in Phoenix LiveView v0.16 and they will enforce stateful components only have a single element at the root. So I will close this. Thanks!
