### ISSUE TITLE
Uploading file to memory

### ISSUE THREAD

**Issue by gugahoa** [phoenixframework/phoenix_live_view#1399]
Hi all,
I was looking into using LiveView to handle file upload, and it [seems that it saves the file on disk](https://github.com/phoenixframework/phoenix_live_view/blob/v0.15.4/lib/phoenix_live_view/upload_channel.ex#L38-#L39).

Is there anything barring us from creating a config where it would be saved on memory?

**Comment by josevalim** [comment]
Not at the moment. Keep in mind keeping it in memory can be very prone to attacks, as people can just have a bunch of concurrent clients uploading data and cause you to run out of memory. But you can load it from disk after it has been written.
