### ISSUE TITLE
@socket.assigns unavailability prevents accessing previously assigned vars in mount callback

### ISSUE THREAD

**Issue by dzhlobo** [phoenixframework/phoenix_live_view#1402]
Since [0.11.1](https://github.com/phoenixframework/phoenix_live_view/blob/master/CHANGELOG.md#0111-2020-04-08), `@socket.assigns` [no longer available](https://github.com/phoenixframework/phoenix_live_view/pull/726) and it prevents me assigning variables that depends on previously assigned variables:

```elixir
def mount(_params, session, socket) do
  {
    :ok,
    socket
    |> fetch_current_user(session)
    |> fetch_dashboard()
  }
end

def fetch_current_user(socket, %{"user_id" => user_id}) do
  assign(socket, :current_user, App.Users.get!(user_id))
end

def fetch_dashboard(socket) do
  assign(socket, :dashboard, socket |> current_user() |> App.Dashboards.for_user())
end

def current_user(socket) do
  socket.assigns[:current_user]
end
```

Instead, I'm probably forced to write something like this:
```elixir
def mount(_params, %{"user_id" => user_id}, socket) do
  user = App.Users.get!(user_id)
  dashboard = App.Dashboards.for_user(user)
  {:ok, assign(socket, current_user: user, dashboard: dashboard)}
end
```

Which is okay, but that's not how I wanted to write it from the beginning. What do you think about it?

Also, I have a bunch of helper functions for views, including one for current user:
```elixir
def current_user(conn) do
  conn.assigns[:current_user]
end
```

If `@socket.assigns` were available, it would work for `conn` and for `socket`. I could have shared helper function for live and normal views but it's not possible.

**Comment by dzhlobo** [comment]
Ah, I forgot that with approach when we load all variables first and then assign them to socket
```elixir
def mount(_params, %{"user_id" => user_id}, socket) do
  user = App.Users.get!(user_id)
  dashboard = App.Dashboards.for_user(user)
  {
    :ok,
    assign(socket, current_user: user, workspace: workspace)
  }
end
```
it seems not possible to use `assign_new`.

**Comment by josevalim** [comment]
Assigns is available in the fashion you want to use both. It is not available only inside the render function.
