### ISSUE TITLE
Add LiveComponent.render/2 function or similar

### ISSUE THREAD

**Issue by DaTrader** [phoenixframework/phoenix_live_view#1403]
### Actual behavior

Given the following UC requirements:
1. The component should be capable of overwriting the same element and keep the same CID upon doing so (e.g. when flagging itself for deletion in its appended/prepended container);
2. The overwriting component HTML should be allowed to be totally different than the overridden ones' (other than the id of course) i.e. there should be a way to condition diverse variations of the component template as a whole;
3. Having the component template in its own html.leex file should always be a viable alternative;
4. A component template should always have the same scope as the component and be capable of nesting other templates that have the scope of the component (and not a LiveView's scope as in with using the Phoenix.View.render/3 function).

Currently, the only way to meet the #1 and #2 requirements is to write template variations in the component render callbacks i.e.
```
    
        use Phoenix.LiveComponent
        
        def render( %{ delete: true} = assigns) do
          ~L"""
          <div id="<%= @id %>" data-delete="true"></div>
          """
        end
        def render( assigns) do
          ~L"""
          <div id="<%= @id %>"
                [ whole lot of different attributes than the delete variation]
                >
               [ other nested elements]
           </div>
          """
        end

```
#3 when using a template with the same name as the component, is conflicting #2 for the below does not always work (may exhibit strange behavior of always rendering the first block under the if statement and never the block under the else. What may be the reason for why a conditional rendering of the kind won't sometimes work properly, I don't know but I guess it may be related to the constraint that a component template must always start with an element tag. I could elaborate on the side effects of the pattern below if considered a bug, but not here.

SomeComponent.html.leex:

```
        <%= if @delete do %>
          <div id="<%= @id %>" data-delete="true"></div>
        <% else %>
          <div id="<%= @id %>"
            [ whole lot of different attributes than the delete case]>
            [ other nested elements]
          </div>
        <% end %>

```
#4 is simply not the case and AFAIK we lack a way to render nested component templates within the same component scope.

### Expected behavior

All that is required is a LiveComponent.render/2 function (or the equivalent) that makes the following possible:

```
        defmodule SomeComponent do
          use Phoenix.LiveComponent
        
          def render( %{ delete: true} = assigns) do
            ~L"""
            <div id="<%= @id %>" data-delete="true"></div>
            """
          end
          def render( assigns) do
            render( "some_component_update.html", assigns)
          end
        end

```
With the emphasis that both referenced template files should be located in the same folder as the component, have its scope so they can invoke its module functions, and of course, invoke the same render2/ function to nest other such templates.

**Comment by josevalim** [comment]
In this case, your best option is to delegate to a view:

```elixir
def render(assigns) do
  if this?(assigns) do
    MyView.render("foo.html", assigns)
  else
    MyView.render("bar.html", assigns)
  end
end
```

We don't plan to add extra conveniences beyond this at the moment.

**Comment by DaTrader** [comment]
That's too sad for this is exactly what I've been doing all along, but as my app has grown in size, at a certain point I had to take a different route, the one with the L sigil in the render functions instead, as I can't have the separation of concerns reflected in my files if I go with the views. As you well know, when you go that route the templates don't share the component scope (are able access the component as if they were local to them) and, worse, they must reside along with the the view templates instead of being in their component folder where they logically belong.

**Comment by josevalim** [comment]
I believe you should be able to `use Phoenix.Template` and import `render/2` templates into your LiveView. The logic that collocates in LiveView is also quite contains if you want to reproduce it: https://github.com/phoenixframework/phoenix_live_view/blob/master/lib/phoenix_live_view/renderer.ex#L1

Some of it is error checking that is exclusive to LiveView and which you can eliminate.

**Comment by DaTrader** [comment]
I'll give it a try. Thanks.

**Comment by DaTrader** [comment]
@josevalim 

Here's what I've come up with following your suggestion, and it works! Thanks again, Jose!

```
defmodule LiveComponent.Helpers do
  @moduledoc """
  Provides a @before_compile macro for our LiveComponents to have as many collocated templates as needed.
  Each template name should start with the underscored name of the component module followed by a suffix.

  ex:
      defmodule MyComponent do
        use Phoenix.LiveComponent
        require LiveComponent.Helpers
        @before_compile LiveComponent.Helpers

        @impl true
        def render( %{ delete: :true} = assigns) do
          render( "my_component_delete.html", assigns)
        end
        def render( assigns) do
          render( "my_component_enjoy.html", assigns)
        end
      end
  """

  defmacro __before_compile__( env) do
    render? = Module.defines?( env.module, { :render, 1})
    if render? do
      root = Path.dirname( env.file)
      filename = template_pattern( env)
      templates = Phoenix.Template.find_all( root, filename)

      for template <- templates do
        basename = Path.basename( template, Path.extname( template))
        relative_path = Path.relative_to_cwd( template)
        ext = template |> Path.extname() |> String.trim_leading( ".") |> String.to_atom()
        engine = Map.fetch!( Phoenix.Template.engines(), ext)
        ast = engine.compile( template, filename)

        quote do
          @external_resource unquote( relative_path)
          def render( unquote( basename), var!( assigns)) when is_map( var!( assigns)) do
            unquote( ast)
          end
        end
      end
    end
  end

  defp template_pattern( env) do
    env.module
    |> Module.split()
    |> List.last()
    |> Macro.underscore()
    |> Kernel.<>( "*.html")
  end
end

```
