### ISSUE TITLE
Testing regular messages fails when using element/2

### ISSUE THREAD

**Issue by dmorneau** [phoenixframework/phoenix_live_view#1406]
### Environment

* Elixir version (elixir -v): Elixir 1.12.0-rc.0 (3df04b2) (compiled with Erlang/OTP 24)
* Phoenix version (mix deps): 1.5.8
* Phoenix LiveView version (mix deps): 0.15.4
* Operating system: macOS

### Actual behavior

When testing a LiveView with regular messages (handle_info/2), the documentation suggests using render/1 to test the side-effect:

https://hexdocs.pm/phoenix_live_view/Phoenix.LiveViewTest.html#module-testing-regular-messages

This works fine when passing a view to render/1, but not when passing a subtree (from element/2). The former seems to do a synchronous call and reliably return the updated HTML, whereas the latter returns the old HTML as it was before the message was processed.

This makes tests a bit awkward since we have to call render/1 once to ensure the message has been processed, then again with a subtree to do the actual assertion.

### Expected behavior

Perhaps rendering a subtree could go through the same synchronous call as rendering the entire view (if that's not the case?), or if not it would be good to mention in the documentation that render/1 must be called with a view to ensure messages have been processed.

**Comment by josevalim** [comment]
Both element and render will synchronize it. You are more likely running into a race condition. What do you do in your handle_info?

**Comment by josevalim** [comment]
I have confirmed in the source that both of them sync before, so this is more likely a race due. They are just different enough to make it behave slightly different. Let me know what your handle_info does and I can provide more context.

**Comment by dmorneau** [comment]
Ah yes! I see what's going on, thank you. There's actually two views, the main one and a sidebar inside the live layout. I'm trying to test sidebar notifications, but I was calling render on the main view returned by live/2, which didn't synchronize the sidebar (I didn't notice since render returns the whole HTML - not just the main view). Using live_children or live_isolated should fix it.
