### ISSUE TITLE
Question about `push_event` & `push_redirect`

### ISSUE THREAD

**Issue by edisonywh** [phoenixframework/phoenix_live_view#1408]
I can see from the docs that `push_event` doesn't work if we do a `push_redirect` right after that,

https://github.com/phoenixframework/phoenix_live_view/blob/v0.15.4/lib/phoenix_live_view/utils.ex#L208-L214

But I'm wondering if this is a technical limitation or just status quo?

For context, I'm basically trying to implement a toast/notification, the set-up is like this:

- the actual notification DOM node on layout
- a renderless DOM element that only does one thing - include a `phx-hook='Notification'`
- the `Notification` hook listens for `push_event` from server, and then it dispatches a JS event to the DOM node on layout and have Alpine handle the pop-up/timeout for the notification.

This is the actual PR with some other noise, so apologies for that https://github.com/edisonywh/backoffice/pull/32/files

(EDIT: I extracted the relevant bits out)

```html
# layout.html
<div
            id="bo-notification"
            x-data="{ open: false, title: '', subtitle: '' }"
            x-on:bo-notification="open = true; title = $event.detail.title; subtitle = $event.detail.subtitle"
            x-init="$watch('open', value => {
              if(value) {
                setTimeout(function () {
                  open = false
                  title = ''
                  subtitle = ''
                }, 3000)
              }
            })"
            class="z-10 fixed inset-0 flex items-end justify-center px-4 py-6 pointer-events-none sm:p-6 sm:items-start sm:justify-end"
          >
```

```html
<span style="display: hidden" phx-hook="Notification" id="notification-hook"></span>
```

```js
Hooks.Notification = {
  mounted() {
    let notification = document.querySelector("#bo-notification")
    this.handleEvent("bo-notification", ({ title, subtitle }) => {
      var event = new CustomEvent('bo-notification', {
        detail: {
          title: title,
          subtitle: subtitle
        }
      });
      notification.dispatchEvent(event);
    })
  }
}
```

```elixir
# somewhere in my FormComponent's `save` action..
# this doesn't work
socket
|> push_notification(
  title: "Success!",
  subtitle: "#{action_msg} resource [#{resource.id}]"
)
|> push_redirect(to: socket.assigns.return_to)
```

**Comment by josevalim** [comment]
I can't remember the reason for said limitation: if it was to simplify the initial implementation or due to some inherent limitation. I would suggest to try exploring a PR that addresses it and then we will know for sure. :) Thanks!
