### ISSUE TITLE
LiveView can actually update when phx-update is append or prepend

### ISSUE THREAD

**Issue by vfsoraki** [phoenixframework/phoenix_live_view#1410]
I didn't know about this, and [docs](https://hexdocs.pm/phoenix_live_view/dom-patching.html) do not mention that this works.

You can render a list of items with DOM ids and a temporary assign. When you add an item, if the item is already rendered before, it is just updated (matched with DOM id).

I suppose it is the expected behavior, but the docs fail to mention this.

**Comment by josevalim** [comment]
it is expected behaviour, yes. A PR to amend ### ### docsis welcome.
