### ISSUE TITLE
Compiler warning: variable "socket" is unused in live_component/3

### ISSUE THREAD

**Issue by arnodirlam** [phoenixframework/phoenix_live_view#1413]
### Environment

* Elixir version (elixir -v): 1.11.2
* Phoenix version (mix deps): 1.5.8
* Phoenix LiveView version (mix deps): 0.15.4
* Operating system: macOS

### Actual behavior

After upgrading to 0.15.4, compiler warnings start to appear:

```
==> phoenix_live_dashboard
Compiling 36 files (.ex)
warning: variable "socket" is unused (if the variable is not meant to be used, prefix it with an underscore)
  lib/phoenix/live_dashboard/page_live.ex:208: Phoenix.LiveDashboard.PageLive.render_page/3

warning: variable "socket" is unused (if the variable is not meant to be used, prefix it with an underscore)
  lib/phoenix/live_dashboard/page_live.ex:232: Phoenix.LiveDashboard.PageLive.live_modal/3

Generated phoenix_live_dashboard app
==> my_app
Compiling 48 files (.ex)
warning: variable "socket" is unused (if the variable is not meant to be used, prefix it with an underscore)
  lib/phaseshift_web/live/live_helpers.ex:22: PhaseshiftWeb.LiveHelpers.live_modal/3
```

The warning in `my_app` is on code that was generated using `mix phx.gen.live` without modifications:

```elixir
  1 defmodule PhaseshiftWeb.LiveHelpers do
  2   @moduledoc "Helpers to be used in Live views."
  3
  4   import Phoenix.LiveView.Helpers

 22   def live_modal(socket, component, opts) do
 23     path = Keyword.fetch!(opts, :return_to)
 24     modal_opts = [id: :modal, return_to: path, component: component, opts: opts]
 25     live_component(socket, PhaseshiftWeb.ModalComponent, modal_opts)
 26   end
```

I believe this was introduced [here](https://github.com/phoenixframework/phoenix_live_view/compare/v0.15.3..v0.15.4?diff=split#diff-772657b5f70b8bd2605ba308b37fca3a4cac3e478d3ee87f1186a8eba646b5d6R210-R211).

I know, it's just a compiler warning, but we use `--warnings-as-errors` in our CI pipeline, the warning is also pretty confusing without looking into the phoenix_live_view code (macro), and it is unclear to me how it should be solved.

### Expected behavior

For now, I'd suggest mentioning in the release notes how to upgrade existing code (or newly generated code) to 0.15.4.

Thank you 🙏

**Comment by josevalim** [comment]
This has been fixed in master. :)
