### ISSUE TITLE
live_isolated/3 connect_params option doesn't work as documented?

### ISSUE THREAD

**Issue by garthk** [phoenixframework/phoenix_live_view#1414]
G'day!

### Environment

* Elixir version: Elixir 1.11.4 (compiled with Erlang/OTP 23)
* Phoenix version: 1.5.8 
* Phoenix LiveView version: 0.15.4
* NodeJS version: v14.16.0
* NPM version: 6.14.11
* Operating system: macOS
* Browsers you attempted to reproduce this bug on (the more the merrier): mix test
* Does the problem persist after removing "assets/node_modules" and trying again? yes

### Actual behavior

Given this test code:

```elixir
assert {:ok, %View{module: MainView}, <<_::binary>>} =
         live_isolated(conn, MainView, session: %{}, connect_params: %{"param" => value})
```

When `MainView.mount/3` is called with a connected socket, `get_connect_params(socket)` doesn't return the `connect_params` from the `opts` argument to `live_isolated/3`. 

Investigating,`LiveView.Static.render/3` returns an `{:ok, content, socket_assigns}` and the case clause doesn't use the `opts` argument. If I'm reading it right, the only use of `opts` is after it's re-bound in the match of the second clause?

```elixir
# lib/phoenix_live_view/test/live_view_test.ex:220

  defmacro live_isolated(conn, live_view, opts \\ []) do
    quote bind_quoted: binding(), unquote: true do
      unquote(__MODULE__).__isolated__(conn, @endpoint, live_view, opts)
    end
  end

  @doc false
  def __isolated__(conn, endpoint, live_view, opts) do
    put_in(conn.private[:phoenix_endpoint], endpoint || raise("no @endpoint set in test case"))
    |> Plug.Test.init_test_session(%{})
    |> Phoenix.LiveView.Router.fetch_live_flash([])
    |> Phoenix.LiveView.Controller.live_render(live_view, opts)
    |> connect_from_static_token(nil)
  end

# lib/phoenix_live_view/controller.ex:34

  def live_render(%Plug.Conn{} = conn, view, opts \\ []) do
    case LiveView.Static.render(conn, view, opts) do
      {:ok, content, socket_assigns} ->
        conn
        |> Phoenix.Controller.put_view(LiveView.Static)
        |> LiveView.Plug.put_cache_headers()
        |> Phoenix.Controller.render(
          "template.html",
          Map.merge(socket_assigns, %{content: content, live_module: view})
        )

      {:stop, %Socket{redirected: {:redirect, opts}} = socket} ->
        conn
        |> put_flash(LiveView.Utils.get_flash(socket))
        |> Phoenix.Controller.redirect(Map.to_list(opts))

      {:stop, %Socket{redirected: {:live, _, %{to: to}}} = socket} ->
        conn
        |> put_flash(LiveView.Utils.get_flash(socket))
        |> Plug.Conn.put_private(:phoenix_live_redirect, true)
        |> Phoenix.Controller.redirect(to: to)
    end
  end
```

### Workaround

Use `Phoenix.LiveViewTest.put_connect_params/2`, instead:

```elixir
assert {:ok, %View{module: MainView}, <<_::binary>>} =
          conn
          |> put_connect_params(%{"param" => value})
          |> live_isolated(conn, MainView, session: %{})
```

### Expected behavior

`connect_params` works [as documented](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveViewTest.html#live_isolated/3-options), if I'm reading it right, or is no longer documented.

**Comment by josevalim** [comment]
Given we have put_connect_params, I find that a clearer API. Can you please send a PR that removes the option from the docs then? Thank you! :heart:

**Comment by garthk** [comment]
No worries, @josevalim!
