### ISSUE TITLE
After live_redirect form does not throw phx-change

### ISSUE THREAD

**Issue by kszambelanczyk** [phoenixframework/phoenix_live_view#1424]
### Environment

* Elixir version (elixir -v): 1.11.2
* Phoenix version (mix deps): 1.5.7
* Phoenix LiveView version (mix deps): 0.15.5
* NodeJS version (node -v): 14.3.0
* NPM version (npm -v): 6.14.5
* Operating system: Linux Mint
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome  90.0.4430.85
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

I have a problem with handling phx-change on a form in LiveView. I am creating a search field for filtering a list of objects. The field also has a reset button. It looks like this:
```
<form phx-change="search-change">
  <input type="text" name="search" value="<%= @search_list %>" placeholder="Search..." phx-debounce="500" />
  <button type="button" phx-click="search-change" phx-value-search="">X</button>
</form>
```
The search field handler is in LiveView, not in a LiveView component. Handler is implemented this way:
```
@impl true
def handle_event("search-change", _, socket) do
  IO.inspect("Searching...")
  {:noreply, socket}
end
```
Everything works as expected when I start from the page or refresh where the list of objects and search field are. But when I live_redirect to another page and then live_redirect back, the form does not throw events anymore. The reset button still works and throws events. I am new to LiveView, maybe I am missing something but what could be the issue here?

**Comment by josevalim** [comment]
Everything looks good to me! I would try to reproduce the issue in an app you can share so others can take a deeper look at it.

**Comment by kszambelanczyk** [comment]
Thank you for quick answer
Here is a whole LiveView module:
```
defmodule EzswWeb.ObjectTypeLive.Index do
  @moduledoc false
  use EzswWeb, :live_view

  alias Ezsw.ObjectTypes

  @impl true
  def mount(_params, session, socket) do
    socket = assign_defaults(session, socket)

    {:ok,
     assign(socket,
       object_types: list_object_types(),
       search_list: ""
     )}
  end

  # @impl true
  # def handle_params(params, _url, socket) do
  #   {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  # end

  @impl true
  def handle_event("delete", %{"id" => id}, socket) do
    object_type = ObjectTypes.get_object_type!(id)
    {:ok, _} = ObjectTypes.delete_object_type(object_type)

    {:noreply, assign(socket, :object_types, list_object_types())}
  end

  @impl true
  def handle_event("search-change", _, socket) do
    IO.inspect("Searching...")
    {:noreply, socket}
  end

  # @impl true
  # def handle_event("search-change", %{"search" => search}, socket) do
  #   {:noreply, assign(socket, object_types: list_object_types(search), search_list: search)}
  # end

  defp list_object_types(search \\ nil) do
    ObjectTypes.list_object_types(no_user_types: true, search: search)
  end
end
```

and a template:

```
<h1>Typy obiektów</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Schemable</th>
      <th>Photoable</th>
      <th>Parametable</th>
      <th>Parentable</th>
      <th>Mapable</th>
      <th>Threatable</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <div>
      <form phx-change="search-change">
        <input type="text" name="search" value="<%= @search_list %>" placeholder="Search..." phx-debounce="500" />
        <button type="button" phx-click="search-change" phx-value-search="">X</button>
      </form>
    </div>

    <%= for object_type <- @object_types do %>
      <tr>
        <td><%= object_type.name %></td>
        <td><%= object_type.description %></td>
        <td><%= if object_type.schemable, do: "TAK", else: "-" %></td>
        <td><%= if object_type.photoable, do: "TAK", else: "-" %></td>
        <td><%= if object_type.parametable, do: "TAK", else: "-" %></td>
        <td><%= if object_type.parentable, do: "TAK", else: "-" %></td>
        <td><%= if object_type.mapable, do: "TAK", else: "-" %></td>
        <td><%= if object_type.threatable, do: "TAK", else: "-" %></td>
        <td>
          <span><%= live_redirect "Show", to: Routes.object_type_show_path(@socket, :show, object_type) %></span>
          <span><%= live_redirect "Edit", to: Routes.object_type_form_path(@socket, :edit, object_type) %></span>
          <span><%= link "Delete", to: "#", phx_click: "delete", phx_value_id: object_type.id, data: [confirm: "Are you sure?"] %></span>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

<span><%= live_redirect "Nowy typ obiektu", to: Routes.object_type_form_path(@socket, :new) %></span>
```
If anything else is needed then I will share

**Comment by josevalim** [comment]
We ask folks to isolate this into a small application because a huge amount of times the bug is discovered after stripping it down. So if you can isolate it into a small app with the minimum, it would be very appreciated. Thanks @kszambelanczyk !

**Comment by kszambelanczyk** [comment]
Here is a repository with a basic app created for that issue. I have created only two LiveView modules one with list and search field, and the other just to have ability to redirect to. On my machine issue is still there in this isolated app
https://github.com/kszambelanczyk/form-event-issue

**Comment by kszambelanczyk** [comment]
After some investigation, here is where the event is lost in phoenix_live_view.js
```
  bindForms(){
    .....
    for(let type of ["change", "input"]){
      this.on(type, e => {
        let input = e.target
        let phxEvent = input.form && input.form.getAttribute(this.binding("change"))
        // here form gets null after redirect
        if(!phxEvent){ return }
```
On first draw the variable input.form exists but after redirect and redirecting back input.form is null
By the way, I do not know why the inner part of the form is being pushed outside:
```
<div>
  <form phx-change="search-change"></form>
  <input type="text" name="search" value="" placeholder="Search...">
  <button type="button" phx-click="search-change" phx-value-search="">X</button>
</div>
```

**Comment by josevalim** [comment]
I am pretty sure the issue is being caused because you have a div inside a tbody and that's not allowed. So the browser is rewriting the HTML into something invalid. Move the form out of the table (or move it inside a tr) and see if the issue persists, if it doesn't, you have to write your markkup.

**Comment by kszambelanczyk** [comment]
You are right! Everything is working now. Thank you for your help.
