### ISSUE TITLE
Add topbar introduction to changelog

### ISSUE THREAD

**Issue by florish** [phoenixframework/phoenix_live_view#1430]
While reviewing the generated code from `mix phx.new --live` (Phoenix 1.5.8), my eye caught`topbar` instead of `nprogress` in the generated JavaScript. Some googling led me to https://github.com/phoenixframework/phoenix_live_view/issues/828 , which helped me understand why this change was made.

As I have a couple of LiveView based applications running in different versions, I hoped to see this change listed in the changelog as well to help me take the correct steps when upgrading, but unfortunately, it doesn't seem to be in there.

Would it be possible to add this? (I'd do this myself if I was sure which version introduced the change.)

**Comment by josevalim** [comment]
Done here: https://github.com/phoenixframework/phoenix/commit/23c101349ba532d3d922c221d725ea43252b6205 thanks.
