### ISSUE TITLE
Proposal: Idiomatic JS changes

### ISSUE THREAD

**Issue by bcardarella** [phoenixframework/phoenix_live_view#1431]
I'd like to discuss the cons/benefits of the following for the liveview.js file:

1. breaking up the single `phoenix_live_view.js` file into separate class files that the build pipeline will compile into a single file for distribution
2. Don't pre-compile the js in the project, allow the consuming app's build pipeline to control this
3. Implementing [source maps](https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Use_a_source_map) for the `MIX_ENV=dev` environment.

## Breaking up the files

I can understand why the mono-file exist, especially during the time when LiveView was under rapid development. However, as the complexity of the JS continues to grow the project will benefit from having the individual files broken up so the project is more easily managed. The build pipeline can take advantage of [ES6 modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules) which leads to the next point

## Don't pre-compile the js

Currently both `phoenix_live_view` and `phoenix` precompile the JS into `priv/static`. The downside to this is that the consuming applications now don't get to apply their own compilation preferences. I am sympathetic to reducing the potential problems with core team having to triage issues from those that are trying to draw outside the lines with their JS build systems. However, the upside on this gets me into the next issue

## Implementing source maps for `dev`

Right now with the JS being pre-compiled we don't have an opportunity to get environment-specific builds. If we allow the compilation of the JS during the consuming app's build phase then we can inject developer ergonomics like source maps. Right now as a consumer of LiveView if I am either finding potential bugs or looking to expand the functionality contributing back to the project is very difficult because at run-time inspecting and debugging the LiveView js is (nearly) impossible due to the compiled code.

I'm willing to volunteer my time to implement these changes if they're of interest back to Core.

As far as order of how to implement this. I suggest the following: #2, #3, #1. This punts on changing the original JS file to the very end this way to can isolate and eliminate and edge cases that may arise from the build pipeline and source maps changes. I also suspect that this would need to be done upstream on `phoenix` first.

**Comment by chrismccord** [comment]
Done!
