### ISSUE TITLE
Tests: render_upload fails with custom progress function

### ISSUE THREAD

**Issue by Softknobs** [phoenixframework/phoenix_live_view#1432]
### Environment

* Elixir version (elixir -v):
Erlang/OTP 21 [erts-10.3] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]
Elixir 1.9.2 (compiled with Erlang/OTP 20)

* Phoenix version (mix deps):  1.5.8
* Phoenix LiveView version (mix deps): 0.15.5
* NodeJS version (node -v): v12.13.0
* NPM version (npm -v): 6.12
* Operating system: Windows 10 x64
* Browsers you attempted to reproduce this bug on (the more the merrier): Brave
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior
With `allow_upload(:media_file, auto_upload: true, progress: &handle_progress/3, accept: :any, max_entries: 512)` I try to upload a file in a test:
 ```
uploaded_file = file_input(view, "#wizard_upload_form", :media_file, [%{
  last_modified: 1_594_171_879_000,
  name: "sirius.mid",
  content: File.read!("test/site/uploads/sirius.mid"),
  size: 444,
  type: "audio/midi"
}])

render_upload(uploaded_file, "sirius.mid")
```
using the example handle_progress code:
```
  defp handle_progress(:synth_file, entry, socket) do
    if entry.done? do
      uploaded_file =
        consume_uploaded_entry(socket, entry, fn %{} = meta ->
          IO.inspect("Entry: #{Macro.to_string(entry)}")
        end)

      {:noreply, put_flash(socket, :info, "file #{uploaded_file.name} uploaded")}
    else
      {:noreply, socket}
    end
  end
```
I get this error:
```
     ** (exit) exited in: GenServer.call(#PID<0.434.0>, {:chunk, "sirius.mid", 100, #PID<0.432.0>, #Phoenix.LiveViewTest.Element<selector: "#wizard_upload_form input[type=\"file\"][name=\"media_file\"]", text_filter: nil, ...>}, 5000)
         ** (EXIT) shutdown: :closed
     code: html = render_upload(uploaded_file, "sirius.mid")
     stacktrace:
       (elixir) lib/gen_server.ex:1009: GenServer.call/3
       (phoenix_live_view) lib/phoenix_live_view/test/live_view_test.ex:1391: Phoenix.LiveViewTest.render_chunk/3
```
Running the same code without custom progress fuction does not fail:
 `allow_upload(:media_file, auto_upload: true, accept: :any, max_entries: 512)`

**Comment by mcrumm** [comment]
Hi @Softknobs I believe this was fixed in #1409 - could you try latest and see if the problem persists?

**Comment by Softknobs** [comment]
Hi @mcrumm, 

Thanks. I tried again with this dependency `{:phoenix_live_view, git: "https://github.com/phoenixframework/phoenix_live_view.git"}` but I still get the error.

I tried to look at the liveview code but it's beyond what I can understand at this point. Still when debugging I feel like the match in the `receive` of the code of `handle_call({:chunk, ...})` is never true:
```
    receive do
      {^ref, {:ok, _}} ->
        {:reply, :ok, new_state}
    after
      1000 -> exit(:timeout)
    end
```
It looks that only `:garbage_collect` is received when using a less restrictive match expression in this `receive`. I don't know if this is relevant or not as I don't understand much what's happening here.

**Comment by iwarshak** [comment]
I am also experiencing the same issue. I did a git bisect and narrowed it down to this commit: https://github.com/phoenixframework/phoenix_live_view/commit/11496d79de7e593af4877bc68ad340af1fc8c08e

I am also using a custom `handle_progress` function too, FWIW
