### ISSUE TITLE
LiveViewTest does not support `phx-trigger-action`

### ISSUE THREAD

**Issue by a8t** [phoenixframework/phoenix_live_view#1436]
I want to be able to write a test for a LiveView that calls a login form using `phx-trigger-action`, as per [this](https://hexdocs.pm/phoenix_live_view/form-bindings.html#submitting-the-form-action-over-http). Currently, it seems that LiveViewTest tooling does not cause the action to be triggered. In other words, it works in my browser, but not in my test after `render_submit`ing. 

I believe there are two options for a solution here, and I'm happy to contribute to either given a bit of direction:

1. Support `phx-trigger-action` by adding some test helpers to LiveViewTest (I'm guessing it'd go around [here](https://github.com/phoenixframework/phoenix_live_view/blob/master/lib/phoenix_live_view/test/dom.ex#L219))
2. Suggest a workaround in the documentation, so that developers don't have to dig through the forum to find [this thread](https://elixirforum.com/t/testing-liveview-form-with-phx-trigger-action/37737/5?u=a8t).

The workaround from the link option 2 (h/t @paulstatezny) is to 'manually' call the route from the test after `render_submit`. This is a barely-good-enough solution, obviously, considering the POST is not actually tied to the code that it's testing:
```elixir

test "sample test" do
  # ...

  show_live
  |> form("#some_form", foo: %{field: "value"})
  |> render_submit()

  # LiveViewTest doesn't jive well with phx_trigger_action yet
  # So manually simulate what happens when they submit the form

  post(
    conn,
    Routes.foo_path(conn, :create),
    %{"foo" => %{"field" => "value"}}
  )
end
```

I'd like to hear from experienced contributors if option 1 is viable. If not, is there a better workaround than the one I pasted above?

Thanks for all the hard work :)

**Comment by josevalim** [comment]
@a8t I think we can add something like follow_trigger_action, that will dispatch the form with the given parameters to the chosen URL and return a conn, similar to how follow_redirect works. A PR is welcome!

**Comment by a8t** [comment]
Thanks for the starting point, I'll take a look!

**Comment by a8t** [comment]
@josevalim do you think we also need a `render_trigger_action`?

**Comment by josevalim** [comment]
No, a single function, called either `render_trigger_action` or `follow_trigger_action` is enough. It is going to do the request behind the scenes and return a `conn`.

**Comment by a8t** [comment]
@josevalim Sorry, I'm finding that I can't figure out how to get the action specified in the form using the existing helpers. So I have `follow_trigger_action` defined as follows:

```elixir
  defmacro follow_trigger_action(_, conn, path, body) do

    quote bind_quoted: binding() do
      conn
      |> post(path, body)
    end
  end
```

and it's implemented like this:

```elixir
      conn =
        show_live
        |> form("#lobby-form", values)
        |> render_submit()
        |> follow_trigger_action(conn, Routes.username_path(conn, :create), values)

      assert get_session(conn, :username) == "hello"
```

The test passes, so that's cool. But it's identical to the workaround presented in the original post. I think I want to get the `path` AND the `values` from the form (presumably as that first parameter). Do you think that's possible?

**Comment by josevalim** [comment]
I see. That's what you probably meant with `render_trigger_action` too. We probably need something like this:

```elixir
show_live
|> form("#lobby-form", values)
|> render_submit()

show_live
|> form("#lobby-form", values)
|> render_trigger_action()
```

And the second checks it is a form and that trigger action is set and dispatches to the given url with the given values in the form? 🤔

**Comment by a8t** [comment]
I'll try that. It was actually one of my previous implementations that I threw away because I couldn't figure out how to do those checks (but I'll try again). 

I am also starting to think that for maximal test ergonomics, the test runner should automatically mimic the client behaviour here. The behaviour is to listen to DOM patches for `phx-trigger-action` to be set, and and run the form action if so. I think that `Phoenix.LiveViewTest.ClientProxy` (or `Phoenix.LiveViewTest.DOM` which the ClientProxy uses) might be the place for this. 

The reason I think this is the case is that the other `render_*` actions model user interactions. But the user doesn't trigger the phx-trigger-action directly - instead, it's usually the *result* of other `render_*` actions. That's why this feels in between a `render_*` and a `follow_*`.

**Comment by josevalim** [comment]
The issue with doing so automatically is that it messes up the return type. It means every `render` function can now return a connection. And even more, phx-trigger-action can be set to true at any moment, which means every single operation can now trigger a request which can be confusing. That's why I think it is better to be explicit.

**Comment by paulstatezny** [comment]
@josevalim with what you're proposing, would the action be prevented if the `phx_trigger_action` condition is false? I think that would be ideal, so that tests maximally reflect what would happen when actually running the code.

**Comment by a8t** [comment]
OK, I went back to `follow_trigger_action`:

```elixir
defmacro follow_trigger_action(html, conn, body) do
  quote bind_quoted: binding() do
    {:ok, {"form", attrs, _child_nodes}} =
      html
      |> DOM.parse()
      |> DOM.maybe_one("form[phx-trigger-action")

    {"action", path} = List.keyfind(attrs, "action", 0)

    conn
    |> post(path, body)
  end
end
```

Use:

```elixir
conn =
  show_live
  |> form("#lobby-form", values)
  |> render_submit()
  |> follow_trigger_action(conn, values)
```

Notice passing in `values` twice. It's in the html but I didn't find a quick way to get them from the form's subtree yet. Maybe it's better if we have to pass it explicitly anyway, though. 

Thoughts on this? I think I can open a PR now too.

**Comment by josevalim** [comment]
Right, since we need to pass the value twice, I would prefer to pass the whole form twice, and reuse the values inside the form. As mentioned above, something like this:

```elixir
show_live
|> form("#lobby-form", values)
|> render_submit()

show_live
|> form("#lobby-form", values)
|> follow_trigger_action(conn)
```

`follow_trigger_action` will lookup the form, check that phx-trigger-action true, and then do the request with the given method as you did in your implementation. :)

**Comment by a8t** [comment]
The reason I didn't do that is that I assumed show_live is not mutated between the two uses of it, in other words phx-trigger-action won't be true unless you follow_ the action that sets it to true, which is render_submit in my use case. I can check to see if it's the case that show_live persists the state.

Thanks for all the feedback on this. Home stretch!

**Comment by a8t** [comment]
OK I think I have it!

```elixir
defmacro follow_trigger_action(
            element,
            conn,
            event_type \\ :submit
          ) do
  quote bind_quoted: binding() do
    %Element{proxy: proxy, selector: selector, form_data: form_data} = element

    {:ok, {"form", attrs, _child_nodes}} =
      element |> Phoenix.LiveViewTest.__render_triggering_event__(event_type)

    %{"action" => path, "method" => method} = Enum.into(attrs, %{})

    conn
    |> dispatch(@endpoint, method, path, form_data)
  end
end

def __render_triggering_event__(%Element{form_data: form_data} = element, event_type) do
  element
  |> render_event(event_type, form_data)
  |> DOM.parse()
  |> DOM.maybe_one("form[phx-trigger-action")
end
```

```elixir

conn =
  show_live
  |> form("#lobby-form", values)
  |> follow_trigger_action(conn)

assert get_session(conn, :username) == "hello"
```

**Comment by josevalim** [comment]
Awesome job! A couple extra notes:

@a8t the state is persisted, since the LiveView is stateful. So the idea is that you will emit an event that changes phx-trigger-action and then you will "follow" it. That's why I don't want to trigger the event within `follow_trigger_action`, because as I said in the previous comment, anything can set phx-trigger-action, even a random message. For example, someone could load a page that automatically submits a form after 5 seconds (I hope no one does this :P but you get the idea).

The other thing is that the HTML spec says the default method is "get" and the default path is the current URL, so we need to add these defaults accordingly.

Finally, one last thing regarding meta-programming: we want to minimize the code inside the `quote` as much as possible. You already did part of this by moving some logic to `__render_triggering_event__` but you want to rather put almost all there. Something like this:

```elixir
defmacro follow_trigger_action(element, conn) do
  quote bind_quoted: binding() do
    {method, path, form_data} = Phoenix.LiveViewTest.__follow_trigger_event__(element)
    dispatch(conn, @endpoint, method, path, form_data)
  end
end
```

Once we have these changes and a test, I think we are good! :D

**Comment by a8t** [comment]
What i'm finding is that with this:

> ```elixir
> show_live
> |> form("#lobby-form", values)  # <-- this form
> |> render_submit()                      #          ↑
>                                                     #   these are the same, i.e. phx-trigger-action is not being persisted between calls
> show_live                                     #          ↓ 
> |> form("#lobby-form", values) # <-- this form
> |> follow_trigger_action(conn)
> ```

**Comment by josevalim** [comment]
How is the follow trigger implementation in this case and the LiveView? I assume it still needs to call render to get the latest? Maybe something is setting it to false right after?

**Comment by a8t** [comment]
You mean in my app code? I'm doing this: https://hexdocs.pm/phoenix_live_view/form-bindings.html#submitting-the-form-action-over-http

(lmk if you'd prefer to hop to DMs or slack or something)

**Comment by a8t** [comment]
Oh, I understand your message now. Yes, I'm taking the form element, calling `render` on it, and the second time it's the same as the first time (i.e. phx-trigger-action is still not present)

**Comment by josevalim** [comment]
Ok, so let’s submit a PR with your event_type version and tests and once merged I can explore if we can simplify. Thanks :D
