### ISSUE TITLE
Generated tests are failing for boolean ecto attributes

### ISSUE THREAD

**Issue by MMore** [phoenixframework/phoenix_live_view#1437]
### Environment

* Elixir version (elixir -v): Elixir 1.11.4 (compiled with Erlang/OTP 23)
* Phoenix version (mix deps): phoenix 1.5.8
* Phoenix LiveView version (mix deps): phoenix_live_view 0.15.5
* NodeJS version (node -v): v15.14.0
* NPM version (npm -v): 7.7.6
* Operating system: MacOS 10.15.7
* Browsers you attempted to reproduce this bug on (the more the merrier): -
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Trigger

Generate LiveView etc. for a resource: `mix phx.gen.live Resources Resource resources title:string active:boolean`

### Actual behavior

Run `mix test` and get the following failing tests

```
    1) test Show updates resource within modal (TestAppWeb.ResourceLiveTest)
       test/test_app_web/live/resource_live_test.exs:94
       ** (ArgumentError) value for checkbox "resource[active]" must be one of ["false", "true"], got: ""
       code: |> render_change() =~ "can&apos;t be blank"
       stacktrace:
         (phoenix_live_view 0.15.5) lib/phoenix_live_view/test/live_view_test.ex:893: Phoenix.LiveViewTest.call/2
         test/test_app_web/live/resource_live_test.exs:104: (test)

    2) test Index updates resource in listing (TestAppWeb.ResourceLiveTest)
       test/test_app_web/live/resource_live_test.exs:54
       ** (ArgumentError) value for checkbox "resource[active]" must be one of ["false", "true"], got: ""
       code: |> render_change() =~ "can&apos;t be blank"
       stacktrace:
         (phoenix_live_view 0.15.5) lib/phoenix_live_view/test/live_view_test.ex:893: Phoenix.LiveViewTest.call/2
         test/test_app_web/live/resource_live_test.exs:64: (test)

    3) test Index saves new resource (TestAppWeb.ResourceLiveTest)
       test/test_app_web/live/resource_live_test.exs:32
       ** (ArgumentError) value for checkbox "resource[active]" must be one of ["false", "true"], got: ""
       code: |> render_change() =~ "can&apos;t be blank"
       stacktrace:
         (phoenix_live_view 0.15.5) lib/phoenix_live_view/test/live_view_test.ex:893: Phoenix.LiveViewTest.call/2
         test/test_app_web/live/resource_live_test.exs:42: (test)
```

### Expected behavior

Run `mix test` and get no failing tests.

### Issue

The tests checks for `can&apos;t be blank`, but the code includes `can&#39;t be blank`.

**Comment by josevalim** [comment]
These have been fixed in Phoenix master, which is where the generators belong. Thanks!
