### ISSUE TITLE
Default tests from phx.gen.live is generating some failing specs for `can't be blank`

### ISSUE THREAD

**Issue by sadjow** [phoenixframework/phoenix_live_view#1438]
### Environment

* Elixir version (elixir -v): Elixir 1.11.4 (compiled with Erlang/OTP 23)
* Phoenix version (mix deps): 1.5.8
* Phoenix LiveView version (mix deps): 0.15.4
* NodeJS version (node -v): v14.16.0
* NPM version (npm -v):7.11.2
* Operating system: macOS
* Browsers you attempted to reproduce this bug on (the more the merrier):  (no aplicable)
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

The generated tests are generating specs with `can&apos;t be blank` but the live view is rendering `can&#39;t be blank` and the default specs are failing.

![image](https://user-images.githubusercontent.com/177525/116787193-3280d200-aa79-11eb-99aa-0dbe14f21729.png)

### Expected behavior

I think it should generate specs with right string: `can't be blank`

**Comment by sadjow** [comment]
Note: I am using gettext, but the default generated from `mix gettext.extract --merge`
![image](https://user-images.githubusercontent.com/177525/116787273-868bb680-aa79-11eb-911c-4fa2b27d46f9.png)

**Comment by josevalim** [comment]
The generators are part of Phoenix and, IIRC, this issue has been solved on Phoenix master. Can you please give it a try and, if the issue persists, open up an issue there? Thanks!

**Comment by sadjow** [comment]
Thanks for the feedback @josevalim. I am going to give it a try.
