### ISSUE TITLE
"DOM patching and temporary ass" in HexDocs sidebar

### ISSUE THREAD

**Issue by sudochop** [phoenixframework/phoenix_live_view#1439]
### Environment

* Elixir version (elixir -v): N/A
* Phoenix version (mix deps): N/A
* Phoenix LiveView version (mix deps): N/A
* NodeJS version (node -v): N/A
* NPM version (npm -v): N/A
* Operating system: N/A
* Browsers you attempted to reproduce this bug on (the more the merrier): Chromium-based
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: N/A

### Actual behavior

The sidebar width creates an interesting title for this section: https://hexdocs.pm/phoenix_live_view/dom-patching.html#content

### Expected behavior

I don't actually mind but maybe the team does

**Comment by josevalim** [comment]
thank you, I appreciate double checknig with us!
