### ISSUE TITLE
Is it possible to have disconnected callback invoked _before_ the element loses focus over the disconnection?

### ISSUE THREAD

**Issue by DaTrader** [phoenixframework/phoenix_live_view#1445]
### Actual behavior

The element hook disconnected callback is invoked after the element loses focus over the very fact that LiveView disconnected.

### Expected behavior

The disconnected callback should be invoked before the element loses focus so that any listeners e.g. a focus out listener may properly detect the cause.

**Comment by mcrumm** [comment]
Hi @DaTrader, I am not sure if this is possible, but you may feel free to try it out and submit a PR. Otherwise I am not aware of any upcoming changes to the hook lifecycle. Thanks!

**Comment by DaTrader** [comment]
Hi @mcrumm,
All I can say is I'll try. You shouldn't have closed the issue though for whether I succeed or not in a) properly detecting what it takes to be done and b) actually making it work, it won't change the fact that this is an issue that needs to be addressed sooner or later.

**Comment by josevalim** [comment]
The issues tracker currently focuses only on bug reports. This feels like an extension of current functionality rather than a bug, so it personally makes sense to me it is closed.

**Comment by DaTrader** [comment]
@josevalim 

Sorry, but I beg to differ. AFAIK the hooks are there for proper JS interop and having one's focus out listener invoked with a stale (not the actual state) of whether LiveView is connected or not, is a bug or a design flaw if intentional.

As for submitting a PR, I'll be happy to, but since there was obviously an intent to blur the focus here I don't know what I should do. The problem is in the asterisk-flagged line below, or to be more precise in the author's intent behind the line below:

```
 key: "onClose",
        value: function (e) {
          if (!this.isDestroyed()) {
            if (this.isJoinPending() || this.liveSocket.hasPendingLink() && "leave" !== e) return this.liveSocket.reloadWithJitter(this);
*            this.destroyAllChildren(), this.liveSocket.dropActiveElement(this), document.activeElement && document.activeElement.blur(), this.liveSocket.isUnloaded() && this.showLoader(200);
          }
        }
```
Now, what was the purpose of the "document.activeElement && document.activeElement.blur()" in the first place? Why blur on disconnect? In my app for instance, this is the cause of the problem for I don't want it blurred on disconnect. Yet, if for some reason that is beyond my understanding this is the desired behavior, why not move it after the showLoader(200) which invokes the disconnected  callback?

It's about the intent here and I cannot guess why this was done.
