### ISSUE TITLE
Deprecate rootless components

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix_live_view#1453]

**Comment by josevalim** [comment]
This will raise in the new `~H` templates. Then it is a matter of no longer support `~L` sigils for components in the future and optimizing the LiveView front-end.

**Comment by miguel-s** [comment]
Would it be possible (or desirable) to add something similar to React's [Fragments](https://reactjs.org/docs/fragments.html) for rendering multiple elements in one component without having to create wrapper DOM nodes?

**Comment by josevalim** [comment]
This limitation is only for stateful components, there is no restriction for regular components, and I think that’s fine. Stateful components do require additional constraints so we track them.

**Comment by josevalim** [comment]
Deprecation is already in master.
