### ISSUE TITLE
JS Hook pushEvent with an ArrayBuffer results in empty map

### ISSUE THREAD

**Issue by tylersamples** [phoenixframework/phoenix_live_view#1457]
### Environment

* Elixir version (elixir -v): Elixir 1.11.3
* Phoenix version (mix deps): 1.5.9
* Phoenix LiveView version (mix deps): 0.15.5
* NodeJS version (node -v): v16.1.0
* NPM version (npm -v): 7.12.1
* Operating system: Fedora 34 x86_64
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome 90 / Firefox 88
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

With a minimal hook:
```javascript
let Hooks = {}
Hooks.Binary = {
  mounted() {
    this.pushEvent("binary", new Uint8Array(1).buffer)
  }
}
```

```elixir
def handle_event("binary", data, socket) do
  {:noreply, socket}
end
```
`data` in `handle_event/3` yields an empty map: `%{}`

### Expected behavior

I would expect the same result as a channel or some equivalent way to receive binary data.

For reference a channel:
```javascript
channel.push("binary", new Uint8Array(1).buffer)
```

```elixir
def handle_in(event, data, socket) do
  {:noreply, socket}
end
```
`data` in `handle_in/3` is `{:binary, <<0>>}`.

---

I found one other mention of Array Buffers in the upload images issue but nothing more about specifically supporting the passing of binary data: https://github.com/phoenixframework/phoenix_live_view/issues/104

I did look at how Uploads is handling binary data and it appears to use it's own channel but I can't tell if that's for better control over the lifecycle of the upload or simply that is the preferred way of handling ArrayBuffers with Liveview. I'm aware I could Base64 encode the data and handle it that way. However base64 maybe too cost prohibitive long term.

In poking around I found that I could call in `this.__view.channel.push` in my hook to send data to the backend:
```javascript
this.__view.channel.push("binary", new Uint8Array(1).buffer)
```

I could then capture the data by implementing:
```elixir
def handle_info(%Phoenix.Socket.Message{event: "binary", payload: payload}, socket) do
    {:noreply, socket}
end
```
 This seems not intended :P

**Comment by chrismccord** [comment]
Binary data over LV events is not supported. You could use a regular channel if needed. Thanks!
