### ISSUE TITLE
We are telling users to import Phoenix.LiveView.View but it is private

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix_live_view#146]
We should move the functions in `Phoenix.LiveView.View` to an internal module and keep only `live_render/2,3` and document it.

**Comment by chrismccord** [comment]
Where is this docd? View is not user land and we have the entire public API on LiveView

**Comment by josevalim** [comment]
Sorry, We are using Phoenix.LiveView in the view, my bad!
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
