### ISSUE TITLE
Can we add Storage fallbacks?

### ISSUE THREAD

**Issue by JEG2** [phoenixframework/phoenix_live_view#1460]
### Environment

* Elixir version (elixir -v):  1.11.4
* Phoenix version (mix deps):  1.5.9
* Phoenix LiveView version (mix deps):  0.15.5
* NodeJS version (node -v):  v14.16.1
* NPM version (npm -v):  7.11.2
* Operating system:  macOS Big Sur 11.2.3
* Browsers you attempted to reproduce this bug on (the more the merrier):  Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:  yes

### Actual behavior

At [Payitoff](https://payitoff.io/) we provide a widget, powered by LiveView, that our partners load on their domains in an iframe.  Unfortunately, the widget breaks when viewed on one of our partner's sites in a Chrome incognito window.  The reason is that incognito blocks third party data access from the cross-origin iframe.  LiveView uses `sessionStorage` to [track debugging states](https://github.com/phoenixframework/phoenix_live_view/blob/1cad4ceb50b8417ecacdae0c0cbcc627ca71ce9e/assets/js/phoenix_live_view.js#L750-L773) and `localStorage` to [count retry attempts](https://github.com/phoenixframework/phoenix_live_view/blob/1cad4ceb50b8417ecacdae0c0cbcc627ca71ce9e/assets/js/phoenix_live_view.js#L860).

### Expected behavior

Our question is if you would accept a PR from us that:

1. Checks for access to these APIs
2. Uses the current code when available
3. Falls back to attribute-based storage on the Javascript objects when unavailable

We know that last case isn't completely equivalent, but would it be acceptable to you as a fallback only?  Again, we are happy to write the PR if you agree with the approach.

Thanks for your time.

**Comment by chrismccord** [comment]
We'd be happy to evaluate a PR. Perhaps the simplest and least complex on our side would be to accept the `sessionStorage` and `localStorage` as `LiveSocket` constructor options? That way we don't need to fallback ourselves and you can pass in  your own bag of data after your check for access to these apis?
