### ISSUE TITLE
Cannot create phoenix app inside umbrella project Windows machine

### ISSUE THREAD

**Issue by Fl4m3Ph03n1x** [phoenixframework/phoenix_live_view#1467]
### Environment

* Elixir version (elixir -v):
```
λ elixir -v
Erlang/OTP 22 [erts-10.7] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1]
Elixir 1.11.2 (compiled with Erlang/OTP 21)
```

λ mix archive
```
* hex-0.21.2
* phx_new-1.5.9
Archives installed at: c:/Users/palme/.mix/archives

```

* Operating system:
```
λ systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.19042 N/A Build 19042
```

### Actual behavior

I am running `mix phx.new.web phx_test --live --no-ecto` inside of my `apps` folder in my umbrella app. However I get the following error:

```
λ mix phx.new.web test --no-ecto
** (Mix) Could not find "use Mix.Config" or "import Config" in "c:/Users/palme/Documents/GitHub/market_manager/config/config.exs"
```

### Expected behavior

The umbrella app should be created.

---------------

### Problem

After a long analysis with the community, we found out that the issue lies in the line endings. Phoenix's code, apparently, does not like the CRLF ending from Windows, and thus does not recognize the "import Conifg" line because this line does not have the Linux line ending.

When I forced/changed all my project's line endings to be LF, the mix task worked as expected. I am working in a Windows machine, and since Elixir does officially support Windows (and this is something that breaks on Windows) I believe the best course of action would be to change the code to:
 - consider both line ending types OR
 - not be dependent on line endings

### Research forum threads:

 - https://elixirforum.com/t/cannot-create-phoenix-app-inside-umbrella-project/39970
 - https://elixirforum.com/t/new-umbrella-web-could-not-find-import-config/29884

### Fix (for vscode users)

- https://qvault.io/clean-code/how-to-get-consistent-line-breaks-in-vs-code-lf-vs-crlf/

**Comment by josevalim** [comment]
Fixed on Phoenix master, thanks.

**Comment by Fl4m3Ph03n1x** [comment]
I apologize if this is a dumb question, but when will the release with the fix be out ?

**Comment by josevalim** [comment]
There is no time schedule for now. Note formatter also normalizes \r\n to \n, so my suggestion is to configure your git to it rewrites everything to \n to avoid mixing formats.
