### ISSUE TITLE
`follow_trigger_action` doesn't work with PUT (etc)

### ISSUE THREAD

**Issue by lleger** [phoenixframework/phoenix_live_view#1470]
### Environment

* Elixir version (elixir -v): 1.11.0-otp-23
* Phoenix version (mix deps): 1.5.7
* Phoenix LiveView version (mix deps): 0.15.7
* NodeJS version (node -v): 16.2.0
* NPM version (npm -v): 7.13.0
* Operating system: macOS
* Browsers you attempted to reproduce this bug on (the more the merrier): Safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

If you use `follow_trigger_action` on a form that is using a non-default method such as PUT, the test fails with a routing error because it tries to send it to POST instead.

Updating the route to be POST instead of PUT makes the test pass.

Here's a failing test case illustrating this behavior: https://github.com/lleger/phoenix_live_view/commit/79dc9834bce0b2f3d21276c3a2bd25c98fcfa20a

I think the issue might be here: https://github.com/phoenixframework/phoenix_live_view/blob/3055ad570ea895bc9b1e7abcb7cbd02e574dce04/lib/phoenix_live_view/test/live_view_test.ex#L1361

Should this line instead be checking for `_method` in the form params first?

### Expected behavior

I would expect that `follow_trigger_action` can see the `_method` param and send the conn accordingly.

**Comment by josevalim** [comment]
@lleger Thanks for the report. I am afraid that line is correct. That's the form method and, similar to a browser, we only submit GET/POST. Then you should have a Plug.OverrideMethod in your pipeline that will convert that POST into a PUT/DELETE according to the _method. Do you have said plug in your pipeline? is it being invoked?

**Comment by lleger** [comment]
@josevalim Yes, it looks like `Plug.MethodOverride` is indeed present in the endpoint for the project: https://github.com/newaperio/phoenix_starter/blob/a0a52cb1b4232def191b255bade28b381c22633d/lib/phoenix_starter_web/endpoint.ex#L52

I should mention that the functionality works in the browser, so I'm guessing the MethodOverride is being invoked there. It's just not working in the test.

**Comment by lleger** [comment]
Ah, so when I added a breakpoint, yes indeed `Plug.MethodOverride` is being called in the test, but that lead me to realize that I need to explicitly pass the `_method` param in the `form` test helper.

**Doesn't work**
```elixir
live
|> form(@form_id, user: %{email: "test@example.com"})
|> render_submit()
|> follow_trigger_action(conn)
```

**Does work**
```elixir
live
|> form(@form_id, user: %{email: "test@example.com"}, _method: "put")
|> render_submit()
|> follow_trigger_action(conn)
```

Guess I can close it since it's not a bug, but wonder if it would make sense to be added to the docs? Or, you know, maybe it's just me that's confused 😅
