### ISSUE TITLE
Deprecation of socket.connected?

### ISSUE THREAD

**Issue by wmnnd** [phoenixframework/phoenix_live_view#1476]
Hey there,

I just noticed that `connected?` was removed from the socket struct in a recent commit:
https://github.com/phoenixframework/phoenix_live_view/commit/4c9f46d566d4f2c2062b68a1425faba8245d2595#diff-dbe072dea09d3c01df875a8493bb630a0b596112af249cd42420ae07a45bc253

The way I noticed was that a user reported a bug in Phoenix LiveSession which relies on the `connected?` attribute for pattern matching: https://github.com/pentacent/phoenix_live_session/issues/5

I know that LiveView is still in pre-1.0 territory, but this seems to be a breaking change introduced in a patch release with no note of it in the changelog.

**Comment by josevalim** [comment]
`connected?` was not a public struct field (it doesn't show up on inspection), so instead of relying on it, please use the appropriate `connected?` function instead. That's why it isn't in the CHANGELOG, we were not expecting anyone to be using it in the first place. :) Thanks!

**Comment by wmnnd** [comment]
Thanks for clarifying this, @josevalim!
