### ISSUE TITLE
@socket.connected? not available in 0.15.6

### ISSUE THREAD

**Issue by Softknobs** [phoenixframework/phoenix_live_view#1477]
### Environment

* Elixir version (elixir -v): 1.11
* Phoenix version (mix deps):
* Phoenix LiveView version (mix deps): 0.15.6
* NodeJS version (node -v):
* NPM version (npm -v):
* Operating system: Windows 10
* Browsers you attempted to reproduce this bug on (the more the merrier): 
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:

### Actual behavior

Starting 0.15.6, code like this does not work anymore: `<%= if @socket.connected? do %>`
Error: `key :connected? not found in: #Phoenix.LiveView.Socket`
And this is not explicitly  documented in the changelog as a backwards incompatible change.
The log does not seem to be up to date as latest release seems to be 0.15.7 (when doing deps.update), and only 0.15.6 is mentionned in the log.

### Expected behavior

It is either a bug or undocumented change in the changelog. Either a fix or changelog update (with an alternative to this feature) is expected.

**Comment by josevalim** [comment]
Please see #1476, thanks.
