### ISSUE TITLE
calling upload entry error function causes backend to crash

### ISSUE THREAD

**Issue by dvic** [phoenixframework/phoenix_live_view#1478]
### Environment

* Elixir version (elixir -v): 1.12.1
* Phoenix version (mix deps): 1.5.9
* Phoenix LiveView version (mix deps): 0.15.7
* NodeJS version (node -v): 14.17.0
* NPM version (npm -v): 7.15.0
* Operating system:
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, Firefox, Safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

I'm seeing an error on the backend when `entry.error(..)` is called: 
```
** (KeyError) key nil not found in: %{"phx-FoS6bbgndEF9hARj" => :photo}
    :erlang.map_get(nil, %{"phx-FoS6bbgndEF9hARj" => :photo})
    (phoenix_live_view 0.15.7) lib/phoenix_live_view/upload.ex:186: Phoenix.LiveView.Upload.get_upload_by_ref!/2
    (phoenix_live_view 0.15.7) lib/phoenix_live_view/upload.ex:127: Phoenix.LiveView.Upload.update_progress/4
    (phoenix_live_view 0.15.7) lib/phoenix_live_view/channel.ex:143: anonymous fn/4 in Phoenix.LiveView.Channel.handle_info/2
    (phoenix_live_view 0.15.7) lib/phoenix_live_view/channel.ex:1020: Phoenix.LiveView.Channel.write_socket/4
    (phoenix_live_view 0.15.7) lib/phoenix_live_view/channel.ex:141: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 3.14.2.1) gen_server.erl:689: :gen_server.try_dispatch/4
    (stdlib 3.14.2.1) gen_server.erl:765: :gen_server.handle_msg/6
    (stdlib 3.14.2.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: %Phoenix.Socket.Message{event: "progress", join_ref: "4", payload: %{"entry_ref" => "0", "event" => nil, "progress" => %{"error" => "xhr request failed"}, "ref" => nil}, ref: "7", topic: "lv:phx-FoS6bT4FpVUSbwEC"}
```

The uploader that is used:

```ts
const Uploaders = {
  Gcs: function (
    entries: UploadEntry[],
    onViewError: (arg0: () => void) => void,
  ) {
    entries.forEach((entry) => {
      const { endpoint } = entry.meta as { endpoint: string }

      const xhr = new XMLHttpRequest()

      onViewError(() => xhr.abort())

      xhr.onload = () =>
        xhr.status === 200
          ? entry.progress(100)
          : entry.error(`got http ${xhr.status}`)

      xhr.onerror = () => {
        entry.error("xhr request failed")
      }

      xhr.upload.addEventListener("progress", (event) => {
        if (event.lengthComputable) {
          const percent = Math.round((event.loaded / event.total) * 100)
          if (percent < 100) {
            entry.progress(percent)
          }
        }
      })

      xhr.open("PUT", endpoint, true)

      xhr.send(entry.file)
    })
  },
}
```

### Expected behavior
I expect no backend errors when I call `entry.error`.

**Comment by dvic** [comment]
I'm not sure it's related to calling `entry.error` because I'm now getting it also with a successful upload, so it's likely an issue on my side, I'll look into it and update/close this issue if necessary.

**Comment by chrismccord** [comment]
To be clear, is it possible you are sending progress(100) then later sending the error? If that is the case and you are consuming the file on the backend using `auto_upload: true`, then you could consume the file which removes it from the state, and the client is later trying to report an error even tho it no longer exists. We should make a better error message, but we need to rule out a misbehaving client in this case as well.

**Comment by dvic** [comment]
I don't think this is the the case, as we're not using `auto_upload` and it seems the progress reporting does not affect the outcome. If I change the code to avoid reporting any progress (just errors), like this:

```typescript
const Uploaders = {
  Gcs: function (
    entries: UploadEntry[],
    onViewError: (arg0: () => void) => void,
  ) {
    entries.forEach((entry) => {
      const { endpoint } = entry.meta as { endpoint: string }

      const xhr = new XMLHttpRequest()

      onViewError(() => xhr.abort())

      xhr.onload = () =>
        // xhr.status === 200
        //   ? entry.progress(100)
        //   : entry.error(`got http ${xhr.status}`)
        entry.error("fake error")

      xhr.onerror = () => {
        entry.error("xhr request failed")
      }

      // xhr.upload.addEventListener("progress", (event) => {
      //   if (event.lengthComputable) {
      //     const percent = Math.round((event.loaded / event.total) * 100)
      //     if (percent < 100) {
      //       entry.progress(percent)
      //     }
      //   }
      // })

      xhr.open("PUT", endpoint, true)

      xhr.send(entry.file)
    })
  },
}
```

then I still get an error (last message contains `"fake error"` now, as I expected)

```
module=gen_server [error] GenServer #PID<0.1089.0> terminating
** (KeyError) key nil not found in: %{"phx-FoTLAZ_HT9mIhgnG" => :photo}
    :erlang.map_get(nil, %{"phx-FoTLAZ_HT9mIhgnG" => :photo})
    (phoenix_live_view 0.15.7) lib/phoenix_live_view/upload.ex:186: Phoenix.LiveView.Upload.get_upload_by_ref!/2
    (phoenix_live_view 0.15.7) lib/phoenix_live_view/upload.ex:127: Phoenix.LiveView.Upload.update_progress/4
    (phoenix_live_view 0.15.7) lib/phoenix_live_view/channel.ex:143: anonymous fn/4 in Phoenix.LiveView.Channel.handle_info/2
    (phoenix_live_view 0.15.7) lib/phoenix_live_view/channel.ex:1020: Phoenix.LiveView.Channel.write_socket/4
    (phoenix_live_view 0.15.7) lib/phoenix_live_view/channel.ex:141: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 3.14.2.1) gen_server.erl:689: :gen_server.try_dispatch/4
    (stdlib 3.14.2.1) gen_server.erl:765: :gen_server.handle_msg/6
    (stdlib 3.14.2.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: %Phoenix.Socket.Message{event: "progress", join_ref: "8", payload: %{"entry_ref" => "0", "event" => nil, "progress" => %{"error" => "fake error"}, "ref" => nil}, ref: "11", topic: "lv:phx-FoTLAZ6X87EsMx9C"}
```

**Comment by chrismccord** [comment]
If you are using the `onViewError`, then the view has already gone away and there is no entry to report to since the view that tracked it is long gone. It appears you are sending the error report to a newly connected LV after a crash. Can you confirm if the view is crashing which is aborting the xhr, and if so why?

**Comment by dvic** [comment]
This is the order of things:

![image](https://user-images.githubusercontent.com/1214337/120505785-9888ae00-c3c5-11eb-9057-afdef5e9f618.png)

As a reference, this is the code:

```typescript
const Uploaders = {
  Gcs: function (
    entries: UploadEntry[],
    onViewError: (arg0: () => void) => void,
  ) {
    entries.forEach((entry) => {
      const { endpoint } = entry.meta as { endpoint: string }

      const xhr = new XMLHttpRequest()

      onViewError(() => {
        console.log("onViewError called, aborting xhr")
        xhr.abort()
      })

      xhr.onload = () => {
        // xhr.status === 200
        //   ? entry.progress(100)
        //   : entry.error(`got http ${xhr.status}`)
        console.log("onload, faking error")
        entry.error("fake error")
      }

      xhr.onerror = () => {
        console.log("xhr onerror callback called")
        entry.error("xhr request failed")
      }

      // xhr.upload.addEventListener("progress", (event) => {
      //   if (event.lengthComputable) {
      //     const percent = Math.round((event.loaded / event.total) * 100)
      //     if (percent < 100) {
      //       entry.progress(percent)
      //     }
      //   }
      // })

      xhr.open("PUT", endpoint, true)

      xhr.send(entry.file)
    })
  },
}
```

Commenting out the `xhr.abort()` does not help mitigating the crash. It really looks like the view crashes after the error is signaled from the `onload` callback.

**Comment by chrismccord** [comment]
I missed it earlier, but it looks like we have no reference from the client for the upload as we are fetching the `nil` key. I need to investigate how this may happen.

**Comment by dvic** [comment]
If it helps, I have replicated this issue in a separate repo: https://github.com/dvic/lv_error_crash

**Comment by dvic** [comment]
Okay, I think I found the problem:

https://github.com/phoenixframework/phoenix_live_view/blob/c3dbe6bc0f78da95a24051ad5713c9a4f669c476/assets/js/phoenix_live_view.js#L189-L192

If I change these two lines around, then the problem goes away 🙂 Is this a correct solution?

**Comment by dvic** [comment]
The `clearFiles` call was added in https://github.com/phoenixframework/phoenix_live_view/commit/b8ae4d3da38b64197468064704d9bd8cbb3b987b, I'm not sure how/if changing these lines around affects the issue being resolved in this commit.

**Comment by dvic** [comment]
And something related to this: the `update_progress` does not add the `reason` received from the client in the error:

```elixir
  def update_progress(%Socket{} = socket, config_ref, entry_ref, %{"error" => reason})
      when is_binary(reason) do
    conf = get_upload_by_ref!(socket, config_ref)

    put_upload_error(socket, conf.name, entry_ref, :external_client_failure)
  end
```

Not sure what the way to go is here but I can image something like `{:external_client_failure, reason}` ? (although this is a breaking change)

**Comment by chrismccord** [comment]
Yes swapping the lines is the fix. Do you want to send a PR?

Let's leave the `:external_client_failure` error as is for now. There's very little you can do on the server if the client fails and we must hold the error reason in memory so I would prefer to wait for now since you can still provide user feedback with the bare atom. Thanks!

**Comment by dvic** [comment]
Clear, I'll send a PR that swaps the lines.
