### ISSUE TITLE
`live_img_preview` performance compared to `blue-imp-loadImage`

### ISSUE THREAD

**Issue by Zurga** [phoenixframework/phoenix_live_view#1481]
My project requires that I can upload a lot of images (around 100) which are relatively large 3-6MB. Unfortunately, `live_image_preview` does not perform very well with this amount of images. To fix this, I implemented `live_img_preview` myself with the following hook using [Load Image:](https://github.com/blueimp/JavaScript-Load-Image)

```
Hooks.UploadPreview = {
  mounted() { 
    this.ref = this.el.getAttribute("data-phx-entry-ref")
    this.inputEl = document.getElementById(this.el.getAttribute(PHX_UPLOAD_REF))
    let file = LiveUploader.activeFiles(this.inputEl).find(file => LiveUploader.genFileRef(file) === this.ref)
    loadImage(file, img => this.el.appendChild(img))
  } 
} 
```
The resulting image will be appended to a container `div` which has the hook set on it.

So far, my performance on both Firefox 88.0.1 and Chromium 90.0.4430.212 has been a lot better. Please have a look at the profiles I created loading the same images with different implementations. We can see that there is a lot less time spent on scripting with `loadImage` when the images have been selected to be uploaded and the RAM usage is also a lot lower.

[Profiling on Chromium with normal live_img_preview.json](https://gist.github.com/Zurga/18e782dfbe685c50e14a6762479edbfd)
[Profiling on Chromium with loadImage.json](https://gist.github.com/Zurga/9d600439ddd8afb9b76b8793b619e6b9)

My question, or issue, is thus as follows: can `loadImage` become the standard image loader, or can we export the `LiveUploader` class in `phoenix-live-view.js`? By exporting it, I can keep using my custom hook without having to maintain a fork.

My preference would be to use loadImage as a new dependency (it itself brings no dependencies) compared to base64'ing the uploads and using those as the `img src`. There are other performance gains with not using base64, for example, when wanting to show the entry in a modal to show it in full size.

**Comment by mcrumm** [comment]
My understanding is that browsers are fairly fickle wrt what conditions cause an `<img>` element to be redrawn. My inclination here is that when we update attributes on the tag the browser redraws the preview. So I think the smallest change that would mitigate the perf difference would be nesting the element, for instance in a [`<figure>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figure).

**Comment by Zurga** [comment]
I can test it but I am not sure how that would change things.

I still think that having images stored as base64 blobs is not an optimal way of representing them in terms of resource usage. I have a Ryzen 4700 and my browser was lagging. I can only imagine the performance hit on mobile.

I don't know exactly what `loadImage` is doing, but there the image is not stored as a base64 blob, rather the src is pointing to "blob:http://localhost/[UUID]".

**Comment by Zurga** [comment]
@mcrumm sorry wrapping the imgs in a figure did not change much. 

I can make a video of the difference between the current implementation and the one I am proposing, I think that might shed more light on what I mean.

**Comment by mcrumm** [comment]
@Zurga no worries and thank you for the offer but a video shouldn't be necessary, I think I found it. It's likely the use of `createObjectURL` vs. the FileReader API.

**Comment by Zurga** [comment]
Okay, after reading a bit more I am guessing that loadImage is probably using `createObjectURL` as that returns a url. It would be great if that solves this issue.

**Comment by Zurga** [comment]
Yesterday I also found someone testing the difference, but not really noticing any real performance gain with one or the other, though this was with smaller images. 

That is why I opted to use the `loadImage` library. But I can also see that it brings a lot of unnecessary code.

**Comment by Zurga** [comment]
The performance is a lot better with `createObjectURL`! :fire:  Even better than with `loadImage` 

```
~  259 class LiveUploader {
....
   270   static getEntryDataURL(inputEl, ref, callback){
   271     let file = this.activeFiles(inputEl).find(file => this.genFileRef(file) === ref)
~_ 272     callback(URL.createObjectURL(file))
   273   }
   274 
   ```

**Comment by mcrumm** [comment]
@Zurga could try the latest changes on #1485 and report back on what you see, performance-wise?

**Comment by Zurga** [comment]
The performance is superb, almost instant loading with 73 images each 5MB. Scrolling also does not cause any rendering issues. Nice work!
