### ISSUE TITLE
Upload folder and get relative paths

### ISSUE THREAD

**Issue by arnaub** [phoenixframework/phoenix_live_view#1482]
I'm trying to upload a folder instead of files using LiveView uploads.

`<%= live_file_input @uploads.files, class: "hidden", webkitdirectory: true %>`

It works perfect and it uploads all the folder and subfolder files. But I think there is no way to get the relative path of each file.

It would be nice to get this information inside the `UploadEntry` struct.

**Comment by SteffenDE** [comment]
Supported since #1781 was merged. The relative path will show up in the `client_relative_path` field of the UploadEntry. I think this can be closed now.
