### ISSUE TITLE
Infinite Reloading - Exceeded 10 Consecutive Reloads

### ISSUE THREAD

**Issue by papakay** [phoenixframework/phoenix_live_view#1488]
### Environment

* Elixir version (elixir -v): 23.1
* Phoenix version (mix deps): 1.11.2
* Phoenix LiveView version (mix deps): 0.15.7
* Operating system: Linux
* Browsers you attempted to reproduce this bug on (the more the merrier): Microsoft Edge
* Does the problem persist after removing "assets/node_modules" and trying again? Yes

We have an app that uses liveview in production hosted on heroku. There are a couple of pages that uses liveview. However we observed two of those pages doesn't work as expected.

It keeps reloading endlessly and then enter a fail safe mode.

Please see the screenshot of the debug message below.

![Screenshot 2021-06-10 at 4 30 33 PM](https://user-images.githubusercontent.com/5013738/121554006-b4193780-ca09-11eb-8211-12591dda4506.png)

**Comment by josevalim** [comment]
It is a bit weird that it only happens in certain live views. There is nothing logged on the server?

**Comment by papakay** [comment]
@josevalim nothing on the server. So weird, we've tried several things but still didn't work. One of the things we did was to refactor our code to load the data required after liveview is mounted statefully. Another thing we did was to increase the heartbeatIntervalMs property to 20 seconds.

**Comment by josevalim** [comment]
Oh, a slow mount would definitely justify it, especially if you are loading a lot of data.

If you need to load a lot of data, perhaps you should send yourself a message on mount and then load the data in a callback, bit by bit if possible.

**Comment by papakay** [comment]
Those data are not really much. And now we've deferred the loading of those data till after liveview is mounted. We really expected this to resolve the issue but still no luck.

**Comment by papakay** [comment]
> Oh, a slow mount would definitely justify it, especially if you are loading a lot of data.
> 
> If you need to load a lot of data, perhaps you should send yourself a message on mount and then load the data in a callback, bit by bit if possible.

Please can you share a guide on how to achieve this?

**Comment by papakay** [comment]
@josevalim please find below a skeletal code of the liveview module.

```ex
defmodule MyAppWeb.PageLive do
  use Phoenix.LiveView
  
  def mount(_params, %{"user" => user}, socket) do
    if connected?(socket), do: send(self(), {:load_initial_data, user})

    {:ok,
     assign(
       socket,
       user: user,
       initial_balance: nil,
       page_data: [],
       refined_data: [],
     )}
  end

  def render(assigns) do
    Phoenix.View.render(MyAppWeb.PageView, "show.html", assigns)
  end

  
  def handle_info({:load_initial_data, user}, socket) do
    page_data = load_user_page_data(user)
    additional_data = get_additional_data_from_external_service()
    
    send(self(), {:process_those_additional_data, additional_data})

    {:noreply, assign(socket,
      page_data: page_data,
      initial_balance: additional_data.initial_balance
    )}
  end

  def handle_info({:process_those_additional_data, additional_data}, socket) do
    refined_data = refine_raw_data(additional_data)
    {:noreply,
      assign(
        socket,
        refined_data: refined_data
      )}
  end

end
```

**Comment by josevalim** [comment]
Yup, you got it!!!

**Comment by papakay** [comment]
Hi @josevalim thanks a lot for validating the above skeletal code. What is still so strange to us is why the infinite reloading keeps happening on those two liveview pages and others are working fine.

I also like to inform you that we render liveview from the controller as below

```ex
live_render(
      conn,
      MyAppWeb.PageLive,
      session: %{
        "user" => user,
      }
    )
   ```

**Comment by papakay** [comment]
Hello @josevalim another thing i found out is that it when you click on the link to the liveview page, it takes about 10 to 15 seconds before the nprogress loading indicator appears.

**Comment by josevalim** [comment]
Right, because you are on the redirect loop, LiveView enters a throttle mode. But maybe, if you are in throttle mode and then you try to redirect, perhaps we should do a full page redirect. /cc @chrismccord

**Comment by papakay** [comment]
Hi @josevalim the screenshot below is output of clicking on the source file link connected with the debug message. I felt perhaps it could help.


<img width="828" alt="Screenshot 2021-06-14 at 2 33 19 PM" src="https://user-images.githubusercontent.com/5013738/121900642-8986f180-cd1d-11eb-8372-e6f476f5800b.png">

**Comment by tnaftali** [comment]
Hi @josevalim, I work with @papakay, is there a chance we could send you a screencast showing you the issue happening?

We are now using a 60000 ms as `heartbeatIntervalMs` and the issue still happens...

**Comment by chrismccord** [comment]
I don't think a screencast will help without logs as to why you may not be receiving an acknowledgment from the server. A higher timeout isn't likely to be the answer because it shouldn't be taking that long and without an error stack trace from the server it's really difficult to say what could be happening. One thing to keep in mind is the following code is an anti-pattern and a potential place to start looking:

```
live_render(
      conn,
      MyAppWeb.PageLive,
      session: %{
        "user" => user,
      }
    )

```

You are storing the entire user struct in the session, which will be serialized on the client and must be decoded on the server. If this struct is very large, it could be causing issues, but the server decode should be telling us it is an invalid token, unless you are going very CPU bound decoding massive tokens. You should instead change it to this:

```
live_render(
      conn,
      MyAppWeb.PageLive,
      session: %{
        "user_id" => user,
      }
    )
```

and use `assign_new` to lookup the user from the DB if it is not present, ie

```
def mount(_params, %{"user_id" => user_id}, socket) do
...
  socket = 
    socket
    |> ...
    |> assign_new(:user, fn -> Accounts.get_user!(user_id) end)
...
end
```

**Comment by himangshuj** [comment]
Happening for me too, js console shows The connection to wss://rt-zen.gigalixirapp.com/live/websocket?_csrf_token=G3sKKiMoHVsBLBMLKAI7Ll0RH3QvL2IZr6MBunv-yFdgJHXhesM8JJPq&_track_static%5B0%5D=https%3A%2F%2Frt-zen.gigalixirapp.com%2Fcss%2Fapp-8f38379e58262cd3f6c614857ad981b1.css%3Fvsn%3Dd&_track_static%5B1%5D=https%3A%2F%2Frt-zen.gigalixirapp.com%2Fjs%2Fapp-124e77604793bf56a183f3c8e46fca75.js%3Fvsn%3Dd&_mounts=0&vsn=2.0.0 was interrupted while the page was loading.

Funnily, it works fine when I open the page, but when I wake up my computer from hibernation, it goes bonkers. I think issue is related to web socket not elixir code per se

**Comment by papakay** [comment]
Thank you @josevalim and @chrismccord for your huge support.

@chrismccord recommendation fixed this for us. We now pass user_id instead of passing the entire user struct which sometime could be large.

The pages now loads fine.
