### ISSUE TITLE
Alpine `@` attributes in dynamic LiveView code cause JS crash

### ISSUE THREAD

**Issue by paulstatezny** [phoenixframework/phoenix_live_view#1491]
### Environment

* Elixir version (elixir -v): 1.12.0
* Phoenix version (mix deps): 1.5.7
* Phoenix LiveView version (mix deps): 0.15.4
* NodeJS version (node -v): v14.13.0
* NPM version (npm -v): 6.14.8
* Operating system: MacOS 11.3
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

Whenever calling `Phoenix.HTML.Form.checkbox(form, field, ["@click": "..."])` in a LiveView context, the following JS error occurs:

<img width="757" alt="Screen Shot 2021-06-11 at 3 06 01 PM" src="https://user-images.githubusercontent.com/4662353/121753915-32d4aa00-cac8-11eb-8027-41c2483e2877.png">

### Expected behavior

The checkbox is rendered with an `@click` attribute

```html
<input type="checkbox" @click="...">
```

### Notes

- Hardcoding some HTML with `@click` in LiveView works without a problem. (E.g. `<div @click="foo">`)
- I'm encountering this while using [Surface](https://github.com/surface-ui/surface)'s `<Checkbox>` component, which calls `Phoenix.HTML.Form.checkbox` under the hood.
- `@click` is from [Alpine.js](https://alpinejs.dev/)
- This seems to be a conflict between Alpine and the browser vendors / JS specification, so I understand we might be at an impasse.
- Alpine's long-form syntax for `@click` is `x-on:click`, and this works without a problem.

**Comment by chrismccord** [comment]
Until I can take a look at this you can use the non sugar form of alpine bindings with x-on:click=

**Comment by grrrisu** [comment]
I have a similar error with the `@` directive shortcut `@keyup.prevent=...`. Different error message, but in the same function `mergeAttrs`. Probably the same root cause.
```
Uncaught DOMException: String contains an invalid character phoenix_live_view.js:1900
    mergeAttrs webpack:///../deps/phoenix_live_view/priv/static/phoenix_live_view.js?:1900
    mergeFocusedInput webpack:///../deps/phoenix_live_view/priv/static/phoenix_live_view.js?:1909
    onBeforeElUpdated webpack:///../deps/phoenix_live_view/priv/static/phoenix_live_view.js?:2114
```
I could solve it temporarily with `x-on`  as @chrismccord suggested.

**Comment by matthewadowns** [comment]
Just a +1 as I ran into this as well.  Using the `x-on:` syntax is a suitable work around.
