### ISSUE TITLE
`page_title` test helper returns `nil` in some cases

### ISSUE THREAD

**Issue by lleger** [phoenixframework/phoenix_live_view#1496]
### Environment

* Elixir version (elixir -v): OTP 23.1.1 / Elixir 1.11.0
* Phoenix version (mix deps): 1.5.7
* Phoenix LiveView version (mix deps): 0.15.7
* NodeJS version (node -v): 14.13.1
* NPM version (npm -v): 6.14.8
* Operating system: macOS
* Browsers you attempted to reproduce this bug on (the more the merrier): Safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

`Phoenix.LiveViewTest.page_title/1` returns nil. Confirmed behavior works in the browser (`<title>` tag is indeed updated). The LV being tested does set the `:page_title` assign and inspecting the value in the test confirms it.

### Expected behavior

Would expect this test passes:

```elixir
assert page_title(view) =~ "Update Profile"
```

Here is a PR on an app that exhibits this behavior with a failing CI check: https://github.com/newaperio/phoenix_starter/pull/203

[💬 For context link to Elixir Slack conversation.](https://elixir-lang.slack.com/archives/CD594E0UU/p1623961128441500)

**Comment by nickdichev** [comment]
I also have a minimal example repo which displays the behavior in this test file: https://github.com/nickdichev/phoenix_liveview_page_title_bug/blob/master/test/client_proxy_page_title_web/live/page_live_test.exs

Thanks!

**Comment by lleger** [comment]
Thanks for fixing this @chrismccord! Do you think it'll get ported to a 0.15.7 release or will we have to wait for 0.16.0 to get this?
