### ISSUE TITLE
Map.put(:action, :insert) removes param on Chrome

### ISSUE THREAD

**Issue by jfreeze** [phoenixframework/phoenix_live_view#150]
### Environment

* Elixir version (elixir -v):
Erlang/OTP 21 [erts-10.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [dtrace]
Elixir 1.8.0 (compiled with Erlang/OTP 21)

* Phoenix version (mix deps):

* file_system 0.2.6 (Hex package) (mix)
  locked at 0.2.6 (file_system) fd4dc3af
  ok
* connection 1.0.4 (Hex package) (mix)
  locked at 1.0.4 (connection) a1cae722
  ok
* gettext 0.16.1 (Hex package) (mix)
  locked at 0.16.1 (gettext) e2130b25
  ok
* ranch 1.7.1 (Hex package) (rebar3)
  locked at 1.7.1 (ranch) 6b1fab51
  ok
* telemetry 0.2.0 (Hex package) (mix)
  locked at 0.2.0 (telemetry) 5b40caa3
  ok
* decimal 1.7.0 (Hex package) (mix)
  locked at 1.7.0 (decimal) 30d6b52c
  ok
* jason 1.1.2 (Hex package) (mix)
  locked at 1.1.2 (jason) b03dedea
  ok
* db_connection 2.0.6 (Hex package) (mix)
  locked at 2.0.6 (db_connection) bde2f85d
  ok
* ecto 3.0.8 (Hex package) (mix)
  locked at 3.0.8 (ecto) 9eb6a1fc
  ok
* phoenix_pubsub 1.1.2 (Hex package) (mix)
  locked at 1.1.2 (phoenix_pubsub) 496c303b
  ok
* cowlib 2.7.0 (Hex package) (rebar3)
  locked at 2.7.0 (cowlib) 3ef16e77
  ok
* cowboy 2.6.1 (Hex package) (rebar3)
  locked at 2.6.1 (cowboy) f2e06f75
  ok
* mime 1.3.1 (Hex package) (mix)
  locked at 1.3.1 (mime) 30ce04ab
  ok
* postgrex 0.14.1 (Hex package) (mix)
  locked at 0.14.1 (postgrex) 63247d4a
  ok
* ecto_sql 3.0.0 (Hex package) (mix)
  locked at 3.0.0 (ecto_sql) 8d188337
  ok
* plug_crypto 1.0.0 (Hex package) (mix)
  locked at 1.0.0 (plug_crypto) 18e49317
  ok
* plug 1.7.2 (Hex package) (mix)
  locked at 1.7.2 (plug) d7b7db7f
  ok
* phoenix_html 2.13.2 (Hex package) (mix)
  locked at 2.13.2 (phoenix_html) f5d27c9b
  ok
* plug_cowboy 2.0.2 (Hex package) (mix)
  locked at 2.0.2 (plug_cowboy) 6055f168
  ok
* phoenix 1.4.3 (Hex package) (mix)
  locked at 1.4.3 (phoenix) 8eed4a64
  ok
* phoenix_live_reload 1.2.0 (Hex package) (mix)
  locked at 1.2.0 (phoenix_live_reload) 3bb31a9f
  ok
* phoenix_live_view 0.1.0 (https://github.com/phoenixframework/phoenix_live_view.git) (mix)
  locked at 1279f96
  ok
* phoenix_ecto 4.0.0 (Hex package) (mix)
  locked at 4.0.0 (phoenix_ecto) c43117a1
  ok

* NodeJS version (node -v):
v10.6.0

* NPM version (npm -v):
6.8.0

* Operating system:
Darwin 18.2.0 x86_64

### Actual behavior

A project showing this bug is at https://github.com/jfreeze/lv_form

Run the app and browse to http://localhost:4000/registrations/new

On Chrome browser, params will print to the console from inside `new.ex`
      `def handle_event("validate", %{"user" => params}, socket) do`
```
%{"email" => "x", "name" => "", "password" => "", "tos_agreement" => "false"}
%{"email" => "x", "name" => "", "password" => ""}
```

Browsing to the above url in Safari or Firefox prints the params as below:
```
%{"email" => "x", "name" => "", "password" => "", "tos_agreement" => "false"}
```

You can also comment out line #30 in `new.ex` and the bad param line does not exhibit itself in Chrome, but you don't get updates while typing.

**Comment by pawelduda** [comment]
I could not reproduce it. Used `Chrome Version 73.0.3683.86 (Official Build) (64-bit)` and all the params were there:

```elixir
%{"email" => "", "name" => "", "password" => "", "tos_agreement" => "true"}
%{"email" => "", "name" => "", "password" => "", "tos_agreement" => "true"}
%{"email" => "", "name" => "2", "password" => "", "tos_agreement" => "true"}
%{"email" => "", "name" => "", "password" => "", "tos_agreement" => "true"}
%{"email" => "", "name" => "t", "password" => "", "tos_agreement" => "true"}
%{"email" => "", "name" => "te", "password" => "", "tos_agreement" => "true"}
%{"email" => "", "name" => "tes", "password" => "", "tos_agreement" => "true"}
%{"email" => "", "name" => "test", "password" => "", "tos_agreement" => "true"}
%{"email" => "", "name" => "test@", "password" => "", "tos_agreement" => "true"}
%{"email" => "", "name" => "test@", "password" => "", "tos_agreement" => "false"}
```

**Comment by jfreeze** [comment]
You have to enter your first character on the email or the password.
If you don't, you will need to reload and try again.

Just reverified with Chris

[info] Replied phoenix:live_reload :ok
%{"email" => "", "name" => "", "password" => "x", "tos_agreement" => "false"}
%{"email" => "", "name" => "", "password" => "x"}
