### ISSUE TITLE
Params for a clicked form button are not sent to handle_event/3

### ISSUE THREAD

**Issue by bdtomlin** [phoenixframework/phoenix_live_view#1501]
### Environment

* Elixir version (elixir -v): Elixir 1.12.1 (compiled with Erlang/OTP 24)
* Phoenix version (mix deps): 1.5.9
* Phoenix LiveView version (mix deps): 0.15.7
* NodeJS version (node -v): 15.8.0
* NPM version (npm -v): v15.8.0
* Operating system: macOS Big Sure 11.4
* Browsers you attempted to reproduce this bug on (the more the merrier): Safari, Chrome, Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior
When submitting a form with a `phx-submit` handler on Chrome or Firefox the param for the clicked button is not included in the params sent to handle_event/3.

When using Safari, the button param is included.

I'm pretty sure that the different ways that the browsers handle `FormData` is the source of this issue. I think some changes to https://github.com/phoenixframework/phoenix_live_view/blob/master/assets/js/phoenix_live_view.js are needed to compensate for this.

### Expected behavior

I would expect the param from the clicked button to be present the the params sent to handle_event/3 in all browsers.

### Work around

I created a hook to use as a work around. There is probably a better way to handle this. I think it should be handled in the live view js.

Here is my work around hook:

```javascript
# Phoenix Live View Hook
const buttonValue = {
  mounted() {
    this.el.addEventListener("click", this.clickListener.bind(this))
  },
  clickListener() {
    const hiddenInput = document.querySelector(`input[type='hidden'][name='${this.el.name}']`)
    if (hiddenInput) {
      hiddenInput.value = this.el.value
    } else {
      const input = document.createElement("input")
      input.setAttribute("type", "hidden")
      input.setAttribute("name", this.el.name)
      input.setAttribute("value", this.el.value)
      this.el.closest("form").append(input)
    }
  }
}

export default buttonValue
```

**Comment by josevalim** [comment]
Yes, browsers indeed do not necessarily include this information on formdata. Note they don’t include this in regular form submission either, which is why we don’t try to capture it. A custom solution is the way to go in this case. You can also search in the issues tracker for past discussions.

**Comment by bdtomlin** [comment]
@josevalim,

Respectfully, I would like to provide more information since part of your reply isn't correct.

The name and value of the clicked button are included in regular form submission according the the HTML spec. Here are some links for some additional information: 

* [html spec](https://html.spec.whatwg.org/multipage/form-elements.html#the-button-element)
* [mdn](https://html.spec.whatwg.org/multipage/form-elements.html#the-button-element)
* [a simple app to demonstrate this locally](https://github.com/bdtomlin/fb)

Maybe your thoughts are the same about not handling it in live view, but I just wanted to make sure the decision is based on accurate information.

Thanks, and I really appreciate the amazing work you have put into the Elixir ecosystem :smile:

**Comment by josevalim** [comment]
Thanks for correcting me! <3

Indeed I misspoke: it is not that the browser does not submit it, it is rather that we don't have a reasonable API to access it from JS. See #1133 and the linked discussions!

**Comment by bdtomlin** [comment]
Thanks for that information. I was looking for that issue and couldn't find it. Hopefully this additional issue will give it a little more surface area and make it easier to find for others in the future.
