### ISSUE TITLE
Resetting a nested form back to its initial state is not possible

### ISSUE THREAD

**Issue by Awlexus** [phoenixframework/phoenix_live_view#151]
I have a nested form with some checkbox-, radiobutton- and select-elements. I can manipulate the form normally, but If I reset the form to its initial state, it jump back to the last state. 
For example, if I check only one checkbox and try to unset it, it stays checked. If I check another checkbox, I can uncheck the first one, but now I can't uncheck the second one, if it's the only change. Same thing applies to the other elements mentioned.

I logged what happens when I reset it to the initial state:
```
# Data comming in
params: %{"nested_model" => %{"radiobutton" => "true"}} # changed from false to true

# Changeset ( changes is empty, because it is put back into the initial state )
Nested.Model:16 2019-04-01 12:35:12.030234Z: #Ecto.Changeset<action: nil, changes: %{}, errors: [],
 data: #Nested.Model<>, valid?: true>

# Logging data with `FormData.input_value(changeset, nested_form, key) |> IO.inspect(label: "radiobutton")
radiobutton: "false" # Previous value
```

Additional: 
* I'm calling `cast_embed(:nested_model, with: &Nested.Model.changeset/2)` for evaluating changes

### Environment

Elixir version (elixir -v):
Erlang/OTP 21
Elixir 1.8.1 (compiled with Erlang/OTP 20)
Phoenix version (mix deps): 1.4.2
NodeJS version (node -v): v11.10.1
NPM version (npm -v): 6.7.0
Operating system: 10.13.6

**Comment by Awlexus** [comment]
I also just noticed that changes will be lost if I don't render parts of the nested form, then rerender it

**Comment by chrismccord** [comment]
Can you please include your entire template and live view? Thanks!

**Comment by Awlexus** [comment]
Sorry, I can not, becausd it is work related. I will create aproject showcasing the issue after work

**Comment by Awlexus** [comment]
I wasn't able to reproduce the issue yesterday at home, but today I solved it in my project at work, deleting the nested struct I set in the default struct. I'll have to try what happends, when I add it. [this](https://github.com/phoenixframework/phoenix_live_view/issues/151#issuecomment-478592634) still happens, but I'll try to fix that as well 
```diff
# A struct like this was passed in session
%Model{
-  nested: %Nested{}
}
```

**Comment by chrismccord** [comment]
If/when you are able to share a LIveView that recreates it, let us know. Thanks!

**Comment by Awlexus** [comment]
https://github.com/Awlexus/Buggy-project Sorry about my late response. Here is a project that should demonstrate what I was trying to report

**Comment by SamuelWillis** [comment]
I think I am experiencing this issue as well. I noticed it on forms with nested changesets and checkboxes.

Pretty much if I try toggle the same checkbox on and then off again the checkbox remains checked.

[Here is a replication repo. ](https://github.com/SamuelWillis/nested_changesets_live_view)

If you load up the `localhost:4000` there will be a form with a nested list of checkboxes. 

Clicking the same checkbox twice in a row will leave the check box checked.

Clicking the checkbox a third time will uncheck the checkbox visually, but if you submit the form the checkbox will be 
submitted in it's "checked" state.

It's only when you interact with a different checkbox that the original one is set to the "proper" state.
