### ISSUE TITLE
Select dropdown flashes close/open when assigns are updated on Chrome/MacOS

### ISSUE THREAD

**Issue by nikkocampbell** [phoenixframework/phoenix_live_view#1525]
### Environment

* Elixir version (elixir -v): 1.11.4
* Phoenix version (mix deps): 1.5.9
* Phoenix LiveView version (mix deps): 0.15.7
* NodeJS version (node -v): 14.16.0
* NPM version (npm -v): 6.14.11
* Operating system: Phoenix running on Ubuntu 21.04 locally, Alpine 3.13 in prod
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome 91.0.4472.114, Firefox 89.0.2, Safari 14
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

In Chrome on MacOS, an opened select box "flashes" open and closed repeatedly when an assign used in the page is updated. This makes it nearly unusable when frequent updates are happening

Chrome in both Windows and Linux seem to work without any issues

Safari is unaffected

Firefox on MacOS/Windows/Linux doesn't flash the select dropdown, but rather resets the cursor selection to the first item when the assign in updated. Less breaking of an issue since it doesn't affect functionality, but figured it may be related

No errors appeared in either server or browser console

Minimal repoduction repo: https://github.com/nikkocampbell/phx-live-mac-chrome-select-repro
Sample gif of the issue: 
![out](https://user-images.githubusercontent.com/1914937/125118429-aebd1480-e0bd-11eb-8a1a-395ecabdcf84.gif)

### Expected behavior

The select dropdown should be unaffected by assigns being updated

**Comment by mcrumm** [comment]
Hi @nikkocampbell – one thing I noticed in your example is that your `<select>` elements have no `selected` option. Browsers will implicitly set the first option as selected, and I think the flash is being caused by the implicit state when we re-focus the element after the DOM patch.

For example, if you set any option `selected` in each of your lists, the "flash" no longer occurs:

```html
  <select>
    <option value="1">1</option>
    <option selected value="2">2</option>
    <option value="3">3</option>
  </select>

  <select>
    <%= for i <- [1,2,3] do %>
      <option<%= if i == 3, do: ~S( selected) %> value="i"><%= i %></option>
    <% end %>
  </select>
```

**Comment by josevalim** [comment]
Could we automatically set the selected? Or do we want to document this behavior?

**Comment by nikkocampbell** [comment]
Ah, that was the issue, thank you @mcrumm !

For some more context, in our app we were using the the `options_for_select/2` helper, with `nil` as the default selected value. Testing without it didn't seem to have any difference so I had left it out of the reproduction. Switching it to an actual value of one of the options works as expected

**Comment by mcrumm** [comment]
> Could we automatically set the selected?

Perhaps, but a closer look makes me think this _may_ be a side-effect of the way we are determining whether or not to patch the select when it has focus.

I'll send a PR to show y'all what I mean and we can go from there.
