### ISSUE TITLE
Write your own Channel - not flexible - live_patch with wrong path

### ISSUE THREAD

**Issue by SebastianStroniewskiWojtczak** [phoenixframework/phoenix_live_view#1529]
### Environment

* Elixir version (elixir -v):Erlang/OTP 21 [erts-10.3.5.19] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]
* Phoenix version (mix deps): 1.5.9 (phoenix) 7e4bce20
* Phoenix LiveView version (mix deps): 0.15.7 (phoenix_live_view) 3a756cf6
* NodeJS version (node -v): v16.2.0
* NPM version (npm -v): npm@6.14.8
* Operating system: FreeBSD 13.0p3
* Browsers you attempted to reproduce this bug on (the more the merrier): Any
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior
While working with _router.ex_ I figure out that if there is no live path defined in router, app crashed (dev env). I was digging how _live_patch_ is handled and that leads me to _Phoenix.LiveView.Channel_, especially handle_info(...) that is so much important.

> def handle_info(%Message{topic: topic, event: "link"} = msg, %{topic: topic} = state) do
>     %{socket: socket} = state
>     %{view: view} = socket
>     %{"url" => url} = msg.payload
> 
>     case Utils.live_link_info!(socket, view, url) do
>       {:internal, params, action, _} ->
>         socket = socket |> assign_action(action) |> Utils.clear_flash()
> 
>         socket
>         |> Utils.call_handle_params!(view, params, url)
>         |> handle_result({:handle_params, 3, msg.ref}, state)
> 
>       {:external, _uri} ->
>         {:noreply, reply(state, msg.ref, :ok, %{link_redirect: true})}
>     end
>   end

### Expected behavior
It would be awesome to write our own Channel and do something like below

> use Phoenix.LiveView.Channel
> 
> \@impl true
> def handle_info(%Message{topic: topic, event: "link"} = msg, %{topic: topic} = state) do
>   **ret = ...do...our... stuff....**
>    .....
>     if ERROR do
>           Phoenix.LiveView.Channel.handle_info(msg, state)
>     else
>         ret
>     end
> end

With above approach we can have one Channel code placed in Phoenix.LiveView.~~ that is shared/used in our applications, in the meantime we can get more flexibility on _live_patch_. Lets say I want to handle special URL without defining it in _router.ex_ and in such case patch _LiveView_ with my custom data "access prohibited" or redirect to safe place.

Since _live_patch_ requests are not handled by _router.ex_ but by _Channel_ so we can get more responsibility what user is sending to us through _Channel_ topics and we can catch those or even all cases that we are interested. Lets say I want to log all requested url's and push back to LiveView. Without copying whole _Channel_ it is impossible to achieve such behavior. Maybe you have a nice idea how to handle wrong requests  ?

> <%=_ live_patch "DoNotPress", to: "/secret/url/not/defined/anywhere" %>

**Comment by josevalim** [comment]
We have no plans to go in this direction for now. The whole point of live_patch is to closely relate to the router and to make sure that the route is navigatable outside of LiveView (i.e. if you enter directly in the address bar).

If your goal is to perform logging, then we can definitely add telemetry events around live patch, but I don't think we should make live_patch customizable. If your goal is to have generic events, then using any of phx-click or similar is a better fit.
