### ISSUE TITLE
Log opt for Phoenix.Socket

### ISSUE THREAD

**Issue by pbrudnick** [phoenixframework/phoenix_live_view#153]
**Problem**: I don't want `:info` log level.

I was trying to pass the `log: :debug` option to my live socket but I realized it's no possible.
(like this: https://hexdocs.pm/phoenix/Phoenix.Socket.html#module-logging)

The *problem* is that following the README we have to add this to the `endpoint.ex` module:
```elixir
socket "/live", Phoenix.LiveView.Socket
```
and inside `Phoenix.LiveView.Socket` we have `use Phoenix.Socket` without options.

To *solve* that I had to copy the `Phoenix.LiveView.Socket` code into a module in my app inside `channels` (like `user_socket.ex`) that I named `live_socket.ex` and inside it *YES* I used `Phoenix.Socket` with the desired option.

Is this a correct approach? should `Phoenix.LiveView.Socket` cover this to not *exposing* this to the user?

**Comment by josevalim** [comment]
In Phoenix master (v1.5) we allow the :log to also be given on the `socket/2` call in the endpoint. So no need to create your own socket. To quote the docs:

```
  If your socket is implemented using `Phoenix.Socket`,
  you can also pass here all options accepted on
  `use Phoenix.Socket`. An option given here will override
  the value in `Phoenix.Socket`.
```
