### ISSUE TITLE
Page state is lost when a file is downloaded directly by the browser using `Content-Disposition: attachment` header

### ISSUE THREAD

**Issue by Spadavecchia** [phoenixframework/phoenix_live_view#1530]
### Environment

* Elixir version (elixir -v): 1.11.3-otp-23
* Phoenix version (mix deps): 1.5.7
* Phoenix LiveView version (mix deps): 0.15.0
* NodeJS version (node -v): 10.6.0
* NPM version (npm -v): 6.1.0
* Operating system: Ubuntu 20.04.2 LTS 
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome (91.0.4472.114) - Firefox (89.0.2)
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior
The page JS crashed, showing a `view crashed` message in JS console, when a file is downloaded directly by the browser.  The file is served with a `Content-Disposition: attachment` response header to prevent it from be rendered and a file download dialog is showed instead. The error occurs in the browser, JS level; the server doesn't log any message.

Minimal reproduction repo: https://github.com/Spadavecchia/liveview-download-file

https://user-images.githubusercontent.com/1404185/125642951-fcaf823b-ddd0-4caf-8323-2639f4d26199.mp4

### Expected behavior
The file should download and the page state should stay intact.

**Comment by chrismccord** [comment]
This is expected in this case when you are linking an anchor directly to a different URL. The browser will break the websocket connection and unload the page. In this case for direct file anchors, you can try `target="_blank"` on the anchor, the `download` attribute on the anchor (no IE support, and same origin applies), or drop to using a phx-hook and constructing the file downloading launching on the client side via `createObjectURL` depending on what you are doing. Closing as I don't believe there is anything for us to handle on our side.
