### ISSUE TITLE
Race condition in client showError code

### ISSUE THREAD

**Issue by sb8244** [phoenixframework/phoenix_live_view#1532]
### Environment

* Phoenix LiveView version (mix deps): `0.15.7`
* Operating system: Mac
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

There is an HTML element that when checked, will remove itself from the DOM. When this happens, an error for `phoenix_live_view.js:1963 Uncaught TypeError: Cannot read property 'querySelectorAll' of null` happens.

### Expected behavior

There should be no error when the element is checked. I didn't try on master, but the code is the same so I do not believe it would be fixed. I can check if necessary, although I am unable to try at the moment as this feature is still in progress.

### Possible Cause

I believe this is caused because the element is removed in the reply to the input change. https://github.com/phoenixframework/phoenix_live_view/blob/v0.15.7/assets/js/phoenix_live_view.js#L1616 will call `el.form`, which returns undefined because the element has been removed from the form by that point.

It might be possible to capture `inputEl.form` before `this.pushWithReply` is called. This would capture `form` and `DOM.all` would not be called with `undefined`. This seems like a better solution than changing `DOM.all` to handle an undefined element, because the `showError` function would still technically not be working as expected.

**Comment by mveytsman** [comment]
@sb8244 - you diagnosed the problem correctly thanks!
