### ISSUE TITLE
LiveViewTest doesn't support `refute_*`

### ISSUE THREAD

**Issue by a8t** [phoenixframework/phoenix_live_view#1539]
Hi, I'm wondering if there has been discussion (I searched inconclusively) about implementing the _inverses_ of LiveViewTest's `assert_*` utilities. I came across a use-case today to `refute_redirect`. Is there some workaround way to do this using the existing `assert_*` utility? Otherwise, are we interested in adding the `refute_*` utilities?

Thanks so much!

**Comment by josevalim** [comment]
PRs for refute_… are welcome.
