### ISSUE TITLE
Alpine V3 issues with x-transition and @click.outside

### ISSUE THREAD

**Issue by dvic** [phoenixframework/phoenix_live_view#1546]
### Environment

* Elixir version (elixir -v): 1.12.2 (compiled with Erlang/OTP 24)
* Phoenix version (mix deps): 1.5.9
* Phoenix LiveView version (mix deps): 0.15.7
* Operating system: macOS Big Sur
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, Firefox, Safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

After upgrading to Alpine v3, we are seeing an issue with `x-transition` and `@click.outside` (e.g. with popups) not working anymore once we navigate to another page (in Safari the popup briefly flickers, in other browsers it doesn't show). I have replicated the issue in the following repo:

https://github.com/dvic/phoenix_issues/tree/alpinev3-issue (issue illustrated in [page_live.html.leex](https://github.com/dvic/phoenix_issues/blob/alpinev3-issue/lib/demo_web/live/page_live.html.leex))

A summary of the problem (screenshot from the demo repo):

![image](https://user-images.githubusercontent.com/1214337/126638742-91737854-1880-45ea-be50-f2c00fe093b1.png)

Anyone else encountering similar issues? How can I find out which morphdom operations are executed in this example so that I can create a reproducible example for the alpine people (without LiveView)?

### Expected behavior

The Alpine directives `x-transition` and `@click.outside` should still work after a `live_redirect`.

**Comment by chrismccord** [comment]
You need to update your Dom callback to use the new alpine clone method:

https://github.com/dvic/phoenix_issues/blob/alpinev3-issue/assets/js/app.js#L47-L49

https://elixirforum.com/t/alpine-js-v3-support-for-liveview/40465

**Comment by dvic** [comment]
That's already in there right?
![image](https://user-images.githubusercontent.com/1214337/126642482-e5e493a2-4d83-41f8-8652-6465ab532bc2.png)

![image](https://user-images.githubusercontent.com/1214337/126642448-62e70df7-e5ae-445b-94a7-230c123f651a.png)

**Comment by chrismccord** [comment]
Yes sorry I thought it was the old reference. That's the entirety of the integration so I don't believe there is anything to be done on our side if things are not working for you as expected. You can try that forum thread to see if others can point you in the right direction :)

**Comment by dvic** [comment]
Yeah I figured that as well, I'll poke around and see what's going on here, thanks! One question related to this: does liveview now expose all morphdom operations as domOptions or just `onbeforeElUpdated`?

**Comment by benvp** [comment]
@dvic Did you find a solution for this? Running into the same issue right now and wasn't able to figure out any way to fix that.

**Comment by benvp** [comment]
I could find a workaround. It works as long as you split the `x-transition` from the `@click.outside` with a wrapper container. Don't know if it's better to use the workaround or just stick with alpine 2.x for now. 

I'd like to help out here but not sure where to start. Any hints?

That's what works for me right now:

```html
<div x-data="{open: false}">
  <button @click="open = true">Open</button>
  <button @click="open = false">Close</button>

  <div x-show="open" @click.outside="open = false">
    <div class="popup" x-show="open" x-transition>
      Hello world
    </div>
  </div>
</div>
```

**Comment by dvic** [comment]
> Did you find a solution for this? Running into the same issue right now and wasn't able to figure out any way to fix that.

No unfortunately not.. I created an issue https://github.com/alpinejs/alpine/discussions/1826 but I didn't get any response yet. I did find something in the LiveWire repo: https://github.com/livewire/livewire/blob/5cffdbfe4204e0d932cde6f8c9bdf63f0928b4d4/js/component/SupportAlpine.js#L260 It seems like they're doing extra stuff for `x-transition`.

> I could find a workaround. It works as long as you split the x-transition from the @click.outside with a wrapper container. Don't know if it's better to use the workaround or just stick with alpine 2.x for now.

Ah nice! Yeah I'm kind of hesitant of upgrading before I figure out what's causing this bug, because other stuff might also be broken.

**Comment by dvic** [comment]
> I'd like to help out here but not sure where to start. Any hints? 

The best thing I can think of is try to replicate it with LiveWire (the PHP framework), if the bug is not in there then we can see what's different about their approach to the morphdom integration.
