### ISSUE TITLE
Liveview UploadChannel Argument Error

### ISSUE THREAD

**Issue by fantypants** [phoenixframework/phoenix_live_view#1547]
### Environment

* Elixir version (elixir -v): 1.9.1
* Phoenix version (mix deps): 1.5.9
* Phoenix LiveView version (mix deps): 0.15.7
* Operating system: Linux Mint (K: 5.4.0-72-generic)
* Browsers you attempted to reproduce this bug on (the more the merrier): FireFox, Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Example Gist
[Example File Upload Gist](https://gist.github.com/fantypants/1fc5b1030c90bad0d7392e5d58a0f869)

### Actual behavior

File Upload save triggers an argument error within the upload_channel.ex file. This results in a consumption failure and file is not processed. 

in upload_channel.ex:44 =>

`socket.assign(socket, %{...`

After changing too:

`assign(socket, %{ ...`

the file is consumed correctly.

### Expected behavior

File should be able to be consumed correctly.

Happy to create PR and go through that method if this is an issue for anyone else

**Comment by josevalim** [comment]
I cannot see the problematic code in master. If you believe it still exists, a PR is welcome. Thanks!

**Comment by fantypants** [comment]
> I cannot see the problematic code in master. If you believe it still exists, a PR is welcome. Thanks!

I just double checked the master - you are correct, it's been fixed already. Thank you.
