### ISSUE TITLE
Programmatically submitting form results in actual form submit post request

### ISSUE THREAD

**Issue by SebastianSzturo** [phoenixframework/phoenix_live_view#155]
### Actual behavior

When submitting a live view form programatically via `form.submit()` it triggers an actual submit post request. 

```
<%= f = form_for @changeset, "#", [phx_submit: "save"] %>
   <%= text_input f, :name, onblur: "this.form.submit()" %>
</form>
```

### Expected behavior

I would expect it to trigger the `phx-submit` event and not an actual form submit post request.

**Comment by dsignr** [comment]
Not sure if this is related, but the same thing goes for `onChange`, etc. of individual form elements as well..I would expect `phx-change` on the form to be triggered too.

**Comment by jwietelmann** [comment]
I disagree with this. Current behavior conforms to the expected behavior for DOM events.

Programmatic `click()` or `submit()` do not trigger event handlers. For good reason: Often people will write a `'submit'` event handler that performs some side effects and then calls `submit()` on the form to continue performing the basic action. If it triggered the event handler again, you'd get an infinite recursion.

What you're looking to do requires different JavaScript code:

https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events#Triggering_built-in_events

**Comment by misswayua** [comment]
I am facing the same problem, the `phx-submit` is not being triggered but instead looks for a post request to pass the data

**Comment by chrismccord** [comment]
You should use `form.dispatchEvent(new Event("submit", {bubbles: true})` . Thanks!

**Comment by tfwright** [comment]
I just tried this on "0.13.3", "2186c55cc7c54ca45b97c6f28cfd267d1c61b5f205f3c83533704cd991bdfdec" and I'm still seeing the request. It does look like the event is also triggered, but then the page loads an error because of the missing form root.

**Comment by simoncocking** [comment]
It's worth pointing out that the `form.dispatchEvent()` trick is problematic in Firefox (at least as of v92.0 at this writing): Although the `phx_submit` message is triggered, Firefox obstinately insists on `POST`ing the form _as well_. I've not found a way to prevent it, so our workaround is to have a controller stub sitting there to `live_render/3` the page again, so at least the user doesn't get a 500.

**Comment by jayjun** [comment]
@simoncocking Firefox won’t `POST` if you set `cancelable: true` thereby allowing Phoenix LiveView’s [`e.preventDefault()`](https://github.com/phoenixframework/phoenix_live_view/blob/37fdd359ede0013e8d04642491f6781bea94a895/assets/js/phoenix_live_view/live_socket.js#L716) to work.

```js
form.dispatchEvent(new Event("submit", { bubbles: true, cancelable: true }));
```
Source: https://bugzilla.mozilla.org/show_bug.cgi?id=1370630

**Comment by Miserlou** [comment]
Thanks so much for the snippet, @jayjun  - this was driving me mad! Since it looks like FF has no intention of fixing this (their solution is to make it a user preference - _what?_), perhaps it should be added to the documentation?
