### ISSUE TITLE
Crash View after live_redirect when a phx_click is used in the middle

### ISSUE THREAD

**Issue by shahryarjb** [phoenixframework/phoenix_live_view#1550]
### Environment

* Elixir version (elixir -v): Elixir 1.12.0 (compiled with Erlang/OTP 24)
* Phoenix version (mix deps): 1.5.9
* Phoenix LiveView version (mix deps): 0.15.7
* Operating system: mac os 11.2.3 (with docker)
* Browsers you attempted to reproduce this bug on (the more the merrier):  Chrome and Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: no

when you use a `phx event` like `phx-click` in  the middle of `live_redirect`, after redirecting it takes 6 or 10 sec and crash the liveview and refresh the page.
```elixir
<%= live_redirect to: Routes.live_path(@socket, MishkaHtmlWeb.BlogPostLive, item.alias_link), replace: false do %>
 <img class="img-fluid client-home-normal-post-image" src="<%= item.main_image %>" alt="<%= item.title %>" id="<%= item.id %>" phx-click="image_go_to_post" phx-value-alias-link="<%= item.alias_link %>">
<% end %>
```

the error is shown is
```
LiveView Falling back to hard refresh for recovery
```

![without-liverender](https://user-images.githubusercontent.com/8413604/127750407-03593a69-e850-4449-94e8-3034c51668c7.png)

it should be noted, if I do without `phx-click` like this code I have no error and code works for me
```elixir
<%= live_redirect to: Routes.live_path(@socket, MishkaHtmlWeb.BlogPostLive, item.alias_link), replace: false do %>
   <img class="img-fluid client-home-normal-post-image" src="<%= item.main_image %>" alt="<%= item.title %>" id="<%= item.id %>">
<% end %>
```

The project I will release open source ( a phoenix elixir CMS) is: https://github.com/shahryarjb/mishka-cms

**Comment by chrismccord** [comment]
Can you try master to see if this is resolved there already? thanks!

**Comment by shahryarjb** [comment]
@chrismccord ,  unfortunately I tried several times to update my project to master, but it has many errors like this

### mix:
```elixir
{:phoenix_live_view, git: "https://github.com/phoenixframework/phoenix_live_view.git", override: true},
{:phoenix_html, github: "phoenixframework/phoenix_html", override: true},
```

### error:

```elixir
== Compilation error in file lib/mishka_html_web/router.ex ==
** (ArgumentError) unknown live option :session.

Supported options include: :container, :as, :metadata, :private.

Got: [session: {Phoenix.LiveDashboard.Router, :__session__, [nil, false, {MishkaHtmlWeb.Telemetry, :metrics}, nil, [], nil, nil, nil]}]

    (phoenix_live_view 0.16.0-dev) lib/phoenix_live_view/router.ex:389: anonymous fn/1 in Phoenix.LiveView.Router.validate_live_opts!/1
    (elixir 1.12.0) lib/enum.ex:930: Enum."-each/2-lists^foreach/1-0-"/2
    (phoenix_live_view 0.16.0-dev) lib/phoenix_live_view/router.ex:363: Phoenix.LiveView.Router.validate_live_opts!/1
    (phoenix_live_view 0.16.0-dev) lib/phoenix_live_view/router.ex:343: Phoenix.LiveView.Router.__live__/4
    lib/mishka_html_web/router.ex:85: (module)
    (stdlib 3.15) erl_eval.erl:685: :erl_eval.do_apply/6
    (elixir 1.12.0) lib/kernel/parallel_compiler.ex:319: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

do you have a sample project which has master LiveView to clone it ?

**Comment by shahryarjb** [comment]
@chrismccord After hours and delete live dashboard in my mix file and create a new project, I succeeded to test master of LiveView, I think it was fixed , because I couldn't find any problem which I had on 0.15.7 version 

Thanks

**Comment by chrismccord** [comment]
A new release will be out shortly. Thanks for confirming!

**Comment by hubertlepicki** [comment]
@shahryarjb do you know what was the issue related to this error you were having `** (ArgumentError) unknown live option :session.` ?

I am trying to update my app to liveview 1.6.4 and I am stuck at the same issue.

**Comment by hubertlepicki** [comment]
I suspect the documentation is outdated and I need to remove `session: ...` from my `live/4` entries in `router.ex`, and replace it with `live_session` instead.

The documentation bit that seems outdated is also in v1.7.3 docs:

```
https://hexdocs.pm/phoenix_live_view/0.17.3/Phoenix.LiveView.html
```

```

It is also possible to pass additional session information to the LiveView through a :session option:

# In the router
live "/thermostat", ThermostatLive, session: %{"extra_token" => "foo"}

```

This seems to be the old mechanism that's no longer valid?

**Comment by josevalim** [comment]
Correct. I will fix the docs!

**Comment by hubertlepicki** [comment]
Awesome!
