### ISSUE TITLE
feature request: Interchangeable nesting of ignored/not ignored containers

### ISSUE THREAD

**Issue by DaTrader** [phoenixframework/phoenix_live_view#1552]
Relative to JS interoop and integrating LV projects with other JS frameworks and components (e.g. JS scrollbar), it would be _very_ useful to have the feature of nesting non-ignored containers within ignored ones.

Explanation:
At present, ignored containers simply get ignored as a whole meaning they cannot container LV-managed elements anywhere in their hierarchy. So, if a container that otherwise contains LV managed elements, needs to feature a JS scrollbar library which alters the container attributes and possibly adds additional elements to it, the only way (known to me) to properly handle this is by relying on beforeUpdate/updated callbacks to save/restore the JS library attribute values. This is indeed sufficient if the library only relies on attributes, but if it also adds its own HTML elements, it is no longer enough and an update call to the library is required to have it reinsert its elements once LV removes them. This update can be sometime expensive and/or have glitch-like side effects.

Therefore, wouldn't it be nice if there was no need to manually restore the attribute values and force-reinsert the external library controlled content?

My suggestion is about adding support for the following:

```
<div phx-update="ignore">
  <div id="MyResponsiveContainer">
     <div id="MyLVManagedContent" phx-update="update">
       ..
     </div>
     <!-- external JS library added elements expected here -->
  </div>
</div>

```

Thanks!

**Comment by josevalim** [comment]
We have no plans to support something like this at the moment. The idea is to move the ignore inside and wrap around the relevant bits. If necessary, request or try to customize the libraries so the elements can be added with more flexibility.

**Comment by DaTrader** [comment]
Well, you can't say I didn't try :)
