### ISSUE TITLE
Unable to access conn's assigns from live_rendered Live View

### ISSUE THREAD

**Issue by kieraneglin** [phoenixframework/phoenix_live_view#1555]
### Environment

* Elixir version (elixir -v): 1.12.2
* Phoenix version (mix deps): branch v1.5 (for MFA tuples needed for ESBuild)
* Phoenix LiveView version (mix deps): 0.15.7
* Operating system: N/A
* Browsers you attempted to reproduce this bug on (the more the merrier): N/A
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Context

I'm using Live Views more like widgets on a page but routing and mounting is handled by traditional controllers.  This is because I want to be able to return proper HTTP codes and server-issued redirects if needed.

This causes an issue where I'm often duplicating work and database calls - once in the controller and once in a Live View.  For instance, if I wanted to render a TODO list I use the controller to render the proper view if a TODO list exists or to render a 404 if it does not.  Assuming success, the view would contain something like this:

```elixir
<%= live_render(@conn, MyappWeb.TodoListLive, session: %{"todo_list_id" => @todo_list.id}) %>
```

Since I cannot directly access the conn's assigns I have to pass data via the session and re-fetch in the Live View, duplicating a database call.  This is a contrived example to be sure, but I hope it gets the point across.

Another example is with user authentication via a Plug.  If my controller ensures the existence and auth state of a given user, it's counter-intuitive to then have to re-check and fetch user data in the Live View.

### Actual behavior

A connection's assigns are not passed (either implicitly or explicitly) to a `live_render`ed view

### Expected behavior

A connection's assigns are either passed automatically to then be accessed by `socket.assigns` in the Live View, or instead it could be passed manually like so:

```elixir
<%= live_render(@conn, MyappWeb.TodoListLive, assigns: %{todo_list: @todo_list, current_user: @current_user}) %>
```

___

If this is unexpected behaviour I'd be more than happy to open a PR!  If I'm not mistaken it should be simple enough to add considerations for the assigns [here](https://github.com/phoenixframework/phoenix_live_view/blob/v0.15.7/lib/phoenix_live_view/static.ex#L116) and [here](https://github.com/phoenixframework/phoenix_live_view/blob/v0.15.7/lib/phoenix_live_view/utils.ex#L65)

**Comment by josevalim** [comment]
This is expected behavior. A LiveView runs in a separate connection and can be recovered at any time. You can use assign_new in the LiveView and it will use the assign from the connection if one already exists, this is done so we provide caching without hurting LiveView isolation.

**Comment by kieraneglin** [comment]
@josevalim fair enough! I see it's mentioned in the docs, but there seems to be a lot of confusion about the purpose of `assign_new` with regards to pulling conn data into the LV. The docs say "assigns will not be available during the connected mount", but it seems like any socket assigns I set in the initial mount aren't persisted. If that's the case it doesn't help with the issue of DB calls being duplicated.  Is there an official recommendation for this use case? 

Here's a more concrete example:

```elixir
# Controller
defmodule MyappWeb.PostController do
  use MyappWeb, :controller

  alias Myapp.Posts

  def show(conn, %{"id" => id}) do
    post = Posts.get_post(id)
      
    if post do
      live_render(conn, MyappWeb.Posts.PostViewLive, session: %{"post_id" => post.id})
    else
      redirect(conn, "404.html")
    end
  end
end

# post_view_live
def mount(_params, %{"post_id" => post_id}, socket) do
  new_socket = assign_new(socket, :post, fn -> Posts.get_post(post_id) end)
    
  {:ok, new_socket}
end
```

In this example the `new_socket` will first show the assigns containing the `post` object without a second DB call (as expected) but then when `mount` is called the second time the assign for `post` won't be present, causing another DB call.

___

At least to me that's pretty counter-intuitive.  I understand wanting to preserve the isolation of a LV, but is there any recommended mechanism to handle this case?  Personally I'd expect the `socket` returned by the first invocation of `mount` to become the passed socket argument for the second invocation.

**Comment by kieraneglin** [comment]
Fair enough!  Thank you both very much for the insight
