### ISSUE TITLE
There seems to be a typo in the documentation around "target"

### ISSUE THREAD

**Issue by HendrikPetertje** [phoenixframework/phoenix_live_view#1564]
### Environment

* Elixir version (elixir -v): Elixir 1.12.1 (compiled with Erlang/OTP 23)
* Phoenix version (mix deps): 1.5.10 (Hex package) (mix)
* Phoenix LiveView version (mix deps):0.15.7 (Hex package) (mix)
* Operating system: MacOSX Big Sur 11.4
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox, Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: YES

### Actual behavior

Visit docs page and see description telling me to write phx-target as "phx-target={@myself}"
https://hexdocs.pm/phoenix_live_view/Phoenix.LiveComponent.html
<img width="915" alt="image" src="https://user-images.githubusercontent.com/3583395/129400091-88d096a2-16e0-4581-8602-8f236bee78a8.png">

Try to actually write that in my html.leex file
Event goes nowehere when I click button (it's not emitted to the backend)

<img width="1516" alt="image" src="https://user-images.githubusercontent.com/3583395/129400492-1ccbe9b3-5bb8-4048-b3f1-4a8e65927405.png">
<img width="1516" alt="image" src="https://user-images.githubusercontent.com/3583395/129400510-59a9eba1-a4a1-4bf7-aec4-d20f244eb5fd.png">

Change code to 
Editor:  
<img width="661" alt="image" src="https://user-images.githubusercontent.com/3583395/129400578-ae8a3778-606d-4533-b196-d7b8cbadd5ae.png">
Rendered:  
<img width="856" alt="image" src="https://user-images.githubusercontent.com/3583395/129400650-efbc05a9-3ac5-48fc-bf64-a0949bd8edde.png">

*click
Great success!
<img width="1516" alt="image" src="https://user-images.githubusercontent.com/3583395/129400754-3ef2a742-3dc8-40ef-8b28-076b9facbbeb.png">

### Expected behavior
- Docs to mention correct syntax for html.leex or the html.leex rendering dealing correctly with prop={} attributes.

Sorry for the issue I'm opening, I'd love to provide a pull req with this, but I'm unsure where to begin.

**Comment by josevalim** [comment]
Hi @HendrikPetertje!

The docs in master have been updated to use the new HEEx templates / ~H sigil, with a slight different syntax. So you either need to use the old synyax, which you suggested, or update everything to HEEx/~H.

**Comment by HendrikPetertje** [comment]
Gotcha, so to iterate this correctly for users seeing this issue in the future (and future me)

```
some_page.html.leex 
```

as well as 

```
def render(assigns) do
~L"""
<h1 class="#{assigns.my_stateful_class}">Hello world!</h1>
"""
end
```

becomes 


```
some_page.html.heex 
```

as well as 

```
def render(assigns) do
~H"""
<h1 class={assigns.my_stateful_class}>Hello world!</h1>
"""
end
```

Thanks for taking the time to respond to the issue I posted @josevalim, really appreciated!

**Comment by HendrikPetertje** [comment]
Gotcha, so to iterate this correctly for users seeing this issue in the future (and future me)

```
some_page.html.leex 
```

as well as 

```
def render(assigns) do
~L"""
<h1 class="#{assigns.my_stateful_class}">Hello world!</h1>
"""
end
```

becomes 


```
some_page.html.heex 
```

as well as 

```
def render(assigns) do
~H"""
<h1 class={assigns.my_stateful_class}>Hello world!</h1>
"""
end
```

Thanks for taking the time to respond to the issue I posted @josevalim, really appreciated!
