### ISSUE TITLE
Breaking changes for layout option in `Phoenix.LiveView.Router.live/4`

### ISSUE THREAD

**Issue by matthewlehner** [phoenixframework/phoenix_live_view#1565]
### Environment

* Elixir version (elixir -v): 1.11
* Phoenix version (mix deps): 1.6
* Phoenix LiveView version (mix deps): 0.16
* Operating system: MacOS
* Browsers you attempted to reproduce this bug on (the more the merrier): 
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:

### Actual behavior

I'm in the process of upgrading our app from LiveView 0.15.7 → 0.16.0 and am getting the following compilation error:

```
== Compilation error in file lib/my_app_web/router.ex ==
** (ArgumentError) unknown live option :layout.

Supported options include: :container, :as, :metadata, :private.
```

Looking through the docs, I can't see an alternative or workaround to this change.

Looks like the option was removed in https://github.com/phoenixframework/phoenix_live_view/commit/67ed03e34e35ebe09512f4cf13f1e39ca4f86145#diff-c05739a1d15ca243adeb5be1fdba00cb5e0b740cf0667a4ae81fbe4994899e14

### Expected behavior

The layout option isn't removed, or the changelog talks about what to do now that it's changed.

**Comment by josevalim** [comment]
It is intentional. It should be given on live_session instead. Feel free to send a PR for the CHANGELOG otherwise I will do it in 30.

**Comment by matthewlehner** [comment]
@josevalim On it with the changelog PR (hope you haven't already started)

**Comment by josevalim** [comment]
I have not, go for it!
