### ISSUE TITLE
HEEX Templates Choke on Some Forms of Interpolation

### ISSUE THREAD

**Issue by jherdman** [phoenixframework/phoenix_live_view#1568]
### Environment

* Elixir version (elixir -v):

Erlang/OTP 24 [erts-12.0.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]
Elixir 1.12.1 (compiled with Erlang/OTP 24)

* Phoenix version (mix deps):

phoenix 1.5.10 (Hex package) (mix)
locked at 1.5.10 (phoenix) f9c2eaa5

* Phoenix LiveView version (mix deps):

phoenix_live_view 0.16.0 (Hex package) (mix)
locked at 0.16.0 (phoenix_live_view) eed6ba0a

* Operating system: Linux

* Browsers you attempted to reproduce this bug on (the more the merrier):  irrelevant

* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

Given this heex template:

```
<div data-foo="{ apple: '<%= @my_assign %>' }">hello</div>
```

We see this error:

> nofile:34:25: expected closing `"` for attribute value

Alternatively...

```
<div data-foo="{ apple: '{@my_assign}' }">hello</div>
```

The following is rendered:

```html
<div data-foo="{ apple: '{@my_assign}' }">hello</div>
```

i.e. `'{@my_assign}'` is not interpolated

### Expected behavior

There is a reasonable way to interpolate the `@my_assign` into the template. This is valuable for things like Alpine's `x-data` and friends.

**Comment by jherdman** [comment]
Note:

```
<div data-foo="{ apple: '#{@my_assign}' }">hello</div>
```

Does not work either (re suggestion by @msaraiva in Slack).

**Comment by josevalim** [comment]
@jherdman that should definitely work. Do you get an error or exception?

**Comment by josevalim** [comment]
Also, we need to investigate why is it showing nofile instead of the actual filename.

**Comment by josevalim** [comment]
@jherdman is that a file on disk or is it the ~H sigil?

**Comment by jherdman** [comment]
Exception, and this is from a file on disk.

I should note that per further conversation in Slack (apologies — I seemed to have filed this too soon), the template _should be_:

```
<div data-foo={"{ apple: '#{@my_assign}' }"}>hello</div>
```

Two notes:

1. The wrap of `{ ... }` around the whole attr caught me by surprise
2. Within the `{ }` I'm more or less in normal Elixir String land, which was quite surprising

**Comment by josevalim** [comment]
Correct. The syntax for Elixir values (and interpolation) starts with bracket. For the nofile in error messages, I pushed a fix to master. Thanks!
