### ISSUE TITLE
connected?(socket) is returning "false" , even though being mounted at router after upgrading phoenix_live_view.

### ISSUE THREAD

**Issue by Ritvyk** [phoenixframework/phoenix_live_view#1569]
### Environment

* Elixir version (elixir -v): "~> 1.12"
* Phoenix version (mix deps): ~> 1.5.9
* Phoenix LiveView version (mix deps):  ~> 0.16.0"
* Operating system: Linux Ubuntu (20.04)
* Browsers you attempted to reproduce this bug on (the more the merrier): Google Chrome , Firefox & Safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: **Yes**

### Actual behavior

I upgraded to the latest **phoenix_live_view** (0.16.0) , and tried mounting a **/testpage** at the route, it's a live view, it was behaving unusual as it wasn't executing **_send(self(),{:render_component})_** , I doubled check the dependencies and they are on point as they were working well with previous live view version.

I did `IO.inspect( connected?(socket) )` but it seems to be only logging out false everytime , even though the live_view has been mounted at router.

### Expected behavior

`connected?(socket)` should return `true` as i have just upgraded to latest live view nothing else.

### Screenshots / Code : 

```
defmodule Rweb.TestPagesLive.Show do
  use RWeb, :live_view
 
  def mount(_params, session, socket) do
   
    IO.puts("Mounted Test Page")

    if connected?(socket) do
      IO.inspect("conected")
    end
   
    {:ok, socket}
  end
```

> **Output** : 
--> `Mounted Test Page` is being logged out in the console

> **Expectation**:
--> `connected` should also be logged out 

Thanks in advance as it has affected the whole application.

**Comment by josevalim** [comment]
Can you please provide a small application that reproduces the error? A LiveView is first rendered over HTTP, which makes it return false for connected, but then it should connect over web sockets.

make sure that the web socket connection is happening and, if it does and it returns false, please provide a small app to reproduce it.  Thanks!

**Comment by Ritvyk** [comment]
@josevalim strange when I did `mix phx.new app_name --live` and updated the `deps` with new `live_view` it's working, something probably wrong at upgrading the older code base to newer one ! , my previous version of `live_view was 0.15.0` , do you think that this can be a problem ?

**Comment by josevalim** [comment]
No, that should not be a problem. It should all work, even on earlier versions. Make sure you remove node_modules just in case it is a cache issue.

**Comment by josevalim** [comment]
Hi @Ritvyk, if this is still an issue and you can provide a way to reproduce it, please let us know. Otherwise I am assuming it isn't an issue here as it doesn't happen in new apps. :) Thanks!
