### ISSUE TITLE
Alpine.js x-data gets out of sync with assigns

### ISSUE THREAD

**Issue by dev-cyprium** [phoenixframework/phoenix_live_view#1579]
### Environment

* Elixir version (elixir -v): 
```
➜ elixir -v
Erlang/OTP 22 [erts-10.7.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.11.3 (compiled with Erlang/OTP 21)
```
* Phoenix version (mix deps):
```
{:phoenix, "~> 1.5.10"}
```
* Phoenix LiveView version (mix deps):
* Operating system:
```
macOS Big Sur
11.5.2
```
* Browsers you attempted to reproduce this bug on (the more the merrier): 
```
Chrome, Firefox Nightly, Firefox developer edition, Firefox, Safari
```
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:
```
Yes
```

** Note, I've tested it with the Phoenix `16-rc`, and the bug still remains.
### Actual behavior

Simply put, the state of the `assigns` from the `LiveView` get out of sync with `Alpine.js`. I've tried to fix the issue in user land, but I couldn't find a way to get it working.

Even though I have this snippet: 

```
dom: {
    onBeforeElUpdated(from, to) {
      if (from._x_dataStack) {
        window.Alpine.clone(from, to);
      }
    },
  },
```

The actual code:
```eex
<section x-data="{count: <%= @count %>}">
  <h1>The count is (from phoenix): <%= @count %></h1>
  <h1>The count is (from Alpine): <span x-text="count"></span></h1>
  <button class="button" phx-click="increment">
    Increment
  </button>
  <button class="button" phx-click="decrement">
    Decrement
  </button>
</section>

```

```elixir
defmodule BugAlpineWeb.PageLive do
  use BugAlpineWeb, :live_view

  @impl true
  def mount(_params, _session, socket) do
    {:ok, assign(socket, count: 0)}
  end

  @impl true
  def handle_event("increment", _, socket) do
    {:noreply, update(socket, :count, &(&1 + 1))}
  end

  @impl true
  def handle_event("decrement", _, socket) do
    {:noreply, update(socket, :count, &(&1 - 1))}
  end
end
```

If you run the demo repo, or visit this Heroku link, you'll see that the Alpine.js state and assigns get out of sync.
https://damp-reaches-77745.herokuapp.com

The repository is linked here: https://github.com/dev-cyprium/alpine-live-bug

### Expected behavior

These 2 counters should be in sync.

**Comment by josevalim** [comment]
What is your alpine version? The code to integrate with Alpine has changed between v2 and v3, so you may want to check other discussions in the issues tracker.

**Comment by chrismccord** [comment]
This is not something related tithe LV side. Check the forums as you may need to initTree with apline after clone, but afaik x-data cannot be reset like that on a node and be picked up by default. Thanks!
