### ISSUE TITLE
New heex engine should treat nil as an empty list for dynamic attributes

### ISSUE THREAD

**Issue by seb3s** [phoenixframework/phoenix_live_view#1592]
Hello,
I wish the new heex engine treat a nil value for dynamic attributes as an empty list (meaning no attributes are to be rendered).
I'm converting my leex to heex and I wrote the following as an illustration:

`<div {if user_rights(@board, :move_column?), do: [{"phx-hook", "sortable_columns"}], else: []}>`

I would like to be able to remove the else part in this case.
Cheers,

Sébastien.

**Comment by josevalim** [comment]
For now, I would go with a no, to keep the contract clearer. Counter suggestions:

1. Write the above as a regular attribute:

        <div phx-hook={user_rights(@board, :move_column?) && "sortable_columns"}>

2. Move the above to a separate function, where perhaps there will be less need to make it super compact

        <div {sortable_hook_attributes(@board)}>

:)

**Comment by seb3s** [comment]
Hi josé,

1. doesn't work for most cases where multiple attributes are used (which is in fact the purpose of dynamic attributes i guess)
such in :

`     {if @column.descr, do:
            [{"id", temp_id()}, {"phx-hook", "tippy"},
             {"data-tippy-placement", "bottom-start"},
             {"data-tippy-allowhtml", "true"},
             {"data-tippy-theme", "light-border lightblue-bg"},
             {"data-tippy-offset", "[0, 4]"},
             {"data-tippy-maxwidth", "282"},
             {"data-tippy-content", text_to_html(@column.descr)}
            ], else: []}`
2. I lost the dynamic part if I have to write a func for all of these

I will stick with the else part for now ;-)
Thanks for your hard work !
