### ISSUE TITLE
Different behaviour between leex & heex

### ISSUE THREAD

**Issue by seb3s** [phoenixframework/phoenix_live_view#1593]
Hi,
don't know if it is intended but I noticed the following unwanted effect:
leex:
`<div id="<%= temp_id() %>" phx-hook="scroll_on_update" data-scroll-count="<%= @scroll_count %>"></div>`
heex:
`<div id={temp_id()} phx-hook="scroll_on_update" data-scroll-count={@scroll_count}></div>`

When @scroll_count is updated, only data-scroll-count gets updated in leex, whereas in heex, both id & data-scroll-count gets re-rendered. This results in broken behaviour in my application.
Is this wanted or did I miss something ?

Cheers, 
Sébastien

**Comment by josevalim** [comment]
Hrm, we can definitely improve this and keep all attributes that never change in a separate bundle. It means that we would still resend both for:

    <div id={@temp_id} phx-hook="scroll_on_update" data-scroll-count={@scroll_count}></div>

But your case would be addressed. :)

**Comment by seb3s** [comment]
And to make it complete, writing :

`<div {[id: temp_id(), data_scroll_count: @scroll_count]} phx-hook="scroll_on_update"></div>`

fails to me as both get re-rendered in that case.

**Comment by josevalim** [comment]
Today we separate the attributes in three buckets: fully static, partially static (the key is known but value is not) and fully static. Hence the behaviour. The secret is to separate them into individual buckets based on what trigger their change.

**Comment by seb3s** [comment]
What's the difference between fully static & fully static ?
;-)

**Comment by josevalim** [comment]
Haha, meant to be fully dynamic, of course. When you do `{keyword_list_or_map}`. :)
