### ISSUE TITLE
Another diff between leex & heex

### ISSUE THREAD

**Issue by seb3s** [phoenixframework/phoenix_live_view#1594]
I use the following code to produce pseudo xml export of data in kandesk (small opensource kanban app) :

```
<textarea class="textarea" style="min-height: 20em;">
<board>
  <name><%= @board.name %></name><%= if @board.descr do %>
  <descr><%= @board.descr %></descr><% end %>
  <%= for column <- if @column_id, do: Enum.filter(@columns, & &1.id == @column_id), else: @columns do %>
  <column>
    <name><%= column.name %></name><%= if column.descr do %>
    <descr><%= column.descr %></descr><% end %>
    <%= for task <- column.tasks do %>
    <card>
      <name><%= task.name %></name><%= if task.descr do %>
      <descr><%= task.descr %></descr><% end %>
      <%= for tag <- Enum.filter(@board.tags, fn tag -> Enum.find(task.tags, & &1.id == tag.id) end) do %>
      <tag><%= tag.name %></tag>
      <% end %>
    </card>
    <% end %>
  </column>
  <% end %>
</board>
</textarea>
```

It was initially written with leex.
Converting it to heex has the undesirable side effect that all <%= for... %> and <% end %> instructions produce newline in the generated html.
I would expect these special  lines to be transparent as fixing it in the template produces unreadable spaghetti ;-)

Sebastien.

**Comment by josevalim** [comment]
I cannot reproduce this difference in behaviour. Here is the code:

```elixir
  import Phoenix.LiveView.Helpers

  def run do
    assigns = %{list: [1, 2, 3]}

    l = ~L"""
    <div>
      <%= for i <- @list do %>
        <foo><%= i %></foo>
      <% end %>
    </div>
    """

    h = ~H"""
    <div>
      <%= for i <- @list do %>
        <foo><%= i %></foo>
      <% end %>
    </div>
    """

    IO.inspect l
    IO.inspect h

    IO.inspect l.dynamic.(false)
    IO.inspect h.dynamic.(false)
  end
```

They have different fingerprints and stuff, but the static and dynamic bits are all the same.

**Comment by seb3s** [comment]
Hi José,
Yes you're right, I get the same output now with both engine. 
This is  more probably a difference between 0.15.x & 0.16.x versions.

**Comment by seb3s** [comment]
Anyway, it would be cool if special forms <%= if  %>  <%= for  %>  <% end  %>  are made transparent when they are alone on a template line.
What do you think ?

**Comment by josevalim** [comment]
It is much tricker in practice because in some places removing the line can cause different behaviour. The classic example is textareas. It is unlikely we will see changes in this area for now. :)
