### ISSUE TITLE
Opening/Closing Tags in branches confuse HTML Engine

### ISSUE THREAD

**Issue by SteffenDE** [phoenixframework/phoenix_live_view#1604]
### Environment

* Elixir version (elixir -v): 1.12.2
* Phoenix version (mix deps): 1.6.0-rc.0
* Phoenix LiveView version (mix deps): 0.16.3
* Operating system: macOS

### Actual behavior

Considering the following HEEx Templates:
```elixir
<p>This is a
<%= if @assign == :foo do %>
    test
</p>
<% else %>
    fail
</p>
<% end %>
```
--> raises at line 7
```
(SyntaxError) missing opening tag for </p>

Stacktrace:
  │ (phoenix_live_view 0.16.3) lib/phoenix_live_view/html_engine.ex:174: Phoenix.LiveView.HTMLEngine.pop_tag!/2
  │ (phoenix_live_view 0.16.3) lib/phoenix_live_view/html_engine.ex:309: Phoenix.LiveView.HTMLEngine.handle_token/3
  │ (elixir 1.12.2) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
  │ (eex 1.12.2) lib/eex/compiler.ex:48: EEx.Compiler.generate_buffer/4
  │ (eex 1.12.2) lib/eex/compiler.ex:80: EEx.Compiler.generate_buffer/4
  │ (phoenix_live_view 0.16.3) expanding macro: Phoenix.LiveView.Renderer.__before_compile__/1
  │ lib/html_engine_bug_web/live/page_live.ex:1: HtmlEngineBugWeb.PageLive (module)Elixir
No quick fixes available
```

and

```elixir
<%= if @foo == :bar do %>
    <p>Cool
<% else %>
    <p>Not Cool
<% end %>
</p>
```
--> raises at line 6
```
(SyntaxError) missing opening tag for </p>

Stacktrace:
  │ (phoenix_live_view 0.16.3) lib/phoenix_live_view/html_engine.ex:174: Phoenix.LiveView.HTMLEngine.pop_tag!/2
  │ (phoenix_live_view 0.16.3) lib/phoenix_live_view/html_engine.ex:309: Phoenix.LiveView.HTMLEngine.handle_token/3
  │ (elixir 1.12.2) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
  │ (eex 1.12.2) lib/eex/compiler.ex:48: EEx.Compiler.generate_buffer/4
  │ (phoenix_live_view 0.16.3) expanding macro: Phoenix.LiveView.Renderer.__before_compile__/1
  │ lib/html_engine_bug_web/live/page_live.ex:1: HtmlEngineBugWeb.PageLive (module)Elixir
No quick fixes available
```

I've noticed this while trying to port the bytepack totp component to use HEEx: https://github.com/dashbitco/bytepack_archive/blob/79f8e62149d020f2afcc501592ed399f7ce7a60b/apps/bytepack_web/lib/bytepack_web/live/user_settings_live/totp_component.ex#L80

### Expected behavior

I guess the engine should keep track if a tag is opened or closed inside a branch.

**Comment by josevalim** [comment]
This is expected. We don't plan to track opened or closed inside branches, it should be moved either inside or outside the conditional. :)

**Comment by SteffenDE** [comment]
Alright, thank you for the quick clarification! As this is something that worked when using LEEx, maybe it should be added to the [heex-pitfalls](https://hexdocs.pm/phoenix_live_view/0.16.3/assigns-eex.html#heex-pitfalls)?

**Comment by josevalim** [comment]
I am not sure. It only makes sense when you consider LEEx and how it allowed no structure on the HTML. If someone starts with HEEx today, I am not convinced the would expect this to work, as the markup is definitely broken apart.

**Comment by Zurga** [comment]
I had the same issue when I tried to conditionally tried to wrap an HTML element. 

So:
```
<%= if true do %>
<div>
<% end %>
<p>wrapped</p>
<%= if true do %>
</div>
<% end %>
```

**Comment by Zurga** [comment]
I experience the same issue when conditionally trying to wrap an element. So for example:
```
<%= if true do %>
  <div>
<% end %>
<p>wrapped</p>
<%= if true do %>
  </div>
<% end %>
```

**Comment by SteffenDE** [comment]
> If someone starts with HEEx today, I am not convinced the would expect this to work, as the markup is definitely broken apart.

Yes, I agree. Still, for users migrating from LEEx to HEEx it would be great to mention this in the changelog, as I wasn't sure if this should work or not and I guess others could come across this too.
