### ISSUE TITLE
Class `phx-change-loading` not removed after live file upload

### ISSUE THREAD

**Issue by alexblackie** [phoenixframework/phoenix_live_view#1609]
### Environment

* Elixir version (elixir -v): 1.12.1 (Erlang/OTP 24)
* Phoenix version (mix deps): 1.15.12
* Phoenix LiveView version (mix deps): 0.15.7 (also tried 0.16.3)
* Operating system: macOS 11.5.2
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox 91.0.2, Safari 14.1.2
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

When using `auto_upload: true` for an `allow_upload`, the form and `live_file_input` element retain the `phx-change-loading` class after the upload has completed. Additionally, even after a `phx-submit`, the `live_file_input` seems to retain its `phx-change-loading` class, while the form has it removed correctly.

In my app currently I use `phx-change-loading` to show a loading state, which causes issues with this behaviour as uploading a file will cause the UI to appear to load forever.

I [created a reproduction app](https://github.com/alexblackie/phoenix-live-view-change-loading) (just following the Phoenix Guides), and you can see the changes [in commit `d052aba`](https://github.com/alexblackie/phoenix-live-view-change-loading/commit/d052abad50c7649b8adc7dbd169cb69c2cac8a00).

### Expected behavior

After all entries have uploaded, the form and input element lose the `phx-change-loading` class.

**Comment by whitepaperclip** [comment]
Can confirm, also having this issue with `phx-click-loading` and other classes not being removed.
