### ISSUE TITLE
`phx-click-loading` class not removed when sending an event to another rendered live view

### ISSUE THREAD

**Issue by whitepaperclip** [phoenixframework/phoenix_live_view#1619]
### Environment

* Elixir version (elixir -v): 1.12.0
* Phoenix version (mix deps): 1.5.12
* Phoenix LiveView version (mix deps): 0.16.3
* Operating system: macOS 11.4
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes (lol)

### Actual behavior

Given some button:

`<button id="addToCartButton" type="button" phx-click="add-to-cart" phx-target="#CartLiveView" class="btn">Add to Cart</button>`

After clicking this, the `phx-click-loading` class and `data-phx-ref="0"` are applied. The message is sent to `#CartLiveView`. However, the ref is never cleared and `phx-click-loading` never gets removed.

I made an attempt to trace this through `phoenix_live_view/view.js` and found:

```javascript
// view.js:643

undoRefs(ref){
  DOM.all(this.el, `[${PHX_REF}="${ref}"]`, el => {

  // ...
}
```

In the above, `this.el` is `#CartLiveView`, _not_ the Phoenix-generated ID of the LiveView container that contains `#addToCartButton`. So: ```DOM.all(this.el, `[${PHX_REF}="${ref}"]`) === []```, and the ref never gets removed.

### Expected behavior

The refs should be undone and loading classes removed from both the caller and the target.

**Comment by josevalim** [comment]
Oh… this is tricky. I don’t think we can support sending events across LiveViews like that. I think we should raise altogether.

**Comment by whitepaperclip** [comment]
@josevalim I would send a PR but I don't know where and how the error should be raised. Would this be a client-side error?

**Comment by josevalim** [comment]
It is on the client, yeah. Once you find the target, you need to find somehow what LiveView it belongs to and if it is the same as the current element. Then I think we usually log? In any case a log would be a good start.

**Comment by simoncocking** [comment]
> Oh… this is tricky. I don’t think we can support sending events across LiveViews like that. I think we should raise altogether.

@josevalim We're also in this situation (see also #956): we have a notifications pane live view which is rendered with `live_render/3`, which receives events from outside the view. Clicks on buttons sending these events never have their `phx-click-loading` class removed.

My workaround right now is to leave the css for `.phx-click-loading` empty but that's obviously not ideal.

**Comment by whitepaperclip** [comment]
@simoncocking For what it's worth, we ended up handling our use case by broadcasting a message on a pubsub channel. This allowed for communication between live views.

**Comment by chrismccord** [comment]
With JS commands, you can now target another element that receives the loading class via the `:loading` option. Thanks!
