### ISSUE TITLE
Use in SPA

### ISSUE THREAD

**Issue by benkeil** [phoenixframework/phoenix_live_view#1622]
Could we use `LiveSocket` in a SPA and configure the URL of the LV server? It should not matter who the initial page content comes from, or?

**Comment by josevalim** [comment]
Hi @benkeil, LiveView should be the one doing the initial rendering.

Btw, for more details and questions in general, please use the [ElixirForum](http://www.elixirforum.com) or StackOverflow for questions/help/feedback, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
