### ISSUE TITLE
Rename lifecycle default mount callback to on_mount

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix_live_view#1629]
As discussed with @crumm, we should rename the default `mount` callback to `on_mount` for lifecycle hooks declared with `on_mount MyModule`. Today the we call `mount` if no MF is provided, but this leads to overloading what kind of mount you're looking at in any given module. For example, imagine you `use Phoenix.Component` to define a group of function components. You may also define this module as a lifecycle hook. Seeing `use Phoenix.Component` then `def mount/3` is eerily close to `use Phoenix.LiveComponent` and can be confusing what it is this module is responsible for. I propose for 0.17 we rename the default function to `on_mount` to better signal the purpose. Thoughts // @josevalim @jeregrine

**Comment by josevalim** [comment]
Sounds good to me!

**Comment by dvic** [comment]
A related question: is there an explicit behavior for the callback? (so one can refer to it using `@impl Phoenix.Hook` for example) If not, would it be a good idea to add it?

**Comment by josevalim** [comment]
@dvic it is hard to add a callback when the function name itself can be customizable :(

**Comment by dvic** [comment]
I see, didn't think of that. It's become less important now we have this rename so I'm fine with keeping things as they are, but one thing we could do is say in the docs that if you use `on_mount MyModule`, then `MyModule` needs to adhere to the `Phoenix.Hook` behavior.

Another unrelated question to this: is it possible/normal to typespec macros to indicate how can be called? (in this case the `on_mount` macro)? Or is this considered bad practice?
