### ISSUE TITLE
on_mount brackets in formatter

### ISSUE THREAD

**Issue by maennchen** [phoenixframework/phoenix_live_view#1637]
### Environment

* Elixir version (elixir -v): `Elixir 1.12.1 (compiled with Erlang/OTP 22)`
* Phoenix version (mix deps): `phoenix 1.5.12`
* Phoenix LiveView version (mix deps): `phoenix_live_view 0.16.3`
* Operating system: `Ubuntu 20.04.2 LTS`
* Browsers you attempted to reproduce this bug on (the more the merrier): None
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

When adding calls to `on_mount/1`, adding `:phoenix_live_view` to the `import_deps` of `.formatter.exs` and running `mix format` there are brackets added.

### Expected behavior

No brackets are added (formatted as in the docs).

### PR

If you agree, I'll send a PR that adds `on_mount` to the `locals_without_parens` config.

**Comment by josevalim** [comment]
@maennchen we keep this information in the Phoenix project and it is available from 1.6.0-rc onwards. So you can either update Phoenix or add it to your formatter temporarily.

**Comment by maennchen** [comment]
@josevalim Ok, I will do that.

Is there a reason that this is not kept in the place where the function/macro is actually defined?

**Comment by josevalim** [comment]
@maennchen it was done to reduce the number of installation steps (when it was a separate project) and because the Phoenix generators understands those constructs anyway, so it felt convenient to all be there.
