### ISSUE TITLE
mount is called once in version 0.16

### ISSUE THREAD

**Issue by Nimdis** [phoenixframework/phoenix_live_view#1640]
### Environment

* Elixir version (elixir -v): Elixir 1.12.3 (compiled with Erlang/OTP 22)
* Phoenix version (mix deps): 1.5.13
* Phoenix LiveView version (mix deps): 0.16.4
* Operating system: Ubuntu 21.04
* Browsers you attempted to reproduce this bug on (the more the merrier): Google Chrome 
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

Inside on_mount I'm trying to log `pid` with `IO.puts(inspect(self()))` after that I'm trying to check the `pid` from iex -S phx.server with `Process.alive?(pid("<thepid>"))` and receive false

### Expected behavior

I expect to get true. It worked this way in LiveView 0.15.*
As I understand problem affects PubSub, since subscription in on_mount stopped working

Does behavior of LiveView changed somehow in latest release?

Sorry if the question is actually silly, I'm still learning Phoenix and Elixir

**Comment by josevalim** [comment]
`on_mount` is called twice. Once during the regular HTTP request for the initial render and then another time for the LiveView. You are probably getting the first PID. You can use `connected?(socket)` to know if it is the initial render or the connected websocket render.

**Comment by Nimdis** [comment]
@josevalim  Thank you, for some reason I haven't spotted it in the docs.
I did a couple of tests yesterday, and still have the same issue on version 0.16.4, but don't have on version 0.15
I've prepared a repo with an example, but had no time to upload it yet. I'll upload it this evening.
Problem is that for some reason in version 0.15 the `mount` hook is called 2 times and in version 0.16 just once. Only thing that I'm changing is version of libraries.

**Comment by Nimdis** [comment]
I created a test repo https://github.com/Nimdis/test_liveview Last commit updates deps and after it problem appears. Below two screenshots first logs everything correctly after connection (two pids + logic defined in `mount`), second incorrect (just first pid)
![Screenshot from 2021-09-24 20-35-56](https://user-images.githubusercontent.com/3230486/134717459-431c4056-a909-4a23-8fb4-c9b7c959cb2e.png
![Screenshot from 2021-09-24 20-38-59](https://user-images.githubusercontent.com/3230486/134717749-02e12295-cecc-4acd-8469-e55b83a69d3f.png)
)

**Comment by dvic** [comment]
Did you update the js dependencies when you upgraded to 0.16?

**Comment by josevalim** [comment]
I cannot reproduce this locally, so it seems @dvic may be on the right track. When you upgraded, did you remove node_modules and installed everything from scratch to make sure the latest version of LV client was picked? Do you see any errors in the browser console?

**Comment by Nimdis** [comment]
Ooh, such a rookie mistake. Yes removing of `node_modules` and reinstalling helped. Thank you for help. 
@josevalim I saw no warnings or errors in the browser console. Also WS was successfully connected.

**Comment by dvic** [comment]
> Ooh, such a rookie mistake. Yes removing of `node_modules` and reinstalling helped. Thank you for help.

Hah no worries, been there, done that 🙂
