### ISSUE TITLE
Converting LEEx to HEEx showed old, removed template in dev until "mix clean"

### ISSUE THREAD

**Issue by henrik** [phoenixframework/phoenix_live_view#1646]
* Elixir version (elixir -v): 1.12.3
* Phoenix version (mix deps): 1.6.0
* Phoenix LiveView version (mix deps): 0.16.4

I upgraded a project to newer Phoenix and LiveView per above.

Then I converted one template from LEEx to HEEx to try it out – adding a new HEEx template, removing the old LEEx template.

Everything seemed to work fine in dev when reloading that page. But then I tried changing some text in the template and it didn't take when reloading my browser. Restarting the dev server didn't help, either.

Finally I tried "mix clean" and that fixed it. I have not dug into it, but I assume the compiled LEEx template somehow shadowed the new HEEx template.

If this is generally how it will behave, I think that could make converting from one to the other a little confusing and error prone, so I thought I'd point it out.

**Comment by henrik** [comment]
If it’s relevant, this component is rendered via `<%= live_component MyWeb.MyComponent,… %>` from a LEEx template.

You can see the actual code in the reference GitHub pulled in just above.

**Comment by josevalim** [comment]
This is an Elixir bug fixed in master. We were not tracking when the external file was removed.
