### ISSUE TITLE
Using Gettext

### ISSUE THREAD

**Issue by Dohxis** [phoenixframework/phoenix_live_view#165]
I been trying to get gettext working with `live_render` without any success. Right now live_render is always using default locale, but I am not really sure if its a problem with gettext or liveview. Maybe there is an example somewhere how to set a right locale?

**Comment by chrismccord** [comment]
You need to pass the locate in your LV session then you can use it within the LV. Please send questions to the forums or slack as we reserve the issue tracker for issues, and folks there are generally around for help. If you feel you've found an issue, please use the issue template and provide the requested information, what you've tried, what was expected vs actual, etc. Thanks!
