### ISSUE TITLE
compilation error in heex template

### ISSUE THREAD

**Issue by k-cross** [phoenixframework/phoenix_live_view#1658]
### Environment

* Elixir version (elixir -v): 1.12.3
* Phoenix version (mix deps): 1.6.0
* Phoenix LiveView version (mix deps): master: 874af9e8d5474c199bf0feff71a593941530067e
* Operating system: MacOS 11.6
* Browsers you attempted to reproduce this bug on (the more the merrier): none
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

I tried compiling master after the other bug I reported was fixed (#1656) and ran into another compilation issue. I'm not sure where to begin looking since the stack trace blows up in elixir itself. This is the only dependency that updated and changed, removing the other code that caused the other compilation issue in 0.16.4 fully compiles without this issue so that's also not it. It's also in a completely different module but it also heavily uses templates so I doubt it's related to `<script>` tags again.

```
** (EXIT from #PID<0.93.0>) an exception was raised:
    ** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not an integer

        :erlang.integer_to_binary({:line, [line: 13], :elixir_quote})
        (elixir 1.12.3) lib/module/parallel_checker.ex:199: Module.ParallelChecker.format_file_line/2
        (elixir 1.12.3) lib/module/parallel_checker.ex:186: Module.ParallelChecker.format_location/1
        (elixir 1.12.3) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
        (elixir 1.12.3) lib/module/parallel_checker.ex:180: Module.ParallelChecker.format_locations/1
        (elixir 1.12.3) lib/module/parallel_checker.ex:165: anonymous fn/1 in Module.ParallelChecker.emit_warnings/1
        (elixir 1.12.3) lib/enum.ex:3900: Enum.flat_map_list/2
        (elixir 1.12.3) lib/module/parallel_checker.ex:300: anonymous fn/5 in Module.ParallelChecker.spawn_checkers/1
```

### Expected behavior

Project compiles.

If there's anything I can be more helpful with in trying to solve this issue, please ping me. Please let me know if this is noise and you wish not to be notified of master build issues. I'll follow up with more context as I get it. Thank you for your help and time!

**Comment by josevalim** [comment]
Thank you for the report! Unfortunately we will need access to the templates that cause this, as I am worried this is an Elixir bug. :) can you try isolating this issue? Try removing  the templates, leaving one at a time, until you find the one that fails. Then I can take a look at it ASAP :)

**Comment by k-cross** [comment]
I will but it will take some time, I'll try to have something isolated by Wed (PT).

**Comment by k-cross** [comment]
Okay, this one definitely blows up. There are probably more. I wonder if it's something from a helper. I put it in a gist which you can find here.

https://gist.github.com/k-cross/94f2e225728d0ffd1c6c93dd98880c54 

I'll try playing around with it a little and see if I can provide any more context. LMK if you'd like me to try anything. Thanks again for your help!

**Comment by josevalim** [comment]
Unfortunately I cannot reproduce it yet. For the snippet above, for which line do you get the error? It is something related to warning...

**Comment by josevalim** [comment]
Nevermind, I could reproduce it! :D

**Comment by josevalim** [comment]
I got a fix for Elixir. :) Pushing a fix to master and v1.12 branches soon. Thanks for the report!

**Comment by josevalim** [comment]
I also pushed a workaround for LV master.

**Comment by k-cross** [comment]
Thanks a million! That was quick work, sorry I couldn't be more helpful.

**Comment by josevalim** [comment]
You were very helpful, the isolation case was exactly what i need, the fault to reproduce it was on my side. :)
