### ISSUE TITLE
Duplicate channel join for topic

### ISSUE THREAD

**Issue by 123mitnik** [phoenixframework/phoenix_live_view#1664]
when using live_redirect between two LVs 

```[debug] Duplicate channel join for topic "lv:phx-FqwDqxbJqIiDffsi" in Phoenix.LiveView.Socket. Closing existing channel for new join.```

i have about 5 LVs with only cross live_redirect links inside them (only pointing to each-other, nothing else) when i try to navigate between them i receive the above error

i tried it on the newly generated project and it is the same

### Environment

* Elixir version (elixir -v):
``` 
Erlang/OTP 24 [erts-12.0.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit]

Elixir 1.12.2 (compiled with Erlang/OTP 24)
```

* Phoenix version (mix deps):
```
* phoenix 1.6.0 (Hex package) (mix)
  locked at 1.6.0 (phoenix) 52ffdd31
  ok
* phoenix_ecto 4.4.0 (Hex package) (mix)
  locked at 4.4.0 (phoenix_ecto) 09864e55
  ok
* phoenix_html 3.0.4 (Hex package) (mix)
  locked at 3.0.4 (phoenix_html) ce17fd3c
  ok
* phoenix_live_dashboard 0.5.0 (Hex package) (mix)
  locked at 0.5.0 (phoenix_live_dashboard) 609740be
  ok
* phoenix_live_reload 1.3.3 (Hex package) (mix)
  locked at 1.3.3 (phoenix_live_reload) 76679667
  ok
* phoenix_live_view 0.16.4 (Hex package) (mix)
  locked at 0.16.4 (phoenix_live_view) 754ba49a
  ok
* phoenix_pubsub 2.0.0 (Hex package) (mix)
  locked at 2.0.0 (phoenix_pubsub) c52d948c
  ok
* phoenix_view 1.0.0 (Hex package) (mix)
  locked at 1.0.0 (phoenix_view) 82be3e25
  ok
```

* Operating system:
```
macOS 11.6
```
* Browsers you attempted to reproduce this bug on (the more the merrier): 
```
Chrome
Version 94.0.4606.71 (Official Build) (x86_64)
```

* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:

```
Yes
```

Link created with live_redirect - pointing to the same or other LV leads to - ``` [debug] Duplicate channel join for topic "lv:phx-FqwMMwXAH_DQxT6i" in Phoenix.LiveView.Socket. Closing existing channel for new join. ```

In my case i have live_redirect links pointing to 5 LVs in a sidebar menu. When navigating between LVs .. the error appears

**Comment by josevalim** [comment]
@123mitnik can you please fill in the issues template? We need the exact versions you tried things on. :)

**Comment by 123mitnik** [comment]
@josevalim . Hello Jose, sure (sorry for not doing it initially). original text updated now

**Comment by 123mitnik** [comment]
Thank you Chris !

![image](https://user-images.githubusercontent.com/1234337/136573281-83b58362-d80b-48ca-8e4f-52f7dc834364.png)

yes, i double-checked on my end .. i was able to replicate it on Safari too

here is a simple [toy repo](https://github.com/123mitnik/testproject) i created with a clean project and two LVs

(the toy repo is with everything updated to the latest version)

**Comment by chrismccord** [comment]
Phoenix 1.6.1 was just released which fixes this :)

**Comment by 123mitnik** [comment]
@chrismccord Thank you very much Chris !!

Amazing speed :zap: and work :trophy:
:clap: :tada: :tada: :tada:
