### ISSUE TITLE
[Suggestion] Handling action permissions from `handle_event/3` using hooks

### ISSUE THREAD

**Issue by aleDsz** [phoenixframework/phoenix_live_view#1674]
Hi, I'm aleDsz from company [magnetis](https://github.com/magnetis)

This year our team decided to create some views from our software using `Phoenix LiveView`, but we discovered we don't have a good permission handling for actions inside a `Phoenix LiveView`, which was okay, for now.

But, last month we decided to refactor our old Phoenix views into LiveView. And this question came across again. How we can deal with permissions? I had an idea, using the library [`decorator`](https://github.com/arjan/decorator) and injecting permissions based on arguments given to decorator function (Probably some function called handle_access or handle_permission):

```elixir
@decorate handle_permission(:accounts, :create)
def handle_event("create-user", params, socket) do
  # do stuff...
end
```

But, after talking to some people, the best idea was making it using LiveView hooks, like `on_mount` hook. And makes sense, because u can handle the module callback to the user (developer) to decide how to deal with actions, or not. Making it without any premise, just executing a function before calling the `handle_event/3` from the user's live view.

So, if u guys thinks that's a good feature, i can contribute to the repo to add this feature to the LiveView's project.

**Comment by chrismccord** [comment]
enforcing authorization is strictly on the user-land side. You could use hooks for this, but I would avoid the decorate pattern as it is unnecessary indirection. Inline authorization is also fine as well. Thanks!
