### ISSUE TITLE
Remove phx-page-loading and phx-capture-click

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix_live_view#1676]

**Comment by shortly-portly** [comment]
Hi @josevalim. May I ask why phx-capture-click is being removed? I've used phx-capture-click with a component on a modal to prevent the modal from receiving click events (and in my case submitting a form too early). What, if any, is the alternative to this. thanks.

**Comment by josevalim** [comment]
There is phx-click-away or something similar.

**Comment by shortly-portly** [comment]
Thanks for the quick reply but I'm struggling to see how `phx-click-away` would replace `phx-capture-click` - so apologies if I'm missing something obvious. 

As an example, I have a component which mimics a select dropdown. The below code is a skeleton example:

      def select(assigns) do
        ~H"""
          <div id="item">
            <div>Hello</div>
            <div>Hello</div>
            <div>Hello</div>
          </div>
          <button phx-capture-click={JS.toggle(to: "#item")}> 
            toggle!
          </button>
        """
      end

I can include this "select" component inside a form component that comes with Liveview 0.17.5. If I replace the `phx-capture-click` with a `phx-click` then the click event bubbles up and causes the form itself to submit. How would `phx-click-away` replace the functionality provided by `phx-capture-click`.

cheers

Dave

**Comment by josevalim** [comment]
Wouldn’t phx-click be enough for this case?

**Comment by shortly-portly** [comment]
No because `phx-click` bubbles up to the form component which sees it as a submit and then submits the form. With `phx-capture-click` the click is captured and shows/hides the select as appropriate. 

For another example, standard forms are normally shown in a modal - without the `phx-capture-click` the modal also receives the click event and closes.

**Comment by josevalim** [comment]
I see. That’s something for Chris to consider then when going ahead with these deprecations! Thanks for clarifying!

**Comment by shortly-portly** [comment]
No problem. I've said it before but thanks for an awesome language and framework.

**Comment by chrismccord** [comment]
`<button>` by default in an HTML form is `type="submit"`. When you have a button in a form that you don't want to submit it, you need to specify `<button type="button"`. In this case, the capture click was a band-aid around the missing attribute :)

**Comment by shortly-portly** [comment]
Ah so my example was incorrect. I'll have another go at implementing my dropdown using the JS style of commands. Thanks for the help (and the amazing framework of course).

**Comment by shortly-portly** [comment]
HI Chris - I reimplemented my dropdown with just JS style commands and it works perfectly.

**Comment by josevalim** [comment]
I think those have been deprecated but the JavaScript code may still handle them.

**Comment by rhcarvalho** [comment]
Is this something to consider removing for the 1.0.0 release if it is still in the code base?
