### ISSUE TITLE
phx-trigger-action submits empty fields when client JavaScript is enabled

### ISSUE THREAD

**Issue by brettinternet** [phoenixframework/phoenix_live_view#1679]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 24 [erts-12.1.2] [source] [64-bit] [smp:20:20] [ds:20:20:10] [async-threads:1] [jit]
Elixir 1.12.2 (compiled with Erlang/OTP 24)
```
* Phoenix version (mix deps): `phoenix 1.6.2`
* Phoenix LiveView version (mix deps): `phoenix_live_view 0.16.4`
* Operating system: Linux
* Browsers you attempted to reproduce this bug on (the more the merrier): Chromium 94.0.4606.81, Firefox v93
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

When `phx-trigger-action` is used to submit formdata to a controller, the form fields are empty. However, when JavaScript is disabled on the client, the form submits as expected.

Here is a reproduction of the issue (at least, in my environment): https://github.com/brettinternet/phx-trigger-action-formdata

### Expected behavior

When `phx-trigger-action` has a value of `true`, forms should submit formdata with populated form field values.

---

I thought maybe this was an issue with my code, so I [posted to the forums](https://elixirforum.com/t/phx-trigger-action-submits-form-with-empty-fields-unless-javascript-is-disabled-on-client/43172). However, after I recreated the issue in a new repo, I believe this could be a bug.

With the client debug mode and the Chrome dev tools "Preserve log" option enabled, I noticed an error probably from the view channel:

```
phx-Fq9NezP9MslvnwCN error: view crashed -  undefined
```

**Comment by chrismccord** [comment]
You need to maintain the form state on the server. For example, if you didn't use `phx-trigger-submit` and only handled, say `phx-change`, you'd also see the form fields be cleared since the server is not setting or maintaining the form values. This would give you what you want:

```elixir
defmodule DemoWeb.LoginLive do
  use DemoWeb, :live_view

  def render(assigns) do
    ~H"""
    <h1>Live Login</h1>
    <.form
      let={f}
      for={:user}
      phx-submit="login"
      method="post"
      action="/login"
      phx-trigger-action={@login_valid}>
      <%= label f, :email %>
      <%= email_input f, :email, value: @email %>
      <%= error_tag f, :email %>

      <%= label f, :password %>
      <%= password_input f, :password, value: @pass %>
      <%= error_tag f, :password %>

      <%= submit "Login" %>
    </.form>
    """
  end

  def mount(_params, _session, socket) do
    {:ok, assign(socket, login_valid: false, email: nil, pass: nil)}
  end

  def handle_event("login", %{"user" => user}, socket) do
    %{"email" => email, "password" => pass} = user
    {:noreply, assign(socket, login_valid: true, email: email, pass: pass)}
  end
end
```

Thanks!

**Comment by brettinternet** [comment]
Dang, sorry Chris, I'm a bit embarrassed. Should anyone else arrive here, the docs clearly demonstrate the `changeset` passed back into assigns: https://hexdocs.pm/phoenix_live_view/form-bindings.html#submitting-the-form-action-over-http
