### ISSUE TITLE
handle_progress callback for upload needs a better error

### ISSUE THREAD

**Issue by mcrumm** [phoenixframework/phoenix_live_view#1693]
We should check against the return from handle_progress and provide a better error if the user returns something other than `{:noreply, socket}`.

https://github.com/phoenixframework/phoenix_live_view/blob/2b9952b2eeda5d333821dd75ebeb45a5b62adef4/lib/phoenix_live_view/channel.ex#L149-L150

**Comment by tmjoen** [comment]
I belive this is fixed in https://github.com/phoenixframework/phoenix_live_view/commit/a961e5b1413be2545d8a157928e45407ef5537cb now :)

**Comment by chrismccord** [comment]
confirm :)

**Comment by mcrumm** [comment]
I forgot I even made this issue– thanks Chris! :)
