### ISSUE TITLE
live_render :container option doesn't respect :class

### ISSUE THREAD

**Issue by nathanjohnson320** [phoenixframework/phoenix_live_view#170]
### Environment

* Elixir version (elixir -v): Elixir 1.8.1 (compiled with Erlang/OTP 21)
* Phoenix version (mix deps): phoenix 1.4.3
* NodeJS version (node -v): v11.12.0
* NPM version (npm -v): 6.7.0
* Operating system: macOS Mojave 10.14.4

### Actual behavior

If you call `live_render` with the `:container` argument  it does not keep any `:class` values passed in. i.e.

```
<%= live_render(@socket, DemoWeb.EnvLive, [session: %{environment: environment}, container: {:div, [class: "column is-3"]}]) %>
```

results in

```
<div class="phx-disconnected phx-error">
```

### Expected behavior

The class is rendered in addition to the live view classes.

```
<div class="phx-disconnected phx-error column is-3">...</div>
```

**Comment by jamilabreu** [comment]
I'm seeing this as well - looks like phoenix_live_view.js is overriding the class list in a few places:

- https://github.com/phoenixframework/phoenix_live_view/blob/master/assets/js/phoenix_live_view.js#L687
- https://github.com/phoenixframework/phoenix_live_view/blob/master/assets/js/phoenix_live_view.js#L701
- https://github.com/phoenixframework/phoenix_live_view/blob/master/assets/js/phoenix_live_view.js#L774

There may be others, but that's what I can see.

**Comment by djm** [comment]
I encountered this today and wrote a solution which works for us at Teller; please give the PR a review @nathanjohnson320 & @jamilabreu to see if it'll work for you. 

Thanks.
