### ISSUE TITLE
Should `disabled` form elements be included in `phx_change` and `phx_submit` payloads?

### ISSUE THREAD

**Issue by zorn** [phoenixframework/phoenix_live_view#1702]
### Environment

* Elixir version (elixir -v): Elixir 1.12.3
* Phoenix version (mix deps): 1.6.2
* Phoenix LiveView version (mix deps): 0.17.2
* Operating system: macOS 10.15.7 (19H2)
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox and Safari.
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes.

### Actual behavior

I have an HTML form in a LiveView with two text inputs, `string_one` and `string_two`. I use the `phx_change` and `phx_submit` events on this form. When the events trigger only `string_two` is included in the form payload.

### Expected behavior

Despite being `disabled` I expected to see the value of `string_one` to be included in the payload during `phx_change` and `phx_submit`. For me, the `disabled` value is more a hint to the browser rendering the form, to disallow user editing, but the values are still a part of the form. 

If the current behavior is expected, perhaps we could expand on the documentation of these two events to better describe expectations?

### Example

```elixir
defmodule DisabledChangeEventWeb.DemoLive do
  use DisabledChangeEventWeb, :live_view

  def mount(_params, _session, socket) do
    {:ok,
     assign(socket,
       changeset:
         form_changeset(%{
           "string_one" => "value_one",
           "string_two" => "value_two"
         })
     )}
  end

  def handle_event("validate", %{"profile" => profile_params}, socket) do
    IO.inspect(profile_params, label: "profile_params during validate")

    {:noreply, socket}
  end

  def handle_event("save", %{"profile" => profile_params}, socket) do
    IO.inspect(profile_params, label: "profile_params during save")

    {:noreply, socket}
  end

  def render(assigns) do
    ~H"""
    <.form let={f} for={@changeset} as="profile" phx_change="validate" phx_submit="save">

    <div>
      <%= label f, :string_one %>
      <%# Disabled form inputs are not included with the phx_change/phx_submit payloads,
      which was an unexpected behavior for me. %>
      <%= text_input f, :string_one, [disabled: true] %>
      <%= error_tag f, :string_one %>
    </div>

    <div>
      <%= label f, :string_two %>
      <%= text_input f, :string_two %>
      <%= error_tag f, :string_two %>
    </div>

    <div>
     <%= submit "Submit" %>
    </div>

    </.form>
    """
  end

  defp form_changeset(params) do
    data = %{}
    types = %{string_one: :string, string_two: :string}

    changeset =
      {data, types}
      |> Ecto.Changeset.cast(params, Map.keys(types))
  end
end

```

Posted online at: https://github.com/elixirfocus/disabled_change_event/blob/main/lib/disabled_change_event_web/live/demo_live.ex

**Comment by lkananowicz** [comment]
@chrismccord And is there any recipe for disabled checkboxes? Setting `readonly` on them via HTML is not possible as far as I understand. And setting `pointer-events: none;` CSS property doesn't do the trick either

**Comment by lkananowicz** [comment]
> @chrismccord And is there any recipe for disabled checkboxes? Setting `readonly` on them via HTML is not possible as far as I understand. And setting `pointer-events: none;` CSS property doesn't do the trick either

Never mind, setting hidden input with the same name and value as disabled checkbox input solved the problem :)
