### ISSUE TITLE
do block in comprehension produces incorrect diffs

### ISSUE THREAD

**Issue by jayjun** [phoenixframework/phoenix_live_view#1716]
### Environment

* Elixir version (elixir -v): 1.12.3
* Phoenix version (mix deps): 1.6.2
* Phoenix LiveView version (mix deps): 0.17.2
* Operating system: macOS 11.1
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, Firefox, Safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

```eex
<%= for _ <- [""] do %>
  <%= "foo" %>
  <%= "bar" %>
  <%= content_tag :span do %>
    <%= "baz" %>
  <% end %>
<% end %>
```
renders

```html
baz
bar
<span>
  baz
</span>
```
### Expected behavior

```html
foo
bar
<span>
  baz
</span>
```

Reproducible with any nested `do` block except `if` or `case` ones. Definitely server-side bug because the WebSocket frame shows the wrong diff.

Not a fancy use case, stumbled on this while creating a pretty conventional list of `live_patch` links.

```eex
<%= for product <- @products do %>
  <%= product.name %>
  <%= live_patch to: Routes.product_path(@socket, :edit, product) do %>
    <.icon name="edit" />        
  <% end %>
<% end %>
```

**Comment by josevalim** [comment]
This has been fixed in master, we will do a new release shortly.
