### ISSUE TITLE
FunctionClauseError in render/1

### ISSUE THREAD

**Issue by masterkain** [phoenixframework/phoenix_live_view#172]
### Environment

* Elixir version (elixir -v):

```
Erlang/OTP 21 [erts-10.2.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.8.1 (compiled with Erlang/OTP 21)
```

* Phoenix version (mix deps):

```
* phoenix_live_view 0.1.0 (https://github.com/phoenixframework/phoenix_live_view.git) (mix)
  locked at 26e9d25

* phoenix 1.4.3 (https://github.com/phoenixframework/phoenix.git) (mix)
  locked at 9754b38 (branch: v1.4)
```

* NodeJS version (node -v): `v11.9.0`
* NPM version (npm -v): `6.9.0`
* Operating system: `macOS 10.13.6`

### Actual behavior

in my page

```
<%= live_render(@conn, PandamexWeb.ActivityLive, session: %{widget: true}) %>
```

![Screen Shot 2019-04-08 at 23 38 40](https://user-images.githubusercontent.com/12844/55758590-7c905880-5a57-11e9-9587-6b15059a7bf7.png)

### Expected behavior

I started seeing this exception only in production mode few days ago (I update git deps daily) and now it started in development mode too.

**Comment by alexgaribay** [comment]
Does `mount/1` in your live view actually assign `:widget` to `true` on the socket? The error doesn't show `:widget` as one of the assigned values.

**Comment by chrismccord** [comment]
As Alex said, the `session` map is passed to mount/1, and you must lift out and assign necessary socket assigns for `render/1`. It sounds like you didn't:

```elixir
def mount(%{widget: widget}, socket) do
  {:ok, assign(socket, :widget, widget)}
end
```

If you continue to have issues. Please let us know. Thanks!
