### ISSUE TITLE
phx-click-away event runs even when element is hidden on page

### ISSUE THREAD

**Issue by wking-io** [phoenixframework/phoenix_live_view#1722]
### Environment

* Elixir version (elixir -v): 1.12.0
* Phoenix version (mix deps): 1.6.2
* Phoenix LiveView version (mix deps): 0.17.4
* Operating system: OS
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

No error, but I have a `JS.dispatch` that runs on `phx-click-away`. My assumption was that click away only runs when the element is visible, but anytime a click happens the dispatch is run.

### Expected behavior

`phx-click-away` on hidden elements like menu buttons and modals only happen when element is showing.

**Comment by chrismccord** [comment]
fixed on master last night! :) Thanks!

**Comment by wking-io** [comment]
Keep up the great work! I am LOVING JS Commands.
