### ISSUE TITLE
push_redirect across live sessions does not bring live flash

### ISSUE THREAD

**Issue by en30** [phoenixframework/phoenix_live_view#1732]
### Environment

* Elixir version (elixir -v): `Elixir 1.12.2 (compiled with Erlang/OTP 24)`
* Phoenix version (mix deps): `1.6.2`
* Phoenix LiveView version (mix deps): https://github.com/phoenixframework/phoenix_live_view/tree/1787aba2a42b7eb377247a3072650d44c704fab1
* Operating system: macOS 11.6
* Browsers you attempted to reproduce this bug on (the more the merrier): Google Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior
Here is a demo application.
https://github.com/en30/live_flash_across_live_session

Given an example route like
```elixir
live_session :a do
  scope "/", FooWeb do
    pipe_through :browser

    live "/a", ALive
  end
end

live_session :b do
  scope "/", FooWeb do
    pipe_through :browser

    live "/b", BLive
  end
end
```

if `ALive` `push_redirect`s a socket to `/b`
```elixir
socket
|> put_flash(:info, "test")
|> push_redirect(to: "/b")
```

`BLive` cannot receive the flash message.
If `ALive` uses regular `redirect`, then `Blive` can get the flash message.

### Expected behavior
`BLive` receive the flash message even when `ALive` `live_redirect`s a socket.

**Comment by mcrumm** [comment]
This is expected. You must not `live_redirect`/`push_redirect` across live_session groups. If the server detects a live redirect across sessions it will force a hard redirect in the background. As you noted, flash _will_ make it across the live_session boundary when using `redirect`, so that is the correct solution. :)

**Comment by en30** [comment]
Thanks for the reply. I understood that it is a specification.

I was a little surprised that LiveViews had to know the structure of the route. For example, if I move a live route `/a` across live sessions, I have to review all the code that redirects from `/a` or to `/a`, right? Though an automated test that tests a content of a flash message helped me in my case, I may misunderstand how to use `live_session`.
