### ISSUE TITLE
Compilation error when we are using if macro to create 2 different lines

### ISSUE THREAD

**Issue by shahryarjb** [phoenixframework/phoenix_live_view#1738]
### Environment

* Elixir version (elixir -v): 1.12
* Phoenix version (mix deps): 1.6.2
* Phoenix LiveView version (mix deps): master and 0.17.5
* Operating system: mac & docker Linux alpine
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: no

when I want to use an `if` and create 2 `span` like this, I have a compiler error: 

```elixir
<span>
  <%= if 1 == 1 do %>
    <span class="text-left float-left">
  <% else %>
    <span class="text-left float-left" phx-click="like_post" phx-value-post-id="some_id">
  <% end %>
    1
  </span>
</span>
```

### Error 

```
Compilation error in file lib/liveview_if_web/views/page_view.ex ==
** (Phoenix.LiveView.HTMLTokenizer.ParseError) lib/liveview_if_web/templates/page/index.html.heex:9:1: missing opening tag for </span>
```

it should be noted without `if` it works:

```elixir
<div id="main">
  <span>
    <span class="text-left float-left" phx-click="like_post" phx-value-post-id="some_id">
      1
    </span>
  </span>
</div>
```

**Comment by josevalim** [comment]
Yes, this is correct. You cannot start defining a tag inside a conditional and then finish it outside.

**Comment by shahryarjb** [comment]
Thank you, @josevalim 
I think with this logic we have many lines to be repeated if we do not use Phoenix LiveView component.
