### ISSUE TITLE
Would love to help work on improving JS Commands

### ISSUE THREAD

**Issue by wking-io** [phoenixframework/phoenix_live_view#1739]
I have found two things I would love to be able to add to JS Commands and would be willing to do the work if allowed/given direction on if that sounds good to the Phoenix team.

### Attribute helpers

A big part of accessibility in components I have been using JS Commands on is updating aria attributes and other a11y related attributes on change. Would love to help add the following Commands:

- `add_attribute`
- `remove_attribute`

### Passing events

I ran into this one today. I had a set of JS Commands to run on the `phx-keyup` and had to write a custom event listener instead because the key details attached to the event were unavailable (from what I could tell). I imagine this may be a larger discussion, but could see that being added to the %JS{} struct under a key for `event` or `data` that could be passed or accessed when composing JS Commands or being dispatched to a custom listener.

**Comment by mcrumm** [comment]
Hi @wking-io! You can modify key event metadata through the LiveSocket constructor: https://hexdocs.pm/phoenix_live_view/bindings.html#key-events

**Comment by wking-io** [comment]
Just tested that with a `JS.dispatch` call triggered in phx-keyup and it didn't pass the attributes into the dispatch event. Maybe I am missing something. Here is a minimal example of what I am doing.

```
    <button phx-keyup={navigate()}></button>
```

```
   def navigate() do
     JS.dispatch("tab:navigate", [])
   end
```

```
  ...
  keyup: (e, el) => ({
    keyCode: e.keyCode
  })
  ...

  window.addEventListener("tab:navigate", (e) => {
    console.log(event)
  })
```

Logs event without the keyCode.

**Comment by VictorGaiva** [comment]
Liveview doesn't pass the whole event to handlers, as you can see [here](https://github.com/phoenixframework/phoenix_live_view/blob/b6bdfc9faa3eae28dbcf1ba9e1f6978819a8ac20/assets/js/phoenix_live_view/view_hook.js#L43). Might this be the root cause?

A possible fix would be to pass the whole event as a second argument for the callback, which would be backwards compatible, like this:
```javascript
let callbackRef = (customEvent, bypass) => bypass ? event : callback(customEvent.detail, customEvent)
```

**Comment by en30** [comment]
Here is one of the use cases for attribute helpers.
[Collapsible Dropdown Listbox Example | WAI-ARIA Authoring Practices 1.1](https://www.w3.org/TR/2019/NOTE-wai-aria-practices-1.1-20190814/examples/listbox/listbox-collapsible.html)
An accessible dropdown list needs to manage
- `tabindex` for focus management
- `aria-expanded` for screen readers

It would be helpful if there were attribute helpers.
I understand Phoenix team is super busy, but I would be glad if I could hear your position or situation on attribute helpers.
