### ISSUE TITLE
Should `LiveViewTest.live/2` macro return flash unsigned?

### ISSUE THREAD

**Issue by aymanosman** [phoenixframework/phoenix_live_view#1741]
I was confused about the return value of the `live/2` testing macro in case of a redirect. It returned the flash as a signed string. After digging into the code, I figured I could use `Phoenix.LiveView.Utils.verify_flash/2` in order to reconstruct the flash map for testing.

Here is an example:

``` elixir
  test "redirected to home if not logged in", %{conn: conn} do
    home = Routes.page_path(conn, :index)

    assert {:error, {:redirect, %{to: ^home, flash: flash}}} =
             live(conn, Routes.thing_index_path(conn, :index))

    real_flash = Phoenix.LiveView.Utils.verify_flash(@endpoint, flash)

    assert real_flash["error"] == "You must be logged in to view that page"
  end
```

Should it not return the flash as a map just like `assert_redirect/2` does?

**Comment by josevalim** [comment]
Yes, we must verify it. A PR is welcome!

**Comment by aymanosman** [comment]
Isn't the "solution" simply not signing the flash map?

What is the purpose of signing it here https://github.com/phoenixframework/phoenix_live_view/blob/master/lib/phoenix_live_view/test/live_view_test.ex#L362?

**Comment by aymanosman** [comment]
As in https://github.com/aymanosman/phoenix_live_view/commit/5481101296ec1cf268c1051dd07703f478e9eda5

**Comment by josevalim** [comment]
@aymanosman the issue is that we have a `follow_redirect` that handles the `:error` tuple. But we can simply moving the signing of the flash to `follow_redirect` instead. PR is welcome!

**Comment by aymanosman** [comment]
Understood. [PR](https://github.com/phoenixframework/phoenix_live_view/pull/1748)
