### ISSUE TITLE
Optimization for new heex templates combined with JS and for loops

### ISSUE THREAD

**Issue by seb3s** [phoenixframework/phoenix_live_view#1744]
Hi,
this is a suggestion for a wanted optimization to reduce the payload associated with the new JS commands when used inside a for loop.
Right now the payload increase a lot when I use the new JS commands (which I find a nice solution for a lot of things I was doing differently before so big thanks for that !)

Here is a sample template :
```
<tbody id="hover_event">
  <%= for event <- @events do %>
    <tr phx-click={JS.push("view_details", value: %{delegate: @module})
      |> JS.remove_class("is-selected", to: "#hover_event > tr")
      |> JS.add_class("is-selected") }
      phx-value-id={event.id}>
    <td><%= event.event_dt %></td>
    <td><%= event.event_name %></td>
    <td><%= event.event_data %></td>
  </tr>
  <% end %>
</tbody>
```
I've voluntarily put outside the phx-click attribute the only dynamic param to this click event (which is an id passed as phx-value-id)

Right now, the fully static phx-click rendered attribute is passed for each event of the for loop.
I can force the diff engine to optimize it as a static portion by writing this template:

```
<tbody id="hover_event">
  <%= for event <- @events do %>
    <tr phx-click="[[&quot;push&quot;,{&quot;event&quot;:&quot;view_details&quot;,&quot;value&quot;:{&quot;delegate&quot;:&quot;Admin.Sysevent&quot;}}],[&quot;remove_class&quot;,{&quot;names&quot;:[&quot;is-selected&quot;],&quot;time&quot;:200,&quot;to&quot;:&quot;#hover_event > tr&quot;,&quot;transition&quot;:[[],[],[]]}],[&quot;add_class&quot;,{&quot;names&quot;:[&quot;is-selected&quot;],&quot;time&quot;:200,&quot;to&quot;:null,&quot;transition&quot;:[[],[],[]]}]]" phx-value-id={event.id}>

    <td><%= event.event_dt %></td>
    <td><%= event.event_name %></td>
    <td><%= event.event_data %></td>
  </tr>
  <% end %>
</tbody>
```

You guess that I would like liveview to do this for me ;-)
Thanks a lot for your attention,

Sébastien.

**Comment by chrismccord** [comment]
This is not something we will optimize since the datastructure itself is dynamic, at least not without new features so not any any near future. Note the serialized format is not something I would rely on :). Thanks!

**Comment by seb3s** [comment]
Hi Chris,
I quite knew what the answer would be. I decided it to post it to document my investigations so that maybe it could be done in the future.
In my case, for a few hundred lines, the payload is divided by 6, so even if the serialized format is a kind of quicksand, I will maybe use it for the places where I've got a lot of lines....
Thanks for your hard work,

Sébastien.

**Comment by seb3s** [comment]
For those who want to take the same risky route as me, here is the final code I use:
```
<tr phx-click='[["push",{"event":"view_details","value":{"delegate":"Admin.Sysevent"}}],
    ["remove_class",{"names":["is-selected"],"to":"#hover_event > tr"}],
    ["add_class",{"names":["is-selected"]}]]'
    phx-value-id={event.id}>
```
which reads quite the same as the originale one.
BUT please note that this is unsupported code ;-)
