### ISSUE TITLE
Allow to pass custom params from live_render to mount.

### ISSUE THREAD

**Issue by jung-hunsoo** [phoenixframework/phoenix_live_view#175]
### Problem
- One should load the custom values in `:session` from `live_render/3` to `mount/2`.
- This is not efficient; values in the `:session` key are encoded and loaded to the HTML template.

### Solution
- Provide custom key-value to pass from `live_render` to `mount`, which isn't encoded.

### Explained

I'm trying to migrate the existing forms to LiveView enabled. There are places calling routes helpers like `Routes.tips_brand_path(@conn, :create)`.

As the Router [doc](https://hexdocs.pm/phoenix/Phoenix.Router.html#module-helpers) says `:host` and `:scheme` are used to make a path, so I tried to pass them to use the Router helper.

But there's no other way but using `:session` to pass the payload `:host` and `:scheme` as below, which is not a good idea at all.

Current code is like this:
```elixir
def new(conn, params) do
  live_render(conn, NohoguWeb.Tips.BrandLive.Form, session: %{conn: Map.take(conn, [:scheme, :host])})
end
...
def mount(session, socket) do
  uri = struct(URI, Map.take(session, [:scheme, :host]))
  {:ok, assign(socket, %{ uri: uri })}
end
```

Changes expected:
```elixir
def new(conn, params) do
  live_render(conn, NohoguWeb.Tips.BrandLive.Form, session: %{}, uri: Map.take(conn, [:scheme, :host]))
end
...
def mount(session, socket, %{uri: uri}) do
  {:ok, assign(socket, %{ uri: uri })}
end
```

**Comment by alexgaribay** [comment]
You can use your application’s Endpoint to generate paths and urls with using a conn.

```
Routes.tips_brand_path(NogohuWeb.Endpoint, :create)
```

**Comment by jung-hunsoo** [comment]
@alexgaribay Thanks, It works. But I think there're more cases that leverages custom parameters.

**Comment by skovmand** [comment]
I think it would be nice to have a way of passing data to a LiveView without sending it to the client as the encoded session. 

I have a use case where I pass data fetched in a controller to a LiveView. Currently I can only do it through `session`, although I'm only using it in the `LiveView` `render` function. So it doesn't need to be sent to the browser as the encoded session. 

I _could_ do the fetching of the data in the LiveView itself, but I think it's cleaner to do it in the controller along with fetching of other needed data. Fetching the data in the LiveView would also mean that the server would have to fetch the data twice: Once when `mount` is called during the server side render, once when the client connects to the live view.

**Comment by josevalim** [comment]
The big problem with allowing unencoded data is that an attacker can modify it to do whatever they want. Possibly even access information from another user. I understand the appeal but it is very easy to get it wrong and it has large implications.

Also, with LiveView, the most natural is to actually load the data in the LiveView, and not in the controller. For example, if you load in the controller and then the user closes the computer and opens it up 1 hour later, you want to reconnect and get the latest data. If you just load it in the controller and keep it there forever, encoded or not, then the user never gets the latest.

Therefore, I think it is best to treat the live view requests as two separate requests. In a regular application, how do you commonly transfer data between requests? Using parameters in the URL, which are public, or using the session, which is private. We already support the session approach and we plan to support parameters as described in #174.

Finally, if the goal is to support better URL generation, I think this is a separate discussion, as it should be done natively as part of LiveView and not require you to build URIs and pass them around. Also note that you can pass the `@socket` to your router helpers. :)
