### ISSUE TITLE
alpinejs @click listener called twice after live redirect

### ISSUE THREAD

**Issue by ftes** [phoenixframework/phoenix_live_view#1751]
### Environment

* Elixir version (elixir -v): 1.13.0-rc.0
* Phoenix version (mix deps): 1.6.2
* Phoenix LiveView version (mix deps): 0.17.5
* alpinejs version (node deps): 3.5.1
* Operating system: macOS
* Browsers you attempted to reproduce this bug on (the more the merrier): chrome, firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes

### Actual behavior

https://user-images.githubusercontent.com/2614732/141469706-3dbcee87-2221-412f-be74-dcf32bcd19f6.mov

- After a live redirect, a single alpinejs event listener is called twice
- Does not occur after a full page load (e.g. navigation via regular link)
- `phx-update="ignore"` is specified on container
- `dom.onBeforeElUpdated` is configured for the live socket

Code excerpt:
```html
<div
  id="alpine-live"
  phx-update="ignore"
  x-data="{
    addEvent(text) { ... }
  }"
  x-init="addEvent('x-init')"
>
  <button @click="addEvent('@click')">Click me!</button>
  <h2>Events:</h2>
  <ul x-ref="clicks"></ul>
</div>
```

Full example: https://github.com/ftes/phoenix_alpine_duplicate

### Expected behavior

- The @click listener is only executed once after a live redirect

**Comment by ftes** [comment]
I have observed other effects, presumably also caused by this issue:
- `<template x-for` renders elements several times, if liveview assign is bound to alpinejs `x-data`
- `@dragend` listener called twice

**Comment by ftes** [comment]
Docs for `phx-update` state that
>  only the element contents are ignored, its attributes can still be updated.

Unfortunately, moving `phx-update` one level up does not solve the issue.

```html
<div
  id="alpine-live"
  phx-update="ignore"
>
  <div
    x-data="{ ...
```

This change
- prevents `x-init` from being called twice on full page load
- does not prevent `x-init` from being called twice after live redirect
- does not prevent `@click` handler from being called twice after a live redirect

**Comment by josevalim** [comment]
I can't help here but I want to thank you for running Elixir's RC! :heart:

**Comment by ftes** [comment]
Most likely related: https://github.com/alpinejs/alpine/discussions/1998

**Comment by ftes** [comment]
Possible workaorund.
Need to investigate further.

```
x-init="$root.setAttribute('x-ignore', 'true')"
```

**Comment by reliablendn** [comment]
This workaround does seem to work but I think this will cause different issues if the container needs to be updated by LV (as in phx-update is not ignore on cointainer). In this case LV will update the elements but alpine will ignore it. I have not tried it though.

**Comment by alaadahmed** [comment]
This doesn't happen with me,
make sure your alpine configured like so in your `app.js` file
```javascript

let liveSocket = new LiveSocket('/live', Socket, {
  params: { _csrf_token: csrfToken },
  dom: {
    onBeforeElUpdated(from, to) {
      if (from._x_dataStack) { // <<<<<<<<<<<<  use it like this _x_dataStack
        Alpine.clone(from, to); // <<<<<<<<<<<< remove __x after from
      }
    },
  },
});
```

**Comment by ftes** [comment]
@alaadahmed The example I posted in the issue description is already using the LiveSocket javascript configuration you suggested:
https://gitlab.wescale.io/wpr/wpr-form-generator/-/merge_requests/241/diffs

So that does not help unfortunately.

**Comment by dvic** [comment]
I think the problem here is more profound, I also encountered issues related to Alpine.js and navigation: https://github.com/alpinejs/alpine/discussions/1826

After a long investigation at https://github.com/livewire/livewire/discussions/3392#discussioncomment-1298316 it seems that there are problems with the new mutation observer and a whole page replacement in liveview (in the similar library livewire they don't have page navigation like in liveview).

**Comment by chrismccord** [comment]
This isn't anything to be solved on our side, but I encourage the folks to follow the issues that @dvic linked. Thanks!
