### ISSUE TITLE
Should the LiveView salt be considered sensitive?

### ISSUE THREAD

**Issue by thbar** [phoenixframework/phoenix_live_view#176]
(apologies in advance if the issue tracker is not the right place for questions - if that's the case let me know what is the right place for this!)

Given the current implementation, is it recommended to move the salt out of the code & keep it safe, or is it not that sensitive?

I'm wondering because the Phoenix salt itself, if I understand well, is not necessarily considered sensitive (based on https://github.com/phoenixframework/phoenix/issues/2146).

Also (although I'll use different values - this is out of curiosity), I wonder if using the same value for both LV & Phoenix salt is posing any trouble?

Happy to issue a doc PR based on the outcome of that.

Thanks!

**Comment by josevalim** [comment]
You can use the same salt, it is not an issue, just don't to tell anyone you are using the same salt. ;) Since the whole purpose of the salt is add some randomness. And yeah, it is not sensitive.
