### ISSUE TITLE
live_redirect & live_patch don't work inside ~H in some cases

### ISSUE THREAD

**Issue by alaadahmed** [phoenixframework/phoenix_live_view#1760]
### Environment

* Elixir version (elixir -v): __`1.13.0-rc.1`__
* Phoenix version (mix deps): __`1.6.2`__
* Phoenix LiveView version (mix deps): __`0.17.5`__
* Operating system: __`macOS 11.6.1`__
* Browsers you attempted to reproduce this bug on (the more the merrier): __`Firefox`, `Chrome` and `Safari`__
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: __`Yes`__

### Actual behavior
using `live_redirect` or `live_patch` inside `~H` doesn't work in some cases, I used full namespace module, or aliases and didn't work

```elixir
def render(assigns) do
    ~H"""
    <section class="relative w-full px-8 text-gray-700 bg-white body-font">
      <div class="container flex flex-col flex-wrap items-center justify-between py-5 mx-auto md:flex-row max-w-7xl">
        <%= live_redirect(to: Routes.live_path(@socket, Home)) do %>
          <img class="h-24" src={Routes.static_path(@socket, "/images/logo_en.svg")} alt="Ahram German School">
        <% end %>
     </div>
   </section>
```
also here in some function component I made to put in header nav, a two button to switch locale, but also doesn't work.

```elixir
def locale(assigns) do
    ~H"""
    <%= live_redirect @title, to: Routes.live_path(@socket, Home, locale: @locale), class: "px-1 rounded bg-slate-200 border-slate-300 border" %>
    """
  end
```
I mean by doesn't work, it doesn't even click, it doesn't change cursor to pointer, but just normal arrow cursor and non clickable.
But in html rendered code when I inspected it, I see it is normal link

for the first code snippet, the html is:
```html
<a data-phx-link="redirect" data-phx-link-state="push" href="/">
      <img class="h-24" src="/images/logo_en.svg" alt="Ahram German School">
</a>
```
for the second code snippet:
```html
<div class="inline-flex space-x-2 text-sm font-bold text-slate-800">
        <a class="px-1 rounded bg-slate-200 border-slate-300 border" data-phx-link="redirect" data-phx-link-state="push" href="/?locale=en">En</a>
        <a class="px-1 rounded bg-slate-200 border-slate-300 border" data-phx-link="redirect" data-phx-link-state="push" href="/?locale=ar">Ar</a>
</div>
```
### Expected behavior
I expected to have normal clickable links that redirect me to what is specified to `Routes.live_path/2`

https://user-images.githubusercontent.com/14099508/142166138-37cea1f7-a053-42e9-9db1-db7d5e20267c.mov

**Comment by josevalim** [comment]
Can you please provide a small application that reproduces the error? Thank you.

**Comment by alaadahmed** [comment]
@josevalim https://github.com/alaadahmed/ahram_school_platform

**Comment by alaadahmed** [comment]
sorry, just pushed it now

**Comment by josevalim** [comment]
And can you please include the steps to reproduce it? Is it `mix phx.server` and then access the home page?

**Comment by alaadahmed** [comment]
Yes go to home page, and I updated repo to include for you image folder and remove some deps that will bother you like cloudex and its config

**Comment by robokuma** [comment]
The HTML nav element is overlapping the anchor tags

**Comment by alaadahmed** [comment]
@robokuma Actually not at all, the anchor tag that wrap the logo is outside the nav tag, and the 2 language buttons also outside the nav tag .. nav tag only wrap the navigation items which are 4 elements as shown in screen recording.

**Comment by robokuma** [comment]
@alaadahmed You have "md:absolute" tailwind class on the nav element, remove it.

**Comment by alaadahmed** [comment]
Ops! This is it?!! It works, So nav tag was overlapping as you said!!

**Comment by alaadahmed** [comment]
Thank you @robokuma, and I really feel bad because of @josevalim time maybe investigating this from `live_view` perspective.
