### ISSUE TITLE
Provide link function component

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix_live_view#1769]
<.link navigate={...}> => push_navigate(socket, to: ...)
    <.link patch={...}> => push_patch(socket, to: ...)
    <.link href={...}>  => redirect(socket, to: ...)

**Comment by lessthanseventy** [comment]
```
    <%= live_patch to: Routes.messages_path(MyAppWeb.Endpoint, :show_conversation, @conversation.id) do %>
        <div class="contact__avatars">
          <%= for profile <- @participants do %>
            <.live_component module={DisplayAvatar} id={"contact-avatar-#{@conversation.id}-#{profile.id}"} />
          <% end %>
        </div>
    <% end %>
```

A call to live_component inside of live_patch errors with:

```
A component must always be returned directly as part of a LiveView template.

For example, this is not allowed:

    <%= content_tag :div do %>
      <.live_component module={SomeComponent} id="myid" />
    <% end %>

That's because the component is inside `content_tag`. However, this works:

    <div>
      <.live_component module={SomeComponent} id="myid" />
    </div>

Components are also allowed inside Elixir's special forms, such as
`if`, `for`, `case`, and friends.

    <%= for item <- items do %>
      <.live_component module={SomeComponent} id={item} />
    <% end %>

However, using other module functions such as `Enum`, will not work:

    <%= Enum.map(items, fn item -> %>
      <.live_component module={SomeComponent} id={item} />
    <% end %>
```

This TODO appears relavant:
https://github.com/phoenixframework/phoenix_live_view/blob/24a5917dd72feab33b29d078e5da9ff1ac91a612/lib/phoenix_live_view/helpers.ex#L6

**Comment by alopezz** [comment]
@chrismccord I realize that you're assigned to this issue, but as far as I know there's nothing done yet, so I went ahead and started to implement this (the way I understand it) in #1880. Hopefully you can help me clarify the questions I posed there, and let me know if it's OK for me to take this up.

**Comment by sodapopcan** [comment]
What is `push_navigate/2`?  I looked through the docs and code and can't find it!
