### ISSUE TITLE
Unable to differentiate between url params and query params

### ISSUE THREAD

**Issue by deepankar-j** [phoenixframework/phoenix_live_view#1772]
LiveView: v0.17.5

**Problem:**
Currently, there's no way for a LiveView to differentiate between the url params (i.e. those appearing in the router) and query params.

**Use Case:**
I'd like to have a LiveComponent within my LiveView, which consumes uri + params that the LiveView's handel_params/3 receives.  As appropriate, the LiveComponent either adds or removes its own query params and uses push_patch/live_patch to apply the changes.   The parent LiveView shouldn't have knowledge about the specific query params that the child adds.  It should simply pass along all of the query params to the child LiveComponent.

Unfortunately, if the LiveView route includes a url parameter, for example `/orders/:id` and page loaded is something like, `https://localhost/orders/123?tab=1`, the `handle_params/3` callback merges the query params and the url params.   When I pass the query params to the child LiveComponent and it eventually composes a URL from the params, it will be something like `https://localhost/orders/123?tab=2&id=123` because the `id` was part of the `params` map passed to the component.

**Why not just drop the known URL param from the map before sending it to the child?**
Indeed!  That's the workaround we're applying now, but it would be nicer to have a more generic solution.

**Opportunity for improvement with server-side hooks**
With the introduction of server-side hooks, we'd like to put in place a hook that automatically puts the URI and query_params in the assigns of the socket.   Right now, we have to configure this hook for each LiveView we use it in.  For example: 

```     
# LiveView's mount function...
def mount(_params, _session, socket) do
      socket
      |> AssignUrlContextHook.attach(url_params: ["id"])
      |> then(& {:ok, &1})
end

# AssignUrlContextHook...
def attach(%Socket{} = socket, opts \\ []) when is_list(opts) do
  url_params = Keyword.get(opts, :url_params, [])

  socket
  |> attach_hook(:assign_url_context, :handle_params, fn
    %{} = params, uri, socket when is_binary(uri) ->
      uri
      |> UrlContext.from_uri(url_params, params)
      |> then(&assign(socket, :url_context, &1))
      |> then(&{:cont, &1})
  end)
  
# UrlContext...
def from_uri(uri, url_params, %{} = params) when is_binary(uri) and is_list(url_params) do
    parsed_uri = uri |> URI.parse()
    query_params = params |> Map.drop(url_params)

    %__MODULE__{
      uri: parsed_uri,
      query_params: query_params
    }
end
```

If we had some way of knowing what the URL param name is for a route, we could put this hook within the `router.ex` file and not have to configure it in every LiveView.

**Comment by chrismccord** [comment]
We don't plan on stripping these, but your solution works well. Note that controllers behave this same way. Note that your component or LV could also drop known path params. Thanks!
