### ISSUE TITLE
Phoenix.LiveView.Utils.prune_uri/1 raises

### ISSUE THREAD

**Issue by matthijsqd** [phoenixframework/phoenix_live_view#1773]
### Environment

* Elixir version (elixir -v): 1.12.3-otp-24
* Phoenix version (mix deps): 1.6.2
* Phoenix LiveView version (mix deps): 0.16.4

### Actual behavior
I am getting the following error in production:

```
RuntimeError: client did not send full URL, missing host in 
  File "lib/phoenix_live_view/utils.ex", line 104, in Phoenix.LiveView.Utils.prune_uri/1
  File "lib/phoenix_live_view/utils.ex", line 91, in Phoenix.LiveView.Utils.configure_socket/5
  File "lib/phoenix_live_view/channel.ex", line 911, in Phoenix.LiveView.Channel.verified_mount/7
  File "lib/phoenix_live_view/channel.ex", line 58, in Phoenix.LiveView.Channel.handle_info/2
  File "gen_server.erl", line 695, in :gen_server.try_dispatch/4
  File "gen_server.erl", line 771, in :gen_server.handle_msg/6
  File "proc_lib.erl", line 226, in :proc_lib.init_p_do_apply/3
```

Which is coming from `{"file":"lib/phoenix/channel/server.ex","line":41,"function":"Elixir.Phoenix.Channel.Server.join/4"}`

And the last message is
```elixir
{
  Phoenix.Channel,
  %{
    "params" => %{
      "_csrf_token" => "dAU0V1MxS1cqYgFWclkVCyULB3MgLH1TGdUo2rzam3S412DHRoXFvuIa",
      "_mounts" => 0,
      "_track_static" => [...]
    },
    "redirect" => "",
    "session" => ...,
    "static" => ...
  },
  {#PID<0.13467.2>,#Reference<0.2219215103.1508376577.175999>},
  %Phoenix.Socket{
    assigns: %{},
    channel: Phoenix.LiveView.Channel,
    channel_pid: nil,
    endpoint: MyApp.Endpoint,
    handler: Phoenix.LiveView.Socket,
    id: "users_sessions:***",
    join_ref: "8",
    joined: false,
    private: %{
      connect_info: %{
        session: %{...}
      }
    },
    pubsub_server: MyApp.PubSub,
    ref: nil,
    serializer: Phoenix.Socket.V2.JSONSerializer,
    topic: "lv:phx-FrprXq5vupQQeKQC",
    transport: :websocket,
    transport_pid: #PID<0.13467.2>
  }
}

```
Which is handled by https://github.com/phoenixframework/phoenix_live_view/blob/5bfbd8378f47f51aa3567776865991b35410aeaa/lib/phoenix_live_view/channel.ex#L56

It seems like the error is caused because of the attribute `"redirect" => ""` in auth_payload.  However, I can't reproduce this locally and I can not figure out where this attribute is set. Is this a bug in LiveView or am I doing something wrong here?

**Comment by josevalim** [comment]
Can you check what happens if you do `<%= live_redirect @socket, to: "" %>`? From a quick glance at the code, we may not be expanding it, but I may be wrong.

**Comment by matthijsqd** [comment]
@josevalim Do you mean https://hexdocs.pm/phoenix_live_view/0.16.4/Phoenix.LiveView.Helpers.html#live_redirect/2 ? 
`@socket` as the first argument is not allowed. 

When I try `<%= live_redirect "foo", to: "" %>`, `<a data-phx-link="redirect" data-phx-link-state="push" href="">foo</a>` is rendered. When I click the link, the following is printed in the console:
```
phx-Frp-LChq_nCG3AQm destroyed: the child has been removed from the parent -  undefined utils.js:25:12
phx-Frp-LChq_nCG3AQm mount:  -  
```
and the current liveview's `mount/3` is called. I don't see any errors.

**Comment by matthijsqd** [comment]
After experimenting some more, I seem to have found the problem.  We use Surface in this app, and it looks https://hexdocs.pm/surface/Surface.Components.LiveRedirect.html doesn't generate the `href` attribute when the `to` prop is an empty string. 

In other words, `<LiveRedirect label="test" to={""} />` generates `<a data-phx-link="redirect" data-phx-link-state="push">test</a>`. Clicking this link results in the above error.

I will create an issue in the Surface repository . Thanks for your help.
