### ISSUE TITLE
Component's assignments are not being updated when using send_update

### ISSUE THREAD

**Issue by mustela** [phoenixframework/phoenix_live_view#1775]
### Environment

* Elixir version (elixir -v): 1.12.3
* Phoenix version (mix deps): 1.6.2
* Phoenix LiveView version (mix deps): 0.17.5
* Operating system: Mac-OS
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

Hello there! I'm just trying to understand if this is a bug or something you can't just do. I created [a site](https://github.com/mustela/phx_spot/) to showcase my problem. 

I have a [live view ](https://github.com/mustela/phx_spot/blob/master/lib/spot_web/live/home_live.ex) page that [renders a component](https://github.com/mustela/phx_spot/blob/master/lib/spot_web/live/home_live.ex#L18). 

```
@impl true
  def render(assigns) do
    ~H"""
    <div >
      <.live_component module={MessageComponent} id="message" >
        <%= @message %>
      </.live_component>
      <button phx-click="say_hello">Say hello</button>
    </div>
    """
  end
```

I want that component to be updated through a message (in my real app, Im pushing messages from other components), so I added a button to perform that action.

```
 def handle_event("say_hello", _value, socket) do
    debug("handle_event: say_hello")
    send_update MessageComponent, id: "message", message: "Hello? - #{DateTime.utc_now()}"

    {:noreply, socket}
  end
```

The component is a very [simple one](https://github.com/mustela/phx_spot/blob/master/lib/spot_web/live/message_component.ex)

```
defmodule SpotWeb.MessageComponent do
  use Phoenix.LiveComponent

  def render(assigns) do
    ~H"""
    <span>
      From the component
      <%= render_slot(@inner_block) %>
    </span>
    """
  end
end
```

The liveview is handling correctly the button event and is sending the message, but for some reason, the component can't reflect that update. It is stuck in the [Initial Hello!....](https://github.com/mustela/phx_spot/blob/master/lib/spot_web/live/home_live.ex#L10) message. 

It does work correctly if I just update the message in the view like

```
def handle_event("say_hello", _value, socket) do   
    {:noreply, assign(socket, :message, "Hello! - #{DateTime.utc_now()}")}
  end
```

Am I missing something? 

Any help is appreciated! :)

**Comment by josevalim** [comment]
The `@message` you are accessing inside the live component block belongs to the LiveView, not the component. The only assign the component is using is `@inner_block`, as you can see in its template. :)

**Comment by mustela** [comment]
Oh I thought that the `inner_block` was going to be handled in the context of the component, I mean the assignments. So is there any way to change the liveview assignment from the component? I tried doing something like 

```
<%= render_slot(@inner_block, message: @message) %> 
```
But that didn't work.

**Comment by josevalim** [comment]
@mustela check the documentation for `let` in `Phoenix.Component`.

**Comment by mustela** [comment]
Thank you!
