### ISSUE TITLE
LiveComponent Conditional Rendering Issue Using a For Comprehension

### ISSUE THREAD

**Issue by crockwave** [phoenixframework/phoenix_live_view#1782]
### Environment

* Elixir version 1.12.2
* Phoenix version 1.6.2
* Phoenix LiveView version 0.17.5
* Operating system: ubuntu
* Browsers you attempted to reproduce this bug on Microsoft Edge
* Does the problem persist after removing "assets/node_modules" and trying again? N/A

### Actual behavior

I think that [this resolved issue](https://elixirforum.com/t/livecomponent-conditional-rendering-issue-using-a-for-comprehension/44128/5) on `ElixirForum` has an underlying issue, identified in my solution confirmation post:

> _Since the problem I identified occurs even with no immediate text in the for comprehension, I think there continues to be an issue where passing an id attribute in the LiveComponent render command, should allow proper DOM manipulation._

### Expected behavior

I think that we should be able to successfully create conditionally rendered `for comprehension`s for `LiveComponent`s by passing an `id` attribute in the `LiveComponent` render call and using that `id` value in the wrapping `div` of the `LiveComponent`

If that is not possible, perhaps a compilation error could be generated when that pattern is used.

**Comment by josevalim** [comment]
Can you please provide a small application that reproduces the error? Thank you!

**Comment by crockwave** [comment]
I have created a project that demonstrates the conditional rendering issue.  The project demonstrates both the problem and the workaround arrived at in `ElixirForum`

https://github.com/crockwave/render

**Comment by josevalim** [comment]
The reason it doesn't work is because the ID is an integer and an integer is not valid ID. If you change the id too `id={"foo-#{@id}"}`, then it all works. The fact it works on the other case is rather an accident. Once the ID is invalid, then it becomes browser specific behaviour.

I have an idea of a check we can add to catch those cases and I will push it soon.

**Comment by josevalim** [comment]
Phoenix.HTML v3.2.0 raises on numeric IDs.
