### ISSUE TITLE
Suffix required for LiveViews? And other inconsistencies

### ISSUE THREAD

**Issue by khionu** [phoenixframework/phoenix_live_view#1785]
I'm currently using LiveView 0.17, and I'm having a rather hard time getting things working quite right. The main issue is that there are inconsistencies between LiveView and Vanilla Phoenix that can make it hard to reason around them when not conforming to specific usage patterns. One of the easier things to point out is how `Phoenix.LiveView.Router.live/4` requires LiveView modules have a specific naming convention. This is at odds with Pnoenix, which doesn't have that requirement. There's also the oddity of how Components are strictly a LiveView thing when they could be very useful in non-LiveView contexts.

That LiveViews can't be used as the root of a page is a bit of a stumbling block. I have a menu in a side bar that I want to use to change the main view, so the side bar doesn't reload while the main content renders a different page. So, they have to be either the same LiveView, or two entirely separate LiveViews that then have to be able to communicate somehow, ideally not through sending a BEAM message since this could be done client-side with JS. In pseuocode, this is the layout `<root><side><menu /></ side><mainview /></root>`

I'll keep updating this issue and I rediscover these painpoints; I'm picking back up a project I had put down because these hiccups, I recall thinking that LiveViews should probably just be a type of Component, and views shouldn't be broken up between Vanilla and LiveViews. I haven't gotten acquainted with the internals of LiveView, so idk how feasible that is, but I would like to discuss this.

**Comment by josevalim** [comment]
Hi @khionu, feel free to submit those as individual issues with as much detailed information as possible, and we will either close them or work on them. 

For example, I don’t understand the naming requirements you speak of. The new function components work on both Live and “dead” views, etc. so individual issues with as much precision as possible is the way to go. Or even forum threads if you want a longer discussion (as we will close what we don’t consider issues). Thank you.

**Comment by josevalim** [comment]
Oh, you updated the issue. The comment about root live views also seem to be addressed with sticky live views in master too, please see this PR: https://github.com/phoenixframework/phoenix_live_view/pull/1762

**Comment by khionu** [comment]
Alrighty. My apologies, I will open a thread on the forums tomorrow.
