### ISSUE TITLE
LiveView JS does not support older browsers

### ISSUE THREAD

**Issue by schinckel** [phoenixframework/phoenix_live_view#179]
### Environment

* Elixir version (elixir -v): Elixir 1.8.1 (compiled with Erlang/OTP 21)
* Phoenix version (mix deps): 1.4.3
* NodeJS version (node -v): v6.11.0
* NPM version (npm -v): 3.10.10
* Operating system: iOS 9.3.5 (client)

### Actual behaviour

There are some JS issues that prevent LiveView working on an old iPad mini, which cannot be updated to a newer browser.

The initial page renders, but updates are not delivered.

There are at least two issues preventing this:

1. `NodeList.prototype.forEach` is not defined. This is surmountable: you can shim this quite easily before LiveSocket is loaded. (`NodeList.prototype.forEach = Array.prototype.forEach`)

2. `Element.prototype.classList` is a read-only property. In several places `this.el.classList` is assigned to, instead of added to/removed from. This seems to work (at least in newer versions of Safari), but https://developer.mozilla.org/en-US/docs/Web/API/Element/classList suggests that it should be read-only. It appears to me that using `this.el.className` would work (and have the same behaviour in other browsers).

### Expected behaviour

Older browsers should be able to run LiveView sites.

**Comment by snewcomer** [comment]
@schinckel Mind testing out #182 && letting me know your thoughts?

**Comment by djm** [comment]
In regards to Point 2: #186 should fix this even though it was designed for a different problem. It removes all the direct writes to `classList`, replacing them with the appropriate `classList.add/remove` methods instead.
