### ISSUE TITLE
live_component is not rendering as usual in .leex

### ISSUE THREAD

**Issue by Ritvyk** [phoenixframework/phoenix_live_view#1797]
After upgrading to `phoenix 1.6.4`  and `phoenix_live_view 0.17.5` `live_component` in `.leex`  templates throws error.

Error : `undefined function live_component/4` 

NOTE: I have both `live_component` with `do-end` block and without block content neither of them seems to be worked.

I have a large project changing all files to `.heex` doesn't seems to be good idea, help me out.

**Comment by josevalim** [comment]
You no longer need to pass the socket as argument to live_component, so removing the first argument is enough to make the code work. But you have to plan to migrate to heex in the long term, otherwise you will have to use old live view versions.
