### ISSUE TITLE
phx-disable-with on submit button does not reset correct value when there are inner HTML tags 

### ISSUE THREAD

**Issue by jwilger** [phoenixframework/phoenix_live_view#1800]
### Environment

* Elixir version (elixir -v): Erlang/OTP 24 [erts-12.1.5] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit]; Elixir 1.13.0 (compiled with Erlang/OTP 24)
* Phoenix version (mix deps): 1.6.4
* Phoenix LiveView version (mix deps): 0.17.5
* Operating system: Ubuntu 20.04
* Browsers you attempted to reproduce this bug on (the more the merrier): Google Chrome 96.0.4664.45
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

When using a submit button defined as follows:

```elixir
<%= submit phx_disable_with: "Processing..." do %>
  Next&nbsp;<i class="fas fa-angles-right"></i>
<% end %>
```

The nested `<i>` tag is not restored once the event is processed, so the resulting HTML after processing becomes:

```html
<button class="button is-link" phx-disable-with="Processing..." type="submit">Next&nbsp;</button>
```

### Expected behavior

The nested `<i>` tag should be restored, so that the resulting HTML after processing returns to:

```html
<button class="button is-link" phx-disable-with="Processing..." type="submit">
            Next&nbsp;<i class="fas fa-angles-right"></i>
</button>
```

I'm aware that the desired effect can be achieved through the use of some custom CSS tied to the CSS loading state classes provided by LiveView, but it seem like the behavior here is, at the very least, surprising. If there's no good way to implement the expected behavior, we should at least update the documentation to make it clear that `phx-disable-with` doesn't play well with nested tags.

**Comment by josevalim** [comment]
Hi @jwilger, you are correct. See this previous issue #1352.

The docs also say (emphasis mine):

> To handle latent events, any HTML tag can be annotated with phx-disable-with, which swaps the **element's innerText** with the provided value during event submission.
>
> - https://github.com/phoenixframework/phoenix_live_view/blob/master/guides/client/form-bindings.md

If you think there are other places this should be mentioned, a PR is welcome!
