### ISSUE TITLE
How to use Alpine V3 with LiveView 1.6.. Heex template engine

### ISSUE THREAD

**Issue by Ritvyk** [phoenixframework/phoenix_live_view#1801]
I am unable to use alpine js with HEEX template engine

**Comment by Rio517** [comment]
This might be more appropriate for the support form. If you Google search for questions about this topic, there are several answered already - https://www.google.com/search?q=alpine+js+Heex+site:elixirforum.com

Perhaps one of those threads already answers your question? If not, the community is very friendly - describe what you've tried and where you're getting stuck. Lots of us are happy to help over there! 😁

Of course, if you do find an issue with the library, try to follow the template that shows up when you start to create a new issue. Context and specific information makes it easier for the maintainers to help us all.

Good luck!

**Comment by josevalim** [comment]
Yes, please use the forum for general questions/support!

Thanks for the help @Rio517 !
