### ISSUE TITLE
LiveView stuck in an endless recursion can never be killed

### ISSUE THREAD

**Issue by egze** [phoenixframework/phoenix_live_view#1804]
### Environment

* Elixir version (elixir -v): 1.13.1
* Phoenix version (mix deps): 1.6.5
* Phoenix LiveView version (mix deps): 0.17.5

### Actual behavior

I built a recursive function in the LiveView and started it. When I close the browser tab, it kept running. There was nothing I could do to recover from it, only a server restart helped.

### Expected behavior

When the websocket connection is closed - LiveView should be killed with whatever crazy things it was doing.

### How to reproduce

Run this liveview, click the link. Then in the logs you will see that the number goes up forever, even if you close the browser.

```elixir
defmodule HelloWorldWeb.RecurLive do

  use HelloWorldWeb, :live_view

  def render(assigns) do
    ~H"""
    <a href="#" phx-click="recur">do it</a>
    """
  end

  def mount(_params, _session, socket) do
    {:ok, assign(socket, :temperature, 1)}
  end

  def handle_event("recur", _params, socket) do
    recur()

    {:noreply, socket}
  end

  defp recur(i \\ 0) do
    IO.inspect(i)

    recur(i + 1)
  end
end
```

**Comment by chrismccord** [comment]
This is likely the same thing that would happen for any process that you have a bug were it infinitely recurses on itself. I don't believe there is anything for us to solve on our side. Thanks!

**Comment by chrismccord** [comment]
Looking into it more on the phoenix side, we aren't shutting it down because we rely on the channel processes to monitor the transport connection and stop on DOWN. Since the process is in a death loop, it will never process the DOWN. I'll think more about this, but I'm not sure if there's an acceptable solution for this edge case that is necessarily user land bug.

**Comment by egze** [comment]
Thanks Chris for the explanation.

I wonder if it’s possible for some other process to monitor the DOWN message and shut down the channel.

**Comment by chrismccord** [comment]
It’s possible for sure but every option introduces more overhead so it’s not an acceptable to solution if we have to introduce overhead for every channel at scale to catch this kind of edge case

**Comment by octosteve** [comment]
If you need to recurse, maybe use message passing to do it. That way you're constantly checking the mailbox for kill signals.
```elixir
defmodule HelloWorldWeb.RecurLive do

  use HelloWorldWeb, :live_view

  def render(assigns) do
    ~H"""
    <a href="#" phx-click="recur">do it</a>
    """
  end

  def mount(_params, _session, socket) do
    {:ok, assign(socket, :temperature, 1)}
  end

  def handle_event("recur", _params, socket) do
    send(self(), {:recur, 0})

    {:noreply, socket}
  end
  
  def handle_info({:recur, i}, socket) do
    IO.inspect(i)
    send(self(), {:recur, i + 1})
    {:noreply, socket}
  end
end
```

This would let your LiveView shutdown properly.

**Comment by egze** [comment]
@octosteve Thanks, that's a good way indeed. The problem is - I don't need to recurse 😅 There was a bug in our code where it happened by accident, and was hitting an API. And to my surprise, it kept going after I closed the browser. I was so used to the self-healing nature of LiveView, that I expected a browser reload to make it go away. Yes, totally our fault because of many reasons, but would be nice for a LiveView to have extra guard rails.

I also get why it may never happen.
