### ISSUE TITLE
Phoenix.Component does not show changes to list in a map

### ISSUE THREAD

**Issue by brianmay** [phoenixframework/phoenix_live_view#1805]
### Environment

* Elixir version (elixir -v): Elixir 1.13.1 (compiled with Erlang/OTP 24)
* Phoenix version (mix deps): 1.6.5
* Phoenix LiveView version (mix deps): 0.17.5
* Operating system: Linux
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: N/A

### Actual behavior

I have a component that iterates through a list:

```
  def logs(assigns) do                                                           
    lines = Map.fetch!(assigns, :lines)                                          
                                                                                 
    ~H"""
        [...]
                <%= for line <- lines do %>
                    [...]
                <% end %>
        [...]
    """
```

And three live views (heex file).

First one:

```
<% lines = Map.get(@nodes, node_id, []) %>                               
<.logs lines={lines}/> 
```

Second one:

```
    <% keys = nodes.map |> Map.keys() %>                                         
    <%= for id when id==node_id <- keys do %>                                    
        <% lines = Map.get(@nodes, node_id, []) %>                               
        <.logs lines={lines}/>                                                   
    <% end %>
```

Third version is the same as the first version but removes the component and inserts the contents directly into the heex template.

Observed results:

1. The 1st version does not update and show changes.
2. The 2nd version displays updated to the list in @nodes[node_id].
3. The 3rd version does update correctly.

### Expected behavior

All three versions should update and show changes to the list.

I imagine this might be a difficult one to debug and fix :-(

**Comment by simonmcconnell** [comment]
@brianmay what's the reason you are pulling variables out before the `~H` sigil in your component and inside your liveviews?  You reference assigns like so:

```
  def logs(assigns) do                                                                                                                             
    ~H"""
        [...]
                <%= for line <- @lines do %>
                    [...]
                <% end %>
        [...]
    """
```

And if you want to change the assigns **within** a function component, you need to use `assign` or `assign_new`.

Your other snippets would be `<.logs lines={@nodes[node_id] || []}/>` and
```                                   
    <%= for id when id==node_id <- Map.keys(@nodes.map) do %>                                                           
        <.logs lines={@nodes[node_id] || []}/>                                                   
    <% end %>
```

**Comment by brianmay** [comment]
Hmm. I already tried the second suggestion. When I tried the first suggestion (something I didn't think of), it seems to solve the problem.

This is a bit weird and unexpected. But not sure if this is a design issue or a bug. If you think this is not a bug, happy to close.

**Comment by chrismccord** [comment]
This is is expected and outlined in the docs thoroughly. You must use assigns and the assign apis for proper change tracking. Thanks!

**Comment by simonmcconnell** [comment]
@brianmay check out [this section of the docs](https://hexdocs.pm/phoenix_live_view/assigns-eex.html)

**Comment by brianmay** [comment]
Thanks for the documentation reference.

**Comment by josevalim** [comment]
@brianmay if you can provide a small app that reproduces the issue, I can take a look. Using a variable is supposed to *always* show changes, instead of never. So you definitely want to use assigns so you get change tracking, but if you don't use it, then it should still work.

**Comment by josevalim** [comment]
(PS: I cannot reproduce this issue, hence why I am asking for the app)

**Comment by brianmay** [comment]
@josevalim Thanks. Will try to get you a test case, as time permits.

**Comment by brianmay** [comment]
@josevalim See https://github.com/brianmay/test_1805

This is a new phoenix project without ecto support, and a live view added. See the [README.md](https://github.com/brianmay/test_1805/blob/main/README.md) for instructions.

The code itself is stupid, but hopefully it should demonstrate the problem.

**Comment by josevalim** [comment]
Thank you, I was able to reproduce and address the bug, but you definitely want to follow the advice on this thread as that will emit less output. :)

**Comment by iwarshak** [comment]
I got bitten by this type of problem today and it was very confusing because using a local variable in a heex template works if I am outputting it, but using it in a conditional fails.

I am wondering if it's possible to perhaps emit a warning if I use a local variable?

```
def my_component(assigns) do
  has_errors = Enum.any?(Keyword.get_values(assigns[:form].errors, assigns[:field]))
  ~H"""
  <% if has_errors do %>
    This will never display!
  <% end %>
end
```

versus the proper way:

```
def my_component(assigns) do
  has_errors = Enum.any?(Keyword.get_values(assigns[:form].errors, assigns[:field]))
  assigns = assigns
  |> assign(:has_errors, has_errors)

  ~H"""
  <% if @has_errors do %>
  ...
  <% end %>
end
```

**Comment by josevalim** [comment]
This is definitely a bug though, which should have been addressed in recent versions. Is it reproducible on latest? :)

**Comment by iwarshak** [comment]
José - here is a runnable example. It's completely arbitrary, but it works (and by that, I mean it actually breaks) 😄 

```
Application.put_env(:phoenix, :json_library, Jason)

Application.put_env(:sample, SamplePhoenix.Endpoint,
  http: [ip: {127, 0, 0, 1}, port: 5001],
  server: true,
  live_view: [signing_salt: "aaaaaaaa"],
  secret_key_base: String.duplicate("a", 64)
)

Mix.install([
  {:plug_cowboy, "~> 2.5"},
  {:jason, "~> 1.0"},
  {:phoenix, "~> 1.6.10"},
  {:phoenix_live_view, "~> 0.17.10"}
])

defmodule SamplePhoenix.ErrorView do
  use Phoenix.View, root: ""

  def render(_, _), do: "error"
end

defmodule BrokenComponent do
  use Phoenix.Component
  require Integer

  def is_the_count_even(assigns) do
    # has_errors = Enum.any?(Keyword.get_values(assigns[:form].errors, assigns[:field]))
    # ^^^^ this is my original problem
    is_even = Enum.all?(Keyword.get_values(assigns[:var].counters, :counter), fn(x) -> Integer.is_even(x) end)


    # assigns = assigns
    # |> assign(:is_even, is_even)
    # ^^^^ this seems to be the "proper" way to do it

    ~H"""
    <%#= is_even %>
    <%# ^^^ if I uncomment this, and output the variable it all works %>

    <%= if is_even do %>
      <p>is_the_count_even: true</p>
    <% else %>
      <p>is_the_count_even: false</p>
    <% end %>
    """
  end
end

defmodule SamplePhoenix.SampleLive do
  use Phoenix.LiveView, layout: {__MODULE__, "live.html"}

  def mount(_params, _session, socket) do
    {:ok, assign(socket, :count, 2)}
  end

  def render("live.html", assigns) do
    ~H"""
    <script src="https://cdn.jsdelivr.net/npm/phoenix@1.6.10/priv/static/phoenix.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/phoenix_live_view@0.17.10/priv/static/phoenix_live_view.min.js"></script>
    <script>
      let liveSocket = new window.LiveView.LiveSocket("/live", window.Phoenix.Socket)
      liveSocket.connect()
    </script>
    <style>
      * { font-size: 1.1em; }
    </style>
    <%= @inner_content %>
    """
  end

  def render(assigns) do
    ~H"""
    <%= @count %>
    <button phx-click="inc">+</button>
    <button phx-click="dec">-</button>
    <BrokenComponent.is_the_count_even var={%{counters: [counter: @count]}} />
    """
  end

  def handle_event("inc", _params, socket) do
    {:noreply, assign(socket, :count, socket.assigns.count + 1)}
  end

  def handle_event("dec", _params, socket) do
    {:noreply, assign(socket, :count, socket.assigns.count - 1)}
  end
end

defmodule Router do
  use Phoenix.Router
  import Phoenix.LiveView.Router

  pipeline :browser do
    plug(:accepts, ["html"])
  end

  scope "/", SamplePhoenix do
    pipe_through(:browser)

    live("/", SampleLive, :index)
  end
end

defmodule SamplePhoenix.Endpoint do
  use Phoenix.Endpoint, otp_app: :sample
  socket("/live", Phoenix.LiveView.Socket)
  plug(Router)
end

{:ok, _} = Supervisor.start_link([SamplePhoenix.Endpoint], strategy: :one_for_one)
Process.sleep(:infinity)

```

**Comment by chrismccord** [comment]
@iwarshak the bare binding `is_even` breaks change tracking and will not work. Your `assign(assigns, :is_even)` commented out code is indeed the proper way to handle it. Can you confirm it works with the `@is_even` assign?

**Comment by josevalim** [comment]
@chrismccord using naked variables should taint the code so it is always reevaluated though. So @iwarshak should see changes, we just won't be efficient about it.

Unless @iwarshak is complaining that we are sending too much output. :)

**Comment by josevalim** [comment]
Fixed in master!

**Comment by iwarshak** [comment]
@chrismccord `@is_even` works fine. What was confusing is that displaying is_even (`<%= is_even %>`) always displayed correctly, but using it in a conditional always failed. 

I understand I should have been using assigns, but because it worked I never noticed I was using it incorrectly until I put the variable in an if-statement.
