### ISSUE TITLE
phx-click not exec'd if phx-click-away fired in same epoch

### ISSUE THREAD

**Issue by whitepaperclip** [phoenixframework/phoenix_live_view#1809]
### Environment

* Elixir version (elixir -v): 1.12.3
* Phoenix version (mix deps): 1.6.5
* Phoenix LiveView version (mix deps): master
* Operating system: macOS
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Expected behavior

Given two elements on the same page:

```html
<div phx-click-away="foo">
  click away
</div>

<div phx-click="bar">
  click
</div>
```

And given their respective event handlers in the parent LiveView:

```elixir
  def handle_event("foo", _params, socket) do
    IO.puts("foo")
    {:noreply, socket}
  end

  def handle_event("bar", _params, socket) do
    IO.puts("bar")
    {:noreply, socket}
  end
```

I expect clicking "bar" to output either of the following in the console:

```
bar
foo
```

or:

```
foo
bar
```

### Actual behavior

It only outputs `foo`. I think this is due to this commit from @chrismccord : https://github.com/phoenixframework/phoenix_live_view/commit/1480b49e52e973f551c88bede2f802e5f5d8c298

This has the unfortunate consequence of preventing the execution of every `phx-click` binding on the page if even a single `phx-click-away` is present.

For a practice use case, we have a modal on a page that's only visible when some other element is clicked, which then shows the modal with `LiveView.JS`. `phx-click-away` is set on the modal, which calls `JS.hide/2`. I don't mind if clicking some completely unrelated element with `phx-click` set still calls `JS.hide/2` on the modal, but the `phx-click` should still work.

**Comment by chrismccord** [comment]
I can recreate the issue with your example, but we only prevent the `phx-click` if the `phx-click-away` element is visible on the page. In your modal example, in what scenarios does the click-away'd element remain visible on click away?

**Comment by whitepaperclip** [comment]
That makes sense! I can understand the logic behind that commit.

`JS.isVisible(el)` is only checking the visibility of the element, but what frequently happens with modals is some structure like:

```html
<div class="dark-modal-background-thing hidden">
  <div class="white-background-modal-content" phx-click-away="hide_everything">
    modal content
  </div>
</div>
```

The `phx-click-away` attribute is set on the content div (not the parent div) because clicking the dark background should close the modal.

**Comment by chrismccord** [comment]
Right, we generate similar code for the `phx.gen.live` modals. I'm still not following which scenario's this fails because phx-click-away will hide the modal, so clicks won't silenced. Likewise clicks within the modal will be fine because we do not invoke click-away if the target is contained inside the element. Can you put together a complete modal example where this is causing issues? Thanks!

**Comment by whitepaperclip** [comment]
Yep! I'll submit an example repo shortly.

**Comment by whitepaperclip** [comment]
https://github.com/whitepaperclip/click_away

If you navigate to localhost:4000/posts, the links at the bottom all work. If you switch to PLV master, the links fail.

**Comment by maxvw** [comment]
The `isVisible` function should be updated with a better check I think, right now it is checking computer properties for the element itself however that is not the same as checking visibility in the DOM. It could have opacity 1 and display block but still be invisible if the parent is, as shown in the demo. 

After some quick research, it appears to be some discussion on what is the best way to determine this. However the `[implementation done by jQuery](https://github.com/jquery/jquery/blob/a684e6ba836f7c553968d7d026ed7941e1a612d8/src/css/hiddenVisibleSelectors.js)` seems simple enough. 

Then the function would simply need to do this check:
```js
  isVisible(el){
    return !!( el.offsetWidth || el.offsetHeight || el.getClientRects().length )
  },
```

**Comment by chrismccord** [comment]
@whitepaperclip can you confirm if @maxvw's patch solves your issue? Thanks!

**Comment by whitepaperclip** [comment]
@chrismccord we are working on the same codebase; it definitely does 😃

**Comment by chrismccord** [comment]
ah prrfect. Thanks! :)
