### ISSUE TITLE
Confusion with snake-case vs dash_case in ~H heex Component Syntax

### ISSUE THREAD

**Issue by mavuio** [phoenixframework/phoenix_live_view#1812]
when converting my code to the new ~H syntax i found the following a bit inconsistent:

when using function syntax you can use parameters as atom-friendly snake_case and they end up
as markup friendly dash-case in the markup:

e.g:
`<%= link "", to: "#", phx_click: "bar" %>`

when using the new component syntax, we can use dash-case or snake_case, but those params
get passed as-is:

so i still need to pass snake_case arguments in the new, more html-ish syntax:
 
`<.live_component module={Foo.Bar}  first_name={@model.first_name} />`

which is fine for me, i don't like thinking to convert those syntaxes in my mind anyway.

but looking at the liveview-docs, in the doc for <.form its advocated using dash-case as
paramers:

`<.form let={f} for={@changeset} phx-change="validate" phx-submit="save">`
this works fine, as `phx-change` is internally passed as `"phx-change":`, which
is passed on again to the markup to be consumed by liveview's-javascript.

but:
`<.form let={f} for={@changeset} phx_change="validate" phx_submit="save">`

would work as well (because the dash_cased args get auto-converted to snake-case again)

I'm just afraid that newcomers mix up the syntaxes, and i would be more comfortable with:

the new component's default be to convert dash-case parameters internally to snake-cased atoms.
so you could use `first-name="foo"` as well as `first_name="foo"`, they both end up as
`%{ first_name: "foo"}` in  the assigns, and not like now as: `%{ "first-name": "foo"}` and `%{ first_name: "foo"}` 

but maybe this would breaks things, 
and the currently practised auto-conversion makes sense when going from elixir to html,
but not from ~H - Components to elixir, because elixir can handle dashed atoms as well while
html is not supposed to handle snake_cased tag-parameters.

➜ maybe it would just help to use some dash/snake-case example-variables in the documentation for <.live_component or the component syntax in ~H to clarify this a bit, when to use which case
as it starts to get used in mixed versions out there:

https://elixirforum.com/t/petal-components-package-a-set-of-tailwind-styled-components-written-in-heex/43633/18

![clipping-2021_12_23-11_00_49@2x](https://user-images.githubusercontent.com/1092088/147223959-25346212-2a20-4701-8892-6bb1eaba5d05.png)

**Comment by josevalim** [comment]
I agree that we should rewrite `foo-bar` to `foo_bar`. Let's see what the team thinks.

**Comment by josevalim** [comment]
I was pointed out that both `<div some_attr=...>` and `<div some-attr=...>` are valid HTML and are distinct. Therefore, if we convert both to `some_attr`, we will be unable to render it back to its proper HTML representation. So most likely we can't go ahead with this change.

The good news is that the upcoming declarative assign will at least raise and hopefully make it less prone for confusion.

**Comment by mavuio** [comment]
>The good news is that the upcoming declarative assign will at least raise and hopefully make it less prone for confusion.

that sure helps, thanks for the swift reply.

but still: 
optional mistyped attributes may never raise then, if they are just allowed to pass thru as  "extra"-attributes in the final HTML

so `some-attr` might end up as an attribute in the final HTML but not doing the magic `some_attr` would have
caused.

may be this can be tackled in the upcoming declarative assign spec, there are somewhat bigger things to solve over there anyway.

my conclusion:

i might start using `some_attr` for all my component-parameters by default, as they would most always be translated
to `some-attr` in HTML anyway, then i don't have to memorize which params are for the component and which are for HTML.


for reference, this is what i found for rendering dynamic attributes back to HTML:

if using dynamic attributes **as a keyword list** the case is unified:

`<div {[ some-attr: "foo","other_attr": "foo"]} >` becomes `<div some-attr="foo" other-attr="foo">`

if you pass them **as a map**, the case is preserved:

`<div {%{ "some-attr"=> "foo","other_attr"=>"foo"}  >` becomes `<div some-attr="foo" other_attr="foo">`

from my end this issue can be closed then, happy holidays!
