### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by pyladune** [phoenixframework/phoenix_live_view#1815]
### Environment

* Elixir version (elixir -v): 1.12
* Phoenix version (mix deps): 1.6.4
* Phoenix LiveView version (mix deps): 0.17.5
* Operating system: Fedora 35
* Browsers you attempted to reproduce this bug on (the more the merrier): all
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

Adding live_view to existing app : 

- With plug_forgery -> does not work
- Without plug_forgery -> works, but permanently refresh the page (loops)

### Expected behavior
No refreshing loop.
I look for possible mistake following https://hexdocs.pm/phoenix_live_view/installation.html but did not found any reason despite it is probably something in setup

**Comment by josevalim** [comment]
Hi @pyladune, it is impossible for us to know what went wrong without looking at the code. My suggestion is for you to run `mix archive.install hex phx_new` and generate a new app, and compare the produced contents, or isolate the issue in an app we can take a look at.

**Comment by walkr** [comment]
For what it's worth, I've also had issues with infinite loops and LiveView on multiple Phoenix installations, which previously worked just fine.

I've seen a lot of 
```
Parameters: %{"_csrf_token" => "...", "_mounts" => "0", "_track_static" => %{"0" => "http://localhost:4000/assets/app.css", "1" => "http://localhost:4000/assets/app.js"}, "vsn" => "2.0.0"}
```
in the logs of one app and plenty `*-consecutive-reloads` client side in local storage.

It works now, but I have no idea why. 

I'm developing multiple Phoenix apps locally, so I'm curious if there's some incompatibility when moving and developing between them.

**Comment by chrismccord** [comment]
For localhost, if you have old tabs up that are running against a different app, they will attempt to reconnect to the new app with an invalid csrf token (different secrets), and that would explain the behavior. Without more information we can't assess what's going on here. If you can provide an example app and steps to reproduce, please let us know. Thanks!
