### ISSUE TITLE
Injected container element should not affect layout

### ISSUE THREAD

**Issue by type1fool** [phoenixframework/phoenix_live_view#1823]
### Environment

* Elixir version (elixir -v): 1.31.1
* Phoenix version (mix deps): 1.6.2
* Phoenix LiveView version (mix deps): 0.17
* Operating system: MacOS 12.1 Monterey
* Browsers you attempted to reproduce this bug on (the more the merrier): N/A
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

When rendering a LiveView, a `div` is injected via LV's Javascript, where a session key and other data is stored.

```html
<div
  data-phx-main="true"
  data-phx-session="...gD5xxZ...I"
  data-phx-static="...aAJhB..."
  id="phx-FsfIGzzw..."
  data-phx-root-id="phx-FsfIGzz..."
  class="phx-connected">
  <!-- inner content -->
</div>
```

This injected div affects the page layout, where I prefer to apply flexbox to the body to ensure a full-height `<body>`. 

### Expected behavior

In a dead view, the above container is not injected, so the layout defined in HTML works as expected.

### Proposed change

I found `replaceRootContainer()` in dom.js where this element swap happens. By adding `style="display: contents"` to the container, the layout would not be affected. The style attribute would work regardless of what CSS tooling is used an a project, and it's well-supported.

https://caniuse.com/css-display-contents

Should a `style` attribute be appended within `replaceRootContainer`? I am happy to open a PR for this with a little guidance.

### Before

![image](https://user-images.githubusercontent.com/13895134/148449831-e5de2472-ad70-482d-91cc-d11f954e24bf.png)

### After

![image](https://user-images.githubusercontent.com/13895134/148449859-598b0198-b6b3-4302-b7c3-99f3b617d4aa.png)

**Comment by chrismccord** [comment]
Note that we support the ability to customize the tag and attributes of the container, via the `:container` option, but if applying this style by default would cut the corner cases that affect layouts it seems like a nice default. Let me dig in a bit. Thanks!

**Comment by chrismccord** [comment]
I'm going to punt on this for default for now until I become more acquainted with the behavior. It would also break other apps potentially relying on the fact we don't set this. Note that you can get what you want with a one line change to your app_web.ex's `live_view` block:

```elixir
      use Phoenix.LiveView, 
        layout: {MyAppWeb.LayoutView, "live.html"},
        container: {:div, style: "display: contents;"}
```

Hope that helps! Thanks!

**Comment by type1fool** [comment]
Excellent! I figured there was a way to adjust the container, I just couldn't [find it](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#__using__/1) in the docs.

That's a sneak peek at my BigElixir demo, btw. 😉 I may be having too much fun with LV.
