### ISSUE TITLE
JS.push target option is ignored in tests

### ISSUE THREAD

**Issue by grrrisu** [phoenixframework/phoenix_live_view#1824]
environment

* Elixir version (elixir -v): Elixir 1.13.1 (compiled with Erlang/OTP 24)
* Phoenix version (mix deps): 1.6.6
* Phoenix LiveView version (mix deps): 0.17.5
* Operating system: MacOS / Ubuntu
* Browsers you attempted to reproduce this bug on (the more the merrier): -
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: -

### Actual behavior

I have a live component with an event handler:

```
defmodule MeepleWeb.BoardLive.Map do
  use MeepleWeb, :live_component

  def handle_event("discover", %{"x" => x, "y" => y}, socket) do
    # show some details
  end

  def field(assigns) do
    ~H"""
      <div
        id={"field-#{@x}-#{@y}"} 
        phx-click="discover" phx-value-x={@x} phx-value-y={@y} phx-target={@myself} 
      />
    """ 
  end
end
```

And a corresponding test for it:

```
  test "show field details", %{conn: conn} do
    {:ok, view, _html} = live(conn, "/board")

    view
    |> element("#field-1-2")
    |> render_click()

    assert view |> element("#field-card") |> render() =~ "<h2>Planes</h2>"
  end
```
Everything worked as expected, until, at some point, I extended the click event with some transitions:

```
def field(assigns) do
  ~H"""
    <div
      id={"field-#{@x}-#{@y}"} 
      phx-click={fade_in(@x, @y, @myself)}
    />
  """ 
end

def fade_in(x, y, target) do
  JS.push("discover", value: %{x: x, y: y}, target: target)
  |> JS.show(
    transition: {"ease-out duration-500", "opacity-25", "opacity-100"},
    to: "#field-details"
  )
end

```

This still works fine, but now the **tests** are breaking:

```
** (UndefinedFunctionError) function MeepleWeb.BoardLive.Index.handle_event/3 is undefined or private
        (meeple_web 0.1.0) MeepleWeb.BoardLive.Index.handle_event("discover", %{"x" => 1, "y" => 2}, ...
```

The event is not passed to live component, but to the live view instead. It looks like the target option has been ignored.

### Expected behavior

`render_click` should pass the target when using `JS.push` with the `target` option.

**Comment by josevalim** [comment]
I believe we don't read the target option inside the JS event in tests. A PR would be very welcome!

**Comment by grrrisu** [comment]
Looks like the latest master fixes the problem, I only have the problem with the `0.17.5` release.
