### ISSUE TITLE
live_file_input is rendered too many times

### ISSUE THREAD

**Issue by krystofrezac** [phoenixframework/phoenix_live_view#1827]
### Environment

* Elixir version (elixir -v): 1.13.0
* Phoenix version (mix deps): 1.6.6
* Phoenix LiveView version (mix deps): 0.17.5
* Operating system: Arch Linux
* Browsers you attempted to reproduce this bug on (the more the merrier): Google Chrome, Mozilla Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

I was trying to do file uploading and I managed to do so but I found a weird bug. I have a modal component and I am using it twice once for creating a new item and once for editing the item. But for some reason, if `live_file_input` is in the template twice it is rendered three times.

``` elixir
  @impl Phoenix.LiveView
  def mount(_params, _session, socket) do
    {:ok,
     socket
     |> allow_upload(:image,
       accept: ~w(.jpg .jpeg .png)
     )}
  end

  @impl Phoenix.LiveView
  def render(assigns) do
    ~H"""
    <div>
      <.modal_with_animations action="edit" uploads={@uploads}/>
      <.modal_with_animations action="add" uploads={@uploads}/>
    </div>
    """
  end

  defp modal_with_animations(assigns) do
    ~H"""
    <div id={@action} class="bg-red-100 p-4 m-2">
      <%= live_file_input @uploads.image, ahoj: @action %>
    </div>
    """
  end
```

![DeepinScreenshot_select-area_20220113163353](https://user-images.githubusercontent.com/39591095/149360121-5c77ed32-d58b-457d-8df7-142a94a1bf2a.png)

It doesn't work even if the `live_file_input` elements are not in the component.

``` elixir
  @impl Phoenix.LiveView
  def render(assigns) do
    ~H"""
    <div>
      <%= live_file_input @uploads.image %>
      <%= live_file_input @uploads.image %>
    </div>
    """
  end
```

I checked the initial HTML that is sent to the browser and it contains only two inputs so I guess that it's a fault of JS or some weird diff.

Is it possible to have multiple `live_file_input` elements with the same first parameter or do I need to find a way around it?

**Comment by josevalim** [comment]
Does it happen if you use another input such as text_input?

**Comment by krystofrezac** [comment]
No, I didn't notice it anywhere else.

**Comment by chrismccord** [comment]
sounds like a duplicate ID issue. If you call `liveSocket.enableDebug()`, my guess is it will warn about duplicate DOM IDs. We don't support overriding the `:id`, but it's not clear from the example where this kind of setup makes sense. You can only edit the image after you've uploaded, no?

**Comment by krystofrezac** [comment]
Yes, it logs `Multiple IDs detected: description. Ensure unique element ids.`. I tried to wrap the upload in div with a unique id but that didn't fix the issue. Is there any other attribute besides id and name that I could set to make JS aware that they are two different elements?

And yeah images can be edited only after upload, but this component in the real app contains a whole form for adding/editing products and images can be added even when the product is being created. You can see the form [here](https://github.com/krystofrezac/od_stastnych_vcel/blob/feature/products/lib/bees_web/live/admin/products/product_modal.ex) and it's called twice in [here](https://github.com/krystofrezac/od_stastnych_vcel/blob/feature/products/lib/bees_web/live/admin/products/index.html.heex).

**Comment by chrismccord** [comment]
You need to provide a unique `id` here
https://github.com/krystofrezac/od_stastnych_vcel/blob/feature/products/lib/bees_web/live/admin/products/product_modal.ex#L38 , but you will also have duplicate IDs for the `live_file_input`. You can only render them in a single place at a given time at the moment since we use their ID to track certain things.

**Comment by krystofrezac** [comment]
So I fixed it by reworking how the modal component works. I added an `if` clause so if it's close then it does not render any HTML, which fixed the two upload elements issue. And I added some JS hooks to preserve animations. Thanks for your help and have a nice day.
