### ISSUE TITLE
duplicate elements with sticky live_render

### ISSUE THREAD

**Issue by cdock1029** [phoenixframework/phoenix_live_view#1830]
### Environment

* Elixir version (elixir -v): `1.13.1`
* Phoenix version (mix deps): `1.6.6`
* Phoenix LiveView version (mix deps): `github ref:62050eb995d13fb46976d2ff18c7a1dfa40eadfe`
* Operating system: `Manjaro Linux`
* Browsers you attempted to reproduce this bug on (the more the merrier): `Brave, Firefox`
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: `N/A, using esbuild`

### Actual behavior

[Test repo to demonstrate](https://github.com/cdock1029/weightlifting/tree/6b8df875793b61f64f61edea1364bf5e5ca1f7a7)

In `live.html.heex`, I `live_render` a header:

```elixir
<%= live_render @socket, WeightliftingWeb.HeaderLive, id: "header_nav", sticky: true, container: {:header, class: ""} %>
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>
```

In browser console, after running `liveSocket.enableDebug()` and refreshing page and/or navigating links using `live_redirect`, I see:
```
utils.js:19 Multiple IDs detected: header_nav. Ensure unique element ids.
```

Run in console:

`document.querySelectorAll("#header_nav")`

result:

`NodeList [ header#header_nav.phx-connected, header#header_nav ]`

Markup is oddly nested and duplicated:

![Screenshot from 2022-01-13 18-41-05](https://user-images.githubusercontent.com/802586/149426194-8c8e7bbd-a514-4c7a-8844-da3203863290.png)

### Expected behavior

Using `sticky: true` just persists the header, no incorrect duplicate elements or nesting in DOM

**Comment by josevalim** [comment]
@cdock1029 you are rendering the sticky view from the layout and the sticky view uses the same layout. If you are rendering the sticky view within your live layout, make sure that the sticky view itself does not use the same layout. You can do so by returning `{:ok, socket, layout: false}` from mount.

**Comment by josevalim** [comment]
I also pushed an update to docs to help others not get stuck, thanks for the report!

**Comment by cdock1029** [comment]
Thanks a lot Jose, sorry for the noise. This doc update makes sense and clarifies it now. Appreciate it!
