### ISSUE TITLE
LiveView doesn't respect `phx-debounce="blur"`

### ISSUE THREAD

**Issue by alaadahmed** [phoenixframework/phoenix_live_view#1832]
### Environment

* Elixir version (elixir -v): __`1.13.2`__
* Phoenix version (mix deps): __`1.6.6`__
* Phoenix LiveView version (mix deps): __`0.17.5`__
* Operating system: __`macOS 11.6.2`__
* Browsers you attempted to reproduce this bug on (the more the merrier): __`firefox`__ , __`chrome`__ & __`safari`__
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: __`Yes`__

### Actual behavior
LiveView doesn't respect `phx-debounce="blur"` on all __required__ input fields. I am not sure if this due to the custom classes I used for showing errors, but I didn't remove `invalid-feedback` class from `error_tag` if this can affect at all. I am not sure where is the issue.

```elixir
  def error_tag(form, field) do
    Enum.map(Keyword.get_values(form.errors, field), fn error ->
      content_tag(:span, translate_error(error),
        class: "block my-2 text-accent invalid-feedback",
        phx_feedback_for: input_name(form, field)
      )
    end)
  end
```
When I change any __required__ input field and then press __TAB__ to move to next input field or event without pressing __TAB__, I find all other show errors of required or not valid input.

These are error classes I use to show invalid fields:
```
"border-red-500 focus:border-red-500 focus:ring-red-500 text-red-800 placeholder-red-700 bg-red-50"
```
Actually this application was working fine with __LiveView__ `0.15.7` and I just moved it to latest version and updated the template files to use new syntax. am I missing something?
 

https://user-images.githubusercontent.com/14099508/149513603-b1c322ff-e20a-4c0c-a16f-aff3c5ec15a3.mov

### Expected behavior
Expected when I use `phx-debounce="blur"` it will affect only fields that I touch or changed, not all form fields.

**Comment by josevalim** [comment]
That's not supposed to happen and I can't reproduce it on my own forms. Do you have a small application that reproduces the error?

**Comment by alaadahmed** [comment]
Unfortunately I don't have small app that reproduce the same exact error, I initiated now fresh phoenix app and it of course didn't produce the same error! It's ok we can close this issue if it doesn't produce on fresh phoenix app, it means I have something wrong somewhere .. but for many days I am trying to figure out what is the issue.

**Comment by josevalim** [comment]
I would try to isolate from the current app. Try removing other stuff, keeping the form small, removing javascript libraries, etc. It may help pinpoint exactly what is causing it.

**Comment by alaadahmed** [comment]
Here is the old app run on `0.15.7` which I just copied to new phoenix running `0.17.5`

https://user-images.githubusercontent.com/14099508/149518340-bc452473-a139-4966-8762-8493fca5643d.mov

I checked __CHANGELOG__ I thought maybe something changed in APIs for `phx-debounce` but everything as is. I will try to isolate the form and check again.
