### ISSUE TITLE
Socket rejoins again and again which causes Live View to emit events itself periodically. when using with Alpine js

### ISSUE THREAD

**Issue by uzairaslam196** [phoenixframework/phoenix_live_view#1837]
Issue: 
Socket rejoins again and again which causes Live View to emit events itself periodically.

1 reason I noticed that sometimes heartbeat stops for more than 1 minute(timeout limit is 1 minute), in this case socket rejoined again.

I increased timeout at client side as well at server side in Endpoint to check if this is the only issue but it didn't work and socket behaved the same.

Did anyone face same issue before, what could be a possible reasons and how to avoid this issue, any suggestion?

Stack: PETAL

Elixir: 1.11 
Erlang: 23.0
phoenix: 1.5.3
phoenix_live_view: 0.15.7
alpinejs  "^2.8.2"
Browsers: chrome, safari

I think issue is with Alpine Js but couldn't figure out any solution.

**Comment by josevalim** [comment]
Hi @uzairaslam196! I recommend using ElixirForum for those questions, as the odds of more people looking at it is much higher. If you can boil down to a LiveView issue, then feel free to reopen. :)

**Comment by chrismccord** [comment]
Yes we need more information here to identify if this is an issue on our side. If you can provide more information or a way to reproduce, please let us know. Thanks!

**Comment by uzairaslam196** [comment]
> Hi @uzairaslam196! I recommend using ElixirForum for those questions, as the odds of more people looking at it is much higher. If you can boil down to a LiveView issue, then feel free to reopen. :)

Ahh my mistake. I will reopen the issue with enough details if it's on Phoenix side.
