### ISSUE TITLE
Add `phx-mount` binding

### ISSUE THREAD

**Issue by totaltrash** [phoenixframework/phoenix_live_view#1838]
## Background

Live view currently supports two DOM patch bindings: `phx-update` and `phx-remove`. `phx-remove` is a beautiful thing when you want to apply a transition to an element when removing a component, as shown here: https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.JS.html#module-client-utility-commands.

One limitation of the above example is that the css classes and keyframes needs to be defined in your css. This is improved when you use the 3-tuple version of `JS.hide` (and if you are using a utility css framework), you can do something like:

```elixir
def hide_modal(js \\ %JS{}) do
  js
  |> JS.hide(transition: {"ease-in duration-200", "opacity-100", "opacity-0"}, to: "#modal")
  ...
end
```

## Proposal

Currently, when you want to apply a transition on mount, you need to add css classes to the elements you want to apply the transition to, and define those classes and keyframes in the css. It would be amazing to do something similar to `phx-remove` but on mount.

```elixir
def show_modal(js \\ %JS{}) do
  js
  |> JS.show(transition: {"ease-in duration-200", "opacity-0", "opacity-100"}, to: "#modal")
  ...
end
def hide_modal(js \\ %JS{}) do
  js
  |> JS.hide(transition: {"ease-in duration-200", "opacity-100", "opacity-0"}, to: "#modal")
  ...
end

def modal(assigns) do
  ~H"""
  <div id="modal" class="phx-modal" phx-mount={show_modal()} phx-remove={hide_modal()}>
  ...
  """
end
```

**Comment by benvp** [comment]
As a little workaround for now. You could achieve the same using a hook with something like this.

```js
const Hooks = {
  Mount: {
    mounted() {
      liveSocket.execJS(this.el, this.el.getAttribute('phx-mount');
    }
  }
}
```

```elixir
def modal(assigns) do
  ~H"""
  <div id="modal" class="phx-modal" phx-mount={show_modal()} phx-hook="Mount">
  ...
  """
end
```
