### ISSUE TITLE
Submit button value not included in event params

### ISSUE THREAD

**Issue by nathanl** [phoenixframework/phoenix_live_view#184]
### Environment

* Elixir version (elixir -v): Elixir 1.8.1 (compiled with Erlang/OTP 20)
* Phoenix version (mix deps): 
  * phoenix 1.4.3 (ref [06e60fe](https://github.com/phoenixframework/phoenix/commit/06e60fe17503cec168928c6fea4df25b9f129559))
  * phoenix_html 2.13.2 (ref [2208553](https://github.com/phoenixframework/phoenix_html/commit/22085530f23322d360ddf8944f08d468c836f1b1))
  * phoenix_live_view 0.1.0 (ref c7ea73b)
* NodeJS version (node -v): v11.11.0
* NPM version (npm -v): 6.7.0
* Operating system: MacOS 10.14 (Mojave)

### Actual behavior

In an app I'm working on, I have a form that has two different submit buttons:

```
<%= submit "Do Thing A", name: "thing_to_do", value: "a" %>
<%= submit "Do Thing B"", name: "thing_to_do", value: "b" %>
```

This submits to a normal controller, and the params tell me which button was clicked:

```
"thing_to_do" => "a"
```

I also have a `phx_submit` form with two buttons:

```
<%= submit "Save", name: "submit_type", value: "save" %>
<%= submit "Delete", name: "submit_type", value: "delete" %>
```

When I click one of these, the params I get in my live view do not tell me which button was clicked; there is no `"submit_type"` param.

### Expected behavior

I expected the params given to the live view's `handle_event` to include the button value.

**Comment by nathanl** [comment]
FWIW, I also tried plopping in plain HTML inputs (not `<button>`s) like this:
```
  <input type="submit" name="submit_type" value="save">
  <input type="submit" name="submit_type" value="delete">
```
Clicking this submit did submit the form but also did not get the value to the live view.

**Comment by alexgaribay** [comment]
The `FormData` constructor in javascript does not keep track of the submitting element when used from Javascript. That means elements with `type="submit"` with a value attached will not be able to be submitted with the form over the socket currently.

**Comment by LostKobrakai** [comment]
What @alexgaribay said. Had to deal with the same problem in turbolinks as well to get it to submit via ajax. You can kinda hack around it by setting a hidden field on click of the submit button.

**Comment by nathanl** [comment]
Cool, thanks for responding, @alexgaribay and @LostKobrakai. Maybe this issue will be useful for others who are confused in the future.
