### ISSUE TITLE
TypeError when clicking a live link prior to connection

### ISSUE THREAD

**Issue by rockwood** [phoenixframework/phoenix_live_view#1845]
### Environment

* Elixir version (elixir -v): **Elixir 1.13.1 (compiled with Erlang/OTP 24)**
* Phoenix version (mix deps): **1.6.6**
* Phoenix LiveView version (mix deps): **0.17.6**
* Operating system: **MacOS 11.6.2**
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, Edge, Safari, FF
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

Clicking a link (with data-phx-patch) causes a type error if clicked prior to a connection being established. Subsequent link clicks have no effect.

TypeError: Cannot read properties of undefined (reading 'receive')

### Expected behavior

The link click should fall back to the default browser behavior

### Possible Cause

It appears the issue stems from `pushWithReply` prematurely returning undefined.

https://github.com/phoenixframework/phoenix_live_view/blob/53bb1c5a1af8a5f3e033bf97f117291907dbae73/assets/js/phoenix_live_view/view.js#L1016

**Comment by chrismccord** [comment]
We only bind click events until after we have connected, so I'm not sure how this code could be encountered. Are you absolutely sure you're running the 0.17.6 phoenix_live_view.js client? Thanks!

**Comment by rockwood** [comment]
Thanks @chrismccord!

❤️  ❤️  ❤️  ❤️  ❤️
