### ISSUE TITLE
"no component for CID X" with async updates to the DOM

### ISSUE THREAD

**Issue by RealVidy** [phoenixframework/phoenix_live_view#1848]
### Environment

* Elixir version (elixir -v): 1.13
* Phoenix version (mix deps): 1.6.6
* Phoenix LiveView version (mix deps): 0.16.4
* Surface: 0.6.1
* Operating system: Mac OS Monterey
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, Brave, Safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

My users have always told me that the UI sometimes freezes and I had never seen it until I started adding some delay in my requests with `enableLatencySim`. Now, if I click on buttons that perform updates to the DOM fast enough (i.e. not that fast), I get "no component for CID" errors, which indeed freezes the UI. A refresh fixes everything (which means the backend is doing just fine). There are always two errors:

```
utils.js:7 no component for CID XXX {1: {…}, 2: {…}, 3: {…}, <a lot of components>}
logError @ utils.js:7
recursiveCIDToString @ rendered.js:181
dynamicToBuffer @ rendered.js:172
toOutputBuffer @ rendered.js:152
recursiveToString @ rendered.js:42
recursiveCIDToString @ rendered.js:183
dynamicToBuffer @ rendered.js:172
comprehensionToBuffer @ rendered.js:164
toOutputBuffer @ rendered.js:147
dynamicToBuffer @ rendered.js:174
toOutputBuffer @ rendered.js:152
recursiveToString @ rendered.js:42
recursiveCIDToString @ rendered.js:183
dynamicToBuffer @ rendered.js:172
toOutputBuffer @ rendered.js:152
dynamicToBuffer @ rendered.js:174
toOutputBuffer @ rendered.js:152
dynamicToBuffer @ rendered.js:174
toOutputBuffer @ rendered.js:152
recursiveToString @ rendered.js:42
toString @ rendered.js:36
(anonymous) @ view.js:465
time @ live_socket.js:208
renderContainer @ view.js:460
(anonymous) @ view.js:449
time @ live_socket.js:208
update @ view.js:448
(anonymous) @ view.js:521
applyDiff @ view.js:218
(anonymous) @ view.js:521
(anonymous) @ live_socket.js:229
trigger @ channel.js:278
(anonymous) @ socket.js:510
decode @ serializer.js:25
onConnMessage @ socket.js:497
conn.onmessage @ socket.js:222
```

```
rendered.js:147 Uncaught TypeError: Cannot read properties of undefined (reading 'd')
    at Rendered.toOutputBuffer (rendered.js:147:8)
    at Rendered.recursiveToString (rendered.js:42:10)
    at Rendered.recursiveCIDToString (rendered.js:183:31)
    at Rendered.dynamicToBuffer (rendered.js:172:29)
    at Rendered.toOutputBuffer (rendered.js:152:12)
    at Rendered.recursiveToString (rendered.js:42:10)
    at Rendered.recursiveCIDToString (rendered.js:183:31)
    at Rendered.dynamicToBuffer (rendered.js:172:29)
    at Rendered.comprehensionToBuffer (rendered.js:164:14)
    at Rendered.toOutputBuffer (rendered.js:147:41)
toOutputBuffer @ rendered.js:147
recursiveToString @ rendered.js:42
recursiveCIDToString @ rendered.js:183
dynamicToBuffer @ rendered.js:172
toOutputBuffer @ rendered.js:152
recursiveToString @ rendered.js:42
recursiveCIDToString @ rendered.js:183
dynamicToBuffer @ rendered.js:172
comprehensionToBuffer @ rendered.js:164
toOutputBuffer @ rendered.js:147
dynamicToBuffer @ rendered.js:174
toOutputBuffer @ rendered.js:152
recursiveToString @ rendered.js:42
recursiveCIDToString @ rendered.js:183
dynamicToBuffer @ rendered.js:172
toOutputBuffer @ rendered.js:152
dynamicToBuffer @ rendered.js:174
toOutputBuffer @ rendered.js:152
dynamicToBuffer @ rendered.js:174
toOutputBuffer @ rendered.js:152
recursiveToString @ rendered.js:42
toString @ rendered.js:36
(anonymous) @ view.js:465
time @ live_socket.js:208
renderContainer @ view.js:460
(anonymous) @ view.js:449
time @ live_socket.js:208
update @ view.js:448
(anonymous) @ view.js:521
applyDiff @ view.js:218
(anonymous) @ view.js:521
(anonymous) @ live_socket.js:229
trigger @ channel.js:278
(anonymous) @ socket.js:510
decode @ serializer.js:25
onConnMessage @ socket.js:497
conn.onmessage @ socket.js:222
```

My Liveview has a lot of small components (buttons, images, tooltips, tooltips on images on buttons, etc) and all of these get updated quite often asynchronously (as in, I click on a button to send an event to my Liveview which sends a :noreply and updates assigns soon after). Most of these are displayed from within for comprehensions (the ones provided by Surface with `{#for}`). All of these images and buttons are Surface LiveComponents.

Upon investigating, I have come to realize that the component that is causing the error has in fact been deleted one or two updates prior and Liveview's client doesn't seem to be aware of it (yet?). If I inject some code in the failing functions to return early when a component doesn't exist, things work fine.

I am guessing the asynchronous nature of my updates might be to blame? I realize it might be difficult to know what's wrong here so if you could let me know how I can help investigate, that'd be great. I could try to reproduce the issue on a sample app (but that's quite a bit of work so I'd rather avoid it at first).

I have tested this on phoenix_live_view 0.17.6 too and I see the same behavior.

**Comment by kuon** [comment]
We have the same issue when the components we add/remove are inside tables. If we remove the `<table>` elements, the issue does not occur.

I tried to produce a minimal example, but I cannot reproduce the issue by itself.

I suspect there is a sync problem caused by special handling of table by the DOM which might defer the element. Or maybe we have an invalid table structure at some point during the update, and the HTML engine removes them.

**Comment by josevalim** [comment]
Please double check if the elements you are inserting in the table are actually valid. If you insert invalid elements, they may be moved out, which can break things.

**Comment by kuon** [comment]
If I remove the `id` attribute from the `tr` the issue does not occur. I realize now that the first `tr` is rendered in B via path A->B->C (where ABC are components) and when I change an option, it is rendered in D via A->D->C.

Ensuring that different component do not use the same ID seems to fix the problem. But I do not have the problem without table.

**Comment by chrismccord** [comment]
If you're able to put together a reproducible example, please let us know. Thanks!

**Comment by kuon** [comment]
I was not able to reproduce the issue in a minimal example, I just use `display: table;` on `<div>` which never had this issue.
