### ISSUE TITLE
Live view re-mounts in its initial state during a vanilla form submit, causing a flash of old content

### ISSUE THREAD

**Issue by jwietelmann** [phoenixframework/phoenix_live_view#185]
Basically what's happening is that when I hit the submit button, I'm seeing the view's initially-rendered state for a second while I'm waiting for the server's HTTP response.

### Environment

* Elixir version (elixir -v): Erlang/OTP 21 [erts-10.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] / Elixir 1.8.1 (compiled with Erlang/OTP 20)
* Phoenix version (mix deps): locked at 1.4.3 (phoenix) 8eed4a64
* NodeJS version (node -v): v11.9.0
* NPM version (npm -v): 6.5.0
* Operating system: OS X

`phoenix_live_view` commit hash: `c7ea73ba9223e2cf285fb970cd9090f92183ed80` 

### Actual behavior

I have a `PUT` form (not sure if that part's relevant) that uses `:phx_change` for real-time validation but does not use `:phx_submit`. Submitting goes to a regular controller action. It re-renders the live view on failure and redirects on success.

* I change an input to an invalid value.
* The live view updates with the error message. (Good.)
* I submit the form.
* The controller renders the page again with errors. (Good.)
* I fix the invalid input.
* The live view updates and clears the error message. (Good.)
* I submit the form.
* While I'm waiting for the server to respond, the live view re-mounts and momentarily displays the invalid input and error message from the last `live_render`. (Bad.)

### Expected behavior

The live view does not re-mount when the form is submitted.

**Comment by philipgiuliani** [comment]
We also see this problem in our form. We use `phx_submit` though. After saving we are using `{:stop, redirect(..)}`.

While the browser performs the redirect, the initial state of the form is visible.

**Comment by philipgiuliani** [comment]
We still have this issue, and it's very annoying. Is there any workaround?

**Comment by chrismccord** [comment]
> It re-renders the live view on failure and redirects on success.

If you are relying on a regular controller update which re-live_render's from the controller, you should instead use phx-submit for the LV submission. For the case of using phi-submit, can you provide a minimal LV example that reproduces this issue? Thanks!

**Comment by jwietelmann** [comment]
> If you are relying on a regular controller update which re-live_render's from the controller, you should instead use phx-submit for the LV submission.

I feel like you may be missing the point. The re-`live_render` only happens for the error condition, and in this case it doesn't cause a problem. (Maybe that's only incidental to the UI that it doesn't look like a problem. It was months ago that I was fighting with this. Who knows.) The problem I _know_ involves making a regular request to another URL, which in turn redirects.

I can't work up an example right at this moment to _really_ prove it, but I suspect that your suggested "don't do that; do this" only sort of happens to be arguably workable for the particular scenario I reported. I _suspect_ that certain types request (at least `POST`), made from within the LiveView, if they redirect, will cause the LiveView to re-mount on redirect.

So let's say you have a dynamic list of items in a LiveView, and a form to add a new one by just entering its name, after which you'll be redirected to another page where you can optionally put in more details. I hypothesize that submitting this form with valid data will cause a re-mount and a flash of initial state until the redirect completes.

**Comment by Awlexus** [comment]
I've updated the [repo](https://github.com/Awlexus/Buggy-project) I used to showcase another bug. 

I set [`phx_submit: :save` in the form](https://github.com/Awlexus/Buggy-project/blob/master/lib/buggy_project_web/live/form2.ex#L19) and [redirect to a normal controller on submit](https://github.com/Awlexus/Buggy-project/blob/master/lib/buggy_project_web/live/form2.ex#L38-L45). The controller waits 5 seconds before rendering the page and during that time you can see the empty form. The same happened when I didn't set `:phx_submit` and directly send a POST request. 

This is the output of the process
```
[info] GET /form2
[debug] Processing with Phoenix.LiveView.Plug.Elixir.BuggyProjectWeb.Form2/2
  Parameters: %{}
  Pipelines: [:browser]
[debug] Mounting
[info] Sent 200 in 962µs
[info] CONNECTED TO Phoenix.LiveView.Socket in 296µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Connect Info: %{}
  Parameters: %{"vsn" => "2.0.0"}
[debug] Mounting
[debug] Params: %{"name" => "a"}
[debug] Params: %{"name" => "as"}
[debug] Params: %{"name" => "asd"}
[debug] Params: %{"name" => "asdf"}
[debug] Save
[info] GET /delayed
[debug] Processing with BuggyProjectWeb.PageController.index_with_delay/2
  Parameters: %{}
  Pipelines: [:browser]
[info] CONNECTED TO Phoenix.LiveView.Socket in 266µs # <- The liveview get's remounted at this point
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Connect Info: %{}
  Parameters: %{"vsn" => "2.0.0"}
[debug] Mounting
[info] Sent 200 in 5001ms
[info] CONNECTED TO Phoenix.LiveView.Socket in 338µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Connect Info: %{}
  Parameters: %{"vsn" => "2.0.0"}
```

**Comment by chrismccord** [comment]
I'm unable to recreate this on master in chrome, safari, and Firefox. I posted to a regular controller, which sleeps for 15s and my LV controlled form never remounted or reset. Please try master and let us know if you still have issues. If you are able to recreate this, a minimal LiveView + template would  be very helpful. Thanks!

**Comment by chrismccord** [comment]
I am also unable to recreate with the phx-submit => latent controller redirect approach

**Comment by philipgiuliani** [comment]
Hi Chris,
we are still experiencing the problem. I also updated the JS dependencies.  Did you take a look at the given example of Awlexus: https://github.com/Awlexus/Buggy-project ? You have to update the `phoenix_live_view` dependency there.

**Comment by chrismccord** [comment]
When you updated, did you also blow away and reinstall npm deps?

**Comment by philipgiuliani** [comment]
Yes. I tested it after `(cd assets && npm install --force phoenix_live_view)`, and I also tried removing the `node_modules` folder completely.

**Comment by tmpduarte** [comment]
Hi @chrismccord we also have a similar issue in one of our projects.

After researching the internet a bit, me and @dfalmeida ended up here and have cloned the [repository]( https://github.com/Awlexus/Buggy-project) from @philipgiuliani and we can reproduce the issue on chrome & firefox:

```
Go to localhost:4000/form2
Type something. Just change the formular a bit
Submit the form
A post request will be sent to /delayed, which just renders the indexpage after 5 seconds. While waiting you should see the empty form.
```

**Comment by chrismccord** [comment]
can you try latest master? Failing that, you can add a phx-hook which on form submit, calls `liveSocket.disconnect()`

**Comment by tmpduarte** [comment]
thank you very much @chrismccord! Tried both solutions and they both work 🙏🏼

We tried @philipgiuliani project with [this commit](https://github.com/phoenixframework/phoenix_live_view/commit/c73010597ee12c463e44d190714778a16607a9b5) and the reported bug is present. When we forced mix to fetch master ([this commit](https://github.com/phoenixframework/phoenix_live_view/commit/d74226987dae3f60f7f01b20b4d12e2aa14a518a)) we could not reproduce the bug.

When is it expected that the code in the master branch is released?

p.s.: We tried the `liveSocket.disconnect()` solution in a current project we have under development and it also worked. Can help  those who can't migrate right now.

**Comment by DavidVII** [comment]
This is still happening for me on 0.8.1. Adding a hook to disconnect from the socket does the trick, but that doesn't seem to be fixing the underlying issue.

I was previously *not* redirecting on save and was dealing with this issue by assigning the socket with an updated changeset after my resource was saved. This makes sense because when you're responding with `{:noreply, socket}` it's clear that the changeset wasn't updated and therefore re-rendering with the previous value. However, there doesn't seem to be a way to update the changeset when redirecting. I've tried assigning an updated changeset before redirecting, but still no dice.

I'm happy to jump on a screen share and share my code.

**Comment by josevalim** [comment]
Hi @DavidVII, thanks for the offer but unfortunately we have limited time. The best would be if someone could isolate those errors into a sample application that we can take a look at. Thanks!
