### ISSUE TITLE
_target param is not sent when using JS.push on phx-change/phx-submit

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix_live_view#1850]

**Comment by dvic** [comment]
I encountered this issue as well: an upload form event was going to the liveview instead of the component. A workaround until this is fixed is to explicitly set the target on the form, using `phx-target={@myself}`.

**Comment by SteffenDE** [comment]
I think this was fixed via https://github.com/phoenixframework/phoenix_live_view/commit/2d5381834951c417107a3e6eba43c6a487e74afd
