### ISSUE TITLE
Liveview infinite reloading due to websocket unable to connect

### ISSUE THREAD

**Issue by nolman** [phoenixframework/phoenix_live_view#1851]
### Environment

* Elixir version (elixir -v): 1.12.3
* Phoenix version (mix deps): 1.6.6
* Phoenix LiveView version (mix deps): 0.17.6
* Operating system: iOS 15.1.1
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, Safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes (I nuked the build cache in heroku - it's still happening however only for one iPhone)

### Actual behavior

The Liveview page is stuck in a reload loop because the websocket is unable to successfully connect - every 10 seconds it tries to reload the liveview page - this only happens on one iPhone and I am unable to reproduce on other devices however my other iOS devices have upgraded to 15.2.1

Putting on transport debugging for the live websocket I don't see the connection successfully being established on the server side. I do see successful connection messages for other clients.

Here is a screenshot of the log from the device, and the error in the console.

`
WebSocket connection to 'wss://www.joinsecondhome.com/live/websocket?_csrf_token=VhBLOlA7MQgmNQAcAGh7HC9cPXQZPzcw1WfX8UdcMQKpR_VkwloC4XUF&_track_static%5B0%5D=https%3A%2F%2Fwww.joinsecondhome.com%2Fassets%2Fapp-17849f135d07b559ce57b2f47bb1e5ae.css%3Fvsn%3Dd&_track_static%5B1%5D=https%3A%2F%2Fwww.joinsecondhome.com%2Fassets%2Fapp-f6519af39ee99a57251655a7408e2dd2.js%3Fvsn%3Dd&_mounts=0&vsn=2.0.0' failed: WebSocket is closed before the connection is established.
`

<img width="1153" alt="Screen Shot 2022-01-25 at 7 41 20 PM" src="https://user-images.githubusercontent.com/22493/151100384-8afc8f02-d7ed-478d-8319-a257005bddf0.png">
<img width="1153" alt="Screen Shot 2022-01-25 at 7 41 41 PM" src="https://user-images.githubusercontent.com/22493/151100395-aeefc396-d046-4e2f-b4cd-c772aac7848e.png">

### Expected behavior

Websocket able to establish connection.

**Comment by nolman** [comment]
Welp this is fixed after I upgraded the device in question to iOS 15.2.1

**Comment by nolman** [comment]
Maybe related: https://github.com/gorilla/websocket/issues/731 - it looks like some versions of Safari do not support compressed fragmented messages

**Comment by josevalim** [comment]
How did you enable compression? In the http/https configuration?

**Comment by nolman** [comment]
I didn't explicitly enable it - was just guessing at the cause, it could be a red herring.

**Comment by megalithic** [comment]
II've been experiencing this as well, in latest Brave and LiveView 0.17.7.

**Comment by zkat** [comment]
I was about to post that we could maybe work around this by using LongPoll, but that seems to be completely broken too. I currently have no apparent way to get my thing working for iOS safari users :(

**Comment by chrismccord** [comment]
I folks can provide more information around this, I would be able to take a closer look. It could be specific to your deployment configuration or the user's network. As it sits right now, I've spent a lot of time using latest LV on iOS and testing behavior coming out of a slept javascript thread and everything has worked appropriately.  Thanks!
