### ISSUE TITLE
Uploads using LiveView: content_type from UploadEntry is empty

### ISSUE THREAD

**Issue by silvagustin** [phoenixframework/phoenix_live_view#1852]
### Environment

* Elixir version (elixir -v): Elixir 1.13.1 (compiled with Erlang/OTP 24)
* Phoenix version (mix deps): 1.6.6
* Phoenix LiveView version (mix deps): 0.17.6
* Operating system: macOS Monterey
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, Safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes

### Actual behavior

Hi everyone. I'm working on file uploads using LiveView and when I've tried to upload an `.eot` file the `Phoenix.LiveView.UploadEntry` has an empty `content_type`. This only happens with this type of file, I've tried with other common file types (i.e. "jpg", "png") and the `content_type` wasn't empty.

I've found a workaround for this:
`if entry.client_type == "", do: MIME.from_path(entry.client_name), else: entry.client_type`

### Expected behavior

I'd expect not to use that line, but I don't mind. It's not like is something critical, just an improvement.

**Comment by mcrumm** [comment]
Hi @silvagustin, thanks for the issue! You should not rely on the file metadata sent by the clients. In fact, there is a large warning about doing so in the [HTML specification](https://html.spec.whatwg.org/#file-upload-state-(type=file)) (emphasis mine):

> Extensions tend to be ambiguous (e.g. there are an untold number of formats that use the `".dat"` extension, and users can typically quite easily rename their files to have a `".doc"` extension even if they are not Microsoft Word documents), and MIME types tend to be unreliable (e.g. many formats have no formally registered types, and many formats are in practice labeled using a number of different MIME types). Authors are reminded that, as usual, **data received from a client should be treated with caution, as it may not be in an expected format even if the user is not hostile and the user agent fully obeyed the `accept` attribute's requirements**.

That is why we do not validate or compute any values from the client metadata automatically, so a user-land workaround like you have shown is already the best way to handle this :) 

If you need robust validation of the uploaded file contents, I would recommend checking out a package like [GenMagic](https://github.com/evadne/gen_magic). Thanks!
