### ISSUE TITLE
HTML engine doesn't raise for invalid void tags 

### ISSUE THREAD

**Issue by feliperenan** [phoenixframework/phoenix_live_view#1853]
### Environment

* Elixir version (elixir -v): 1.13
* Phoenix version (mix deps): master
* Phoenix LiveView version (mix deps): master
* Operating system: MacOS

### Actual behavior

This is a valid HTML for HTML engine:

```html
<img %>
```

The HTML compiler will raise for normal  tags though:

```html
<section %>
```

Telling that it is not closed:

```
** (Phoenix.LiveView.HTMLTokenizer.ParseError) test/phoenix_live_view/html_engine_test.exs:1:2: end of template reached without closing tag for <section>
```

### Expected behaviour

It would be nice if the HTML compiler should raise an error for void tags that are not being closed correctly.

**Comment by feliperenan** [comment]
@josevalim let me know if that is indeed an issue. I'm happy to work on it if that is the case :)

**Comment by josevalim** [comment]
There is no bug here. % is a valid attriubute name according to the spec:

> attribute names must consist of one or more characters other than the space characters, U+0000 NULL, """, "'", ">", "/", "=", the control characters, and any characters that are not defined by Unicode.

Therefore, `%>` is valid unless it is closing a previous `<%`.

**Comment by feliperenan** [comment]
Ooh. I thought it as an issue 🙈

I will have to handle such case in the formatter then.

Thanks
