### ISSUE TITLE
Heex Parser Error on  left angle bracket `<` in `for` loop condition expression

### ISSUE THREAD

**Issue by matthewadowns** [phoenixframework/phoenix_live_view#1854]
### Environment

* Elixir version (elixir -v): `Elixir 1.13.2 (compiled with Erlang/OTP 24)`
  Erlang/OTP 24 [erts-12.0.3] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit]
* Phoenix version (mix deps): `1.6.6`
* Phoenix LiveView version (mix deps): `0.16.4`
* Operating system: macOS 11.6.1
* Browsers you attempted to reproduce this bug on (the more the merrier):  N/A - compilation error
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

I have a `.html.heex` layout template with a `<script>` tag that contains a `for` loop, that contains the common `i < foo.length` comparison.

The heex tokenizer wants to treat the the `<` as the start of an Elixir (or HTML?) tag, rather than recognize that it's part of a JavaScript expression.

I get the following error, which seems to indicate that it's expecting an Elixir token, rather than recognizing it as JS:

```sh
(Phoenix.LiveView.HTMLTokenizer.ParseError) invalid attribute value after `=`. 
Expected either a value between quotes (such as "value" or 'value') or an Elixir 
expression between curly brackets (such as `{expr}`)

Stacktrace:
  │ (phoenix_live_view 0.16.4) lib/phoenix_live_view/html_tokenizer.ex:340: Phoenix.LiveView.HTMLTokenizer.handle_attr_value_begin/5
  │ (phoenix_live_view 0.16.4) lib/phoenix_live_view/html_engine.ex:90: Phoenix.LiveView.HTMLEngine.handle_text/3
  │ (eex 1.13.2) lib/eex/compiler.ex:49: EEx.Compiler.generate_buffer/4
  │ (phoenix_view 1.1.0) lib/phoenix/template.ex:410: Phoenix.Template.compile/3
  │ (phoenix_view 1.1.0) lib/phoenix/template.ex:196: anonymous fn/4 in Phoenix.Template."MACRO-__before_compile__"/2
  │ (elixir 1.13.2) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
  │ (phoenix_view 1.1.0) expanding macro: Phoenix.Template.__before_compile__/1
  │ lib/veeps_web/views/layout_view.ex:1: VeepsWeb.LayoutView (module)Elixir
```

I tried the same JS snippet in a `.ex` file with `~L` and `~E` -- no parser errors there, but the same issue was observed when using `~H`.

### Expected behavior

Recognize that the `<` in a `for` loop inside a `<script>` tag is JavaScript, not the start of an Elixir or HTML tag: 

```js
for(var e = 0; e < myObj.subObj.length; e++) {
``` 

### Workaround

I am able to get passed this by simply reversing the order of the variables in the expression and changing the operator to `>`.

The error is resolved by changing the above to:

```js
for(var e = 0; myObj.subObj.length > e; e++)
```

**Comment by josevalim** [comment]
This has been fixed in more recent LV versions. Please update! :)
