### ISSUE TITLE
[Proposal] What about having post-hooks?

### ISSUE THREAD

**Issue by nallwhy** [phoenixframework/phoenix_live_view#1855]
I love to use hooks on Phoenix LiveView, but sometimes I want to add hooks triggered after `handle_params/3`, `handle_event/3`, and `handle_info/3`.

Example

```elixir
def mount(_params, _session, socket) do
  socket =
    socket
    |> attach_hook(:my_hook, :handle_event, :pre, fn ->
      "This is a pre-hook for handle_event/3" |> IO.inspect()
    end)
    |> attach_hook(:my_hook, :handle_event, :post, fn ->
      "This is a post-hook for handle_event/3" |> IO.inspect()
    end)

  {:ok, socket}
end
```

**Comment by chrismccord** [comment]
Please send proposal discussions to the forums as we reserve the issue tracker for issues and active feature development. Over on the other side it would also be helpful to outline the usecases you have. Thanks!

**Comment by nallwhy** [comment]
I see. Thanks!
