### ISSUE TITLE
Missing opening tag error when using `if` and  closing tag is not present in same `if` block

### ISSUE THREAD

**Issue by lkarthee** [phoenixframework/phoenix_live_view#1856]
### Environment

* Elixir version (elixir -v): Elixir 1.13.0 (compiled with Erlang/OTP 22)
* Phoenix version (mix deps): "~> 1.6.4"
* Phoenix LiveView version (mix deps): "~> 0.17.5"
* Operating system: mac 12.0.1
* Browsers you attempted to reproduce this bug on (the more the merrier): 
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: No

### Actual behavior

If a tag is wrapped in `if` and it is not closed immediately - it is throwing compiler error. Below template should produces always valid html with matching closing tags

``` elixir
def div_wrapper_bug(assigns) do
    assigns = assign_if_nil(assigns, :wrapper_class, nil)
    ~H"""
    <%= if @wrapper_class do %>
    <div class={@wrapper_class}> <!-- opening tag -->
    <% end %>
      <%= render_slot(@inner_block) %>
    <%= if @wrapper_class do %>
    </div> <!-- closing tag -->
    <% end %>
    """
  end
```

```
Compiling 1 file (.ex)

== Compilation error in file lib/indy_bootstrap/bootstrap/form.ex ==
** (Phoenix.LiveView.HTMLTokenizer.ParseError) lib/indy_bootstrap/bootstrap/form.ex:177:5: missing opening tag for </div>
    (phoenix_live_view 0.17.5) lib/phoenix_live_view/html_engine.ex:227: Phoenix.LiveView.HTMLEngine.pop_tag!/2
    (phoenix_live_view 0.17.5) lib/phoenix_live_view/html_engine.ex:432: Phoenix.LiveView.HTMLEngine.handle_token/2
    (elixir 1.13.0) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix_live_view 0.17.5) lib/phoenix_live_view/html_engine.ex:86: Phoenix.LiveView.HTMLEngine.handle_end/1
    (eex 1.13.0) lib/eex/compiler.ex:191: EEx.Compiler.wrap_expr/5
    (eex 1.13.0) lib/eex/compiler.ex:140: EEx.Compiler.generate_buffer/4
    (eex 1.13.0) lib/eex/compiler.ex:82: EEx.Compiler.generate_buffer/4
    (phoenix_live_view 0.17.5) expanding macro: Phoenix.LiveView.Helpers.sigil_H/2
    (indy_bootstrap 0.1.0) lib/indy_bootstrap/bootstrap/form.ex:171: Indy.Bootstrap.Form.div_wrapper_bug/1
```
### Expected behavior

compile without errors.

**Comment by josevalim** [comment]
Yes, as the error message says, it is intentional. The goal of HEEx is to validate HTML and we can’t do that if you are generating tags dynamically.

**Comment by lkarthee** [comment]
I fail understand generating tags dynamically part - everything is inside the template. 

This works and even in this cases we are generating  tags dynamically.
```
<%= if @wrapper_class do %>
    <div class={@wrapper_class}>
       <%= render_slot(@inner_block) %>
    </div>
<% else %>
    <%= render_slot(@inner_block) %>
<% end %>
```
Do you mean to say that Heex html engine has limitations that it can only check for closing tag only inside a `if` block  ?

**Comment by lkarthee** [comment]
One solution might be escape blocks where you disable matching html closing tags due to Heex engine limitations?

It is a pretty common scenario to wrap things in a div or span or use a tag directly. Workaround is leading to duplication of code. What do suggest as solution for this scenario ?

``` html 
<!--  normal radio -->
<.bs_radio items={[{"phone", "Phone"}, {"email", "Email"}]} 
                   form={:user} field={:mode}>
</.bs_radio>
<!-- wrap in div>col something to generate grid -->
<.bs_radio wrapper_class="col-12" items={[{"phone", "Phone"}, {"email", "Email"}]} 
                   form={:user} field={:mode}>
</.bs_radio>
<!-- inline radio items need div to be wrapped for them to appear in single line -->
<.bs_radio inline items={[{"phone", "Phone"}, {"email", "Email"}]} 
                   form={:user} field={:mode}>
</.bs_radio>
```

``` elixir
def bs_radio(assigns) do
    assigns = create_id(assigns, "inp")
    items = 
      Enum.with_index(assigns.items, fn item, index ->
        id = "#{assigns.id}-#{index}"
        case item do
          {value, label, true} ->
            {value, label, id, [id: id, disabled: true]}

          {value, label, false} ->
            {value, label, id, [id: id]}

          {value, label} -> 
            {value, label, id, [id: id]}

          {value, true} ->
            {value, value, id, [id: id, disabled: true]}

          {value, false} ->
            {value, value, id, [id: id]}

          _ ->
            {item, item, id, [id: id]}
        end
      end)
    assigns = assign(assigns, :items, items)
    assigns = add_class(assigns, "form-check-input")
    extras = assigns_to_attributes(assigns, [:form, :for, :id, :items, :inline])
    assigns = assign(assigns, :extras, extras)
    assigns = assign_if_nil(assigns, :wrapper_class, nil)
    assigns = 
      case assigns[:inline] do
        nil ->
          assigns
          |> assign(:inline, false)
          |> assign(:form_check_class, "form-check")

        _ ->
          assign(assigns, :form_check_class, "form-check form-check-inline")
          
      end
    ~H"""
    <%= if @inline or @wrapper_class != nil do %>
    <div class={@wrapper_class}>
    <.bs_radio_core form={@form} field={@field} items={@items} extras={@extras} form_check_class={@form_check_class}></.bs_radio_core>
    </div>
    <% else %>
    <.bs_radio_core form={@form} field={@field} items={@items} extras={@extras} form_check_class={@form_check_class}></.bs_radio_core>
    <% end %>
    """
  end

# the following component is being written as a workaround for this bug.
  def bs_radio_core(assigns) do
    ~H"""
    <%= for {value, label, id, opts} <- @items do %>
    <div class={@form_check_class}>
      <%= radio_button(@form, @field, value, opts ++ @extras) %>
      <label class="form-check-label" for={id}><%= label %></label>
    </div>
    <% end %>
    """
  end
```

**Comment by lkarthee** [comment]
heex html engine considers this as valid and compiles without an issue.
``` elixir
  def div_wrapper_bug(assigns) do
    assigns = assign_if_nil(assigns, :wrapper_class, nil)
    ~H"""
    <%= if @wrapper_class do %>
    <div class={@wrapper_class}> <!-- this is never be closed-->
    <% end %>
      <%= render_slot(@inner_block) %>
    """
  end
```
Summary 
1) **Valid HTML produces compiler error :** The snippet in bug description I have provided always produces valid html - heex engine generates invalid html warning
2) **Invalid HTML does produces compiler error :** snippet about compiles and is rendered in page.
2) Templating engines are all about generating tags dynamically.
3) **Escape hatch :** Validating HTML is a legitimate goal - but when library cannot validate something 100% - its better  to provide some escape hatch. 
4) **Warning/Error Configuration :**  Validating html is more static analysis or linting - it is better to have configuration on how to treat certain kind of errors - should they produce warning or error.

I hope this bug will be reopened or at least  some issues are addressed.

**Comment by josevalim** [comment]
The escape hatch exists, you can render the tags dynamically:

    <%= raw "<div ...>" %>

    <%= raw "</div>" %>

What you can't do is render the tags statically and conditionally.

The invalid HTML not being caught is a bug though, I will take a look.

**Comment by josevalim** [comment]
> The invalid HTML not being caught is a bug though, I will take a look.

Fixed a month ago: https://github.com/phoenixframework/phoenix_live_view/commit/321d2ff2ca3860fb584769bf7fc59975f106a70e

**Comment by josevalim** [comment]
And, FWIW, your code would likely be better handled by using a function component:

```elixir
def maybe_div(assigns) do
  if assigns.wrapper_class do
    ~H"""
    <div class={@wrapper_class}><%= render_slot(@inner_block) %></div>
    """
  else
    ~H"""
    <%= render_slot(@inner_block) %>
    """
  end
end
```

and then:

```
  <.maybe_div wrapper_class={@class}>
    <%= for {value, label, id, opts} <- @items do %>
    <div class={@form_check_class}>
      <%= radio_button(@form, @field, value, opts ++ @extras) %>
      <label class="form-check-label" for={id}><%= label %></label>
    </div>
    <% end %>
  </.maybe_div>
```

Then the complexity and most of the duplication is moved out of the template. HEEx is more strict since HTML validation helps catch tons of bugs. At the same time, features like slots are also powerful to the point where having to generate tags dynamically are very rare.

**Comment by lkarthee** [comment]
Thank you @josevalim ,  should this be added in docs with example?

> What you can't do is render the tags statically and conditionally.

**Comment by josevalim** [comment]
Yes, we could, perhaps we already do. A PR is welcome!
