### ISSUE TITLE
TypeError: statics is undefined in comprehensionToBuffer

### ISSUE THREAD

**Issue by rktjmp** [phoenixframework/phoenix_live_view#1866]
### Environment

* Elixir version (elixir -v):
 
    Erlang/OTP 24 [erts-12.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit]
    Elixir 1.13.1 (compiled with Erlang/OTP 24)

* Phoenix version (mix deps): 1.6.6
* Phoenix LiveView version (mix deps): 0.17.6 (and [e94d145](https://github.com/phoenixframework/phoenix_live_view/commit/e94d145e6c611934c53f16699a393a90f4669443))
* Operating system: Linux
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox, Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

Under a particular combination of PubSub + nested Liveview, LV fails to apply DOM updates and raises `TypeError: statics is undefined` in `comprehensionToBuffer`.

See https://github.com/rktjmp/phx-pubsub-socket-bug for reproduction and more background

![image](https://user-images.githubusercontent.com/866010/152380742-5e1e352d-26ea-469f-8e9a-6251373eae26.png)

### Expected behavior

It does not raise `Typeerror: statics is undefined"

**Comment by tmjoen** [comment]
To anyone else hitting this after upgrading to 0.17.7 — make sure that your LV JS is also upgraded. I got this error when my LV JS was not in sync with my LV version. Not saying that is the case with OP, but it was for me :)
