### ISSUE TITLE
EACCES: permission denied

### ISSUE THREAD

**Issue by jc00ke** [phoenixframework/phoenix_live_view#187]
### Environment

* Elixir version (elixir -v): 1.8.1
* Phoenix version (mix deps): 1.4.3
* NodeJS version (node -v): 11.13.0
* yarn version (yarn -v): 0.27.5
* Operating system: Heroku-18 stack

My apologies if this is not the right time/place to report this, but I'm seeing buildpack compilation errors on Heroku CI only after adding `phoenix_live_view` to our project. If I run again without the cache, then it tends to work.

### Actual behavior

```
       * MIX_ENV=test

-----> Installing binaries

       Using cached node 11.13.0...

       Installing Node 11.13.0...

       Using default npm version

Downloading and installing yarn 0.27.5...

Installed yarn 0.27.5

-----> Building dependencies

       Installing and caching node modules

yarn install v0.27.5

(node:778) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

[1/4] Resolving packages...

[2/4] Fetching packages...

warning fsevents@1.2.4: The platform "linux" is incompatible with this module.

info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.

warning fsevents@1.2.6: The platform "linux" is incompatible with this module.

info "fsevents@1.2.6" is an optional dependency and failed compatibility check. Excluding it from installation.

[3/4] Linking dependencies...

error An unexpected error occurred: "EACCES: permission denied, open '/app/assets/node_modules/phoenix_live_view/.git/objects/pack/pack-15b0adf2c2385498a45c5a191214c7f565151a9a.idx'".

info If you think this is a bug, please open a bug report with the information provided in "/app/assets/yarn-error.log".

info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

### Expected behavior

```
       * MIX_ENV=test

-----> Installing binaries

Resolving node version 11.13.0...

Downloading and installing node 11.13.0...

       Installing Node 11.13.0...

       Using default npm version

Downloading and installing yarn 0.27.5...

Installed yarn 0.27.5

-----> Building dependencies

       Installing and caching node modules

yarn install v0.27.5

(node:1125) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

[1/4] Resolving packages...

[2/4] Fetching packages...

warning fsevents@1.2.4: The platform "linux" is incompatible with this module.

info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.

warning fsevents@1.2.6: The platform "linux" is incompatible with this module.

info "fsevents@1.2.6" is an optional dependency and failed compatibility check. Excluding it from installation.

[3/4] Linking dependencies...

[4/4] Building fresh packages...

Done in 61.55s.
```

One thing that stuck out to me is `npm install --prefix assets`. Is it OK to use `yarn`? If not, is the `--prefix assets` necessary?

If this isn't the right place for this, that's cool, but I thought I'd start here. Can always open an issue on another repo if appropriate.

Edit: #100 was just suggested by GH issues, so I'll consider adding those assets directly.

**Comment by chrismccord** [comment]
This doesn't appear to be anything on our side. I'm not sure how yarn handles git deps, but does npm work fine for you? The `--prefix assets` is necessary if you don't `cd assets`. Thanks!

**Comment by jc00ke** [comment]
I had not see this issue locally, but I'll see if I can recreate on Heroku with `npm`.

**Comment by cpjolicoeur** [comment]
Seeing the same here.  We have our `node_modules` at the root of our repo, so `cd` or `--prefix` is not the issue for us.  Been working around it by just placing the JS assets statically into our project, but am looking forward to when live view has it's own hex package.

**Comment by cpjolicoeur** [comment]
`npm` just symlinks when using `file://` path packages, where `yarn` copies the files directly.

**Comment by chrismccord** [comment]
This is a yarn + Heroku issues, so not much to do on our side. It will become a package once we close out some outstanding issues and button up a couple features. In the meantime you could vendor your js as needed. Hope that helps!
