### ISSUE TITLE
LiveView not work when set container to tr

### ISSUE THREAD

**Issue by KeepZen** [phoenixframework/phoenix_live_view#1888]
### Environment

* Elixir version (elixir -v): Elixir 1.13.0
* Phoenix version (mix deps): ~> 1.6.4
* Phoenix LiveView version (mix deps): ~> 0.17.5
* Operating system: Win10
* Browsers you attempted to reproduce this bug on (the more the merrier): Microsoft Edge  98.0.1108.50
* Does the problem persist after removing "assets/node_modules" and trying again? Yes

### Actual behavior
I set the live container at <app>_web.ex file, such as:
```
def live_view do
    quote do
      use Phoenix.LiveView,
        # :td for tag <td> if <td> out side the <table>
        # browser will ignore it as it is not exist.
        container: {:tr, class: ""},
        layout: {LifeNoteWeb.LayoutView, "live.html"}

      unquote(view_helpers())
    end
  end
```
If there is not set the container, the default is div tag it have a long phx-session-data attribute.
And I find LiveView document example use the  `tr` tag, I try it , and find tr will not show when I inspect in browser,
but still in the source. 

Then the bad thing happend, the liveview socket `/live/websocket?_csrcf=xxx` not connection to the server,
only  `phoenix/websocke?vsn=2.0.0" connection.

### Expected behavior
I want the liveview work, we the container is `tr`.

**Comment by josevalim** [comment]
Can you try returning container on mount instead?

    def mount(_session, _params, socket) do
      {:ok, socket, container: {:tr, class: ""}}
    end

**Comment by KeepZen** [comment]
Now  expected keys return by `mount` are ` [:temporary_assigns, :layout]`.  

But I think it not about the expected keys returned by mount. It about the way of the JS code how to find the containder.
Phoenix JS use the `phx-session-data` attribue selector  to find the container, but `tr` do not exitst in the DOM.

I thought `container: {:tr}` is the counterpart of  [React.Fragment](https://reactjs.org/docs/fragments.html), 
it worked at first look, untail I find the LiveView did not work.

**Comment by chrismccord** [comment]
`tr` shouldn't have a problem. Are you sure you're rendering your table rows inside of a `<tbody>` ?

**Comment by KeepZen** [comment]
No，I do not try render a table，I try to find counterpart of [React.Fragment](https://reactjs.org/docs/fragments.html), and I found in document liveview container is `tr`. I think there is some reason use it as the example. The I try it. 

My liveview didn't render to a table. And the parents note is not table or table body. `tr` outside the table environment will ignore by brower, I same way like the Fragment.

This is a wrong way to use lieview, not a bug.
I should close this issue.

**Comment by josevalim** [comment]
Oh, you don't need to set the container at all. If you don't set it, then it should use a `div` by default!
