### ISSUE TITLE
Browser support: version 0.17.5 not support in chrome <= 59

### ISSUE THREAD

**Issue by ottenkoop** [phoenixframework/phoenix_live_view#1889]
### Environment

* Elixir version (elixir -v):
1.13.1

* Phoenix version (mix deps):
1.5.9

* Phoenix LiveView version (mix deps):
 0.17.5
* Operating system:
Reproduced on windows 7.

* Browsers you attempted to reproduce this bug on (the more the merrier): 
All chrome versions < 60

* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:
Yes.

### Actual behavior
Javascript throwing errors on certain functions:

![image](https://user-images.githubusercontent.com/1642854/154014737-36411d81-29f2-4bc5-849c-45588a7a57f8.png)

Tried adding polyfills into the project:
https://github.com/phoenixframework/phoenix_live_view#browser-support

But no actual fix for it yet. 

### Expected behavior
JS picked up by actual polyfills.

Anyone has any suggestions?

**Comment by Gazler** [comment]
Could you try adding this to the esbuild script (in config/dev.exs)?

`esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --target=chrome58,firefox57,safari11,edge16 --watch)]}`

**Comment by chrismccord** [comment]
Please let us know if the targets do not work for you, but I don't believe there is anything for us to add on top. Thanks!
