### ISSUE TITLE
Calling render within comprehension, getting "(MatchError) no match of right hand side value: :comprehension"

### ISSUE THREAD

**Issue by moxley** [phoenixframework/phoenix_live_view#189]
### Environment

* Elixir version (elixir -v): 1.8.1
* Phoenix version (mix deps): 1.4.2 ef26978
* NodeJS version (node -v): 10.15.1
* NPM version (npm -v): 6.4.1
* Operating system: macOS 10.14.4

### Actual behavior

1. Load page successfully. Page's leex template contains:
```elixir
<%= for note <- @member.notes do %>
  <%= render("show_note.html", %{note: note, admin_member: @admin_member}) %>
<% end %>
```
2. Click button that causes `handle_event("delete_note", _value, socket)` on my Live module to be called. (note: other handle_event heads called will result in this same error)
3. handle_event updates member referenced above, and assigns updated member to existing key in `socket.assigns`.
4. Server logs the following:
```
[error] GenServer #PID<0.624.0> terminating
** (MatchError) no match of right hand side value: :comprehension
    (my_app) lib/my_web/templates/admin/member/show_note.html.leex:1: MyAppWeb.Admin.MemberView."show_note.html"/1
    (my_app) lib/my_web/templates/admin/member/show.html.leex:77: anonymous fn/3 in MyAppWeb.Admin.MemberView."show.html"/1
...
```
5. Page refreshes, and everything looks fine now.

### Expected behavior

* No error in the logs
* Page doesn't refresh
* Updated member is rendered on the page

### Workaround

I was able to work around this problem by rewriting the template code like this:

```elixir
<%=
admin_member = @admin_member
for note <- @member.notes do
%>
  <%= render("show_note.html", %{note: note, admin_member: admin_member}) %>
<% end %>
```

**Comment by albertosramires** [comment]
Having the same issue.

**Comment by josevalim** [comment]
I can't reproduce this error. Can someone please provide a minimal app that reproduces it? Thanks!

**Comment by josevalim** [comment]
Beautiful, thank you! :heart:
