### ISSUE TITLE
Improve error message on invalid conditional component slots

### ISSUE THREAD

**Issue by rafaeliga** [phoenixframework/phoenix_live_view#1892]
### Environment

* Elixir version (elixir -v): 1.13.2
* Phoenix version (mix deps): 1.6.6
* Phoenix LiveView version (mix deps): 0.17.7
* Operating system: macOS Monterey (12.1)
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

Error when using conditional slots:

**no case clause matching: %{file: "lib/phx_conditional_slots_example_web/templates/page/index.html.heex", root: nil, slots: [], stack: [substate: %{counter: {:atomics, #Reference<0.3277811488.2529034248.20745>}, dynamic: [], static: []}], subengine: Phoenix.LiveView.Engine, substate: %{counter: {:atomics, #Reference<0.3277811488.2529034248.20745>}, dynamic: [], static: ["\n "]}, tags: [{:tag_open, ":col", [{"let", {:expr, "user", %{column: 16, line: 3}}}, {"label", {:string, "Address", %{delimiter: 34}}}], %{column: 5, line: 3}}]}**

```
def table(assigns) do
    ~H"""
    <div class="table-responsive">
      <table class="table table-sm table-hover">
        <thead>
          <tr>
            <%= for col <- @col do %>
              <th><%= col.label %></th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <%= for row <- @rows do %>
            <tr>
              <%= for col <- @col do %>
                <td class={col[:class]}><%= render_slot(col, row) %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    """
  end
```

```
<PhxConditionalSlotsExample.Components.table rows={[%{name: "John", address: "Somewhere"}, %{name: "Jane", address: "Some place"}]}>
  <%= if true do %>
    <:col let={user} label="Address">
      <p><%= user.address %></p>
    </:col>
  <% end %>
</PhxConditionalSlotsExample.Components.table>
```

### Expected behavior

Error message

**invalid slot entry <:col>. A slot entry must be a direct child of a component**

If I remove the tag `<p>`, the error message changes to the `invalid slot`.

**Comment by josevalim** [comment]
You cannot have conditional slots. You can do this instead:

```elixir
    <:col let={user} label="Address" if={true}>
      <p><%= user.address %></p>
    </:col>
```

And render according to the `if` attribute.

**Comment by josevalim** [comment]
Sorry, I missed that. Thanks for following up. Reopening as we definitely need a better error message!
