### ISSUE TITLE
Unexpected error while invoking assign/3 inside function component

### ISSUE THREAD

**Issue by thiagomajesk** [phoenixframework/phoenix_live_view#1896]
Hello everyone! Just noticed this while testing a function component today with a coworker. Since I couldn't find any mentions about it on the [documentation](https://hexdocs.pm/phoenix_live_view/Phoenix.Component.html), it brought a little bit of confusion why it wouldn't work. Here's the situation...

Let's take this simple `icon` component as an example:

```elixir
defmodule Icons do
  use Phoenix.Component

  def icon(assigns) do
    extra = assigns_to_attributes(assigns)
    assigns = assign(assigns, :extra, extra)

    ~H"""
    <i class={"fa fa-#{assigns[:name]}"} {@extra}></i>
    """
  end
end
```

If we try to test this inside iex, like the documentation suggests we get the following error:

```elixir
iex> MyComponent.icon(%{name: "telescope"})                                           
** (ArgumentError) assign/3 expects a socket or an assigns map from a function component as first argument, got: %{name: "telescope"}
    (phoenix_live_view 0.17.5) lib/phoenix_live_view.ex:697: Phoenix.LiveView.assign/3
    (my_app 1.6.0) lib/my_app_web/components/icons.ex:15: MyComponent.icon/1
```

It's not immediately obvious why this fails, since we are in fact passing a map, as the error instructs us to. But upon further inspection, we can see that both [`assign/3`](https://github.com/phoenixframework/phoenix_live_view/blob/v0.17.7/lib/phoenix_live_view.ex#L753) and [`assign_new/3`](https://github.com/phoenixframework/phoenix_live_view/blob/v0.17.7/lib/phoenix_live_view.ex#L722) also need a `:__changed__` key in the map to match. 

Currently, the catch-all clause for both functions raises an error, but I think it would be better if instead of raising we assigned the `:__changed__` key to a default value. 

Perhaps something like this before the catch-all clause that raises:

```elixir
def assign(assigns, key, value) when is_map(assigns) do
  assign(Map.put_new(assigns, :__changed__, nil}) 
end
```

Right now, we need to call our function components outside the template scope like `MyComponent.icon(%{__changed__: nil, name: "telescope"}})` for it to work, which is kind of annoying and counter-intuitive, because we are not expecting to track any changes with it (we are not using live components btw).

**Comment by josevalim** [comment]
It is important for the `__changed__` key to be there, because otherwise we lose change tracking. Automatically adding a key can hide important bugs in user code that actually uses live tracking.

I don't think calling it directly is helpful either, because it will return a Rendered struct. Even without HEEx, when using EEx, the output was an IO list, which you would need to render it too. Your best option is to use something [Phoenix.LiveViewTest.render_component/2](https://github.com/phoenixframework/phoenix_live_view/blob/master/lib/phoenix_live_view/test/live_view_test.ex#L442) to render all of those cases for you.

**Comment by thiagomajesk** [comment]
Hey @josevalim, thanks for the reply...

> It is important for the __changed__ key to be there, because otherwise we lose change tracking. Automatically adding a key can hide important bugs in user code that actually uses live tracking.

I understand that the key `:__changed__` is mandatory because of LiveView, but since we can't call `assign/3` without it, why, can't we at least have it initialized beforehand so we have a 'consistent' API to deal with assigns? I'm not sure I follow what you mean by "hide important bugs in user code", could you elaborate? We already receive `%{__changed__: nil}` directly from the template when we are using plain function components without LiveView, so...

Besides that, the main use-case that concerns me is not even on the test side, it's on the refactoring process to use components. I'm working on a 2yo application and I'm constantly finding places where we have calls that used to do the job of components and now we need to refactor, for instance:

```elixir
def renders_title_with_icon(icon, type) do
  icon = case type do
    #:error -> get_icon(:error)
    :error -> Icons.icon(%{"error"}) 
  end
  
   content_tag(:div, [title, icon])
end

def get_icon(:error), do: content_tag(:i, nil, class: "fa fa-error")
```

Of course, this is a very generic and simplistic example, but it's impractical to refactor huge chunks of code to accommodate this particular implementation detail. That's why we have been "faking" the map blueprint to call it inside those helpers. 

Again, those assigns are exactly what is already built by Phoenix, all I'm saying is that I'm not seeing a reason for us not to be able to pass assigns directly to the components invocation (be it a shortcut or syntax sugar if you will); which is consistent with the behavior we get when we call those functions from templates.

**Comment by chrismccord** [comment]
`render_component/2` is exactly how to test the function components without worrying about internal details :)

**Comment by josevalim** [comment]
As said previously, we should not automatically set `__changed__` on assign/assign_new. This will actually hide bugs in actual code. Because now someone can do:

```elixir
<%= icon(%{foo: foo}) %>
```

Instead of:

```elixir
<.icon foo={@foo} />
```

And that's going to lead to worst performance, losing change tracking, etc. Unless there is a proposal that addresses how exactly we can keep those properties while adding `__changed__` at the same time, we won't add the requested behaviour. The reason why `Phoenix.LiveViewTest` adds it is exactly because it is made clear the scenario is for "testing".

Similarly, Phoenix.LiveViewTest is not only for unit testing. It is also perfectly fine to "test" things from IEx.

**Comment by thiagomajesk** [comment]
Hey @josevalim! Thanks again for your time... It seems to me that this is starting to get cyclic. You said "this will hide bugs in actual code" but it seems that the argument being made is about live components... Please correct me if I'm wrong, but the "worst performance" in that case would be related to losing the aforementioned change tracking, right!? If that's the case, how would that still be relevant for the scenario I'm describing? Since I'm not using live components (hence don't want to track changes) aren't those examples basically equivalent? 

Like I said before, Phoenix does return `%{__changed__: nil}`, if I do `<.icon foo={@foo} />`, so why can't I `<%= icon(%{foo: foo}) %>` if I'm not meaning to track any changes as well? It seems consistent to me with the language since it's just a function call. IMHO, seems more obvious to allow that instead of raising `assign/3 expects a socket or an assigns map from a function component as first argument, got: %{name: "telescope"}`... Or perhaps I'm reading "assigns map" wrong in this sentence, should "assigns map" be considered a map that always has `:__changed__` in it?  

I haven't found documentation to support what you just explained nor does the API message seem to help you understand where's the problem. 

> Similarly, Phoenix.LiveViewTest is not only for unit testing. It is also perfectly fine for "testing" things from IEx

What about the use case I mentioned before, what would be the option for reusing function components in places where we currently have helpers in place? Is it out of scope?

> That's the "syntax sugar" you are asking for and two maintainers have already told you so. :)

I think that maybe you missed the point, if you check the title of the issue, you'll see that I'm raising my concern from a usability standpoint first. That's why I tried to explain the whole situation before actually making a suggestion (which wasn't in the first draft of the issue, to begin with), perhaps my mistake was thinking that I could make a contribution (considering your responses, it seems that's the case at least). Nevertheless, I'm not exactly **only** making the case for creating a syntax sugar that would allow this to happen, but rather questioning why it isn't allowed when it "seems" it would be reasonable to be - I mean, considering it's just a function. 

Perhaps we could both agree that even though this could be extremely obvious for **two** maintainers, it's not immediately obvious for someone using it? All I ask is a little bit of consideration on the 80% of the issue, instead of focusing on the other 20% which was meant as a proactive appendix to a possible solution. Maybe what should be done is actually improve the error message!? I don't know, that's why I'm trying to report it - and miserably failing apparently.

**Comment by josevalim** [comment]
> You said "this will hide bugs in actual code" but it seems that the argument being made is about live components

No. What I said is correct. It applies to any component within a LiveView. We provide diff tracking even to regular components, which was one of the big reasons for introducing them. You are making me confirm my answer for the third time! :D

In any case, I have already fixed the error message, I took that as TODO as soon as I saw the issue. My reply to you was about making super clear that **you should not be setting the `__changed__` assign manually**. If you do **bad things will happen!**. Use the proper APIs instead.

**Comment by thiagomajesk** [comment]
Ok @josevalim, sorry for taking up your time. Have a nice day 👍.
