### ISSUE TITLE
live_img_preview causes remnant <img> element after entry removal

### ISSUE THREAD

**Issue by bultas** [phoenixframework/phoenix_live_view#1897]
### Environment

* Elixir version (elixir -v): 1.13.2
* Phoenix version (mix deps): 1.6.6
* Phoenix LiveView version (mix deps): 0.17.7
* Operating system: MacOS Monterey
* Browsers you attempted to reproduce this bug on (the more the merrier):  chrome, firefox, safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

When I use `live_img_preview(entry)` helper inside the `<.form>` (to render preview of image to be uploaded) and then I remove it from the entries, it will cause DOM structure with remnant img tag of the entry which has been removed.

https://user-images.githubusercontent.com/545385/155141915-664475a0-a069-4e4d-ab2d-0ac59dee92f1.mp4

### Expected behavior

Same as if I use `live_img_preview(entry)` outside the `<form>` element. So if I remove entry, it will remove all entry preview elements from the DOM without problem.

**Comment by bultas** [comment]
Yes, I am getting `Multiple IDs detected: phx-preview-0. Ensure unique element ids.`

..aha, so the DOM hiearchy is not the problem at all.. the problem is using the `live_img_preview` with same entry twice

**Comment by chrismccord** [comment]
yeah we currently don't support overriding the ID to `live_img_preview`, but the broken behavior is expected for duplicate DOM ids. I just updated master to allow overriding the ID to accommodate rendering dup previews.

**Comment by bultas** [comment]
nice, thanks for the quick response..

**Comment by ThomasGl** [comment]
> yeah we currently don't support overriding the ID to `live_img_preview`, but the broken behavior is expected for duplicate DOM ids. I just updated master to allow overriding the ID to accommodate rendering dup previews.

Hey, I was wondering if this fix was merged?

I am using Phoenix LiveView version (mix deps): 0.19.5

And I still have

from the ```phoenix_component.ex```:

```elixir

def live_img_preview(assigns) do
    ~H"""
    <img
      id={"phx-preview-#{@entry.ref}"}
      data-phx-upload-ref={@entry.upload_ref}
      data-phx-entry-ref={@entry.ref}
      data-phx-hook="Phoenix.LiveImgPreview"
      data-phx-update="ignore"
      {@rest} />
    """
  end

```

Thus, anything passed as ```id="some-id"``` is ignored
