### ISSUE TITLE
Docs - minor clarification for assign_new docstring

### ISSUE THREAD

**Issue by samaaron** [phoenixframework/phoenix_live_view#1898]
Hi there,

this is definitely nothing major, I just personally struggled to understand the following paragraph:

https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#attach_hook/4

> Referencing parent assigns
> When a LiveView is mounted in a disconnected state, the [Plug.Conn](https://hexdocs.pm/plug/1.12.1/Plug.Conn.html) assigns will be available for reference via [assign_new/3](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#assign_new/3), allowing assigns to be shared for the initial HTTP request. The [Plug.Conn](https://hexdocs.pm/plug/1.12.1/Plug.Conn.html) assigns will not be available during the connected mount. Likewise, nested LiveView children have access to their parent's assigns on mount using [assign_new/3](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#assign_new/3), which allows assigns to be shared down the nested LiveView tree.

It's probably just because I don't have a full enough understanding of all the various terms being used here. However, I do believe there's some opportunity to clarify a few things without stopping it being terse and clear for experts.

I'm happy to create a PR once I've figured this out, I'm just raising it here as a reminder to come back and revisit this once I've got my head around things.

The first things I'm going to figure out are:

1. What it means for a LiveView to be "mounted in a disconnected state" vs in a "connected mount".
2. What it means for assigns to be "available" and how availability can change.

Other than the fact one takes a value and the other takes a function, it's not clear to me what the different usecases of `assign` and `assign_new` are. 

I'm guessing the lambda in `assign_new` is evaluated at a later point, perhaps only on demand and the result replaces the 'value' of the assign for subsequent reads?

**Comment by mcrumm** [comment]
Hi @samaaron! We reserve the issue tracker for issues, but I recommend taking this discussion to [ElixirForum](https://elixirforum.com/) or Slack where there is a larger community available to answer questions. That said, docs PRs for clarity are always very, very welcome! :)
