### ISSUE TITLE
Add latency simulator for dev

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix_live_view#19]
Browser dev tools today do not add latency for WS frames, so we'll need to simulate a tunable latency knob on the server for dev UX testing.

**Comment by nickjj** [comment]
It would be neat if you added a second knob to control the jitter too. Being able add 150ms of latency will definitely be useful but it would also be very beneficial to be able to say "add 150ms of latency with 50ms of jitter".

On a real connection you're probably not going to get a perfect 150ms of latency for each packet. It would have variance to it. That's where the jitter would come into play. In the above example you would end up with 100-200ms of latency (50ms of jitter in either direction).
