### ISSUE TITLE
Booleans unexpectedly dropped after moving from eex to heex

### ISSUE THREAD

**Issue by agundy** [phoenixframework/phoenix_live_view#1900]
### Environment

* Elixir version (elixir -v): Elixir 1.13.2 (compiled with Erlang/OTP 24)
* Phoenix version (mix deps): 1.6.6
* Phoenix LiveView version (mix deps): 0.17.0
* Operating system: Ubuntu
* Browsers you attempted to reproduce this bug on (the more the merrier): 
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:

### Actual behavior

Maybe a bug, more likely a confusion or inconsistency. I faced the following issue after upgrading an EEX template to the HEEX format.

HEEX of the form:
```heex
<data id="feature-flags"  data-flag-enabled={true} data-flag-disabled={false}></data>
or
<data id="feature-flags"  data-flag-enabled={true} data-flag-disabled={enabled?(:flag_name)}></data>
```
turns into:
```html
<data id="feature-flags"  data-flag-enabled=""></data>
```
### Expected behavior

I expected this to be:

```html
<data id="feature-flags"  data-flag-enabled="true" data-flag-disabled="false"></data>
```
Maybe this is my misunderstanding but I didn't notice anything in the release notes or docs about this and ran into this issue.

Is the expected way to do something like this?
```heex
<data id="feature-flags"  data-flag-enabled={"#{enabled?(:flag_name)}"} data-flag-disabled={"#{enabled?(:flag_two_name)}"}></data>
```

**Comment by josevalim** [comment]
Yes, this is expected behaviour and it is also how `content_tag(:a, foo: true, bar: false)` have always worked. I think using words like "enabled" / "disabled" will be clearer here, as the semantics for actual booleans have always been the same, it is just that before they were interpolated as strings!
