### ISSUE TITLE
Form changeset change trigger from custom component for Phoenix.HTML.Form.multiple_select

### ISSUE THREAD

**Issue by mxrguspxrtwork** [phoenixframework/phoenix_live_view#1902]
Let's say on a page there is a form with multiple_select field.

For desktop we want to have custom MultiSelect component, that looks styled (so different, that needs custom html and styles). 

This custom MultiSelect component shows selected values, and on clicking on selected value, the value is removed.

I tried to `document.getElementById('permissions').options.map(option => option.selected = false)` on click, but it seems, that form change event is not triggered.

Having specific `def handle_event("remove_seleted_value", params, socket)` would work, but it is much more code.

Would it be possible to have native HTML form elements, that are manipulated by custom elements, so that form changeset events work? Or what would be recommended approach.

**Comment by margusp2heathmont** [comment]
https://hexdocs.pm/phoenix_live_view/js-interop.html

```
document.getElementById("my-select").dispatchEvent(
  new Event("input", {bubbles: true})
)
```

combined with

```
var select = document.getElementById('permissions');
for (var i in select.options) {
  select.options[i].selected = false;
}
```

Seems to work as expected. (Unless there are default values, that will be resetted - instead of not selecting anything, but it seems to be progress).

**Comment by petemcfarlane** [comment]
We had a similar issue today - a custom web component (also a dropdown/select) is set up with `formAssociated = true` and calling `attachInternals`. It seems if I directly add an event listener on the form with `form.addEventListener(change, console.log)` I _do_ see the change event fired from the web component, but the `phx-change` listener doesn't seem to respond. 
To get around this, we ended up inserting a hidden input after each instance of the web component, that listens for a custom event from the web component, sets the value of the hidden element, then dispatches an `Event("change", {bubbles: true})`  from the hidden element. This does cause the form `phx-change` listener to update. But it seems a bit of a hack, adding an extra hidden input for every web component...

**Comment by feliperenan** [comment]
We know have `phx-change` on input level. Does it solve your issue?

https://github.com/phoenixframework/phoenix_live_view/pull/1934/files#diff-9dfe7db43161b3ef6a4fb87d6b6327340d608400db23565632f99ec01bc33d13R89

**Comment by josevalim** [comment]
Closing. Please let us know if still relevant. :)
