### ISSUE TITLE
phx-change events not generated on Edge browser

### ISSUE THREAD

**Issue by brianmay** [phoenixframework/phoenix_live_view#191]
Not sure how important Edge compatibility is at present time, however I notice my site works mostly fine with Firefox and Chrome, but on Edge phx-change events generated by an input field or an option field seem to get ignored.

Will try to get an Edge browser I can do more testing on myself.

**Comment by michallepicki** [comment]
Microsoft provides free virtual machines for testing: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by chrismccord** [comment]
Edge + IE11 will be supported. I have VMs so will take a look once I find some time. If folks would like to assist here, that would also be great! Thanks!

**Comment by brianmay** [comment]
I saw a java script error along the lines of "Invalid argument" in the JavaScript console. The was minimized JavScript, so not very helpful in working out why the error occurred. Will try the VM above, thanks for the reference.

**Comment by brianmay** [comment]
OK, reproduced in browser stack, although I can't work out copy and paste in browser stack. Here are some screen shots instead.

The error. There are two errors, I suspect only the second one is causing problems, although both should probably be fixed.

![image](https://user-images.githubusercontent.com/112729/56996750-e62ffc80-6be8-11e9-8037-9ed6bd293f37.png)

Here is debug session immediately before the error occurred, note I reproduced the error condition in the watch expression.

![image2](https://user-images.githubusercontent.com/112729/56996777-fd6eea00-6be8-11e9-94b0-5c28447c4c55.png)

I don't really understand this code or why it is failing, and unfortunately it is minimized.

**Comment by brianmay** [comment]
Also note that `new FormData(e)` appears to work, although the object seems to be empty, and has no data except for `__proto__` - which is a `FormDataPrototype`.

**Comment by brianmay** [comment]
The first error, I can't find anything that looks like that filename, or any reference to `isPersonal` even.

I suspect this is the original code behind the second crash:

```
let serializeForm = (form) => {
  return((new URLSearchParams(new FormData(form))).toString())
}
```

**Comment by brianmay** [comment]
This works on Firefox, but fails on Edge, with the 2nd error:

```
new URLSearchParams(new FormData())
```

This works:

```
new URLSearchParams(new FormData().toString())
```

Also calling `URLSearchParams` method  `toString()` on Firefox gives a query string. Making the same call on Edge gives string that doesn't look very useful:

![2019-05-01T11 38 53+10 00](https://user-images.githubusercontent.com/112729/57002861-d672e100-6c05-11e9-9317-7a5782cbdf56.png)

**Comment by brianmay** [comment]
Also worth noting that `URLSearchParams` may not even be implemented on IE11 - yuck - https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams

**Comment by brianmay** [comment]
Might be useful for IE11: https://github.com/LvChengbin/url/blob/master/src/search-params.js
