### ISSUE TITLE
HTMLFormatter (heex) can disable CSS pseudo-class `:empty`

### ISSUE THREAD

**Issue by paulbickford** [phoenixframework/phoenix_live_view#1913]
### Environment

* Elixir version (elixir -v): 1.13.3
* Phoenix version (mix deps): 1.6.6
* Phoenix LiveView version (mix deps): 0.17.7 (https://github.com/phoenixframework/phoenix_live_view
* Operating system: Ubuntu Ubuntu 20.04.4 LTS
* Browsers you attempted to reproduce this bug on (the more the merrier): Brave Version 1.36.109 Chromium: 99.0.4844.51 , Firefox Version 97.0.2
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

The original code triggers the CSS pseudo-class `:empty` and the element is not visible, (`display: none`).

```elixir
<p class="alert alert-info" role="alert"
  phx-click="lv:clear-flash"
  phx-value-key="info"><%= live_flash(@flash, :info) %></p>
```

After `mix format`, the code looks like this: 

```elixir
<p class="alert alert-info" role="alert" phx-click="lv:clear-flash" phx-value-key="info">
  <%= live_flash(@flash, :info) %>
</p>
```
The pseudo-class `:empty` is no longer triggered and the element is shown on the page.

### Expected behavior

The `:empty` pseudo-class response remains the same before and after formatting.

**Comment by chrismccord** [comment]
there's no way for us to really know the `:empty` pseudo class is being a applied, and it was rather a hack that we relied on this before for the flash. The new generators will use a `<.flash` component to handle the presence or not of flash, so this is working as intended. Thanks!

**Comment by narrowtux** [comment]
Good to know that new projects will have this fixed, but where can I see the `<.flash` component that's being generated?

**Comment by 03juan** [comment]
@narrowtux It'll probably be in phx.gen.live's `live_helpers.ex` template once it gets into master https://github.com/phoenixframework/phoenix/blob/443a0a72c10d93aa3210ffd9851cc8377aff6c38/priv/templates/phx.gen.live/live_helpers.ex
