### ISSUE TITLE
Idea: allow sharing live view instances between clients

### ISSUE THREAD

**Issue by hubertlepicki** [phoenixframework/phoenix_live_view#192]
I have a commenting system on a customer's web site. This system renders list of comments under given article. Each URL has own list of comments, but the list is identical for all users seeing given article.

Users can paginate through the comments, so the unique list of comments visible at any given time is determined by: `article.id` and `current_page` parameters.

I was thinking how would I approach that with LiveView, and quickly realized that with amount of traffic this web site recieves, we are going to very quickly have major performance and memory bloat issues.

The web site can often times have 50,000 users at given article, possibly more. Lists of comments have 50 comments per page, and it's these contain long user-generated texts.

Every time new article is added, the 50,000 live views would have to be notified, re-render, compute assigns diff and send over the diff to listening clients. Everything, except the last step would be identical, between clients as the views are identical.

Would it make sense to provide and option in LiveView to build shared views? They would obviously not have access to things like user session data, but if I have two variables that basically identify what the view renders (`article.id` and `current_page`), I could have single LiveView instance doing the heavy lifting, and then some layer to send the results to listening clients en masse.

I was thinking this would be Registry-based, where on first mount a LiveView registers itself under given key (`article.id` and `current_page` in my case). It responds to events such as "comment_added", and re-renders / computes diff - all in single instance/process.

Then it needs some sort of tracking of overall current assigns/template state, so we can send down the initial render to connecting clients without hitting LiveView if it's already running. I was having a look at the testing code provided here: https://github.com/phoenixframework/phoenix_live_view/blob/master/lib/phoenix_live_view/test/client_proxy.ex and it would be a good starting point. When such "shared live view" initially mount, we would start this server-side client/proxy, which tracks each update to the LiveView and keeps rendered HTML on hand. When new client joins, we serve latest version of HTML, when they join over channel, we start sending them continous updates. And then we'd need some time-based or event-based system to shut down these shared liveviews when no more clients are looking at them.

An alternative that could work would be a form of caching, but I don't if that's more suitable.

What do you think? I would love to put in some time to resolve the issue but a guidance would be nice, so I am sending the proposal before I do anything / research further.

**Comment by chrismccord** [comment]
We will explore optimization paths like the channel fastlaning, but not in the short term. With optimized collections and the ability to offload some dynamic state (assigns that don't change often), I think your requirements will fit nicely. Computing diffs is cheap, but the encoding side is more expensive, and that's where something akin to fastlaning would help, but I think as is you will find adequate performance as is. For example, provided you broadcast the prefetched data such that LV's don't need to all fetch the same data/massage the same data, the render + encode step is the only thing that needs performed.

The biggest help right now would be to build the thing and put it under the load, and let us know how it goes. Thanks!
