### ISSUE TITLE
phx-click-away should only trigger when the click was initiated outside the element

### ISSUE THREAD

**Issue by rupurt** [phoenixframework/phoenix_live_view#1920]
### Environment

* Elixir version (elixir -v):
* Phoenix version (mix deps):
* Phoenix LiveView version (mix deps):
* Operating system:
* Browsers you attempted to reproduce this bug on (the more the merrier): 
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:

### Actual behavior

`phx-click-away` triggers when click is released outside element making it difficult to select text. e.g. selecting text within a modal can close the modal if the click is released outside the modal.

### Expected behavior

Given I select text within an element with `phx-click-away`
When I move the mouse outside the element
But I am still holding the click down
When I release the click outside the `phx-click-away` element
Then the `phx-click-away` binding should not trigger

**Comment by josevalim** [comment]
I think doing this change will break other workflows. For example, imagine you have a dropdown. Clicking on anything in dropdown and outside should most likely close it. What you most likely want is to have a onclick/phx-click event on the text element that does not let the click event bubble up.

**Comment by rupurt** [comment]
> Clicking on anything in dropdown and outside should most likely close it

I'm not 100% sure about that. For example if you click down the select box for the github repo branches, drag outside of the drop down and release the click it doesn't close the dropdown. That seems more friendly to me, rather than closing a modal that might have unsaved work.

<img width="482" alt="Screen Shot 2022-03-17 at 4 51 12 PM" src="https://user-images.githubusercontent.com/680789/158912156-0031fa57-10b0-4594-bd77-4ce4ba8be4ba.png">

> What you most likely want is to have a onclick/phx-click event on the text element that does not let the click event bubble up.

I feel like that is mostly impractical unfortunately :/ I always want the ability to select text so would have to add that to every element in the modal

**Comment by josevalim** [comment]
I see. I think this is the same discussion as #1826, or is it different?

**Comment by rupurt** [comment]
Dang! Thank you @chrismccord. I didn't even have time to respond :)

**Comment by arianvassili** [comment]
Maybe this is the wrong place to ask but I'm wondering if there are any considerations regarding clicking to close a live_flash without wanting phx-click-away to trigger for eg a open modal? Something like phx-click-away-ignore on the live_flash div?

**Comment by jonatanklosko** [comment]
@chrismccord with this change the `phx-click` target is also taken from `mousedown`, should that be the case? https://github.com/phoenixframework/phoenix_live_view/commit/db841e39f8fdeebce93d8978aea4a3d7683a1445#diff-365d22aa5022f9d9a68ebc1483378c0bbcb863511eb84e81e7cdbc97387064fbR588

Context: I programmatically do `element.dispatchEvent(new Event("click", { bubbles: true }))` and `phx-click` targets an unexpected element. If I dispatch `mousedown` beforehand it works, but I'm wondering if the target should work like that.

**Comment by jackcarlisle** [comment]
https://github.com/enzai-technologies/enzai/issues/88
