### ISSUE TITLE
A more generic Phoenix.LiveView.JS used outside of LiveView

### ISSUE THREAD

**Issue by egze** [phoenixframework/phoenix_live_view#1927]
When building a `Phoenix.Component` it is often a requirement to have a rich user experience. One way to do it is to add some javascript that adds some handlers for the component and bundle the js with your application.

Another way that I am exploring is to keep all the logic in the `*.ex` component file. To achieve a rich interaction, I thought `Phoenix.LiveView.JS` could be a nice way to do it. But... we don't use LiveView.

Is there a way towards moving `Phoenix.LiveView.JS` to just `Phoenix.JS` and make it work regardless if it is LiveView or not?

**Comment by josevalim** [comment]
This has been discussed in the Phoenix mailing list and the TL;DR is that we are not sure. We will be glad to review a PR that attempts to implement this, but if we should merge it or not will ultimately depend on the complexity of the final code!

**Comment by egze** [comment]
I would like to take a stab at it. Thanks for the quick reply @josevalim
