### ISSUE TITLE
Using web components with LiveView

### ISSUE THREAD

**Issue by timgent** [phoenixframework/phoenix_live_view#1928]
### Environment

* Elixir version (elixir -v): Elixir 1.13.2 (compiled with Erlang/OTP 24)
* Phoenix version (mix deps): 1.6.6
* Phoenix LiveView version (mix deps): 0.17.7
* Operating system: Cross-OS issue (At least occurs on MacOS and Alpine)
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes

### Actual behavior

We created a web component, backed by [easydropdown](https://github.com/patrickkunka/easydropdown). The component works fine in a standard Phoenix view, but we've struggled to get it to work with Phoenix Liveview - issues with updates to the component, issues with keyboard only use, etc.

### Expected behavior

Web components "just work" in Phoenix Liveview. This issue is more a question of "what are the current expectations around web components working with Liveview?". If it's helpful I can create a small repo with a complete example of the issues we've been having.

**Comment by chrismccord** [comment]
There shouldn't be any problem using webcomponents within LV, but if you aren't using shadow DOM, you'll need to mark the container as `phx-update=ignore` to have us skip it when we patch the DOM. This talk should be helpful
https://www.youtube.com/watch?v=xXWyOy9XdA8

Thanks!
