### ISSUE TITLE
Possible bug in DOM.mergeFocusedInput

### ISSUE THREAD

**Issue by al2o3cr** [phoenixframework/phoenix_live_view#1931]
This line in `DOM.mergeFocusedInput` calls `DOM.mergeAttrs` with an `except` option:

https://github.com/phoenixframework/phoenix_live_view/blob/e9d41cb0533b3ee7ed4613a62070177a0a6395ce/assets/js/phoenix_live_view/dom.js#L292

but `mergeAttrs` looks for an option named `exclude`:

https://github.com/phoenixframework/phoenix_live_view/blob/e9d41cb0533b3ee7ed4613a62070177a0a6395ce/assets/js/phoenix_live_view/dom.js#L271

I'm currently reading this code to understand how form values interact with re-rendered DOM - so I can't say for sure what this is _supposed_ to do - but it jumped out as the kind of thing that's easy to overlook.

**Comment by 03juan** [comment]
@al2o3cr I think you're right. The HTML spec sees the value attribute as the default value for the input, but when a user changes the value the user agent sets a dirty value bit and essentially ignores the default value in favour of the user input. I've tested and this bug clobbers the default value which I'm don't think is the intention.

'mergeFocusedInput` should be sending `{exclude: ["value"]}`, not `except`.
