### ISSUE TITLE
Incorrect error for sticky nested liveview

### ISSUE THREAD

**Issue by LostKobrakai** [phoenixframework/phoenix_live_view#1938]
### Environment

* Elixir version (elixir -v):
* Phoenix version (mix deps):
* Phoenix LiveView version (mix deps): 0.17.7
* Operating system:
* Browsers you attempted to reproduce this bug on (the more the merrier): 
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:

### Actual behavior

https://github.com/phoenixframework/phoenix_live_view/blob/3474c8cf4b1d548025e71b66fbc922ca1c71ce1c/lib/phoenix_live_view.ex#L1480-L1495

`Phoenix.LiveView.child?/1` checks the `parent_pid` to assert of a LV is nested. That key is not set for sticky nested LVs.

### Expected behavior

Correct error message to be thrown.

**Comment by chrismccord** [comment]
Can you describe the steps to produce the wrong error? Thanks!

**Comment by chrismccord** [comment]
ping @LostKobrakai :)
