### ISSUE TITLE
Extra linebreak in single line heex

### ISSUE THREAD

**Issue by atavistock** [phoenixframework/phoenix_live_view#1942]
### Environment

* Elixir version (elixir -v): 1.13.3-otp-24
* Phoenix version (mix deps):  1.6.6 
* Phoenix LiveView version (mix deps): 0.17.7 (https://github.com/phoenixframework/phoenix_live_view.git - 1d70646)
* Operating system: OS/X 12.2.1

### Actual behavior

Not a serious issue by any means, but certainly looks weird when editing a file because indent is wonky.  This only happens for a some components where I'm deliberately only returning a single line of heex and running the heex formatter.

A line like 
```
     ~H"<%= raw(source) %>"
```

gets formatted like
```
     ~H"<%= raw(source) %>
"
```

### Expected behavior

This line should remain unchanged.

**Comment by atavistock** [comment]
I've tried with other delimiter pairs and its the same behavior of putting the trailing delimiter on the next line with no indent.

**Comment by 03juan** [comment]
This required a fix upstream that will be live in Elixir 1.13.4. See https://github.com/feliperenan/heex_formatter/issues/48#issuecomment-1043352802

**Comment by josevalim** [comment]
Elixir v1.13.4 is out!
