### ISSUE TITLE
Phoenix.LiveView.HTMLFormatter plugin causing issue in UI

### ISSUE THREAD

**Issue by Sed9yDataBank** [phoenixframework/phoenix_live_view#1943]
### Environment

* Elixir version (elixir -v):

1.13.3 (compiled with Erlang/OTP 24)

* Phoenix version (mix deps):

~> 1.6.6

* Phoenix LiveView version (mix deps):

https://github.com/phoenixframework/phoenix_live_view

* Operating system:

MacOS

* Browsers you attempted to reproduce this bug on (the more the merrier): 

FireFox

* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:

Yes

### Actual behavior

alerts background keep appearing, this is cause by the HTML Formatter  i added as a plugin, `Phoenix.LiveView.HTMLFormatter` in my `.formatter.exs`

code in `live.html.heex` that does not work after formatting

```html
<main class="mt-5 px-10">
  <div class="container">
    <p class="alert alert-info" role="alert" phx-click="lv:clear-flash" phx-value-key="info">
      <%= live_flash(@flash, :info) %>
    </p>
    <p class="alert alert-danger" role="alert" phx-click="lv:clear-flash" phx-value-key="error">
      <%= live_flash(@flash, :error) %>
    </p>
  </div>

  <%= @inner_content %>
</main>
```
the alert act normally when i remove the HTML formatting caused by the [formatter](https://github.com/phoenixframework/phoenix_live_view/blob/master/lib/phoenix_live_view/html_formatter.ex)

code in `live.html.heex` that does work before formatting

```html
<main class="mt-5 px-10">
  <div class="container">
    <p class="alert alert-info" role="alert"
      phx-click="lv:clear-flash"
      phx-value-key="info"><%= live_flash(@flash, :info) %></p>

    <p class="alert alert-danger" role="alert"
      phx-click="lv:clear-flash"
      phx-value-key="error"><%= live_flash(@flash, :error) %></p>
  </div>

  <%= @inner_content %>
</main>
```
 
![Screen Shot 2022-04-07 at 12 59 22 AM](https://user-images.githubusercontent.com/58634448/162093645-4e8cfa66-187b-4ce8-8b19-9b8d84ead2cd.png)

### Expected behavior

alerts background should only appear when there is an alert

_i decided to remove the plugin entirely, to skip having other weird issues like this one, but i just wanted to report this_

**Comment by 03juan** [comment]
This required a fix upstream in Elixir 1.13.4. See https://github.com/feliperenan/heex_formatter/issues/48#issuecomment-1043352802

**Comment by josevalim** [comment]
Elixir v1.13.4 is out! Thank you @03juan!

**Comment by Sed9yDataBank** [comment]
@josevalim you confused me with your comment. the new elixir release fixed the issue that i am showing?

**Comment by feliperenan** [comment]
@Sed9yDataBank This is happens because `p` tag will always be rendered and the Formatter needs to introduce that extra space in order to proper format the HTML.

The fix for that will be likely changing Phoenix generators to use a `Phoenix component` instead so the tag `p` will not be rendered at all in case there isn't an alert https://github.com/phoenixframework/phoenix/pull/4667. For other cases, you'd need to do the same thing or make sure blank spaces are not handled by CSS.
