### ISSUE TITLE
Attribute `replace` not allowed in `phx-update`.

### ISSUE THREAD

**Issue by pierot** [phoenixframework/phoenix_live_view#1944]
### Environment

* Elixir version (elixir -v): 1.13.3
* Phoenix version (mix deps): 1.6.6
* Phoenix LiveView version (mix deps): 0.17.8
* Operating system: Mac OS 12.3
* Browsers you attempted to reproduce this bug on (the more the merrier): /
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: /

### Actual behavior

Given this in a `heex` template:

```html
<tbody phx-update="replace">
```

When compiling:

```elixir
** (Phoenix.LiveView.HTMLTokenizer.ParseError) lib/justified_web/lives/partner_dashboard/inbox_live.html.heex:76:11: the value of the attribute "phx-update" must be: ignore, append or prepend
```

### Expected behavior

As stated in the docs, `replace` should be allowed: https://hexdocs.pm/phoenix_live_view/dom-patching.html

**Comment by josevalim** [comment]
Fixed. Meanwhile note that replace is the default value, so you can skip the attribute altogether.

**Comment by pierot** [comment]
@josevalim thanks! 
_I know it is the default but I like to be explicit sometimes :)_
