### ISSUE TITLE
Heel formatter forbid @value

### ISSUE THREAD

**Issue by obsidienne** [phoenixframework/phoenix_live_view#1947]
### Environment

* Elixir version (elixir -v): 1.13.4 erlang 24
* Phoenix version (mix deps): ~> 1.13
* Phoenix LiveView version (mix deps): ~> 1.17.8
* Operating system: Monterey
* Browsers you attempted to reproduce this bug on (the more the merrier): N/A
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: N/A

### Actual behavior

I have in one of my heex template the following code

```heex
<ul id="tracks" phx-update={@update_action} role="list" class="space-y-3">
  <%= for track <- @tracks do %>
    <.live_component module="..." id={track.id} />
  <% end %>
</ul>
```

@update_action is set at runtime to prepend _(when a new track is created/broadcasted)_ or append _(when the user scroll)_
This code works, but I have the following error when I compile

```
** (Phoenix.LiveView.HTMLTokenizer.ParseError) lib/.../show.html.heex:70:7: the value of the attribute "phx-update" must be: ignore, append or prepend
```

### Expected behavior

No error and allow the usage of runtime value

Thanks

**Comment by hattmarris** [comment]
:raised_hands:
