### ISSUE TITLE
Compiler error when phx-update value is replace in 17.8.8

### ISSUE THREAD

**Issue by hattmarris** [phoenixframework/phoenix_live_view#1948]
### Environment

* Elixir version (elixir -v): 1.13.2
* Phoenix version (mix deps): 1.6.6
* Phoenix LiveView version (mix deps): 0.17.8
* Operating system: Linux (Ubuntu)
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome - but prob. N/A as it's a compiler error
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

The new `17.8.8` release errors when I have a dynamic `phx-update={@phx_update}` assigns of value `replace` - I'm unsure if this compilation error is due to the dynamic value or `replace` as [the code](https://github.com/phoenixframework/phoenix_live_view/blob/268b4f6d4a0c52f6e4f25ecdb9b94e80f60b57ba/lib/phoenix_live_view/html_engine.ex#L795) appears to allow replace, but the message stipulates `the value of the attribute "phx-update" must be: ignore, append or prepend`.  

```
== Compilation error in file lib/app_web/components/block.ex ==
** (Phoenix.LiveView.HTMLTokenizer.ParseError) lib/app_web/components/block.ex:50:5: the value of the attribute "phx-update" must be: ignore, append or prepend
    (phoenix_live_view 0.17.8) lib/phoenix_live_view/html_engine.ex:801: Phoenix.LiveView.HTMLEngine.validate_phx_attrs!/5
    (phoenix_live_view 0.17.8) lib/phoenix_live_view/html_engine.ex:418: Phoenix.LiveView.HTMLEngine.handle_token/2
    (elixir 1.13.2) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix_live_view 0.17.8) lib/phoenix_live_view/html_engine.ex:53: Phoenix.LiveView.HTMLEngine.handle_body/1
    (phoenix_live_view 0.17.8) expanding macro: Phoenix.LiveView.Helpers.sigil_H/2
    lib/app_web/components/block.ex:49: AppWeb.Components.Block.paragraph/1
==> phoenix_pubsub
Compiling 11 files (.ex)
Generated phoenix_pubsub app
==> phoenix
Compiling 69 files (.ex)
Generated phoenix app
==> honeybadger
Compiling 20 files (.ex)
Generated honeybadger app
==> phoenix_live_view
Compiling 31 files (.ex)
Generated phoenix_live_view app
==> phoenix_live_dashboard
Compiling 40 files (.ex)
Generated phoenix_live_dashboard app
==> app
Compiling 46 files (.ex)
```

### Expected behavior
My reading of [the docs for dom patching](https://hexdocs.pm/phoenix_live_view/dom-patching.html) is that the `replace` value is the default - but also an allowed value for a developer to use as input to the binding.  If that's changing / changed maybe this is less a "bug issue" and more a "hexdocs updating issue" :smile:   

FWIW Our use case is "prepping" a div for replacement that is for most of it's life cycle `phx-update=ignore` (b/c it's a prosemirror rich text editor instance), so when the user submits a form to change that block (div) from a rich text editor to something else there's a process spawned for converting the data, we change `phx-update` to `replace` via assigns + a re-render and then when the data conversion is done we can update our list and the div is replaced instead of ignored.  (Definitely open to suggestions if there's a better way to do things) -- at least this is the way we got it working in `0.17.7`

Thanks for any help on this one! We :heart: phoenix live view :smile:

**Comment by josevalim** [comment]
Fixed in master :)

**Comment by hattmarris** [comment]
Looks like this might be a dupe of #1947 as well - thanks @josevalim !
