### ISSUE TITLE
Unwanted line-breaks by HTMLFormatter

### ISSUE THREAD

**Issue by hfjallemark** [phoenixframework/phoenix_live_view#1950]
### Environment

* Elixir version (elixir -v): 1.13.4
* Phoenix version (mix deps): 1.6.6
* Phoenix LiveView version (mix deps): 0.17.8
* Operating system: macOS

### Actual behavior

The following HEEX code:

```html
<div>
  This should not wrap on a new line <input />.
</div>
```

Gets formatted into this:

```html
<div>
  This should not wrap on a new line
  <input />
  .
</div>
```

### Expected behavior

It should not break lines since that causes unwanted spacing in when the browser is rendering the HTML.

**Comment by hfjallemark** [comment]
It does not seem to break lines for inline elements:

```html
<div>
  This should not wrap on a <b>new line</b>.
</div>
```

But it does do it for block elements, self-closing tags and custom Phoenix components.

**Comment by josevalim** [comment]
We could make it so self-closed elements are always considered inline, but I’m not sure if should. WDYT @feliperenan ?

**Comment by hfjallemark** [comment]
I think all self-closing elements are inline by default so that would make sense. But more importantly, how to handle custom Phoenix components that are inline? E.g. your own `<b>` element. If they are treated as block elements and always formatted on a new line there will be issues when you need text right after it without a space in between (in my use case I have a custom component just before the end of a sentence that ends with a dot).

**Comment by josevalim** [comment]
Yeah, this sounds like a good change then.

**Comment by feliperenan** [comment]
Merged a fix. Please, let me know about any issues 🙌🏻

**Comment by hfjallemark** [comment]
Works like a charm @feliperenan! Thanks for the quick turnaround.

Discovered one more unwanted line break:

```html
<div>
  Should not <%= "line-break" %>.
  But it does.
</div>
```

becomes:

```html
<div>
  Should not <%= "line-break" %>
  .
  But it does.
</div>
```

**Comment by feliperenan** [comment]
@hfjallemark fixed in master too. Please, take a look :)

**Comment by hfjallemark** [comment]
Now that example works! But if there's enough text after the eex expression it still wraps a bit weird:

```html
<div>
  Should not line break after the eex expression<%= "line break" %>. But it does and brings the dot 
  down to a new line.
</div>
```

becomes:

```html
<div>
  Should not line break after the eex expression<%= "line break" %>
  . But it does and brings the dot
  down to a new line.
</div>
```

Not sure if it's possible but the following format would be better:

```html
<div>
  Should not line break after the eex expression<%= "line break" %>. But it does and brings the
  dot down to a new line.
</div>
```

Maybe this is impossible since the dot is just text like the rest of the text, if I manually line break before the "dot" it keeps it that way so that's a good workaround at least.

**Comment by josevalim** [comment]
Yeah, automatically formatting text would open up a can of worms but we do respect what you write!
