### ISSUE TITLE
HTMLFormatter adds unwanted newline (whitespace) between text and interpolation

### ISSUE THREAD

**Issue by superhawk610** [phoenixframework/phoenix_live_view#1955]
### Environment

* Elixir version (elixir -v):

```
Erlang/OTP 23 [erts-11.1.3] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [hipe]

Elixir 1.13.4 (compiled with Erlang/OTP 22)
```

* Phoenix version (mix deps): `1.6.6`
* Phoenix LiveView version (mix deps): `0.17.9`
* Operating system: `Ubuntu 20.04.3 via WSL`
* Browsers you attempted to reproduce this bug on (the more the merrier): n/a
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

To reproduce, create a new Phoenix project, then create a live template using the `.heex` extension with this text content:

```heex
<div>
  _______________________________________________________ result<%= if(@row_count != 1, do: "s") %>
</div>
```

Formatting this file with `mix format` results in this output:

```heex
<div>
  _______________________________________________________ result
  <%= if(@row_count != 1, do: "s") %>
</div>
```

The exact number of `_` characters is important: with any less, the line won't wrap.

### Expected behavior

I would expect this output instead (the `s` should stay on the same line as `result`):

```heex
<div>
  _______________________________________________________
  result<%= if(@row_count != 1, do: "s") %>
</div>
```

In HTML, newlines within text are converted into whitespace, so these two HTML documents are meaningfully different:

```heex
<div>
  foo<%= "bar" %>
</div>
```

which outputs `foobar`, and

```heex
<div>
  foo
  <%= "bar" %>
</div>
```

which outputs `foo bar`.

**Comment by feliperenan** [comment]
The PR I opened will fix that but the output for this case will keep the eex expr at the same line. See for more info https://github.com/phoenixframework/phoenix_live_view/pull/1956#discussion_r846619017
