### ISSUE TITLE
Formatter moves period to next line when after link

### ISSUE THREAD

**Issue by jsmestad** [phoenixframework/phoenix_live_view#1957]
Was testing out #1956 and #1953 changes and noticed there is an issue with the formatter inserting a space if the last thing in a sentence is a link. This causes an extra space to show up. For example, `"Click the link here."` renders as `"Click the link here ."`

### Environment

* Elixir version (elixir -v): `1.13.4`
* Phoenix version (mix deps): `phoenix 1.6.6`
* Phoenix LiveView version (mix deps): `phoenix_live_view 0.17.9 (https://github.com/phoenixframework/phoenix_live_view.git - 1b313b3466776d2439e681c443c8efd7ee296fc1) (mix)`
* Operating system: `macOS`

### Actual behavior

```html
      <p>
        Based on the applicable laws of your country, you may have the right to request access to the personal information we collect from you, change that information, or delete it in some circumstances. To request to review, update, or delete your personal information, please submit a request form by clicking
        <a
          class="text-blue-500"
          href=""
          rel="noopener noreferrer"
          target="_blank"
        >
          here
        </a>
        . We will respond to your request within 30 days.
      </p>
```

### Expected behavior

```html
      <p>
        Based on the applicable laws of your country, you may have the right to request access to the personal information we collect from you, change that information, or delete it in some circumstances. To request to review, update, or delete your personal information, please submit a request form by clicking
        <a
          class="text-blue-500"
          href=""
          rel="noopener noreferrer"
          target="_blank"
        >
          here
        </a>. We will respond to your request within 30 days.
      </p>
```

**Comment by feliperenan** [comment]
hummm... the issue here is that our HTML formatter formats tags regardless it is inline or block. So, in your example, in case your sentence reaches the limit of a line break and/or your anchor element has enough attributes, the formatter would format your element as you said.

I was taking a look at other formatters and I've seen that they don't format inline elements at all. I'm not sure if we want to go down this path or if there is a better way of handling this.

**Comment by feliperenan** [comment]
It is fixed on master. Please, take a look and let me know about any issues 🙌🏻
