### ISSUE TITLE
When `live_flash` is clicked, it cleans `temporary_assigns` inside a `live_component`

### ISSUE THREAD

**Issue by shahryarjb** [phoenixframework/phoenix_live_view#1960]
### Environment

* Elixir version (elixir -v): 1.13.3
* Phoenix version (mix deps): 1.6
* Phoenix LiveView version (mix deps): 0.17.5
* Operating system: macOS
* Browsers you attempted to reproduce this bug on (the more the merrier): Google Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: no

I created a short video about my problems:

https://user-images.githubusercontent.com/8413604/162621159-72a28a63-d008-4ec8-a08d-c3d8f46ef80d.mp4

---

When I want to call a component in my LiveView like this:
```elixir
 @impl true
  def render(assigns) do
    ~H"""
    <button type="button" phx-click="btn">Click Me!</button>
    <.live_component module={TestFlashWeb.PageLiveComponent} id={:pagecom} notifs={@notifs} flash={@flash} />
    """
  end

  @impl true
  def mount(_params, _session, socket) do
    socket =
      assign(socket,
        page_title: "Hello Live",
        notifs: list()
      )
    {:ok, socket, temporary_assigns: [notifs: []]}
  end
```

If I create a `handle_event` to show a `put_flash` like this:
```
  @impl true
  def handle_event("btn", _value, socket) do
    socket =
      socket
      |> assign(notifs: list())
      |> put_flash(:info, "Hi it is for test")
    {:noreply, socket}
  end
```
Now if my user click on the `live_flash`, because `notifs` is `temporary_assigns`, it cleans the records in the page

Test source: https://github.com/shahryarjb/liveflashbug (http://localhost:4003/test)

> I think it is a bug, so I sent there, if it is not, I can create a post in forum let me know

**Comment by josevalim** [comment]
This is intentional. if you declare something as temporary it will be cleared immediately after rendering and any other event won’t have that date anymore. You need to make sure that the variable is being properly changed tracked so it is not rerendered unless the variable itself changes.

**Comment by shahryarjb** [comment]
@josevalim, thank you, I just want to understand why when we click the flash message it cleans even I use it in `live.html.heex` not a `live_component` after changing a `temporary_assigns` variable I always re-bind it to re-render a component. But flash message after all of them if it is pushed, clean the page and re-render the component.

```elixir
<p class="alert alert-info" role="alert" phx-click="lv:clear-flash" phx-value-key="info">
      <%= live_flash(@flash, :info) %>
 </p>
```

my problem is why `lv:clear-flash` event clean re-render a component in a page?

**Comment by josevalim** [comment]
https://github.com/shahryarjb/liveflashbug/blob/master/lib/test_flash_web/live/home_live.ex#L8

You are passing the `@flash` and `@notifs` to the component, which means that, if any of those change, the other will be re-rendered.

You are also using many stateful components, which means each of them is having their own version of `@notifs`. I would try to rely more on regular components.
