### ISSUE TITLE
Missing telemetry events for handle_info/2 callback (?)

### ISSUE THREAD

**Issue by teamon** [phoenixframework/phoenix_live_view#1961]
I'm trying to integrate AppSignal with LiveView, here's what I've tried:

1. Using [lifecycle hooks](https://sergiotapia.com/integrating-appsignal-with-phoenix-liveview-tutorial) works for sending events, but not for capturing exceptions as lifecycle hooks are executed before the actual functions  
2. Using [telemetry integration](https://github.com/appsignal/appsignal-elixir-phoenix/pull/41) only works for `mount`, `handle_params` and `handle_event` callback - not for `handle_info`

As I've noticed in [LiveView Telemetry docs](https://github.com/phoenixframework/phoenix_live_view/blob/master/guides/server/telemetry.md) there are not telemetry events for `handle_info` - are there any reasons for this? 

To give you some use-case context I'm spawning some remote data fetch processes in `mount` and capture results via `handle_info`

**Comment by chrismccord** [comment]
That's something you'll need to instrument yourself. Since LiveView's are regular processes, we leave it to the user to instrument custom message handling, just like you would do for a GenServer in your app. Thanks!
