### ISSUE TITLE
Formatter doesn't indent function calls

### ISSUE THREAD

**Issue by jonatanklosko** [phoenixframework/phoenix_live_view#1963]
Function calls are formatted as

```heex
<%= live_patch("Import",
  to: Routes.home_path(@socket, :import, "url"),
  class: "button-base button-outlined-gray whitespace-nowrap"
) %>
```

while intuitively I'd expect the call to be aligned, same as in Elixir code

```heex
<%= live_patch("Import",
      to: Routes.home_path(@socket, :import, "url"),
      class: "button-base button-outlined-gray whitespace-nowrap"
    ) %>
```

This of course a matter of preference, but worth discussion :)

**Comment by feliperenan** [comment]
Oh we don't format eex function at all. That's a bit harder to do and we decided to not do it since phoenix components is now the preferred way of writing this.

https://github.com/phoenixframework/phoenix_live_view/blob/master/lib/phoenix_live_view/html_formatter.ex#L107

**Comment by josevalim** [comment]
@feliperenan I think we don't format do-blocks, but we do format single EEx expressions, no?

**Comment by feliperenan** [comment]
Ohh sorry, I guess you are right. I confused with do..block. I will take a look at it soon 🙌🏻

**Comment by josevalim** [comment]
Alright then!

**Comment by jonatanklosko** [comment]
Okay! I don't have a strong opinion either, just wanted to make sure the behaviour is intended :)
