### ISSUE TITLE
Consecutive calls to `mix format` raise an exepection

### ISSUE THREAD

**Issue by alvivi** [phoenixframework/phoenix_live_view#1969]
### Environment

* Elixir version (elixir -v): `1.13.4` (OTP `24.3.3`)
* Phoenix version (mix deps): `1.6.6`
* Phoenix LiveView version (mix deps): `0.17.9`
* Operating system: Linux
* Browsers you attempted to reproduce this bug on (the more the merrier):  N/A
* Does the problem persist after removing "assets/node_modules" and trying again? Yes

### Actual behavior

In an umbrella application, with a `apps/xxx/.formatter.exs` like this:
```elixir
[
  import_deps: [:phoenix],
  plugins: [Phoenix.LiveView.HTMLFormatter],
  inputs: ["*.{heex,ex,exs}", "priv/*/seeds.exs", "{config,lib,test}/**/*.{heex,ex,exs}"]
]
```
The first call to `mix format` works as expected, but consecutive calls raise an exception. Example:
```
$ mix format

$ mix format
mix format failed for file: apps/xxx/lib/xxx/live/xxx.ex
** (UndefinedFunctionError) function Phoenix.LiveView.HTMLFormatter.format/2 is undefined (module Phoenix.LiveView.HTMLFormatter is not available)
    Phoenix.LiveView.HTMLFormatter.format("<-- sigil code here -->", [file: "xxx", line: 26, sigil:
 :H, modifiers: [], opening_delimiter: "\"\"\"", import_deps: [:phoenix], plugins: [Phoenix.LiveView.HTMLFormatter], inputs: ["*.{heex,ex,exs}", "priv/*/seeds.
exs", "{config,lib,test}/**/*.{heex,ex,exs}"]])
    (elixir 1.13.4) lib/code/formatter.ex:1333: Code.Formatter.maybe_sigil_to_algebra/4
    (elixir 1.13.4) lib/code/formatter.ex:458: Code.Formatter.quoted_to_algebra/3
    (elixir 1.13.4) lib/code/formatter.ex:549: anonymous fn/3 in Code.Formatter.block_args_to_algebra/4
    (elixir 1.13.4) lib/code/formatter.ex:1898: Code.Formatter.each_quoted_to_algebra_with_comments/6
    (elixir 1.13.4) lib/code/formatter.ex:1876: Code.Formatter.quoted_to_algebra_with_comments/6
    (elixir 1.13.4) lib/code/formatter.ex:554: Code.Formatter.block_args_to_algebra/4
    (elixir 1.13.4) lib/code/formatter.ex:1796: Code.Formatter.clauses_to_algebra/4

$ mix compile && mix format
mix format failed for file: apps/xxx/lib/xxx/live/xxx.ex
** (UndefinedFunctionError) function Phoenix.LiveView.HTMLFormatter.format/2 is undefined (module Phoenix.LiveView.HTMLFormatter is not available)
...
```

### Expected behavior

Not getting an exception. Not sure if this related to `HTMLFormatter` itself or not. I tried removing `_build` and `deps` and using `main`, but no luck.

**Comment by josevalim** [comment]
Does the application with a custom .formatter.exs depend on phoenix_live_view?

If yes and it still fails, can you please provide a minimal application that reproduces the error?

**Comment by alvivi** [comment]
@josevalim Yes, that application depends on `phoenix_live_view`.

I was able to reproduce the issue a new (minimal) project:  https://github.com/alvivi/issue_1969. I just created a new project using `mix phx.new --umbrella`, upgrade `phoenix_live_view` to `0.17.9`, added a file with a `H_sigil` and got the same exception after running `mix format`.

**Comment by SteffenDE** [comment]
Seeing the same issue. As workaround I currently add `phoenix_live_view` as dependency in the umbrella root and add the plugin to the root `.formatter.exs`, additionally to configuring it in the actual application:
```
[
  plugins: [Phoenix.LiveView.HTMLFormatter],
  subdirectories: ["apps/*"]
]
```
Then formatting works reliably.

**Comment by josevalim** [comment]
Oh! I see why it happens... When running the formatter from the root, it doesn't load the dependencies from children. Which means the HTML formatter is missing... the answer might be to add phoenix_live_view to the root too.
