### ISSUE TITLE
HTMLFormatter allow preventing breaks for custom components

### ISSUE THREAD

**Issue by SteffenDE** [phoenixframework/phoenix_live_view#1976]
Based on #1973, the issue with unwanted line breaks is fixed now when using the HTML `<textarea>` element, but still remains when wrapping elements using a custom function component, as is common when using something like Tailwind.

```elixir
<.textarea ...>My content</.textarea>
```

being formatted as

```elixir
<.textarea ...>
  My content
</.textarea>
```

and the component rendering into a `textarea` like this:

```elixir
<textarea class="my custom classes" {@extra_assigns}><%= render_slot(@inner_block) %></textarea>
```

This causes some unexpected content in the textarea, as the `@inner_block` contains whitespaces.

In #1973, @josevalim mentioned a `phx-no-break` attribute that could probably be helpful in those cases.

**Comment by josevalim** [comment]
The `phx-no-break` attribute can be checked in the same place as we check contenteditable. We should also change the engine to not emit phx-no-break in the actual HTML.

**Comment by feliperenan** [comment]
Also fixing this one and in the same PR https://github.com/phoenixframework/phoenix_live_view/pull/1977. Let me know if that works 🙌🏻

**Comment by SteffenDE** [comment]
That works indeed, although only when running the formatter for the first time, afterwards `phx-no-break` is removed from the element. I think this is exactly what was already commented in the PR.

**Comment by feliperenan** [comment]
Yeah. Just fixed that. Hopefully we are good now 🙌

**Comment by SteffenDE** [comment]
Yes, `phx-no-break` stays now. But maybe I'm doing something wrong, as I still see `phx-no-break` in the rendered HTML, see https://github.com/SteffenDE/heex_formatter_issue/tree/no_break.

Also, assuming that I actually don't want very long lines, I'd expect something like this to work:
```elixir
...
                <.textarea
                  id="textarea"
                  class="hidden very-long-class-name foo-bar-baz"
                  phx-no-break
                  blablablablablablablasdkasdjioasjdlaksjdlaksjdlajsdl="foooooo"
                >My content</.textarea>
...
```
But the formatter always forces it into one line. So no break after the end of the opening tag and the content, but still allowing breaks after all. That's just personal preference of course, not sure if that's possible without major changes.

**Comment by josevalim** [comment]
> Yes, phx-no-break stays now. But maybe I'm doing something wrong, as I still see phx-no-break in the rendered HTML, see https://github.com/SteffenDE/heex_formatter_issue/tree/no_break.

I have fixed this in the PR. :)

> Also, assuming that I actually don't want very long lines, I'd expect something like this to work:

@feliperenan the preserve mode should only apply to the contents of a tag, not for it attributes. Maybe this is something we could improve too?

**Comment by feliperenan** [comment]
Yes, definitely. I just assumed we would not format at all. I will change to format tag attributes regardless.

**Comment by feliperenan** [comment]
Ooh, I remembered why. Because of this case here:

```
        <p>
          text text<a class="text-blue-500" href="" target="_blank" attr1="">link</a>text.
        </p>
```

which would format to something like this:

```
        <p>
          text text<a
            class="text-blue-500"
            href=""
            target="_blank"
            attr1=""
          >link</a>text.
```

They all share the same function while formatting. We could check for `phx-no-break` attr and format the attributes in this case, but I wonder if we really should. I'm fine with both versions, so I'd keep as is. Wdyt?

**Comment by josevalim** [comment]
For me it is fine to format it in the way you described above. There is not much we can do to make the code pretty, but I would rather break than not break.

**Comment by SteffenDE** [comment]
This is great, thank you 😃
