### ISSUE TITLE
phx_join timeout, Routes helper very slow on connected render

### ISSUE THREAD

**Issue by SteffenDE** [phoenixframework/phoenix_live_view#1986]
### Environment

* Elixir version (elixir -v): 1.13.4
* Phoenix version (mix deps): 1.6.7
* Phoenix LiveView version (mix deps): 0.17.9
* Operating system: macOS
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, Brave, Safari, Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

To reproduce: clone this repo https://github.com/SteffenDE/live_view_timeout, set it up using the normal procedure (mix deps.get, mix compile, mix ecto.create, mix ecto.migrate), then run `mix generate_data --num 2000` and start the server `iex -S mix phx.server`. Load http://localhost:4000/test_items and refresh the page a couple of times.

This issue only seems to occur in development. When using a mix release, I could not reproduce it.

### Actual behavior

When loading a page, I see the following on some page loads:
The initial render works fine. Then, the websocket connection is established and a phx_join message is sent. The LiveView mounts, but no response is received on the websocket. After a couple of seconds, a timeout occurs and the page is reloaded.

![IMG_4863](https://user-images.githubusercontent.com/4116351/164419369-7093a721-ed06-40e2-901c-267b1ec278f2.png)

When it works, it looks as expected:

![IMG_0973](https://user-images.githubusercontent.com/4116351/164421003-eeb87c25-1308-4ee2-a23d-d52a9d77afaf.png)

Looking in the observer, there seems to be a silent error inside the Routes helper:

![image](https://user-images.githubusercontent.com/4116351/164424722-f07964a4-36e7-4c12-93f3-4d0a777deb82.png)
![image](https://user-images.githubusercontent.com/4116351/164424737-15ad63c8-c053-4115-88a6-d09f532a3481.png)

Indeed, removing the following lines from the template,

```elixir
          <span><%= live_redirect "Show", to: Routes.test_item_show_path(@socket, :show, test_item) %></span>
          <span><%= live_patch "Edit", to: Routes.test_item_index_path(@socket, :edit, test_item) %></span>
```

the issue seems to be gone.

### Expected behavior

Mounting the LiveView should work. If there is an error, it should be clearly visible and not silently timeout.

**Comment by SteffenDE** [comment]
So, quick update: changing the timeout on the liveSocket
```js
let liveSocket = new LiveSocket("/live", Socket, {params: {_csrf_token: csrfToken}, timeout: 60000})
```
actually leads to a complete render. I added some logs to `deps/phoenix/lib/router/helpers.ex`:
```elixir
      defp to_param(data) do
        IO.puts("fallback for #{inspect(data)}")
        Phoenix.Param.to_param(data)
      end
```
And can see that sometimes the calls are very slow on the connected render, taking up to 20 seconds for the 2000 items.

Probably my initial assumption is false, and there is no real error, but the calls to the error_handler come from the protocol not being defined for the struct and somehow the whole thing being very slow?

**Comment by SteffenDE** [comment]
What also helps is changing the markup to not pass the struct but the id directly:
```elixir
          <span><%= live_redirect "Show", to: Routes.test_item_show_path(@socket, :show, test_item.id) %></span>
          <span><%= live_patch "Edit", to: Routes.test_item_index_path(@socket, :edit, test_item.id) %></span>
```

**Comment by chrismccord** [comment]
This is not an issue in LiveView. Your mount is taking longer than the timeout (defaults to 10s). It does appear your protocol consolidation is not happening in development. In any case, you are likely rendering too much data. Rather than thousands of seconds, you may considering pagination or dynamically loading elements on scroll. Thanks!

**Comment by SteffenDE** [comment]
Yes, I know that it is suboptimal to render that many items on one page and I actually work on implementing pagination. I particularly do not understand why this only happens on the connected render.
But: I still think that this is very much unexpected (using the unmodified output of the `phx.gen.live` generator) and would appreciate a hint where to file a more appropriate issue then 😄
