### ISSUE TITLE
HTMLFormatter - behavior with inline comments `<%# comment %>`

### ISSUE THREAD

**Issue by leandrocp** [phoenixframework/phoenix_live_view#1989]
AFAIK such kind of comments were deprecated in favor of `<%!-- --%>` (https://github.com/elixir-lang/elixir/pull/11505) and the EEx tokenizer just ignore them now:

```
# v1.14
iex> EEx.tokenize '<%# comment %>'
{:ok, [eof: %{column: 15, line: 1}]}

# v1.13.4
ex> EEx.Tokenizer.tokenize '<%# comment %>', 0, 0, %{indentation: 0, trim: false}
{:ok, [{:eof, 0, 14}]}
```

_I'm not sure if that has changed on v.13.4_

Turns out we still have some of those comments in our codebase and I've noticed they are just removed when formatting the code, eg:

```
iex> input = """
...> <div>
...>   <%# comment %>
...>   <div>content</div>
...> </div>
...> """
"<div>\n  <%# comment %>\n  <div>content</div>\n</div>\n"
iex> IO.puts Phoenix.LiveView.HTMLFormatter.format(input, [])
<div>
  
  <div>content</div>
</div>
```

As you can see that blank line will put the template on an "imcomplete" state, ie: I need to run `mix format` again to get the "final" version of the template.

While that's not a big problem and I understand it's not supposed to deal with deprecated API, I see 2 issues that does impact the overall experience:

1. It does remove comments silently
2. Requires to run `mix format` twice

For 1 I'd say that a mention on docs asking to manually change comments to the new format is good enough, and for 2 seems like it should convert to `""` on the first pass instead of `\n`.

Thoughts?

**Comment by josevalim** [comment]
Unfortunately there is nothing we can do because Elixir does not give us the comment AST/metadata at all, and we don't want to add it for something that is deprecated. The best we can do is document that they are not supported and using them makes them be silently discarded.
