### ISSUE TITLE
csrf input not generated anymore for forms when action is nil

### ISSUE THREAD

**Issue by wkirschbaum** [phoenixframework/phoenix_live_view#1991]
Before version 0.17.8 it was possible to have a form without an action posting to the current path. After this change https://github.com/phoenixframework/phoenix_live_view/commit/e9fd7fa7 POST requests on forms without an action will return a forbidden response.

Unfortunately we did not spot this in changelog and the docs still says the action is optional.

For clarity: This is for non-live-view forms using hex, but since the helper seems to live in phoenix_live_view it causes this issue.

**Comment by josevalim** [comment]
@wkirschbaum apologies. You must explicitly say that you are posting to the current path. I will uipdate CHANGELOG and docs.

**Comment by wkirschbaum** [comment]
@josevalim thanks :). Hope this helps other people. I am curious to know why this change was made, as it does deviate from the standard empty action behavior on a html form.
