### ISSUE TITLE
Pass the assigns into the fn on assign_new. 

### ISSUE THREAD

**Issue by joshchernoff** [phoenixframework/phoenix_live_view#1996]
Using this as an example. 
```
assigns = assigns
  |> assign_new(:foo, fn -> "foo" end)
  |> assign_new(:bar, fn %{foo: foo} -> foo <> "bar" end)
```
Clearly this wont work currently but it illustrates the desire. 

What I want is a way to essentially pipe the assign_new and have access to the previously new set values.

**Comment by josevalim** [comment]
A PR is welcome!

**Comment by joshchernoff** [comment]
Fair enough, I will see if its something with in my capabilities. That said, does this seems like a worthy effort?

**Comment by josevalim** [comment]
My personal opinion is that yes, but others may disagree!

**Comment by joshchernoff** [comment]
Cleaning up after myself until I can get PR in. Feel free to chime in if you have any thoughts.
