### ISSUE TITLE
Heex formatter changes HTML

### ISSUE THREAD

**Issue by timgent** [phoenixframework/phoenix_live_view#2001]
### Environment

* Elixir version (elixir -v): Elixir 1.13.2 (compiled with Erlang/OTP 24)
* Phoenix version (mix deps): 1.6.7
* Phoenix LiveView version (mix deps): 0.17.9
* Operating system: MacOS
* Browsers you attempted to reproduce this bug on (the more the merrier): n/a (issue with rendered HTML rather than browser behaviour)
* Does the problem persist after removing "assets/node_modules" and trying again? Yes

### Actual behavior

This Heex template:

```
<p>Read <%= @my_managers_name %>'s feedback. Reading their feedback in advance will help you to get the most value from your Progress Review meeting!</p>
```

Got reformatted to:

```
  <p>
    Read <%= @my_managers_name %>
    's feedback. Reading their feedback in advance will help you to get the most value from your Progress Review meeting!
  </p>
```

Which is bad as when it renders there is now a space between `my_managers_name` and the apostrophe.

### Expected behavior

Don't insert newlines where there wasn't a space before

**Comment by chrismccord** [comment]
I believe master will leave this as is. Thanks!

**Comment by leandrocp** [comment]
master with default config will format it as:

```
<p>
  Read
  <%= @my_managers_name %>'s feedback. Reading their feedback in advance will help you to get the most value from your Progress Review meeting!
</p>
```

**Comment by josevalim** [comment]
The current master formatting is correct. :)

it is not ideal but we don’t break in the middle of the text. We break before/after tags though when possible.

**Comment by josevalim** [comment]
Actually, maybe we can improve here… we don’t break after the tag because of `’s` but maybe in this case we shouldn’t break before either.

**Comment by josevalim** [comment]
@leandrocp do you want to check how the formatter would behave if we dont break before AND after a tag/eex whenever the tag/eex does not have space before OR after?

**Comment by leandrocp** [comment]
I agree it can be improved and it may actually fix another issue I'm still having with the formatter. I'm gonna explore it further.

**Comment by feliperenan** [comment]
If I'm not mistaken, that happens because of this `flex_break`.

https://github.com/phoenixframework/phoenix_live_view/blob/master/lib/phoenix_live_view/html_algebra.ex#L59

> @leandrocp do you want to check how the formatter would behave if we dont break before AND after a tag/eex whenever the tag/eex does not have space before OR after?

I guess that would work. One way we could do this, is setting some metadata (maybe preserve) in the eex/tag checking the token before and after, if they are texts and they start and finish with whitespaces. Then, we could conditionally add this flex break.

@leandrocp let me know if you are working on this otherwise I can explore here 🙌🏻

**Comment by leandrocp** [comment]
Hi @feliperenan sorry for the late reply, yes I've resumed working on it today and your link helped. I believe that `prev_node`, `next_node`, and `head` provide enough information to build `on_break` for all possible cases. Currently I'm dealing with a couple of failing tests but making progress, thanks!

**Comment by karangejo** [comment]
I noticed that when I upgraded liveview to get the heex formatter that it would change ```lib/myapp_web/templates/layout/live.html.heex```  from this:
```html
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>
```
 to this:

```html
<main class="container">
  <p class="alert alert-info" role="alert" phx-click="lv:clear-flash" phx-value-key="info">
    <%= live_flash(@flash, :info) %>
  </p>

  <p class="alert alert-danger" role="alert" phx-click="lv:clear-flash" phx-value-key="error">
    <%= live_flash(@flash, :error) %>
  </p>

  <%= @inner_content %>
</main>
```

and these extra spaces and indentations make it so the flash alerts show up all the time because they are not empty. The phoenix css has this:
```css
.alert:empty {
    display: none;
}
```
 Maybe this new PR solves the problem. Anyway this formatter is great!

**Comment by leandrocp** [comment]
Hi @karangejo that PR won't change the behavior you reported because `p` is not an inline element. But you can add `phx-no-format` on each one of those `p` elements to get the output want like so:

```html
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info" phx-no-format><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error" phx-no-format><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>
```

And you'll get:

```html
<main class="container">
  <p
    class="alert alert-info"
    role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"
    phx-no-format
  ><%= live_flash(@flash, :info) %></p>

  <p
    class="alert alert-danger"
    role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"
    phx-no-format
  ><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>
```

That's available on the master branch.

**Comment by karangejo** [comment]
Ok! thank you for that. Perhaps I can change the default generated output for that file so that a new phoenix project already has this line that to if someone were to run ```mix format``` with the heex formatter they would not mess up their flash alerts.

**Comment by leandrocp** [comment]
> Ok! thank you for that. Perhaps I can change the default generated output for that file so that a new phoenix project already has this line that to if someone were to run `mix format` with the heex formatter they would not mess up their flash alerts.

IMO a PR to Phoenix adding that `phx-no-format` on the installer templates is welcome.

/cc @josevalim

**Comment by karangejo** [comment]
Ok working on it now!

**Comment by josevalim** [comment]
There is already a PR to change how we generate flash messages in Phoenix. We will pick one of them by the next Phx release!
