### ISSUE TITLE
Live navigation from a within stickied liveview

### ISSUE THREAD

**Issue by wwww-wwww** [phoenixframework/phoenix_live_view#2003]
### Environment

* Elixir version (elixir -v):
* Phoenix version (mix deps):
* Phoenix LiveView version (mix deps): 0.17.9
* Operating system:
* Browsers you attempted to reproduce this bug on (the more the merrier): 
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:

### Actual behavior

push_patch doesn't work, saying that the root is different. OK.
push_redirect works, but it causes the web page to reload.

### Expected behavior

The redirect should only patch like it does in a non-stickied liveview.

**Comment by chrismccord** [comment]
are you doing a push_redirect to a route within the same live_session?

**Comment by wwww-wwww** [comment]
yeah, they're in the same live_session (I have everything under 1 live_session)

**Comment by atif** [comment]
@chrismccord Facing the same issue https://elixirforum.com/t/push-redirect-not-working-from-sticky-child-liveview-instead-it-seems-to-do-a-socket-reconnection-as-per-console/49320

**Comment by josevalim** [comment]
Can you folks provide a minimal app to reproduce the error? You can find a starting example here: https://github.com/wojtekmach/mix_install_examples/blob/main/phoenix_live_view.exs

**Comment by chrismccord** [comment]
If folks can put together a reproduction, I would be happy to take a look. Thanks!
