### ISSUE TITLE
LiveView multi_select (or any form element becomes slugish to use when a lot of data)

### ISSUE THREAD

**Issue by margusp2heathmont** [phoenixframework/phoenix_live_view#2005]
Create multi_select (https://hexdocs.pm/phoenix_html/Phoenix.HTML.Form.html#multiple_select/4) with form and changeset.

1. Have it 1000 options.
2. Change 1 of it.
3. Look at the WS communication.
4. Change selection.
5. Look at the WS communication.

Currently the options seem to be, so that optimal data would be exchanged:
1. Use limit for the list of options (and "Load more" or infinite scroll)
2. Not to use Form multi_select, but some custom component (and custom state for managing component)

Is the some "best practice" how to get form behavior and only minimal data round trip for small operations? 

The question is kind of important in context of LiveViewTests, because one would hope that render_update() and render_submit() etc behaviour keeps working and is familiar.

**Comment by chrismccord** [comment]
Closing as this is not a functional issue. We can improve our form diffing to be sure, but this case if you are rendering thousands of options in a form, there's not a lot we can do. Thanks!
