### ISSUE TITLE
HTMLFormatter - text between inline elements in separated lines

### ISSUE THREAD

**Issue by leandrocp** [phoenixframework/phoenix_live_view#2008]
While working on https://github.com/phoenixframework/phoenix/pull/4793#issuecomment-1119687158 I've found another edge case:

```elixir
assert_formatter_doesnt_change("""
<span><%= link("Edit", to: Routes.post_path(@conn, :edit, @post)) %></span>
| <span><%= link("Back", to: Routes.post_path(@conn, :index)) %></span>
""")
```

This template can be found on https://github.com/phoenixframework/phoenix/blob/dcc7ae530767896d458fcfde95156e037f3adc36/priv/templates/phx.gen.html/show.html.heex#L12-L13

/cc @feliperenan

**Comment by josevalim** [comment]
Just for completeness, what does it format to today?

**Comment by leandrocp** [comment]
It's one of those cases where it get's formatted on the 1st pass, becomes "invalid" for `mix format --check-formatted`, and running it again get's it to the previous format:

```
iex> input = """                                                         
...> <span><%= link("Edit", to: Routes.post_path(@conn, :edit, @post)) %></span> |
...> <span><%= link("Back", to: Routes.post_path(@conn, :index)) %></span>
...> """

iex> IO.puts formatted = Phoenix.LiveView.HTMLFormatter.format(input, [])
<span><%= link("Edit", to: Routes.post_path(@conn, :edit, @post)) %></span>
| <span><%= link("Back", to: Routes.post_path(@conn, :index)) %></span>

iex> IO.puts Phoenix.LiveView.HTMLFormatter.format(formatted, [])
<span><%= link("Edit", to: Routes.post_path(@conn, :edit, @post)) %></span> |
<span><%= link("Back", to: Routes.post_path(@conn, :index)) %></span>
```

**Comment by leandrocp** [comment]
Changed examples moving the text `|` to the next line, which makes more sense considering it's surrounded by whitespaces and based on other tests.
