### ISSUE TITLE
Phoenix.LiveView.HTMLFormatter breaks Liveview flash

### ISSUE THREAD

**Issue by dewetblomerus** [phoenixframework/phoenix_live_view#2009]
### Environment

* Elixir version (elixir -v): 1.13.4
* Phoenix version (mix deps): 1.6.8
* Phoenix LiveView version (mix deps): 1.17.9
* Operating system: OSX
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, Firefox, Safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

A newly generated Phoenix App has a file at `lib/formatted_web/templates/layout/live.html.heex`

The following blue and red boxes appear as soon as the file is formatted:

<img width="797" alt="Screen Shot 2022-05-07 at 7 36 41 AM" src="https://user-images.githubusercontent.com/2397841/167252567-5e1ae014-6285-4986-903e-9f3d68ae478b.png">

The file can be formatted up to this point:

```
<main class="container">
  <p
    class="alert alert-info"
    role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p
    class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>
```

But as soon as the line `phx-value-key="error"><%= live_flash(@flash, :error) %></p>` get broken up into multiple lines, it breaks and renders the blue and red boxes

### Expected behavior

We can run `mix format` on all our `.heex` layout files without seeing blue and red boxes.

**Comment by josevalim** [comment]
Yes, this has been reported and there is an issue in Phoenix to tackle this. :)

**Comment by KristerV** [comment]
Discussion and solution suggestions here: https://elixirforum.com/t/how-to-remove-empty-flash-box-from-a-page/48615/3
