### ISSUE TITLE
HTML validations

### ISSUE THREAD

**Issue by feliperenan** [phoenixframework/phoenix_live_view#2015]
Related to: https://github.com/phoenixframework/phoenix_live_view/issues/1506

It would be nice if our HTML engine warn developers when their HTML is invalid. For instance, forms is not allowed within table tag according to HTML spec.

There are validations specific to some tags, as you can see [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/thead). I'm using these as reference to come up with a doc with all validations we could potentially introduce.

**Comment by thdaraujo** [comment]
Hi @feliperenan, I'd be interested in helping with this task. Is there anyone else working on it? How can I help?
Thanks!

**Comment by feliperenan** [comment]
Hi @thdaraujo 

I'm not working on this at the moment. When I created this issue I was looking for obvious validations we could introduce like forms within tables since following the whole spec will be complex and hard to maintain I guess.

One way we can go about it is listing the validations it would be nice to have so we can decide the ones it worth implementing? I'd appreciate some help in this area 🙌🏻

**Comment by SteffenDE** [comment]
@josevalim do you still know why this was closed without really implementing much?

Coming from https://github.com/phoenixframework/phoenix_live_view/issues/3284 I thought we could maybe warn if there are nested `<form>` tags.

**Comment by josevalim** [comment]
We implemented some of the most obvious ones and the idea was to implement others as needed. In other words, they are still welcome!
