### ISSUE TITLE
Wrap up declarative assigns API

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix_live_view#2016]
* [x] API docs (CM)
  * [x] Installation docs (mention `compilers: Mix.compilers() ++ [:phoenix_live_view]` in mix.exs) (CM)
  * [x] Update new app generator mix.exs (CM)
  * [x] Release a new version from v0.17 branch (CM)
  * [x] Check component from chunk attributes (MS)
  * [x] Do not default attrs to `nil` (conflicts on assign_new) (CM)
  * [x] Support :default (JV)
  * [x] Add basic types (:boolean / :integer / :float / :string / :list / :atom / :map) (JV)
  * [x] Add :global type (CM)
  * [x] Add :struct type (JV)
  * [x] Add attrs to existing components in LiveView.Helpers (CM)
  * [x] Automatically generate docs from attrs (CL)
  * [x] Slots
  * [ ] LiveComponents / LiveViews

Continuation of #1506.

**Comment by chrismccord** [comment]
Global is everything passed to the function that isn't declared, so how would you specify the different attribute groups? You'd have to segment them under a different attribute, in which case the existing features have you covered, no?, ie `<.email_input label={%{class: "foo"}} container={%{class: "bar"}}/>` etc. That said, you may also consider slots for this case, which would allow:

```
    <.email_input class="container-class">
      <:label class="label-class">My Label</:label>
      <:input class="input-class"/>
    </.email_input>

```

**Comment by rubas** [comment]
Thanks for clarifying 👍 . I just re-read the docs and the catch-call aspect of `:global` is/was missing for me. 

Based on the examples and the description, I figured it's just a struct with supported keys (global attributes) that can be passed.

- I suggest adding an example/sentence that highlights the "catch-al" aspect of it. 

https://github.com/phoenixframework/phoenix_live_view/blob/master/lib/phoenix_component.ex#L298
https://github.com/phoenixframework/phoenix_live_view/blob/master/lib/phoenix_component.ex#L343
