### ISSUE TITLE
Formatter drops EEx comments inconsistently

### ISSUE THREAD

**Issue by matthewlehner** [phoenixframework/phoenix_live_view#2026]
### Environment

* Elixir version (elixir -v): 1.13.4
* Phoenix version (mix deps): 1.6.8
* Phoenix LiveView version (mix deps): 0.17.9
* Operating system: MacOS 12.3.1
* Browsers you attempted to reproduce this bug on (the more the merrier): n/a
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: n/a

### Actual behavior

The HTMLFormatter seems to be behaving inconsistently with EEx comments in HEEx files.

Also, it looks like putting in `{ # this is a comment}` anywhere in the HEEx file works, which feels unexpected. I couldn't find anything about how curly braces work outside of their use for attributes/dynamic attributes.

Given the following HEEx file:

```heex
<div>
  <%# I'm an EEx comment tag %>
  <% # I _might_ be an EEx comment tag? %>
  {# I'm an HEEx expression, I guess? }
  { # Also an HEEx expression }
</div>
```
If I run `mix format` the output is:

```heex
<div>
  
  <% # I _might_ be an EEx comment tag? %>
  {# I'm an HEEx expression, I guess? }
  { # Also an HEEx expression }
</div>
```

### Expected behavior

It leaves the first comment in.

```heex
<div>
  <%# I'm an EEx comment tag %>  
  <% # I _might_ be an EEx comment tag? %>
  {# I'm an HEEx expression, I guess? }
  { # Also an HEEx expression }
</div>
```

**Comment by josevalim** [comment]
Correct. To repeat the docs:

```
  Inline comments `<%# comment %>` are deprecated and the formatter will discard them silently
  from templates. You must change them to the multi-line comment `<%!-- comment --%>` on
  Elixir v1.14+ or the regular line comment `<%= # comment %>`.
```
