### ISSUE TITLE
Unclear of where to put files based on the documentation

### ISSUE THREAD

**Issue by ukd1** [phoenixframework/phoenix_live_view#2029]
I'm just getting started with phoneix_live_view, and am getting stuck going through examples in the docs. Part of the issue is knowing where example files should go, and how they should be named. I'd expect it's obvious once you know, but as I don't and it's not specified in the examples, it makes things hard / impossible.

So, in https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#module-life-cycle

> A LiveView is a simple module that requires two callbacks: [mount/3](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#c:mount/3) and [render/1](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#c:render/1):

This first example is to me unclear where to put; I've tried ``lib/aal_web/thermostat_live.ex``, ``lib/aal_web/controllers/thermostat_live.ex`` and ``lib/aal_web/live/thermostat_live.ex``

<img width="1336" alt="image" src="https://user-images.githubusercontent.com/44345/168374142-6da7a31d-a6bc-4129-b7fc-88927f96e375.png">

... and have no idea which it is. Errors do not seem to suggest it's missing from a specific file, just `no function clause matching in AalWeb.ThermostatLive.mount/3` (as an Elixir beginner) a function matching that signature can't be found...

<img width="1329" alt="image" src="https://user-images.githubusercontent.com/44345/168374659-2dc60777-0fd9-4558-b005-e26b86beff79.png">

**Comment by josevalim** [comment]
Hi @ukd1! Where you put the file doesn't really matter, as long as it is in `lib` and it has the `.ex` extension. The issue you are running into is because you are expecting the session (the second argument to `mount`) to have a "current_user_id" field, but it does not. Perhaps the documentation should not assume something exists in the session and go with a simpler example (such as a counter) to showcase LiveView lifecycle.

**Comment by ukd1** [comment]
@josevalim thanks, and ah ok! re the example; a working example would be enough, though perhaps I missed a step. The location of the files being not important is interesting, and at least to me non-obvious.
