### ISSUE TITLE
"cannot consume uploaded files when entries are still in progress" when live_file_input outside of form

### ISSUE THREAD

**Issue by denvaar** [phoenixframework/phoenix_live_view#2030]
### Environment

* Elixir version (elixir -v): 1.13.3
* Phoenix version (mix deps): 1.6.8
* Phoenix LiveView version (mix deps): 0.17.9
* Operating system: MacOS Mojave
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

When I use a `live_file_input` outside of a form, I get the following error when submitting the form:

```
[error] GenServer #PID<0.1753.0> terminating
** (ArgumentError) cannot consume uploaded files when entries are still in progress
    (phoenix_live_view 0.17.9) lib/phoenix_live_view/upload.ex:238: Phoenix.LiveView.Upload.consume_uploaded_entries/3
    (primula 0.1.0) lib/primula_web/live/project_stepper_live.ex:38: PrimulaWeb.ProjectStepperLive.handle_event/3
    (phoenix_live_view 0.17.9) lib/phoenix_live_view/channel.ex:382: anonymous fn/3 in Phoenix.LiveView.Channel.view_handle_event/3
    (telemetry 1.1.0) /Users/denvaar/code/elixir-apps/primula/deps/telemetry/src/telemetry.erl:320: :telemetry.span/3
    (phoenix_live_view 0.17.9) lib/phoenix_live_view/channel.ex:215: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 3.17.1) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.17.1) gen_server.erl:771: :gen_server.handle_msg/6
    (stdlib 3.17.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

### Expected behavior

It's possible to place HTML input fields outside of the form they belong to, using the `form=` attribute ([ref](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fae-form)). This can be a helpful workaround to nesting multiple forms on a page.

Example:

```html
<form id="upload-form" for="uploads" action="#" method="post" phx-submit="upload-files" phx-change="validate-files"></form>

<label>
  <span>Select files</span>
  <%= live_file_input @uploads.documents, form: "upload-form" %>
</label>
<input type="submit" form="upload-form" value="Upload"  />
```

I would expect this to work the same as if the form wrapped `live_file_input`. It seems to me like it doesn't work because of the way the input is found in the dom, which expects it to be a child of the form:
- https://github.com/phoenixframework/phoenix_live_view/blob/master/assets/js/phoenix_live_view/dom.js#L51
- https://github.com/phoenixframework/phoenix_live_view/blob/master/assets/js/phoenix_live_view/live_uploader.js#L33

Thanks.

**Comment by Ayrdim** [comment]
I was also having this issue and it looks like it was because I was uploading after removing the `.live_file_input` element. Maybe someone else might find this useful.

E.g. This code will cause the above error:
```heex
        <div :if={Enum.empty?(@uploads.markdown.entries)} class="drop">
          <div>
            <img src="/images/upload.svg" />
            <div>
              <label for={@uploads.markdown.ref}>
                <span>Upload a file</span>
                <.live_file_input upload={@uploads.markdown} class="sr-only" />
              </label>
              <span>or drag and drop here</span>
            </div>
            <p>
              Upload markdown files here
            </p>
          </div>
        </div>
```

However changing to the following code resolves the issue:
```heex
        <div class="drop">
          <div>
            <img src="/images/upload.svg" />
            <div>
              <label for={@uploads.markdown.ref}>
                <span>Upload a file</span>
                <.live_file_input upload={@uploads.markdown} class="sr-only" />
              </label>
              <span>or drag and drop here</span>
            </div>
            <p>
              Upload markdown files here
            </p>
          </div>
        </div>
```

**Comment by kamaroly** [comment]
@Ayrdim  you just saved me a lot of time. Thanks 100x

**Comment by michaelst** [comment]
This also happened to me when I was using a phx-click action on my "save" button instead of submitting the form
