### ISSUE TITLE
Add phx-mounted

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix_live_view#2032]

**Comment by dvic** [comment]
Is this different from #1838 ?

**Comment by alexslade** [comment]
@chrismccord I hope this is the best place to ask. The docs say 

> If phx-mounted is used on the initial page render, it will be invoked only after the initial WebSocket connection is established. 

This means it's also invoked on first page render, which seems at odds with the goal of tracking when something is _added_. I can't seem to find a permutation here that will _not_ apply on the first load of the view, but will when the element is mounted to the existing view. (E.g. to show a new item being added to a list) 

Am I looking at this the wrong way?

**Comment by SteffenDE** [comment]
@alexslade I think the docs are actually wrong and `phx-mounted` is executed **before** the initial WebSocket connection. 

You are right that there's not a straightforward way to do something only when an element is freshly added. You should be able to achieve this with a hook on the todo list though. Something like this:

```javascript
const TodoList = {
  mounted() {
    this.todos = Array.from(this.el.children);
  }
  updated() {
    const children = Array.from(this.el.children);
    children.forEach(child => {
      if (!this.todos.includes(child)) {
        this.liveSocket.execJS(child, this.el.getAttribute("data-on-added"));
      }
    });
    this.todos = children;
  }
}
```

```heex
<ul id="todos" phx-hook="TodoList" data-on-added={JS.transition(...)}>
  <li :for={...}>...</li>
</ul>
```
