### ISSUE TITLE
Running hooks in dead views

### ISSUE THREAD

**Issue by mplatts** [phoenixframework/phoenix_live_view#2034]
I have some hooks for things like dark mode toggle and syntax highlighting. Since `app.js` loads on both live and dead views, I wanted to re-use my hooks. I wrote this and got it working, but was wondering if it's the best way:

```javascript
let liveSocket = new LiveSocket("/live", Socket, {
  hooks: {
    MyHook: {
      deadViewCompatible: true,
      mounted() {
        doStuff(this.el)
      }
    }
  },
  params: { _csrf_token: csrfToken },
});

docReady(() => {
  // If not a live view, still run hooks.
  if (!liveSocket.boundTopLevelEvents) {
    [...document.querySelectorAll("[phx-hook]")].map((hookEl) => {
      let hookName = hookEl.getAttribute("phx-hook");
      let hook = Hooks[hookName];

      if (hook.deadViewCompatible) {
        let mountedFn = hook.mounted.bind({ ...hook, el: hookEl });
        mountedFn();
      }
    });
  }
});
```

I wasn't sure how to check if this a dead view. For the moment I just check if `liveSocket.boundTopLevelEvents` is `false`. Guessing there is a better way...

**Comment by mayel** [comment]
Thanks for the hint @mplatts :)

**Comment by ChristianAlexander** [comment]
@mplatts, it's possible that this is no longer necessary now that hooks are supported in 0.18+ deadviews.

From [the changelog](https://hexdocs.pm/phoenix_live_view/0.18.0/changelog.html#0-18-0-2022-09-20):
> Add dead view support for hooks

**Comment by mplatts** [comment]
@ChristianAlexander Oh interesting... I'll have to test that out

**Comment by mayel** [comment]
@ChristianAlexander I couldn't find much documentation about that, since I have seperate JS files for the live and non-live parts of the app, I'm not sure what to put in the latter?
