### ISSUE TITLE
formatter inserts whitespace into the layout live.html.heex which cases the alerts to render improperly

### ISSUE THREAD

**Issue by koenusz** [phoenixframework/phoenix_live_view#2042]
### Encouragement

First of all I would like to thank you and everyone that has helped in making the Phoenix framework into what it is today. I hope that with reporting this issue I can help make the framework just that tiny little bit better.

### Environment

* Elixir version (elixir -v): 13.2
* Phoenix version (mix deps): 1.6.9
* Phoenix LiveView version (mix deps): 0.17.9
* Operating system: Linux/Ubuntu 20
* Browsers you attempted to reproduce this bug on (the more the merrier):  firefox and brave
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

The alert boxes in phoenix do not render properly when they are empty

![image](https://user-images.githubusercontent.com/5352759/170498421-a69c77ad-b3aa-4439-a949-783f91c9fcb4.png)

### Expected behavior

I expect the alerts to be hidden if there are no alerts that need to be shown.

### Problem analysis

This started happening after I added the Phoenix.LiveView.HTMLFormatter as a plugin to my .formatter.exs. The plugin adds some whitespace to the file live.html.heex which causes the following style in the app.css to fail:

```css
.alert:empty {
  display: none;
}
```

### Solution

I managed to solve this in my application by defining a helper function in the formatter configuration file that exludes the file in question. I suspect this is probably not the best solution to solve this issue but maybe it can serve as some inspiration.

```elixir
defmodule FHelper do

  def inputs(includes, excludes) do
    (Enum.flat_map(includes, &Path.wildcard(&1, match_dot: true)) -- excludes)
  end
end

[
  import_deps: [:ecto, :phoenix],
  plugins: [Phoenix.LiveView.HTMLFormatter],
  inputs:
    FHelper.inputs(
      [
        "*.{heex,ex,exs}",
        "priv/*/seeds.exs",
        "{config,lib,test}/**/*.{heex,ex,exs}"
      ],
      ["lib/vt_phx_web/templates/layout/live.html.heex"]
    ),
  subdirectories: ["priv/*/migrations"]
]
```

**Comment by feliperenan** [comment]
Hi @koenusz 👋🏻 

This issue is similar to this one https://github.com/phoenixframework/phoenix/pull/4818

At some point it will solved on Phoenix generator (in case you are using it) by this PR https://github.com/phoenixframework/phoenix/pull/4667. You could also use the same approach - moving your flash messages to be under a Phoenix component so that you don't need to exclude the file from Formatter.

Thanks 🙏🏻
