### ISSUE TITLE
Compiler error using master branch with Alpine.js custom markup

### ISSUE THREAD

**Issue by brainlid** [phoenixframework/phoenix_live_view#2049]
### Environment

* Elixir version (elixir -v): Elixir 1.13.4 (compiled with Erlang/OTP 24)
* Phoenix version (mix deps): 1.6.10
* Phoenix LiveView version (mix deps): master
* Operating system: Linux, Arch
* Browsers you attempted to reproduce this bug on (the more the merrier):  N/A
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: N/A

### Actual behavior

Using Alpine.js "extra" markup breaks when using current master version of LiveView. [Relevant Alpine.js docs](https://alpinejs.dev/essentials/templating#binding-attributes)

This example changes the `class` of an `svg` when a menu is open vs closed.

```html
            <svg x-show="mobileOpen" class="hidden h-6 w-6" :class="{ 'block': open, 'hidden': !(open) }" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
```

The problem is the `:class=` syntax. This creates the following compiler error.

```
== Compilation error in file lib/web/views/layout_view.ex ==
** (Phoenix.LiveView.HTMLTokenizer.ParseError) lib/web/templates/layout/root.html.heex:96:61: unsupported attribute ":class" in tags
    (phoenix_live_view 0.18.0-dev) lib/phoenix_live_view/html_engine.ex:1047: Phoenix.LiveView.HTMLEngine.validate_phx_attrs!/5
    (phoenix_live_view 0.18.0-dev) lib/phoenix_live_view/html_engine.ex:513: Phoenix.LiveView.HTMLEngine.handle_token/2
    (elixir 1.13.4) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix_live_view 0.18.0-dev) lib/phoenix_live_view/html_engine.ex:123: Phoenix.LiveView.HTMLEngine.handle_body/1
    (phoenix_live_view 0.18.0-dev) expanding macro: Phoenix.LiveView.HTMLEngine.compile/1
    lib/web/templates/layout/root.html.heex:1: Web.LayoutView."root.html"/1
    (phoenix_view 1.1.2) /home/mark/spice/apps/web/lib/web/views/layout_view.ex:1: Phoenix.Template.__before_compile__/1
```

This did not happen using LiveView 0.17.10.

### Expected behavior

I can see this as a challenging situation. Multiple different libraries (LiveView and Alpine.js) are expecting to find and use customized HTML markup. 

Ideally, this would not conflict.

**Comment by connorlay** [comment]
@feliperenan I suspect this is due to https://github.com/phoenixframework/phoenix_live_view/pull/2013 adding support for `:let` and friends, what do you think?

**Comment by brainlid** [comment]
Followup: 
- Here are the Alpine docs on this feature. https://alpinejs.dev/essentials/templating#binding-attributes
- Changing it to not use the short form worked. Requires adding `x-bind` prefix.

From:
```
:class="{ 'block': open, 'hidden': !(open) }"
```

To:
```
x-bind:class="{ 'block': open, 'hidden': !(open) }"
```

After the change, the Phoenix template compiled and the Alpine behavior still worked.

**Comment by kantum** [comment]
Coming from Vue I would love to be able to use the shorthand `:` syntax.

As I understand, [this line](https://github.com/phoenixframework/phoenix_live_view/blob/5a33080d3b92fe3656deb49c3b0bc6afe787e477/lib/phoenix_live_view/tag_engine.ex#L1009) defines a constant of liveview attributes and [this one](https://github.com/phoenixframework/phoenix_live_view/blob/5a33080d3b92fe3656deb49c3b0bc6afe787e477/lib/phoenix_live_view/tag_engine.ex#L1039) does the pattern matching that triggers the error.

I'm not sure about what this test is all about, it looks to me that it can be removed or just not raise an error as the other pattern will still match what is relative to liveview.

Can someone explain why it is needed, and if just ignoring it is a solution?
