### ISSUE TITLE
Question: Is there a simple JavaScript escape hatch for manually triggering LiveView events?

### ISSUE THREAD

**Issue by jwietelmann** [phoenixframework/phoenix_live_view#206]
## What I'm doing

Using the browser drag and drop API to order a list: https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API

## What I think I need

To write sprinkles of JavaScript that will trigger LiveView events from the drag and drop events.

## Looks sort of like this

```elixir
content_tag :tr, [
  draggable: "true",
  ondragover: "Dragdrop.dragover(this, event)",
  ondrop: "Dragdrop.drop(this, event)",
  data: [id: id],
] do
  # inner content
end
```

With this dirty JavaScript:

```javascript
class DragdropManager {
  dragover(destinationElement, event) {
    event.preventDefault()
    // TODO: trigger LiveView event
  }

  drop(sourceElement, event) {
    event.preventDefault()
    // TODO: trigger LiveView event
  }
}

window.Dragdrop = new DragdropManager()
```

But what I'd need to finish out are some docs (or maybe a pointer in comments) on how to get a JavaScript handle to the mounted LiveView and then manually send an event to it.

**Comment by chrismccord** [comment]
Not yet, but it's on the roadmap and isn't far off. Thanks!

**Comment by jwietelmann** [comment]
To answer my own question, after reading the source and experimenting, I discovered you can do something like this:

```javascript
function pushLiveViewEvent(liveSocket, element, event, value = "") {
  liveSocket.owner(element, (view) => view.pushWithReply("event", {
    type: "event",
    event,
    value,
  }))
}
```

**Comment by chrismccord** [comment]
Note that is a private API, so you shouldn't rely on it

**Comment by jwietelmann** [comment]
Understood. Keeping myself pinned to a commit until the real API ships.

**Comment by alecho** [comment]
Does anyone know is there's any movement on the public API for this?

**Comment by shahryarjb** [comment]
Hello, sir @chrismccord, Is it possible for you to tell about any movement for creating Drag and Drop API in Phoenix LiveView? because you said 

> Not yet, but it's on the roadmap and **isn't far off.** Thanks!


Thank you for all your efforts.
