### ISSUE TITLE
Heex class list notation doesn't work correctly when nested

### ISSUE THREAD

**Issue by LostKobrakai** [phoenixframework/phoenix_live_view#2066]
### Environment

* Elixir version (elixir -v): 1.13.4
* Phoenix version (mix deps): 1.6.10
* Phoenix LiveView version (mix deps): 0.17.10
* Operating system: Mac OS
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:

### Actual behavior

```
def nav_mobile_item(assigns) do
    color =
      if assigns[:active] do
        "bg-gray-100 text-gray-900"
      else
        "text-gray-600 hover:bg-gray-50 hover:text-gray-900"
      end

    icon_color =
      if assigns[:active] do
        "text-gray-500"
      else
        "text-gray-400 group-hover:text-gray-500"
      end

    assigns = assigns |> assign(:color, color) |> assign(:icon_color, icon_color)

    ~H"""
    <a href={@href} class={["group p-2 rounded-md flex items-center text-base font-medium", @color]}>
      <.svg name={@icon} class={["mr-4", @icon_color]} />
      <%= @title %>
    </a>
    """
  end
```

The svg here renders with `class="h-6 w-6 mr-4text-gray-400 group-hover:text-gray-500"`.

`<.svg />` also uses `class={["h-6 w-6", @class]}`

### Expected behavior

Spaces between all classes maintained.

**Comment by chrismccord** [comment]
In this case, I think the list is working by accident. I'd have to check, but I believe this is the Phoenix.HTML.Safe protocol concatenating the list for you – not us specifically handling a list for classes. What you want instead is `class={"group p-2 rounded-md flex items-center text-base font-medium #{@color}"}` . Thanks!

**Comment by LostKobrakai** [comment]
Isn't the list syntax supposed to prevent the need for string interpolation? This feels a bit half done if it's only usable on html elements, but not for passing into function components. Is there something, which would speak against having `class` work with nested lists of class names?

**Comment by chrismccord** [comment]
the problem is the list will always simply concatenate, so to support this you'd have to write `lcass={["group p-2 rounded-md flex items-center text-base font-medium", [" ", @color]}` or `class={["group p-2 rounded-md flex items-center text-base font-medium", " #{@color}"]}`

So there's no way to support this without surprises unless we special case the class attribute in the engine.

**Comment by josevalim** [comment]
We added support for actual lists when HEEx started. There is ambiguity but we thought it was worth it, especially for conditional classes.

**Comment by LostKobrakai** [comment]
There's for something else going on. The changes made on the phoenix_html side (both mine as well as jose's improvements) still leave my liveview component rendering the class without spaces.

**Comment by LostKobrakai** [comment]
I tested this yesterday with phoenix_live_view master besides the updated phoenix_html and it seemed to work fine there 🎉

**Comment by josevalim** [comment]
Yes, I fixed the logic on LiveView too :) because we have some duplication when inlining some attributes.
