### ISSUE TITLE
Template and Liveview do not get the same assigns when rendering

### ISSUE THREAD

**Issue by isaksky** [phoenixframework/phoenix_live_view#207]
### Environment

* Elixir version (elixir -v): Elixir 1.8.1
* Phoenix version (mix deps): 1.4.3
* NodeJS version (node -v): 11.13.0
* NPM version (npm -v): 6.9.0
* Operating system: Win 10 / WSL

### Actual behavior

If I print out the same `assigns` variable in the template and the live view .leex.html file, I get different results.

### Expected behavior

The template and liveview should see the same assigns, at least for static_mount.

### Details

In my case, since I'm doing `socket |> assign(session)` in my `mount`, [this change](https://github.com/isaksky/phoenix_live_view/commit/f885892473fc75bfa2b96e8fe3bebd54a00c010c) worked for me, but it probably isn't good enough as a general purpose solution.

What I'm trying to achieve is to pass assigns from my controller that are visible in the template, just like one would for normal Phoenix views. (E.g., assigns like `:page_title`.)

**Comment by isaksky** [comment]
Created a PR now that has a real fix (I think).

**Comment by josevalim** [comment]
See the PR for the rationale for closing this. Thanks!
