### ISSUE TITLE
Standalone Attribute in checkbox: Enumerable not implemented for "checked"

### ISSUE THREAD

**Issue by christo-ph** [phoenixframework/phoenix_live_view#2070]
### Environment

* Elixir version (elixir -v): 1.13.4
* Phoenix version (mix deps): 1.6.10
* Phoenix LiveView version (mix deps): 0.17.10
* Operating system: Macos

### Actual behavior
When trying to render standalone attributes like checkbox based on a condition:

```
<input type="checkbox" name={col} value="true" {if @show_cols[col], do: "checked"} >
```

I get:

```
** (exit) an exception was raised:
    ** (Protocol.UndefinedError) protocol Enumerable not implemented for "checked" of type BitString
        (elixir 1.13.4) lib/enum.ex:1: Enumerable.impl_for!/1
        (elixir 1.13.4) lib/enum.ex:143: Enumerable.reduce/3
        (elixir 1.13.4) lib/enum.ex:4144: Enum.reverse/1
        (elixir 1.13.4) lib/enum.ex:3491: Enum.to_list/1
        (phoenix_html 3.2.0) lib/phoenix_html.ex:212: Phoenix.HTML.attributes_escape/1
```

When I change to 

```
<input type="checkbox" name={col} value="true" checked={@show_cols[col]} >
```

It is working, but not valid, as `false` is not interpreted as unchecked in HTML standard.

### Expected behavior

`checked` shall be rendered as in other "assigned" attributes simply as a string inside the HTML tag.

**Comment by josevalim** [comment]
Stand-alone attributes must be keyword lists or maps. If you need to render something else, then you cannot use booleans, you can render empty strings and “checked” as values, for example.

**Comment by christo-ph** [comment]
Not sure I understand this correctly. I could get the desired behavior working with:

```
 <input type="checkbox" name={col} value="true" {checked?(@show_cols[col])} >
```

and `checked?` implemented with

```
def checked?(value) do
    case value do
      "true" -> %{"checked" => "checked"}
      "false" -> %{"checked" => nil}
    end
  end
```

But not with keyword lists. This looks for me quite cumbersome - is it done properly? Is there some documentation available for this behavior?

Thanks

**Comment by josevalim** [comment]
> But not with keyword lists. 

can you let me know what you tried?

In any case, I see the issue with the complete code. `@show_cols[col]` is returning a string, not a boolean. This is what you want:

    <input type="checkbox" name={col} value="true" checked={@show_cols[col] == true} >

**Comment by christo-ph** [comment]
That's interesting, I was assuming `checked=<whatever>` is interpreted as checked according to HTML: only the absence of the entire attribute is considered as `false`. (i.e. https://stackoverflow.com/a/4613192)

I do have an initial state of the checkboxes, might be checked or not. And depending on the checked ones, a data table show the columns or not.

Thank you.
