### ISSUE TITLE
Cannot set live layout in router / live_session / on_mount

### ISSUE THREAD

**Issue by inoas** [phoenixframework/phoenix_live_view#2071]
### Environment

* Elixir version (elixir -v): Elixir 1.13.4
* Phoenix version (mix deps): 1.6.6
* Phoenix LiveView version (mix deps): 0.17.9
* Operating system: macOS 11.6.7

### Actual behavior

Setting live layout in `router.ex` or `on_mount` callback seems impossible.

Tried:

```elixir
  pipeline :layout do
    plug :put_root_layout, {AquaWeb.LayoutView, :root}
    plug :put_layout, {AquaWeb.LayoutView, :app}
  end

  pipeline :live_layout do
    plug :put_root_layout, {AquaWeb.LayoutView, :root}
    plug :put_layout, {AquaWeb.LayoutView, :live}
  end

  pipeline :admin_layout do
    plug :put_root_layout, {AquaWeb.LayoutView, :admin_root}
    plug :put_layout, {AquaWeb.LayoutView, :admin_app}
  end

  pipeline :admin_live_layout do
    plug :put_root_layout, {AquaWeb.LayoutView, :admin_root}
    plug :put_layout, {AquaWeb.LayoutView, :admin_live}
  end
```

```elixir
  scope "/admin", AquaWeb.Admin, as: :admin do
    pipe_through [:browser, :require_authenticated_admin_user, :admin_layout]

    get "/", PageController, :index

    import Phoenix.LiveDashboard.Router
    live_dashboard "/system", metrics: AquaWeb.Telemetry

    live_session :default, on_mount: AquaWeb.UserAuthLive do
      pipe_through [:admin_live_layout]

      live "/pages", PageLive.Index, :index
      live "/pages/new", PageLive.Index, :new
      live "/pages/:id/edit", PageLive.Index, :edit

      live "/pages/:id", PageLive.Show, :show
      live "/pages/:id/show/edit", PageLive.Show, :edit
      # ...
```

Which silently "fails", aka does not throw any error or warning about `admin_live_layout` not applying the layout. Because `MYAPP_web.ex` has a macro that defines the live layout:

```elixir
  # Sets the de facto layout for live_views
  def live_view do
    quote do
      use Phoenix.LiveView,
        layout: {AquaWeb.LayoutView, "live.html"}

      unquote(view_helpers())
    end
  end

  # my solution for now, requires all admin live views to `use :admin_live_view`, thus not DRY
  def admin_live_view do
    quote do
      use Phoenix.LiveView,
        layout: {AquaWeb.LayoutView, "admin_live.html"}

      unquote(view_helpers())
    end
  end
```

* * *

In addition there is no way to specify the live layout in on_mount callbacks as these require to return `{:cont | :halt, socket}`

So something like this cannot be returned:

`{:ok, socket, layout: {MyAppWeb.LayoutView, "live.html"}}`

### Expected behavior

1. Be able to set the live layout via the router.
2. Not have the live layout be set via `MYAPP_web.ex` for the initial phoenix skeleton / EDIT: Or should at least be overwritable by 1. and/or 3.
3. Be able to set the live layout in the on_mount callback.

**Comment by josevalim** [comment]
The priority is typically locality/closeness: a module is closer to the source than the router, so a module should always win. If you want, you can provide a pull request for 3. But the priority today is correct.

**Comment by inoas** [comment]
Understood the priority. What about 1. and simply set it there instead of in the generated macro `live_view` in `MYAPP_web.ex` ?

**Comment by inoas** [comment]
Another idea would be to allow `:layout` for live_session in routes?

**Comment by josevalim** [comment]
> Another idea would be to allow :layout (it can already set :root_layout) for live_session in routes?

Seems fine!
