### ISSUE TITLE
Duplicate `data-phx-link-state` in `<.link>`

### ISSUE THREAD

**Issue by LostKobrakai** [phoenixframework/phoenix_live_view#2081]
### Environment

* Elixir version (elixir -v):
* Phoenix version (mix deps):
* Phoenix LiveView version (mix deps):
* Operating system:
* Browsers you attempted to reproduce this bug on (the more the merrier): 
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:

### Actual behavior

https://github.com/phoenixframework/phoenix_live_view/blob/3507c989c771991cf4e48a062de4881e765f2629/lib/phoenix_live_view/helpers.ex#L1245-L1246

### Expected behavior

I think the first `data-phx-link-state` is a duplicate.

**Comment by josevalim** [comment]
PR please? :)
