### ISSUE TITLE
push_redirect/2 related LiveView JS bug not solved

### ISSUE THREAD

**Issue by DaTrader** [phoenixframework/phoenix_live_view#2082]
@chrismccord 

I'm afraid it's not. I've migrated the cards_demo2 to to 0.17.9 (running on Erlang 24.3 and Elixir 1.13.4.) and it still features the same LV bug as originally reported,

Same repo as before: https://github.com/DaTrader/cards_demo2

_Originally posted by @DaTrader in https://github.com/phoenixframework/phoenix_live_view/issues/1520#issuecomment-1159688829_

**Comment by DaTrader** [comment]
UPDATE:

When submitting this issue I didn't realize there were issues with static files in the demo project when migrating to esbuild. Those issues have been fixed and the now properly migrated project demonstrates the #1520 issue (again).

**Comment by lessless** [comment]
Thank you for your persistence!

**Comment by SteffenDE** [comment]
Hi @DaTrader, can you check if this still happens in recent versions of LiveView? I checked you repo with LV 0.20 and cannot reproduce the problem you've described concerning the "Clicked" message not updating.

If you do indeed see this happening, I'd recommend you to open a new issue with a minimal single-file example that shows it and steps to reproduce.

Thank you!
