### ISSUE TITLE
live_patch/2 live_redirect/2 overrides phx-click 

### ISSUE THREAD

**Issue by MartinElvar** [phoenixframework/phoenix_live_view#2083]
### Environment

* Elixir version (elixir -v):
Erlang/OTP 24 [erts-12.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit]
Elixir 1.13.1 (compiled with Erlang/OTP 24)
* Phoenix version (mix deps):
1.6.10
* Phoenix LiveView version (mix deps):
0.17.10
* Operating system:
Arch Linux
* Browsers you attempted to reproduce this bug on (the more the merrier):
Brave

### Actual behavior

Stumbled upon this issue while re-building a dropdown menu in my header. Using LiveView.JS i ended up with the following code.

```
                  <button
                    class="ml-4 px-3 py-2 rounded-md text-sm font-medium leading-5 text-olaf hover:text-olaf hover:bg-flatearth focus:outline-none focus:text-olaf focus:bg-flatearth"
                    phx-click={JS.toggle(to: "#community-menu")}
                    phx-click-away={JS.hide(to: "#community-menu")}
                  >
                    Community
                  </button>

                  <div
                    id="community-menu"
                    class="hidden origin-top-right absolute mt-2 w-48 bg-flatearth shadow-lg"
                  >
                    <div
                      class="py-1 rounded-md shadow-xs"
                    >
                      <%= live_patch("Utility applications",
                        to: Routes.product_application_index_path(@socket, :index),
                        phx_click: JS.hide(to: "#community-menu"),
                        class:
                        "block px-4 py-2 text-sm leading-5 text-olaf hover:bg-pantera focus:outline-none focus:bg-gray-100 transition duration-150 ease-in-out"
                      ) %>
                    </div>
                  </div>
```

This will toggle my dropdown on click, and also hide it on click away, my problem is that clicking the "Utility applications" link inside the dropdown does not hide the menu. It seems like the javascript part of LiveView hijacks the click handler. If i change live_patch to link, everything works fine (It's removed before the page redirects). 
This worked as intended with AlpineJS.

Not sure if this is a bug, or intended, you can let me know. :slightly_smiling_face:

**Comment by chrismccord** [comment]
This is supported on master. Thanks!
