### ISSUE TITLE
Adding `:prompt` to `select` breaks generated live view tests for obligatory `belongs_to`

### ISSUE THREAD

**Issue by inoas** [phoenixframework/phoenix_live_view#2089]
### Environment

* Elixir version (elixir -v): `Erlang/OTP 25 [erts-13.0] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns] Elixir 1.13.4 (compiled with Erlang/OTP 25)`
* Phoenix version (mix deps): `1.6.10`
* Phoenix Live View: `0.17.10`
* Operating system: `mac os 11.6.7`

### Actual behavior

I have belongs_to relationships that may not be null:

* `add :media_id, references(:medias, on_delete: :nothing), null: false`.
* `:media_id` in `cast([])` and `validate_required([])`.
* `foreign_key_constraint(:media_id, message: "Media required")`.

Everything runs fine, but the LV tests fail once I add an empty select option. I have tried two ways:

1st attempt:

```elixir
<%= select(
  f,
  :media_id,
  [
    [
      key: "Please select Media…",
      value: "",
      disabled: true,
      selected: @article_attribute_value.media_id == nil
    ]
  ] ++
    @medias
) %>
```

2nd attempt:

```elixir
<%= select(
  f,
  :media_id,
  @medias,
  prompt: "Please select Media…"
) %>
```

### Expected behavior

Now the latter does not disable the element which means the earlier is preferred, but I expected at least the latter to work out of the box.

I have tried to get to mimick something like `querySelector("#select_element_selector_here option:last-child").value` with `element()` to set @create_attrs to that, but wasn't successful.

```elixir
{:ok, _, html} =
  index_live
  |> form("#article_attribute_value-form", article_attribute_value: @create_attrs)
  |> render_submit()
  |> follow_redirect(conn, Routes.admin_article_attribute_value_index_path(conn, :index))
```

I have looked for so that a user can select the 2nd option of the select by calling live view functions but could not find a way to do that either.

In the end I can either discard the tests or do not show a prompt which means the first option in selects for belongs_to relationships is auto selected for creating new records which can lead to user input errors (accidentially not selecting a correct relationship).

The only other thing I can think of is to create the media fixtures with static primary keys to be references in `@create_attrs`.

**Comment by inoas** [comment]
As a sidenote:

`selected: @article_attribute_value.media_id == nil` was required because otherwise not even updating records tests would run. Why:

* The browser behavior is to take the **LAST** `<option>` for a `<select>` that has `selected="selected"` set as the value submitted for the parent `<select>`.
* Live view tests take the **FIRST** `<option>` for a `<select>` that has `selected="selected"` set as the value submitted for the parent `<select>`.

**Comment by LostKobrakai** [comment]
> The only other thing I can think of is to create the media fixtures with static primary keys to be references in @create_attrs.

That sound like it might be time to drop the use of static inputs for your tests.

**Comment by inoas** [comment]
Thank you a lot @LostKobrakai :)
