### ISSUE TITLE
Live view has inverse priority for `selected="selected"` `<option>` versus browser reality

### ISSUE THREAD

**Issue by inoas** [phoenixframework/phoenix_live_view#2090]
### Environment

* Elixir version (elixir -v): `Erlang/OTP 25 [erts-13.0] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns] Elixir 1.13.4 (compiled with Erlang/OTP 25)`
* Phoenix version (mix deps): `1.6.10`
* Phoenix Live View: `0.17.10`
* Operating system: `mac os 11.6.7`

### Actual behavior

Note: `prompt:` gets around this problem, but there is no way (to my knowledge) to add `disabled="disabled"` to the prompt option, which is recommended UX in most cases.

```elixir
<%= select(
  f,
  :media_id,
  [
    [
      key: "Please select Media…",
      value: "",
      disabled: true
    ]
  ] ++
    @medias
) %>
```

This would make generated live view tests that test record updates fail, because there are 2 `<option/>` tags having `selected="selected"`.

This can be amended like so:

```elixir
<%= select(
  f,
  :media_id,
  [
    [
      key: "Please select Media…",
      value: "",
      disabled: true,
      selected: @article_attribute_value.media_id == nil
    ]
  ] ++
    @medias
) %>
```

However the testing result just differs from browser reality.
The application works in the browser just fine, because for multiple `<option>` with `selected="selected"` the browser will pick the last per `<select>` to use as the value, where live view will pick the first.

### Expected behavior

* While update the record there can be 2 `<option>` with `selected="selected"`: 1. The prompt and 2. the currently associated foreign key.
* The browser behavior is to take the LAST `<option>` for a `<select>` that has `selected="selected"` set as the value submitted for the parent `<select>`.
* Live view tests take the FIRST `<option>` for a `<select>` that has `selected="selected"` set as the value submitted for the parent `<select>`.

**Comment by LostKobrakai** [comment]
> Note: prompt: gets around this problem, but there is no way (to my knowledge) to add disabled="disabled" to the prompt option, which is recommended UX in most cases. 

I'd push back on that claim. A disabled prompt has multiple issues to it. It's not shown to the user given selection falls on the first non-disabled option (so not really a prompt anymore). Also pre-selecting an option won't force a selection from the user, which is usually the reason for adding the prompt. The pre-selected item might stay selected by accident.

**Comment by inoas** [comment]
Thank you a lot @LostKobrakai :)
