### ISSUE TITLE
Make `PUSH_TIMEOUT` configurable

### ISSUE THREAD

**Issue by luka-TU** [phoenixframework/phoenix_live_view#2092]
### Environment

* Elixir version (elixir -v): `1.13.2`
* Phoenix version (mix deps): `1.6.10`
* Phoenix LiveView version (mix deps): `0.17.10`
* Operating system: any
* Browsers you attempted to reproduce this bug on (the more the merrier):  chrome, safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes

### Actual behavior
I need to upload large files (1GB+). Around the moment when the upload is about to be consumed a page reload happens.
As far as I can tell this is the timeout that governs it: https://github.com/phoenixframework/phoenix_live_view/blob/83292c44eb6477b1dce53786c61c387ff9c3e06f/assets/js/phoenix_live_view/constants.js#L62

### Expected behavior
Is it possible to make this param configurable?

**Comment by chrismccord** [comment]
We could m make this configurable, but I am not convinced yet you want to bump it higher. If after submitting a form takes the backend > 30s to process before updating the UI, you very likely want to do your file processing is another process and yield back to the UI, then report progress/completion after that. You can see an example of this in the LiveBeats code: https://github.com/fly-apps/live_beats/blob/master/lib/live_beats_web/live/profile_live/upload_form_component.ex#L138-L151 thanks!

**Comment by luka-TU** [comment]
@chrismccord the approach you mentioned could be useful for us as well, but I have one question: will postponing the entry consumption keep the temp file that was uploaded until the consumption is done?
