### ISSUE TITLE
Mix format deletes code commented out with `<%# %> `

### ISSUE THREAD

**Issue by herbedev** [phoenixframework/phoenix_live_view#2098]
### Environment

* Elixir version (elixir -v): Elixir 1.13.4 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): 
* Phoenix LiveView version (mix deps): 0.17.10
* Operating system: Mac OS 12.4
* Browsers you attempted to reproduce this bug on (the more the merrier): N/A
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

Mix format deletes code commented out with `<%# %>`
ie: 

```elixir
~H"""
<%# <footer>
</footer> %>
"""
```
will render an empty string after mix format is done with it

### Expected behavior

It does not delete commented out code?

**Comment by feliperenan** [comment]
This way of commenting is deprecated. You need to use <%-- ... %> now.

**Comment by josevalim** [comment]
To complement, this is documented in the docs. You can use `<%-- ... %>` from Elixir v1.14. Meanwhile, add a space between `<% #`. :)
