### ISSUE TITLE
`live_file_input` clears other form elements after selecting files

### ISSUE THREAD

**Issue by nathanalderson** [phoenixframework/phoenix_live_view#2109]
### Environment

* Elixir version (elixir -v): 1.13.4 (Erlang/OTP 24)
* Phoenix version (mix deps): 1.6.11
* Phoenix LiveView version (mix deps): 0.17.11
* Operating system: Arch Linux
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox, Chrome, Edge (all on Linux)
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

On a Live View page with a `live_file_input`, selecting a file with the file input clears any other input elements on the page.

I have reproduced this using a minimal project built from `mix phx.new` and using essentially the example code from https://hexdocs.pm/phoenix_live_view/uploads.html.

```elixir
defmodule LiveFileInputDemoWeb.UploadLive do
  use Phoenix.LiveView
  require Logger

  @impl Phoenix.LiveView
  def render(assigns) do
    ~H"""
    <form id="upload-form" phx-submit="save" phx-change="validate">
      <textarea id="the-textarea" />
      <%= live_file_input @uploads.avatar %>
      <button type="submit">Upload</button>
    </form>

    <section phx-drop-target={@uploads.avatar.ref}>
      <%= for entry <- @uploads.avatar.entries do %>
        <p><%= entry.client_name %></p>
      <% end %>
    </section>
    """
  end

  @impl Phoenix.LiveView
  def mount(_params, _session, socket) do
    {:ok, socket |> allow_upload(:avatar, accept: ~w(.jpg .jpeg), max_entries: 2)}
  end

  @impl Phoenix.LiveView
  def handle_event("validate", _params, socket) do
    {:noreply, socket}
  end

  @impl Phoenix.LiveView
  def handle_event("save", _params, socket) do
    consume_uploaded_entries(socket, :avatar, fn %{path: path}, _entry ->
      Logger.info("Consumed #{path}")
      {:ok, nil}
    end)

    {:noreply, socket}
  end
end
```

A full project with this live_view mounted at `/upload` can be found [here](https://github.com/nathanalderson/live_file_input_demo).

To reproduce:

1. Visit the page
2. Type some text into the `textarea`
3. Click "Browse..." on the file input, select a file, and click "OK"
4. The `textarea` will be cleared

A few other notes:

* Removing the `phx-change` handler on the form fixes this behavior. Of course, then the `live_file_input` doesn't function correctly, but I thought I would mention it.
* It doesn't seem to matter if the `textarea` is outside of the form or even in another form.
* It happens with an `<input>` element as well.

### Expected behavior

Selecting a file should not affect other input elements on the page.

**Comment by ryanjafari** [comment]
Thanks for filing this @nathanalderson, we are grappling with this now as well. Seems it has been a while without any activity so I will take a look at this tonight with your helpful hints.

**Comment by ryanjafari** [comment]
So I looked into this for a few hours trying a bunch of things. I looked into the JS end of `phoenix_live_view` and of course it is resetting that field with `moprhdom` but the question is why. I will try and look more into the Elixir end of it today.

**Comment by chrismccord** [comment]
This is expected. You need to maintain the form values yourself in assigns and set them on the inputs, or mark the inputs with phx-update=ignore. Thanks!

**Comment by ryanjafari** [comment]
Awesome, thanks @chrismccord this helped us out a lot. @nathanalderson, our `validate` function now looks like:

```
  def handle_event("validate", %{"package" => package}, socket) do
    {:noreply, socket |> assign(:package_changeset, Package.changeset(%Package{}, package))}
  end
```

This will make sure the form keeps its data after the upload attachment. For you it doesn't look like you have your `textarea` bound to anything, so if you'd like to get your simple demo working I'd imagine you'd have to, like Chris says, maintain the form values yourself. Perhaps something like:

```
def handle_event("validate", params, socket) do
  # get the textarea value here, may need to add a "name" attr to the textarea
  # value = params[:name]
  # in some way, assign the textarea value to the socket so it adds it back to the textarea
  # {:noreply, socket |> assign(...value...)}
  # ???
end
```

Haha, I'm new to Phoenix so that's the best I got for now. Be well.

**Comment by nathanalderson** [comment]
Yes, this can be done. It's just an extra burden that I didn't expect to be necessary.
