### ISSUE TITLE
Improvement: <.live_component module={MyFancyComponent} ...> => <.MyFancyComponent ...>

### ISSUE THREAD

**Issue by DaTrader** [phoenixframework/phoenix_live_view#2110]
An plans of making it happen?

Thanks

**Comment by josevalim** [comment]
Zero plans. :) calls to live component should be as explicit as it gets given they have their own state.

**Comment by DaTrader** [comment]
@josevalim I don't get it. What does live components having their own state have to do syntactic sugar and making things more shorter?

For instance, I have several such generic components (with their own state) and it'd be soo nice if they could fit into a single line along together with their arguments (akin to Surface)

**Comment by DaTrader** [comment]
As a reminder.. Having the ability of using slots along with let={} encourages the creation of generic (content neutral) components both stateless and statefull.
