### ISSUE TITLE
Setting a url path breaks LiveView's websocket (due to app.js)

### ISSUE THREAD

**Issue by starkeepers** [phoenixframework/phoenix_live_view#2111]
### Environment

LiveView 0.17.5, phoenix 1.6.6 , Elixir 1.13.0, Ubuntu 20.04.1 (firefox, chrome)

### The issue

When a url config has a path, as in:

```
config :foo, FooWeb.Endpoint,
  url: [..., path: "/a/b", ...]
```

The endpoint correctly sets up a websocket at `/a/b/live/websocket`, but app.js ignores the path prefix and tries to communicate with an inexistent `/live/websocket`, breaking LiveView.

### A fix

I worked around this by first changing app.js from

```
let liveSocket = new LiveSocket("/live", Socket, {params: {_csrf_token: csrfToken}})
```

to

```
let socketPath = window.phx_path_prefix || "/live"
let liveSocket = new LiveSocket(socketPath, Socket, {params: {_csrf_token: csrfToken}})
```

And then adding this in the head of the layout:

```
    <%= path = Application.get_env(:foo, FooWeb.Endpoint)[:url][:path]
        if path do %>
         <script type="text/javascript">window.phx_path_prefix="<%= path %>"</script>
    <% end %>
```

**Comment by josevalim** [comment]
Yes, the fix is the way to go! We don’t plan to do this change by default to keep it simple for now! Thanks for the issue though, it can help others who may want to do the same!

**Comment by travisgriggs** [comment]
Is this still the recommendation? I'm struggling to get my LiveView app running behind nginx for ssl with a subpath. But I see this issue is 2 years old now. Is there some other fix/configuration I'm expected to employ to make this work now?

I'm surprised this is as it is. I would have thought subpath'ing applications would be common?

**Comment by adamtharani** [comment]
Running into this same issue, does any one have any insight on getting this working in todays versions?

**Comment by SteffenDE** [comment]
@adamtharani it should still work the same: you set the path in the URL config of the endpoint and you ensure that the app.js also contains the prefix for the LiveSocket.

**Comment by adamtharani** [comment]
@SteffenDE thanks, I _think_ I found my issue being with my CDN provider
