### ISSUE TITLE
`upload_name` in `allow_upload` requires an atom but a string would make more sense

### ISSUE THREAD

**Issue by luka-TU** [phoenixframework/phoenix_live_view#2116]
### Environment

* Elixir version (elixir -v): all
* Phoenix version (mix deps): all
* Phoenix LiveView version (mix deps): all
* Operating system: macOs
* Browsers you attempted to reproduce this bug on (the more the merrier):  all
* Does the problem persist after removing "assets/node_modules" and trying again? Yes

### Actual behavior

`allow_upload` requires an `upload_name` as an argument, and it requires an atom.
We generate multiple uploads dynamically so we have to construct this argument to make it unique, converting it from string via `String.to_atom`.

### Expected behavior
I think making it into a string makes sense to avoid multiplying atoms.

**Comment by kenpb** [comment]
Hey, I also have the dynamically defined uploads use case, I found this post from @chrismccord where he pointed that both should be allowed https://elixirforum.com/t/dynamic-file-uploads-using-liveview/37915/10 this is not the case though.
