### ISSUE TITLE
Replacing tags in %Phoenix.LiveView.Rendered{} :static field works but not with varying use of a same component

### ISSUE THREAD

**Issue by DaTrader** [phoenixframework/phoenix_live_view#2118]
### Environment

* Elixir version (elixir -v): 1.13.4
* Phoenix version (mix deps): 1.6.7
* Phoenix LiveView version (mix deps): 0.17.11
* Operating system: Linux Mint
* Browsers you attempted to reproduce this bug on (the more the merrier): FF, Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

I have built a set of stateful helper components to facilitate the use of my auto-sorting (optimized insert/delete/replace items) list framework.

An example of the template code looks like this:

```
<.live_component
  module={ ListComponent} tag={ :div} adapter={ CardListilled} state={ assigns} let={ card_assigns}
  id="dln-cards" class="DealingDeck">

  <.live_component
    module={ ItemComponent} tag={ :div} state={ card_assigns}
    id={ "dln-card-#{ card_assigns.id}"} class="Card">

    <div>Some title <%= card_assigns.id %></div>

    <.live_component
      module={ ListComponent} tag={ :ul} adapter={ EntryListilled} state={ card_assigns} let={ entry_assigns}
      id={ "dln-entries-#{ card_assigns.id}"}>

      <.live_component
        module={ ItemComponent} tag={ :li} state={ entry_assigns}
        id={ "dln-#{ entry_assigns.class}-#{ entry_assigns.id}"} class={ "dln-#{ entry_assigns.class}"}>

        <div id={entry_assigns.id}><%= entry_assigns.entry.summary %></div>

      </.live_component>
    </.live_component>
  </.live_component>
</.live_component>
```

Please note that in the outer list (the list of lists) I am using `<div>` as the tag for both the list and the item component, while I wish to use `<ul>` and `<li>` for the inner list and item components respectively.

Since there's no other way to parametrize tags for a LiveComponent, I am simply doing the following in the ListComponent `render/1` function (and a similar thing in the ItemComponent `render/1` function)

```
def render( assigns) do
  ~H"""
  <listill_tag phx-update={ phx_update( @item_list_update)} { @attrs}>
    <%= for item <- @item_list_assigns do %>
      <%= render_slot( @inner_block, item) %>
    <% end %>
  </listill_tag>
  """
  |> replace_tag( "listill_tag", assigns[ :tag] || :div)
end

@spec replace_tag( Phoenix.LiveView.Rendered.t(), term(), term()) :: Phoenix.LiveView.Rendered.t()
defp replace_tag( rendered, old_tag, new_tag) do
  old = to_string( old_tag)
  new = to_string( new_tag)

  struct!( rendered, static: Enum.map( rendered.static, &String.replace( &1, old, new)))
end
```

If I deserve a "big no-no" lecture for my good intentioned code above, so be it, but please realize we need a way to parametrize tags in live components (the :content_tag is unusable since it does not support change tracking).

Anyway, when rendered, my tag replacement changes in the inner instances of ListComponent and ItemComponent are ignored and the `<div>` tag will be used as it was first configured for the outer instances of the same components. This looks to me as an optimization effort at the live component module level, since LiveView probably figures those are the same components so they static fields should be the same as well.

I am not sure if this is a bug, a flaw or a desired side-effect of the optimization. Maybe it's the desired behavior, but even if so, I'd like to call for a reconsideration.

PS. I am aware I could probably use a macro to have different component modules for each component use in the template, but that would be a forced creation of otherwise unnecessary modules to work around this issue.

### Expected behavior

Each LiveComponent should render the exact `Phoenix.LiveView.Rendered` structure that is returned by its `render/1` function.

**Comment by josevalim** [comment]
It is a big no-no. Each rendered struct has a fingerprint. Once you change the contents and the fingerprint stays the same, then you will confuse LiveView. Messing up with the internals is going to bite you one way or the other.

**Comment by DaTrader** [comment]
@josevalim 

And I guess using a copy-paste of the code below (given it's originally private) is another big no-no because 'inner workings subject to change any moment without prior notice'?

```
defp fingerprint(block, static) do
  <<fingerprint::8*16>> =
    [block | static]
    |> :erlang.term_to_binary()
    |> :erlang.md5()

  fingerprint
end
```
