### ISSUE TITLE
Allow more control of session storage?

### ISSUE THREAD

**Issue by jjcarstens** [phoenixframework/phoenix_live_view#212]
In some cases one might use a controller to do lookups and perform validations before passing session info to the LiveView to render via a `live_render` call. But its bad pattern to put full structs and data pieces in a session passed to the live view because it creates giant session tokens (i.e. `live_render(App.Endpoint, UserLive, session: %{user: user, favorites: favs}`, etc). This means to fit pattern in a typical use-case, one would query user info in the controller, do validations, pass the id to LiveView which then does another lookup which is not very ideal for those wanting more DB control.

It would be nice if there was a mechanism to allow passing full data and structs in a session, but customizing what actually gets stored in the session for little more explicit control. something like:
```elixir
defmodule MyController do
  def show(conn, params) do
    # do some DB work
    user = User.lookup(params["id"])
           |> validate_permisions
           |> preload
           
    live_render(
      conn,
      UserLive,
      session: %{user: user},
      session_store: %{user_id: user.id}
    )
  end
end

# in LiveView
defmodule UserLive do
  use Phoenix.LiveView
  
  # Session given directly from live_render
  # called elsewhere
  def mount(%{user: user}, socket) do
    {:ok, assign(socket, :user, user)}
  end
  
  # We may be in disconnected state and this is restored
  # from session store on page. No need to do validations at this
  # point, just lookup and go
  def mount(%{user_id: user_id}, socket) do
    mount(%{user: User.lookup(user_id)}, socket)
  end
end
```

**Why not just do all the lookups/validations in LiveView and skip controller?**
Well, very valid question. For any new LiveView app, I'd definitely recommend that. However, sometimes that's not as easy when you want to integrate LiveView in an existing app especially with lots of plugs in the route and conditional controller validations based on an action (i.e. `plug(:validate_me, when action in [:edit, :delete]`).

I think as LiveView progresses, we'll start seeing more support for routing. But it seems like the easier win right now could be letting user decide session store and how to deal with it for their cases.

Thoughts? ideas? Things I'm totally misunderstanding?

**Comment by chrismccord** [comment]
The controller and plug stack can do very little work in respect to what needs to happen in the LV. Keep in mind, the LV client can disconnect and reconnect at any time, and the reconnected WS request will not go thru the plug or controller stack, so the model demands a shared code path that exists inside the LV. Check out the `assign_new` docs for avoiding extra DB lookups on the initial HTTP request. Thanks!
