### ISSUE TITLE
`mix format` on `live.html.heex` causes empty flash containers to appear on LiveViews.

### ISSUE THREAD

**Issue by tlietz** [phoenixframework/phoenix_live_view#2121]
### Environment

* Elixir version (elixir -v): Elixir 1.13.4 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): 1.6.11
* Phoenix LiveView version (mix deps): 0.17.11
* Operating system: Mac Monterey 12.1 (M1 chip)
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes

### Actual behavior

I am migrating my website’s index page to a LiveView. Initially, when setting the LiveView up, everything works as expected. However, after running `mix format` there are always empty `info` and `error` flash containers at the beginning of the page. 

<img width="1442" alt="Screen Shot 2022-07-31 at 4 27 26 PM" src="https://user-images.githubusercontent.com/25965706/182168612-9647a1e7-9c67-4268-859a-db2266b0cc2d.png">

I think this issue is occurring because `mix format` has added `space` and `enter` characters between the `<p>` tags:

```
# Original live.html.heex

<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>
```

```
# After `mix format` live.html.heex

<main class="container">
  <p class="alert alert-info" role="alert" phx-click="lv:clear-flash" phx-value-key="info">
    <%= live_flash(@flash, :info) %>
  </p>

  <p class="alert alert-danger" role="alert" phx-click="lv:clear-flash" phx-value-key="error">
    <%= live_flash(@flash, :error) %>
  </p>

  <%= @inner_content %>
</main>
```

```elixir
# .formatter.exs

[
  plugins: [Phoenix.LiveView.HTMLFormatter],
  import_deps: [:ecto, :phoenix],
  inputs: ["*.{ex,exs,heex}", "priv/*/seeds.exs", "{config,lib,test}/**/*.{ex,exs,heex}"],
  subdirectories: ["priv/*/migrations"]
]
```

### Expected behavior

The blue and red flash containers do not show up with the extra whitespace between the `<p>` tags. Or `mix format` does not add any whitespace.

**Comment by chrismccord** [comment]
There are other issues around this, but this is expected and the solution is to render your containers only if there is a flash, such as in a function component like this:

```
  def flash(%{kind: :info} = assigns) do
    ~H"""
    <%= if live_flash(@flash, @kind) do %>
      <div>...</div>
    <% end %>
    """
  end
```

**Comment by tcoopman** [comment]
There's an other issue on the forum related to this: https://elixirforum.com/t/live-view-mix-format/51290

I feel like formatting should not have an impact on the whitespace?

**Comment by josevalim** [comment]
If the assumption is that it has no impact, then the only logical conclusion is that we disable formatting altogether, because via CSS the whitespace behavior can really be anything.

So Unfortunately we need to handle those things case by case and, even then, it is likely we can’t handle all of them (and every exception case we add is a place we could do formatting and now we no longer will).

@tcoopman can you please open up an issue for the above? It may be doable, but we can’t promise.

**Comment by arcanemachine** [comment]
@chrismccord When the LiveView HTMLFormatter is enabled for `.heex` templates, running `mix format` on a new Phoenix project creates these empty alert blocks in the starter LiveView template.

Perhaps the `live_flash` statement could be placed in a conditional for all new projects? As it stands, I believe this issue will occur on every Phoenix project out-of-the-box the first time `mix format` is run when auto-formatting is enabled for `.heex` templates (which is how I found this issue).

I'm new to Phoenix/LiveView/Elixir, but simply wrapping the default layout in a conditional (as suggested in your comment above) appears to solve the problem:

```
  <%= if live_flash(@flash, :info) do %>
    <p class="alert alert-info" role="alert" phx-click="lv:clear-flash" phx-value-key="info">
      <%= live_flash(@flash, :info) %>
    </p>
  <% end %>

  <%= if live_flash(@flash, :error) do %>
    <p class="alert alert-danger" role="alert" phx-click="lv:clear-flash" phx-value-key="error">
      <%= live_flash(@flash, :error) %>
    </p>
  <% end %>
```

Thanks
