### ISSUE TITLE
Add dev config for injecting HTML comments around function components

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix_live_view#2122]
This would inject something like:

```
<!-- MyAppWeb.Components.flash lib/app_web/components.ex:125 -->
<div id="flash>
  ...
</div>
<!-- /MyAppWeb.Components.flash lib/app_web/components.ex:125 -->
```

Rationale: for a componentized app it can often become difficult to ascertain from the browser markup where it is being generated from. The module/func/file/line will be a nice dev UX boost.

Caveats: we can only inject comments when we see HTML tags inside the component.

**Comment by derpycoder** [comment]
Hello @chrismccord,

This is how I solve this problem:

A Live Component is shown at the top:
![image](https://github.com/phoenixframework/phoenix_live_view/assets/25662120/1cd18c18-45e1-4118-976c-6e8d470f3936)

```elixir
<.live_component
        :if={Mix.env() == :dev}
        module={DerpyToolsWeb.InspectorComponent}
        file={__ENV__.file}
        line={__ENV__.line}
        id={"#{__MODULE__}-inspector"}
 />
```

```elixir
defmodule DerpyToolsWeb.InspectorComponent do
  @moduledoc """
  Useful component for development.
  Can be embedded into other components, which will allow developers to open
  the source code of the component directly from browser.
  """
  use DerpyToolsWeb, :live_component

  def render(assigns) do
    ~H"""
    <div class="absolute -top-10 flex justify-end w-full">
      <%!-- <form class="absolute flex justify-center w-full" target={@myself} phx-submit="do-nothing"> --%>
      <%!-- To link directly to the storybook page! --%>
      <button class="rounded-tl-lg rounded-bl-lg p-2 bg-slate-100 m-0" title="Show in Catalog">
        <Heroicons.eye solid class="h-3 w-3 text-gray-500" />
      </button>
      <button
        phx-click="inspect-source"
        class="-ml-1 rounded-tr-lg rounded-br-lg p-2 bg-slate-100 m-0 border-l border-slate-200"
        title="Open in VS Code"
        phx-target={@myself}
      >
        <Heroicons.code_bracket solid class="h-3 w-3 text-gray-500" />
      </button>
    </div>
    """
  end

  def handle_event("inspect-source", _params, socket) do
    %{file: file, line: line} = socket.assigns
    System.cmd("code", ["--goto", "#{file}:#{line}"])

    {:noreply, socket}
  end
end
```

Of course, I had to put the following env variable for `iex` to open the VS Code editor properly:
```bash
export ELIXIR_EDITOR="code --goto __FILE__:__LINE__"
```

----

I was thinking if it was possible for this kind of functionality to be built in. So in dev, upon hover of a web component, a red outline can show up, with buttons to take us to the source code.

![image](https://github.com/phoenixframework/phoenix_live_view/assets/25662120/8bc54132-7a24-4a29-8fd2-bc20e3ff0432)

**Comment by derpycoder** [comment]
I have figured out how to make it work as a function component:

Although I am running into an issue:
https://elixirforum.com/t/im-getting-no-function-clause-matching-in-derpytoolsweb-utmbuilderlive-handle-event-3/56673

**Comment by derpycoder** [comment]
![Source Code Viewer](https://github.com/phoenixframework/phoenix_live_view/assets/25662120/5cc736ef-343f-45ac-9915-d84e5aa6baa4)

Tada, it works like a charm!

But it would be great, if every component somehow had this ability, and we can just inspect each component, and jump to the source code!

**Comment by tmbb** [comment]
I've made a pull request handing the compiler side of this issue: https://github.com/phoenixframework/phoenix_live_view/pull/2719

**Comment by SteffenDE** [comment]
Added in 0.20, right? https://github.com/phoenixframework/phoenix_live_view/blob/7781a38b15f3341d381752cbba116f2075e0f422/CHANGELOG.md?plain=1#L77
