### ISSUE TITLE
Tidy up declarative assigns for v0.18

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix_live_view#2128]
* [x] Refactor HTML engine to not parse attrs twice (JV)
* [x] Docs for defmacro slot
* [x] Declared slots should default to `[]`
* [x] Use `@after_verify` (CM)

**Comment by connorlay** [comment]
We also need to raise if a declarative slot and a declarative attribute share the same name for the same component: https://github.com/phoenixframework/phoenix_live_view/pull/2133

**Comment by chrismccord** [comment]
BOOM great work everyone! ❤️❤️❤️🐥🔥
