### ISSUE TITLE
Support declarative assigns in LiveComponent and LiveView

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix_live_view#2129]
Do we want to go this route? Or should we tell them to wrap their LiveComponent/LiveView in a function component? I am not the biggest fan of the second because it hides the internal complexity.

Leftover from #2016.

**Comment by connorlay** [comment]
I would like to start exploring declarative assigns for LiveComponents next, then move to declarative assigns for LiveViews based on what we learn.

I am also not a fan of wrapping LiveComponents and LiveViews in a HEEx function component. HEEx function components look like HTML and imply no hidden state or behavior. Visually I think it makes sense for LiveComponents and LiveViews to stand out and take a bit more syntax to setup. 

Hopefully that will guide users towards writing smaller function components and composing those together?

**Comment by dvic** [comment]
Is this something that is blocking the 0.18 release or will it be released afterwards?

**Comment by josevalim** [comment]
Afterwards.

**Comment by maxmarcon** [comment]
FWIW, I'd also like to see at least LiveComponent support declarative assigns (I arrived here while trying to figure out if this is in the plan)

**Comment by josevalim** [comment]
Closing this for now. The best option for now is to wrap them in a function component.
