### ISSUE TITLE
Window blur causes phx_blur on inputs still in focus

### ISSUE THREAD

**Issue by owenstrevor** [phoenixframework/phoenix_live_view#213]
I’m building multiplayer forms, and when the user has focus on an input and then switches windows or tabs, the input is still focused but phx_blur is run (i.e. phx_blur runs when the input is still in focus).

This causes a side-effect for multiplayer forms because the value of inputs in focus is never changed by LiveView (a good thing).

**Comment by chrismccord** [comment]
I cannot recreate this on master. If you are able to recreate this on latest, please provide a minimal example for us to diagnose. Thank you!
