### ISSUE TITLE
Private assigns defined on the router not available in socket

### ISSUE THREAD

**Issue by barkerja** [phoenixframework/phoenix_live_view#2136]
I've realized that assigns attached to `private: %{}` from the router are not available on the socket. Is this a bug, intentional or something that currently isn't possible?

My use case is generating dynamic routes from external configuration at compile time, passing an identifier in the route -- as part of the private assigns -- to be able to identify and load that configuration when the route is called. I would like to use hooks to do some pre-checks/authorizations.

Example
```elixir
live "my-path", MyComponent, nil, private: %{page_id: page.id}
```

In `MyComponent`
```elixir
defmodule MyComponent
  use Phoenix, :live_view

  on_mount {__MODULE__, :check_auth}
  
  def on_mount(:check_auth, _params, _session, socket) do
    # socket.private.page_id does not exist
  end
end
```

**Comment by josevalim** [comment]
It is probably a good idea to make it work so plugins/library can use private to configure their behaviour without leaking assigns. PRs welcome!

**Comment by josevalim** [comment]
See discussion in #2654.
