### ISSUE TITLE
Attach_hook does not assign in some pages the handle_info

### ISSUE THREAD

**Issue by theguuholi** [phoenixframework/phoenix_live_view#2138]
### Environment

* Elixir version (elixir -v): 
```
Erlang/OTP 25 [erts-13.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] [dtrace]

Elixir 1.13.4 (compiled with Erlang/OTP 24)
```

* Phoenix version (mix deps): 1.6.11
* Phoenix LiveView version (mix deps): 0.17.11
* Operating system:  macOS Monterey
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

Hello, I don't know if it is a bug on **LiveView**  or a wrong implementation.

I implemented in my **live_session** the **attach_hook** bellow: 

```
  ....  |> attach_hook(:logout_user_hook, :handle_info, fn
      :logout_user, socket ->
        {:cont, push_redirect(socket, to: "/auth/auth0/logout")}

      _, socket ->
        {:cont, socket}
    end)
```

Some pages work, and some pages do not with the error below:

`[error] GenServer #PID<0.3653.0> terminating ** (FunctionClauseError) no function clause matching in ClarusWeb.DashboardLive.handle_info/2 (app 1.18.1) lib/app_web/live/dashboard/dashboard_live.ex:56: ClarusWeb.DashboardLive.handle_info(:logout_user, ....`

### Expected behavior

Instead of getting this error, expect all my **LiveView** pages with my handle_info without the error above.

**Comment by josevalim** [comment]
Can you provide a small application that reproduces the error? It will help rule out the error being application specific. Thank you!

**Comment by theguuholi** [comment]
@josevalim  we fixed the problem. Instead of using `:cont` we changed to `:halt`. IDK if this is the real problem but worked.   If you want to close the issue. I am okay. Thank you. 

```
    attach_hook(socket, :session_timeout_hook, :handle_info, fn
      :logout_user, socket ->
        {:halt, push_redirect(socket, to: "/auth/auth0/logout")}

      _, socket ->
        {:cont, socket}
    end)
    ````
