### ISSUE TITLE
Live_patch to absolute paths doesn't write to browser location

### ISSUE THREAD

**Issue by VictorGaiva** [phoenixframework/phoenix_live_view#2139]
### Environment

* Elixir version (elixir -v): 1.13.4 (
* Phoenix version (mix deps): 1.6.11
* Phoenix LiveView version (mix deps): 0.17.11
* Operating system: Linux (local Arch, prod Ubuntu)
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: N/A

### Actual behavior

After updating `phoenix_live_view` to 0.17.11, using `live_patch` to redirect to absolute paths does't writes the path to the address bar, but changes the page. And then if you navigate to relative paths, it goes to the wrong location.

Forcing `phoenix_live_view` to version 0.17.10 solves the issue.

### Expected behavior

`live_patch` should redirect to absolute paths.

**Comment by chrismccord** [comment]
live patch is only about patching the relative current path, so we should raise if you try to go to an absolute path instead. In such cases, live_redirect should be used.
