### ISSUE TITLE
Feature request: attach_hook for live components

### ISSUE THREAD

**Issue by dustinfarris** [phoenixframework/phoenix_live_view#2140]
my understanding is that attach_hook only works on liveview callbacks, not live components.

I am trying to set up hooks to decorate callbacks with [`Sentry.Context.add_breadcrumb`](https://hexdocs.pm/sentry/Sentry.Context.html#add_breadcrumb/1) and the attach_hook pattern seems perfect for this if it was supported.

**Comment by chrismccord** [comment]
This is planned, but not a current priority. Thanks!
