### ISSUE TITLE
Add first selector in Phoenix Liveview testing?

### ISSUE THREAD

**Issue by JJamesWWang** [phoenixframework/phoenix_live_view#2157]
Would it be possible to add a function to `Phoenix.LiveViewTest` that returns the first result after an `element/1` is called?

For example, let's say my HTML page has two `a` tags that have the same text.
```html
<a href="/">My Link</a>
<a href="/">My Link</a>
```

I want to test that the link indeed redirects to `"/"`, and I would usually do this as follows:
```elixir
    {:error, {:redirect, %{to: url}}} =
        view
        |> element("a", "My Link")
        |> render_click()

    assert url == "/"
```
However, there are two `a` tags, so I get an error: `* (ArgumentError) selector "a" returned 2 elements and 2 of them matched the text filter "My Link":`

I could fix this with a `first/1` method as follows:
```elixir
      {:error, {:redirect, %{to: url}}} =
        view
        |> element("a", "My Link")
        |> first()  
        |> render_click()
```

It doesn't have to be `first/1`, it could also select an arbitrary one; since they both do the same thing, I just need to select one, but I can't seem to do that with the current functions in `Phoenix.LiveViewTest` right now. Am I missing something that would make testing this easier?

**Comment by rktjmp** [comment]
You can use the `first-child` css selector.

```elixir
element("a:first-child", "My Link")
```

`nth-child(n)` is also supported, but `last-child` is not.
