### ISSUE TITLE
Pass an array of (event,payload) to `push_event`?

### ISSUE THREAD

**Issue by ndrean** [phoenixframework/phoenix_live_view#2158]
The use case is for example when you want to render real-time changes to a page that contains multiple listeners client side, either in a hook with `handleEvent(evt, (payload)=> ...)` or via the `window.addEventListener('phx:evt, ({detail})=> ...)`. However,  the `handle_info(%Phoenix.Socket.Boradcast{},socket)` returns a `{:noreply, push_event/3}` that supports only one `(event, payload)`. Would it be possible to consider to pass an array of `{evt, payload}` ?

**Comment by ndrean** [comment]
Or "just" client-side include several `node.dispatchEvent(new Event('some-event'))` in the `handleEvent` callback to the `push_event`.

**Comment by chrismccord** [comment]
I'm not sure I follow entirely, but you can already push an arbitrary number of events server to client and client to server, so we already support this. You could also push a single event with multiple datasets inside that the client dispatches, but all the primitives are already there I believe for what you want. Thanks!

**Comment by ndrean** [comment]
I am not sure you can send several events from the server with one push only, and especially if several hooks are interested in the event. However thanks to  `JS.dispatch` reaching a listener in `app.js` where the hooks live, then I can run `eval(hook.method)` through a list so I managed it anyway. And thanks again, really amazing tool.
