### ISSUE TITLE
phx-window-focus and phx-window-blur not working?

### ISSUE THREAD

**Issue by thiagomajesk** [phoenixframework/phoenix_live_view#2161]
### Environment

* Elixir version (elixir -v): Elixir 1.13.4 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): ~> 1.6.9
* Phoenix LiveView version (mix deps): ~> 0.17.11
* Operating system: 5.10.60.1-microsoft-standard-WSL2 (Ubuntu 20.04.4 LTS)
* Browsers you attempted to reproduce this bug on (the more the merrier):  Chrome 104.0.5112.102
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

I'm using the component below to detect user activity on the current tab and just noticed that the events are being fired on the client but don't get pushed to the server...

```elixir
defmodule AwayDetectorComponent do
  use Phoenix.LiveComponent

  @impl true
  def update(assings, socket) do
    socket =
      socket
      |> assign(assings)
      |> assign(:class, (assings[:away] && "absolute") || "absolute")

    {:ok, socket}
  end

  @impl true
  def render(assigns) do
    ~H"""
    <div
      id={@id}
      class={"#{@class} top-0 bottom-0 right-0 left-0 bg-black/50 backdrop-blur-sm
      z-50 flex items-center justify-center cursor-progress"}
      phx-target={@myself}
      phx-window-focus="page-active"
      phx-window-blur="page-inactive"
    >
      <h1 class="px-4 animate-pulse">Focus on this tab to reconnect</h1>
    </div>
    """
  end

  @impl true
  def handle_event("page-active", _params, socket) do
    IO.puts("ACTIVE PAGE")
    {:noreply, socket}
  end

  @impl true
  def handle_event("page-inactive", _params, socket) do
    IO.puts("INACTIVE PAGE")
    {:noreply, socket}
  end
end
```

I think I found a problem with the JS code, but I'm not sure if my assessment is right because there's a comment about removing duplicated events and I'm not sure about it. Check this out:

![image](https://user-images.githubusercontent.com/13930952/187052463-9b02b3f2-65ac-433d-b9fe-ee87756524e6.png)

The next param `phxTarget` (badly cropped) is `undefined` and the `phxEvent` holds the value of "window".  So this event is never pushed to the server. This function has 7 params and is called with only 6, so naturally the 7th param `phxTarget` is `undefined.` Here is the calling point:

![image](https://user-images.githubusercontent.com/13930952/187052491-9335cc77-4bf4-4059-8a1c-9ff67fcc7e5f.png)

**Comment by sodapopcan** [comment]
I'm experiencing the same thing.

**Comment by Eiji7** [comment]
> I think I found a problem with the JS code, but I'm not sure if my assessment is right because there's a comment about removing duplicated events and I'm not sure about it.

No this line looks good.

> The next param phxTarget (badly cropped) is undefined and the phxEvent holds the value of "window". So this event is never pushed to the server. This function has 7 params and is called with only 6, so naturally the 7th param phxTarget is undefined.

I would rather say that looks like there is an extra `targetCtx` parameter that should be removed. Pay attention that there is no such attribute in both `callbacks` defined above for `focusout` and `focusin` as well as `keyup` and `keydown` events.

After locally removing mentioned argument:
```diff
-     this.bind({ blur: "blur", focus: "focus" }, (e, type, view, targetEl, targetCtx, phxEvent, phxTarget) => {
+     this.bind({ blur: "blur", focus: "focus" }, (e, type, view, targetEl, phxEvent, phxTarget) => {
        if (phxTarget === "window") {
          let data = this.eventMeta(type, e, targetEl);
          js_default.exec(type, phxEvent, view, targetEl, ["push", { data }]);
        }
      });
```
the event is fired properly for me.
