### ISSUE TITLE
ETA for 0.18 release?

### ISSUE THREAD

**Issue by moissela** [phoenixframework/phoenix_live_view#2171]
Hi there, any ETA for LiveView 0.18 release? 🙏🏻

We started using the master branch and tried some new functionalities but actually e.g. LiveDashboard doesn't compile correctly 🤓

**Comment by josevalim** [comment]
It will be out as soon as it is ready. :)

**Comment by moissela** [comment]
I deserved this answer 😅

I was hoping for a release during ElixirConf but what was presented is beyond all expectations 🙌🏼

Thank you for this fantastic piece of technology and for the whole ecosystem that surrounds it!

**Comment by josevalim** [comment]
Our goal was to ship it in time for ElixirConf, but travelling, preparing talks, etc tend to throw a wrench on plans. :D But we are also very excited about this and we want to ship it soon :)
