### ISSUE TITLE
Non-determinate formatting of script tag

### ISSUE THREAD

**Issue by edds** [phoenixframework/phoenix_live_view#2174]
### Environment

* Elixir version (elixir -v): Elixir 1.13.4 (compiled with Erlang/OTP 24)
* Phoenix version (mix deps): 1.6.12
* Phoenix LiveView version (mix deps): current master: `e26635e7b3e14dbb7153584a7f0c93cb83553194`
* Operating system: MacOS
* Browsers you attempted to reproduce this bug on (the more the merrier): 
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:

### Actual behavior

Running `HTMLFormatter.format` produces different results when piping the output back into the function:

```elixir
iex(42)> heex = ~s|"\n<div>\n    <script type=\"text/props\">\n        <%=\n        raw(Jason.encode!(%{\n            whatEndpoint: Routes.api_search_options_path(@conn, :role_search_options)}, escape: :html_safe))\n        %>\n    </script>\n</div>\n"|
"\"\n<div>\n    <script type=\"text/props\">\n        <%=\n        raw(Jason.encode!(%{\n            whatEndpoint: Routes.api_search_options_path(@conn, :role_search_options)}, escape: :html_safe))\n        %>\n    </script>\n</div>\n\""
iex(43)> heex = Phoenix.LiveView.HTMLFormatter.format(heex, [])
"\"\n<div>\n  <script type=\"text/props\">\n            <%= raw(Jason.encode!(%{whatEndpoint: Routes.api_search_options_path(@conn, :role_search_options)},\n    escape: :html_safe)) %>\n        \n  </script>\n</div>\n\"\n"
iex(44)> heex = Phoenix.LiveView.HTMLFormatter.format(heex, [])
"\"\n<div>\n  <script type=\"text/props\">\n                <%= raw(Jason.encode!(%{whatEndpoint: Routes.api_search_options_path(@conn, :role_search_options)},\n    escape: :html_safe)) %>\n            \n      \n  </script>\n</div>\n\"\n"
iex(45)> heex = Phoenix.LiveView.HTMLFormatter.format(heex, [])
"\"\n<div>\n  <script type=\"text/props\">\n                    <%= raw(Jason.encode!(%{whatEndpoint: Routes.api_search_options_path(@conn, :role_search_options)},\n    escape: :html_safe)) %>\n                \n          \n      \n  </script>\n</div>\n\"\n"
```

Note the extra space put before the `<%=raw` and also the extra newline put after that line with extra indentation after every run.

### Expected behavior

The script tag should be the same regardless of the number of times the formatter runs over the line.

**Comment by feliperenan** [comment]
@edds do you also get this behaviour from the template itself? I was trying to reproduce here but I couldn't. I haven't had time to take a deeper look yet but just in case you also can reproduce it there, let me know.

**Comment by edds** [comment]
@feliperenan yes, this snippet came from within one of our templates. It's getting in the way of us turning auto formatting on.

**Comment by feliperenan** [comment]
Got it. I was able to reproduce that too. Thanks!
