### ISSUE TITLE
Diff mechanism should send changes for tags that have really changed in comprehensions

### ISSUE THREAD

**Issue by mspanc** [phoenixframework/phoenix_live_view#2187]
### Environment

* Elixir version (elixir -v): `Erlang/OTP 25 [erts-13.0.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]`
* Phoenix version (mix deps): 1.6.12
* Phoenix LiveView version (mix deps): 0.17.11
* Operating system: macOS 12.5.1 / M1
* Browsers you attempted to reproduce this bug on (the more the merrier): Safari, Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: no

### Actual behavior

I am playing with LiveView and I find the diff mechanism to be not very efficient with comprehensions.

Let’s say I have a 100x100 table where user can click a cell to select it. Only one cell can be selected.

It is represented just by list of lists and it is passed as assign to the live view template:

```elixir
  @impl true
  def mount(_params, _session, socket) do
    table =
      for i <- 1..100 do
        for j <- 1..100 do
          "#{i},#{j}"
        end
      end

    {:ok,
      socket
      |> assign(:selected_cell, nil)
      |> assign(:table, table)
    }
  end
```

And rendered using comprehensions:

```rex
<table>
<%= for row <- @table do %>
  <tr>
    <%= for cell <- row do %>
      <td phx-click="cell_clicked" {"phx-value-cell": cell]}>
        <%= if @selected_cell == cell do %>
          <b><%= cell %></b>
        <% else %>
          <%= cell %>
        <% end %>
      </td>
    <% end %>
  </tr>
<% end %>
</table>
```

Once the user clicks the cell, it marks the cell as selected, causing re-render:

```elixir
  @impl true
  def handle_event("cell_clicked", %{"cell" => cell}, socket) do
    {:noreply, assign(socket, :selected_cell, cell)}
  end
```

The problem is that the size of diff being sent over web socket is 600 KB. It seems that it contains updated contents of the whole table. I’ve read [the docs](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.Engine.html#module-comprehensions) on how comprehensions are handled but the approach explained in the docs seems to be very limited. The real issue here is not to split "static" and "dynamic" parts, but update only these tags which were affected.

IMO the diff mechanism should be smart enough to update just the particular cell.

I tried to optimize this by splitting this into multiple components.

I have wrapped `<tr>` into LiveComponent:

```rex
<tr>
  <%= for cell <- @cells do %>
    <.live_component
      module={CellComponent}
      id={cell}
      cell={cell}
      selected={@selected_cell == cell}
    />
  <% end %>
</tr>
```

and `<td>` as well:

```eex
<td phx-click="clicked" phx-target={@myself}>
  <%= if @selected do %>
    <b>
      <%= @cell %>
    </b>
  <% else %>
    <%= @cell %>
  <% end %>
</td>
```

When it is clicked, it handles the event on the component level, sends the message to the parent view, which stores which cell is selected and then passes this down to the component by passing argument in the template:

```eex
<table>
<%= for {row_cells, row_index} <- Enum.with_index(@sheet) do %>
  <.live_component
    module={RowComponent}
    id={row_index}
    cells={row_cells}
    selected_cell={@selected_cell}
  />
<% end %>
</table>
```

The updates went down to 70 KB. Still too large.

### Expected behavior

The diff should should be minimal and contain only cells that were changed (one that was deselected and one that was selected).

### Rationale

For any sort of application that has to display tabular data (and there are many of them, not only in finance) with this kind of user interaction this is a dealbreaker. 

I can try to work on improving diffing mechanism for comprehensions so it updates just tags that were actually changed. I'd appreciate some guidance before I start.

**Comment by josevalim** [comment]
In order to implement that we would need to ID each individual column. We are working on a streaming system where you would have more control over that, but that would be in addition to the comprehension system. For now, using phx-update="append" | "prepend" is the way to go.

**Comment by gabrielmancini** [comment]
i having face the same issue and in my case i need the list sorted, so i can't use streaming way. my mgs are in 250k each one.
