### ISSUE TITLE
Doc formatting for slot with attributes: missing dash separator before "Accepts attributes"

### ISSUE THREAD

**Issue by ArthurClemens** [phoenixframework/phoenix_live_view#2193]
### Environment

* Elixir version (elixir -v): 1.14.0
* Phoenix version (mix deps): 1.6.12
* Phoenix LiveView version (mix deps): https://github.com/phoenixframework/phoenix_live_view `72443db`
* Operating system: macOS 12.5.1
* Browsers you attempted to reproduce this bug on (the more the merrier): n.a. (command line)
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: n.a. (command line)

### Actual behavior

When using a slot with attributes, the slot name and string "Accepts attributes" are concatenated without separator.

With this example from the documentation:

```
slot :column do
  attr :label, :string, required: true, doc: "Column label."
end
```

Generated HTML:

<ul>
  <li>
    <code class="inline">column</code>Accepts attributes: <ul><li><code class="inline">label</code> (<code class="inline">:string</code>) (required) - Column label.</li></ul>
  </li>
</ul>

Markup:
```html
<ul>
  <li>
    <code class="inline">column</code>Accepts attributes: <ul><li><code class="inline">label</code> (<code class="inline">:string</code>) (required) - Column label.</li></ul>
  </li>
</ul>
```

### Expected behavior

"Accepts attributes" is prefixed with a dash.

Generated HTML:

<ul>
  <li>
    <code class="inline">column</code> - Accepts attributes: <ul><li><code class="inline">label</code> (<code class="inline">:string</code>) (required) - Column label.</li></ul>
  </li>
</ul>

Markup:
```html
<ul>
  <li>
    <code class="inline">column</code> - Accepts attributes: <ul><li><code class="inline">label</code> (<code class="inline">:string</code>) (required) - Column label.</li></ul>
  </li>
</ul>
```

**Comment by josevalim** [comment]
Would you like to send a PR? :)
