### ISSUE TITLE
Formatter removes <%# ... %> comments

### ISSUE THREAD

**Issue by mhanberg** [phoenixframework/phoenix_live_view#2199]
### Environment

* Elixir version (elixir -v):

  ```
  Erlang/OTP 25 [erts-13.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

  Elixir 1.14.0 (compiled with Erlang/OTP 25)
  ```
* Phoenix version (mix deps):
  ```
  * phoenix 1.6.11 (Hex package) (mix)
    locked at 1.6.11 (phoenix) 1664e34f
  * phoenix_ecto 4.4.0 (Hex package) (mix)
    locked at 4.4.0 (phoenix_ecto) 09864e55
  * phoenix_html 3.2.0 (Hex package) (mix)
    locked at 3.2.0 (phoenix_html) 36ec97ba
  * phoenix_live_dashboard 0.6.5 (Hex package) (mix)
    locked at 0.6.5 (phoenix_live_dashboard) ef4fa50d
  * phoenix_live_reload 1.3.3 (Hex package) (mix)
    locked at 1.3.3 (phoenix_live_reload) 76679667
  * phoenix_live_view 0.17.11 (Hex package) (mix)
    locked at 0.17.11 (phoenix_live_view) 71777919
  * phoenix_pubsub 2.1.1 (Hex package) (mix)
    locked at 2.1.1 (phoenix_pubsub) 81367c6d
  * phoenix_view 1.1.2 (Hex package) (mix)
    locked at 1.1.2 (phoenix_view) 7ae90ad2
  ```
* Phoenix LiveView version (mix deps): see above
* Operating system: macOS 12.6
* Browsers you attempted to reproduce this bug on (the more the merrier): N/A
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: N/A

### Actual behavior

This is me formatting the file with the language server (double checked with running mix format)

https://user-images.githubusercontent.com/5523984/191102152-78f0917b-057d-40c9-90ab-34b7246779bb.mov

### Expected behavior

Doesn't remove elixir comments.

**Comment by josevalim** [comment]
Yes, this has been listed a couple times. :)

Elixir doesn't emit those as tokens, so you either need to use `<% #` (with spaces) or use `<!%-- --%>` as of Elixir v1.14. :)

**Comment by mhanberg** [comment]
ahh, sorry about that. I searched for formatter in the issues and didn't see anything, must have missed it.

**Comment by josevalim** [comment]
Ah, no worries. I meant it more as “this is common” rather than “you should have searched it” :D

**Comment by mhanberg** [comment]
Does the HEEx engine need an update before the new EEx comments can be used? I'm getting the following error on elixir 1.14.

```
== Compilation error in file lib/platform_web/views/layout_view.ex ==
** (Phoenix.LiveView.HTMLTokenizer.ParseError) lib/platform_web/templates/layout/_user_menu.html.heex:4:4: end of do-block reached without closing tag for <!%-->
    (phoenix_live_view 0.17.11) lib/phoenix_live_view/html_engine.ex:79: Phoenix.LiveView.HTMLEngine.validate_unclosed_tags!/2
    (phoenix_live_view 0.17.11) lib/phoenix_live_view/html_engine.ex:87: Phoenix.LiveView.HTMLEngine.handle_end/1
    (eex 1.14.0) lib/eex/compiler.ex:424: EEx.Compiler.wrap_expr/5
    (eex 1.14.0) lib/eex/compiler.ex:370: EEx.Compiler.generate_buffer/4
    (eex 1.14.0) lib/eex/compiler.ex:347: EEx.Compiler.generate_buffer/4
    (phoenix_view 1.1.2) lib/phoenix/template.ex:419: Phoenix.Template.compile/3
    (phoenix_view 1.1.2) lib/phoenix/template.ex:197: anonymous fn/4 in Phoenix.Template."MACRO-__before_compile__"/2
    (elixir 1.14.0) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
```

**Comment by feliperenan** [comment]
@mhanberg can you send a template example that reproduces this error in isolation? This wasn't supposing to be happening.

Also, make sure you do mix compile if you just switched to Elixir 1.14. But that error doesn't seem to be it 🤔

**Comment by josevalim** [comment]
Oh, also check Phoenix LiveView main/master branch if you haven't yet. Although 0.18.0 should be out soon.

**Comment by simonmcconnell** [comment]
Isn't it, `<%!-- comment --%>` not `<!%--`?

**Comment by josevalim** [comment]
Yes, sorry!

**Comment by mhanberg** [comment]
Wow, I even read it in the docs several times and didn't notice sweat 😅. 

I'll give it a try later, but I imagine it'll work.
