### ISSUE TITLE
cancel_upload triggers form submit

### ISSUE THREAD

**Issue by clemensm** [phoenixframework/phoenix_live_view#2202]
### Environment

* Elixir version (elixir -v):  1.14.0-otp-25
* Phoenix version (mix deps): 1.6.12
* Phoenix LiveView version (mix deps): 0.17.11
* Operating system: MacOS
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes, tried with new project as well

### Actual behavior

I'm trying to add live_upload to the `form_component.ex` that is generated by `mix phx.gen.live`. I've added the call to `allow_live_update` in the `update` function of the `form_component.ex`, and added all the html (preview image, cancel button etc) from the walkthrough in the docs, so far everything is working fine.

1. Create new item from index page
2. Upload a single file
3. wait for upload to finish
4. cancel upload
5. `handle_event("cancel-upload" ...) is being called
6. handle_event("save" ...) is being called and form closes (if validation passes)

See also the attached sample app, the only things I changed are the additions in the `live_place/form_component.ex` and corresponding `.heex` file.

[example.zip](https://github.com/phoenixframework/phoenix_live_view/files/9607686/example.zip)

### Expected behavior

Should not trigger `submit`

**Comment by josevalim** [comment]
Buttons by default submit the forms they are on. Add `type="button"` to the button so it doesn't submit the form.

**Comment by josevalim** [comment]
To clarify, the above is HTML behaviour, not LiveView's. :)

**Comment by clemensm** [comment]
Damn, my bad :-)
Thanks anyways!
