### ISSUE TITLE
warning: undefined attribute for component Phoenix.Component.form/1

### ISSUE THREAD

**Issue by anmlnath** [phoenixframework/phoenix_live_view#2207]
### Environment

* Elixir version (elixir -v):

Erlang/OTP 25 [erts-13.0.4] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit] [dtrace]

Elixir 1.14.0 (compiled with Erlang/OTP 25)

* Phoenix version (mix deps):

phoenix 1.6.12 (Hex package) (mix)

* Phoenix LiveView version (mix deps):

phoenix_live_view 0.18.0 (Hex package) (mix)

* Operating system:

macOS 12.6

* Browsers you attempted to reproduce this bug on (the more the merrier): 

n/a

* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:

n/a

### Actual behavior

`warning: undefined attribute "autocomplete" for component Phoenix.Component.form/1`

The documentation for the form component indicates that it supports "rest" -- Additional HTML attributes to add to the form tag.
https://hexdocs.pm/phoenix_live_view/0.18.0/Phoenix.Component.html#form/1

This was working in LiveView 0.17.x. However, when upgrading to LiveView 0.18.0, the above mentioned warning appears when compiling.

### Expected behavior

No compiler warning for supported "rest" of attributes.

**Comment by josevalim** [comment]
Fixed in master!

**Comment by anmlnath** [comment]
Thanks. I didn't see an open or closed issue -- guess I should've looked at the commits.
