### ISSUE TITLE
phx-change event needs to update the changeset

### ISSUE THREAD

**Issue by nicolasblanco** [phoenixframework/phoenix_live_view#221]
There's something that is maybe not clear in the LiveView documentation right now, the `phx-change` event when bound to a changeset form must update the changeset with the received params in the socket assigns.

If you write a `handle_event` function for a `phx-change` event and you update other assigns *without* updating the changeset, you have weird behaviours in the form, where some inputs reset for instance.

If updating the changeset is mandatory, maybe this information should be written in the doc, what do you think?

**Comment by future-cyborg** [comment]
This is definitely just a 'problem' with lack of documentation, as I spent some time working around phx-change as well.

I just put this [example repo](https://github.com/future-cyborg/phoenix_example_multi_nested_form) together this weekend about working with forms in LiveView.

Here is the snippet of how I handled phx-change so inputs wouldn't reset while making other changes.
```elixir
  def handle_event("validate", %{"post" => params}, socket) do
    post_changeset = %Post{}
      |> Example.change_post(params)

    {:noreply, assign(socket, post_changeset: post_changeset)}
  end
```

**Comment by chrismccord** [comment]
Correct, you need to update the changeset (server state) when you receive state from the client, otherwise you will "undo" their changes because you are ignoring the data. Thanks!
