### ISSUE TITLE
How to set `temporary_assigns` to an empty list? (Instead of setting `nil`)

### ISSUE THREAD

**Issue by enkr1** [phoenixframework/phoenix_live_view#2210]
> I am not sure if there is something we can do here. When you set the temporary assign to an empty list, then it is an empty list after every render. So when you set it to an empty list in a given render, then we don't consider it as changed, and therefore it won't be re-rendered.
> 
> Another option is for us to consider temporary assigns as changed whenever they are set but this may have other consequences.
> 
> For now, we will go ahead with a doc change. A fix is to simply set it to a value that you don't use, such as nil:
> 
> ```
> {:ok, setup_counter(socket), temporary_assigns: [list: nil]}
> ```

Hi community,

I found out the solution mentioned is just a temporary fix. By Setting the list to `nil`, it will throw you an error when you refresh you page in a modal:
```
protocol Enumerable not implemented for nil of type Atom
```

<img width="1467" alt="image" src="https://user-images.githubusercontent.com/64194467/191678483-43262b97-9c55-4e9d-85f6-ec279480afa0.png">

As this is 3 years ago, I am curious if there is any latest update on this issue. 

Thank you in advance.

_Originally posted by @enkr1 in https://github.com/phoenixframework/phoenix_live_view/issues/469#issuecomment-1254606179_

**Comment by josevalim** [comment]
This is behaving as expected. If you set it to `nil`, you need to consider `nil` in your template. It is often set to an empty list because it is used for collections, so an empty list becomes a no-op.

But in a nutshell, you can set to whatever you want, as long as your template handles it.

**Comment by enkr1** [comment]
> This is behaving as expected. If you set it to `nil`, you need to consider `nil` in your template. It is often set to an empty list because it is used for collections, so an empty list becomes a no-op.
> 
> But in a nutshell, you can set to whatever you want, as long as your template handles it.

Alright, understood. 

Thank you so much @josevalim! 💯
