### ISSUE TITLE
Unmentioned breaking changes in 0.18.0

### ISSUE THREAD

**Issue by florish** [phoenixframework/phoenix_live_view#2212]
Hi, not entirely sure if this is a bug, maybe just a CHANGELOG omission.

On trying to upgrade from 0.17.x to 0.18.0, I'm getting unexpected compiler warnings and errors. Examples (original module names and filenames redacted):

```
** (CompileError): undefined function live_flash/2 (expected <<MODULE>> to define such a function or for it to be imported, but none are available)
warning: undefined function assign/2 (expected <<MODULE>> to define such a function or for it to be imported, but none are available)
warning: undefined function assign/3 (expected <<MODULE>> to define such a function or for it to be imported, but none are available)
** (CompileError): undefined function assign_new/3 (expected <<MODULE>> to define such a function or for it to be imported, but none are available)
```

Quick research learns me that these functions have been moved to `Phoenix.Component` in 0.18.0. Example:

https://hexdocs.pm/phoenix_live_view/0.18.0/Phoenix.Component.html#live_flash/2

In 0.17 this lived in:

https://hexdocs.pm/phoenix_live_view/0.17.12/Phoenix.LiveView.Helpers.html#live_flash/2

Similar changes exist for `assign/2`, `assign/3` and `assign_new/3`, although the 0.17 module is `Phoenix.LiveView` in those cases, not `Phoenix.LiveView.Helpers`.

In the [0.18.0 changelog](https://hexdocs.pm/phoenix_live_view/0.18.0/changelog.html), however, I'm missing a clear "Breaking changes" section on this. To be sure, there is a section related to this:

> [Phoenix.LiveView.Helpers](https://hexdocs.pm/phoenix_live_view/0.18.0/Phoenix.LiveView.Helpers.html) itself has been soft deprecated and all relevant functionality has been migrated. You must import Phoenix.Component where you previously imported [Phoenix.LiveView.Helpers](https://hexdocs.pm/phoenix_live_view/0.18.0/Phoenix.LiveView.Helpers.html) when upgrading.

For me as someone in the process of updating, this did not make clear to me that I _have_ to change my code to avoid compiler errors. As I'm not sure what the exact instructions should be, the best I could think of was to open this issue to create awareness.

Just let me know if any additional information is needed.

**Comment by florish** [comment]
@josevalim Thanks for the quick reply! To be sure: in https://hexdocs.pm/phoenix_live_view/0.18.0/Phoenix.LiveView.Helpers.html the instructions are:

> You must `use Phoenix.Component` instead.

While in the CHANGELOG, I'm instructed to `import Phoenix.Component`. 

Which one is correct?

**Comment by josevalim** [comment]
If you are defining your own components, you must do `use`. Otherwise `import` is fine. :)
