### ISSUE TITLE
warning: undefined attribute "data" (declarations)

### ISSUE THREAD

**Issue by anmlnath** [phoenixframework/phoenix_live_view#2217]
### Environment

* Elixir version (elixir -v):

Erlang/OTP 25 [erts-13.0.4] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit] [dtrace]

Elixir 1.14.0 (compiled with Erlang/OTP 25)

* Phoenix version (mix deps):

phoenix 1.6.12 (Hex package) (mix)

* Phoenix LiveView version (mix deps):

phoenix_live_view 0.18.0 (https://github.com/phoenixframework/phoenix_live_view.git - a3715873f22fb0e0b0ff9cb81d79567f7dd3f433) (mix)

* Operating system:

macOS 12.6

* Browsers you attempted to reproduce this bug on (the more the merrier): 

n/a

* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:

n/a

### Actual behavior

warning: undefined attribute "data" for component Phoenix.Component.form/1

When passing a keyword list to the data element of a form:

e.g. `data={[has_changed: !no_changes?(@changeset)]}`

which renders correctly as `<form data-has-changed="false"  ...`

But has a compiler warning.

### Expected behavior

no warning please!

The global prefix `data-` has no warning (e.g. `data-has-changed="false"`), but has a separate issue (will report it separately #2218).

This documentation doesn't mention using the `data` keyword list syntax, so I don't know if it is officially supported, but it is something we're using.
https://hexdocs.pm/phoenix_live_view/0.18.0/js-interop.html#client-server-communication

**Comment by josevalim** [comment]
> e.g. data={[has_changed: !no_changes?(@changeset)]}

@anmlnath is this your actual code in practice? In this case, I would actually suggest using `data-` because you encode more data in the template (and therefore less data sent over the wire).

**Comment by anmlnath** [comment]
For our use case, I think we're fine transitioning to `data-` because we only have a single attribute anyway, but others may have a reason to pass a larger keyword list to `data`.

**Comment by josevalim** [comment]
Actually, the keyword list syntax just working is surprising for me. `false` anywhere should remove the value. It sounds like a bug in Phoenix.HTML.

**Comment by anmlnath** [comment]
Consistency would be nice.

Such a change could impact custom JavaScript (e.g. hooks) that may expect `false` or `true`, rather than removing the attribute, or an attribute equal to an empty string `""`

**Comment by josevalim** [comment]
To be clear, consistency would be to remove the attribute in all cases.

**Comment by anmlnath** [comment]
Yes. Understood. 

Just noting that it may be a breaking change for some folks, if they, like us, had come to rely on the existing behaviour of the keyword list.

**Comment by josevalim** [comment]
I have changed Phoenix.HTML. The rest of this discussion can be handled in the PR, thank you!

**Comment by anmlnath** [comment]
Thank you!
