### ISSUE TITLE
Data attributes with ={false} not rendered

### ISSUE THREAD

**Issue by anmlnath** [phoenixframework/phoenix_live_view#2218]
### Environment

* Elixir version (elixir -v):

Erlang/OTP 25 [erts-13.0.4] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit] [dtrace]

Elixir 1.14.0 (compiled with Erlang/OTP 25)

* Phoenix version (mix deps):

phoenix 1.6.12 (Hex package) (mix)

* Phoenix LiveView version (mix deps):

phoenix_live_view 0.18.0 (https://github.com/phoenixframework/phoenix_live_view.git - a3715873f22fb0e0b0ff9cb81d79567f7dd3f433) (mix)

This issue also existed in LiveView 0.17.9.

* Operating system:

macOS 12.6

* Browsers you attempted to reproduce this bug on (the more the merrier): 

n/a

* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:

n/a

### Actual behavior

Adding an attribute like `data-has-changed` to a form component only works with quoted values, e.g. `<.form data-has-changed="false">`.

`<.form data-has-changed={false}>` is not rendering the `data-has-changed` attribute.

### Expected behavior

Expect the attribute to render with either syntax, allowing code to be passed into the data attribute.

**Comment by josevalim** [comment]
Yes, this is expected. `false` and `nil` discard the whole attribute. If you want it literally encoded, then you need a string. I believe this is documented in the ~H sigil but, if not, a PR is def. welcome! :)

**Comment by anmlnath** [comment]
Thanks, it is still a little odd that `{true}` encodes to `=""`, but this may be okay.

It was initially confusing because I thought any {code} wasn't encoding the parameter, but it was only if said code evaluates to false that it was missing (whereas the `data={[...]}` syntax must be converting it to a string?).
