### ISSUE TITLE
phx-submit event doesn't work on forms with hidden submit buttons

### ISSUE THREAD

**Issue by tensiondriven** [phoenixframework/phoenix_live_view#222]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 21 [erts-10.3.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe] [dtrace]
Elixir 1.8.1 (compiled with Erlang/OTP 21)
```
* Phoenix version (mix deps):

```
* parse_trans 3.3.0 (Hex package) (rebar3)
* mimerl 1.2.0 (Hex package) (rebar3)
* file_system 0.2.6 (Hex package) (mix)
* connection 1.0.4 (Hex package) (mix)
* metrics 1.0.1 (Hex package) (rebar3)
* bunt 0.2.0 (Hex package) (mix)
* unicode_util_compat 0.4.1 (Hex package) (rebar3)
* idna 6.0.0 (Hex package) (rebar3)
* gettext 0.16.1 (Hex package) (mix)
* merkle_tree 1.6.1 (Hex package) (mix)
* coerce 1.0.1 (Hex package) (mix)
* ranch 1.7.1 (Hex package) (rebar3)
* telemetry 0.4.0 (Hex package) (rebar3)
* decimal 1.7.0 (Hex package) (mix)
* jason 1.1.2 (Hex package) (mix)
* poison 3.1.0 (Hex package) (mix)
* ssl_verify_fun 1.1.4 (Hex package) (mix)
* dialyxir 0.5.1 (Hex package) (mix)
* numbers 5.1.1 (Hex package) (mix)
* combine 0.10.0 (Hex package) (mix)
* extractable 0.2.0 (Hex package) (mix)
* certifi 2.5.1 (Hex package) (rebar3)
* hackney 1.15.1 (Hex package) (rebar3)
* tzdata 0.5.20 (Hex package) (mix)
* timex 3.5.0 (Hex package) (mix)
* db_connection 2.0.6 (Hex package) (mix)
* credo 1.0.4 (Hex package) (mix)
* ecto 3.1.0 (Hex package) (mix)
* phoenix_pubsub 1.1.2 (Hex package) (mix)
* oauth2 0.9.4 (Hex package) (mix)
* cowlib 2.7.0 (Hex package) (rebar3)
* cowboy 2.6.1 (Hex package) (rebar3)
* nanoid 2.0.1 (Hex package) (mix)
* mime 1.3.1 (Hex package) (mix)
* insertable 0.2.0 (Hex package) (mix)
* tensor 2.1.2 (Hex package) (mix)
* map_diff 1.3.3 (Hex package) (mix)
* postgrex 0.14.1 (Hex package) (mix)
* ecto_sql 3.1.0 (Hex package) (mix)
* plug_crypto 1.0.0 (Hex package) (mix)
* plug 1.8.0 (Hex package) (mix)
* phoenix_html 2.13.2 (Hex package) (mix)
* plug_cowboy 2.0.2 (Hex package) (mix)
* phoenix 1.4.3 (Hex package) (mix)
* phoenix_live_view 0.1.0 (https://github.com/phoenixframework/phoenix_live_view.git) (mix)
* phoenix_live_reload 1.2.0 (Hex package) (mix)
* ueberauth 0.6.1 (Hex package) (mix)
* ueberauth_google 0.8.0 (Hex package) (mix)
* phoenix_ecto 4.0.0 (Hex package) (mix)
```

* NodeJS version (node -v):
```
v8.16.0
```
* NPM version (npm -v):
```
6.4.1
```

* Operating system:
```
ProductName:	Mac OS X
ProductVersion:	10.14.4
BuildVersion:	18E226
```

### Actual behavior

1) Set up a form with a `phx-submit` attribute on the form tag
2) Add a submit button to the form
3) Use javascript to trigger `.click()` on the form button
4) Live view is triggered, this is good
5) Hide the submit button using css, `display: none`
6) Use javascript to trigger `.click()` on the form button

** The form submits normally, not using live view

### Expected behavior

** The form submits using liveview

A hidden Submit button should still submit the form.

Why is this needed?  I have dynamic updating on my form fields where I want the form to submit when the field is blurred.  I can't use `phx-blur` because I want to send the whole form back to the server so that I can simplify the live view code by accepting the whole form on every submit.

This hack is necessary because calling ".submit()" directly on the form doesn't trigger the liveview handler either (which is a separate bug).

**Comment by chrismccord** [comment]
This sounds like a click event bubbling issue for hidden buttons, that is browser specific. Can you trigger the submit event on the form instead? That should fix it. Thanks!

**Comment by chrismccord** [comment]
> This hack is necessary because calling ".submit()" directly on the form doesn't trigger the liveview handler either (which is a separate bug)

I missed this part. Can you share a minimal example which produces the submit issue. I am able to trigger submit just fine on my side. Thanks!

**Comment by chrismccord** [comment]
My examples use `form.dispatchEvent(new Event("submit"))`, which I believe is required for buttonless forms. I don't believe this is an issue on our side if form.submit() isn't working, since my brief searching shows it's normal browser behavior. Let me know if dispatchEvent works for you.

**Comment by tensiondriven** [comment]
I tried using `form.dispatchEvent(new Event("submit"))` but couldn't get the forms to submit using that method.  However, I did some research and saw what you're suggesting, that dispatchEvent is required for buttonless forms, so its safe to say my repro case isn't valid.  I'm going to close this.

**Comment by tensiondriven** [comment]
For anyone that may stumble across this, if you have a select box in a form that has a `phx_submit` handler attached, and you want the form to submit to the liveview when the select is changed, you do need to use `dispatchEvent(new Event...` but it is necessary to pass `bubbles: true` to get the event to trigger `phx_submit`.

I'm using the following javascript, and it works: (without adding `bubbles: true`, it does not)

```
if (document.querySelectorAll(".js-submit-on-change")) {
  for (const element of document.querySelectorAll(".js-submit-on-change")) {
    element.addEventListener("change", function (event) {
      this.form.dispatchEvent(new Event("submit", {
        'bubbles': true
      }))
    });
  }
}
```
