### ISSUE TITLE
Using Phoenix.Component Drops Argument Names in Docs

### ISSUE THREAD

**Issue by aj-foster** [phoenixframework/phoenix_live_view#2222]
### Environment

* Elixir version (elixir -v): Elixir 1.14.0 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): 1.6.12
* Phoenix LiveView version (mix deps): 0.18.0
* Operating system: macOS 12.6
* Browsers you attempted to reproduce this bug on (the more the merrier): N/A
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: N/A

### Actual behavior

This is such a small thing, I almost feel guilty opening this issue.

After running `mix docs` (with `ex_doc` version 0.28.5), single-arity functions within modules that call `use Phoenix.Component` (and therefore use `Phoenix.Component.Declarative.def/2`) are all documented with a generic argument `arg` rather than the real name of the argument. For example, `def foo(bar), do: ...` produces documentation titled `foo(arg)`.

This is true for functions that do not use declarative assigns. In contrast, functions that use declarative assigns have the correct name `assigns`. Similarly, functions with arity other than 1 are well-documented.

### Expected behavior

Generated documentation should include the names of arguments for functions. For example, `def foo(bar), do: ...` should produce documentation titled `foo(bar)`.

### Discussion

I vaguely understand that the insertion of the call to `Phoenix.Component.Declarative.__pattern__!/2` in the function definition probably causes this. At the time that the documentation is generated, this call is or becomes a phrase with no proper name that `ex_doc` can use. Perhaps the lack of any `attr` or `slot` calls accumulated for the function prevented this. It's interesting that functions with `attr` calls do have the correct docs, but this could be a side-effect of the `assigns` argument having a predetermined name.

Perhaps there is a nice way to lift the original argument name out of the incoming expression and present it to `ex_doc` at the appropriate time. My attempts to do this at the level of `annotate_call/2` were inelegant and unfruitful. I suspect `__on_definition__/6` might have the opportunity.

Happy to contribute, with your help in understanding the problem better.

**Comment by josevalim** [comment]
Hi @aj-foster, I cannot reproduce it. Elixir is smart enough to see a `def foo(%{pattern} = var)` and extract the var. Can you provide a minimal component where you see this?

**Comment by connorlay** [comment]
@josevalim I can look into this if you want. I have a theory as to what could be going on given our use of `defoverride`.

**Comment by aj-foster** [comment]
Hi all 👋🏼 

I produced a minimal example [here](https://github.com/aj-foster/liveview-docs-example/blob/main/lib/example_web/helpers.ex). The generated documentation appears as:

<img width="911" alt="image" src="https://user-images.githubusercontent.com/2789166/192003930-277bb6d8-d615-4ca1-b912-75c949b51712.png">

If there is anything I can do to help, please let me know.

**Comment by josevalim** [comment]
Oh, it is related to functions which are not components. I see. Yeah, we need to be smarter in our macro wrapping I think!

@connorlay please do!

**Comment by aj-foster** [comment]
Just confirmed the fix with my original example. Thank you ❤️
