### ISSUE TITLE
How does live_render work with .18?

### ISSUE THREAD

**Issue by ndrean** [phoenixframework/phoenix_live_view#2223]
### Environment

* Elixir version (elixir -v): 1.14
* Phoenix version (mix deps): 1.16.12
* Phoenix LiveView version (mix deps): 0.17.11 -> 0.18
* Operating system: OSX
* Browsers you attempted to reproduce this bug on (the more the merrier):  any
* Does the problem persist after removing "assets/node_modules" and trying again? Yes

### Actual behavior
Pb with [live_render](https://hexdocs.pm/phoenix_live_view/Phoenix.Component.html#live_render/3)

Controller
```elixir
conn
    |> put_session(:user, profile.email)
    |> put_view(LiveMapWeb.PageView)
    |> render(:welcome, profile: profile)
```

/tempaltes/page/welcome.html.heex
```html
<%= live_render(@conn, LiveMapWeb.MapLive, session: %{"name" => @profile.name, "email" => @profile.email}) %>
```

== Compilation error in file lib/live_map_web/views/page_view.ex ==
** (CompileError) lib/live_map_web/templates/page/welcome.html.heex:10: undefined function live_render/3 (expected LiveMapWeb.PageView to define such a function or for it to be imported, but none are available

### Expected behavior

OK with 0.17.11. The function works the way it is written above

**Comment by josevalim** [comment]
As per the CHANGELOG, you also need to `import Phoenix.Component` were you previously imported `Phoenix.LiveView.Helpers`. :)

**Comment by ndrean** [comment]
Yes, confirmed
