### ISSUE TITLE
function component isn't updating as i'd expect

### ISSUE THREAD

**Issue by nickkaltner** [phoenixframework/phoenix_live_view#2225]
### Environment

* Elixir version (elixir -v):
elixir -v
Erlang/OTP 25 [erts-13.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.14.0 (compiled with Erlang/OTP 23)

* Phoenix version (mix deps):
phoenix 1.7.0-dev (https://github.com/phoenixframework/phoenix.git) (mix)
  locked at 22ef871

* Phoenix LiveView version (mix deps):

* phoenix_live_view 0.18.0 (Hex package) (mix)
  locked at 0.18.0 (phoenix_live_view) 545f11c1

* Operating system:
* macos monterey - 12.5.1 (21G83)

* Browsers you attempted to reproduce this bug on (the more the merrier): 
chrome, safari

* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:
not applicable 

here is some code;

```elixir
defmodule ComponentTestWeb.Widgets do
  use Phoenix.Component

  attr :value, :float, default: 0.0
  attr :width, :integer, default: 200
  attr :show_label, :boolean, default: false

  def inline_bar(assigns) do
    percentage_computed = Math.clamp(assigns.value, 0, 1) * 100
    IO.puts "new inline_bar #{percentage_computed}"
    style = "width: #{percentage_computed}%;"
    words = "#{percentage_computed}"

    ~H"""
    <div
      class="rounded max-h-6 bg-gradient-to-r bg-zinc-100 border-solid border-black border-1"
      style={"width: #{assigns.width}px;"}
    >
      <%= if assigns.show_label do %>
        <div class="float-left mix-blend-overlay bg-blend-color-dodge text-black text-bold max-h-6 pl-2">
          <%= words %>
        </div>
      <% end %>
      <div class="bg-highlight1 rounded transition-width duration-500 max-h-6" style={style}>
        &nbsp;
      </div>
    </div>
    """
  end
end
```

I include it in a live view with this

```
<.inline_bar value={@percentage} show_label={true} />
```

### Actual behavior

![image](https://user-images.githubusercontent.com/822124/192132986-c8fd9100-1ff0-452e-a29e-90b84febc8fe.png)
![image](https://user-images.githubusercontent.com/822124/192132999-4ecbbb14-3bdf-4621-b628-77df9db64f5a.png)

the component changes width (eg. the bar moves) when the assign is updated, but the text does not change.
the logs show the values are changing too
<img width="335" alt="image" src="https://user-images.githubusercontent.com/822124/192133039-b171d34b-d338-420e-9473-019ead42e896.png">

### Expected behavior

I would expect the <%= words %> to update, as it's derived from the same assign the "style" variable is derived from

Apologies if I misunderstand the behaviour

**Comment by josevalim** [comment]
Hi @nickkaltner! You must avoid using variables in your templates, always use assigns, something like below:

```elixir

 def inline_bar(assigns) do
    assigns = assign(assigns, :computed, Math.clamp(assigns.value, 0, 1) * 100)

    ~H"""
    <div
      class="rounded max-h-6 bg-gradient-to-r bg-zinc-100 border-solid border-black border-1"
      style={"width: #{@width}px;"}
    >
      <%= if assigns.show_label do %>
        <div class="float-left mix-blend-overlay bg-blend-color-dodge text-black text-bold max-h-6 pl-2">
          <%= @computed %>
        </div>
      <% end %>
      <div class="bg-highlight1 rounded transition-width duration-500 max-h-6" style={"width: #{@computed}%;"}>
        &nbsp;
      </div>
    </div>
    """
  end
```

LiveView can only track changes in assigns, not in variables.

**Comment by nickkaltner** [comment]
Thank you so much José!  It now works correctly.  I can't believe this was it.  I read the docs several times and didn't realise this - i think it's because to me, the function component isn't a "template" - but it makes sense now :) thank you again

**Comment by nickkaltner** [comment]
I don't know from the code (macros still aren't something i've dived into) but is there a way the ~H can check the types of variables you're using? and warn you ?

**Comment by josevalim** [comment]
It is tricky because why variables are not recommended, they are not exactly forbidden either. And in scenarios like comprehensions and so on, it is ok to use them.

**Comment by connorlay** [comment]
@josevalim I've thought about this and agree we need some kind of UX improvement warning on variable usage in HEEx. I've seen this a lot in the past year or so on a large Live View project. I don't know what the solution looks like though.

**Comment by nickkaltner** [comment]
I believe this fixes it https://github.com/phoenixframework/phoenix_live_view/pull/2236
