### ISSUE TITLE
warning: undefined attribute "autocomplete" for component Phoenix.Component.form/1

### ISSUE THREAD

**Issue by blakedietz** [phoenixframework/phoenix_live_view#2227]
### Environment

* Elixir version (elixir -v):
```
❯ elixir -v
Erlang/OTP 25 [erts-13.0.4] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.14.0 (compiled with Erlang/OTP 25)
```
* Phoenix version (mix deps):
```
* phoenix 1.6.12 (Hex package) (mix)
  locked at 1.6.12 (phoenix) 2d6cf558
  ok
```
* Phoenix LiveView version (mix deps):
```
* phoenix_live_view 0.18.0 (Hex package) (mix)
  locked at 0.18.0 (phoenix_live_view) 545f11c1
  ok
```
* Operating system: macOS Monterey Version 12.4
* Browsers you attempted to reproduce this bug on (the more the merrier): n/a
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

When setting an attribute of `autocomplete="off"` on forms, I'm seeing the following errors when running `mix compile --force --warnings-as-errors`

#### Example code

```elixir
<.form ... autocomplete="off">...</.form>
```
#### Example output

```bash
warning: undefined attribute "autocomplete" for component Phoenix.Component.form/1
```

### Expected behavior

No warning should be shown [since autocomplete is a valid form attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete).

**Comment by chrismccord** [comment]
Already fixed in https://github.com/phoenixframework/phoenix_live_view/commit/a3715873f22fb0e0b0ff9cb81d79567f7dd3f433 Thanks!

**Comment by blakedietz** [comment]
Is there a way to fix this temporarily until the next version of LiveView is released? I've migrated our codebase to 0.18.0 and this warning is the only thing that's stopping me from merging.

**Comment by chrismccord** [comment]
@blakedietz `{:phoenix_live_view, github: "phoenixframework/phoenix_live_view"}`

**Comment by chrismccord** [comment]
Note that I removed `autocomplete` from master. Your permentant solution you can do today is add `attr :autocomplete, :boolean, default: false` to your own input component. Then done!

**Comment by blakedietz** [comment]
> Note that I removed `autocomplete` from master. Your permentant solution you can do today is add `attr :autocomplete, :boolean, default: false` to your own input component. Then done!

I guess I don't understand why a default html attribute like `autocomplete` isn't a part of the form component. What was the reasoning behind this?

**Comment by chrismccord** [comment]
Sorry, I thought you were referring to `autocomplete` on the new input function components on phoenix master which are entirely user land. LiveView master has been changed to allow `autocomplete` on `<.form>` so you can reference LV master if you need the feature before 0.18.1
