### ISSUE TITLE
Compilation error in Engine.bins_and_vars/3 if a <% .. %> expression tag is present in .leex

### ISSUE THREAD

**Issue by guidotripaldi** [phoenixframework/phoenix_live_view#223]
### Environment

* Elixir version (elixir -v): Elixir 1.8.1 (compiled with Erlang/OTP 21)
* Phoenix version (mix deps): phoenix 1.4.2 (https://github.com/phoenixframework/phoenix.git) (mix)
  locked at ef26978 (branch: v1.4)
* NodeJS version (node -v): v11.12.0
* NPM version (npm -v): 6.7.0
* Operating system: macOS 10.14.4

### Actual behavior

This simple code, where an `inline expression tag` is used to hold a temporary value, causes the compilation error
```
  def render(assigns) do
    ~L"""
       <h3>Test</h3>
       <% my_tmp_value = 42 %>
       <p>my_tmp_value: <%= inspect my_tmp_value %></p>
     """
  end
```

Here it is the compiler complaint:
```
== Compilation error in file lib/demo_web/live/counter_live.ex ==
** (FunctionClauseError) no function clause matching in Phoenix.LiveView.Engine.bins_and_vars/3

    The following arguments were given to Phoenix.LiveView.Engine.bins_and_vars/3:

        # 1
        ["  <h3>Test</h3>\n  ", "\n  <p>my_tmp_value: ", {:arg0, [], Phoenix.LiveView.Engine}, "</p>\n"]

        # 2
        []

        # 3
        []

    Attempted function clauses (showing 4 out of 4):

        defp bins_and_vars([bin, var | acc], bins, vars) when is_binary(bin) and is_tuple(var)
        defp bins_and_vars([var | acc], bins, vars) when is_tuple(var)
        defp bins_and_vars([bin], bins, vars) when is_binary(bin)
        defp bins_and_vars([], bins, vars)

    lib/phoenix_live_view/engine.ex:393: Phoenix.LiveView.Engine.bins_and_vars/3
    lib/phoenix_live_view/engine.ex:353: Phoenix.LiveView.Engine.to_rendered_struct/3
    lib/phoenix_live_view/engine.ex:237: Phoenix.LiveView.Engine.handle_body/1
    expanding macro: Phoenix.LiveView.sigil_L/2
    lib/demo_web/live/counter_live.ex:31: DemoWeb.CounterLive.render/1
    (elixir) lib/kernel/parallel_compiler.ex:208: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6

```

Instead, if a `replace expression tag` is used to hold the temporary value, it works as expected
```
defmodule DemoWeb.CounterLive do
  use Phoenix.LiveView

  def render(_assigns) do
    ~L"""
       <h3>Test</h3>
       <%= my_tmp_value = 42
            " "
       %>
       <p>my_tmp_value: <%= inspect my_tmp_value %></p>
     """
  end

  ...
```

And it works also if we move the expression tag in a partial:

```
defmodule DemoWeb.CounterLive do
  use Phoenix.LiveView

  def render(assigns) do
    ~L"""
      <h3>Test</h3>
      <%= Phoenix.View.render(DemoWeb.PageView, "test.html", assigns) %>
     """
  end

  ...
```
```eex
# file test.html.eex
	<% my_tmp_value = 42 %>
	<p>my_tmp_value: <%= inspect my_tmp_value %></p>
```
### Expected behavior

` .leex` templates with `inline expression tags` inside,  should be compiled without errors

**Comment by chrismccord** [comment]
I don't believe we can properly change track inline expressions with bindings like that. Your best option even if we fix this error is to assign a variable to the socket hen reference it in the template rather than the inline binding. I'll let José confirm if we will support this, but it is unlikely.

**Comment by guidotripaldi** [comment]
Thank you Chris. But just in case, is it legitimate to use the inline expressions in a `.eex` partial, rendering it from LiveView, as in my last example, or it might cause future problems?

**Comment by chrismccord** [comment]
In general, inline expressions are an anti pattern since you are embedding logic and details in the view which are better done in a function or assigns.

**Comment by josevalim** [comment]
All valid .eex code should compile, so this is definitely a bug. I am on it. :)

**Comment by josevalim** [comment]
And this is actually already fixed in master, please upgrade. :)
