### ISSUE TITLE
Phoenix.FocusWrap hook not found

### ISSUE THREAD

**Issue by bigardone** [phoenixframework/phoenix_live_view#2232]
### Environment

* Elixir version (elixir -v): Elixir 1.14.0
* Phoenix version (mix deps): 1.6.6
* Phoenix LiveView version (mix deps): 0.18.0
* Operating system: macOS Monterey
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

I have updated my project to `v0.18.0` and I'm trying to use the new `.focus_wrap` component like in the docs:

```elixir
<.focus_wrap id="new_iteml" class="w-[568px] h-screen flex flex-col">
...content
</.focus_wrap>
```

However, I get the following error in the browser:

```
utils.js:7 unknown hook found for "Phoenix.FocusWrap"
```

I've tried adding it manually, just in case, with something like the following, but neither work:

```js

// ....

import PhoenixHooks from '../../deps/phoenix_live_view/assets/js/phoenix_live_view/hooks';

export default {
  Phoenix: {
    FocusWrap: PhoenixHooks.FocusWrap,
  },
  'Phoenix.FocusWrap': PhoenixHooks.FocusWrap,
  ...
}
```

### Expected behavior

The hook should exist?

**Comment by chrismccord** [comment]
How are you building your assets? If you are using node, please ensure you have the latest js dependency. This hook definitely exists on the 0.18 release :) Thanks!

**Comment by bigardone** [comment]
👋🏼 Hi @chrismccord , thanks for the response. I'm not using node, just the default `esbuild` hex package. If I inspect  `PhoenixHooks` from `../../deps/phoenix_live_view/assets/js/phoenix_live_view/hooks` it actually exists, but it is not working whatsoever 🤷🏼‍♂️

**Comment by chrismccord** [comment]
I just used it from a project using `{:phoenix_live_view, "~> 0.18"}` and it works fine so unless you have a way to recreate, I can't really say what's going on. If `Phoenix.FocusWrap` is undefined internally it would have to be js build related I think. I also checked that the 0.18.0 js build indeed included the FocusWrap, so I'm pretty confident it's on your side. Can you double check that your LV dup is actually pointing to 0.18? Can you try a fresh project to rule out something else? Thanks!

**Comment by bigardone** [comment]
I have created a new project from scratch that reproduces the error: https://github.com/bigardone/live-view-focus-wrap-issue

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/1090272/192691171-83e3c638-f29c-4e14-a35a-e85151451503.png">

This is what I did:

- Created the new project using `mix phx.new`
- Updated `phoenix_live_view` to `0.18.0`
- Created a `MyAppWeb.HomeLive` module.
- Added the `focus_wrap` component.
- Added a custom `Log` hook as well to test that hooks are working.

I've tried deleting both `deps` and `_build` folders, but the error persists.
On the flipside, if I open `./deps/phoenix_live_view/assets/js/phoenix_live_view/hooks.js`, I can see the hook there:

/Users/ricardogarciavega/projects/elixir/my_app/deps/phoenix_live_view/assets/js/phoenix_live_view/hooks.js

I hope this helps

**Comment by nathanmalishev** [comment]
I had the same issue. Removed `_build` and `node_modules` in assets, resolved the issue :)

**Comment by chrismccord** [comment]
This must be something specific to your setup. Are you absolutely positive you don't have an older server running on localhost and you're hitting the wrong app? Does your compiled js bundle served from the app contain the hook?

**Comment by bigardone** [comment]
Yeah, it's a brand new phoenix project from scratch, without npm deps. I've tried removing `_build`, `deps`, unlocking and removing `phoenix_live_view`, and installing `0.18.1`, but the issue persists. So weird 🤷🏼‍♂️ 

<img width="3360" alt="image" src="https://user-images.githubusercontent.com/1090272/193192561-be7a7203-b849-43b1-b0d2-fdca837c5e54.png">

Have you had the chance to try this https://github.com/bigardone/live-view-focus-wrap-issue ?

**Comment by connorlay** [comment]
@bigardone I cloned your repo and cannot reproduce the issue in Firefox or Chromium on Ubuntu 22 🤔 Tabbing between the two buttons works as expected. Have you tried clearing your browser cache, or trying a different browser to reproduce the issue?

**Comment by bigardone** [comment]
I've also tried both Safari and Firefox and same issue:

<img width="2105" alt="image" src="https://user-images.githubusercontent.com/1090272/193197486-23306f08-4245-4ec0-af66-8ef096e231f5.png">

It's definitely something on my side. Anyways, thanks a lot for the help 🙌🏼

**Comment by bigardone** [comment]
👋🏼 I'm still having the same issue. However, I've found that if I import `LiveSocket` from the build folder like the following, everything works fine:

```js
import { LiveSocket } from '../../_build/dev/lib/phoenix_live_view/priv/static/phoenix_live_view.cjs';
```

So the issue is with the default import:

```js
import { LiveSocket } from 'phoenix_live_view';
```

Somehow it is loading an outdated cached version from somewhere.

**Comment by bigardone** [comment]
I found the issue. There were outdated versions in my `~/node_modules` folder 🤷🏼‍♂️ . Thanks for the help 🙌🏼
