### ISSUE TITLE
Improve the error message when attempting to render a LiveComponent outside of a LiveView

### ISSUE THREAD

**Issue by ccapndave** [phoenixframework/phoenix_live_view#2233]
This is just a suggestion, not an actual bug.

### Environment

* Elixir version (elixir -v): Elixir 1.14.0 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): 1.6.12
* Phoenix LiveView version (mix deps): 0.18.0

### Actual behavior

Recently, I accidentally put a `<.live_component>` into a normal HTML page rendered from a controller, instead of a LiveView.  The error message says:

```
cannot convert component ListComponent with id :list_component to HTML.
A component must always be returned directly as part of a LiveView template.

For example, this is not allowed:

    <%= content_tag :div do %>
      <.live_component module={SomeComponent} id="myid" />
    <% end %>

That's because the component is inside `content_tag`. However, this works:

    <div>
      <.live_component module={SomeComponent} id="myid" />
    </div>

Components are also allowed inside Elixir's special forms, such as
`if`, `for`, `case`, and friends.

    <%= for item <- items do %>
      <.live_component module={SomeComponent} id={item} />
    <% end %>

However, using other module functions such as `Enum`, will not work:

    <%= Enum.map(items, fn item -> %>
      <.live_component module={SomeComponent} id={item} />
    <% end %>
```

### Expected behavior

Although the `A component must always be returned directly as part of a LiveView template.` bit of the error is correct, the examples suggest the cause of the problem is something else.  It would be nice to clarify the error message to include this extra case.

**Comment by chrismccord** [comment]
This error is working double duty for a few cases, but it's still correct (emphasis mine):

> A component must always be returned directly *as part of a LiveView template*

If you think it could be improved, we'd welcome a PR. Thanks!
