### ISSUE TITLE
Formatter adds space/newline to inline elements

### ISSUE THREAD

**Issue by krns** [phoenixframework/phoenix_live_view#2237]
### Environment

* Phoenix LiveView version (mix deps): 0.18.0

### Actual behavior

We made a simple `abbr` component to handle abbreviations inline:

```html
<p>
  A program or a programmer that uses one of these parts is said to call that portion of the (<.abbr label="application programming interface">API</.abbr>).
</p>
```

The paragraph is formatted as follows:

```html
<p>
  A program or a programmer that uses one of these parts is said to call that portion of the 
  (
  <.abbr label="application programming interface">API</.abbr>
  ).
</p>
```
Unfortunately because of the line breaks the part `(API)` is rendered as `( API )`. 

### Expected behavior

There shouldn't be added space / newlines.

**Comment by krns** [comment]
Btw the surrounding text is irrelevant.. the following will result in the same format:

```html
<p>
  (<.abbr label="application programming interface">API</.abbr>)
</p>
```

results in

```html
<p>
  (
  <.abbr label="application programming interface">API</.abbr>
  )
</p>
```

**Comment by feliperenan** [comment]
@krns thanks for reporting this. I will take a look at this later. For now you can do `<p phx-no-format>...<p>` so the formatter will ignore it.

**Comment by krns** [comment]
I just tested the latest version and now it works. Thanks @feliperenan 🙃
