### ISSUE TITLE
 Phoenix.Component.{link,form, etc} shadow any local definitions

### ISSUE THREAD

**Issue by elliottneilclark** [phoenixframework/phoenix_live_view#2238]
### Environment

* Elixir version (elixir -v): Elixir 1.14.0 (compiled with Erlang/OTP 25)
* Phoenix Liveview version (mix deps): phoenix_live_view 0.18.1 (Hex package) (mix)
* Operating system: Linux

### Expected behavior
I want to be able to provide a default styled link with some different variants. Something equivalent to:

```elixir
defmodule CommonUI.Link do
  use Phoenix.Component

  attr :navigate, :string
  attr :type, :string, default: "unstyled"
  def link(%{type: "unstyled"} = assigns) do
    ~H"""
    <.link />
    """
  end

    def link(%{type: "styled"} = assigns) do
    ~H"""
    <.link class="text-semibold"/>
    """
  end
end
```

### Actual behavior

However `use Phoenix.Component` always imports `link/1` so compilation fails with:

```
== Compilation error in file lib/link.ex ==
** (CompileError) lib/link.ex:1: imported Phoenix.Component.link/1 conflicts with local function
```

The cleanest I can think of is to move the components in "Phoenix.Component" into their own module and have view_helpers import that module. However that would be a breaking change, and hurts the usability of creating components outside of a phoenix web project with view_helpers.

Or add an option for `except` onto `_using__/1` such that someone can drop the tags that have a project default.

```elixir
defmodule CommonUI.Link do
  use Phoenix.Component, except: [link 1]

  attr :navigate, :string
  attr :type, :string, default: "unstyled"
  def link(%{type: "unstyled"} = assigns) do
    ~H"""
    <Phoenix.Component.link />
    """
  end

    def link(%{type: "styled"} = assigns) do
    ~H"""
    <Phoenix.Component.link class="text-semibold"/>
    """
  end
end

defmodule MyWeb do
  def component do
    quote do
      use Phoenix.Component, except: [link: 1]

      unquote(view_helpers())
    end
  end
  defp view_helpers do
    quote do
      use CommonUI

      import Phoenix.Component, except: [link: 1]
    end
  end  
end

**Comment by chrismccord** [comment]
You can conditionally import those functions or name your functions something else, the letter of which may be less confusing. Thanks!

**Comment by elliottneilclark** [comment]
> You can conditionally import those functions

No you can't on any module that defines components.

**Comment by chrismccord** [comment]
Right, but any scope that your code exists in will have its own `use Phoenix.Component` and you can use `:except` in those cases

**Comment by elliottneilclark** [comment]
> any scope that your code exists in will have its own use Phoenix.Component and you can use :except in those cases

I'm not sure I am following that. This doesn't work:

```elixir
defmodule MyLink do
  use Phoenix.Component, except: [link: 1]

  attr :navigate, :string
  attr :type, :string, default: "unstyled"
  def link(%{type: "unstyled"} = assigns) do
    ~H"""
    <Phoenix.Component.link />
    """
  end

    def link(%{type: "styled"} = assigns) do
    ~H"""
    <Phoenix.Component.link class="text-semibold"/>
    """
  end
end
```

That gets this error:

```
== Compilation error in file lib/link.ex ==
** (ArgumentError) invalid options passed to Phoenix.Component.Declarative.

The following options are supported: [:global_prefixes], got: [except: [link: 1]]

    (phoenix_live_view 0.18.1) lib/phoenix_component/declarative.ex:210: Phoenix.Component.Declarative.__setup__/2
    lib/link.ex:2: (module)
    (stdlib 4.0.1) lists.erl:1350: :lists.foldl/3
```

I don't think it's possible to have a module with a user defined 'link/1' and `use Phoenix.Component` in the same scope. So there's no using our own .link in components. [Petal Components](https://github.com/petalframework/petal_components/commit/ba1f46902bb3e91d48f8ddba42d5be81031b81ee) had to rename their link component to .a instead.

**Comment by josevalim** [comment]
You must do `import Phoenix.Component, except: [link: 1]` after you use. `except` is not a valid option for `use`.

**Comment by elliottneilclark** [comment]
> You must do import Phoenix.Component, except: [link: 1] after you use.

but the `use Phoenix.Component` will expand to `import Phoenix.Component` with no except.

> except is not a valid option for use.

I know that's actually one of the solutions I am suggesting. Make `Phoenix.Component.__using__/1` handle the except opts correctly.

**Comment by josevalim** [comment]
> but the use Phoenix.Component will expand to import Phoenix.Component with no except. importing again doesn't seem to make that go away when I tested. It just moves when the error shows up.

You can import a module later again with except, and it will remove those listed in except. Try it! :)

**Comment by josevalim** [comment]
```
iex(1)> import List
List
iex(2)> flatten([1, 2, 3])
[1, 2, 3]
iex(3)> import List, except: [flatten: 1]
List
iex(4)> flatten([1, 2, 3])
** (CompileError) iex:4: undefined function flatten/1 (there is no such import)
    (elixir 1.15.0-dev) src/elixir.erl:377: :elixir.quoted_to_erl/3
    (elixir 1.15.0-dev) src/elixir.erl:287: :elixir.eval_forms/3
    (elixir 1.15.0-dev) lib/module/parallel_checker.ex:101: Module.ParallelChecker.verify/1
    (iex 1.15.0-dev) lib/iex/evaluator.ex:329: IEx.Evaluator.eval_and_inspect/3
    (iex 1.15.0-dev) lib/iex/evaluator.ex:303: IEx.Evaluator.eval_and_inspect_parsed/3
    (iex 1.15.0-dev) lib/iex/evaluator.ex:292: IEx.Evaluator.parse_eval_inspect/3
    (iex 1.15.0-dev) lib/iex/evaluator.ex:187: IEx.Evaluator.loop/1
```

**Comment by elliottneilclark** [comment]
Yep I tried that unfortunately.

I have this code: https://gist.github.com/elliottneilclark/6e2d4cda5db7cd91d2f89c9a9deaec60

Compiling gives this error: https://gist.github.com/elliottneilclark/f1403a95ca9e2e20d7ac4319fbc6ce23

The code the errors out is a live view that depends on a component that depends on a component in another project. Simpler examples work.

**Comment by josevalim** [comment]
You are probably excepting it too early. Check `__ENV__` and see the imports. Make sure to apply it after `use`.

**Comment by elliottneilclark** [comment]
Thank you for the help. I'll keep debugging since your solution obviously should work. Thank you again

**Comment by elliottneilclark** [comment]
Today I learned that when you import a dependent module you are also getting all of the things that dependent ever imported. Also how hard that is to track down.

**Comment by josevalim** [comment]
Hi @elliottneilclark, that’s also not true. When you use a module, it may import other modules for you, but imports by themselves are never transitive.

It may be your code is doing a mix of imports and use of several modules and that’s where the complexity is, if that’s the case, it may be worthy untangling that.
