### ISSUE TITLE
Updating from 0.17.12 to 0.18.1 update form actions missing hidden "_method" input

### ISSUE THREAD

**Issue by cpgo** [phoenixframework/phoenix_live_view#2246]
### Environment

* Elixir version (elixir -v):
Erlang/OTP 25 [erts-13.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.14.0 (compiled with Erlang/OTP 23)

* Phoenix version (mix deps):
phoenix 1.6.13 (Hex package) (mix)
locked at 1.6.13 (phoenix) 13d8806c

* Phoenix LiveView version (mix deps):
phoenix_live_view 0.18.1 (Hex package) (mix)
locked at 0.18.1 (phoenix_live_view) b785e1cc

* Operating system:
Ubuntu
* Browsers you attempted to reproduce this bug on (the more the merrier): 
Chrome, Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:
Yes

### Actual behavior
After updating live_view version form generated by `<.form :let={f} for={@changeset} action={@action}>` on an `edit` action does not have the hidden "_method = put" input causing the update request to `POST` to an invalid route.

One change I noticed was the change from `let` to `:let` mentioned on the changelog but I cant find anything related to the form action.
Am I missing something?
### Expected behavior

The generated form should have a hidden `_method` input

This is the commit that caused the problem https://github.com/cpgo/bill_crud/commit/893d564103e6a08c90b9570d2ce186934ea11592

**Comment by benoawfu** [comment]
The [`form_for` documentation](https://hexdocs.pm/phoenix_html/Phoenix.HTML.Form.html#form_for/4) states that by default the method is "POST".

Why do we have this default set to "PUT" with the Liveview `form` component? (I couldn't find the related documentation talking about this behaviour).
Couldn't the method be deduced along with the action from the route (if we point to a router route) ? router has all that info already, one change there should be all that's needed.

**Comment by cpgo** [comment]
Not sure where on the docs this is mentioned, but I know that if you give `form_for` or `.form` a changeset thats from an already persisted schema it will automatically create the hidden "_method" input with the value "put".

This was always the case, I opened this issue because this behavior changed with live_view 0.18.1 but its fixed now on 0.18.2

**Comment by benoawfu** [comment]
Yeah, after this problem with 0.18.1 we moved to POST on all our form submission routes to get our way around it, but now it backfired with 0.18.2.
We've settled to add `method="post"`on all our forms, so that the behaviour doesn't change in the future.

**Comment by cpgo** [comment]
After some digging I think I identified more precisely what phoenix looks for at the FormData to decide its method.
Its a `defimpl Phoenix.HTML.FormData, for: Ecto.Changeset` on the `phoenix_ecto` integration package.
https://github.com/phoenixframework/phoenix_ecto/blob/v4.4.0/lib/phoenix_ecto/html.ex#L322-L323

> Why do we have this default set to "PUT" with the Liveview form component? (I couldn't find the related documentation talking about this behaviour).

Looks like it was a bug on the phoenix component `form` helper so the `form_for` documentation is still correct
