### ISSUE TITLE
** (ArgumentError) unsupported scheme given to redirect/2.

### ISSUE THREAD

**Issue by crova** [phoenixframework/phoenix_live_view#2248]
### Environment

* Elixir version (elixir -v): Elixir 1.14.0 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): phoenix 1.6.12 (Hex package) (mix)
* Phoenix LiveView version (mix deps): phoenix_live_view 0.18.1 (Hex package) (mix)
* Operating system: Ubuntu 20.04
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

After bumping from `phoenix_live_view 0.17.11` to `0.18.1` passing a custom scheme URI to `redirect/2` will raise an exception:
```elixir
Phoenix.LiveView.redirect(socket, external: "custom_scheme://someuri.com")

** (ArgumentError) unsupported scheme given to redirect/2. In case you want to link to an
unknown or unsafe scheme, such as javascript, use a tuple: {:javascript, rest}
```

So I tried passing `external: {:javascript, uri}` and got:
```elixir
Phoenix.LiveView.redirect(socket, external: {:javascript, "custom_scheme://someuri.com"})

** (ArgumentError) expected :external option in redirect/2 to be valid URL, got: {:javascript, "custom_scheme://someuri.com"}
```

### Expected behavior
```elixir
Phoenix.LiveView.redirect(socket, external: "custom_scheme://someuri.com")
# user gets redirected
# or at least, by using the suggestion from the first exception:
Phoenix.LiveView.redirect(socket, external: {:javascript, "custom_scheme://someuri.com"})
# user gets redirected
```

### Comment
[This tests](https://github.com/phoenixframework/phoenix_live_view/commit/74d3673df81cf902368de2683530d679993bef45#diff-00b59ee51f11c0adeb778f7396badfe77bb1f122d026afe6c2f5ea58d6021f96R417-R428) indicates that the suggestion from the first exception message is not really an option, as it will raise as well.

[This looks like the change](https://github.com/phoenixframework/phoenix_live_view/commit/74d3673df81cf902368de2683530d679993bef45#diff-342f13c3b0c7f180d1babf918156af38462ead68395f51b90874c7228bd02e7fR1245-R1254) that introduced this new restriction on `unknown` schemes.

So I'm confused as to how one should redirect to external custom scheme URIs.

Our use case is to redirect to external mobile apps.

[I created a small patch](https://github.com/crova/phoenix_live_view/tree/fix-redirect) so we can fix on our app the redirection.
I would be happy to open a PR once I understand what's supposed to happen here.

Let me know if you need more information and thanks a lot for all the great work put on this.

Cheers.

**Comment by josevalim** [comment]
You must do:  `external: {:custom_scheme, "//rest"}`.

**Comment by josevalim** [comment]
Ignore me, we force string validation at the moment.
