### ISSUE TITLE
Strange behavior when rendering a static template inside a live one

### ISSUE THREAD

**Issue by jackalcooper** [phoenixframework/phoenix_live_view#225]
### Environment

* Elixir version (elixir -v): 1.8.2
* Phoenix version (mix deps): 1.4.6 
* NodeJS version (node -v): v12.1.0
* NPM version (npm -v): 6.9.0
* Operating system: macOS

### Actual behavior

There is a live render function like this:
```elixir
def render(assigns) do
    ~L"""
    <pre>
      <svg viewBox="0 0 500 500" class="chart">
        <%= Phoenix.View.render(XXXWeb.SvgView, "polyline.svg", []) %>
      </svg>
    </pre>
    """
  end
```
If `polyline.svg` is a `leex` file, it got rendered correctly. 
![image](https://user-images.githubusercontent.com/5133557/57969580-2f36cd80-79ab-11e9-9ecc-fb5664283330.png)

If `polyline.svg` is a `exx` file, I got what is shown below is not recognized by browser.
![image](https://user-images.githubusercontent.com/5133557/57969550-ba639380-79aa-11e9-8320-4c6b96853db9.png)

### Expected behavior'
It should not be mandatory to use a `leex` template when it is rendered by `Phoenix.View.render`.

**Comment by josevalim** [comment]
The HTML is being escaped. You need to do this:

    <%=raw Phoenix.View.render(XXXWeb.SvgView, "polyline.svg", []) %>

**Comment by jackalcooper** [comment]
It works. Thanks a lot!
