### ISSUE TITLE
Upload tutorial file path triggers live reload for images

### ISSUE THREAD

**Issue by jsmestad** [phoenixframework/phoenix_live_view#2253]
## Background

While trying to implement LiveView uploads I was pulling my hair out because the Plug.Upload file kept disappearing. 

I could not figure out the cause until it hit me: the default [live_reload config](https://github.com/phoenixframework/phoenix/blob/master/installer/templates/phx_single/config/dev.exs#L51) uses `priv/static/*.(png|jpg|....)` which is the [same save location](https://github.com/phoenixframework/phoenix_live_view/blob/d3e91b04a0281796e129c77091eea1fcabf66f54/guides/server/uploads.md?plain=1#L232) used by the Upload tutorial.

## What happens
Whenever the file is copied into the path this triggers a recompilation due to the live_reload pattern match and thus reaping the current process and the Plug.Upload path goes missing.

## Suggested Change

Most folks are probably testing this with image files, so I'd suggest using an alternative path in the tutorial. Since the path makes sense though, we could also add a disclaimer in the tutorial. I really wasn't sure which is least disruptive.

**Comment by chrismccord** [comment]
This is a tricky one because the shortest path to serving the files that were uploaded is to put them into priv/static, so they can be picked up by the `Plug.Static`. The alternative is to place them own something like `priv/uploads`, then add another Plug.Static definition, or update the live reload patterns in the guide to ignore the uploads dir. The latter gets my vote. Can you send a PR? Thanks!

**Comment by chrismccord** [comment]
Ping @jsmestad any interest in sending PR to the guides? Thanks!

**Comment by jsmestad** [comment]
@chrismccord definitely interested in contributing when I can find the time. Crunch time getting [HeadsDown](https://www.headsdown.app) out the door 🔥

**Comment by josevalim** [comment]
This is tricky because we want to add them to priv/static so we can render them :S
