### ISSUE TITLE
How we call components.

### ISSUE THREAD

**Issue by theguuholi** [phoenixframework/phoenix_live_view#2262]
### Environment

Hey, @josevalim or @chrismccord  I am a super fan of Liveview, And I think if we have a way to use components would be super awesome, I would like to hear from you guys what do you think, and Also if you guys approve I can try to implement this behavior: 

### Actual behavior
<img width="913" alt="Screen Shot 2022-10-07 at 07 05 47" src="https://user-images.githubusercontent.com/12762300/194529205-3e8a7dbf-8b7f-46cf-b02d-1912d04c79b7.png">

**Comment by josevalim** [comment]
There are no plans at the moment. Module components have additional costs, so we want to make them quite distinct, API wise, from calling function components.

**Comment by simonmcconnell** [comment]
@theguuholi you can use Surface if you want that kind of syntax.
