### ISSUE TITLE
Support global attrs within slots

### ISSUE THREAD

**Issue by mveytsman** [phoenixframework/phoenix_live_view#2265]
Currently if I have a slot with a global

```elixir
slot :myslot do
  attr :rest, :global
end
```

And I use it as 
```heex
<:myslot class="foo">
  content
</:myslot>
```

`rest` will not actually get populated, e.g. in 

```heex
 <%= for myslot <- @myslot do %>
```

the value of `myslot` is  `%{__slot__: :myslot, class: "foo"}`
 instead of `%{__slot__: :myslot, rest: %{class: "foo"}}`

I fixed an exception that would be thrown when compiling the above code in https://github.com/phoenixframework/phoenix_live_view/pull/2264 . I'd be up for tackling adding support for globals in slots, but would appreciate a bit of guidance how to handle it. Currently we merge in the named globals as part of compiling the function body - should this be factored into a function that's called when ever we invoke slots as well?

**Comment by josevalim** [comment]
I think you can skip the do-block in slots and it will accept anything, no?

the tricky part with global in slots is the runtime preprocessing.

**Comment by mveytsman** [comment]
> I think you can skip the do-block in slots and it will accept anything, no?

Not sure I understand what that means.

Maybe this will make what I meant clearer:

```heex
<div :for={myslot <- @myslot} {myslot.rest}>
  <%= render_slot(myslot) %>
</div>
```

Above won't work. Maybe that's by design, in which case we can update the docs and maybe [warn](https://github.com/phoenixframework/phoenix_live_view/blob/master/lib/phoenix_component/declarative.ex#L502-L505) like we do when trying to use default within slot attributes...

**Comment by connorlay** [comment]
https://github.com/phoenixframework/phoenix_live_view/issues/2164 the current plan is to raise a compilation error.

**Comment by josevalim** [comment]
I meant to specify only the slot but none of its attributes!

**Comment by TunkShif** [comment]
I've encountered the same problem. What I'm trying to build is a component used roughly like this:

```heex
<.component>
  <:trigger><div class="my-button-comp">Show</div></:trigger>
</.component>

<!-- renders to this -->

<div class="my-button-comp">Show</div>

<.component>
  <:trigger as="button" class="my-button" >Show</:trigger>
</.component>

<!-- renders to this -->

<button class="my-button">Show</button>
```

But currently with the component definition below, `rest` doesn't exist in slot's attributes.

```elixir
slot(:trigger, required: true) do
  attr :as, :string
  attr :rest, :global
end

def component(assigns) do
  ~H"""
  <%= for t <- @trigger do %>
    <%= if t[:as] do %>
      <.dynamic_tag name={t.as} {t.rest}><%= render_slot(t) %></.dynamic_tag>
    <% else %>
      <%= render_slot(t) %>
    <% end %>
  <% end %>
  """
end
```

If it's designed to be like this, maybe it's better to indicate that in the documentation or raise a compilation error.

**Comment by josevalim** [comment]
Yes, it is meant to raise. See #2164!
