### ISSUE TITLE
Function components generates wrong output depending on the slots order

### ISSUE THREAD

**Issue by shamanime** [phoenixframework/phoenix_live_view#2266]
### Environment

* Elixir version (elixir -v): 1.14.0
* Phoenix version (mix deps): from master
* Operating system: Linux

### Expected behavior

Given this component:
```
  @doc """
  Sample component that demonstrates a bug.

  <.sample_component>
    <:entry :if={false}>0</:entry>
    <:entry>1</:entry>
    <:entry :for={entry <- [2, 3]}><%= entry %></:entry>
    <:entry>4</:entry>
  </.sample_component>

  """
  slot :entry

  def sample_component(assigns) do
    ~H"""
    <p>Sample component</p>
    <ul>
      <li :for={entry <- @entry}><%= render_slot(entry) %></li>
    </ul>
    """
  end
```

When it is called as the doc the HTML should be:

```
<p>Sample component</p>
<ul>
  <li>1</li>
  <li>2</li>
  <li>3</li>
  <li>4</li>
</ul>
```

### Actual behavior

The generated HTML is:

```
<p>Sample component</p>
<ul>
  <li></li>
  <li>1</li>
  <li>23</li>
  <li>4</li>
</ul>
```

Oh wow I opened the issue on the wrong repo, this belongs to https://github.com/phoenixframework/phoenix_live_view instead. Can it be transferred please?

**Comment by shamanime** [comment]
@chrismccord do you know when we will get a release for 0.18.3? This bug is blocking us right now from replacing some old code and I can't work around it without this fix. The whole app is LV so using master is a bit troublesome. Thanks!

**Comment by chrismccord** [comment]
Soon? You can freely use master or depend direction this commit `{:phoenix_live_view, github: "phoenixframework/phoenix_live_view", ref: "74ecf58a991084ad8786f49bd2aa1688ca99283e"}`
