### ISSUE TITLE
feature request: support combined types for `attr` macro

### ISSUE THREAD

**Issue by ouven** [phoenixframework/phoenix_live_view#2267]
### Environment

* Elixir version (elixir -v): 14
* Phoenix version (mix deps): 1.6
* Phoenix LiveView version (mix deps): 1.18

### Shoutout

Huge "THANK YOU" for this feature!

### Context

I want to define a form field component that delegates to the Phoenix.HTML.Form functions.

### Problem

I need to have an attribute `form`, that either accepts a `Phoenix.HTML.Form` struct or an `:atom` like:

  `attr :form, Phoenix.HTML.Form | :atom, required: true`

which does not compile. Is there anything planned to achieve this?

**Comment by josevalim** [comment]
There are no plans at the moment, because there is little validation we can do in such cases. Using any is the way to go.
