### ISSUE TITLE
Undefined function f/0 using form bindings examples from docs

### ISSUE THREAD

**Issue by williamthome** [phoenixframework/phoenix_live_view#2275]
I'm trying to use a form in a template using the [docs examples](https://hexdocs.pm/phoenix_live_view/form-bindings.html), but I receive this exception:
```console
== Compilation error in file lib/todo_web/live/page_live.ex ==
** (CompileError) lib/todo_web/live/page_live.ex:30: undefined function f/0 (expected TodoWeb.PageLive to define such a function or for it to be imported, but none are available)
```

[ElixirLS](https://github.com/elixir-lsp/vscode-elixir-ls) highlight the code with this msg in VSCode:
> variable "f" does not exist and is being expanded to "f()", please use parentheses to remove the ambiguity or change the variable nameElixir
(CompileError) undefined function f/0 (expected TodoWeb.PageLive to define such a function or for it to be imported, but none are available)Elixir

The docs set the `f` function as `:let={f}`. I receive no exception removing the colon at the beginning, like `let={f}`.
Am I missing something? Or the docs examples are wrong?

Docs example (causing exception):
```heex
<.form :let={f} for={@changeset} phx-change="validate" phx-submit="save">
  <%= label f, :username %>
  <%= text_input f, :username %>
  <%= error_tag f, :username %>

  <%= label f, :email %>
  <%= text_input f, :email %>
  <%= error_tag f, :email %>

  <%= submit "Save" %>
</.form>
```

Working one:
```heex
<.form let={f} for={@changeset} phx-change="validate" phx-submit="save">
  <%= label f, :username %>
  <%= text_input f, :username %>
  <%= error_tag f, :username %>

  <%= label f, :email %>
  <%= text_input f, :email %>
  <%= error_tag f, :email %>

  <%= submit "Save" %>
</.form>
```

**Comment by josevalim** [comment]
:let was introduced in v0.18. Please make sure your LV version matched the one you are reading the docs for!
