### ISSUE TITLE
Flashing element on `phx-connected` / `phx-disconnected`

### ISSUE THREAD

**Issue by moogle19** [phoenixframework/phoenix_live_view#2276]
### Environment

* Elixir version (elixir -v): 1.14.1
* Phoenix version (mix deps): 1.16.4
* Phoenix LiveView version (mix deps): 0.18.2
* Operating system: macOS
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome / Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:

### Actual behavior
Currently the `phx-disconnected` binding is executed on every page load before the LiveSocket is connected. 
This means if a message is displayed (like in the [example](https://hexdocs.pm/phoenix_live_view/bindings.html#lifecycle-events)) the message flashes on every page reload.
I think it would be nice to delay the `phx-disconnected` binding on initial page load.

The same problem exists when changing the page from a live view to a dead view where the message flashes for a moment before the page changes.

Here are two examples:

Reloading (fresh Phoenix 1.16.4 project with the code snippet from the hex docs example):

https://user-images.githubusercontent.com/792046/195353415-c113c3b9-680f-4ca4-ae7b-29672d4b721f.mov

Page changing (project generated from the current phoenix master branch and `phx.gen.auth --live` generated pages) :

https://user-images.githubusercontent.com/792046/195353479-b8e23a05-48ce-4f5c-9ae8-8a4e01a84cad.mov

**Comment by chrismccord** [comment]
To be clear just so I understand the problem correctly, the containers are *not* shown on initial page load correct? Only on refresh or navigate away? Thanks!

**Comment by moogle19** [comment]
No, it also shows during the initial page load:


https://user-images.githubusercontent.com/792046/195360801-be5bdc28-ff4a-4ec5-9bb8-c56767a09040.mov

**Comment by lud** [comment]
To me it only happens on leave. For instance if the page displays a link to an external page and I click on it. On page load the behaviour is as expected.

**Comment by rgraff** [comment]
Not sure if related or helpful, but this occurs for me when I remove the `hidden` class from the flash div.

**Comment by coladarci** [comment]
@rgraff this save me a lot of time - I must have removed the` hidden` class from the parent div at some point when debugging something. Putting it back did the trick..
