### ISSUE TITLE
Form recovery for nested LiveViews

### ISSUE THREAD

**Issue by SteffenDE** [phoenixframework/phoenix_live_view#2281]
Hello everyone,

I am using nested LiveViews for a page and noticed that form recovery inside a child LiveView does not work, as it is not included in the initial mount message after a reconnect and therefore removed from the DOM. When the child LiveView then connects the old form is gone. I see that this is potentially not an easy thing to handle, as it would probably require storing the old DOM until every view is reconnected. What do you think?

In this case I do not want to switch to using LiveComponents as each child view handles its own PubSub messaging and doing all this in the parent LiveView would make things quite ugly and would be rather painful to maintain. Therefore my question: is this something that could be supported or do you have any recommendations how I could handle this instead?

Thanks for any ideas and a big praise to the Phoenix team!

**Comment by chrismccord** [comment]
This is expected behavior. If you need to dynamically build up state after the LV mounts (such as something that toggles a nested form), you'll necessarily need to place that state somewhere, like the database. That said, it's likely you can always render the nested LV form but only toggle it's visibility, which would allow you to recover the state without throwing it in the DB.

**Comment by SteffenDE** [comment]
Hmm so I do always render the nested form. Maybe I misunderstood, but it reads like the following should work. I've attached an example elixir script that uses `Mix.install` to reproduce. Just kill the script and start it again to trigger a reconnect:

```elixir
Application.put_env(:phoenix, :json_library, Jason)

Application.put_env(:sample, SamplePhoenix.Endpoint,
  http: [ip: {127, 0, 0, 1}, port: 5001],
  server: true,
  live_view: [signing_salt: "aaaaaaaa"],
  secret_key_base: String.duplicate("a", 64)
)

Mix.install([
  {:plug_cowboy, "~> 2.5"},
  {:jason, "~> 1.0"},
  {:phoenix, "~> 1.6.15"},
  {:phoenix_live_view, "~> 0.18.3"},
  {:ecto, "~> 3.9"},
  {:phoenix_ecto, "~> 4.0"}
])

defmodule SamplePhoenix.ErrorView do
  use Phoenix.View, root: ""

  def render(_, _), do: "error"
end

defmodule SamplePhoenix.SampleLive do
  use Phoenix.LiveView, layout: {__MODULE__, "live.html"}

  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  def render("live.html", assigns) do
    ~H"""
    <script src="https://cdn.jsdelivr.net/npm/phoenix@1.6.15/priv/static/phoenix.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/phoenix_live_view@0.18.3/priv/static/phoenix_live_view.min.js"></script>
    <script>
      let liveSocket = new window.LiveView.LiveSocket("/live", window.Phoenix.Socket)
      liveSocket.connect()
    </script>
    <style>
      * { font-size: 1.1em; }
    </style>
    <%= @inner_content %>
    """
  end

  def render(assigns) do
    ~H"""
    <%= live_render(@socket, SamplePhoenix.SampleNestedLive, id: "nested", layout: nil) %>
    """
  end
end

defmodule SamplePhoenix.SampleNestedLive do
  use Phoenix.LiveView, layout: {SamplePhoenix.SampleLive, "live.html"}
  import Phoenix.HTML.Form
  import Ecto.Changeset
  use Phoenix.Component

  defp changeset(params \\ %{}) do
    data = %{}
    types = %{name: :string, email: :string}

    {data, types} 
    |> Ecto.Changeset.cast(params, Map.keys(types)) 
  end

  def mount(_params, _session, socket) do
    {:ok, assign(socket, :changeset, changeset())}
  end

  def render(assigns) do
    ~H"""
    <.form
      id="my-form"
      :let={f}
      as="my_data"
      for={@changeset}
      phx-change="validate"
    >
      <%= text_input f, :name %>
    </.form>
    """
  end

  def handle_event("validate", params, socket) do
    {:noreply, assign(socket, :changeset, changeset(params["my_data"]))}
  end
end

defmodule Router do
  use Phoenix.Router
  import Phoenix.LiveView.Router

  pipeline :browser do
    plug(:accepts, ["html"])
  end

  scope "/", SamplePhoenix do
    pipe_through(:browser)

    live("/", SampleLive, :index)
    live("/not-nested", SampleNestedLive, :index)
  end
end

defmodule SamplePhoenix.Endpoint do
  use Phoenix.Endpoint, otp_app: :sample
  socket("/live", Phoenix.LiveView.Socket)
  plug(Router)
end

{:ok, _} = Supervisor.start_link([SamplePhoenix.Endpoint], strategy: :one_for_one)
Process.sleep(:infinity)
```

http://localhost:5001/ renders a parent live view that unconditionally renders a child using `live_render`. The child then has the form which does not recover. Mounting the child LV directly at the router (the http://localhost:5001/not-nested) has working form recovery.

**Comment by SteffenDE** [comment]
> That said, it's likely you can always render the nested LV form but only toggle it's visibility, which would allow you to recover the state without throwing it in the DB.

Sorry to bother you @chrismccord, but I'm not sure if this really works as expected. Can you clarify if the example script I posted above should work? Thank you!

**Comment by chrismccord** [comment]
Nested live views won't recover on their own because the parent mounts first and then the nested children are joined from the client. There is no form data to send up after the parent first mounts, so you need to render the forms outside of the child and pass that data down to the children. Live components on the other hand would be able to recover.

**Comment by SteffenDE** [comment]
Alright, thank you. Would you be open for a PR that changes this behaviour? There are situations where separate child live view are much easier to handle (e.g. when each one has separate pubsub subscriptions) and the only downside I found is missing form recovery. Having to render the forms in the parent kind of defeats that separation.

I thought about somehow keeping the original DOM around until all children are connected again, but I don't know the downsides.

Otherwise: should I make a PR that mentions this limitation in the docs?
