### ISSUE TITLE
Nested LiveView doesn't work in table

### ISSUE THREAD

**Issue by ruudk** [phoenixframework/phoenix_live_view#229]
### Environment

* Elixir version (elixir -v): Elixir 1.8.2 (compiled with Erlang/OTP 21)
* Phoenix version (mix deps): Latest master #90d240f
* NodeJS version (node -v): v10.15.2
* NPM version (npm -v): 6.9.0
* Operating system: macOS

### Actual behavior

I render my liveview like this:
```eex
<table>
        <%= for item <- section.items do %>
            <%= live_render(@socket, AppWeb.Live.Checklist.TaskRow, container: {:tbody, []}, child_id: item.id, session: %{account: @account, user: @user, checklist: @checklist, item: item}) %>
        <% end %>
</table>
```

As you can see, I use the `container` property to prevent the creation of a `<div>` inside `<table>`. 

The problem is that `static_render`,`disconnected_nested_static_render` and `connected_nested_static_render` always create `<div class="phx-loader"></div>`.

The JS lib uses 
https://github.com/phoenixframework/phoenix_live_view/blob/93c561178688578ec788bdd7a8ebdf6653c90a64/assets/js/phoenix_live_view.js#L680
to find that loader and that doesn't work when it's a div (as it's invalid to have a div inside a table).

When I change the `<div>` in `static_render`,`disconnected_nested_static_render` and `connected_nested_static_render` to this:
```ex
<%= Phoenix.HTML.Tag.content_tag(tag, "", [class: "phx-loader"]) %>
```
it continues.

The HTML is valid, but now the first load from the Websocket removes the `<tr>` and produces invalid HTML again:
<img width="1101" alt="Screenshot 2019-05-25 at 14 03 56" src="https://user-images.githubusercontent.com/104180/58369093-ff7d4d80-7ef5-11e9-81a2-1f0d2a2d2d29.png">

There is no `<tr>` tag anymore:
<img width="657" alt="Screenshot 2019-05-25 at 14 05 19" src="https://user-images.githubusercontent.com/104180/58369107-305d8280-7ef6-11e9-9e17-a33df35073bc.png">

## Expected behavior

LiveView doesn't play nicely when the LV is a table row. I think it's a common usecase for LV's.

**Comment by chrismccord** [comment]
This will be fixed soon, when the pushstate stuff lands where I have updated the loader to use the existing container and css pseudo elements. Thanks!

**Comment by chrismccord** [comment]
Dup of #193
