### ISSUE TITLE
Cannot put LiveComponents inside a <%= link %> tag

### ISSUE THREAD

**Issue by desmondmonster** [phoenixframework/phoenix_live_view#2291]
### Environment

* Elixir version (elixir -v): 1.14.0-rc.0
* Phoenix version (mix deps): 1.6.14
* Phoenix LiveView version (mix deps):  0.18.2
* Operating system: OS X Big Sur 11.6
* Browsers you attempted to reproduce this bug on (the more the merrier):  Safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

I cannot mount a LiveComponent inside of a `link...do` tag like so:
```
<%= link, to: "#", phx_click: "have-fun" do %>
  <.live_component module={MyModule} id={@my_id} />
<% end %>
```

Doing so gives the following error:
```
** (ArgumentError) cannot convert component MyModule with id "50" to HTML.

A component must always be returned directly as part of a LiveView template.

For example, this is not allowed:

    <%= content_tag :div do %>
      <.live_component module={SomeComponent} id="myid" />
    <% end %>

That's because the component is inside `content_tag`. However, this works:

    <div>
      <.live_component module={SomeComponent} id="myid" />
    </div>

Components are also allowed inside Elixir's special forms, such as
`if`, `for`, `case`, and friends.

    <%= for item <- items do %>
      <.live_component module={SomeComponent} id={item} />
    <% end %>

However, using other module functions such as `Enum`, will not work:

    <%= Enum.map(items, fn item -> %>
      <.live_component module={SomeComponent} id={item} />
    <% end %>

    (phoenix_live_view 0.18.2) lib/phoenix_live_view/engine.ex:21: Phoenix.HTML.Safe.Phoenix.LiveView.Component.to_iodata/1
    (mrgr 0.1.0) lib/mrgr_web/components/live/pending_merge_item.html.heex:3: anonymous fn/2 in MrgrWeb.Components.Live.PendingMergeItem.render/1
    (phoenix_live_view 0.18.2) lib/phoenix_live_view/diff.ex:387: Phoenix.LiveView.Diff.traverse/7
    (phoenix_live_view 0.18.2) lib/phoenix_live_view/diff.ex:691: Phoenix.LiveView.Diff.render_component/9
    (phoenix_live_view 0.18.2) lib/phoenix_live_view/diff.ex:636: anonymous fn/5 in Phoenix.LiveView.Diff.render_pending_components/6
    (elixir 1.14.0-rc.0) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (stdlib 4.1.1) maps.erl:411: :maps.fold_1/3
    (phoenix_live_view 0.18.2) lib/phoenix_live_view/diff.ex:609: Phoenix.LiveView.Diff.render_pending_components/6
    (phoenix_live_view 0.18.2) lib/phoenix_live_view/diff.ex:145: Phoenix.LiveView.Diff.render/3
    (phoenix_live_view 0.18.2) lib/phoenix_live_view/channel.ex:810: Phoenix.LiveView.Channel.render_diff/3
    (phoenix_live_view 0.18.2) lib/phoenix_live_view/channel.ex:425: Phoenix.LiveView.Channel.maybe_call_mount_handle_params/4
    (phoenix_live_view 0.18.2) lib/phoenix_live_view/channel.ex:1010: Phoenix.LiveView.Channel.verified_mount/8
    (phoenix_live_view 0.18.2) lib/phoenix_live_view/channel.ex:59: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 4.1.1) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.1.1) gen_server.erl:1200: :gen_server.handle_msg/6
    (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3

```

However, I **can** put the component in an ordinary `<a>` tag:

```
<a href="#">
    <.live_component module={MyModule} id={@my_id} />
</a>
```

This is, shall we say, _a-ok_.  (sorry couldn't resist)

### Expected behavior

Couple thoughts:

1. I would expect the `link...do` semantics to work
1. I don't really care that they don't, ie, I am happy to use an ordinary `<a>` tag
1. The use case in the example above is dumb, ie, putting a single component inside of a link.  I could easily put the link inside the component itself.  **HOWEVER** the real-world use case was I had a large, clickable element of many nested `<div>`s which worked fine until I added my component in somewhere deep in the HTML, causing the whole thing to blow up with an obtuse error

Overall, I would be happy with a solution of "Add this as a gotcha to the docs and make sure to use an `<a>` tag" rather than one that addresses the technical issue of having a Live Component work inside the `link` function helper.

thanks ❤️

**Comment by chrismccord** [comment]
This is expected behavior. You can't render a LiveComponent in a do/end block construct, but you can use the `Phoenix.Component.link` function component from 0.18 and do `<.link ...><.live_component ... /></.link>`. Thanks!
