### ISSUE TITLE
Warning when passing valid non-global attribute down to component

### ISSUE THREAD

**Issue by Gladear** [phoenixframework/phoenix_live_view#2292]
### Environment

* Elixir version (elixir -v): Elixir 1.14.1 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): N/A
* Phoenix LiveView version (mix deps): 1.18.1
* Operating system: Ubuntu 20.04.5 LTS on WSL2
* Browsers you attempted to reproduce this bug on (the more the merrier): N/A
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: N/A

### Actual behavior

When passing an attribute that isn't listed in globals (?) to `attr :rest, :global`, but still a valid attribute for the component it will be passed down to, Heex emits a warning `warning: undefined attribute`.

**attr_undefined.exs**
```ex
Application.put_env(:phoenix, :json_library, Jason)

Mix.install([
  phoenix_live_view: "0.18.2",
  jason: "~> 1.0"
])

defmodule Components do
  use Phoenix.Component

  attr :rest, :global

  def my_link(assigns) do
    ~H"""
    <.link class="a-link" {@rest}>
      Content
    </.link>
    """
  end

  def using_my_link(assigns) do
    ~H"""
    <.my_link id="my_id" navigate="/" />
    """
  end
end

Components.using_my_link(%{})
|> Phoenix.LiveViewTest.rendered_to_string()
|> IO.inspect()
```

**run elixir**
```sh
$ elixir live_view_bug.exs
"<a href=\"/\" data-phx-link=\"redirect\" data-phx-link-state=\"push\" class=\"a-link\" id=\"my_id\">\n  Content\n</a>"
warning: undefined attribute "navigate" for component Components.my_link/1
  live_view_bug.exs:25: (file)
```

Note that the attribute is correctly passed down to the component.

### Expected behavior

I think no warning should be emitted in this case.

**Comment by josevalim** [comment]
Global attributes only include the HTML attributes that are shared across all HTML elements. “navigate” is not one of them, so the warning is correct. :)

**Comment by pehbehbeh** [comment]
What about "global" Attributes from Alpine.js? We get warnings like these...

```
      warning: undefined attribute "x-show" for component Heroicons.chevron_right/1
  lib/my_app/components/sidebar.ex:48: (file)

warning: undefined attribute "x-show" for component Heroicons.chevron_down/1
  lib/my_app/components/sidebar.ex:49: (file)
```

I think the either Heroicons nor LiveView should care about 3rd party custom attributes.

Would be great, if one could add known global attributes (or prefixes like `x-`) on a per project basis.

**Comment by josevalim** [comment]
Yes, you can do so on your `use Phoenix.Component`, IIRC.

**Comment by pehbehbeh** [comment]
Great! Thank you. You can find the documentation [here](https://hexdocs.pm/phoenix_live_view/Phoenix.Component.html#module-custom-global-attribute-prefixes), in case anyone else stumbles across it.

**Comment by Gladear** [comment]
Thanks for the clarification and sorry for the noise, I didn't understand it that way 🙂
For people like me who'd like to add some attributes, you can use the [`:include`](https://hexdocs.pm/phoenix_live_view/Phoenix.Component.html#module-global-attributes) option of `attr/3`.

**Comment by arcanemachine** [comment]
Here's a summary for anyone who runs into this problem (I have added comments to all lines that were changed from the defaults generated when the project was created):

- Prevent compiler warnings in your dead views:

`lib/your_app_web.ex`
```elixir
  def html do
    quote do
      # use Phoenix.Component  # <-- old line 
      use Phoenix.Component, global_prefixes: ~w(x-)  # <-- new line

      # Import convenience functions from controllers
      import Phoenix.Controller,
        only: [get_csrf_token: 0, view_module: 1, view_template: 1]

      # Include general helpers for rendering HTML
      unquote(html_helpers())
    end
  end
```

- Prevent compiler warnings in your live views:

`lib/your_app_web.ex`
```elixir
  def live_view do
    quote do
      use Phoenix.LiveView,
        layout: {AttributeProblemWeb.Layouts, :app}, # <-- added a comma to the end of this line
        global_prefixes: ~w(x-)  # <-- added this line

      unquote(html_helpers())
    end
  end
```

- Prevent compiler warnings in your component modules (e.g. `YourAppWeb.CoreComponents`):

`lib/your_app_web/components/core_components.ex`
```elixir
defmodule AttributeProblemWeb.CoreComponents do
  # use Phoenix.Component  # <-- old line
  use Phoenix.Component, global_prefixes: ~w(x-)  # <-- new line

  # example component should not generate any warnings
  def your_component(assigns) do
    ~H"""
    <.button x-data x-on:click="alert('hello')">
      Hello
    </.button>
    """
  end
end
```

**Comment by eKIK** [comment]
Maybe a bit of a silly question - is there a way to add certain global attributes, like "x-" for components that I haven't created or are in control of?

Example case:
```
<Heroicons.chevron_down class="w-md" x-show="visible" />
```

Since [Heroicons](https://hex.pm/packages/heroicons) is an Elixir library that isn't authored by me I can't simply add `global_prefixes` to it. I could of course fork it, do a pull request etc, but I'm just checking if there's some other way?

Right now I've worked around it by wrapping the `<Heroicons...` in a `<span>` since it's only affecting me in a single case, like this:

```
<span x-show="visible">
    <Heroicons.chevron_down class="w-md" />
</span>
```
