### ISSUE TITLE
formatting impacts whitespace

### ISSUE THREAD

**Issue by tcoopman** [phoenixframework/phoenix_live_view#2298]
related to https://elixirforum.com/t/live-view-mix-format/51290 and #2121 

preformatting:
```elixir
(<.link 
  navigate={...} 
  class={["class"]} 
  other-attr="value" 
  {@rest}
>Show</.link>)
```

doesn't output the same html (whitespaces, newlines) as post formatting:

```elixir
(<.link 
  navigate={...} 
  class={["class"]} 
  other-attr="value" 
  {@rest}
>
  Show
</.link>)
```

As some people noted, html rules suck regarding this, but maybe the formatter could try harder to keep whitespace.
I've had a look at what prettier does and they have configuration for it: [htmlWhitespaceSensitivity](https://prettier.io/blog/2018/11/07/1.15.0.html#htmlvueangular)

**Comment by rktjmp** [comment]
Adding `phx-no-format` fixes this behaviour for me, whether or not the formatter should be "smarter", that might at least help you?

```elixir
(<.link 
  navigate={...} 
  class={["class"]} 
  other-attr="value" 
  {@rest}
  phx-no-format
>Show</.link>)
```

**Comment by luka-TU** [comment]
should we add `.link` into the list of inline components (or some other list of custom components, if that sounds better)?

**Comment by feliperenan** [comment]
yeah, `phx-no-format` is the way to go here. We do handle cases when the tag is an inline element, but the Formatter doesn't handle it for components since it could be either a block or an inline element.

**Comment by kreba** [comment]
## Notes for posterity:

### `phx-no-format` requires a parent element

This magic attribute cannot be applied e.g. when only looping, without a wrapping element.

```
    ~H"""
    <%= for name <- @names do %><.fruit name={name} /><% end %>
    """
```

Will get formatted to

```
    ~H"""
    <%= for name <- @names do %>
      <.fruit name={name} />
    <% end %>
    """
```

### No point in using a single-line string

```
    ~H'<%= for name <- @names do %><.fruit name={name} /><% end %>'
```

Will get formatted in an odd way that the Elixir parser doesn't... parse.

```
    ~H'<%= for part <- @parts do %>
  <.date_part part={part} phx-no-format />
<% end %>'
```

### Use a workaround

As other people have suggested, use `display: inline-block`.
Or add a wrapper using `phx-no-format`, even though you really didn't want one.
Or use Flexbox, possibly in a parent component.

**Comment by feliperenan** [comment]
@kreba I think you could use `:for` attribute instead of `for` macro:

```elixir
<ul>
  <li :for={item <- @items}><%= item.name %></li>
</ul>
```

https://github.com/phoenixframework/phoenix/blob/main/guides/components.md#html-extensions
