### ISSUE TITLE
heex templates and support for <?xml> declarations

### ISSUE THREAD

**Issue by thdaraujo** [phoenixframework/phoenix_live_view#2300]
(I'm not sure if this is the right place to report this or if it's even supported, so I apologize in advance!)

### Environment

* Elixir version (elixir -v): Elixir 1.13.4 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): 1.6.14
* Phoenix LiveView version (mix deps): 0.17.12
* Operating system: fedora linux 36

### Actual behavior

I'm able to render xml templates (more specifically, a `sitemap.xml` file) with leex and heex templates.

But if the template includes a [xml prolog declaration](https://developer.mozilla.org/en-US/docs/Web/XML/XML_introduction#xml_declaration), the `leex` template still works fine, but the `heex` template raises an error. See example below.

This works fine (leex):
```
  def render_xml(assigns) do
    ~L"""
    <?xml version="1.0" encoding="utf-8" standalone="yes"?>
    <url>
      <loc><%= @loc %></loc>
    </url>
    """
  end
```

This doesn't work (heex):
```
  def render_xml(assigns) do
    ~H"""
    <?xml version="1.0" encoding="utf-8" standalone="yes"?>
    <url>
      <loc><%= @loc %></loc>
    </url>
    """
  end
```

Error:
```
== Compilation error in file (...) ==
** (Phoenix.LiveView.HTMLTokenizer.ParseError): end of template reached without closing tag for <?xml>
    (phoenix_live_view 0.17.12) lib/phoenix_live_view/html_engine.ex:79: Phoenix.LiveView.HTMLEngine.validate_unclosed_tags!/2
    (phoenix_live_view 0.17.12) lib/phoenix_live_view/html_engine.ex:54: Phoenix.LiveView.HTMLEngine.handle_body/1
    (phoenix_live_view 0.17.12) expanding macro: Phoenix.LiveView.Helpers.sigil_H/2
   (...)
```

Removing the prolog fixes the problem:
```
  def render_xml(assigns) do
    ~H"""
    <url>
      <loc><%= @loc %></loc>
    </url>
    """
  end
```

### Expected behavior

I would expect `heex` to render the xml with the declaration, just like it would work with `<!DOCTYPE html>` declarations. But I'm not sure xml is currently supported.

**Comment by josevalim** [comment]
HEEx stands for HTML + EEx and I don't think we should commit to rendering valid XML because HTML is not valid XML. For example, some tags in HTML, such as `<br>`, do not need to be closed, and if we ever render them as such, it may break XML.

**Comment by thdaraujo** [comment]
that makes sense, thank you!
