### ISSUE TITLE
LiveView doesn't wait for long running process to complete and reloads a page 

### ISSUE THREAD

**Issue by lessless** [phoenixframework/phoenix_live_view#2305]
### Environment

* Elixir version (elixir -v): 1.14.1
* Phoenix version (mix deps): current (`"6e23d1a1120a241e3bf3e41343a43e2df8a831f2"`)
* Phoenix LiveView version (mix deps): current ("52f2cabce618acd5da620f8e744bb20e64e1cb65")`
* Operating system:  macOS
* Browsers you attempted to reproduce this bug on (the more the merrier):  Safari and Chrome

### Actual behavior

A page reloads before the response came through. 

The sequence: 

I am submitting a request to generate a report:

```
iex(12)> [debug] HANDLE EVENT
  Component: CoinsentryWeb.XPubImportLive.StatementReportFormComponent
  View: CoinsentryWeb.XPubImportLive.Index
  Event: "save"
  Parameters: %{"x_pub" => %{"address" => "[FILTERED]"}}
generating report
```

Then the response comes in: 

```
[debug] Replied in 37332ms
```

and then the page just reloads

```
[info] GET /
[debug] Processing with CoinsentryWeb.XPubImportLive.Index.index/2
  Parameters: %{}
  Pipelines: [:browser]
[info] Sent 200 in 4ms
[info] CONNECTED TO Phoenix.LiveView.Socket in 32µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Parameters: %{"_csrf_token" => "KGcCPyNhSQYYXBpVByI-HiUkHwMNFRQVAVvnWVyQZ0x-uSjSvFwjyQMm", "_live_referer" => "undefined", "_mounts" => "0", "_track_static" => %{"0" => "http://localhost:4000/assets/app.css", "1" => "http://localhost:4000/assets/app.js"}, "vsn" => "2.0.0"}
```

For a moment, I can see a `"We can't find Internet. Attempting to reconnect"` message.
And after page reloads, I can see the report is printed to the console 

UPDT: After pocking around for a while I figured out that code ends up here https://github.com/phoenixframework/phoenix_live_view/blob/master/assets/js/phoenix_live_view/live_socket.js#L287

And I wonder if `PHX_TIMEOUT` is configurable.  Obviously, keeping users waiting for more than the 30s doesn't make a lot of sense, but it's fine for the prototype. 

### Expected behavior

LiveView waits for the operation to complete

**Comment by josevalim** [comment]
We recommend moving the processing to be async. Yes, the timeout could be increased for prototypes, but we are also not sure adding a flag that could be misused to the point of making the app unusable is worth only for prototyping reasons. See #2092 with a similar discussion. :)

**Comment by lessless** [comment]
> We recommend moving the processing to be async. Yes, the timeout could be increased for prototypes, but we are also not sure adding a flag that could be misused to the point of making the app unusable is worth only for prototyping reasons. See #2092 with a similar discussion. :)

Makes sense. Would you please look at the https://elixirforum.com/t/is-it-possible-to-control-liveview-from-load-state/51425/3 in regard to this? 

(I somewhat anticipated that async processing might be the only option :)
