### ISSUE TITLE
Element remains on page after live_patch with `raw` HTML

### ISSUE THREAD

**Issue by mbuhot** [phoenixframework/phoenix_live_view#2306]
### Environment

* Elixir version (elixir -v): Elixir 1.14.0 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): phoenix 1.7.0-dev (https://github.com/phoenixframework/phoenix.git) (mix) (reproduced with older version also)
* Phoenix LiveView version (mix deps): 0.18.3 (Hex package) (mix) (Reproduced with older version also)
* Operating system: MacOS 12.6
* Browsers you attempted to reproduce this bug on (the more the merrier): MacOS Safari 16.0 (17614.1.25.9.10, 17614), Chrome Version 106.0.5249.119
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes (assets/node_modules does not exist)

### Actual behavior

Below is a minimal reproduction of https://github.com/ash-project/ash_hq/issues/38

A `live_patch` is used to replace a section of a page which is populated with pre-rendered HTML.
After the live_patch, a DOM element from the previous content remains on the page, when it should have been removed.

To reproduce with the script below:

1. Run `elixir repro.exs`
2. Visit http://localhost:5001/repro/1
3. Click the "Page 2" link to live_patch to http://localhost:5001/repro/2
4. See that there is a 'duplicate DOM id' warning in the browser console for id="details".
5. See that "Page1 h2" remains on the page.
6. Refresh the browser window
7. See that "Page1 h2" is not longer on the page, and there are no duplicate DOM ID warnings in the console.

```html
<div class="mb-4">
  <a data-phx-link="patch" data-phx-link-state="push" href="/repro/1">Page 1</a>
  <a data-phx-link="patch" data-phx-link-state="push" href="/repro/2">Page 2</a>
</div>
<h2 id="details">Page1 h2</h2>
<h1 id="details">Page2 h1</h1>
```

### Expected behavior

When live_patch from `/repro/1` to `/repro/2`, the content of the page should be:

```html
<div class="mb-4">
  <a data-phx-link="patch" data-phx-link-state="push" href="/repro/1">Page 1</a>
  <a data-phx-link="patch" data-phx-link-state="push" href="/repro/2">Page 2</a>
</div>
<h1 id="details">Page2 h1</h1>
```

#### Reproduction Script:

```elixir
#repro.exs
Application.put_env(:phoenix, :json_library, Jason)

Application.put_env(:sample, SamplePhoenix.Endpoint,
  http: [ip: {127, 0, 0, 1}, port: 5001],
  server: true,
  live_view: [signing_salt: "aaaaaaaa"],
  secret_key_base: String.duplicate("a", 64)
)

Mix.install([
  {:plug_cowboy, "~> 2.5"},
  {:jason, "~> 1.0"},
  {:phoenix, "~> 1.6.10"},
  {:phoenix_live_view, "~> 0.17.10"}
])

defmodule SamplePhoenix.ErrorView do
  use Phoenix.View, root: ""

  def render(_, _), do: "error"
end

defmodule SamplePhoenix.ReproLive do
  use Phoenix.LiveView, layout: {__MODULE__, "live.html"}
  import Phoenix.HTML

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    {:noreply, socket |> assign(:content, content(id))}
  end

  def render("live.html", assigns) do
    ~H"""
    <script src="https://cdn.jsdelivr.net/npm/phoenix@1.6.10/priv/static/phoenix.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/phoenix_live_view@0.17.10/priv/static/phoenix_live_view.min.js"></script>
    <script>
      let liveSocket = new window.LiveView.LiveSocket("/live", window.Phoenix.Socket)
      liveSocket.connect()
    </script>
    <style>
      * { font-size: 1.1em; }
    </style>
    <%= @inner_content %>
    """
  end

  @impl true
  def render(assigns) do
    ~H"""
    <div class="mb-4">
      <%= live_patch("Page 1", to: "/repro/1") %>
      <%= live_patch("Page 2", to: "/repro/2") %>
    </div>
    <%= raw(@content) %>
    """
  end

  # This is a contrived example for reproduction purposes
  # The real use case is to load pre-rendered HTML from a database
  defp content("1") do
    """
    <h1 id="heading1">Page1 h1</h1>
    <h2 id="details">Page1 h2</h2>
    """
  end

  defp content("2") do
    """
    <h1 id="details">Page2 h1</h1>
    """
  end
end

defmodule Router do
  use Phoenix.Router
  import Phoenix.LiveView.Router

  pipeline :browser do
    plug(:accepts, ["html"])
  end

  scope "/", SamplePhoenix do
    pipe_through(:browser)

    live("/repro/:id", ReproLive)
  end
end

defmodule SamplePhoenix.Endpoint do
  use Phoenix.Endpoint, otp_app: :sample
  socket("/live", Phoenix.LiveView.Socket)
  plug(Router)
end

{:ok, _} = Supervisor.start_link([SamplePhoenix.Endpoint], strategy: :one_for_one)
Process.sleep(:infinity)
```

**Comment by josevalim** [comment]
LiveView thinks there are duplicate IDs, and that's part of the reason, but as far as I know the duplicate IDs are from different renders, so that should not be a problem.

**Comment by mbuhot** [comment]
The LiveView debug output:

Initial mount on `/repro/1`

```
{
  "0": {
    "0": "<a data-phx-link=\"patch\" data-phx-link-state=\"push\" href=\"/repro/1\">Page 1</a>",
    "1": "<a data-phx-link=\"patch\" data-phx-link-state=\"push\" href=\"/repro/2\">Page 2</a>",
    "2": "<h1 id=\"heading1\">Page1 h1</h1>\n<h2 id=\"details\">Page1 h2</h2>\n",
    "s": ["<div class=\"mb-4\">\n  ", "\n  ", "\n</div>\n", ""]
  },
  "s": [
    "<script src=\"https://cdn.jsdelivr.net/npm/phoenix@1.6.10/priv/static/phoenix.min.js\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/phoenix_live_view@0.17.10/priv/static/phoenix_live_view.min.js\"></script>\n<script>\n  let liveSocket = new window.LiveView.LiveSocket(\"/live\", window.Phoenix.Socket)\n  liveSocket.connect()\n</script>\n<style>\n  * { font-size: 1.1em; }\n</style>\n",
    ""
  ]
}
```

Diff from live_patch:

```json
{"0":{"2":"<h1 id=\"details\">Page2 h1</h1>\n"}}
```

So it appears to be a problem applying the patch client side.

**Comment by mbuhot** [comment]
I believe this is actually a bug in morphdom: https://github.com/patrick-steele-idem/morphdom/pull/231

**Comment by mbuhot** [comment]
@josevalim I think this issue can be worked around in LiveView by including the `tagName` in the key used by morphdom.
 
The [getNodeKey](https://github.com/phoenixframework/phoenix_live_view/blob/master/assets/js/phoenix_live_view/dom_patch.js#L97-L99) function could be changed to something like:


```javascript
        getNodeKey: (node) => {
          if(DOM.isPhxDestroyed(node)) { return null; }
          // workaround for https://github.com/patrick-steele-idem/morphdom/pull/231
          if(node.id && node.tagName) { return `${node.id}-${node.tagName}`; }
          return node.id;
        },
```

Would something like that be acceptable for LiveView?
