### ISSUE TITLE
LiveView calls mount/2 three times if a call to Plug.Crypto.KeyGenerator.generate/3 is looped in a .leex template

### ISSUE THREAD

**Issue by guidotripaldi** [phoenixframework/phoenix_live_view#231]
### Environment

* Elixir. 1.8.1 (compiled with Erlang/OTP 21)
* Phoenix. 1.4.2 (https://github.com/phoenixframework/phoenix.git)
* NodeJS: v11.12.0
* NPM: 6.7.0
* Operating system: macOS 10.14.5

### Actual behavior

After encoding the `phx-value` for a list of controls (to avoid to transmit clear data, and to be able to pass maps to the LV handler), I noticed that if the number of controls to render (and therefore the calls to `Plug.Crypto.KeyGenerator.generate/3`) are  >= 30, `mount/2` is called three times.

This toy code reproduce the problem (try to change the number of comprehension iterations (<30 or >30 on my machine) to see how many times `mount/2` is called):

```elixir
defmodule DemoWeb.TestCryptoLive do
  use Phoenix.LiveView

  def render(assigns) do
    ~L"""    
      <h4><%= @message %></h4>
      <%= for n <- 1..50 do %>
        <%= Phoenix.HTML.Link.button("Button #{n}", to: "#", method: :get, phx_click: "button-clicked", phx_value: "#{encode(%{value: n})}") %>
      <% end %>
    """
  end

  def mount(_session, socket) do
    IO.puts("\n---> mount\n")
    {:ok, assign(socket, :message, "")}
  end

  def handle_event("button-clicked", encoded_params, socket) do
    params = decode(encoded_params)

    message = "Button #{params.value} clicked."
    {:noreply, assign(socket, :message, message)}
  end

  def encode(message) do
    {secret, sign_secret} = keys()
    message
    |> :erlang.term_to_binary()
    |> Plug.Crypto.MessageEncryptor.encrypt(secret, sign_secret)
    |> Base.encode64()
  end

  def decode(message) do
    {secret, sign_secret} = keys()
    message
    |> Base.decode64!()
    |> Plug.Crypto.MessageEncryptor.decrypt(secret, sign_secret)
    |> case do
         {:ok, decrypted} -> :erlang.binary_to_term(decrypted)
         :error -> :error
       end
  end

  defp keys() do
    secret_key_base = "abcd1234"
    secret =      Plug.Crypto.KeyGenerator.generate(secret_key_base, "test salt")
    sign_secret = Plug.Crypto.KeyGenerator.generate(secret_key_base, "test sign salt")
    {secret, sign_secret}
  end

end
```

After refreshing the browser, with n < 30, on the console:
```
[info] GET /testcrypto

---> mount

[info] Sent 200 in 41ms
[info] CONNECT Phoenix.LiveView.Socket
  Transport: :websocket
  Connect Info: %{}
  Parameters: %{"vsn" => "2.0.0"}
[info] Replied Phoenix.LiveView.Socket :ok

---> mount

[info] Replied phoenix:live_reload :ok
```
with n > 30 :
```
[info] GET /testcrypto

---> mount

[info] CONNECT Phoenix.LiveView.Socket
  Transport: :websocket
  Connect Info: %{}
  Parameters: %{"vsn" => "2.0.0"}
[info] Replied Phoenix.LiveView.Socket :ok
[info] Replied phoenix:live_reload :ok

---> mount

[info] Sent 200 in 135ms
[info] CONNECT Phoenix.LiveView.Socket
  Transport: :websocket
  Connect Info: %{}
  Parameters: %{"vsn" => "2.0.0"}
[info] Replied Phoenix.LiveView.Socket :ok

---> mount

[info] Replied phoenix:live_reload :ok
```

### Expected behavior

The number of times `Plug.Crypto.KeyGenerator.generate/3` is called inside a view should not influences the re-render of the view.

**Comment by petermm** [comment]
can replicate.. though it doesn't seem related to "n" being above or under 30..

in my test it's related to reloading the browser (3 mounts most of the time) vs new page load(new window) in the browser (always 2 mounts)

so something is up with how the browser reloads and phoenix liveview acts under a reload..

tested in chrome and safari - same behaviour
tested in dev and prod - same behaviour

**Comment by guidotripaldi** [comment]
Yes, sorry, I missed to highlight well these aspects in the description: the bug shows up only when some Crypto calls are involved in a loop AND `n` is big AND the live page is reloaded.
Instead, it not shows up if `n` is changed updating an assignment.

In brief, on my configuration:
- if `Crypto` is called n times AND n < 30 AND the page is loaded/reloaded -> 
     `mount/2` is called **2** times
-  if `Crypto` is called n times AND n > 30 AND the page is loaded/reloaded ->
    `mount/2` is called **3** times
-  if `Crypto` is called n times AND n is changed updating an assignment, regardless n size ->
    the page is refreshed regularly (without any supplemental call to `mount/2`)

**Comment by josevalim** [comment]
How long does is it take to encode 30? Is it more than 5 seconds?  Perhaps we are timing out in the front end and that is reloading the page?

**Comment by guidotripaldi** [comment]
yes, I've check it out better, it is a timeout problem, I've changed my test calling a generic delay function instead to call Crypto: if the .leex compilation takes more than (about) 150/200ms, `mount/2` is called again.

(so maybe I should change the issue title to something like "LiveView calls mount/2 three times if .leex takes more than 150ms to compile."

My simple test:

```
  def render(assigns) do
    ~L"""
      <h4>LV timeout test</h4>
      <p> Elapsed: 
        <%=
          milliseconds = 120
          timing(&delay/1, milliseconds) 
        %>
        ms.
      </p>

    """
  end

  def mount(_session, socket) do
    IO.puts("\n---> mount\n")
    {:ok, socket}
  end

## Helpers

  def delay(msec) do
    Stream.timer(msec) |> Enum.to_list()
  end

  def timing(function, arguments) do
    {t, r} = :timer.tc(fn -> function.(arguments) end)
    t / 1000
  end
```

**Comment by chrismccord** [comment]
This is expected behavior because we abandon the join after the timeout and retry. You can either defer your slow work by using `send(self(), :after_mount)`, or you can configure a higher timeout on the LiveSocket constructive, ie `new Socket("/live", {timeout: 15000})`. You may also consider starting an async task on the LV and reporting the results to it if you really are blocking the LV for this long. Hope that helps, but not an issue for us to address in this case. Thanks!

**Comment by iwarshak** [comment]
@chrismccord This is the second time google has directed me here for this same issue. Perhaps it would be good to log something to the browser console if the LV has to be remounted due to this timeout?

**Comment by chrismccord** [comment]
The timeout is on the client side, and we do log the timeout if you are doing `liveSocket.enableDebug()`. If the app is blocking the LV for >30s, there's a definition issue on the user implementation side so I don't think there's much for us to be able to handle log wise on the server.
