### ISSUE TITLE
"Attempting to reconnect" Error flashes on log out

### ISSUE THREAD

**Issue by mgwidmann** [phoenixframework/phoenix_live_view#2311]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 25 [erts-13.1.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit] [dtrace]

Elixir 1.14.1 (compiled with Erlang/OTP 24)
```
* Phoenix version (mix deps): 
```
* phoenix 1.7.0-dev (https://github.com/phoenixframework/phoenix.git) (mix)
  locked at d488e2b
```
* Phoenix LiveView version (mix deps):
```
* phoenix_live_view 0.18.3 (https://github.com/mgwidmann/phoenix_live_view.git - origin/fix-redirect) (mix)
  locked at 74b6ef3 (branch: fix-redirect)
```
* Operating system: Mac OSX Monterey 12.6
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome only happens on log out, Firefox happens on both clicking log in and log out, Safari does not happen at all
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: N/A (project does not have `assets/node_modules` folder)

Project source code at commit where issue is reproducible:
https://github.com/mgwidmann/kart_vids/tree/e6b0ef7c2df713658ab4c3684c48902d0cba9d4e

### Actual behavior

An error message pops up for a split second on some browsers during certain actions. Its very hard to catch as the page changes very quickly, but I managed to catch it on a screenshot so I could read it.

![screenshot](https://user-images.githubusercontent.com/5035724/199392824-51fbf4ee-c81b-4a61-8880-53e12be6778b.png)

It appears that the intentional disconnect from the web socket is being interpreted as an unintentional disconnect (where internet connection is assumed lost). Safari performs the best and there is no error message. Chrome only on log out, and Firefox seems to do it on just about all links.

No errors are logged on the Elixir side nor are there any console messages in the browser's developer tools.

### Expected behavior

No red error messages pop up.

**Comment by josevalim** [comment]
Potentially related to #2276.
