### ISSUE TITLE
assign_new does not pick current_user from conn

### ISSUE THREAD

**Issue by blset** [phoenixframework/phoenix_live_view#2312]
### Environment

* Elixir version (elixir -v): 1.14
* Phoenix version (mix deps): 1.6.15
* Phoenix LiveView version (mix deps): 0.18.3
* Operating system: ubuntu 20.04
* Browsers you attempted to reproduce this bug on (the more the merrier): firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

in a liveview assign_new is triggered even though :current_user already exists in conn

on first render one sees current_user from conn as expected,
 on second render in connected state, current_user originates from assign_new which does not reuse already existing :current_user

test app https://github.com/blset/bg1
mix ecto.reset
login as bg1@bg1.com 
password bg1
click rows, and use the links

### Expected behavior

from the docs https://hexdocs.pm/phoenix_live_view/Phoenix.Component.html#assign_new/3-referencing-parent-assigns

> Referencing parent assigns
> 
> When a user first accesses an application using LiveView, the LiveView is first rendered in its disconnected state, as part of a regular HTML response. In some cases, there may be data that is shared by your Plug pipelines and your LiveView, such as the :current_user assign.
> 
> By using assign_new in the mount callback of your LiveView, you can instruct LiveView to re-use any assigns set in your Plug pipelines as part of [Plug.Conn](https://hexdocs.pm/plug/1.13.6/Plug.Conn.html), avoiding sending additional queries to the database. Imagine you have a Plug that does

:

**Comment by josevalim** [comment]
Yes, it helps on the disconnected render. The connected render still has to query it.

**Comment by blset** [comment]
maybe some clarification is needed in the documentation then ?

assign_new re-uses conn in disconnected state but not in connected state 

so there is no porosity from conn to socket at all

**Comment by josevalim** [comment]
Good call. Can you please send a PR?
