### ISSUE TITLE
`LiveView.JS` commands in static views have no effect when sharing page with `live_render`

### ISSUE THREAD

**Issue by mxgrn** [phoenixframework/phoenix_live_view#2314]
### ;tldr

JS commands on static ("dead") views have no effect when `live_render` is used in in the same .heex template.

A very bare Phoenix project isolating this issue can be found [here](https://github.com/mxgrn/js_issue).

### Environment

* Elixir version (elixir -v): Elixir 1.14.0 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): 1.6.15
* Phoenix LiveView version (mix deps): 0.18.3
* Operating system: macOS Monterey
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome Version 107.0.5304.87 (Official Build) (arm64)
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: N/A (no node_modules)

### Isolating the issue

I generated a vanilla Phoenix project, and here's the exact content of my [page/index.html.heex](https://github.com/mxgrn/js_issue/blob/master/lib/js_issue_web/templates/page/index.html.heex):

```heex
<%= Phoenix.Component.live_render @conn, FooLive %>

<button phx-click={Phoenix.LiveView.JS.hide()}>I must hide on click</button>
```

My [FooLive](https://github.com/mxgrn/js_issue/blob/master/lib/js_issue_web/live/foo_live.ex):

```elixir
defmodule FooLive do
  use Phoenix.LiveView

  def render(assigns) do
    ~H"""
    I'm a LiveView. If you don't render me in page/index.html.heex, the button below will work as intended.
    """
  end
end
```

Screenshot from the running app:

<img width="791" alt="image" src="https://user-images.githubusercontent.com/33935/199660846-7c760543-2369-4390-94c3-8fb29862f2eb.png">

### Actual behavior

When I click the button, it does not hide itself as it should. No JS errors are to be seen in the Chrome dev tools.

As soon as I remove the `live_render` call from the page, everything starts working as expected.

Full phx app that reproduced this issue can be found [here](https://github.com/mxgrn/js_issue).

### Expected behavior

The button should hide itself on a click.

---

UPD: also reproducible with Phoenix 1.7.0-dev.

**Comment by mxgrn** [comment]
@maxmarcon 

> LiveView 0.18 now includes support for JS commands and hooks inside content rendered outside of LiveView. This allows many of your core UI function components to be used across LiveViews or regular views, such as modals, flash messages, and dropdowns.

[source](https://www.phoenixframework.org/blog/phoenix-liveview-0.18-released)

**Comment by maxmarcon** [comment]
Oh I didn't know. That's interesting. I should really start reading the blog posts :) the docs  for JS commands don't mention this.

They claim hooks should also work, but I just tried and they're also ignored.

**Comment by maxmarcon** [comment]
@mxgrn Ok I debugged my way through the JS calls, and this is where it gives up:

https://github.com/phoenixframework/phoenix_live_view/blob/8fb58099bf627d00f9ee405c565ccfb85af5c63e/assets/js/phoenix_live_view/live_socket.js#L417

Before continuing the handling of the click event, it tries to find a live view that _contains_ your element (that's what `closest()` does). If it can't find any, it stops. So the handling of the event can only work if your content is rendered inside a LV.

I think we're misunderstanding the sentence in the blog post. I think what is meant is that you can render elements with JS commands and hooks in "dead" components and use them within your LV. Or, you can use them outside of a LV but the bindings are not gonna work (they require a LV to operate).

**Comment by ChristianAlexander** [comment]
+1, I'm also seeing this issue with hooks.

Here's a repo that demonstrates the issue with hooks: https://github.com/ChristianAlexander/deadview_live_render_hooks
