### ISSUE TITLE
Duplicate items in for loop with form

### ISSUE THREAD

**Issue by tqwewe** [phoenixframework/phoenix_live_view#2315]
### Environment

* Elixir version (elixir -v):
   - Erlang/OTP 25 [erts-13.1.1] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns] [dtrace]
   - Elixir 1.14.1 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): phoenix 1.6.13
* Phoenix LiveView version (mix deps): phoenix_live_view 0.17.12
* Operating system: MacOS
* Browsers you attempted to reproduce this bug on (the more the merrier): Google Chrome, Safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: no

### Actual behavior

Given the following html:

```html
~H"""
<div>
  <%= for todo <- @todos do %>
    <li>
      <form>
        <span><%= todo["title"] %></span>
        <input name="id" />
      </form>
    </li>
  <% end %>
</div>
"""
```

And assigns:

```elixir
def mount(_params, assigns, socket) do
  socket =
    assign(socket, :todos, [
      %{
        "title" => "Hello"
      },
      %{
        "title" => "World"
      }
    ])

  {:ok, socket}
end
```

There are 3 elements rendered on initial load:
1. "Hello"
2. "Hello"
3. "World"

With `Hello` form being rendered twice.

Inspecting the page source (without the websocket connection), I can see that there's only the 2 items rendered as expected.

### Expected behavior

The form should render only the 2 items "Hello", "World", instead of "Hello" being rendered twice.

**Comment by josevalim** [comment]
Can you please replace the `div` by `ui`? A `li` is only allowed inside `ul` or `ol`, so I believe the browser is moving the `li` outside, which makes the patching code misbehave.

This is one of the validations we could add as part of #2015.

**Comment by tqwewe** [comment]
Replacing the div with `ul` still shows the issue.
```html
~H"""
<ul>
  <%= for todo <- @todos do %>
    <li id={todo["title"]}>
      <form>
        <span><%= todo["title"] %></span>
        <input name="id" />
      </form>
    </li>
  <% end %>
</ul>
"""
```

**Comment by tqwewe** [comment]
The weird thing about this issue, is that this is about the smallest example I could make.
If I:
- change the `form` element to a `div`
- remove the `name` attribute from the `input`
- remove the `input` element

The issue no longer occurs for any of these changes.

**Comment by josevalim** [comment]
Yeah, in that case it is definitely something weird going on in the HTML bits. Try opening the browser console and running `liveSocket.enableDebug()`, then reload the page. Is anything logged about duplicate IDs or similar?

**Comment by tqwewe** [comment]
I enabled the debug, and nothing new is shown in the console. No warnings or anything.

Here's the repo:
https://github.com/tqwewe/phoenix_live_view_bug

The file I'm working on:
https://github.com/tqwewe/phoenix_live_view_bug/blob/main/lib/app_web/router.ex

**Comment by chrismccord** [comment]
This is a somewhat obscure HTML issue, but the tldr; is you are giving your input the name `id`, and HTML forms objects will have all their child input names as attributes, so the parent `form.id` would actually point to the input element, rather than the DOM id, which is going to break the DOM patching (and likely other things). It's not a LV specific issue but it's more often experience because identifying nodes is going to be broken when patching. Use a different input name and you're golden. Thanks!

**Comment by atomkirk** [comment]
wooooow. wasted an hour because I named a hidden input id. I wonder how many people waste time on this and if its worth adding a check/warning to tooling.
