### ISSUE TITLE
Blur & mouseup events should be fired ignoring phx-throttle

### ISSUE THREAD

**Issue by tqwewe** [phoenixframework/phoenix_live_view#2318]
### Environment

* Elixir version (elixir -v):
   - Erlang/OTP 25 [erts-13.1.1] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns] [dtrace]
   - Elixir 1.14.1 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): phoenix 1.6.13
* Phoenix LiveView version (mix deps): phoenix_live_view 0.17.12
* Operating system: MacOS
* Browsers you attempted to reproduce this bug on (the more the merrier): Google Chrome, Safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: no

### Actual behavior

When implementing a slider with `phx-throttle="500"`, the value is not updated if I release the mouse too soon.

https://user-images.githubusercontent.com/16362377/200239347-ab57a34d-c4f1-4c88-9f21-d934f8304db3.mov

The min is 100, and max is 1000 in this example. When I click away from the slider, thats when it suddenly snaps back to its old value.

```html
<input
    name="tick_frequency"
    type="range"
    min="100"
    max="1000"
    value="500"
    phx-throttle="500"
    phx-change="ChangeTickFrequency" />
```

### Expected behavior

When I release my mouse, the throttle settings should be ignored, and an event should be fired immediately.

**Comment by chrismccord** [comment]
Blur is now trigger. Mouseup is
