### ISSUE TITLE
Live redirects update document title prior to pushState() call, resulting in an incorrect browser history

### ISSUE THREAD

**Issue by daamsie** [phoenixframework/phoenix_live_view#2322]
### Environment

* Elixir version (elixir -v): Elixir 1.13.4
* Phoenix version (mix deps): 1.6.15
* Phoenix LiveView version (mix deps): 0.18.3
* Operating system: Mac OS 11.6.2
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome / Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Not using node_modules

### Actual behavior

When clicking a live_redirect link, the title of the document is updated prior to the pushState() call. This results in the previous item in the history being incorrectly titled. 

<img width="617" alt="Screen Shot 2022-11-09 at 5 42 47 pm" src="https://user-images.githubusercontent.com/740324/200758225-2d475c43-a525-40ab-bacc-143685d27c75.png">

The incorrect title is shown when long-clicking on the back button (in the example below it should show "Morocco | Travel Massive").

<img width="618" alt="Screen Shot 2022-11-09 at 5 43 07 pm" src="https://user-images.githubusercontent.com/740324/200758245-935c5904-70d2-40ac-a14b-ccc49da2d11d.png">

### Expected behavior

The title in the history matches the title of the actual URL in the history. 

### Some further findings. 

In debugging this, I looked for where in the lifecycle the title of the page is updated. I found it was updated in this function. 

<img width="479" alt="Screen Shot 2022-11-09 at 5 09 01 pm" src="https://user-images.githubusercontent.com/740324/200758760-7a720dec-08dd-4257-8ff4-a1e4b54eb718.png">

Stepping over that showed clearly that it was being called before the pushState had happened.

**Comment by travelmassive** [comment]
This appears to be most problematic on mobile browsing (more use of the back button on mobile).
