### ISSUE TITLE
LiveView `live_img_preview` does not work for videos

### ISSUE THREAD

**Issue by mgwidmann** [phoenixframework/phoenix_live_view#2325]
### Environment

* Elixir version (elixir -v): 
Elixir 1.14.1 (compiled with Erlang/OTP 24)
* Phoenix version (mix deps):
  phoenix 1.7.0-dev (https://github.com/phoenixframework/phoenix.git) (mix)
  locked at d488e2b
* Phoenix LiveView version (mix deps):
  phoenix_live_view 0.18.3 (https://github.com/mgwidmann/phoenix_live_view.git - origin/fix-redirect-with-priv) (mix)
  locked at 836ddc6 (branch: fix-redirect-with-priv) (https://github.com/phoenixframework/phoenix_live_view/pull/2304)
* Operating system: mac OSX ARM64
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

When using the following code:

```
<.simple_form :let={f} for={@changeset} id="video-form" phx-target={@myself} phx-change="validate" phx-submit="save">
      <div class="hidden">
        <.live_file_input upload={@uploads.video} />
      </div>
      <%= for entry <- @uploads.video.entries do %>
        <article class="upload-entry">
          <figure>
            <.live_img_preview entry={entry} />
            <figcaption><%= entry.client_name %></figcaption>
          </figure>
 ...
```
[Link to repository here](https://github.com/mgwidmann/kart_vids/blob/b5953aa3eab58d268b7d234b4f5617b92cf1089a/lib/kart_vids_web/live/video_live/form_component.ex#L24)

It produces the following result visually:

![Screen Shot 2022-11-11 at 11 58 31 PM](https://user-images.githubusercontent.com/5035724/201457931-e2028a3b-84d7-44c4-8824-f680ca775ee7.png)

This is because in the DOM, the [element is an `img` tag](https://github.com/phoenixframework/phoenix_live_view/blob/703170844436ce7a1327b3a111a3967673b684c8/lib/phoenix_component.ex#L2423).

### Expected behavior

By simply allowing the user to indicate they expect video files, or Phoenix classified based upon the mime type as using an `img` or `video` tag accordingly, I would expect the video to be displayed. A `<video />` tag should have a `<source />` which has the `el.src = URL.createObjectURL(file)` done to it rather than the `<video />` which is where the `<img />` tag applies its source. The video will then show the video in the browser and the user can play it before submission (from their local machine, not yet uploaded).

I think only a few changes need to occur to make this work. A simple way to do it would be to have the user to simply pass in an indication that they intend to be displaying a `video`. Or, LiveView could use the `client_type` field it already has and detect which tag to use accordingly. Based on this [if conditional](https://github.com/phoenixframework/phoenix_live_view/blob/703170844436ce7a1327b3a111a3967673b684c8/lib/phoenix_component.ex#L2423), LiveView could render the `video` and `source` tags or the existing `img` tag. The JS hook would need to be updated to know this information as well, so it would have to check what type of tag it was and attach the `src` field accordingly.

Would a PR be accepted for this? I feel like videos are a common enough format that LiveView should support it but I understand if LiveView would not want to since the component is named `live_img_preview` not `live_video_preview` (this is also an alternative to detection to just create another component).

**Comment by rktjmp** [comment]
Probably makes sense to have a `live_audio_preview` too? (or `live_media_preview` if it were all in one.)

**Comment by mgwidmann** [comment]
This isn't any kind of blocker as this function is just a regular `Phoenix.Component` with nothing special. So, for those coming back to this later, heres a working example of a video preview component:

```
  @doc """
  Displays a video preview for a file which is being uploaded.

  Example:

      <.live_video_preview entry={entry} />
  """
  def live_video_preview(%{entry: %Phoenix.LiveView.UploadEntry{ref: ref} = entry} = assigns) do
    rest =
      assigns
      |> assigns_to_attributes([:entry])
      |> Keyword.put_new_lazy(:id, fn -> "phx-preview-#{ref}" end)

    assigns = assign(assigns, entry: entry, ref: ref, rest: rest)

    ~H"""
    <video data-phx-upload-ref={@entry.upload_ref} data-phx-entry-ref={@ref} data-phx-hook="Phoenix.LiveImgPreview" data-phx-update="ignore" {@rest} />
    """
  end
```

Just put into your `core_components.ex` file (or any module with `use Phoenix.Component` which is part of your `html_helpers` `*_web.ex` file). A similar `live_audio_preview` could be created.

However, this begs a larger question. Since there is extra data available, such as video and audio having durations, how do we get access to that? It seems the [JS LiveUploader](https://github.com/phoenixframework/phoenix_live_view/blob/master/assets/js/phoenix_live_view/live_uploader.js#L41-L57) has a serialize function which is called to gather metadata. But there doesn't seem to be a way to attach additional data here. Would be great to see a way to add a hook to the JavaScript which gets the entry object and allows it to modify the serialized payload before returning it. This would prevent nasty things like setting a hidden input element on a JS mount hook manually (which doesn't seem to always work for obvious reasons).

**Comment by mcrumm** [comment]
Thanks for the detailed thoughts! This is not a priority for us right now, but if someone is interested in sending a PR to add a `live_video_preview` component we would be happy to review it :)
