### ISSUE TITLE
Clarification/maybe a bug on assigns for mount and render_click in test

### ISSUE THREAD

**Issue by epinault** [phoenixframework/phoenix_live_view#233]
Hello! 

I am reading the API doc for testing a live view https://github.com/phoenixframework/phoenix_live_view/blob/master/lib/phoenix_live_view/test/live_view_test.ex#L133

It seems that we can set the assigns (I expected to see them on the socket assigns).

I tried and I see them set under the private field in the socket. What I am confused is how do I see assigns for a socket in test? I can use the session and pass them to the socket manually but then why is the API allowing you to set the assigns? or is that for a different use case?

So not really a bug per say but more a clarification
### Environment

* Elixir version (elixir -v):
* Phoenix version (mix deps):
* NodeJS version (node -v):
* NPM version (npm -v):
* Operating system:

**Comment by josevalim** [comment]
This is changing in a new branch since we will remove both assigns and session in favor of emulating mount_disconnected as a GET request ini the front end. So this discussion doesn't matter anymore, we will have a new API soon.
