### ISSUE TITLE
On recovery/After reconnection LiveView form submits only first (single) field value

### ISSUE THREAD

**Issue by cr0t** [phoenixframework/phoenix_live_view#2333]
### Environment

* Elixir version (elixir -v): 1.12+
* Phoenix version (mix deps): 1.6
* Phoenix LiveView version (mix deps): 0.17
* Operating system: macOS/Linux
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome 106-107, Firefox 106-107, Safari 13-14
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: no

### Actual behavior

After reconnection, LiveView attempts to recover forms' states by sending their corresponding values.

If a form in a live view component has an input field with `phx-change` attribute defined (**it must be first in the form!**), it sends the value of only this single field and ignores the rest.

This breaks backend processing.

See https://github.com/cr0t/liveview-form-recovery-example repo, which reproduces issue. Its README describes the steps need to be done to see the issue with form recovery process.

### Expected behavior

Form should send all its inputs' values despite `phx-change` attribute.

### Solution proposal

See https://github.com/phoenixframework/phoenix_live_view/pull/2181 for proposed solution.

**Comment by chrismccord** [comment]
Fixed for next release
