### ISSUE TITLE
Phoenix generators create invalid code with LiveView 0.18.

### ISSUE THREAD

**Issue by TheArrowsmith** [phoenixframework/phoenix_live_view#2335]
I generate a new Phoenix app; by default it uses Phoenix `1.6.15` and LiveView `0.17.12`:

```
$ mix phx.new example
$ cd example
$ mix deps | grep -w phoenix
* phoenix (Hex package) (mix)
  locked at 1.6.15 (phoenix) d70ab9fb
$ mix deps | grep live_view 
* phoenix_live_view (Hex package) (mix)
  locked at 0.17.12 (phoenix_live_view) af6dd5e0
```

Then I update `mix.exs` to bump live view to `0.18.3`; this also requires me to bump `phoenix_live_dashboard` to `0.7.2`:

```
… after editing mix.exs …
$ mix deps.update phoenix_live_view phoenix_live_dashboard
…
Upgraded:
  phoenix_live_dashboard 0.6.5 => 0.7.2 (minor)
  phoenix_live_view 0.17.12 => 0.18.3 (minor)
* Updating phoenix_live_view (Hex package)
* Updating phoenix_live_dashboard (Hex package)
```

But now I get this error when I try to start the server:

```
== Compilation error in file lib/example_web/views/layout_view.ex ==
** (CompileError) lib/example_web/templates/layout/live.html.heex:4: undefined function live_flash/2 (expected ExampleWeb.LayoutView to define such a function or for it to be imported, but none are available)
```

If I comment out the calls to `live_flash`, I get a different error after generating auth templates with `mix phx.gen.auth`:

```
$ mix phx.gen.auth Accounts User users
$ mix deps.get
$ mix phx.server
…
== Compilation error in file lib/example_web/views/user_session_view.ex ==
** (CompileError) lib/example_web/templates/user_session/new.html.heex:3: undefined function form/1 (expected ExampleWeb.UserSessionView to define such a function or for it to be imported, but none are available)
```

What am I doing wrong?

**Comment by josevalim** [comment]
Please follow the upgrage/CHANGELOG from Phoenix LiveView if you want to update it to v0.18. A module moved around but `import Phoenix.Component` should be enough to fix it.

**Comment by tamsanh** [comment]
For anyone who encounters this issue, the discreet solution is to open up your project, find any lines that are `import Phoenix.LiveView.Helpers` and replace that line with `import Phoenix.Component`.

**Comment by tindrew** [comment]
> For anyone who encounters this issue, the discreet solution is to open up your project, find any lines that are `import Phoenix.LiveView.Helpers` and replace that line with `import Phoenix.Component`.

Thank you, this was a big help for me. Just upgraded my first Phoenix project :)

**Comment by KaseyCantu** [comment]
Thank you @tamsanh - this worked perfectly! I too was upgrading my Phoenix project and ran into this weirdness. Not sure how I missed the updated in the changelog, but I am glad by app is back up and running :smile:
