### ISSUE TITLE
Have you considered using the approach for mobile apps as well?

### ISSUE THREAD

**Issue by pwtail** [phoenixframework/phoenix_live_view#2339]
Hi @josevalim , @chrismccord  and all the contributors.
LiveView is pure magic, I'm really impressed.

Have you considered using the approach for mobile apps as well?
Things have changed quite a bit, and now the declarative UI for mobile apps is a lot more possible.

For example, there is [divkit](https://github.com/divkit/divkit) from Yandex that is something like html for mobile apps (however, the only useful docs/overview of it are in Russian currently).

The fact that mobile platforms use different languages (Kotlin and Swift, at least) makes server-side rendering twice as attractive - because you don't have to use the platform-specific language.

Btw, I think, you might consider enabling Github Discussions for this repo.

**Comment by josevalim** [comment]
Hi @pwtail, glad to hear you are enjoying it! We have a place for discussions in the Elixir community via the ElixirForum.com, so I recommend moving the discussion there so more people can join. :)

**Comment by pwtail** [comment]
Ok, I ll do that
