### ISSUE TITLE
phx-disable-with doesn't work for input type="submit"

### ISSUE THREAD

**Issue by ashton314** [phoenixframework/phoenix_live_view#234]
### Environment

* Elixir version (elixir -v): 1.8.2
* Phoenix version (mix deps): locked at 8e57f77
* NodeJS version (node -v): v12.3.1
* NPM version (npm -v): 6.9.0
* Operating system: macOS 10.14.5

### Actual behavior

If the submit button for a form is actually an `input` tag like `<input type="submit" value="Submit this form!" phx-disable-with="Submitting..."/>", the text of the button doesn't get replaced during submission.

This isn't seen if using the nice `<%= submit ... %>` HTML helper because this creates a `<button>` element.

I think this happens because the disable code tries to set the `innerText` attribute. It seems that for `<input type="submit"/>`, this isn't used and the `value` attribute should be used instead.

Before submission:

<img width="1440" alt="Screen Shot 2019-06-01 at 20 08 58" src="https://user-images.githubusercontent.com/2874507/58755821-341a7780-84a9-11e9-9886-b24b68be8f38.png">

During form submission:

<img width="1440" alt="Screen Shot 2019-06-01 at 20 09 16" src="https://user-images.githubusercontent.com/2874507/58755830-409ed000-84a9-11e9-8343-b8b796b9d8b4.png">
 
Relevant code:

```html
<input type="submit" value="Save (input tag)" phx-disable-with="Saving (input tag)..." class="btn btn-primary"/>
<%= submit "Save (regular button)", phx_disable_with: "Saving...", class: ["btn btn-primary"]%>
```

Note how the text for the input tag is not changed in the second image.

### Expected behavior

`<input type="submit"/>` text would be replaced just as the regular button text would.

**Comment by TheMushrr00m** [comment]
Yes, you are right, i just make a pull request to fix this.
#238
