### ISSUE TITLE
`assign_new` small doc improvement 

### ISSUE THREAD

**Issue by tcoopman** [phoenixframework/phoenix_live_view#2352]
The docs contain this:

```elixir
        assigns = assign_new(assigns, :color, fn -> Enum.random(~w(red green blue)) end) 
  
         ~H""" 
         <div class={"bg-#{@color}"}> 
           Example 
         </div>
```

It's a tiny issue but still, the problem is that this show text concatenation for CSS classes and this is something that doesn't work with tailwind.
As tailwind is now the default, the concatenation should be removed.

I'll try to submit a pr tomorrow

**Comment by chrismccord** [comment]
Please send a PR. Thanks!
