### ISSUE TITLE
preload does not receive existing assigns

### ISSUE THREAD

**Issue by dvic** [phoenixframework/phoenix_live_view#2357]
### Environment

* Phoenix LiveView version: 0.18.3

### Actual behavior

The `preload/1` callback of a live component does not receive the existing assigns. For example, when rendering a list view like this:

```
<.live_component :for={id <- @ids} id={id} module={CommentListItem} />
```

Now imagine the `preload/1` callback loads the actual comment from the database. When adding a new item to `@ids`, `preload/1` will be call with a list of assigns for all instances, but the assigns will only contain the `id` assign. Is this  intended?

### Expected behavior

I expected to have all assigns available in the preload so that I can filter out the stuff that is already loaded.

**Comment by josevalim** [comment]
Preload is only called on the first render, so there are no existing assigns. If you need to do any loading during updates of existing components, then that logic needs to be moved up to the LiveView currently. There are no plans to change that at the moment.

**Comment by josevalim** [comment]
Thanks, I definitely got confused.

The goal of preload is to massage the data before it ever reaches `update/2`. The big question is: is this just a "surprising" behaviour (if so we should document) or is it blocking you from doing something? (i.e. you now have to load data you have already loaded or similar?).

**Comment by dvic** [comment]
> The big question is: is this just a "surprising" behaviour (if so we should document) or is it blocking you from doing something? (i.e. you now have to load data you have already loaded or similar?).

It's definitely blocking me to avoid loading data that I already have loaded. I mean, I could avoid it, but then I would have to jump through extra hoops, an example would better explain it:

Let's say we have a `ListView` live component that is responsible for fetching a list of item IDs and responding to `NewItemAdded` events by appending the new ID to the current list of IDs.

The template could look something like this:

```
<.live_component :for={id <- @ids} id={id} module={ListItem} />
```

Then, the `ListItem` live component could preload all the necessary data, which is nice (the fetching of the data is colocated with the same place where it's being rendered).

However, when `@ids` is mutated (e.g., by handling the `NewItemAdded` event), then all the items are loaded again, whereas only the last one needs loading.

In order to achieve this, I would have to do something like:

```
<.live_component :for={{id, already_loaded} <- @ids} id={id}
                                                     already_loaded={already_loaded}
                                                     module={ListItem} />
```

and manually set `already_loaded` to false only for the last item (unless it's the first time, then all are false). Then I can check this assign inside the `preload/1` function to skip loading these items.

**Comment by josevalim** [comment]
We could support `preload/2` that receives old and current assigns. You can zip them to see "do i have data for this?". WDYT? Can you explore this and send a PR?

**Comment by dvic** [comment]
> We could support `preload/2` that receives old and current assigns. You can zip them to see "do i have data for this?". WDYT? Can you explore this and send a PR?

Sounds good! I'll have a look and send a PR!
