### ISSUE TITLE
Accidentally using attr on live_components causes errors that are difficult to debug

### ISSUE THREAD

**Issue by trashhalo** [phoenixframework/phoenix_live_view#2358]
I was refactoring a component to a live component to manage some state and I absentmindedly thought I could keep the attr definitions. It broke in weird ways that didn't explain the real issue. 

## Attrs before the mount method causes:

 ** (ArgumentError) assign/3 expects a socket from Phoenix.LiveView/Phoenix.LiveComponent  or an assigns map from Phoenix.Component as first argument, got: %{}You passed an assigns map that does not have the relevant change tracking information. This typically means you are calling a function component by hand instead of using the HEEx template syntax. If you are using HEEx, make sure you are calling a component using:

## attr rest global above render method messes with state set in mount

Any state you assign in mount somehow gets put inside the rest map. Like you can assign a new atom to root and it gets moved to rest in render

## solutions
I think failing loudly and clearly when putting a attr in a lc would be good. Or adding that attrs are component only somewhere clear in the docs.

**Comment by josevalim** [comment]
Can you please provide a code example of how to reproduce it? Can you fill in the issues template with versions and everything else? Thank you.

**Comment by trashhalo** [comment]
Sure thing. I'm away from laptop right now but will be back to work Monday

**Comment by trashhalo** [comment]
I managed to reproduce the first one on my cellphone using replit https://replit.com/@trashhalo/Issue2358

**Comment by chrismccord** [comment]
Declarative assigns are only supported for function components, so using them before mount necessarily errors. Declaring them on render for a LV is also not supported, but we would be happy to accept a PR that improves the error. Thanks!
