### ISSUE TITLE
Hidden input value not properly updated after triggering change event from JS

### ISSUE THREAD

**Issue by maxmarcon** [phoenixframework/phoenix_live_view#2359]
### Environment

* Elixir version (elixir -v):  1.14.0
* Phoenix version (mix deps):  1.6.15
* Phoenix LiveView version (mix deps): 0.18.3 
* Operating system: macOS 13.0.1
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox, Chrome 
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Context

Here's the repository to replicate the issue: https://github.com/maxmarcon/input_update_behavior

There's a hidden and a text input in a form, both bound to the same assign called `value` (initially 0)

The value can be incremented by either clicking on a div or on a button.

There is also a button that triggers a change event on the form, by using a JS hook to dispatch an "input" event on the hidden input field:

 ```js
this.el.querySelector("input[type=hidden]").dispatchEvent(new Event('input', {bubbles: true}))
```

There is also a submit button. The parameters of change and submit events are shown on the UI when received

### Actual behavior

When the user performs the following sequence of events:

* Click on the `div` a few times
* Click on the `trigger change` button
* Click on the `div` again
* Click on the `trigger change` button

The change event handler receives different values for the text input and hidden input fields, even though they're both bound to the same variable:

<img width="816" alt="mismatch" src="https://user-images.githubusercontent.com/11156096/207544184-59f01ba1-0281-452c-baa2-e57b5024a75c.png">

The text input field sends the most up-to-date value to the server, whereas the hidden input sends the (outdated) value at the time of the last change event

Interestingly enough, the issue doesn't occur if one increments the value using the button instead of the div.

### Expected behavior

The values of the 2 input fields should never get out of sync, they should always be the same.The hidden input field should send the current value of the `value` assign to the server.

**Comment by maxmarcon** [comment]
thanks @chrismccord. However I tried with master and the issue is still there :(

**Comment by chrismccord** [comment]
Are you sure you are referencing the correct js dep? Using npm? Using your repro this fixes it, so please double check. Thanks!

**Comment by maxmarcon** [comment]
yep, my bad, I had forgotten to rebuild LiveView's JS assets from master before testing 🤦 

I confirm that it works! Thank you so much 🚀

**Comment by chrismccord** [comment]
Great!
