### ISSUE TITLE
Nested phx-updates

### ISSUE THREAD

**Issue by aDingil** [phoenixframework/phoenix_live_view#2361]
It would be very helpful to have the option to overwrite a phx-update of a parent inside a child.

For example when writing plugins for a existing js lib, where the lib has to have a phx-update="ignore" to work properly.

**Comment by chrismccord** [comment]
We don't accept feature requests on the issue tracker. Target the container the js lib needs access to. Thanks!

**Comment by aDingil** [comment]
How can i create a feature requests?

**Comment by chrismccord** [comment]
Start a discussion on the elixir forums or send a proposal to the phoenix-core mailing list, but I can say that the requested feature is not feasible for us to implement. Thanks!

**Comment by aDingil** [comment]
Okay, will do. Many thx.
