### ISSUE TITLE
Decoupled hooks for liveviews that are rendered from Controller are not supported

### ISSUE THREAD

**Issue by margusp2heathmont** [phoenixframework/phoenix_live_view#2365]
If live_render()/2 is used from Controller (that imports Phoenix.LiveView.Controller), then Hooks are not executed. Even if post()/3 is declared within live_session, that has hooks described. Using attach_hook from LiveView would not work in all the scenarios (let's say when you want to use 3rd external libraries LiveView, but with some custom data loader.)

Is there any other approach to attach decoupling or will this support be enabled?

**Comment by josevalim** [comment]
@margusp2heathmont can you please file the issues template? Which browsers? Which LiveView versions? thanks.

**Comment by margusp2heathmont** [comment]
Hey, @josevalim! :) 

I hope your end of year and new year are beautiful! :) 

I made example here: https://github.com/margusp2heathmont/example_app/tree/main/lib/example_app_web

Background context: I want to use LiveView functionality, but I need to set cookie from controller, so it would be HTTP only.

Please notice problems that I noticed:
1. LiveView does not support updating cookie (http only, so it can not be stoled with XSS)
2. When live_render is used from controller, Hooks do not get executed.

Important files/lines:
1. In plug I set locale, that is set to socket in Hook, that is decoupled into router.ex: https://github.com/margusp2heathmont/example_app/blob/main/lib/example_app_web/router.ex#L25  
2. In LiveView I use mount: https://github.com/margusp2heathmont/example_app/blob/main/lib/example_app_web/pages/hello_page.ex#L50 (that sets data from Hook or from session)

For setting secure cookie, it would be ideal:
a. if router.ex live()/2 would support POST (not only get) - (so maybe plug could be used to do login?)
b. if LiveView is rendered from Controller, then Hooks will be executed (in decoupled way)

Maybe I am doing wrong pattern - any ideas welcome.

**Comment by josevalim** [comment]
Thank you, happy new year to you too!

---

Correct. The hooks are only executed for `live` actions.

Generally speaking you can't set cookies from LiveView because they happen over websocket. You'd need a POST action and then redirect to a regular `get` or `live` route.

Inside a LiveView, you can also set cookies by doing either HTTP/Ajax requests. There is also phx-trigger-action that facilitates how forms work.

**Comment by chrismccord** [comment]
Lifecycle hooks are a way for LiveView to handle lifecycle "middleware", similar to plugs in a controller pipeline. Since you are staying inside controller land, live_render from the controller pipeline is necessarily limited. You almost need want to live render from a controller. Thanks!
