### ISSUE TITLE
 Can’t use `Element.remove()` nor `Element.replaceChildren()` in LiveView modal

### ISSUE THREAD

**Issue by Sleepful** [phoenixframework/phoenix_live_view#2368]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 25 [erts-13.0.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.14.1 (compiled with Erlang/OTP 25)
```
* Phoenix version (mix deps):
* Phoenix LiveView version (mix deps):
```
      {:phoenix, "~> 1.6.13"},
      {:phoenix_ecto, "~> 4.4"},
      {:ecto_sql, "~> 3.6"},
      {:postgrex, ">= 0.0.0"},
      {:phoenix_html, "~> 3.0"},
      {:phoenix_live_reload, "~> 1.2", only: :dev},
      {:phoenix_live_view, "~> 0.18.3"},

```
* Operating system: OSX
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Behavior 

Whenever I try to use [Element.remove()](https://developer.mozilla.org/en-US/docs/Web/API/Element/remove) or [Element.replaceChildren()](https://developer.mozilla.org/en-US/docs/Web/API/Element/replaceChildren) on an HTML node that belongs to the subtree of a liveview modal provided by [mix.gen.live](https://hexdocs.pm/phoenix/Mix.Tasks.Phx.Gen.Live.html), the entire modal closes and liveview triggers navigation to the previous page.

Removing `phx-remove={hide_modal()}` from the liveview modal doesn't have any effect. Adding `phx-update="ignore"` doesn't have any effect either.

This is the default boilerplate code from the liveview modal, in case it is handy:

```
  def modal(assigns) do
    assigns = assign_new(assigns, :return_to, fn -> nil end)

    ~H"""
    <div id="modal" class="phx-modal fade-in" phx-remove={hide_modal()}>
      <div
        id="modal-content"
        class="phx-modal-content fade-in-scale
         bg-base-100 "
        phx-click-away={JS.dispatch("click", to: "#close")}
        phx-window-keydown={JS.dispatch("click", to: "#close")}
        phx-key="escape"
      >
        <%= if @return_to do %>
          <%= live_patch "✖",
            to: @return_to,
            id: "close",
            class: "phx-modal-close",
            phx_click: hide_modal()
          %>
        <% else %>
          <a id="close" href="#" class="phx-modal-close" phx-click={hide_modal()}>✖</a>
        <% end %>

        <%= render_slot(@inner_block) %>
      </div>
    </div>
    """
  end

  defp hide_modal(js \\ %JS{}) do
    js
    |> JS.hide(to: "#modal", transition: "fade-out")
    |> JS.hide(to: "#modal-content", transition: "fade-out-scale")
  end
```

Using the same functions inside a shadow root does not present this issue, suggesting that this is a liveview issue.

Additionally, using the functions from the browser console does not present the issue either, example:

`document.querySelector("[data-id=label]").remove()`

**Comment by chrismccord** [comment]
Can you put together a minimal example application that demonstrates the issue? It's not clear what is happening as described and we won't be able to say more without an example that reproduces the issue. Thanks!

**Comment by Sleepful** [comment]
@chrismccord look at the last two commits here:

https://github.com/Sleepful/phoenix_bug

lmk if this is a bug that I can help solve, would be happy to do so

**Comment by Sleepful** [comment]
What it looks like: 

![2023-01-03 13 17 12](https://user-images.githubusercontent.com/7144046/210425967-878e6232-a776-4c3f-bbcc-4f7fae83ac2d.gif)

**Comment by chrismccord** [comment]
Looks like you need to call event.stopPropagation() here:
https://github.com/Sleepful/phoenix_bug/blob/main/assets/js/app.js#L63
Otherwise it bubbles up to LV and the modal is closed. I don't believe there is any issue on our side. Thanks!
