### ISSUE TITLE
Segmentation fault Phoenix live view

### ISSUE THREAD

**Issue by eduazul29** [phoenixframework/phoenix_live_view#237]
### Environment

*Elixir 1.7.2 (compiled with Erlang/OTP 20)
* 1.4.0
*v6.9.2
*3.10.9
*Debian GNU/Linux 9.5 (stretch)

### Actual behavior

Hi, can you help me?
I'm working with elixir and phoenix and I just implemented live view.
Everything goes smoothly but **sometimes** when loading the url of my application in live view my application stops but no error appears in the console.
The only reference I have is: "Segmentation fault".
Recently update my elixir version with the following commands:
`wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb && sudo dpkg -i erlang-solutions_1.0_all.deb`
`sudo apt-get update`
`sudo apt-get install elixir`

But I only started to have this problem since I implemented live view as indicated on this page: https://elixirschool.com/blog/phoenix-live-view/
And I have other applications that are not live view and had never been presented to me.

**Comment by chrismccord** [comment]
Since we don't use nifs in this project, this is not something on our end. I would recommend installing the latest Erlang OTP, or a different stable version
