### ISSUE TITLE
Configurable csrf token session key

### ISSUE THREAD

**Issue by cjbottaro** [phoenixframework/phoenix_live_view#2370]
It seems that LV expects the session key to be `"_csrf_token"` and it's not a configurable option. My app is sharing a session with a Rails app which already uses that session key. So I'm configuring Phoenix with a different session key:
```elixir
plug :protect_from_forgery, session_key: "_phoenix_sa_csrf_token"
```
This breaks connected `mount/3` because it can't find `"_csrf_token"` in the session (or in my case, it finds Rails' csrf token which doesn't work).

It would be nice if `Phoenix.Endpoint.socket/3` could take the csrf token session key as a configurable option, something like:
```elixir
socket "/live", Phoenix.LiveView.Socket, websocket: [
    connect_info: [
      session: [...],
      csrf_session_key: "_phoenix_sa_csrf_token"
    ]
  ]
```

I think could open a PR for this if you let me know how to name the configuration option.

**Comment by josevalim** [comment]
Yes, please PR. csrf_session_key is perfect.

**Comment by cjbottaro** [comment]
It seems the relevant code is in the phoenix repo. I opened a PR:
https://github.com/phoenixframework/phoenix/pull/5183

But I'm not sure if phoenix_live_view also needs to be updated because of this code in Phoenix.LiveView.Channel:
```elixir
  defp load_csrf_token(endpoint, socket_session) do
    if token = socket_session["_csrf_token"] do
      state = Plug.CSRFProtection.dump_state_from_session(token)
      secret_key_base = endpoint.config(:secret_key_base)
      Plug.CSRFProtection.load_state(secret_key_base, state)
    end
  end
```

Which also seems to be using a hardcoded session key.
