### ISSUE TITLE
'mix format' adds a newline to link() / <a href=.../> text   

### ISSUE THREAD

**Issue by markmark206** [phoenixframework/phoenix_live_view#2374]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 25 [erts-13.1.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit] [dtrace]

Elixir 1.14.1 (compiled with Erlang/OTP 25)
```
* Phoenix version (mix deps):

```
$ mix deps
...
* phoenix 1.6.15 (Hex package) (mix)
  locked at 1.6.15 (phoenix) d70ab9fb
  ok
...
* phoenix_html 3.2.0 (Hex package) (mix)
  locked at 3.2.0 (phoenix_html) 36ec97ba
  ok
...
* phoenix_live_view 0.18.3 (Hex package) (mix)
  locked at 0.18.3 (phoenix_live_view) c8845177
  ok
...
* phoenix_template 1.0.0 (Hex package) (mix)
  locked at 1.0.0 (phoenix_template) 1b066f99
  ok
* phoenix_view 2.0.1 (Hex package) (mix)
  locked at 2.0.1 (phoenix_view) 6c358e2c
  ok
```
* Phoenix LiveView version (mix deps):
```
* phoenix_live_view 0.18.3 (Hex package) (mix)
  locked at 0.18.3 (phoenix_live_view) c8845177
  ok
```

* Operating system:

```
mac os 12.6.1 
```

* Browsers you attempted to reproduce this bug on (the more the merrier): 

```
chrome: 108.0.5359.124 (Official Build) (arm64)
safari: Version 16.1 (17614.2.9.1.13, 17614)
```
(however, further down, i am including a link to an elixirforum post containing a script that reproduces the problem without a browser)

* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: 
Yes.

### Actual behavior

This HEEX code works as expected:

```elixir
    ~H"""
    <%= link to: "/i", method: :get do %>
      <%= "same line" %><% end %>,
    """
```

In the generated (and rendered HTML), the comma follows the link text immediately, as expected:

```html
<a href=\"/i\">\n  same line</a>,\n
```

"`same line,`"

However,  `mix format` reformats the HEEX code into 
```elixir
    ~H"""
    <%= link to: "/i", method: :get do %>
      <%= "same line" %>
    <% end %>,
    """
```

It turns out that this format change also changes what the code actually does – in the generated HTML, there is now a newline before the comma 

```html
<a href=\"/i\">\n  same line\n</a>,\n
```

When I render this html, I now see a space between "same line" and the comma: "`same line ,`"

### Expected behavior

I expect that running `mix format` does not add whitespace in my rendered html, ;)

More generally, I expect a code formatter to format the code, and to have 0 effect on what the code actually does.

Please see this elixirforum thread for more details / repro script:  https://elixirforum.com/t/heex-formatter-adds-a-line-break-in-generated-html/52837/4?u=markmark206
 
Thank you for creating and growing such an excellent language / framework / ecosystem. ; )

**Comment by josevalim** [comment]
Unfortunately this is intentional.

The rules for whitespace on HTML are actually quite complex and if we were to always preserve them, then we would never change any whitespace ever, which would defeat the point of the formatter. For example, you can also think someone would write the exact same code as above and want the `<% end %>` to be moved. :)

Luckily, in your case, you should rather write it using the new `<.link>` HEEx component (or even just `<a ...>`) which HEEx does a better job of formatting and respecting the whitespace around in certain cases.

**Comment by adamu** [comment]
> write it using the new `<.link>` HEEx component

Just in case anybody else reads that and wonders where it is:
https://hexdocs.pm/phoenix_live_view/1.0.9/Phoenix.Component.html#link/1
