### ISSUE TITLE
`:assign_new` empty on a child live_view added dynamically

### ISSUE THREAD

**Issue by DianaOlympos** [phoenixframework/phoenix_live_view#2375]
### Environment

* Elixir version (elixir -v): `Elixir 1.14.2 (compiled with Erlang/OTP 25)`
* Phoenix version (mix deps): ```phoenix 1.7.0-rc.0 (Hex package) (mix)
  locked at 1.7.0-rc.0 (phoenix) ed503f6c```
* Phoenix LiveView version (mix deps): ```phoenix 1.7.0-rc.0 (Hex package) (mix)
  locked at 1.7.0-rc.0 (phoenix) ed503f6c
```
* Operating system: Linux
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

When adding a child Liveview through  `live_render`, the use of `assign_new` works correctly if the liveview is rendered directly in the heex. If the liveview is added _dynamically_, like following an handle_event, then the `assign_new` received is empty, and as such `assign_new` behave like if the parent assigns were never received.

It seems after debugging a bit that the `Utils.configure_socket` get called here https://github.com/phoenixframework/phoenix_live_view/blob/v0.18.3/lib/phoenix_live_view/channel.ex#L1001 a second time with an empty `mount_priv`, in the case that the liveview is added dynamically, clearing the `private.assign_new`.

### Expected behavior

I expect the child liveview to always receive the parents assigns. This seems to be in agreement with the code at https://github.com/phoenixframework/phoenix_live_view/blob/v0.18.3/lib/phoenix_live_view/static.ex#L172

A  reproduction can be found at https://github.com/DianaOlympos/nested_liveview_for_bug, sadly not minimal/one file for now, i will work on doing a one file next week if i have time.

**Comment by chrismccord** [comment]
This is expected. The child always needs to be able to recover on its own with minimal session state, such as a cross and remount, which a dynamic child is treated it the same way. Thanks!

**Comment by DianaOlympos** [comment]
Ok but then what do we do if we want to pass information to a child? Do we have to pass it in a session? If yes, then what is the purpose of assign_new?

For example, I have 4 different charts, all the same LiveView but tracking a separate piece of data. How can I tell the child which piece of data they are tracking? Or is it that I cannot use LiveViews child like this and I have to limit it to LiveComponents?
