### ISSUE TITLE
Layouts with live_session don't work on initial mount

### ISSUE THREAD

**Issue by binarypaladin** [phoenixframework/phoenix_live_view#2376]
### Environment

* Elixir version (elixir -v): Elixir 1.14.2 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): 1.7.0-rc.0
* Operating system: macOS 13.1

### Expected behavior

When specifying a layout using `live_session` the layout should appear on the initial mount.

### Actual behavior

When using `live_session` to specify a layout, the layout is not rendered on the initial load. It seems to kick in on once the web socket starts up.

[See this forum discussion.](https://elixirforum.com/t/layouts-specified-in-live-session-liveview-0-18-3-phoenix-1-7-0-rc-0-and-first-renders/52587)

**Comment by jsonmaur** [comment]
A workaround for this is to use a custom `on_mount` function for setting the layout:

```elixir
defmodule MyAppWeb.Layouts do
  # ...
  
  def on_mount(:some_layout, _params, _session, socket) do
    {:cont, Phoenix.Component.assign_new(socket, :layout, fn -> {MyAppWeb.Layouts, :some_layout} end)}
  end
end
```

```elixir
live_session :default, on_mount: [{MyAppWeb.Layouts, :auth_layout}] do
  live "/foobar", FooBarLive
end
```

**Comment by jsonmaur** [comment]
@chrismccord Hope you don't mind but I took a stab at fixing this :)
