### ISSUE TITLE
moving tag with a particular id into temporary assigns breaks phx-update ordering

### ISSUE THREAD

**Issue by ityonemo** [phoenixframework/phoenix_live_view#2378]
### Environment

* Elixir version (elixir -v): 1.14.2, 1.13.4
* Phoenix version (mix deps): 1.6.15
* Phoenix LiveView version (mix deps): 0.17.2
* Operating system: linux, mac
* Browsers you attempted to reproduce this bug on (the more the merrier):  Firefox, Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: N/A

Minimal Reproduction

```elixir
defmodule TestyMcTestFaceWeb.Live do
  use Phoenix.LiveView

  defmodule Item do
    use Phoenix.LiveComponent

    def render(assigns) do
      ~H"""
      <div id={@id}><%= @id %></div>
      """
    end
  end

  def render(assigns) do
    ~H"""
    <div id="main">
      <div id="buffer" phx-update="append">
        <%= for id <- @buffer do %>
        <Item.render id={id}/>
        <% end %>
      </div>
      <div id="current">
        <Item.render id={@current}/>
      </div>
    </div>
    """
  end

  def mount(_, _, socket) do
    if connected?(socket) do
      :timer.send_interval(500, :ping)
    end
    {:ok, assign(socket, index: 1, current: "id-1"), temporary_assigns: [buffer: []]}
  end

  def handle_info(:ping, socket) do
    index = socket.assigns.index + 1
    {:noreply, assign(socket, buffer: [socket.assigns.current], index: index, current: "id-#{index}")}
  end
end
```

### Actual behavior

The new temporary assigns tags are prepended to the front of the children of `#buffer` div in the DOM.

### Expected behavior

The new temporary assigns tags should be appended to the back of the children of `#buffer` div in the DOM.

It might be reasonable to issue guidance that the divs NEED to have different ids when they transition from permanent assign to temporary assign, however, there are many cases where having the same id would be much, much more convenient for the developer.

**Comment by josevalim** [comment]
This is in purpose as you can easy this mechanism to update entries in place. We want to provide tighter controls in the future but the current behavior is on purpose!

**Comment by ityonemo** [comment]
OK, I will PR some documentation.
