### ISSUE TITLE
`attr` - missing required attribute does not throw compiler warning from .heex files

### ISSUE THREAD

**Issue by mbuquet** [phoenixframework/phoenix_live_view#2383]
### Environment

* Elixir version (elixir -v): `Elixir 1.14.2 (compiled with Erlang/OTP 24)`
* Phoenix version (mix deps): `phoenix 1.6.15`
* Phoenix LiveView version (mix deps): `phoenix_live_view 0.18.4`
* Operating system: `Alpine Linux v3.16`
* Browsers you attempted to reproduce this bug on (the more the merrier): N/A
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: N/A

### Example Code

```elixir
# lib/test/my_component.ex
defmodule Test.MyComponent do
  use Phoenix.Component

  attr :name, :string, required: true

  def my_component(assigns) do
    ~H"""
    hello, <%= @name %>
    """
  end

  def my_func(assigns) do
    ~H"""
    <.my_component />
    """
  end
end
```

```elixir
# lib/test_web/views/page_view.ex
defmodule TestWeb.PageView do
  use TestWeb, :view
end
```

```elixir
# lib/test_web/templates/page/index.html.heex
<Test.MyComponent.my_component />
```

### Actual behavior

When compiling, the above code correctly returns a compiler warning for the missing `name` attribute in the `Test.MyComponent.my_func/1` call. There is no compiler warning for invoking the function component inside the `index.html.heex` file.

Compile output:

```
warning: missing required attribute "name" for component Test.MyComponent.my_component/1
  lib/test/my_component.ex:14: (file)
```

### Expected behavior

A compiler warning should be thrown when invoking a function component with missing required attributes from `.html.heex` files.

Expected compiler warning:
```
warning: missing required attribute "name" for component Test.MyComponent.my_component/1
  lib/test_web/templates/page/index.html.heex:1: (file)
```

**Comment by mbuquet** [comment]
After some trial and error, I've found that adding `use Phoenix.Component` to the view file (`lib/test_web/views/page_view.ex` in my example above) fixes the issue and a compiler warning is then returned for the `.html.heex` file.

```elixir
defmodule TestWeb.PageView do
  use TestWeb, :view
  use Phoenix.Component
end
```

I'm unsure if this is considered a bug or not, but considering that I can invoke function components and other compiler warnings work _without_ `use Phoenix.Component` being in view file it seems something isn't right with the `attr` required attribute checks.

**Comment by josevalim** [comment]
Yes, this is expected. The tracking only happens if you `use Phoenix.Component`. Feel free to send a PR to add this note but IIRC it was noted somewhere.

**Comment by mbuquet** [comment]
I understand. The only argument I have is that a developer could go a long time invoking function components throughout their app and not have the benefit of the attribute compiler warnings since just using function components does not also enable the compiler warnings.

For example, in our app we had an instance/typo of `<.form phx_chang={:validate} ...>` (the missing `e` on change). It was only until I realized yesterday that we need to add `use Phoenix.Component` to all views for the compiler warnings to work that these type of issues were brought up.
```
warning: undefined attribute "phx_chang" for component Phoenix.Component.form/1
```

We're now digging into creating our own custom function components which is the only thing that sparked my interest in these compiler warnings. If we were just sticking to the components that come baked in, we might not ever realize that the compiler warnings existed to assist us.

**Comment by josevalim** [comment]
This is tricky because the template engine does not require Phoenix.Component and requiring so right now could be a breaking change.  Also, new Phoenix apps only use Phoenix.Component, no Phoenix.View, so in time that will be the norm and maybe we can flip things around. But too disruptive at the moment.

**Comment by srcrip** [comment]
Has anyone else had issues with this in new Phoenix projects? I have a component where the required attrs do not throw an error unless I use it in an explicit `render` function of a LV (ie it does nothing in a heex file)

**Comment by josevalim** [comment]
Can you provide a minimal repro? As long as the module that calls the component has `use Phoenix.Component` in it, it should work.

**Comment by josevalim** [comment]
In theory it should also work because all compilers diagnostics are emitted the same way. Which LSP are you using? And can you confirm it does not show even on save?
