### ISSUE TITLE
handle_event doesn't work with x-data/x-show

### ISSUE THREAD

**Issue by aleagnelli** [phoenixframework/phoenix_live_view#2385]
### Environment

* Elixir version (elixir -v): 1.14.2
* Phoenix version (mix deps): 1.6.14
* Phoenix LiveView version (mix deps): 0.18.4
* Operating system: linux
* Browsers you attempted to reproduce this bug on (the more the merrier): chrome/firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

I have a live view page with navigation bar to switch between multiple tabs, in each tab I have a component which contains a dedicated form.
The navigation bar is controlled by alpine js: with `x-data` I have a variable that hold the active tab and `x-show` hide/show the correct tab.
After upgrading to 0.18.4 the forms, that are not in the default tab, do not invoke `handle_event/3` function of components when their tab is selected.

### Expected behavior

Components should invoke the `handle_event/3` function after they become visible

**Comment by tomtaylor** [comment]
I think I'm experiencing something similar, where elements that are show/hidden with a Bootstrap 5.2 toggle area don't fire events after the toggle is expanded.

**Comment by chrismccord** [comment]
Sounds like this is something on the alpine side. If folks can put together an example that recreates the issue I will try to take a look. Thanks!

**Comment by aleagnelli** [comment]
@chrismccord Thanks for reaching out, one thing I missed the last time is:
from the console.log when I press the button I see:
```
phx-.... socket: disconnect for page nav
phx-.... destroyed: the child has been removed from the parent
```
I am trying to reproduce in a simple example (like [here](https://github.com/wojtekmach/mix_install_examples/blob/main/phoenix_live_view.exs)) but haven't had any luck
if you have any clue on where to look to be able to reproduce it, I can try to come up with an example
