### ISSUE TITLE
Params of form_for, not available in form component

### ISSUE THREAD

**Issue by MartinElvar** [phoenixframework/phoenix_live_view#2388]
A bit unsure if this is a bug, feature request or just me doing it wrong.

I've create a form using the <.form ..> component, as it doesn't make sense to have a structure for this form i've supplied an atom to the for attribute, as such.

```
  <.form
    :let={f}
    for={:template}
    phx-change="change_template"
    phx-target={@myself}
  >
```

I have found, that if i don't manually supply the value of each field it won't be applying the state to the forms, and the following will happen.

![forms-attrs](https://user-images.githubusercontent.com/1180266/211569650-7b9fc270-c325-4132-9ffc-db6b66544f71.gif)

I then looked up the documentation and found the [params](https://hexdocs.pm/phoenix_html/3.2.0/Phoenix.HTML.Form.html#__struct__/0) attribute, which allows me to supply a map with the field names and maintain them in my `change_template`

```
  <.form
    :let={f}
    for={:template}
    phx-change="change_template"
    params={@template}
    phx-target={@myself}
  >
```
This solves the problem for me, now i don't have to supply the value manually to each input field. Ready to commit a push, i ran a compiler warning check and got

```
warning: undefined attribute "params" for component Phoenix.Component.form/1
  lib/...web/live/components/organisms/admin/solution_sprints/export_template.html.heex:6: (file)
```

Is this intended? I don't mind submitting a pr that adds the attribute if it isn't. :slightly_smiling_face: 

Thanks.

**Comment by josevalim** [comment]
A PR is welcome I believe!

**Comment by philipgiuliani** [comment]
I just wanted to create a similar issue. We are using Alpine.JS and the `<form>` component doesn't accept the alpines `x-ref`, `x-data` ect... What do you think about a way to extend the `:global`-Attributes via configuration?

**Comment by josevalim** [comment]
@philipgiuliani there is already a mechanism to extend globals. Please check Phoenix.Component docs :)

**Comment by josevalim** [comment]
Closing in favor of the PR.
