### ISSUE TITLE
Regression: Cannot convert component ...

### ISSUE THREAD

**Issue by maennchen** [phoenixframework/phoenix_live_view#2389]
### Environment

* Elixir version (elixir -v): `.14.2 (compiled with Erlang/OTP 25)`
* Phoenix version (mix deps): `1.6.15`
* Phoenix LiveView version (mix deps): `0.18.6`
* Operating system: `Ubuntu 22.04.1 LTS / Linux 5.15.0-57-generic`
* Browsers you attempted to reproduce this bug on (the more the merrier): irrelevant
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

https://github.com/jshmrtn/hygeia/blob/c5b9178ecbc031946a89b63124b55e372bae1d1e/lib/hygeia_web/live/lock.ex#L49

```elixir
  @impl Phoenix.LiveComponent
  def render(assigns) do
    ~F"""
    <div>
      <#slot :if={not @lock or @lock_acquired} />
      <div :if={@lock and not @lock_acquired} class="alert alert-info">
        <p>{gettext("Someone else is currently editing this resource. Wait until they finished their work.")}</p>
        <div class="d-flex align-items-center gap-2">
          <div class="spinner-border" role="status">
          </div>
          <span class="sr-only">{gettext("Acquiring Lock...")}</span>
        </div>
      </div>
    </div>
    """
  end
```

https://github.com/jshmrtn/hygeia/actions/runs/3883681890/jobs/6625274266

```
Error:      test/hygeia_web/live/visit_live_test.exs:83
     ** (ArgumentError) cannot convert component HygeiaWeb.Lock with id "lock_visit_189f4f42-f3ea-4969-941e-92128a098f29" to HTML.
     
     A component must always be returned directly as part of a LiveView template.
     
     For example, this is not allowed:
     
         <%= content_tag :div do %>
           <.live_component module={SomeComponent} id="myid" />
         <% end %>
     
     That's because the component is inside `content_tag`. However, this works:
     
         <div>
           <.live_component module={SomeComponent} id="myid" />
         </div>
     
     Components are also allowed inside Elixir's special forms, such as
     `if`, `for`, `case`, and friends.
     
         <%= for item <- items do %>
           <.live_component module={SomeComponent} id={item} />
         <% end %>
     
     However, using other module functions such as `Enum`, will not work:
     
         <%= Enum.map(items, fn item -> %>
           <.live_component module={SomeComponent} id={item} />
         <% end %>
```

### Expected behavior

No error as in live view version `0.18.4`.

**Comment by maennchen** [comment]
@josevalim The first error in the linked CI run comes from here:

https://github.com/jshmrtn/hygeia/blob/c5b9178ecbc031946a89b63124b55e372bae1d1e/lib/hygeia_web/live/visit_live/show.sface#L78

The component is used all over the project:

https://github.com/search?q=Lock+repo%3Ajshmrtn%2Fhygeia+extension%3Asface&type=Code&ref=advsearch&l=&l=

**Comment by josevalim** [comment]
I think it is a Surface bug. @msaraiva, LV v0.18.5 requires the calls to components with slots to declare all slot attributes as a list of atoms in the call metadata:

https://github.com/phoenixframework/phoenix_live_view/commit/674fd69344e8bcd710fa76440c2098e0ca8db228#diff-589d22905e415399e6ac5cacf5028ae08428fbc7d7669aedbb5b277cf98e6235R1357-R1359

This allows us to more reliably convert slots to rendered structs, because we no longer need to guess which attributes are slots. This should even be beneficial if Surface supports `:if` and `:for` in slots.

@maennchen feel free to report it downstream. :)
