### ISSUE TITLE
Cascade `phx-remove` for children elements

### ISSUE THREAD

**Issue by evaldobratti** [phoenixframework/phoenix_live_view#2391]
I’m setting up some tooltips on my live view application using  [floating ui](https://floating-ui.com/). I was able to set it up using `phx-mounted` by dispatching an event and it’s working like a charm, now I want to tear it down when elements are removed. 

I tried using `phx-remove` as the [modal example](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.JS.html#module-client-utility-commands) but it doesn't work as the entire row, where some tooltips are in, is removed and as the docs states, `phx-remove` is only called for the parent element, but this is kinda odd as `phx-mounted` works anywhere.

Would it be possible to cascade it to children elements to allow these proper teardowns on the client side?

I could set it up to work as a hook but ideally, I don't want to set individual ids for each tooltip on the page.

part of my component
```
      <span class="tooltip" 
        phx-mounted={JS.dispatch("budget:tooltip-setup")} 
        phx-remove={JS.dispatch("budget:tooltip-cleanup")} 
        {@rest}
      >
        <%= @tooltip %>
        <div class="arrow"></div>
      </span>
```

client side
```
window.addEventListener("budget:tooltip-setup", event => setupTooltip(event.target)) // works perfectly
window.addEventListener("budget:tooltip-cleanup", event => console.info('cleanup', event)) // does not print anything
``` 

If you think this feasible I can give it a shot on a PR.

**Comment by chrismccord** [comment]
phx-remove is only applied to the top-level most parent by design. Thanks!
