### ISSUE TITLE
Improve scroll restoration defaults

### ISSUE THREAD

**Issue by sevensidedmarble** [phoenixframework/phoenix_live_view#2395]
## Issue when navigating out of a liveview

Scroll position restoration behaves strangely when navigating out of a liveview (using a regular old anchor tag), and then hitting back. The position will not restore correctly.

There has been discussion about this in this PR from December 2020 to March 2022: https://github.com/phoenixframework/phoenix_live_view/pull/1256

The suggestion in that PR was to set `history.scrollRestoration` to `'auto'`. The author of that PR said it fixed their issues in the above scenario, and I tried it myself and found it did too. There were stated concerns in that PR about potential breakage in LV -> LV navigation scenarios however. I was not able to replicate these problems however.

## Needs determination
- `history.scrollRestoration` to `'auto'` break LV -> LV navigation?
- Does doing so break any other scroll behavior in the included JS files?

Another thing I noticed is that when setting `history.scrollRestoration` to `'auto'`, when hitting refresh while sitting on a LV, my scroll position properly stayed in the same place. With `history.scrollRestoration` set to `'manual'`, it jumps to the top. I think there are some other open issues talking about this very thing, but I don't think any of them put forward this particular solution.

**Comment by dvic** [comment]
Is this somehow related to my fix for another scroll issue in https://github.com/phoenixframework/phoenix_live_view/pull/2173?

**Comment by chrismccord** [comment]
Please try master which just merged #2173 and report back if the behavior is still not what you expect. Thanks!
