### ISSUE TITLE
Should optional attrs be set to nil by default?

### ISSUE THREAD

**Issue by alexcastano** [phoenixframework/phoenix_live_view#2396]
Hello,

I have a suggestion about not required attr(ibute) in a component. I expected it to be nil when it wasn't given.
Let me explain with a simple example:

```elixir
attr :hint_text, :string
def text(assigns) do
  ~H"""
  <p>Hello <.hint :if={@hint_text} text={@hint_text}/></p>
  """
end

attr :text, :string, required: true
def hint(assigns) do
  ...
end
```

Then if we call just call the component `<.text/>` we receive the following error:

```elixir
key :hint_text not found in: %{__changed__: nil}
```

I think this error could be very confusing for a newcomer. I also think that it would be very convenient to be nil by default, after all, you are defining the attribute for the component, and it can be nicely handled with a simple `:if`.

Maybe there is a major reason to don't do that. In that case, we can try to improve the error message.

Let me know what you think, and maybe I can help with a PR.

Thank you

PD: You can use `attr :hint_text, :string, default: nil`

**Comment by josevalim** [comment]
We discussed this, and perhaps even implemented it, but reverted it for reasons I can't fully remember. I think it was related to `assigns_new` and the fact nillifying everything could be expensive. `default: nil`is the way to go.

**Comment by alexcastano** [comment]
It makes sense. Thank you!
