### ISSUE TITLE
Wrapping a JS hook that emits an event within a conditional <%= if @x %> creates an infinite series of events.

### ISSUE THREAD

**Issue by davidahmed** [phoenixframework/phoenix_live_view#2399]
### Environment

* Elixir version (elixir -v): Elixir 1.14.2 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): 1.6.9
* Phoenix LiveView version (mix deps): 0.18.1
* Operating system: MacOS Monterey
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox 108.0.1
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior
If I wrap my phx-hook div in `<%= if ...%> ... <% end %>`, I get an infinite series of `qr-scanned` (see below) events.

If I don't wrap the block within the `if ... else` block, then I don't receive extra events. However, if I manually do something like `html5QrcodeScanner.clear().then(...)` in my hook, then the problem goes away. But why do I need to even resort to that if my `div` which has the hook is already destroyed? I also am not sure who is creating the stream of the events, the Js hook (I doubt), or LiveView is trying to do something in the backround.

#### LiveComponent
```elixir
defmodule MyAppWeb.StageLive do
  alias MyAppWeb.BenchmarkStage
  use(MyAppWeb, :live_view)

  def mount(_params, _session, socket) do
    socket =
      assign(socket,
        next_stage_available: false,
      )

    {:ok, socket, layout: {MyAppWeb.LayoutView, "dashboard.html"}}
  end

  def render(assigns) do
  ~H"""
  <div>
    <div class="my-4 pt-4"> 
    <!-- adding this `if` starts the trouble -->
    <%= if @next_stage_available == false do %> 
      <div id="reader" class="w-32" phx-hook="QRReader">Scan Qode </div>
    <% else %>
      <div> Code Scanned </div>
    <% end %>
   </div>
 </div>
  """
  end

  def handle_event("qr-scanned", %{"decodedText"=> %{"decodedText"=> decodedText}}, socket) do
    socket = assign(socket, next_stage_available: true)
    {:noreply, socket}
  end

end
```

#### The `phx-hook` `QRReader` 
```js
Hooks.QRReader = {
  mounted() {
    let view = this;
    console.log("QR Scanner Ready");

    let html5QrcodeScanner = new Html5QrcodeScanner(
      "reader",
      { fps: 10, qrbox: {width: 250, height: 250} },
      /* verbose= */ false);

    function onScanSuccess(decodedText, decodedResult) {
      // handle the scanned code as you like, for example:
      console.log(`Code matched = ${decodedText}`, decodedResult);
      view.pushEvent("qr-scanned", {decodedText: decodedResult});

      // I have to use the following line to get rid of the issue. BUT WHY?
      html5QrcodeScanner.clear().then(_ => { /*clear UI here*/ })
        .catch(error => {
          console.log(error);
        });
    }

    function onScanFailure(error) {
      // handle scan failure, usually better to ignore and keep scanning.
      // for example:
      console.warn(`Code scan error = ${error}`);
    }

      html5QrcodeScanner.render(onScanSuccess, onScanFailure);
  },
  update() {
    console.log("QR Coded updated"); // Doesn't get triggered. Understandable
  },
  destroyed() {
    console.log("QR Code destroyed"); // Get's triggered.
  }

}
```

### Expected behavior
After receiving the first `qr-scanned` event, there should be no more events sent by coming to my LiveViewComponent. My understanding is that everything is destroyed anyways.

**Comment by davidahmed** [comment]
The QR Code reader library in context is: https://github.com/mebjas/html5-qrcode

**Comment by 03juan** [comment]
I don't think this is a problem with LV, the scanner keeps scanning and re-runs the `onScanSuccess()` until it is told to stop.

This is happening even when the node is removed because the scanner is probably creating a reference to the node/one or more children that survives its deletion, that's just the way that the `delete` operator works. It's the responsibility of the developer to ensure all references are removed. [[1]](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/delete#description) [[2]](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Memory_Management#references)

So in this case the `if` removes the node but the scanner is still running and keeps sending events on success, until is receives a `clear()`.

So you can hard-stop in the way you're doing or, if you need to do some logic on the value sent to the LV and then decide whether to keep scanning, the simplest way would be to clear the scanner in the `destroyed()` hook.

Something like:

```javascript
Hooks.QRReader = {
  mounted() {
    let view = this

    this.scanner = new Html5QrcodeScanner("reader",
      { fps: 10, qrbox: { width: 250, height: 250 } }, false);

    function onScanSuccess(decodedText, decodedResult) {
      view.pushEvent("qr-scanned", { decodedText: decodedResult });
    }

    this.scanner.render(onScanSuccess);
  },
  destroyed() { this.scanner.clear().then((_) => { console.log("QR Code destroyed") }) }
}
```

**Comment by chrismccord** [comment]
Confirm, you need to clean up after yourself on destroyed
