### ISSUE TITLE
Layout is not applied during the initial render

### ISSUE THREAD

**Issue by nmbrone** [phoenixframework/phoenix_live_view#2401]
### Environment

* Elixir version (elixir -v): `1.14.3`
* Phoenix version (mix deps): `1.6.15`
* Phoenix LiveView version (mix deps): `0.18.7`
* Operating system: `macOS 13.1 (Ventura)`
* Browsers you attempted to reproduce this bug on (the more the merrier): `Chrome`
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: `Yes`

### Actual behavior

It looks like `0.18.7` introduces another layout-related bug. The layout (`"live.html"`) is not applied during the initial render of a live page, only after the page is mounted. `0.18.6` works as expected

### Expected behavior

The layout is applied during the initial render of a live page

**Comment by josevalim** [comment]
This has been fixed in master. Can you please give it a try?

**Comment by nmbrone** [comment]
Yes, it works in master. Thanks for the quick response.
