### ISSUE TITLE
Regression: LiveView socket disconnects on form submission

### ISSUE THREAD

**Issue by simoncocking** [phoenixframework/phoenix_live_view#2403]
### Environment

* Elixir version (elixir -v): Elixir 1.14.1, OTP25
* Phoenix version (mix deps): 1.17.0-rc.2
* Phoenix LiveView version (mix deps): 0.18.8 (regression introduced in 0.18.4)
* Operating system: MacOS, Linux
* Browsers you attempted to reproduce this bug on (the more the merrier): Safari, Brave
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### The issue

With a fresh project generated by `mix phx.new` (version 1.17.0-rc.2), and a single LiveView as follows:

```elixir
defmodule MyAppWeb.PageLive do
  use MyAppWeb, :live_view

  def render(assigns) do
    ~H"""
    <.form for={:form} action={~p"/submit"} phx-change="validate">
      <button type="submit">Submit</button>
    </.form>
    """
  end

  def handle_event("validate", _changes, socket) do
    {:noreply, socket}
  end
end
```

Clicking the `Submit` button causes the LiveView socket to disconnect rather than submit the form. Note that without the `phx-change` attribute, the form **does** submit as intended.

I believe this issue rhymes with #2394 and was likewise introduced with Phoenix LiveView 0.18.4 - this behaviour is not apparent in 0.18.3.

**Comment by chrismccord** [comment]
Fixed in 0.18.9. Thanks!
