### ISSUE TITLE
LiveView disconnects when submitting a Stripe Elements form

### ISSUE THREAD

**Issue by adamwiggall** [phoenixframework/phoenix_live_view#2405]
### Environment

* Elixir version (elixir -v): **1.14.0**
* Phoenix version (mix deps): **1.6.15**
* Phoenix LiveView version (mix deps): **0.18.4 (see note below)**
* Operating system: **MacOS, Debian**
* Browsers you attempted to reproduce this bug on (the more the merrier): **Chrome, Safari, Firefox** 
* Does the problem persist after removing "assets/node_modules" and trying again? **Yes**

### Actual behavior

We have a live view that contains a div which is populated when we fetch a payment intent from Stripe. It holds a Stripe Elements checkout form. The markup is thus:

```
<.form
  :if={@stripe_payment_intent}
  for={:intent}
  method="post"
  data-secret={@stripe_payment_intent.client_secret}
  phx-hook="InitCheckout"
  id="payment-form"
>
  <div id="payment-element"></div>
  <button id="payment_submit">
    Pay <%= @gross_amount %>
  </button>
  <div id="error-message"></div>
</.form>
```
After we have completed our preliminary data fetching a `@stripe_payment_intent` assign is populated and the form appears. The user can then complete the form and submit, Stripe takes care of the rest.

**This all worked as expected on 0.18.3**

When we upgraded to 0.18.4 the following occurred. 

Once the button is pressed we immediately see `socket: disconnect for page nav -  undefined` in the console and the resulting JS triggered when Stripe responds never occurs.

We've isolated all other changes, and can reliably trigger the error on 0.18.4 (and we've also run 0.18.10 which exhibits the same problem).

I note that there has been some remedial work around disconnections in 0.18.6, 0.18.7 & 0.18.10, and I'm wondering if this is a case that has perhaps been missed?

Thanks in advance.

**Comment by chrismccord** [comment]
Can you share your `InitCheckout` code? I assume you `preventDefault` in there? Thanks!

**Comment by adamwiggall** [comment]
Here you go Sir.

```
let stripePublishableKey = document
  .querySelector("meta[name='stripe-publishable-key']")
  .getAttribute("content");

const stripe = Stripe(stripePublishableKey);

export const InitCheckout = {
  mounted() {
    const successCallback = (paymentIntent) => {
      this.pushEvent("payment-success", paymentIntent);
    };
    init(this.el, successCallback);
  },
};

const init = (form, successCallback) => {
  const options = {
    clientSecret: form.dataset.secret,
    appearance: {
      theme: "stripe",
    },
  };

  const elements = stripe.elements(options);

  // Create and mount the Payment Element
  const paymentElement = elements.create("payment");
  paymentElement.mount("#payment-element");

  // Handle real-time validation errors from the card Element.
  paymentElement.on("change", function (event) {
    var displayError = document.getElementById("error-message");
    if (event.error) {
      displayError.textContent = event.error.message;
    } else {
      displayError.textContent = "";
    }
  });

  form.addEventListener("submit", async (event) => {
    event.preventDefault();
    const submitButton = document.getElementById("payment_submit");
    const currentButtonText = submitButton.innerHTML;
    submitButton.innerHTML = "Processing...";
    submitButton.disabled = true;

    stripe
      .confirmPayment({
        elements,
        redirect: "if_required",
      })
      .then(function (result) {
        submitButton.disabled = false;
        submitButton.innerHTML = currentButtonText;
        if (result.error) {
          const messageContainer = document.querySelector("#error-message");
          messageContainer.textContent = result.error.message;
        } else {
          if (result.paymentIntent.status === "succeeded") {
            successCallback(result.paymentIntent);
          }
        }
      });
  });
};

```

**Comment by chrismccord** [comment]
Fixed and released in 0.18.11. Thanks!

**Comment by adamwiggall** [comment]
Thank you!

**Comment by jeroenbourgois** [comment]
Maybe a bit related @chrismccord but we had a similar issue when opening a link using a simple `<a href>` tag, using a `target="blank"` attribute (I know, links in a tab, don't get me started.... the client insisted and I have given up fighting over this :P). 

Using `blank` as value resulted in the same behaviour where the socket got disconnected, but when using `_blank` as a value it worked. Obviously the value should have been `_blank` from the get to, but this kind off caught me by surprise.
