### ISSUE TITLE
inputs_for discussion

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix_live_view#2410]
Hi @LostKobrakai, I have reverted #2404 for now. I should have reviewed more carefully but:

1. The `field={f, field}` is only in new apps and we don't use this pattern in LV yet
2. We should inline the implementation of both inputs_for and hidden_inputs_for in this module
3. We should update the references to `inputs_for` in this source code
4. I am not sure if it should be called `inputs_for` given it is no longer `form_for`. Although there benefits with sticking to the name

Thoughts?

_Originally posted by @josevalim in https://github.com/phoenixframework/phoenix_live_view/issues/2404#issuecomment-1399093086_

**Comment by LostKobrakai** [comment]
1. Happy to move them to be separate inputs. 
2. Seems like I misread the current `<.form />` implementation. I though it used `Phoenix.HTML.Form.form_for` and therefore didn't question this more, but it's `Phoenix.HTML.FormData.to_form`, so this makes sense.
3. Good point. I certainly missed updating them.
4. Given I don't really have a better name for it I'd opt for keeping it, but I'd be fine with any name.

**Comment by josevalim** [comment]
@LostKobrakai if you want to send a PR with 2 and 3, please feel free to go ahead, but I don't have a definitive answer for 1 and 4 yet. :)
