### ISSUE TITLE
Live redirect is performing a full reload for live routes within a forwarded router within the same live_session

### ISSUE THREAD

**Issue by kenblasko** [phoenixframework/phoenix_live_view#2418]
### Environment

* Elixir version: **1.14.2**
* Phoenix version: **1.7.0-rc.2**
* Phoenix LiveView version: **0.18.3**
* Operating system: **macOS 13.0.1**

### Actual behavior

We have a multi router setup.  Our “base” router forwards requests prefixed with “/admin” to an admin router.  When trying to link between the two admin routes within the same live_session, the live redirect fails with an error of “unauthorized” due to what seems to be the router not aware of the “forwarded” path… 

Here is a basic example:

**router.ex**

![router](https://user-images.githubusercontent.com/6202405/215157835-74b1829c-2a91-4c0c-84bd-5990d88403f0.png)

**admin_router.ex**

![admin_router](https://user-images.githubusercontent.com/6202405/215157856-d0e74d81-219b-400a-8117-9edca8e62215.png)

When trying to link between the two admin routes, the live redirect performs a full page reload.  Here are some link examples with verified routes:

![nav](https://user-images.githubusercontent.com/6202405/215157881-8a000505-acb0-4f4b-91a9-a0c7389ae6f4.png)

I would only expect a full reload going between the root path “/” and the admin paths.  If we remove “/admin” from the path the live redirects work fine between the admin routes, but then we get a compiler warning and the URL doesn’t account for the “admin” prefix.   If we use the path helper, we fix the warning but we have the same issue with the URL.

![nav_path_helper](https://user-images.githubusercontent.com/6202405/215157904-861e0eef-da05-4618-994e-65e7cfed0421.png)

At that point, neither scenario will allow the root route in the base router to match unless I hard reload the page.  Given the forwarding setup, I would expect live navigation to work between the two admin links then full refresh when going to the root route in the other live_session.

![route_info](https://user-images.githubusercontent.com/6202405/215157943-3eb8b827-4e7d-423c-add6-3d48b71bcbcf.png)

Moving the admin routes under a scope in the main router works, but we’d prefer to keep them separate if possible.  Is there a way to get this to work while forwarding?

Here’s a repo for reproduction: https://github.com/kenblasko/blog_live

### Expected behavior

Live redirects within the same live_session should still work when using the forward macro to a different router.

**Comment by josevalim** [comment]
Correct, it does not work with forward. Can you please open up a PR to at least update the docs to mention this limitation? Thank you!

**Comment by chrismccord** [comment]
live session is tied to the router, and it even invalidates existing sessions if the router itself changes as we can't guarantee a previously valid session is still reachable. Please submit a docs PR if you have time. Thanks!
