### ISSUE TITLE
Configurable HEEx file name

### ISSUE THREAD

**Issue by taronull** [phoenixframework/phoenix_live_view#2420]
Currently, HEEx file name must conform `./<last_part_of_module_name>.html.heex` to be rendered. This doesn't work well for module names like `Home.Live`. All modules will look for `./live.html.heex`.

Users need to be able to embed template by choice.

This is a workaround from the community.

```elixir
embed_templates "*"

def render(assigns) do
  extra = assigns_to_attributes(assigns)
  assigns = assign(assigns, :extra, extra)

  ~H"""
  <.foo @{extra} />
  """
end
```

**Comment by chrismccord** [comment]
You an either use more unique module naming or you can define another module and embed_templates there. We do not accept feature requests on the issue tracker. Thanks!

**Comment by taronull** [comment]
All working module names are unique by nature. It's the convention of soldering technicality in the end, like `FooLiveTest`, creeping into the hardcoded part of the framework.

**Comment by chrismccord** [comment]
Right, I'm saying if the inflection rules are a problem for you, you can either change the final module alias to something more unique in the directory/namespace, or you can use the `embed_templates` feature delegate to whatever name of a template file you want. Thanks!
