### ISSUE TITLE
Gettext Locale Change Not Updating LiveView Template

### ISSUE THREAD

**Issue by allenwyma** [phoenixframework/phoenix_live_view#2422]
### Environment

* Elixir version (elixir -v): 1.14.2
* Phoenix version (mix deps):  1.6.15
* Phoenix LiveView version (mix deps): 0.18.10
* Operating system: Mac OS 13.2
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox Developer Version
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior
Using patch or a Phoenix LiveView event to change the locale for LiveView doesn't re-render content in new locale.

### Expected behavior
Text should be updated from Gettext when locale is changed.

**Comment by josevalim** [comment]
Correct. Gettext is part of the process dictionary, so you need to do a <.live navigate ...> instead of patching the page.

**Comment by allenwyma** [comment]
Because it's part of process dictionary, so the templates cannot be updated?

**Comment by josevalim** [comment]
The process dictionary is not computed as part of Phoenix.LiveView knowing when the page changed and has to be rendered. We could add a way to opt-in to this functionality but right now a `navigate` will do!

**Comment by allenwyma** [comment]
I'd be interested in that feature: Shall I update the title of the issue? I have a multi-step form that is on 1 route and changing the language would be great if can do this from one of the middle steps.

**Comment by josevalim** [comment]
Meanwhile I have updated the docs to avoid confusion. :)
