### ISSUE TITLE
Compilation warning when accessing a variable in template that shadows another outside template

### ISSUE THREAD

**Issue by jfpedroza** [phoenixframework/phoenix_live_view#2432]
### Environment

* Elixir version (elixir -v): 1.14.3
* Phoenix version (mix deps): 1.6.15
* Phoenix LiveView version (mix deps): 0.18.11
* Operating system: Endeavour OS
* Browsers you attempted to reproduce this bug on (the more the merrier): N/A
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: N/A

### Actual behavior

Define a function component like so:

```elixir
  def my_component(assigns) do
    foo = :bar
    ...

    ~H"""
        <%= case @some_assign do %>
          <% foo -> %>
            Some use of <%= foo %>
        <% end %>
    """
  end
```

When compiling, Elixir will emit a warning like so:

```
warning: you are accessing the variable "foo" inside a LiveView template.

Using variables in HEEx templates are discouraged as they disable change tracking. You are only allowed to access variables defined by Elixir control-flow structures, such as if/case/for, or those defined by the special attributes :let/:if/:for. If you are shadowing a variable defined outside of the template using a
control-flow structure, you must choose a unique variable name within the template.
```

### Expected behavior

No warning should be emitted, since the `foo` accessed inside the template is actually defined by the case.

Also happens if you do `if foo = @some_assign do`.

**Comment by chrismccord** [comment]
Note from the warning:
> If you are shadowing a variable defined outside of the template using a
control-flow structure, you must choose a unique variable name within the template.

Thanks!
