### ISSUE TITLE
DOM update breaks `dialog[phx-update=ignore]`

### ISSUE THREAD

**Issue by taronull** [phoenixframework/phoenix_live_view#2433]
### Environment

* Elixir version (elixir -v): 1.14.3
* Phoenix version (mix deps): 1.7.0-rc2
* Phoenix LiveView version (mix deps): 0.18.11
* Operating system: macOS Monterey 12.6.3 (21G419)
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, Safari, and FireFox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

Any DOM update from LiveSocket that precedes a dialog[phx-update=ignore], will break it.

| Before update | After update |
| :---: | :---: |
| Modal is set with `HTMLDialogElement.showModal` method. The setup should remain the same after LiveSocket update because it is `[phx-update=ignore]`. | DOM update that comes before the `dialog` element broke the modal setup. And `dialog` is appended to its markup position.
| ![Screen Shot 2023-02-08 at 20 14 13](https://user-images.githubusercontent.com/118569516/217689556-635b745a-81da-4d3b-b003-572efa3940cc.png) | ![Screen Shot 2023-02-08 at 20 14 21](https://user-images.githubusercontent.com/118569516/217689559-8af64f80-865d-4654-b03f-44334278ebf4.png) |

```elixir
def mount(_params, _session, socket) do
  {:ok, assign(socket, :status, false)}
end

def render(assigns) do
  ~H"""
  <%= if @status do %>
    <p>Updated!</p>
  <% end %>

  <!-- Or, any DOM update here will break the modal. -->

  <button onclick="dialog.showModal()">Open Modal</button>

  <dialog id="dialog" phx-update="ignore">
    <form phx-submit="update">
      <button>Update</button>
    </form>
  </dialog>
  """
end

def handle_event("update", _params, socket) do
  {:noreply, assign(socket, :status, true)}
end
```

### Expected behavior

The modal remains after any update from Phoenix LiveSocket

**Comment by chrismccord** [comment]
Please see my answer here. Thanks!
https://github.com/phoenixframework/phoenix_live_view/issues/2349#issuecomment-1349616302
