### ISSUE TITLE
Compilation error when creating components with more than 2 attributes 

### ISSUE THREAD

**Issue by viniciusmuller** [phoenixframework/phoenix_live_view#2440]
### Environment

* Elixir version (elixir -v):
  ```sh
  Erlang/OTP 25 [erts-13.1.4] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]
  Elixir 1.14.3 (compiled with Erlang/OTP 25)
  ```
* Phoenix version (mix deps): N/A
* Phoenix LiveView version (mix deps): >0.18.11
* Operating system: NixOS 23.05
* Browsers you attempted to reproduce this bug on (the more the merrier): N/A 
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: N/A

### Actual behavior

When trying to define a component with more than a single attr, the program fails to compile with the following message:
```
** (ArgumentError) you attempted to apply a function named :name on {:doc, nil}. If you are using Kernel.apply/3, make sure the module is an atom. If you are using the dot syntax, such as map.field or module.function(), make sure the left side of the dot is an atom or a map
    :erlang.apply({:doc, nil}, :name, [])
    (phoenix_live_view 0.18.12) lib/phoenix_component/declarative.ex:385: anonymous fn/2 in Phoenix.Component.Declarative.validate_attr_type!/7
    (elixir 1.13.1) lib/enum.ex:1113: anonymous fn/3 in Enum.find/3
    (elixir 1.13.1) lib/enum.ex:4475: Enumerable.List.reduce/3
    (elixir 1.13.1) lib/enum.ex:1112: Enum.find/3
    (phoenix_live_view 0.18.12) lib/phoenix_component/declarative.ex:385: Phoenix.Component.Declarative.validate_attr_type!/7
    (phoenix_live_view 0.18.12) lib/phoenix_component/declarative.ex:345: Phoenix.Component.Declarative.__attr__!/6
    reproduce.exs:9: (module)
```

Snippet to reproduce the issue:

```ex
Mix.install([
  {:phoenix_live_view, "~> 0.18.12"}
])

defmodule MyComponents do
  import Phoenix.Component

  attr :name, :string
  attr :last_name, :string
  def hello(assigns), do: ~H"<%= "#{@name} #{@last_name}" %>"
end
```

### Expected behavior

Being able to define a component with more than two attributes without any issues

### Investigation

It seems that the `__attrs__` module attribute is not returning a list, even though `accumulate: true` should have been set to it.
If I use live_view master as a `:path` dependency and inspect `{module, key, attrs}` in [declarative.ex](https://github.com/phoenixframework/phoenix_live_view/blob/1d98c04cc3f8d6ca705f49dacba150a0b5c4507d/lib/phoenix_component/declarative.ex#L383), I can see the following output before the compilation error when compiling the simple example:

```
{MyComponents, :__attrs__, []}
{MyComponents, :__attrs__,
 %{
   doc: nil,
   line: 4,
   name: :name,
   opts: [],
   required: false,
   slot: nil,
   type: :string
 }}
```

**Comment by chrismccord** [comment]
You need to `use Phoenix.Component`. I will see about improving the error in this case. Thanks!

**Comment by viniciusmuller** [comment]
Hey @chrismccord, I'm willing to implement such a change, do you have any pointers on the cases and when should this error be thrown?

**Comment by chrismccord** [comment]
I took care of it :) Thank you!
