### ISSUE TITLE
no route path warnings after upgrade to 0.18.12 and phx 1.7 RC

### ISSUE THREAD

**Issue by woylie** [phoenixframework/phoenix_live_view#2444]
### Environment

* Elixir version (elixir -v):
  Erlang/OTP 25 [erts-13.0.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]
  Elixir 1.14.0 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): 1.7.0-rc.2
* Phoenix LiveView version (mix deps): 0.18.12 and 0.18.13
* Operating system: macOS 13.1
* Browsers you attempted to reproduce this bug on (the more the merrier): not applicable
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

After upgrading `phoenix_live_view` from 0.18.11 to either 0.18.12 or 0.18.13, `no route path for CoachWeb.Router matches ...` warnings are emitted for every p sigil used in my application. The warnings disappear again after downgrading to versions < 0.18.12. I tried force compiling and deleting the `_build` folder to no avail.

All routes work fine in the browser despite the warnings. The warnings also appear during tests, yet all tests still pass.

### Expected behavior

The application compiles without those warnings.

**Comment by josevalim** [comment]
Please use Phoenix 1.7.0 from main branch. rc3 should be out shortly with a fix.

**Comment by josevalim** [comment]
rc3 is out!
