### ISSUE TITLE
No match of right hand side value

### ISSUE THREAD

**Issue by dsignr** [phoenixframework/phoenix_live_view#246]
### Environment

* Elixir version (elixir -v): Elixir 1.8.1
* Phoenix version (mix deps): 1.4.8 c72dc3ad
* NodeJS version (node -v): v11.12.0
* NPM version (npm -v): 6.9.0
* Operating system: Mac OS X High Sierra

### Actual behavior

After running `mix phx.server` on terminal, I'm spammed with 100s of these messages:
```elixir
[error] GenServer #PID<0.1238.0> terminating
** (MatchError) no match of right hand side value: %{"session" => "SFMyNTY.g3QAAAACZAAEZGF0YXQAAAAFZAACaWRtAAAADHBoeC15OWVXQ285MWQACnBhcmVudF9waWRkAANuaWxkAAZyb3V0ZXJkABVFbGl4aXIuS2FsaVdlYi5Sb3V0ZXJkAAdzZXNzaW9udAAAAAFkAAtwYXRoX3BhcmFtc3QAAAAAZAAEdmlld2QAJkVsaXhpci5LYWxpV2ViLkxpdmUuQ29udGVudC5QYWdlLkluZGV4ZAAGc2lnbmVkbgYAPzO9XGsB.E3UFbP2c3Ek3vsbSaUoJDg75wtNbxoD29WN11-OCnyo", "static" => nil}
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:323: Phoenix.LiveView.Channel.verified_mount/9
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:mount, Phoenix.LiveView.Channel}
State: {%{"session" => "SFMyNTY.g3QAAAACZAAEZGF0YXQAAAAFZAACaWRtAAAADHBoeC15OWVXQ285MWQACnBhcmVudF9waWRkAANuaWxkAAZyb3V0ZXJkABVFbGl4aXIuS2FsaVdlYi5Sb3V0ZXJkAAdzZXNzaW9udAAAAAFkAAtwYXRoX3BhcmFtc3QAAAAAZAAEdmlld2QAJkVsaXhpci5LYWxpV2ViLkxpdmUuQ29udGVudC5QYWdlLkluZGV4ZAAGc2lnbmVkbgYAPzO9XGsB.E3UFbP2c3Ek3vsbSaUoJDg75wtNbxoD29WN11-OCnyo", "static" => nil}, {#PID<0.1235.0>, #Reference<0.342465988.2695626754.135630>}, %Phoenix.Socket{assigns: %{}, channel: Phoenix.LiveView.Channel, channel_pid: nil, endpoint: KaliWeb.Endpoint, handler: Phoenix.LiveView.Socket, id: nil, join_ref: "37", joined: false, private: %{}, pubsub_server: Kali.PubSub, ref: nil, serializer: Phoenix.Socket.V2.JSONSerializer, topic: "lv:phx-y9eWCo91", transport: :websocket, transport_pid: #PID<0.1235.0>}}
[error] an exception was raised:
    ** (MatchError) no match of right hand side value: %{"session" => "SFMyNTY.g3QAAAACZAAEZGF0YXQAAAAFZAACaWRtAAAADHBoeC15OWVXQ285MWQACnBhcmVudF9waWRkAANuaWxkAAZyb3V0ZXJkABVFbGl4aXIuS2FsaVdlYi5Sb3V0ZXJkAAdzZXNzaW9udAAAAAFkAAtwYXRoX3BhcmFtc3QAAAAAZAAEdmlld2QAJkVsaXhpci5LYWxpV2ViLkxpdmUuQ29udGVudC5QYWdlLkluZGV4ZAAGc2lnbmVkbgYAPzO9XGsB.E3UFbP2c3Ek3vsbSaUoJDg75wtNbxoD29WN11-OCnyo", "static" => nil}
        (phoenix_live_view) lib/phoenix_live_view/channel.ex:323: Phoenix.LiveView.Channel.verified_mount/9
        (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
        (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3

```
I suspect one of the most recent commits is causing this.

### Expected behavior
There shouldn't be any socket/livereload related errors.

Things I've tried:
- `mix deps.clean --all`
- Removing `mix.lock` and re-running `mix deps.get` again
- Deleting the repo and re-fetching again (to see if it was caused by a file system error)

### Solution
In my `mix.exs`:
```{:phoenix_live_view, github: "phoenixframework/phoenix_live_view", ref: "b94f0d3a1299fcc0fb3e6ea1bdd298e9c4d1571c"}```

Temporary solution was to downgrade to this particular commit from March. I chose this particular one because this is the date I started my project. The whole thing started because I cleaned my deps and re-installed them again, which seems to have fetched a newer version of live view.

Thank you.

**Comment by dukalskis** [comment]
So I fixed, problem with JS.

I had incorrect NPM dep: 
```
"phoenix_live_view": "^0.1.0-dev"
```
changed to:
```
"phoenix_live_view": "file:../deps/phoenix_live_view"
```

and then:
```
npm install --force phoenix_live_view
```
or:
```
yarn
```

**Comment by dsignr** [comment]
> So I fixed, problem with JS.
> 
> I had incorrect NPM dep:
> 
> ```
> "phoenix_live_view": "^0.1.0-dev"
> ```
> 
> changed to:
> 
> ```
> "phoenix_live_view": "file:../deps/phoenix_live_view"
> ```
> 
> and then:
> 
> ```
> npm install --force phoenix_live_view
> ```
> 
> or:
> 
> ```
> yarn
> ```

Will try this and let you know buddy. Thanks for sharing.

**Comment by josevalim** [comment]
will be tackled with #251.

**Comment by kwando** [comment]
I had the same issue, "solved" it by deleting the `node_modules` directory and install nodejs dependencies again with `yarn`.
