### ISSUE TITLE
input/1 behavior different from guides description

### ISSUE THREAD

**Issue by malgeon** [phoenixframework/phoenix_live_view#2463]
### Environment

* Elixir version (elixir -v): 1.14.3 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): 1.7.0-rc.2
* Phoenix LiveView version (mix deps): 0.18.14
* Operating system: macOS 13.1
* Browsers you attempted to reproduce this bug on (the more the merrier): 
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

When I follow the guides and try to use input/1, I get a key error.

<.input type="text" field={@form[:username]} label="Title" /> 

I found that replacing this with the following works.

<.input type="text" field={{@form, :username}} label="Title" /> 

Is this what you intended?

**Comment by josevalim** [comment]
The guides have been updated to 1.7.0-rc.3, released yesterday. You can run `mix phx.new` with .rc.3 and copy the new core components file. :)
