### ISSUE TITLE
key :variable_name not found in

### ISSUE THREAD

**Issue by ruannawe** [phoenixframework/phoenix_live_view#2467]
### Environment

* Elixir version (elixir -v): 1.14.3
* Phoenix version (mix deps): 1.6.16
* Phoenix LiveView version (mix deps): 0.17.14
* Operating system: MacOS
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome 
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

When I go to URL [http://localhost:4000/counter](http://localhost:4000/counter), I'm receiving the following error

```
key :variable_name not found in: %{__changed__: %{}, flash: %{}, live_action: nil, socket: #Phoenix.LiveView.Socket<id: "phx-F0S9iNzftAgImQMC", endpoint: CounterWeb.Endpoint, view: CounterWeb.CounterLive, parent_pid: nil, root_pid: nil, router: CounterWeb.Router, assigns: #Phoenix.LiveView.Socket.AssignsNotInSocket<>, transport_pid: nil, ...>}
``` 

<img width="1536" alt="Screenshot 2023-02-17 at 18 57 48" src="https://user-images.githubusercontent.com/9044734/219813067-abb8ef9e-73d4-4e61-8cc3-15816cc54731.png">

My repository is available at https://github.com/ruannawe/live_view_counter, it's a test repository with just a tiny live view example.
I guaranteed that I followed all configuration steps present inside live view documentation before opening the issue. 

### Expected behavior

Show the page without errors with the follow HTML.

```html
<h1>Count: 0</h1>
<button>+</button>
<button>-</button>
```

**Comment by josevalim** [comment]
The mount function expects three arguments, your definition has two. Put `@impl true` on top of callbacks and you get a warning in case of argument mismatch :)
