### ISSUE TITLE
form ignoring form data

### ISSUE THREAD

**Issue by AHBruns** [phoenixframework/phoenix_live_view#2469]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 25 [erts-13.1.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit] [dtrace]
Elixir 1.14.2 (compiled with Erlang/OTP 25)
```
* Phoenix version (mix deps): `1.7.0-rc.3`
* Phoenix LiveView version (mix deps): `0.18.15`
* Operating system: `OSX`
* Browsers you attempted to reproduce this bug on (the more the merrier): `chrome`
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

I have the following live component:

```elixir
defmodule FancyTableWeb.UserLive.TableComponent do
  use FancyTableWeb, :live_component

  @impl true
  def render(assigns) do
    ~H"""
    <div>
      <.simple_form for={@name_filter_form} phx-target={@myself} phx-change="filter">
        <.input field={@name_filter_form[:name_filter]} />
      </.simple_form>
    </div>
    """
  end

  @impl true
  def handle_event("filter", %{"name_filter" => name_filter}, socket) do
    {:noreply, assign(socket, :name_filter_form, to_form(%{name_filter: name_filter}))}
  end

  @impl true
  def mount(socket) do
    {:ok, assign(socket, :name_filter_form, to_form(%{name_filter: "some value"})}
  end
end
```

My input is empty when I render this live component, but there are no errors and it still emits events as I would expect.

### Expected behavior

I would expect my input to have an initial value of "some value" because that's what I provided in my form data, but it doesn't. What's odd is that it does emit events and it does update its state as I type so long as it's uncontrolled. If I set its state in response to, for example, an update it reverts to being empty.

**Comment by josevalim** [comment]
When you give it a map, it expects string keys, because it considers it to be the form parameters and not the form data. I will improve the docs.
