### ISSUE TITLE
allow union types for attributes (`attr :class :string | :list`)

### ISSUE THREAD

**Issue by tcoopman** [phoenixframework/phoenix_live_view#2472]
It would be nice if attributes accepted union types, so that the class attribute could for example take both `string` and `list`.

For example, the core_component button could be typed like this, because now it generates a warning when you pass in a list, while it works fine with lists as well.

The current way to fix is to use the `any` attribute.

**Comment by josevalim** [comment]
Yes, the types could be richer but the amount of things we can validate at compile time is limited too, so we kept the types closer to what can be checked.

**Comment by tcoopman** [comment]
Fair enough.

Would you accept a PR that changes the class attribute on the button to `any`?

**Comment by josevalim** [comment]
@tcoopman either that or we introduce a `:class` type. It is not my call to make though. :)
