### ISSUE TITLE
Allow creation of "fake" upload entries

### ISSUE THREAD

**Issue by sezaru** [phoenixframework/phoenix_live_view#2473]
## Problem

To explain the problem here, I will use a scenario where I'm creating an online store and I can add and edit products with images.

Right now, LiveView gives great support for upload of files/images when adding new products. It will check for the max number of entries, I can easily change the order of the images by changing the `entries` array (because for products, the order of the images will be shown on the page is important) and I have a nice preview of it before I need to really upload everything.

But, IMO the current implementation lacks a little bit when we are talking about editing a product depending on their requirements:

1) Need to keep a max number of images.
  When editing I will need to do that by hand since now I have 2 different types of images, images that are already stored in my system (images that were added when I create the product) and new images that I want to upload.

    LiveView `UploadConfig` will only be aware of the new images since they are the ones inside the `entries` array so the `max_entries` will always be wrong.
  
2) Hard to have a custom order of images.
  When creating a new product, changing the order of images was trivial, I just needed to change it inside the `entries` array.
  
    Now, when editing, that is way harder since now I have images that are not inside the `entries` array. So the best approach I can think of is a separate list with the correct order which maps to each image, be it an already stored image or a new one.

## Suggested Solution

I think that a good solution for that issue is to allow the user to manually add "fake" `UploadEntry`.

Basically, these entries can be a different struct or just new fields inside `UploadEntry` which will indicate that they are not a real upload.

For example, if I had a `FakeUploadEntry` which had just a field called `url`, I could add it to the `entries` list with the real URL for the stored image, and LiveView `live_file_input` component would understand that, and preview the image using that `url`.

The advantage here is that I can place my already stored images inside the `entries` array, meaning that I can keep my `max_entries` field as-is since it will still work just fine, I can also keep logic to remove an upload very similar since it will be the same event, but I will just differentiate via pattern match and handle the removal in a different way, and especially I would be able to reorder the images (using a library to do drag-and-drop for example) the same way I did in the new product page.

In other words, I would be able to keep the logic almost the same for both the new product page and the edit product page.

This may sound like a very specific corner case, but at least IMO this will be something that every one that is creating an online store of something similar will have to do in one way or another.

**Comment by josevalim** [comment]
I think this would be conflating two different aspects: the goal of file uploads is only to track uploads, but you are using it for sorting and also generally tracking existing images. For example, what happens when you want to edit a product? Will you create several fake upload entries, just so you can re-use the same structure?

My suggestion is for you to invert things: keep @upload_entries to keep only the entries in upload and, as each upload starts, you add it to your own `@entries` list, which may also contain already uploaded entries. If an upload is cancelled, you remove from your own `@entries` list and so on. It is pretty much the solution you described, but without pushing unrelated concerns to the framework. :)

**Comment by sezaru** [comment]
@josevalim That's what I'm doing right now.

With that, I can display all the entries, even the already uploaded ones in the same list, but this still has problems that I'm not sure what is the best approach to solve them.

One is regarding `max_entries`, I can handle that myself, sure, but I still need to set a `max_entries` during `allow_upload` otherwise I can't select multiple files when adding new images. I did a workaround by setting the `allow_upload` `max_entries` to 999, but this seems like a hack to me... Maybe if there were a `:infinity` option or a way to set that I allow the selection of multiple files without needing to set `max_entres` it would be better.

The other issue I see right now is the progress bar during upload. Since I will be storing the entries in a new key in my state called `@entries` the progress bar will not be updated since that value will only be updated for the entries inside the `@uploads` assign. I don't have a workaround for this now. Any suggestion?
