### ISSUE TITLE
Select input error class persists when errors are absent

### ISSUE THREAD

**Issue by jounimakela** [phoenixframework/phoenix_live_view#2476]
### Environment

* Elixir version (elixir -v)
  * Erlang/OTP 25 [erts-13.1.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]
  * Elixir 1.14.1 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): 1.7.0-rc.3
* Phoenix LiveView version (mix deps): 0.18.15, master
* Operating system: Void Linux, MacOS
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox v110.0, Safari v16.1, qutebrowser v2.5.2 (based on Chromium 87.0.4280.144)
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

I want to style `select`-input with error styles on invalid input.

I've created a simple test case to reproduce the issue:

* A User schema with a name (`string`) and a country (`Ecto.Enum`)
* Name and country are required and country must be either "Finland" or "Other" 
* Country is a select input
* Select input has error styles in the same way its done to other inputs:
```diff
       <select
         id={@id}
         name={@name}
-        class="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-zinc-500 focus:border-zinc-500 sm:text-sm"
+        class={[
+          "mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-zinc-500 focus:border-zinc-500 sm:text-sm",
+          "phx-no-feedback:border-zinc-300 phx-no-feedback:focus:border-zinc-400 phx-no-feedback:focus:ring-zinc-800/5",
+          @errors != [] && "border-rose-400 focus:border-rose-400 focus:ring-rose-400/10"
+        ]}
         multiple={@multiple}
         {@rest}
       >
```

If name is filled and the user selects a country, select input gets the error style, even when no errors are present. Errors disappear when name input changes.

If country is selected first, it works as expected; neither input gets the error style as both are valid.

Repository of the demonstrable problem: https://github.com/jounimakela/liveview-select-input-error

Demonstration:

![output](https://user-images.githubusercontent.com/9807635/220642595-2021c08e-bc79-4c81-8357-acf37748a5c2.gif)

### Expected behavior

If the value of select input is valid, it should not get error styles.

**Comment by SteffenDE** [comment]
I'm seeing the same error. It seems like the `<select>` element is not properly patched. Not only the `class` attribute is affected, I tried working around with something like this:
```
<%= inspect(@errors != [] %>
<select
   id={@id}
   name={@name}
   data-has-error={@errors != []}
   class="data-[has-error]:border-error ..."
>
...
```
And while the inspect shows `false` when resetting the error, the `data-has-error` attribute stays there.

**Comment by SteffenDE** [comment]
Probably related to https://github.com/phoenixframework/phoenix_live_view/issues/1313

**Comment by SteffenDE** [comment]
I just tested this using on main. Fixed via https://github.com/phoenixframework/phoenix_live_view/pull/2659.

**Comment by josevalim** [comment]
Thank you @SteffenDE !
