### ISSUE TITLE
Logout form appears on click on Logout link

### ISSUE THREAD

**Issue by SeverineB** [phoenixframework/phoenix_live_view#2479]
### Environment

* Elixir version (elixir -v): 
```
Erlang/OTP 25 [erts-13.1.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.14.3 (compiled with Erlang/OTP 25)
```
* Phoenix version (mix deps):
```
phoenix 1.7.0-rc.3 (Hex package) (mix)
locked at 1.7.0-rc.3 (phoenix) ae651c30
```
* Phoenix LiveView version (mix deps):
```
phoenix_live_view 0.18.15 (Hex package) (mix)
locked at 0.18.15 (phoenix_live_view) 888dd8ea
```
* Operating system: Arch Linux - Endeavouros
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox and Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: No `assets/node_modules` folder

### Actual behavior

This issue is maybe related to the [issue 2311](https://github.com/phoenixframework/phoenix_live_view/issues/2311)
The logout form with an input "submit" (here in french, "Envoyer") appears at the bottom of the page after clicking on Logout link.
![image](https://user-images.githubusercontent.com/64303691/220632425-113ce5b6-e895-464c-915e-a08aaeca5257.png)

### Expected behavior
The logout form would not appear.

**Comment by chrismccord** [comment]
I can't recreate this. Did you customize the templates after you ran `phx.gen.auth`? The only way the logout text appears is if you're rendering it. If you can provide a minimal reproduction I would be able to take a closer look, but I don't believe this is an issue on our side. Thanks!

**Comment by SeverineB** [comment]
Thanks for your answer !
I tried to install a new app test, the setup is the same than the one described above.
I let the repo in public so you can access if needed. 
[gitlab repo](https://gitlab.com/public-projects4393708/app-test)
I dockerize the app but it does not matter for the logout problem.

I generate the authentication with `mix phx.gen.auth Accounts User users` and choose the Liveview one, then i had to edit the `user_login_live.ex` and `user_registration_live.ex` because the key `name` of the component `input` could not be created
so instead of
`<.input field={@form[:email]} type="email" label="Email" required />`
i changed the field as below
`<.input field={{ @form, :email }} type="email" label="Email" required />`

And then i tried to login / logout (I have set a network limit in Firefox to have time to do the screenshot) and the logout text appears as below :

![image](https://user-images.githubusercontent.com/64303691/220778951-3a23044e-9189-494f-8c21-0cbfb282e98d.png)

I don't know if it's related to my setup or my install 😐

I also noticed that the flash message "Attempting to reconnect" appears each time i reload the login or register page (I read the issue about it and check in` deps/phoenix_live_view/assets/js/phoenix_live_view/live_socket.js` but it's ok
 ```
redirect(to, flash){
    this.unload()
    Browser.redirect(to, flash)
  }
  )
```
