### ISSUE TITLE
child LiveView click event sent to parent LiveView

### ISSUE THREAD

**Issue by KristerV** [phoenixframework/phoenix_live_view#2483]
### Environment

      {:phoenix, "~> 1.7.0-rc.3", override: true},
      {:phoenix_html, "~> 3.3"},
      {:phoenix_live_view, "~> 0.18.14"},

* Elixir version (elixir -v): Elixir 1.14.3 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): 1.7 rc3 (checked in deps dir)
* Phoenix LiveView version (mix deps): 0.18.16 (checked in deps dir), also tested with 0.18.11.
* Operating system: Arch Linux
* Browsers you attempted to reproduce this bug on (the more the merrier): firefox, chromium, mix test
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: n/a

### Actual behavior

- I have a LiveView inside of a LiveView using `live_render()` (called ParentLive and ChildLive).
- Inside ChildLive is a button with `phx-click`.
- Clicking on the button in the browser fires the ChildLive `handle_event`.
- Running `mix test` that also clicks the same button fires the ParentLive `handle_event`.

I made a demo project from scratch, [here's the commit](https://github.com/KristerV/test_child_liveview_event/commit/008f28724dc4927c3677320e1252b3f88a1bf8c9) that diff's the important bits.

also made a video to save your time.

https://user-images.githubusercontent.com/2750622/220995988-211babd6-8cee-4b05-94d4-6fb6bda077df.mp4

### Expected behavior

Clicking a button will fire `handle_event` in ChildLive in both browser and test.

### Sanity check

Googled and searched issues as usual, nothing turned up. So either I'm doing something obviously wrong, this is this an anti-pattern or a bug introduced recently.

I'm pretty sure my usecase is legit: child LiveView is complex and needs to receive PubSub messages.

The problem exists also in LV 0.18.11, older versions started giving unrelated errors.

**Comment by mrdotb** [comment]
Hello,

Since you render a liveview in another liveview the lv in your test is the parent lv
See https://hexdocs.pm/phoenix_live_view/Phoenix.LiveViewTest.html#live_children/1
```
defmodule TestChildLiveviewEventWeb.ChildEventTest do
  use TestChildLiveviewEventWeb.ConnCase
  import Phoenix.LiveViewTest

  test "click event should be handled by child component", %{conn: conn} do
    {:ok, parent_lv, _html} = live(conn, "/")
    [child_lv] = live_children(parent_lv)

    child_lv
    |> element("button")
    |> render_click()

    # message in console CLICKED child
  end
end
```

**Comment by KristerV** [comment]
yeah that fixed it.

maybe this issue is documentation enough, but i kind of feel like there should be another section just under [Testing LiveComponents](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveViewTest.html#module-testing-livecomponents).

what do you think, should i make a PR?

**Comment by mrdotb** [comment]
Actually [https://hexdocs.pm/phoenix_live_view/Phoenix.LiveViewTest.html#live_isolated/3](live_isolated) is a better fit to test your exemple it take the same option as live_render. Maybe you can just edit the doc of live_isolated and say that it's a good fit to test the live_render(liveview).

**Comment by miguelcoba** [comment]
Thanks @mrdotb, I was getting crazy about this and couldn't understand why in the browser it worked but in the test it didn't!

**Comment by josevalim** [comment]
PR to the docs are always welcome!
