### ISSUE TITLE
`TypeError: Cannot read properties of null` coming from live_socket.js and dom.js

### ISSUE THREAD

**Issue by jdav-dev** [phoenixframework/phoenix_live_view#2485]
### Environment

* Elixir version (elixir -v): Elixir 1.14.0 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): 1.6.14
* Phoenix LiveView version (mix deps): 0.18.2
* Operating system: Alpine Linux 3.15.4
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

We're getting `TypeError: Cannot read properties of null` errors from a couple different places.  Unfortunately, the stack traces I have are minified, but I'll point out where the errors are coming from:

`Cannot read properties of null (reading 'isConnected')` is coming from [here in live_socket.js](https://github.com/phoenixframework/phoenix_live_view/blob/v0.18.2/assets/js/phoenix_live_view/live_socket.js#L665).

`Cannot read properties of null (reading 'phxPrivate')` is coming from [the various private functions in dom.js](https://github.com/phoenixframework/phoenix_live_view/blob/v0.18.2/assets/js/phoenix_live_view/dom.js#L117-L139).

### Expected behavior

Check for `null` before reading `isConnected` or `phxPrivate`.

**Comment by chrismccord** [comment]
rather than checking internally we need to see where these calls are happening higher up in the stack. It's likely they shouldn't be happening but I would need a reproduction to figure out what the issue is. Thanks!
