### ISSUE TITLE
Question/feature request: How can I access uploaded files using JavaScript?

### ISSUE THREAD

**Issue by caspg** [phoenixframework/phoenix_live_view#2498]
Looks like LiveView JS is removing uploaded files from `input.files`. I need to access them to read the width, height, and coordinates.

I found a way to read it from [phx private](https://github.com/phoenixframework/phoenix_live_view/blob/main/assets/js/phoenix_live_view/dom.js#L147) object but it doesn't seem right using "private" functions.

Is there any recommended way to do so? If not, maybe I could create a PR with some official way of accessing upload files on the client?

**Comment by josevalim** [comment]
Please use the [ElixirForum](http://www.elixirforum.com) for questions/help/feedback, where a wider community will be able to help you. Thank you! Personally I would track it yourself by adding my own JS handlers.
