### ISSUE TITLE
Improve the loading strategy from bfcache

### ISSUE THREAD

**Issue by sevensidedmarble** [phoenixframework/phoenix_live_view#2501]
Apologies if this is the wrong forum but I feel like this discussion can be most helpful on GH.

I would really like to improve the loading story of LiveView around the bfcache (see https://web.dev/bfcache/ if you're not familiar).

By default websocket pages cannot be cached, but luckily the `pagehide` event allows you to cleanup websocket connections, so you can do stuff like:

```javascript
liveSocket.connect()

window.addEventListener('pagehide', () => {
  liveSocket.disconnect()
})

window.addEventListener('pageshow', (e) => {
  if (e.persisted) {
    console.log('loaded from bfcache')
    liveSocket.connect()
  }
})
```

This works surprisingly well at cleaning up the connection, at least on chrome, but when navigating backwards the double mount still occurs which defeats any benefit of using the bfcache.

If there was a way to instruct LV that the next page load should *only* remount the socket and not do the first render, I think we could improve the loading from bfcache.

I'm not sure this would be a great default, but for people who want to do it I think it'd be a nice option to have.

Note that I have not spelunked super deeply into LVs JS to figure out the exact interactions going on here yet.

**Comment by SteffenDE** [comment]
So this is quite an interesting topic. In my opinion LiveView should be able to handle this by itself, but currently LV contains some code that forcefully refreshes the page when it detects a restore from bfcache:
https://github.com/phoenixframework/phoenix_live_view/blob/a31c57e08af0c7a9c0ecffc101f709abc782890a/assets/js/phoenix_live_view/live_socket.js#L520

The corresponding commit is here: https://github.com/phoenixframework/phoenix_live_view/commit/75b0b5cfde9826e015927475ab51ad52efc8f6f1

Maybe the problem this commit addresses could be handled differently, without breaking the benefits of the bfcache.

**Comment by chrismccord** [comment]
The page will have stale tokens, which are required for us to "upgrade" the dead page to a LV, so this is not something we can easily do. Bfcache should be less common as using live navigation uses push state and skips any bfcache. So the refresh fallback is only for cases where a tab is backgrounded and killed, then restored, which is not happening constantly and should restore the page for the user in a fast manner in any case. Thanks!

**Comment by srcrip** [comment]
Can we keep this discussion going? Surely there are solutions to this problem if we're willing to use more JavaScript. I'm particularly concerned about the case of leaving the page via an external link and coming back.

Why can't we check the state of the LV state in JS against some last copy in local storage to determine if it's safe to reconnect? Doesn't this kind of thing kinda exist already in other places where LV gracefully reconnects? @chrismccord
