### ISSUE TITLE
Docs https://hexdocs.pm/phoenix_live_view/Phoenix.Component.html#link/1-examples

### ISSUE THREAD

**Issue by ghenry** [phoenixframework/phoenix_live_view#2514]
Hi all,

I'm looking at this:

https://hexdocs.pm/phoenix_live_view/Phoenix.Component.html#link/1-examples

Are these the correct examples:

```
<.link navigate={Routes.page_path(@socket, :index)} class="underline">home</.link>

<.link navigate={Routes.live_path(@socket, MyLive, dir: :asc)} replace={false}>
  Sort By Price
</.link>

<.link patch={Routes.page_path(@socket, :index, :details)}>view details</.link>
```

as I get `function Routes.page_path/3 is undefined (module Routes is not available)`

I'm on:

```
      {:phoenix, "~> 1.7.1"},
      {:phoenix_live_view, "~> 0.18.17"},
```

Thanks.

**Comment by ghenry** [comment]
I think these should all be like:

` <.link patch={~p"/posts/#{post}/edit"}>Edit</.link>`

as per https://elixirforum.com/t/phoenix-1-7-0-final-is-out/54113 ?

**Comment by josevalim** [comment]
Yes, that’s the new style. A PR is welcome!

**Comment by ghenry** [comment]
Will get this done and a few other things I've spotted as I hadn't updated phx_new to 1.7.1 

Was still on rc-0.

**Comment by ghenry** [comment]
Was looking at this PR in my fork, but actually a bit confused as to what these would look like with `~p`:

  ```heex
  <.link navigate={Routes.page_path(@socket, :index)} class="underline">home</.link>
  ```

Could potentially be?

  ```heex
  <.link navigate={~p"/"} class="underline">home</.link>
  ```

  ```heex
  <.link navigate={Routes.live_path(@socket, MyLive, dir: :asc)} replace={false}>
    Sort By Price
  </.link>
  ```

and (not sure which anchor to use):

  ```heex
  <.link navigate={~p"/?#[dir: "asc"]} class="underline">home</.link>
  ```

same for below, not sure.

  ```heex
  <.link patch={Routes.page_path(@socket, :index, :details)}>view details</.link>

**Comment by josevalim** [comment]
It doesn't really matter I think, it can be anything. My suggestions: `~p"/"`, `~p"/?sort=asc"`, and `~p"/details"`. :)
