### ISSUE TITLE
.inputs_for not working

### ISSUE THREAD

**Issue by gabrielmancini** [phoenixframework/phoenix_live_view#2526]
### Environment

* Elixir version (elixir -v): Elixir 1.14.3 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): phoenix 1.7.1 (Hex package) (mix)
* Phoenix LiveView version (mix deps): phoenix_live_view 0.18.16 (Hex package) (mix)
* Operating system: linux ubuntu 22
* Browsers you attempted to reproduce this bug on (the more the merrier):  chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior
not show the inner fields
```
      <.form
        :let={f}
        for={@form}
        id="group-form"
        phx-target={@myself}
        phx-change="validate"
        phx-submit="save"
      >
        <.input field={@form[:name]} type="text" label="Name" />
        [
        <.inputs_for :let={fu} field={f[:users]} >
          <.input field={fu[:email]} type="text" label="Email" />
        </.inputs_for>
        ][
        <.inputs_for :let={fp} field={@form[:pages]}>
          <.input field={fp[:name]} type="text" label="pages" />
        </.inputs_for>
        ]

          <.button phx-disable-with="Saving...">Save Group</.button>
      </.form>
```
not work in simple_form too
https://github.com/phoenixframework/phoenix_live_view/blob/main/lib/phoenix_component.ex#L2266 here its return an empty array

### Expected behavior
must show inner fields

**Comment by josevalim** [comment]
Can you please provide a small app or a single file LV app that reproduces the error? Thank you.

**Comment by gabrielmancini** [comment]
oh i, found

its on my cast many to many schema

not working
```
    group
    |> cast(attrs, [:name])
    |> validate_required([:name])
    |> put_assoc(:users, Map.get(attrs, :users, []))
    |> put_assoc(:pages, Map.get(attrs, :pages, []))
```

then 
```
    group
    |> cast(attrs, [:name])
    |> validate_required([:name])
    |> put_assoc(:users, Map.get(attrs, :users))
    |> put_assoc(:pages, Map.get(attrs, :pages))
```
works!
