### ISSUE TITLE
Extra form value when submitting form with button

### ISSUE THREAD

**Issue by sanntt** [phoenixframework/phoenix_live_view#2532]
### Environment

* Elixir version (elixir -v): `Elixir 1.14.3 (compiled with Erlang/OTP 25)`
* Phoenix version (mix deps): `1.7.1`
* Phoenix LiveView version (mix deps): `0.18.17`
* Operating system: `MacOS Monterey 12.6.2`
* Browsers you attempted to reproduce this bug on (the more the merrier): `Chrome, Firefox, Safari`
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: `Yes`

### Actual behavior
In Phoenix LiveView version 0.18.17 (but not in 0.18.16 or any previous one), when submitting a form, an extra field is submitted for the button. This comes directly from the browser, so my theory is that it's something from the JS, and after seeing the recent changes, I think it's related to the new submitter, though I'm not proficient on JS to find it myself XD. 
It looks like when submitting, it's generating a form field for every element in the form, wether it's an expected input or not. I'm not sure this is the expected behaviour, but at least it didn't happen in the previous minor version. This happens both when the button has the attributes `name` and `value`, but also when it does not have them.

This is the HTML that is generating the situation:
```HTML
<form phx-submit="send">
  <input name="field" />
  <button name="button" value="test" type="submit">Send</button>
</form>
```

Here is a screenshot of the extra empty field, both in the browser and in the server:
<img width="509" alt="image" src="https://user-images.githubusercontent.com/1985181/225308289-7e72d958-1c66-4419-9ab9-36d2575594ab.png">

<img width="553" alt="image" src="https://user-images.githubusercontent.com/1985181/225308337-d070a784-6cf9-4e2e-9f86-12349bb59aa4.png">

Here is a gist with the code: https://gist.github.com/sanntt/fa1559d369ce22807f51a364f3a4437d

### Expected behavior
With version 0.18.16 (which is the one I pinned to), no form field was sent for the submit button, as can be seen in the following image:
<img width="437" alt="image" src="https://user-images.githubusercontent.com/1985181/225309348-c7decc49-684b-454f-a8bf-dfc96eebf4ab.png">

Using the same gist as above, but changing the JS version of live view to 0.18.16, the button is not sent in the form.

**Comment by josevalim** [comment]
This is intentional and (it was) a commonly requested feature. Is this change affecting you negatively?

**Comment by sanntt** [comment]
Thanks for your answer @josevalim.
Our application did have an unintended problem, but it may be because of lack of knowledge of a better way.

We have an internal application (not public to the open world but just for company employees), where we receive the input from the form. This is a bulk edit, so we are just iterating over every value received from the form, like so:
```Elixir
  defp parse_values(params) do
    Enum.reduce(params, %{}, fn {season, value}, acc ->
      Map.put(acc, String.downcase(season), String.to_integer(value) / 100)
    end)
  end
```
But now, because we have a new value, we can't do it this way. We have to either Enum.reject empty values, or wrap the actual values in a struct of some sort. Which is fine, it can be done, though again I'm not sure what the correct way is, but the concern is that it was a minor change, and we noticed when in production, as also the tests didn't notify us (again, we might be doing them wrong if this is expected)

**Comment by josevalim** [comment]
You can delete the button in this case but I assume your button does not have a name and it is simply an empty string, right? So we should probably not submit for buttons without names and that will reduce the breakage.
