### ISSUE TITLE
Suggestion: add an `:unless` directive

### ISSUE THREAD

**Issue by andyl** [phoenixframework/phoenix_live_view#2535]
LiveView recently added the [:if directive](https://blog.appsignal.com/2022/10/11/phoenix-liveview-018-new-special-html-attributes.html), a great feature which helps to streamline `HEEX` code.

Suggesion: also add an `:unless` directive.  This would be a small convenience that many would find handy.  Note that `unless` is part of [Elixir itself](https://elixir-lang.org/getting-started/case-cond-and-if.html#if-and-unless)!

**Comment by josevalim** [comment]
Hi @andyl! There are no plans for now to keep the number of additional attributes minimal, but we may revisit it in the future. Thanks!
