### ISSUE TITLE
live view process terminates when downloading a file

### ISSUE THREAD

**Issue by ykato123** [phoenixframework/phoenix_live_view#2549]
### Environment

* Elixir version (elixir -v): 1.13.4
* Phoenix version (mix deps): 1.6.16
* Phoenix LiveView version (mix deps): 0.18.15
* Operating system: Windows
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

With my sample code below, when I click the download link, the live view process terminates with the reason `{:shutdown, :left}`.
And a dead page is left after the download and you cannot use anymore live view functions like `phx-click`s until you refresh.

```elixir
defmodule MyAppWeb.TestLive do
  use MyAppWeb, :live_view
  def terminate(reason, socket) do
    IO.inspect(reason)
  end

  def render(assigns) do
    ~H"""
    <div>
      <a href={Routes.static_path(@socket, "/sample_file")}>a tag to download a file</a>
    </div>
    """
  end
end
```

I tried making the link tag with button tag using `Phoenix.HTML.Link.button/2`, but the situation was similar.

### Expected behavior
Because the page stays after the download, the live view process should also stay alive.
As far as I understand, it used to work before phoenix_live_view 0.18.3.

**Comment by chrismccord** [comment]
add `target="_blank"` to your anchor. Thanks!
