### ISSUE TITLE
PushState replaces the content of the first LiveView in the DOM instead of the one that updated

### ISSUE THREAD

**Issue by wrren** [phoenixframework/phoenix_live_view#255]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 21 [erts-10.2.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.8.0 (compiled with Erlang/OTP 21)
```
* Phoenix version (mix deps):
```
* phoenix 1.4.8 (Hex package) (mix)
   locked at 1.4.8 (phoenix) c72dc3ad
```
* NodeJS version (node -v):
```
v10.12.0
```
* NPM version (npm -v):
```
6.9.0
```
* Operating system:
```
macOS Mojave, v10.14.3
```

### Actual behavior

When using the new `pushState` functions in an application that renders multiple LiveViews are part of its layout, updates resulting from `live_redirect` or `live_link` triggers cause the incorrect LiveView to have its content updated.

https://github.com/wrren/phoenix_live_view_issues/tree/issue/push_state

### Expected behavior

When a LiveView updates as a result of `live_redirect` or `live_link`, other LiveViews should be unaffected.

**Comment by albertosramires** [comment]
Having the same issue, @wrren 's branch solved the issue for me. 👍

**Comment by chrismccord** [comment]
Currently only the root live view can issue live redirects. We can explore alternatives later, but the tldr; is the root controls the mount url and we must ensure that URLs remain reachable so we don't allow pushing bad urls that sharing links or refreshes would fail to work, such as is if a child pushed a URL over its parent. Thanks!
