### ISSUE TITLE
After html.heex uses script to introduce vue.js, how to use ":" on the label

### ISSUE THREAD

**Issue by duanzhichao** [phoenixframework/phoenix_live_view#2553]
### Environment

* Elixir version (elixir -v): 1.14
* Phoenix version (mix deps): 1.7.2
* Phoenix LiveView version (mix deps):0.18.16
* Operating system: macOS 13.1
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: no

### Html code
```
<script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>
<html>
<div :id='1'></div>
</html>
```
### error
```
(Phoenix.LiveView.Tokenizer.ParseError) lib/hello_web/controllers/page_html/home.html.heex:2:6: unsupported attribute ":id" in tags
```

**Comment by josevalim** [comment]
The `:` is also used by LiveView, so you need to use something like `v-bind:id="1"` and similar. :)

**Comment by duanzhichao** [comment]
thanks 💯
