### ISSUE TITLE
Only call LiveUploader.untrackFile after the entry is consumed

### ISSUE THREAD

**Issue by sezaru** [phoenixframework/phoenix_live_view#2556]
~~Right now, `LiveUploader`is not exported, meaning it is only available for phoenix liveview JS code.~~

~~At the same time, the current `LiveImgPreview` hook is insufficient for scenarios where you want to keep the `blob` image generated by `URL.createObjectURL` after the original `live_img_preview` component was removed since it will always call `URL.revokeObjectURL` during its destruction.~~

~~If, for example, someone wants to use auto_upload and then do something else with the images before actually submitting the form (like showing it in another component that allows the user to reorder the images) the current implementation will not work since even if I use a hook to fetch that `blob` URL from `live_img_preview`, it will still be an invalid URL if the original `live_img_preview` component is removed before that and as a consequence `destroyed` is called inside the `LiveImgPreview` hook invalidating that URL.~~

~~As a generic solution for that, exporting `LiveUploader` will allow anyone to implement their own version of `LiveImgPreview` that will, for example, not call `URL.revokeObjectURL` and leave that call for another hook used when submitting the form.~~

Looking a little bit more at how things work internally, maybe just exposing LiveUploader is not enough or the best approach.

Maybe a better approach would be to call `LiveUploader.untrackFile` only when the file is actually consumed and not right after the upload is done? That way anyone can just simply return `:postpone` from the consume function and still have the reference to the file available in `LiveUploader` so they can simply create a new `live_img_preview` in some other place with the same entry and the hook would be able to fetch the URL from `LiveUploader` just fine.

**Comment by chrismccord** [comment]
I'ts not clear exactly what you are asking for here. Please start a discussion on the elixir forums and we can pick up the convo there. Thank you!
