### ISSUE TITLE
(KeyError) key :count not found in: %{__changed__: %{},

### ISSUE THREAD

**Issue by manuelmdexcorp** [phoenixframework/phoenix_live_view#2557]
I am a new programmer and I tried not to report this, however, I can't get this code to work. Is there a setup issue? I followed this tutorial https://elixircasts.io/pattern-matching-in-elixir.

Phoenix: I upgrade from 1.6 to 1.7
Elixir 1.14.2 (compiled with Erlang/OTP 25)

Erlang/OTP 25 [erts-13.1.1] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns] [dtrace]

Mix 1.14.2 (compiled with Erlang/OTP 25)

 I see the error is with the @count. If I remove the @count the error does not show.

Code:
defmodule MdexcorpWeb.PageLive do
  use MdexcorpWeb, :live_view
 def mount(_session, socket) do
   socket = assign(socket, :count, 0)
   {:ok, socket}
 end

 def render (assigns) do
  ~H"""
  \<h1> Count: <%= @count %> </h1>   
    <button>+</button>
    <button>-</button>
 """
  end
end

Error: 
[info] GET /
[debug] Processing with MdexcorpWeb.PageLive.home/2
  Parameters: %{}
  Pipelines: [:browser]
[info] Sent 500 in 114ms
[error] #PID<0.633.0> running Phoenix.Endpoint.SyncCodeReloadPlug (connection #PID<0.632.0>, stream id 1) terminated
Server: localhost:4000 (http)
Request: GET /
** (exit) an exception was raised:
    ** (KeyError) key :count not found in: %{__changed__: %{}, flash: %{}, live_action: :home, socket: #Phoenix.LiveView.Socket<id: "phx-F0_CSR2j5YwHfQWI", endpoint: MdexcorpWeb.Endpoint, view: MdexcorpWeb.PageLive, parent_pid: nil, root_pid: nil, router: MdexcorpWeb.Router, assigns: #Phoenix.LiveView.Socket.AssignsNotInSocket<>, transport_pid: nil, ...>}
        (mdexcorp 0.1.0) lib/mdexcorp_web/live/page_live.ex:12: anonymous fn/2 in MdexcorpWeb.PageLive.render/1
        (phoenix_live_view 0.18.18) lib/phoenix_live_view/diff.ex:398: Phoenix.LiveView.Diff.traverse/7
        (phoenix_live_view 0.18.18) lib/phoenix_live_view/diff.ex:544: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
        (elixir 1.14.2) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
        (phoenix_live_view 0.18.18) lib/phoenix_live_view/diff.ex:396: Phoenix.LiveView.Diff.traverse/7
        (phoenix_live_view 0.18.18) lib/phoenix_live_view/diff.ex:139: Phoenix.LiveView.Diff.render/3
        (phoenix_live_view 0.18.18) lib/phoenix_live_view/static.ex:252: Phoenix.LiveView.Static.to_rendered_content_tag/4
        (phoenix_live_view 0.18.18) lib/phoenix_live_view/static.ex:135: Phoenix.LiveView.Static.render/3
        (phoenix_live_view 0.18.18) lib/phoenix_live_view/controller.ex:39: Phoenix.LiveView.Controller.live_render/3
        (phoenix 1.7.2) lib/phoenix/router.ex:430: Phoenix.Router.__call__/5
        (mdexcorp 0.1.0) lib/mdexcorp_web/endpoint.ex:1: MdexcorpWeb.Endpoint.plug_builder_call/2
        (mdexcorp 0.1.0) lib/plug/debugger.ex:136: MdexcorpWeb.Endpoint."call (overridable 3)"/2
        (mdexcorp 0.1.0) lib/mdexcorp_web/endpoint.ex:1: MdexcorpWeb.Endpoint.call/2
        (phoenix 1.7.2) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4
        (plug_cowboy 2.6.1) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2
        (cowboy 2.9.0) /Users/Open/projects/myelixir/mdexcorp/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.9.0) /Users/Open/projects/myelixir/mdexcorp/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.9.0) /Users/Open/projects/myelixir/mdexcorp/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3

**Comment by josevalim** [comment]
The callback is `mount/1`, with a single argument, and not two. Add `@impl true` on top of the function and Elixir will warn in case of such mismatches.

**Comment by manuelmdexcorp** [comment]
Thank you Jose!

**Comment by manuelmdexcorp** [comment]
Thank you again, Jose! Using the @impl true and the mount/3 cleared the error.
defmodule MdexcorpWeb.PageLive do
  use MdexcorpWeb, :live_view
  @impl true
  def mount(_params, _session, socket) do
    socket = assign(socket, :count, 0)
    {:ok, socket}
  end
end
