### ISSUE TITLE
Feature request: re-assigning stream

### ISSUE THREAD

**Issue by nallwhy** [phoenixframework/phoenix_live_view#2562]
I expected that the existing stream to be replaced with new items when stream is assigned again, but it isn’t.
It crashes with `** (ArgumentError) existing hook :messages(stream name) already attached on :after_render.`

I think supporting re-assigning streams would help with the reuse of LiveComponent.

```elixir
  @impl true
  def update(assigns, socket) do
    ...

    socket =
      socket
      |> assign(assigns)
      |> assign_messages(new_channel_name)

    {:ok, socket}
  end

  @impl true
  def render(assigns) do
    ~H"""
    <div>
      <.h2># <%= @channel_name %></.h2>
      <p>Your ID: <%= @session_id %></p>
      <div id="messages" class="h-96 overflow-y-auto" phx-update="stream" phx-hook="ChatMessages">
        <div :for={{message_id, message} <- @streams.messages} id={message_id} class="mt-4">
          <p>User id: <%= message.user_id %></p>
          <p><%= message.created_at %></p>
          <p><%= message.body %></p>
        </div>
      </div>
      ...
    </div>
    """
  end

  defp assign_messages(socket, channel_name) do
    {:ok, messages} = Chat.list_messages(channel_name)

    socket
    |> stream(:messages, messages) # <-- here
    ...
  end
```

You can test it on the page below, by changing channel.

page: https://json.media/playgrounds/chat
code: https://github.com/nallwhy/json_corp/blob/chat/apps/json_corp_web/lib/json_corp_web/live/playgrounds/chat_live/channel.ex

**Comment by nallwhy** [comment]
Oh, it's on the roadmap.

https://elixirforum.com/t/phoenix-liveview-stream-api-for-inserting-many/54202/8

**Comment by manast** [comment]
@nallwhy since the issue is closed I wonder, has it been released? if so, how can it be used?

**Comment by nallwhy** [comment]
@manast Maybe https://github.com/phoenixframework/phoenix_live_view/pull/2577/files
