### ISSUE TITLE
Uncaught type error when recovering a form with only hidden inputs

### ISSUE THREAD

**Issue by andreasknoepfle** [phoenixframework/phoenix_live_view#2569]
Hello 👋 

### Environment

* Elixir version (elixir -v): Elixir 1.14.1
* Phoenix version (mix deps):  1.6.16
* Phoenix LiveView version (mix deps):  0.18.18
* Operating system: MacOS + alpine Linux
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome/Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

We have a multistep wizard, which is implemented with live view and that uses the `phx-auto-recover` [feature](https://hexdocs.pm/phoenix_live_view/0.7.0/Phoenix.LiveView.html#module-form-recovery-following-crashes-or-disconnects). All works well, except on the last page of the wizard, which is a confirmation page with just hidden inputs (the inputs from the previous steps) that crashes when it is being auto-recovered:

```
view.js:1052 Uncaught TypeError: Cannot read properties of undefined (reading 'name')
    at view.js:1052:73
    at live_socket.js:434:33
    at LiveSocket.owner (live_socket.js:430:15)
    at LiveSocket.withinOwners (live_socket.js:434:10)
    at View.pushFormRecovery (view.js:1046:21)
    at view.js:265:16
    at Array.forEach (<anonymous>)
    at view.js:264:15
    at View.applyDiff (view.js:241:5)
    at View.onJoin (view.js:256:10)
```

The reason for it is that it seems to be implemented through a `change` event, which [searches for the first non-hidden input ](https://github.com/phoenixframework/phoenix_live_view/blob/51a48e5740e408d620ac0f06823cf940e9ebe5d8/assets/js/phoenix_live_view/view.js#L1051-L1053) on the page, to be used as [input target](https://github.com/phoenixframework/phoenix_live_view/blob/51a48e5740e408d620ac0f06823cf940e9ebe5d8/assets/js/phoenix_live_view/view.js#L1056).  
Unfortunately, since it is just the summary page, we have no input that could be the target and therefore we get a crash. 

### Expected behavior

Auto-recovery also works without any input elements and the change event still comes in as normal change event.

### Workaround

My current workaround is just adding an non-related input element somewhere on the page that won't hurt:

```
<input name="summary" style="display: none" value="" />
```

Cheers,
Andi

**Comment by nshafer** [comment]
I hit this problem as well, and the workaround worked for me for now (Thanks!)
