### ISSUE TITLE
:if does not work in HTML comments

### ISSUE THREAD

**Issue by Awlexus** [phoenixframework/phoenix_live_view#2571]
I came across an error in my tests, because of a HTML comment with like the following. When `@some_struct` is nil this will fail, because it tried to access the `:name` field
```html
<!--
<p :if={@some_struct}><%= @some_struct.name %></p>
-->
```
### Environment

* Elixir version (elixir -v): Elixir 1.14.3 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): phoenix 1.7.2 (Hex package) (mix)
* Phoenix LiveView version (mix deps): phoenix_live_view 0.18.18 (Hex package) (mix)
* Operating system: OSX 12.6
* Browsers you attempted to reproduce this bug on (the more the merrier): 
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:

### Actual behavior
The `p`-tag is not rendered, and the body of the p-tag is not executed.

### Expected behavior
The following error is thrown
```
** (KeyError) key :name not found in: nil. If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
```

Edit: Please close if this is expected behaviour

**Comment by josevalim** [comment]
It is expected behavior because the interpolation always happens inside comments. Use <%!— instead. :)

**Comment by josevalim** [comment]
Thanks to @feliperenan for doing all the work in figuring it out it was not a bug. :)
