### ISSUE TITLE
live_file_input accessibility

### ISSUE THREAD

**Issue by sevensidedmarble** [phoenixframework/phoenix_live_view#2574]
Hello,

Sorry if this is explained somewhere else but I think there are some issues with `live_file_input` and a11y at present. `live_file_input` sets its own id, so there's no way to explicitly pass one and to use to tie a label to the input with the `for` attribute.

You can use implicit labels but putting the `live_file_input` inside a `label` tag, but I don't think it's an acceptable solution to have that be the only feasible way to do it. There should be some solution to using explicit labels too. I guess `live_file_input` needs the id to be unique, but couldn't we just have the option of supplying it ourselves if we ensure it's unique?

**Comment by mcrumm** [comment]
The `live_file_input` `id` is the [UploadConfig](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.UploadConfig.html#t:t/0) `ref`.

For example, if you allow an upload called `:anything`:

```elixir
@impl true
def mount(_params, _session, socket) do
  {:ok,
   socket
   |> allow_upload(:anything, accept: :any, max_entries: 5)}
end
```

...then you can render a label for the input like the following:

```heex
<label for={@uploads.anything.ref}>
  Any Files (up to <%= @uploads.anything.max_entries %>)
</label>

<.live_file_input upload={@uploads.anything} />
```

**Comment by sevensidedmarble** [comment]
Gotcha, that helps a lot thanks. I do think the docs probably should say something about that though. I mean I'm sure they point it out in some sense but I had a hard time figuring that out.
