### ISSUE TITLE
LiveviewTest render_submit behaves differently if form is in parent liveview or child live_component

### ISSUE THREAD

**Issue by danturn** [phoenixframework/phoenix_live_view#2579]
### Environment

* Elixir version (elixir -v): 1.14.0
* Phoenix version (mix deps): 1.7.2
* Phoenix LiveView version (mix deps): 0.18.18
* Operating system: MacOs Ventura 13.1
* Browsers you attempted to reproduce this bug on (the more the merrier): n/a
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

if i have a form submit event handler that does a push_patch in a parent liveview, when submitting the form in a test like this:
```
  test "can assert on update from parent syncronously", %{conn: conn} do      
    {:ok, view, _html} = live(conn, ~p|/|)                                    
                                                                              
    view                                                                      
    |> element("#parent-form")                                                
    |> render_submit()                                                        
  end   
```
the handle_params function is called and completes before the test exits

however, if i have the same event handler in a child component and initiate the push_patch from the child, the same test (with the form in the component rather than the parent) exits before the handle_params function returns

```
  test "cannot assert on update from child syncronously", %{conn: conn} do    
    {:ok, view, _html} = live(conn, ~p|/|)                                    
                                                                              
    view                                                                      
    |> element("#child-form")                                                 
    |> render_submit()                                                        
  end     
```

in my case, i have db queries in handle_params and end up with db errors:

```
13:01:16.743 pid=<0.432.0> [error] Postgrex.Protocol (#PID<0.432.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.497.0> exited
```
after the test ends

### Expected behavior
render_submit should behave the same in both instances?

**Comment by danturn** [comment]
I've pushed the repo if it helps

https://github.com/danturn/liveview-async-issue

**Comment by chrismccord** [comment]
You can await the navigation with an `assert_patch` call. In the context of a LC, it sends a message to the parent to navigate, so you need to await this event being sent. Thanks!
