### ISSUE TITLE
Form errors not highlighting input properly.

### ISSUE THREAD

**Issue by benwilson512** [phoenixframework/phoenix_live_view#2587]
### Environment

* Elixir version (elixir -v): 1.14.3
```
 mix deps|grep phoenix
* phoenix 1.7.2 (Hex package) (mix)
  locked at 1.7.2 (phoenix) 1ebca94b
* phoenix_ecto 4.4.0 (Hex package) (mix)
  locked at 4.4.0 (phoenix_ecto) 09864e55
* phoenix_html 3.3.1 (Hex package) (mix)
  locked at 3.3.1 (phoenix_html) bed1906e
* phoenix_live_dashboard 0.7.2 (Hex package) (mix)
  locked at 0.7.2 (phoenix_live_dashboard) 0e5fdf06
* phoenix_live_reload 1.4.1 (Hex package) (mix)
  locked at 1.4.1 (phoenix_live_reload) 9bffb834
* phoenix_live_view 0.18.18 (Hex package) (mix)
  locked at 0.18.18 (phoenix_live_view) a5810d04
* phoenix_pubsub 2.1.1 (Hex package) (mix)
  locked at 2.1.1 (phoenix_pubsub) 81367c6d
* phoenix_template 1.0.1 (Hex package) (mix)
  locked at 1.0.1 (phoenix_template) 157dc078
```

* Operating system: OS X
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

I made a project:

```
mix phx.new form_fun
mix phx.gen.live Accounts User user name:string email:string
mix setup
mix phx.server
```

https://github.com/benwilson512/bug_example

Go to

http://localhost:4000/users/new

Enter text into name, then delete the text.

<img width="695" alt="image" src="https://user-images.githubusercontent.com/247817/231870626-01eaeba9-a934-4901-be87-fa7f2f44fc74.png">

The label appears properly, but the highlight text that seems like it ought to be there is not.

### Expected behavior

https://github.com/benwilson512/bug_example/blob/main/lib/form_fun_web/components/core_components.ex#L350

This line seems to say that if there are errors, and if we aren't in "no feedback" mode, then the border would be `rose`. If I remove this line:

https://github.com/benwilson512/bug_example/blob/main/lib/form_fun_web/components/core_components.ex#L349

Then things work:

<img width="676" alt="image" src="https://user-images.githubusercontent.com/247817/231871354-9a77fb4b-1b04-43f9-8d54-8cc92404dc88.png">

But I don't know enough about tailwind, CSS, or the phx feedback system to tell if that's the right answer or not.

P.S. Finally getting to use heex / component oriented features in a new project, pretty good experience so far, thanks!

**Comment by chrismccord** [comment]
Thanks for the detailed report! Fixed in https://github.com/phoenixframework/phoenix/commit/21cf47df1a1beba97ae4828dfc8528f4e63660d2

**Comment by benwilson512** [comment]
Thanks for the speedy fix!

**Comment by benwilson512** [comment]
Perhaps a dumb question, but what is the semantic difference between these lines:

```
          "phx-no-feedback:border-zinc-300 phx-no-feedback:focus:border-zinc-400",
          @errors == [] && "border-zinc-300 focus:border-zinc-400",
```

Because when I load the page and before any validation has happened I already have the `phx-no-feedback:border-zinc-300 phx-no-feedback:focus:border-zinc-400` classes applied, so what does adding the `border-zinc-300 focus:border-zinc-400` classes actually do? I don't visually see any difference.

**Comment by chrismccord** [comment]
we need the "regular" border and focus styling applied for the case that the element has been interacted with *and is valid*. Otherwise it losing its styling since the phx-no-feedback is a special case where we want to hide the feedback, and once the element is interacted with those classes are removed. So we need both in this case.

**Comment by benwilson512** [comment]
>  and once the element is interacted with those classes are removed

When you say removed, are you saying I shouldn't see them on the element? I am seeing:

<img width="672" alt="image" src="https://user-images.githubusercontent.com/247817/231875448-1fa47438-61a6-416b-95be-5ba51bfeeda8.png">

<img width="563" alt="image" src="https://user-images.githubusercontent.com/247817/231875507-a1c7d31d-e65c-4156-b59b-3eca8a9aba59.png">

I have given the input `123` and then moved to the next input so it has been interacted with, and it is valid, but those no feedback classes are still there.

**Comment by chrismccord** [comment]
Ah I see the confusion. So we add the class to the `phx-feedback-for` elements (the parent div of the input). The way the tailwind plugin for `phx-no-feeback` works is it applies the classes if either the current element *or the parent* have the `phx-no-feedback` class. So in this case we are apply the error styles whenever the parent `phx-feedback-for` div has the the class. Makes sense?
