### ISSUE TITLE
Memory usage from initial stream is not released

### ISSUE THREAD

**Issue by aaronrenner** [phoenixframework/phoenix_live_view#2592]
### Environment

* Elixir version (elixir -v): 1.14.3
* Phoenix version (mix deps): 1.7.2
* Phoenix LiveView version (mix deps): 0.18.18
* Operating system: Pop! OS 22.04
* Browsers you attempted to reproduce this bug on (the more the merrier): 
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:

### Actual behavior

I've put together an example app that demonstrates differing memory usage patterns using liveview streams here: https://github.com/aaronrenner/liveview_streams. This project has LiveDashboard installed so you should be able to view memory usage of the websocket processes here: http://localhost:4000/dev/dashboard/processes?limit=50&search=cowboy&sort_by=memory&sort_dir=desc

First, when rendering a stream of 3000 items in the mount callback, the process uses 5.1 MB memory, which never gets released.

```elixir
  def mount(_params, _session, socket) do
    books = Enum.map(1..@max_list_size, &%{id: &1, name: "Book #{&1}"})
    {:ok, stream(socket, :books, books)}
  end
```

However, if I start with an empty list and add 3000 books one by one, we only use 1.1MB of memory.

```elixir
  def mount(_params, _session, socket) do
    send(self(), :tick)
    {:ok, socket |> assign(:n, 1) |> stream(:books, [])}
  end

  def handle_info(:tick, socket) do
    id = socket.assigns.n
    book = %{id: id, name: "Book #{id}"}

    if id < @max_list_size do
      send(self(), :tick)
    end

    {:noreply, socket |> assign(:n, id + 1) |> stream_insert(:books, book, at: -1)}
  end
```

### Expected behavior

According to the docs for the new streams API, I would expect the process's memory usage to spike to 5.1 MB during initial render (or less if we were reading from Stream.map/2`) and then drop down much lower as soon as that rendering is done.

**Comment by josevalim** [comment]
Can you call :erlang.garbage_collect? You can either use an after_render hook or send a message to yourself. But perhaps it may be a good practice to always GC after streams or temporary assigns.

**Comment by aaronrenner** [comment]
Thanks for that idea. I just tried calling `:erlang.garbage_collect/0` and I'm still seeing 5.1 MB of memory usage after the GC. Here's the code I used to test it out:

```elixir
  def mount(_params, _session, socket) do
    books = Enum.map(1..@max_list_size, &%{id: &1, name: "Book #{&1}"})
    send(self(), :gc)
    {:ok, stream(socket, :books, books)}
  end

  def handle_info(:gc, socket) do
    :erlang.garbage_collect()
    {:noreply, socket}
  end
```
This seems like the approach you're talking about, but let me know if I'm doing it incorrectly.

**Comment by aaronrenner** [comment]
I did a little more digging and it looks like I need to call `:erlang.garbage_collect/1` on both the current liveview process and `socket.transport_pid`

```elixir
  def handle_info(:gc, socket) do
    :erlang.garbage_collect(socket.transport_pid)
    :erlang.garbage_collect(self())
    {:noreply, socket}
  end
```

Once I did this, memory usage returned to what I expected.

Is this something developers should do or should there be something to make this more automatic?

**Comment by aaronrenner** [comment]
I also found I needed to trigger this by sending a message with `Process.send_after/3` instead of using `send/2`. Sending it with a 100 ms delay worked, but a 10 ms delay did not.

**Comment by aaronrenner** [comment]
I've been playing around with garbage collection more and when I trigger GC on my process, it doesn't even seem like I need to use streams or temporary assigns in my situation. I'm thinking this probably isn't the source of my memory spikes anymore.

Thanks so much for the help! I'm going to close out this issue.
