### ISSUE TITLE
Bug: Issue with phx-change on form recovery when first field is a live component

### ISSUE THREAD

**Issue by barkerja** [phoenixframework/phoenix_live_view#2603]
### Environment

* Elixir version (elixir -v): 1.14.4
* Phoenix version (mix deps): 1.7.2
* Phoenix LiveView version (mix deps): 0.18.8
* Operating system: Alpine 3.16
* Browsers you attempted to reproduce this bug on (the more the merrier): Safari 16.5, Chrome 112.0.5615.137
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

If a form field that is a live component with its `phx-target` set to `@myself` is the first field in a form, on form recovery the live component — not its parent LiveView — receives the form's `phx-change` event.

This leads to a constant reconnect/crash loop for the user. The only recourse is to either reorder the fields so that the first field is not a live component field, or add a `handle_event/3` callback to the live component that serves as a noop.

### Expected behavior

On form recovery, the parent LiveView receives the form's `phx-change` event as it normally would.

An example repo of this can be found here: https://github.com/barkerja/lv_test

Steps to reproduce:

1. Visit http://localhost:4000/example
2. View console, get PID of the LiveView process
3. Run command `Process.exit(..., :kill)`
4. Note the issue with the form attempting to recover when the socket reconnects

**Comment by chrismccord** [comment]
Your component should set its own phx-change for the input, then it will not be considered for recovery by the parent. As written, the LC has to know what event name the parent form has for phx-change, so I actually think we should deprecate the fact that phx-target works on an input without phx-change. Thanks!
