### ISSUE TITLE
Receiving 1001 websocket code from web servers breaks liveview

### ISSUE THREAD

**Issue by carterbryden** [phoenixframework/phoenix_live_view#2610]
### Environment

* Elixir version (elixir -v): 1.14.1
* Phoenix version (mix deps): 1.7.2
* Phoenix LiveView version (mix deps): 0.18.6
* Operating system: Ubuntu 22.04
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

Using a web server like Caddy, when a config update is pushed to Caddy it will close existing websocket connections with 1001 with the expectation that they will reconnect almost immediately after.

Liveview treats this as if we're navigating away from the page (I think), I suspect because Firefox sends a 1001 code on navigating away. Because we aren't actually navigating away, the liveview breaks and ends up in a confused disconnected state that never reconnects.

### Expected behavior

Liveview reconnects as soon as it can after the websocket connection is closed (once it's available again).

### Proposed solution

I don't know enough about how this is designed under the hood, but perhaps we could do some secondary check to confirm that we're actually navigating away before destroying the liveview (or whatever it's doing here). If that fails, we treat it as a normal disconnection and try to reconnect. If that makes sense to the core team, I'd be happy to contribute that.

I know that the first reaction to this will likely be that Caddy should change, but the spec is vague enough that both Firefox and Caddy are technically within the spec, and it's likely that there will be other servers and situations where this is an issue. We'd be doing ourselves a favor to have some kind of solution to this in my opinion.

**Comment by carterbryden** [comment]
Sorry, I forgot that there's a similar issue to this in #2544 but I'll leave this up since I think it likely affects more than Caddy. Feel free to close this if needed, of course.

**Comment by josevalim** [comment]
Yeah, let's keep the discussion on #2544 and we can reopen if it does branch out outside of Caddy :)
