### ISSUE TITLE
Incorrect examples for JS.dispatch

### ISSUE THREAD

**Issue by zimt28** [phoenixframework/phoenix_live_view#2613]
Some examples in the documentation for `JS.dispatch` use the `:to` option incorrectly. The event listener is added to `window` but it must be attached to the element specified in the `:to` option. Alternatively the `:to` option could be removed, but it would be nice to have a correct example using it.

https://github.com/phoenixframework/phoenix_live_view/blob/dc4c139092c8b5eb6617ba9c9c6266853011c88e/lib/phoenix_live_view/js.ex#L106-L119

https://github.com/phoenixframework/phoenix_live_view/blob/dc4c139092c8b5eb6617ba9c9c6266853011c88e/lib/phoenix_live_view/js.ex#L214-L216

**Comment by rktjmp** [comment]
`dispatch` events bubble by default. The example is working and believe is using both parts intentionally, binding to the window so it catches all events of the type, and dispatching to the element to `event.target` is available to retrieve the content from.

Perhaps the bubbling behaviour could be mentioned?

https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.JS.html#dispatch/2

> :bubbles – The boolean flag to bubble the event or not. Default true.

**Comment by chrismccord** [comment]
@rktjmp is correct. The events bubble by default so things should work as advertised. Thanks!
