### ISSUE TITLE
inputs_for omits replaced records from forms

### ISSUE THREAD

**Issue by dfalling** [phoenixframework/phoenix_live_view#2616]
### Environment

* Elixir version (elixir -v): 1.14.4
* Phoenix version (mix deps): 1.7.2
* Phoenix LiveView version (mix deps): 0.18.18
* Operating system: macOS 13.2.1
* Browsers you attempted to reproduce this bug on (the more the merrier): Arc
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

`inputs_for` omits associations that have been marked as `:replace`. If you remove every association of a collection, any other change to the form will cause all of the associations to be restored, as the absence of data for that field clears out the previous changes.

### Expected behavior

`inputs_for` shouldn't omit the replaced records. This works for removing some items, but is insufficient for replacing all of them. Do we need some other solution that can hide (but include) these records based on their presence in `drop_param`?

**Comment by dfalling** [comment]
Hrm, I can't get that to work. I added the empty input and can see the empty string in the drop_param in the Changeset's params. But the association (`element_photos`) is still coming back.

The Changeset's params:
```elixir
# this works, the final element_photo in index 0 is removed and the form field is empty
params: %{
  "element_photos_drop" => ["", "0"],
  "element_photos_order" => ["0"]
}


# this is caused by another change, and results in the element_photos all coming back
params: %{
  "completed" => true,
  "element_photos_drop" => [""]
}
```

Could it be that my schema's structure is more complex than drop_param supports?
```
element Form
|- element_photos inputs_for             # drop and sort params
  |- photo inputs_for.                   # nested photo inputs
  |- another photo inputs_for            # render a photo thumbnail
```

<details>
<summary>
The whole messy form field
</summary>

```elixir
<div
  id="element_photos"
  class="grid grid-cols-1 lg:grid-cols-3 gap-2"
  phx-hook="Sortable"
  data-reorder="reorder_photos"
>
  <input type="hidden" name="element[element_photos_drop][]" />
  <.inputs_for :let={element_photo_form} field={@form[:element_photos]} skip_hidden>
    <div class="grid grid-flow-col gap-1 justify-start items-center pt-2">
      <.input field={element_photo_form[:id]} type="hidden" />
      <input
        type="hidden"
        name="element[element_photos_order][]"
        value={element_photo_form.index}
        class="hidden"
      />
      <IdoWeb.PhotoComponents.form_fields form={element_photo_form} field={:photo} />
      <.inputs_for :let={photo_form} field={element_photo_form[:photo]}>
        <img src={photo_form[:thumbnail].value} alt="" />
      </.inputs_for>
      <label class="cursor-pointer">
        <input
          type="checkbox"
          name="element[element_photos_drop][]"
          value={element_photo_form.index}
          class="hidden"
        />
        <Heroicons.x_mark solid class="h-5 w-5 stroke-current" />
      </label>
    </div>
  </.inputs_for>
</div>
```
</details>

Thanks for the help! I'm excited about these new features cleaning up my forms.

**Comment by dfalling** [comment]
> Anyway, you will need Ecto v3.10.1 and you need to make sure that at least one of the association, sort param or drop param to always be set so it doesn't restore everything once deleted.

That was it! I thought I was current, but Ecto v3.10.1 fixed it for me. Thanks!

**Comment by Munksgaard** [comment]
I was stumped by this issue today, and I don't think the documentation adequately explains the fix. Should this be reopened?

**Comment by josevalim** [comment]
Better docs pushed.
