### ISSUE TITLE
Add support for modifiers and multiply key events on element

### ISSUE THREAD

**Issue by Schultzer** [phoenixframework/phoenix_live_view#2617]
Hi, I have a use case where I bind multiple key events and their modifiers, e.g. `ctrl`, `meta`, and `shift`, to an element.

And I propose adding `phx-keydown-*` and `phx-keyup-*` attributes.

```
<div phx-keydown="keydown" phx-key="a" phx-keydown-control-a={JS.set_attribute({"aria-selected", "true"}, to: "div")}>
```

Please take a look at my PR for a proposed solution.

**Comment by chrismccord** [comment]
I think this is better solved other ways that don't require more bindings. For example you could ship a keyboard hook:

```
  <.keyboard>
    <:on key="ArrowUp" push="keyup" />
    <:on key="ArrowDown" exec={JS.hide(to: "body")} />
  </.keyboard>
```

I've considered shipping this with LiveView, but you could implement it yourself in the meantime with existing primitives. THanks!
