### ISSUE TITLE
Support nested JS commands

### ISSUE THREAD

**Issue by Schultzer** [phoenixframework/phoenix_live_view#2619]
Hi, I have a use case where I need to nest JS commands, e.g. `JS.set_attribute/2`

```
<div tabindex="0" phx-click-away={JS.set_attribute({"phx-click", JS.set_attribute({"phx-click", JS.remove_attribute("aria-selected", to: "div:focus>div[ariaselected=true]")})})}
   phx-click={JS.remove_attribute("aria-selected", to: "div:focus>div[aria-selected=true]")}>
  <div aria-selected="true"/>
  <div/>
<div>
```

Please take a look at my PR for a proposed solution.

**Comment by SteffenDE** [comment]
As per https://github.com/phoenixframework/phoenix_live_view/issues/1766#issuecomment-974638482 I don't think that this is something LV wants to support. For toggling attributes, https://github.com/phoenixframework/phoenix_live_view/pull/2004 seems to be on Chris' todo list for the near future.

Do you think `toggle_attribute` would solve your usecases?
