### ISSUE TITLE
LiveViewTest.file_input/4 doesn't allow setting of newer attributes

### ISSUE THREAD

**Issue by camelpunch** [phoenixframework/phoenix_live_view#2628]
This is kind of a feature request, following on from the recent addition of support for the `webkitdirectory` attribute on file inputs.

A `LiveView.UploadEntry` currently looks like this:

```
%Phoenix.LiveView.UploadEntry{
  progress: 100,
  preflighted?: true,
  upload_config: :files,
  upload_ref: "phx-F19IgQiyZM1HYwMB",
  ref: "0",
  uuid: "cac6e331-9477-4d7b-a912-bddd671497c2",
  valid?: true,
  done?: true,
  cancelled?: false,
  client_name: "my-new-blog.html",
  client_relative_path: "dist/blog/my-new-blog.html",
  client_size: 34,
  client_type: "text/html",
  client_last_modified: 1684140816865
}
```

At present, though, [LiveViewTest.file_input/4](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveViewTest.html#file_input/4) only allows control over some of these attributes in LiveView tests.

I have an application that uses the new `webkitdirectory` attribute on an `input` element. In order to process the files in the directory correctly, I need access to e.g. `client_relative_path`, which includes the subdirectories that the files are under.

I can get around this restriction by passing along the whole `UploadEntry` to lower-level code and testing there, but it'd be nice to be able to set these attributes inside a LV test, just like a browser would.

**Comment by chrismccord** [comment]
Can you send a PR to allow the test client to send "relative_path" metadata? Thanks!
