### ISSUE TITLE
Form submit fails in automated tests

### ISSUE THREAD

**Issue by SteffenDE** [phoenixframework/phoenix_live_view#2630]
### Environment

* Elixir version (elixir -v): 1.14.4
* Phoenix version (mix deps): 1.7.2
* Phoenix LiveView version (mix deps): main

### Actual behavior

We've got a lot of automated end to end tests using [Playwright](https://playwright.dev/). After https://github.com/phoenixframework/phoenix_live_view/commit/26a776cd1cb7461c0a22e1a14a6315ddaa66c740 many of those tests fail because the form submit event is not triggered any more, e.g. when clicking on a submit button. This occurs because the automated browser is much faster in filling out forms, clicking buttons, etc. than a real user, so the introduced change discards the event as we're already waiting for an acknowledgement.

### Expected behavior

The only workaround I found is to wait for an arbitrary amount of time, but that's obviously bad.
Is there a reason for this change? Discarding events seems like a bad solution, maybe we can queue them instead?

**Comment by chrismccord** [comment]
Can you try last main and report back? Thanks!

**Comment by SteffenDE** [comment]
That's indeed it, thank you!
