### ISSUE TITLE
Regression: webkitdirectory attribute no longer supported

### ISSUE THREAD

**Issue by camelpunch** [phoenixframework/phoenix_live_view#2631]
### Environment

* Elixir version (elixir -v): 1.14.3
* Phoenix version (mix deps): 1.7.2
* Phoenix LiveView version (mix deps): 19b7784dfef956a2daff1b4e6e264d98325ca440
* Operating system: Linux
* Browsers you attempted to reproduce this bug on (the more the merrier): none
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: no

[This commit](https://github.com/phoenixframework/phoenix_live_view/commit/19b7784dfef956a2daff1b4e6e264d98325ca440) appears to remove support for the webkitdirectory attribute on `live_file_input`s.

### Actual behavior

In my app that uses webkitdirectory, I get this warning:

```
warning: undefined attribute "webkitdirectory" for component Phoenix.Component.live_file_input/1
```

### Expected behavior

No warning. The prior commit does not emit the warning.

**Comment by josevalim** [comment]
We should probably list `webkitdirectory` as an additional :global option. Can you please send a PR?
