### ISSUE TITLE
Bulk uploading

### ISSUE THREAD

**Issue by l3aconator** [phoenixframework/phoenix_live_view#2633]
### Environment

* Elixir version (elixir -v): 1.14.3
* Phoenix version (mix deps): 1.7
* Phoenix LiveView version (mix deps): 0.18.18
* Operating system: MacOS Ventura 13.3.1 (a)
* Browsers you attempted to reproduce this bug on (the more the merrier): Latest Chrome, Safari, Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

I realize this is likely an edge case, but would like to note here and ask if A. something worth fixing in future liveview or B. any tips on how to solve

This pertains to live view uploading through an external provider (google cloud) and a large mass of files. For context, I currently am working on a photography business management application with photo gallery delivery. Wedding photographers tend to upload 1000+ photos in one go. Live view consistently disconnects when uploading a bunch of files. I have solved for the weight of the files on the frontend using resumables direct to google cloud storage, but when it comes to pre-signing the URLs through liveview uploads (which is great btw!), the process tends to fail and the liveview component disconnects. Our entire gallery is built on liveview, we are really trying to avoid rewriting to a deadview which I have played with in a separate repo and that solves it because I am able to essentially fire off requests that are one and done.

(I have also been experimenting with either patching the upload hook to batch entries or writing my own upload component but yours is already so good)

### Expected behavior

I am able to chunk or configure a way to chunk liveview uploads to not overload the server when using `external:` presigning

**Comment by l3aconator** [comment]
Update here: I went the route of hand rolling a frontend uploader using the new `stream()` API on the backend to load in all the photos that are uploading + updating based on those that have been processed. Working well so far. Using pushEvents, streams and Phoenix.PubSub. Error handling and progress updating are still pending on my end but good solution in case anyone runs across this.

**Comment by Neophen** [comment]
@l3aconator Maybe you want to share a repo which shows how to do this?

**Comment by l3aconator** [comment]
@Neophen I will see if I can, or at least a minimal reproduction. The system I've built is wrapped in a ton of other proprietary business logic.

**Comment by josevalim** [comment]
I believe you should indeed tackle this on your side because the best way is to batch on the client and avoid sending 1000 files at once. :) I am not sure how complex it is to achieve this though.

**Comment by chrismccord** [comment]
This isn't something we intend to tackle for 1.0 but may revisit in the future. Thanks!
