### ISSUE TITLE
form binding documentation seem to be incorrect 

### ISSUE THREAD

**Issue by ananda-s** [phoenixframework/phoenix_live_view#2635]
### Environment

* Elixir version (elixir -v): 1.14.3
* Phoenix version (mix deps): 1.7.2
* Phoenix LiveView version (mix deps): 0.18.16
* Operating system: Mac OS
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

```
defmodule MockchainWeb.BugLive do
  use MockchainWeb, :live_view

  def mount(_param, _session, socket) do
    {:ok, assign(socket, :form, to_form(%{username: "", email: ""}))}
  end

  def render(assigns) do
    ~H"""
    <div>
      <.form for={@form} phx-change="validate" phx-submit="save">
        <.input type="text" field={@form[:username]} />
        <.input type="email" field={@form[:email]} />
        <button>Save</button>
      </.form>
    </div>
    """
  end

  def handle_event("validate", _params, socket) do
    {:noreply, socket}
  end

  def handle_event("save", _params, socket) do
    {:noreply, socket}
  end
end
```

I followed the official documentation from https://hexdocs.pm/phoenix_live_view/form-bindings.html , where it says the @form can be created using the `to_form` function.

But when you run this code you get the below error : 

`key :name not found in: %{__changed__: nil, __given__: %{__changed__: nil, field: %Phoenix.HTML.FormField{id: "username", name: "username", errors: [], field: :username, form: %Phoenix.HTML.Form{source: %{email: "", username: ""}, impl: Phoenix.HTML.FormData.Map, id: nil, name: nil, data: %{}, hidden: [], params: %{email: "", username: ""}, errors: [], options: [], index: nil, action: nil}, value: nil}, type: "text"}, field: %Phoenix.HTML.FormField{id: "username", name: "username", errors: [], field: :username, form: %Phoenix.HTML.Form{source: %{email: "", username: ""}, impl: Phoenix.HTML.FormData.Map, id: nil, name: nil, data: %{}, hidden: [], params: %{email: "", username: ""}, errors: [], options: [], index: nil, action: nil}, value: nil}, inner_block: [], label: nil, multiple: false, prompt: nil, rest: %{}, type: "text"}`

This error can be fixed by using the code snippet below on the field parameter

```
     <.form for={@form} phx-change="validate" phx-submit="save">
        <.input type="text" field={{@form, :username}} />
        <.input type="email" field={{@form, :email}} />
        <button>Save</button>
     </.form>
```

Does the documentation need an update ?

**Comment by chrismccord** [comment]
Looks like your application was generated with 1.7-rc which contained a tuple-based `input` component. We have since moved to the access based `form[:field]` approach with `to_form`, so the current documentation is correct. You can either update your `input` components to use the new form, or stay with the tuples as you've shown. Thanks!
