### ISSUE TITLE
Live View does not support events important to our app

### ISSUE THREAD

**Issue by technomage** [phoenixframework/phoenix_live_view#2637]
### Environment

* Elixir version (elixir -v):
Erlang/OTP 25 [erts-13.2] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit] [dtrace]
Elixir 1.14.3 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps):
 phoenix 1.7.2 (Hex package) (mix)
  locked at 1.7.2 (phoenix) 1ebca94b
  ok
* phoenix_ecto 4.4.0 (Hex package) (mix)
  locked at 4.4.0 (phoenix_ecto) 09864e55
  ok
* phoenix_html 3.3.1 (Hex package) (mix)
  locked at 3.3.1 (phoenix_html) bed1906e
  ok
* phoenix_live_dashboard 0.7.2 (Hex package) (mix)
  locked at 0.7.2 (phoenix_live_dashboard) 0e5fdf06
  ok
* phoenix_live_reload 1.4.1 (Hex package) (mix)
  locked at 1.4.1 (phoenix_live_reload) 9bffb834
  ok
* phoenix_live_session 0.1.3 (Hex package) (mix)
  locked at 0.1.3 (phoenix_live_session) ae353587
  ok
* Phoenix LiveView version (mix deps):

* phoenix_live_view 0.18.18 (Hex package) (mix)
  locked at 0.18.18 (phoenix_live_view) a5810d04
* Operating system:
MacOS Ventura
* Browsers you attempted to reproduce this bug on (the more the merrier): 
Chrome, Safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:
N/A
### Actual behavior
No support for "onInput" to get character by character input is needed for search boxes (as an example).
No support for "onMouseLeave" to implement popup menus and such that should disappear on mouse leave.

### Expected behavior
Ideally LiveView would support all standard events.

**Comment by chrismccord** [comment]
José's answer is perfect, but also note that phx-change is essentially oninput for al the inputs in the form, so you only need the hook for onmouseleave, which we won't support but would take only 3 LOC in a hook to do yourself. Cheers :)
