### ISSUE TITLE
GitHub Security Alerts for npm packages

### ISSUE THREAD

**Issue by PJUllrich** [phoenixframework/phoenix_live_view#264]
I just created a new Demo project with LiveView and after pushing my code to GitHub, I received Security Alerts for the following npm packages:

```
mem - moderate severity
shelljs - moderate severity
js-yaml - high severity
```

Given the severity of the alerts, should we consider replacing these packages if possible?

**Comment by Schultzer** [comment]
These are child dependencies of the dev dependencies. `npm auth fix` would fix this.

moderate or high severity doesn't really provide any context to why there is a security risk here.

**Comment by PJUllrich** [comment]
Thank you that clears it up. If those are only dev dependencies then these alerts are of lesser priority indeed. I'll try to fix this using `npm auth fix`

**Comment by PJUllrich** [comment]
I wasn't able to fix this issue with the `npm audit fix` command. However, I'm going to close this, since it only affects the `development` dependencies.
