### ISSUE TITLE
to_form/2 incorrectly documented or input core_component broken?

### ISSUE THREAD

**Issue by BrooklinJazz** [phoenixframework/phoenix_live_view#2641]
### Environment

* Elixir version (elixir -v):
Erlang/OTP 25 [erts-13.2.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.14.4 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): {:phoenix, "~> 1.7.2"},
* Phoenix LiveView version (mix deps): {:phoenix_live_view, "~> 0.18.16"},
* Operating system: Ubuntu
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome (irrelevant)
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: (irrelevant)

# Expected Behavior

I attempted to use the to_form/2 function as documented: https://hexdocs.pm/phoenix_live_view/0.18.18/Phoenix.Component.html#to_form/2-options

```elixir
to_form(%{"search" => nil}, errors: [search: [{"Can't be blank", []}]])
```

## Actual Behavior

But the errors are provided to the form in the following incorrect structure:

```elixir
[[{"Can't be blank", []}]]
```

This causes the following error:

```elixir
** (FunctionClauseError) no function clause matching in LiveViewCounterWeb.CoreComponents.translate_error/1
    (live_view_counter 0.1.0) lib/live_view_counter_web/components/core_components.ex:617: LiveViewCounterWeb.CoreComponents.translate_error([{"Can't be blank", []}])
```

I can solve the issue by changing how I define the errors in the form by removing the list.

```elixir
to_form(%{"search" => nil}, errors: [search: {"Can't be blank", []}])
```

I'm not sure if:
1. The to_form function is documented incorrectly.
2. The `input` component in `core_components.ex` is broken.
3. I'm misunderstanding something.

If it's 1 or 2, I'm happy to make a PR to resolve the issue. If it's 3 then I'm happy to be corrected and sent along my merry way! Thank you for your time.

P.S. I haven't submitted too many issues so please let me know if I can improve how I submit them to better match your standards.

**Comment by josevalim** [comment]
> to_form(%{"search" => nil}, errors: [search: {"Can't be blank", []}])

This is the correct format indeed.

I believe it has been fixed in main already, if not, feel free to PR.

P.S. Issue was great :+1:
