### ISSUE TITLE
stream mixed with Presence results in empty lists

### ISSUE THREAD

**Issue by cabello** [phoenixframework/phoenix_live_view#2643]
### Environment

* Elixir version (elixir -v):  Erlang/OTP 25 / Elixir 1.14.4
* Phoenix version (mix deps): 1.7.2
* Phoenix LiveView version (mix deps): 0.18.18
* Operating system: MacOS
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Not Applicable

Steps to reproduce:

1. Have two browsers, use Presence and stream in that live_view.
2. For example the following HEEX uses streams and Presence:
```
<li :for={{dom_id, participant} <- @streams.participants} id={dom_id}>
        <span class="username">
          <%= participant.user.nickname %>

          <%= if @presences[Integer.to_string(participant.user_id)] do %>
            <span class="text-white bg-green-600 px-2 rounded-lg text-sm mx-1">
              Online
            </span>
          <% else %>
            <span class="text-white bg-red-600 px-2 rounded-lg text-sm mx-1">
              Offline
            </span>
          <% end %>
</li>
```
3. Open the first browser (A) see the list of users online
4. Open the second browser (B) see the list of users online

### Actual behavior

Confirm that the first browser (A) now renders an empty list.

Upon inspection of websocket messages:
```
["4",null,"lv:phx-F2JzwHPEf9nZCwAl","diff",{"1":{"2":{"d":[],"stream":[{},[]]}}}]
```

If removed the presence portion (Online/Offline) then the list persist between refreshes.

### Expected behavior

The list to stay even when other people join the Presence channel.

**Comment by josevalim** [comment]
Can you please provide a small replication, preferrably a single file Phoenix app, that reproduces the error?

**Comment by cabello** [comment]
🤦 I think I forgot to add a wrapper with id and `phx-update` `<div id="photos" phx-update="stream">`

**Comment by cabello** [comment]
That was it, once I wrapped the stream usage with `<div id="people" phx-update="stream">` it works as expected, at least on the minimal use case, let me see the one with Presence.

**Comment by chrismccord** [comment]
Glad you got it sorted!
