### ISSUE TITLE
JS client crashes when div with name attribute contains HTML input

### ISSUE THREAD

**Issue by maxmarcon** [phoenixframework/phoenix_live_view#2648]
### Environment

* Elixir version (elixir -v): 1.14.0
* Phoenix version (mix deps): 1.6.16
* Phoenix LiveView version (mix deps): 0.19.0
* Operating system: MacOS
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, Safari, Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes

### Actual behavior

When loading a page with a div element that has a `name` attribute and contains an HTML input, the JS client crashes with this error:

```
dom.js:276 Uncaught TypeError: Cannot read properties of undefined (reading 'endsWith')
    at Object.maybeHideFeedback (dom.js:276:21)
    at dom_patch.js:268:11
    at Array.forEach (<anonymous>)
    at DOMPatch.perform (dom_patch.js:267:19)
    at View.performPatch (view.js:417:11)
    at View.applyJoinPatch (view.js:343:10)
    at View.onJoinComplete (view.js:314:14)
    at view.js:278:14
    at View.applyDiff (view.js:247:5)
    at View.onJoin (view.js:262:10)
```

### Expected behavior

It shouldn't crash :)

### To reproduce:

```bash
git clone git@github.com:maxmarcon/live_select.git
cd live_select
git checkout lv_latest
pushd assets; yarn; popd  # not strictly necessary, but might help make the page more understandable
mix deps.get
mix phx.server
```
now visit ```http://localhost:4000```, you'll see the error in the JS console.

### Description:

The error happens because the div of the live select container element (`div#my_form_city_search_live_select_component`) has a name attribute, which is accessed [here](https://github.com/phoenixframework/phoenix_live_view/blob/76cadff532495fdfdef78a11324743399f403218/assets/js/phoenix_live_view/dom.js#L276) by LiveView using the `.name` property of its HTML element object, which is an API only available (I believe) for HTML elements that can have a name attribute. A `div` is not among them, and since the live_select container is a `div`, `.name` returns undefined in this case.

LiveView starts keeping track of the div [here](https://github.com/phoenixframework/phoenix_live_view/blame/76cadff532495fdfdef78a11324743399f403218/assets/js/phoenix_live_view/dom_patch.js#L250), where the div gets added to the `trackedInputs` array.

I know that an HTML div is not supposed to have a `name` attribute, and that should go away in my code. Still, LiveView should be more robust and not crash when such an element is encountered (it could silently ignore the element or output a warning).

it might be enough to use the `.name` property to decide if an element is an input. Something like:

```js
if (toEl.getAttribute("name")){
  if (toEl.name) {
      trackedInputs.push(toEl)
   } else {
     // log warning: non-input element with name attribute detected
   }
}
```

Thanks to all of you for your great work with LiveView!

**Comment by dougw-bc** [comment]
I have the same issue - pretty big lv app, with JS hooks that rely on `name` attributes on non-input elements. We are using this for identifying elements within the hooks `this.el` - which might be rendered multiple times.

I am trying to take a stab at reverting using `name` on non inputs - but feel like this is a bit too easy to run into - not sure if the code handles these other elements that could legitimately have a `name` attribute: 
https://www.w3schools.com/tags/att_name.asp

I also have a bunch of `meta` tags with a `name` attribute - not sure if that could be the culprit...
```html
<meta name="keywords" content="HTML,CSS,JavaScript">
```
