### ISSUE TITLE
`handle_params/3` called twice 

### ISSUE THREAD

**Issue by tgxworld** [phoenixframework/phoenix_live_view#265]
I was playing around with the example on Live Redirect in https://github.com/chrismccord/phoenix_live_view_example when I noticed that loading `localhost:4000/users` would end up fetching the users twice. This can be seen from the logs as well.

![Screenshot from 2019-07-09 20-26-28](https://user-images.githubusercontent.com/4335742/60887823-ddfada00-a287-11e9-8917-c171653d7b8e.png)

I'm not sure whether this is the intended behavior or not but it seems like live view shouldn't have to run the same database query twice?

**Comment by tgxworld** [comment]
Not sure if this is related as well but it seems like a `live_redirect` causes `handle_params/3` to be called twice as well

![Screenshot from 2019-07-09 21-10-28](https://user-images.githubusercontent.com/4335742/60890544-0d144a00-a28e-11e9-9995-a9aa2978618b.png)

**Comment by stuartmackey** [comment]
We just noticed some very similar behaviour in our application. We haven't investigated it yet though, can I ask why you closed the issue, did you realise it was the correct behaviour after all?

**Comment by stuartmackey** [comment]
Please ignore me, i just found the other issue that you raised that covers this (https://github.com/phoenixframework/phoenix_live_view/issues/268).
