### ISSUE TITLE
Stream reset (and maybe delete) is broken when custom rows comprehension is used

### ISSUE THREAD

**Issue by a3kov** [phoenixframework/phoenix_live_view#2650]
### Environment

* Elixir version (elixir -v): 1.14
* Phoenix version (mix deps): 1.7.2
* Phoenix LiveView version (mix deps): 0.19.0
* Operating system:

### Actual behavior

I have a table component that is enumerating stream items (rows) to be able to add even/odd classes.
Instead of 
```elixir
<tr ... :for={row <- @rows}
```
its doing
```elixir
<tr ... :for={{row, ri} <- Enum.with_index(@rows)}
```

Turns out this completely breaks stream reset - old items are not removed at all. I was able to reproduce on a fresh Phoenix project just by adding this to the built-in table component.
Probably it was also the reason stream delete by dom_id didn't work for me in 0.18.18.

### Expected behavior
The way we use stream enumerable in the template should not break streams. If something is required for the stream to work, it should be documented.

**Comment by chrismccord** [comment]
closed via [fda779b](https://github.com/phoenixframework/phoenix_live_view/commit/fda779b249f5d315bac04f25b585c079d71255ad)
