### ISSUE TITLE
Streams inside of live components do not work with tests

### ISSUE THREAD

**Issue by ethangreenberg** [phoenixframework/phoenix_live_view#2653]
### Environment

* Elixir version (elixir -v): 1.14.0
* Phoenix version (mix deps): 1.6.16
* Phoenix LiveView version (mix deps): 0.18.18
* Operating system: Mac OS Ventura 13.3.1
* Browsers you attempted to reproduce this bug on (the more the merrier): N/A
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: N/A

### Actual behavior

I am using `stream` inside of a live_component. On update, I call `stream_insert`. When running the app, `stream_insert` works as expected. However, when the update is called in tests, I get the following error.

<img width="1422" alt="237234178-e447cb3c-1624-49a3-98cf-d4a97addc2f5" src="https://github.com/phoenixframework/phoenix_live_view/assets/15315492/f79d46c9-38a5-4e65-bc26-99f71b2456a1">

### Expected behavior

`stream_insert` inside a live component works when testing

**Comment by chrismccord** [comment]
Please try 0.19 and report back. Thanks!
