### ISSUE TITLE
Doc generation: newlines are removed from slot doc

### ISSUE THREAD

**Issue by ArthurClemens** [phoenixframework/phoenix_live_view#2661]
### Environment

* Elixir version (elixir -v): `1.14.4`
* Phoenix version (mix deps): `1.7.3`
* Phoenix LiveView version (mix deps): `0.19.0`
* Operating system: `MacOS 13.4`

### Actual behavior

A component `slot` declaration that contains a doc comment result in a doc text with all newlines removed. If the slot describes attrs, the line "Accepts attributes:" is appended to the doc text without any whitespace.

Code:

```hex
slot :title,
  required: true,
  doc: """
  Line 1.

  Line 2.
  """ do
  attr(:class, :string,
    doc: """
    Additional classname.
    """
  )
end
```

Rendered as:

```html
<ul>
  <li>
    <p><code class="inline">title</code> (required) - Line 1.Line 2.Accepts attributes:</p>
    <ul>
      <li>
        <code class="inline">class</code> (<code class="inline">:string</code>) - Additional classname.
      </li>
    </ul>
  </li>
</ul>
```

Resulting HTML:

<ul>
  <li>
    <p><code class="inline">title</code> (required) - Line 1.Line 2.Accepts attributes:</p>
    <ul>
      <li>
        <code class="inline">class</code> (<code class="inline">:string</code>) - Additional classname.
      </li>
    </ul>
  </li>
</ul>

### Expected behavior

Whitespace should be preserved (as is done with `attr` docs). The desired output is:

```html
<ul>
  <li>
    <p><code class="inline">title</code> (required) - Line 1.</p>
    <p>Line 2.</p>
    <p>Accepts attributes:</p>
    <ul>
      <li>
        <code class="inline">class</code> (<code class="inline">:string</code>) - Additional classname.
      </li>
    </ul>
  </li>
</ul>
```

Resulting HTML:

<ul>
  <li>
    <p><code class="inline">title</code> (required) - Line 1.</p>
    <p>Line 2.</p>
    <p>Accepts attributes:</p>
    <ul>
      <li>
        <code class="inline">class</code> (<code class="inline">:string</code>) - Additional classname.
      </li>
    </ul>
  </li>
</ul>

**Comment by josevalim** [comment]
Agreed. pR is welcome!

**Comment by josevalim** [comment]
Thank you @CoderDennis !
