### ISSUE TITLE
Stream limit documentation incomplete

### ISSUE THREAD

**Issue by SteffenDE** [phoenixframework/phoenix_live_view#2666]
### Environment

LV: 0.19

### Actual behavior

The documentation on stream limits abruptly ends:
https://github.com/phoenixframework/phoenix_live_view/blob/03ae646bd38fc60b3bd33574b20bd14b5fc9347d/lib/phoenix_live_view.ex#LL1572C3-L1573C15

> When a stream exceeds the limit on the client, the existing items will be removed
>  based on the

### Expected behavior

I'm not sure if only the end of the sentence is missing or if there should be more sentences following.

**Comment by josevalim** [comment]
Please send a PR for that one? :)

**Comment by rktjmp** [comment]
Fixed in https://github.com/phoenixframework/phoenix_live_view/commit/8ab3a5c9d534200ebc18de872ee77cb4c3574d75
