### ISSUE TITLE
Infinite redirect loop when `#` anchor fragment is present

### ISSUE THREAD

**Issue by topherhunt** [phoenixframework/phoenix_live_view#267]
### Environment

* Elixir version (elixir -v): 1.8.1
* Phoenix version (mix deps): 1.4.9
* `phoenix_live_view` version: 0.1.0
* NodeJS version (node -v): 8.9.3
* NPM version (npm -v): 6.9.0
* Operating system: OSX 10.14.4

### Actual behavior

Hi! I notice that when I load a liveview-driven page with a `#` anchor fragment appended to the url (e.g. http://localhost:4000/my_liveview#topher), the liveview process appears to enter an infinite redirect loop, spitting out tons of page request logs in the console output and tons of redirect-related frames in the /live websocket.

I assume this is a known thing, but I don't see an issue describing it. My hunch is that this behavior is something to do with the WIP redirecting & live_link stuff.

Full repro steps below. I've also published a repo that demos this behavior: https://github.com/topherhunt/liveview-redirect-loop-repro

### Expected behavior

I'm not sure. At the very least, I'd expect that tacking a `#` onto the current url should not result in an infinite redirect loop.

Naively, it would be cool if `#` url anchors could work the same way on liveview-driven pages as they do on static pages.

### Repro steps

1. Create a fresh Phoenix app.

```
$ mix phx.new omg
$ cd omg
$ mix ecto.create
```

2. Install LiveView following the standard steps at https://github.com/phoenixframework/phoenix_live_view/

3. Add a new route and a controller action that renders a bare-bones liveview:

```
# router.ex
...
scope "/", OmgWeb do
  pipe_through :browser

  get "/", PageController, :index
  get "/live", PageController, :live
end
...
```

```
# page_controller.ex
...
def live(conn, _params) do
  live_render(conn, OmgWeb.OmgLive, session: %{})
end
...
```

```
# lib/omg_web/live/omg_live.ex
defmodule OmgWeb.OmgLive do
  use Phoenix.LiveView

  def mount(%{}, socket) do
    {:ok, socket}
  end

  def render(assigns) do
    ~L"""
      Here's a string
    """
  end
end
```

4. Start the server: `mix phx.server`

5. In your browser, go to http://localhost:4000/. It renders the homepage.

6. Go to http://localhost:4000/live. It renders the LiveView's content and then stops, as expected.

7. Go to http://localhost:4000/live#. (Optionally add any text after the #.) The console spits out a constant loop of rendering messages, as if the page is getting continually redirected. You can also see the /live websocket generating tons of redirect-related frames.

**Comment by nathanl** [comment]
https://github.com/phoenixframework/phoenix_live_view/issues/296 links to a demo app which also shows this issue

**Comment by chrismccord** [comment]
Fixed on master. Thanks!
