### ISSUE TITLE
live_socket.js unloads socket on click in contenteditable="true" contexts where click will not navigate

### ISSUE THREAD

**Issue by dkulchenko** [phoenixframework/phoenix_live_view#2670]
### Environment

* Elixir version (elixir -v): 1.14.4
* Phoenix version (mix deps): 1.7.3
* Phoenix LiveView version (mix deps): 0.18.18 (in 0.19 the issue persists)
* Operating system: macOS
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox (LV disconnects but doesn't redirect), Safari and Chrome (LV disconnects and (incorrectly) redirects)
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

I'm integrating with TipTap (the rich text editor) using `phx-hook`. TipTap is set up to suppress link clicks in the editor by intercepting the click event in the editor. In deadviews, this works correctly, and I can click on links in the editor and nothing happens. 
 
In the LiveView version, however, LV is doing something odd when I click on links within the editor:

![Screenshot at 2023-06-05 at 18 04 09](https://github.com/phoenixframework/phoenix_live_view/assets/144206/3161f2b8-6e6d-4b3d-96b4-06185ea41f04)

In Chrome and Safari, the LiveView version proceeds with a full navigation to the clicked link (which doesn't happen in dead views).

In Firefox, it's even weirder - for some reason LiveView believes that the navigation is taking place anyway (see the console logs) and destroys the RTE, but then doesn't navigate anywhere, so I'm left with a broken page.

I've created a minimal app here that repros the issue: https://github.com/dkulchenko/navbug

I attach TipTap using the same initialization code to both a dead view example (which works correctly) and the LiveView example (which doesn't).

### Expected behavior

I would not expect any navigation or attempted navigation to take place when clicking on the link, as in the dead view example.

**Comment by dkulchenko** [comment]
Here's something even weirder - I just learned that deadviews can use hooks as well. 

I replaced the manual JS `window.addEventListener("load")` code in the deadview example with the same `phx-hook` as the LiveView, and it broke just the same, in Chrome/Safari it does the nav and in Firefox it destroys the element but doesn't navigate. So it looks like it's something about the hook mechanism that makes it navigate/destroy and not navigate?

**Comment by dkulchenko** [comment]
I've tracked it down to this line in `live_socket.js`: https://github.com/phoenixframework/phoenix_live_view/blob/19cafaa8afa9e4c3bce96be90a09bea268cf5a40/assets/js/phoenix_live_view/live_socket.js#L643

Commenting out this line prevents both the destroy and/or navigation in all 3 tested browsers.

Basically, it seems like the LiveView click handler is triggering before TipTap has a chance to process the event and unloads the component before TipTap can block it. I'm unclear on why `this.unload` leads to navigation happening in Chrome/Safari, when it's still blocked in Firefox, but this seems to be the reason.

**Comment by dkulchenko** [comment]
Even more context. It doesn't look like TipTap adds any special handlers to prevent clicks. Instead, it relies on the fact that in all major browsers (I just tested in Chrome, Firefox, and Safari), `<a href="">` tags inside of a `<div contenteditable="true">` are not clickable, instead when you click on a link it just focuses the `contenteditable` portion and lets you edit the text/link.

It looks like LiveView manually attaches click handlers to all <a> tags, even those that are inside `contenteditable` sections, and performs an unload when they are clicked even when they will have no action (because they're in `contenteditable` and clicking them doesn't perform navigation).

**Comment by dkulchenko** [comment]
PR filed which fixes the issue.

**Comment by dkulchenko** [comment]
For future reference/note to self, the way to fix this type of unwanted unload for regular `click` handlers that are intercepting `<a href="">` is:

```javascript
document.getElementById("ignore-link").addEventListener("click", (e) => {
        e.preventDefault();
        e.stopImmediatePropagation(); // <- this line
})
```

But in this case, `contenteditable` is browser default behavior and thus has no click handler being manually set, and needs to be handled separately.

See also issues #492, #2394, and #2552.

**Comment by chrismccord** [comment]
Fixed on main. Thanks!
