### ISSUE TITLE
Proposal: Support for WebTransport API

### ISSUE THREAD

**Issue by r0xsh** [phoenixframework/phoenix_live_view#2684]
**Description:**
I would like to propose adding support for the WebTransport API in Phoenix LiveView. WebTransport is a new web API that offers efficient, low-latency, and secure communication channels between web applications and servers. Integrating this API would enhance the real-time capabilities of LiveView applications and provide several benefits.

**Benefits of WebTransport:**
- Low-latency communication: WebTransport minimizes round trips and enables proactive data transmission, resulting in improved performance and user experience.
- Multiplexing: WebTransport allows for multiplexing multiple data streams over a single connection, optimizing resource utilization.
- Stream prioritization: WebTransport supports stream prioritization, ensuring critical data is delivered promptly.

**Proposal:**
I propose adding support for the WebTransport API in Phoenix LiveView.
This could involve:
- Introducing WebTransport as a transport layer option alongside WebSocket.
- Providing hooks or callbacks for handling WebTransport events and data streams.
- Updating documentation to guide developers on using WebTransport in LiveView applications.

I believe that incorporating WebTransport support inLiveView would greatly enhance the framework and enable developers to build even more responsive and efficient real-time web applications.

**Comment by josevalim** [comment]
This is a big ask that is not in our priority right now. Folks are to experiment and implement additional Phoenix Channel transports, which will then be transparently used by LV.

**Comment by o-t-w** [comment]
WebTransport is now a more mature technology implemented in Firefox and Chrome/Edge. I think it would be good to rethink this decision.
