### ISSUE TITLE
Inconsistent or unclear stream :limit behaviour (regression from 0.19.0)

### ISSUE THREAD

**Issue by rktjmp** [phoenixframework/phoenix_live_view#2686]
### Environment

* Elixir version (elixir -v): 1.14
* Phoenix version (mix deps): 1.7.3
* Phoenix LiveView version (mix deps): 0.19.2

### Actual behavior

The docs describe limit as:

> :limit - the optional positive or negative number of results to limit on the
> UI on the client. As new items are streamed, the UI will remove existing
> items to maintain the limit.

Given a

- initial stream of items numbered 1 to 10
-  a button that adds 10 more 
-  a button that adds 1 more,

Interacting gives the following results (creation and updating all use the given at values):

| at  | limit | initial | add 10 (stream)               | add 1 (stream_insert)             |
| --- | ---   | ---     | ---                    | ---               |
| -1  | 5     | 1..10   | 1..5,11..20 (15 items) | 1..5,11 (6 items) |
| 0   | 5     | 10..1   | 20..11 (10 items)      | 11..7  (5 items)  |
| -1  | -5    | 1..10   | 11..20 (10 items)      | 7..11 (5 items)   |
| 0   | -5    | 10..1   | 20..11,5..1 (15 items) | 11,5..1 (6 items) |

Related: https://github.com/phoenixframework/phoenix_live_view/issues/2666

### Expected behavior

- `limit` would have an effect on the initial render, or the documentation reflects that it only applies on DOM updates
  - The docs *sort of* imply this with the language "As new items are streamed...", "while appending new items", and the examples, but I don't think it's clear that the option *doesn't* apply to any initial render.
- `limit` when applied to `stream_insert` and `stream` would always limit the total number of dom elements to the given value, even if this would discard all new elements.
  -  I.e. with `at: -1, limit: 5`, where we are appending items and limiting the UI to the first 5, appending an item to 5 existing should have no visible effect.

| at  | limit | initial | add 10                 | add 1             | expected
| --- | ---   | ---     | ---                    | ---               | --
| -1  | 5     | 1..10   | 1..5,11..20 (15 items) | 1..5,11 (6 items) | 1..5 or 1..5
| 0   | 5     | 10..1   | 20..11 (10 items)      | 11..7  (5 items)  | 20..16 or 11..7 
| -1  | -5    | 1..10   | 11..20 (10 items)      | 7..11 (5 items)   | 16..20 or 7..11
| 0   | -5    | 10..1   | 20..11,5..1 (15 items) | 11,5..1 (6 items) | 5..1 or 5..1

or

- The documentation reflects the differing behaviour depending on operation, at and limit.

### code

```elixir
Application.put_env(:sample, Example.Endpoint,
  http: [ip: {127, 0, 0, 1}, port: 5001],
  server: true,
  live_view: [signing_salt: "aaaaaaaa"],
  secret_key_base: String.duplicate("a", 64)
)

Mix.install([
  {:plug_cowboy, "~> 2.5"},
  {:jason, "~> 1.0"},
  {:phoenix, "~> 1.7.2"},
  {:phoenix_live_view, "~> 0.19.2"}
])

defmodule Example.ErrorView do
  def render(template, _), do: Phoenix.Controller.status_message_from_template(template)
end

defmodule Example.HomeLive do
  use Phoenix.LiveView, layout: {__MODULE__, :live}
  alias Phoenix.LiveView.JS

  @limit 5

  def mount(_params, _session, socket) do
    {:noreply, socket} = handle_event("configure", %{"at" => "-1", "limit" => "5"}, socket)
    {:ok, socket}
  end

  def render("live.html", assigns) do
    ~H"""
    <script src="https://cdn.jsdelivr.net/npm/phoenix@1.7.2/priv/static/phoenix.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/phoenix_live_view@0.19.2/priv/static/phoenix_live_view.min.js"></script>
    <script>
      let liveSocket = new window.LiveView.LiveSocket("/live", window.Phoenix.Socket)
      liveSocket.connect()
    </script>
    <style>
      body { width: 80ch; margin: 20px auto;}
    </style>
    <%= @inner_content %>
    """
  end

  def render(assigns) do
    ~H"""
    <form phx-submit="configure">
      at: <input type="text" name="at" value={@at}/>
      limit: <input type="text" name="limit" value={@limit}/>
      <button type="submit">recreate stream</button>
    </form>

    <div>configured with at: <%= @at %>, limit: <%= @limit %></div>

    <button phx-click="insert_10">add 10</button>
    <button phx-click="insert_1">add 1</button>

    <ul id="items" phx-update="stream">
      <li :for={{id, item} <- @streams.items} id={id}><%= item.id %></li>
    </ul>
    """
  end

  def handle_event("configure", %{"at" => at, "limit" => limit}, socket) do
    socket =
      socket
      |> assign(limit: String.to_integer(limit), at: String.to_integer(at), last_id: 0)
      |> new_stream()

    {:noreply, socket}
  end

  def handle_event("insert_10", params, socket) do
    %{limit: l, at: a, last_id: last_id} = socket.assigns
    items = for n <- 1..10, do: %{id: last_id + n}
    opts = [at: a, limit: l]
    IO.inspect({:insert_10, items, opts})

    socket =
      socket
      |> assign(last_id: last_id + 10)
      |> stream(:items, items, opts)

    {:noreply, socket}
  end

  def handle_event("insert_1", params, socket) do
    %{limit: l, at: a, last_id: last_id} = socket.assigns
    item = %{id: last_id + 1}
    opts = [at: a, limit: l]
    IO.inspect({:insert_1, item, opts})

    socket =
      socket
      |> assign(last_id: last_id + 1)
      |> stream_insert(:items, item, opts)

    {:noreply, socket}
  end

  defp new_stream(socket) do
    %{limit: l, at: a} = socket.assigns
    items = for n <- 1..10, do: %{id: n}
    opts = [reset: true, at: a, limit: l]
    IO.inspect({:new_stream, items, opts})

    socket =
      socket
      |> assign(last_id: 10)
      |> stream(:items, items, opts)
  end
end

defmodule Example.Router do
  use Phoenix.Router
  import Phoenix.LiveView.Router

  pipeline :browser do
    plug(:accepts, ["html"])
  end

  scope "/", Example do
    pipe_through(:browser)

    live("/", HomeLive, :index)
  end
end

defmodule Example.Endpoint do
  use Phoenix.Endpoint, otp_app: :sample
  socket("/live", Phoenix.LiveView.Socket)
  plug(Example.Router)
end

{:ok, _} = Supervisor.start_link([Example.Endpoint], strategy: :one_for_one)
Process.sleep(:infinity)

```

**Comment by oohnoitz** [comment]
Did some digging and this did change between 0.19.0 and 0.19.1. The following change was introduced which seems to ignore pruning added items:

https://github.com/phoenixframework/phoenix_live_view/blob/v0.19.2/assets/js/phoenix_live_view/dom_patch.js#L152-L157

It does seem odd that we could exceed the limit when doing bulk insert with `stream/4` and with subsequent `stream_insert/4` it can remove items back down to the limit. Did some testing with the code changed to:

```javascript
childrenToRemove.forEach((removeChild) => {
  // don't reorder ignored inserts
  if (this.streamInserts[removeChild.id]) {
    delete this.streamInserts[removeChild.id];
  }
  this.removeStreamChildElement(removeChild);
});
```
