### ISSUE TITLE
<form method="dialog"> will disconnect the socket

### ISSUE THREAD

**Issue by Knovour** [phoenixframework/phoenix_live_view#2687]
### Environment

* Elixir version (elixir -v): 1.14.5
* Phoenix version (mix deps): 1.7.3
* Phoenix LiveView version (mix deps): 0.19.2
* Operating system: MacOS 13.4
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

In `<dialog>` element, you can use `<form method="dialog">` to close the dialog
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog#simple_example

In Liveview, this method will disconnect the socket
![截圖 2023-06-13 下午4 12 16](https://github.com/phoenixframework/phoenix_live_view/assets/893846/7bf9a153-1554-44e6-96dc-f45ce4a02258)

```html
<button onclick="document.querySelector('dialog').showModal()">open dialog</button>
<dialog>
  <form method="dialog">
    <button>close</button>
  </form>
</dialog>
```
[Demo](https://github.com/Knovour/liveview_dialog_test)

If use the close method in JavaScript, socket will remain connected.

### Expected behavior

Close dialog by `<form method="dialog">` without disconnect.

**Comment by ramuuns** [comment]
seems like this is something that `DOM.isUnloadableFormSubmit` doesn't handle.

One could stick something like this in that method to make the issue go away:
```
if ( e.srcElement && e.srcElement.method === "dialog" ) { return false }
```
