### ISSUE TITLE
Phoenix LiveView 0.19 changed the behaviour of the `rest` attribute for components

### ISSUE THREAD

**Issue by vermaxik** [phoenixframework/phoenix_live_view#2688]
### Environment

* Elixir version (elixir -v): Elixir 1.14.3
* Phoenix version (mix deps): 1.7.2
* Phoenix LiveView version (mix deps): 0.19.2 (reproducible from 0.19.0)
* Operating system: MacOS 13.3.1
* Browsers you attempted to reproduce this bug on (the more the merrier): 
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: 

### Actual behavior
We have a lot of failing test (and functionality) due to this change:
```elixir
<.link href="/" phx_click="event" data_tooltip_part="link">Regular anchor link</.link>
```

renders as (respects to snake_case):
```html
<a href="/" data_tooltip_part="link" phx_click="event">Regular anchor link</a>
```

### Expected behavior
Changes attributes from snake_case to kebab-case:
```html
<a href="/" data-tooltip-part="link" phx-click="event">Regular anchor link</a>
```

It was especially more readable to use it as atom keys when you have a map separately and want to combine it with the rest of the attributes:

```elixir
attrs = %{phx_click: "event", data_tooltip_part: "link"}
<.link href="/" {attrs}>Link</a>
````

I want to clarify whether this was an intended change, because I don't see this change mentioned in the `Backwards incompatible changes` of changelog.

**Comment by chrismccord** [comment]
I don't remember this ever being intentional, but I think a change in Phoenix.HTML caused this. In any case, we don't intentionally convert casing of attributes anywhere in LV, and have no plans to do so as of now. Thanks!

**Comment by chrismccord** [comment]
I'll ad a note to the changelog about :phoenix_html changing behavior

**Comment by b-erdem** [comment]
It seems like this change was intentional. See here: https://github.com/phoenixframework/phoenix_live_view/pull/2546
