### ISSUE TITLE
Native JSON diff patch support

### ISSUE THREAD

**Issue by woutdp** [phoenixframework/phoenix_live_view#2695]
Hi,

Something I've been thinking about, feel free to close if this shouldn't be an issue (it's more of a discussionm but the discussion board is not available in this repo).

Currently, when diffing json inside a LiveView, it uses morphdom, just like all other diffs in LiveView. This is not ideal in the situation where you're passing json, especially if the json is big and changes quite frequently. This can happen when you're using and interacting with the json in the frontend.

Solutions for this already exist:
- server -> [json_diff_ex](https://github.com/olafura/json_diff_ex)
- client -> [jsondiffpatch](https://github.com/benjamine/jsondiffpatch)

or an [RFC 6902](https://datatracker.ietf.org/doc/html/rfc6902) compatible approach:

- server -> [jsonpatch](https://github.com/corka149/jsonpatch)
- client -> [JSON-Patch](https://github.com/Starcounter-Jack/JSON-Patch)

And a wrapper of those packages in the form of [live_json](https://github.com/Miserlou/live_json) is also available.

I think it would be quite neat if this was supported natively inside LiveView. It would reduce a lot of complexity of setting this up. And it would be supported inside function components as well as you move the responsibility to LiveView. Above approaches always have to have access to a socket to work. A function component in a dead view would pass on the json and ignore the optimization, but in a LiveView, it would use json patch instead of morphdom, reducing the amount of data that gets sent.

What if you have the following:

```elixir
def render(assigns) do
  ~H"""
  <%= @my_really_big_json_object %>
  """
end
```

Every time that object changes, it sends the entire thing over the wire.

If we could somehow 'tag' this variable as json, LiveView could do a json diff on it instead of a morphdom. Significantly reducing the amount of data that's being sent. Not sure about the syntax of this tagging (could it detect it automatically, no need for the developer to tag it?). 

I'm interested in this for use in [LiveSvelte](https://github.com/woutdp/live_svelte). It renders Svelte inside Phoenix dead views, as well as LiveViews. Under the hood, it's a function component. The issue is that it uses morphdom in the `data-props` attribute. If the json object that gets passed to Svelte gets too big, this becomes an issue. If LiveView supported this natively, I could tag this props attribute as json, and only the diff would be sent.

Besides my interest in this for LiveSvelte, I think it would be quite a nice optimization to LiveView for when you're sending json. Any time you have data you want to use in JS natively, you'll be using json, so it seems it could happen quite often.

Thoughts?

**Comment by josevalim** [comment]
I don't think we should provide this by default. My suggestion would be for you to generate the patches yourself and then pick them up and apply on the client using a hook?

**Comment by woutdp** [comment]
@josevalim thanks for the quick response!

That would be an approach but then I'd have to create 2 components depending on if I'm in a LiveView or a dead view. Since I'm using a function component, currently everything is in one component which is quite ergonomic. You don't really have to think about where the data is passing from, you just include the component and it works. LiveView takes care of it.

The main issue for LiveSvelte is that I don't have access to the previous state inside the function component, so I can't do a diff of the json and generate the patches.

Another approach is asking the user to generate the patches, but again not so ergonomic.

I think it could be in scope though. LiveView already does diffing, but just purely on HTML, this feels more like an optimization of something that already exists in LiveView.

**Comment by josevalim** [comment]
> That would be an approach but then I'd have to create 2 components depending on if I'm in a LiveView or a dead view.

You can have the same function component and have it render the LiveComponent internally. You need to ask users to pass the `@conn` or `@socket` as a `context={...}` attribute and then render accordingly (or ask them to pass the value of `connected?(socket)`).

> I think it could be in scope though. LiveView already does diffing, but just purely on HTML, this feels more like an optimization of something that already exists in LiveView.

The HTML diffing is really done in the client, we just render an HTML structure based on template rendering. This seems a completely different approach (and more abstractions for the LiveView team to maintain). We should provide abstractions to make it possible, not incorporate all needs. :)

**Comment by josevalim** [comment]
Sweet!
