### ISSUE TITLE
Resetting `stream/4` results in empty LiveComponent

### ISSUE THREAD

**Issue by oohnoitz** [phoenixframework/phoenix_live_view#2696]
### Environment

* Elixir version (elixir -v): Elixir 1.14.0 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): 1.7.3
* Phoenix LiveView version (mix deps): 0.19.2
* Operating system: Linux
* Browsers you attempted to reproduce this bug on (the more the merrier): FireFox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes

### Actual behavior

With LiveComponent as each item in a stream and using `reset: true` to bulk replace. The content of any LiveComponent that existed on the client before is now empty and marked with `data-phx-skip=""`. Once the you modify the state of the LiveComponent it will reset properly, but a subsequent reset when the state is unmodified will result in an empty element with the `PHX_SKIP` attribute applied.

Related commit/code: 
- https://github.com/phoenixframework/phoenix_live_view/blob/v0.19.2/assets/js/phoenix_live_view/rendered.js#L221-L224
- https://github.com/phoenixframework/phoenix_live_view/pull/686/commits/39e727476e3c1ef31400b5ec561e7ef3394b5163

Initial State

![image](https://github.com/phoenixframework/phoenix_live_view/assets/916311/b74940d1-ecc5-4b54-bb0f-a937b0abfb21)

After clicking `Reset`

![image](https://github.com/phoenixframework/phoenix_live_view/assets/916311/3f2853fe-c16a-4e6b-9ff4-7be1182c9c36)

```elixir
Application.put_env(:sample, Example.Endpoint,
  http: [ip: {127, 0, 0, 1}, port: 5001],
  server: true,
  live_view: [signing_salt: "aaaaaaaa"],
  secret_key_base: String.duplicate("a", 64)
)

Mix.install([
  {:plug_cowboy, "~> 2.5"},
  {:jason, "~> 1.0"},
  {:phoenix, "~> 1.7.3", override: true},
  {:phoenix_live_view, "~> 0.19.2"}
])

defmodule Example.ErrorView do
  def render(template, _), do: Phoenix.Controller.status_message_from_template(template)
end

defmodule Example.LiveComponent do
  use Phoenix.LiveComponent

  def render(assigns) do
    ~H"""
    <li id={@id}>
      <%= @text %>
    </li>
    """
  end
end

defmodule Example.HomeLive do
  use Phoenix.LiveView, layout: {__MODULE__, :live}

  def render("live.html", assigns) do
    ~H"""
    <script src="https://cdn.jsdelivr.net/npm/phoenix@1.7.3/priv/static/phoenix.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/phoenix_live_view@0.19.2/priv/static/phoenix_live_view.min.js"></script>
    <script>
      let liveSocket = new window.LiveView.LiveSocket("/live", window.Phoenix.Socket)
      liveSocket.connect()
    </script>
    <style>
      * { font-size: 1.1em; }
    </style>
    <%= @inner_content %>
    """
  end

  def render(assigns) do
    ~H"""
    <ul id="stream" phx-update="stream">
      <.live_component
        :for={{dom_id, item} <- @streams.items}
        module={Example.LiveComponent}
        id={dom_id}
        text={item.id}
      />
    </ul>

    <div>
      <button phx-click="add">Add</button>
      <button phx-click="reset">Reset</button>
    </div>
    """
  end

  def mount(_params, _session, socket) do
    socket =
      socket
      |> assign(:increment, 1)
      |> stream_configure(:items, dom_id: &"item-#{&1.id}")
      |> stream(:items, items())

    {:ok, socket}
  end

  def handle_event("add", _params, socket) do
    socket =
      socket
      |> update(:increment, &(&1 + 1))
      |> then(&stream_insert(&1, :items, %{id: &1.assigns.increment}))

    {:noreply, socket}
  end

  def handle_event("reset", _params, socket) do
    {:noreply, stream(socket, :items, items(), reset: true)}
  end

  defp items do
    [%{id: 1}]
  end
end

defmodule Example.Router do
  use Phoenix.Router
  import Phoenix.LiveView.Router

  pipeline :browser do
    plug(:accepts, ["html"])
  end

  scope "/", Example do
    pipe_through(:browser)

    live("/", HomeLive, :index)
  end
end

defmodule Example.Endpoint do
  use Phoenix.Endpoint, otp_app: :sample
  socket("/live", Phoenix.LiveView.Socket)
  plug(Example.Router)
end

{:ok, _} = Supervisor.start_link([Example.Endpoint], strategy: :one_for_one)
Process.sleep(:infinity)
```

### Expected behavior

The LiveComponent should not be empty and render `1` when the stream is reset.

**Comment by oohnoitz** [comment]
Did some more digging and noticed that when the [recursiveCIDToString](https://github.com/phoenixframework/phoenix_live_view/blob/v0.19.2/assets/js/phoenix_live_view/rendered.js#L205-L251) function is called:

- called on a component within a `Stream`, the DOM is mutated directly which is resulting in the issue.
- when it isn't used in combination with `Stream`, the `child` isn't mutated in the DOM directly at all.

Is there any reason for the `innerHTML` to be set to an empty string?

**Comment by bigardone** [comment]
👋🏼 Probably related to https://github.com/phoenixframework/phoenix_live_view/issues/2698

**Comment by oohnoitz** [comment]
@bigardone yeah, we are running into the same issue. I haven't had more time to look into this problem. It doesn't seem like we are able to differentiate between the various modes for `phx-update` to have the `PHX_SKIP` logic ignored for streams which may solve this problem.

**Comment by oohnoitz** [comment]
Looks like this has been fixed. Not seeing this issue anymore on the latest release.
