### ISSUE TITLE
Rendering issues with stream reset and live components

### ISSUE THREAD

**Issue by bigardone** [phoenixframework/phoenix_live_view#2698]
### Environment

* Elixir version (elixir -v): Elixir 1.14.4 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): 1.7.6
* Phoenix LiveView version (mix deps): 0.19.2
* Operating system: macOS
* Browsers you attempted to reproduce this bug on (the more the merrier): chrome, safari, firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

👋🏼 Hi there! I have a list of items and a form to filter them. I'm using `stream` to assign the collection to the socket, and on the `handle_params` callback, I fetch the new records depending on the user's search and stream them again using the `reset: true` options. If I use a function component to render each item in the stream, it works fine. On the other hand, if I use a live component, the UI starts having rendering issues:

### Initial render

<img width="1512" alt="image" src="https://github.com/phoenixframework/phoenix_live_view/assets/1090272/a240d507-2097-4575-8380-4eff70c4fc5e">

### Applying the filter

<img width="1494" alt="image" src="https://github.com/phoenixframework/phoenix_live_view/assets/1090272/32e0b1e1-cf57-4ac7-ae13-17c231526f45">

I have prepared a demo project showcasing the issue:

- Here it is using function components and working fine https://icy-fog-1916.fly.dev/
- Here it is using live components with the rendering issue https://icy-fog-1916.fly.dev/issue

[Here's the code](https://github.com/bigardone/live_view_stream_issue/blob/main/lib/live_view_issue_web/live/issue_page_live.ex#L39-L46): 

```elixir
      <div class="grid grid-cols-3 gap-6 auto-rows-auto mb-6" id="users_list" phx-update="stream">
        <.live_component
          :for={{id, user} <- @streams.users}
          module={UserComponent}
          id={id}
          user={user}
        />
      </div>
```

I've also tried wrapping the live component with a `div,` but it behaves the same:

```elixir
      <div class="grid grid-cols-3 gap-6 auto-rows-auto mb-6" id="users_list" phx-update="stream">
        <div :for={{id, user} <- @streams.users} id={id}>
          <.live_component module={UserComponent} id={"item_#{user.id}"} user={user} />
        </div>
      </div>
```

The source code is available at https://github.com/bigardone/live_view_stream_issue/tree/main

### Expected behavior

The expected behavior would be not having rendering issues as if it was using function components.

**Comment by bigardone** [comment]
This issue does not seem to happen anymore 🎉

**Comment by aqib008** [comment]
Hi, i am on `{:phoenix_live_view, "~> 0.19.5"}` and still facing same issue, should I upgrade to newest version?
