### ISSUE TITLE
message queue on client (to bridge disconect / offline periods)

### ISSUE THREAD

**Issue by testbird** [phoenixframework/phoenix_live_view#270]
Even if it is not default, it's easy to make a phoenix app load from local storage when offline:
https://www.botsquad.com/2018/03/07/phoenix-sw
https://elixirforum.com/t/progressive-web-apps-pwas/12876/14

Have you thought of making the live-view elements on the client apply user input locally right away first (unconfirmed DOM change), and then queue it to be sent, if or once online (again)?

**Comment by chrismccord** [comment]
We aren't taking feature requests at the moment. Thanks!
