### ISSUE TITLE
Test assert_patch fails

### ISSUE THREAD

**Issue by jg70** [phoenixframework/phoenix_live_view#2700]
### Environment

* Elixir version (elixir -v): 1.14.5
* Phoenix version (mix deps): 1.7.3
* Phoenix LiveView version (mix deps): 0.19.0
* Operating system: macOS Ventura 13.4
* Browsers you attempted to reproduce this bug on (the more the merrier): Safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

After phx.gen.auth I created a user admin page with phx.gen.live --no-context --no-schema --web admin.
When running mix test, it fails with:

![failed_test](https://github.com/phoenixframework/phoenix_live_view/assets/83812641/74a46a30-8b3f-441f-931b-d0fe977a06e4)

The views in myapp_web/live/admin/user_live are unchanged:
![index](https://github.com/phoenixframework/phoenix_live_view/assets/83812641/edf817ea-0243-4c40-9c05-5bdeb9938908)

![index_html_heex](https://github.com/phoenixframework/phoenix_live_view/assets/83812641/28256bfa-592a-4c77-baf0-2a01c47532bc)

![form_component_1](https://github.com/phoenixframework/phoenix_live_view/assets/83812641/42efe3b0-8e36-40f0-b6c9-cd421ef67113)
![form_compoent_2](https://github.com/phoenixframework/phoenix_live_view/assets/83812641/7937ae44-1e51-49ea-b495-c825cd41bb17)

The routes are there in the router:
![router](https://github.com/phoenixframework/phoenix_live_view/assets/83812641/1c2e9d3c-d612-4cd9-b94e-ea401a83befe)

Other pages I added as well like for accounts or licenses passes the test as expected, there a no issues.

### Expected behavior

mix test should not fail.

**Comment by josevalim** [comment]
Can you please try latest LV and if it persists can you please isolate the issue further into something it is easy for us to reproduce? The smaller the test case, the better. :) Thank you!

**Comment by josevalim** [comment]
Improved the docs, thanks!
