### ISSUE TITLE
attr/3 results in runtime error when required attribute of struct type is defined but not passed

### ISSUE THREAD

**Issue by maxmarcon** [phoenixframework/phoenix_live_view#2702]
### Environment

* Elixir version (elixir -v): Elixir 1.14.0 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps):  1.6.16 
* Phoenix LiveView version (mix deps): 0.19.2
* Operating system: MacOS
* Browsers you attempted to reproduce this bug on (the more the merrier): irrelevant
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: irrelevant

### Actual behavior

```
use Phoenix.Component

attr :id, :string
attr :field, Phoenix.HTML.FormField, required: true

def live_select(assigns) do
...
end
```

Then, using the component in a heex template:
```
<.live_select id="some_id" />
```

or in a test:
```
 render_component(&LiveSelect.live_select/1, id: "some_id")
```

results in:

```
** (FunctionClauseError) no function clause matching in LiveSelect."live_select (overridable 1)"/1    
    
    The following arguments were given to LiveSelect."live_select (overridable 1)"/1:
    
        # 1
        %{
          __given__: %{},
          debounce: 100,
          max_selectable: 0,
          mode: :single,
          option: [],
          style: :tailwind,
          tag: [],
          update_min_len: 1,
          user_defined_options: false
        }
    
    Attempted function clauses (showing 1 out of 1):
    
        defp live_select (overridable 1)((%{field: %Phoenix.HTML.FormField{}} = _) = assigns)
    
    (live_select 1.0.4) lib/live_select.ex:340: LiveSelect."live_select (overridable 1)"/1
    iex:2: (file)

```

**Note:** The runtime error disappears if I don't use a struct as the attribute's type or remove `required: true`.

### Expected behavior

As stated [in the docs](https://hexdocs.pm/phoenix_live_view/Phoenix.Component.html#attr/3-compile-time-validations), and in accordance to my previous experience, passing the wrong attributes to a function component should only result in compile-time warnings.

**Comment by josevalim** [comment]
The type validation is compile only, but required key checks may happen at runtime. Feel free to PR the docs if not clear. :) thanks!
