### ISSUE TITLE
Proposal: `after_handle_params` lifecycle hook

### ISSUE THREAD

**Issue by mayel** [phoenixframework/phoenix_live_view#2705]
This would be useful to to things like send the page title (which may have been set in a mount or handle_params function) to a breadcrumb component.

**Comment by josevalim** [comment]
Can you please provide more context. Examples of how it is done today and how such a feature would improve the status quo?

**Comment by josevalim** [comment]
Actually, I have updated the issues template to point to the Elixir Forum for new feature discussions, so please redirect it there. Thanks!

**Comment by mayel** [comment]
(will do when the forum is back up)
