### ISSUE TITLE
Doc string for global attributes not rendered in documentation

### ISSUE THREAD

**Issue by LostKobrakai** [phoenixframework/phoenix_live_view#2709]
### Environment

* Elixir version (elixir -v): 1.12
* Phoenix version (mix deps): 1.7.6
* Phoenix LiveView version (mix deps): 0.19.3
* Operating system: Mac OS
* Browsers you attempted to reproduce this bug on (the more the merrier): 
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:

### Actual behavior

Using `attr :rest, :global, doc: "Something"` doesn't fail to compile, but the documentation is not rendered by automatically appended chunk.

### Expected behavior

Documentation for global attributes is rendered as well. My usecase here is documented where the global attributes are set to.

**Comment by begedin** [comment]
Added a PR to fix this. There is definitely code there that wants to render full proper docs for a global attribute type, it just became unreachable.

**Comment by begedin** [comment]
One of the built in components renders it with linked PR:

<img width="720" alt="image" src="https://github.com/phoenixframework/phoenix_live_view/assets/1925540/5bdf4457-710a-4976-8419-fda75c9603c3">
