### ISSUE TITLE
Feature suggestion: implement handleEvent() API for `ondisconnect` fallback interactivity

### ISSUE THREAD

**Issue by thepeoplesbourgeois** [phoenixframework/phoenix_live_view#271]
Hi 👋. First-time issue-writer, long time … framework… admirer. 😐 

phoenix_live_view is an incredibly sophisticated framework. The fact that you're developing real-time UI interaction _via_ direct server communication is a minor revolution in web development in and of itself, so I'm nothing but admiring of what you're building.

I was looking at the `phoenix_live_view_example` implementations of the various `phx-` events, and it struck me that the pattern looked [very familiar](https://dev.to/rikschennink/the-fantastically-magical-handleevent-function-1bp4), and I began to think of what it might take to ensure that the client remained interactive even when it couldn't communicate with the server.

If the `socket.assigns` don't ever become too complicated, then I think it would be a minimal effort for immense payoff to store the map within the client, and to pass the AST of the `handle_event` functions through as part of the mount phase. 

The benefit of this would be that the client could retain interactivity by building a `handleEvent()` function tree that took over maintaining state `ondisconnect`, and then `onconnect` could send the latest version of `state` back, if it has been maintaining it.  

Since there may be processes that occur faster, or are part of a persistence model e.g., any database, on the server, the argument for maintaining a socket connection as much as possible is obvious; however, decoupling UX from server availability in cases of server unavailability seems like a huge win for both developer adoption and user satisfaction.

Thanks for reading!
🐾 

EDIT: Right, I forgot about the ~~challenge~~ opportunity: I didn't notice a significant way that the LiveView template was keeping track of where the values within `assigns` were being inserted. That doesn't mean the mechanism doesn't exist, just that it wasn't apparent from the template itself or from the interactions on the client side.

**Comment by chrismccord** [comment]
Thanks! We are working on our greater js interop story, but offline support is not in the plans today.
