### ISSUE TITLE
<.link patch... that apply actions are broken (until a page refresh)

### ISSUE THREAD

**Issue by Intelliractive** [phoenixframework/phoenix_live_view#2710]
### Environment

* Elixir version (elixir -v): 1.14.3
* Phoenix version (mix deps): 1.7.6
* Phoenix LiveView version (mix deps): 0.19.0
* Operating system: Windows 10 22H2(last major update)
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox
### Actual behavior
Links that apply new actions (:new, :edit) do not work until page reload
[Video](https://cloud.mail.ru/public/HpLb/uCMqmmtuv)
### Expected behavior
The buttons (<.link patch=...) must work as intended

**Comment by josevalim** [comment]
Can you please update our LiveView version and, if the issue persists, provide a way to reproduce the error?

**Comment by Intelliractive** [comment]
I've did so, bot the issue is still there. It's not present when `<.link navigate` or `<a>` is used, though.
[video№1](https://cloud.mail.ru/public/fTGp/MPKpuG854)
[video№2](https://cloud.mail.ru/public/MKJ7/kkkUAgMWb)
---
The error is reproducable just by generating a new project and running `mix phx.gen.live`. It is present in Firefox and Chrome
The app is run sometimes with admin rights, sometimes without, from a batch file (I highly doubt this causes problems, that is just a command).

**Comment by josevalim** [comment]
Hi @Intelliractive, when you open up an issue, it gives you an example for a single file Phoenix app. Can you please reproduce the issue with it? I understand it is easy to reproduce but that’s still time we have to spend (and sometimes we fail) and we have to maximize time fixing bugs instead!

**Comment by chrismccord** [comment]
I cannot recreate this on latest phoenix and LiveView, so we need to know more

**Comment by Intelliractive** [comment]
Hello again! I tried to achieve this issue in a new project, but didn't succeed. Could this be an issue with the root layout (I put it on mount in a live session)?

**Comment by Intelliractive** [comment]
I stopped putting own root_layout instead of `:root`, but the issue persists

**Comment by chrismccord** [comment]
We can't say without a reproduction, but I don't believe this an issue on our side. Note that you can only patch between LV's in the same live session in the router, so it's possible that is your issue. Thanks!

**Comment by Intelliractive** [comment]
I figured out the issue was Tailwind CDN (I refused to install Tailwind in the beginning). After installing Tailwind with [your installer](https://github.com/phoenixframework/tailwind), all the things work properly.
