### ISSUE TITLE
Maybe a bug - on ancestor state change, element position lost when in fixed container

### ISSUE THREAD

**Issue by DaTrader** [phoenixframework/phoenix_live_view#2711]
### Environment

* Elixir version (elixir -v): 1.14.4
* Phoenix version (mix deps): 1.7.3
* Phoenix LiveView version (mix deps): 0.18.8
* Operating system: Linux Mint
* Browsers you attempted to reproduce this bug on (the more the merrier):  FF, Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

Having a function component that conditionally renders a modal ( as in `:if={ ..}`). This modal is a window-wide overlay with the visible element absolute positioned in it.  The position of the visible element is set relative to its fixed container by JavaScript code (invoked in the element's Alpine's `x-init`) so it can be anywhere in the viewport. The function component is used in LiveComponents that themselves are items in the streams. This all works splendid most of the time.

However, when one such LiveComponent state changes, the modal visible element's positioning gets reset and the element ends up in the 0,0 corner of its fixed container. The Alpine's `x-init` code does not get re-invoked nor it should.

Now, is this a bug and if so, are there any plans to fix it in the near future? Asking because otherwise I need to plan to redesign such stateless components as LiveComponents to hopefully avoid this position reset.

### Expected behavior

Regardless of the changes made to the LiveComponent state containing the said stateless component, the elements in it should keep the position set by the JS code when they are first loaded.

**Comment by josevalim** [comment]
If the element doesn’t have an ID, then this is expected behavior, as the element may be added/removed as we patch the page. This is why we require ids for hooks and similar state full components.

**Comment by DaTrader** [comment]
But the element DOES have an id.

**Comment by josevalim** [comment]
I see, so it is hard to say without looking at a minimal app that reproduces the issue. Please do provide a single file one, thanks!

**Comment by josevalim** [comment]
Please let us know if there is a way to reproduce it, thanks!

**Comment by DaTrader** [comment]
@josevalim This is not right. Just because I haven't yet found the time to create a demo app reproducing it, it doesn't mean it's gone away. All the stream bugs I have reported so far are still there. 

For your info, what frustrates me the most is the fact that when it comes to streams the v0.19.x behaves worse than v0.18.18 in some aspects while the upgrade itself cannot be done without changes to code. 

In August I will take the time to study each of the cases in which I use streams where they don't behave as they should and I will provide a demo hopefully reproducing all the bugs or will close the issues myself in the cases it was my mistake.

**Comment by josevalim** [comment]
I will be glad to reopen it if we can reproduce it, but if we cannot reproduce it, there is nothing we can do. It may be a LV bug, it may not, and keeping only actionable issues helps a lot with issues tracker maintenance (otherwise every person triaging needs to go through issues they can’t act on).

**Comment by DaTrader** [comment]
@josevalim A promise made is a promise kept.

Please see the same repo as for the bugs reproduced yesterday: https://github.com/DaTrader/lv_bugs_0_19_5

**Comment by josevalim** [comment]
Excellent. Let's continue tracking that on #2657 and we break it apart if the bugs need to fixed in isolation.

**Comment by josevalim** [comment]
To follow up from #2657, this was indeed not a bug, hence it is why it is important for us to reproduce it otherwise it is best to close it to help keep the house clean. :)
