### ISSUE TITLE
`stream_insert` bug?

### ISSUE THREAD

**Issue by wojtekmach** [phoenixframework/phoenix_live_view#2713]
### Environment

* Elixir version (elixir -v): 1.15.0
* Phoenix version (mix deps): 1.7.6
* Phoenix LiveView version (mix deps): 0.19.3
* Operating system: macOS
* Browsers you attempted to reproduce this bug on (the more the merrier): Safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:

### Actual behavior

I'm trying to use `stream_insert` to update an existing element:

```elixir
  @rows [
    %{id: 1, value: 1},
    %{id: 2, value: 2},
    %{id: 3, value: 3}
  ]

  def mount(_params, _session, socket) do
    {:ok, stream(socket, :rows, @rows)}
  end

  def render(assigns) do
    ~H"""
    <ul>
      <li :for={{_, row} <- @streams.rows}>
        <%= row.value %>
        <button phx-click="inc" phx-value-id={row.id}>+</button>
      </li>
    </ul>
    """
  end

  def handle_event("inc", %{"id" => id}, socket) do
    row = Enum.find(@rows, &(&1.id == String.to_integer(id)))

    socket =
      stream_insert(
        socket,
        :rows,
        Map.update!(row, :value, &(&1 + 1))
      )

    {:noreply, socket}
  end
```

It's rendered as:

<img width="155" alt="image" src="https://github.com/phoenixframework/phoenix_live_view/assets/76071/8513cbad-b73b-4093-9eac-051fe6a5fb94">

However when I click on any button only that one element gets updated and all the other ones are removed. For example, after clicking + on 1, I get:

<img width="114" alt="image" src="https://github.com/phoenixframework/phoenix_live_view/assets/76071/7c3fac3a-707b-441c-842e-ad331e7c67d5">

Here's a full Mix install script:

<details>
Application.put_env(:sample, Example.Endpoint,
  http: [ip: {127, 0, 0, 1}, port: 5001],
  server: true,
  live_view: [signing_salt: "aaaaaaaa"],
  secret_key_base: String.duplicate("a", 64)
)

Mix.install([
  {:plug_cowboy, "~> 2.5"},
  {:jason, "~> 1.0"},
  {:phoenix, "~> 1.7.0"},
  {:phoenix_live_view, "~> 0.19.3"}
])

defmodule Example.ErrorView do
  def render(template, _), do: Phoenix.Controller.status_message_from_template(template)
end

defmodule Example.HomeLive do
  use Phoenix.LiveView, layout: {__MODULE__, :live}

  @rows [
    %{id: 1, value: 1},
    %{id: 2, value: 2},
    %{id: 3, value: 3}
  ]

  def mount(_params, _session, socket) do
    {:ok, stream(socket, :rows, @rows)}
  end

  defp phx_vsn, do: Application.spec(:phoenix, :vsn)
  defp lv_vsn, do: Application.spec(:phoenix_live_view, :vsn)

  def render("live.html", assigns) do
    ~H"""
    <script src={"https://cdn.jsdelivr.net/npm/phoenix@#{phx_vsn()}/priv/static/phoenix.min.js"}></script>
    <script src={"https://cdn.jsdelivr.net/npm/phoenix_live_view@#{lv_vsn()}/priv/static/phoenix_live_view.min.js"}></script>
    <script>
      let liveSocket = new window.LiveView.LiveSocket("/live", window.Phoenix.Socket)
      liveSocket.connect()
    </script>
    <style>
      * { font-size: 1.1em; }
    </style>
    <%= @inner_content %>
    """
  end

  def render(assigns) do
    ~H"""
    <ul>
      <li :for={{_, row} <- @streams.rows}>
        <%= row.value %>
        <button phx-click="inc" phx-value-id={row.id}>+</button>
      </li>
    </ul>
    """
  end

  def handle_event("inc", %{"id" => id}, socket) do
    row = Enum.find(@rows, &(&1.id == String.to_integer(id)))

    socket =
      stream_insert(
        socket,
        :rows,
        Map.update!(row, :value, &(&1 + 1))
      )

    {:noreply, socket}
  end
end

defmodule Example.Router do
  use Phoenix.Router
  import Phoenix.LiveView.Router

  pipeline :browser do
    plug(:accepts, ["html"])
  end

  scope "/", Example do
    pipe_through(:browser)

    live("/", HomeLive, :index)
  end
end

defmodule Example.Endpoint do
  use Phoenix.Endpoint, otp_app: :sample
  socket("/live", Phoenix.LiveView.Socket)
  plug(Example.Router)
end

{:ok, _} = Supervisor.start_link([Example.Endpoint], strategy: :one_for_one)
Process.sleep(:infinity)

</details>

### Expected behavior

The list is properly updated.

**Comment by chrismccord** [comment]
The parent ul needs phx-update=“stream” :)

**Comment by chrismccord** [comment]
I will find a way to log on the client in these scenarios

**Comment by wojtekmach** [comment]
gah, thank you so much!

**Comment by wojtekmach** [comment]
I've updated the snippet to include `<ul id=x phx-update=x>` and `<li id=x>`:

```elixir
  def render(assigns) do
    ~H"""
    <ul id="rows" phx-update="stream">
      <li :for={{row_id, row} <- @streams.rows} id={row_id}>
        <%= row.value %>
        <button phx-click="inc" phx-value-id={row.id}>+</button>
      </li>
    </ul>
    """
  end
```

I noticed it works for every item but just _once_, subsequent clicks do nothing. Here's the full gist: https://gist.github.com/wojtekmach/c64012bdbfe8d630c41b274b3384dcca

**Comment by wojtekmach** [comment]
Please never mind, the issue is:

```
row = Enum.find(@rows, &(&1.id == String.to_integer(id)))
...
Map.update!(row, :value, &(&1 + 1))
```

`row` is always fetched fresh from `@rows` (from module body) every time, we never store updated `row` anywhere.
