### ISSUE TITLE
Events raised before child LiveView mount completes are handled by parent LiveView

### ISSUE THREAD

**Issue by schrockwell** [phoenixframework/phoenix_live_view#2727]
### Environment

* Elixir version (elixir -v): 1.14.0
* Phoenix version (mix deps): 1.7.6
* Phoenix LiveView version (mix deps): 0.19.4 (main)
* Operating system: macOS Ventura 13.3.1 (a)
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox 
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

See the single-file reproduction below.

1. Load `http://localhost:5001/`
2. Within 5 seconds of loading, click the "Child click" button
3. After 5 seconds has elapsed, note that `ParentLive` has crashed because `ParentLive.handle_event/3` was called, but it doesn't exist.

### Expected behavior

`ChildLive.handle_event/3` should be called.

### Reproduction

```elixir
Application.put_env(:sample, Example.Endpoint,
  http: [ip: {127, 0, 0, 1}, port: 5001],
  server: true,
  live_view: [signing_salt: "aaaaaaaa"],
  secret_key_base: String.duplicate("a", 64)
)

Mix.install([
  {:plug_cowboy, "~> 2.5"},
  {:jason, "~> 1.0"},
  {:phoenix, "~> 1.7.0"},
  {:phoenix_live_view,
   github: "phoenixframework/phoenix_live_view", ref: "5a625b653ea1259847fe556ed170ec2b9ae548e3"}
])

defmodule Example.ErrorView do
  def render(template, _), do: Phoenix.Controller.status_message_from_template(template)
end

defmodule Example.ChildLive do
  use Phoenix.LiveView, layout: false

  def mount(_params, _session, socket) do
    # Simulate a long loading time
    if connected?(socket) do
      :timer.sleep(:timer.seconds(5))
    end

    {:ok, socket}
  end

  def render(assigns) do
    ~H"""
    <button phx-click="click">Child click</button>
    """
  end

  def handle_event("click", _, socket) do
    IO.puts("good click")
    {:noreply, socket}
  end
end

defmodule Example.ParentLive do
  use Phoenix.LiveView, layout: {__MODULE__, :live}

  defp phx_vsn, do: Application.spec(:phoenix, :vsn)
  defp lv_vsn, do: Application.spec(:phoenix_live_view, :vsn)

  def render("live.html", assigns) do
    ~H"""
    <script src={"https://cdn.jsdelivr.net/npm/phoenix@#{phx_vsn()}/priv/static/phoenix.min.js"}></script>
    <script src={"https://cdn.jsdelivr.net/npm/phoenix_live_view@#{lv_vsn()}/priv/static/phoenix_live_view.min.js"}></script>
    <script>
      let liveSocket = new window.LiveView.LiveSocket("/live", window.Phoenix.Socket)
      liveSocket.connect()
    </script>
    <style>
      * { font-size: 1.1em; }
    </style>
    <%= @inner_content %>
    """
  end

  def render(assigns) do
    ~H"""
    <%= live_render(@socket, Example.ChildLive, id: "child") %>
    """
  end
end

defmodule Example.Router do
  use Phoenix.Router
  import Phoenix.LiveView.Router

  pipeline :browser do
    plug(:accepts, ["html"])
  end

  scope "/", Example do
    pipe_through(:browser)

    live("/", ParentLive, :index)
  end
end

defmodule Example.Endpoint do
  use Phoenix.Endpoint, otp_app: :sample
  socket("/live", Phoenix.LiveView.Socket)
  plug(Example.Router)
end

{:ok, _} = Supervisor.start_link([Example.Endpoint], strategy: :one_for_one)
Process.sleep(:infinity)
```

**Comment by chrismccord** [comment]
Looks like this is already fixsed on main. Can you give it a shot on your side and report back? Thanks!

**Comment by schrockwell** [comment]
This is still reproducible on main. I checked with the single-file repro, and with a standalone Phoenix project.

**Comment by jmhossler** [comment]
Just want to chime in and say that we are also seeing this, though we aren't seeing it happen just with child/parent views. We are seeing it happen where some of our components are receiving events from 'cousins'. 

We have components that have no forms/no nested components that are receiving "validate" events that are meant for entirely different components on the page. It does seem to be a timing issue, because on our servers this issue only happens intermittently. Also seeing this on the latest version of phoenix_live_view (v0.19.4)
