### ISSUE TITLE
Separate "custom" from "system" assigns

### ISSUE THREAD

**Issue by PJUllrich** [phoenixframework/phoenix_live_view#273]
### Environment

* Elixir version (elixir -v): `1.9.0`
* Phoenix version (mix deps): `0.1.0`
* NodeJS version (node -v): `12.6.0`
* NPM version (npm -v): `6.9.0`
* Operating system: `macOS Mojave`

### Actual behavior

When I want to pass "custom/manually assigned" assigns (i.e. `assign(socket, :foo, "bar")`) from one LiveView (Parent) to a nested LiveView (Child), I have to pass every `assigns` parameter manually like this:
```
<%= Phoenix.LiveView.live_render(@socket, AppWeb.ChildLive, session: Map.take(assigns, [:foo, :other, :third])) %>
```

#### Problem
This manually selecting the parameters can become boilerplate, if many parameters need to be passed down to a nested LiveView or when the exact names of parameters are not known beforehand. A more dynamic way of passing all "custom" assigned parameters down to a nested LiveView would solve this.

##### Possible Solution 1
One could wrap all "custom" parameters into a e.g. `state` map (e.g. `assign(socket, :state, %{foo: "bar", other: "test"})`), but then all parameter insertions (e.g. `<%= @state.foo %>`) get updated whenever anything within the `state` map gets updated. This is bad for performance.

##### Possible Solution 2
Pass the `@socket.assigns` map into the Child LiveView (e.g. `..., session: @socket.assigns) %>`. The `@socket.assigns` map holds all "custom" assignments, which would be optimal for solving the problem. Unfortunately, the `@socket.assigns` map gets emptied once the socket is connected. The following code showcases this:

**parent.html.leex**
```
<%= Phoenix.LiveView.live_render(@socket, AppWeb.ChildLive, session: @socket.assigns) %>
```
**child_live.ex**
```elixir
def render(assigns) do
  Phoenix.View.render(AppWeb.PageView, "child.html", assigns)
end

def mount(params, socket) do
  IO.inspect("Connected: #{connected?(socket)}")
  IO.inspect(params)
  {:ok, socket}
end
```
**Output**
```
"Connected: false"
%{foo: "bar", other: "test"}

"Connected: true"
%{}
```
This solution would solve the problem nicely by only passing the "custom" assigns down to a Child LiveView. Unfortunately, it doesn't work (yet).

### Expected behavior
Is there an already existing solution for dynamically handing down "custom" assignments to nested LiveViews? 

If not, would it be possible to:

1. either don't empty the "Parent" LiveViews `@socket.assigns` map when the socket connection state changes?
1. Separate "custom" and "system" assignments with the `session` map looking like this for example:
```
%{
  state: {
    foo: "bar",
    other: "test"
  },
  socket: %Phoenix.LiveView.Socket{
    assigns: %{},
    changed: %{foo: true, other: true},
    connected?: true,
    endpoint: AppWeb.Endpoint,
    fingerprints: {nil, %{}},
    id: "phx-1IjJnkwW",
    parent_pid: nil,
    private: %{connect_params: %{}},
    redirected: nil,
    router: AppWeb.Router,
    view: AppWeb.ParentLive
  },
  view_module: AppWeb.PageView,
  view_template: "parent.html"
}
```
Then, one could simply pass down the `state` to a Child LiveView with:
```
<%= Phoenix.LiveView.live_render(@socket, AppWeb.ChildLive, session: @state) %>
```

**Comment by chrismccord** [comment]
Please see the `assign_new` documentation on passing parent state down to children. Thanks!
