### ISSUE TITLE
Issues rendering correct hexdoc links for functions with `attr` macro definitions and `@doc type: :component` directive

### ISSUE THREAD

**Issue by 03juan** [phoenixframework/phoenix_live_view#2735]
In the `@doc` for function declarations that interpolate `LVATTRDOCS` and have an `@doc type: :component` directive, the links generated in hexdocs point to line 1 in the github file.

This is consistent for all such functions in this document.

https://github.com/phoenixframework/phoenix_live_view/blob/5a625b653ea1259847fe556ed170ec2b9ae548e3/lib/phoenix_component.ex#L1913-L1941
![image](https://github.com/phoenixframework/phoenix_live_view/assets/4416345/61981ca3-4e36-4a16-a008-7aa3f0b51ece)

**Comment by CoderDennis** [comment]
The `@doc type: :component` directive seems unrelated to the issue. The problem exists whenever there is an `attr` on a function. I'm looking into a fix.

**Comment by 03juan** [comment]
Good catch @CoderDennis, so the issue is neither in the interpolation mechanism or the directive, but perhaps something in the `attr` macro messing with the line number resolution for the function in the AST?
