### ISSUE TITLE
If a form button has an icon inside, the icon disappears on form rerender after failed validations

### ISSUE THREAD

**Issue by a3kov** [phoenixframework/phoenix_live_view#2746]
### Environment

* Elixir version (elixir -v): Erlang/OTP 25 Elixir 1.14.5 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): 1.7.5
* Phoenix LiveView version (mix deps): 0.19.1
* Operating system: KUbuntu 22.04
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox stable
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:

### Actual behavior

If I add an icon (via built-in component) to a form button, it's displayed on initial render, but on subsequent renders (after failed form validation) its removed. The span is missing from the source completely.
```
<.button phx-disable-with="Deleting..." class="w-48"><.icon name="hero-trash-solid" class="w-5 h-5 mr-1" />Delete</.button>
```

### Expected behavior
The icon should not disappear.

**Comment by josevalim** [comment]
Can you please provide a minimal app that reproduces the issue? When you open up an issue we include a template for single file LV apps. :)

**Comment by a3kov** [comment]
Looks like its a bug with `phx-disable-with` if I remove it, the bug disappears

**Comment by a3kov** [comment]
Ok, I'll try to reproduce with single file LV

**Comment by chrismccord** [comment]
phx-disable-with only works for text content. Check the fomr-binding docs on toggling full block content on submit using the phx-submit-loading classes. thanks!
