### ISSUE TITLE
Streams block DOM updates on non-stream items

### ISSUE THREAD

**Issue by adkron** [phoenixframework/phoenix_live_view#2748]
### Environment

* Elixir version (elixir -v): Erlang/OTP 26 [erts-14.0.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.15.0 (compiled with Erlang/OTP 26)

* Phoenix version (mix deps):  phoenix 1.7.7
* Phoenix LiveView version (mix deps): phoenix_live_view 0.19.5

### Actual behavior

I have a table of items using the default LiveView generator. The items are using the new `stream` API. The table is wrapped in a form and has a checkbox for bulk actions, like delete-all, at each row. At the top of the table are two buttons for selecting and deselecting all.

The deselect_all action looks like this:

```elixir
  def handle_event("deselect_all", _params, socket) do
    {:noreply,
     socket
     |> assign(:bulk_checkouts, Ecto.Changeset.cast({%{}, %{id: {:array, :string}}}, %{"id" => []}, [:id]))}
  end
```

I can check as many boxes as I want, but the view doesn't change when I deselect all.

I can force the view to update by adding a call to reload the stream.

```elixir
  def handle_event("deselect_all", _params, socket) do
    {:noreply,
     socket
     |> stream(:books, Library.list_books())
     |> assign(:bulk_checkouts, Ecto.Changeset.cast({%{}, %{id: {:array, :string}}}, %{"id" => []}, [:id]))}
  end
```

### Expected behavior

I should not need to reload the stream in order to have the fields from the changeset updated on the front end. If I remove the stream and use a list of books, everything works as expected.

**Comment by chrismccord** [comment]
I need a minimal example that reproduces this as this isn't enough for me to say what is going. Thanks!

**Comment by josevalim** [comment]
When you create an issue, it links to the single file LV app you can use as a template.

**Comment by adkron** [comment]
Okay, I will update that.

**Comment by chrismccord** [comment]
Is the `@bulk_checkouts` assign used within the rows and supposed to change the checked state? if so it can't work any other way than re-inserting the stream items as they are gone from the server. To check, uncheck, or update the items in any way requires them to be restreamed so I think this is working as designed. Please let know if I'm misunderstanding and I aill reopen. Thanks!

**Comment by adkron** [comment]
That is the issue, but the checkboxes are not part of the stream. They have an id and value that comes from the stream, but they are part of a changeset.

I created a single file example but didn't use the checkboxes or a changeset. Instead, I used the count field from the basic example. I thought it would be less complicated.

https://gist.github.com/adkron/24113f371fb81845149c85e333cf7bb5

I don't know if it is a bug/feature request, but reloading the stream seems strange since it has stayed the same.

**Comment by chrismccord** [comment]
This is working as expected. The only way to re-render stream items is to have all the state you rendered the item with in the first place as that is the only way we can re-encounter the `@count` assign. Imagine you did `if @count > book.reader_count`. There is no way to re-execute the stream item code without the items. You can either reinsert the items or use live components to provide optimized diffs that hold onto minimal state, but there's no way around it here with streams.

**Comment by adkron** [comment]
Thanks.
