### ISSUE TITLE
Live View Doesn't Dasherize While Phoenix Dasherize

### ISSUE THREAD

**Issue by b-erdem** [phoenixframework/phoenix_live_view#2749]
### Environment

* Elixir version (elixir -v): 1.14.3
* Phoenix version (mix deps): 1.7.7
* Phoenix LiveView version (mix deps): 0.19.5
* Operating system: MacOS Ventura
* Browsers you attempted to reproduce this bug on (the more the merrier): 
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:

### Actual behavior

When you provide element keys to Phoenix, it dasherize them. But after this change it's no longer dasherize keys: https://github.com/phoenixframework/phoenix_live_view/pull/2546

We have some Phoenix components that are used in Phoenix components and Live View components. This causes inconsistency when you write some components. Because if it's just a Phoenix component it'll dasherize but if it is used in Live View component it will not. How to solve this issue? Is there any recommended way to handle this?

Additionally, I'm adding this question from @josevalim's answer here: https://github.com/phoenixframework/phoenix_live_view/issues/2545#issuecomment-1477851364

> The question is if Phoenix LiveView wants to preserve this behaviour or not.

### Expected behavior

Element keys are consistent across all Phoenix and Live View components.

**Comment by chrismccord** [comment]
It's not clear what you're asking for or what issues exist? Can you provide code examples? Thanks!

**Comment by b-erdem** [comment]
Sorry for that. Here is an example:

`<.input value="123" { %{data_field1: "123", data_field2: "345"} } />`

Renders as

Version: `~0.19.0`:
`<input type="text" class="syn_input min-w-0" data_field1="123" data_field2="345" value="123">`

Version: `~0.18.0`
`<input type="text" class="syn_input min-w-0" data-field1="123" data-field2="345" value="123">`

This happens because there is this new change: https://github.com/phoenixframework/phoenix_live_view/blob/main/lib/phoenix_live_view/tag_engine.ex#L893-L903

It bypass Phoenix.HTML's dasherizing function. But this causes for us to update lots places to adopt this change. Moreover when I use `<.input>` component in Live View components and regular Phoenix component and pass some dynamic parameters I get different behaviours as you can see from the examples above. Just want to make sure if this change is intended and if it's do you have any recommendations. Thanks!

**Comment by josevalim** [comment]
@b-erdem yes, the change is intentional, since the PR was merged after the discussion. However, you said this:

> Because if it's just a Phoenix component it'll dasherize but if it is used in Live View component it will not.

When this is the case?

**Comment by josevalim** [comment]
It is expected to get a different behaviour across versions. But do you get different behaviours within the same version?

**Comment by b-erdem** [comment]
Thanks for clarification.

The issue was if you wrap a component in another component and so on and using `Phoenix.HTML` functions dasherizes some keys if you directly passes them. So this was causing some confusions, in some places it dasherizes but in some it's not. But this not an issue for us anymore. We figured out to overcome this. Thanks for your help!
