### ISSUE TITLE
customize live_file_input accompanying text

### ISSUE THREAD

**Issue by MitchellJeppson** [phoenixframework/phoenix_live_view#2755]
### Environment

* Elixir version (elixir -v): 1.15.4
* Phoenix version (mix deps): 1.7.7
* Phoenix LiveView version (mix deps): 0.19.5
* Operating system: MacOS 
* Browsers you attempted to reproduce this bug on (the more the merrier): Safari 
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

When using live_file_input the accompanying text "no files selected" seems static and never changes, even when files are indeed selected. I saw this same behavior in [Chris McCords upload deep dive](https://www.phoenixframework.org/blog/phoenix-live-view-upload-deep-dive) and the pragmatic studio videos. Is this intended, or can we remove this text if it isn't used?

<img width="445" alt="Screenshot 2023-07-28 at 10 43 59 AM" src="https://github.com/phoenixframework/phoenix_live_view/assets/8956912/9705596a-36d5-4ce9-896b-c3cb0ff0a261">

### Expected behavior

I would expect that text to update at least to say the names of the files or have the ability to hide it if we can't update it.

Thanks!

**Comment by MitchellJeppson** [comment]
No idea what changed, but when I refreshed and tried again it was working and updating.

**Comment by MitchellJeppson** [comment]
Sorry for the whiplash on this issue. I figured out what causes the break and the fix. The file input text works as expected if I do not bind `phx-change` on the form. If I set that binding then that functionality breaks.

**Comment by MitchellJeppson** [comment]
@CoderDennis yep, good call. When I change to only allow one upload it works as expected. But when I change it to > 1 (even if I only choose to upload a single file) it does not show the mini preview or the updated text.

**Comment by MitchellJeppson** [comment]
@chrismccord no drag and drop. I'm selecting files using the popup file selector. I can get a minimal example to reproduce the issue if you think that would be helpful.

**Comment by CoderDennis** [comment]
As Chris mentioned, the browser is setting that text, so to gain control over it, you probably need to hide the native HTML file input and build your own. I've done that before in other frameworks, so maybe I'll work on an example of how to do it with LiveView.

**Comment by MitchellJeppson** [comment]
Maybe I am missing something here. The text and image preview do not behave as expected when `max_entries` > 1 AND `phx-update` is set on the form. Seems like we are causing the issue if phx-update is controlling the change?

**Comment by CoderDennis** [comment]
@MitchellJeppson maybe I'm missing something. I thought you were talking about the text on the native file input control and missed the fact that you were also having a problem with an image preview. Could you share an example of the code you're using to display image previews?

**Comment by chrismccord** [comment]
I don't believe there is anything we can do in this case as the browser is the one that handles that native text. You can hide the input and proxy click events to the hidden input if you want to customize the UI. Thanks!

**Comment by MitchellJeppson** [comment]
Just in case anyone else stumbles upon this with the same issue. I was able to find a workaround:

```html
<.live_file_input upload={@uploads.img} class="hidden" />

<label for={@uploads.img.ref} class="<styles like a button>">
    attach files
</label>

<label>
@file_chooser_text
</label>
```

then you can customize the @file_chooser_text as needed.
