### ISSUE TITLE
reset stream appends new elements relative to the existing ones instead of respecting the new order

### ISSUE THREAD

**Issue by DaTrader** [phoenixframework/phoenix_live_view#2767]
### Environment

* Elixir version (elixir -v): v1.14.4
* Phoenix version (mix deps): 1.7.7
* Phoenix LiveView version (mix deps): 0.19.5+ commit: fb03c851f5b9025b237f1554e511f4a3fb502228
* Operating system: Linux Mint
* Browsers you attempted to reproduce this bug on (the more the merrier):  FF, Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

When `stream/4` is invoked with a list of elements and the `:reset` option set to `true` on a stream with existing elements, the elements that are both among the existing ones and the new ones will maintain their position in the list while any new elements that are not already in the stream will be appended to it (instead of having the stream truly reset by preserving the provided list item order).

Repo branch:
https://github.com/DaTrader/lv_bugs_0_19_5/tree/bug_reset_disrespects_order

Steps:
1. http://localhost:4000/live
2. Click on the "Reset items" button below the list

As described, the stream reset will have a 6th item appended despite the fact that it's listed first in the list provided to the `stream/4` function.

### Expected behavior

The `reset` option should have the stream reset in the provided order of the items regardless of whether they already exist in the stream or not.

**Comment by nallwhy** [comment]
I'm also having this issue in my service.
So, I was trying to reproduce this issue, but I couldn't.

https://github.com/nallwhy/phoenix_live_view/commit/faafe4a195b88022fce3f51d3cd3a159fd2aeccd

Is it fixed? or Is there a something I missed?

**Comment by nallwhy** [comment]
I added one more patching and bug happens, but it's not a bug only about order, also about reset itself.

https://github.com/nallwhy/phoenix_live_view/commit/fc51da686c66e1090a2ad98b0074644f14f900c3

  1) test stream reset on patch (Phoenix.LiveView.StreamTest)
     test/phoenix_live_view/integrations/stream_test.exs:107
     Assertion with == failed
     code:  assert lv |> render() |> items_in_dom("items") == [
              {"items-1", "Apples"},
              {"items-2", "Oranges"},
              {"items-4", "Tomatoes"}
            ]
     left:  [{"items-3", "Carrots"}, {"items-4", "Tomatoes"}, {"items-1", "Apples"}, {"items-2", "Oranges"}]
     right: [{"items-1", "Apples"}, {"items-2", "Oranges"}, {"items-4", "Tomatoes"}]
     stacktrace:
       test/phoenix_live_view/integrations/stream_test.exs:141: (test)

**Comment by nallwhy** [comment]
Oh, it's about https://github.com/phoenixframework/phoenix_live_view/issues/2816

**Comment by chrismccord** [comment]
Please give main a shot and let us know if this resolves your issue. Thanks!

**Comment by DaTrader** [comment]
Thanks. Will do.

**Comment by DaTrader** [comment]
@chrismccord 

Unfortunately the issue is still there. The result is different this time but still incorrect - the prepended item ends up inserted as penultimate instead of appended as with the original bug. To replicate the bug simply update the demo app's `mix.exe` to use the main, start the app and click on the "Reset items" button.

Please reopen the issue.
