### ISSUE TITLE
error 'assign @conn not available in eex template' when using live_render

### ISSUE THREAD

**Issue by KaytonFletcher** [phoenixframework/phoenix_live_view#277]
### Environment

* Elixir version: 1.9.1
* Phoenix version: 1.4.9
* NodeJS version: v10.10.0
* NPM version: 6.9.0
* Operating system: MacOS

### Actual behavior

When attempting to access @conn within the index.html.leex template, I receive an error that it is not one of the assigns available. Within the list of available assigns I can see that it is not present. Is this the expected behavior?

**Controller**
```
defmodule MusicBrewWeb.PartyController do
  use MusicBrewWeb, :controller
  alias Phoenix.LiveView

  def index(conn, %{"id" => party_id}) do
    session_uuid = Ecto.UUID.generate()
    LiveView.Controller.live_render(conn,  MusicBrewWeb.PartyLive, session: %{access_token: conn.cookies["spotify_access_token"], party_id: party_id, session_uuid: session_uuid})
  end
end
```
**Within live view**
```
  def render(assigns) do
    MusicBrewWeb.PartyView.render("index.html", assigns)
  end
```
**View**
```
defmodule MusicBrewWeb.PartyView do
  use MusicBrewWeb, :view
end
```

**Comment by alexgaribay** [comment]
Yes this is expected. You'd have to explicitly pass the `conn` to the `session` for LiveView (which isn't recommended) and assign it to the socket.

**Comment by KaytonFletcher** [comment]
> Yes this is expected. You'd have to explicitly pass the `conn` to the `session` for LiveView (which isn't recommended) and assign it to the socket.

If you have the option to use live_link with @conn in templates (as per the documentation), should live_link not be used within live-rendered templates?

**Comment by benwilson512** [comment]
@KaytonFletcher live_link also takes `@socket`

**Comment by alexgaribay** [comment]
Ben is correct. `live_link` calls should be using the `@socket` when generating the routes. If you are using templates that are rendered underneath your LiveView template that naively expect a `@conn`, you can substitute the `@conn`, with `MyAppWeb.Endpoint` to get the same effect in most cases.

**Comment by johannesE** [comment]
> Yes this is expected. You'd have to explicitly pass the `conn` to the `session` for LiveView (which isn't recommended) and assign it to the socket.

@alexgaribay Why is this not recommended?

I'm getting the user in the template `Pow.Plug.current_user(@conn)`. Any security risks involved when I pass conn to the socket?

**Comment by johannesE** [comment]
I got a `** (ArgumentError) cannot deserialize #Function<0.70535915/1 in Plug.CSRFProtection.call/2>, the term is not safe for deserialization` when I tried to put the `conn` into the socket. The page loaded correctly, so I guess it would "only" impact the live part of liveview.
So I'm taking the long road instead..
