### ISSUE TITLE
Discrepancy in form change tracking

### ISSUE THREAD

**Issue by dvic** [phoenixframework/phoenix_live_view#2770]
### Environment

* Elixir version: **1.15.4**
* Phoenix version: **1.7.7**
* Phoenix LiveView version: **0.19.5**
* Operating system: **MacOS**
* Browsers you attempted to reproduce this bug on (the more the merrier): **Chrome, Safari, Firefox**
* Does the problem persist after removing "assets/node_modules" and trying again? **not applicable**

### Actual behavior

reproduced using https://gist.github.com/dvic/9cd697a7364819938fb05e9713e1ee12

There is a difference between using `@form[:field]` and `Access.get(@form, :field)`. 

In the former, change tracking works as intended, in the later, it is not working and acts as a normal function (always evaluated).

```elixir
    ~H"""
    <div>working: <.item item={Access.get(@form, :foo)} /></div>
    <div>not working: <.item item={@form[:foo]} /></div>
    <button phx-click="change_item">change</button>
    """
```

### Expected behavior

There should be no difference between `@form[:field]` and `Access.get(@form, :field)` in terms of change tracking.

Also: the reason why I found out about this is that I forgot about this change tracking feature in the first place 😅 We had some code that implement FormData for a struct and stored draft changes server side. So when you change a field and publish the changes, the value remains the same but the 'changed' status switches from 'changed' to 'not changed', but this was not picked up because the change tracking detected no changes (value and error were not changed).

So my question is: is it enough to have the behaviour of `Phoenix.HTML.Form.input_changed?/3` hardcoded (i.e., true only if *error or value for field changed*) Or should it be customisable by the FormData protocol or through some other way?

**Comment by dvic** [comment]
@josevalim thanks for the fast fix! :) What do you think about my comment at the end? Should this `input_changed?` behaviour be customisable or is it a bad pattern that I'm using? (storing field meta in the form source, like whether a field is translatable or what the server status of the field is). Otherwise maybe I should add some docs to `Field` to mention that you cannot rely on anything other than `errors` and `value` when using the field (when it comes to values that can change).

**Comment by josevalim** [comment]
You could pass this to the component though: `changed=@changes[:some_field]` and we will perform change tracking on `@changes[:some_field]`. The only reason we added this feature is because `@form` was already a rich data structure. But if you have maps, change tracking should just work.
