### ISSUE TITLE
inputs_for breaks css by creating empty whitespace when there is no inner html

### ISSUE THREAD

**Issue by Schultzer** [phoenixframework/phoenix_live_view#2772]
### Environment

* Elixir version (elixir -v): 1.14.3
* Phoenix version (mix deps): 1.7.7
* Phoenix LiveView version (mix deps): 0.19.4
* Operating system: macOS
* Browsers you attempted to reproduce this bug on (the more the merrier): Safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

Currently `inputs_for/4` are generating whitespace if an empty list is passed and skip_hidden is set to true breaking the CSS rule `empty`

### Expected behavior

The below code should work without displaying the border if there is no fruits or hidden inputs created.

```html
<ul class="empty:border-hidden border border-gray-200 divide-y divide-gray-200">
  <.inputs_for :let={fruit} field={@form[:fruits]} skip_hidden={true}>
     <li><%= fruit.name %></li>
   <./inputs_for>
</ul>
```

**Comment by josevalim** [comment]
Can you please send a PR? You may be able to check for an empty list and return an empty H sigil.

**Comment by Schultzer** [comment]
> Can you please send a PR? You may be able to check for an empty list and return an empty H sigil.

Yeah, what about the case where the list is not empty and there still wouldn’t be an inner block, e.g an if statement on the li.

**Comment by josevalim** [comment]
I am unsure. :( Although note that CSS Selectors 4 have retconned `:empty` to also ignore whitespace: https://drafts.csswg.org/selectors-4/#the-empty-pseudo

**Comment by Schultzer** [comment]
> I am unsure. :( Although note that CSS Selectors 4 have retconned `:empty` to also ignore whitespace: https://drafts.csswg.org/selectors-4/#the-empty-pseudo

I ended up solving this by using [:has](https://developer.mozilla.org/en-US/docs/Web/CSS/:has) and [:not](https://developer.mozilla.org/en-US/docs/Web/CSS/:not) since I had a checkbox in the inner block that I could match on.

```html
<ul class="[&:has(input[class~=peer]:not(:checked))]:border border-gray-200 [&:has(input[class~=peer]:not(:checked))]:divide-y divide-gray-200">
  <.inputs_for :let={fruit} field={@form[:fruits]} skip_hidden={true}>
     <li><%= fruit.name %></li>
   <./inputs_for>
</ul>
```

Looking at the test https://github.com/phoenixframework/phoenix_live_view/blob/214a4fa4cb00475e0d4fedcc0f8d8de87a52391b/test/phoenix_component/components_test.exs#L504 then it looks to me that no whitespace should be created in a function component, is this a valid assumption, and if so, do we have a bug in the rendering engine then?

**Comment by josevalim** [comment]
I don't think the engine guarantees there is no whitespace. As you said, the issue isn't on inputs_for either, but the contents that you pass to it (and then you skip).

**Comment by Schultzer** [comment]
> I don't think the engine guarantees there is no whitespace. As you said, the issue isn't on inputs_for either, but the contents that you pass to it (and then you skip).

Yeah, I took a closer look and tested a few scenarios, and it turns out that I would need to write my templates like:

```elixir
      template = ~H"""
        <.form for={@form}>
          <ul class="empty:border-hidden border border-gray-200 divide-y divide-gray-200"><.inputs_for :let={fruit} field={@form[:fruits]} skip_hidden={true}>
            <li :if={true}><%= fruit.name %></li>
          </.inputs_for></ul>
        </.form>
      """
```

To produce something like: 
```elixir
"<form method=\"post\">\n  \n  \n  \n    <ul class=\"empty:border-hidden border border-gray-200 divide-y divide-gray-200\"></ul>\n  \n</form>"
```
