### ISSUE TITLE
Progress callback not called for invalid upload entries.

### ISSUE THREAD

**Issue by LostKobrakai** [phoenixframework/phoenix_live_view#2775]
### Environment

* Elixir version (elixir -v): 1.14.4
* Phoenix version (mix deps): 1.7.7
* Phoenix LiveView version (mix deps): 0.19.5
* Operating system: MacOS
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox, Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:

### Actual behavior

When implementing an auto_upload live upload `handle_progress/3` is not called for files, which are invalid.

### Expected behavior

`handle_progress/3` to be called for all uploads, so the UI can do things like show errors or cancel the upload entry.

**Comment by LostKobrakai** [comment]
Hmm, seems like one can use the `handle_event("validate", _, socket)` callback, but I'd still think that invalid files should be reported to `handle_progress` – even with a progress value of `0`.

**Comment by chrismccord** [comment]
This is fixed on main. Thanks!
