### ISSUE TITLE
Supplied LiveComponent id is not available as an assign

### ISSUE THREAD

**Issue by TrevorHinesley** [phoenixframework/phoenix_live_view#2779]
### Environment

* Elixir version (elixir -v): Elixir 1.15.4 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): 1.7.7
* Phoenix LiveView version (mix deps): 0.19.5
* Operating system: macOS Ventura 13.2.1
* Browsers you attempted to reproduce this bug on (the more the merrier):  Chrome/Arc
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

I cannot access a LiveComponent's `id` from assigns, despite the documentation mentioning that it's accessible that way ([and examples showing it being used to construct custom dom IDs](https://hexdocs.pm/phoenix_live_view/0.19.0/Phoenix.LiveComponent.html#module-mount-and-update)). Visit localhost:4000/test after cloning [this example repo](https://github.com/TrevorHinesley/iderror) to see the error, or view below.

The error's stacktrace is below. Notice that the ID does appear to be in assigns' referenced socket, but is not available at the top-level outside of the socket itself:

```zsh
[error] #PID<0.502.0> running Phoenix.Endpoint.SyncCodeReloadPlug (connection #PID<0.501.0>, stream id 1) terminated
Server: localhost:4000 (http)
Request: GET /test
** (exit) an exception was raised:
    ** (KeyError) key :id not found in: %{
  __changed__: %{flash: true},
  flash: %{},
  myself: %Phoenix.LiveComponent.CID{cid: 1},
  socket: #Phoenix.LiveView.Socket<
    id: "phx-F3z9ptTrS9Q_uQkB",
    endpoint: IderrorWeb.Endpoint,
    view: IderrorWeb.LiveTest,
    parent_pid: nil,
    root_pid: nil,
    router: IderrorWeb.Router,
    assigns: #Phoenix.LiveView.Socket.AssignsNotInSocket<>,
    transport_pid: nil,
    ...
  >
}
        (iderror 0.1.0) lib/iderror_web/components/test_live_component.ex:14: anonymous fn/2 in IderrorWeb.TestLiveComponent.render/1
        (phoenix_live_view 0.19.5) lib/phoenix_live_view/diff.ex:386: Phoenix.LiveView.Diff.traverse/7
        (phoenix_live_view 0.19.5) lib/phoenix_live_view/diff.ex:711: Phoenix.LiveView.Diff.render_component/9
        (phoenix_live_view 0.19.5) lib/phoenix_live_view/diff.ex:657: anonymous fn/5 in Phoenix.LiveView.Diff.render_pending_components/6
        (elixir 1.15.4) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
        (stdlib 4.3.1.2) maps.erl:411: :maps.fold_1/3
        (phoenix_live_view 0.19.5) lib/phoenix_live_view/diff.ex:629: Phoenix.LiveView.Diff.render_pending_components/6
        (phoenix_live_view 0.19.5) lib/phoenix_live_view/diff.ex:143: Phoenix.LiveView.Diff.render/3
        (phoenix_live_view 0.19.5) lib/phoenix_live_view/static.ex:252: Phoenix.LiveView.Static.to_rendered_content_tag/4
        (phoenix_live_view 0.19.5) lib/phoenix_live_view/static.ex:135: Phoenix.LiveView.Static.render/3
        (phoenix_live_view 0.19.5) lib/phoenix_live_view/controller.ex:39: Phoenix.LiveView.Controller.live_render/3
        (phoenix 1.7.7) lib/phoenix/router.ex:430: Phoenix.Router.__call__/5
        (iderror 0.1.0) lib/iderror_web/endpoint.ex:1: IderrorWeb.Endpoint.plug_builder_call/2
        (iderror 0.1.0) deps/plug/lib/plug/debugger.ex:136: IderrorWeb.Endpoint."call (overridable 3)"/2
        (iderror 0.1.0) lib/iderror_web/endpoint.ex:1: IderrorWeb.Endpoint.call/2
        (phoenix 1.7.7) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4
        (plug_cowboy 2.6.1) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2
        (cowboy 2.10.0) mycomp/iderror/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.10.0) mycomp/iderror/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.10.0) mycomp/iderror/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
```

### Expected behavior

The component's `id` should be available as `@id` in the component given the documentation's explicit mention of it (quoted below) [and examples showing it being used](https://hexdocs.pm/phoenix_live_view/0.19.0/Phoenix.LiveComponent.html#module-mount-and-update):

> You must always pass the module and id attributes. The id will be available as an assign and it must be used to uniquely identify the component. All other attributes will be available as assigns inside the LiveComponent.

**Comment by josevalim** [comment]
You need to store the given assigns in your socket: https://github.com/TrevorHinesley/iderror/blob/main/lib/iderror_web/components/test_live_component.ex#L9

call assign(socket, assigns).

**Comment by TrevorHinesley** [comment]
Wow not sure how I missed that! Thanks 🤦🏼‍♂️
