### ISSUE TITLE
documentation bug

### ISSUE THREAD

**Issue by norpan** [phoenixframework/phoenix_live_view#2784]
In https://hexdocs.pm/phoenix_live_view/installation.html under "Layouts", the code for the root layout has an unfortunate mix of eex and heex. This took me a while to figure out, since I put the code in an eex file (heex did not work), and the csrf token was literally being set to "{Plug.CSRFProtection.get_csrf_token()}" instead of the value of that call.

That lead to csrf errors when connecting to the live socket, of course.

So it should be
```
<meta name="csrf-token" content="<%= Plug.CSRFProtection.get_csrf_token() %>" />
```
or the whole example should be converted to heex.

**Comment by josevalim** [comment]
Good find. Would you like to send a PR?

**Comment by norpan** [comment]
Ok, I'll make it heex then, since that seems to be what's used elsewhere, so it's actually the src= call below that should be converted.
