### ISSUE TITLE
LiveStream fails with `BadFunctionError` for the `dom_id` function when used after recompile

### ISSUE THREAD

**Issue by DaTrader** [phoenixframework/phoenix_live_view#2790]
### Environment

* Elixir version (elixir -v): 1.14.4
* Phoenix version (mix deps): 1.7.6
* Phoenix LiveView version (mix deps): 0.19.5+ 
* Operating system: Linux Mint
* Browsers you attempted to reproduce this bug on (the more the merrier):  FF, Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

Quite often when recompiling the umbrella project, even when the modules changed are not in the AppWeb application, when trying to insert in an existing stream (in a LiveComponent), the following is raised:

```
** (BadFunctionError) function #Function<3.3283069/1 in MyAppWeb.MyLiveComponent> is invalid, likely because it points to an old version of the code
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/live_stream.ex:62: Phoenix.LiveView.LiveStream.insert_item/4
    (phoenix_live_view 0.19.5) lib/phoenix_live_view.ex:1865: anonymous fn/3 in Phoenix.LiveView.update_stream/3
    (phoenix_live_view 0.19.5) lib/phoenix_component.ex:1305: Phoenix.Component.update/3
    (elixir 1.14.4) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
```

### Expected behavior

Obviously, it'd be nice if this stopped happening.

**Comment by chrismccord** [comment]
There's not anything we can do in this case. Your best bet is to used a captured function for the dom_id lookup if you want the LiveView reference to survive code upgrades. Thanks!

**Comment by DaTrader** [comment]
So there goes the reuse of my `dom_id/1` function ;)

**Comment by chrismccord** [comment]
I'l update the docs to use examples of captured functions. Thanks!

**Comment by DaTrader** [comment]
Thanks
