### ISSUE TITLE
0.19 does not emit multiple events on a form element like 0.18 did

### ISSUE THREAD

**Issue by jamesvl** [phoenixframework/phoenix_live_view#2796]
### Environment

* Elixir version (elixir -v): 1.15.4
* Phoenix version (mix deps): 1.7.x
* Phoenix LiveView version (mix deps): 0.19.x
* Operating system: Linux (Fedora)
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox, Chromium
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

In 0.19, only the `phx-focus` event is fired when clicking on a radio button label, even though the `<input>` element itself has both `phx-focus` and `phx-click` events tied to it.

### Expected behavior

In 0.18, a form element with both handlers would emit both events under the same user actions.

I do not know if this change of behavior was intentional or not; none of the 0.19.x releases has restored this behavior.

### Minimal example

```elixir
    <label>
      <input
        id="yes-radio"
        type="radio"
        name="radio-01"
        value="Yes"
        checked={@is_yes_checked}
        phx-click="got-click"
        phx-focus="got-focus"
        phx-value-val="yep"
        phx-value-addl={[1, 2]}
      />
      Yes
    </label>
```

Repo with minimal example of LiveView demos showing this change of behavior: https://github.com/jamesvl/lv_event_example

**Comment by guessthepw** [comment]
I can confirm I see this too 😢

**Comment by chrismccord** [comment]
I don't consider this an issue. We'd have to pick which order they fire first and document it. If you can say what you're trying to accomplish by having both on the input I could say more, but in general you almost never want a phx-click bound to an input. Thanks!
