### ISSUE TITLE
Phoenix.LiveView container set to body breaks LiveReload

### ISSUE THREAD

**Issue by mpotra** [phoenixframework/phoenix_live_view#2799]
### Environment

* Elixir version (elixir -v):
Erlang/OTP 26 [erts-14.0.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]
Elixir 1.15.2 (compiled with Erlang/OTP 24)

* Phoenix version (mix deps): phoenix 1.7.7
* Phoenix LiveView version (mix deps): phoenix_live_view 0.19.5
* Phoenix LiveReload version (mix deps): phoenix_live_reload 1.4.1 and 1.5.0-dev
* Operating system: Fedora Linux 38 (Workstation Edition) 6.4.6-200.fc38.x86_64
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox, Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

1. Warning in browser console:

> VM906 frame:1025 WebSocket connection to 'wss://localhost/phoenix/live_reload/socket/websocket?vsn=2.0.0' failed: WebSocket is closed before the connection is established.

2. LiveReload functionality not working - changes to heex files are reflected only when browser refresh.
3. No other errors reported in Elixir, Phoenix, HTTP server logs, system

### Expected behavior

LiveReload updates contents when heex files are modified.

### How to reproduce:

```
  def live_view do
    quote do
      use Phoenix.LiveView,
        layout: {TestyWeb.Layouts, :app},
        container: {:body, class: "bg-white antialiased"}

      unquote(html_helpers())
    end
  end
```
**Please note that `container` is set to `:body` !**

### Identified cause

Setting the LiveView container to `<body>` in conjunction with the current [root.html.heex](https://github.com/phoenixframework/phoenix/blob/main/installer/templates/phx_web/components/layouts/root.html.heex) actually makes the browser replace the first `<body>` with the "container" `<body>` element.

`LiveReload` injects a `<iframe>` as the last child of the request `<body>` in order to initialize its WebSocket.

Thus, LiveView configured with a `<body>` container replaces the `<body>` contents and the `<iframe>` injected by LiveReload is removed from the DOM tree. 
This in turn closes the LiveReload WebSocket that the `<iframe>` injects, and without this websocket all Live reloading functionality is no longer working.

This has no impact on Live sockets set via `<script>` (such as the ones used by LiveView).

Not sure if this belongs in `phoenix_live_reload`, but I feel like at least there should be [a documentation](https://github.com/phoenixframework/phoenix_live_view/blob/main/lib/phoenix_live_view.ex#L544) note or warning on this unexpected behaviour so that people are aware at least that using the `<body>` tag of a document as the root container for a LiveView will break LiveReload.

**Comment by josevalim** [comment]
I would rather document it here to not set the container as the whole body.

**Comment by chrismccord** [comment]
The document should only have a single body, so I don't consider this an issue. If you would like to submit a documentation PR to clarity, please let us know. Thanks!

**Comment by josevalim** [comment]
The issue here is the iframe being removed but I am pushing the docs. :)
