### ISSUE TITLE
Fields rendered conditionally with `case` don't get validation, clear when form updates

### ISSUE THREAD

**Issue by ashton314** [phoenixframework/phoenix_live_view#280]
### Environment

* Elixir version: 1.9.1
* Phoenix version: 1.4.6
* NodeJS version: v8.11.3
* NPM version: 5.6.0
* Operating system: macOS 10.14.5

### Actual behavior

Inside a form, when you use `case` to conditionally render some fields, these fields' errors don't display and any text entered into them gets deleted once another field gets selected. However, if you use an `if` block, everything works as expected.

I've created a sample repo here:

https://github.com/ashton314/phoenix_live_view_case_form_bug

### Expected behavior

Conditionally rendering form components with a `case` would work just as well as when using an `if`.

**Comment by chrismccord** [comment]
Can you verify if the `case` works as expected without the nested `if`. Note that currently the code is `case if ... do`. That will help us verify if it's a general case issue of an issue with nesting. Thanks!

**Comment by ashton314** [comment]
@chrismccord It's a general issue. I've updated my sample project so it just switches on a simple variable. I came across this issue in another project where the branches were matching on a struct.
