### ISSUE TITLE
Allow nesting of phx-update="ignore" and phx-update="replace" within a single LiveView

### ISSUE THREAD

**Issue by orsenkucher** [phoenixframework/phoenix_live_view#2802]
### Environment
- Phoenix version: phoenix 1.7.7, phoenix_live_view 0.19.5 
- Elixir version: Elixir 1.15.2 (compiled with Erlang/OTP 26)
- NodeJS version: v20.3.1

### Issue

We are integrating raw HTML, CSS, and JS exported from Webflow into our Phoenix application. This allows us to utilize designs, animations, and form structures directly from the Webflow export by adding them into the `priv/static` folder. We subsequently convert specific pages into LiveViews to populate with data from our backend.

However, when a page is converted to a LiveView, Phoenix LiveView takes over DOM diffing, causing the original JS functionality from the Webflow export to be bypassed. This affects our animations and other JS-based functionalities. To address this, we've been using a combination of `phx-update="ignore"` to preserve animations and JS behaviors, and `phx-update="replace"` by creating nested LiveViews and communicating between them using the `send` function.

It would significantly simplify our integration process if we could directly nest `phx-update="ignore"` and `phx-update="replace"` within a single LiveView. This would allow us to selectively disable and enable DOM diffing in specific regions of the DOM as per our requirements.

### Expected behavior

Allow the nesting of `phx-update="ignore"` and `phx-update="replace"` directives within a single LiveView, giving developers more granular control over DOM diffing on a per-region basis.

### Actual behavior

Currently, we need to use nested LiveViews to achieve this functionality, adding unnecessary complexity to our codebase.

**Comment by orsenkucher** [comment]
Hey @josevalim,

Thank you, I truly appreciate the response directly from elixir's father :)

I've set up a [minimal reproducible example](https://github.com/orsenkucher/nested_lv) that illustrates the redirect to the `/null` route issue when using `phx-update="ignore"` on parent LV with nested child LiveViews. It's a peculiar behavior after a server restart, which could be problematic especially in production environments 💀

For a quick code overview, you can check out the [commit diff](https://github.com/orsenkucher/nested_lv/commit/b334ee9dddbefb9d5ee41ea421bfbea961ea1ef4).

I'd greatly appreciate any help on this further. I think making Phoenix work seamlessly with static site generators have possibility to boost development process for many teams.

Got your point about the `dom.js` workaround too. Though it can be tricky to pinpoint every attribute that must be preserved and it seem not to work for attached callback listeners.

Can say that making LV `sticky: true` fixes this problem, but introduces another problem of using sticky component after all.

Lastly, here are a few lines of related logs from the browser:
```
error: unauthorized live_redirect. Falling back to page request {reason: 'stale'}
socket: disconnected for page nav
```

**Comment by josevalim** [comment]
Hi @orsenkucher, can you please open up a bug report with the issue and the link to the app? Thank you! The tokens are indeed stale but it should not redirect to null. :)

**Comment by orsenkucher** [comment]
@josevalim yep, sure! 
Done [Issue #2806](https://github.com/phoenixframework/phoenix_live_view/issues/2806).
