### ISSUE TITLE
updated hook triggered for multiple elements instead of only the updated element.

### ISSUE THREAD

**Issue by tcoopman** [phoenixframework/phoenix_live_view#2805]
### Environment

* Elixir version (elixir -v): 1.15.2
* Phoenix version (mix deps): 1.7.7
* Phoenix LiveView version (mix deps):0.19.5
* Operating system: mac
* Browsers you attempted to reproduce this bug on (the more the merrier): firefox, safari

### Actual behavior

I'm try to create a Highlight component that highlights something when data from the server changes.
I tried some other things first (as described here: https://elixirforum.com/t/recreating-a-highlight-component-with-liveview/58256) but found out that this probably needs to be solved by hooks, so I've tried with hooks in combination with the `updated()` callback.

*The issue*: With multiple `highlight` components. When I trigger a component to highlight, all components that have already run the callback in the past get triggered as well, even though the server doesn't rerender them.
Furthermore. It's not only the updated callback that is triggered, the component is actually rerendered on the client side (the attribute is reset again, while nothing happens on the server).

The *expected behaviour* is that only the element that changed, actually changes and runs the `updated` callback.

This video shows clearly what's wrong. As long as I have only clicked on 1 element, everything is fine. As soon as I click an other, you see the wrong behaviour.

https://github.com/phoenixframework/phoenix_live_view/assets/45546/142f76b9-4656-40eb-8fa6-fc6c4e2fbcdf

I've created a reproduction of the bug: https://github.com/tcoopman/liveview-hooks-bug
the first commit is the intial commit, the second commit is everything that's added for the bug.

*update*:
the issue only occurs when I change the `element` in the updated hook. If I don't run `this.el.setAttribute` the `updated` callback is not triggered multiple times.

**Comment by codeanpeace** [comment]
After a bit of tinkering, it looks like this is because the `data-highlight` never gets turned `off` on the server so it gets out of sync with the client after the initial click. I got it working without the unwanted highlighting in [this commit](https://github.com/tcoopman/liveview-hooks-bug/compare/main...codeanpeace:liveview-hooks-bug:main).

https://user-images.githubusercontent.com/2991389/269468121-4dbf83b6-66ce-4884-bbcd-9f1f3b3182dd.mov

**Comment by tcoopman** [comment]
That feels like a workaround. Also, if the client-side animation takes longer than a new rerender from the server, there will be some inconsistencies I think?

I've tried to update my code, so that the js code doesn't touch anything the server is tracking, but it still results in the same bug:

```js
Hooks.Highlight = {
  updated() {
		if (this.handler) {
			clearTimeout(this.handler);
		}
		this.el.setAttribute("data-highlight-client", "on");
			const handler = setTimeout(() => {
				this.el.setAttribute("data-highlight-client", "off");
			}, 1000);
			this.handler = handler;
			
 }
}
```

And I’ve removed all change tracking from the highlight component:
```elixir
  def highlight(assigns) do
    ~H"""
    <div id={@id} data-id={@id} phx-hook="Highlight" {@rest}>
      <%= render_slot(@inner_block) %>
    </div>
    """
  end
```

But the bug stays the same.
It seems to me that something goes wrong as soon as you change the element client-side? 

But isn't this something that hooks are for?
I considered using `phx-update=ignore`. But that doesn't work, because then the updated hooks are never called in the first place.

**Comment by chrismccord** [comment]
It is expected that the updated hook is called anytime the DOM differs from what the server sends. If you have your own js that is setting attributes then you'll necessarily have updated called when a patch occurs. Your js hook needs to handle this case (such as during the timer execution it maintains the attribute). This is expected and not an issue in this case. Thanks!
