### ISSUE TITLE
Unexpected Redirect to `/null` Route due to Stale Tokens in Nested LiveViews with `phx-update="ignore"`

### ISSUE THREAD

**Issue by orsenkucher** [phoenixframework/phoenix_live_view#2806]
### Environment
- Phoenix version: phoenix 1.7.7, phoenix_live_view 0.19.5 
- Elixir version: Elixir 1.15.2 (compiled with Erlang/OTP 26)
- NodeJS version: v20.3.1

### Actual behavior
I've set up a [minimal reproducible example](https://github.com/orsenkucher/nested_lv) that illustrates the redirect to the `/null` route issue when using `phx-update="ignore"` on parent LV with nested child LiveViews. It's a peculiar behavior after a server restart, which could be problematic especially in production environments. 

For a quick code overview, you can check out the [commit diff](https://github.com/orsenkucher/nested_lv/commit/b334ee9dddbefb9d5ee41ea421bfbea961ea1ef4).

Here are a few lines of related logs from the browser:
```
error: unauthorized live_redirect. Falling back to page request {reason: 'stale'}
socket: disconnected for page nav
```

### Expected behavior
The tokens are indeed stale but it should not redirect to `/null`.

**Comment by chrismccord** [comment]
Confirm, we must track and control the dom where the child LV is located.
