### ISSUE TITLE
Naming mismatch in `assign_new/3` documentation

### ISSUE THREAD

**Issue by codeanpeace** [phoenixframework/phoenix_live_view#2808]
Shouldn't the assign passed to the component match the assign passed to `assign_new`?
At the moment, the former is `color` whereas the latter is `bg_color`.

https://github.com/phoenixframework/phoenix_live_view/blob/fb111738d56745f37338867b9faea86eb9baa6e1/lib/phoenix_component.ex#L1072-L1098

**Comment by josevalim** [comment]
Yes, can you please send a PR?
