### ISSUE TITLE
Warning on unknown attributes for slots with blockless definitions causes problem due to lack of `:global` attributes for slots.

### ISSUE THREAD

**Issue by Serabe** [phoenixframework/phoenix_live_view#2811]
### Environment

* Elixir version (elixir -v): 1.14.5
* Phoenix version (mix deps): 1.7.7
* Phoenix LiveView version (mix deps): 0.19.5
* Operating system: macOS Ventura 13.5.1
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

When defining a slot without a `do` block, passed attributes are checked.

```elixir
defmodule FunctionalComponents do
  slot :paragraph, required: true
  def renderer(assigns) do
    ~H"""
    Something here
    """
  end

  def other(assigns) do
    ~H"""
    <.renderer>
      <:paragraph class="a-class" data-something="value" />
    </.renderer>
    """
  end
end
```

The code above will raise a warning because the attributes were unknown.

### Expected behavior

There is no way to define `:global` attributes in slots and [previously was pointed that we could not provide a `do` block and manually use them](https://github.com/phoenixframework/phoenix_live_view/issues/2265#issuecomment-1272110925). If attributes are checked, there is no way to provide _global_ attributes to slots without having warnings in our compilations, which is a common check in CI.

**Comment by josevalim** [comment]
Currently being discussed in #2331.
