### ISSUE TITLE
In tests, resetting a stream after adding items doesn't remove items

### ISSUE THREAD

**Issue by nathanalderson** [phoenixframework/phoenix_live_view#2816]
### Environment

* Elixir version (elixir -v): 1.14.1 (OTP 25)
* Phoenix version (mix deps): 1.6.15
* Phoenix LiveView version (mix deps): 0.20.0
* Operating system: Linux
* Browsers you attempted to reproduce this bug on (the more the merrier): n/a
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: n/a

### Actual behavior

In a LiveViewTest, sending items to the stream (via, for example, `stream(socket, :some-stream, [item1, item2])`) and subsequently resetting the stream (via `stream(socket, :some-stream, [], reset: true)`) does not remove the items from the DOM.

I have reproduced this in the testbench. See [this comparison](https://github.com/phoenixframework/phoenix_live_view/compare/v0.20.0...nathanalderson:phoenix_live_view:cc00678217849b47b07784a8b091f2e71307a9fb).

### Expected behavior

Resetting a stream should always remove the items from the DOM.

**Comment by danschultzer** [comment]
FWIW I opened this a while ago: https://github.com/phoenixframework/phoenix_live_view/pull/2677

I don't think this is the right way to solve it, but I couldn't grok the code path to map the phx stream. This was just the simplest fix I could think of.

**Comment by nathanalderson** [comment]
I updated my fork to test whether the recently merged #2864 would resolve this issue. It does not. The testcase I added to demonstrate the bug still fails in the same way. Updated branch is [here](https://github.com/nathanalderson/phoenix_live_view), for reference.
