### ISSUE TITLE
live_link supplemental options aren't forwarded to the underlying <a> tag

### ISSUE THREAD

**Issue by guidotripaldi** [phoenixframework/phoenix_live_view#283]
### Environment

* Elixir version (elixir -v):  1.8.2
* Phoenix version (mix deps): 1.4.9
* NodeJS version (node -v): 11.12.0
* NPM version (npm -v): 6.10.1
* Operating system: macOS 10.14.5

### Actual behavior
Supplemental options (e.g. `class`) passed to `live_link`  are ignored.

For example

  `live_link("Page 1", to: Routes.live_path(@socket, MyApp.MyPage, 1), class: "nav-item nav-link")`

is translated to:
  ```eex
   <a data-phx-live-link="push" href="/page/1">
     Page 1
   </a>
```
instead of the expected:

  ```eex
   <a data-phx-live-link="push" href="/page/1" class="nav-item nav-link">
     Page 1
   </a>
```

This way is not possible to customise the aspect of the link unless writing and managing manually the above html code.

### Expected behavior

`live_link` should extract the supplemental options popping out its specific options from the main list, and pass the remaining to the call to `Phoenix.HTML.Tag.content_tag/2`, likewise the `Phoenix.HTML.Link` functions.

**Comment by benwilson512** [comment]
I believe there's a PR open for this: https://github.com/phoenixframework/phoenix_live_view/pull/263

**Comment by alexgaribay** [comment]
Fixed in https://github.com/phoenixframework/phoenix_live_view/commit/8c2dc794ebe8a5f9430f580311e3a10f47b9655b.
