### ISSUE TITLE
assign_async gets stuck in a loading state when using multi-nested LiveViews

### ISSUE THREAD

**Issue by xMunch** [phoenixframework/phoenix_live_view#2841]
### Environment

* Elixir version (elixir -v): 1.14.3
* Phoenix version (mix deps): 1.7.7
* Phoenix LiveView version (mix deps): 0.20.0
* Operating system: WSL
* Browsers you attempted to reproduce this bug on (the more the merrier): (Chrome 117, Firefox 118)
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

When you have a multi-nested live view (at least 3 levels) only the root and deepest child assign_async task gets resolved.  It seems to be completely stuck in that state and reassigning the assign_async doesn't seem to help.

### Expected behavior

assign_async should work at all levels of nesting.

#### Media 
3-level nest example
![image](https://github.com/phoenixframework/phoenix_live_view/assets/735825/b2592dab-a27e-4465-9ed7-7235c5ef5ecc)

4-level next example
![image](https://github.com/phoenixframework/phoenix_live_view/assets/735825/716766b0-8052-446b-abeb-c56fc4c89218)

----

It could be entirely possible that LV wasn't intended to be used this way, I'm not entirely sure.

**Comment by josevalim** [comment]
Can you please provide a minimal app that reproduces this issue? A single file app would be even better, you can find a link to those on the new issue template!

**Comment by xMunch** [comment]
@josevalim I didn't see any links on the template.  Hopefully, this will suffice.
https://github.com/xMunch/async_test

**Comment by josevalim** [comment]
It is there on the description of Actual Behaviour but it is alright: https://github.com/wojtekmach/mix_install_examples/blob/main/phoenix_live_view.exs :) I was also on my phone when I replied, otherwise I'd have pasted it :)

**Comment by chrismccord** [comment]
I don't believe there is anything wrong on our side. In your example you only ever dispatch the `:parent_params` message a single time on `handle_params`, but you do it immediately, when no children are actually alive and present:

https://github.com/xMunch/async_test/blob/master/lib/async_test_web/live/test_live.ex#L39-L44

The children join after the client gets the render, so you are not yet sending to anyone here. You need to rethink your app/example for to really verify what your issues are, but in this example it's a user bug not aassign_async bug. If you can give another example I can take another look. Thanks!

**Comment by xMunch** [comment]
@chrismccord The thing is...  Logging the `text` assign in the render function shows 

```
Inner assigns: %Phoenix.LiveView.AsyncResult{
  ok?: false,
  loading: true,
  failed: nil,
  result: nil
}
Inner assigns: %Phoenix.LiveView.AsyncResult{
  ok?: false,
  loading: [:text],
  failed: nil,
  result: nil
}
Inner assigns: %Phoenix.LiveView.AsyncResult{
  ok?: true,
  loading: nil,
  failed: nil,
  result: "> Inner attached to parent"
}
[debug] MOUNT AsyncTestWeb.SecondaryLive
  Parameters: :not_mounted_at_router
  Session: %{"_csrf_token" => "vlaXt1p-yrHfaVKsdr-IW4YT"}
Second assigns: %Phoenix.LiveView.AsyncResult{
  ok?: false,
  loading: true,
  failed: nil,
  result: nil
}
Inner assigns: %Phoenix.LiveView.AsyncResult{
  ok?: true,
  loading: nil,
  failed: nil,
  result: "> Inner attached to parent"
}
[debug] Replied in 81µs
Second assigns: %Phoenix.LiveView.AsyncResult{
  ok?: false,
  loading: [:text],
  failed: nil,
  result: nil
}
Second assigns: %Phoenix.LiveView.AsyncResult{
  ok?: true,
  loading: nil,
  failed: nil,
  result: "> > Secondary attached to Inner"
}
[debug] MOUNT AsyncTestWeb.ThirdLive
  Parameters: :not_mounted_at_router
  Session: %{"_csrf_token" => "vlaXt1p-yrHfaVKsdr-IW4YT"}
Second assigns: %Phoenix.LiveView.AsyncResult{
  ok?: true,
  loading: nil,
  failed: nil,
  result: "> > Secondary attached to Inner"
}
Third assigns: %Phoenix.LiveView.AsyncResult{
  ok?: false,
  loading: true,
  failed: nil,
  result: nil
}
[debug] Replied in 111µs
Third assigns: %Phoenix.LiveView.AsyncResult{
  ok?: false,
  loading: [:text],
  failed: nil,
  result: nil
}
Third assigns: %Phoenix.LiveView.AsyncResult{
  ok?: true,
  loading: nil,
  failed: nil,
  result: "> > > Third attached to Second"
}
```

Yet `inner` and `secondary` still only show loading even though its logged as being changed.  Is this still a user error or am I crazy?

**Comment by xMunch** [comment]
@josevalim / @chrismccord I updated the [Repo](https://github.com/xMunch/async_test) to remove the subscriptions to parent LVs and message passing to children as it's not necessary to replicate the issue.  It's barebones, please take another look and let me know if it's still a "me" issue.
