### ISSUE TITLE
[Webcomponents] LiveView should not manage children nodes for given components

### ISSUE THREAD

**Issue by thomasnaudin** [phoenixframework/phoenix_live_view#285]
### Environment

* Elixir version (elixir -v): 1.9.0
* Phoenix version (mix deps): 1.4.9
* NodeJS version (node -v): 10.16.0
* NPM version (npm -v): 6.9.0
* Operating system: Fedora 30

### Actual behavior

I've got a problem using webcomponents (I use [Stencil](https://stenciljs.com/)) with LiveView.

I created a `<leaflet-map>` component. In my `.leex` template, I just use it this way :

```html
<leaflet-map data="{some_json_data}"></leaflet-map>
```

Client-side, the component generates some child nodes :

```html
<leaflet-map data="{some_json_data}">
    <div id="map-random-id"> <!--generated by the component-->
        <!--here some nodes generated by leaflet-->
    </div>"
</leaflet-map>
```

The first rendering works well.

The problem occurs when I update my `<leaflet-map>` `data` attribute: it seems that LiveView cleans all the children nodes.

### Expected behavior

Would it be feasible to have a way to declare to LiveView JS runtime not to manage children nodes for given components ?

**Comment by thomasnaudin** [comment]
Note: I just managed to make it work using shadow root – maybe the best way to do it ?

**Comment by chrismccord** [comment]
See the `phx-ignore` docs on marking a container as ignored when we patch the DOM. Thanks!

**Comment by thomasnaudin** [comment]
I tried `phx-ignore`, but it didn't work as it wouldn't let me update the attribute `data` of my component.
Anyway, it works wonderfully with shadow dom. ;)

Thanks a lot for your work, LiveView is a fantastic tool.
