### ISSUE TITLE
Phoenix.LiveView.UploadWriter does not work

### ISSUE THREAD

**Issue by TwistingTwists** [phoenixframework/phoenix_live_view#2850]
### Environment

* Elixir version (elixir -v): 1.15.6
* Phoenix version (mix deps): 1.7.7
* Phoenix LiveView version (mix deps): 0.19.5
* Operating system: linux Ubuntu 22.04
* Browsers you attempted to reproduce this bug on (the more the merrier):  chrome, firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

It should follow the S3Upload Writer and upload the file. However, `write_chunk/2` is randomly called. It is not called each time for some reason.

https://github.com/TwistingTwists/learning-concurrent-elixir/blob/master/sample.exs
Run this file like 
```
elixir sample.exs
```
Make sure to enter the following environment variables properly .

export AWS_ACCESS_KEY_ID="<yourkeyid>"
export AWS_SECRET_ACCESS_KEY="<yourkey>"
export AWS_S3_HOST_URL="<your_bucketid>.r2.cloudflarestorage.com"
export AWS_S3_BUCKET="sample-app"

also, allow CORS on the bucket to `localhost:5001 for all CRUD operations.

### Expected behavior

It should result in the file getting uploaded to S3. Instead `write_chunk/2` is not called. Directly, `close/2` is called. Which is weird.

**Comment by josevalim** [comment]
Thank you. Can you please try v0.20.0 as well and let us know if the results are any different?

**Comment by TwistingTwists** [comment]
and Phoenix 1.7.7 ?

**Comment by josevalim** [comment]
The Phoenix version should not matter in this case!

**Comment by TwistingTwists** [comment]
Yup. Still persists in liveview v0.20.0

**Comment by TwistingTwists** [comment]
I will report back in a couple of hours with logs. Outside at the moment.

**Comment by TwistingTwists** [comment]
https://github.com/TwistingTwists/learning-concurrent-elixir/blob/master/logs.md

Here are the logs. Can't reproduce "random" calls to write_chunk/2. This time, it doesn't get called at all! Not even once during 10 trials of script.

I am using CloudflareR2 as S3 store.

https://github.com/TwistingTwists/learning-concurrent-elixir/blob/master/sample.exs -- this is thee latest script I used for generating logs.

don't worry. I'll redact the keys very soon.

**Comment by TwistingTwists** [comment]
^^^ Updated above with latest logs after setting required environment variables.

**Comment by TwistingTwists** [comment]
https://github.com/ex-aws/ex_aws_s3/blob/main/lib/ex_aws/s3.ex#L1106

This does a `:post` at the url . Maybe clouldflare does not support `:post` . I will try changing it to `:put` that tomorrow. Let's see if that works. 

Allow me to debug it for one more day with above said change.

**Comment by chrismccord** [comment]
If you can provide more information about how the writer fails on our side, please let us know, but this looks squarely on your side with the API calls failing. Thanks!

**Comment by TwistingTwists** [comment]
Irrespective of API failing , I think the IO.inspect in write_chunk/2 would be printed. That is before the API call. I wonder why it doesn't show up in the logs.

**Comment by TwistingTwists** [comment]
> https://github.com/ex-aws/ex_aws_s3/blob/main/lib/ex_aws/s3.ex#L1106
> 
> This does a `:post` at the url . Maybe clouldflare does not support `:post` . I will try changing it to `:put` that tomorrow. Let's see if that works.
> 
> Allow me to debug it for one more day with above said change.

Just confirmed with API failing is not the issue. 
script: https://github.com/TwistingTwists/learning-concurrent-elixir/blob/master/only_aws_connectoin.exs
logs: https://github.com/TwistingTwists/learning-concurrent-elixir/blob/master/aws_s3.md 

Edit: Just figured out that I had `length(data)` in my IO.inspect/1 which was causing the write_chunk/2 to crash and hence I could never see the IO.inspect in write_chunk/2

instead I had to use `byte_size(data)` since the data is binary, not a list.

**Comment by TwistingTwists** [comment]
Maybe more useful stacktrace would help debug better ?
