### ISSUE TITLE
Channel.authorize_session/3 is called with %{"redirect" => nil} when implementing a custom serializer for LiveSockets

### ISSUE THREAD

**Issue by Zurga** [phoenixframework/phoenix_live_view#2860]
### Environment

* Elixir version (elixir -v): 1.14.4
* Phoenix version (mix deps):  1.7.7
* Phoenix LiveView version (mix deps): 0.19.5
* Operating system: NixOS
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox, Chromium
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior
After implementing the Msgpack encoder and decoder in the LiveSocket constructor as follows:
```assets/js/app.js
import {encode, decode} from "@msgpack/msgpack";
....

new LiveSocket("/live", Socket, {encode: (payload, callback) => callback(encode(payload)), decode: (payload, callback) => callback(decode(payload))})
```

When the Serializer is implemented and uses the following function for `decode!/2`:
```
def decode!(message, opts) do
  message
  |> Msgpax.unpack!()
  |> Phoenix.Socket.Message.from_map!()
end
```

The message sent on join has the redirect key in the payload set to `nil`. This triggers `authorize_session/3` on line 1444 of Phoenix.LiveView.Channel to be called. This will then eventually fail in `Phoenix.LiveView.Route.live_link_info/3`. 

Adding an `is_binary` guard to `Phoenix.LiveView.Channel.authorize_session/3`:1444 fixes this bug. i.e.:
```
defp authorize_session(%Session{} = session, endpoint, %{"redirect" => url}) when is_binary(url) do
```

### Expected behavior
Implementing the serializer with LiveSockets should work according to the documentation (which is great!).

**Comment by josevalim** [comment]
Can you please submit a PR for review? :)

**Comment by Zurga** [comment]
Will do, it seems my fix breaks other things. Gotta love tests :). I got a bit too excited hat I got MessagePack to work with only these small changes.

**Comment by chrismccord** [comment]
Can you verify whether this is already fixed in 0.20? We patched a case where the client wasn't sending the full url, but I don't believe it should have sent nil. By the way, it's not clear how `%{"redirect" => nil}` is happening in this case? The client should only be sending that key when there is a redirect.

**Comment by chrismccord** [comment]
Actually, I believe this could be the case of JSON dropping any key that has value `undefined`, which we rely on in the client. In this case, it's not a server issue but a client issue. I'm not sure if we should have LV or the serializers worry about this case though. Can you verify how msgpax js client handles `undefined` ?

**Comment by Zurga** [comment]
@chrismccord you are correct. I was unaware of this behavior. While copying the payload from the Chromium console I already noticed the key was missing, but did not make the link. The msgpax client does have the option to ignore undefined values. Thanks for your insight.

If the project is interested, I would be happy to write a guide on using Messagepack or other serializers with LiveView.

**Comment by chrismccord** [comment]
Other serializers is pretty niche for a guide, but sounds like a very valuable blog post. In this case I think passing the msgpack undefined option is the best bet, so closing as this is not an issue on our side. Thanks!
