### ISSUE TITLE
<select> elements (and ancestors) get `beforeUpdate` and `updated` lifecycle events on every render

### ISSUE THREAD

**Issue by borisgoro** [phoenixframework/phoenix_live_view#2866]
### Environment

* Elixir version (elixir -v): 1.15.6
* Phoenix version (mix deps): 1.7.7
* Phoenix LiveView version (mix deps): 0.20.0
* Operating system: MacOS 14.0
* Browsers you attempted to reproduce this bug on (the more the merrier): Safari, Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

In the code sample below, when the `val` assign is incremented, `beforeUpdate` and `updated` events are fired on `<div id="div2"...>` even though it is not affected by `val`. Events are not fired if the `<select>` element is removed.

### Expected behavior

Update events are not fired unless the element is actually changed.

###

LiveView

```elixir
  @impl true
  def mount(_, _, socket) do
    socket = socket |> assign(val: 0)
    {:ok, socket}
  end

  @impl true
  def render(assigns) do
    ~H"""
    <div id="div1" phx-hook="EventHook" phx-click="inc">
      <%= @val %>
    </div>

    <div id="div2" phx-hook="EventHook">
      <select id="sel">
        <option value="opt">opt</option>
      </select>
    </div>
    """
  end

  @impl true
  def handle_event("inc", _params, socket) do
    {:noreply, socket |> assign(val: socket.assigns.val + 1)}
  end
```

Hook

```javascript
const EventHook = {
  beforeUpdate () {
    console.info(`${this.el.id} beforeUpdate`)
  },

  updated () {
    console.info(`${this.el.id} updated`)
  }
}
```
Console

<img width="517" alt="image" src="https://github.com/phoenixframework/phoenix_live_view/assets/65460569/d236b7b2-f7ea-4b77-84bf-9d41bd3a79b9">

**Comment by 03juan** [comment]
Your `#sel` select's first option is being given a default `selected` attribute by the UA on first render, then the dom diff picks up that the server-sent html differs and replaces the element, to which the UA again adds a default `selected`... etc.

```html
<script>
  const EventHook = {
    mounted() { console.info(`$this.el.id} mounted`, this.el.innerHTML) },
    beforeUpdate () { console.info(`${this.el.id} beforeUpdate`) },
    updated () { console.info(`${this.el.id} updated`) }
}
</script>

  <div id="div1" phx-hook="EventHook" phx-click="inc">
    <%= @val %>
  </div>

  <div id="div2" phx-hook="EventHook">
    <select id="sel">
      <option value="opt">opt</option>
    </select>
  </div>

  <div id="div3" phx-hook="EventHook">
    <select id="sel2">
      <option value="opt" selected="">opt</option>
    </select>
  </div>

  <div id="div4" phx-hook="EventHook">
    <select id="sel3">
      <option value="opt">opt</option>
      <option value="opt2" selected>opt2</option>
    </select>
  </div>
</div>
```
![image](https://github.com/phoenixframework/phoenix_live_view/assets/4416345/f618bf90-cc03-4afa-82ef-d31f019837e9)

**Comment by josevalim** [comment]
Great find @03juan ❤️
