### ISSUE TITLE
Support async operations with liveview streams (assign_async => stream_async

### ISSUE THREAD

**Issue by hg-runs** [phoenixframework/phoenix_live_view#2870]
The new async functions around `assign_async` are **very** nice! Easy to setup and a good enhancement to phoenix liveview functionality.

In my opinion it is very likely that these functions will be used for database queries, which might or might not return a greater amount of data for the initial rendering.

Since the general recommendation is to use streams (which are also a great improvement and simplification) I would like to see a `stream_async` function supported

If this is not the proper place to ask for this: feel free to delete/close this issue

Sincerely

**Comment by chrismccord** [comment]
Please send feature requests/discussions to the forums. Thanks!

**Comment by Munksgaard** [comment]
For the record, I've posted a suggestion on the forums here: https://elixirforum.com/t/support-async-operations-with-liveview-streams/59863/7
