### ISSUE TITLE
JS.toggle behaves unexpectedly with phx-mounted and nested hidden elements

### ISSUE THREAD

**Issue by dylbyl** [phoenixframework/phoenix_live_view#2873]
### Environment

* Elixir version (elixir -v): Elixir 1.15.4 (compiled with Erlang/OTP 26)
* Phoenix version (mix deps): 1.7.9
* Phoenix LiveView version (mix deps): 0.20.1

### Actual behavior

If `JS.toggle/1` is used on a child element in `phx-mounted` of a hidden parent element, the child elements are toggled based on their parent's visibility. In other words, they're toggled `on` no matter what their individual stylings are.

When the example below mounts, both child spans are given `display: block` since the parent div has `display: none`. This is despite the second span already having `display: block`. When the parent div is clicked, the panel is opened with both spans already visible. Clicking the panel's "visibility toggle" toggles both spans on and off at the same time, rather than alternating from one another.

```
<div phx-click={JS.toggle(to: "#test-panel")}>click to show panel</div>
  <div id="test-panel" style="display: none;" phx-mounted={JS.toggle(to: "#test-panel span")}>
    <span style="display: none;">should start visible, after mount toggle</span>
    <span>should start hidden, after mount toggle</span>
    <div phx-click={JS.toggle(to: "#test-panel span")}>should toggle visibility between the two spans</div>
  </div>
</div>
```

### Expected behavior

`JS.toggle/1` toggles visibility based on the child's styling, not the visibility status of its parent element.

In the example above, I would expect `phx-mounted` to toggle `display: block` to the first child span, and `display: none` to the second. Thus when the parent div is clicked and the panel is opened, only one span is shown. Clicking the "visibility toggle" then alternates which span is shown.

**Comment by chrismccord** [comment]
I don't entire follow this scenario, but we must use the visibility of the child to know whether we can toggle it. If the parent is hiding it, it will necessarily not be visible regardless of the child's styling itself, which is expected. I don't believe there is anything to be done here on our side. If you want the first child of the hidden container to be visible when it is rendered, you can render it as visible, no? Thanks!

**Comment by dylbyl** [comment]
I forgot a single piece of this- that `phx-mounted` should be something more like `phx-mounted={if @first_option_starts_open, do: JS.toggle....}`. So it won't always be the same child hidden or shown once the panel is opened- that's all based on a user preference passed in through an assign.

That being said, I respect your answer and will find a workaround on my end. Thanks!
