### ISSUE TITLE
Push_navigate is 5-10x slower than using a .link component (with a sticky liveview in a layout)

### ISSUE THREAD

**Issue by Terbium-135** [phoenixframework/phoenix_live_view#2876]
### Environment

* Elixir version (elixir -v): **1.15.7**
* Phoenix version (mix deps): **github: "phoenixframework/phoenix"**
* Phoenix LiveView version (mix deps): github: **"phoenixframework/phoenix_live_view"**
* Operating system: **Linux Debian 12**
* Browsers you attempted to reproduce this bug on (the more the merrier): **Firefox, Chrome, Brave**
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: **N/A**

### Actual behavior
With the following sticky layout in the `app.html.heex` file:
```heex
<%= live_render(@socket, BackendWeb.Live.Components.Navbar,
  id: "workspace-sidebar-container",
  session: %{"locale" => @locale,
    "current_user" => @current_user,
    "current_path" => @nav_active_path
    },
  sticky: true,
  container:
    {:aside,
      class: "fullscreen:hidden flex-shrink flex-grow-0 bg-slate-200 dark:bg-slate-600"}
) %>
```

this loads in a fraction of a second:

```heex
<.link navigate={@path}>
  [...]
</.link>
```

and the following is very slow (almost needs around 5 seconds to load):

```elixir
<div phx-click={JS.push("navigate", value: %{path: @path})}>
  [...]
</div>
```

The handler is:

``` elixir
@impl true
def handle_event("navigate", %{"path" => path}, socket) do
  if path == socket.assigns.current_path do
    {:noreply, socket}
  else
    {:noreply, socket |> assign(current_path: path) |> push_navigate(to: path)}
  end
end

```
**With `sticky` set to `false` both methods are equally fast.**
### Expected behavior

Using either `.live` component or `push_navigate` should make no difference regarding the speed.

**Comment by josevalim** [comment]
Can you please provide a minimal application that reproduces the error? You can get a starting point from here: https://github.com/wojtekmach/mix_install_examples/blob/main/phoenix_live_view.exs

**Comment by Terbium-135** [comment]
Of course, but this will take a while.

In the meanwhile I noticed the (main?) reason for the delay is, that the navbar liveview gets mounted again despite being sticky:
```log
[2023-10-22 09:38:15.910] [debug] HANDLE EVENT "navigate" in BackendWeb.Live.Components.Navbar
  Parameters: %{"altKey" => false, "ctrlKey" => false, "path" => "/users", "shiftKey" => false, "target" => %{}}
[lib/backend_web/live/components/navbar.ex:326: BackendWeb.Live.Components.Navbar.handle_event/3]
binding() #=> [
  path: "/users",
  socket: #Phoenix.LiveView.Socket<
    id: "workspace-sidebar-container",
    endpoint: BackendWeb.Endpoint,
    view: BackendWeb.Live.Components.Navbar,
    parent_pid: nil,
    root_pid: #PID<0.7713.0>,
    router: BackendWeb.Router,
    assigns: %{
      flash: %{},
      current_path: "/tags",
      __changed__: %{},
      live_action: :show,
      locale: "de",
      reporting_expanded: false,
      balancing_expanded: false,
      current_user: nil,
      nav_active_path: "/tags"
    },
    transport_pid: #PID<0.7699.0>,
    ...
  >
]

[2023-10-22 09:38:15.911] [debug] Replied in 1ms
[2023-10-22 09:38:15.922] [debug] MOUNT BackendWeb.UsersPageLive
  Parameters: %{}
  Session: %{"_csrf_token" => "J8PjNkFemJ9Kuo0Pb1unUK15", "locale" => "de"}
[2023-10-22 09:38:15.922] [debug] Replied in 568µs
[2023-10-22 09:38:15.923] [debug] HANDLE PARAMS in BackendWeb.UsersPageLive
  Parameters: %{}
[lib/backend_web/nav_hooks.ex:18: BackendWeb.NavHooks.on_mount/4]
URI.parse(url).path #=> "/users"

[2023-10-22 09:38:15.924] [debug] Replied in 1ms
[lib/backend_web/nav_hooks.ex:18: BackendWeb.NavHooks.on_mount/4]
URI.parse(url).path #=> "/users"

[2023-10-22 09:38:25.879] request_id=F5Bd5uquB3oL_doAAyDh [info] GET /users
[lib/backend_web/live/components/navbar.ex:280: BackendWeb.Live.Components.Navbar.mount/3]
session #=> %{
  "_csrf_token" => "J8PjNkFemJ9Kuo0Pb1unUK15",
  "current_path" => "/users",
  "current_user" => nil,
  "locale" => "de"
}
```

**Comment by rktjmp** [comment]
Hopefully this isn't just noise.

When I looked at this yesterday (from the forum post), I thought it might be because `push_navigate` ends up stopping the liveview that runs that function, which is why the previous comment sees the sticky view remount (you can also see the `lv:sticky-view, phx_close` message come over the websocket right after the `send: js.push navigate, recv: live_redirect`.

In my test, the navigation *does* happen immediately, but the "sticky nav" stops itself, so any "nav bar" changes dont show up until after the sticky view reconnects itself from JS land (after ~5 seconds), which might make it _look_ like the navigation took some time -- but I assume the OP also doesn't see the primary view content update as well?

Since the `<.link>` event occurs client side and communicates with the "main" liveview, the sticky view never closes so it has different behaviour. 

Eg: We `push_navigate` from the sticky view, (`opts` ends up being `%{to: path, kind :push}`.):

https://github.com/phoenixframework/phoenix_live_view/blob/5d62621a4efcb1707965d90707f1a1d42f044277/lib/phoenix_live_view.ex#L1182-L1185



https://github.com/phoenixframework/phoenix_live_view/blob/5d62621a4efcb1707965d90707f1a1d42f044277/lib/phoenix_live_view.ex#L1222-L1224

I *think* we then end up here 

https://github.com/phoenixframework/phoenix_live_view/blob/5d62621a4efcb1707965d90707f1a1d42f044277/lib/phoenix_live_view/channel.ex#L790

Where we land in 

https://github.com/phoenixframework/phoenix_live_view/blob/5d62621a4efcb1707965d90707f1a1d42f044277/lib/phoenix_live_view/channel.ex#L812-L817

Which finally stops the channel (for the sticky view).

https://github.com/phoenixframework/phoenix_live_view/blob/5d62621a4efcb1707965d90707f1a1d42f044277/lib/phoenix_live_view/channel.ex#L855-L858

I figured either views (and components?) in the page might want to delegate `event:navigate` events to the liveSockets main view, or maybe that could be done server side (but I dont think the views currently have enough context to do that).

For ref, here is the repro I got to, though its a bit sketchy. To see the behaviour, start from "page 1" (`/`), then click the "push - page 2".


<details><summary>Details</summary>
<p>

```elixir
Application.put_env(:sample, Example.Endpoint,
  http: [ip: {127, 0, 0, 1}, port: 5001],
  server: true,
  live_view: [signing_salt: "aaaaaaaa"],
  secret_key_base: String.duplicate("a", 64)
)

Mix.install([
  {:plug_cowboy, "~> 2.5"},
  {:jason, "~> 1.0"},
  {:phoenix, "~> 1.7.9"},
  {:phoenix_live_view, "~> 0.20.1"}
])

defmodule Example.ErrorView do
  def render(template, _), do: Phoenix.Controller.status_message_from_template(template)
end

defmodule Example.Layout do
  use Phoenix.LiveView, layout: false

  def render("live.html", assigns) do
    ~H"""
    <script src="https://cdn.jsdelivr.net/npm/phoenix@1.7.9/priv/static/phoenix.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/phoenix_live_view@0.20.1/priv/static/phoenix_live_view.min.js"></script>
    <script>
      let liveSocket = new window.LiveView.LiveSocket("/live", window.Phoenix.Socket)
      liveSocket.connect()
    </script>
    <style>
      html {
        width: 1000px;
        margin: 1rem auto;
      }
      main {
        display: grid;
        grid-template-columns: 1fr 1fr;
        grid-column-gap: 1em;
      }
      * { font-size: 1rem; }
      div { margin-bottom: 2rem; }
      button, form {
        padding: 1ex 2ex;
        border: 1px solid black;
      }
    </style>
    <%= live_render @socket, Example.StickyNav, id: "sticky-nav-container", sticky: true %>
    <%= @inner_content %>
    """
  end
end

defmodule Example.StickyNav do
  use Phoenix.LiveView, layout: false
  require Logger

  use Phoenix.VerifiedRoutes,
    endpoint: Example.Endpoint,
    router: Example.Router

  alias Phoenix.LiveView.JS

  def mount(params, session, socket) do
    socket = assign(socket, :current_path, ~p"/")
    Logger.warning("mounted StickyNav")
    # dbg({:sticky, socket})
    {:ok, socket}
  end

  def render(assigns) do
    ~H"""
    <ul>
      <li>@current_path = <%= @current_path %></li>
      <li><.link navigate={~p"/"}>link - page 1</.link></li>
      <li><.link navigate={~p"/2"}>link - page 2</.link></li>
      <li><span phx-click={JS.push("navigate", value: %{path: ~p"/"})}>push - page 1</span></li>
      <li><span phx-click={JS.push("navigate", value: %{path: ~p"/2"})}>push - page 2</span></li>
    </ul>
    """
  end

  def handle_event("navigate", %{"path" => p}, socket) do
    Logger.warning("handle_event: navigate, path: #{p}")

    socket =
      case socket.assigns do
        # Not bothered to configure plug etc to grap current path all the time, so we just
        # always navigate.
        # %{current_path: ^p} ->
        #   Logger.warning("handle_event: navigate, p == current_path, doing nothing")
        #   socket

        _ ->
          Logger.warning("handle_event: navigate, p != current_path, assign and push_navigate")

          socket
          |> assign(:current_path, p)
          |> push_navigate(to: p)
      end

    {:noreply, socket}
  end
end

defmodule Example.Page1Live do
  use Phoenix.LiveView, layout: {Example.Layout, :live}
  alias Phoenix.LiveView.JS

  def mount(params, session, socket) do
    socket = assign(socket, count: 0)
    # dbg({:page1, socket})
    {:ok, socket}
  end

  def render(assigns) do
    ~H"""
    <div>
      Page1
    </div>
    """
  end
end

defmodule Example.Page2Live do
  use Phoenix.LiveView, layout: {Example.Layout, :live}
  alias Phoenix.LiveView.JS

  def mount(params, session, socket) do
    socket = assign(socket, count: 0)
    {:ok, socket}
  end

  def render(assigns) do
    ~H"""
    <div>
      Page2
    </div>
    """
  end
end

defmodule Example.Router do
  use Phoenix.Router
  import Phoenix.LiveView.Router

  pipeline :browser do
    plug(:accepts, ["html"])
  end

  scope "/", Example do
    pipe_through(:browser)

    live("/", Page1Live, :index)
    live("/2", Page2Live, :index)
  end
end

defmodule Example.Endpoint do
  use Phoenix.Endpoint, otp_app: :sample
  socket("/live", Phoenix.LiveView.Socket)
  plug(Example.Router)
end

{:ok, _} = Supervisor.start_link([Example.Endpoint], strategy: :one_for_one)
Process.sleep(:infinity)
```


</p>
</details>

**Comment by chrismccord** [comment]
Is the `push_navigate` sent from the sticky LV?

If this is defined in the sticky LV:
```
@impl true
def handle_event("navigate", %{"path" => path}, socket) do
  if path == socket.assigns.current_path do
    {:noreply, socket}
  else
    {:noreply, socket |> assign(current_path: path) |> push_navigate(to: path)}
  end
end
```

Then it makes sense that it remounts as you are navigating away. Navigating from the main LV would be what you need in this case. Also note that push navigate over link navigate is going to require an extra round trip so if that's all you're using it for (link vs JS.push + push_navigate) you already incurring 2x time even when everything is working properly. If you can share a full example we can say more about what is going on. Thanks!

**Comment by Terbium-135** [comment]
@rktjmp Thank you for the detailed explanation. It was fun to read.
@chrismccord Yes. It's been sent from the sticky LV.

You both were right. The slowdown came from the sticky navigation LV getting reloaded.
Somehow I was thinking:
* A sticky LV would be just this: sticky
* `.link `and` push_navigate` would share some code path

Thanks for pointing out the extra round trip.

Main reason to use `push_navigate `was to add some logic because:
        *Every time the user clicks on the same link the requested LV will reload.*
We did not like this UX. But of course it's arguable.

Switched to a `hook` for now:
```elixir
<.link id={"link-#{UUID.uuid1()}"} navigate={@path} phx-hook="LinkClicked">
   [...]
</.link>
```

**Comment by chrismccord** [comment]
Yes they function the same as regular anchor clicks, which is in general what you want. Be careful that right/alt/meta click to open in new tab or new window is honored by your js hook.

**Comment by limeuser** [comment]
After navigation, the sticky LV getting reloaded, client channel is closed. But the channel is not reconnecting and phx-click don't worked anymore. 
i created a a full example:  [sticky lv](https://github.com/limeuser/test)

1. open http://localhost:4000/articles/1
2. click article 2, it'ok to navigate to article 2
3. click article 1, can't navigate to article 1, side bar liveview can't receive event
