### ISSUE TITLE
Auto upload doesn't work following validation error

### ISSUE THREAD

**Issue by arien48** [phoenixframework/phoenix_live_view#2880]
### Environment

* Elixir version (elixir -v): 1.15.2
* Phoenix version (mix deps): 1.7.7
* Phoenix LiveView version (mix deps): 0.19.5
* Operating system: Linux
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Description

This is related to #1668.

1. When I select (or drag-drop) more than `max_entries` files to upload at once with `auto_upload: true`, upload doesn't start and I get form error (so far so good).
2. Afterwards I trim the existing upload list (using `cancel_upload` to fit within `max_entries`), the form error is gone, but the auto upload doesn't start (which is IMO a bug) -- the only way to upload is to trigger `save` event on the form.

### Setup

Sorry, can't spin this up as the single file app, because the list of dependencies to make it work seems endless (first components, then pubsub, ...).

So, minimal relevant setup instead...

Live view file:

``` elixir
defmodule TestWeb.UploadLive.Bug do
  use TestWeb, :live_view

  @impl true
  def mount(_params, _session, socket) do
    {:ok,
      socket
      |> assign(:form, to_form(%{}))
      |> allow_upload(
        :files,
        accept: :any,
        max_entries: 2,
        max_file_size: 1_000_000,
        auto_upload: true,
        progress: &handle_progress/3)
    }   
  end
  
  def handle_progress(:files, entry, socket) do
    if entry.done? do
      uploaded_file =
        consume_uploaded_entry(socket, entry, fn %{} = meta ->
          IO.inspect meta, label: "consume_uploaded_entry"
          {:postpone, "abc"}
        end)
    end
    {:noreply, socket}
  end

  @impl true
  def handle_event("cancel_upload", %{"ref" => ref}, socket) do
    {:noreply, cancel_upload(socket, :files, ref)}
  end 
    
  @impl true
  def handle_event("save", %{} = params, socket) do
    IO.inspect params, label: "save"
    {:noreply, socket}
  end
    
  defp error_to_string(:too_large), do: "File too large."
  defp error_to_string(:too_many_files), do: "Too many files."
  defp error_to_string(:not_accepted), do: "Not an acceptable file type."
end
```

and a template:

``` heex
<div>
  <.header>
    Let's upload
    <:subtitle>
    Demonstrating auto-upload bug -- adding 3 files at once kills auto-upload.

    And the auto-upload doesn't start even if one file is then removed.

    Only way to start the upload then is "Save" button.
    </:subtitle>
  </.header>

  <.simple_form
    for={@form}
    id="upload-form"
    phx-change="save"
    phx-submit="save"
  >

  <div phx-drop-target={@uploads.files.ref} class="border-2 border-dashed p-8">
    <div class="text-zinc-600 text-sm">
      <div>
        <label for={@uploads.files.ref} class="cursor-pointer font-semibold">
          <span>Upload a file</span>
          <.live_file_input upload={@uploads.files} class="sr-only" />
        </label>
        <span>or drag and drop here</span>
      </div>
      <p class="text-xs">
      <%= @uploads.files.max_entries %> files max,
      up to <%= trunc(@uploads.files.max_file_size / 1_000_000) %> MB each
      </p>
    </div>
  </div>

  <.error :for={err <- upload_errors(@uploads.files)}>
  <%= error_to_string(err) %>
  </.error>

    <ul>
      <li :for={entry <- @uploads.files.entries} class="border-2 border-dashed p-8 text-sm">
        <span class="w-full">
          <%= entry.client_name %> (<%= entry.client_size %> bytes)
          <div>
            <label><%= entry.progress %>%</label>
            <.error :for={err <- upload_errors(@uploads.files, entry)}>
            <%= error_to_string(err) %>
            </.error>
          </div>
        </span>

        <a phx-click="cancel_upload" phx-value-ref={entry.ref} class="self-center">
          <.icon name="hero-x-circle" class="w-6 h-6 m-1 hover:text-red-600 cursor-pointer" />
        </a>
      </li>
    </ul>

    <:actions><.button name="save">Save</.button></:actions>
  </.simple_form>
</div>
```

### Actual behavior

With the liveview above ---

#### Happy path

Selecting two files to upload works as expected -- auto upload immediately uploads files:

![two file upload](https://raw.githubusercontent.com/arien48/lv-autoupload-bug-files/8611d3845d3adb1b1d27f1e1c611bb0def4c34b0/twofiles-ok.png)
(notice the 100% upload progress)

#### Broken (buggy) path

Selecting three files to upload (at once) doesn't work -- there's validation error:

![three files upload](https://raw.githubusercontent.com/arien48/lv-autoupload-bug-files/8611d3845d3adb1b1d27f1e1c611bb0def4c34b0/threefiles-err.png)

That is still correct behavior. However, removing one of the files using `cancel_upload` (pressing the `X` button) removes the validation error, but the auto upload isn't triggered:

![three files upload -- one removed, still no autoupload](https://raw.githubusercontent.com/arien48/lv-autoupload-bug-files/8611d3845d3adb1b1d27f1e1c611bb0def4c34b0/threefiles-onegone-err.png)

(notice the 0% upload progress... the upload did not auto start, but should have)

The only way to trigger the upload of already selected files is to click "Submit" (submit the form), which isn't WAI.

### Expected behavior

As soon as validation error clears, the files are auto-uploaded. No need to manually submit the form.

**Comment by chrismccord** [comment]
This is expected. You could have a hook trigger the form submit, or look into the `this.upload` features of hooks, but we had to make a decision on behavior here one vs the other, and we settled on not auto uploading during the user pruning phase. It's tricky because if the user selects a bunch of files, they may want a specific subset once they learn "10 files max" or whatever. Starting the upload immediately while they prune may not be what the user actually wants. For example, your UX may want a "Clear All" button instead for the user to select exactly what they want, but it all depends. Thanks!

**Comment by josevalim** [comment]
Also please try v0.20.1, which has some fixes around this area.

**Comment by josevalim** [comment]
>  but the behavior is actually even more inconsistent.

The behaviour looks consistent to me. It uploads until it finds a failure. The point is exactly that, once there is a failure, we can't assume the user behaviour is to continue or stop. Both can be bad defaults depending on the use case and, in such cases, doing the least work out of the box is sensible.

Adding a bit of JavaScript for your use case makes sense. It is extremely unlikely we can support all different use cases. You got 99% of the JS done for you, you just need to do the 1% left.
