### ISSUE TITLE
Debug heex annotations shown on web pages

### ISSUE THREAD

**Issue by puruzio** [phoenixframework/phoenix_live_view#2881]
### Environment

* Elixir version (elixir -v): 1.15.5 (Erl/OTP 26)
* Phoenix version (mix deps): 
* Phoenix LiveView version (mix deps):  1.7.9
* Operating system:  Windows Server 2019 Datacenter
* Browsers you attempted to reproduce this bug on (the more the merrier):  Edge, Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

The new debug_heex_annotations set to true in config.exs is showing an unexpected behavior on one of my machines where the component module name is not only shown in the debug window but also in the webpage itself.  Inspecting the html code in the debugger, I noticed there are auto-generated span> tags right below the module name comments.  

This issue was not reproduced when the same app runs on my laptop on Windows 11, so it could be OS dependent.

### Expected behavior
Annotations only appear in the browser debug window, not the web page.

**Comment by chrismccord** [comment]
This sounds like you are running on an old version of the phoenix_live_view.js javascript client that attempted to fallback to injecting root spans when a live component failed to have a single root. With the heex annotation release we require the root live component to be wrapped in an HTML tag, so if you aren't receiving a compilation error from elixir, this must be an outdated client. Can you double check? Please also include your `:phoenix_live_view` version from your mix deps. Thanks!

**Comment by puruzio** [comment]
Upgrading the JS client fixed the problem. Thank you, Chris!!
