### ISSUE TITLE
Mount sequence - phx-mounted vs Hook.mounted()

### ISSUE THREAD

**Issue by ukutaht** [phoenixframework/phoenix_live_view#2882]
### Environment

* Elixir version (elixir -v): 1.15.5
* Phoenix version (mix deps): 1.7.9
* Phoenix LiveView version (mix deps):  0.20.1
* Operating system: MacOS Ventura
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox 118, Safari 16.6
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: No

### Actual behavior

What I'm trying to do: use `phx-mounted` to dispatch an event and listen to it in my `phx-hook`. 

The component:
```elixir
  def render(assigns) do
    ~H"""
    <div 
      id="repro-element-id" 
      phx-hook="TestHook" 
      phx-mounted={JS.dispatch("mounted-event")}>
    </div>
    """
  end
```

The hook :
```javascript
Hooks.TestHook = {
  mounted() {
    console.log('Hook is registering')
    this.el.addEventListener('mounted-event', (e) => {
      console.log('mounted event - in Hook')
    })
  }
}

window.addEventListener('mounted-event', (e) => {
  console.log('mounted event - on window')
})
```

The console printout looks like this:

<img width="856" alt="Screenshot 2023-10-24 at 22 46 16" src="https://github.com/phoenixframework/phoenix_live_view/assets/3731516/f2ea9c7b-4cba-454c-9312-b5efcba559bb">

Full phoenix app that reproduces this: https://github.com/ukutaht/issue_repro. 

### Expected behavior

In the example above I would expect the sequence to go as follows:
1. `TestHook.mounted()` is called first
  1.1 console prints `Hook is registering`
  1.2 Event listener for `mounted-event` is registered
2. `phx-mounted={JS.dispatch('mounted-event')}` is executed
  2.1 dispatches `mounted-event`
  2.2 console prints `mounted event - in Hook` since the listener was set up for it in step 1

I'm not sure if I'm looking at the right parts of the code but [view.execNewMounted](https://github.com/phoenixframework/phoenix_live_view/blob/3feb03faa48a9dff26c4e258eaabf7aa27c63e1d/assets/js/phoenix_live_view/view.js#L327-L338) seems to be doing things in the expected order. What I don't understand is why `execNewMounted` is triggered twice during the initial mount:

<img width="1512" alt="Screenshot 2023-10-24 at 23 45 34" src="https://github.com/phoenixframework/phoenix_live_view/assets/3731516/38f762b9-198b-428b-8aba-6dafd09b0cf0">

Maybe it has something to do with it [running as a callback](https://github.com/phoenixframework/phoenix_live_view/blob/3feb03faa48a9dff26c4e258eaabf7aa27c63e1d/assets/js/phoenix_live_view/live_socket.js#L371) to `window.requestAnimationFrame`? Not sure.

**Comment by SteffenDE** [comment]
`phx-mounted` is also called on the initial dead render, but there your hook does not run. Therefore you see the log twice. I think this works as expected. `phx-mounted` is not called again on the live render.

You can conditionally include `phx-mounted` only in the live render like this:

```html
    <div
      id="repro-element-id"
      phx-hook="TestHook"
      phx-mounted={if connected?(@socket), do: JS.dispatch("mounted-event")}>
    </div>
```

Then your hook will receive the event.
