### ISSUE TITLE
Flash Message Interactions Cause Console Error

### ISSUE THREAD

**Issue by kyleboe** [phoenixframework/phoenix_live_view#2885]
### Environment

* Elixir version (elixir -v): `Elixir 1.15.7 (compiled with Erlang/OTP 26)`
* Phoenix version (mix deps): `1.7.9`
* Phoenix LiveView version (mix deps): `0.20.1`
* `phx.new` version (mix help phx.new): `1.7.9`
* Operating system: macOS 14.0 (23A344)
* Browsers you attempted to reproduce this bug on (the more the merrier):
  * Chrome v118.0.5993.88 
  * Firefox v119.0
  * Safari v17.0
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes (no `node_modules` folder present)

### Actual behavior
With a vanilla generated Phoenix project with LiveView and auth (see repro steps below), clicking on any flash message results in an error in the dev console. There also seems to be an issue where the click event will not be handled properly and the flash message will become unable to be closed. I can't reproduce that consistently, but I infer that if this error is resolved, the inability to close the flash message will be resolved as well.

It seems to be caused by the auto-generated `core_components.ex` `flash/1` function not assigning an `id` properly.

Whenever the flash is clicked, an error in thrown in the browser dev console:
```
Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Document': '#' is not a valid selector.
    at Object.all (http://localhost:4000/assets/app.js:1844:35)
    at Object.filterToEls (http://localhost:4000/assets/app.js:4126:31)
    at http://localhost:4000/assets/app.js:3924:14
    at Array.forEach (<anonymous>)
    at Object.exec (http://localhost:4000/assets/app.js:3919:16)
    at http://localhost:4000/assets/app.js:5764:24
    at http://localhost:4000/assets/app.js:5548:37
    at LiveSocket.owner (http://localhost:4000/assets/app.js:5544:9)
    at LiveSocket.withinOwners (http://localhost:4000/assets/app.js:5548:12)
    at http://localhost:4000/assets/app.js:5763:16
```

Further debugging can be done by adding an `IO.inspect/1` to the `flash/1` function mentioned above:
```elixir
def flash(assigns) do
  assigns = assign_new(assigns, :id, fn -> "flash-#{assigns.kind}" end)
  IO.inspect(assigns.id)

  ~H"""
  . . .
```

Which shows in the console:
```elixir
"client-error"
"server-error"
nil
nil
```

### Expected behavior

Expected the flash `id` to be generated and the flash message to close consistently and without error.

### Steps to Reproduce

1. `mix phx.new hello_world`
2. `mix phx.gen.auth Accounts User users`
3. `mix setup`
4. Try to sign in with any account info (email/password)
5. Click the error flash message
6. Check the dev console

**Comment by josevalim** [comment]
What is the last line of your `mix help phx.new`? That should tell your `phx.new` version.

**Comment by josevalim** [comment]
But you are on the right track. We need to understand when the `@id` is nil. Because it understandable calling `hide("#")` will fail.

**Comment by kyleboe** [comment]
phx.new version is `1.7.9` I'll add this to the Environment section as well.

**Comment by kyleboe** [comment]
> But you are on the right track. We need to understand when the `@id` is nil. Because it understandable calling `hide("#")` will fail.

Yeah that's what I've been trying to figure out. I rendered the `@id` directly in the flash message by adding
```
<p class="this-is-the-id"><%= @id %></p>
```
and it always comes up as `nil`:
```
<p class="this-is-the-id"></p>
```
<img width="275" alt="image" src="https://github.com/phoenixframework/phoenix_live_view/assets/4054771/7a0211b6-301a-4048-a466-dc2f466706e6">

 I'm digging into `assign_new/3` now.

**Comment by josevalim** [comment]
What is the value of `assigns` before `assign_new`? We should not have an ID field in there.

**Comment by kyleboe** [comment]
> What is the value of `assigns` before `assign_new`? We should not have an ID field in there.

I was just checking this haha you beat me to it.

I think its because of the logic here:
https://github.com/phoenixframework/phoenix_live_view/blob/9adf28cc984f5c84d5a10013e264a0a4f051c21c/lib/phoenix_component.ex#L1207-L1212

In this case `key` is `:id` and it has a default of `nil` from the generated `attr` line above, but it still matches so it results in a noop in terms of assigns.

**Comment by kyleboe** [comment]
Yep! Thanks for the help!

**Comment by kyleboe** [comment]
For the sake of leaving a trail of GitHub breadcrumbs: Resolved by https://github.com/phoenixframework/phoenix/pull/5602
