### ISSUE TITLE
Reformatting of spans breaks the generated html vs what what intended

### ISSUE THREAD

**Issue by ahacking** [phoenixframework/phoenix_live_view#2900]
### Environment

* Elixir version (elixir -v):

Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:32:24] [ds:32:24:10] [async-threads:1] [jit:ns]
Elixir 1.15.4 (compiled with Erlang/OTP 26)

* Phoenix version (mix deps): phoenix 1.7.7
* Phoenix LiveView version (mix deps):  phoenix_live_view 0.19.5
* Operating system: Linux
* Browsers you attempted to reproduce this bug on (the more the merrier): brave, chrome, firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

#1951 is not resolved for span cases.

Example:

```html
<span class="underline decoration-secondary decoration-2 font-extrabold">Check</span> Messages
```
becomes:

```html
<span class="underline decoration-secondary decoration-2 font-extrabold">
  Check
</span>
Messages
```

The original code only underlines "Check", but the re-formatted code now also underlines  the space between "Check" and Messages".

### Expected behavior

Don't mess with spans, or provide a ```phx-no-format``` escape hatch for any markup regardless of the element type.

The code wrapping issue appears in a surprising way and is  dependent on the width of the attribute text so it just adding another class can trigger the reformatting and ruin your day.

Currently I use the ```:heex_line_length``` option in *.formatter.exs* to work around the problem buts its a coarse grained configuration and not ideal.

**Comment by josevalim** [comment]
>  provide a phx-no-format escape hatch for any markup regardless of the element type.

That should already be the case today.

**Comment by ahacking** [comment]
> > provide a phx-no-format escape hatch for any markup regardless of the element type.
> 
> That should already be the case today.

When I looked at the PR for phx-no-format it appeared to be scoped to specific elements like textarea, not generic or spans.

Suffice to say it has no effect on spans.

**Comment by josevalim** [comment]
As said above, that's not the case, it applies to any element and I have pushed a test that show it works, at least on main. If it still fails for you, then we would need a failing test to reproduce the failure.

**Comment by josevalim** [comment]
cde18fd8d961c3cdc1dbfaefba3f9d9169578466
