### ISSUE TITLE
Assigns dissapears on second mount/3 call with non-root router

### ISSUE THREAD

**Issue by maslowalex** [phoenixframework/phoenix_live_view#2911]
### Environment

* Elixir version (elixir -v): `1.15.5 OTP 26`
* Phoenix version (mix deps): `1.7.10`
* Phoenix LiveView version (mix deps): `0.20.1`
* Operating system: `macOS`
* Browsers you attempted to reproduce this bug on (the more the merrier): `All browsers`
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior
I have a separate router which I use to render in the `iframe`.
In my `router.ex` I have:
```elixir
defmodule MyAppWeb.Router do
  use MyAppWeb, :router

  scope "/", MyAppWeb do
    forward "/iframe", IframeRouter
  end
```

Which forwards to the IframeRouter:
```elixir
defmodule MyAppWeb.IframeRouter do
  use MyAppWeb, :router

  ...

  scope "/", MyAppWeb do
    pipe_through [:iframe]

    live_session :iframe, on_mount: MyAppWeb.IframeLive.OnMount do
      live "/:hashed_id", IframeLive.Quiz, :show
      live "/:hashed_id/wait", IframeLive.Wait, :show
      live "/:hashed_id/results", IframeLive.Results, :show
    end
  end
```

# The problem
All my assigns which is available on first call of `mount/3` dissapears on the second call, when socket is supposed to connect. I debugged the assigns and I have everything that I'm expect on first call of `mount/3`, but on the second call it's just default empty assigns.

It's also calls `mount/3` with first parameter as `:not_mounted_at_router`, however I can see my IframeRouter under `socket.router`.

## Note
It worked well when I had everything in single router, however issue appears after I moved it into the separate one.
I found nothing about using multiple routers in the docs. I'll be happy to elaborate on the documentation.

### Expected behavior

Should have all assigns persisted after first call of `mount/3` ?

**Comment by josevalim** [comment]
Please provide code snippets of how you are trying to access the assigns and what do you mean by them disappearing?

>  I found nothing about using multiple routers in the docs. I'll be happy to elaborate on the documentation.

If you have nested routers it may be that we will only consider those mounted at the root router for now.

**Comment by maslowalex** [comment]
Sure. Here is the code that I have in `mount/3`:

```elixir
  def mount(_params, _session, socket) do
    %{quiz_run_id: quiz_run_id} = socket.assigns

    dbg("mounting quiz live view for quiz_run_id: #{quiz_run_id}")

    if connected?(socket) do
      :ok =
        EventSubmitter.maybe_submit_start_event(%{
          quiz_run_id: socket.assigns.quiz_run_id,
          quiz_user_id: socket.assigns.current_quiz_user.id
        })

      socket =
        socket
        |> assign_flow()
        |> Flow.setup()
        |> push_event("restore", %{key: @restore_key, event: @restore_event})

      {:ok, socket}
    else
      {:ok, assign_flow(socket)}
    end
  end
```

The output in the console is following:

```
[(my_app 0.1.0) lib/my_app_web/live/iframe_live/quiz.ex:19: QuizArenaWeb.IframeLive.Quiz.mount/3]
"mounting quiz live view for quiz_run_id: #{quiz_run_id}" #=> "mounting quiz live view for quiz_run_id: 125"

** (MatchError) no match of right hand side value: %{__changed__: %{}, flash: %{}, live_action: nil}
    (my_app 0.1.0) lib/my_app_web/live/iframe_live/quiz.ex:17: QuizArenaWeb.IframeLive.Quiz.mount/3
```

**Comment by josevalim** [comment]
I would expect that to never work. The socket never comes prepopulated with assigns, you should load those from params and/or session. The big question is *why* sometimes it has entries there, but I don't think it ever does.

**Comment by maslowalex** [comment]
The assigns is populated in the `on_mount` callback.

I think that I might missunderstand the behaviour of LiveView mounted to non-root router.

**Comment by josevalim** [comment]
It is very hard to help without the full context of the code. But looking at the snippet you pasted:

```
  def on_mount(
        _,
        %{"hashed_id" => quiz_run_hashed_id},
        %{"token" => token, "platform_id" => platform_id},
        socket
      ) do
```

And the fact your LiveView is not mounted at the main router, I don't expect the second argument to match (i.e. you have no parameters). You will have to break this down into a small reproducible app if you want us to help further.
