### ISSUE TITLE
a JS error

### ISSUE THREAD

**Issue by DaTrader** [phoenixframework/phoenix_live_view#2918]
### Environment

* Elixir version (elixir -v): 1.14.1
* Phoenix version (mix deps):  1.7.9
* Phoenix LiveView version (mix deps): 0.20.1
* Operating system: Linux Mint
* Browsers you attempted to reproduce this bug on (the more the merrier):  FF, Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

It's hard for me to describe the exact circumstances (let alone provide an app demoing this bug), but here's what happens when trying to click fast on a button that switches from loading one list of data and placing into a stream to another. Similar thing occurs if instead of resetting the stream to place data into it, I replace the list component instance. I truly hope someone will have an idea of the nature of this bug.

Firefox:
```
Uncaught TypeError: tdiff is undefined
    cachedFindComponent http://localhost:4000/assets/app.js:3375
    mergeDiff http://localhost:4000/assets/app.js:3355
    update http://localhost:4000/assets/app.js:4244
    bindChannel http://localhost:4000/assets/app.js:4334
    applyDiff http://localhost:4000/assets/app.js:4003
    bindChannel http://localhost:4000/assets/app.js:4334
    flushPendingOps http://localhost:4000/assets/app.js:5756
    flushPendingOps http://localhost:4000/assets/app.js:5757
    flushPendingOps http://localhost:4000/assets/app.js:5757
    flushPendingOps http://localhost:4000/assets/app.js:5757
    timer http://localhost:4000/assets/app.js:5740
    setTimeout handler*addTransition http://localhost:4000/assets/app.js:5737
    transition http://localhost:4000/assets/app.js:5086
    transition http://localhost:4000/assets/app.js:3979
    toggle http://localhost:4000/assets/app.js:3758
    show http://localhost:4000/assets/app.js:3718
    exec_show http://localhost:4000/assets/app.js:3705
    exec http://localhost:4000/assets/app.js:3623
    exec http://localhost:4000/assets/app.js:3622
    exec http://localhost:4000/assets/app.js:3617
    execJS http://localhost:4000/assets/app.js:5042
    owner http://localhost:4000/assets/app.js:5242
    execJS http://localhost:4000/assets/app.js:5042
    anonymous http://localhost:4000/assets/app.js line 6229 > AsyncFunction:16
    generateEvaluatorFromString http://localhost:4000/assets/app.js:6247
    tryCatch http://localhost:4000/assets/app.js:6169
    evaluate http://localhost:4000/assets/app.js:6192
    <anonymous> http://localhost:4000/assets/app.js:8254
    skipDuringClone http://localhost:4000/assets/app.js:6901
    flushHandlers http://localhost:4000/assets/app.js:6317
    stopDeferring http://localhost:4000/assets/app.js:6322
    deferHandlingDirectives http://localhost:4000/assets/app.js:6325
    initTree http://localhost:4000/assets/app.js:6524
    mounted http://localhost:4000/assets/app.js:10704
    __mounted http://localhost:4000/assets/app.js:3558
    maybeAddNewHook http://localhost:4000/assets/app.js:4123
    performPatch http://localhost:4000/assets/app.js:4132
    trackAfter http://localhost:4000/assets/app.js:2982
    trackAfter http://localhost:4000/assets/app.js:2982
    perform http://localhost:4000/assets/app.js:3192
    perform http://localhost:4000/assets/app.js:3192
    performPatch http://localhost:4000/assets/app.js:4161
    componentPatch http://localhost:4000/assets/app.js:4280
    update http://localhost:4000/assets/app.js:4250
    update http://localhost:4000/assets/app.js:4249
    time http://localhost:4000/assets/app.js:5065
    update http://localhost:4000/assets/app.js:4247
    bindChannel http://localhost:4000/assets/app.js:4334
    applyDiff http://localhost:4000/assets/app.js:4003
    bindChannel http://localhost:4000/assets/app.js:4334
    after http://localhost:4000/assets/app.js:5730
    requestDOMUpdate http://localhost:4000/assets/app.js:5082
    bindChannel http://localhost:4000/assets/app.js:4333
    onChannel http://localhost:4000/assets/app.js:5092
    trigger http://localhost:4000/assets/app.js:566
    onConnMessage http://localhost:4000/assets/app.js:1250
    decode http://localhost:4000/assets/app.js:826
    onConnMessage http://localhost:4000/assets/app.js:1236
    onmessage http://localhost:4000/assets/app.js:1017
    connect http://localhost:4000/assets/app.js:1017
    doConnect http://localhost:4000/assets/app.js:5018
    connect http://localhost:4000/assets/app.js:5027
    <anonymous> http://localhost:4000/assets/app.js:10726
    <anonymous> http://localhost:4000/assets/app.js:10728
```

Chrome:

```
rendered.js:92 Uncaught TypeError: Cannot read properties of undefined (reading 's')
    at Rendered.cachedFindComponent (rendered.js:92:16)
    at Rendered.mergeDiff (rendered.js:69:26)
    at View.update (view.js:507:19)
    at view.js:601:68
    at View.applyDiff (view.js:248:5)
    at view.js:601:14
    at TransitionSet.flushPendingOps (live_socket.js:950:7)
    at TransitionSet.flushPendingOps (live_socket.js:951:12)
    at TransitionSet.flushPendingOps (live_socket.js:951:12)
    at TransitionSet.flushPendingOps (live_socket.js:951:12)
```

**Comment by DaTrader** [comment]
UPDATE: Actually, the clicking speed does not matter at all and the bug manifests in the same way in two different variations of the following scenario:
1. Open a modal
2. Modal shows a list (a stream) of items
3. Click on an item's "view more"
4. Modal shows a stream of items under the item in #3
5. Click on an item's "view more"
6. Modal shows a stream of items under the item in #5
7. Click back
8. Click back
9. Again click on the item in #3 to "view more" thus making making it show the list in #4
=> The JS error as shown in the original post

As mentioned before, I've tried two different approaches and they both yield this same error.
a) Reuse the list of items LiveComponent by resetting the stream prior to showing the level down or level up (back) of the items
b) Restart the list of items LiveComponent by changing its id.

In both cases the list LiveComponent is another LiveComponent that makes the modal.

Since the error in both cases is produced in the exact same way and in the same function `cachedFindComponent` I imagine LiveView has issues when making it render the same components (in its JS client code terms) that have been previously deleted and it makes no difference of how they've been deleted (by dropping the component instance or reusing it but resetting its stream)

My 2c

**Comment by josevalim** [comment]
Perfect, if you can isolate it, I will look into. :)

**Comment by DaTrader** [comment]
I found what's troubling it. It's the use of `JS.show` from `liveSocket.execJS`. If I remove it, or not use it only when the items need to appear as part of the list stream reset or list restart, then there's no bug. 

So, it's the combo of `JS.show` and showing items that used to be deleted (JS client-wise).

**Comment by DaTrader** [comment]
Update: 

So far, the outcome has been that the `cacheFindComponent` fails every single time the `JS.show` gets "interrupted" by resetting the stream of items while the effect of their still being shown is taking place.

It should be easy to demo this, so as soon as I find a little spare time I'll post the demo app.

**Comment by DaTrader** [comment]
@josevalim 

Update:

It's not about `JS.show`, but about `liveSocket.execJS` (invoked from AlpineJS  `x-show`). And it's not just this case. It's either `execJS` creates a client-side execution flow that is concurrent to other JS client updates and in doing so it sometimes fails or it's about Alpine integration and the lifespan of the `execJS` under it.

For instance, in my app, I have two application sections each based on its own set of 2 or 3 LiveViews (the two sections are mutually exclusive i.e. by clicking on a sidebar button the user switches from one section to another). The second section use to be composed of a single LiveView instance only, but when I made it have two (a main LiveView instance + a nested LiveView instance), the first section when shutting down its LiveViews started creating problems. Not much of the problems, but still reporting a JS error in the Web console (see below). This time it was `liveSocket.execJS` within Alpine's `x-intersect`:

```
no component found matching phx-target of 2 undefined [utils.js:7:61](http://localhost:4000/deps/phoenix_live_view/assets/js/phoenix_live_view/utils.js)

logError utils.js:7
    withinTargets view.js:234
    exec_push js.js:55
    exec js.js:20
    exec js.js:19
    exec js.js:14
    execJS live_socket.js:238
    owner live_socket.js:435
    execJS live_socket.js:238
    anonymous app.js line 6229 > AsyncFunction:3
    generateEvaluatorFromString module.esm.js:489
    tryCatch module.esm.js:409
    observer2 module.esm.js:13
    observer2 module.esm.js:10
```

I can (and will) circumvent this latest issue by conditioning the rendering of the component featuring the `x-intersect`, but the problem as such remains.

Now, as for the originally reported issue here, I can make a minimal app demoing the problem but only IF you (or Chris) are not going to dismiss the issue for occurring (so far) only with the AlpineJS + `execJS` combo.

Otherwise, if you think this is outside the scope of your debugging LiveView, feel free to close the issue.

Thanks

**Comment by josevalim** [comment]
Thanks for the updates as always! Yeah, we need to have a reproduction without Alpine. Some minimal amount of custom JS is fine, but as you know, we can't debug a whole separate JS library. :)
