### ISSUE TITLE
Dialyzer errors on `handle_event/3`

### ISSUE THREAD

**Issue by coladarci** [phoenixframework/phoenix_live_view#292]
### Environment

* Elixir version (elixir -v): `Elixir 1.9.1 (compiled with Erlang/OTP 22)`
* Phoenix version (mix deps): `phoenix 1.4.9 (Hex package) (mix)`
* NodeJS version (node -v): `v12.7.0`
* NPM version (npm -v):`6.10.0`
* Operating system: `mac 10.14.5`

### Actual behavior
I am sending a click like `phx-click="next" phx-value="something"` and the second param to my `handle_event/3` is the `"something"` I'd expect.

That said, when running dialyzer I am getting warned:
```
The specified type for the 2nd argument of handle_event/3 (
          binary()) is not a supertype of
          map(), which is expected type for this argument in the callback of the 'Elixir.Phoenix.LiveView' behaviour
```

Since `handle_event`'s second param can either be a `map()` (in the case of a form submission) but can be a `String.t()` (in the case of a `phx-click`).

### Expected behavior

While fixing the spec is a decent fix, it might be a cleaner contract to consider always sending a map, and in the case of a `phx-click` wrap the value in a map w/ a single key..

**Comment by chrismccord** [comment]
We indeed will always send a map once my latest round of refactoring lands. Thanks!
