### ISSUE TITLE
clarify documentation around what the expected results are from `fetch_org!`

### ISSUE THREAD

**Issue by tcoopman** [phoenixframework/phoenix_live_view#2927]
in [the doc](https://github.com/phoenixframework/phoenix_live_view/blob/9adf28cc984f5c84d5a10013e264a0a4f051c21c/lib/phoenix_live_view.ex#L332) it's not clear what the results of `fetch_org!` are:

```elixir
|> assign_async(:org, fn -> {:ok, %{org: fetch_org!(slug)}} end)
```

Is `fetch_org!` a regular function that might tak a while to return a result? A bit further the docs say:

> The [handle_async/3](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#c:handle_async/3) callback is called when the **task** completes or exits

And then in the docs of `start_async`

> Starts an ansynchronous task and invokes callback to handle the result.

So I think it works like this:

1. `start_async` and `assign_async` wrap the function inside a Task. The function you call should just return a result on completion?
2. I think `{:exit...}` or `failed` is called when: function returns other keys or a different set of keys + if the function raises something?

Is this correct?
Should I try to write a PR to improve the docs?

**Comment by tcoopman** [comment]
Glancing the source code, it seems that the async task is only run when LV is connected, which makes sense, but the docs don't say anything about that. 
Shouldn't that be added to the docs as well?

**Comment by josevalim** [comment]
You got it all right. Please send a PR and I will gladly review it!
