### ISSUE TITLE
Incorrect HEEX variable access warning

### ISSUE THREAD

**Issue by simoncocking** [phoenixframework/phoenix_live_view#2932]
### Environment

* Elixir version (elixir -v): 1.15.7
* Phoenix version (mix deps): 1.7.10
* Phoenix LiveView version (mix deps): 0.20.1
* Operating system: MacOS 14.1.1
* Browsers you attempted to reproduce this bug on (the more the merrier): Safari, Brave
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

The following HEEX produces a the compiler warning `warning: you are accessing the variable "category" inside a LiveView template.`:
```heex
def render(%{category: category} = assigns) when category in ~w[foo bar]a do
  ~H"""
  <div>
    ... other markup ...
    <div :for={category <- all_categories()}>
      Something using <%= category %>
    </div>
  </div>
  """
end
```

### Expected behavior

When using a variable in pattern matching to select the correct render function, if we reuse that variable name in a `:for={...}` assignment later in that function we get the compiler warning `warning: you are accessing the variable "category" inside a LiveView template.`. This is incorrect: we're reassigning that variable in our `:for={...}` attribute, which is a legal use of a variable within the HEEX template. This is easily worked around by using a different variable name in the pattern match, but the warning is nonetheless incorrect.

**Comment by josevalim** [comment]
I have thought about this the whole weekend and unfortunately having precise tracking is going to be too complex and still have false positives from macros, so I don't think it is worth going down this route. :(

We have recently improve the warning to clarify it may have indeed overlap though. thank you for the report!
