### ISSUE TITLE
LiveView 0.20 no longer sends parameters in fragments

### ISSUE THREAD

**Issue by objectuser** [phoenixframework/phoenix_live_view#2937]
### Environment

* Elixir version (elixir -v): 1.15.4
* Phoenix version (mix deps): 1.7.10
* Phoenix LiveView version (mix deps): 0.20.1
* Operating system: macOS
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox, Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

I have a route:

```elixir
    live "/signup#:step", PageLive
```

In LiveView 0.20.1, `step` is not included as a key in the first argument to `handle_params/3`. Instead, the value of step is included as a key with an empty value.

That is:

`/signup#first` => `%{"first" => ""}`
`/signup#second` => `%{"second" => ""}`

### Expected behavior

In LiveView 0.19.x, `step` is included as the key in the first argument to `handle_params/3`.

That is:

`/signup#first` => `%{"step" => "first"}`
`/signup#second` => `%{"step" => "second"}`

**Comment by objectuser** [comment]
> Therefore, I'd propose for us to not send anchor tags altogether to the server, even on LiveViews. I recommend you pick another URL style for your use cases.

Unfortunately, this choice was not arbitrary.

**Comment by josevalim** [comment]
If you must stick to it, you can parse it on the JS side and push it later.
