### ISSUE TITLE
Unreachable code

### ISSUE THREAD

**Issue by janpieper** [phoenixframework/phoenix_live_view#2938]
### Environment

I just found this code and I am wondering whether there is any way to reach line 42 :thinking: 

https://github.com/phoenixframework/phoenix_live_view/blob/ba596df42e23d5f4f7d03fd2250522e9a41a769b/lib/phoenix_live_view/html_engine.ex#L41-L42

I would guess not, so either we need to remove line 42 or we should flip these two lines, so we get an error when calling it with `:inner_block`.

### Actual behavior

```elixir
Phoenix.LiveView.HTMLEngine.classify_type(":example") # {:slot, "example"}
Phoenix.LiveView.HTMLEngine.classify_type(":inner_block") # {:slot, "inner_block"}
```

### Expected behavior

```elixir
Phoenix.LiveView.HTMLEngine.classify_type(":example") # {:slot, "example"}
Phoenix.LiveView.HTMLEngine.classify_type(":inner_block") # {:error, "the slot name :inner_block is reserved"}
```

**Comment by chrismccord** [comment]
Can you send a PR? Thanks!
