### ISSUE TITLE
`key :live_view_module not found in [assigns]` when testing

### ISSUE THREAD

**Issue by coladarci** [phoenixframework/phoenix_live_view#294]
### Environment

* Elixir version (elixir -v): `Elixir 1.9.1 (compiled with Erlang/OTP 22)`
* Phoenix version (mix deps): `phoenix 1.4.9 (Hex package) (mix)`
* NodeJS version (node -v): `v12.7.0`
* NPM version (npm -v):`6.10.0`
* Operating system: `mac 10.14.5`

### Actual behavior
I have written a live-view (that part was awesome and worked flawlessly!) and was experimenting w/ writing a test for it. 

My test is simply:
```
defmodule MyApp.QuizLiveTest do
  use MyApp.ConnCase
  import Phoenix.LiveViewTest

  test "that things work..?", %{conn: conn} do
    {:ok, view, _html} = live(conn, "/")
  end
end

```
But when running `live(` it throws:
```
** (KeyError) key :live_view_module not found in: [a big dump of my assigns being sent in my controller]

     code: {:ok, view, _html} = live(conn, "/")
     stacktrace:
       (phoenix_live_view) lib/phoenix_live_view/test/live_view_test.ex:230: Phoenix.LiveViewTest.do_connect/6
       test/map_app_web/views/live/my_test.exs:18: (test)
``` 

The only thing that I think might be related (?) is that my homepage is a normal view, but I am using `Phoenix.LiveView.live_render` inside to render a live partial of sorts. 

### Expected behavior

Coming from the ember world of components, I got very excited at the idea of writing `live_views` that can individually be embedded and individually tested. The notion that I would have to hit a real route of my application to test a one (of many?) live views seems odd. 

In my ideal world I could write a test specific to my LiveView and show that the various events are handled and change the html in the expected way. 

Is this possible and I am missing something?

Thanks again for all this work... very exciting.

**Comment by josevalim** [comment]
can you provide a minimal app that reproduces the error? thank you!

**Comment by gregjopa** [comment]
@coladarci there is an open PR to improve the testing story for shared components: https://github.com/phoenixframework/phoenix_live_view/pull/284. It adds a new `live_isolated` function so you don't have to hit a route to test a shared LiveView component. 

For example, let's say I have a widget that's in charge of collecting user feedback. It's used on many pages. We can test it out like so using `live_isolated`:

```elixir
test "increment event increases feedback count", %{conn: conn} do
  {:ok, view, _html} = live_isolated(conn, ReviewHelpfulLive, session: %{})

  assert html =~ "<strong>0</strong> out of"
  html = render_click(view, "increment")
  assert html =~ "<strong>1</strong> out of"
end
```

**Comment by coladarci** [comment]
@josevalim - sorry for the delay here - took some time to rip out everything to isolate this.. Here's a repo - https://github.com/coladarci/live_view_bug_report a simple `mix test` should repro this. 

@gregjopa - what you have put together is *exactly* what I'd be looking for; I think testing the entire route is important, but not the job of the controller test to verify interactions w/ each individual live-view; testing those in isolation is the "most correct" way and; and building one-off routes for each live view is a little nutty. If you can get that through review I'd certainly be a fan :)

**Comment by HangingClowns** [comment]
had similar issue with #259 but was told currently "widget-style" components are being dealt with in the future.

Having something like this would be great if I can get to certain components. I have a LiveView for comments from users that is embedded in the template of most sections of my site, and of course some sections render multiple live view components. Having some kind of way to target them is blocking me from upgrading to the latest version of LiveView.

**Comment by coladarci** [comment]
Thanks @HangingClowns - this is good background. I also noticed you are manually setting `live_view_module` in your tests; if that's expected that also solves my problem here :) We currently only happen to have 1 live view, so the limitation you ran into isn't an issue for us (yet).

**Comment by HangingClowns** [comment]
I would think this wouldn't be expected. Just my guess, but I'm wondering if it's cause you're rendering a "widget style" way? As in not using live_render from controller or router?

**Comment by coladarci** [comment]
Yeah I'm not sure what "widget style" means, but as I said above 

> The only thing that I think might be related (?) is that my homepage is a normal view, but I am using Phoenix.LiveView.live_render inside to render a live partial of sorts.

So maybe that's considered widget style? Either way, being explicit and setting `live_view_module` made my tests pass and I tested all interactions. I would suspect if I added a second widget to that same page things might fail given your bug report

**Comment by HangingClowns** [comment]
"Widget-style" would be if you did what you are doing now: rendering live view from within an `eex` template. I haven't dug into the source, but what I'm guessing is that if you use LiveView from within the router or controller, then this would set that variable for you.

**Comment by chrismccord** [comment]
Please see #284 for testing non-routable LiveViews. Thanks!
