### ISSUE TITLE
phx-update=stream does not trigger onClick events

### ISSUE THREAD

**Issue by DriesCruyskens** [phoenixframework/phoenix_live_view#2940]
### Environment

* Elixir version (elixir -v): 1.14.4
* Phoenix version (mix deps): 1.7.3
* Phoenix LiveView version (mix deps): 0.20.1
* Operating system: MacOs Ventura
* Browsers you attempted to reproduce this bug on (the more the merrier): Arc
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

Hello,

I came across a weird behaviour while refactoring one of my applications from the old 'temporary assigns' to the new 'stream' api. I'm not sure if it's an actual bug or not but it is definitely preventing me using the new streams api.

For some reason the click event is not triggered when clicking on elements with `phx-update=stream`.

I have constructed a minimal reproducable example ([https://github.com/DriesCruyskens/phoenix-stream-onclick-mre](https://github.com/DriesCruyskens/phoenix-stream-onclick-mre)) that shows this behaviour. It consist of a single liveview page and some leaflet.js javascript code. Most javascript code is bootstrap except one important function:

- leaflet-map.js: connectedCallback()

To replicate the weird behaviour, simply change `phx-update=stream` to  `phx-update=append` or remove the attribute completely (in `index.html.heex`). As you can see in the browser logs the original leaflet html element does not receive the 'click' event when streams are enabled on the parent. Here's a summary of the observed behavior:

phx-update=append: both leafletmarker and the original element's click event are triggered on click (bind is inside the hook)
phx-update=stream: only leaflet marker click event is triggered

![Untitled](https://github.com/phoenixframework/phoenix_live_view/assets/26900172/c5fe5591-c610-45a9-a6cc-88d1e307c3d9)

I hope this issue is not too esoteric and I would appreciate it greatly if someone would be able to take a look at this.

Thanks again to everyone working Phoenix LiveView!

**Comment by josevalim** [comment]
Hi @DriesCruyskens, thank you for the report. Can you please provide the minimal app/example that reproduces this?

**Comment by DriesCruyskens** [comment]
I forgot to add it, here it is:
[https://github.com/DriesCruyskens/phoenix-stream-onclick-mre
](https://github.com/DriesCruyskens/phoenix-stream-onclick-mre
)I also added it to the original comment.

**Comment by SteffenDE** [comment]
I think this is because the marker elements are replaced when the stream elements are added, therefore the click event is never dispatched on them. In your `connectedCallback` you go over the current `leaflet-marker` elements, but if these change you dispatch the event to a node that does not exist any more. Instead you want to do something like this:

```javascript
      leafletMarker.addEventListener("mousedown", (event) => {
        event.originalEvent.stopPropagation();
      });
      leafletMarker.addEventListener("click", (event) => {
        event.originalEvent.preventDefault();
        // click on the marker element that is currently in the dom based on the id
        this.querySelector(`#${markerEl.id}`).click();
      });
```

The mousedown event needs to be handled as LiveView otherwise attributes the click to the leaflet-map element and will not dispatch the phx-click event correctly.

**Comment by SteffenDE** [comment]
@DriesCruyskens note that to fully make this work as in your video you will need to handle slot changes to properly initialize the markers when they are updated by the stream. Here is how this could look like in your `leaflet-map.js`:

```javascript
import L from "leaflet";
import "leaflet-control-geocoder";
import "leaflet.markercluster";
import "../../vendor/L.VisualClick";

const template = document.createElement("template");
template.innerHTML = `
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"
    integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
    crossorigin=""/>
    <link
      rel="stylesheet"
      href="/css/MarkerCluster.css"
    />
    <link
      rel="stylesheet"
      href="/css/L.VisualClick.css"
    />
    <link
      rel="stylesheet"
      href="/css/MarkerCluster.Default.css"
    />
    <link rel="stylesheet" href="https://unpkg.com/leaflet-control-geocoder@2.4.0/dist/Control.Geocoder.css" />
    <div style="height: 100%; width: 100%; z-index: 0;">
        <slot />
    </div>
`;

class LeafletMap extends HTMLElement {
  constructor() {
    super();

    this.attachShadow({ mode: "open" });
    this.shadowRoot.appendChild(template.content.cloneNode(true));

    this.defaultSlot = this.shadowRoot.querySelector("slot");
    this.defaultSlot.addEventListener("slotchange", () => this.slotChange(this));

    this.mapElement = this.shadowRoot.querySelector("div");

    this.map = L.map(this.mapElement).setView(
      [this.getAttribute("lat"), this.getAttribute("lng")],
      this.getAttribute("zoom")
    );

    L.tileLayer("https://{s}.tile.osm.org/{z}/{x}/{y}.png", {
      attribution:
        '&copy; <a href="https://osm.org/copyright">OpenStreetMap</a> contributors',
    }).addTo(this.map);

    // https://github.com/perliedman/leaflet-control-geocoder
    L.Control.geocoder({ position: "topleft", defaultMarkGeocode: false })
      .on(
        "markgeocode",
        function (e) {
          var bbox = e.geocode.bbox;
          var poly = L.polygon(
            [
              bbox.getSouthEast(),
              bbox.getNorthEast(),
              bbox.getNorthWest(),
              bbox.getSouthWest(),
            ],
            { fillColor: "#75b2db", color: "#4e96cf" }
          ).addTo(this.map);
          this.map.fitBounds(poly.getBounds());
        }.bind(this)
      )
      .addTo(this.map);

    L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png?{retina}", {
      retina: "", // to be extended for detected Retina displays with value '@2x'
      // maxZoom and maxNativeZoom are necessary to allow zooming beyong 18.5
      // https://gis.stackexchange.com/a/277848
      maxNativeZoom: 18,
      maxZoom: 20,
      attribution:
        '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
    }).addTo(this.map);
  }

  slotChange () {
    this.markerClusterGroup.clearLayers();
    Array.from(this.defaultSlot.assignedNodes()).forEach(markerEl => {
      if (markerEl.tagName === "LEAFLET-MARKER") {
        const lat = markerEl.getAttribute("lat");
        const lng = markerEl.getAttribute("lng");

        const leafletMarker = L.marker([lat, lng]);

        leafletMarker.addEventListener("mousedown", (event) => {
          event.originalEvent.stopPropagation();
        });
        leafletMarker.addEventListener("click", (event) => {
          event.originalEvent.preventDefault();
          markerEl.click();
        });

        const iconEl = markerEl.querySelector("leaflet-icon");

        iconEl.addEventListener("attribute-changed", (e) => {
          leafletMarker.setOpacity(0.8).setIcon(
            L.icon({
              iconUrl: e.detail,
              iconSize: [25, 41],
              iconAnchor: [12, 41],
            })
          );
        });

        leafletMarker.setOpacity(0.8).setIcon(
          L.icon({
            iconUrl: iconEl.getAttribute("icon-url"),
            iconSize: [25, 41],
            iconAnchor: [12, 41],
          })
        );

        this.markerClusterGroup.addLayer(leafletMarker);
        markerEl.marker = leafletMarker;
      }
    });
  }

  connectedCallback() {
    this.markerClusterGroup = L.markerClusterGroup({ maxClusterRadius: 40 });
    this.map.addLayer(this.markerClusterGroup);
  }
}

window.customElements.define("leaflet-map", LeafletMap);
```

Not sure if that's the best solution though.
For me it looks like LiveView itself does everything correct here, so probably not a bug 😃

**Comment by chrismccord** [comment]
@SteffenDE thank you for the amazing deep dive on this one (and all your other contributions in general :)). Agree this one looks like an issue with the way the leaflet component is handling the bindings internally. Thanks!

**Comment by DriesCruyskens** [comment]
Thank you for this insight and for your troubles! In my particular use case, since there will be a lot of markers it will be more performant using the old "append" way since this does not iterate over all markers on every marker click.
