### ISSUE TITLE
Should `phx-hook-loading` be added to `PHX_EVENT_CLASSES`?

### ISSUE THREAD

**Issue by samharnack** [phoenixframework/phoenix_live_view#2941]
I'm trying to reduce flicker from scrolling elements into place within a Hook by using the `phx-hook-loading` class that gets added automatically via `putRef` as part of the mount process. However, if I add it manually to hide the element on start it's never removed.

```html
<div id="my-id" phx-hook="MyCustomHook" class="phx-hook-loading [&.phx-hook-loading]:invisible">
  Should be invisible while loading.
</div>
```

The expectation is that the `phx-hook-loading` class is removed via `undoRefs`.

https://github.com/phoenixframework/phoenix_live_view/blob/1fe6fade7aa85aeea4532bf07436b92d01cfadff/assets/js/phoenix_live_view/constants.js#L6

I'm happy to open a PR, just making sure I'm on the right track.

**Comment by SteffenDE** [comment]
I've been thinking about this for a while, but I think you're right. Since it's added via putRef it should also be removed via undoRefs as the other classes. Opened #3007.

**Comment by samharnack** [comment]
Thank you so much for this @SteffenDE 🎉

Looks like morphdom adds it back when restoring the node 😞: https://github.com/phoenixframework/phoenix_live_view/blob/main/assets/js/phoenix_live_view/dom_patch.js#L304

For anybody that might stumble across this... I ended up adding a `data-mounted` callback to the node and calling it from the hook:

```html
<div id="hook" phx-hook="TestHook" data-mounted={JS.remove_class("invisible")} class="invisible"></div>
```

Then in the hook:

```javascript
export default {
  mounted() {
    const { el } = this;
    const { dataset } = el;
    const { mounted } = dataset;

    // ....

    if (mounted) {
      this.liveSocket.execJS(el, mounted);
    }
  }
}
```

**Comment by SteffenDE** [comment]
@samharnack I think this is actually the correct solution 👍🏻
