### ISSUE TITLE
`stream_insert` with `:at` option prevent alpine JS to be executed

### ISSUE THREAD

**Issue by johanesa** [phoenixframework/phoenix_live_view#2943]
### Environment

* Elixir version (elixir -v): a.1.15.4
* Phoenix version (mix deps): 1.7.9
* Phoenix LiveView version (mix deps): 0.19.5
* Operating system: MacOS Sonoma
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, Safari, Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior
```
def handle_info({:created, item}, socket) do
    socket
    |> stream_insert(:items, item, at: 0)
    |> then(&{:noreply, &1})
  end
```

### Expected behavior

The item is inserted, and AlpineJS does not work on the item. My guess alpine JS is  executed on the newly rendered dom, but the `maybe_reoder_by` remove it. It works fine when the position is not set.  This [PR](https://github.com/phoenixframework/phoenix_live_view/pull/2904) by @Matsa59 can resolve this Issue .

**Comment by josevalim** [comment]
Excellent, let's continue the discussion in the PR then, but notice that we do not necessarily guarantee it all works under Alpine, but we are glad to consider PRs addressing particular issues.
