### ISSUE TITLE
`stream()` with en empty list but with new limit is not sent to browser

### ISSUE THREAD

**Issue by gorghoa** [phoenixframework/phoenix_live_view#2951]
### Environment

* Elixir version (elixir -v): 1.14
* Phoenix version (mix deps):  1.7.10
* Phoenix LiveView version (mix deps):  0.20.1
* Operating system: dockerized debian 11
* Browsers you attempted to reproduce this bug on (the more the merrier):  firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: not tried.

### Actual behavior

With LiveView 0.20.1, it seems that updating a stream with an empty list but with a new limit does not update the client.

1st call:

```ex
{:noreply, stream(socket, :elems, my_plenty_items_list, limit: 50)} 
```

2nd call:

```ex
{:noreply, stream(socket, :elems, [], limit: 10)}
```

The 2nd call is not sent to the view, the list is not reduced to 10 on the interface . I guess that is for performance reasons : don’t send stream event if no event to update.

### Expected behavior

I was expecting that the client would drop out of bound extra nodes based on new limit.

**Comment by csokun** [comment]
`:limit` is server filter https://github.com/phoenixframework/phoenix_live_view/blob/main/lib/phoenix_live_view/live_stream.ex#L23C5-L23C80

So LV reduces your items_list before sending it to the client.

Your 2nd call doesn't have any effect on the client cause you're sending an empty list. If the intention is to clear 40/50 items that had been rendered then you're using the wrong tool.

**Comment by gorghoa** [comment]
Thanks for your answer @csokun, not sure that’s the all story though :thinking: 

afaik, item list is not stored on server, that’s the point of streams. So, when updating an existing stream, the client must be somehow aware that it should drop existing items when a new batch of items arrive.

**Comment by chrismccord** [comment]
You need to pass `reset: true`. If you want it to prune the existing list on the client, you need to re-insert that list. The server doesn't know what the previous elements are, so without passing `reset: true`, all we know is you are trying to insert an empty list. I agree a new limit is an edge case, but I'm not sure what the behavior should be here as limit was added with the idea of limiting new insertions, not applying it to previously inserted items which we are no longer tracking. That said, this can be made to work on the client if you would like to send a PR. I'd happily evaluate a PR, but it's not something I can prioritize myself atm. Thanks!

**Comment by gorghoa** [comment]
Hi @chrismccord , thanks for the reply

> as limit was added with the idea of limiting new insertions, not applying it to previously inserted items

But any new limit sent along new items **does** apply to previously inserted items, no? 

For instance, if I have an initial list of 50 items, then add 2 new items  with a limit of 5 via `stream(socket, :mystream, [one, two], limit: 5)`, I assume the updated displayed list will be of 5, thus acting on previous now untracked items :thinking:. Or maybe I’m wrong and assuming wrong things is my main problem on this issue :D 


I’m sure using `reset:` is ok, it’s just more logic I have to do on my LV + a little more work for the server. Absolutely not a blocker in my case.


> if you would like to send a PR.

Not sure at all what would be the best way to modify this, but I’ll have a look eventually  if I find something I find valuable enough ^^

Have a good day!

**Comment by gorghoa** [comment]
see also #2686, I guess it is somehow related :thinking:

**Comment by SteffenDE** [comment]
I reopened this because I thought I could maybe address this when changing the limit handling in https://github.com/phoenixframework/phoenix_live_view/pull/3035, but with the current stream implementation this isn't something easy to do. You could implement this yourself by pushing an event:
`{:noreply, push_event(socket, "apply-stream-limit", %{ref: socket.assigns.streams[:my_stream].ref, limit: 10})}` and something like this in you `app.js`:

```javascript
window.addEventListener("phx:apply-stream-limit", (e) => {
  const streamRef = e.detail.ref
  const limit = e.detail.limit
  const streamChild = document.querySelector(`[data-phx-stream="${streamRef}"]`)
  if(streamChild){
    const parent = streamChild.parentElement
    let children = limit !== null && Array.from(parent.children)
    if(limit && limit < 0 && children.length > limit * -1){
      children.slice(0, children.length + limit).forEach(el => el.remove())
    } else if(limit && limit >= 0 && children.length > limit){
      children.slice(limit).forEach(el => el.remove())
    }
  }
});
```

This will not work correctly when using LiveComponents as stream children though, because they won't be properly destroyed.

**Comment by gorghoa** [comment]
Thanks @SteffenDE for having a go :) 

I also tried yesterday morning to have a shot and came to the same conclusion that actual implementation is not wired at all for such evolution. It was turtles all the way down and I stopped when it was clear that it would need taking too much decisions and changes for a problem with many easy ways to circumvent.

Won’t spam on this issue again, don’t worry all :D
