### ISSUE TITLE
Testing phx-click with both patch and push

### ISSUE THREAD

**Issue by jonatanklosko** [phoenixframework/phoenix_live_view#2954]
We have a button with

```
phx-click={JS.patch(~p"/sessions/#{@session.id}") |> JS.push("deploy_app")}
```

As of v0.20.2 the push is no longer dispatched on `render_click()` in tests. It's a regression from #2899, since now if we find patch, other events are ignored.

**Comment by josevalim** [comment]
The regression in particular has been fixed on main but ideally we want to execute both. cc @nmk in case you want to take a look!
