### ISSUE TITLE
LiveViewTest client renders child LiveComponents ~10x slower than actual browser

### ISSUE THREAD

**Issue by dspigarelli** [phoenixframework/phoenix_live_view#2957]
### Environment

* Elixir version (elixir -v): 1.15.7 (OTP 26)
* Phoenix version (mix deps): 1.7.10
* Phoenix LiveView version (mix deps): 0.20.2
* Operating system: Mac Intel
* Browsers you attempted to reproduce this bug on (the more the merrier): 
  * Chrome (120.0.6099.129 x86_64)
  * Firefox (121.0 64-bit)
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes
* Repro: https://github.com/dspigarelli/phoenix-repro/tree/repro/send-updates

### Actual behavior

A LiveView that renders a list of LiveComponents can take 2.5 seconds to return from `render_async/3` in a test, but only ~250ms when viewing in a browser (varies depending on environment).

Steps to repo:
1. Clone https://github.com/dspigarelli/phoenix-repro/tree/repro/send-updates
2. `mix deps.get`
3. `mix phx.server`
4. Navigate to http://localhost:4000/repro and observe the speed in the browser
5. `mix test test/repro_web/live/repro_live_test.exs`

I tried composing this as a single page app, but ran into trouble with the test part. This [gist](https://gist.github.com/dspigarelli/e785abe0662ab956c5f591f9ce2bbadf) can be run with `elixir slow_test_render_async.exs` to start the server, and `elixir slow_test_render_async.exs test` to run the test (currently failing on an :ets error)

### Expected behavior
The LiveViewTest client renders child LiveComponents comparable to browser behavior.

### Additional context
I discovered this issue because my test suite takes multiple seconds when testing this Liveview, a cost that is incurred every time the test calls `render_click`/`render_submit`/`render_async`/etc. This is a key LiveView in my project and accounts for 75% of the total test time (currently 16 minutes out of 22 minutes in my CI).

Digging into the code, I found that while the call to `render_async` takes a long time to complete, the interior [handle_call({:async_pids}, ...)](https://github.com/phoenixframework/phoenix_live_view/blob/edee91ae510cac4709efbd9c46942b3d1d9cea61/lib/phoenix_live_view/test/client_proxy.ex#L530-L534) completes in only a few milliseconds. The delay appears to be from the 400 "diff" events that are already in the process message queue and were taking on average 6.8ms each to complete [handle_info(%{event: "diff", ...})](https://github.com/phoenixframework/phoenix_live_view/blob/edee91ae510cac4709efbd9c46942b3d1d9cea61/lib/phoenix_live_view/test/client_proxy.ex#L439-L448). Also, I noticed that the first 200 "diff" events all had a payload of `%{c: %{}}`, which I understand as effectively no-ops.

My real world scenario has only 15 children (a two week calendar view) but significantly more HEEX template code. I bumped the repro child count to 200 to compensate for the reduced HEEX template code. My real world scenario has only 30 pending "diff" messages that on average completed in 45ms each, for a total time of 1.4 seconds. Again, the first 15 of those messages had a no-op payload of `%{c: %{}}`.

I timed the browser speed by placing the following conditional breakpoint on [this line](https://github.com/phoenixframework/phoenix_live_view/blob/edee91ae510cac4709efbd9c46942b3d1d9cea61/assets/js/phoenix_live_view/utils.js#L28), then refreshing the page:

```javascript
(function() { if (window.now) { return console.log(Date.now() - window.now)} else { window.now = Date.now(); } }())
```

### Conclusion
I'm not sure exactly what my options are here to reduce my test suite time. Having [handle_info(%{event: "diff"})](https://github.com/phoenixframework/phoenix_live_view/blob/edee91ae510cac4709efbd9c46942b3d1d9cea61/lib/phoenix_live_view/test/client_proxy.ex#L439-L448) complete in time comparable to the browser would be the ideal situation.

Otherwise it seems that my options are:
- rewrite my LiveView to remove LiveComponents,
- replace most of my LiveView tests with LiveComponent tests
- ???

I'm open to other suggestions.

### Possibly related
- https://github.com/phoenixframework/phoenix_live_view/issues/2855

**Comment by josevalim** [comment]
Good find. I have made it about twice faster by discarding empty patches. It is likely we can improve things further by profiling. So if anyone wants to give it a try, PRs are definitely welcome.

**Comment by josevalim** [comment]
To be clear, 50% faster on the example you provided, you will likely see faster times on your project. :)

**Comment by dspig** [comment]
> Good find. I have made it about twice faster by discarding empty patches. It is likely we can improve things further by profiling. So if anyone wants to give it a try, PRs are definitely welcome.

Thanks for the quick turn around. I'll try it out with my real world scenario.

**Comment by josevalim** [comment]
I can see about 10% improvement on Livebook's suite as well. :)

**Comment by dspigarelli** [comment]
Thanks for the quick turn around. I'll try it out with my real world scenario.

**Comment by dspigarelli** [comment]
I'm seeing a 20% reduction on my overall test suite and 27% reduction within the part of my test suite which relies heavily on the target Liveview

**Comment by josevalim** [comment]
@dspigarelli I just merged another PR that speeds up component rendering. Please try latest main/master. :)

**Comment by dspigarelli** [comment]
@josevalim Against latest [main](https://github.com/phoenixframework/phoenix_live_view/commit/c0d3acc0266478c43eb2cad884a67071d7d4b19a) I'm seeing a 27% reduction for my overall test suite and 40% reduction in the part of the suite that relies heavily on this Liveview.
