### ISSUE TITLE
SlideOver no longer getting handle_event on click of underlying page

### ISSUE THREAD

**Issue by tjchambers** [phoenixframework/phoenix_live_view#2964]
### Environment

* Elixir version (elixir -v): 1.15.4
* Phoenix version (mix deps): 1.7.10
* Phoenix LiveView version (mix deps): 0.20.2
* Operating system: MacOS
* Browsers you attempted to reproduce this bug on (the more the merrier): Safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: no

### Actual behavior

- Click link that Opens slide over
- Slide over opens (good)
- Click underlying page (outside of slideover)
- No handle_event is fired to close_slide_over

### Expected behavior

on 0.20.1 behavior was:

- Click on link that opens slider over
- Slide over handle_event is triggered and appears (same and good)
- Click anywhere outside slide_over on page (whitespace, another link, etc.) 
- Handle_event to close_slide_over is fired and handled and slide_over disappears 

I suspect this is a regression, as I am no longer getting any close_slide_over handle_event unless I click the close button on  the slide over itself which leads to a very poor UX.

**Comment by josevalim** [comment]
What slideOver are you talking about? It seems some important context is missing.

**Comment by tjchambers** [comment]
As an aside the only change I made during this test was phoenix_live_view from 0.20.1 -> 0.20.2 . No other changes were made.

**Comment by tjchambers** [comment]
https://petal.build/components/slide_over is the slipover code and it is version 1.7.1 latest.

**Comment by tjchambers** [comment]
Another piece of information which may not be relevant, but the options to close when click away and close on escape are by default true for this component and I am using the defaults. Hitting escape key when the slide over is showing DOES trigger the close_slide_over event. Clicking anywhere else on the page has no visible effect.

**Comment by tjchambers** [comment]
Seems this uses `phx-click-away` and noted in 0.20.2 release notes `* Extend visibility checks for phx-click-away to better handle whether an element is visible in the viewport or not`

**Comment by josevalim** [comment]
Please report this on petal or please reproduce the issue in a minimal app with LiveView and no external dependencies. :)

**Comment by tjchambers** [comment]
thanks - will report on petalcomponents first.

**Comment by josevalim** [comment]
Thank you! Feel free to open an issue with steps to reproduce if it is indeed a LiveView issue.
