### ISSUE TITLE
`Phoenix.LiveView.cancel_async/3` do not emit `handle_async/3`

### ISSUE THREAD

**Issue by sankaku-deltalab** [phoenixframework/phoenix_live_view#2972]
### Environment

* Elixir version (elixir -v): Elixir 1.14.3 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): 1.7.10
* Phoenix LiveView version (mix deps): 0.20.2
* Operating system: Windows 11 64bit
* Browsers you attempted to reproduce this bug on (the more the merrier): Chromium
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

When call `Phoenix.LiveView.cancel_async/3`, `handle_async/3` will not be called.

```ex
@impl true
def handle_event("add_count_async", _params, socket) do
  {:noreply, socket |> start_async(:add_count, fn -> :timer.sleep(1000) end)}
end

@impl true
def handle_event("cancel_add_count", _params, socket) do
  {:noreply, socket |> cancel_async(:add_count)}
end

@impl true
def handle_async(:add_count, {:ok, _} = result, socket) do
  IO.inspect(result, label: "handle_async add_count")

  {:noreply, socket |> update(:count, &(&1 + 1))}
end

@impl true
def handle_async(:add_count, {:exit, _} = result, socket) do
  # Expected: cancel_async emit this function
  # Actual: cancel_async do not emit this function
  IO.inspect(result, label: "handle_async add_count")

  {:noreply, socket}
end
```

Sample: https://github.com/sankaku-deltalab/phx_cancel_async/blob/main/lib/pca_web/live/async_live/index.ex

### Expected behavior

When call `Phoenix.LiveView.cancel_async/3`, `handle_async/3` will be called.

**Comment by josevalim** [comment]
I am not sure if this should actually be the case. If `cancel_async` calls it, then we would need a mechanism to distinguish cancelled ones from others that actually failed.

Given you are the one calling `cancel_async`, you could move what needs to happen on exit and cancellation to a shared function, and call it from both places, without coupling cancel_async with other exits.

**Comment by sankaku-deltalab** [comment]
Thank you for your response. Based on the documentation, I had understood `cancel_async` to emit `handle_async/3`.

https://hexdocs.pm/phoenix_live_view/0.20.2/Phoenix.LiveView.html#cancel_async/3

> Cancels an async operation if one exists.
> 
> Accepts either the %AsyncResult{} when using assign_async/3 or the key passed to start_async/3.
> 
> The underlying process will be killed with the provided reason, or {:shutdown, :cancel}. if no reason is passed. For assign_async/3 operations, the :failed field will be set to {:exit, reason}. For start_async/3, the handle_async/3 callback will receive {:exit, reason} as the result.
> 
> Returns the %Phoenix.LiveView.Socket{}.

Based on this description, I thought of distinguishing between cancelled and failed async operations by using the `reason` passed to `cancel_async`. Here is an example approach:

```elixir
@impl true
def handle_event("cancel_add_count", _params, socket) do
  {:noreply, socket |> cancel_async(:add_count, {:shutdown, :cancel})}
end

@impl true
def handle_async(:add_count, {:exit, {:shutdown, :cancel}} = result, socket) do
  # Canceled
  {:noreply, socket}
end

@impl true
def handle_async(:add_count, {:exit, _} = result, socket) do
  # Error in async
  {:noreply, socket}
end
```

However, if `handle_async` is not invoked upon cancellation, I am considering implementing the cancellation process as follows:

```elixir
@impl true
def handle_event("cancel_add_count", _params, socket) do
  {:noreply, socket |> cancel_async(:add_count) |> add_count_async_aborted()}
end

@impl true
def handle_async(:add_count, {:exit, _} = result, socket) do
  # Error in async
  {:noreply, socket |> add_count_async_aborted()}
end

defp add_count_async_aborted(socket) do
  socket |> put_flash(:error, "add_count aborted")
end
```

If there is any misunderstanding on my part, or if there is room for improvement, I would appreciate your guidance.

Best regards.
