### ISSUE TITLE
UpChunk multi-part client side upload to S3/minio doesn't work, missing partNumber

### ISSUE THREAD

**Issue by chris838** [phoenixframework/phoenix_live_view#2978]
This example for chunked uploads using UpChunk doesn't work, at least when using minio, which in theory should be the same as S3.

https://github.com/phoenixframework/phoenix_live_view/blob/343911f9d3db27e703df278c81495fa6a9e55603/guides/client/uploads-external.md?plain=1#L78C7-L78C7

The upload PUT requests are missing the `partNumber` parameter, which should be enumerated for all parts. This means every chunk overwrites each other, and the result is only the final chunk stored in minio.

Technically I guess this is an UpChunk problem, but the result is example code that doesn't work as described. Perhaps there is some way to ensure UpChunk includes this parameter, but I haven't found anything.

I'm about to look at https://github.com/Buzut/huge-uploader as an alternative.

**Comment by chris838** [comment]
Looks like actually you need a distinct pre-signed URL for each part, with the `partNumber` and probably a unique `X-Amz-Signature`?

Perhaps the issue is in generating the presigned URL.

**Comment by chris838** [comment]
Eventually got this working but had to fork upchunk here: https://github.com/tractive-ai/upchunk-s3

It also requires some way of generating presigned URLs for each part, gathering the ETags and then completing the upload.

Here's my very hacky uploader implementation. I think a better way would be to abandon creating a JS uploader and just create a custom hook, then handle all the back and forth with the LiveView socket (rather than creating new endpoints).

Unless the LiveView socket can be accessed from an uploader somehow.

```
const UpChunkS3 = function (entries, onViewError) {
    entries.forEach((entry) => {
        // Extract the upload ID when we started the session
        let {
            file,
            meta: { bucket, key, uploadId },
        } = entry;

        // Promise for generating endpoint URLs for each chunk
        function getUploadUrl(partNumber) {
            return fetch(
                `/app/generate_presigned_url_for_part?bucket=${encodeURIComponent(
                    bucket
                )}&key=${encodeURIComponent(key)}&uploadId=${encodeURIComponent(
                    uploadId
                )}&partNumber=${encodeURIComponent(partNumber)}`
            )
                .then((response) => {
                    if (!response.ok) {
                        throw new Error("Network response was not ok");
                    }
                    return response.json();
                })
                .then((data) => {
                    return data.url;
                })
                .catch((error) => {
                    console.error("Error fetching presigned URL:", error);
                });
        }

        // create the upload session with UpChunk
        let upload = MuxUpChunkS3.createUpload({
            endpoint: getUploadUrl,
            chunkSize: 30720,
            file,
        });

        // stop uploading in the event of a view error
        onViewError(() => {
            console.log(`View error, pausing upload.`);
            upload.pause();
        });

        etags = new Map();
        upload.on("chunkSuccess", (e) => {
            this.etags.set(e.detail.partNumber, e.detail.response.headers.etag);
        });

        // upload error triggers LiveView error
        upload.on("error", (e) => entry.error(e.detail.message));

        // notify progress events to LiveView
        upload.on("progress", (e) => {
            if (e.detail < 100) {
                entry.progress(e.detail);
            }
        });

        // success completes the UploadEntry
        upload.on("success", () => {
            const partsArray = Array.from(this.etags, ([partNumber, etag]) => ({
                [partNumber]: etag.replace(/[^A-Za-z0-9]/g, ""),
            }));
            const partsJson = JSON.stringify(partsArray);
            fetch(
                `/app/complete_multipart_upload?bucket=${encodeURIComponent(
                    bucket
                )}&key=${encodeURIComponent(key)}&uploadId=${encodeURIComponent(
                    uploadId
                )}&parts=${encodeURIComponent(partsJson)}`
            ).then((data) => {
                entry.progress(100);
            });
        });
    });
};
```

**Comment by chrismccord** [comment]
Chunked multipart is necessarily going to involve more moving pieces. Sounds like a great blog post, but not something I feel our examples need to cover inside the docs. Thanks!
