### ISSUE TITLE
Checkboxes aren't selectable inside a phx-click element

### ISSUE THREAD

**Issue by aaronrenner** [phoenixframework/phoenix_live_view#298]
### Environment

* Elixir version (elixir -v): 1.9.1
* Phoenix version (mix deps): 1.4.9
* NodeJS version (node -v): 12.6.0
* NPM version (npm -v): 6.9.0
* Operating system: MacOS 10.14.6 
* Browser: Chrome and Safari (haven't tested others)

### Actual behavior

Whenever a checkbox is inside of a `phx-click` it not able to be clicked. Instead the parent element's `phx-click` event is sent to the server.

![Checkbox issue - medium](https://user-images.githubusercontent.com/120878/62740797-03e5dc80-b9f6-11e9-9aa2-0215b2146d57.gif)

Here is an example project that recreates the issue: https://github.com/aaronrenner/live_view_playground/tree/checkbox-click-issue (check out the `checkbox-click-issue` branch). 

This module shows the various permutations I've tried and only the first template (without `phx-click`) works: https://github.com/aaronrenner/live_view_playground/blob/checkbox-click-issue/lib/phoenix_one_four_web/views/sample_form_view.ex#L6-L66

### Expected behavior

Since you're still able to click and type in text boxes that are inside a `phx-click`, it seems like you should also be able to check checkboxes inside a `phx-click`.

**Comment by snewcomer** [comment]
@aaronrenner Thx for putting up this issue!  Just a note, uniqueness is required for the id attribute document wide.  When we go to diff/replace, the we are relying on this standard as well.  Just in case you might have a similar pattern in a project of yours.  

<img width="786" alt="Screen Shot 2019-08-31 at 1 41 33 PM" src="https://user-images.githubusercontent.com/7374640/64068970-10281880-cbf5-11e9-9929-659b9c2eaf97.png">

However, for your actual issue, I pared it down to one `render` for testing (so not sure what multiple forms will do). We want to stop propagation or nothing at all.  I'll let Chris confirm. 

https://github.com/phoenixframework/phoenix_live_view/pull/330/files
