### ISSUE TITLE
Minimum on <input type="date"> causes browser state to be lost while typing date on Chrome

### ISSUE THREAD

**Issue by shadowfacts** [phoenixframework/phoenix_live_view#2984]
### Environment

* Elixir version (elixir -v): 1.15.7
* Phoenix version (mix deps): 1.7.10
* Phoenix LiveView version (mix deps): 0.20.3
* Operating system: macOS 14.1.2
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome (does not repro on Firefox, Safari)
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

When using an `<input type="date">` with the `min` attribute set, typing in a full date (month, day, year) causes Chrome to reset some internal state

Example live view that reproduces this:
```elixir
defmodule LiveDateTestWeb.TestLive do
  use LiveDateTestWeb, :live_view
  def mount(_params, _session, socket) do
    {:ok, assign(socket, data: %{"date" => ""})}
  end
  def render(assigns) do
    ~H"""
    <.form :let={f} for={@data}>
      <%= Phoenix.HTML.Form.date_input(f, :date, phx_change: "date", min: "2023-01-04") %>
    </.form>
    """
  end
  def handle_event("date", %{"date" => date}, socket) do
    {:noreply, assign(socket, data: %{"date" => date})}
  end
end
```

Steps to reproduce:
1. Visit the live view in Chrome
2. Select the month field of the date input
3. Type in a month and day
4. Attempt to type in a year
5. Observe that typing in the second character of the year fails (e.g., typing 2345 for the year results in the year field reading 0005)

In the following screen recording, my keystrokes were `11112345`:

https://github.com/phoenixframework/phoenix_live_view/assets/7091588/ad9478d4-3f61-4d1e-8509-ac74aaf63452

### Expected behavior

Typing in a date does not cause the browser to lose any state and the user can finish typing the year successfully.

---

The underlying cause of the issue is twofold:

1. When merging the updates into the DOM, LiveView always calls `setAttribute` regardless of whether the value actually changes (`min` does not): https://github.com/phoenixframework/phoenix_live_view/blob/dd89eea5b70d0c89a3a7148ddab093a0de6393d9/assets/js/phoenix_live_view/dom.js#L363
2. When the `min`/`max` attributes are set (regardless of whether the value changed), Chrome always destroys and recreates the shadow DOM of the input, which effectively resets the type ahead buffer. (The old element had no value and a type ahead buffer containing `2`, and the new element has a value of `2` and an empty type ahead buffer. So, when the next character (`3`) is typed, it's the only thing in the buffer and replaces the actual value of `2`).
    1. https://github.com/chromium/chromium/blob/4de1cec1246698932cde06c8d628130b4541a93c/third_party/blink/renderer/core/html/forms/multiple_fields_temporal_input_type_view.cc#L526-L528
    2. https://github.com/chromium/chromium/blob/4de1cec1246698932cde06c8d628130b4541a93c/third_party/blink/renderer/core/html/forms/date_time_edit_element.cc#L780-L810

**Comment by SteffenDE** [comment]
Thank you for the great and very in-depth writeup. I'm wondering if we can just add something like

```javascript
if(exclude.indexOf(name) < 0){
  if (target.getAttribute(name) !== source.getAttribute(name)) {
    target.setAttribute(name, source.getAttribute(name))
  }
} 
```

I added a PR that implements this and from my testing this indeed fixes the problem you described. Let's see what the maintainers say.
