### ISSUE TITLE
Confusing behavior by push_navigate in phx-submit event

### ISSUE THREAD

**Issue by anotherzxx** [phoenixframework/phoenix_live_view#2985]
Since both `push_navigate` and `phx-submit` dispatch `phx:page-loading-start` and `phx:page-loading-stop` event, combing them causes two `start` event and then two `stop` event.

It would be more rational if the second `start` event and the first `stop` event were not dispatched.

The topbar would be hide a bit earlier than the navigation is completed in this example.
```javascript
import topbar from "topbar"
window.addEventListener("phx:page-loading-start", info => topbar.show())
window.addEventListener("phx:page-loading-stop", info => topbar.hide())
```

**Comment by josevalim** [comment]
I think this is somehow expected, as Those are two different events. For example, you could have some JS execute between them too for some time. Is it now a single one? I would say delaying the topbar is probably the best call here and I would improve usability too.

**Comment by anotherzxx** [comment]
Thanks for your answer.

Just used a simple solution like this in my code:
```
let phxPageLoading = 0

addEventListener(
  'phx:page-loading-start',
  _ =>
    phxPageLoading++ == 0 &&
    document.body.classList.add('has-[.phx-connected]:opacity-50')
)

addEventListener(
  'phx:page-loading-stop',
  _ =>
    --phxPageLoading == 0 &&
    document.body.classList.remove('has-[.phx-connected]:opacity-50')
)
```

Thought it would be helpful for others.
