### ISSUE TITLE
Confusing documentation? LiveComponent -> Life-cycle -> Mount and update

### ISSUE THREAD

**Issue by gregjohnsonsaltaire** [phoenixframework/phoenix_live_view#2987]
> After the component is updated, [render/1](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveComponent.html#c:render/1) is called with all assigns. On first render, we get:
>     mount(socket) -> update(assigns, socket) -> render(assigns)
> On further rendering:
>     update(assigns, socket) -> render(assigns)

On further rendering  implies update/2 (callback) is called before render/1 (callback), which conflicts with the diagram at "Summary" and with the actual life-cycle.

Perhaps the documentation should read:

>On further rendering:
>    handle_event(event, unsigned_params, socket) -> render(assigns)

to match the Summary diagram and the actual life-cycle.

**Comment by chrismccord** [comment]
if the component is being updated from the parent `<.live_component ... foo={@bar}` and `@bar` changes, then the update => render flow applies, so the documentation is correct. It does not speak to the encapsulated handle_event flow, which would indeed be `handle_event => render`. If you'd like to speak to this flow in the docs, we'd gladly accept a PR. Thanks!
