### ISSUE TITLE
False/nil attributes rendered with empty string 

### ISSUE THREAD

**Issue by dmorneau** [phoenixframework/phoenix_live_view#2988]
According to the documentation, an attribute with value false or nil is not rendered:

https://github.com/phoenixframework/phoenix_live_view/blob/096d8ee5b6203128926127df5640bfe5a2715d4e/lib/phoenix_component.ex#L647

In reality the attribute appears to be rendered with an empty string value:

https://github.com/phoenixframework/phoenix_live_view/blob/096d8ee5b6203128926127df5640bfe5a2715d4e/test/phoenix_live_view/html_engine_test.exs#L299-L300

Which one is correct?

(The behavior seems to have changed slightly between 0.20.1 and 0.20.2, as a dynamic attribute like `{[class: nil]}` previously ignored now renders `class=""` - maybe due to #2930?)

**Comment by josevalim** [comment]
This is an optimization. If know we rendering an empty string is safe, then we render it, and we need to send less dynamic data to the client. Perhaps we should add a note about this?

**Comment by chrismccord** [comment]
Please add a doc PR if you'd like. Thanks!
