### ISSUE TITLE
Live Component getting removed from DOM unexpectedly 

### ISSUE THREAD

**Issue by threeaccents** [phoenixframework/phoenix_live_view#2990]
### Environment

* Elixir version (elixir -v): 14.4.4
* Phoenix version (mix deps): 1.7.10
* Phoenix LiveView version (mix deps): tried 0.20.1 - 0.20.3
* Operating system: linux
* Browsers you attempted to reproduce this bug on (the more the merrier): all
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

Live Component that has no visibility toggling and all ids are set properly keeps getting removed from the DOM. Happens when some sort of state change occurs.
https://www.loom.com/share/f678f1587a7749b59954d9d70dbe6d42

### Expected behavior
The live component is not removed from the DOM.

**Comment by josevalim** [comment]
Thank you for the report. Please provide a minimal app that reproduces the error. Otherwise it is hard to reproduce the error without an application we can debug. Thanks!

**Comment by threeaccents** [comment]
@josevalim I couldn't create a minimal app to reproduce the issue. However I was able to "fix" the issue by removing the use of `async_assign` for the table data. I also noticed that removing a JS Hook I had in my live component also stopped LV from sending the `cids_will_destroy` message for my Live Component.

For now I'm just going to stick to the regular assigns for my data as I can't spend too much time looking into this issue. I do plan though for end of this week or early next week to do a deeper dive and get a minimal app with the issue. Speaking to the greater PepsiCo team someone else had encountered a very similar issue. They had a live component with a hook that after loading kept getting removed from the DOM. Their issue though was related to the fact that the `async_result` destroys the element when switching from loading to result. They bypassed their issue by creating an overlay based `async_result` helper.

Though I wasn't using the `async_result` helper for my code our issues were too similar to not be related.

For now I will close this issue and hopefully end of week I can bring forward more valuable information.

**Comment by chrismccord** [comment]
Without a reproduction we can't say what is going on. cids_will_destroy is sent when the DOM container for the LC is removed from the dom. The way things work should accommodate the LC being "swapped" to a different place in the DOM, but it's possible there is a bug with our component tracking. If you can put together a reproduction, please do! Thanks!
