### ISSUE TITLE
"phx-disable-with" disables button completely

### ISSUE THREAD

**Issue by PJUllrich** [phoenixframework/phoenix_live_view#2993]
### Environment

* Elixir version (elixir -v): `1.15.7`
* Phoenix version (mix deps): `1.17.10`
* Phoenix LiveView version (mix deps): `0.20.1`
* Operating system: `macOS Sonoma`
* Browsers you attempted to reproduce this bug on (the more the merrier): `Arc (Chrome)`
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: `Yes`

### Actual behavior

When I set the `phx-disable-with` flag on a button and click the button, the button doesn't re-enable after the server sent the response.

Usually, the button would be disabled right after I clicked it and while the server processes the event, but then re-enable after the server responds to the event and the browser received the response. However, if I set the `phx-disable-with` parameter, the button stays disabled and I need to reload the page to fix it.

Here's a demo. The `HTML Button` has no `phx-disable-with` set and works as expected. The other two buttons have `phx-disable-with` and stay disabled. I also tested whether this is a LiveView vs LiveComponent or "HTML Button" vs CoreComponent button issue, but this doesn't seem to make a difference.

![CleanShot 2024-01-09 at 11 04 27](https://github.com/phoenixframework/phoenix_live_view/assets/10426523/5e50a4c7-35e1-49f4-9c0b-179cc1fdebb7)

I created an example repo that replicates this issue here: https://github.com/PJUllrich/button

### Expected behavior

The button should re-enable after the server sent a response.

**Comment by josevalim** [comment]
Does it only fail if inside a component?

**Comment by chrismccord** [comment]
This only happens when the server sends no diff. I will take a look. Thanks!

**Comment by PJUllrich** [comment]
Thank you @chrismccord May I ask when you plan on releasing the new version with the bugfix on Hex?
