### ISSUE TITLE
sigil_L misses code coverage

### ISSUE THREAD

**Issue by TheFirstAvenger** [phoenixframework/phoenix_live_view#301]
This code shows a lack of code coverage on line 2 but coverage on line 3

```elixir
    ~L"""
      <%= if @foo do %>
        <span><%= "hello" <> "world" %></span>
      <% end %>
    </div>
    """
```
The same code with `~E` shows coverage on both lines:
```
    ~E"""
      <%= if @foo do %>
        <span><%= "hello" <> "world" %></span>
      <% end %>
    </div>
    """
```
Repo containing minimal reproduction (in `page_view.ex`):
https://github.com/TheFirstAvenger/liveview_coverage_example

![Screen Shot 2019-08-12 at 3 51 39 PM](https://user-images.githubusercontent.com/8557871/62893914-9ac5d800-bd19-11e9-9316-e360f42c4823.png)

**Comment by chrismccord** [comment]
Will gladly accept a PR for this, but not a priority for me at the moment. Thanks!
