### ISSUE TITLE
Bulk stream inserts at some indices inserts in reverse order

### ISSUE THREAD

**Issue by dspigarelli** [phoenixframework/phoenix_live_view#3023]
### Environment

* Elixir version (elixir -v): Elixir 1.15.7 (compiled with Erlang/OTP 26)
* Phoenix version (mix deps): 1.7.10
* Phoenix LiveView version (mix deps): 0.20.3
* Operating system: macOS Sonoma 14.2.1
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome 120.0.6099.216 (Official Build) (x86_64)
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

Repro: https://gist.github.com/dspigarelli/362a33237fed29929fb02d3063d176aa

### Actual behavior

When calling [stream/4](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#stream/4) with a list of items and an `at` of anything other than -1, the list of items is inserted in reverse order.

Examples:
```elixir
  stream(socket, :list, [%{id: 1}, %{id: 2}]) # inserted as [1,2]
  stream(socket, :list, [%{id: 1}, %{id: 2}], at: -1) # inserted as [1,2]
  stream(socket, :list, [%{id: 1}, %{id: 2}], at: 0) # inserted as [2,1] <<<<< reverse order insert
  stream(socket, :list, [%{id: 1}, %{id: 2}], at: 1) # inserted as [2,1] <<<<< reverse order insert
```

### Expected behavior

Examples:
```elixir
  stream(socket, :list, [%{id: 1}, %{id: 2}]) # inserted as [1,2]
  stream(socket, :list, [%{id: 1}, %{id: 2}], at: -1) # inserted as [1,2]
  stream(socket, :list, [%{id: 1}, %{id: 2}], at: 0) # inserted as [1,2]
  stream(socket, :list, [%{id: 1}, %{id: 2}], at: 1) # inserted as [1,2]
```

I suspect that on bulk insert, specifying `at` for a list is interpreted as "insert each item separately at the index X", which causes any index other than -1 to be inserted in effectively reverse order. I can understand if this means just a documentation change to specify the behavior.

**Comment by chrismccord** [comment]
Closed via f64c13027bbc33dfe965a7b2180cc61b005194ae
