### ISSUE TITLE
Nested form in live component not re-rendering after update

### ISSUE THREAD

**Issue by syamilmj** [phoenixframework/phoenix_live_view#3026]
### Environment

* Elixir version (elixir -v): 1.16.0
* Phoenix version (mix deps): 1.7.10
* Phoenix LiveView version (mix deps): 0.20.2
* Operating system: Mac OS
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

After upgrading to 0.20.2 from 0.20.1 I have noticed that a form inside a live component no longer re-renders completely after the parent live view has been updated. This seems to happen under a very specific condition where the live component sends an update to the parent that triggers an asynchronous event, handled via `handle_event/3`.

Here's a minimal example to reproduce this bug: https://gist.github.com/syamilmj/55dbac9fef7f93d183a384519d81314b

1. Wait for the page to load
2. Fill in the form and git Submit
3. Notice that the form is not being re-rendered completely

### Expected behavior

Nested form in live component should be rendered fully after update.

**Comment by tmjoen** [comment]
This happens to me with other elements too. They are marked as data-phx-skip and are empty. I have been having a hard time reproducing it, but maybe there are some things I could try from this to see if it's the same issue

**Comment by syamilmj** [comment]
@chrismccord I am still able to reproduce this issue from latest main.

**Comment by SteffenDE** [comment]
Are you testing with your single file script? Make sure that you are using also the javascript from main:

```
<script src={"https://cdn.jsdelivr.net/gh/phoenixframework/phoenix_live_view@main/priv/static/phoenix_live_view.min.js"}></script>
```

**Comment by SteffenDE** [comment]
Okay, can confirm that there's another problem with the patch

**Comment by SteffenDE** [comment]
@syamilmj Please try `<script src="https://cdn.jsdelivr.net/gh/SteffenDE/phoenix_live_view@issue_3026_test_assets/priv/static/phoenix_live_view.js"></script>`.

**Comment by syamilmj** [comment]
@SteffenDE thank you, that fixed it!

**Comment by sevenseacat** [comment]
I'm still seeing this on the latest version of LiveView (0.20.12). but seemingly only in some very specific circumstances. The fields don't render if -
* The fields are in a function component
* The root level of the function component is an element without an ID on it OR
* The root level of the function component doesn't have any static content 
eg.
```heex
    ~H"""
    static content
    <div phx-feedback-for={input_name(@form, @field)}>
    ...
```

Adding an ID (even a static one) seems to fix the issue for me so I can work around it, but I'll do some more digging!

**Comment by SteffenDE** [comment]
@sevenseacat do you see `data-phx-skip` in the DOM?

**Comment by sevenseacat** [comment]
Yes, I do!

**Comment by SteffenDE** [comment]
It would be great if you can create a minimal example to reproduce and create a new issue. You can use this to get started:

```elixir
Application.put_env(:sample, Example.Endpoint,
  http: [ip: {127, 0, 0, 1}, port: 5001],
  server: true,
  live_view: [signing_salt: "aaaaaaaa"],
  secret_key_base: String.duplicate("a", 64)
)

Mix.install([
  {:plug_cowboy, "~> 2.5"},
  {:jason, "~> 1.0"},
  {:phoenix, "~> 1.7"},
  # please test your issue using the latest version of LV from GitHub!
  {:phoenix_live_view, github: "phoenixframework/phoenix_live_view", branch: "main", override: true},
])

# build the LiveView JavaScript assets (this needs mix and npm available in your path!)
path = Phoenix.LiveView.__info__(:compile)[:source] |> Path.dirname() |> Path.join("../")
System.cmd("mix", ["deps.get"], cd: path, into: IO.binstream())
System.cmd("npm", ["install"], cd: Path.join(path, "./assets"), into: IO.binstream())
System.cmd("mix", ["assets.build"], cd: path, into: IO.binstream())

defmodule Example.ErrorView do
  def render(template, _), do: Phoenix.Controller.status_message_from_template(template)
end

defmodule Example.HomeLive do
  use Phoenix.LiveView, layout: {__MODULE__, :live}

  def mount(_params, _session, socket) do
    {:ok, assign(socket, :count, 0)}
  end

  def render("live.html", assigns) do
    ~H"""
    <script src="/assets/phoenix/phoenix.js"></script>
    <script src="/assets/phoenix_live_view/phoenix_live_view.js"></script>
    <%!-- uncomment to use enable tailwind --%>
    <%!-- <script src="https://cdn.tailwindcss.com"></script> --%>
    <script>
      let liveSocket = new window.LiveView.LiveSocket("/live", window.Phoenix.Socket)
      liveSocket.connect()
    </script>
    <style>
      * { font-size: 1.1em; }
    </style>
    <%= @inner_content %>
    """
  end

  def render(assigns) do
    ~H"""
    <%= @count %>
    <button phx-click="inc">+</button>
    <button phx-click="dec">-</button>
    """
  end

  def handle_event("inc", _params, socket) do
    {:noreply, assign(socket, :count, socket.assigns.count + 1)}
  end

  def handle_event("dec", _params, socket) do
    {:noreply, assign(socket, :count, socket.assigns.count - 1)}
  end
end

defmodule Example.Router do
  use Phoenix.Router
  import Phoenix.LiveView.Router

  pipeline :browser do
    plug(:accepts, ["html"])
  end

  scope "/", Example do
    pipe_through(:browser)

    live("/", HomeLive, :index)
  end
end

defmodule Example.Endpoint do
  use Phoenix.Endpoint, otp_app: :sample
  socket("/live", Phoenix.LiveView.Socket)

  plug Plug.Static, from: {:phoenix, "priv/static"}, at: "/assets/phoenix"
  plug Plug.Static, from: {:phoenix_live_view, "priv/static"}, at: "/assets/phoenix_live_view"

  plug(Example.Router)
end

{:ok, _} = Supervisor.start_link([Example.Endpoint], strategy: :one_for_one)
Process.sleep(:infinity)
```
