### ISSUE TITLE
Passing data between parent and child live_views

### ISSUE THREAD

**Issue by Cinderella-Man** [phoenixframework/phoenix_live_view#3028]
Hello :wave: 

### Environment

* Elixir version (elixir -v):
Erlang/OTP 26 [erts-14.1] [source] [64-bit] [smp:24:24] [ds:24:24:10] [async-threads:1] [jit:ns]
Elixir 1.15.6 (compiled with Erlang/OTP 24)
* Phoenix version (mix deps): "~> 1.7.3"
* Phoenix LiveView version (mix deps): "~> 0.20"
* Operating system: Ubuntu
* Browsers you attempted to reproduce this bug on (the more the merrier):  Brave [Version 1.61.116 Chromium: 120.0.6099.217 (Official Build) (64-bit)]
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: NA

### Actual behavior

I can't pass any data between parent live_view and the child live_view. Based on the current implementation:

https://github.com/phoenixframework/phoenix_live_view/blob/b3bc8eda49d706475cd841b2a630cdee978fa0c8/lib/phoenix_live_view/static.ex#L177

All of the parent's assigns are deeply nested inside the child's socket:

```
elem(socket.private.assign_new, 0)
```

### Expected behavior

I would love to be able to pass any information down to the child live_view and have them either assigned to the socket or kick off some callback in the nested live_view(where I can set my socket based on the passed data maybe working like the `update` from the live_component)

### Backstory

Example usage of this could be: I'm creating a multi person chat "plugin" that will be used as add-on to multiple views, I would like it to handle it's own events as well as handle_infos(pubsub) without views even being aware of actions inside the "chat". Chat on initialization requires to know some stuff about the user/view etc. - hence I need to pass some details from the main live_view to the "chat" live_view. The (nested) live_view abstractions are in this case a way better fit than live_component as they are separate processes(handle_event & handle_info are sent to the nested process automatically).

Thanks in advance for taking time to read this and any feedback would be appreciated :pray:

**Comment by josevalim** [comment]
Yes, LiveViews are designed to be mounted independently, as we provide an optimization via `assigns_new`, but not a guarantee. All information necessary needs to be passed in the session and then you rebuild it in the child LiveView.

**Comment by Cinderella-Man** [comment]
Thank you very much for responding. As I wanted to implement a feature using nested live_views - could I ask a few questions:
- "All information necessary needs to be passed in the child session" - this means a `session` key in `opts` (3rd argument) to the `live_render/3` function? (https://hexdocs.pm/phoenix_live_view/Phoenix.Component.html#live_render/3). As all of this will go to the browser session, that's limiting the amount/possibilities drastically(as some data shouldn't be passed to the browser etc.)
- "if the child LiveView crashes, it can always rebuild itself with the latest information." - I'm getting `:not_mounted_at_router` instead of params inside the nested Liveview - does this means that I need to assign absolutely everything to the `session` that comes as a `param` inside the parent Liveview so I will be able to use it inside the nested Liveview?
- maybe I'm completely wrong about using nested Liveviews - how would you try to add completely independent(managing it's own handle_event & handle_info callbacks) "plugin" that needs to know a little bit about the currently open page, logged user, some dynamic configuration passed from the outside etc.?

Any recommendations/feedback would be much appreciated :+1:  :pray:

**Comment by SteffenDE** [comment]
You can use message passing to send information like updated params to child LiveViews. The child has the pid of the parent as `socket.parent_pid`, therefore you can `send(socket.parent_pid, {:child, self()})` and have a `handle_info` in the parent that stores the child pid. Whenever handle_params in the parent is called you can send the new params using `send` with the child pid.

**Comment by josevalim** [comment]
>  this means a session key in opts (3rd argument) to the live_render/3 function? 

As the docs say, you don't need to pass the whole data, only how to fetch the data. For example, the data IDs.

Another option is for you to implement a handle_call in the parent LiveView and have the child LiveView ask it for the data it needs using `GenServer.call`.

For more feedback/suggestions, I recommend a discussion in the forums. :)
