### ISSUE TITLE
Exception when implementing handle_params/3 when rendering from within a template

### ISSUE THREAD

**Issue by mononym** [phoenixframework/phoenix_live_view#303]
### Environment

Not at the computer that this happened on, but it doesn't matter. Issue is definitely with the code.

### Actual behavior

Assuming this declaration within an `.eex` template:
`<%= Phoenix.LiveView.live_render(@conn, AppWeb.ThermostatLive, session: %{user_id: @user.id}) %>`

There will be a mismatch on this line here:
https://github.com/phoenixframework/phoenix_live_view/blob/master/lib/phoenix_live_view/channel.ex#L152

Which is due to this incorrect line matching in the case statement:
https://github.com/phoenixframework/phoenix_live_view/blob/master/lib/phoenix_live_view/view.ex#L365

Basically, the view module expects the following format:
`%{plug: Phoenix.LiveView.Plug, plug_opts: ^view, path_params: path_params}`

The view parameter *should* be `AppWeb.ThermostatLive`, and is when you're rendering from the controller or from the router. But if you're making the above render call from within a template the value of `plug` and `plug_opts` will not match.

If I am rendering `:show` for `SimulationController`, for example, the value for plug would be `SimulationController` and the plug_opts would be `:show`.

### Expected behavior

The handle_params callback is properly called and there is no crash within LiveView code.

**Comment by josevalim** [comment]
You were never meant to call `live_redirect` from a child live view, so we wrote the assertive code, but it should instead raise a better error message. :) I have done so in a branch I will push soon, thanks!
