### ISSUE TITLE
Documentation for [:phoenix, :live_component, :update, :stop] telemetry event

### ISSUE THREAD

**Issue by rhcarvalho** [phoenixframework/phoenix_live_view#3036]
### Environment

* Elixir version (elixir -v): N/A
* Phoenix version (mix deps): 1.7.10
* Phoenix LiveView version (mix deps): 0.20.3
* Operating system: N/A
* Browsers you attempted to reproduce this bug on (the more the merrier): N/A
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: N/A

### Actual behavior

Documentation:
https://hexdocs.pm/phoenix_live_view/telemetry.html

```
[:phoenix, :live_component, :update, :stop] - Dispatched by a [Phoenix.LiveComponent](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveComponent.html) when the [update/2](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveComponent.html#c:update/2) or a [update_many/1](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveComponent.html#c:update_many/1) callback completes successfully.

In the case of[update/2](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveComponent.html#c:update/2) it might dispatch one event for multiple calls. The sockets metadata contain the updated sockets.

Measurement:

%{duration: native_time}

Metadata:

%{
  socket: Phoenix.LiveView.Socket.t,
  component: atom,
  assigns_sockets: {map(), Phoenix.LiveView.Socket.t},
  sockets: Phoenix.LiveView.Socket.t
}
```

My telemetry logger:

```
  def lc_update_stop(_event, measurement, metadata, _config) do
    %{socket: socket, component: component, assigns_sockets: {assigns, _socket}} = metadata
    %{duration: duration} = measurement

    # ...
  end
```

The observed behavior is that the pattern matching fails. Seems that `assigns_sockets` is a `[{assigns, socket}]`, a list and not a single value as documented.

Similarly, I think `sockets` is a list and not a single socket.

Tests confirming the `assigns_sockets` is a list: https://github.com/phoenixframework/phoenix_live_view/blob/2d573f7e2fc02f04869568b00b05fd869e51abfd/test/phoenix_live_view/integrations/telemetry_test.exs#L290-L296

### Expected behavior

The behavior doesn't match the docs. If the documentation is indeed wrong I can contribute a small change (but am equally happy if someone else updates it or clarifies the behavior).

**Comment by rhcarvalho** [comment]
Found https://github.com/phoenixframework/phoenix_live_view/blob/2d573f7e2fc02f04869568b00b05fd869e51abfd/lib/phoenix_live_view/diff.ex#L661-L687

Unless I'm reading it wrong, the docs should be corrected to say:

```
Metadata:

%{
  socket: Phoenix.LiveView.Socket.t,
  component: atom,
  assigns_sockets: [{map(), Phoenix.LiveView.Socket.t}],
  sockets: [Phoenix.LiveView.Socket.t]
}
```

**Comment by josevalim** [comment]
Yes, Please do submit a pull request!
