### ISSUE TITLE
Enter key press for simple_form and :new live_action closes modal disregarding form/changeset errors after 0.20 update

### ISSUE THREAD

**Issue by YYOANN** [phoenixframework/phoenix_live_view#3040]
### Environment

* Elixir version (elixir -v): 1.15.7
* Phoenix version (mix deps): 1.7.10
* Phoenix LiveView version (mix deps): 0.20.3
* Operating system: Linux
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox / Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

Steps to reproduce:
* Create a new liveview project: `mix phx.new demo`
* Change directory to project: `cd demo`
* Create a new live view: `mix phx.gen.live Assests Asset assets name:string  description:string`
* Update the router in `lib/demo_web/router.ex` with new routes:
```
    live "/assets", AssetLive.Index, :index
    live "/assets/new", AssetLive.Index, :new
    live "/assets/:id/edit", AssetLive.Index, :edit
    live "/assets/:id", AssetLive.Show, :show
    live "/assets/:id/show/edit", AssetLive.Show, :edit
```

* Configure database in `config/dev.exs`   and migrate `mix ecto.migrate`
* Start dev server `mix phx.server`
* Open browser and go to `/assets`
* Click "New" button, the form_component modal opens
* Hit enter key without any input or with only one input field

Result: 
* The form is invalid (missing field), the server assign new form with errors to the socket as expected
* The client closes the modal and does not report any errors  

### Expected behavior
* Validation errors are reported to the user and the modal is kept open
* Was working as expected with phoenix_live_view 0.19

**Comment by SteffenDE** [comment]
Caused by https://github.com/phoenixframework/phoenix_live_view/commit/067b632fdcf00777f2712d55a1247d5eea36df22
