### ISSUE TITLE
liveSocket.execJS event doesn't execute in iOS WKWebView after coming back into focus

### ISSUE THREAD

**Issue by Neophen** [phoenixframework/phoenix_live_view#3041]
### Environment

* Elixir version (elixir -v):
Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]
Elixir 1.15.5 (compiled with Erlang/OTP 26)

* Phoenix version (mix deps):
phoenix 1.7.10

* Phoenix LiveView version (mix deps):
phoenix_live_view 0.20.3

* Operating system:
iOS

* Browsers you attempted to reproduce this bug on (the more the merrier): 
This only happens in a custom iOS app when using the WKWebView

* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:
Yes

### Actual behavior
I have an iOS Swift UI app which uses WKWebView to represent our website marko.ch

Opening any external link which brings WKWebView to the background and back, breaks the liveSocket.execJS events clicking on those elements does not execute liveview javascript anymore. Note that the button receives the click events and normal javascript still works, but liveSocket.execJS event's don't fire anymore

### Expected behavior
liveSocket.execJS should still work after loosing focus

### Workaround
The way i've worked around these limitations was by removing all the JS commands and replacing them with web-components at the moment.

**Comment by chrismccord** [comment]
Are you sure the page is connected when you retrun to the page? Perhaps the connection is broken when backgrounded and doesn't reconnect for some reason. We need more information to help move this forward and as we don't have a reproduction, and a reproduction would require a swift app, this isn't something we can easily handle on our own. If you'd like to explore and provide a PR we'd be happy to evaluate it. First we need to figure out what's happening lifecycle wise when you return to the page. Thanks!

**Comment by Neophen** [comment]
Ok will try to at least do and minimal reproduction. to see if it's the connection
