### ISSUE TITLE
`handle_params` callback gets out of sync with query string when LiveView crashes

### ISSUE THREAD

**Issue by aaronrenner** [phoenixframework/phoenix_live_view#306]
### Environment

* Elixir version (elixir -v): 1.9.1
* Phoenix version (mix deps): 1.4.9
* NodeJS version (node -v): 12.6.0
* NPM version (npm -v): 6.9.0
* Operating system: Mac OS 10.14.6

### Actual behavior

I have an example counter app that stores the current count in the url via `live_redirect`. However, when I crash the LiveView, instead of restarting with the current count in the query string, it reverts back to the count when the page was initially loaded.

![Push state issue - small](https://user-images.githubusercontent.com/120878/63172247-7d835900-bffa-11e9-98c3-67045e94a52c.gif)

Example app (`ar-push-state` branch): https://github.com/aaronrenner/live_view_playground/tree/ar-push-state

### Expected behavior

`handle_params` should be called with the current url params when recovering from a crash.

**Comment by chrismccord** [comment]
❤️❤️❤️🐥🔥

**Comment by aaronrenner** [comment]
Thank you! ❤️
