### ISSUE TITLE
open_browser not working on WSL2 Ubuntu-20.04

### ISSUE THREAD

**Issue by waranlogesh** [phoenixframework/phoenix_live_view#3063]
### Environment

* Elixir version (elixir -v): Elixir 1.14.0 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): phoenix 1.7.10
* Phoenix LiveView version (mix deps): phoenix_live_view 0.20.2
* Operating system: WSL2 Ubuntu-20.04
* Browsers you attempted to reproduce this bug on (the more the merrier): firefox installed in WSL2 Ubuntu-20.04
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

```
  test "test open_browser", %{conn: conn} do
    {:ok, live, _html} = live(conn, ~p"/")
    
    live
    |> open_browser()
  end
```

Running the above test, `open_browser` fails with an error 

```
'\\wsl.localhost\Ubuntu-20.04\home\<username>\workspace\phoenix_live_view'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
Invalid switch - "/tmp".
```

### Expected behavior

Should open the firefox installed in WSL2 Ubuntu-20.04

**Comment by josevalim** [comment]
Closing in favor of the PR. :)
