### ISSUE TITLE
Using Phoenix HTML helpers breaks diffing

### ISSUE THREAD

**Issue by jwietelmann** [phoenixframework/phoenix_live_view#307]
# Environment

* Elixir version (elixir -v): 1.8.1
* Phoenix version (mix deps): 1.4.9
* NodeJS version (node -v): 11.10.0
* NPM version (npm -v): 6.7.0
* Operating system: macOS 10.14.3

### Actual behavior

Tag helpers break through LiveViews boundaries for diffing. For example any content that renders inside of `Phoenix.HTML.Tag.content_tag` doesn't get `diff`'d and instead that entire subtree gets fully re-rendered on every update.

### Expected behavior

Diffing still works when using tag helpers.

### My thoughts

Conceptually, I mostly understand why this happens. I'm busting out of LEEx, and that means from that point on, nothing is keeping track of static-vs-dynamic. It does seem like an oversight and a problem, however, that it is not possible to use Phoenix HTML helpers (or a hypothetical API-compatible replacement) in a way that preserves diff-tracking.

By way of example, I have an entire UI library that provides stuff like `<%= row medium:4 do %>`. It's built on `Phoenix.HTML` for obvious reasons, so what that means is I can't use it to lay out my grid in a large LiveView unless I'm okay putting up with a huge payload on every update.

### Question

At the moment, my best idea for dealing with the issue is to use macros to switch my UI lib between using `~E` and `Phoenix.HTML.Tag` and using `~L` and a `Tag`-compatible module that uses `~L`.

Is there a better choice? Is this already on your radar and being solved another way?

**Comment by chrismccord** [comment]
It's possible to use phoenix helpers, but you are right that anytime an assign used in the tag generation changes, we have to regenerate the entire tag. There's no easy way around this so it's not something we intend to tackle. Thanks.

**Comment by chrismccord** [comment]
To be extra clear, diff tracking still works within the content_tag helpers, but we will only be able to reinvoke the content tag function if the assign(s) change. So diff tracking remains valid, but we will have to resend the "static" html that the tag generates if ones of its assigns change.
