### ISSUE TITLE
Assigns disappear from connected socket in forwarded routes

### ISSUE THREAD

**Issue by monooso** [phoenixframework/phoenix_live_view#3089]
### Environment

* Elixir version (elixir -v): `1.15.6 OTP 26` (also reproduced using Elixir 16)
* Phoenix version (mix deps): `1.7.11`
* Phoenix LiveView version (mix deps): `0.20.4`
* Operating system: macOS 14.2.1
* Browsers you attempted to reproduce this bug on (the more the merrier): Affects every browser 
* Does the problem persist after removing "assets/node_modules" and trying again?: Yes

### Actual behaviour
I have created [a repository][1] containing a single-file app, which demonstrates this behaviour. The README contains a more detailed breakdown of the circumstances in which this bug _does not_ appear, which may be useful.

When forwarding a route to another router, values assigned to a socket in a `live_session` `on_mount` handler are discarded when the socket is connected. The values are present when the LiveView is first mounted.

You can clearly see this behaviour when running the single-file application from the linked repository. When loading the `/forwarded` route in the browser, you will briefly see the text "Test value". This is replaced by "Fallback value" once the socket is connected.

[1]: https://github.com/monooso/forward_mount_bug

### Expected behaviour
The assigned value should persist when the socket is mounted, as is the case for non-forwarded routes.

**Comment by SteffenDE** [comment]
Hi @monooso, do you know if this worked in a previous version if LiveView?

**Comment by monooso** [comment]
Hi @SteffenDE,

I don't, sorry. We've just started breaking up our router, and I immediately ran into this.

**Comment by josevalim** [comment]
I believe this is a documented limitation or it should be. Live_session does not work with forward. :)

**Comment by monooso** [comment]
@josevalim I think this issue may have been closed prematurely. I'm not nesting `forward` inside a `live_session`.

**Comment by SteffenDE** [comment]
@monooso even when not using live_session directly, live routes are always inside a default live_session iirc

**Comment by josevalim** [comment]
Exactly. It is clear my explanation is unclear though, I will give it another try!

**Comment by josevalim** [comment]
Actually, the whole work around I propose won't work. It seems you can't use forward with live_session at all. It may be that we can make my proposal work but that's not true today.

**Comment by monooso** [comment]
@SteffenDE Indeed, my point was that I'm not using `forward` inside a `live_session` block as cautioned against in the documentation update. I'm using a `live_session` in the "forwarded" router.

@josevalim Understood. I'll figure out an alternative approach.

Thank you both for your time.

**Comment by monooso** [comment]
@josevalim One last thing, which may be of use should you return to this in the future. As noted in the README in [the linked repository](https://www.github.com/monooso/forward_mount_bug):

- If you forward the `/` route, everything works.
- If the LiveView itself defines the `on_mount` handler, everything works.

I have no idea why.

**Comment by josevalim** [comment]
Yeah, the on_mount on LV always works, the issue is only with live_session. The root forward works by chance, because we don’t break the URL apart. :)

**Comment by monooso** [comment]
Accidentally correct is the best kind of correct.
