### ISSUE TITLE
Submit event triggered from a form with a submit button using `form` attribute does not have the name/value attribute on the button

### ISSUE THREAD

**Issue by sa-mm** [phoenixframework/phoenix_live_view#3092]
### Environment

* Elixir version (elixir -v): 1.15.7
* Phoenix version (mix deps): 1.7.11
* Phoenix LiveView version (mix deps): 0.20.4
* Operating system: macOS Ventura 13.6.3
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, Safari, Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

A submit event triggered from a form with a submit button outside the form does not have the name/value attribute on the button. Example:

```elixir
defmodule NameValueSubmitButtonWeb.Live.FormLive do
  use NameValueSubmitButtonWeb, :live_view

  def render(assigns) do
    ~H"""
    <div>
      <form id="my-form-id" phx-submit="submit"></form>
      <button form="my-form-id" type="submit" name="save" value="send">
        Send
      </button>
      <p><%= @match %></p>
    </div>
    """
  end

  def mount(_params, _session, socket) do
    {:ok, assign(socket, match: nil)}
  end

  def handle_event("submit", %{"save" => "send"} = params, socket) do
    IO.inspect(params)
    {:noreply, assign(socket, match: "send clause")}
  end

  def handle_event("submit", params, socket) do
    IO.inspect(params)
    {:noreply, assign(socket, match: "not send clause")}
  end
end
```

The second clause gets hit.

### Expected behavior

The event contains the name/value and pattern matches on the first clause.

It's reproduced [here](https://github.com/sa-mm/name_value_submit_button) at http://localhost:4000/form. You can checkout the previous commit, run `mix deps.get`, _refresh the page_, and click the button again to see that the behavior was different on 0.20.3.

Refreshing the page is necessary, so it seems to be a javascript issue. I see the following in the changelog for 0.20.4:

> Allow regular buttons with name/value attributes to send form events and adjusted dynamic form documentation to reflect this

and what looks like a related commit: https://github.com/phoenixframework/phoenix_live_view/commit/fbe2226611511c89e9a61661f425e9d471cbbcb0

However, I don't understand how that's causing the issue.

**Comment by SteffenDE** [comment]
Sorry that's my fault. Will be fixed via https://github.com/phoenixframework/phoenix_live_view/pull/3093.
