### ISSUE TITLE
elements outside of the comprehension (the for loop) but inside the `phx-update=stream` are not rendering on tests in 0.20.4

### ISSUE THREAD

**Issue by midigofrank** [phoenixframework/phoenix_live_view#3096]
### Environment

* Elixir version (elixir -v): `Elixir 1.15.7 (compiled with Erlang/OTP 26)`
* Phoenix version (mix deps): `1.7.11`
* Phoenix LiveView version (mix deps): `0.20.4`
* Operating system: `macOS Sonoma 14.2`

### Actual behavior
Say I have this `HEEX` template using `async assigns` and `streams`:
```heex
      <.async_result :let={artist} assign={@artist}>
        <h3>Artist: <%= artist.name %></h3>

        <div id="albums" phx-update="stream">
          <div :for={{dom_id, album} <- @streams.albums} id={dom_id}><%= album.title %></div>
          <div id="albums-placeholder" class="hidden only:block">
            ALBUMS PLACEHOLDER
          </div>
        </div>
      </.async_result>
```

```elixir
    {:ok, view, html} = live(conn, ~p"/")
     
    # All these fail
    assert html =~ "ALBUMS PLACEHOLDER"
    assert render(view) =~ "ALBUMS PLACEHOLDER"
    assert render_async(view) =~ "ALBUMS PLACEHOLDER"
```
When I start the containing liveview in tests, the rendered html doesn't contain the `ALBUMS PLACEHOLDER` element. 
This only happens when I use an `async assign`.
I have created a dummy repo which reproduces the issue: https://github.com/midigofrank/phoenix_async_result_streams

#### NOTE
This works well on `0.20.{1, 2, 3}` 

### Expected behavior
I expect elements outside of the `stream comprehension` to get rendered in tests

**Comment by SteffenDE** [comment]
I'm not sure if rendering non-stream elements in a `phx-update="stream"` container is something that is officially supported. I don't think that you should rely on it.
You could use a separate assign that keeps track if the stream is empty and render the placeholder outside of the stream container.

**Comment by josevalim** [comment]
That's correct. You cannot mix stream with non-stream elements in the same container.
