### ISSUE TITLE
LiveView (0.20.5) drops stream items in tests

### ISSUE THREAD

**Issue by RomanKotov** [phoenixframework/phoenix_live_view#3100]
### Environment

* Elixir version (elixir -v): 1.16.0
* Phoenix version (mix deps): 1.7.11
* Phoenix LiveView version (mix deps): 0.20.5
* Operating system: MacOS
* Browsers you attempted to reproduce this bug on (the more the merrier): N/A, fails in tests
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: no, not relevant to browser

I have integration tests, that use Phoenix LiveView streams.

1. The first test creates 5 elements and checks that they are visible: https://github.com/exshome/exshome/blob/0fd72c173f4ca07dede619ea6553f465698fc65b/test/exshome_web/live/svg_canvas_test.exs#L210-L214
2. The second tests does the same thing - it creates 5 items in setup(https://github.com/exshome/exshome/blob/0fd72c173f4ca07dede619ea6553f465698fc65b/test/exshome_automation/live/automation_editor_test.exs#L52) and then checks that they are visible (https://github.com/exshome/exshome/blob/0fd72c173f4ca07dede619ea6553f465698fc65b/test/exshome_automation/live/automation_editor_test.exs#L65)

### Actual behavior

The first test (1) shows 3 items instead of 5.
The second test (2) shows only 2 items instead of 5.

### Expected behavior

The tests should pass. They were working on `0.20.4`, but stopped after update to `0.20.5`.

### Extra information about the issue

It seems, that older stream items are dropped. Newer ones are visible.

How do I create an item:
1. UI sends event to server.
2. LiveView process starts to create an item. It calls a GenServer.
3. Once the item is created, GenServer broadcasts the data (PubSub). It is "Insert" event with the item.
4. LiveView process receives the "Insert" event, and inserts the item to a stream.
5. LiveView process updates a new item. It calls GenServer from step 3.
6. GenServer broadcasts "Update" event.
7. LiveView process receives "Update" event, and inserts the item into stream.

I have checked - LiveView process receives both "Insert" and "Update" events.

You can reproduce it in this repo at this commit: https://github.com/exshome/exshome/tree/0fd72c173f4ca07dede619ea6553f465698fc65b and updating the `phoenix_live_view` dependency to 0.20.5 (it is 0.20.4 in the `mix.lock` file https://github.com/exshome/exshome/blob/0fd72c173f4ca07dede619ea6553f465698fc65b/mix.lock#L39).

Was not able to reproduce the issue with smaller example yet. Will try to dig deeper into it. Possibly something with how test implementation handles the streams.

**Comment by RomanKotov** [comment]
The feature works as expected in browser.

**Comment by markquezada** [comment]
I've noticed this as well +1
