### ISSUE TITLE
A comment on recent LiveView bug and regressions

### ISSUE THREAD

**Issue by crertel-getthru** [phoenixframework/phoenix_live_view#3116]
(I know this is not quite the use of the bug report feature, but it's for a good cause.)

In one of the last patch releases (we ran into it at `0.20.5`, ended up rolling back to `0.20.3`), an issue seemed to have been introduced that caused checkboxes to double-fire and toggle/untoggle really quickly. This ended up getting fixed quickly in a few hours on our side via application of `phx-debounce`, and then a longer fix applied via rollback. It was annoying to track down and fix, but we did so in short order and--honestly--that's what we should all expect from a pre-`1.0` library that is being provided gratis, at the end of the day. :)

I'm sure you (the team) have received bug reports, complaints, and whatnot about this. I'm not going to add to that pile. 

**Instead, I want to tell any of y'all that need to hear it what I'd tell any of my reports after this sort of thing:**

*If we're not shipping the occasional bug, we're not being ambitious enough.*

*If we're not touching code we don't completely 100% understand, we're not being curious enough.*

*If we're not cleaning messy--if currently "working"--code, we're not being responsible enough.*

**We appreciate the hard work y'all have put into this library**. We've gone all-in on it here, and by and large it has been a force multiplier and let a small team do big things. Thank y'all for your continued work on this and for the improvements y'all keep making. Don't let a bump like this get you down. :)

**If we never have bugs :bug: , we'll never have butterflies :butterfly: .**

**Comment by chrismccord** [comment]
❤️❤️❤️🐥🔥
