### ISSUE TITLE
(LiveView 0.20.2+) When performing patch navigation, SVG within `<td>` inside LiveComponent disappears 

### ISSUE THREAD

**Issue by AkioCode** [phoenixframework/phoenix_live_view#3117]
### Environment

* Elixir version (elixir -v): 1.16.1
* Phoenix version (mix deps): 1.7.11
* Phoenix LiveView version (mix deps): >= 0.20.2
* Operating system: Ubuntu 23.04/ MacOs Sonoma
* Browsers you attempted to reproduce this bug on (the more the merrier):  Chrome / Opera / Edge
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

I have a table where each row is a live component, and one column has a custom icon (SVG in a function component). 
When I do patch the URL, from the second row until the end, the SVG disappears and the height of the row increases.

Here is an App to reproduce the behavior: https://github.com/AkioCode/svg-inside-table-issue
- Go to /posts
- There will be 2 tables, the first one is the CoreComponents table, and the second is a custom one where each row is a live component. In each table, you will notice two columns with icons, one with HeroIcon and the other with a custom icon.
- Press the 'Click' button
- Press the browser back button
- Notice the UI change only occurs in the second table, custom icon column, from the second row.

I also noticed this UI change doesn't occur if we replace the LiveComponent with a Phoenix Component, or put the row code in the same file of the table.
This behavior doesn't occur if the SVG is outside the table.

### Expected behavior
I am not sure if this is an intentional behavior, but If possible, I would like to know why this occurs after 0.20.2.

**Comment by AkioCode** [comment]
Thanks very much for the quick fix, @chrismccord.
I noticed another issue that might be related.
A LC contains another LC that has a table with the SVG Icon. This causes the custom icon to disappear as well.
At the end of the day I can push another project to replicate this issue.

**Comment by chrismccord** [comment]
Yes please push up a reproduction and open an new issue. Thanks!
