### ISSUE TITLE
Support setting cookies from live view

### ISSUE THREAD

**Issue by ethanjgoldberg** [phoenixframework/phoenix_live_view#313]
I'd like to manage session state with a live view. In order to do this, I imagine returning something like `live_cookie(session, cookie_data)` from `handle_event`, etc. The server would send a message similar to a live_reload, and the client would set a cookie.

Is this sort of thing within the scope of this project? I have something working locally -- would you be interested in a PR?

**Comment by chrismccord** [comment]
We aren't accepting feature requests at this time (per the issue template). You can perform this kind of thing yourself with our new js hooks, but be aware that you'll need to sign the data if you expect it to be tamper proof like the default plug/phoenx cookie session. Thanks!

**Comment by Gurimarukin** [comment]
@ethanjgoldberg
> I have something working locally

May I ask you a code snippet of how you did it? Thanks in advance!
