### ISSUE TITLE
`Tokenizer.ParseError: expected attribute` is thrown on HTML element malformed 

### ISSUE THREAD

**Issue by LauraBeatris** [phoenixframework/phoenix_live_view#3137]
### Environment

* Elixir version (elixir -v): 1.15.7
* Phoenix version (mix deps): 1.7.11
* Phoenix LiveView version (mix deps): 0.20.2
* Operating system: MacOS Sonoma

### Actual behavior

I've accidentally introduced a typo when closing an HTML tag on my render function - should be `<./button>` instead of `</.button>`:

```
<.button type="submit" phx-disabled-with="Saving...">Create Post</.button> 
```

Throwing the following error:

````
== Compilation error in file lib/pubsub_example_web/live/home_live.ex ==
** (Phoenix.LiveView.Tokenizer.ParseError) lib/pubsub_example_web/live/home_live.ex:16:73: expected attribute name
````

### Expected behavior

I'd expect to receive a `ParseError` related to the HTML element being malformed, but I got a bit stuck trying to debug why the error was related to a missing attribute.

**Comment by josevalim** [comment]
Yeah, we should improve the error message here. There is also a bug if you do `<. tag` which tries to render a component with no name. Thank you for the report!
