### ISSUE TITLE
Clicking on links doesn't always play well with "beforeunload" event handling

### ISSUE THREAD

**Issue by eriknaslund** [phoenixframework/phoenix_live_view#3147]
### Environment

* Elixir version (elixir -v): 1.16.0 (OTP 26)
* Phoenix version (mix deps): 1.7.10
* Phoenix LiveView version (mix deps):  0.20.3
* Operating system: Manjaro 23.1.3 Vulcan
* Browsers you attempted to reproduce this bug on (the more the merrier): Opera
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

I've added the following script on my LiveView page which registers an "[beforeunload](https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event)" event handler. The intent is to show the user a prompt asking if they really want to leave the page in case they have unsaved changes.

```javascript
window.addEventListener("beforeunload", (event) => {
    event.preventDefault();
});
```

If i click a normal `<a href=/whatever>...</a>` link on the page, this leads to the page beginning to unload. I can then see the following in the browser console:

```
phx-F7kOjXNh-5yJqNEC socket: disconnect for page nav -  undefined
```

This happens before the "unload confirmation dialog" appears.
If the user chooses to cancel and stay on the page, LiveView has disconnected the socket and the page isn't functional any more.

It seems to be a bit of a race condition, because it doesn't happen every time. If I retry it once or twice I always get it though. It doesn't seem to matter if I change `addEventListener` to use the capture phase either.

### Expected behavior

The LiveView socket disconnection should preferably not happen until the page is actually going to be unloaded.

I would also be perfectly fine if there was a way to hook in a piece of code that's guaranteed to run before the LiveView socket is disconnected, if the disconnect can be cancelled that way. Btw, this is just me thinking out loud - that might be an increadibly bad idea!

### Notes

The "offending line" that causes the LiveView socket disconnection is this one:

https://github.com/phoenixframework/phoenix_live_view/blob/e66beb60eefff7a8153881f823cc5ff6b7bfb089/assets/js/phoenix_live_view/live_socket.js#L649

The "mousedown" event is sent immediately when the link is clicked, which is before the "beforeunload" event. My event handler therefore doesn't seem to get the chance to cancel the navigation before LiveView has disconnected its socket.

**Comment by chrismccord** [comment]
I think the best approach in this scenario is to have your own click listener on the button and stopPropagation so LV doesn't pick it up. Thanks!

**Comment by eriknaslund** [comment]
@chrismccord It was a simple (and clever) idea, but I can't quite get it to work.

The "beforeunload" popup (shown below) is displayed by the browser when I do `event.preventDefault()` in the "onbeforeunload" event handler, i.e. I can't display that dialog myself from a "click" listener on a button.

![image](https://github.com/phoenixframework/phoenix_live_view/assets/1250308/1d3e3b83-9019-4b35-aa51-cde527a172f0)
