### ISSUE TITLE
phx-update="ignore" ignores when class attribute changes on element

### ISSUE THREAD

**Issue by jtormey** [phoenixframework/phoenix_live_view#3153]
### Environment

* Elixir version (elixir -v): `Elixir 1.16.1 (compiled with Erlang/OTP 26)`
* Phoenix version (mix deps): `locked at 1.7.11 (phoenix) b1ec57f2`
* Phoenix LiveView version (mix deps): `locked at 0.20.11 (phoenix_live_view) 56eb5a75`
* Operating system: MacOS
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

After upgrading from LiveView 0.20.2 to 0.20.11, a `class={@class}` attribute no longer updates when the `@class` assign changes. The element has `phx-update="ignore"`. Data attributes update correctly when changed.

### Expected behavior

All attributes, including `class` should update when their assigned value updates, even though `phx-update="ignore"` is set. (Only changes to contents should be ignored, as was my understanding.)

**Comment by josevalim** [comment]
Sorry, to be clear, it was not clear in the changelog, but it is after your issue :)
