### ISSUE TITLE
Visual Documentation for live views

### ISSUE THREAD

**Issue by carlogilmar** [phoenixframework/phoenix_live_view#316]
Hi! I'm was learning about Live Views for prepare a talk in the Mexico City Meetup, and I drew some illustrations about the documentation, and then I think that maybe it could be a contribution if the maintainers are agree with that, if is possible, I'll create the PR 

The visual illustrations are this:
 
![image](https://user-images.githubusercontent.com/17634377/63631107-4f98a880-c5e8-11e9-94d2-25eb3a1a9a4d.png)

![IMG_0450](https://user-images.githubusercontent.com/17634377/63631119-7d7ded00-c5e8-11e9-8f37-6cf1517c9372.PNG)

I create this from the documentation, so I think that maybe this kind of information could make this project more accesible. If you're agree I should know in which directory I could store the images and I'll generate the PR for be evaluated with more detail.

Thanks, Carlo. 🇲🇽

**Comment by josevalim** [comment]
We are not ready to make a decision on this yet but I just want to stop by and say thank you! Have a great talk!

**Comment by carlogilmar** [comment]
Thanks! This are the images that I drew based on the docs, maybe if there any feedback or recommendations I could fixing, I'd like to contribute with some kind of resources if there any possibility.

This are the slides that I made for the meetup, I think that this is a great way to be more clearly and accesible to share technical content. 

![ElixirLiveViews (2)](https://user-images.githubusercontent.com/17634377/64463107-74048280-d0c8-11e9-821c-62444af46b9a.png)
![ElixirLiveViews (3)](https://user-images.githubusercontent.com/17634377/64463108-74048280-d0c8-11e9-8fcf-c3dab4e0d2e2.png)
![ElixirLiveViews (4)](https://user-images.githubusercontent.com/17634377/64463109-74048280-d0c8-11e9-84c8-1cc2ea904741.png)
![ElixirLiveViews (5)](https://user-images.githubusercontent.com/17634377/64463110-749d1900-d0c8-11e9-88c0-c99f1f35e775.png)
![ElixirLiveViews (7)](https://user-images.githubusercontent.com/17634377/64463111-749d1900-d0c8-11e9-9d15-bc169bacd97a.png)
![ElixirLiveViews (8)](https://user-images.githubusercontent.com/17634377/64463112-749d1900-d0c8-11e9-8dc7-53e13a9b0d32.png)
![ElixirLiveViews (9)](https://user-images.githubusercontent.com/17634377/64463113-749d1900-d0c8-11e9-9602-b443e82c53ac.png)
![ElixirLiveViews (10)](https://user-images.githubusercontent.com/17634377/64463114-749d1900-d0c8-11e9-8d7c-71c7f4be158a.png)

Thanks, Carlo, 🇲🇽

**Comment by Skoda091** [comment]
@carlogilmar Was this talk recorded?

**Comment by carlogilmar** [comment]
@Skoda091 yes! https://youtu.be/vMkZ1QrE42Y?t=7787

**Comment by henrik** [comment]
I love the idea of visual documentation! I also worry that it could be harder to maintain as things change. Two ideas:

1. Link from the appropriate parts of the docs to this talk or to a blog post with these graphics. 
2. Generate graphics from code (perhaps even making this part of ExDoc, or as an add-on) - though those would likely be simpler and have less personality.

**Comment by carlogilmar** [comment]
Sure! I've been working on how to create useful visual documentation to communicate better some complex concepts and for use as learning tools, recently I create this in a workshop of @whatyouhide 

![IMG_5853](https://user-images.githubusercontent.com/17634377/86856082-36261100-c081-11ea-9586-7d6b8ebde1f9.PNG)

![IMG_5854](https://user-images.githubusercontent.com/17634377/86856085-37573e00-c081-11ea-939c-6ce6c28e190c.PNG)

I'll be happy to collaborate with this kind of resources.

**Comment by josevalim** [comment]
Thank you @carlogilmar! We have started incorporating some visualizations as mermaid diagrams and more examples along those lines are welcome. :)
