### ISSUE TITLE
Setting CSP to require-trusted-types-for 'script' gives a console error in findPhxChildrenInFragment()

### ISSUE THREAD

**Issue by peterhartman** [phoenixframework/phoenix_live_view#3166]
### Environment

* Elixir version (elixir -v): Elixir 1.16.1 (compiled with Erlang/OTP 26)
* Phoenix version (mix deps): 1.7.11
* Phoenix LiveView version (mix deps): 0.20.12
* Operating system: OS X Sonoma 14.3.1 (23D60)
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes

### Actual behavior
If I set `require-trusted-types-for 'script'` in my CSP headers I get a browser console error:

```
Uncaught TypeError: Failed to set the 'innerHTML' property on 'Element': This document requires 'TrustedHTML' assignment.
    at Object.findPhxChildrenInFragment (admin:4594:26)
    at View.onJoinComplete (admin:7108:37)
    at admin:7094:16
    at View.applyDiff (admin:7064:7)
    at View.onJoin (admin:7079:12)
    at admin:7446:57
    at TransitionSet.after (admin:8795:9)
    at LiveSocket.requestDOMUpdate (admin:8147:24)
    at Object.callback (admin:7446:29)
    at admin:3052:73
findPhxChildrenInFragment @ admin:4594
onJoinComplete @ admin:7108
(anonymous) @ admin:7094
applyDiff @ admin:7064
onJoin @ admin:7079
(anonymous) @ admin:7446
after @ admin:8795
requestDOMUpdate @ admin:8147
(anonymous) @ admin:7446
(anonymous) @ admin:3052
matchReceive @ admin:3052
(anonymous) @ admin:3083
trigger @ admin:3399
(anonymous) @ admin:3193
trigger @ admin:3399
(anonymous) @ admin:4223
decode @ admin:3680
onConnMessage @ admin:4209
conn.onmessage @ admin:3910
``` 

### Expected behavior
No console error

**Comment by josevalim** [comment]
I don't think that would work, by definition with LiveView. We could change LiveView to wrap our innerHTML in a trustedType policy, but you would still need to explicitly allow LiveView's trusted type policy. PRs exploring this would be interesting to see before we move forward.
