### ISSUE TITLE
Unadvertent bump on `floki` usage now requires Elixir v1.13+

### ISSUE THREAD

**Issue by rafaeelaudibert** [phoenixframework/phoenix_live_view#3167]
In https://github.com/phoenixframework/phoenix_live_view/commit/0c1667739b1880b3142c959b08116ea1a4744a1a, `floki` was updated to `~> 0.36.0` - that version however, dropped support to Elixir v1.12. `phoenix_live_view` was *not* updated to `v1.13+` which meant my CI kept breaking because it thought it was fine to upgrade to `phoenix_live_view 0.20.13` while it isn't because this transitive dependency now requires a higher Elixir version.

I don't think this change belongs to a `patch` version update, so I think we should revert this change and launch a new `0.20.14` without the change.

If the fix is important - which probably is - it should then be released with a new `phoenix_live_view 0.21.0` with that change *plus* a bump for Elixir `v1.13+`

**Comment by josevalim** [comment]
Good find. Unfortunately it is a bit too late, we have already released the breakage, so we are in a tough spot:

1. If we revert the fix that requires latest Floki, we will break 0.20.x for some
2. If we keep it as is, then we will break for those who are running on earlier Elixir versions

Given the concept of patch version updates for semver is only after 1.0.0 ([anything goes before 1.0.0](https://semver.org/#spec-item-4)), it is probably best to continue moving forward and add a clear note in the CHANGELOG. Thank you.

**Comment by rafaeelaudibert** [comment]
@josevalim I appreciate the considerations, and I ultimately agree with you here. We'll update our dependencies pinning `phoeninx_live_view` to `< 0.20.13`, thank you
