### ISSUE TITLE
Removes checkbox when adding a new entry

### ISSUE THREAD

**Issue by DaTrader** [phoenixframework/phoenix_live_view#317]
### Environment

* Elixir version (elixir -v): 1.9.0
* Phoenix version (mix deps): 1.4.9
* NodeJS version (node -v): 8.12.0
* NPM version (npm -v): 6.4.1
* Operating system: Windows 7

### Actual behavior

When running LiveView Todo demo (https://dennisbeatty.com/2019/04/24/how-to-create-a-todo-list-with-phoenix-liveview.html), and submitting a new todo entry, the previous last entry gets its checkbox removed (see screenshot with the inspected element). Interestingly, the problem repeats on every second entry (the first entry is entered correctly, the second entry is added with the first entry checkbox removed, the third entry is entered correctly and it corrects the second entry - gets its checkbox back, the fourth entry entry is added the third entry checkbox getting removed, and so on).

The template code is rather simple:

<form action="#" phx-submit="add">
  <%= text_input( :todo, :title, placeholder: "What do you want to get done?") %>
  <%= submit( "Add", phx_disable_with: "Adding...") %>
</form>

<%= for todo <- @todos do %>
  <div>
    <%= checkbox( :todo, :done, phx_click: "toggle_done", phx_value: todo.id, value: todo.done) %>
    <%= todo.title %>
  </div>
<% end %>

![image](https://user-images.githubusercontent.com/30151179/63677012-69a2d880-c7ec-11e9-9859-08f874ff66e9.png)

### Expected behavior

A new entry should be added with the previous ones kept intact.

**Comment by chrismccord** [comment]
I haven't tested the example app yet, but in the meantime it would be super helpful if you could try the latest LV to see if this has been fixed as we fixed a related issue recently. Be sure to blow away the LV js and reinstall:

```elixir
$ mix deps.update phoenix_live_view
$ cd assets
$ rm -rf node_modules/phoenix_live_view
$ npm install
$ cd ..
$ mix phx.server
```

And report back. Thanks!

**Comment by DaTrader** [comment]
I've just removed and reinstalled LV js as per your instructions. The bug is still there.
Btw, please see the warning below that I get when installing js.

![image](https://user-images.githubusercontent.com/30151179/63697060-67587280-c81c-11e9-8dc5-1f6f9ae67d67.png)

**Comment by DaTrader** [comment]
@snewcomer No, the browser is not the problem. It behaves the same in FF and Chrome.
But, you are right. I have now cloned the repo myself into another folder and it works properly.
Gotta check what went wrong with the first instance. Apologies for the false alarm.

**Comment by DaTrader** [comment]
@snewcomer 
Ok. At first I thought it was something with me switching from milligram to bootstrap, but it wasn't.
Several hours later and I think I nailed it, not the bug itself, but how to repeat it.
The thing is that the demo from the repo works because it uses an older version of liveview (and phoenix). I discovered that accidentally, because it wouldn't compile with the LV install instructions provided here on the github so I realized it was using an older version (thanks to its mix.lock file). The LV version the demo uses does not have live_link functions so the compilation fails, but unlike the latest version it does not have this bug that I am talking about here.

Now, try it yourself and you'll be able to repeat the bug:
- clone the live_view_todo repo
- delete the mix.lock file as it contains a reference to the old liveview version that doesn't have the bug
- run mix deps.get
- run mix phx.server

**Comment by DaTrader** [comment]
I am reopening the issue because of the above.

**Comment by snewcomer** [comment]
Confirmed this is not an issue with morphdom (current or past versions 2.5.2-2.5.5).  Will keep digging.

**Comment by snewcomer** [comment]
@DaTrader I found the issue.  Effectively your input checkbox in a _loop_ needs to look like this or else you will have invalid HTML - duplicate **ids** is problem:

`<%= checkbox(:todo, :done, phx_click: "toggle_done", id: todo.id, phx_value: todo.id, value: todo.done) %>`

![Screen Shot 2019-08-31 at 10 40 43 AM](https://user-images.githubusercontent.com/7374640/64067330-cda61200-cbdb-11e9-9eda-ce66291316db.png)

vs.

![Screen Shot 2019-08-31 at 10 42 58 AM](https://user-images.githubusercontent.com/7374640/64067351-1d84d900-cbdc-11e9-8e42-ed923f8f198d.png)

Really you can construct the `input[id]` any way you want.  Just as long as they are not duplicated on the page!  Lmk if you have any other issues and thanks for bringing this up!

**Comment by yeongsheng-tan** [comment]
> @DaTrader I found the issue. Effectively your input checkbox in a _loop_ needs to look like this or else you will have invalid HTML - duplicate **ids** is problem:
> 
> `<%= checkbox(:todo, :done, phx_click: "toggle_done", id: todo.id, phx_value: todo.id, value: todo.done) %>`
> 
> ![Screen Shot 2019-08-31 at 10 40 43 AM](https://user-images.githubusercontent.com/7374640/64067330-cda61200-cbdb-11e9-9eda-ce66291316db.png)
> 
> vs.
> 
> ![Screen Shot 2019-08-31 at 10 42 58 AM](https://user-images.githubusercontent.com/7374640/64067351-1d84d900-cbdc-11e9-8e42-ed923f8f198d.png)
> 
> Really you can construct the `input[id]` any way you want. Just as long as they are not duplicated on the page! Lmk if you have any other issues and thanks for bringing this up!

Worked like a charm!

**Comment by DaTrader** [comment]
@snewcomer Yes, it works! Thanks a lot for the tip and for the time spent on finding this bug.
