### ISSUE TITLE
phx-hook "updated" not called when inserting new items

### ISSUE THREAD

**Issue by ponychicken** [phoenixframework/phoenix_live_view#3173]
### Environment

* Elixir version (elixir -v): 1.14.0
* Phoenix version (mix deps): 1.7.11
* Phoenix LiveView version (mix deps): 0.20.11
* Operating system: Debian
* Browsers you attempted to reproduce this bug on (the more the merrier): all
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

When a new item is inserted, and I have Javascript debuggin enabled (``enableDebug()``), I can see in the console a log entry 
`phx-F7yVmoPD4tN0wgXj update:  -  {1: {…}}1: {1: {…}}[[Prototype]]: Object`
containing the correct element. 
But, the phx-hook `updated()` is only called if I modify an already existing event.

**Comment by josevalim** [comment]
It would be great if you can create a minimal example to reproduce and create a new issue. You can use this to get started:

```elixir
Application.put_env(:sample, Example.Endpoint,
  http: [ip: {127, 0, 0, 1}, port: 5001],
  server: true,
  live_view: [signing_salt: "aaaaaaaa"],
  secret_key_base: String.duplicate("a", 64)
)

Mix.install([
  {:plug_cowboy, "~> 2.5"},
  {:jason, "~> 1.0"},
  {:phoenix, "~> 1.7"},
  # please test your issue using the latest version of LV from GitHub!
  {:phoenix_live_view, github: "phoenixframework/phoenix_live_view", branch: "main", override: true},
])

# build the LiveView JavaScript assets (this needs mix and npm available in your path!)
path = Phoenix.LiveView.__info__(:compile)[:source] |> Path.dirname() |> Path.join("../")
System.cmd("mix", ["deps.get"], cd: path, into: IO.binstream())
System.cmd("npm", ["install"], cd: Path.join(path, "./assets"), into: IO.binstream())
System.cmd("mix", ["assets.build"], cd: path, into: IO.binstream())

defmodule Example.ErrorView do
  def render(template, _), do: Phoenix.Controller.status_message_from_template(template)
end

defmodule Example.HomeLive do
  use Phoenix.LiveView, layout: {__MODULE__, :live}

  def mount(_params, _session, socket) do
    {:ok, assign(socket, :count, 0)}
  end

  def render("live.html", assigns) do
    ~H"""
    <script src="/assets/phoenix/phoenix.js"></script>
    <script src="/assets/phoenix_live_view/phoenix_live_view.js"></script>
    <%!-- uncomment to use enable tailwind --%>
    <%!-- <script src="https://cdn.tailwindcss.com"></script> --%>
    <script>
      let liveSocket = new window.LiveView.LiveSocket("/live", window.Phoenix.Socket)
      liveSocket.connect()
    </script>
    <style>
      * { font-size: 1.1em; }
    </style>
    <%= @inner_content %>
    """
  end

  def render(assigns) do
    ~H"""
    <%= @count %>
    <button phx-click="inc">+</button>
    <button phx-click="dec">-</button>
    """
  end

  def handle_event("inc", _params, socket) do
    {:noreply, assign(socket, :count, socket.assigns.count + 1)}
  end

  def handle_event("dec", _params, socket) do
    {:noreply, assign(socket, :count, socket.assigns.count - 1)}
  end
end

defmodule Example.Router do
  use Phoenix.Router
  import Phoenix.LiveView.Router

  pipeline :browser do
    plug(:accepts, ["html"])
  end

  scope "/", Example do
    pipe_through(:browser)

    live("/", HomeLive, :index)
  end
end

defmodule Example.Endpoint do
  use Phoenix.Endpoint, otp_app: :sample
  socket("/live", Phoenix.LiveView.Socket)

  plug Plug.Static, from: {:phoenix, "priv/static"}, at: "/assets/phoenix"
  plug Plug.Static, from: {:phoenix_live_view, "priv/static"}, at: "/assets/phoenix_live_view"

  plug(Example.Router)
end

{:ok, _} = Supervisor.start_link([Example.Endpoint], strategy: :one_for_one)
Process.sleep(:infinity)
```

**Comment by ponychicken** [comment]
Yes, mounted is called. For this is not completely clear from the docs, what is supposed to be the right behavior. I think it would be make sense that both are called in this case. Otherwise from the JS hook it's impossible (without hacks) to distinguish whether it it's being called during initial mount, or later when new items are added.

**Comment by ponychicken** [comment]
Or if not maybe clarify the docs on this.

**Comment by ponychicken** [comment]
OK, I think maybe it becomes more clear when I explain the use case. I want to trigger a small CSS animation when items are added or updated. If I trigger this in the mounted() callback it will also do the animation on initial page load. If I add it only to updated() it will not play on page load, but it will also not trigger when new items are added.
I have a workaround, a hook on the parent item which sets a class to the body to enable the animations on the children after some delay, but it doesn't feel like the right solution.

**Comment by ponychicken** [comment]
Thanks for explaining :)
I am new to Elixir, and before I started my project I was a little bit in doubt how wise the decision would be to use a new language and paradigm for it, but I am super happy how it is working out so far. ❤️
