### ISSUE TITLE
Forms with child input with attribute `name="id"` are not tracked during re-renders.

### ISSUE THREAD

**Issue by peaceful-james** [phoenixframework/phoenix_live_view#3181]
### Environment

* Elixir version (elixir -v): 1.16.1
* Phoenix version (mix deps): 1.7.11
* Phoenix LiveView version (mix deps): 0.20.2
* Operating system: Ubuntu
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome and Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

Forms with child input with attribute `name="id"` are not tracked during re-renders.

I provide 2 examples:

```
defmodule MyAppWeb.WeirdLive do
  use Phoenix.LiveView

  def render(assigns) do
    ~H"""
    <form :for={index <- 1..3} id={"form-#{index}"}>
      <input name="id" placeholder={"Form #{index}"} />
    </form>
    """
  end
end
```

and

```
defmodule MyAppWeb.WeirdLive do
  use Phoenix.LiveView

  def render(assigns) do
    ~H"""
    <form id="form-1">
      <input name="id" placeholder="Form 1" />
    </form>
    <button phx-click="toggle">
      Click Me
    </button>
    <div :if={not @condition}>
      Conditional Div
    </div>
    <form id="form-2">
      <input name="id" placeholder="Form 2" />
    </form>
    """
  end

  def mount(_params, _session, socket), do: {:ok, assign(socket, :condition, false)}

  def handle_event("toggle", _params, socket), do: {:noreply, update(socket, :condition, &(!&1))}
end
```

In the first example, there should be 3 forms, but 5 get rendered. The first 2 forms are not tracked during the 2nd render, I think.

In the second example, clicking on "Click Me" will duplicate the first form. I believe the underlying issue is the same.

An interesting thing to note is if you run `document.getElementById("form-1").id` in browser console, you will see it returns not a string as usual but rather the child input element.

### Expected behavior

At least the compiler could warn me about `name="id"` inputs? I will be avoiding them henceforth!

**Comment by SteffenDE** [comment]
Related https://github.com/phoenixframework/phoenix_live_view/issues/2786#issuecomment-1713936820

**Comment by josevalim** [comment]
We could add a warning if we detect this in the engine. But in practice, if the value is interpolated, it will be hard to catch.

**Comment by chrismccord** [comment]
> This one is tricky because it's a quirk with how HTML forms behave. All their inputs are added as properties of the form instance, so setting <input name="id"> the form.id becomes a reference to that input instead of the DOM id, which breaks all kinds of things. It's not specific to LiveView, but is probably more aggravated by it with our DOM patching, but most js apps will have to deal with this quirk, so I'm closing for now. Thanks!
