### ISSUE TITLE
LiveView duplicates SVG text elements rather than properly replacing/removing them

### ISSUE THREAD

**Issue by mononym** [phoenixframework/phoenix_live_view#3187]
### Environment

* Elixir version (elixir -v): Elixir 1.15.4 (compiled with Erlang/OTP 26)
* Phoenix version (mix deps): 1.7.8
* Phoenix LiveView version (mix deps): 0.20.1
* Operating system: Ubuntu
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox, Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

Text elements inside an SVG are not being updated properly. They are duplicating instead of being replaced, or persisting when they should be removed from the DOM.

I don't have a simple app example, but what I'm doing is taking some data and building up an SVG from it to build a simple top down map complete with text labels. I'm only using `rect`, `path` and `text` elements inside the SVG currently and it looks something like this:

![Screenshot from 2024-03-17 15-52-00](https://github.com/phoenixframework/phoenix_live_view/assets/1351942/534b9086-c70d-42b6-adbe-e110382b904d)

If I trigger an update to one of the `rect` elements through some sort of interaction, the `rect` will draw/update properly in the front end, however all of the `text` elements will be duplicated:

![Screenshot from 2024-03-17 15-22-37](https://github.com/phoenixframework/phoenix_live_view/assets/1351942/0fd0c5d2-3900-44ef-a2a1-0b365e46668d)

If I trigger an update to one of the `text` elements, such as by changing the text within the `text` element, the new text _will_ appear but the old `text` elements will remain in place. Meaning if I change the label "Awesome" to say "Awesome!" I'll end up with two `text` elements stacked on top of each other, one saying "Awesome" and the other with the updated "Awesome!" and both sharing the same ID indicating they came from the same piece of source data.

If I delete one of the `text` elements on the server side and trigger a redraw/update of the component, it will no longer duplicate the `text` element in the front end but the existing `text` element will just stay there rather than being deleted as expected.

The logic that builds this SVG map works 100% of the time on first load, it is only when there is a diff/update performed that things go sideways and so far only with `text` elements. Reloading the page after performing some of these changes shows the updated map as expected.

### Expected behavior

`text` elements should be properly tracked in diffs just like other SVG elements.

**Comment by josevalim** [comment]
It would be great if you can create a minimal example to reproduce and create a new issue. You can use this to get started:

```elixir
Application.put_env(:sample, Example.Endpoint,
  http: [ip: {127, 0, 0, 1}, port: 5001],
  server: true,
  live_view: [signing_salt: "aaaaaaaa"],
  secret_key_base: String.duplicate("a", 64)
)

Mix.install([
  {:plug_cowboy, "~> 2.5"},
  {:jason, "~> 1.0"},
  {:phoenix, "~> 1.7"},
  # please test your issue using the latest version of LV from GitHub!
  {:phoenix_live_view, github: "phoenixframework/phoenix_live_view", branch: "main", override: true},
])

# build the LiveView JavaScript assets (this needs mix and npm available in your path!)
path = Phoenix.LiveView.__info__(:compile)[:source] |> Path.dirname() |> Path.join("../")
System.cmd("mix", ["deps.get"], cd: path, into: IO.binstream())
System.cmd("npm", ["install"], cd: Path.join(path, "./assets"), into: IO.binstream())
System.cmd("mix", ["assets.build"], cd: path, into: IO.binstream())

defmodule Example.ErrorView do
  def render(template, _), do: Phoenix.Controller.status_message_from_template(template)
end

defmodule Example.HomeLive do
  use Phoenix.LiveView, layout: {__MODULE__, :live}

  def mount(_params, _session, socket) do
    {:ok, assign(socket, :count, 0)}
  end

  def render("live.html", assigns) do
    ~H"""
    <script src="/assets/phoenix/phoenix.js"></script>
    <script src="/assets/phoenix_live_view/phoenix_live_view.js"></script>
    <%!-- uncomment to use enable tailwind --%>
    <%!-- <script src="https://cdn.tailwindcss.com"></script> --%>
    <script>
      let liveSocket = new window.LiveView.LiveSocket("/live", window.Phoenix.Socket)
      liveSocket.connect()
    </script>
    <style>
      * { font-size: 1.1em; }
    </style>
    <%= @inner_content %>
    """
  end

  def render(assigns) do
    ~H"""
    <%= @count %>
    <button phx-click="inc">+</button>
    <button phx-click="dec">-</button>
    """
  end

  def handle_event("inc", _params, socket) do
    {:noreply, assign(socket, :count, socket.assigns.count + 1)}
  end

  def handle_event("dec", _params, socket) do
    {:noreply, assign(socket, :count, socket.assigns.count - 1)}
  end
end

defmodule Example.Router do
  use Phoenix.Router
  import Phoenix.LiveView.Router

  pipeline :browser do
    plug(:accepts, ["html"])
  end

  scope "/", Example do
    pipe_through(:browser)

    live("/", HomeLive, :index)
  end
end

defmodule Example.Endpoint do
  use Phoenix.Endpoint, otp_app: :sample
  socket("/live", Phoenix.LiveView.Socket)

  plug Plug.Static, from: {:phoenix, "priv/static"}, at: "/assets/phoenix"
  plug Plug.Static, from: {:phoenix_live_view, "priv/static"}, at: "/assets/phoenix_live_view"

  plug(Example.Router)
end

{:ok, _} = Supervisor.start_link([Example.Endpoint], strategy: :one_for_one)
Process.sleep(:infinity)
```

**Comment by chrismccord** [comment]
Happy to revisit with a reproduction. Thanks!
