### ISSUE TITLE
"Interop" documentation contains HTML (instead of HTML source)

### ISSUE THREAD

**Issue by Qqwy** [phoenixframework/phoenix_live_view#319]
Congrats on publishing a first version of the library to Hex!

I was just browsing through the now-online docs, and in the [interop section](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#module-custom-js-interop-and-client-controlled-dom) I came across a HTML text field. I think this is rendered as HTML by the markdown parser, instead of showing it as HTML source, which is what the surrounding paragraphs allude to (because they explain what kind of attributes one should add to it).

 
![image](https://user-images.githubusercontent.com/5345745/63757159-e780e580-c8b9-11e9-8848-f1abbf8f08cb.png)

This is probably a simple, low-hanging-fruit kind of fix, but I just wanted to mention it because I happened to see it. :purple_heart:

**Comment by josevalim** [comment]
Fixewd in master, thank.
