### ISSUE TITLE
Doc on dom-patching outdated

### ISSUE THREAD

**Issue by ponychicken** [phoenixframework/phoenix_live_view#3193]
[The Doc on DOM Patching](https://hexdocs.pm/phoenix_live_view/dom-patching.html) recommends temporary-assigns as a solution to not keep everything in memory.
I believe (please correct me if I am wrong), that nowadays streams are the preferred solution for this, but they are only fleetingly mentioned. 
In case so I can make a PR with a suggestion.

**Comment by josevalim** [comment]
I believe this has already fixed in main. :)

**Comment by ponychicken** [comment]
Sweet! thanks!
