### ISSUE TITLE
stream/3 etc don't specify what it returns

### ISSUE THREAD

**Issue by ponychicken** [phoenixframework/phoenix_live_view#3195]
From the context of blog posts and own experiments I figured out that [stream/3](https://github.com/phoenixframework/phoenix_live_view/blob/37bcbc4515efbedd3e85b3c0fbd39c4f88cea9f7/lib/phoenix_live_view.ex#L1660) returns the socket, but it is nowhere mentioned in the docs. The same is true for many other functions in the module.

**Comment by josevalim** [comment]
A pull request that adds ``This function returns an updated `socket`.`` will be very welcome!

**Comment by josevalim** [comment]
You can add to all functions you find relevant. :)

**Comment by ponychicken** [comment]
ok will do!
