### ISSUE TITLE
Documentation on using Form bindings with many-to-many or belongs-to fields lacking

### ISSUE THREAD

**Issue by ponychicken** [phoenixframework/phoenix_live_view#3197]
In many applications you have some kind of belongs-to or many-to-many associations.
Like a blog post which has many categories, and each category has many blog posts.

It is straightforward to figure out how to make a `<.input type="select">` for an Enum,
such as 
```
<.input
          field={@form[:status]}
          type="select"
          label="Status"
          options={Ecto.Enum.values(Post, :status)}
/>
```

The same approach fails when trying to add a similar dropdown field to select the categories
```
<.input
          field={@form[:categories]}
          type="select"
          label="Categories"
          options={get_categories()}
/>
```
with `** (Protocol.UndefinedError) protocol Phoenix.HTML.Safe not implemented for %Category{...`

Since this is a common pattern, I would suggest to add some paragraph into `guides/client/form-bindings.md` to explain the prefered way to solve this.

**Comment by ponychicken** [comment]
In https://hexdocs.pm/phoenix_html_helpers/PhoenixHTMLHelpers.Form.html#multiple_select/4 its quite nicely documented how to do this, but don't find a reference for Phoenix 1.7

**Comment by ponychicken** [comment]
Ok, I have to correct myself.
<.input type="select"> is the correct way to do this.

But `get_options_for_select` will fail if the `value` is not specified explicitely.

**Comment by chrismccord** [comment]
tracking on the phx side. Thanks!
