### ISSUE TITLE
Clarify the use of assign_new to "share" assigns in security model docs

### ISSUE THREAD

**Issue by aymanosman** [phoenixframework/phoenix_live_view#3205]
In the [Mounting Considerations](https://hexdocs.pm/phoenix_live_view/security-model.html#mounting-considerations) section of the security models docs, the language describing the use of `assign_new` to share assigns "across LiveViews" could be misleading. Is it not the case that this sharing across LiveViews is only for parent-child sharing of assigns? Am I right to assume that you cannot share assigns between root LiveViews?

**Comment by chrismccord** [comment]
This is correct. If you think the docs could be clearer, please send a PR. Thank you!
