### ISSUE TITLE
Question: Is it possible for a LiveView to efficiently display and update lists?

### ISSUE THREAD

**Issue by jwietelmann** [phoenixframework/phoenix_live_view#321]
I constructed this example where a parent LiveView contains a list of IDs that it passes to child LiveViews, which in turn fetch and render their respective items: https://github.com/jwietelmann/phoenix_live_view_issues/blob/master/lib/lvtest_web/live/test_live.ex

What I have observed is that anything which causes the list of IDs to change in turn causes all of the children to be re-mounted and rendered from scratch. Which means that, for example, a todo list with a large, prioritized list of todos cannot be re-ordered without fully re-rendering the entire list. The strategy in my example app represents my most aggressive attempt at optimizing LiveView updates, but I still haven't managed to get behavior that will practically serve my real-world use case.

Is this a problem with my code or strategy? Is this just how LiveView is? If it's just how LiveView is, is that a bug or known behavior? If it's known behavior, is it considered a problem or not particularly? I'm just trying to get a sense of whether or not this is just one of those use cases where I should curtail my usage of LiveView.

**Comment by josevalim** [comment]
@jwietelmann that's a LiveView limitation when using `live_render`, that's why we generally say to use nested `live_render` with care. For example, you could handle it in a single live view and usse the regular render only for the templates. We can possibly fix it in the future, but it is low priority right now (there are more important things we are working on).

**Comment by jwietelmann** [comment]
@josevalim I'm not married to using nested `live_render`. I only started using it at all because I am trying to optimize a poorly-performing LiveView that loops over collections and has undesirably-large diffs.

Can you clarify this? Let's say I have a big list that renders each item in a comprehension for a total of 500KB HTML. Is there _any technique_ I can use that will allow me to add an item to the list without incurring a 500KB diff update?

**Comment by josevalim** [comment]
As a matter of fact there is an alternative: `phx-update="append"`. Then you need to add only new elements to the container, instead of keeping everything in memory. If you are appending an existing ID, then it is updated in place. There are no removals currently though  (coming soon).

**Comment by jwietelmann** [comment]
@josevalim Is changing the order of existing elements also coming soon? (Thinking sort direction, drag-and-drop ordering, that sort of thing.)

**Comment by jwietelmann** [comment]
Er, wait, `phx-update` only affects the client-side behavior. I still end up having to transfer a 500KB diff over the socket on every change, right?

**Comment by josevalim** [comment]
No, you can keep only what you want to send extra or what changed.
Temporary assigns also help with that.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by jwietelmann** [comment]
So to recap, the current best way to efficiently deal with lists is:

* Use `phx-update="append"` (or `phx-update="prepend"` if that's the better behavior).
* To minimize the size of the diff (and the LiveView's resource usage!), replace `socket.assigns.my_list_of_items` with a list of _just the new or updated items_.
* This will add new elements and update existing ones, but `phx-update` currently has no way deal with:
  * Removing existing elements (but this is planned to be handled in the future)
  * Inserting new elements into the middle
  * Changing the order of existing elements

**Comment by josevalim** [comment]
Correct. We did talk about phx-sort though, so we may have it in the future.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by devshahani** [comment]
> As a matter of fact there is an alternative: `phx-update="append"`. Then you need to add only new elements to the container, instead of keeping everything in memory. If you are appending an existing ID, then it is updated in place. There are no removals currently though (coming soon).

@josevalim is there a way to follow along / contribute to work on removals? My app would greatly benefit from being able to use `phx-update`

**Comment by josevalim** [comment]
@devshahani today there is a very simple solution. Since each element inside an append needs an ID, you can delete anything by sending the container with an ID and empty contents:

    <div id="id_you_want_to_delete" class="deleted">

Whatever we add will simply be an optimization to fully remove it from DOM.

**Comment by mitchellhenke** [comment]
@josevalim regarding `phx-sort`, is it still possible? Would it be reasonable for me to have a go at it?

**Comment by josevalim** [comment]
It probably makes sense, @chrismccord, would know better, but sorting is also very doable with components. Make each of the sorted entries a component. That will allow random sorting with a minimal amount of data over the wire.
