### ISSUE TITLE
Live component: no component found matching phx-target of 1 (Wallaby)

### ISSUE THREAD

**Issue by ftes** [phoenixframework/phoenix_live_view#3222]
### Environment

* Elixir version (elixir -v): 1.16.1
* Phoenix version (mix deps): 1.17.12
* Phoenix LiveView version (mix deps): 0.20.14
* Operating system: macOS
* Browsers you attempted to reproduce this bug on (the more the merrier): chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

When changing a form input in a live component immediately after page load, more often than not the `phx-change` `handle_event` callback is not executed and this JS error occurs:

```js
no component found matching phx-target of 1 undefined
```

Single file app:

<details>
<summary>Single file app</summary>

```ex
Application.put_env(:sample, Example.Endpoint,
  http: [ip: {127, 0, 0, 1}, port: 5001],
  server: true,
  live_view: [signing_salt: "aaaaaaaa"],
  secret_key_base: String.duplicate("a", 64)
)

Mix.install([
  {:plug_cowboy, "~> 2.5"},
  {:jason, "~> 1.0"},
  {:phoenix, "~> 1.7"},
  # please test your issue using the latest version of LV from GitHub!
  {:phoenix_live_view, github: "phoenixframework/phoenix_live_view", branch: "main", override: true},
])

# build the LiveView JavaScript assets (this needs mix and npm available in your path!)
path = Phoenix.LiveView.__info__(:compile)[:source] |> Path.dirname() |> Path.join("../")
System.cmd("mix", ["deps.get"], cd: path, into: IO.binstream())
System.cmd("npm", ["install"], cd: Path.join(path, "./assets"), into: IO.binstream())
System.cmd("mix", ["assets.build"], cd: path, into: IO.binstream())

defmodule LiveFormComponent do
  # In Phoenix apps, the line is typically: use MyAppWeb, :live_component
  use Phoenix.LiveComponent
  alias Phoenix.LiveView.JS

  def render(assigns) do
    ~H"""
    <div>
    <.form phx-change="validate" phx-target={@myself}>
      <input phx-mounted={JS.dispatch("input")} />
    </.form>
    </div>
    """
  end
end

defmodule Example.ErrorView do
  def render(template, _), do: Phoenix.Controller.status_message_from_template(template)
end

defmodule Example.HomeLive do
  use Phoenix.LiveView, layout: {__MODULE__, :live}

  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  def render("live.html", assigns) do
    ~H"""
    <script src="/assets/phoenix/phoenix.js"></script>
    <script src="/assets/phoenix_live_view/phoenix_live_view.js"></script>
    <%!-- uncomment to use enable tailwind --%>
    <%!-- <script src="https://cdn.tailwindcss.com"></script> --%>
    <script>
      let liveSocket = new window.LiveView.LiveSocket("/live", window.Phoenix.Socket)
      liveSocket.connect()
    </script>
    <style>
      * { font-size: 1.1em; }
    </style>
    <%= @inner_content %>
    """
  end

  def render(assigns) do
    ~H"""
    <.live_component module={LiveFormComponent} id="form" />
    """
  end
end

defmodule Example.Router do
  use Phoenix.Router
  import Phoenix.LiveView.Router

  pipeline :browser do
    plug(:accepts, ["html"])
  end

  scope "/", Example do
    pipe_through(:browser)

    live("/", HomeLive, :index)
  end
end

defmodule Example.Endpoint do
  use Phoenix.Endpoint, otp_app: :sample
  socket("/live", Phoenix.LiveView.Socket)

  plug Plug.Static, from: {:phoenix, "priv/static"}, at: "/assets/phoenix"
  plug Plug.Static, from: {:phoenix_live_view, "priv/static"}, at: "/assets/phoenix_live_view"

  plug(Example.Router)
end

{:ok, _} = Supervisor.start_link([Example.Endpoint], strategy: :one_for_one)
Process.sleep(:infinity)

```

</details>

### Expected behavior

The `handle_event` callback for `phx-change` is always called and no JS error occurs.

### Further info

In the single file app, I triggered the error via a `phx-mounted={JS.dispatch("input")}` on page load.
But where this error actually hurts me is in Wallaby-based browser tests.
When run in CI, the error usually does not occur (likely due to more sluggish execution).
When run locally, this error lets tests that change values in forms in live components fail more often than not.

**Comment by SteffenDE** [comment]
The problem is that phx-mounted also runs on the initial dead render, before the LiveView is joined. In that case the live component is not annotated in the DOM. To make this work, you can only include the phx-mounted attribute only in the connected HTML:

```
<.form phx-change="validate" phx-target={@myself}>
  <input phx-mounted={if connected?(@socket), do: JS.dispatch("input")} />
</.form>
```

Not sure if there's a good clientside solution to make this work better. But maybe better documentation would be enough?

**Comment by chrismccord** [comment]
We actually should be waiting on connect for phx-mounted in the case of a LV, per the docs:

```
If `phx-mounted` is used on the initial page render, it will be invoked only
after the initial WebSocket connection is established
```

I'm wondering if we have a race in the order we invoke the mounted's after joint patch. I will take a look. Thanks!

**Comment by SteffenDE** [comment]
@chrismccord I think it's related to https://github.com/phoenixframework/phoenix_live_view/commit/166884950fde91eea8ad492b0731f91bcdfc5c48

I've seen this behavior for quite some time already and thought by now it's expected.

The check here:
https://github.com/phoenixframework/phoenix_live_view/blob/aac5f9f31402687a583035ae8d49df575bc40d20/assets/js/phoenix_live_view/live_socket.js#L366

does not return true as `document.firstElementChild` returns the html element, so execNewMounted always runs twice for LiveViews.

**Comment by SteffenDE** [comment]
(the fix is to change `document.firstElementChild` to `body.firstElementChild`)

**Comment by SteffenDE** [comment]
Related to: https://github.com/phoenixframework/phoenix_live_view/issues/2882#issuecomment-1896294043

**Comment by SteffenDE** [comment]
> (the fix is to change `document.firstElementChild` to `body.firstElementChild`)

@chrismccord The other question is: what about root layouts where the LV element is not the direct child of the body? I guess the check should actually look for live views in the whole DOM?

**Comment by chrismccord** [comment]
document.firstElementChild is to check if the HTML document itself is a LV
