### ISSUE TITLE
Lacking a way to compose a `JS` instance from more than two other `JS` instances

### ISSUE THREAD

**Issue by DaTrader** [phoenixframework/phoenix_live_view#3233]
There's a use case with a pipe of three `JS` structs where the middle one is not known upfront and is supplied as a parameter to the function, ex:

```elixir
defp make_sandwich( path, inner_js, push_opts) do
  JS.dispatch( "replace-state", detail: %{ path: path})
  |> JS.pipe( inner_js)
  |> JS.push( "do_something_useful", push_opts)
end
```

If the `JS` type wasn't opaque, we could do the above ourselves i.e. 

```elixir
defp pipe( first, second) do
  %JS{ first | ops: first.ops ++ second.ops}
end
```

But since it is opaque, it'd be of great help if the pipe function was added to `JS` module.

**Comment by DaTrader** [comment]
PS: I'll make a PR myself if I have a blessing from the core team to add this feature.

**Comment by SteffenDE** [comment]
Sorry for the silence. When I first saw this issue I wasn't quite sure when the order would matter, as most JS functions only show / hide / toggle things, and then I forgot about it.

I just came across a use case with a dropdown using a custom menu component and remembered this issue. My menu passes a `hide` js for a close button, and in the specific use case I need a dispatch to execute first:

```heex
<Menu.menu :let={%{close: close}} id={@id} on_show={JS.dispatch("dropdown:show", to: "##{@id}")} on_hide={JS.dispatch("dropdown:hide", to: "##{@id}")}>
  <:activator :let={activator_opts}><%= render_slot(@activator, activator_opts) %></:activator>
  ...
  <:actions :let={%{close: close}} :if={@multiple}>
    <.text_link phx-click={JS.dispatch("dropdown:reset", to: "##{@id}-form")}>
      Reset
    </.text_link>
    <div class="flex-1 min-w-8"></div>
    <.button phx-click={JS.dispatch("dropdown:apply", to: "##{@id}-form") |> JS.pipe(close)}>
      Apply
    </.button>
  </:actions>
</Menu.menu>
```

If the menu closes before the apply event is handled by my hook, things won't work, as the hide event triggers first, cancelling selections.

Of course I could workaround this by having a `data-close` and doing execJS inside my apply event, but that complicates things unnecessarily in my opinion. So +1 from me for adding a `JS.pipe(first, second)`.

@josevalim opinions?

**Comment by josevalim** [comment]
A JS.concat or JS.compose is fine by me. :)
