### ISSUE TITLE
(1.0.0-rc.0) Removed `phx-feedback-for` still around in documentation

### ISSUE THREAD

**Issue by rhcarvalho** [phoenixframework/phoenix_live_view#3248]
### Environment

* Elixir version (elixir -v): N/A
* Phoenix version (mix deps): N/A
* Phoenix LiveView version (mix deps): `1.0.0-rc.0`
* Operating system: N/A
* Browsers you attempted to reproduce this bug on (the more the merrier): N/A
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: N/A

### Actual behavior

The documentation at https://hexdocs.pm/phoenix_live_view/1.0.0-rc.0 still has many references to  `phx-feedback-for` which is documented to be removed in 1.0 (breaking change).

![image](https://github.com/phoenixframework/phoenix_live_view/assets/88819/fc3b4d4b-69bc-48c9-abe8-0ef4619f1911)

Despite not in the search results above, `phx-feedback-for` is also present in the cheatsheet https://hexdocs.pm/phoenix_live_view/1.0.0-rc.0/html-attrs.html.

### Expected behavior

Need to update docs to point people towards the supported alternatives (including shim).

**Comment by SteffenDE** [comment]
Note that all but one location was already removed in https://github.com/phoenixframework/phoenix_live_view/commit/4643fc152f89dcef7e922c96285b96cdd78eb901.

Closed via https://github.com/phoenixframework/phoenix_live_view/commit/bc33a98113e31b85c0975cde2bd3a206ae34f8b1.

Thank you for reporting! 🙌

**Comment by rhcarvalho** [comment]
Oh, sorry I missed https://github.com/phoenixframework/phoenix_live_view/commit/4643fc152f89dcef7e922c96285b96cdd78eb901 and thanks for the quick fix of the missing reference :purple_heart:
