### ISSUE TITLE
Sidebar guides in progressive order

### ISSUE THREAD

**Issue by rhcarvalho** [phoenixframework/phoenix_live_view#3252]
### Environment

* Elixir version (elixir -v): N/A
* Phoenix version (mix deps): N/A
* Phoenix LiveView version (mix deps): `1.0.0-rc.0`
* Operating system: N/A
* Browsers you attempted to reproduce this bug on (the more the merrier):  N/A
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: N/A

### Actual behavior

When I consult the documentation (which is btw top quality :purple_heart: ), I expected the guides to be ordered based on a progression from basic to more advanced topics that might make more sense for someone new to Phoenix LiveView.

### Expected behavior

I'd be willing to give this a shot / send a PR if welcome. One possible direction:

**SERVER-SIDE FEATURES**

| Current order                    | Suggestion                       |
|----------------------------------|----------------------------------|
| Assigns and HEEx templates       | Assigns and HEEx templates       |
| Deployments                      | Live layouts                     |
| Error and exception handling     | Live navigation                  |
| Live layouts                     | Error and exception handling     |
| Live navigation                  | Security considerations          |
| Security considerations          | Telemetry                        |
| Telemetry                        | Deployments                      |
| Uploads                          | Uploads                          |
| Gettext for internationalization | Gettext for internationalization |

**CLIENT-SIDE INTEGRATION**

(no changes)

<details>

| Current order               | Suggestion                  |
|-----------------------------|-----------------------------|
| Bindings                    | Bindings                    |
| Form bindings               | Form bindings               |
| JavaScript interoperability | JavaScript interoperability |
| External Uploads            | External Uploads            |

</details>

**Comment by josevalim** [comment]
I recently changed them to be alphabetic, as they are unrelated and that’s easier to follow. :) thank you for askinf
