### ISSUE TITLE
Nested slots within function components

### ISSUE THREAD

**Issue by bcardarella** [phoenixframework/phoenix_live_view#3255]
I understand the reason for not allowing nested components like so:

```heex
<.foo>
  <:bar>
    <:baz/>
  </:bar>
</.foo>
```

but what would be nice is if slots that render function compoents supported their slots:

```heex
<.foo>
  <:bar>
    <.card>
      <:baz/>
    </.card>
  </:bar>
</.foo>
```

In this example `<:baz>` is a slot for `<.card>` and shouldn't be viewed as a nested slot within `<.foo>`

**Comment by chrismccord** [comment]
This has always worked. Can you share function component definitions and a template where this errors?

**Comment by bcardarella** [comment]
Maybe we got in a bad compile state as we cannot reproduce now. If we see it again we'll copy the stacktrace.
