### ISSUE TITLE
Lacking a way for a nested LiveView to crash its parent in mount/first render when the two are linked

### ISSUE THREAD

**Issue by DaTrader** [phoenixframework/phoenix_live_view#3257]
LiveView version: 0.20.14 (but since nothing of the kind can be found in the 1.0.0rc changelog, I expect it to be there as well)

- A `RuntimeException` taking place in a nested LiveView process over its **post-mount** life cycle result in its restart, as it should.
- Same scenario but with the nested LV process linked to its parent results in having them both restarted. Again, as it should.
- A `RuntimeException` taking place at any point in the parent lifecycle, **including while mounting** results in its restart, as it should.

However, regardless of whether the two processes are linked, I can't get a crashing nested LiveView process crash its parent process along if the crash is occurring while the child is getting mounted or while rendering after mounting. This is a problem, for the desired behavior for an unhandled exception in this case would be to let it crash i.e. consequently have the 500 error page rendered (especially in production), while instead we get an immediate retry of a nested LiveView mount on behalf of its (manually linked!!) parent and then an exponential backoff-like wait forever.

Can it be done so that there's at least a configuration parameter (an option) in the `live_render/3` function that will ensure that the failure of the nested LiveView process will bring down the parent as well if the two are linked?

Thanks!

**Comment by josevalim** [comment]
How soon are you linking it? If you link it first thing on mount then any crashes should cause its parent to crash as well. If it is not crashing, then you need to make sure it is terminating with reasons different than normal. Do this before linking in the parent:

parent = self()
spawn(fn ->
  ref = Process.monitor(parent)
  receive do
    {:DOWN, ^ref, _, _, reason} -> IO.inspect {:dead, reason}
  end
end)
```

**Comment by DaTrader** [comment]
I link them in the first line of the nested LV `mount`.

They all are already monitored b/c I need to cleanup after each one of them.

The nested LV does crash as explained before (say, on referencing a non
existent key within an assign in the template or something like that), but
the parent simply remounts it just one more time and that's it (the blue
progress line at the top keeps on slowing and going like that forever).

Note: it matters not what I do with the LiveMonitor. I can also remove it,
it will still behave the same in this regard.

If you intend all this is not by design, I will make a demo app that
reproduces it. Shouldn't be a problem.

**Comment by josevalim** [comment]
If you are linking them at the beginning, then the parent LiveView should terminate as soon as the child LiveView crashes. The only reason for that not to happen is:

1. If you are actually not linking them
2. The child LiveView is not actually existing with an error status

The code I proposed above will answer the second question. Please let me know what it prints.

**Comment by DaTrader** [comment]
Ok. Tomorrow morning when I am back on my computer.

**Comment by DaTrader** [comment]
@josevalim Here's what happens when placing a non existent `aaa` key reference to an assign in a live component template of the nested LiveView:

1. The nested LV error dump:

```
[error] GenServer #PID<0.1126.0> terminating
** (KeyError) key :aaa not found in: {nil, 0}. If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map

[ the stacktrace]
```

2. Your `IO.inspect`:

```
:dead,
 {%KeyError{
    key: :aaa,
    term: {nil, 0},
    message: "key :aaa not found in: {nil, 0}. If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map"
  },
  
 [ the stacktrace]
```

3. The error dump once more:
```
[error] an exception was raised:
    ** (KeyError) key :aaa not found in: {nil, 0}. If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
```

Note that by the time the first error occurs, the LiveVIew is already connected to the server because most of the app templates don't ever render during the static mount run.

**Comment by DaTrader** [comment]
And with respect to the the first option (me not linking the processes, here's what the nested LiveView mount looks like (the relevant part anyway):

```
  def mount( params, session, socket)

  def mount( _params, _session, %{ transport_pid: nil} = socket) do
    Process.link( socket.parent_pid)
  
    { :ok, assign_initialized( socket, false)}
  end

  def mount( _params, _session, socket) do
    Process.link( socket.parent_pid)
  
    ..
  end
```

**Comment by josevalim** [comment]
So this should work, unless you are raising before linking or the parent is trapping exits. I can look if there is a single file reproduction.

**Comment by DaTrader** [comment]
Double checked it - not trapping exits. The only place I am trapping exits is my Cache module (that has nothing to do with this), but nevertheless, I commented that too, removed all monitoring from every single LiveView process and I can no longer see anything that could even remotely affect the parent behavior.

Will make a single file demo app trying to reproduce this.

**Comment by DaTrader** [comment]
@josevalim Here's a single file demo reproducing the issue..

```elixir
Application.put_env(:sample, Example.Endpoint,
  http: [ip: {127, 0, 0, 1}, port: 5001],
  server: true,
  live_view: [signing_salt: "aaaaaaaa"],
  secret_key_base: String.duplicate("a", 64)
)

Mix.install([
  {:plug_cowboy, "~> 2.5"},
  {:jason, "~> 1.4"},
  {:gettext, "~> 0.23"},
  {:phoenix, "~> 1.7.11"},
  {:phoenix_ecto, "~> 4.4"},
  {:phoenix_html, "~> 3.3"},
  {:phoenix_live_view, "0.20.14"}
])

defmodule Example.ErrorView do
  def render(template, _), do: Phoenix.Controller.status_message_from_template(template)
end

defmodule Example.NestedLive do
  use Phoenix.LiveView, layout: {__MODULE__, :live}

  def mount( params, session, socket)

  def mount( _params, _session, %{ transport_pid: nil} = socket) do
    Process.link( socket.parent_pid)

    { :ok, socket}
  end

  # note: this hangs forever
  def mount( _params, _session, socket) do
    Process.link( socket.parent_pid)

    :ok = :error

    { :ok, socket}
  end

  def render( assigns) do
    ~H"""
    Nested LiveView
    """
  end
end

defmodule Example.ParentLive do
  use Phoenix.LiveView, layout: {__MODULE__, :live}

  defp phx_vsn, do: Application.spec(:phoenix, :vsn)

#  # note: this properly results in an internal server error
#  def mount( _params, _session, socket) do
#    :ok = :error
#
#    { :ok, socket}
#  end

  def render("live.html", assigns) do
    ~H"""
    <script src={"https://cdn.jsdelivr.net/npm/phoenix@#{phx_vsn()}/priv/static/phoenix.min.js"}></script>
    <script src={"https://cdn.jsdelivr.net/gh/phoenixframework/phoenix_live_view@main/priv/static/phoenix_live_view.min.js"}></script>
    <script src=" https://cdn.jsdelivr.net/npm/topbar@3.0.0/topbar.min.js"></script>
    <script>
      let liveSocket = new window.LiveView.LiveSocket("/live", window.Phoenix.Socket)

      topbar.config({barColors: {0: "#29d"}, shadowColor: "rgba(0, 0, 0, .3)"})
      window.addEventListener("phx:page-loading-start", info => topbar.show())
      window.addEventListener("phx:page-loading-stop", info => topbar.hide())

      liveSocket.connect()
    </script>
    <style>
      * { font-size: 16px; }
    </style>
    <%= @inner_content %>
    """
  end

  def render( assigns) do
    ~H"""
    <div>
      <%=
        live_render( @socket, Example.NestedLive, id: "TopicLive")
      %>
    </div>
    """
  end
end

defmodule Example.Router do
  use Phoenix.Router
  import Phoenix.LiveView.Router

  pipeline :browser do
    plug(:accepts, ["html"])
  end

  scope "/", Example do
    pipe_through(:browser)

    live("/", ParentLive)
  end
end

defmodule Example.Endpoint do
  use Phoenix.Endpoint, otp_app: :sample
  socket("/live", Phoenix.LiveView.Socket)
  plug(Example.Router)
end

{:ok, _} = Supervisor.start_link([Example.Endpoint], strategy: :one_for_one)
Process.sleep(:infinity)
```

**Comment by josevalim** [comment]
@DaTrader everything is working as expected.

Both child and parent LiveViews, if crashed during dead render, leads to the 500 page. If crashing during the live render, and they are linked, they reconnect. I believe more recent LiveViews/Phoenix will attempt a dead render though, after several failed attempts to reconnect.

You said this:

> However, regardless of whether the two processes are linked, I can't get a crashing nested LiveView process crash its parent process along if the crash is occurring while the child is getting mounted or while rendering after mounting.

And I cannot reproduce this behaviour. I added this to the ParentLive (which is the snippet I suggested in my first comment):

```
  def mount(_params, _session, socket) do
    if socket.transport_pid do
      parent = self()

      spawn(fn ->
        ref = Process.monitor(parent)

        receive do
          msg -> IO.inspect(msg)
        end
      end)
    end

    {:ok, socket}
  end
```

And I could see that, whenever the child/nested liveview crashed, the parent would crash too, with the precise error of the child (which is what happens in case of links):

```
{:DOWN, #Reference<0.3561019800.1059061761.58467>, :process, #PID<0.367.0>,
 {%MatchError{term: :error},
  [
    {Example.NestedLive, :mount, 3, [file: ~c"foo.exs", line: 37]},
    {Phoenix.LiveView.Utils, :"-maybe_call_live_view_mount!/5-fun-0-", 6,
     [file: ~c"lib/phoenix_live_view/utils.ex", line: 354]},
    {:telemetry, :span, 3,
     [
       file: ~c"/Users/jose/Library/Caches/mix/installs/elixir-1.18.0-dev-erts-15.0/03d0bc2dc33f319852ed285e2759ec51/deps/telemetry/src/telemetry.erl",
       line: 321
     ]},
    {Phoenix.LiveView.Channel, :verified_mount, 8,
     [file: ~c"lib/phoenix_live_view/channel.ex", line: 1176]},
    {Phoenix.LiveView.Channel, :handle_info, 2,
     [file: ~c"lib/phoenix_live_view/channel.ex", line: 84]},
    {:gen_server, :try_handle_info, 3, [file: ~c"gen_server.erl", line: 2173]},
    {:gen_server, :handle_msg, 6, [file: ~c"gen_server.erl", line: 2261]},
    {:proc_lib, :init_p_do_apply, 3, [file: ~c"proc_lib.erl", line: 329]}
  ]}}
```

**Comment by josevalim** [comment]
After playing a bit more with the code, it seems there is a race condition. Depending on _when_ the link breaks, the parent LiveView crashes, the websocket is terminated and never reconnected. Everything is behaving as expected on the _server_ but we may not be handling a scenario on the client. Thanks for the repro!

**Comment by DaTrader** [comment]
@josevalim I'm glad I helped. I also apologize for not expressing myself clearly/correctly. What I really meant by 

> I can't get a crashing nested LiveView process crash its parent process along if the crash is occurring while the child is getting mounted or while rendering after mounting. 

was that I couldn't get it to display the 500 page. It does restart on the server side, but what follows on the client side is that it hangs (which is why I included the `topbar` in the demo to make it obvious).

Thanks

**Comment by josevalim** [comment]
> was that I couldn't get it to display the 500 page

Just to align expectations, it don't believe it will display the 500 page. Once fixed, it will most likely behave as a button on the page that crashes whenever you click it. Or a Task async link that breaks.
