### ISSUE TITLE
Allow trailing / leading elements in stream containers

### ISSUE THREAD

**Issue by SteffenDE** [phoenixframework/phoenix_live_view#3260]
As mentioned in https://github.com/phoenixframework/phoenix_live_view/pull/3078#issuecomment-1944180783 and https://github.com/phoenixframework/phoenix_live_view/pull/3078#issuecomment-1944377073, we should allow leading / trailing non stream elements in stream containers for easier handling of empty states.

References #3078.

**Comment by DaTrader** [comment]
@SteffenDE Nice! I've been working around the absence of this feature by simply having a parent scroll container and then a leading, a stream and a trailing container as its children.
