### ISSUE TITLE
function arguments indentation is not fixed if followed by `do` when formatting heex file

### ISSUE THREAD

**Issue by michallepicki** [phoenixframework/phoenix_live_view#3275]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 26 [erts-14.2.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

Elixir 1.16.2 (compiled with Erlang/OTP 26)
```
* Phoenix LiveView version (mix deps): main
* Operating system: MacOS, Ubuntu

### Actual behavior

```elixir
# formatter_bug.exs

Mix.install([
  {:phoenix_live_view, github: "phoenixframework/phoenix_live_view", branch: "main", override: true},
])

html =
"""
<%= link(
  to: "some/path",
            class: "btn"
    ) do %>
  asdf
<% end %>
"""

dbg(Phoenix.LiveView.HTMLFormatter.format(html, heex_line_length: 100) == html)
```

```
$ elixir formatter_bug.exs
[formatter_bug.exs:17: (file)]
Phoenix.LiveView.HTMLFormatter.format(html, heex_line_length: 100) == html #=> true
```

### Expected behavior

I would expect the snippet to be formatted e.g. this way:

```
<%= link(
  to: "some/path",
  class: "btn"
) do %>
  asdf
<% end %>
```

i.e. function arguments / keyword list elements to be aligned consistently with an indentation that makes some logical sense

**Comment by SteffenDE** [comment]
Hi @michallepicki, this is documented behavior: https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.HTMLFormatter.html#module-formatting

> This formatter does not format Elixir expressions with do...end. The content within it will be formatted accordingly though. Therefore, the given input:
> ```elixir
> <%= live_redirect(
>        to: "/my/path",
>   class: "my class"
> ) do %>
>         My Link
> <% end %>
> ```
> Will be formatted to
> ```elixir
> <%= live_redirect(
>        to: "/my/path",
>   class: "my class"
> ) do %>
>   My Link
> <% end %>
> ```

I don't know the reasons why it is the way it is, but I assume we'd probably accept a PR to implement this.

**Comment by michallepicki** [comment]
Thanks, I must have missed this part of the docs! Or if there are good reasons it is the way it is, maybe it should be mentioned in the docs why

**Comment by michallepicki** [comment]
Maybe @feliperenan remembers why the formatter doesn't handle such cases?

**Comment by josevalim** [comment]
It doesn't handle such cases because we would need to build an incomplete Elixir expression and then give it to the Elixir formatter. But the formatter does not accept incomplete Elixir expressions in the first place.

Another option would be to complete the expression yourself, by attaching the `end` node, and then remove it out before formatting, but there may be caveats too.

**Comment by josevalim** [comment]
Closing this. With function components and the like, do end blocks are less used, and things like conditionals and comprehensions have special attributes too.
