### ISSUE TITLE
assigns-eex.md says you can't reassign `assigns` in `render/1` when you can

### ISSUE THREAD

**Issue by anagrius** [phoenixframework/phoenix_live_view#3290]
### Environment

LiveView Docs v1.0.0-rc.0

### Actual behavior

The docs says:

> Unlike LiveView's `render/1` callback, a function component can
modify the assigns it receives via the `assign/2`, `assign/3`,
`assign_new/3`, and `update/3` functions. Therefore, you can assign
the computed values before declaring your template.

### Expected behavior

Cleanly you can:

```
def render(assigns) do
    assigns = assign(assigns, :foo, 123)

    ~H"""
    <%= @foo %>
    """
end
```

I think that should just be removed from the docs? See https://elixirforum.com/t/reassigning-assigns-in-render/64038/3 for context

**Comment by SteffenDE** [comment]
Related: https://github.com/phoenixframework/phoenix_live_view/pull/2887

@josevalim @alexcastano one of you can probably clarify this :)
