### ISSUE TITLE
Unexpected Focus Shift Bug in Phoenix Code When Interacting with Editable Elements

### ISSUE THREAD

**Issue by Roadhammer-Gaming** [phoenixframework/phoenix_live_view#3311]
*Phoenix version: Release 3.7 build 3.7.3-20322
build timestamp: 2024-05-25T13:23:21.725Z
* Operating system: windows 10
* Browsers you attempted to reproduce this bug on (the more the merrier): 
The problem ONLY happens in Phoenix code's built in live preview window.

I’ve encountered a bug in Phoenix Code related to the live server’s element click-to-navigate feature. When I click on an element within the live server preview, the editor automatically shifts focus to the corresponding HTML element in the code. This feature also switches the currently open file in the editor if the clicked element is associated with a different file. While this functionality is intended to aid in code navigation, it’s causing an unexpected focus shift that results in unwanted edits to the HTML file. The focus should remain on the live server’s editable fields until I explicitly click back into the editor. This issue disrupts the workflow, especially when I need to maintain my position in a specific part of the code. It appears to be a bug within the feature that handles element-to-code navigation in Phoenix Code.
![phoenixbug](https://github.com/phoenixframework/phoenix_live_view/assets/160162199/1fd81b6b-161e-4802-ada5-762b152f1c89)

**Comment by SteffenDE** [comment]
Hi, you’ve reported this issue to the wrong project. The project you are looking for is probably https://github.com/phcode-dev/phoenix

Thanks!

**Comment by Roadhammer-Gaming** [comment]
Sorry, I followed a link provided by Copilot AI to report the software bug
in Phoenix code, I should not have automatically assumed I was given the
correct link.
