### ISSUE TITLE
Is Phoenix LiveView compatible with Svelte?

### ISSUE THREAD

**Issue by mayel** [phoenixframework/phoenix_live_view#332]
I'm wondering if [Svelte](https://svelte.dev/) and Phoenix LiveView can be used together? What would be the pros, cons, limitations of such an approach? 

I also asked at #https://github.com/sveltejs/svelte/issues/3497

**Comment by chrismccord** [comment]
Please see our JS hook documentation and in the future direct questions to the elixir forum or slack. Thanks!
