### ISSUE TITLE
Discordance on liveview_Version, ln295, onJoin,  View.js

### ISSUE THREAD

**Issue by ndrean** [phoenixframework/phoenix_live_view#3321]
### Environment

* Elixir version (elixir -v): 1.17
* Phoenix version (mix deps): 1.17.14

* Phoenix LiveView version (mix deps): 0.20.17
"phoenix_live_view": {:hex, :phoenix_live_view, "0.20.17", "f396bbdaf4ba227b82251eb75ac0afa6b3da5e509bc0d030206374237dfc9450"

* Operating system: OSX
* Browsers you attempted to reproduce this bug on (the more the merrier):  Firefox, Chrome, Safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

with FIREFOX and SAFARI, but not with Chrome ,  I get an error message in the browsers console:

```
LiveView asset version mismatch. JavaScript version 0.20.15 vs. server 0.20.17. To avoid issues, please ensure that your assets use the same version as the server.
```

Check:
```
> liveSocket.version()
"0.20.15"
```

**Comment by rhcarvalho** [comment]
Could it have been a browser caching issue? I've just tried to reproduce on Firefox/Linux and I get `"0.20.17"` as expected both on latest Chrome and Firefox.

**Comment by ndrean** [comment]
Yes, thanks for the follow-up. 
Basically, I reset the computer and it's gone... so your guess is correct, caching issue probably.
Although I did check in a private window of course, reset node_modules, _build, deps, mix deps.update, stopped and relaunched browsers...

I indeed had a custom build.js to enable Solid.js with an esbuild plugin and esbuild does the job. I updated packages ?!

Thanks.
