### ISSUE TITLE
LastPass addon clears password fields when using phx-change

### ISSUE THREAD

**Issue by arianvassili** [phoenixframework/phoenix_live_view#334]
### Environment

* Elixir version (elixir -v): Elixir 1.9.1 (compiled with Erlang/OTP 20)
* Phoenix version (mix deps): Phoenix version (mix deps): phoenix_live_view 0.1.1 (hex), phoenix 1.4.9
* NodeJS version (node -v): v10.15.3
* NPM version (npm -v): 6.9.0
* Operating system: Windows 10
* Browser: Any

### Actual behavior

Password and password confirmation field gets cleared after leaving its focus when using phx-change with LastPass addon installed and enabled

### Expected behavior

Password field doesn't get cleared after leaving its focus when using phx-change with LastPass addon installed and enabled

**Comment by josevalim** [comment]
Could it be related to #70?

**Comment by arianvassili** [comment]
Yes! But what they missed, and what worked for me, is that it works as expected when disabling the LastPass addon

**Comment by chrismccord** [comment]
To be clear, have you added something along the lines of the following to your code? The `:value` must be explicitly provided:

```
  <%= label f, :password %>
  <%= password_input f, :password, value: input_value(f, :password) %>
  <%= error_tag f, :password %>

  <%= password_input f, :password_confirmation, value: input_value(f, :password_confirmation) %>
  <%= error_tag f, :password_confirmation %>
```

**Comment by chrismccord** [comment]
Please double check what I posted above. I just installed LastPass and was unable to recreate this in safari with the LastPass extension autofill. Thanks!
