### ISSUE TITLE
.dynamic_tag_name breaks for tags which need a 'name' attribute

### ISSUE THREAD

**Issue by superchris** [phoenixframework/phoenix_live_view#3341]
### Actual behavior

For code like the following:

```elixir
 ~H"""
   <.dynamic-tag name="custom-input" value="bar"></.dynamic-tag>
"""
```

There is no way to set the `name` attribute of the `custom-input` tag that will be generated. Particularly in the case of [form associated custom elements](https://html.spec.whatwg.org/dev/custom-elements.html#form-associated-custom-elements), this is a show stopper as the name attribute is used to set the inputs value on the form data.

### Expected behavior

Not clear, but a good option would be to allow a `tag_name` assign in addition to or instead of the `name` assign. In looking at the code, this seems easily doable. If there is agreement on the approach, I'd be happy send a PR.

**Comment by SteffenDE** [comment]
See also https://github.com/phoenixframework/phoenix_live_view/issues/2833

**Comment by superchris** [comment]
Not ideal, but I managed to craft a workaround in [live_elements](https://github.com/launchscout/live_elements) like so:
```elixir
  def custom_element_tag(assigns, tag_name, events) do
    attrs =
      assigns
      |> maybe_generate_id()
      |> Map.put("phx-hook", custom_event_hook())
      |> Map.put("phx-send-events", events)
      |> assigns_to_attributes()
      |> serialize()

    # Taken from `dynamic_tag` while awaiting fix for https://github.com/phoenixframework/phoenix_live_view/issues/3341

    assigns =
      assigns
      |> assign(
        tag_name: tag_name,
        escaped_attrs: Phoenix.LiveView.HTMLEngine.attributes_escape(attrs),
      )

    if assigns.inner_block != [] do
      ~H"""
      <%= {:safe, [?<, @tag_name]} %><%= @escaped_attrs %><%= {:safe, [?>]} %><%= render_slot(@inner_block) %><%= {:safe, [?<, ?/, @tag_name, ?>]} %>
      """
    else
      ~H"""
      <%= {:safe, [?<, @tag_name]} %><%= @escaped_attrs %><%= {:safe, [?/, ?>]} %>
      """
    end
  end
```

**Comment by SteffenDE** [comment]
Quoting @josevalim (https://github.com/phoenixframework/phoenix_live_view/issues/2833#issuecomment-1741335923):
> Yes, that's a tough one but changing this would be a breaking change. Since you know it is an input, you could do this:

@josevalim I'd say now is the time to make such a breaking change, before the final 1.0 release. Finding and adjusting this shouldn't be too bad. But, what about doing this:

```elixir
attr.(:tag_name, :string, required: false, doc: "The name of the tag, such as `div`.")
attr.(:name, :string, required: false, doc: "Deprecated: use tag_name instead. If tag_name is used, passed to the tag. Otherwise the name of the tag, such as `div`.")

attr.(:rest, :global,
  doc: """
  Additional HTML attributes to add to the tag, ensuring proper escaping.
  """
)

slot.(:inner_block, [])

def dynamic_tag(%{rest: rest} = assigns) do
  {tag_name, name} = case assigns do
    %{tag_name: tag_name, name: name} -> {tag_name, name}
    %{tag_name: tag_name} -> {tag_name, nil}
    %{name: name} -> {name, nil}
    _ -> raise "Either tag_name or name is required when using Phoenix.Component.dynamic_tag/1"
  end

  rest = Map.put(rest, :name, name)

  tag =
    case Phoenix.HTML.html_escape(tag_name) do
      {:safe, ^tag_name} ->
        tag_name

      {:safe, _escaped} ->
        raise ArgumentError,
              "expected dynamic_tag name to be safe HTML, got: #{inspect(tag_name)}"
    end

  assigns =
    assigns
    |> assign(:tag, tag)
    |> assign(:escaped_attrs, Phoenix.LiveView.HTMLEngine.attributes_escape(rest))

  if assigns.inner_block != [] do
    ~H"""
    <%= {:safe, [?<, @tag]} %><%= @escaped_attrs %><%= {:safe, [?>]} %><%= render_slot(@inner_block) %><%= {:safe, [?<, ?/, @tag, ?>]} %>
    """
  else
    ~H"""
    <%= {:safe, [?<, @tag]} %><%= @escaped_attrs %><%= {:safe, [?/, ?>]} %>
    """
  end
end
```

I didn't test this, but it should be backwards compatible. The only downside is the more complex code and the missing compile time validation for either tag_name or name being required.

**Comment by josevalim** [comment]
I agree that now is the time to change it. :+1: with deprecating it.
