### ISSUE TITLE
put_flash doesn't work together with push_navigate

### ISSUE THREAD

**Issue by ponychicken** [phoenixframework/phoenix_live_view#3347]
### Environment

* Elixir version (elixir -v): Elixir 1.16.2
* Phoenix version (mix deps): 1.7.14
* Phoenix LiveView version (mix deps): 1.0.0-rc.6
* Operating system: Linux

### Actual behavior

I have a form_component which I embed in different places.
After submitting the form the user should be redirected to another view,
which lives inside another LiveView.

form_component:
```
  defp save_object(socket, :new, params) do
    case Objects.create_object(params) do
      {:ok, case} ->
        notify_parent({:saved, object})

        {:noreply,
         socket
         |> put_flash(:info, "Object created successfully")
         |> push_navigate(to: socket.assigns.patch)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign_form(socket, changeset)}
    end
  end
```

Inside put_flash there is a note:
```
*Note*: While you can use `put_flash/3` inside a `Phoenix.LiveComponent`,
  components have their own `@flash` assigns. The `@flash` assign
  in a component is only copied to its parent LiveView if the component
  calls `push_navigate/2` or `push_patch/2`.
```
Inside my router I have the `plug :fetch_live_flash` inside the browser pipeline. 

### Expected behavior
Since I am calling put_flash together with push_navigate I would expect it to work. But it only works if I use push_patch, otherwise the flash never shows up.

**Comment by ponychicken** [comment]
Edit: Its independent of the form component. Even if I call push_navigate from the parent live view, I can never get the flash to show up.

**Comment by ponychicken** [comment]
I had my router setup like this:  
  ```

  ## Routes that require write permission
  scope "/", ToolWeb do
    pipe_through [:browser, :require_write_user]

    live_session :require_write_user,
      on_mount: [{ToolWeb.UserLive.Auth, :ensure_write_user}] do
      live "/object/new", ObjectLive.Index, :new
      live "/object/:id/edit", ObjectLive.Index, :edit
      live "/object/:id/show/edit", ObjectLive.Edit, :edit

    end
  end


  ## Routes that require logged-in
  scope "/", ToolWeb do
    pipe_through [:browser, :require_authenticated_user]

    live_session :require_authenticated_user,
      on_mount: [{ToolWeb.UserLive.Auth, :ensure_authenticated}] do
      live "/", ObjectLive.Index, :index

      live "/object", ObjectLive.Index, :index
      live "/object/:id", ObjectLive.Show, :show

    end
  end
```

This meant that the whole live session was changed on navigation. After adding the read only access path to the privileged session as well it worked again

**Comment by chrismccord** [comment]
You cannot push_navigation from one live session to another, you need to `socket |> put_flash(...) |> redirect(to: ...)` in such cases. Thanks!
