### ISSUE TITLE
form only changes after errors

### ISSUE THREAD

**Issue by Alt-iOS** [phoenixframework/phoenix_live_view#3362]
### Environment

* Elixir version (elixir -v):
Erlang/OTP 27 [erts-15.0] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]
Elixir 1.17.0 (compiled with Erlang/OTP 27)

* Phoenix version (mix deps):
   phoenix 1.7.14 (Hex package) (mix)
   locked at 1.7.14 (phoenix) c7859bc5

* Phoenix LiveView version (mix deps):
  phoenix_live_view 1.0.0-rc.6 (Hex package) (mix)
  locked at 1.0.0-rc.6
* Operating system:
   macOS 14.5
* Browsers you attempted to reproduce this bug on (the more the merrier): 
  Arc (chromium), Safari 
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:
   Yes
### Actual behavior

When a form is successful on the first try, it doesnt get cleaned despite receiving a clean form.
If I first fail, then succed, the form does get cleaned.

### Expected behavior

When submitting the form, the inputs should clear once I pass an empty changeset, they dont seem to be doing that if I am successful on the first try

### Some code to better explain 
```elixir
  def handle_event("save", %{"volunteer" => volunteer_params}, socket) do
    case Volunteers.create_volunteer(volunteer_params) do
      {:ok, volunteer} ->
        socket =
          update(
            socket,
            :volunteers,
            fn volunteers -> [volunteer | volunteers] end
          )

        changeset = Volunteers.change_volunteer(%Volunteer{})

        {:noreply, assign(socket, :form, to_form(changeset))}

      {:error, changeset} ->
        {:noreply, assign(socket, :form, to_form(changeset))}
    end
  end
```
Heres a video showing what I mean, 
1. the first time the form was correct, it doesnt get cleaned (unexpected)
2. then I failed with bad input, it doesnt get cleaned (expected)
3. then I submit a correct version, it does get cleaned (expected)
https://github.com/user-attachments/assets/1b76b6ae-c288-472e-810c-6bd490e640fe

**Comment by SteffenDE** [comment]
This is most likely caused by your `form` not actually changing in between mount and your handle_event. I assume you also assign a form based on an empty changeset in your `mount` callback, therefore the assign in the handle_event actually assigns exactly the same form and LV won't patch it.

There are multiple ways to handle this, the most straightforward one would probably be to push_navigate on success, getting a fresh LiveView. Another way would be to add an incrementing counter and put your form inside a `<div id={"form-#{@count}"}>`, which will force the form to be recreated on the client.

**Comment by chrismccord** [comment]
If you can provide a full example application, we can give better direction, but Steffen's feedback should work if the form contains no changes. Thanks!

**Comment by Alt-iOS** [comment]
I see, thanks to both of you! Coming from a more OOP world it didnt make sense in my head why it didnt change, because it is a new instance, but making it an action, `:new` in this case, it does get cleaned
