### ISSUE TITLE
Checkbox failing to render intermittently 

### ISSUE THREAD

**Issue by A-Legg** [phoenixframework/phoenix_live_view#338]
### Environment

* Elixir version (elixir -v): 1.8.1
* Phoenix version (mix deps): 1.4.9
* NodeJS version (node -v): v10.16.0
* NPM version (npm -v): 6.9.0
* Operating system: MacOS Majove 10.14.6

### Actual behavior
When attempting to render a list of TODO items that contain a checkbox, the checkbox will intermittently fail to render. 
![Screen Shot 2019-09-03 at 10 01 21 PM](https://user-images.githubusercontent.com/6379700/64378058-13524880-cfe9-11e9-9a7a-88e583aa05b8.png)

```
      <%= for task <- @completed_tasks do %>
        <li class="todo__item">
          <label class="todo__control">
            <%= checkbox(:follow_up_task, :complete,
              class: "todo__checkbox",
              phx_click: "save_task",
              phx_value: task.id,
              value: task.completed)
            %>
            <span class="todo__text">Contact via <%= task.medium %> regarding <%= format_content(task.content) %> completed on <%= format_datetime(task.updated_at) %></span>
          </label>
        </li>
      <% end %>

```
### Expected behavior
The checkbox renders for every task.

**Comment by chrismccord** [comment]
It looks like you need to specify a unique name to each checkbox, otherwise they are all identical inputs on the form. Can you try setting a unique name? Thanks!

**Comment by A-Legg** [comment]
@chrismccord That did it, thanks for taking the time!
