### ISSUE TITLE
allow_upload max_file_size doesn't allow arbitrary sizes

### ISSUE THREAD

**Issue by liamwhite** [phoenixframework/phoenix_live_view#3385]
### Environment

* Elixir version (elixir -v): 1.15.7
* Phoenix version (mix deps): 1.7.14
* Phoenix LiveView version (mix deps): 1.0.0-rc.6

### Enhancement

`allow_upload/3` currently only allows positive integer input for the `max_file_size` option. It should be extended to accept the atom `:infinity` to disregard this limit, since the default is 8MB.

Obviously we can also specify a limit that is so large it would never be reached in practice, but when using a custom writer to stream data into a remote service, my application doesn't need to occupy memory or disk space on the server running the LiveView application.

**Comment by chrismccord** [comment]
For an upload writer, you do what you want with the chunks, so the only thing held in memory is a sum of the chunks sizes sent over time, which is negligible. I would review a PR to add this, but as you said, you can seta  sufficiently large value so I am not entirely convinced we need to support infinity. Thanks!
