### ISSUE TITLE
Submitting a form with validation errors, if the button has `flex` class it inserts `<br>` tags inside it.

### ISSUE THREAD

**Issue by theopechli** [phoenixframework/phoenix_live_view#3388]
### Environment

* Elixir version (elixir -v): 1.17.2
* Phoenix version (mix deps): 1.7.9
* Phoenix LiveView version (mix deps): 0.20.1
* Operating system: Linux
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox, Chromium
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

When submitting a form with validation errors, if the button class contains `flex` then on multiple presses of the button it inserts `<br>` tags inside said button.

I cannot provide a single file app but I can provide the needed steps to reproduce:

1. Generate a new Phoenix application `mix phx.new hello`
2. Generate LiveView `mix phx.gen.live Blog Post posts title:string body:text`
3. Modify the `HelloWeb.PostLive.FormComponent` with the following contents:

```
defmodule HelloWeb.PostLive.FormComponent do
  use HelloWeb, :live_component

  alias Hello.Blog

  @impl true
  def render(assigns) do
    ~H"""
    <div>
      <.header>
        <%= @title %>
        <:subtitle>Use this form to manage post records in your database.</:subtitle>
      </.header>

      <.simple_form
        for={@form}
        id="post-form"
        phx-target={@myself}
        phx-change="validate"
        phx-submit="save"
      >
        <.input field={@form[:title]} type="text" label="Title" />
        <.input field={@form[:body]} type="text" label="Body" />
        <:actions>
          <.button phx-disable-with={gettext("add")} class="flex">
            <span>
              <%= gettext("some text") %>
            </span>
            <span>
              <span>
                <%= @number_x %>
              </span>
              <hr />
              <span>
                <%= @number_y %>
              </span>
            </span>
          </.button>
        </:actions>
      </.simple_form>
    </div>
    """
  end

  @impl true
  def update(%{post: post} = assigns, socket) do
    {:ok,
     socket
     |> assign(assigns)
     |> assign(number_x: 1)
     |> assign(number_y: 2)
     |> assign_new(:form, fn ->
       to_form(Blog.change_post(post))
     end)}
  end

  @impl true
  def handle_event("validate", %{"post" => post_params}, socket) do
    changeset = Blog.change_post(socket.assigns.post, post_params)

    {:noreply,
     socket
     |> assign(number_x: 1)
     |> assign(number_y: 2)
     |> assign(form: to_form(changeset, action: :validate))}
  end

  def handle_event("save", %{"post" => post_params}, socket) do
    save_post(socket, socket.assigns.action, post_params)
  end

  defp save_post(socket, :edit, post_params) do
    case Blog.update_post(socket.assigns.post, post_params) do
      {:ok, post} ->
        notify_parent({:saved, post})

        {:noreply,
         socket
         |> put_flash(:info, "Post updated successfully")
         |> push_patch(to: socket.assigns.patch)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, form: to_form(changeset))}
    end
  end

  defp save_post(socket, :new, post_params) do
    case Blog.create_post(post_params) do
      {:ok, post} ->
        notify_parent({:saved, post})

        {:noreply,
         socket
         |> put_flash(:info, "Post created successfully")
         |> push_patch(to: socket.assigns.patch)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, form: to_form(changeset))}
    end
  end

  defp notify_parent(msg), do: send(self(), {__MODULE__, msg})
end
```
 
5. Go to `http://localhost:4000/posts/new` and submit an empty form at least twice. You will notice that it adds `<br>` tags inside the button. If you press it more then it generates a lot of `<br>` tags. If you remove the `flex` class from the button, it works fine.

### Expected behavior

It should not insert `<br>` tags out of nowhere, even if the button has `flex` class.

**Comment by SteffenDE** [comment]
Hi @theopechli,

phx-disable-with works by replacing an elements `innerText`. It doesn't work with elements containing other elements.

From the docs:

> To handle latent events, the <button> tag of a form can be annotated with phx-disable-with, which swaps the element's innerText with the provided value during event submission.

See also https://github.com/phoenixframework/phoenix_live_view/issues/3224#issuecomment-2075079083

If you feel like the docs should be improved, feel free to send a PR :)
