### ISSUE TITLE
Select2 breaks radio button phx_change trigger

### ISSUE THREAD

**Issue by hasmanyguitars** [phoenixframework/phoenix_live_view#339]
### Environment

* Elixir version (elixir -v): Elixir 1.8.2 (compiled with Erlang/OTP 22)
* Phoenix version (mix deps): 1.4.9
* NodeJS version (node -v): v9.1.0
* NPM version (npm -v): 6.3.0
* Operating system: MacOS Mojave 10.14.6

### Actual behavior
Adding [select2](https://select2.org/) to a dropdown breaks radio buttons on the same form.

Example repo: https://github.com/hasmanyguitars/live_view_select2_demo (http://localhost:4000/form) and the [commit](https://github.com/hasmanyguitars/live_view_select2_demo/commit/dcea794d907013b1a5bde8c6e7eb72e05bd42844) that adds the select2 CSS breaks the radio button trigger.

#### Before the select2 CSS is added the radio button trigger works:
![without-select2-redo](https://user-images.githubusercontent.com/2788875/64393059-90d78200-d004-11e9-9ef6-63069a1945c1.gif)

#### After the select2 CSS is added, the radio button trigger no longer works until you select the opposite radio button and reselect the original:
![with-select2](https://user-images.githubusercontent.com/2788875/64391913-5ddebf80-cfff-11e9-891d-0dcebad6c48f.gif)

### Expected behavior
When the template is changed, the radio buttons should continue to trigger `filters_changed` events from the form.

The main thing that's different between the 2 versions, is that the working version is not going through `self.pushEvent` in a hook whereas the broken version is.

**Comment by chrismccord** [comment]
Please see the phx-hook documentation for interop with existing js libraries. You will need to "activate" or setup your select2 nodes on mount, and you will also need to mark the container which holds the js injected select2 DOM nodes as `phx-update="ignore"`. Thanks!

**Comment by chrismccord** [comment]
Since you are relying on phx-change on the form, you need to either dispatch the change event yourself on the select2 hook, or push *all* form values up with the pushEvent. The issue you're seeing is your pushEvent does not send the radio values. The following will fix it:

```javascript
    
    $(this.el).select2({
      placeholder: 'Choose template',
      minimumResultsForSearch: Infinity,
      templateResult: self.formatSelect
    }).off("select2:select").on("select2:select", function(e) {
      self.el.dispatchEvent(new Event("change", {bubbles: true}))
    });
```

**Comment by hasmanyguitars** [comment]
Thank you @chrismccord! Great talk at ElixirConf last week by the way. I saw you mention `pushEvent` and got a little overzealous without really digging into what was going on behind the scenes.
