### ISSUE TITLE
Testing Liveview inside Liveview strange behaviour.

### ISSUE THREAD

**Issue by WernerBuchert** [phoenixframework/phoenix_live_view#3393]
### Environment

* Elixir version (elixir -v): Erlang/OTP 26 [erts-14.2.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit] [dtrace]
                                          Elixir 1.16.2 (compiled with Erlang/OTP 26)
* Phoenix version (mix deps): locked at 1.7.14 (phoenix) 
* Phoenix LiveView version (mix deps): 0.20.17 (Hex package) (mix)  locked at 0.20.17 (phoenix_live_view) 
* Operating system: MacOS 14.6.1
* Browsers you attempted to reproduce this bug on (the more the merrier): Work's in all browser but not the test.
* Does the problem persist after removing "assets/node_modules" and trying again? Yes

### Actual behavior

First of all, thanks for phoenix and phoenix_live_view, i love it.
On a side project i have a liveview application with  a another liveview application in the side bar of the application,
that is a liveview inside a liveview.
It work's fine in all browser's as expected, the strange thing is, that the test of the liveview in the sidebar doesn't work,
that is, the event isn't send to the liveview process in the sidebar but to the main liveview process,  which of course has no corresponding handle_event function.

I've made a simplified version of the problem on github:

[live_test](https://github.com/WernerBuchert/live_test)

And this is the test, that doesn't work:

[live_temperature_test.exs](https://github.com/WernerBuchert/live_test/blob/main/test/live_test_web/live/live_temperature_test.exs)

The liveview in the sidebar is rendered with live_render in the file

[app.html.heex](https://github.com/WernerBuchert/live_test/blob/main/lib/live_test_web/components/layouts/app.html.heex)

But as far as I know, LiveBeat also uses the live_render function for the LiveBeatsWeb.PlayerLive Module.

mix test results in the following error:

>  ** (EXIT from #PID<0.338.0>) an exception was raised:
         ** (UndefinedFunctionError) function LiveTestWeb.MainLive.Index.handle_event/3 is undefined or private
             (live_test 0.1.0) LiveTestWeb.MainLive.Index.handle_event("inc_temperature", %{}, #Phoenix.LiveView.Socket<id: "phx-F-0Rb2Z_ZxXe7wFK", endpoint: LiveTestWeb.Endpoint, view: LiveTestWeb.MainLive.Index, parent_pid: nil, root_pid: #PID<0.341.0>, router: LiveTestWeb.Router, assigns: %{text: "Main Content of the application.", __changed__: %{}, flash: %{}, live_action: :index}, transport_pid: #PID<0.340.0>, ...>)
             (phoenix_live_view 0.20.17) lib/phoenix_live_view/channel.ex:508: anonymous fn/3 in Phoenix.LiveView.Channel.view_handle_event/3
             (telemetry 1.2.1) /Users/wernerbuchert/phoenix/live_test/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
             (phoenix_live_view 0.20.17) lib/phoenix_live_view/channel.ex:260: Phoenix.LiveView.Channel.handle_info/2
             (stdlib 5.2.2) gen_server.erl:1095: :gen_server.try_handle_info/3
             (stdlib 5.2.2) gen_server.erl:1183: :gen_server.handle_msg/6
             (stdlib 5.2.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3

### Expected behavior
As far as I understand it, the test should work.
or is my understanding of a Liveview inside Liveview completely wrong?

**Comment by SteffenDE** [comment]
Hi @WernerBuchert,

the functions inside LiveViewTest don't automatically target the nested LiveView. To send the event to the child view, you'll need to use [`find_live_child/2`](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveViewTest.html#find_live_child/2) or [`live_children/1`](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveViewTest.html#live_children/1), so something like this:

```elixir
    test "Increment Temperature", %{conn: conn} do
      {:ok, index_live, _html} = live(conn, ~p"/")
      assert inner_live = find_live_child(index_live, "inner-live")

      assert inner_live |> element("#button-temperature") |> render_click() =~
               "71"
    end
```

We're always happy to accept PRs to improve the documentation, so if you have the time, feel free to contribute :)

Thank you!

**Comment by jdmarshall** [comment]
`find_live_child/2`  is mighty difficult to find via googling the myriad flavors of "why aren't my nested liveview tests working' (almost all of the top links are about nested live_components, which I think maybe had some bugs back in the early days, and are still dominating the search results)

I'll see if I can find some better places to 'see also' that. Is there a doc about nested liveviews? I'm sure I found something when I did the first one but my brain is full.

**Comment by jdmarshall** [comment]
After sleeping on this, I'm wondering if it wouldn't be better for render_click to detect that you're clicking in a child view and handle this problem directly.

It's weird to have to change integration tests because the implementation of your code changed but not the user's experience.
