### ISSUE TITLE
phx-change requires target

### ISSUE THREAD

**Issue by francois08** [phoenixframework/phoenix_live_view#3394]
When typing in this input:
```elixir
<.input
  phx-change="suggest_country"
  value={@country_search_input}
  name="country"
/>
```
I get the JS error:
> view.js:944 Uncaught TypeError: Cannot read properties of null (reading 'getAttribute')
    at View.targetComponentID (view.js:944:47)
    at View.pushInput (view.js:1026:49)
    at js.js:72:20
    at view.js:275:55
    at LiveSocket.owner (live_socket.js:463:15)

It fails on this line:
```js
let cidOrSelector = opts.target || target.getAttribute(this.binding("target"))
```

It seems that a target is required? It isn't explained in docs?
https://hexdocs.pm/phoenix_live_view/form-bindings.html#form-events

Even when I try to add:
`phx-target={@myself}`

I'd have the error:
> ** (KeyError) key :myself not found in: %{

(where the map is the assigns)

I only have 1 live view for this app:
```elixir
defmodule MyAppWeb.MainLive do
  use MyAppWeb, :live_view
```

**Comment by francois08** [comment]
I found a comment of Chris here that all inputs need a parent form:
https://github.com/phoenixframework/phoenix_live_view/issues/2916#issuecomment-1884042538

I wrapped the input by `<.form>` and now it is working. But can we improve the error message? It is cryptic and misleading while having to wrap an input by a form is not enforced by LiveView (no warning/error given).

**Comment by francois08** [comment]
I have the following warning now though:

> warning: missing required attribute "for" for component Phoenix.Component.form/1
     │
 126 │         <.form>
 
 While I just want to make the input working. Nor sure what to pass to the `for` attribute in this case.

**Comment by francois08** [comment]
So instead of this:

```elixir
<.input
  phx-change="suggest_country"
  value={@country_search_input}
  name="country"
/>
```

I changed it to this:

```elixir
<.simple_form for={@country_search_form} phx-change="suggest_country">
  <.input field={@country_search_form[:search_input]} />
</.simple_form>
```

Got it working now if I handle the change on the form level, but note that this imply me having to feed the form with a map while I just care about a single input value.

This issue can be closed; leaving it open if anything interesting can be taken from this.

**Comment by SteffenDE** [comment]
Hi @francois08,

indeed every input with phx-change must be inside a form. I created a PR to get a better error message and changed the docs.

Just for completeness, to address your `for` "problem", you should be able to simply use a plain HTML `<form>` instead of the form/simple_form components:

```heex
<form>
  <.input
    phx-change="suggest_country"
    value={@country_search_input}
    name="country"
  />
</form>
```

I will say though that it is generally preferable to have the phx-change binding on a form instead of having it on individual inputs, even if your form only contains a single input, so your final solution is the way to go!

**Comment by francois08** [comment]
> even if your form only contains a single input

Could you explain why? And maybe that can also be explained in the docs. If I remember, the docs just say it's better without elaborating on the reason.

**Comment by SteffenDE** [comment]
@francois08 we had a long discussion on Slack a while ago about events from individual inputs. Iirc the gist of it is that we don't want to lead users onto a path that is generally bad for UX. Maybe @chrismccord can elaborate on this. He has a strong opinion on that one.
