### ISSUE TITLE
Passing a slot via attributes emits a warning (but still works)

### ISSUE THREAD

**Issue by aymanosman** [phoenixframework/phoenix_live_view#3399]
I get the following warning if I try to pass a slot via a components attributes.

```
     warning: undefined attribute "loading" for component Phoenix.Component.async_result/1
     │
 133 │       I am a wrapper <.async_result assign={@assign} loading={@loading} inner_block={@inner_block} />
```

Everything renders fine, but the warning is annoying. Is this expected behaviour?

Here is a minimal example that demonstrates the issue.

```elixir
attr :assign, :any
slot :loading
slot :inner_block
def wrap_async_result(assigns) do
  ~H"""
  <div>
    I am a wrapper <.async_result assign={@assign} loading={@loading} inner_block={@inner_block} />
  </div>
  """
end
```

```
<.wrap_async_result assign={AsyncResult.loading()}>
  <:loading>Loading...</:loading>
  Finished
</.wrap_async_result>
```

**Comment by SteffenDE** [comment]
Hi @aymanosman,

sorry for the late response. I'd say yes, this is expected, at least at the moment. LV differentiates between attributes and slots, so you'd need to do something like

```elixir
attr :assign, :any
slot :loading
slot :inner_block
def wrap_async_result(assigns) do
  ~H"""
  <div>
    I am a wrapper
    <.async_result assign={@assign}>
      <:loading><%= render_slot(@loading) %></:loading>
      <%= render_slot(@inner_block) %>
    </.async_result>
  </div>
  """
end
```

There are probably ways we could improve situations where existing components need to be wrapped, e.g. saying something like "wrap_async_result accepts the same attributes and slots as XYZ", but that's not something that is currently planned. If you want to start a discussion on this, the proposals section in the Elixir forum would probably the best place: https://elixirforum.com/c/phoenix-forum/proposals-suggestions/126

Thank you!

**Comment by aymanosman** [comment]
Cool. I've started a discussion [here](https://elixirforum.com/t/allow-forwarding-slots-without-warning/65967).
