### ISSUE TITLE
Flash message is not shown when redirect/2 is replaced with live_redirect/2

### ISSUE THREAD

**Issue by aptinio** [phoenixframework/phoenix_live_view#340]
### Environment

* Elixir version (elixir -v): 1.9.1
* Phoenix version (mix deps): 1.4.9
* NodeJS version (node -v): 12.10.0
* NPM version (npm -v): 6.11.3
* Operating system: Linux

### Actual behavior

When `redirect/2` is replaced with `live_redirect/2`, everything works just the same, except flash message isn't shown.

### Expected behavior

Flash message is shown.

#### Also, LiveView is awesome! Thank you to all those involved! <3

**Comment by minibikini** [comment]
Can confirm, I'm experiencing the same.

**Comment by TheMushrr00m** [comment]
Just curious, did you follow installation steps defined in the README.md?
Specifically this step:

```
Next, add the LiveView flash plug to your browser pipeline, after :fetch_flash:

# lib/my_app_web/router.ex

pipeline :browser do
  ...
  plug :fetch_flash
  plug Phoenix.LiveView.Flash
end
```

**Comment by minibikini** [comment]
@TheMushrr00m, yes, I did. 

Here is a demo:  http://redirect_demo.5jung.com/no_flash

Source: https://github.com/minibikini/redirect_demo ([router.ex](https://github.com/minibikini/redirect_demo/blob/master/lib/redirect_demo_web/router.ex), [live views](https://github.com/minibikini/redirect_demo/tree/master/lib/redirect_demo_web/live/no_flash_live))

**Comment by aptinio** [comment]
@TheMushrr00m, I did too. Thanks for making sure!

**Comment by snewcomer** [comment]
I think I know the scope of this issue.  There are a few things involved - 1. setting a `__phoenix_flash__` cookie and 2.`history.pushState`.  However, because we don't change the window.location (as we do in `redirect`), the `LiveView.Flash` plug, when called, doesn't know about the cookie in the `conn` yet.  @chrismccord Any thoughts on what we can do?  I could take care of setting the cookie in `js`, but not sure how we can get the `conn` aware of the new cookie...

**Comment by leseigneur** [comment]
Having the same issue here. Even if the display would work, the question is : how long do we keep the flash message on ? For non-LV pages, the message stay until page refresh or new URL, but in case of LV I think I'd like the message to auto-disapear after a while or a click on it. So, I'm thinking to implement myself a new type of flash message for LV.

**Comment by josevalim** [comment]
To be tackled on #570.
