### ISSUE TITLE
Support Navigate API

### ISSUE THREAD

**Issue by francois08** [phoenixframework/phoenix_live_view#3405]
To detect a change in the URL (when calling `push_patch`) I have the following ugly temporary workaround:

```js
let currentPage = location.href;
setInterval(function() {
  if (currentPage != location.href) {
    currentPage = location.href;
    // do something
  }
}, 500);
```

I would like to be able to use the new Navigate API, which address this needs of SPAs:

```js
window.navigation.addEventListener('navigate', (_event) => {
  // do something
});
```

https://developer.mozilla.org/en-US/docs/Web/API/Navigation_API

**Comment by tmjoen** [comment]
I believe Firefox and Safari still don't support this API? There was also a PR for some navigation guards/hooks, but I think it stranded: https://github.com/phoenixframework/phoenix_live_view/pull/3051

**Comment by SteffenDE** [comment]
@francois08 I just tested this in Arc (Chromium) and the navigate events fire as expected. Let me know if you've got any further questions :)
