### ISSUE TITLE
Access to hash fragment in handle_params

### ISSUE THREAD

**Issue by LostKobrakai** [phoenixframework/phoenix_live_view#341]
I wanted to highlight the row the hash pointed to and noticed currently one has only access to get params and the url, but not the hash fragment. This would especially be useful for highlights, which would not be possible with just css.

**Comment by chrismccord** [comment]
```elixir
def handle_params(params, url, socket) do
  hash = URI.parse(url).fragment
  ...
end
```

:)

**Comment by LostKobrakai** [comment]
Trying it a second time and it works. Apologies for the noise :D

**Comment by josevalim** [comment]
@LostKobrakai keep in mind though the first time around the fragment is nil, because the browser doesn't send the fragment on regular GET requests.
