### ISSUE TITLE
Lacking a public API function to extract params the way `Phoenix.LiveView.Route.live_link_info!/3` does

### ISSUE THREAD

**Issue by DaTrader** [phoenixframework/phoenix_live_view#3432]
The use case is I need both the query and the in-path params that the said function returns in a structure (which are also supplied to `handle_params/3`), but I have this need to propagate them along with the relative URI (because of its path). 

Currently I am doing just just that, but it feels very redundant and I'd really like to be able to pass/assign just a `URI.t()` structure and then transform it according to my needs on an on-demand basis. In doing so I'd prefer to reuse the params extraction logic that is already in place in LiveView but is not (yet) exposed as such, rather than copying that part of code.

For this purpose I propose a new public API function that, unlike the `live_link_info` and its bang variant, does only the params extraction so that both the `live_link_info` functions and our code can benefit from it.

Thanks

**Comment by chrismccord** [comment]
You can get this from `Phoenix.Router.route_info/4`, which returns a path_params key in the metadata, so I don't think there's any interface LV needs to expose?

    %{path_params: path_params} = Phoenix.Router.route_info(socket.router, "GET", path, host)

Thanks!

**Comment by DaTrader** [comment]
Thanks @chrismccord !
