### ISSUE TITLE
update to DOM is incorrectly done when using push_patch

### ISSUE THREAD

**Issue by sezaru** [phoenixframework/phoenix_live_view#3439]
### Environment

* Elixir version (elixir -v): 1.17.2
* Phoenix version (mix deps): 1.17.14
* Phoenix LiveView version (mix deps): 1.0.0-rc.6
* Operating system: Fedora Silverblue 40
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox, Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: no

### Actual behavior

I'm creating a dynamic tab component for my system. Basically the core idea is that the user can click in a button and a new tab will be created. When that tab is created, I also do a `push_patch` to "persist" the tabs in the URL.

If I click only in one button to add a tab, it works great, but if I add some latency (2000 ms) and then click in 3 buttons one after another very fast, LV will add the first tab, then the second but will not add the third, even though I can see the update event with it arriving and the URL having the third tab in its query.

Since this possible bug is hard to explain in more details on how to trigger, I created a small project so you can easily reproduce the issue:

https://github.com/sezaru/ui_tabs_bug

To reproduce it:
1) Go to `http://localhost:4000/dynamic_tabs`
2) Add some latency with `liveSocket.enableLatencySim(3000)`, enough latency so you are able to click in the buttons before the first request cames back from the server;
3) Click in the buttons `add tab 1`, `add tab 2` and `add tab 3` one after another;
4) You will see that the tabs 1 and 2 will be added but tab 3 will not.

Here is a quick video showing it:

https://github.com/user-attachments/assets/ae4f2cce-a77a-4dfc-9db5-6ef63a5a629d

Note that if I remove the push_patch call in `ui_web/live/dynamic_tabs_live/params.ex:47`, then all the tabs will be created correctly, but then the URL is not updated so that is not a real solution.

**Comment by chrismccord** [comment]
Can you try latest main to see if this still reproduces? Thanks!

**Comment by chrismccord** [comment]
I appreciate the reproduction, but it has a lot of no easily auditable deps so you'll need to prune it done to make it more minimal for me to try to reproduce on my end. In the meantime, please try it out on latest main and with any luck this is already fixed! Thanks!

**Comment by sezaru** [comment]
I just tested with the latest main and indeed it was fixed! Cheers!!

Thanks for fixing it and sorry for the convulated example.
