### ISSUE TITLE
Web View Transitions

### ISSUE THREAD

**Issue by bcardarella** [phoenixframework/phoenix_live_view#3447]
Has there been discussion on how to integrate [View Transitions API](https://developer.mozilla.org/en-US/docs/Web/API/View_Transitions_API/Using) with LiveView?

The View Transitions API apparently was introduced last year and it looks very impressive:

https://www.youtube.com/watch?v=xZteiW-cun8

And the [browser support](https://caniuse.com/?search=view%20transition) appears to be pretty good at the moment:

<img width="731" alt="Screenshot 2024-09-28 at 1 47 41 PM" src="https://github.com/user-attachments/assets/0b2e372a-2b75-4abb-8876-cb5b464eb3da">

In the event of browsers that don't yet support (i.e. Firefox) I believe it just falls back to the current behavior.

@SteffenDE thoughts?

**Comment by chrismccord** [comment]
Related efforts/discussions: https://github.com/phoenixframework/phoenix_live_view/pull/3051

Short of full browser support, the goal is to open up whatever interfaces we need to allow focus to integrate themselves before we can adopt it within LiveView. After 1.0 it's something we can tackle

**Comment by bcardarella** [comment]
Thanks!
