### ISSUE TITLE
Fragment scrolling does not work when using patch (Page B to Page A#something)

### ISSUE THREAD

**Issue by shahryarjb** [phoenixframework/phoenix_live_view#3452]
### Environment

* Elixir version (elixir -v): 1.17.2
* Phoenix version (mix deps): 1.7.14
* Phoenix LiveView version (mix deps): 1.0.0-rc.6 and last commit in main branch
* Operating system: macOs 14.6.1
* Browsers you attempted to reproduce this bug on (the more the merrier): chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: no

### Actual behavior
I am in Page B and want to go Page A after going; it needs to be scrolled to a div. I am using patch.

https://github.com/user-attachments/assets/39efb43b-127f-4ba6-bfef-73cea34c7775

As you see if I be in Page A and click on the link it works but if I go from Page B to A it does not work

> I tested it with `navigate` and still does not work

I just had small testing: first time user navigate from another page it returns the log or hash undefined, second time user click on the button again, it works and has `Hash`

path: `assets/js/phoenix_live_view/browser.js`

```javascript
  getHashTargetEl(maybeHash){
    let hash = maybeHash.toString().substring(1)
    if(hash === ""){ return }
    console.log("Log ======>", document.getElementById(hash))
    return document.getElementById(hash) || document.querySelector(`a[name="${hash}"]`)
  }
}
```
and it should be noted, it brings the last page history to new page and i do not know it is conflict? because the url history is not for new page

## Update - My solution to the problem

As you see if I create a timeout here (or wait to finish), it works and scroll to the div#id
```javascript
  pushState(kind, meta, to){
    if(this.canPushState()){
      if(to !== window.location.href){
        if(meta.type == "redirect" && meta.scroll){
          // If we're redirecting store the current scrollY for the current history state.
          let currentState = history.state || {}
          currentState.scroll = meta.scroll
          history.replaceState(currentState, "", window.location.href)
        }

        delete meta.scroll // Only store the scroll in the redirect case.
        history[kind + "State"](meta, "", to || null) // IE will coerce undefined to string
        let hashEl = this.getHashTargetEl(window.location.hash)

        if(hashEl){
          hashEl.scrollIntoView()
        } else if(meta.type === "redirect"){
          window.scroll(0, 0)
        }
       // or we can use timeout 1 here or `Promise.resolve()` instead of requestAnimationFrame to wait the page
       // is finished after mount
        requestAnimationFrame(() => {
          const locationHash = window.location.hash
          if (kind === "push" && locationHash != "") {
            const elmn = this.getHashTargetEl(locationHash)
            if (elmn) {
              elmn.scrollIntoView()
            }
          }
        });
      }
    } else {
      this.redirect(to)
    }
  },
```
----

### Expected behavior
I expect after coming from Page B it scroll to the div I specify

> **I did not make PR, because I think my way is so easy select and maybe there is better way and fix the problem from the source of this problem**

Thanks

**Comment by shahryarjb** [comment]
Hello LiveView team, I put my solution on first post. if you think it is a good way please tell me create a PR. it passes the unit test locally
Thank you in advance

**Comment by SteffenDE** [comment]
Hey @shahryarjb,

I didn’t have time to look into this yet. It would help us a lot if you could find the time to create a minimal single file reproduction that demonstrates the problem. No promises, but I’ll try to find some time tomorrow.

**Comment by shahryarjb** [comment]
Hi @SteffenDE, Thank you for your time
I needs 2 ex files to navigate, so I created very basic app that has 2 pages PageA: `"/"` and PageB: `"/b"`

https://github.com/shahryarjb/fragment

### I made screen record of problem and the fixed version 

https://github.com/user-attachments/assets/4b7d12cf-7049-4eb3-91ca-54256e808e35

If you need another things about this problem just let me know I do as fast as possible

My solution as the first comment i said, if it is a good way or can be improved let me know, I wish to be this project contributor, I am really excited 😆😆

```javascript
requestAnimationFrame(() => {
  const locationHash = window.location.hash
  if (kind === "push" && locationHash != "") {
    const elmn = this.getHashTargetEl(locationHash)
    if (elmn) {
      elmn.scrollIntoView()
    }
  }
});
```

Thank you in advance

**Comment by SteffenDE** [comment]
@shahryarjb thank you for the reproduction. I created a PR (https://github.com/phoenixframework/phoenix_live_view/pull/3467) and added you as co-author. Delaying the scrolling to only run after the DOM patch is a fine solution here :)

**Comment by shahryarjb** [comment]
@SteffenDE This is really an honor for me. I always wanted my name to be in the LiveView project. Thank you for doing me this favor

**Comment by SteffenDE** [comment]
You're welcome, thanks for reporting :)
