### ISSUE TITLE
KeyError: key "phx-xxx" not found after socket reconnection when uploading image

### ISSUE THREAD

**Issue by uzairaslam196** [phoenixframework/phoenix_live_view#3458]
### Environment

* Elixir version (elixir -v): 1.17.3-otp-27
* Phoenix version (mix deps): 1.7.14
* Phoenix LiveView version (mix deps): 0.20.17
* Operating system: macOS
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

A KeyError is encountered if the socket connection is re-established (e.g., after a server restart or resuming from laptop sleep) and the user attempts to upload an image without refreshing the page.

The error occurs because the upload references are invalid after reconnection, but the LiveView form doesn’t get reset, resulting in an attempt to access an outdated reference.

Error:
```
(KeyError) key "phx-F_xPxf3ZGfHt87hE" not found in: %{"phx-F_xSXzoxuMmUIr_D" => :file}
(phoenix_live_view 0.20.17) lib/phoenix_live_view/upload.ex:196:in `Phoenix.LiveView.Upload.get_upload_by_ref!/2'
```

### Expected behavior

The LiveView form should gracefully handle reconnections and reinitialize the file upload references after the socket is reconnected. Users should not encounter a KeyError when they try to upload files after reconnection without needing to refresh the page.

### Steps to reproduce

- Open a page that includes an image upload field using Phoenix LiveView.
- Without refreshing the page, perform one of the following actions to disrupt the socket connection:
	Option 1: Restart the server.
	Option 2: Put the laptop to sleep and then wake it back up.
- After the connection is re-established, attempt to upload an image.
- Observe that the upload fails, and the KeyError is thrown.

**Comment by chrismccord** [comment]
I believe this is fixed on 1.0-rc. If you can recreate on latest rc, please reopen. Thanks!
