### ISSUE TITLE
Potential issue with changing form values that make forms difficult to work with

### ISSUE THREAD

**Issue by andrewtimberlake** [phoenixframework/phoenix_live_view#3461]
### Environment

* Elixir version (elixir -v): 1.17.3
* Phoenix version (mix deps): 1.7.14
* Phoenix LiveView version (mix deps):1.0.0-rc.6

### Actual behavior

I have created an example form at https://github.com/andrewtimberlake/live_view_form_example
http://localhost:4000/form

The form manages a transaction that needs to be allocated to multiple receipts.
The transaction has a value and all the receipts must total the transaction value to be valid (in this example the transaction total switches between red and green)
The receipts are added/removed using the techniques illustrated in the docs for `inputs_for/1`

Most of the trouble comes when trying to calculate the running total because the value coming from the form field `@form[field].value` is constantly changing.
To make matters a little more complicated, the amounts are a struct, `%Money{amount: cents, currency: "GBP"}`, the money library has an ecto type that should be dealing with most of that.
The form displays an inspected view of the transaction total and the receipts list which shows how the values change back and forth between `%Money{}` and `string` for the transaction value, and the receipts list changes between `%Receipt{}` and `%Ecto.Changeset{}` and, sometimes,`{idx, %Map{}}`
I have added a lot of comments in the code I needed to write to get the form to actually work which highlights all the use cases I needed to account for. (Yes, it works, the bug I’m reporting is about usability)

Lastly, @josevalim requested I open this issue (https://x.com/josevalim/status/1844684140513255862)

I hope this helps. I’m happy to do any work to help change this for the better.

**Comment by SteffenDE** [comment]
Hi @andrewtimberlake,

this all looks correct to me. You should not rely on a field's `value` to have a nice format. In fact, the value field can be multiple things, as you noticed. If you're interested in the underlying code, this is it:

https://github.com/phoenixframework/phoenix_ecto/blob/b6f618d3336bcf8460b4cce59c23acad1cc82205/lib/phoenix_ecto/html.ex#L111-L125

Instead of working with the field's value, I'd suggest to instead move your logic into the changeset validation, where you can use functions like [`get_embed`](https://hexdocs.pm/ecto/Ecto.Changeset.html#get_embed/3) that even allow you to specify which format you want. Here's what I've come up with:

```diff
diff --git a/lib/live_view_form_example_web/live/form_live.ex b/lib/live_view_form_example_web/live/form_live.ex
index 967c724..9b3d193 100644
--- a/lib/live_view_form_example_web/live/form_live.ex
+++ b/lib/live_view_form_example_web/live/form_live.ex
@@ -9,6 +9,7 @@ defmodule LiveViewFormExampleWeb.FormLive do
       field :date, :date
       field :description, :string
       field :amount, Money.Ecto.Type
+      field :remaining, Money.Ecto.Type, virtual: true
 
       embeds_many :receipts, Transaction.Receipt, on_replace: :delete
     end
@@ -18,6 +19,43 @@ defmodule LiveViewFormExampleWeb.FormLive do
       |> cast(params, [:date, :description, :amount])
       |> validate_required([:date, :description, :amount])
       |> cast_embed(:receipts, sort_param: :receipts_sort, drop_param: :receipts_drop)
+      |> calc_and_validate_remaining()
+    end
+
+    defp calc_and_validate_remaining(changeset) do
+      receipts = get_embed(changeset, :receipts)
+
+      current_total =
+        Enum.reduce(receipts, Money.new(0, "GBP"), fn receipt, acc ->
+          if receipt.valid? do
+            amount =
+              case get_field(receipt, :amount) do
+                %Money{} = money -> money
+                amount -> Money.new(amount, "GBP")
+              end
+
+            Money.add(acc, amount)
+          else
+            Money.add(acc, Money.new(0, "GBP"))
+          end
+        end)
+
+      should_be_total =
+        case get_field(changeset, :amount) do
+          %Money{} = money -> money
+          amount -> Money.new(amount, "GBP")
+        end
+
+      remaining = Money.subtract(should_be_total, current_total)
+      changeset = put_change(changeset, :remaining, remaining)
+
+      if Money.equals?(current_total, should_be_total) do
+        changeset
+      else
+        add_error(changeset, :amount, "Total receipts do not match transaction amount")
+      end
     end
 
     defmodule Receipt do
@@ -107,9 +145,10 @@ defmodule LiveViewFormExampleWeb.FormLive do
         Add receipt
       </.button>
       <div>
-        <% remaining = calculate_remaining(@form) %> Remaining to allocate:
-        <strong class={if(Money.zero?(remaining), do: "text-green-500", else: "text-red-500")}>
-          <%= remaining %>
+        <strong class={
+          if(Money.zero?(@form[:remaining].value), do: "text-green-500", else: "text-red-500")
+        }>
+          <%= @form[:remaining].value %>
         </strong>
       </div>
       <div>
@@ -121,58 +160,4 @@ defmodule LiveViewFormExampleWeb.FormLive do
     </.form>
     """
   end
-
-  defp calculate_remaining(%Phoenix.HTML.Form{} = form) do
-    # Can’t guarantee that this is a Money struct, sometimes it’s a string — "£100.00"
-    # amount = form[:amount].value
-    amount = parse_amount(form[:amount].value)
-
-    # When I remove the intial receipt, this doesn’t correctly recalculate because there is a changeset indicating the removal that is unaccounted for
-
-    receipts = form[:receipts].value
-    # This doesn’t work because sometimes receipts is a list of Changesets
-    # receipts_total = receipts |> Enum.reduce(Money.new(0, "GBP"), &Money.add(&2, &1.amount))
-    receipts_total = sum_receipts(receipts)
-    Money.subtract(amount, receipts_total)
-  end
-
-  defp sum_receipts(receipts) do
-    receipts
-    |> Enum.reduce(Money.new(0, "GBP"), fn receipt, acc ->
-      IO.inspect(receipt, label: "receipt", structs: false)
-      Money.add(acc, receipt_amount(receipt))
-    end)
-  end
-
-  defp receipt_amount(%{amount: amount}), do: amount
-
-  # I need to account for a removed receipt (one from the original list, not added through the form, i.e. the first receipt) (otherwise the total is incorrect)
-  defp receipt_amount(%Ecto.Changeset{action: :replace}) do
-    Money.new(0, "GBP")
-  end
-
-  defp receipt_amount(%Ecto.Changeset{} = changeset) do
-    case Ecto.Changeset.get_field(changeset, :amount) do
-      # This case could be handled with a default value in the struct (but what if I need to set the currency?)
-      nil -> Money.new(0, "GBP")
-      %Money{} = amount -> amount
-    end
-  end
-
-  # This happens randomly—I can’t pin it down
-  # It happened when I adjusted the overall amount of the transaction
-  # It happens fairly reliably if I add a receipt and then remove it without having changed anything else
-  defp receipt_amount({_idx, %{"amount" => amount}}) do
-    parse_amount(amount)
-  end
-
-  defp parse_amount(%Money{} = money), do: money
-
-  # This is needed only in the case where a changeset is deleted (above: {_idx, %{"amount" => ""}})
-  defp parse_amount(""), do: Money.new(0, "GBP")
-
-  # Sometimes the money is a string
-  defp parse_amount(value) do
-    Money.parse!(value)
-  end
 end
```

**Comment by josevalim** [comment]
Thank you so much @SteffenDE, you did my homework for me. :heart:

I think we should probably add some notes to the docs about access `.value` and `input_value`, saying that the value is meant to keep form/field internals, and it is preferable to work on the underlying data. It would be great if we could come up with a tiny example to push people to the right direction.

Any thoughts on what this example could be, @SteffenDE and @andrewtimberlake?

**Comment by SteffenDE** [comment]
I’m off for today, but I can try to create a doc PR tomorrow. Probably adding a new section to the inputs_for documentation?

**Comment by josevalim** [comment]
Either `inputs_for` or `form`, or maybe both?

**Comment by SteffenDE** [comment]
@andrewtimberlake I created a doc PR (#3463), please don't hesitate to leave any comments :)

**Comment by andrewtimberlake** [comment]
Thanks @SteffenDE for the explanation, and the example changes.
