### ISSUE TITLE
The "Welcome - Phoneix LiveView" page (https://hexdocs.pm/phoenix_live_view/1.0.0-rc.6/welcome.html)  example doesn't work

### ISSUE THREAD

**Issue by justamanpop** [phoenixframework/phoenix_live_view#3464]
This is an issue I had when following the docs, not an issue with live_view itself, please let me know if this is not the right place to report this

### Environment

* Elixir version (elixir -v): 1.17.3
* Phoenix version (mix deps): 1.7.14
* Phoenix LiveView version (mix deps): 1.0.0-rc.6
* Operating system: Pop OS 22.04 LTS
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox 123.0.1 (64 bit)
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

I generated a project using `mix phx.new`, then tried to follow the live view example given in the docs (https://hexdocs.pm/phoenix_live_view/1.0.0-rc.6/welcome.html) 

### Actual behavior
Clicking the '+' button does not increment the temperature

### Expected behavior
Clicking the '+' button increments the temperature by one each time

### How I got it to work
I got it working by adding a pipeline with the following plugs to the scope that defines the live route:
```
  pipeline :liveview_pipe do
    plug :fetch_session
    plug :put_root_layout, html: {LiveviewTestWeb.Layouts, :root}
    plug :protect_from_forgery
  end
```
The example in the docs **does not** pipe_through anything in the live route scope:
```
defmodule MyAppWeb.Router do
  use Phoenix.Router
  import Phoenix.LiveView.Router

  scope "/", MyAppWeb do
    live "/thermostat", ThermostatLive
  end
end
```

**Comment by SteffenDE** [comment]
Hi @justamanpop,

this was recently addressed in https://github.com/phoenixframework/phoenix_live_view/pull/3457. I also adjusted the example a little bit further in https://github.com/phoenixframework/phoenix_live_view/commit/bff90ede202303b21b4a6c0d466f2a31add41dbd. So as soon as a new release is out, the guide is hopefully less confusing :)
