### ISSUE TITLE
Form inputs rendered outside the form element are not associated to the form via form attribute

### ISSUE THREAD

**Issue by victor23k** [phoenixframework/phoenix_live_view#3483]
### Environment

* Elixir version (elixir -v): 1.15.4
* Phoenix version (mix deps): 1.7.7
* Phoenix LiveView version (mix deps): 0.20.14
* Operating system: Linux
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox, Chromium
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

Inside an `.html.heex` template, I have a `.form` inside a table header, with a `text_input` and some `select` elements inside different table headers rows. The code looks like this:

```elixir
<.form
  :let={f}
  for={@changeset}
  phx-change="filter-event"
  phx-submit="filter-event"
  class="d-flex align-items-center"
>
  <tr>
    <th colspan="1">
      <div class="input-with-icon form-control-max-width mr-2">
        <i class="material-icons">search</i>
        <%= text_input(f, :query, placeholder: "Search by content…") %>
      </div>
    </th>
  </tr>
  <tr>
    <th colspan="3">
      <div class="d-flex w-fit">
        <%= select(
          f,
          :validity,
          [
            "Any validity": "all",
            Pending: "pending",
            Valid: "valid",
            Invalid: "invalid"
          ]
        ) %>
        <%= select(
          f,
          :answer,
          [
            "Any answer type": "all",
            Answered: "answered",
            Unknown: "unknown"
          ]
        ) %>
        <%= select(
          f,
          :user_feedback,
          [
            "Any feedback": "all",
            "User feedback": "with-feedback",
            "Positive feedback": "positive-feedback",
            "Negative feedback": "negative-feedback"
          ]
        ) %>
      </div>
    </th>
  </tr>
</.form>
```

When the input fields are changed, the phx-change event is not triggered. However, after a page reload the event is triggered.

In the rendered DOM, the `<form>` element appears empty, and the `<tr>` elements are rendered after. 

Doing some debugging with the browser developer tools, I could confirm that the input and select fields don't have the `form` attribute set on the first page load, but after a reload the form attribute is there.

### Expected behavior

The `form` attribute is set on first page load for the input and select elements to trigger the phx-change event.

**Comment by SteffenDE** [comment]
I think you're most likely rendering invalid HTML. See this Stackoverflow answer: https://stackoverflow.com/a/5967613

> A form is [not allowed](http://validator.w3.org/) to be a child element of a table, tbody or tr. Attempting to put one there will tend to cause the browser to move the form to it appears after the table (while leaving its contents — table rows, table cells, inputs, etc — behind).

You can either move the `<.form>` to be outside of your `<table>` element, or render it separately and associate your input fields using the `form` attribute.

**Comment by victor23k** [comment]
I tested explicitly adding the `form` attribute and it works regardless if the `<.form>` is inside `<table>` or outside. If the behaviour I described is considered normal then this issue can be closed. Thanks @SteffenDE!

**Comment by SteffenDE** [comment]
Yes it is most likely expected. I wouldn't call it "normal" though, as rendering a `<form>` inside a `<table>` / `<tbody>` is not valid HTML, therefore the browser tries to be helpful and rearranges the elements. Setting the form attribute works around this issue, but I'd still recommend you to render valid HTML in the first place.

I'll close this for now, let me know if you have any more questions :)
