### ISSUE TITLE
Auth scaffolding disabled-with

### ISSUE THREAD

**Issue by bkilshaw** [phoenixframework/phoenix_live_view#3485]
### Environment

* Elixir version (elixir -v): 1.17.2
* Phoenix version (mix deps): phoenix 1.7.14
* Phoenix LiveView version (mix deps): phoenix_live_view 1.0.0-rc.7
* Operating system: macOS 15.0.1
* Browsers you attempted to reproduce this bug on (the more the merrier):  Chrome, Firefox, Safari

### Actual behavior

When using the LV based auth scaffolding, the generated page includes `phx-disabled-with` on the login button. However; when you submit the form the button is not disabled and the disabled with text is not applied allowing the user to submit the form multiple times.

### Expected behavior

Once the form is submitted I'd expect the login button to be in it's disabled state so the user can't submit the form multiple times.

**Comment by bkilshaw** [comment]
https://github.com/user-attachments/assets/932c33ec-dded-4847-9bbb-b734876fab65

Demo on a fresh omsta;; only difference is I added a `Process.sleep(5000)` in the `TestappWeb.UserSessionController.create/3` so there's extra time to see the button state.

**Comment by chrismccord** [comment]
This was an artifact left over from the previous approach where we had the login_live LV maintaining the form with `to_form` and using `phx-trigger-action`. If you want phx-disable-with to work within dead forms, you need to have LV manage the form with`phx-change` on the form, and `phx-trigger-action` to submit to a controller. I have updated the phoenix generators to remove phx-disable-with from this template. Thanks!
