### ISSUE TITLE
Minor error: Incorrect names in array destructuring in Javascript View.cancelSubmit method

### ISSUE THREAD

**Issue by pzingg** [phoenixframework/phoenix_live_view#3524]
I have been trying to add Typescript typings to the Javascript in `phoenix_live_view/assets/js/phoenlx_live_view`. I believe there is a minor coding error that has no effects, but does make the argument naming incorrect for any developer (like me) who reads the code.

In the file view.js, the `View` class has a `formSubmits` field, an array. The method `scheduleSubmit` adds elements to the array:
`this.formSubmits.push([formEl, ref, opts, callback])`. Each item of the array is thus another array with **4** items.

But in the same file, in the method `cancelSubmit`, `Array.filter` is called, destructuring the array item, with only **3** items (the `opts` item has been omitted: `this.formSubmits = this.formSubmits.filter(([el, ref, _callback]) => ...`). The destructured `_callback` item (never used) is actually the `opts` item. The code should read:  `this.formSubmits = this.formSubmits.filter(([el, ref, _opts, _callback]) => ...`).

**Comment by 03juan** [comment]
Do all the tests pass if you make this change locally? You can submit a PR

**Comment by SteffenDE** [comment]
Thank you for reporting!
