### ISSUE TITLE
put_submitter/2 reports selector returning no elements when it should return two

### ISSUE THREAD

**Issue by woylie** [phoenixframework/phoenix_live_view#3525]
### Environment

* Elixir version (elixir -v):

Erlang/OTP 27 [erts-15.1.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]
Elixir 1.17.3 (compiled with Erlang/OTP 27)

* Phoenix version (mix deps): 1.7.14
* Phoenix LiveView version (mix deps): 1.0.0-rc.7
* Operating system: macOS Sequoia 15.1.1 (24B91)
* Browsers you attempted to reproduce this bug on (the more the merrier): no browser, LiveView tests only
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: no

### Actual behavior

If a form has two named submit buttons with the same name and a `form` attribute, and the buttons are not nested within the form:

```elixir
<.form
  for={@form}
  id="my-form"
  phx-change="validate"
  phx-submit="save"
>
  <.input field={@form[:name]} label="name" />
</.form>

<button type="submit" name="submit" form="my-form">Submit</button>
<button type="submit" name="submit" form="my-form">Submit</button>
```

And `Phoenix.LiveView.put_submitter/2` is used with a selector that should return both buttons:

```elixir
lv
|> form("#my-form")
|> put_submitter("button[name='submit']")
|> render_submit() 
```

The resulting error reports that the selector returns no elements:

```
** (ArgumentError) invalid form submitter, expected selector "button[name='submit']" to return a single element, but got none within:

(...)
```

### Expected behavior

I would expect the error to be the same as when the selector matches two submit buttons that are nested within the form:

```
** (ArgumentError) invalid form submitter, expected selector "button[name='submit']" to return a single element, but got 2:

         <button type="submit" name="submit">Submit</button>
         <button type="submit" name="submit">Submit</button>
```

**Comment by SteffenDE** [comment]
Thank you for reporting! :)
