### ISSUE TITLE
Form recovery not working when targeting forms in Live Components

### ISSUE THREAD

**Issue by ammancilla** [phoenixframework/phoenix_live_view#3527]
### Environment

* Elixir version (elixir -v): 1.15.7 (compiled with Erlang/OTP 26)
* Phoenix version (mix deps): 1.7.14
* Phoenix LiveView version (mix deps): 0.20.17 - a61d741f
* Operating system: mac OS - sequoia
* Browsers you attempted to reproduce this bug on (the more the merrier):  Firefox, Chrome, Safari.
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

A recoverable form rendered through a Live Compnent does not recover after a Live View crash/disconnect. In fact, not only the form does not recover but the Live View remains broken with:

> no component found matching phx-target of 1 undefined

<details><summary>Demo 🎥</summary>
<p>

![deterministic](https://github.com/user-attachments/assets/b7909557-53d9-4ae5-b14e-18f5a6f0f726)

</p>
</details> 

 

### Expected behavior

A recoverable form rendered through a live component, recovers successfully after a Live View crash/disconnect.

### Solution 

The bug was resolved in `Live View 1.0.0-rc.7` through commit https://github.com/phoenixframework/phoenix_live_view/commit/628f885ab745083b97009e23c1174d429bc456c2. Unfortunately, this fix was not included in the `LiveView ~> 0.20.7` release. Therefore, my question is: **Would it be possible to backport the fix and release it as part of the 0.20.x series for users who are unable to upgrade to Live View 1.x.x?**

**Comment by SteffenDE** [comment]
@ammancilla can you elaborate on why you are unable to update to 1.0?

Concerning backporting, that's up to @josevalim or @chrismccord :)

**Comment by SteffenDE** [comment]
> The final version 1.0.0 is not there yet.

There is no difference in stability between the 1.0 release candidates and any other release we did in the past. Looking back, I do think we should have done a `0.21.X` instead of naming them `1.0.0-rc.X`, but it is how it is now.

> who knows when they will support version 1.0.0.

Apart from the phx-feedback-for changes, there is no backwards incompatible change in 1.0 compared to 0.20, so if you use the shim mentioned in the changelog, you should be good to go. I encourage you to try moving to the RCs. You can add `override: true` to your dependency declaration to use the latest version even if a dependency officially only declared support for 0.20.

I think it is also worth mentioning that we do rely on people trying out the RCs to find issues and report them. While we try our best to not mess things up, sometimes unexpected issues do still arise. So if you find any issues when updating, please open an issue!

**Comment by ammancilla** [comment]
> > The final version 1.0.0 is not there yet.
> 
> There is no difference in stability between the 1.0 release candidates and any other release we did in the past. Looking back, I do think we should have done a `0.21.X` instead of naming them `1.0.0-rc.X`, but it is how it is now.
> 
> > who knows when they will support version 1.0.0.
> 
> Apart from the phx-feedback-for changes, there is no backwards incompatible change in 1.0 compared to 0.20, so if you use the shim mentioned in the changelog, you should be good to go. I encourage you to try moving to the RCs. You can add `override: true` to your dependency declaration to use the latest version even if a dependency officially only declared support for 0.20.
> 
> I think it is also worth mentioning that we do rely on people trying out the RCs to find issues and report them. While we try our best to not mess things up, sometimes unexpected issues do still arise. So if you find any issues when updating, please open an issue!

Thanks! 

There are certainly a few ways to stay on 0.27.x and get form recovery working without requiring a backport. Additionally, you provided a helpful tip on upgrading to 1.x.x by using override: true to manage dependencies that haven't been updated yet. That said, I'm okay with you deciding to close the issue, though it would still be great to have a fully functional form-recovery feature in a 0.27.x release.

**Comment by SteffenDE** [comment]
I'll keep this open to see if we might get feedback from José or Chris. Personally, I'd like people to not stumble into this (long fixed) bug on 0.20, but I don't do the releases. That being said, there are also other bugs that are already fixed, so it's not always easy to decide what is worth backporting and what not.

**Comment by josevalim** [comment]
1.0.0 is out :)
