### ISSUE TITLE
Type Error Thrown in Live Link Navigation in IE 11

### ISSUE THREAD

**Issue by brotherjack** [phoenixframework/phoenix_live_view#353]
### Environment

* Elixir version: 1.9.1
* Phoenix version: 1.4.10
* NodeJS version: 12.4.0
* NPM version: 6.9.0
* Operating system: Windows 10 Pro Version 1903

### Actual behavior

Content will not load and the following error is displayed in the console:

`SCRIPT5007: Unable to get property 'type' of undefined or null reference`

I created a minimal Live View example which demonstrates this error and can be viewed [here](https://github.com/brotherjack/ieelf).

The content will load on a page refresh. From what I could determine, the error was being generated by the following in  `assets/js/phoenix_live_view.js`

```javascript
  isTextualInput(el){
    return FOCUSABLE_INPUTS.indexOf(el.type) >= 0
  }
```

We changed this to return false when `el` is undefined, but as @chrismccord explained to me via email, this variable should not be undefined.

### Expected behavior

Content on page should display without a page refresh.

**Comment by snewcomer** [comment]
Do you happen to know who the `callee` is of `isTextualInput`?  IE11 only has partial support for `input` events (only text and password)...

**Comment by mcrumm** [comment]
@brotherjack Can you give this a shot with 0.2.0?  The issue appears to be resolved:

![live_nav_ie11](https://user-images.githubusercontent.com/168677/64918272-d278d300-d750-11e9-825c-c95aa3bbec22.gif)

My changes for reference: https://github.com/brotherjack/ieelf/compare/master...mcrumm:lv-0_2_0

**Comment by brotherjack** [comment]
I merged the changes you made @mcrumm, and I can confirm that the issue has been resolved. Thanks!
