### ISSUE TITLE
Unexpected pattern matching error with function components

### ISSUE THREAD

**Issue by thiagomajesk** [phoenixframework/phoenix_live_view#3531]
I noticed something today and thought it was better to raise it since it did not seem very intuitive (I might be just tired)... At first glance, it looks like an edge case of declarative attributes. The problem becomes apparent only when you call the function component directly - since with HEEx, you would get a compile-time warning. 

You can just scaffold a new Phoenix 1.7 project and make the following changes to the input component: 

```diff
- attr :field, Phoenix.HTML.FormField
+ attr :field, Phoenix.HTML.FormField, required: true
```

Then you'll get a `FunctionClauseError` which is weird considering that the function should technically match otherwise.
Making the `attr` required here seems to be preventing the other clauses from matching (since `field` is being assigned `nil`).

**Comment by SteffenDE** [comment]
This is expected as far as I can see:

![image](https://github.com/user-attachments/assets/6b848832-f62f-4031-871c-77535bf2e228)

The input component's first clause handles the `:field` being a `%Phoenix.HTML.FormField{}`:

```elixir
def input(%{field: %Phoenix.HTML.FormField{} = field} = assigns) do
  errors = if Phoenix.Component.used_input?(field), do: field.errors, else: []

  assigns
  |> assign(field: nil, id: assigns.id || field.id)
  |> assign(:errors, Enum.map(errors, &translate_error(&1)))
  |> assign_new(:name, fn -> if assigns.multiple, do: field.name <> "[]", else: field.name end)
  |> assign_new(:value, fn -> field.value end)
  |> input()
end
```

In there, we explicitly set `field` to `nil` and recursively call `input/1` because we want another clause to match next. So this code does rely on `field` not being required.

When LiveView transforms
```elixir
attr :field, Phoenix.HTML.FormField, required: true
```
into the underlying function, the generated code looks like this:

```elixir
def input((%{field: %Phoenix.HTML.FormField{}} = %{field: %Phoenix.HTML.FormField{} = field}) = assigns)
def input((%{field: %Phoenix.HTML.FormField{}} = %{type: "checkbox"}) = assigns)
def input((%{field: %Phoenix.HTML.FormField{}} = %{type: "select"}) = assigns)
def input((%{field: %Phoenix.HTML.FormField{}} = %{type: "textarea"}) = assigns)
def input((%{field: %Phoenix.HTML.FormField{}} = _) = assigns)
```

where required struct attributes are pattern matched in the function head. That's where the FunctionClauseError originates from. (If you're interested, I decompiled the code to remove all the macro magic where you can see the generated code: https://gist.github.com/SteffenDE/fc644dbb2b19f2261dd216999e16e177#file-core_components_required_decompiled-ex-L2485)

I'm not sure how we could improve the error message. (cc @josevalim)

**Comment by thiagomajesk** [comment]
I mean, you are right, in the sense that this is how `attr` works (and we are making `field` required). But I'm talking about userland, what I meant by _unexpected_ is the fact that the message doesn't make it obvious unless you know how `attr` works under the hood 😊.

**Comment by josevalim** [comment]
There isn't much we can do here, the error message is given by the compiler, and that's a general side-effect of code generation in general.

We could tell the compiler to not emit any error message, but I think that would be worse. Given this only happens if:

1. You are invoked the component directly
2. After proper warnings if you use HEEx

I think it is fine to say show it in those cases.

---

Btw, I disagree with this statement:

> Then you'll get a FunctionClauseError which is weird considering that the function should technically match otherwise.

If you make it required, then by definition, it is invalid input. If the input shows up as a FunctionClauseError or another exception, it is an implementation detail.

**Comment by thiagomajesk** [comment]
Hi @josevalim! 

> If you make it required, then by definition, it is invalid input. If the input shows up as a FunctionClauseError or another exception, it is an implementation detail.

We might be biased because we know what `attr` does under the hood (many users don't have this context). The way the code looks, makes you think `attr` is only applying to the first function declaration. 

I think I gave a good suggestion to make this look less ambiguous, if we enforce a function header must be used when you have multiple definitions, it might make it more obvious (again, same reasoning with `@doc`):

```elixir
attr :field, Phoenix.HTML.FormField, required: true

def input(assigns)

def input(%{field: field} = assigns), do: ~H""
def input(%{type: "textarea"} = assigns), do: ~H""

```

**Comment by josevalim** [comment]
> We might be biased because we know what attr does under the hood (many users don't have this context). The way the code looks, makes you think attr is only applying to the first function declaration.

I can see how people can interpret that but `@doc` is a perfect counter argument, as it applies to all clauses, and you are not required to write a `def input(assigns)` for `@doc` at all. That clause is only required if you have default arguments.

Similarly, I can see how `def input(assigns)` could be beneficial, but I can also see someone unfamiliar with Phoenix looking at it and thinking: why do we have a "clause" without any "do-end" part?

The issue with this discussion is precisely that, if our starting point is that the user doesn't know how it works, then we cannot assume they know anything and therefore there is no useful reference point. We can always argue that anything we choose will be unclear.

Therefore the question should be: which code would be clearest for an existing developer? Is it adding a line of code that is not strictly necessary? I don't think that would be it. Perhaps this is a matter of improving the docs for `:required` and saying that it will raise `FunctionClauseError` if the field is not given, if we don't do so yet.

**Comment by thiagomajesk** [comment]
> I can see how people can interpret that but @doc is a perfect counter argument, as it applies to all clauses, and you are not required to write a def input(assigns) for @doc at all. That clause is only required if you have default arguments.

Yes, but I was thinking more how it works in cases like the following:

```elixir
defmodule Greeter do
  @doc "Greet docs"
  def greet(term) when is_binary(term), do: "Hello #{term}"

  @doc "Greet docs"
  def greet(term) when is_integer(term), do: "Hello #{term}"
end
```

The usual way out of this is to just:

```elixir
defmodule Greeter do
  @doc "Greet docs"
  def greet(term)
  
  def greet(term) when is_binary(term), do: "Hello #{term}"
  def greet(term) when is_integer(term), do: "Hello #{term}"
end
```

Your example with default values was also a good one, which I think translates well with how `attr` works (for both required and default values).

> Similarly, I can see how def input(assigns) could be beneficial, but I can also see someone unfamiliar with Phoenix looking at it and thinking: why do we have a "clause" without any "do-end" part?

If we try to be more practical while still using this premise, what would you say is more cryptic, knowing about the inner workings of `attr` or that you can have function headers? My opinion is that the later is more common knowledge than the former.

> Therefore the question should be: which code would be clearest for an existing developer? Is it adding a line of code that is not strictly necessary? I don't think that would be it. Perhaps this is a matter of improving the docs for :required and saying that it will raise FunctionClauseError if the field is not given, if we don't do so yet.

I get your point, to me, the problem of just documenting the behavior, is that it doesn't really collocate the problem with the solution. It just makes the information available somewhere. Going with Read The Friendly Manual is valid but not the best UX 😅

In the end, I just wanted to make sure this concern was raised, I'm not qualified to determine what will work best as the core team, I can just share my experience with it. If you think this is already the best we can do, there's no improvements to be made.

**Comment by SteffenDE** [comment]
@josevalim I'm not that familiar with the Phoenix.Component.Declarative code, but just in theory we should be able to inject a fallback clause when we have a required struct and raise a custom exception at runtime when the attribute is missing, right?

**Comment by josevalim** [comment]
@SteffenDE that's tricky because maybe it is failing because of the user forgetting a clause. Then the user will be without their usual reporting too and our custom exception won't do as good of a job as the compiler.

**Comment by SteffenDE** [comment]
@josevalim I think something like this should have no false positives:

```diff
diff --git a/lib/phoenix_component/declarative.ex b/lib/phoenix_component/declarative.ex
index b80c3235..cf4b16fe 100644
--- a/lib/phoenix_component/declarative.ex
+++ b/lib/phoenix_component/declarative.ex
@@ -655,6 +655,28 @@ defmodule Phoenix.Component.Declarative do
         slot_names = for(slot <- slots, do: slot.name)
         known_keys = attr_names ++ slot_names ++ @reserved_assigns
 
+        fields =
+          for %{name: name, required: true, type: {:struct, struct}} <- attrs do
+            {name, quote(do: %unquote(struct){})}
+          end
+
+        field_names = Enum.map(fields, fn {name, _} -> name end)
+
+        required_fields_pattern_check =
+          if fields == [] do
+            []
+          else
+            [
+              quote do
+                if not match?(%{unquote_splicing(fields)}, merged) do
+                  raise <<"missing a required field for component ",
+                          unquote(to_string(name))::binary, ": ",
+                          unquote(Enum.join(field_names, ", "))::binary>>
+                end
+              end
+            ]
+          end
+
         def_body =
           if global_name do
             quote do
@@ -671,7 +693,11 @@ defmodule Phoenix.Component.Declarative do
                 |> Map.merge(assigns)
                 |> Map.put(:__given__, assigns)
 
-              super(Phoenix.Component.assign(merged, unquote(global_name), globals))
+              merged = Phoenix.Component.assign(merged, unquote(global_name), globals)
+
+              unquote_splicing(required_fields_pattern_check)
+
+              super(merged)
             end
           else
             quote do
@@ -680,6 +706,8 @@ defmodule Phoenix.Component.Declarative do
                 |> Map.merge(assigns)
                 |> Map.put(:__given__, assigns)
 
+              unquote_splicing(required_fields_pattern_check)
+
               super(merged)
             end
           end
```

but the stacktrace is not very nice:

```elixir
defmodule MyStruct do
  defstruct [:name]
end

defmodule MyComponent do
  use Phoenix.Component

  attr :foo, MyStruct, required: true

  def my_component(%{} = assigns) do
    ~H""
  end
end

defmodule Test do
  def run do
    MyComponent.my_component(%{foo: %MyStruct{name: "bar"}})
    MyComponent.my_component(%{})
  end
end

Test.run()
```

```
** (RuntimeError) missing a required field for component my_component: foo
    sample.exs:5: MyComponent.my_component/1
    sample.exs:22: (file)
```

This could probably be improved though.

**Comment by josevalim** [comment]
But won't that affect performance because we are now additionally checking for all fields? The goal of emitting the code that we have today is mostly to give the Elixir compiler enough hints to do further compiler checks without affecting runtime. Although once we have a type system we could get rid of modifying the user clauses altogether and just let the type system do the work.

**Comment by SteffenDE** [comment]
It is an additional check at runtime, yes, although I'm not sure if this is really a concern performance wise. The check does already happen in the generated clauses, so we "just" have it twice. I don't see a way to do it without a runtime check though.

So in the end we need to decide if this is worth it or not. I'm not really convinced.

If you think this can be nicely handled by future types, that's probably good enough :)

**Comment by josevalim** [comment]
Closing this for now. Types will do a better job and no runtime cost.

**Comment by thiagomajesk** [comment]
That makes sense, thanks for the clarifications @SteffenDE, @josevalim! 👍
