### ISSUE TITLE
`{...}` interpolation doesn't work with MJML style tag

### ISSUE THREAD

**Issue by oohnoitz** [phoenixframework/phoenix_live_view#3541]
### Environment

* Elixir version (elixir -v): 1.17.3
* Phoenix version (mix deps): 1.7.14
* Phoenix LiveView version (mix deps): 1.0.0-rc8
* Operating system: Linux
* Browsers you attempted to reproduce this bug on (the more the merrier):  Chrome, FireFox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

This isn't necessarily a bug. Currently, we are using HEEx to render our MJML templates with the `mjml` hex library. The new support for `{...}` interpolation causes problems with the usage of the `mj-style` tag since it tries to interpolate the CSS markup within that tag.

```heex
<mj-head>
  <mj-style>
    .p-15 { padding: 15px; }
     @media screen and (max-width:480px) {
       .sm-text-center div { text-align: center !important; }
     }
  </mj-style>
</mj-head>
```

It throws the following error:

```
** (SyntaxError) invalid syntax found _________________________
    error: invalid character "p" after number 15. If you intended to write a number, make sure to separate the number from the character (using comma, space, etc). If you meant to write a function name or a variable, note that identifiers in Elixir cannot start with numbers. Unexpected token: p
```

We could escape the markup like the following and it works, but is there a better way to handle this? It might be useful to document how to escape these characters. Or should we extend the HEEx engine instead and have it ignore the `mj-style` tag when dealing with MJML templates?

```heex
<mj-head>
  <mj-style>
    {".p-15 { padding: 15px; }"}
    {"@media screen and (max-width:480px) { .sm-text-center div { text-align: center !important; } }"}
  </mj-style>
</mj-head>
```

**Comment by SteffenDE** [comment]
Maybe it should be configurable like the global prefixes? @josevalim 

@oohnoitz it should also work like this I think 

```
<mj-head>
  <mj-style>
    {"""
     .p-15 { padding: 15px; }
     @media screen and (max-width:480px) {
       .sm-text-center div { text-align: center !important; }
     }
     """}
  </mj-style>
</mj-head>
```

**Comment by josevalim** [comment]
Another option is to introduce some sort of macro component. Surface has similar, and we don’t touch what is inside. It could be used for example to have a markdown tag that compiles to markdown at compile time or similar.

**Comment by SteffenDE** [comment]
It could maybe be a special attribute like `phx-no-format`?

**Comment by oohnoitz** [comment]
> ```
> <mj-head>
>   <mj-style>
>     {"""
>      .p-15 { padding: 15px; }
>      @media screen and (max-width:480px) {
>        .sm-text-center div { text-align: center !important; }
>      }
>      """}
>   </mj-style>
> </mj-head>
> ```

The code above returns the following:

```
** (MismatchedDelimiterError) mismatched delimiter found on lib/ui_v2/components/mjml.ex:14:14:
    error: unexpected token: }
    │
  4 │   def body(assigns) do
    │                     └ unclosed delimiter
 ...
 14 │           """}
    │              └ mismatched closing delimiter (expected "end")
    │
    └─ lib/ui_v2/components/mjml.ex:14:14
    (elixir 1.17.3) lib/kernel/parallel_compiler.ex:429: anonymous fn/5 in Kernel.ParallelCompiler.spawn_workers/8
```

This does affect `pre` and `code` tags with code snippets if they were hard-coded into the template too. I was curious on if a special attribute would work.

**Comment by josevalim** [comment]
I am not sure if we can make it work but if so that would be great. We could even remove it at compile time, so it is never emitted.
