### ISSUE TITLE
{...} breaks displays of JSON and other code (like displaying {...} interpolation)

### ISSUE THREAD

**Issue by andrewtimberlake** [phoenixframework/phoenix_live_view#3543]
### Environment

* Phoenix LiveView version (mix deps): 1.0.0-rc.8

JSON within a code block
```html
<pre><code>{"foo": "bar"}</code></pre>
```

```elixir
error: syntax error before: foo
         "foo": "bar"
```

Displaying interpolation (e.g. within a blog post)
```html
<p><code>{one}</code></p>
```

```elixir
error: undefined variable "one"
```

It would also break, so whitelisting `<pre>` or `<code>` would not be enough
```html
<div class="whitespace-pre">{"foo": "bar"}</div>
```

```elixir
error: syntax error before: foo
         "foo": "bar"
```

One suggestion is to replace `{` with `&#123;` or similar but that could be impractical with large amounts of JSON or similar code

**Comment by SteffenDE** [comment]
You can set `phx-no-curly-interpolation` on tags where you don't want to use the new syntax :)
