### ISSUE TITLE
Intermittent DBConnection.ConnectionError in tests

### ISSUE THREAD

**Issue by Munksgaard** [phoenixframework/phoenix_live_view#3545]
### Environment

* Elixir version (elixir -v): 1.17.3 (OTP 27)
* Phoenix version (mix deps): 1.7.14
* Phoenix LiveView version (mix deps): 0.20.17
* Operating system: NixOS

### Actual behavior

When running LiveView tests, that interact with the database, I sometimes get the following error message:

```
13:12:26.773 [error] Postgrex.Protocol (#PID<0.397.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.2126.0> exited
```

Here is an example:

```
mix test --trace lib/foo_test.exs
Running ExUnit with seed: 567516, max_cases: 1


FooTest [test/foo_test.exs]
  * test 1 (42.9ms) [L#48]
13:12:26.610 [error] Postgrex.Protocol (#PID<0.393.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.1966.0> exited
  * test 2 (33.8ms) [L#27]

Finished in 0.07 seconds (0.07s async, 0.00s sync)
2 tests, 0 failure
```

The errors don't seem to impact the result of the test (`mix test` still indicates that all tests ran successfully), but they clutter up the output and confuse everyone who looks at them.

The errors seem to mainly happen when testing LiveViews that consist of multiple processes. For instance, the tests in `foo_test.exs` connect to a LiveView, perform different actions including a live component that sends a message to its parent.

### Expected behavior

No errors.

**Comment by chrismccord** [comment]
Can you share your LiveView and your tests? Are you performing async work with assign_async or start_async? Or are you starting processing in any other way?

**Comment by Munksgaard** [comment]
I'm working on a minimal example, but it is a bit cumbersome since it involves both database accesses and components. However, I think I've managed to reproduce the issue without using any `assign_async` or `start_async`. 

There's been some discussion about (what I believe is) this issue on elixir forums: https://elixirforum.com/t/intermittent-dbconnection-connectionerror-in-tests/46037

**Comment by Munksgaard** [comment]
I've shrunk my example down a lot. Here is the LiveView module:

```elixir
defmodule LeafWeb.OrganizationLive.Onboarding do
  use Phoenix.LiveView

  alias Leaf.Companies.Company
  alias Leaf.Organizations.Organization
  alias Leaf.Repo

  @impl true
  def mount(%{"organization_id" => organization_id}, _session, socket) do
    organization = Repo.get!(Organization, organization_id)

    companies = Repo.all(Company) |> Repo.preload(:another_relation)

    {:ok,
     socket
     |> assign(:organization, organization)
     |> assign(:companies, companies)}
  end

  @impl true
  def handle_event("connect", _params, socket) do
    send(self(), :ok)

    {:noreply, socket}
  end

  @impl true
  def handle_params(params, _uri, socket) do
    company = Repo.get!(Company, params["company_id"])

    {:noreply, socket |> assign(:company, company)}
  end

  @impl true
  def handle_info(:ok, socket) do
    {:noreply,
     socket
     |> update(
       :companies,
       &replace_by_id(&1, socket.assigns.company)
     )}
  end

  defp replace_by_id([], x), do: [x]
  defp replace_by_id([%{id: id} | xs], %{id: id} = thing), do: [thing | xs]
  defp replace_by_id([x | xs], thing), do: [x | replace_by_id(xs, thing)]

  defp onboarding_steps(assigns) do
    [Enum.all?(assigns.companies, &Repo.preload(&1, :another_relation).another_relation)]
  end

  @impl true
  def render(assigns) do
    ~H"""
    <.another_element :for={step <- onboarding_steps(assigns)}></.another_element>

    <button phx-click="connect">
      Connect
    </button>
    """
  end

  defp another_element(assigns) do
    ~H"""
    <div></div>
    """
  end
end
```

And here is the test:

```elixir
defmodule LeafWeb.OrganizationLive.OnboardingTest do
  use LeafWeb.ConnCase, async: true

  import Mox
  setup :verify_on_exit!

  import Phoenix.LiveViewTest
  import Leaf.CompaniesFixtures
  import Leaf.OrganizationsFixtures

  alias Leaf.Accounts
  alias Leaf.Companies

  defp create_organization(%{user: user}) do
    organization = organization_fixture()
    user = Accounts.assign_organization(user, organization)
    %{organization: organization, user: user}
  end

  describe "integrations and companies" do
    setup [:register_and_log_in_user, :create_organization]

    test "do the thing", %{conn: conn, organization: organization} do
      company = company_fixture(organization)

      {:ok, lv, _html} =
        live(
          conn,
          ~p"/organizations/#{organization}/onboarding/new_integration/#{company}"
        )

      lv |> element("button", "Connect") |> render_click()
    end
  end
end
```

All the test does is click the "Connect" button, which is handled by the `handle_event` function. That in turn sends a process to itself (to mimic a LiveComponent communicating with its parent), which is handled in `handle_info`. 

There are a some other things going on, and I think they mostly have to be there to simulate some work going on. Removing either `another_element`, the `update` inside `handle_info` or the various preloads makes the error go away for me.

I reproduce the error with

```
mix test --trace --repeat-until-failure 1000 test/leaf_web/live/organization_live/onboarding_test.exs
```

Note that the tests don't actually fail, so you'll need to keep an eye out for the error message and stop the test loop yourself. For me, the error happens quite consistently within the first few runs of the test.

P.S.: Congrats on the release! I'm excited to try out 1.0 :heart:

**Comment by Munksgaard** [comment]
Aha! It seems like I need to insert a separate `render/1` call at the end of my function. If I change the end of the test to 

```elixir
lv |> element("button", "Connect") |> render_click()
render(lv)
```

The errors seem to go away.

**Comment by SteffenDE** [comment]
@Munksgaard you're absolutely right. Your handle_event sends a message to your LiveView to perform something at a later point in time, but the render_click in your test does not wait, it's basically finished right after your handle_event returns. Therefore the test process starts to be shutdown while your LV process does work in the database and you get the exit message from Postgrex.

When you insert the render call, your test actually waits for the LiveView to perform another render, which, since it is a single process, ensures that any other things it is currently doing are finished. I don't think there's much for LiveView to do here, maybe clarifying this somewhere in the docs. But in general if you see such an error, depending on what is happening in your LV you'll either do a `render` (if the LV itself does the work) or a `render_async` (if the LV uses start_async/assign_async and the database work is in the async task).

**Comment by Munksgaard** [comment]
Thanks for the detailed explanation @SteffenDE, it matches what I had reasoned myself. The only sort-of-reference to this kind of issue I can find in the documentation is [this section](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveViewTest.html#module-testing-regular-messages) which doesn't mention errors such as this one. Adding a note about errors like this might be nice, but I also think it helps just to have this issue which documents it.

**Comment by mackshkatz** [comment]
> When you insert the render call, your test actually waits for the LiveView to perform another render

@SteffenDE thanks for your answer, it helped clarify a situation I was dealing with where we do a `send_update()` to a LiveComponent within the same LiveView process within our `handle_event` callback. But the line I quoted above is a bit confusing to me. I didn't think that `render(view)` literally "waits" for the LiveView to "perform another render". I thought it simply returns the HTML based on the current state of the process linked to the liveview in the test.

The only reason I mention that is because if that's the case, then it seems like it could still _technically_ lead to the `render(view)` returning before the work in the `update` callback of the LiveComponent receiving the `send_update` finishes, am I tracking?

**Comment by SteffenDE** [comment]
@mackshkatz that's exactly it. Everything is serialized, therefore when you `render`, you guarantee that all other events have been processed (except things like assign_sync / start_async, they need render_async). This also applies to LiveComponents since they are also part of the LiveView process.

**Comment by ream88** [comment]
```elixir
  def wait_for_async_tasks(view, timeout \\ 5000) do
    {:ok, pids} = Phoenix.LiveView.Channel.async_pids(view.pid)

    pids
    |> Enum.map(&Process.monitor/1)
    |> Enum.each(fn ref ->
      assert_receive {:DOWN, ^ref, :process, _pid, _reason}, timeout
    end)
  catch
    :exit, _ -> :ok
  end
```

This is my current implementation for a small helper, which I use in every LiveView test.
