### ISSUE TITLE
Formatter adds whitespace with curly brace interpolation

### ISSUE THREAD

**Issue by woylie** [phoenixframework/phoenix_live_view#3548]
### Environment

* Elixir version (elixir -v): Elixir 1.17.3 (compiled with Erlang/OTP 27)
* Phoenix version (mix deps): 1.7.17
* Phoenix LiveView version (mix deps): 1.0.0
* Operating system: macOS
* Browsers you attempted to reproduce this bug on (the more the merrier): n/a
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

I have a component that deliberately avoided white space to prevent styling issues:

```elixir
    ~H"""
    {@value}<span
      :if={is_nil(@value)}
      class={@class}
      aria-label={@accessibility_text}
      {@rest}
    >{@placeholder}</span>
    """
```

With the previous syntax (`<%= ... %>`), the formatter left the component as it is. After upgrading to 1.0.0 and switching to the curly brace syntax, the formatter wants to introduce line breaks:

```
121 121  |      aria-label={@accessibility_text}
122 122  |      {@rest}
123     -|    >{@placeholder}</span>
    123 +|    >
    124 +|      {@placeholder}
    125 +|    </span>
124 126  |    """
125 127  |  end
```

### Expected behavior

I would expect that the formatter behaves the same way with the old syntax and the new syntax and doesn't introduce white space / line breaks.

As a workaround, I added the `phx-no-format` attribute.

**Comment by paulo-silva** [comment]
For me, it actually create a new empty like, like for example:

```
10 10  |    {AnalyticsTabs.render(@socket, @current_tab, @tab_params, @current_originator)}
11 11  |
   12 +|
   13 +|
```

**Comment by colindensem** [comment]
I should possibly open a new ticket, however this is a bit of an edge case, so adding here for future self/others. Please do let me know if you want a new issue.

Using LV 1.0.1, I was seeing this behaviour while prototyping some route specific layouts and using some html comments:

```
<body class="flex h-full flex-col font-body bg-white dark:bg-black">
  <!-- root -->
  {@inner_content}
</body>
</html>
```

The formatter was injecting a blank line. Once comitted, it would then inject two blank lines.

Removing the comment; intended to so once done prototyping, fixes the problem. Hence it's only really an issue if you're littering code with html comments... so perhaps this is a feature ;)

Many thanks for all the work.
