### ISSUE TITLE
Bracket syntax seems overly sensitive

### ISSUE THREAD

**Issue by pejrich** [phoenixframework/phoenix_live_view#3558]
I have some bracket literals in my HTML tags as the page displays some JSON(API docs so something like `<span>{</span>`). LiveView doesn't like these `{`. I can't find anything in the docs mentioning how to insert `{` inside HTML tags. I tried `\{` which didn't work. The reason I'm opening this as a bug is because even `{"{"}` didn't work. The only two things I got to work were......
.....get ready for it......
.....`{"#{"{"}"}`....that monstrosity, and `<%= "{" %>`.

`{"{"}` not working seems a bug to me, as this should surely interpret it as an Elixir string and not try to interpolate HEEX syntax in Elixir syntax(i.e. `{` vs `#{`). To me `<%= "{" %>` and `{"{"}` should be equivalent.

**Comment by TheArrowsmith** [comment]
According to [this error message](https://github.com/phoenixframework/phoenix_live_view/blob/593bab25b416fc76298c02cf1b10398250d8b20e/lib/phoenix_live_view/tokenizer.ex#L659), the preferred approach is to use the HTML escape character `&lbrace;`, or `<%= "{" %>`.

According to [this comment](https://github.com/phoenixframework/phoenix_live_view/pull/3514#discussion_r1846447083) from José, it's a deliberate choice to not support `{"{"}` as it would significantly increase the complexity of the implementation.

**Comment by pejrich** [comment]
> According to [this error message](https://github.com/phoenixframework/phoenix_live_view/blob/593bab25b416fc76298c02cf1b10398250d8b20e/lib/phoenix_live_view/tokenizer.ex#L659), the preferred approach is to use the HTML escape character `&lbrace;`, or `<%= "{" %>`.
> 
> According to [this comment](https://github.com/phoenixframework/phoenix_live_view/pull/3514#discussion_r1846447083) from José, it's a deliberate choice to not support `{"{"}` as it would significantly increase the complexity of the implementation.

That error message seems to be intermittent and only appears if the error is on the closing brace. I did get it after creating this post, but before that I was just getting this error message which isn't as helpful.

```
== Compilation error in file lib/myapp_web/html/page_html.ex ==
** (SyntaxError) invalid syntax found on lib/myapp_web/html/page/index.html.heex:335:244:
     error: syntax error before: '<'
     │
 335 │ ...                   </span><span class="token plain"></span>
     │                              ^
```

**Comment by pejrich** [comment]
Appear to be intentional behaviour. :(

**Comment by SteffenDE** [comment]
Note that we have adjusted the docs to mention this in https://github.com/phoenixframework/phoenix_live_view/pull/3554, but there’s no new release yet.

We know that the error messages aren’t great at the moment and are looking into improving them :)
