### ISSUE TITLE
Regression in 1.0.1: attr with struct reference creates compile time dependency 

### ISSUE THREAD

**Issue by marcandre** [phoenixframework/phoenix_live_view#3592]
### Environment

* Elixir version (elixir -v): Elixir 1.18.0 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): 1.7.18
* Phoenix LiveView version (mix deps): 1.0.1

### Actual behavior

```elixir
#...
attr :user, User
```

`mix xref --label compile` now shows a compile time dependency to `user.ex` which wasn't there in LiveView 0.20.14

### Expected behavior

No compile-time dependency should be introduced.

Regression of #2509 and https://github.com/phoenixframework/phoenix/issues/5160

**Comment by SteffenDE** [comment]
@josevalim it's https://github.com/phoenixframework/phoenix_live_view/commit/0b0b2a50660fc0b72fbd8c9fa61d227830e48344#diff-8a399cc9a3e142ef2ff2b7437ba397cb3affa4ed0346b53eb087d4d303b0f781

**Comment by SteffenDE** [comment]
weird, as the AST is identical

```
{:__block__, [],
 [
   {:=, [], [{:name, [line: 1995, column: 5], Phoenix.Component}, :foo]},
   {:=, [],
    [{:type, [line: 1995, column: 5], Phoenix.Component}, FooBarApp.User]},
   {:=, [], [{:opts, [line: 1995, column: 5], Phoenix.Component}, []]},
   {{:., [],
     [
       {:__aliases__, [alias: false], [:Phoenix, :Component, :Declarative]},
       :__attr__!
     ]}, [],
    [
      {:__MODULE__, [], Phoenix.Component},
      {:name, [], Phoenix.Component},
      {:type, [], Phoenix.Component},
      {:opts, [], Phoenix.Component},
      {{:., [], [{:__ENV__, [], Phoenix.Component}, :line]}, [no_parens: true],
       []},
      {{:., [], [{:__ENV__, [], Phoenix.Component}, :file]}, [no_parens: true],
       []}
    ]}
 ]}
```

**Comment by josevalim** [comment]
I messed up, I forgot the `%{__CALLER__ | function: {:__attr__, 3}}` bit. I will patch it accordingly. Thank you @marcandre and @SteffenDE.

**Comment by marcandre** [comment]
Thanks @josevalim ❤️

I had the exact same reasoning as @SteffenDE: identifying the commit, realizing the AST produced was the same and thus being thoroughly confused...

I understand it might be tricky, but the doc of `expand_literals` offers no explanation whatsover that could help resolve this (for mere mortals like myself).

Also, since there's clearly a pattern going on here, I was curious if it would be possible to have a macro `expand_litterals/1` that would generate the `expand_litterals(arg, %{__CALLER__ |  function: ... })`?

**Comment by josevalim** [comment]
@marcandre i don't think we should necessarily assume that we don't to track the literals and, even if we did, we wouldn't be able to say the module and function they are meant to belong to. :(

However, if you think the docs could be clearer, a PR is definitely welcome  :)

**Comment by marcandre** [comment]
> i don't think we should necessarily assume that we don't to track the literals 

(assuming this was meant to read "...don't want to...")
The doc does state this, though: "This function is mostly used to remove compile-time dependencies from AST nodes".
I'm also not suggesting (of course) to remove `expand_literals/2`, just to add `expand_literals/1`.

> and, even if we did, we wouldn't be able to say the module and function they are meant to belong to. :(

This wouldn't be successful (and helpful)?

```elixir
  defmacrop expand_literals(ast) do
    quote bind_quoted: [ast: ast, f: __CALLER__.function, m: __CALLER__.module] do
      Macro.expand_literals(ast, %{__CALLER__ | function: f, module: m})
    end
  end
```

> However, if you think the docs could be clearer, a PR is definitely welcome :)

My bad, I had entirely missed the part about `%{env | function: }`, although that's the part I don't quite understand, how that changes the dependency resolution.

**Comment by SteffenDE** [comment]
I have no idea if that’s right, but my working theory is that by setting the function, it’s treated as if we accessed the alias inside of a function, avoiding a compile time dependency, when we actually accessed it outside of a function. Does that make sense?

**Comment by josevalim** [comment]
> This wouldn't be successful (and helpful)?

Your definition wouldn't work because now we would expand the literal in the context of the caller (i.e. the Phoenix macro) and not the one calling the macro. You would need the macro and still pass the environment. Although I still think there is a dangerous assumption here that should be done very explicitly. I am not convinced hiding it will make it less confusing.

> I have no idea if that’s right, but my working theory is that by setting the function, it’s treated as if we accessed the alias inside of a function, avoiding a compile time dependency, when we actually accessed it outside of a function.

Exactly. Perhaps those are the exact bits that should be added to the docs? 🤔

**Comment by marcandre** [comment]
> Your definition wouldn't work because now we would expand the literal in the context of the caller (i.e. the Phoenix macro) and not the one calling the macro.

I'm confused as to why... won't the `__CALLER__` inside the `quote` be expanded at the same level?

I made a (ugly) script to verify this...

```elixir
defmodule I do
  def i(env, amended_env, context) do
    send(self(), {:i, env, amended_env})
    IO.inspect(amended_env, label: context)
    env
  end
end

defmodule Macro2 do
  defmacro expand_literals(ast) do
    quote bind_quoted: [ast: ast, f: __CALLER__.function, m: __CALLER__.module] do
      I.i(__CALLER__, %{__CALLER__ | function: f, module: m}, "in expand_literals/1")
      Macro.expand_literals(ast, %{__CALLER__ | function: f, module: m})
    end
  end
end

defmodule Phoenix do
  require Macro2

  defmacro attr(type) do
    I.i(__CALLER__, %{__CALLER__ | function: {:attr, 1}, module: Phoenix}, "in attr/1")
    Macro2.expand_literals(type)
  end
end

defmodule Example do
  require Phoenix
  Phoenix.attr(:example)

  {:i, env1, env_amended1} =
    receive do
      x -> x
    end

  {:i, env2, env_amended2} =
    receive do
      x -> x
    end

  (env1 == env2) |> dbg
  (env_amended1 == env_amended2) |> dbg
end
```

It prints that the both equality are respected. I wouldn't want to abuse your time though, so feel free to ignore since you are not convinced it could be helpful.

> Although I still think there is a dangerous assumption here that should be done very explicitly. I am not convinced hiding it will make it less confusing.

Clearly, this is up to you to decide, but I think there can not be a better proof that there is also danger in forgetting to do this

**Comment by josevalim** [comment]
I am sorry, my previous comment could have been better elaborated. You are right the __CALLER__ is correct but it assumes that it is being called from inside Phoenix macro. It could also be called from a private function called by the Phoenix macro where the caller is now a variable. I hope this makes a bit more sense, otherwise I can write it down tomorrow once I am back at the computer.

> Clearly, this is up to you to decide, but I think there can not be a better proof that there is also danger in forgetting to do this

Agreed. But there is a potentially more likely explanation that the developer who introduced this regression was over confident and should have double checked. :)

The most beneficial improvement we could do here is actually making this more testable, but I have no idea how it could be done at the moment. :(
