### ISSUE TITLE
`on_mount` introduce compile-time dependency in v1.0.1

### ISSUE THREAD

**Issue by marcandre** [phoenixframework/phoenix_live_view#3593]
### Environment

* Elixir version (elixir -v): Elixir 1.18.0 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): 1.7.18
* Phoenix LiveView version (mix deps): 1.0.1

### Actual behavior

Both `on_mount/4` and `live_session/3` with `on_mount` option introduce a compile-time dependency in LiveView 1.0.1:

```elixir

# index.ex
defmodule BasicAppWeb.FooLive.Index do
  use BasicAppWeb, :live_view

  on_mount {BasicAppWeb.ExampleHook, :example}
end

# router.ex
  # ...
  scope "/", BasicAppWeb do
    pipe_through :browser

    live_session :test,
      on_mount: BasicAppWeb.ExampleHook do
        live "/users", UserLive.Index, :index
      end
  end
  # ...
```

```
$ mix xref graph --label compile --sink lib/basic_app_web/example_hook.ex
lib/basic_app_web/live/foo_live/index.ex
└── lib/basic_app_web/example_hook.ex (compile)
lib/basic_app_web/router.ex
└── lib/basic_app_web/example_hook.ex (compile)
```

### Expected behavior

I expected that neither would introduce a compile-time dependency, like it was the case before (e.g. LiveView 0.20.14).

**Comment by josevalim** [comment]
Fixed as well.
