### ISSUE TITLE
redirect/2 is not working from childs

### ISSUE THREAD

**Issue by tim2CF** [phoenixframework/phoenix_live_view#362]
### Environment

* Elixir version (elixir -v): 1.9.1
* Phoenix version (mix deps): 1.4.9
* NodeJS version (node -v): v12.4.0
* NPM version (npm -v): 6.11.3
* Operating system: Mac

### Actual behavior

At the moment `redirect/2` function is not working from child LiveView component, for example 
https://github.com/coingaming/bennu/blob/5eff5ce5259b611a1742ccca15b0ad3ed3071f1c/lib/bennu/live_form.ex#L262-L264
If this expression is called - exception is raised. It worked just fine before.

```elixir
14:38:32.572 [error] GenServer #PID<0.964.0> terminating
** (ArgumentError) cannot invoke redirect/2 from a child LiveView
    (phoenix_live_view) lib/phoenix_live_view.ex:1171: Phoenix.LiveView.assert_root_live_view!/2
    (phoenix_live_view) lib/phoenix_live_view.ex:1073: Phoenix.LiveView.redirect/2
    (site_builder_flask) lib/bennu/live_form.ex:368: SiteBuilderFlask.Component.BOSiteDetails.DefaultCoreuiLive.handle_event/3
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:85: Phoenix.LiveView.Channel.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

Maybe this exception make sense for `live_redirect`, but why it is raised with `redirect`?

### Expected behavior

`redirect/2` works from a child LiveView like it was before

**Comment by tim2CF** [comment]
With this workaround redirects from child are working again
https://github.com/coingaming/bennu/commit/b73eb52779a31abae833a81ecf14bad6bae2361c
But I still think what this behaviour is a bug

**Comment by chrismccord** [comment]
It was intentional. Send a message to the `root_pid` if you need to redirect. Thanks!

**Comment by OvermindDL1** [comment]
@chrismccord Where is the `root_pid` documented, can't find it on hexdocs:
https://hexdocs.pm/phoenix_live_view/search.html?q=root_pid

**Comment by chrismccord** [comment]
It’s on the  %Socket{}
