### ISSUE TITLE
All the buttons submit the form

### ISSUE THREAD

**Issue by alexcastano** [phoenixframework/phoenix_live_view#368]
### Environment

* Elixir version (elixir -v): Elixir 1.9.1 (compiled with Erlang/OTP 22)
* Phoenix version (mix deps): phoenix 1.4.10 / phoenix_live_view 0.2.1
* NodeJS version (node -v): v10.13.0
* NPM version (npm -v): 6.8.0
* Operating system: ArchLinux

### Actual behavior
Any button inside of a form, even if it has `phx-click` attribute, submits the form.

### Expected behavior
In previous version, 0.1.1, the buttons didn't submit the form, but if they had `type="submit"`.

I executed the following command to update the js: `(cd assets && npm install --force phoenix_live_view)`

**Comment by chrismccord** [comment]
You need to provided `<button type="button"`. Per the spec, if no type is specified, it defaults to "submit" within forms:

> submit: The button submits the form data to the server. This is the default if the attribute is not specified, or if the attribute is dynamically changed to an empty or invalid value.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button

Thanks!

**Comment by alexcastano** [comment]
Thanks @chrismccord! What about `<a>` with `phx-click`? If we remove `href` is not clickable by default, if we put `href="#"` it jumps to the top and if we put `href=""` it reloads the page. Am I missing something here again?

Thank for your time :)

**Comment by moxley** [comment]
> Thanks @chrismccord! What about `<a>` with `phx-click`? If we remove `href` is not clickable by default, if we put `href="#"` it jumps to the top and if we put `href=""` it reloads the page. Am I missing something here again?

In the past, I've always solved this problem by putting `javascript:;` in the `href` attribute: `href="javascript:;`.

**Comment by alexcastano** [comment]
@moxley thanks! This works for my case :)
