### ISSUE TITLE
Back button does not update the page view after an initial live_redirect 

### ISSUE THREAD

**Issue by jfreeze** [phoenixframework/phoenix_live_view#380]
### Environment
* Elixir 1.9.1 (compiled with Erlang/OTP 21)
* phoenix_live_view 0.3.0 (Hex package) (mix)
* node - v10.6.0
* npm - 6.8.0
* Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

### Actual behavior

I have created a sample project at github called [Forbak](https://github.com/jfreeze/ForBak).
Clone the project and run `mix ecto.create` and launch it.

Browse to localhost:4001/registrations/new

Click on the Registration button to move the /registrations/show page.
Notice that the URL is updated and so is the page.

Click the back button, and the URL changes to /registrations/new, but the page does not change/update.

Click the forward button, and the URL changes to /registrations/show.

Click the back button, and the URL changes to /registrations/new and the page also updates.

You can refresh the page and repeat using the `live_link` "Go to Show Page". When using the `live_link`, the back button changes the URL and updates the page, unlike when using the form Registration button.

### Expected behavior

I expected the Registration button to perform the same as the `live_link` link.

**Comment by tmepple** [comment]
I'm having exactly this same issue with the master version of live_view on Chrome v78 with my project.  I cloned the Forbak repo, updated the `phoenix_live_view` dep to pull master from github, ensured the webpack compiled app.js file embedded the latest JS from master, and was able to reproduce.

Going to /registrations/new then clicking the button redirects you to the show page.  Clicking back causes the URL to change but not the view.  If you then click forward then back again it updates properly.
