### ISSUE TITLE
channel crashes when root_pid is not present

### ISSUE THREAD

**Issue by sparta-developers** [phoenixframework/phoenix_live_view#387]
We have an issue with a handful of our customers, where LiveView crashes during mount when matching on the verified session.

The problem is that the verified map does not include a `root_pid`. `parent_pid` is set to `nil`, but the `root_pid` key is not present. It happens for a small percentage of people, but for those individuals there are many thousands of crash reports.

### Environment

* Elixir version (elixir -v): 1.9.0
* Phoenix version (mix deps): 1.4.10
* NodeJS version (node -v): 10.16.0
* NPM version (npm -v): 6.11.3
* Operating system: Ubuntu

### Actual behavior

Observed stacktrace:

```
lib/phoenix_live_view/channel.ex:434 Phoenix.LiveView.Channel.mount/1
lib/phoenix_live_view/channel.ex:28 Phoenix.LiveView.Channel.handle_info/2
gen_server.erl:637 :gen_server.try_dispatch/4
gen_server.erl:711 :gen_server.handle_msg/6
proc_lib.erl:249 :proc_lib.init_p_do_apply/3
```

In a recent commit, this has moved here: https://github.com/phoenixframework/phoenix_live_view/blob/98249158878f26239803b8da0fc333fc7bf77f91/lib/phoenix_live_view/channel.ex#L435-L442

The associated code, following through `View.verify_session/3` does not appear to have changed to fix this.

### Expected behavior

We suspect that this may be caused by an old cookie session that does not have `root_pid` set. It started happening immediately after upgrading LiveView to `0.2.0`, and continues after upgrading to `0.3.0`. Looking at recent changes, we think that upgrading to `0.3.1` will not solve this problem.

It looks like [this commit](https://github.com/phoenixframework/phoenix_live_view/commit/2a21ac01be437860193b1d892341100caec69c77) added `root_pid`, but expects it to already be in the session. If there is an old session, `root_pid` will not be merged in.

We can reproduce locally by:
* deleting our session cookie
* checking out a revision of our application at LiveView version 0.1.0 and resetting our database
* visiting a live view page, and leaving the page open
* updating to the latest version of our application (LiveView 0.3.0), and running migrations
* starting the application, and seeing the channel crash when live view reconnects

**Comment by chrismccord** [comment]
A browser tab refresh is all that is needed to clear the bad session tokens. In the next release we will detect valid, but outdated tokens and reload the page for you. Thanks!

**Comment by sparta-developers** [comment]
We've pinned our deployed code to the commit which has the fix you mentioned, and now we're good to go; thank you for the direction and for mentioning that you guys have already fixed this issue.  Thanks!

**Comment by nathanl** [comment]
I love this bugfix so much. 💯 ❤️ 😄
