### ISSUE TITLE
Stand up initial js tests

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix_live_view#39]
I'm not up to speed on the latest in front-end testing, but we'll need DOM access for proper tests. My goal would be to keep it as simple as possible – which I'm not sure how much tinkering is involved for something like headless chrome vs jasmine in-browser tests. Would love your help and expertise here Scott!

**Comment by raygesualdo** [comment]
I'd be willing to help with this. 

@snewcomer Looking at the code, I wonder if it would be good to have unit tests (plain ol' Jest/Ava/whatever test) covering the `Browser`, `DOM`, and `Rendered` objects as well as utility functions and have a integration/e2e tests (via Puppeteer/etc.) covering `LiveSocket` and `View`.

**Comment by snewcomer** [comment]
hi @raygesualdo About to push up something basic as we speak.  Would love to work with you on this.  I'll add you to the WIP PR when it is up.
