### ISSUE TITLE
Phoenix.LiveViewTest returns only the first LV from the rendered HTML (potentially with wrong module associated)

### ISSUE THREAD

**Issue by alg** [phoenixframework/phoenix_live_view#392]
Wrong and incomplete view / module is being returned from `Phoenix.LiveViewTest.live(...)`.

### Environment

* Elixir version (elixir -v): Elixir 1.9.1 (compiled with Erlang/OTP 22)
* Phoenix version (mix deps): phoenix 1.4.10, phoenix_live_view 0.3.0 (locked at 04a68ac)
* NodeJS version (node -v): v9.8.0
* NPM version (npm -v): 6.9.0
* Operating system: Mac OS X 10.14.6

### Actual behavior

In tests when `{:ok, view, html} = live(conn, "/path")` returns, the `view` contains `module` corresponding to the one that is supposed to be rendering the whole view (mentioned in routes), but the `proxy` corresponding to the *first* view found in HTML.

It generates the issue when the first view in the HTML is not the one that was rendering the part of the page being tested. For example, I have the status bar LV that is present on every page.

This line returns only the first found view, but gives it the module of the tested view:

https://github.com/phoenixframework/phoenix_live_view/blob/master/lib/phoenix_live_view/test/live_view_test.ex#L255

### Expected behavior

Complete set of views returned as:

`{:ok, [%Phoenix.LiveViewTest.View{}, %Phoenix.LiveViewTest.View{}]}`

Should we return all found views from the `live(...)` function?
Is there even a way to find which view in HTML was rendered by which module?

**Comment by chrismccord** [comment]
This is expected. See the `live_isolated` test helper. Thanks!

**Comment by alg** [comment]
How do I access any LV other than first then? I need to check that the second view contains some text.

**Comment by chrismccord** [comment]
Use `live_isolated`
