### ISSUE TITLE
Diffing problem when using View render inside LiveView

### ISSUE THREAD

**Issue by hypno2000** [phoenixframework/phoenix_live_view#393]
### Environment

* Elixir version (elixir -v):
Erlang/OTP 22 [erts-10.5] [source] [64-bit] [smp:20:20] [ds:20:20:10] [async-threads:1] [hipe] [dtrace]
Elixir 1.9.1 (compiled with Erlang/OTP 22)

* Phoenix version (mix deps): 1.4.9
* Phoenix LiveView version (mix deps): tested with from 0.2.1 to current master (https://github.com/phoenixframework/phoenix_live_view/commit/e4c6f7140d5b8c383e584671a63c14e85e9c26e9)
* NodeJS version (node -v): 10.16.0
* NPM version (npm -v): 6.11.3
* Operating system: macOS Mojave 10.14.6

Demostration of this issue can be seen here: https://github.com/hypno2000/phoenix_live_view_example

Two scenarios:
### 1. LiveView render is using View render (http://0.0.0.0:4000/foo)
```elixir
defmodule DemoWeb.FooLive do
  use Phoenix.LiveView

  def render(assigns) do
    ~L"""
    <h2>Counter: <%= @counter %></h2>
    <button phx-click="inc">Inc</button>
    <%= for index <- @items do %>
      <h3>Item #<%= index %></h3>
      <%= DemoWeb.StaticView.render "index.html", assigns %>
    <% end %>
    """
  end

  def mount(_session, socket) do
    {:ok, socket |> assign(:counter, 0) |> assign(:items, 1..50)}
  end

  def handle_event("inc", _, socket) do
    {:noreply, update(socket, :counter, &(&1 + 1))}
  end
end
```

```elixir
defmodule DemoWeb.StaticView do
  use DemoWeb, :view
  import Phoenix.LiveView

  def render("index.html", assigns) do
    ~L"""
    <div>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit,
      sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
      nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
      reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
      Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia
      deserunt mollit anim id est laborum.
    </div>
    """
  end
end
```

<img width="1271" alt="scenario1" src="https://user-images.githubusercontent.com/417241/65817563-7b273800-e211-11e9-9794-c7c3569b680c.png">

In this scenario when `:counter` is incremented all of the unchanged static content inside `StaticView` is sent over the wire x50.

### 2. LiveView renders contents of StaticView inline (http://0.0.0.0:4000/bar)

```elixir
defmodule DemoWeb.BarLive do
  use Phoenix.LiveView

  def render(assigns) do
    ~L"""
    <h2>Counter: <%= @counter %></h2>
    <button phx-click="inc">Inc</button>
    <%= for index <- @items do %>
      <h3>Item #<%= index %></h3>
      <div>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit,
        sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
        nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
        reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
        Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia
        deserunt mollit anim id est laborum.
      </div>
    <% end %>
    """
  end

  def mount(_session, socket) do
    {:ok, socket |> assign(:counter, 0) |> assign(:items, 1..50)}
  end

  def handle_event("inc", _, socket) do
    {:noreply, update(socket, :counter, &(&1 + 1))}
  end
end
```

<img width="1268" alt="Screenshot 2019-09-28 at 16 48 05" src="https://user-images.githubusercontent.com/417241/65817624-53849f80-e212-11e9-9bb9-80d7fc4138c0.png">

In this scenario when `:counter` is incremented only new counter value is sent over the wire. 👍 

Is this a bug, expected behaviour and rendering views inside LiveView is discouraged, or it's missing feature which the upcoming `live_component`'s should address?

**Comment by chrismccord** [comment]
We have to invoked the `for` comprehension in the first example, because you are passing all `assigns`, and when `@count` changes, all we can say is the assigns for the sub renders have changed. If you instead explicitly passed the require assigns within the comprehension, then we would not evaluate the for  comprehension because we know those assigns did not change. The behavior you are seeing is expected in this case. Thanks!

**Comment by hypno2000** [comment]
Yes thanks, managed to discover this already. But it is inconsistent/fragile. Passing the assigns like this:
`<%= DemoWeb.StaticView.render "index.html", Map.take(assigns, [:socket]) %>` does not work for example. I assume because`Map.take` is seen as dynamic by LiveView.

Will do some macros to help with generating more explicit `%{socket: @socket}` syntax that will be recognized by LiveView. In general it looks like then that using anykind util or helper functions inside LiveView will be complicated.

I think this should be documented somewhere, ie Do's and Dont's what syntax should be used inside LiveView render.
