### ISSUE TITLE
tr phx-click doesn't work for ios

### ISSUE THREAD

**Issue by tobyjr** [phoenixframework/phoenix_live_view#394]
### Environment

* Elixir version (elixir -v): 1.9.1
* Phoenix version (mix deps): 1.4.10
* NodeJS version (node -v): v12.10.0
* NPM version (npm -v): 6.11.3
* Operating system: Mojave

### Actual behavior
Using phx-click within a table tr tag doesn't fire on ios/mobile, it does for desktop.

i.e. `<tr phx-click="show<%= user.id %>">`

### Expected behavior
Clicking on a table row within an ios browser would fire the phx-click

**Comment by jayjun** [comment]
See https://github.com/phoenixframework/phoenix_live_view/pull/315#issuecomment-524577041.

**Comment by snewcomer** [comment]
Thanks @jayjun! @tobyjr Let us know if you have any more thoughts but the discussion in the related issue should cover your use cases.
