### ISSUE TITLE
Diffing at comprehensions

### ISSUE THREAD

**Issue by hypno2000** [phoenixframework/phoenix_live_view#395]
### Environment
Elixir version (elixir -v):
Erlang/OTP 22 [erts-10.5] [source] [64-bit] [smp:20:20] [ds:20:20:10] [async-threads:1] [hipe] [dtrace]
Elixir 1.9.1 (compiled with Erlang/OTP 22)
Phoenix version (mix deps): 1.4.9
Phoenix LiveView version (mix deps): current master (e4c6f71)
NodeJS version (node -v): 10.16.0
NPM version (npm -v): 6.11.3
Operating system: macOS Mojave 10.14.6

Demonstration of this issue can be seen by running closing and running https://github.com/hypno2000/phoenix_live_view_example and visiting http://0.0.0.0:4000/select/1

### Given this LiveView
```elixir
defmodule DemoWeb.SelectLive do
  use Phoenix.LiveView
  alias DemoWeb.SelectLive
  alias DemoWeb.Router.Helpers, as: Routes

  def render(assigns) do
    ~L"""
    <%= for index <- @items do %>
      <h3>Item #<%= index %></h3>
      <%= live_link to: Routes.live_path(@socket, SelectLive, "#{index}") do %>
        <button>Select</button>
      <% end %>
      <div style="<%= if @active == index, do: "color: red" %>">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit,
        sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
        nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
        reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
        Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia
        deserunt mollit anim id est laborum.
      </div>
    <% end %>
    """
  end

  def mount(_session, socket) do
    socket =
      socket
      |> assign(:active, nil)
      |> assign(:items, 1..50)

    {:ok, socket}
  end

  def handle_params(%{"active" => active_str}, _, socket) do
    {:noreply, socket |> assign(:active, Integer.parse(active_str) |> elem(0))}
  end
end
```

### Actual behavior

When clicking "Select" button link contents (`<a data-phx-live-link="push" href="/select/48" to="/select/48">↵    <button>Select</button>↵  </a>`) 50x, once for every item in `for`, is sent over the wire.

<img width="1280" alt="Screenshot 2019-09-30 at 20 59 59" src="https://user-images.githubusercontent.com/417241/65904699-a5225b00-e3c7-11e9-8124-fb39fe983a94.png">

### Expected behavior

When clicking "Select" button expecting that only value of `style` attribute for one item is sent over the wire, as this was the only thing changed. Links should not be sent at all as nothing changed there.

Could be related to #393 

I am not sure if this is a bug or not. But hope that this issue is not closed after technical explanation why it occurs. Rather i'm looking for additional reasoning here if this is expected due to fundamental underlying architecture or it is something temporary that is expected to be solved in the future releases and its just too early at the moment. This is crucial for me to understand as we have big plans with LiveView.

Btw I'm super grateful all the work you are doing here and I'm very excited about this technology. I'm sure this is how we will do the web in the future. 🙏

**Comment by chrismccord** [comment]
This is expected, since the comprehension depends on the `@active` assign, the only thing we can say is the comprehension must be reinvoked. Check out the Temporary Assigns documentation and `phx-update="append"` for ways to optimize this to a single item update over the wire. Thanks!

**Comment by hypno2000** [comment]
Thanks for the answer.

I can not figure out how Temporary Assigns and `phx-update="append"` can help me to achieve granular updates (not inserts) on a single record in comprehensions without sending excessive data for every entry over the wire :(

Any chance you can do small example demonstrating this?

Thanks
