### ISSUE TITLE
Nested Child doesn't remount on parent assign change

### ISSUE THREAD

**Issue by PJUllrich** [phoenixframework/phoenix_live_view#396]
### Environment

* Elixir version (elixir -v): 1.9.1
* Phoenix version (mix deps): 1.4.10
* Phoenix LiveView version: 0.3.1
* NodeJS version (node -v): 12.9.1
* NPM version (npm -v): 6.11.3
* Operating system: macOS

### Actual behavior
When I pass an `assign` value from a parent LiveView to a nested child LiveView, the child LiveView does not re-mount upon value change in the parent LiveView. Here's my setup:

`parent.html.leex`
```elixir
<h1>Parent: <%= @counter %></h1>
<%= live_render(@socket, ChildLive, id: "child-live", session: %{counter: @counter}) %>
<button phx-click="inc">+</button>
```

`child.html.leex`
```elixir
<h1>Child: <%= @counter %></h1>
```

`parent_live.ex`
```elixir
def mount(_session, socket) do
  {:ok, assign(socket, :counter, 0)}
end

def handle_event("inc", _value, socket) do
  {:noreply, assign(socket, :counter, socket.assigns.counter + 1)}
end
```

`child_live.ex`
```elixir
def mount(%{counter: counter}, socket) do
  {:ok, assign_new(socket, :counter, fn -> -1 end)}
end
```

### Expected behavior

Based on e.g. #190 I would expect that the child LiveView's `mount/2` function is called whenever the parent `@counter` value changes. However, the `mount/2` function of the child is called only once during initial rendering.

**Comment by chrismccord** [comment]
Check the `live_render` docs. You need to provide a new `:id` to force a child to be respawned. Thanks!

**Comment by PJUllrich** [comment]
Thanks, Chris! That solved my problem.
Unfortunately, this isn't documented yet in the `live_render` docs, I believe. 
I will fix this with a PR later :)

**Comment by ccapndave** [comment]
I just ran into this as well - especially for people used to the React style of doing things, this is surprising.  Perhaps the documentation could be extended a bit to make this clear, with an example of propagating parent `assigns` to child `session`?
