### ISSUE TITLE
LEEx templates cannot convert HTML content in live_links

### ISSUE THREAD

**Issue by wrren** [phoenixframework/phoenix_live_view#401]
### Environment

* Elixir version (elixir -v): Elixir 1.8.0, Erlang/OTP 21
* Phoenix version (mix deps): 1.4.10
* NodeJS version (node -v): 12.10.0
* NPM version (npm -v): 6.11.3
* Operating system: MacOS Mojave

### Actual behavior

`live_link` calls in `.leex` templates with HTML content cannot be encoded correctly and the conversion process throws an error:

```
** (RuntimeError) cannot convert .leex template with change tracking to iodata
    (phoenix_live_view) lib/phoenix_live_view/engine.ex:59: Phoenix.HTML.Safe.Phoenix.LiveView.Rendered.to_iodata/1
    (phoenix_live_view) lib/phoenix_live_view/engine.ex:67: Phoenix.HTML.Safe.Phoenix.LiveView.Rendered.to_iodata/3
```

Example template:

```
<%= live_link to: Routes.live_path(@socket, PhoenixLiveViewTest.PageLive, 1) do %>
<span>Hello World</span>
<% end %>
```

### Expected behavior

It's possible to work around this issue by changing the file extension to `.eex`, which uses the standard EEx template engine, however for live views this is generally not ideal.

**Comment by josevalim** [comment]
Unfortunately I cannot reproduce the issue. Maybe you are using some assign inside the do/end block or something else? Can you please provide a way to reproduce it? Also, does this issue also happen if you use `link` instead of `live_link`? Thanks.

**Comment by chrismccord** [comment]
ping @wrren

**Comment by wrren** [comment]
I can no longer reproduce this, it was likely fixed in a more recent release. Thanks!
