### ISSUE TITLE
Live routes with different layouts don't replace the layout when a live redirect occurs

### ISSUE THREAD

**Issue by wrren** [phoenixframework/phoenix_live_view#402]
### Environment

* Elixir version (elixir -v): Elixir 1.9.0
* Phoenix version (mix deps): 1.4.10
* NodeJS version (node -v): 8.10.0
* NPM version (npm -v): 3.5.2
* Operating system: Ubuntu 18.04

### Actual behavior

When a router defines several `live` routes that specify different layouts, navigating between routes using `live_redirect` or `live_link` does not result in the layout being replaced.

Example repository: https://github.com/wrren/phoenix_live_view_issues/tree/issues/live_layout

### Expected behavior

When navigating between `live` routes with different layouts, the layout should change to the one specified by the `live` route to which the browser is navigating.

**Comment by snewcomer** [comment]
@wrren 👋 Tested out your repo.  Is this what I am supposed to be seeing?  If so, looks like it might be working alright!

<img width="887" alt="Screen Shot 2019-10-10 at 11 25 12 PM" src="https://user-images.githubusercontent.com/7374640/66628981-402fe780-ebb5-11e9-8d82-f0b471dea2d4.png">

**Comment by nocivus** [comment]
Getting the same problem. Defined this in my router:
```
live "/posts/:id/edit", Post.Edit,
        id: :id,
        layout: {NoozoxWeb.LayoutView, "admin_edit.html"}
```
and when i live navigate away, it keeps the admin_edit layout, instead of switching back to the default.

**Comment by wrren** [comment]
@snewcomer if it's working correctly you should see "This is the alternative layout" above the content rendered by the LiveView.

**Comment by snewcomer** [comment]
Ope you are right!  You are making a network request (as you may already know), which is sending back content based on the `TestLive.render/1` function and mounts a new LiveView in place of the old one.

Does it seem like a normal `plug :put_layout, :alternative` or router based `layout: LayoutView, :alternative` would suffice for this case?   For example, if we are sending down and entire HTML document and diffing/rendering + pushState, we might be better off rendering as we traditionally do on the server?  The browser might be better at that than we are (also cached version of the page + linked resources, remembering scroll position, accessibility, cancelling in flight navigation, etc)

Would love to learn more about your use case though!  If the traditional way seems like the right way to go, it might be beneficial for us to update the docs detailing this "line in the sand".

**Comment by bartblast** [comment]
Has anyone come up with a temporary solution for this problem?

**Comment by josevalim** [comment]
#565  adds support for layouts inside the LiveView, so you can move the layout there, but the root layout itself (the one with HTML head) cannot be effectively reloaded (I mean, we could, but it would introduce a bunch of pitfalls, like script tags not being unloaded or loaded twice, etc).
