### ISSUE TITLE
Combining views in layout with routed liveviews can not use live_link

### ISSUE THREAD

**Issue by Wijnand** [phoenixframework/phoenix_live_view#404]
### Environment

* Elixir version (elixir -v): Elixir 1.9.1 
* Phoenix version (mix deps): 1.4.10
* NodeJS version (node -v): v8.11.1
* NPM version (npm -v):5.6.0
* Operating system: MacOS Mojave

### Actual behavior

We include a small widget made with LiveView within a layout so we can use it on all pages.
However, if we then use a full LiveView coming from an route we can not use live_link inside that liveview (which basically for us means there is no benefit for liveview anymore). 

If we would click a link in the main view the other live view crashes with a message saying: 
`** (ArgumentError) cannot invoke handle_params/3 on MultiLiveviewBugWeb.ClockLive because it is not mounted nor accessed through the router live/3 macro`

This is not expected since there is no parent child relationship between these views, they should be able to operate on their own.

I have created a small demo app that demonstrates this bug:
https://github.com/Wijnand/multi_liveview_bug
After starting you only need to visit http://localhost:4000/data and click the "filter" links.
The timer stops refreshing and the error is in the console.

### Expected behavior
I expect the live_link to only touch the liveview it is embedded in (potentially trickling down to its children). Liveviews that are standalone should not be affected.

**Comment by josevalim** [comment]
Thanks for the report, this is a known limitation. Today only the live view given on `live` can invoke `handle_params`, it is not about parent/child. The root of the issue is that we only have one URL, so only one LiveView can be responsible for it, if we want to avoid races.

However, we are planning to address this by making any live link in a page go to the "main" view. Do you think this would solve your problems?

> After starting you only need to visit http://localhost:4000/data and click the "filter" links.
The timer stops refreshing and the error is in the console.

The page is not refreshed when there is an error? 🤔

**Comment by Wijnand** [comment]
No, there is no refresh, the liveview enters some error state. 

Your solution sounds great, only a "main" view should have knowledge about url params in my opinion. It would totally solve the issue for us.

**Comment by anatoliyarkhipov** [comment]
Not sure if that issue is related, but seems it is.

I'm trying to figure out if that possible to use `live_link` without using the `live` router macro, i.e. when LiveView is rendered via `Phoenix.LiveView.Controller.live_render`? It seems it's not possible, and LiveView `live_link` points to must be routed via `live`, but I can't find a place in the docs where it's explicitly stated and so I'm wondering if it's me doing something wrong or it's actually not possible? 🤔

When I try to `live_link` to a LiveView rendered from a controller, I a similar error from the OP post:
```
** (ArgumentError) cannot invoke handle_params/3 on MyAppWeb.ProjectEditorLive because it is not mounted nor accessed through the router live/3 macro
```

**Comment by josevalim** [comment]
@anatoliyarkhipov when you call `live_render`, you should pass the option `router: NameOfTheRouter` to the LiveView. This would make the view capable of handling `live_link` and `live_redirect` as long as it is the only live view on the page. Live links/redirects with multiple views will be supported one we address this bug.

**Comment by LostKobrakai** [comment]
> But it seems impossible when using the live macro - to pass anything to the template during the first rendering, the first opportunity to assign something appears during the mounting stage. 

@anatoliyarkhipov That's what `assign_new` is for. It uses the data of `conn.assigns` on static render if available and for any websocket mount it uses the function to retrieve the content.

**Comment by chrismccord** [comment]
Also note that mount is called during the original HTTP request, *and* after WebSocket connect, so the initial mount still happens within the HTTP pipeline, thus you can achieve the same data fetching as you are performing in your controller.

**Comment by Wijnand** [comment]
> However, we are planning to address this by making any live link in a page go to the "main" view. Do you think this would solve your problems?

This is in no way an attempt to put pressure on you but I need to make a decision for our current development work. Is there an ETA for this? Is it something that has a high priority or not? 

Knowing this helps me a lot in determining what route to take for an upcoming feature in our product. I would love to use liveview for this but only if it makes sense to do so :-D

**Comment by josevalim** [comment]
@Wijnand I can tell you how to implement it and you can take matter into your hands? :)

1. The first change is to add a data-phx-main=true attribute if the [router here](https://github.com/phoenixframework/phoenix_live_view/blob/master/lib/phoenix_live_view/view.ex#L353) is not nil

2. Then you will go to the phoenix_live_view.js and find the part that dispatches live links and you will make sure the live link will trigger on the LiveView with the [data-phx-main] attribute

That should be all. :)

**Comment by Wijnand** [comment]
That is awesome! Thank you Jose. I will work on it.

**Comment by silverdr** [comment]
> you should pass the option `router: NameOfTheRouter` to the LiveView. This would make the view capable of handling `live_link` and `live_redirect` as long as it is the only live view on the page

The `router:` option is absent from the list of options at

https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.Helpers.html#live_render/3-options

so I take it's been removed as obsolete, right?

**Comment by josevalim** [comment]
I think it is still supported but maybe not documented?

**Comment by chrismccord** [comment]
Live navigation is only supported by LiveViews declared in `live` routes in the router
