### ISSUE TITLE
Autofocus doesn't put cursor at the end

### ISSUE THREAD

**Issue by kuon** [phoenixframework/phoenix_live_view#407]
I have the following text input

```
<%= f = form_for @changeset, "#",
        [class: "justify-start",
         phx_submit: "save"] %>

<%=
text_input f, :name,
  autocomplete: "off",
  autofocus: true,
  class: 'fld block',
  placeholder: "nom"
%>
```

### Actual behavior

When the page loads, the field has focus, but the cursor is at the start of the text field.

### Expected behavior

The field should be focused with the cursor at the end of the text field.

### Versions

I use firefox dev edition 70, and live view commit f9b6b8b

**Comment by hurty** [comment]
@kuon I think LV currently relies on the brower's built-in "autofocus". I ended up with this kind of hook to handle input focus with the cursor at the end:

```js
let Hooks = {};
Hooks.AutoFocus = {
  mounted() {
    // Force focus at the end of input
    if (
      this.el.tagName == "INPUT" &&
      (this.el.type == "text" || this.el.type == "password")
    ) {
      let val = this.el.value;
      this.el.value = " ";
      this.el.value = val;
    }
    this.el.focus();
  }
};
let liveSocket = new LiveSocket("/live", { hooks: Hooks });
```

```elixir
<%= text_input form, :title, phx_hook: "AutoFocus" %>
```

**Comment by snewcomer** [comment]
@kuon @hurty Is the scenario you are referring to - if the input has a primitive value, the cursor should be at the end of it?  If so, I can look into this and see if it is something we want to support out of the box.

**Comment by hurty** [comment]
@snewcomer Yes, I think this is the most appropriate behaviour and devs will frequently need it when dealing with forms (when the page loads but also when a input appears or after a click somewhere else)

And even if an input has no value, the focus should be consistent accros browsers. It's been a while but the last time I checked the native `autofocus` attribute behaviour is too eratic :

- Chrome: works for the first input appearance, but not for the other subsequent inputs. The cursor is at the beginning of text.
- Firefox: doesn’t work at all (but according to @kuon it works recently when the page loads),
- MacOS Safari : works for each input, the input is focused but all the text inside is selected,
- iOS Safari: the input is focused, but the text is not selected and the keyboard isn’t shown.

**Comment by kuon** [comment]
Browser autofocus is broken, it's a pain to work with. And in fact, autofocus is not a single use case. Depending on the context, you might put the cursor at the start or end, you might select or not select the content.

In fact, the cursor position and selection is not limited to auto focus, but also applies to user focus. For example, when I focus a search field, either by autofocus or clicking or tabing to it, I usually want the content selected, which let me either type to replace the search, or use right or left arrow to extend the search.

Cursor position and selection is very app specific, even if 90% of the time it will be unselected with cursor at the end.

Knowing the complexity of required workarounds to get this working properly, I suggest LV integrates support for this by default.

The ideal API would be something like:

`phx_autofocus: true, phx_focus_hook: "myfunc"`

a few defaults for `myfunc` would be provided, like start, end, select

```
myfunc(fieldContentAsString) {
  // defaults with alias
  return 0 // cursor at start, alias to "start"
  return -1 // cursor at end, alias to "end"
  return [0, -1] // everything selected, alias to "select"

  return n // cursor at index n
  return [0, fieldContentAsString.length / 2] // half of it selected 
}
``` 

`phx_autofocus` would sanely focus the field once mounting and rendering is completed
`phx_focus_hook` would run on every focus (auto or user event)

**Comment by chrismccord** [comment]
> Knowing the complexity of required workarounds to get this working properly, I suggest LV integrates support for this by default.

Given the complexity in usecases that you highlighted, as well as browsers all treating `autofocus` differently, this is best up to the user today via a hook. This would be a great little JS lib in fact that others LV users could take advantage of (nudge nudge :)
