### ISSUE TITLE
Incorrect example in docs for mount/2

### ISSUE THREAD

**Issue by wmnnd** [phoenixframework/phoenix_live_view#408]
Hey there,

the [docs for `mount/2`](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#module-example) seem to suggest that the callback can return either `{:ok, socket}` or `{:error, term}`:
```elixir
 def mount(%{id: id, current_user_id: user_id}, socket) do
    case Thermostat.get_user_reading(user_id, id) do
      {:ok, temperature} ->
        {:ok, assign(socket, :temperature, temperature)}

      {:error, reason} ->
        {:error, reason}
    end
  end
```

But if you do return an error tuple, LiveView throws an argument error.
This is due to the pattern matching on the mount callback in `lib/phoenix_live_view/view.ex`: https://github.com/phoenixframework/phoenix_live_view/blob/master/lib/phoenix_live_view/view.ex#L520

### Expected behavior
I’m not sure what the expected behavior should be. It seems to me, however, that it might be good if it was possible to reject establishing a LiveView in the mount callback (e. g. after performing a permissions check).

**Comment by snewcomer** [comment]
@wmnnd Does this recent [change](https://github.com/phoenixframework/phoenix_live_view/blame/2634b0506e47ec415c97ff253ad88abcabe0781f/lib/phoenix_live_view.ex#L945) help?  Has not been published in a release yet...Or are you asking for another `case` statement in `view.ex`?  I think you are asking for the latter.
