### ISSUE TITLE
Compiler warning with function call in if block inside of a for comprehension

### ISSUE THREAD

**Issue by sparta-developers** [phoenixframework/phoenix_live_view#409]
In a `.leex` template loaded from a live view controller, when we call a call a function inside of an if block inside of a for comprehension, we receive the following compiler warning:

```
warning: this clause cannot match because of different types/sizes
```

We have created a reproduction case in the following git repo: https://github.com/sparta-science/live_view_warning_reproduction_case.

This seems to have been introduced between `e4c6f7140d5b8c383e584671a63c14e85e9c26e9` and `05c00391aac7d74bebea85ea1be69d7831eb3200`, though we have not been able to determine the root cause.

### Environment

* Elixir version (elixir -v): 1.9.1
* Phoenix version (mix deps): 1.4.10
* NodeJS version (node -v): 10.16.0
* NPM version (npm -v): 6.11.3
* Operating system: macOS 10.14.6

### Actual behavior

This specific combination of nesting seems to cause the problem: `for -> if -> fn`. We've tried other combinations, but were only able to cause the compiler warning with this specific setup.

### Expected behavior

This should not cause a compiler warning.

**Comment by josevalim** [comment]
Thank you @sparta-developers! Providing a repo that reproduces the issue makes our lives much easier, so we will take a look at it soon!

**Comment by josevalim** [comment]
Oops, I forgot to comment, but this has been fixed. :)
