### ISSUE TITLE
stateful live_component @inner_content events are sent to wrong component

### ISSUE THREAD

**Issue by hypno2000** [phoenixframework/phoenix_live_view#414]
stateful `live_component` do block `@inner_component` events are sent to the component that calls `@inner_component` rather to the component that defined the events.

```elixir
defmodule DemoWeb.HeroLive do
  use Phoenix.LiveComponent

  def render(assigns) do
    ~L"""
    <section class="phx-hero">
      <h2><%= @title %></h2>
      <button phx-click="doit"><%= @button_text %></button>
      <%= @inner_content.([]) %>
    </section>
    """
  end

  def mount(socket) do
    {:ok, assign(socket, :button_text, "Hero Button")}
  end

  def handle_event("doit", _, socket) do
    {:noreply, assign(socket, :button_text, "Expected and works!")}
  end

  # events triggered in @inner_content should not be sent here
  def handle_event("inc", _, socket) do
    {:noreply, assign(socket, :button_text, "Not expected, wrong component!")}
  end
end

defmodule DemoWeb.ComponentLive do
  use Phoenix.LiveView

  def render(assigns) do
    ~L"""
    <%= live_component @socket, DemoWeb.HeroLive, id: 1, title: "Counter" do %>
      <div><%= @counter %></div>
      <button phx-click="inc">Inc</button>
    <% end %>
    """
  end

  def mount(_session, socket) do
    {:ok, socket |> assign(:counter, 0)}
  end

  def handle_event("inc", _, socket) do
    {:noreply, update(socket, :counter, &(&1 + 1))}
  end
end
```

### Actual behavior

Events triggered by `ComponentLive` `phx-click="inc"` are sent to `HeroLive`

### Expected behavior

Events triggered by `ComponentLive` `phx-click="inc"` are sent to `ComponentLive`

### Environment
Elixir version (elixir -v):
Erlang/OTP 22 [erts-10.5] [source] [64-bit] [smp:20:20] [ds:20:20:10] [async-threads:1] [hipe] [dtrace]
Elixir 1.9.1 (compiled with Erlang/OTP 22)
Phoenix version (mix deps): 1.4.9
Phoenix LiveView version (mix deps): current master (3a320ee)
NodeJS version (node -v): 10.16.0
NPM version (npm -v): 6.11.3
Operating system: macOS Mojave 10.14.6

Demonstration of this issue can be seen by cloning and running https://github.com/hypno2000/phoenix_live_view_example and visiting http://0.0.0.0:4000/component_events

**Comment by josevalim** [comment]
@hypno2000 good point. Perhaps the wait to solve this is to add a phx-target that controls who is the target of certain events. Unfortunately I do not think we can make it just work. (OR we could actually make it just work as long as we add a restriction we cannot have no text element in the do/end block).

Btw @hypno2000, can you do me a favor? Can you check if a `live_link` pointing to the same LiveView but inside a component (or inside the do/end block) just works or not? If you feel generous, please check `live_link` to another LiveView too. Thank you!

**Comment by hypno2000** [comment]
All of the `live_link` scenarios seem to work as expected.

https://github.com/hypno2000/phoenix_live_view_example/blob/master/lib/demo_web/live/component_links.ex

**Comment by josevalim** [comment]
>  That is assuming handle_params should be called from LiveView, not from a component.

The assumption is correct. I will document this behaviour. Thanks for verifying!

**Comment by josevalim** [comment]
We are going to address this by requiring events that go to components to have a specific annotation.

**Comment by josevalim** [comment]
Fix in master with phx-target addition.
