### ISSUE TITLE
Mouse events

### ISSUE THREAD

**Issue by mwillema** [phoenixframework/phoenix_live_view#417]
Hi,

Is there a way to send an event when the mouse is over a link for instance? Like phx-focus and phx-blur but applied to the mouse and links.

Thx

**Comment by snewcomer** [comment]
@mwillema would be great to hear your use case.  My initial feeling is there is a fine line between what to delegate to Elixir and what can be handled with JS/CSS.

**Comment by kuon** [comment]
I think for complex desktop app, like dataviz, there are legitimate use cases where moving the mouse around can changes the page content significantly (triggering data fetch). But I would be more interested in `mouseenter` and `mouseleave`.

Maybe one option would be to give a clear API for calling phoenix functions from javascript. Like the hook `pushEvent` but outside hooks. I know we can call it directly on the `LiveSocket` we create in JS, but maybe a clearly documented public JS API would help.

**Comment by chrismccord** [comment]
The rule is you should do as much via css as possible, where possible. Failing that, `phx-hook` is there for you to wire up hover events and react accordingly. Thanks!
