### ISSUE TITLE
Dynamic Select option unselectable

### ISSUE THREAD

**Issue by ityonemo** [phoenixframework/phoenix_live_view#418]
### Environment

* Elixir version (elixir -v): Erlang/OTP 22 Elixir 1.9.1/OTP 21
* Phoenix version (mix deps): phoenix_live_view 0.3.1 / phoenix 1.4.10
* NodeJS version (node -v): v10.16.3
* NPM version (npm -v): 6.9.0
* Operating system: Linux 4.15.0-54-generic #58-Ubuntu SMP

### Actual behavior

Sometimes when there is a server-side generated options list inside of a select field, options besides the first become unselectable, as selecting it reverts the choice to the top option in the select list.

This is reproducible between firefox/Linux and chromium/Linux

### Expected behavior

the options list should be stable.

### rough setup, not minimized yet

```
<form ...>
  <select ...>
    <%= for opt <- dynamic_opts(@data) %>
       <option value="<%= opt %>"><%= opt %></option>
    <% end %>
  </select>
</form>
```

To reproduce this behavior, one of the dynamic options must disappear then reappear.  There is no alphabetical dependency on this issue.

### etc

At the moment the example I have is coupled to the current backend I'm working on, but I will attempt to reproduce this in a minimized form over the weekend.

**Comment by snewcomer** [comment]
@ityonemo Thank you.  I could help you tackle and propose a solution if you had a reproduction of the issue!

**Comment by ityonemo** [comment]
ok, so I looked at it and it appears that I'm not handling Presence join/leave messages in a way that plays nice with liveview!  Will provisionally close this unless something else seems to come up.
