### ISSUE TITLE
Selects in form don't update with returning changeset

### ISSUE THREAD

**Issue by Kaquadu** [phoenixframework/phoenix_live_view#420]
Hi,
as the title says I've got a problem with select tags in forms. I'm currently implementing search with filters using Live View. The way I figured it out is:
- having an embedded schema containing all the search fields, which is responsible also for validations (eg. checks if the min_price > max_price)
- having an Live View event handler, which is responsible for catching `search` event, preparing query based on changeset, and sending back response with found entities
- to clear filters I am using separate Live View events:
   1.  To clear all the filters - It just sends back empty changeset
   2. Individual field clear - it puts a change into changeset, according to which filter is being cleared

### Environment

* Elixir version (elixir -v): 1.9.0
* Phoenix version (mix deps): 1.4.1
* Live View version: 0.3.1
* NodeJS version (node -v): 12.6.0
* NPM version (npm -v): 6.11.2
* Operating system: MacOS Mojave 10.14.6

### Actual behaviour

The first problem was that the select tags, which belong to the form inside a Live View, are disappearing after an `phx_submit` event. I mean if you pick one select, and leave other one as default, it will sometimes somehow disappear after Live View reload.

Here Is what happend exactly (copied from my post on ElixirForum
https://elixirforum.com/t/disappearing-selects-in-form-liveview/25776)
1. I choose any not default option from first select, leaving second select default -> I submit my search form to LiveView -> On the reloaded screen with new entries I choose again default option for first select, leaving second select default -> I submit my search form to LiveView -> Second select disappears
2. I choose any not default option from second select, leaving first select default -> I submit my search form to LiveView -> On the reloaded screen with new entries I choose again default option for second select, leaving first select default -> I submit my search form to LiveView -> First select disappears
3. I choose any not default options from both selects -> I submit my search form to LiveView -> I clear fields submitting clear event to LiveView -> I submit my search form with default values of first and second select to LiveView -> Both selects disappear

By saying disappear I really mean disappear - in elements inside chrome developer tools a place, where selector should be, is just empty.

I managed to put a `hidden_input`s before them, which have the same names as selects. That prevented disappearing, which was kinda strange and I came across this solution just by accident and well, looks dirty for me. Code shown below:
```
<%= hidden_input f, :rent_type, class: "js-adverts-rent-type" %>
<%= hidden_input f, :rooms_number_min, class: "js-adverts-rooms-number-min" %>

<div class="form-group col-md-3 main-search__form-group">
  <%= label f, :rent_type, gettext("Type"), class: "main-search__form-label" %>
  <%= select f, :rent_type, [[key: gettext("choose"), value: ""]] ++ @rent_types,
      class: "form-control main-search__form-input main-search__form-input--select" %>
  <%= error_tag f, :rent_type %>
</div>

<div class="form-group col-md-3 main-search__form-group">
  <%= label f, :rooms_number_min, gettext("Rooms"), class: "main-search__form-label" %>
  <%= select f, :rooms_number_min, [[key: gettext("choose"), value: ""]] ++ @room_options, class: "form-control main-search__form-input main-search__form-input--select",
    phx_hook: "RoomsSelector" %>
  <%= error_tag f, :rooms_number_min %>
</div>
```

The problem occurs now when I'm trying to clear an individual filter. Clearing all filters works fine (which is even stranger). The changeset, which is updated (checked, it really is correct) and sent back to the template, doesn't update selected option in select tag (in this my case I want it to pick a default option).

I tried to find a workaround using JavaScript and this is where things became really strange. There is just no way to update select tag, which belongs to a form inside a Live View. I really tried many combinations and ways. I used pure JS and jQuery. 

After an Live View update I used hooks and I found a behaviour that is probably a cause of the problem. I've got a hook defined as show below.
```
defineRoomsSelectorHook() {
    this.Hooks.RoomsSelector = {
      mounted() {
        console.log("Mounted r");
      },
      updated() {
        console.log("Updated r");
      },
      destroyed() {
        console.log("Destroyed r");
      }
    }
  },
```
The select tag behaves as it would always be mounted, never updated. No matter what happens. I'm gettings only `Mounted r` messages in my console, even when I'm excepting it to update. Same implemented hook, but for simple number input works as I except it to work.

### Expected behaviour

I wan't a selects to be updated to the state, which is determinated by changeset. Changeset is sent as response to the `phx_submit` event.

**Comment by snewcomer** [comment]
@Kaquadu I've read through your issue and in order to come up with a solution, I think I need a reproduction in order to help.  

Also, note this issue and see if any of the comments help!
https://github.com/phoenixframework/phoenix_live_view/issues/160

**Comment by chrismccord** [comment]
As Scott said, we really need a minimal example which reproduces the problem, as there is a lot going on here to try to unpack/guess where your issue may be. If you are able to extract an app which reproduces the issue, we'd be glad to take a look. Thanks!
