### ISSUE TITLE
liveSocket set connect params not working as advertised

### ISSUE THREAD

**Issue by i-n-g-m-a-r** [phoenixframework/phoenix_live_view#422]
### Environment

* Elixir version (elixir -v):
Erlang/OTP 22 [erts-10.5.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
Elixir 1.9.2 (compiled with Erlang/OTP 21)

* Phoenix version (mix deps):
phoenix_pubsub 1.1.2
phoenix_html 2.13.3
phoenix 1.4.10
phoenix_live_view 0.3.1
phoenix_live_reload 1.2.1

* NodeJS version (node -v):
v8.10.0

* NPM version (npm -v):
3.5.2

* Operating system:
Ubuntu 18.04.3 LTS

### Using this code in js
```
// note: same issue for hooks
let liveSocket = new LiveSocket("/live", Socket, {params: {foo: "bar"}})
```

### Actual behavior
```
get_connect_params(socket) == %{}
```

### Expected behavior
```
get_connect_params(socket) == %{"foo" => "bar"}
```

### This works though:
```
let liveSocket = new LiveSocket("/live")

liveSocket.params = function() {
  return {foo: "bar"}  
}

liveSocket.hooks = { ... }
```

**Comment by i-n-g-m-a-r** [comment]
Naively updating dependencies causes confusion.
As far as phoenix_live_view is concerned, this fixes the problem.
```
$ rm -rf assets/node_modules/phoenix_live_view
$ npm install --prefix assets
```

**Comment by snewcomer** [comment]
@i-n-g-m-a-r What lifecycle event are you accessing the `connect_params`?  My belief is that the `params` are dropped after mount.  I'd have to confirm the reason for this though...

**Comment by i-n-g-m-a-r** [comment]
In my LiveView module I use the mount/2 function like so:
```
def mount(%{"custom_param" => custom}, socket) do
  case get_connect_params(socket) do
    %{"timezone" => timezone} ->
      # connected, setup interface
      mounted(custom, timezone, socket)
    _ ->
      # not ready
      {:ok, assign(socket, tpl: "loading.html")}
  end
end
```
Then in the mounted/3 function I assign stuff to the socket,
including mount parameters and connect parameters.
So computer says no when connect params are empty.
(actually I also use Process.send_after to stop "loading")

In my "app.js" I pass in the timezone like so:
```
let liveSocket = new LiveSocket("/live", Socket, {
  params: {
    timezone: get_timezone() // using Intl
  }  
})
liveSocket.connect()
```

The issue I created was about how to pass in the params.
I had to hack around because I didn't think about updating assets too.
A startup message would be nice, come to think of it.
