### ISSUE TITLE
Delaying events

### ISSUE THREAD

**Issue by kuon** [phoenixframework/phoenix_live_view#425]
This is not strictly a bug report, but it's not really a feature request either, I hope here is OK to discuss it.

In my app, for text field dropdowns, I usually use something like this:

```eex
            <%= text_input :document, :schema,
                phx_keyup: "suggest_schema",
                phx_focus: "suggest_schema",
                phx_blur: "hide_schema_suggestions",
                tabindex: 100, autocomplete: "off" %>
            <ul class="dropdown">
              <%= case @schema_suggestions do %>
              <% nil -> %>
              <% [] -> %>
                <li class="font-bold">Aucun résultat</li>
              <% a -> %>
                <%= for s <- a do %>
                  <li phx-click="select_schema"
                      phx-value-schema="<%= s.id %>">
                    <%= s.display_name %>
                  </li>
                <% end %>
              <% end %>
            </ul>

```

The problem with this kind of setup, is that the blur event is fired before the click event of the list item.

One solution would be to add a `phx-blur-delay` on the text input, to allow the click on the list item to get through before the blur event handler is fired.

I don't know if you have other suggestions, the delay thing feels like a hack.

**Comment by snewcomer** [comment]
👋 Events are ran in the order which they are registered, which at the moment are globally with `window.addEventListener`.  This is a problem we need to solve as it doesn't follow how event listeners and the DOM were intended to be handled.  I'm putting together some thoughts on how we can handle this properly.  Appreciate you putting this issue together!

**Comment by kuon** [comment]
Well, ordering events is hard to get right, but I guess sorting them by types could be a start.

I think of something like this (from first processed to last processed):

- click
- keydown
- keyup
- submit
- focus
- blur

When the DOM event fires, a phoenix event is queued and in the next event loop (`requestAnimationFrame`) event are sorted and processed in order, with one frame between thems.

I am not intimate on how live view processes the events, my apologies if this is a bad idea.

Like this: (written in the issue, a rough idea)

```js
let events = {click:[], keydown:[], ...}

window.addEventListener(click, ...., (event) => {
   events.click.push({level: event.composedPath().length})
   requestEventLoop()
}) 


let requested = false
function requestEventLoop() {
  if (requested) return

  requested = true
  requestAnimationFrame(stackEvents)
}

function sort(events) {
  events.sort((a, b) => b.level - a.level)
}

let eventStack = []
function stackEvents() {
  requested = false
  // magick sorting of events, by type and then by nesting level, to have chilldren
  // ran before their parents
  // this could be much fancier than just using composedPath().length
  eventStack = eventStack.concat(sort(events.click), sort(events.keydown), ...) 
  events ={click:[], keydown:[], ...}
  requestAnimationFrame(processEvents)
}

let processingEvents = false
function processEvents() {
  if (processingEvents || eventStack.length === 0) return
  processingEvents = true
  
  let event = eventStack.shift()

  // here do something with the events, the usual phoenix thing

  if (eventStack.length > 0) requestAnimationFrame(processEvents)
  
  processingEvents = false
}
```

I think in most scenarios, the delay would be 2 or 3 frames, which shouldn't be an issue.

This help in a few common use cases:

- removing dropdown on blur, processing events inside the dropdown before removing it (my usecase), this can be extended to things like tooltip with links in them and other contextual form things, like calendar pickers.
- this let the native JS run before, which gives the liberty to the JS custom code to do things before live view, this helps use existing librairies, like form helpers that format inputs.
- when a child and the parent have the same type of event bound, this runs the child properly before the parent

**Comment by kuon** [comment]
Just for info, my current workaround for the dropdown thing is:

In my template:

```eex
<li phx-click="select_schema" phx-value-schema="<%= s.id %>">
```

to
```eex
 <li onmousedown="selectSchema('<%= s.id %>')">
```

And my `selectSchema` function:

```js
function selectSchema(id) {
  liveSocket.
   views[liveSocket.root.id].
   pushWithReply('event', {type: 'form', event: 'select_schema', value: 'schema='+id})
}
```

It is dirty, but it works for now, until we have a saner way to do it.

**Comment by chrismccord** [comment]
Note: pushWithReply is a private API and should not be used. You should use the phx-hook interface instead

**Comment by chrismccord** [comment]
It makes sense to me that the blur event in this case would fire before the click event, as the field necessarily blurs when you focus another element. We will evaluate some options for finer control, but the current solution, and perhaps best solution long term, is to use a phx-hook and wire up the bindings + `pushEvent`'s yourself for this specific usecase. Thanks!

**Comment by kuon** [comment]
Well, adding phx-mousedown would kinda solve the issue without any hack.
-- 
Nicolas Goy

**Comment by chrismccord** [comment]
Add a hook and using pushEvent would also solve this issue for you without any hacks :)

**Comment by kuon** [comment]
You mean use phx-hook on an element that has no phx-xxx on it? I did not realize that would be possible. 
-- 
Nicolas Goy

**Comment by chrismccord** [comment]
Correct. *any* DOM element inside a LV container is hookable, and phx- bindings are not a prereq

**Comment by kuon** [comment]
Aaaah, I understand you other comments way better now.

I realize that the example in the doc has no other phx-xxx on it, but maybe more emphasis could be put on it.

Just adding a paragraph under JS interop with: A hook can be added to any LV element rendered by LV...

I read the doc ten times and did not realize that, and it seems an important feature to be familiar with.

With this, the other issues seems way easier to handle. I will post solutions with hook in other issues.


-- 
Nicolas Goy

**Comment by kuon** [comment]
For reference, here is the solution I used, which should be supported by live view:

EEX template

```eex
                <ul class="dropdown" phx-hook="dropdown">
                  <%= for s <- schemas do %>
                    <li phx-hook="on"
                        on="mousedown"
                        on-event="select_schema"
                        on-data-schema="<%= s.id %>"
                        id="shema-suggestion-<%= s.id %>">
                      <%= s.display_name %>
                    </li>
                  <% end %>
                </ul>

```

JS Hook:

```js
Hooks.on = {
  mounted() {
    this.eventListener = () => this.onEvent()
    this.eventName = this.el.getAttribute('on')
    this.el.addEventListener(this.eventName, this.eventListener)
  },
  destroyed() {
    this.el.removeEventListener(this.eventName, this.eventListener)
  },

  onEvent() {
    let phxEvent = this.el.getAttribute('on-event')
    let params = {}

    let attrs = this.el.attributes
    for (let i = 0; i < attrs.length; i++) {
      let attr = attrs[i]
      let name = attr.name
      let value = attr.value

      let prefix = 'on-data-'
      if (name.substring(0, prefix.length) === prefix) {
        let paramName = name.substring(prefix.length)
        params[paramName] = value
      }
    }
    this.pushEvent(phxEvent, params)
  }
}

```
