### ISSUE TITLE
Wrong documentation

### ISSUE THREAD

**Issue by phpcitizen** [phoenixframework/phoenix_live_view#426]
**[https://github.com/phoenixframework/phoenix_live_view]() documentation shows for master git repository, but in the beginning it has:**

```elixir

def deps do
  [
    {:phoenix_live_view, "~> 0.3.0"},
    {:floki, ">= 0.0.0", only: :test}
  ]
end

```
**Below (_live_component_) does not work for above setting:**
```elixir

def view do
  quote do
    ...
    import Phoenix.LiveView,
      only: [live_render: 2, live_render: 3, live_link: 1, live_link: 2,
             live_component: 2, live_component: 3, live_component: 4]
  end
end
```

**Comment by snewcomer** [comment]
@phpcitizen Until a new release is published with `live_component`, you can point to a commit sha or master!

https://hexdocs.pm/mix/Mix.Tasks.Deps.html#module-git-options-git

```js
{:phoenix_live_view, git: "git@github.com:phoenixframework/phoenix_live_view.git", branch: "master"}
```

**Comment by ityonemo** [comment]
can you include the release's readme as a part of the hexdocs (and maybe also point the readme to hexdocs for versioned installation guides?)  This tripped me up for a hot sec just now.

**Comment by phpcitizen** [comment]
@snewcomer 
I am talking about this documentation:
https://github.com/phoenixframework/phoenix_live_view

There is a conflict between the start and the end as I mentioned. This can be rectified easily without confusing newcomers.

**Comment by PragTob** [comment]
README's on github usually reflect the status on master. Including the README in docs might be nice.

Here is a link to the README at the state of the last release: https://github.com/phoenixframework/phoenix_live_view/tree/v0.3.1

**Comment by DarkMarmot** [comment]
I agree with @ityonemo -- adding the installation instructions that match the current hex version to the hex documentation is a good move. I also encountered this issue.

**Comment by chrismccord** [comment]
master always reflects the actively developed, unreleased branch. Thanks!
