### ISSUE TITLE
dblclick binding

### ISSUE THREAD

**Issue by amencarini** [phoenixframework/phoenix_live_view#427]
I needed a double-click binding on an element and ended up using a hook for it, but I was wondering what your view is on adding a `phx-double-click` binding. Happy to work on a PR if you think it might be a good addition!

**Comment by snewcomer** [comment]
@amencarini Appreciate the input!  Yes `hooks` are a good spot for them atm.  As we are under active development and "how and why" we do things may change, I'll make sure to put this on the back burner.

Just curious, what does your use case look like?  I think this could be a great spot for the examples [repo](https://github.com/chrismccord/phoenix_live_view_example) in the meantime so others could take from your work.

**Comment by amencarini** [comment]
No real use case, I am writing a tutorial on how to recreate the TodoMVC with LiveView 😆 I'll try to submit an example next week!
