### ISSUE TITLE
Modal Issues With Live View Forms

### ISSUE THREAD

**Issue by tobyjr** [phoenixframework/phoenix_live_view#432]
Forms, or elements with phx-click don't appear to work within modals. The usual button doesn't execute phx_submit.

I have also tried to submit the form via jquery - $('#tag-form').submit()

However this just tries to send the standard non live view form.

I don't seem to be able to find a way to $('#tag-form').phx_submit() or $('#save_tag').phx_click();

Just to confirm these actions work perfectly for me when not within a modal.

```
`<div class="ui modal" id="tag_modal">
  <i class="close icon"></i>
  <div class="header">
    Create Tag
  </div>
  <div class="content">
    <p>phx-click doesn't appear to work within a modal</p>

    <div phx-click="save_tag" onclick="" phx-value-tag="Some Tag" class="ui button primary" id="save_tag">Formless Save</div>

    <%= f = form_for :tag, "#", [phx_change: :validate, phx_submit: :save, class: "ui form validate", id: "tag-form"] %>
        <div class="field">
          <%= label f, :name %>
          <%= text_input f, :name %>
          <%= error_tag f, :name %>
          <%= submit "Save", phx_disable_with: "Saving...", class: "ui primary button", id: "tag_submit" %>
        </div>
    </form>        

  </div>
 
</div>`
```

**Comment by chrismccord** [comment]
Ensure you are rendering the hidden modal markup within your LiveView container. If you can provide a full working example template + LV module which demonstrates the issue we can say more, but at the moment we don't have enough details. Thanks!

**Comment by tobyjr** [comment]
I have created a shell phoenix app to show the issue. 

The app works for the non modal form, but not the modal version. Instructions are within the README on git.

https://github.com/tobyjr/modal

**Comment by snewcomer** [comment]
Looks like a jquery dependency is rendering the modal outside of the live container.  As a result, when the form submits, we look for that "live view" that holds some critical information.

Modals and rendering content outside the regular HTML flow is a common scenario and presents an interesting problem.  We could technically find this for you.  We would just need to modify the logic.

**Comment by tobyjr** [comment]
Awesome, thanks for the info. I've tried with a pure javascript approach, and everything now works.

Thanks for your help.

**Comment by MeterSoft** [comment]
@snewcomer  any solution for this?
