### ISSUE TITLE
Add installation (the README) instructions to hex.pm docs

### ISSUE THREAD

**Issue by DarkMarmot** [phoenixframework/phoenix_live_view#433]
From possible confusion on issue #426:

It would be nice if the README page were bundled in the Hex.pm exdoc release. Currently, people go from the hex.pm page to the github page readme to perform an install -- and it fails.

This hit another of my coworkers as well (unless we're missing something in the docs).

**Comment by chrismccord** [comment]
Can you send a PR? Thanks!

**Comment by DarkMarmot** [comment]
will do thanks!
