### ISSUE TITLE
Video doesn't show on mobile IOS when opened after live view change

### ISSUE THREAD

**Issue by mcade** [phoenixframework/phoenix_live_view#436]
### Environment

* Elixir version (elixir -v): 1.9.1
* Phoenix version (mix deps): 1.4.10
* NodeJS version (node -v): v10.15.2
* NPM version (npm -v): 6.4.1
* Operating system: IOS 11.4
* Browsers: Chrome + Safari

### Actual behavior

In my template `video.html.leex` when I conditionally show a video based on updating a socket value, on iPhone the video doesn't show. I've created a sample repo. [Here is a link to the repo with the bug](https://github.com/mcade/LiveViewVideo/tree/0f71de104e300f34344f1d884e6deffe87ae0a6a). 

The offending files

`video.ex`
```
defmodule MyAppWeb.PageLive.Video do
  use Phoenix.LiveView

  def render(assigns) do
    MyAppWeb.PageView.render("video.html", assigns)
  end

  def mount(_, socket) do
    {:ok, assign(socket, show_video: false)}
  end

  def handle_event("show-video", _, socket) do
    {:noreply, assign(socket, show_video: true)}
  end
end
```
`video.html.leex`
```
<h1>Live View Video Page</h1>

<button phx-click="show-video">show video</button>
<%= if @show_video do %>
  <video autoplay loop muted playsinline controls src="https://www.w3schools.com/tags/movie.mp4">
	Your browser does not support the video tag.
  </video>
<% end %>
```

### Expected behavior

The video should not have any trouble being displayed or played on iPhone. This was only an issue after I updated from an [older version](https://github.com/phoenixframework/phoenix_live_view/commit/957b7ebfb66034cb093a81d991c044f7e532aa5d) of live view. In the sample repo, if I [revert to using the older version of live view](https://github.com/mcade/LiveViewVideo/tree/37ce93efa0c7646744901a126e225fce397ca5ae), everything works fine, the video loads and shows on iPhone.

If I enable the controls attribute on the video element I can see the controls on the DOM, but the video isn't loaded at all until after I push play. And even then, the video does not show until after I press the "expand video to full screen" button.

**Edit**
After some digging, [here](https://github.com/phoenixframework/phoenix_live_view/commit/8a3db391c239bc6f951043e91f0ecd417c917219) is the exact live view commit where the behavior of not seeing videos starts. Using any commit prior to this one works as expected.

**Comment by snewcomer** [comment]
@mcade How are you reproducing in development?  If I do this in a simulator, it works.  If there is something wrong with iOS and clicks, take a look at this PR and issue.  It looks like you put it on a button, which is an intractable element

https://github.com/phoenixframework/phoenix_live_view/issues/168
https://github.com/phoenixframework/phoenix_live_view/pull/261

**Comment by snewcomer** [comment]
@mcade Also, I noticed in your repo that an error may have slipped by you.  The `LiveSocket` constructor changed and should look like below.  Perhaps this was causing the error past this [change](https://github.com/phoenixframework/phoenix_live_view/blob/d74245368fe34686e7c35b3a646d432a83ed50ea/CHANGELOG.md#020-2019-09-12) on 2019-09-12.

```js
import LiveSocket from "phoenix_live_view"
import {Socket} from "phoenix"

let liveSocket = new LiveSocket("/live", Socket)
liveSocket.connect()
```

**Comment by mcade** [comment]
There are multiple commits in the sample repo, one with the new constructor style and one with the old. I just tried using a different iPhone and it seems to be working so it must be something specific to my phone. Closing for now. Thanks for taking a look.

**Comment by rozap** [comment]
@mcade did you ever figure out what was going on here? I'm running into the same thing, but also in Chrome for Android. When putting a `video` element on the page with a base64 encoded source, it works fine on initial load, but when live view puts the element there, it is blank, with no console errors. I diffed the elements from initial load and LV update, and they're identical. So I'm not sure LV is in the wrong here - the element contents are correct. But the fact remains that the video doesn't work. 

Chrome/Firefox for Ubuntu: works
Chrome/Firefox/Safari for mac: works
iOS for iPad: works :confused: 

Chrome for Android: this bug happens
iOS for iPhone: this bug happens

Also:
```
v = document.querySelector('#video-21')
<video class=​"message-video" id=​"video-21" preload=​"auto" playsinline autoplay loop muted>​…​</video>​
v.webkitDecodedFrameCount
0
```
but on refresh
```
v = document.querySelector('#video-21')
<video class=​"message-video" id=​"video-21" preload=​"auto" playsinline autoplay loop muted>​…​</video>​
v.webkitDecodedFrameCount
169
```

Interesting that webM seems to work just fine for Chrome (the bug goes away) but no apple iOS devices support webM.
