### ISSUE TITLE
Include version in js for debug purposes

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix_live_view#44]

**Comment by raygesualdo** [comment]
Were you thinking of having the version added as a static value to `LiveSocket` that could be accessed programmatically? Or simply included as a comment in the file?

**Comment by joshchernoff** [comment]
![image](https://user-images.githubusercontent.com/961877/54483750-20e6fc80-4816-11e9-9732-e2c3375cf194.png)
