### ISSUE TITLE
"installation guide on HexDocs" link from README.md 404s

### ISSUE THREAD

**Issue by untoldone** [phoenixframework/phoenix_live_view#440]
Current README.md link titled "installation guide on HexDocs" on master links to a page which 404s. Tried googling and couldn't find the correct link to point to instead. Was trying to install for the first time.

Perhaps https://github.com/phoenixframework/phoenix_live_view/issues/433 was assuming the link would exist but it was never updated?

**Comment by wojtekmach** [comment]
the reasons that page 404s is because the guide is on master and will be available in the next release.

Here's the file btw: https://github.com/phoenixframework/phoenix_live_view/blob/master/guides/introduction/installation.md

**Comment by psolvy** [comment]
@wojtekmach this file is wrong for hex version
for current in hex u need to:
`import Phoenix.LiveView,
      only: [live_render: 2, live_render: 3, live_link: 1, live_link: 2]`

**Comment by josevalim** [comment]
Installation guide is out with updated instructions.
