### ISSUE TITLE
After socket reconnection Channel GenServer losing state with components

### ISSUE THREAD

**Issue by AlexR2D2** [phoenixframework/phoenix_live_view#443]
If you wait on the page with LiveView component until socket reconnect and then open the subcomponent (or smh op with component) then MatchError occur.

Here is stack trace

```
[error] SearchLive.Index GenServer terminated: {{:badmatch, :error}, [{Phoenix.LiveView.Channel, :component_handle_event, 5, [file: 'deps/phoenix_live_view/lib/phoenix_live_view/channel.ex', line: 262]}, {Phoenix.LiveView.Channel, :handle_info, 2, [file: 'deps/phoenix_live_view/lib/phoenix_live_view/channel.ex', line: 81]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 637]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 711]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}
[error] GenServer #PID<0.847.0> terminating
** (MatchError) no match of right hand side value: :error
    (phoenix_live_view) deps/phoenix_live_view/lib/phoenix_live_view/channel.ex:262: Phoenix.LiveView.Channel.component_handle_event/5
    (phoenix_live_view) deps/phoenix_live_view/lib/phoenix_live_view/channel.ex:81: Phoenix.LiveView.Channel.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: %Phoenix.Socket.Message{event: "event", join_ref: "30", payload: %{"cid" => 0, "event" => "toggle_description", "type" => "click", "value" => %{"altKey" => false, "ctrlKey" => false, "metaKey" => false, "pageX" => 367, "pageY" => 367, "screenX" => 451, "screenY" => 453, "shiftKey" => false, "x" => 367, "y" => 367}}, ref: "32", topic: "lv:phx--O9IQ8SW"}
State: %{components: {%{}, %{}, 38}, join_ref: "30", router: NotesWeb.Router, serializer: Phoenix.Socket.V2.JSONSerializer, socket: #Phoenix.LiveView.Socket<assigns: %{extra: [], poi_list: [%{created_at: #DateTime<2019-10-27 08:41:15.337Z>, description: "Купить видеорегистратор АдвоКам в интернет магазине. Каталог с ценами, бесплатная доставка по России | Онлайн магазин AdvoCam. Телефон: +7(495)128-35-33.", ...}, %{created_at: #DateTime<2019-10-05 08:00:03.107Z>, ...}, %{...}, ...], recommended: ["ford focus c-max 2007 tdi", "volvo xc70", ...], suggested: [], tag: nil, ...}, changed: %{}, endpoint: NotesWeb.Endpoint, id: "phx--O9IQ8SW", parent_pid: nil, view: NotesWeb.SearchLive.Index, ...>, topic: "lv:phx--O9IQ8SW", transport_pid: #PID<0.841.0>, uri: %URI{authority: nil, fragment: nil, host: "localhost", path: nil, port: 4444, query: nil, scheme: "http", userinfo: nil}}

```

It seems the Phoenix.LiveView.Diff.with_component return :error term and it can't match with {diff, new_components} tuple

**Comment by chrismccord** [comment]
Can you explain in more detail what leads to this error? An example LV module + template would let us more quickly see what's happening. Thanks!

**Comment by AlexR2D2** [comment]
> Can you explain in more detail what leads to this error? An example LV module + template would let us more quickly see what's happening. Thanks!

Sure, I've created the [pxh_liveview_bug](https://github.com/AlexR2D2/pxh_liveview_bug) repo to reproduce the bug. Please run the project and follow the instructions on the web page. Thanks!

**Comment by feliperenan** [comment]
This issue happens because you are rendering the component again using the same ID you used before.

https://github.com/AlexR2D2/pxh_liveview_bug/blob/d49d417e7fd871c6d03e199d7590c2d0da979deb/lib/notes_web/live/search/index.ex#L48-L53

Notice that step one and two update the poi_list id to the same id even though they seem like different components. If you change the ID from the second step to a different one from the step one, probably will fix your issue.

I'm not sure if this is the desired behaviour though. It seems logic to me that different components should have different IDs, but Live View might need to improve the error or handle this somehow 🤔

**Comment by OvermindDL1** [comment]
It's HTML5 that requires unique ID's.  LiveView just leverages HTML5 calls.

**Comment by AlexR2D2** [comment]
Thanks a lot!
