### ISSUE TITLE
`connected?(socket)` is always false

### ISSUE THREAD

**Issue by xenophilicibex** [phoenixframework/phoenix_live_view#446]
I've followed the documentation's example here: https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html as closely as I possibly can.

The `mount(session, socket)` is called , but when I log `connected?(socket)` or `get_connect_params(socket)` they return `false` and `nil` respectively.

Do I need to do something extra to "connect" it?

socket.js
```js
import { Socket } from 'phoenix'
import LiveSocket from 'phoenix_live_view'

let liveSocket = new LiveSocket('/live', Socket, {
  params: {
    foo: 'bar',
  },
})
liveSocket.connect()
```

```ex
defmodule AppWeb.OperationsLive do
  use Phoenix.LiveView

  require Logger

  def render(assigns) do
    Logger.info "assigns: #{inspect assigns}"

    AppWeb.PageView.render("operations.html", assigns)
  end

  def mount(session, socket) do
    Logger.info "session #{inspect session}"
    Logger.info "socket #{inspect socket}"
    Logger.debug "get_connect_params #{inspect get_connect_params(socket)}"
    Logger.info "CONNECTED? #{connected?(socket)}"

    # if connected?(socket), do: :timer.send_interval(1000, self(), :update)
    if connected?(socket) do
      Logger.info "CONNECTED"
      :timer.send_interval(1000, self(), :update)
    end

    {:ok, assign(socket, users: "...", sessions: "...")}
  end

  def handle_info(:update, socket) do
    Logger.info "UPDATING"
    {:ok, user_count} = App.Metrics.user_count()
    {:ok, session_count} = App.Metrics.session_count()

    {:noreply, assign(socket, users: user_count, sessions: session_count)}
  end
end

```

### Environment

* Elixir version (elixir -v): 1.9.1
* Phoenix version (mix deps): 1.4.10
* NodeJS version (node -v): 12.8.0
* Operating system: macOS 10.15

**Comment by chrismccord** [comment]
are you importing your `socket.js` in `app.js`? Is your project pushed somewhere publicly where we could take a look? Thanks!

**Comment by xenophilicibex** [comment]
Oh man. I need sleep. I commented that out a few hours ago, and forgot to go back and undo it.

Thank you so much.

(I _really really_ appreciate the immediate reply. And thanks for the great project 👍 I watched your talk on LiveView today and learned much)

**Comment by chrismccord** [comment]
No worries. Glad you got rolling again :)
