### ISSUE TITLE
Stuck on the "npm install --prefix assets" step of install

### ISSUE THREAD

**Issue by ericridgeway** [phoenixframework/phoenix_live_view#449]
At the root project directory, I've done everything up to the step `npm install --prefix assets` and get:
`ERR! Could not install from "" as it does not contain a package.json file.`

I also tried `cd assetts` first and do it in that directory since I know there's a package.json there. That only gives a different error `Missing package name`

I have run `mix deps.get` and `ROOTDIR\deps\phoenix_live_view` does exist and have stuff in it

My `package.json` dependencies section looks like:
```
  "dependencies": {
    "phoenix": "file:../deps/phoenix",
    "phoenix_html": "file:../deps/phoenix_html",
    "phoenix_live_view": "file:../deps/phoenix_live_view"
  },
```

**Comment by ericridgeway** [comment]
cd assetts and then just `npm install` did give `added 1 package from 1 contributor and audited 14514 packages in 9.21s`, so maybe I'm set

I don't actually know what `npm install --prefix assets` does but it sure looks like it's just skipping the cd assets step and letting you run from root dir? Maybe I have a bad version of npm or it's the fact that I'm on Windows or something...

**Comment by snewcomer** [comment]
1.  Past npm v3.8.6, you can do `--prefix assets` to install in a specific directory.  This can also be thought of as `npm install --prefix ./assets`.  Here is the [documentation](https://docs.npmjs.com/files/folders#tl-dr).

2. Make sure the `package.json` file is valid.  Missing commas, etc.

📦your-project
 ┣ 📂assets
┃ ┗ 📜package.json
 ┣ 📂config
 ┣ 📂lib

**Comment by snewcomer** [comment]
But, I'm not sure `--prefix` is stable on window.  See this [comment](https://github.com/phoenixframework/phoenix/pull/3421#issuecomment-515982573).

`cd assets && npm install` might be the way to go for you.  if that works and `--prefix assets` doesn't, lets update the documentation 👍

**Comment by ericridgeway** [comment]
`cd assets && npm install` did indeed work. Tyvm!

I'm guessing you're right and the --prefix on windows was the gotcha

Updating the documentation would be <3
