### ISSUE TITLE
Consider using top-level document event handlers instead of complex patch+bind

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix_live_view#45]
Great idea by @Gazler

**Comment by OvermindDL1** [comment]
Just be careful, not all events bubble (like focus, which is an event I use surprisingly often), and there is talk at making no events bubble in the spec (I honestly don't see it going anywhere, but there is still a push for it).  A specific event handler on a specific element will always be more efficient than a bubble listener.

**Comment by OvermindDL1** [comment]
On the other side, having the ability to use a captured event on the global document (or some element) instead of a bubbled event has some very nice use-cases too.

**Comment by wanton7** [comment]
focus & blur events don't bubble but focusin and focusout events do.

Ebay's MarkoJS does similar thing and attaches event handlers only to root DOM element. https://github.com/marko-js/marko/blob/master/docs/why-is-marko-fast.md

**Comment by wanton7** [comment]
It seems that focus & blur supports bubbling when `addEventListener()` is used with `useCapture` parameter set to `true`. From what I read it might have better support for older browsers vs using focusin & focusout events.
