### ISSUE TITLE
JS not initializing element on updated()

### ISSUE THREAD

**Issue by jamilabreu** [phoenixframework/phoenix_live_view#452]
### Actual behavior

I'm initializing a JS library on `mounted()` like so:

```
let hooks = {};
hooks.SimpleBar = {
     mounted() {
          new SimpleBar(this.el);
     }
};
```

A user can then take an action that requires another element to be initialized on the same page via the same hook.

On update, the first element is kicked off - so now only the second element behaves correctly.

Each element has a unique `id`:

```
<div id="post-<%= post.id %>" phx-hook="SimpleBar">
  <%= live_component @socket, AppWeb.PostComponent, id: @post.id, post: @post %>
</div>
```

I tried adding `phx-ignore` to the elements, which causes all the JS to work correctly, but also prevents the assigns nested inside the element from updating.

### Expected behavior

I expected something along the lines of reinitializing on `updated()` would fix this

```
updated() {
     new SimpleBar(this.el);
}
```

### Environment

* Elixir version (elixir -v): 1.9.2
* Phoenix version (mix deps): Master

**Comment by snewcomer** [comment]
@jamilabreu Thank you for the issue! Do you have a reproduction?  Also note, the work on `live_component` is still ongoing so if you don't have time, we can revisit after a release is published...

**Comment by jamilabreu** [comment]
@snewcomer I was able to reproduce here: https://github.com/jamilabreu/lv

Happy to help any way I can.

**Comment by jamilabreu** [comment]
@snewcomer Btw, just to confirm - this doesn't seem to be related to `live_component` specifically

**Comment by jamilabreu** [comment]
Update: I was able to find a temporary workaround - making the id dynamic based on the child assigns, causing `mounted()` to be called again, rather than `updated()`
```
<div phx-hook="SimpleBar" id="post-<%= @post.id %>-<%= @child[:id] %>">
 <%= live_component @socket, AppWeb.PostComponent, id: @post.id, post: @post, child: @child %>
</div>
```

**Comment by chrismccord** [comment]
Can you expand a bit on the behavior you're seeing?

> On update, the first element is kicked off

By kicked off, do you mean the `updated` callback is no longer called for the original? Are you injecting markup via your JS or only generating new elements server side? More info would be helpful. Thanks!

**Comment by jamilabreu** [comment]
@chrismccord By kicked off, I just mean that - though `update()` is called on the element - the element that once had the JS markup is re-rendered as if the JS library was never initialized on it. Essentially I'm seeing the markup being injected on `mount()`, but not on `update()`. 

The repo I posted above shows what I mean more clearly: https://github.com/jamilabreu/lv

**Comment by chrismccord** [comment]
This is expected behavior. You need to mark any container as pax-ignore if you are doing your own DOM injection or manipulation. We will otherwise overwrite any work you did on subsequent updates. Thanks!

**Comment by jamilabreu** [comment]
@chrismccord Yep, In trying that I found that any assigns inside `phx-update=ignore` aren't updated. Given that theres no way to move the assigns outside (it's a scrollbar plugin) - I'm guessing my approach (having the parent re-mount on each update) is the correct one? Thx!

**Comment by jamilabreu** [comment]
@chrismccord Also just a conceptual question: Should calling `this.mounted()` on `updated()` cause the initial custom DOM injections to be re-run on updates?

**Comment by chrismccord** [comment]
> Given that there's no way to move the assigns outside (it's a scrollbar plugin) - I'm guessing my approach (having the parent re-mount on each update) is the correct one? Thx!

On master (and a new release coming today) we merge attributes for an ignored container, so you can populate assigned based attributes and Rea them on `updated`. If you are wanting to update assigns within the container somewhere that cannot be done since it is ignored after mount.

**Comment by jamilabreu** [comment]
@chrismccord Apologies for reopening, but this does seem to me like a bug and I just want to confirm. Here are the steps to reproduce:

1) Load an element on a page, with `phx-hook="InitScrollbar"`
```
// liveSocket.js
hooks.InitScrollbar = {
  mounted() {
    OverlayScrollbars(this.el, {});
  },
  updated() {
    OverlayScrollbars(this.el, {});
  }
};
```
2) Whether OverlayScrollbars is called in `mounted()`, in `updated()`, or in both - `this.el` is correctly initialized.

3) When certain assigns changes, a second, sibling element is added to the page.

4) `InitScrollbar.updated()` is called on the original element, but this code: `OverlayScrollbars(this.el, {});` does not re-initialize it. The first element is rendered without any JS effects on it (pre-mount).

**Comment by chrismccord** [comment]
Please provide relevant LV and template code. Thanks!

**Comment by jamilabreu** [comment]
@chrismccord Example repo here: https://github.com/jamilabreu/lv

**Comment by jamilabreu** [comment]
For a quick view:

```
defmodule LvWeb.SectionLive do
  use Phoenix.LiveView

  def render(assigns) do
    ~L"""
      <div phx-hook="InitScrollbar" id="unique_id">
         <%= for _ <- 1..10 do %><div>Scrollable Data</div><% end %>
      </div>
      <br>
      <button phx-click="add_second">Add Second Element</button>
      <%= if @second do %>
        <div>When this element appears, #unique_id element loses scrollbar, ignoring call in updated()</div>
      <% end %>
    """
  end

  def mount(_session, socket) do
    {:ok, assign(socket, second: false)}
  end

  def handle_event("add_second", _, socket) do
    {:noreply, assign(socket, second: true)}
  end
end

```
