### ISSUE TITLE
I think phoenix updates parts of my liveview which it shouldn't

### ISSUE THREAD

**Issue by johannesE** [phoenixframework/phoenix_live_view#455]
### Environment

* Elixir version (elixir -v): 1.9.1
* Phoenix version (mix deps): 1.4.10
* NodeJS version (node -v): 10.15.2
* NPM version (npm -v): 6.11.3
* Operating system: Ubuntu 19.10
* Browser this has been tested with: Firefox 70.0

### Actual behavior

I have made a stackoverflow post about it here: https://stackoverflow.com/questions/58660655/elixir-phoenix-liveview-echart-just-vanishes-disappears
But the more I think about it, taking into consideration the age of liveview, I think this is a bug.

### Expected behavior
The graph stays i place after it's being mounted. Also: When I change the graphs' background in the browser by adding custom css, then it should not be overridden in less than a second.

I have also made a video of the loading process and put it here: https://nx3357.your-storageshare.de/s/s6DaDTpDbGW5xtL

**Comment by chrismccord** [comment]
You need to mark any js controlled parts of the DOM as `phx-update=ignore`. Please check out the docs. Thanks!

**Comment by johannesE** [comment]
Oh my god, that is awesome. Immediately it works. Thank you so much for all the work you do!
