### ISSUE TITLE
live_redirect does not pass the whole URL

### ISSUE THREAD

**Issue by cadebward** [phoenixframework/phoenix_live_view#459]
### Environment

* Elixir version (elixir -v): 1.9.2
* Phoenix version (mix deps): 1.4.10
* NodeJS version (node -v): 8.11
* NPM version (npm -v): 5.6
* Operating system: OSX

### Actual behavior

`live_redirect/2` causes `handle_params/3` to only receive the path, as opposed to the whole URL.
```
path = Routes.live_path(socket, LiveComponent)
live_redirect(socket, to: path)
```

```
LiveComponent.handle_params(_params, url, _socket) do
  IO.inspect(url) # /path/to/component
end
```

While `live_link/2`, given the same path, provides the whole URL to `handle_params/3`.

### Expected behavior

The following code:

```
path = Routes.live_path(socket, LiveComponent)
live_redirect(socket, to: path)
```

Would cause `LiveComponent.handle_params/3` to be called with the full URL.

```
LiveComponent.handle_params(_params, url, _socket) do
  IO.inspect(url) # host.tld/path/to/component
end
```

**Comment by josevalim** [comment]
Hi @cadebward! I was unable to reproduce this issue. Can you please provide a sample app that reproduces it? Thank you.

**Comment by cadebward** [comment]
Hey @josevalim!

I've forked the examples repo and added a "UrlA" module. Navigate to `http://localhost:4000/urla/param`. Notice that if you click the button it logs out the path. If you go back and click the link instead, it logs the whole url.

https://github.com/cadebward/phoenix_live_view/blob/master/lib/demo_web/live/urla_live.ex#L10

**Comment by josevalim** [comment]
Thanks! Please see #479 for the fix.
