### ISSUE TITLE
After upgrading to 0.4.0, typing in an uncontrolled input field no longer works

### ISSUE THREAD

**Issue by mreishus** [phoenixframework/phoenix_live_view#460]
### Environment

* Elixir version (elixir -v): locally **1.9.2**, deployed **1.9.4** (error occurs in both places)
* Phoenix version (mix deps): **1.4.10**
* NodeJS version (node -v): locally **v12.13.0**, deployed whatever is in `elixir:1.9.4-alpine`
* NPM version (npm -v):  locally **6.12.1**, deployed whatever is in `elixir:1.9.4-alpine`
* Operating system: locally **arch**, deployed `alpine:3.10`

### Preamble

I don't have a stripped down example; rather I have something that used to work in my 0.3.0 liveview app that no longer works in 0.4.0.  I don't see any breaking changes in the changelog, so I'm not sure what's happening.

### Actual behavior

1. Visit https://beta.demonspirit.xyz/game
2. Confirm the top left lists the version as `(beta.lv040.3)` or some later version with lv040 in it
3. Type any name in the name box and click *Log In As Guest*.
4. In the lobby view, there's a chat pane on the right side.  Click the input element at the bottom of the chat pane that reads "your message..." to focus it.
5. Type "abc".
6. No characters appear.

### Expected behavior

1. Visit https://demonspirit.xyz/game . Note: This is a different url.
2. Confirm the top left lists the version as `(1.0.1)` or another `1.0.x` version.  This means it is running on LiveView 0.3.1.
3. Type any name in the name box and click *Log In As Guest*.
4. In the lobby view, there's a chat pane on the right side.  Click the input element at the bottom of the chat pane that reads "your message..." to focus it.
5. Type "abc".
6. The characters abc appear in the input box.
7. Press enter.
8. Your name and message, "abc" appear in the chat box.

### Relevant part of template

https://github.com/mreishus/demon_spirit_umbrella/blob/master/apps/demon_spirit_web/lib/demon_spirit_web/templates/chat/live_index.html.leex#L27-L33

https://github.com/mreishus/demon_spirit_umbrella/blob/master/apps/demon_spirit_web/lib/demon_spirit_web/live/live_chat_index.ex

### Other Relevant Information

- There are no JS errors.
- No errors in the `phx.server` console.
- If I sever the websocket connection, I am able to type in the box.  So live view might think the state of the box is controlled by the server in 0.4.0, where in 0.3.0 it was controlled by the client.
- This is a nested live view.  Could something have changed here wrt components?

### Project

https://github.com/mreishus/demon_spirit_umbrella

Branch `master` - Live view 0.3.1, works.
Branch `live_view-0.4.0` - Live view 0.4.0, does not work.

### Running the project

Luckily it does not have a database.
```
git clone https://github.com/mreishus/demon_spirit_umbrella
cd demon_spirit_umbrella
git fetch origin live_view-0.4.0
git checkout live_view-0.4.0
mix deps.get
cd apps/demon_spirit_web/assets/
npm install
cd ../../../
mix phx.server
```

**Comment by chrismccord** [comment]
Fixed in 0.4.1. Thanks!
