### ISSUE TITLE
Input fields are set to readonly on phx-change

### ISSUE THREAD

**Issue by apognu** [phoenixframework/phoenix_live_view#461]
### Environment

* Elixir version (elixir -v): 1.9.1
* Phoenix version (mix deps): 1.4.10
* NodeJS version (node -v): 12.11.0
* Yarn version (npm -v): 1.19.0
* Operating system: ArchLinux

### Actual behavior

Documentation says input fields will be set to `readonly` on `phx-submit`, but not on `phx-change`. 

In my project, my modified `input` (in a `phx-change`'d form) is set to `readonly` after the first character. If I edit another field, the first one retrieve its read-write status, and the latter is disabled.

### Expected behavior

I should be able to write more than one character in my `input` and for it not to get disabled.

### Investigation

My developer tools tell me the field is disabled by [this](https://github.com/phoenixframework/phoenix_live_view/blob/448e22642e89de7c26fc8eeb12a49c64d925a496/assets/js/phoenix_live_view.js#L916) line.

The inspector shows that `readonly="false" is appended to the field.

As far as I know HTML, any value for the `readonly` attribute will disable the field, even if it is `false`. It is only read-write if the attribute is missing.

**Comment by mreishus** [comment]
This might be fixed by 0.4.1 which was just released. d9c82d783d9a6b1ceb2450481fcb110bb98ab721

**Comment by chrismccord** [comment]
Indeed. Thanks!

**Comment by apognu** [comment]
Talk about good timing. Thanks!
