### ISSUE TITLE
Conditional hooks not triggering if both condition branches are using same tag structure

### ISSUE THREAD

**Issue by hypno2000** [phoenixframework/phoenix_live_view#467]
### Environment

Elixir version (elixir -v):
Erlang/OTP 22 [erts-10.5] [source] [64-bit] [smp:20:20] [ds:20:20:10] [async-threads:1] [hipe] [dtrace]
Elixir 1.9.1 (compiled with Erlang/OTP 22)
Phoenix version (mix deps): 1.4.10
Phoenix LiveView version (mix deps): 0.4.1
NodeJS version (node -v): 10.16.0
NPM version (npm -v): 6.11.3
Operating system: macOS Mojave 10.14.6

```elixir
defmodule DemoWeb.ComponentHooksLive do
  use Phoenix.LiveView

  def render(assigns) do
    ~L"""
    <div>
      <button phx-click="inc">+</button>
      <button phx-click="dec">-</button>
      <div><%= @counter %></div>
      <%= if @counter == 2 do %>
        <div phx-hook="Foo">
          ...
        </div>
      <% else %>
        <div>
          ...
        </div>
      <% end %>
    </div>
    """
  end

  def mount(_session, socket) do
    {:ok, socket |> assign(:counter, 0)}
  end

  def handle_event("inc", _, socket) do
    {:noreply, update(socket, :counter, &(&1 + 1))}
  end

  def handle_event("dec", _, socket) do
    {:noreply, update(socket, :counter, &(&1 - 1))}
  end
end
```

Looks like when the tag structure is same in both condition branches then the hooks are not triggered.

### Actual behavior

If counter hits 2 the `Foo` hook is not triggered.

### Expected behavior

If counter hits 2 the `Foo` hook is triggered.

### Workaround

Avoid using same tag structure in both condition branches, for example this works:

```html
<%= if @counter == 2 do %>
  <div phx-hook="Foo">
    ...
  </div>
<% else %>
  <section>
    ...
  </section>
<% end %>
```

**Comment by chrismccord** [comment]
You need to provide an `id` for the hook element which will resolve this issue. The next release will require IDs for hooks.
