### ISSUE TITLE
Temporary Assign cannot replace with empty list

### ISSUE THREAD

**Issue by kwando** [phoenixframework/phoenix_live_view#469]
I have a list marked as a temporary assign.

```
def mount(_, socket) do
  socket = socket
  |> assign(:list, [])

  {:ok, socket, temporary_assigns: [list: []]}
end
```

```
<div id="my-list-container" phx-update="replace">
 <%= for item <- @list do....
</div>
```

When assigning new lists my UI updates, but when I assign an empty list my UI does not update to reflect that my list is empty.

**Comment by josevalim** [comment]
Can you please provide more information? How are you assigning the list? Are you sure that the code that assigns the list is being invoked? If so, can you please provide a minimal app that reproduces the error?

**Comment by kwando** [comment]
Sorry for being lazy :)
I created a minimal app here:
https://github.com/kwando/live_example_bug

Pressing ADD will add a number to the list, when pressing CLEAR I expect the rendered list to be empty but nothing happens. When I press ADD after that the list is rendered correctly.

**Comment by josevalim** [comment]
I am not sure if there is something we can do here. When you set the temporary assign to an empty list, then it is an empty list after every render. So when you set it to an empty list in a given render, then we don't consider it as changed, and therefore it won't be re-rendered.

Another option is for us to consider temporary assigns as changed whenever they are set but this may have other consequences.

For now, we will go ahead with a doc change. A fix is to simply set it to a value that you don't use, such as nil:

    {:ok, setup_counter(socket), temporary_assigns: [list: nil]}

**Comment by kwando** [comment]
Ah, I see what you mean now. I agree that this no bug then, it was just a little surprising. I will have to admit I just looked at the code snippets in the docs but if I had actually read all the text too then I might have figured this out on my own.

Thanks for your time :) 

(setting it to `nil` works like a charm)

**Comment by enkr1** [comment]
> I am not sure if there is something we can do here. When you set the temporary assign to an empty list, then it is an empty list after every render. So when you set it to an empty list in a given render, then we don't consider it as changed, and therefore it won't be re-rendered.
> 
> Another option is for us to consider temporary assigns as changed whenever they are set but this may have other consequences.
> 
> For now, we will go ahead with a doc change. A fix is to simply set it to a value that you don't use, such as nil:
> 
> ```
> {:ok, setup_counter(socket), temporary_assigns: [list: nil]}
> ```

Hi community,

I found out this is just a temp fix as setting the list to `nil` will throw you an error of:
```
protocol Enumerable not implemented for nil of type Atom
```

<img width="1467" alt="image" src="https://user-images.githubusercontent.com/64194467/191678483-43262b97-9c55-4e9d-85f6-ec279480afa0.png">

As this is 3 years ago, I am curious if there is any latest update on this issue. 

Thank you in advance.
