### ISSUE TITLE
Possible regression in phoenix_live_view.js (?)

### ISSUE THREAD

**Issue by lustrousgorilla** [phoenixframework/phoenix_live_view#470]
Upon updating phoenix_live_view from `5521443b1dd6488f0d9b18043e942608d8d61891` to `a2d776f24242c01061236da669395165b23977cd`, an existing LiveView now throws the following error in the browser console upon initial render:
```
Uncaught TypeError: Cannot read property '0' of undefined
    at Object.toOutputBuffer (phoenix_live_view.js?e545:1)
    at Object.toString (phoenix_live_view.js?e545:1)
    at e.value (phoenix_live_view.js?e545:1)
    at Object.eval [as callback] (phoenix_live_view.js?e545:1)
    at eval (phoenix.js?98f4:1)
    at Array.forEach (<anonymous>)
    at e.value (phoenix.js?98f4:1)
    at Object.eval [as callback] (phoenix.js?98f4:1)
    at e.value (phoenix.js?98f4:1)
    at Object.eval [as callback] (phoenix.js?98f4:1)
```
Unfortunately, I'm not sure how to give y'all more context... I don't have enough understanding of what's under the hood to extract the relevant snippets of my code, but I don't think I'm doing anything unusual in my LiveView - just rendering a paginated data table with some real-time search + toggleable filters.

I did confirm that reverting the version to what was previously in my `mix.lock` file with `{:phoenix_live_view, github: "phoenixframework/phoenix_live_view", ref: "5521443b1dd6488f0d9b18043e942608d8d61891"}` made the error go away.

### Environment

* Elixir version (elixir -v): **1.8.1**
* Phoenix version (mix deps): **1.4.11**
* NodeJS version (node -v): **10.16.0**
* NPM version (npm -v): **yarn 1.17.3**
* Operating system: **MacOS 10.15.1**

**Comment by snewcomer** [comment]
@lustrousgorilla 👋 Thanks for the issue!  There are two dependencies involved.  The elixir `deps/` and the JavaScript `assets/node_modules` (`assets/package.json`).  Example command you can run:

`mix deps.clean --all && mix deps.get && npm install --prefix assets && mix ecto.reset && mix phx.server`

**Comment by Wijnand** [comment]
Well, the `mix ecto.reset` is not really needed :-)

**Comment by josevalim** [comment]
Yeah, when upgrading, you need to make sure you get the latest bundle for the JS bits. If the command above does not work, try nuking `_build` and `node_modules` and installing again. Thanks!

**Comment by lustrousgorilla** [comment]
Doh! :face_with_rolling_eyes: My apologies for submitting an issue for what amounted to user error, but in any case: thanks for sorting me out!
