### ISSUE TITLE
Warn on duplicate IDs

### ISSUE THREAD

**Issue by kuon** [phoenixframework/phoenix_live_view#471]
First I'm sorry if this is a feature request that should be discussed elsewhere, it is half a bug half a feature request, anyway.

I realize that the DOM diffing cannot be done properly with duplicate IDs.

I just spend quite some time realizing that some helper function I wrote a while back was generating duplicate id and broke diffing, it wasn't a problem with regular view but with live view it created hard to track rendering bug.

I think this could be a very common issue and that live view should do something about it.

I don't know what is possible/simple/efficient, from analyzing AST to having something on the JS side, but it would be very useful that phoenix live view warned about duplicate id.

Raising an exception on the phoenix side if duplicate id are rendered would be ideal for me (maybe a configurable config on in debug).

**Comment by snewcomer** [comment]
I agree. Great idea!  We have some utility functions to log already.  Effectively we need development only utilities for this type of stuff.

**Comment by snewcomer** [comment]
This is trivial to implement now that we have a dev/test only logger.  We could add to the `patch` function.

```js
  let elems = document.querySelectorAll('*[id]');
  let ids = new Set();
  for (let i = 0, len = elems.length; i < len; i++) {
    if (ids.has(id)) {
      ids.add(elems[i].id)
    } else {
      console.warn('Multiple IDs #' + elems[i].id);
    }
  }
```

**Comment by chrismccord** [comment]
Awesome. Can you send a PR? Thanks!
