### ISSUE TITLE
phx-update: append maybe not working?

### ISSUE THREAD

**Issue by ityonemo** [phoenixframework/phoenix_live_view#472]
came across phx-update: append not working correctly, here is a minimally reproduced version.

https://github.com/ityonemo/live_message_test

### Environment

* Elixir version (elixir -v):

Erlang/OTP 22 [erts-10.5.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.9.4 (compiled with Erlang/OTP 21)

* Phoenix version (mix deps):

* phoenix 1.4.11 (Hex package) (mix)
  locked at 1.4.11 (phoenix) d112c862
  ok
* phoenix_live_view 0.4.1 (Hex package) (mix)
  locked at 0.4.1 (phoenix_live_view) 17e04bd0

* NodeJS version (node -v):

v10.16.3 (alpine linux; inside a container)

* NPM version (npm -v):

v6.9.0 (alpine linux; inside a container)

* Operating system:
Linux **** 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

The directory tree was created with a fresh install of phoenix, (`mix phx.gen phoenix_live_view --no-ecto`) followed by a forced npm audit (`cd assets; npm audit fix --force; npm install`) followed by the instructions as indicated here:  https://hexdocs.pm/phoenix_live_view/installation.html

### Actual behavior

phx-update: append appears to have "replace" behavior.

### Expected behavior

should append more rows of random text instead of replacing the single row of random text.

### Key code links:

https://github.com/ityonemo/live_message_test/blob/master/lib/live_message_test_web/live/test_message.ex

https://github.com/ityonemo/live_message_test/blob/master/lib/live_message_test_web/templates/page/index.html.eex

https://github.com/ityonemo/live_message_test/blob/master/lib/live_message_test_web/router.ex

**Comment by ityonemo** [comment]
tested on both Firefox 70.0.1 and Chromium Version 78.0.3904.70 (Official Build) Built on Ubuntu , running on LinuxMint 19.2 (64-bit)

**Comment by josevalim** [comment]
Oh, check your browser console. Each child inside `phx-update="append"`must have an ID too. I will update the docs to make this clearer.

**Comment by ityonemo** [comment]
thanks!  I wonder if there's a way to forward some of these errors back to the server console, since some of us 😬 are backend devs not used to looking in the js console for errors.

WRT to the docs specifically, the example doesn't create an id for the child tag, and it may be good to be explicit that the child tags should be unique, per append event.

**Comment by josevalim** [comment]
Yeah, I have updated the docs. Regarding to the logs, noted!
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
