### ISSUE TITLE
Republish docs for 0.4.1

### ISSUE THREAD

**Issue by davydog187** [phoenixframework/phoenix_live_view#483]
Instructions for installation were updated in https://github.com/phoenixframework/phoenix_live_view/commit/6bdca2e06ba81fe624f18ab4fe61aba156e1f2d6#diff-e0d236c4a452b97a2814ffe7bcff18d5

However, the published 0.4.1 docs are published with instructions to install `0.3.0`, which lead to problems. 

<img width="1419" alt="Screen Shot 2019-11-17 at 6 01 24 PM" src="https://user-images.githubusercontent.com/1019721/69015675-4a879300-0964-11ea-8bfe-21a8a6f35f2a.png">

**Comment by josevalim** [comment]
Done, thanks!
