### ISSUE TITLE
phx-value-* not sent with keyup/down events

### ISSUE THREAD

**Issue by zimt28** [phoenixframework/phoenix_live_view#489]
_Phoenix LiveView version (mix deps): 0.4.1_

### Actual behavior

When using `phx-keyup/down`, the `phx-value-*` is not included in the params.
```html
<input phx-keyup="event" phx-value-test="<%= test %>" />
```

When I replace `phx-keyup` with `phx-click`, it's included.

### Expected behavior

Additional values should be included, as implicitly [documented](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#module-click-events):
> If the phx-value- prefix is used, the server payload will also contain a "value" if the element's value attribute exists.

**Comment by snewcomer** [comment]
@zimt28 I'm seeing this for click, focus, blur but not for keydown/up.  I don't see explicit documentation but perhaps it's inclusion was an oversight for the key events.  For clarity, what is your use case?  

https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#module-key-events
