### ISSUE TITLE
Add offsetX and offsetY to click events

### ISSUE THREAD

**Issue by alvises** [phoenixframework/phoenix_live_view#493]
### Environment

* Phoenix LiveView version (mix deps): 0.4.1
### Actual behavior

At the moment a `click` sends an event with `pageX`, `pageY`, `screenX`, `screenY`, `x`, `y` coordinates. With these properties it's not possible to know the click coordinate relative to the clicked element.

### Expected behavior

 It would be also nice to have `offsetX` and `offsetY`, which are the click coordinates relative to the clicked element. 

This can be useful like when clicking on a big rectangular div where we want to render new elements.

![offsetX_offsetY](https://user-images.githubusercontent.com/486085/69256455-c9293e00-0bb9-11ea-81d8-76e8f167b96e.gif)

I've already tried locally to add those two properties to the `meta` in [phoenix_live_view.js#L509](https://github.com/phoenixframework/phoenix_live_view/blob/master/assets/js/phoenix_live_view.js#L509) and works pretty well.

Before opening a PR, I wanted to know if it could be something useful or is it possible to get the same result in other ways without sending additional data in the event?

Thanks

Alvise
****

**Comment by snewcomer** [comment]
This seems like a great idea!  Capturing all 3 (screen/page/client) would cover all the use cases.

**Comment by alvises** [comment]
Great, then I'm going to add a PR :)

**Comment by alvises** [comment]
> This seems like a great idea! Capturing all 3 (screen/page/client) would cover all the use cases.

Great, then I'm going to open a PR :)
