### ISSUE TITLE
Revisit session encoding

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix_live_view#50]
It appears we might be double encoding since Phoenix.Token should already be going the encode/decode work

**Comment by josevalim** [comment]
After a conversation, we decided to keep the current mechanism and provide some sort of `live_view_session` macro in the router to remove the duplication.

**Comment by DanielDent** [comment]
Has there been consideration given to encrypting the session? There are use cases where the contents of the session should not be available to the client.
