### ISSUE TITLE
send_update/2 triggers updated() for all components, rather than just one

### ISSUE THREAD

**Issue by jamilabreu** [phoenixframework/phoenix_live_view#500]
### Environment

* Phoenix LiveView version (mix deps): master

### Actual behavior

I have a list of components with the same phx-hook, and I'm seeing that using:
```
send_update(AppWeb.ExampleComponent, id: "123", example_assigns: "example")
```
triggers `updated()` on all components

### Expected behavior

I expected `updated()` to only trigger for the `AppWeb.ExampleComponent` with an id of `123`

**Comment by jamilabreu** [comment]
Further info: I have a LiveView with three child LiveComponents that are siblings.

Looking into this further, seeing lots of `updated()` methods triggered - even for hooks in the sibling components (none are nested).

**Comment by jamilabreu** [comment]
Reproduced here: https://github.com/jamilabreu/send_update_bug

**Comment by josevalim** [comment]
Yes, it will be called multiple times on the client, because we always remount the whole diff on the client. It is a partial update on the server though. I will clarify it in the docs. Thanks for the reproducing app!

**Comment by josevalim** [comment]
I was wrong. It is actually a bug. :)

**Comment by ljubisa41** [comment]
Sorry to maybe spam this thread. I don't know if this bug is related with problem that I have, but i on the first site it looks to me like it does. Please see this post: https://elixirforum.com/t/liveview-updated-hook-problem/27607/2

**Comment by chrismccord** [comment]
On 0.6.0, this behaves as expected, but note that the updated hooks will all be called on the client because the DOM elements are replaced since you did not give the containers an ID in your components. If you give your divs an id, morphdom will patch the containers rather than replacing them, for example:

```html
      <div phx-hook="ComponentThree" id="<%= @id %>">Component Three</div>
```

On the server, the `updated` callback is only executed for the desired component regardless. Thanks!

**Comment by LazarRistic** [comment]
Hi @chrismccord,
Thank you for resolving this bug, it will help us so much.
Do you maybe know or have a hint when will 0.6.0 be available?
