### ISSUE TITLE
Pattern matching on a `live` route

### ISSUE THREAD

**Issue by jamilabreu** [phoenixframework/phoenix_live_view#513]
What's the recommended way to pattern match on a dynamic live route? 

For example, with the regular router, I use:
```
get "/:slug", CustomRouter, :show, as: :custom
```
to pattern match on :slug within `CustomRouter` and call the correct controller - is there an analogous way to do this with `live` routes?

I've thought about using `live_render` in controllers (after pattern matching) - but then I'm unable to `live_link` to the route (no `live` macro in router).

**Comment by josevalim** [comment]
Yes, you can use the `handle_params` callback in your LiveView to access the pattern matched segments in a `live` macro.

**Comment by jamilabreu** [comment]
@josevalim Does the new 'actions' feature allow for this now? 🙏

**Comment by josevalim** [comment]
Yes!!!

**Comment by jamilabreu** [comment]
😍 ❤️ 🔥 🐤

**Comment by jamilabreu** [comment]
@josevalim Sadly, I haven't been able to figure this out by looking at the docs 😢 

What would the LiveView version of `controller.call(conn, controller.init(action))` be in this code:

`
defmodule Router do
  get "/", PageController, :index
  ... # other routes
  get "/*path", GlobRouter, []
end

defmodule GlobRouter do
  def init(opts), do: opts
  def call(%Plug.Conn{request_path: path} = conn, _opts) do
    cond do
      Regex.match?(path, ~r{[!a-e]*}) -> to(conn, PageController, :catch_all)
      Regex.match?(path, ~r{another}) -> to(conn, AnotherController, :other)

      true -> raise Phoenix.Router.NoRouteError, conn: conn, router: Router
    end
  end

  defp to(conn, controller, action) do
    controller.call(conn, controller.init(action))
  end
end`

**Comment by jamilabreu** [comment]
Was able to get as far as:

```
conn = put_private(conn, :phoenix_live_view, {AppWeb.PageLive, opts})
Phoenix.LiveView.Plug.call(conn, opts)
```
