### ISSUE TITLE
Typo in information regarding LV socket

### ISSUE THREAD

**Issue by StormBytePP** [phoenixframework/phoenix_live_view#515]
While trying the new updates, I followed the guide in terminal to update sockets, and found a little typo which affects this like:

https://github.com/phoenixframework/phoenix_live_view/blob/57f2ef73859a36dee634db3e1e3be2b4ce6ceec9/lib/phoenix_live_view/socket.ex#L65

The Socket parameter is missing, and while it is corrected in documentation, this might drive crazy some people (like me).

Please add here the Socket parameter also so the information for fix the issue is already correct.

**Comment by feliperenan** [comment]
This PR is supposed to fix that https://github.com/phoenixframework/phoenix_live_view/pull/510
