### ISSUE TITLE
Handle "render_existing"

### ISSUE THREAD

**Issue by jamilabreu** [phoenixframework/phoenix_live_view#52]
### Environment

* Phoenix version (mix deps): 1.4

### Expected behavior
I'm using render_existing in `<head>` to conditionally render scripts and styles:
<%= render_existing(@view_module, "head." <> @view_template, assigns) %>

Should ignore if template doesn't exist.

### Actual behavior

Raises `no function clause matching in Phoenix.LiveView.Controller.render/2`

> ### Environment

* Phoenix version (mix deps): 1.4

### Expected behavior
I'm using render_existing in `<head>` to conditionally render scripts and styles:
<%= render_existing(@view_module, "head." <> @view_template, assigns) %>

Should ignore if template doesn't exist.

### Actual behavior

Raises `no function clause matching in Phoenix.LiveView.Controller.render/2`

> [info] GET /
[debug] Processing with LiveTestWeb.PageController.index/2
  Parameters: %{}
  Pipelines: [:browser]
[info] Sent 500 in 11ms
[error] #PID<0.5254.0> running LiveTestWeb.Endpoint (connection #PID<0.5246.0>, stream id 4) terminated
Server: localhost:4000 (http)
Request: GET /
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Phoenix.LiveView.Controller.render/2
        (phoenix_live_view) lib/phoenix_live_view/controller.ex:72: Phoenix.LiveView.Controller.render("head.template.html", %{__phx_render_existing__: {Phoenix.LiveView.Controller, "head.template.html"}, conn: %Plug.Conn{adapter: {Plug.Cowboy.Conn, :...}, assigns: %{conn: %Plug.Conn{adapter: {Plug.Cowboy.Conn, :...}, assigns: %{current_member: nil, member_token: "SFMyNTY.g3QAAAACZAAEZGF0YW0AAAAiZ3Vlc3QtV2d5MVpOQWx0VWdmWXh2bnFFTElRdlo5ZExvPWQABnNpZ25lZG4GANaOQn5pAQ.eC3VCS6FLECsoWjYa851Njabig5CgtpNkZsZMbxT548"}, before_send: [#Function<0.76412652/1 in Plug.CSRFProtection.call/2>, #Function<2.70052748/1 in Phoenix.Controller.fetch_flash/2>, #Function<2.70052748/1 in Phoenix.Controller.fetch_flash/2>,#Function<0.58261320/1 in Plug.Session.before_send/2>, #Function<1.112466771/1 in Plug.Logger.call/2>, #Function<0.89070732/1 in Phoenix.LiveReloader.before_send_inject_reloader/2>], body_params: %{}, cookies: %{"_live_key" => "SFMyNTY.g3QAAAABbQAAAAtfY3NyZl90b2tlbm0AAAAYOHp1Vk9qeXEyeGdQSm9EQ0h1K1ljQT09.1_WO2tAMqyXADqSL58-4vz_0OaKYHfXqzPNL6X4YavA"}, halted: false, host: "localhost", method: "GET", owner: #PID<0.5254.0>, params: %{}, path_info: [], path_params: %{}, port: 4000, private: %{LiveTestWeb.Router => {[], %{}}, :phoenix_action => :index, :phoenix_controller => LiveTestWeb.PageController, :phoenix_endpoint => LiveTestWeb.Endpoint, :phoenix_flash => %{}, :phoenix_format => "html", :phoenix_layout=> {LiveTestWeb.LayoutView, :app}, :phoenix_pipelines => [:browser], :phoenix_router => LiveTestWeb.Router, :phoenix_view => LiveTestWeb.PageView, :plug_session => %{"_csrf_token" => "8zuVOjyq2xgPJoDCHu+YcA=="}, :plug_session_fetch => :done}, query_params: %{}, query_string: "", remote_ip: {127, 0, 0, 1}, req_cookies: %{"_live_key" => "SFMyNTY.g3QAAAABbQAAAAtfY3NyZl90b2tlbm0AAAAYOHp1Vk9qeXEyeGdQSm9EQ0h1K1ljQT09.1_WO2tAMqyXADqSL58-4vz_0OaKYHfXqzPNL6X4YavA"}, req_headers: [{"accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8"}, {"accept-encoding", "gzip, deflate, br"}, {"accept-language", "en-US,en;q=0.9,es;q=0.8"}, {"cache-control", "max-age=0"}, {"connection", "keep-alive"}, {"cookie", "_live_key=SFMyNTY.g3QAAAABbQAAAAtfY3NyZl90b2tlbm0AAAAYOHp1Vk9qeXEyeGdQSm9EQ0h1K1ljQT09.1_WO2tAMqyXADqSL58-4vz_0OaKYHfXqzPNL6X4YavA"}, {"host", "localhost:4000"}, {"referer", "http://localhost:4000/"}, {"upgrade-insecure-requests", "1"}, {"user-agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36"}], request_path: "/", resp_body: nil, resp_cookies: %{}, resp_headers: [{"cache-control", "max-age=0, private, must-revalidate"}, {"x-request-id", "2m5v5koo0rh6139r0s002b44"}, {"x-frame-options", "SAMEORIGIN"}, {"x-xss-protection", "1; mode=block"}, {"x-content-type-options", "nosniff"}, {"x-download-options", "noopen"}, {"x-permitted-cross-domain-policies", "none"}, {"cross-origin-window-policy", "deny"}], scheme: :http, script_name: [], secret_key_base: :..., state: :unset, status: nil}, content: {:safe, ["<div id=\"", "phx-h0+E+E9pIT8=", "\"\n    data-phx-view=\"", "LiveTestWeb.RoomLive", "\"\n    data-phx-session=\"", "SFMyNTY.g3QAAAACZAAEZGF0YW0AAACIZzNRQUFBQUVaQUFDYVdSdEFBQUFFSEJvZUMxb01DdEZLMFU1Y0VsVU9EMWtBQXB3WVhKbGJuUmZjR2xrWkFBRGJtbHNaQUFIYzJWemMybHZiblFBQUFBQVpBQUVkbWxsZDJRQUdFVnNhWGhwY2k1RVlXbHplVmRsWWk1U2IyOXRUR2wyWlE9PWQABnNpZ25lZG4GANaOQn5pAQ.wLi6SpYsIRMOAaD5qf00Tv334Ou-0RS5jZYi4vQMxK8", "\">\n  ", ["  Current temperature:\n"], "\n</div>\n<div class=\"phx-loader\"></div>\n"]}, current_member: nil, layout: {LiveTestWeb.LayoutView, "app.html"}, member_token: "SFMyNTY.g3QAAAACZAAEZGF0YW0AAAAiZ3Vlc3QtV2d5MVpOQWx0VWdmWXh2bnFFTElRdlo5ZExvPWQABnNpZ25lZG4GANaOQn5pAQ.eC3VCS6FLECsoWjYa851Njabig5CgtpNkZsZMbxT548"}, before_send: [#Function<0.76412652/1 in Plug.CSRFProtection.call/2>, #Function<2.70052748/1 in Phoenix.Controller.fetch_flash/2>, #Function<2.70052748/1 in Phoenix.Controller.fetch_flash/2>, #Function<0.58261320/1 in Plug.Session.before_send/2>, #Function<1.112466771/1 in Plug.Logger.call/2>, #Function<0.89070732/1 in Phoenix.LiveReloader.before_send_inject_reloader/2>], body_params: %{}, cookies: %{"_live_key" => "SFMyNTY.g3QAAAABbQAAAAtfY3NyZl90b2tlbm0AAAAYOHp1Vk9qeXEyeGdQSm9EQ0h1K1ljQT09.1_WO2tAMqyXADqSL58-4vz_0OaKYHfXqzPNL6X4YavA"}, halted: false, host: "localhost", method: "GET", owner: #PID<0.5254.0>, params: %{}, path_info: [], path_params: %{}, port: 4000, private: %{LiveTestWeb.Router => {[], %{}}, :phoenix_action => :index, :phoenix_controller => LiveTestWeb.PageController, :phoenix_endpoint => LiveTestWeb.Endpoint, :phoenix_flash => %{}, :phoenix_format => "html", :phoenix_layout => {LiveTestWeb.LayoutView, :app}, :phoenix_pipelines => [:browser], :phoenix_router => LiveTestWeb.Router, :phoenix_template => "template.html", :phoenix_view => Phoenix.LiveView.Controller, :plug_session => %{"_csrf_token" => "8zuVOjyq2xgPJoDCHu+YcA=="}, :plug_session_fetch => :done}, query_params: %{}, query_string: "", remote_ip: {127, 0, 0, 1}, req_cookies: %{"_live_key" => "SFMyNTY.g3QAAAABbQAAAAtfY3NyZl90b2tlbm0AAAAYOHp1Vk9qeXEyeGdQSm9EQ0h1K1ljQT09.1_WO2tAMqyXADqSL58-4vz_0OaKYHfXqzPNL6X4YavA"}, req_headers: [{"accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8"}, {"accept-encoding", "gzip, deflate, br"}, {"accept-language", "en-US,en;q=0.9,es;q=0.8"}, {"cache-control", "max-age=0"}, {"connection", "keep-alive"}, {"cookie", "_live_key=SFMyNTY.g3QAAAABbQAAAAtfY3NyZl90b2tlbm0AAAAYOHp1Vk9qeXEyeGdQSm9EQ0h1K1ljQT09.1_WO2tAMqyXADqSL58-4vz_0OaKYHfXqzPNL6X4YavA"}, {"host", "localhost:4000"}, {"referer", "http://localhost:4000/"}, {"upgrade-insecure-requests", "1"}, {"user-agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36"}], request_path: "/", resp_body: nil, resp_cookies: %{}, resp_headers: [{"cache-control", "max-age=0, private, must-revalidate"}, {"x-request-id", "2m5v5koo0rh6139r0s002b44"}, {"x-frame-options", "SAMEORIGIN"}, {"x-xss-protection", "1; mode=block"}, {"x-content-type-options", "nosniff"}, {"x-download-options", "noopen"}, {"x-permitted-cross-domain-policies", "none"}, {"cross-origin-window-policy", "deny"}], scheme: :http, script_name: [], secret_key_base: :..., state: :unset, status: nil}, content: {:safe, ["<div id=\"", "phx-h0+E+E9pIT8=", "\"\n   data-phx-view=\"", "LiveTestWeb.RoomLive", "\"\n    data-phx-session=\"", "SFMyNTY.g3QAAAACZAAEZGF0YW0AAACIZzNRQUFBQUVaQUFDYVdSdEFBQUFFSEJvZUMxb01DdEZLMFU1Y0VsVU9EMWtBQXB3WVhKbGJuUmZjR2xrWkFBRGJtbHNaQUFIYzJWemMybHZiblFBQUFBQVpBQUVkbWxsZDJRQUdFVnNhWGhwY2k1RVlXbHplVmRsWWk1U2IyOXRUR2wyWlE9PWQABnNpZ25lZG4GANaOQn5pAQ.wLi6SpYsIRMOAaD5qf00Tv334Ou-0RS5jZYi4vQMxK8", "\">\n  ", ["  Current temperature:\n"], "\n</div>\n<div class=\"phx-loader\"></div>\n"]}, current_member: nil,member_token: "SFMyNTY.g3QAAAACZAAEZGF0YW0AAAAiZ3Vlc3QtV2d5MVpOQWx0VWdmWXh2bnFFTElRdlo5ZExvPWQABnNpZ25lZG4GANaOQn5pAQ.eC3VCS6FLECsoWjYa851Njabig5CgtpNkZsZMbxT548", view_module: Phoenix.LiveView.Controller, view_template: "head.template.html"})
        (live_test) lib/live_test_web/templates/layout/app.html.eex:8: LiveTestWeb.LayoutView."app.html"/1
        (phoenix) lib/phoenix/view.ex:399: Phoenix.View.render_to_iodata/3
        (phoenix) lib/phoenix/controller.ex:729: Phoenix.Controller.__put_render__/5
        (phoenix) lib/phoenix/controller.ex:746: Phoenix.Controller.instrument_render_and_send/4
        (live_test) lib/live_test_web/controllers/member_controller.ex:1: LiveTestWeb.PageController.action/2
        (live_test) lib/live_test_web/controllers/member_controller.ex:1: LiveTestWeb.PageController.phoenix_controller_pipeline/2
        (live_test) lib/live_test_web/endpoint.ex:1: LiveTestWeb.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:275: Phoenix.Router.__call__/1
        (live_test) (truncated)
[info] Replied phoenix:live_reload :ok

**Comment by chrismccord** [comment]
Can you please include:

1) the entire stack trace
2) the logs of your request that triggered this

I'm assuming this was from a real request? Was in a test or calling render yourself directly? Thanks!

**Comment by chrismccord** [comment]
Bah, sorry. I actually thought this was the *phoenix* issue tracker :D

In addition to above, can you share your entire view and template?

**Comment by jamilabreu** [comment]
`defmodule LiveTestWeb.PageView do
  use LiveTestWeb, :view
end`

PageController Action
`def index(conn, _params) do
    # render(conn, "index.html")
    Phoenix.LiveView.Controller.live_render(conn, LiveTestWeb.RoomLive, session: %{})
end`

LiveView
`defmodule LiveTestWeb.RoomLive do
  use Phoenix.LiveView

  def render(assigns) do
    ~L"""
      Current temperature: <%= @temperature %>
    """
  end

  def mount(_session, socket) do
    {:ok, assign(socket, :temperature, 1)}
  end
end
`
Removing render_existing from app.html head removes the error.

**Comment by jamilabreu** [comment]
Template
```
<div>
  Test
  <%= live_render(@conn, LiveTestWeb.PageLive, session: %{}) %>
</div>
```

**Comment by chrismccord** [comment]
This is fixed on master. For now there will be no LiveView module support for `render_existing`, which applies to Phoenix.View's. Any calls to render_existing in the shared eex layout for a live_render, will now return nil so it happily plays along.
