### ISSUE TITLE
LiveView does not handle correctly UTF8 URIs

### ISSUE THREAD

**Issue by StormBytePP** [phoenixframework/phoenix_live_view#520]
**Environment**

- Elixir version (elixir -v): v1.9.4 Erlang/OTP 22
- Phoenix version (mix deps): v1.4.11
- Phoenix LiveView version (mix deps): ref 57f2ef7
- NodeJS version (node -v): v13.2.0
- NPM version (npm -v): v6.13.1
- Operating system: Gentoo Linux (amd64, Kernel-5.2.0)

I have setup a multilanguage test, with several rutes using UTF8 URIs, like for example (from mix phx.routes):
```
....
....
live_path  GET  /ru/автоматизмы                        Phoenix.LiveView.Plug MyProjectWeb.Website.Automatic.Live
```

But when I try to live_link to that page, I always get a message:
```
** (ArgumentError) cannot invoke handle_params nor live_redirect/live_link to "http://localhost:4000/ru/%D0%B0%D0%B2%D1%82%D0%BE%D0%BC%D0%B0%D1%82%D0%B8%D0%B7%D0%BC%D1%8B" because it isn't defined in MyProjectWeb.Router
```

This works in "normal" (non LV) controllers, so I think live_link/live_redirect should decode the URL before looking at routes.

Same issue happens when entering manually the URI `http://localhost:4000/ru/автоматизмы` in browser and that page is rendered via `live/3` macro, not happenning when target page is a normal view within a normal controller, even in this usecase.

**Comment by StormBytePP** [comment]
@josevalim here you can find a minimal example of this missbehavior:

https://github.com/StormBytePP/LV-issue-5520-example

After clone, just run `mix deps.get && npm install --prefix assets && mix phx.server` for running the server, then point your browser to http://localhost:4000

Observe how the handling of that example UTF8 URI is completelly failing.

Thanks for the attention.

**Comment by josevalim** [comment]
Fantastic! Thanks for the app. I saw your PR as well. My concern with your PR is that the code path you change is called both by Phoenix inner routes and by the LiveView client, so I am afraid we may end-up double decoding Phoenix inner routes. Which is why I think maybe decoding on the client, if at all possible, is the best option. :)

**Comment by StormBytePP** [comment]
> Fantastic! Thanks for the app. I saw your PR as well. My concern with your PR is that the code path you change is called both by Phoenix inner routes and by the LiveView client, so I am afraid we may end-up double decoding Phoenix inner routes. Which is why I think maybe decoding on the client, if at all possible, is the best option. :)

Thanks for looking into this issue, for nowadays websites it is a blockstopper, however, for me JS is the _language of mordor which I won't use here_ so I can't help more on that front.
