### ISSUE TITLE
Wrong Phoenix.Socket.Serializer used on Heroku

### ISSUE THREAD

**Issue by ream88** [phoenixframework/phoenix_live_view#523]
### Environment

* Elixir version (elixir -v): Elixir 1.9.4 (compiled with Erlang/OTP 20)
* Phoenix version (mix deps): 1.4.11
* Phoenix LiveView version (mix deps): 0.4.1
* NodeJS version (node -v): v10.11.0
* NPM version (npm -v): 6.4.1
* Operating system: macOS Catalina 10.15.1

### Actual behavior

I cross post this here from Elixir forum: https://elixirforum.com/t/weird-error-with-phoenix-live-view-on-heroku/27396

---

I'm getting a super weird error when deploying an app with `phoenix_live_view` on Heroku: 

```
09:33:03.143 [error] Ranch listener ReporterWeb.Endpoint.HTTP had connection
process started with :cowboy_clear:start_link/4 at #PID<0.576.0> exit with
reason: {:function_clause, [{Phoenix.Socket.Message, :from_map!, [["8", "8",
"lv:phx-oZOgz4XU", "phx_join", nil]], []}, {Phoenix.Socket, :__in__, 2, [file:
'lib/phoenix/socket.ex', line: 564]}, {Phoenix.Endpoint.Cowboy2Handler,
:websocket_handle, 2, [file: 'lib/phoenix/endpoint/cowboy2_handler.ex', line:
93]}, {:cowboy_websocket, :handler_call, 6, [file:
'/tmp/build_cae110e886c5c6dcb00c2dec21bb2a2f/deps/cowboy/src/cowboy_websocket.erl',
line: 482]}, {:cowboy_http, :loop, 1, [file:
'/tmp/build_cae110e886c5c6dcb00c2dec21bb2a2f/deps/cowboy/src/cowboy_http.erl',
line: 231]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line:
249]}]}
```

It looks like for whatever reason when running the live view socket on Heroku, it uses `Phoenix.Socket.V1.JSONSerializer` instead of `Phoenix.Socket.V2.JSONSerializer`. However another (older socket before I implemented live view) does use `Phoenix.Socket.V2.JSONSerializer`!

### Expected behavior

Live View should work 😉

**Comment by chrismccord** [comment]
Sounds like you have a javascript asset on heroku that is serving up an old phoenix.js channels client. Can you verify you are using the latest phoenix.js, and that your heroku assets have been redeployed/busted cache/etc? Thanks!

**Comment by ream88** [comment]
Hey @chrismccord thx for the quick answer. Yep busted everything, still the same error. What's also a bit weird, the `socket` directive allows me to set a custom `:serializer`, but this setting was completely ignored!

**Comment by chrismccord** [comment]
The client is the one that sends the protocol version, so it must be an outdated client making the requests.

**Comment by ream88** [comment]
I think the versions are up to date, at least this is in the Heroku build log:

```
remote:        phoenix@1.4.11 /tmp/build_ab274a3de2d6b5eb593c5c95185406f1/node_modules/phoenix
remote:        phoenix_html@2.13.3 /tmp/build_ab274a3de2d6b5eb593c5c95185406f1/node_modules/phoenix_html
remote:        phoenix_live_view@0.4.1 /tmp/build_ab274a3de2d6b5eb593c5c95185406f1/node_modules/phoenix_live_view
```

**Comment by chrismccord** [comment]
Is this something you can trigger yourself via your own browser tab, or errors that appear in the logs from other clients?

**Comment by ream88** [comment]
I'm not 100% what do you mean with that. But I have the same problem in different browsers on different machines.

**Comment by ream88** [comment]
One thing I see in the logs is that the live view endpoint is missing the `vsn=2.0.0` param, which is exactly what you told me:

Included here:
```
2019-12-06T16:39:53.302828+00:00 heroku[router]: at=info method=GET
path="/socket/websocket?vsn=2.0.0" host=**********.com
request_id=9fdd5552-f272-4410-8e81-0e1dd55894cd fwd="***.***.***.***" dyno=web.1
connect=1ms service=53ms status=101 bytes=234 protocol=https
```

Missing here:
```
2019-12-06T16:39:53.364129+00:00 heroku[router]: at=info
method=GET path="/live/websocket" host=**********.com
request_id=b178080f-9b3a-4c1d-a598-f91bcb982b89 fwd="***.***.***.***" dyno=web.1
connect=1ms service=70ms status=101 bytes=234 protocol=https

```

**Comment by ream88** [comment]
Omg, I got it working. AWS CloudFront was striping the param, but only for the one path…. Really weird. Thx a lot @chrismccord for helping me to get on the right track here! The Phoenix/Elixir community is just great! 😊

**Comment by ream88** [comment]
**UPDATE:**

The live view socket pointed to a relative path at `/live`, which used the CF domain and the custom one pointed to an absolute path at Heroku and skipped CF completely. Thats the reason why my custom one worked, and the live view one had problems.
