### ISSUE TITLE
Heroku Deployment Failing

### ISSUE THREAD

**Issue by azuby** [phoenixframework/phoenix_live_view#526]
### Environment
* Elixir version: 1.9.1
* Phoenix version: 1.4.11
* Phoenix LiveView version: `{:phoenix_live_view, github: "phoenixframework/phoenix_live_view"}` (57f2ef73859a36dee634db3e1e3be2b4ce6ceec9)
* NodeJS version: 12.7
* Yarn version: 1.17.3
* Operating system: Heroku

### Actual behavior
When deploying to Heroku with essentially the same code (same live view commit sha), deployments are now failing.

Buildpacks:
`https://buildpack-registry.s3.amazonaws.com/buildpacks/hashnuke/elixir.tgz`
`https://github.com/gjaldon/heroku-buildpack-phoenix-static.git`

Output:
```
remote:        * MIX_ENV=prod
remote:
remote: -----> Installing binaries
remote:        Using cached node 12.7.0...
remote:        Installing Node 12.7.0...
remote:        Using default npm version
remote: Downloading and installing yarn 1.17.3...
remote: Installed yarn 1.17.3
remote:
remote: -----> Building dependencies
remote:        Installing and caching node modules
remote: yarn install v1.17.3
remote: [1/4] Resolving packages...
remote: [2/4] Fetching packages...
remote: info fsevents@1.2.9: The platform "linux" is incompatible with this module.
remote: info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
remote: [3/4] Linking dependencies...
remote: [4/4] Building fresh packages...
remote: Done in 19.38s.
remote: cp: cannot create regular file '/app/tmp/cache/node_modules/phoenix_live_view/.git/objects/pack/pack-e1282fd36b7cceb9c3764befee2c8f0c6d469838.idx': Permission denied
remote: cp: cannot create regular file '/app/tmp/cache/node_modules/phoenix_live_view/.git/objects/pack/pack-e1282fd36b7cceb9c3764befee2c8f0c6d469838.pack': Permission denied
remote:  !     Push rejected, failed to compile Phoenix app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !	Push rejected
```

**Comment by josevalim** [comment]
So the issue seems to be that there are `.git` files inside your phoenix_live_view checkout. The assets buildpack [have some configuration](https://github.com/gjaldon/heroku-buildpack-phoenix-static), try enabling clean_cache and remove_node.

**Comment by azuby** [comment]
I'm not sure what changed between builds but changing the two settings resolved the issue. Thanks @josevalim!
