### ISSUE TITLE
Warn when there is no socket connection

### ISSUE THREAD

**Issue by StormBytePP** [phoenixframework/phoenix_live_view#527]
While doing an example, I just forgot the line of `liveSocket.connect();` inside app.js file.

This made strange errors in JS browser with live_links, like this one:

`phoenix_live_view.js:780 Uncaught TypeError: Cannot read property 'pushInternalLink' of null
    at eval (phoenix_live_view.js:780)`

Connecting a socket is a basic thing, but also it is easy to be forgotten (specially if you follow the instructions at [CHANGELOG.md](https://github.com/phoenixframework/phoenix_live_view/blob/master/CHANGELOG.md) file, where there is no connect line at all)

I think that warning the user that socket was not connected is way better than JS null errors on runtime.

**Comment by ChristopheBelpaire** [comment]
I also have this error if I follow link, and then try to click on a live_link.
It seems the live_link are broken when a link is clicked.
Is there any workaround ?
