### ISSUE TITLE
UI Composition

### ISSUE THREAD

**Issue by nocivus** [phoenixframework/phoenix_live_view#531]
Hi guys, sorry for the open question (the forums would probably be a better place), but i was wondering if you have any plans to somehow support UI composition using live view. It would be amazing to be able to render remote live views inside another project and be able to have a true multi-service inside a common interface. 

Like imagine you have a shopping cart icon live view, that is present in the layout of your main app, but is actually rendering from the shopping-cart phoenix server that you have running on a completely different server/service. I see this as being super useful in not having giant phoenix live view monoliths.

Is it something in the pipeline?

Cheers!

**Comment by chrismccord** [comment]
Forum is the better place for such discussions. Thanks!
