### ISSUE TITLE
Problem tainting local bindings within a comprehension

### ISSUE THREAD

**Issue by mcrumm** [phoenixframework/phoenix_live_view#532]
### Environment

* Elixir version (elixir -v): Erlang/OTP 22 [erts-10.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Elixir 1.8.2 (compiled with Erlang/OTP 22)

* Phoenix version (mix deps): 1.4.11
* Phoenix LiveView version (mix deps): 806016b
* NodeJS version (node -v): v10.16.0
* NPM version (npm -v): 6.9.0
* Operating system: macOS

### Actual behavior

There seems to be a problem tainting local bindings within a comprehension. I put together an example app to illustrate the problem. This isn't normally how I would setup the logic for something like this, but it mimics some code in the wild that was exhibiting this unexpected behavior: https://github.com/mcrumm/lv_local_for_issue

In the example, there are three checkboxes, one for each **Red**, **Green**, **Blue**.

The visibility of the swatches is driven by the currently selected shades, but also the state of the checkboxes is driven by the visibility of the colors. It's a little circular, but it illustrates the unexpected behaviour.

![local_binding](https://user-images.githubusercontent.com/168677/70854544-2a1efb80-1e72-11ea-913f-c36f78182065.gif)

### Expected behavior

If you change this line in the example app: 
https://github.com/mcrumm/lv_local_for_issue/blob/3fb573935c9d297b46494ea29c5358924fc75477/lib/my_app_web/templates/page/palette.html.leex#L8

to use `@changeset` instead of `f.source`, the checkboxes are rendered in the expected way:

![local_binding_not](https://user-images.githubusercontent.com/168677/70854546-31460980-1e72-11ea-8e7a-8ab88974a3c5.gif)

So it seems the issue is with the reference to `f` within the comprehension, as `f.source` and `@changeset` point to the same data.

Thanks!

**Comment by snewcomer** [comment]
@mcrumm I'm seeing this work correctly with both the `@checkbox` and `f.source` with the latest master (since 0.4.1).  Could probably do a git bisect to see which commit since then fixed it!  (importantly I'm seeing the `checked` property being updated)

**Comment by josevalim** [comment]
Solved in master, most likely on e870e9b177043c303091ebb13d574bac7aade527, when I refactored the engine. In the future, feel free to ping me on any engine related issue!
