### ISSUE TITLE
Discussion: Remove deprecated keyboard event values

### ISSUE THREAD

**Issue by joshprice** [phoenixframework/phoenix_live_view#536]
As mentioned in #535, `charCode`, `keyCode`, and `which` are all deprecated, poorly supported cross-browser and should not be relied on.

See https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent#Browser_compatibility for more details on this.

I can't think of a valid use case for these values in new applications and the advice from MDN is to not use for new applications anyway.

I don't think we should be returning these at all. It's somewhat misleading and also confusing to determine the correct key/value to use.

Deprecation isn't really an option in the returned map, so docs will have to serve as the guide here until they are removed.

Happy to make a PR to remove these values and update the relevant docs, if there is agreement on this.

**Comment by snewcomer** [comment]
@joshprice Great point.  I added a PR so we could add development deprecations!  I think once that is in, this would be a phenomenal idea.

**Comment by joshprice** [comment]
Thanks! I saw the PR, but not yet sure how we'd show deprecation warnings when using the various event fields via a DEBUG flag.

Since LiveView is still pre-1.0 I'd imagine "proper" deprecation is not such a concern right now. However we definitely need a way to solve for this once a stable release is cut.

In terms of this issue though, I think the right thing to do is to remove the deprecated options and add a release note for upgrading. This nudges users in the right direction sooner.

I'll put a PR together so we can discuss something more concrete.

**Comment by joshprice** [comment]
Have opened a draft PR #538 for further discussion, I still can't quite see how the deprecation you're thinking of might work though.
