### ISSUE TITLE
session causing connect failures for initial requests

### ISSUE THREAD

**Issue by mcrumm** [phoenixframework/phoenix_live_view#540]
### Environment

* Elixir version (elixir -v): Elixir 1.9.0 (compiled with Erlang/OTP 22)
* Phoenix version (mix deps): 1.4.11
* Phoenix LiveView version (mix deps): 26a9d572
* NodeJS version (node -v): v12.13.1
* NPM version (npm -v): 6.12.1
* Operating system: MacOS Mojave/Ubuntu

### Actual behavior

Even with the proper session configuration, on a first-time request that results in a LiveView.Socket connection, since the user has no existing session/cookie, `connect/3` will fail until the point of the first page reload, which will likely be triggered by the backoff in LiveView JS itself:

![lvs_force_reload](https://user-images.githubusercontent.com/168677/71237203-c0f61880-22b5-11ea-9f44-0465f230878a.gif)

We're seeing this repeated ~10 times per initial request:

```
2019-12-20 07:05:20.344 [error] LiveView session was misconfigured or the user token is outdated.

1) Ensure your session configuration in your endpoint is in a module attribute:

    @session_options [
      ...
    ]

2) Change the `plug Plug.Session` to use said attribute:

    plug Plug.Session, @session_options

3) Also pass the `@session_options` to your LiveView socket:

    socket "/live", Phoenix.LiveView.Socket,
      websocket: [connect_info: [session: @session_options]]

4) Define the CSRF meta tag inside the in <head> in your layout:

    <%= csrf_meta_tag() %>

5) Pass it forward in your app.js:

    let csrfToken = document.querySelector("meta[name='csrf-token']").getAttribute("content");
    let liveSocket = new LiveSocket("/live", Socket, {params: {_csrf_token: csrfToken}});
```

### Expected behavior

Looking for guidance here to help provide a fix. At the moment, there doesn't appear to be enough context from the Transport to determine at connect time whether or not we're looking at an initial request or an invalid session.  If this is a necessary evil, and there's really no way to decide if we're the 🐤 or the 🥚 , then perhaps we could have a way to silence the error if we're confident our configuration is up-to-date?

I'd be happy to provide more context if it would help.  Thanks!

**Comment by mcrumm** [comment]
After digging further, this issue appears to only surface if you clear cookies and refresh the current browser tab, or clear cookies and click back or forward.

If, instead, you clear cookies, open a new browser tab, and navigate to the page, no errors are emitted and the socket connects on the first attempt.

**Comment by chrismccord** [comment]
This only happens when cookies are cleared and a websocket connection is re-established before refreshing the page, which should be extremely rare and is self recovering. Thanks! 7eb0db69bede7a730baf475725acc5ebec6f66d5
