### ISSUE TITLE
Documentation for `render_component` is potentially misleading

### ISSUE THREAD

**Issue by JonRowe** [phoenixframework/phoenix_live_view#545]
### Environment

* Elixir version (elixir -v): 1.9.4
* Phoenix version (mix deps): 1.4.11
* Phoenix LiveView version (mix deps): 0.4.1
* NodeJS version (node -v): 10.16.3
* NPM version (npm -v): 6.9.0
* Operating system: MacOS

### Expected behaviour

The documentation examples show lists being used:

```
assert render_component(MyComponent, id: 123, user: %User{}) 
```

### Actual behaviour

The functions require maps to be used if you wish to pattern match in your render function:

e.g.

```
def render(%{id: nil} = assigns), do: ~L""
```

```
assert render_component(MyComponent, %{id: 123, user: %User{}}) 
```

As assigns will always (? at least in my app) be a map in "reality" perhaps they should be documented as such? There is nothing doing any conversion in the test utils (so an alternative fix would be to make render_component convert the list to a map?)

**Comment by snewcomer** [comment]
@JonRowe 👋 This is using [Keyword](https://elixir-lang.org/getting-started/keywords-and-maps.html) lists for the "options".  Across the Elixir ecosystem, keyword lists are often used instead of maps when you may have an incomplete set of items (the last argument is often one).  A map requires you to potentially pattern match on the keys.  With keyword lists, `assigns` (the options) `(..., id: 123, user: %User{})` would be pattern matched like so - `[id: 123, user: %User{}]`.  So you can use either maps or keyword lists if you like!

Let me know if you have any other questions or if I didn't explain something well enough.

**Comment by JonRowe** [comment]
@snewcomer :wave: I'm aware of what a keyword list is, this issue is that this: 

```
 <%= live_component(@socket, List, items: @items) %>
```

Becomes:

```
def render(%{items: items} = assigns), do ~L""
```

So you *must* use (if you want to pattern match):

```
render_component(List, %{items: items})
```

Where as:

```
render_component(List, items: items)
```

Will call (the equivalent of):

```
def render([items: items] = assigns), do ~L""
```

Which as far as I've been able to tell *never* happens in reality.

There is a disparity between the test helper, and what happens in a real live view. 

So in the best case scenario the documentation is misleading by using the wrong type, in the worst case scenario the test helper is misleading by using the wrong type.

**Comment by snewcomer** [comment]
Oh that is good!  Sorry for the winded explanation ;).  Perhaps I need refinement in my understanding.  In my own examples, I'm see that whether a keyword list or map, the `assigns` passed to `render` is always a map whether using the test helper or `live_component/3`  We have some tests [here](https://github.com/phoenixframework/phoenix_live_view/blob/master/test/phoenix_live_view/integrations/components_test.exs#L157) with both cases as well as a `live_component` [test](https://github.com/phoenixframework/phoenix_live_view/blob/v0.4.1/test/phoenix_live_view/diff_test.exs#L350).  More specifically, this [line](https://github.com/phoenixframework/phoenix_live_view/blob/v0.4.1/lib/phoenix_live_view/utils.ex#L219) will add keyword list items to the socket assigns as a map.

One question I can think of is - Do you define an `update(assigns, socket)` callback and how are you assigning items to the `socket`?  Also, just to check have you cleared cache and reinstalled the dependencies? `mix deps.clean --all && mix deps.get`?  

If you happen to have a sample repo or a test to add to this repo, it could help in debugging this issue!

**Comment by JonRowe** [comment]
Thanks @josevalim :)
