### ISSUE TITLE
Bug: Selects don't get values from an updated changeset programmatically.

### ISSUE THREAD

**Issue by feliperenan** [phoenixframework/phoenix_live_view#547]
### Environment

* Elixir version: 1.8.1
* Phoenix version:  1.4.9
* Phoenix LiveView version: master
* NodeJS version (node -v): 10-4.0
* NPM version (npm -v): 6.1.0
* Operating system: Mac OS

### Actual behavior

This issue happens when we try to update others input's value from an specific input. Let's say we want to change the value from Input B, C, D, etc... when the user changes the Input A. If the input B is a select input, it doesn't work.

![2020-01-03 11 35 58](https://user-images.githubusercontent.com/27698968/71716463-81830c80-2e1d-11ea-878e-0af5f381b7de.gif)

⚠️ Notice that all values are updated, even the multiple-select. The issue seems to be only with select input.

### How to reproduce the issue?
This issue is reproduced on this repo: https://github.com/feliperenan/phoenix_live_view_example (last commit). After installing the project, just go to `http://localhost:4000/users/new` and fill the username with any value. 

### Expected behavior
The select value should be changed as well as other input values are. In this example, the color in the select input should be changed to `white` value.

**Comment by feliperenan** [comment]
This is the diff sent by the web socket:

```
["4","10","lv:phx-R0qYSHDrAkE","phx_reply",{"response":{"diff":{"0":{"0":"<form accept-charset=\"UTF-8\" action=\"#\" method=\"post\" phx-change=\"validate\" phx-hook=\"SavedForm\" phx-submit=\"save\"><input name=\"_csrf_token\" type=\"hidden\" value=\"NUQQMC9lBC8aZk4jPxh5OA8AL0gQcjs6y5Jcm7Rfn-yTvrLzjsAeG5qQ\"><input name=\"_utf8\" type=\"hidden\" value=\"✓\">","1":"<label for=\"user_username\">Username</label>","2":"<input id=\"user_username\" name=\"user[username]\" type=\"text\" value=\"felipe\">","3":"","4":"<label for=\"user_email\">Email</label>","5":"<input id=\"user_email\" name=\"user[email]\" type=\"text\" value=\"test@phoenix.com\">","6":"","7":"<label for=\"user_password\">Password</label>","8":"<input id=\"user_password\" name=\"user[password]\" type=\"password\" value=\"secret\">","9":"","10":"<input id=\"user_password_confirmation\" name=\"user[password_confirmation]\" type=\"password\" value=\"\">","11":"","12":"<label for=\"user_phone_number\">Phone number</label>","13":"<input id=\"user_phone_number\" name=\"user[phone_number]\" type=\"text\" value=\"1\">","14":"","15":"<select id=\"user_tags\" multiple=\"\" name=\"user[tags][]\" style=\"width: 100%\"><option value=\"tag-1\">Tag 1</option><option value=\"tag-2\" selected>Tag 2</option><option value=\"tag-3\">Tag 3</option></select>","16":"<select id=\"user_color\" name=\"user[color]\" style=\"width: 100%\"><option value=\"1\" selected>Red</option><option value=\"2\">Blue</option><option value=\"3\">White</option></select>"}}},"status":"ok"}]
```

We can see that only the select input didn't have its value updated:

```
<select id=\"user_color\" name=\"user[color]\" style=\"width: 100%\"><option value=\"1\" selected>Red</option><option value=\"2\">Blue</option><option value=\"3\">White</option></select>
```

Maybe it's a engine bug? 🤔 cc @josevalim

**Comment by josevalim** [comment]
This does not look like a bug in LiveView but rather a Phoenix.HTML behaviour. For select, we consider the value currently in `params` to choose a select. That's because the value in the data/changes may have been cast, and therefore we won't find a match. For example, imagine you want to select an ID. An ID is an integer. But in params and inside the select, it will be a string. So  because data may be cast, the value in params takes higher precedence and in this case "red" is always in params, even if you set the change explicitly to "white".

**Comment by feliperenan** [comment]
Ohh, that's make sense. So we can set the value manually to override such behaviour.

```Elixir
select f, :color, [{"Red", "red"}, {"Blue", "blue"}, {"White", "white"}], value: input_value(f, :color)
```

Thanks 👍
