### ISSUE TITLE
Nested live_component in calls in templates are not covered by coveralls 

### ISSUE THREAD

**Issue by elbow-jason** [phoenixframework/phoenix_live_view#548]
### Environment

* Elixir version (elixir -v): `Elixir 1.9.0 (compiled with Erlang/OTP 22)`
* Erlang/OTP version: `22.0.7`
* Phoenix version (mix deps): `"~> 1.4.9"`
* Phoenix LiveView version (mix deps): `github: "phoenixframework/phoenix_live_view", ref: "7eb0db6"`
* NodeJS version (node -v): `v12.13.1`
* NPM version (npm -v): `6.12.1`
* Operating system: OSX

### Actual behavior

Coveralls is reporting nested `live_component` lines as not covered in leex templates.

### Expected behavior

Coveralls should show coverage for a nested `live_component` in a template when it is covered by a test.

<img width="582" alt="Screen Shot 2020-01-02 at 3 48 46 PM" src="https://user-images.githubusercontent.com/4923601/71740435-6dd5a700-2e19-11ea-8091-739c95858257.png">

**Comment by chrismccord** [comment]
I'd love for someone to take a look at this, but this is not going to be a priority for me any time soon, so closing for now. Thanks!
