### ISSUE TITLE
Canceling a `beforeunload` prompt invokes `mount/2`

### ISSUE THREAD

**Issue by aptinio** [phoenixframework/phoenix_live_view#550]
### Environment

* Elixir version (elixir -v): Elixir 1.9.4 (compiled with Erlang/OTP 22)
* Phoenix version (mix deps): 1.4.11
* Phoenix LiveView version (mix deps): 0.4.1 locked at 8ff349e
* NodeJS version (node -v): v13.5.0
* NPM version (npm -v): 6.13.4
* Operating system: GNU/Linux

### Actual behavior

We're trying to implement a **"Leave site? Changes you made may not be saved."** prompt. Everything is working nicely with these changes:

**`app.js`**
```javascript
let Hooks = {};

Hooks.BeforeUnload = {
  hasChanged() {
    return this.el.dataset.hasChanged === "true";
  },
  mounted() {
    window.addEventListener("beforeunload", e => {
      if (this.hasChanged()) {
        e.preventDefault();
        e.returnValue = "";
      }
    });
  }
};

let liveSocket = new LiveSocket("/live", Socket, { hooks: Hooks });
```

**`form.html.leex`**
```eex
<%= f =
      form_for(@changeset, "#",
        phx_change: :changed,
        phx_submit: :submitted,
        phx_hook: "BeforeUnload",
        data: [has_changed: !Enum.empty?(@changeset.changes)]
      ) %>
```

However, when the user cancels the prompt, `mount/2` is invoked and the form changes get discarded, which defeats the purpose of the prompt.

The logs show this after canceling the prompt:

```
[info] CONNECTED TO Phoenix.LiveView.Socket in 260µs
```

### Expected behavior

When the user cancels the prompt, `unload` event is canceled and the form changes are kept.

**Comment by aptinio** [comment]
Here's a sample repo that reproduces the issue: https://github.com/aptinio/phx_lv_550. I hope this helps.

**Comment by feliperenan** [comment]
it happens because Phoenix Socket closes the websocket connection even though the User doesn't leave the page:

https://github.com/phoenixframework/phoenix/blob/b93fa36f040e4d0444df03b6b8d17f4902f4a9d0/assets/js/phoenix.js#L768

I've done some tests and removing that line I got the `Hooks.BeforeUnload` working as expected. In order to fix that, I think we should somehow check if the user stayed on the page - when he clicks on the cancel button - and don't close the connection.

**Comment by feliperenan** [comment]
What about if we use `unload` instead of `beforeunload` in order to close the connection? :thinking:I tested it here and it also works, but I'm not sure if that's ok since I'm not familiar with those events.

@chrismccord  you might have some thoughts on this since you've introduced this approach on Phoenix channel :raised_hands: :

**Comment by aptinio** [comment]
> What about if we use `unload` instead of `beforeunload` in order to close the connection?

I thought this doesn't work until I realized I was changing `phoenix_live_view.js` instead of `phoenix.js`. :sweat_smile: 

I think using `unload` makes sense. According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/unload_event):

> It is fired after:
>
> - `beforeunload` (cancelable event)
> - `pagehide`
>
> The document is in the following state:
>
> - All the resources still exist (img, iframe etc.)
> - Nothing is visible anymore to the end user
> - UI interactions are ineffective (`window.open`, `alert`, `confirm`, etc.)
> - An error won't stop the unloading workflow

**Comment by chrismccord** [comment]
`unload` works, but I need to release a new phoenix to make it happen, so stand by for Phoenix v1.4.12 sometime tomorrow. Thanks!

**Comment by aptinio** [comment]
Awesome! Thanks @feliperenan and @chrismccord! :heart:

**Comment by chrismccord** [comment]
This has been fixed in Phoenix 1.4.12 and LV 0.6.0. Thanks!

**Comment by dgigafox** [comment]
@chrismccord I tried this with Phoenix 1.5.9 and LV 0.15.5 but when I cancel the prompt, it still re-mounts the LiveView. What did I miss?

**Comment by pludlum** [comment]
I just ran into this as well on Phoenix 1.5.9 and LiveView 0.15.7. It looks like this behavior was reintroduced as a result of [this issue](https://github.com/phoenixframework/phoenix_live_view/issues/1425). 

Is there a way we can prevent the instability described by the above issue while still allowing the `beforeunload` event to be cancellable?

**Comment by chrismccord** [comment]
We no longer is beforeunload so this won’t be an issue for you in the next release
