### ISSUE TITLE
Race condition exposes bug in client-side javascript

### ISSUE THREAD

**Issue by brainlid** [phoenixframework/phoenix_live_view#555]
### Environment

* Elixir version (elixir -v): 1.9.1-otp-22
* Phoenix version (mix deps): 1.4.11
* Phoenix LiveView version (mix deps): `master`
* NodeJS version (node -v): 12.14.0
* NPM version (npm -v): 6.13.4
* Operating system: Ubuntu LTS

### Actual behavior

I don't have an easy way to create a small reproducible bug. But I can describe the situation and identify the line of javascript code with the issue.

The bug is in with this line: https://github.com/phoenixframework/phoenix_live_view/blob/master/assets/js/phoenix_live_view.js#L930

```javascript
targetContainer = container.querySelector(`[${PHX_COMPONENT}="${targetCID}"]`).parentNode
```
A race condition creates a situation where the following line results in a `null`. The above line tries to call `parentNode` on this and it isn't found. It was already removed from the DOM.

```javascript
container.querySelector(`[${PHX_COMPONENT}="${targetCID}"]`)
```

#### Situation

```
LiveView
    |
live_component
    |
live_component
    |
list of live_components - OptionEditor
```

When a text input is used in the OptionEditor component, using Hooks, hitting "ENTER" triggers a `this.pushEvent("save", {})` call. It triggers an event to save. This results in the component on the server issuing a `send(self(), {:update_item, updated_item})` and the component changes its _own_ state to leave "edit" mode which **removes the input**.

The parent LiveView receives the event which triggers a re-render of the item being edited. At some point, the morphdom instructions for changes being sent from the component's own state change plus the parent LiveView state change end up conflicting and the javascript error is encountered.

### Expected behavior

Be resilient to potentially async DOM changes from the server and handle not finding a `parentNode`.

### Workaround

Avoid the race condition using a `Process.send_after(self(), message, 100)`

**Comment by benwilson512** [comment]
Can confirm we're also running into this. Here's our problem code:

```
<%= if @chart_data do %>
<% limits = limits_for_zone(@context, @zone) %>
<div class="columns is-gapless">
  <div class="column">
    <div class="chart-container">
      <canvas phx-update="ignore" id="zone-chart" class="zone-chart" data-upper-limit="<%= limits[:upper_limit] %>"
        data-lower-limit="<%= limits[:lower_limit] %>" data-data='<%= Jason.encode!(@chart_data) %>'
        phx-hook="ZoneChart" data-mode='<%= mode_for_chart(@zone) %>'
        data-fahrenheit="<%= @context.viewer.fahrenheit && @primary_mq.slug == "temperature" %>"
        data-mq-name="<%= @primary_mq.name %>" data-unit="<%= display_unit(@context, @primary_mq.slug) %>">
      </canvas>
    </div>
  </div>
  <div class="column is-narrow">
    <div id="js-legend" class="chart-legend" phx-update="ignore"></div>
  </div>
</div>
<% else %>
<div class="is-fullwidth">Loading Chart Data...</div>
<% end %>
```

The canvas with the hook, and the associated `#js-legend` div are only rendered once `@chart_data` exists, which happens after the initial page load. Once `@chart_data` loads, its hook fires and tries to find `#js-legend` by id, but it's null. If we change the code so that `js-legend` is always on the page, it works:

```
<div class="columns is-gapless">
  <%= if @chart_data do %>
  <% limits = limits_for_zone(@context, @zone) %>
  <div class="column">
    <div class="chart-container">
      <canvas phx-update="ignore" id="zone-chart" class="zone-chart" data-upper-limit="<%= limits[:upper_limit] %>"
        data-lower-limit="<%= limits[:lower_limit] %>" data-data='<%= Jason.encode!(@chart_data) %>'
        phx-hook="ZoneChart" data-mode='<%= mode_for_chart(@zone) %>'
        data-fahrenheit="<%= @context.viewer.fahrenheit && @primary_mq.slug == "temperature" %>"
        data-mq-name="<%= @primary_mq.name %>" data-unit="<%= display_unit(@context, @primary_mq.slug) %>">
      </canvas>
    </div>
  </div>
  <% else %>
  <div class="is-fullwidth">Loading Chart Data...</div>
  <% end %>
  <div class="column is-narrow">
    <div id="js-legend" class="chart-legend" phx-update="ignore"></div>
  </div>
</div>
```
Perhaps an even simpler scenario where we have an issue is with our map:

```
<div phx-update="ignore" id="map-container" class="map-container"
  data-geolocations='<%= Jason.encode!(@map_data) %>' phx-hook="ZoneMap">
</div>
```

initially `@map_data` is null, and then it is asynchronously updated. The hook fires, but no actual dom changes occur until some later change on the page happens.

**Comment by benwilson512** [comment]
Can confirm that this fixed our issue.
