### ISSUE TITLE
Nested LiveViews – TypeError: Cannot read property 'href' of null

### ISSUE THREAD

**Issue by adriankumpf** [phoenixframework/phoenix_live_view#575]
### Environment

* Elixir version (elixir -v): 1.9.4
* Phoenix version (mix deps): 1.4.11
* Phoenix LiveView version (mix deps): 0.5.2
* NodeJS version (node -v): 13.6.0
* NPM version (npm -v): 6.13.4
* Operating system: macOS

### Actual behavior

Opening a page with nested LiveViews produces the following JS error:

```
Uncaught TypeError: Cannot read property 'href' of null
    at eval [as payload] (phoenix_live_view.js:1)
    at e.value (phoenix.js:1)
    at e.value (phoenix.js:1)
    at e.value (phoenix.js:1)
    at e.value (phoenix.js:1)
    at e.value (phoenix.js:1)
    at e.value (phoenix_live_view.js:1)
    at e.value (phoenix_live_view.js:1)
    at eval (phoenix_live_view.js:1)
    at Array.forEach (<anonymous>)
```

Which corresponds to this line: https://github.com/phoenixframework/phoenix_live_view/blob/e4c920738da717e4aa44f6c0528fbe19325a744b/assets/js/phoenix_live_view.js#L1072

With Phoenix LiveView v0.4 the same code works fine.

#### Code

```elixir
defmodule DemoWeb.ChildLive do
  use Phoenix.LiveView

  def render(assigns) do
    ~L"""
    <h1>Child</h1>
    """
  end
end

defmodule DemoWeb.ParentLive do
  use Phoenix.LiveView

  def render(assigns) do
    ~L"""
    <div>
      Parent
      <%= live_render(@socket, DemoWeb.ChildLive, id: :child) %>
    </div>
    """
  end
end
```

**Comment by alanvardy** [comment]
I also encountered this problem with a very similar error message. I found that `<%= csrf_meta_tag() %>` in the `<head>` section needs to be included before `app.js`, otherwise the content of that csrf meta tag cannot be read.

I hope this helps, and will open up a PR for the installation documentation.

**Comment by sfusato** [comment]
I have the same issue. Moving `<%= csrf_meta_tag() %>` before the `.js` file as @alanvardy suggested didn't helped.

**Comment by josevalim** [comment]
Can someone please provide a sample application that reproduces the error? Thank you.

**Comment by sfusato** [comment]
@josevalim https://github.com/sfusato/phx_live_view_052_nested_liveview

**Comment by feliperenan** [comment]
it seems this issue started to happen after this change: https://github.com/phoenixframework/phoenix_live_view/commit/51b147f3d8264a91b2c948c943669ffcef8efda6 which  is a fix for this PR: https://github.com/phoenixframework/phoenix_live_view/pull/437. I'm not completely sure about this solution, but if we change this line:

https://github.com/phoenixframework/phoenix_live_view/blob/959b8f0c7fae91d41d79199458544fcbaaf5fb3d/assets/js/phoenix_live_view.js#L1072

To:

```JS
this.href || this.liveSocket.href
```
it works on the project sent by @sfusato. I'm not sure about that because it seems that `this.main` is present only when the a router is given:

https://github.com/phoenixframework/phoenix_live_view/blob/959b8f0c7fae91d41d79199458544fcbaaf5fb3d/lib/phoenix_live_view/static.ex#L122

My question to validate this solution: Is there any change `this.liveSocket.main.href` return a different url? if so, we might should check for that as well or proper track how the `href` is sent.

**Comment by josevalim** [comment]
@feliperenan does anything break if we don't send `|| this.liveSocket.main.href` at all? You are not supposed to receive the parent href anyway. Child live views have no access to URLs.

**Comment by feliperenan** [comment]
Removing this the child can't mount anymore:

```
iex(6)> [error] GenServer #PID<0.1894.0> terminating
** (MatchError) no match of right hand side value: %{"params" => %{"_csrf_token" => "GUExBQlFDw1ZJCU5KylQOSRBNGAOMh0TnpTkz7u4kUOtaF1hkrA2Afsj"}, "session" => "SFMyNTY.g3QAAAACZAAEZGF0YWgCYQJ0AAAABWQAAmlkbQAAAAVjaGlsZGQACnBhcmVudF9waWRnZAANbm9ub2RlQG5vaG9zdAAAB1wAAAAAAGQACHJvb3RfcGlkZ2QADW5vbm9kZUBub2hvc3QAAAdcAAAAAABkAAdzZXNzaW9udAAAAABkAAR2aWV3ZAAwRWxpeGlyLlBoeExpdmVWaWV3MDUyTmVzdGVkTGl2ZXZpZXdXZWIuQ2hpbGRMaXZlZAAGc2lnbmVkbgYAxqBVxG8B.mDC5apraKKEPjrXSp8GOEbWwqwwDuvyFsq_BeKpbj1k", "static" => nil}
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:516: Phoenix.LiveView.Channel.verified_mount/4
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:34: Phoenix.LiveView.Channel.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:mount, Phoenix.LiveView.Channel}
State: {%{"params" => %{"_csrf_token" => "GUExBQlFDw1ZJCU5KylQOSRBNGAOMh0TnpTkz7u4kUOtaF1hkrA2Afsj"}, "session" => "SFMyNTY.g3QAAAACZAAEZGF0YWgCYQJ0AAAABWQAAmlkbQAAAAVjaGlsZGQACnBhcmVudF9waWRnZAANbm9ub2RlQG5vaG9zdAAAB1wAAAAAAGQACHJvb3RfcGlkZ2QADW5vbm9kZUBub2hvc3QAAAdcAAAAAABkAAdzZXNzaW9udAAAAABkAAR2aWV3ZAAwRWxpeGlyLlBoeExpdmVWaWV3MDUyTmVzdGVkTGl2ZXZpZXdXZWIuQ2hpbGRMaXZlZAAGc2lnbmVkbgYAxqBVxG8B.mDC5apraKKEPjrXSp8GOEbWwqwwDuvyFsq_BeKpbj1k", "static" => nil}, {#PID<0.1880.0>, #Reference<0.2041456244.2422210561.52920>}, %Phoenix.Socket{assigns: %{}, channel: Phoenix.LiveView.Channel, channel_pid: nil, endpoint: PhxLiveView052NestedLiveviewWeb.Endpoint, handler: Phoenix.LiveView.Socket, id: nil, join_ref: "9", joined: false, private: %{session: %{"_csrf_token" => "w1ensrz92qjMJoaQO3uROTny"}}, pubsub_server: PhxLiveView052NestedLiveview.PubSub, ref: nil, serializer: Phoenix.Socket.V2.JSONSerializer, topic: "lv:child", transport: :websocket, transport_pid: #PID<0.1880.0>}}
[error] an exception was raised:
    ** (MatchError) no match of right hand side value: %{"params" => %{"_csrf_token" => "GUExBQlFDw1ZJCU5KylQOSRBNGAOMh0TnpTkz7u4kUOtaF1hkrA2Afsj"}, "session" => "SFMyNTY.g3QAAAACZAAEZGF0YWgCYQJ0AAAABWQAAmlkbQAAAAVjaGlsZGQACnBhcmVudF9waWRnZAANbm9ub2RlQG5vaG9zdAAAB1wAAAAAAGQACHJvb3RfcGlkZ2QADW5vbm9kZUBub2hvc3QAAAdcAAAAAABkAAdzZXNzaW9udAAAAABkAAR2aWV3ZAAwRWxpeGlyLlBoeExpdmVWaWV3MDUyTmVzdGVkTGl2ZXZpZXdXZWIuQ2hpbGRMaXZlZAAGc2lnbmVkbgYAxqBVxG8B.mDC5apraKKEPjrXSp8GOEbWwqwwDuvyFsq_BeKpbj1k", "static" => nil}
        (phoenix_live_view) lib/phoenix_live_view/channel.ex:516: Phoenix.LiveView.Channel.verified_mount/4
        (phoenix_live_view) lib/phoenix_live_view/channel.ex:34: Phoenix.LiveView.Channel.handle_info/2
        (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
        (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

![example](https://user-images.githubusercontent.com/27698968/72751542-8dfeb780-3bc8-11ea-9ee5-0e40dc8939c0.gif)

**Comment by josevalim** [comment]
@feliperenan thanks, can you please try master? And if it works, can you please send a PR that fixes JS?

**Comment by feliperenan** [comment]
There is a pattern match on the URL that is sent to the `Utils.live_link_info!/2`

https://github.com/phoenixframework/phoenix_live_view/blob/959b8f0c7fae91d41d79199458544fcbaaf5fb3d/lib/phoenix_live_view/channel.ex#L516

if we handle this there somehow, we might fix the issue a well:

```Elixir
    %{"params" => connect_params} = params
   # not sure what add as default
    url = Map.get(params, "url", "/")
```

**Comment by josevalim** [comment]
Yeah, that's what I did in master :)

**Comment by feliperenan** [comment]
@josevalim it's fixed. At least I couldn't reproduce the issue anymore. :tada:

**Comment by josevalim** [comment]
Fantastic, please send a PR and I will merge it ASAP!
