### ISSUE TITLE
Nested live view causing crash after upgrade to 0.5.2

### ISSUE THREAD

**Issue by mreishus** [phoenixframework/phoenix_live_view#580]
### Environment

* Elixir version (elixir -v): **Elixir 1.9.4 (compiled with Erlang/OTP 22)**
* Phoenix version (mix deps): **1.4.11**
* Phoenix LiveView version (mix deps): **0.5.2**
* NodeJS version (node -v): **v13.6.0**
* NPM version (npm -v): **6.13.6**
* Operating system: **Arch Linux**

#### Terminal
```
git clone git@github.com:mreishus/demon_spirit_umbrella.git
cd demon_spirit_umbrella
mix deps.get
cd apps/demon_spirit_web/assets/
npm install
cd ../../../
mix phx.server
```
(Current commit hash of mreishus/demon_spirit_umbrella: `65f1bf73c5da`)

No database is used/required, so testing is easy.

#### Browser
- Visit http://localhost:4000/
- You're redirected to http://localhost:4000/session/new. Type any name in the name box and click "Log In as Guest".
- You're redirected to http://localhost:4000/game.
- Open DevTools; observe javascript error: 
  -  firefox: `TypeError: o.liveSocket.main is null`.
  -  chromium: `Uncaught TypeError: Cannot read property 'href' of null`
- Try to type in the chat box in the right.  Either the livesocket has not connected or the chat box doesn't work.

### Actual behavior

Javascript errors in console; chat live view does not work.

### Expected behavior

No errors in console; chat live view does work.

### Where the error is happening

```javascript
export class View {
  constructor(el, liveSocket, parentView, href) {
    this.liveSocket = liveSocket;
    this.parent = parentView;
    this.gracefullyClosed = false;
    this.el = el;
    this.id = this.el.id;
    this.view = this.el.getAttribute(PHX_VIEW);
    this.loaderTimer = null;
    this.pendingDiffs = [];
    this.href = href;
    this.joinedOnce = false;
    this.viewHooks = {};
    this.channel = this.liveSocket.channel(`lv:${this.id}`, () => {
      return {
        url: this.href || this.liveSocket.main.href,  // <-- This Line
        params: this.liveSocket.params(this.view),
        session: this.getSession(),
        static: this.getStatic()
      };
    });
    this.showLoader(LOADER_TIMEOUT);
    this.bindChannel();
  }
```

See the line noted above.  For the outer live view, `this.href` is populated, and the right side of the `||` is not evaluated.  For the inner live view, `this.href` is null, and the right side of the `||` is evaluated.  `this.liveSocket.main` does not exist, so JS crashes.

### Simplest possible fix

```javascript
url: "",   //o.href || o.liveSocket.main.href,
```

Fixes the issue.  It's not missing the url that causes the issue, rather it's the unsafe access causing JS to error and halt execution which is the issue.

### Where Change was Introduced

https://github.com/phoenixframework/phoenix_live_view/pull/473

### Where are the Live Views

`./apps/demon_spirit_web/lib/demon_spirit_web/templates/game/live_index.html.leex` - Outer LV template
`./apps/demon_spirit_web/lib/demon_spirit_web/live/live_game_index.ex` - Outer LV

`./apps/demon_spirit_web/lib/demon_spirit_web/templates/chat/live_index.html.leex` - Inner LV template
`./apps/demon_spirit_web/lib/demon_spirit_web/live/live_chat_index.ex` - Inner LV

**Comment by josevalim** [comment]
Thanks, dup of #575 !
