### ISSUE TITLE
[Feature Request]: Add option to feed LiveView from conn.assigns

### ISSUE THREAD

**Issue by zimt28** [phoenixframework/phoenix_live_view#583]
In my router I have some plugs that just assigns values to the current `conn`. Using the `session: []` option it's possible to feed the LiveView data from the plug, but I cannot see how to do this with data in `conn.assigns`. It would be great if `conn.assigns` could also be passed to the LiveView without putting the data into a session first.

**Comment by benwilson512** [comment]
Hi @zimt28, as I understand it, this isn't possible. The request via websocket for a live render is a completely and 100% independent request from the initial GET request that renders the page statically. They can even be on completely different servers, server A handling the initial GET request, and then server B handling the websocket request. Where would the assigns be such that they could be picked up?

**Comment by josevalim** [comment]
Closing as explained by @benwilson512!
