### ISSUE TITLE
Internal Anchor links on URL cause Jitter

### ISSUE THREAD

**Issue by morgz** [phoenixframework/phoenix_live_view#592]
### Environment

* Elixir version (elixir -v): 1.9.1
* Phoenix version (mix deps): 1.4.10
* Phoenix LiveView version (mix deps): 0.6.0
* NodeJS version (node -v): v12.2.0
* NPM version (npm -v): 6.9.0
* Operating system: osx 10.15.2

### Actual behavior

A link such as http://localhost:4000/#section-1 should load the page and scroll to visible section.

### Expected behavior

On first load http://localhost:4000/#section-1 behaves correctly. However, if you scroll back up to the top of the page and hit reload, the page goes to anchor tag, but then jumps to the top of page. 

Video:
[![IMAGE ALT TEXT](http://img.youtube.com/vi/HZsS2RLnQ8Q/0.jpg)](http://www.youtube.com/watch?v=HZsS2RLnQ8Q "Phx Liveview Bug")

Example Project:
https://github.com/morgz/anchor-internal

Tested in Safari.

* Start the server
* Head to `http://localhost:4000/#section-3`
* Scroll back to top of page
* Hit reload ⌘r
* Page jumps immediately to #section-3, but then on second paint goes back to top of page.

**Comment by chrismccord** [comment]
This is the same general behavior of browsers when you refresh a page that contains an anchor. It will jump to your previous scroll position. If you disable JS and re-run your safari tests, you'll see the same behavior so I don't believe there is anything for us to address here. Thanks!
