### ISSUE TITLE
Double clicking live_links does not follow the link

### ISSUE THREAD

**Issue by benwilson512** [phoenixframework/phoenix_live_view#593]
### Environment

* Elixir version (elixir -v):
Erlang/OTP 22 [erts-10.4.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.9.1 (compiled with Erlang/OTP 22)

* Phoenix version (mix deps):
* Phoenix LiveView version (mix deps):

```
ben:canopy ben$ mix deps|grep phoenix
* phoenix_gen_socket_client 2.1.1 (Hex package) (mix)
  locked at 2.1.1 (phoenix_gen_socket_client) 0432becc
* phoenix_pubsub 1.1.2 (Hex package) (mix)
  locked at 1.1.2 (phoenix_pubsub) 496c303b
* phoenix_html 2.13.3 (Hex package) (mix)
  locked at 2.13.3 (phoenix_html) 850e292f
* phoenix 1.4.12 (Hex package) (mix)
  locked at 1.4.12 (phoenix) b86fa85a
* phoenix_live_reload 1.2.1 (Hex package) (mix)
  locked at 1.2.1 (phoenix_live_reload) 274a4b07
* phoenix_live_view 0.7.0-dev (https://github.com/phoenixframework/phoenix_live_view.git) (mix)
* phoenix_ecto 4.0.0 (Hex package) (mix)
  locked at 4.0.0 (phoenix_ecto) c43117a1
```
* NodeJS version (node -v):
* NPM version (npm -v):
```
ben:canopy ben$ node -v
v12.11.0
ben:canopy ben$ yarn -v
1.17.3
```
* Operating system:
OS X 10.15.2

### Actual behavior

Double clicking a live link does nothing. Double clicking a regular link follows the link. 

### Expected behavior

Is there a good reason to double click a link? No. Still, a live link should feel like a regular link.

In that vein, is there some javascript call that could be made to trigger the browser's "page loading" tab animations and other affordances? Right now there isn't really any feedback when you click a live link. If the page they requested is particularly slow, of the user is on poor internet, it isn't clear that something is loading.

**Comment by benwilson512** [comment]
Updated issue, sorry for the premature submission.

**Comment by josevalim** [comment]
@benwilson512 to be clear, this happens when using live_link to point to another live view, right? Have you checked if the LiveView container adds any special CSS class? Maybe it should?

**Comment by chrismccord** [comment]
> In that vein, is there some javascript call that could be made to trigger the browser's "page loading" tab animations and other affordances? Right now there isn't really any feedback when you click a live link. If the page they requested is particularly slow, of the user is on poor internet, it isn't clear that something is loading.

We set the `phx-discconected` and `phx-connected` classes on the LV container to handle loading states. If you import the following in your app.css:

    @import "../../deps/phoenix_live_view/assets/css/live_view.css";

You'll see a dimmed background on load (and live link clicks) with a spinner centered on the container. We also set   `pointer-events: none;` and `cursor: wait;` which would disallow clicking a live_link while in a loading state, but we still needed the check on the JS side since folks who don't have this style defined will need it. All of this is of course overridable with your own design, but out of the box we have loading states covered :) Thanks!
