### ISSUE TITLE
live_redirect causes full page reload in Firefox

### ISSUE THREAD

**Issue by driv3r** [phoenixframework/phoenix_live_view#600]
### Environment

* Elixir version (elixir -v): Elixir 1.10.0 (compiled with Erlang/OTP 22)
* Phoenix version (mix deps): 1.4.12
* Phoenix LiveView version (mix deps): 7c9bf92 (branch: master)
* NodeJS version (node -v): v12.14.0
* NPM version (npm -v): 6.13.4
* Operating system: Ubuntu 18.04.1
* Browser: Firefox 72.02

### Actual behavior

With the following links:

```elixir
live_redirect("foo", to: Routes.live_path(@socket, MyApp.FooLive)) 
```

I'm getting full page reloads and socket reconnects with given errors in browser console:

```
GET http://localhost:4000/phoenix/live_reload/socket/websocket?vsn=2.0.0 [HTTP/1.1 101 Switching Protocols 8ms]
GET http://localhost:4000/transactions [HTTP/1.1 200 OK 9ms]
Firefox can’t establish a connection to the server at ws://localhost:4000/live/websocket?_csrf_token=KSABK0EzC314Lho9Pnx9OAQIMydFEwg4mFbOyCOH2GVKn3Etsfba4jaA&vsn=2.0.0.
Firefox can’t establish a connection to the server at ws://localhost:4000/phoenix/live_reload/socket/websocket?vsn=2.0.0.
```

Nothing in the server logs.

Works fine when running against
- chromium
- firefox, elixir 1.9.4, and live_view 0.6.0 (also I don't see then the `GET` requests in the console either)

### Expected behavior

There's no page reload when using `live_redirect`

**Comment by josevalim** [comment]
Hi @driv3r! Can you please provide an app that reproduces the error? It will make it easier for us to investigate and fix the issue.

Also, you said Firefox, does it work in other browsers? Thanks.

**Comment by chrismccord** [comment]
I can't recreate locally using Firefox 73, so a minimal example that reproduces would be super helpful. Also please ensure you aren't seeing a asset caching issue or similar. Thanks!

**Comment by driv3r** [comment]
@josevalim like mentioned, looks like in chromium works fine, also with elixir 1.9 + live view 0.6 on firefox 

@chrismccord I've created example repo https://github.com/driv3r/phx_live_view_600 with which I'm able to reproduce the error

when running with `mix phx.server` and opening root path it looks like
![image](https://user-images.githubusercontent.com/641589/73483117-35d16d80-439f-11ea-8a9f-73e1b5d21d94.png)

Then navigation to `Authors` flashes with red (like when liveview process crashes) and produces the following in the console
![image](https://user-images.githubusercontent.com/641589/73483257-67e2cf80-439f-11ea-9730-a8534bfa18b7.png)

Also the logs from phx server

```
[info] Running IssueWeb.Endpoint with cowboy 2.7.0 at 0.0.0.0:4000 (http)
[info] Access IssueWeb.Endpoint at http://localhost:4000

webpack is watching the files…

[info] CONNECTED TO Phoenix.LiveView.Socket in 130µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Connect Info: %{session: %{"_csrf_token" => "xTglETEq89tFNAWqEqkz7S4S"}}
  Parameters: %{"_csrf_token" => "PhsOBy4EJClWD0YLNC9kSQI7DEpVYwUSFOikkPaXn62Mzn38GJg0b01A", "vsn" => "2.0.0"}
[debug] Live reload: priv/static/js/app.js
[debug] Live reload: priv/static/js/app.js
[debug] Live reload: priv/static/css/app.css
[debug] Live reload: priv/static/images/phoenix.png
[debug] Live reload: priv/static/js/app.js
[debug] Live reload: priv/static/css/app.css
[debug] Live reload: priv/static/images/phoenix.png
[debug] Live reload: priv/static/css/app.css
[debug] Live reload: priv/static/images/phoenix.png
Hash: 21ea6f99fd313078d2d7
Version: webpack 4.4.0
Time: 859ms
Built at: 1/30/2020 8:27:03 PM
                Asset       Size       Chunks             Chunk Names
       ../css/app.css   12.2 KiB  ./js/app.js  [emitted]  ./js/app.js
               app.js    106 KiB  ./js/app.js  [emitted]  ./js/app.js
       ../favicon.ico   1.23 KiB               [emitted]  
../images/phoenix.png   13.6 KiB               [emitted]  
        ../robots.txt  202 bytes               [emitted]  
Entrypoint ./js/app.js = ../css/app.css app.js
   [0] multi ./js/app.js 28 bytes {./js/app.js} [built]
[../deps/phoenix/priv/static/phoenix.js] 34.1 KiB {./js/app.js} [built]
[../deps/phoenix_html/priv/static/phoenix_html.js] 2.21 KiB {./js/app.js} [built]
[../deps/phoenix_live_view/priv/static/phoenix_live_view.js] 59 KiB {./js/app.js} [built]
[./css/app.css] 39 bytes {./js/app.js} [built]
[./js/app.js] 531 bytes {./js/app.js} [built]
[./js/live_view.js] 288 bytes {./js/app.js} [built]
    + 3 hidden modules
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!css/app.css:
    Entrypoint mini-css-extract-plugin = *
    [./node_modules/css-loader/dist/cjs.js!../deps/phoenix_live_view/assets/css/live_view.css] 1.82 KiB {mini-css-extract-plugin} [built]
    [./node_modules/css-loader/dist/cjs.js!./css/app.css] 406 bytes {mini-css-extract-plugin} [built]
    [./node_modules/css-loader/dist/cjs.js!./css/phoenix.css] 10.9 KiB {mini-css-extract-plugin} [built]
        + 1 hidden module
[info] GET /
[debug] Processing with Phoenix.LiveView.Plug.Elixir.IssueWeb.CommentsLive/2
  Parameters: %{}
  Pipelines: [:browser]
[info] Sent 200 in 35ms
[info] CONNECTED TO Phoenix.LiveView.Socket in 147µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Connect Info: %{session: %{"_csrf_token" => "xTglETEq89tFNAWqEqkz7S4S"}}
  Parameters: %{"_csrf_token" => "HD4+IyIxKAFwawAwLSsBPXBDAhROKlwgdjYOgempHRtvcjVL52inyyhs", "vsn" => "2.0.0"}
[info] GET /
[debug] Processing with Phoenix.LiveView.Plug.Elixir.IssueWeb.CommentsLive/2
  Parameters: %{}
  Pipelines: [:browser]
[info] Sent 200 in 531µs
[info] CONNECTED TO Phoenix.LiveView.Socket in 123µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Connect Info: %{session: %{"_csrf_token" => "g3tDV_ujq7TfsDKuZ2Isb_Z5"}}
  Parameters: %{"_csrf_token" => "FHgMPT5uIBA0WwQhB3Z9Ewp6e14FCyhCsKxyh1UzElPGt26fPH2-gTrw", "vsn" => "2.0.0"}
[info] GET /authors
[debug] Processing with Phoenix.LiveView.Plug.Elixir.IssueWeb.AuthorsLive/2
  Parameters: %{}
  Pipelines: [:browser]
[info] Sent 200 in 775µs
[info] CONNECTED TO Phoenix.LiveView.Socket in 355µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Connect Info: %{session: %{"_csrf_token" => "g3tDV_ujq7TfsDKuZ2Isb_Z5"}}
  Parameters: %{"_csrf_token" => "FWQ3MycdIzoLeB4MKiAEJyNHGkYTFB5drWCwqBVPzOJjYdORyuS5qKDh", "vsn" => "2.0.0"}
```

**Comment by chrismccord** [comment]
I can't recreate on Firefox 70 or 73 (OS X) with your example app. Everything works as expected. It almost appears that the browser is not catching the link click event or `e.preventDefault()` is failing to stop the link dispatch, but this should not happen. Are you sure you don't have js disabled?

**Comment by chrismccord** [comment]
scratch that, the websocket is connecting so JS is definitely there. Since you are on 72 and 70/73 appear good, I am stumped on this one. Can you try a different FF version or computer as a sanity check? Thanks!

**Comment by snewcomer** [comment]
It oddly seems Firefox is not being explicit about stricter requirements.  My first inclination was it may be a header issue so I checked there.  Found two differences...

### Firefox - not working
![Screen Shot 2020-01-30 at 8 29 44 PM](https://user-images.githubusercontent.com/7374640/73512656-4550b680-439f-11ea-83d6-3bb185d33e1a.png)

![Screen Shot 2020-01-30 at 8 34 01 PM](https://user-images.githubusercontent.com/7374640/73513034-c8bed780-43a0-11ea-9aa8-edf3adb1c8de.png)


### Brave - working
<img width="528" alt="Screen Shot 2020-01-30 at 8 30 01 PM" src="https://user-images.githubusercontent.com/7374640/73512666-4eda1e80-439f-11ea-8bdb-ad34762b665e.png">

<img width="180" alt="Screen Shot 2020-01-30 at 8 33 57 PM" src="https://user-images.githubusercontent.com/7374640/73513022-c197c980-43a0-11ea-9a50-3a78bddf2773.png">


I also changed the host url to `127.0.0.1` and that didn't help either.  Also tried the https://github.com/chrismccord/phoenix_live_view_example repo with `live_redirect` and it behaves correctly in FF.  I'll give a brand new repo a shot tomorrow.

**Comment by chrismccord** [comment]
I'm 99% certain this was because you are referencing LV master and I had not bumped the webpack build. My local testing was using the source file directly, so please try the following and report back:

```
$ mix deps.update phoenix_live_view
$ cd assets && rm -rf node_modules/phoenix_live_view 
$ npm I
$ cd ..
$ mix phx.server
```

Thanks!

**Comment by driv3r** [comment]
@chrismccord awesome! I can confirm, works in both demo app and the one in which I had issues in the first place. Should we add this info for whomever will be working against master in the future?

**Comment by chrismccord** [comment]
Nah it was my fault for not bumping the build after the `live_redirect` merge. Thanks!
