### ISSUE TITLE
Forms with selects spaz out if some part of the page changes

### ISSUE THREAD

**Issue by benwilson512** [phoenixframework/phoenix_live_view#601]
### Environment

* Elixir version (elixir -v):
Erlang/OTP 22 [erts-10.4.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.9.1 (compiled with Erlang/OTP 22)

* Phoenix version (mix deps):
* Phoenix LiveView version (mix deps):
```
$ mix deps|grep phoenix
* phoenix_gen_socket_client 2.1.1 (Hex package) (mix)
  locked at 2.1.1 (phoenix_gen_socket_client) 0432becc
* phoenix_pubsub 1.1.2 (Hex package) (mix)
  locked at 1.1.2 (phoenix_pubsub) 496c303b
* phoenix_html 2.14.0 (Hex package) (mix)
  locked at 2.14.0 (phoenix_html) d8c6bc28
* phoenix 1.4.12 (Hex package) (mix)
  locked at 1.4.12 (phoenix) b86fa85a
* phoenix_live_reload 1.2.1 (Hex package) (mix)
  locked at 1.2.1 (phoenix_live_reload) 274a4b07
* phoenix_live_view 0.7.0-dev (https://github.com/phoenixframework/phoenix_live_view.git) (mix)
* phoenix_ecto 4.0.0 (Hex package) (mix)
  locked at 4.0.0 (phoenix_ecto) c43117a1
```

Live view exact version: `7c9bf9234a6f2e19322968d333d509ff9e63025c`
### Actual behavior

# Example
```
defmodule Bad do
  use Phoenix.LiveView

  def render(assigns) do
    ~L"""
    <%= @now %>
    <form>
    <input type="text" />
    <select>
      <option>A</option>
      <option>B</option>
    </select>
    </form>
    """
  end

  def mount(_, _, socket) do
    {:ok, tick(socket)}
  end

  def handle_info(:tick, socket) do
    {:noreply, tick(socket)}
  end

  defp tick(socket) do
    Process.send_after(self(), :tick, 1_000)
    assign(socket, :now, DateTime.utc_now())
  end
end
```

If you open the `select` and try to mouse over B, the `select` spazes out, it seems morphdom is trying to override the `selected` attribute on A.

This can cause other issues in the form too. If you type text into the text input it's fine. If you type text, and then repeat the attempt to `select` B, it will cause the text inside the text box to dissapear.

**Comment by benwilson512** [comment]
Hey @chrismccord, this example is still exhibiting the same issue for me. I'm on cd85cf53e7bb29a70d888933fb28210fe3fc0e47 and have done the usual node modules clear / npm install.

**Comment by chrismccord** [comment]
Looks good on my side still on chrome, which is where I was able to recreate it (safari did not have this issue). What browser and browser version are you on?

**Comment by benwilson512** [comment]
```
Chrome
Version 79.0.3945.130 (Official Build) (64-bit)
```

Let me create a brand new complete project and see if it still shows up.

**Comment by benwilson512** [comment]
https://github.com/benwilson512/bug_example

**Comment by chrismccord** [comment]
This was happening because I did not bump the js build on master, but was testing locally by importing the src directly. Run the following and you should be good:

```
$ mix deps.update phoenix_live_view
$ cd assets && rm -rf node_modules/phoenix_live_view 
$ npm I
$ cd ..
$ mix phx.server
```

Thanks!

**Comment by benwilson512** [comment]
This does fix the flickering select form. The behaviour I'm seeing WRT the text field has actually been around for a while, will continue the discussion of whether it's intentional or a bug elsewhere. Thanks!

**Comment by chrismccord** [comment]
If the form isn't a LV form, you'll need to `<form phx-update="ignore">` to skip that DOM node and its children from being patched. If you want to make it a LV form, you need to pick up the params on phx-change, assign the values, and use them to build the input values in render.
