### ISSUE TITLE
Discussion: LiveView to UI events

### ISSUE THREAD

**Issue by DaTrader** [phoenixframework/phoenix_live_view#607]
I've recently upgraded to 0.4.1 and I can now see we're on 0.6.0 already with new features being added. Is there a mid-term schedule of planned features somewhere? 

With one specific feature in mind, is there a plan to integrate a support for LiveView to UI events that JS can react upon after a page is re-rendered (e.g. move focus some place specific based on the event-provided data)? There is an "old" (in LiveView years) article on how to do this by extending the LiveView Socket module (see: https://elixirschool.com/blog/live-view-with-channels/) and I wonder, given the current pace of changes, is something similar on your map already or the users are advised to follow the steps as explained in the article?

**Comment by josevalim** [comment]
Does the phx-hook mechanism address the problems you mentioned? It feels
like it does. If they don’t, why?

**Comment by DaTrader** [comment]
TBH, I don't know. So far, I've been using phx-hook for adding DnD  listeners in JS and pushing the event  from JS to LiveView not the other way around. I must admit I didn't even consider if it might be suitable for this too. Thanks for this hint. I'll try it tomorrow and be back asap.

**Comment by josevalim** [comment]
Oh yeah. So what you do is that you can add data attributes in the element with the phx-hook and use the data attributes as the mechanism to pass data in! I will go ahead and close this then!

**Comment by josevalim** [comment]
Btw, I think code school lessons are open, so consider submitting a PR with the latest practices!

**Comment by DaTrader** [comment]
Yes, I was thinking it overnight how to pass arguments to the event and figured the only way was to bake it into the HTML element. Thanks for helping me narrow the options.
Btw, don't you think it would be useful to keep some structure (a map) exposed to the user JS code for this purpose of communication from LV to JS? In this particular case of mine, a single element id will fit in into a data attribute, but sooner or later there will be a UC where more complex data structure needs to be passed.

**Comment by josevalim** [comment]
We discussed this extensively and you could always embed complex structures in the attribute as JSON. However, this is not a pattern we want to necessarily encourage, as we want to push folks to stay within LiveView abstractions as much as possible, so leaving some of the work to the developers is an acceptable trade-off.

**Comment by DaTrader** [comment]
Point taken. Thanks, again.

**Comment by DaTrader** [comment]
Here's an issue that I cannot resolve elegantly with the rendering of data into elements attributes. Actually, I now need to upgrade to the latest version as 0.4.1 doesn't yet support the beforeDestroy event which I hope will at least make my problem solvable.
Namely, with a tree-like structure of elements (even just two levels) so that more elements get destroyed at once, the JS code will receive just one destroyed event and it won't be the one from the top node (sadly because that would have solved my problem without upgrading to 0.6.0).
I did try rendering the desired element id into a dummy anchor element (from assigns) but then I found out that, naturally, it's gone by the time JS gets it (unlike the data of the element that gets passed to the JS destroyed handler).
I suppose this will now be solvable by relying on beforeDestroy, but I will still need to render the desired element id into a dummy element somewhere in the html for I only need the event on the top destroyed element and not just any (like with the destroy event) or all of them (which I suppose will be the case with beforeDestroy) handled by the JS code. The reason for it being simple - I don't want any server-side data-structure awareness in the JS, just the bare communication with the browser.

**Comment by chrismccord** [comment]
It’s not clear what your issue is exactly that isn’t covered by current features. Can you elaborate what your usecase is with DOM and LV example? Thanks!

**Comment by DaTrader** [comment]
Ok. My previous comment is the continuation of the discussion with José on exposing some data structure to the JS (see our comments above).
My UC:
I need to communicate to my JS code (in a Hook) which html element to move the focus to after a certain element is destroyed. As far as I understood José the intended channel of communication was for me to render this information into html so that is what I am doing. Each of my elements (that are subject to potential removal) has a data attribute rendered to point to another element after the deletion. The problem is that these elements (essentially rows of data) are not comprising just a sequence of rows, but may be nested into logical parent-child relationships so when a parent is destroyed, all of its children should be destroyed as well.
Now, when I destroy one such node of elements (an ancestor and its descendants), there will be only one event reaching my destroyed handler function in the Hook, and it will supply me with just one of the elements destroyed (inconveniently not the top-most ancestor, but that was to be expected as it cannot tell their business-wise logical relationships). So I end up with the data I cannot do anything with for not only do I need the element on the top of their logical hierarchy, but I also need to access its data attribute on where next to move my focus.
I tried rendering this element of interest id into a dummy element on my page but at no use because by the time my JS reads it I can no longer get the info from its data attributes (the id of the element where to move the focus) for it's no longer available (it's no longer rendered the element).

the dummy element code
..
<a <%= case assigns[ :move_focus] do %>
     <% { :post_removal, item_id} -> %>data-item="<%= item_id%>"
     <% _any -> %><%= nil %>
   <% end %>
   id="destroyed"/>
..

the code in each of the elements representing the rows subject to deletion (and potentially logically nested into other such rows i.e. subject to collective deletion):
..
          <div class="mdl-row"
               id="val-row-<%= item_id %>"
               data-pd_row="<%= type_after %>-<%= item_after %>"
               <%= unless is_nil( pd_key) do %>
                 data-pd_key="<%= pd_key %>"
               <% end %>
               <%= case assigns[ :move_focus] do %>
                 <% { :post_insertion, ^item_id} -> %>
                   data-row="val-<%= item_id %>"
                   data-left_key="<%= key_first( ruler_keys) %>"
                 <% _any -> %><%= nil %>
               <% end %>
               phx-hook="MoveFocus">
..
( the data-pd-row being the attribute telling where to move next if destroyed)

the JS Hook
..
Hooks.MoveFocus = {
  mounted: function () {
    let row = this.el.dataset.row;
    if( row != null && row !== "") {
      let key = get_focus_key( row.split( '-')[ 0], this.el.dataset.left_key);
      let new_id = row.concat( '-', key);
      document.getElementById( new_id).focus();
    }
  },
  destroyed: function () {
    console.info( "here:");
    let item_id = document.getElementById( "destroyed").dataset.item;
    console.info( item_id);
    let el = document.getElementById( 'val-row-'.concat( item_id));
    console.info( el.dataset.pd_row);
    
    // it will not reach here as the element no longer exists
    
    let row = this.el.dataset.pd_row;
    // console.info( row);
    let key = get_focus_key( row.split( '-')[ 0], this.el.dataset.pd_key);
    // console.info( key);
    let new_id = key != null ? row.concat( '-', key) : row;
    // console.info( new_id);
    document.getElementById( new_id).focus();
  }
};
..

**Comment by DaTrader** [comment]
Btw, the insertion part (also present in the shared code) works perfectly well, of course.

**Comment by DaTrader** [comment]
Another thing. I've just upgraded from 0.4.1. to 0.5.2 (the recommended stable version), and I've noticed that my MoveFocus JS hook on insertion no longer achieves the desired result (and it used to work perfectly on 0.4.1).
As shown in the code above I am moving the focus on insertion to the element that is being mounted. Now, when I print the active element id to console (after calling the JS focus() function) it gives a correct result, yet the focus on the screen does not move, i.e. it probably does but back to the old element for some reason related to the sequence of things you do in LV that is related to when it is that you trigger the mounted even relative to what else LiveView does after that (that may result in moving the focus back to where it was before the LV rendering) as this is the only place my code is dealing with focus and it prints to console when it does it so it's not me. Other JS events are working properly (DnD). Need to yet to try switching from destroyed to beforeDestroyed re the aforementioned element deletion issue.

**Comment by chrismccord** [comment]
we reworked our hook invocation callbacks so you may now get the information you need when you do a query selector, but I would go with a less query selector centric approach and annotate the "top" row with an attribute that says it should be focused, with a hook on that row, ie:

```
<%= for {row, i} <- Enum.with_index(@rows) do %>
  <%= if i == 0 do %>
    <div id="row-<%= row.id %>" phx-hook="ActiveRow">
    </div>
  <% else %>
    <div id="row-<%= row.id %>">
    </div>
<% end%> 
```

```javascript
Hooks.ActiveRow = {
  mounted() { this.el.focus() }
}
```

I believe that's all you need, but you could also put the hook on the top-level LV container and only annotate the hook with the id of what should be focused, then on `updated()` you send `focus()` to that id. So instead of looking for destroyed IDs or side effects in the DOM, let the server tell you what to do. Make sense?

**Comment by DaTrader** [comment]
I understand. I haven't thought of the updated event for handling insertions and deletions of the inner elements. That sounds neat. I'll try that.
As for focusing on mounted (your ActiveRow hook above), it no longer works on 0.5.2. It used to on 0.4.1. so I think you have a bug there on 0.5.2.

**Comment by DaTrader** [comment]
@chrismccord Thanks for the tip re updated event. Far better this way.

However, to make it all work I had to revert back to 0.4.1 since on 0.5.2. moving focus in JS in both mounted and updated functions of the hook produces no effects. It simply goes back where it was before the LiveView rendering.

I'm now going to open a separate issue for this is most probably a bug introduced with the changes to callback invocation you were referring to above.
