### ISSUE TITLE
Session is not available on consecutive mounts

### ISSUE THREAD

**Issue by askasp** [phoenixframework/phoenix_live_view#608]
The dummy_user is only available on the first mount, then it is nil.
The interesting code is in router.ex and live/show_bug_live.ex

https://github.com/askasp/show_potential_bug

(mix deps.get, cd assets &npm install)
mix phx.server
got to localhost:4000/user/profile. It should  show "Email: "
Not "Email: Some@mail" which would have been correct.

PS: it works as expected if you do not run npm install, but i assume this is because the websocket isn't active

**Comment by cadebward** [comment]
I also noticed this when I was upgrading from 0.4.1 to 0.6.0. Everything is available on first mount, as you would expect. Once the client connects and mount is called a second time, the session is blank.

**Comment by josevalim** [comment]
You are missing these steps from the installation guide:

---

Where `@session_options` are the options given to `plug Plug.Session` extracted to a module attribute. If you don't have a `@session_options` in your endpoint yet, here is how to extract it out:

1. Find plug Plug.Session in your endpoint.ex

```elixir
  plug Plug.Session
    store: :cookie,
    key: "_my_app_key",
    signing_salt: "somesigningsalt"
```

2. Move the options to a module attribute at the top of your file:

```elixir
  @session_options [
    store: :cookie,
    key: "_my_app_key",
    signing_salt: "somesigningsalt"
  ]
```

3. Change the plug Plug.Session to use the attribute:

```elixir
  plug Plug.Session, @session_options
```

---

When upgrading, please make sure to go through the changelog and follow all instructions. :)

**Comment by askasp** [comment]
Sorry about that! Thanks!  :)
