### ISSUE TITLE
Improper update behaviour noticed 

### ISSUE THREAD

**Issue by valloskut** [phoenixframework/phoenix_live_view#610]
![Peek 2020-02-02 00-41](https://user-images.githubusercontent.com/361956/73603820-a1f5d200-4555-11ea-9551-bd406c70087e.gif)

Hi there! Just FYI, using those deps with `phoenix 1.4.12` 
```elixir
      {:phoenix_html, "~> 2.14"},
       . . .
      {:phoenix_live_view, github: "phoenixframework/phoenix_live_view"}
```
noticed that `@mode` in `<a href="#" phx-click="toggle-mode"><%= @mode %></a>` (from [here](https://github.com/chrismccord/phoenix_live_view_example/blob/master/lib/demo_web/live/thermostat_live.ex#L9)) has not being updated properly. Diff looks fine, but DOM update is delayed.

**Comment by josevalim** [comment]
When you updated the app, just you nuke `node_modules` so the dependencies get updated?

**Comment by josevalim** [comment]
Ok, I was able to reproduce it. I have also pushed an updated version of the example app with updated deps.

**Comment by chrismccord** [comment]
This regression was introduced recently in c83e6aa9e64019c091ea831cf841975e6e27643d , but only present in chrome and FF. Thank you for the report!
