### ISSUE TITLE
Button doesn't show updated assign when it is clicked

### ISSUE THREAD

**Issue by tiagoefmoraes** [phoenixframework/phoenix_live_view#611]
### Environment

* Elixir version (elixir -v):1.9.1
* Phoenix version (mix deps): phoenix 1.4.12 (https://github.com/phoenixframework/phoenix.git) (mix) locked at 762cc5f (branch: v1.4)
* Phoenix LiveView version (mix deps): phoenix_live_view 0.7.0-dev (https://github.com/phoenixframework/phoenix_live_view.git) (mix)  locked at b6d8f63
* NodeJS version (node -v): v10.15.0
* NPM version (npm -v): 6.4.1
* Operating system: Linux

### Actual behavior
When I use an assign inside a `<button>` tag it doesn't get updated when I click the button.
```eex
<p>Label <%= @counter %></p>
<button phx-click="increment">Button A <%= @counter %></button>
<button phx-click="increment">Button B <%= @counter %></button>
```
![image](https://user-images.githubusercontent.com/1627293/73810001-c7801700-47b3-11ea-88fb-3d5d2c29a8b0.png)

As we can see on the image Button A has 0 on it's text and the Label and Button B have 3. If I click on Button B then Button A updates to display 4 and Button B stays at 3.

I created this repo to reproduce the problem:
https://github.com/tiagoefmoraes/phoenix_live_view_example/tree/counter
https://github.com/tiagoefmoraes/phoenix_live_view_example/blob/counter/lib/demo_web/live/counter_live.ex

### Expected behavior

As I click Button A it's text should reflect the value of the `counter` assign.

Phoenix.LiveView is looking great! :)

**Comment by chrismccord** [comment]
I cannot recreate this with the example LV. I just tested on master and everything looks as it should. Do you have any JS errors? Are you positive you didn't bump your LV version but forget to reinstall node modules? Closing as this does not appear to be an issue. If you still believe you are hitting a bug, please let us know. Thanks!
