### ISSUE TITLE
phx-click causing issues with JS click event handler using with or without phx-hook

### ISSUE THREAD

**Issue by josephan** [phoenixframework/phoenix_live_view#612]
### Environment

* Elixir version (elixir -v): `Elixir 1.9.4 (compiled with Erlang/OTP 22)`
* Phoenix version (mix deps): `phoenix 1.4.12`
* Phoenix LiveView version (mix deps): `phoenix_live_view 0.7.0-dev (https://github.com/phoenixframework/phoenix_live_view.git) b6d8f63` 
* NodeJS version (node -v): `v10.16.3`
* NPM version (npm -v): `6.13.7`
* Operating system: `macOS Mojave`

### Actual behavior
I have a simple JS click event handler with Hooks for a button that changes the `visible` of an `div` from `hidden` to `visible`.
When I click on the button for the first time, (`<button phx-click="open_notifications" phx-hook="OpenNotification">SHOW NOTIFICATION</button>`) it shows and then instantly hides the `div`. Subsequent clicks work fine.
This happens using with or without `phx-hook`.

Note that the behaviour works fine if I remove the `phx-click` attribute from the `button` element.

Sample App: https://github.com/josephan/liveview_example

Files:
* live view rendered here: https://github.com/josephan/liveview_example/blob/master/lib/example_web/templates/layout/app.html.eex
* live view source: https://github.com/josephan/liveview_example/blob/master/lib/example_web/live/notifications_live.ex
* JS source: https://github.com/josephan/liveview_example/blob/master/assets/js/app.js

### Expected behavior
It should display the `div` on the first click.

**Comment by josephan** [comment]
The bug: On the first click the hidden `div` should be permanently displayed but gets immediately closed.
![recording](https://user-images.githubusercontent.com/8878596/73862039-f32eeb80-480b-11ea-9388-802d981c9dfb.gif)

**Comment by chrismccord** [comment]
LV will patch the DOM with how it know it should look from the last patch. Therefore any direct DOM manipulation you perform will be "undone" on the next patch. If you want LV to avoid touching your own containers, you need to annotate them with `phx-update=ignore`, which should work if you apply this to your container that you are flipping the visibility on. Hope that help. Thanks!
