### ISSUE TITLE
Idea: specify which parts are live 

### ISSUE THREAD

**Issue by dkuku** [phoenixframework/phoenix_live_view#614]
HI
Is there a plan or a way to explicit specify which parts are live and which not? 
this would solve some issues 

I ported a multi step form to liveview and I wanted to keep the current step on the server.
then in the template i was using it to toggle a "hidden" class on/off using if statement
this worked, next I added datalist to some of the inputs using the same assign  and this ended up resetting my input state on tnese fields when changing them - I even removed the change event from the form but it didn't help. 
Another problem I noticed was a 15kB diff when changing my step and I used it on only in few places:
```
class="block text-gray-darker <%= unless @current_step == 1, do: "hidden" %>"
and 
    <%= for i <- 0..4 do %>
      <span class="step <%= if i < @current_step, do: "active" %>"></span>
    <% end %>
```
After few hours massing up with the markup and phx-update property I ended up with normal template with the current step kept in aipine js and 4 live components for the inputs and this seems to work ok.
But basically what I did I specified - leave this parts alone and update only these small live sprinkles.

**Comment by josevalim** [comment]
We have no plans for now besides the current behaviour where we allow developers to call live_render inside their templates to live render only a small part of their layout.

Also, in case of large diffs, make sure to not use block expressions (such as `do/end`) except for the built-in ones (if, for, etc), as we can't perform diff tracking inside them, or alternatively break a large view into components.
