### ISSUE TITLE
Add option to disable socket_connected logging

### ISSUE THREAD

**Issue by ericmj** [phoenixframework/phoenix_live_view#617]
### Environment

* Elixir version (elixir -v): 1.10
* Phoenix version (mix deps): 1.4.12
* Phoenix LiveView version (mix deps): 0.6.0
* NodeJS version (node -v):
* NPM version (npm -v):
* Operating system:

### Feature request

Normal we can disable socket logging with `use Phoenix.Socket, log: false` but this is not possible with live_view since this is internal to the library. Exposing this option would helpful for those that do custom logging.

**Comment by josevalim** [comment]
So you can actually do this in your endpoint:

    socket "/foo", MySocket, websocket: [log: false]

It may be Phoenix v1.5+ only though.
