### ISSUE TITLE
phx-blur to be used instead of phx-change on forms

### ISSUE THREAD

**Issue by nicolasblanco** [phoenixframework/phoenix_live_view#62]
In terms of User eXperience, it makes more sense to trigger some validations when the user is leaving an input field, not on every key press or change.

For example to display if the user email is valid or not already taken, it would be better to do that when the user is leaving the email field only.

I'm open to comments on this feature but would be happy to provide a PR if I manage to do that...

**Comment by chrismccord** [comment]
This will be handled as part of the debounce work. Thanks!
