### ISSUE TITLE
Do flashes have to be binaries?

### ISSUE THREAD

**Issue by ccapndave** [phoenixframework/phoenix_live_view#623]
As of Liveview 0.6.0 flashes are only allowed to be binaries, whereas previously there were no restrictions.  We were actually using this to send a flash that was a map, which then gets picked up in Javascript and formatted into something lovely - for example:

```
put_flash(:download, %{message: "Your certificates are ready. Please click here to download them.", url: url})
```

Is there a specific reason why this isn't allowed anymore?

**Comment by chrismccord** [comment]
How were you picking it up on the js side? We sign the flash into a token with LV so I'm not sure ho you were using it. We are currently revamping flash in general as is does not work for LV <=> LV on existing releases, which will follow the same semantics as Controller.put_flash

**Comment by josevalim** [comment]
As @chrismccord said, we have been discussing the future of flash. I have restricted flash parameters because we were considering one direction but we will stick with a signed cookie, which means we no longer need to forbid values. Therefore I have removed the limitation.

**Comment by ccapndave** [comment]
In order to get the data out, we just write it into the DOM using `get_flash`:

```
<span class="hidden" role="download" data-url="<%= get_flash(@conn, :download)["url"] %>"><%= get_flash(@conn, :download)["message"] %></span>
```

Our use case is that we have a zip that is generated in a Liveview and then uploaded to AWS, and then we redirect out of the Liveview and show the user a message with the link.  So using a flash seemed like the natural fit for passing info from a Liveview back into a normal request (for a single display).

Thanks very much for removing this restriction!
