### ISSUE TITLE
error_tag function and date_select function do not work together

### ISSUE THREAD

**Issue by netikular** [phoenixframework/phoenix_live_view#632]
### Environment

* Elixir version (elixir -v):
Erlang/OTP 21 [erts-10.0.5] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-thre
ads:1] [hipe]
Elixir 1.9.0 (compiled with Erlang/OTP 20)
* Phoenix version (mix deps):
 phoenix 1.4.13 (Hex package) (mix)
  locked at 1.4.13 (phoenix) ab765a0f
* Phoenix LiveView version (mix deps):
phoenix_live_view 0.7.1 (https://github.com/phoenixframework/phoenix_live_view.git) (mix)
  locked at c9384aa

* NodeJS version (node -v):v8.16.2
* NPM version (npm -v): 6.13.6
* Operating system: 10.15.3

### Actual behavior

When utilizing the `date_select` function in a live view the `error_tag` as defined in the repository (https://github.com/phoenixframework/phoenix_live_view/blob/c9384aaad9511de5846c2664689adae113353614/lib/phoenix_live_view.ex#L538) cause a null is not an object error to be raised after submitting the form.

A sample repository is located at: https://github.com/Paradem/checkbox_problem

to reproduce the problem:

1. load the code up (run migrations and other setup as needed)
2. launch the application
3. navigate to /checkboxes
4. try and submit the form

You will see that the checkbox that was below the select boxes is now at the top of the form and you get the error `TypeError: null is not an object (evaluating 'e.phxPrivate')` in the console.

This is because the `data-phx-error-for` value is based on the name of the field in the changeset, and there is no actual html element with that value.

If you put `not_blank_year` in the `error_tag` function call in the form, the JavaScript error no longer happens however the error message showing that the value is invalid does not exist.

The reason for all of this is that the error_tag function does not have knowledge that there is actually 3 fields that represent the one field in the changeset.

Also if you put a hidden field that would just be ignored by your form submission the code works correctly as the JS can find an input with the right id.

`<input type="hidden" id="<%= input_id(f, :not_blank)%>"/>`

### Expected behavior

The expected behaviour is that the error message would be displayed and the application would continue to work.

### Thoughts

I'm opening this issue for discussion, I thing that the correct solution would be to try and create something that maps the errors back from the three fields back to the one field - or just don't use the three date selects for anything other than a toy.

It was quite the chase to hunt down what was causing the problem and I would like to leave some thing that may help someone in the future.

**Comment by chrismccord** [comment]
Can you try master? I am unable to recreate this issue there. Thanks!

**Comment by netikular** [comment]
Sure, I'll pull the latest - we were on master at the time of testing.

**Comment by netikular** [comment]
Yep, works on master - something fixed it between c9384aa and master.

Thanks for your work.
