### ISSUE TITLE
v0.7.1 regression with inline template conditional after handle_event

### ISSUE THREAD

**Issue by toranb** [phoenixframework/phoenix_live_view#637]
### Environment

* Elixir version (elixir -v): v1.8.1
* Phoenix version (mix deps): v1.4.13
* Phoenix LiveView version (mix deps): v0.7.1
* NodeJS version (node -v): v10.16.3
* NPM version (npm -v): v6.9.0
* Operating system: macOS 10.14.6

### Actual behavior

In live view v0.6 when I would alter the changeset with the [click handler](https://github.com/toranb/broken-live-view-demo/blob/master/lib/shop_web/live/signup.ex#L122-L132) shown below

```elixir
  def handle_event(
        "click",
        %{"value" => membership_id},
        %{assigns: %{:changeset => changeset}} = socket
      ) do
    changeset =
      changeset
      |> Ecto.Changeset.put_change(:membership_id, membership_id)

    {:noreply, assign(socket, changeset: changeset)}
  end
```

I would expect the vdiff to re-evaluate the `membership_eq` [function](https://github.com/toranb/broken-live-view-demo/blob/master/lib/shop_web/live/signup.ex#L160-L168) found in the [signup live view template](https://github.com/toranb/broken-live-view-demo/blob/master/lib/shop_web/live/signup.ex#L49-L53) (inline)

```html
                      <%= if membership_eq(@changeset, "BUSINESS") do %>
                        <span class="rounded-full h-3 w-3 text-center block bg-shop-blue m-auto"></span>
                      <% else %>
                        <span class="rounded-full h-3 w-3 text-center"></span>
                      <% end %>
```

This would then alter the class to show the blue outline by adding `bg-shop-blue` to the DOM node.

### Expected behavior

In the animated GIF below I start by showing that phoenix live view v0.6 was working correctly (first tab) but phoenix live view v0.7.1 was not working as it did previously (second tab)

![regression](https://user-images.githubusercontent.com/147411/74607615-eded5e80-509f-11ea-8c21-8cfd29d49f51.gif)

Here is the fully working demo application for further analysis 

https://github.com/toranb/broken-live-view-demo

The page is visible from a locally running `iex -S mix phx.server` from ```http://localhost:4002/signup```

edit: I do notice that if I click the save button - that runs this [handler](https://github.com/toranb/broken-live-view-demo/blob/master/lib/shop_web/live/signup.ex#L101-L115) - the vdiff seems to work in phoenix live view v0.7.1 

```elixir
  def handle_event("save", %{"form" => params}, socket) do
    if Map.get(params, "form_disabled", nil) != "true" do
      changeset =
        Shop.Form.changeset(%Shop.Form{}, params)
        |> Ecto.Changeset.put_change(:form_submitted, true)
        |> Ecto.Changeset.put_change(:form_disabled, true)
        |> Map.put(:action, :insert)

      send(self(), {:disable_form, changeset})

      {:noreply, assign(socket, changeset: changeset)}
    else
      {:noreply, socket}
    end
  end
```

**Comment by josevalim** [comment]
Hi @toranb! I cannot reproduce the failure in your sample app.  It was work as in the Expected demo. Have you removed the `node_modules` directory and installed your assets from scratch to make sure your assets have been updated?

**Comment by toranb** [comment]
@josevalim speedy reply my friend! I can further clarify steps and what browser(s) it works/ doesn't (to be extra explicit)

```
git clean -xfd
mix deps.get
npm install --prefix ./assets
mix compile
iex -S mix phx.server
```

Firefox 73.0 it does work :)
Chrome 80 and Chromium (version 81.0.4) it does *not* work :(

**Comment by josevalim** [comment]
Oh, that explains it then, I was using FF. So this is most likely a client side issue.

**Comment by snewcomer** [comment]
I've narrowed it to this commit with git bisect.  Is is b/c `document.activeElement` is the `button` in Chrome but in Safari and Firefox, it is the `body`.

https://github.com/phoenixframework/phoenix_live_view/commit/c83e6aa9e64019c091ea831cf841975e6e27643d

This seems to be a known [bug](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Clicking_and_focus).  As for a solution...If we are going to handle/query `activeElement`, we may also have to handle focus somehow.

**Comment by toranb** [comment]
Thanks for the speedy work @snewcomer  :) much appreciated my friend
