### ISSUE TITLE
":not_mounted_at_router" when use controller

### ISSUE THREAD

**Issue by EdoardoLopez** [phoenixframework/phoenix_live_view#639]
### Environment

* Elixir version (elixir -v): Elixir 1.9.0 (compiled with Erlang/OTP 22)
* Phoenix version (mix deps): 1.4.11
* Phoenix LiveView version (mix deps): 1.7.1
* NodeJS version (node -v): node v10.18.0
* NPM version (npm -v): npm v6.13.4
* Operating system: Debian 10 (buster)

### Actual behavior

when i use a controller to call a live view with live_render  with "mount" function, i get like first  argument(params) this message  ":not_mounted_at_router", but when i create a live router and serve live view from router i get the params without problems.

this is a sample test https://github.com/EdoardoLopez/live_view_test.git

**Comment by chrismccord** [comment]
This is by design. The controller live render is not mounted from the router and thus you don't get params. You should use `live` in the router in general, which will give you the data you want. Thanks!
