### ISSUE TITLE
Hooks - updated() doesn't affect elements style - JCF

### ISSUE THREAD

**Issue by Kaquadu** [phoenixframework/phoenix_live_view#640]
### Environment

* Elixir version (elixir -v): Elixir 1.10.1 (compiled with Erlang/OTP 22)
* Phoenix version (mix deps): phoenix 1.4.13
* Phoenix LiveView version (mix deps): phoenix_live_view 0.7.1
* NodeJS version (node -v): v12.6.0
* NPM version (npm -v): 6.11.2
* Operating system: macOS Catalina 10.15.3
* Browsers you attempted to reproduce this bug on (the more the merrier): Google Chrome, Safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Description
Hello,
I'm currently using JCF [jcf-source](https://www.psd2html.com/js-custom-forms/) to replace selects styling inside a form that is placed in live view render.

I'm using hooks to replace elements:
```
mounted() {
        AdvertSearch.initFilters(); 
        AdvertSearch.handleFilters();
        jcf.replaceAll(".main-search");
        AdvertMap.adjustMap();
}
```
Mounting works fine - selects styling is replaced, they are 'round'. However when the live view update occurs  the function `updated()` is called, but the styling of selects is not replaced - and they become 'squares' again.
```
updated() {
        console.log("updated-begins");
        AdvertSearch.initFilters();
        AdvertSearch.handleFilters();
        
        jcf.replaceAll('.main-search'); //tried also jcf.refreshAll(`.main-search`);
       console.log("updated-ends");
}
```

### Actual behavior
After the live view update selects styling is not replaced by `updated()` hook, however mounting works fine.

### Expected behavior
Styling of the selects should be replaced.

**Comment by josevalim** [comment]
Can you please provide a sample application that reproduces the error? This will speed up the fixing process considerably. Otherwise it is unclear when we would have to time to put into reproducing the issue itself. Thanks!

**Comment by Kaquadu** [comment]
Here it comes:
[repro](https://github.com/Kaquadu/jcf-live-view)

It is kinda ugly, because it has totally 0 styling, but the idea is preserved:
Once you enter main page: jcf replaces all the styles (select and button - `a` and `Update`).
Once you click on select (`a`) and choose any option, then press `Update` - styling of the select is gone.

**Comment by chrismccord** [comment]
This is not an issue on our end. In general, heavy js controlled DOM that interacts with dynamic LV content is going to be tricky. For areas of JS injected DOM, you must use `phx-update=ignore` on the container so we won't undo your changes, but in this case the entire form is being rewritten by the jfc library, and you can't use phx-update=ignore because you need to patch the form on updates. It looks like the library makes heavy use of its own DOM state, which is being stomped on by our patch. The fix is to teardown the jfc elements before update, then do a "fresh" replace so jcf's state is always intact:

```
Hooks.FormHook = {
  beforeUpdate(){ jcf.destroyAll(this.el) },
  updated(){ jcf.replaceAll(this.el) },
  mounted(){ jcf.replaceAll(this.el) }
}
```

**Comment by Kaquadu** [comment]
Thanks! It really helped me to understand what is happening there!  :+1:

> This is not an issue on our end. In general, heavy js controlled DOM that interacts with dynamic LV content is going to be tricky. For areas of JS injected DOM, you must use `phx-update=ignore` on the container so we won't undo your changes, but in this case the entire form is being rewritten by the jfc library, and you can't use phx-update=ignore because you need to patch the form on updates. It looks like the library makes heavy use of its own DOM state, which is being stomped on by our patch. The fix is to teardown the jfc elements before update, then do a "fresh" replace so jcf's state is always intact:
> 
> ```
> Hooks.FormHook = {
>   beforeUpdate(){ jcf.destroyAll(this.el) },
>   updated(){ jcf.replaceAll(this.el) },
>   mounted(){ jcf.replaceAll(this.el) }
> }
> ```
