### ISSUE TITLE
Select field out of focus

### ISSUE THREAD

**Issue by isavita** [phoenixframework/phoenix_live_view#643]
### Environment

* Elixir version (elixir -v): Elixir 1.10.1 (compiled with Erlang/OTP 22)
* Phoenix version (mix deps): phoenix 1.4.13
* Phoenix LiveView version (mix deps): phoenix_live_view 0.7.1
* NodeJS version (node -v): v10.19.0
* NPM version (npm -v): 6.13.4
* Operating system: Ubuntu 18.04.4 LTS
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox Release 73.0

* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behaviour
When I select for the first time select box it goes out of focus (It's not green any more). 

### Expected behaviour
I expected to stay in focus.

I suspect that the problem being introduce in [this change](https://github.com/phoenixframework/phoenix_live_view/pull/627).

I made [demo app](https://github.com/isavita/bad_select).

**Comment by chrismccord** [comment]
It only blurs on change, right? IE you focus the select box and select a new value, then the select is blurred on form change? Can you describe a bit more what problems you are having with this behavior? Thanks!
