### ISSUE TITLE
Layout in live routes

### ISSUE THREAD

**Issue by shritesh** [phoenixframework/phoenix_live_view#65]
### Environment

* Phoenix version (mix deps): phoenix 1.4.2 

### Expected behavior

I have a `live "/thing", ThingLive` route in my router along with other controllers that have been piped through the `:browser` pipeline. 

I expected the default `:app` LayoutView to apply to the `ThingLive` route like the rest of the controllers.

### Actual behavior

No layout is applied and needs to be manually added to the pipeline like in the example app: https://github.com/chrismccord/phoenix_live_view_example/blob/13b07ae9a019fb89511d7f06f4634b992bc64627/lib/demo_web/router.ex#L11

**Comment by rupurt** [comment]
Leaving a comment for anyone that comes across this when upgrading to `0.9.0`. I had to add the following plug to make live routes render with a default layout.

```elixir
plug :put_live_layout, {MyAppWeb.LayoutView, :app}
```
