### ISSUE TITLE
Efficiently rendering append-only log

### ISSUE THREAD

**Issue by methyl** [phoenixframework/phoenix_live_view#666]
Hey there!

I have a component like following:
```
defmodule ExpandedNodeComponent do
  use Phoenix.LiveComponent

  def render(assigns) do
    ~L"""
      <pre>
        <%= for line <- @logs_out |> String.split("\n") do %>
          <span><%= line %></span>
        <% end %>
      </pre>
    """
  end
end
```

It seems it sends the whole payload down the line every time a line is added which is rather inefficient. Is there any obvious way that I'm missing to avoid that?

**Comment by josevalim** [comment]
See `phx-update="append"`. Also generally speaking, it is best if you use the ElixirForum for questions and general help! Have fun!

**Comment by methyl** [comment]
Thanks, will do. Shame on me!

For the record, if you don't have id's at hand, you can keep track of number of records in a separate assign, like `assign(:logs_out_lines, out |> String.split("\n") |> Enum.count())` and then update it when new stuff is received, offsetting the index that will be used as id:
```
     |> assign(
       :logs_out_lines,
       (out |> String.split("\n") |> Enum.count()) + socket.assigns.logs_out_lines
     )
     |> assign(
       :logs_out,
       out
       |> String.split("\n")
       |> Enum.with_index()
       |> Enum.map(fn {line, index} -> {line, index + socket.assigns.logs_out_lines} end)
       |> Enum.into([])
     )}
```
