### ISSUE TITLE
Inconsistent behaviour when submitting forms within component

### ISSUE THREAD

**Issue by Kraigie** [phoenixframework/phoenix_live_view#668]
### Environment

* Elixir version (elixir -v): Elixir 1.10.0 
* Phoenix version (mix deps): 1.4.14
* Phoenix LiveView version (mix deps):  0.7.1 (although the issue persists on 0.8.1)
* NodeJS version (node -v): v12.15.0
* NPM version (npm -v): 6.13.4
* Operating system: macOS
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, Safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

As part of a project we have a LiveComponent that contains a form used to filter results on a page.

Lets say it looks something like this
```elixir
def render(assigns) do
    ~L"""
      <div id="<%= @id %>">
        <div>
          <%= @query %>
          <form phx-submit="query" phx-target="#<%= @id %>">
            <input name="query" type="text" placeholder="Filter" autofocus="true" value="<%= @query %>"></input>
            <%= @query %>
            <button phx-target="#<%= @id %>" type="submit">Filter</button>
          </form>
        </div>
      </div>
    """
  end

def handle_event("query", query, socket) do
  send(self(), query)
  {:noreply, socket}
end
``` 

And inside the LiveView
```elixir
  def handle_info(%{"query" => q}, socket) do
    to_show = Enum.filter(@test_data, fn d -> d.name =~ q end)

    {:noreply, assign(socket, test_data: to_show, query: q)}
  end
```

As you can see we have the `@query` assign populating the `value` attribute of the input box, as well as elsewhere on the page. If you click on the "Filter" button, everything behaves as you would expect. The query assign is updated, and displayed in other locations on the page. The data in the table not pictured is correctly updated as well.

However, if you press the "enter" key to submit the form the behaviour is a little different. The table is still filtered correctly according to the query, and the queries we are printing outside of the input box using the `@query` assign are updated to what you'd expect. Inside of the input box however, the `value` attribute is not being updated correctly. Instead of showing the latest version of the assign, it is showing whatever the previous value was.

Here's a link to a small project showcasing the problem - https://github.com/Kraigie/value_test

The error does not persist when the filter is put directly on the page, or if we change the `query` assign inside of the `handle_event` callback in the component module. Although I'm not sure if that breaks the guidelines set forth [here](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveComponent.html#module-liveview-as-the-source-of-truth).

### Expected behavior
Pressing the enter key to submit a form correctly updates the value attribute.

**Comment by snewcomer** [comment]
👋 This is a great bug report!  Is it possible that you also need to assign the `query` to the socket in your component `handle_event/3` callback or is it expected `@query` will propagate from the parent `handle_info/2` socket assignment to the component? 

If not, then this is likely a bug on the server as I'm not seeing the result of form submit with a proper `value` on the input.

**Comment by Kraigie** [comment]
Thanks! 

It is possible to assign `query` to the socket in the `handle_event/3` callback, and that fixes the issue.

The reason I didn't take this approach is two fold- 

1. I was following the example set forth [here](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveComponent.html#module-liveview-as-the-source-of-truth).
2. The `@query` does propagate from the `handle_info/2` into the component, but just not consistently. The `@query` assign is seemingly updated everywhere on the page, except for the actual value inside the `value` attribute on the input box.

**Comment by chrismccord** [comment]
You need to track the change with `phx-change="mychange"` and update the value as it is changed:

    def handle_event("my change", %{"query" => query}, socket) do
      {:noreply, assign(socket, :value, value)}
    end

Thanks!
