### ISSUE TITLE
Document ~1 second WebSocket connect delay using localhost with Chrome browser

### ISSUE THREAD

**Issue by wanton7** [phoenixframework/phoenix_live_view#67]
### Environment

* Elixir version (elixir -v): 1.8.1
* Phoenix version (mix deps): 1.4.2
* NodeJS version (node -v): v10.15.0
* NPM version (npm -v): 6.5.0
* Operating system: Windows 10

### Expected behavior
There was no connection delay when using localhost in Chrome browser on Windows

### Actual behavior
There is ~1 second delay is when using localhost, but 127.0.0.1 isn't effected.  More info here https://bugs.chromium.org/p/chromium/issues/detail?id=175237
I think this should be documented.

**Comment by chrismccord** [comment]
Since this is a browser specific bug and not affecting all users, I don't think we should document it. Thanks for the PR!
