### ISSUE TITLE
Use of :flash assign collides with internal Liveview :flash

### ISSUE THREAD

**Issue by Softknobs** [phoenixframework/phoenix_live_view#671]
### Environment

* Elixir version (elixir -v):
Erlang/OTP 21 [erts-10.3] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]
Elixir 1.9.2 (compiled with Erlang/OTP 20)

* Phoenix version (mix deps):
phoenix 1.4.14

* Phoenix LiveView version (mix deps):
phoenix_live_view 0.8.1

* NodeJS version (node -v):

* NPM version (npm -v):
v12.13.0
* Operating system:
Win10 x64

### Actual behavior

On a project started back on Liveview 0.4.1 a custom ":flash" assign was set on a liveview.
After upgrading from 0.6.0 to 0.8.1, the following message appears on some actions on that liveview:

```
[error] GenServer #PID<0.956.0> terminating
** (BadMapError) expected a map, got: nil
    (stdlib) :maps.merge(nil, %{})
    (phoenix_live_view) lib/phoenix_live_view/utils.ex:101: Phoenix.LiveView.Utils.merge_flash/2
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:298: Phoenix.LiveView.Channel.component_handle_event/5
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```
The problem is that :flash is also used as an assign, internally to liveview.
My custom :flash is set to nil which leads to an error when Utils.merge_flash/2 is invoked at some point when handling the Live view.

### Expected behavior
This shows it is possible to interfere with internal liveview engine "by accident"
Possible ways to handle:
* it should not be possible to use assigns that are used internally and a specific error should be fired in such case
* if an assign collides with internal liveview assigns, dynamically rename it so it does not interfere with liveview's assigns.

This applies to these assigns as well:
* :live_view_action
* :inner_content

Actually this problem could also be a security threat:  third party components could try to redefine such assigns on purpose to alter the way Live View works.

**Comment by josevalim** [comment]
I believe `:flash` is the only problematic one because we use it for internal checking, while the others are only set in views. `@inner_content` in particular can be set manually if you are ever calling a layout. TL;DR - we will make it raise for `:flash`, thanks!

**Comment by Softknobs** [comment]
Thanks for the explanation. Raising an exception looks to be a nice solution.
