### ISSUE TITLE
Discussion: A LiveView demo exploring all the new features

### ISSUE THREAD

**Issue by DaTrader** [phoenixframework/phoenix_live_view#674]
Guys, I imagine you are very busy adding new features and fixing bugs, but given the plethora of the already added features since the first demos were made a year ago, it'd be nice to have at least one repo extensively demoing the LV navigation related events/features (the enhancements found in 0.7.0 and 0.8.0).
Thanks.

**Comment by chrismccord** [comment]
Keep on eye on the examples repo on my personal repo, which already include live navigation. We are also working on live generators which will include al these things for you out of the box. We use the issue tracker for issues so please use the forums or slack for discussions in the future. Thanks!

**Comment by DaTrader** [comment]
Will do. Thanks!
