### ISSUE TITLE
phx-keyup for textarea includes its value by default which can be expensive

### ISSUE THREAD

**Issue by alco** [phoenixframework/phoenix_live_view#680]
### Environment

* Phoenix version (mix deps): `1.4.14`
* Phoenix LiveView version (mix deps): `0.8.1 (https://github.com/phoenixframework/phoenix_live_view.git)`

### Actual behavior

I have a simple live view with a text area and one assign:
```elixir
defmodule NokoWeb.LiveViews.KeyboardLive do
  use Phoenix.LiveView

  def render(assigns) do
    ~L"""
    <p>Please type some text below:</p>
    <textarea phx-keyup="keyup"></textarea>
    <pre><%= @text %></pre>
    """
  end

  def mount(_params, _session, socket) do
    {:ok, assign(socket, text: "")}
  end

  def handle_event("keyup", %{"key" => _key, "value" => value} = e, socket) do
    IO.inspect(e)
    {:noreply, assign(socket, :text, value)}
  end
end
```

Whenever I type something into the text area, its whole value is sent to the live view in the `keyup` event:

![Screenshot_2020-03-05_10-16-38](https://user-images.githubusercontent.com/207748/75962474-7e170a80-5ecc-11ea-885b-eba76916fc09.png)

Part of the server output:
```
[...]
%{
  "altKey" => false,
  "code" => "Digit1",
  "ctrlKey" => false,
  "key" => "!",
  "location" => 0,
  "metaKey" => false,
  "repeat" => false,
  "shiftKey" => true,
  "value" => "This is expensive!"
}
%{
  "altKey" => false,
  "code" => "Digit1",
  "ctrlKey" => false,
  "key" => "!",
  "location" => 0,
  "metaKey" => false,
  "repeat" => false,
  "shiftKey" => true,
  "value" => "This is expensive!!"
}
%{
  "altKey" => false,
  "code" => "ShiftLeft",
  "ctrlKey" => false,
  "key" => "Shift",
  "location" => 1,
  "metaKey" => false,
  "repeat" => false,
  "shiftKey" => false,
  "value" => "This is expensive!!"
}
%{
  "altKey" => false,
  "code" => "Backspace",
  "ctrlKey" => false,
  "foo" => "1",
  "key" => "Backspace",
  "location" => 0,
  "metaKey" => false,
  "repeat" => false,
  "shiftKey" => false,
  "value" => "This is expensive!"
}
[...]
```

This looks pretty expensive as a default behaviour and I haven't found a way to turn this off. For example, I may want to read only `"key"` from the `keyup` event but `"value"` will still get sent over the wire.

### Expected behavior

There needs to be a way to specify which event fields should be excluded on the client before the event is sent to the server.

**Comment by barkerja** [comment]
You could always fallback to using a Hook to have more control over what is sent to the server. https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#module-js-interop-and-client-controlled-dom

Here's a basic example of sending only `key` and `code` from the event to the backend.

```elixir
defmodule NokoWeb.LiveViews.KeyboardLive do
  use Phoenix.LiveView

  def render(assigns) do
    ~L"""
    <p>Please type some text below:</p>
    <textarea phx-hook="KeyUpExample"></textarea>
    <pre><%= @text %></pre>
    """
  end

  def mount(_params, _session, socket) do
    {:ok, assign(socket, text: "")}
  end

  def handle_event("keyup", %{"key" => _key, "value" => value} = e, socket) do
    IO.inspect(e)
    {:noreply, assign(socket, :text, value)}
  end
end
```

```javascript
Hooks.KeyUpExample = {
  mounted() {
    this.el.addEventListener('keyup', (event) => {
      this.pushEvent('keyup', {key: event.key, code: event.code});
    });
  }
};

**Comment by alco** [comment]
@barkerja Thanks! That looks neat.

**Comment by chrismccord** [comment]
The hook approach is definitely the way to go. I agree it can cause large payloads but I think it's the best default behavior. More specialize behavior can be accomplished with a hook. Super long term, we could explore OT for text content, but this is also something you could easily wire up yourself with a hook + quilljs or similar. Thanks!

**Comment by snewcomer** [comment]
For more options, `phx-debounce="2000"` may help you here too!
