### ISSUE TITLE
Blank nested leex file rendered as undefined

### ISSUE THREAD

**Issue by seb3s** [phoenixframework/phoenix_live_view#685]
### Environment

* Elixir version (elixir -v): 1.10.0
* Phoenix version (mix deps): 1.4.14
* Phoenix LiveView version (mix deps): 0.8.1
* NodeJS version (node -v): 10.15.3
* NPM version (npm -v): 6.4.1
* Operating system: Debian linux
* Browsers you attempted to reproduce this bug on (the more the merrier):  chromium
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior
when calling a nested template with render, and when that nested template results in an empty string, the rendering result is "undefined" in the browser

### Expected behavior
should be rendered as a blank string ""

**Comment by seb3s** [comment]
Complement : this doesn't happened on the first rendering (via the live path in router.ex) but when a new assignment via handle_event triggers the re-rendering

**Comment by chrismccord** [comment]
Can you include an example LV and template which reproduces this issue? thanks!

**Comment by seb3s** [comment]
Here it is. I've tried to simplify my code to show the case.

index_live.ex => called from router with:
live "/", IndexLive, session: %{"page" => "dashboard"}

    defmodule KandeskWeb.IndexLive do
      use Phoenix.LiveView
    
    
      def mount(params, session, socket) do
        case connected?(socket) do
          true -> connected_mount(params, session, socket)
          false -> {:ok, assign(socket, page: "loading")}
        end
      end
    
      def connected_mount(_params, %{"page" => "dashboard" = page}, socket) do
        {:ok, assign(socket,
          page: page,
          show_modal: nil
        )}
    
      end
    
      def connected_mount(_params, _session, socket) do
        {:ok, assign(socket, page: "error")}
      end
    
    
      def render(%{page: "loading"} = assigns) do
        ~L"<div>La page est en cours de chargement, veuillez patienter...</div>"
      end
    
      def render(%{page: "error"} = assigns) do
        ~L"<div>Une erreur s'est produite</div>"
      end
    
      def render(%{page: page} = assigns) do
        Phoenix.View.render(KandeskWeb.LiveView, "page_" <> page <> ".html", assigns)
      end
    
    
      ## handle_event
      ## ------------
      def handle_event("close_modal", params, %{assigns: assigns} = socket) do
        {:noreply, assign(socket, show_modal: nil)}
      end
    
      def handle_event("show_modal", %{"modal" => modal}, socket) do
        {:noreply, assign(socket, show_modal: modal)}
      end
    
      def handle_event("view_board", _params, %{assigns: assigns} = socket) do
        {:noreply, assign(socket, page: "board")}
      end
    
      def handle_event("view_dashboard", _params, %{assigns: assigns} = socket) do
        {:noreply, assign(socket, page: "dashboard")}
      end
    
    end

page_board.html.leex

    <div class="buttons">
      <button class="button is-primary" phx-click="view_dashboard">View dashboard</button>
      <button class="button is-primary" phx-click="show_modal" phx-value-modal="create_column">Add column</button>
    </div>
    
    <%= render "modal_create_column.html", assigns %>

page_dashboard.html.leex

    <div class="buttons">
      <button class="button is-primary" phx-click="view_board">View board</button>
      <button class="button is-primary" phx-click="show_modal" phx-value-modal="create_board">Create a new board</button>
    </div>
    
    <%= render "modal_create_board.html", assigns%>

modal_create_board.html.leex

    <%= if @show_modal do %>
    <div class="modal is-open" id="modal_create_board" phx-hook="show_modal">
      <div class="modal-background" data-micromodal-close></div>
      <div class="modal-card">
        <header class="modal-card-head">
          <h2 class="modal-card-title">Create a board</h2>
        </header>
        <section class="modal-card-body">
          Modal content
        </section>
        <footer class="modal-card-foot">
          <button class="button is-primary" form="form_board" type="submit">Valider</button>
          <button class="button" data-micromodal-close>Annuler</button>
        </footer>
      </div>
    </div>
    <% end %>

modal_create_column.html.leex

    <%= if @show_modal do %>
    <div class="modal is-open" id="modal_create_column" phx-hook="show_modal">
      <div class="modal-background" data-micromodal-close></div>
      <div class="modal-card">
        <header class="modal-card-head">
          <h2 class="modal-card-title">Create a column</h2>
        </header>
        <section class="modal-card-body">
          Modal content
        </section>
        <footer class="modal-card-foot">
          <button class="button is-primary" form="form_column" type="submit">Valider</button>
          <button class="button" data-micromodal-close>Annuler</button>
        </footer>
      </div>
    </div>
    <% end %>

when you click on view_board button, it displays the second page and undefined at bottom. If you insert a blank line as first line of modal_create_column (or 2 blank lines at the end), the undefined is no more shown.
Hope this helps.

**Comment by josevalim** [comment]
Hi @seb3s, can you please put this in a test app? If you prefer, you can even [fork the examples app](https://github.com/chrismccord/phoenix_live_view_example) and add it directly there.

We want to make sure that the time we spend on the project is on fixing the bug that you are seeing, rather than trying to reproduce it. Thanks!

**Comment by chrismccord** [comment]
I cannot recreate using the provided examples so a full project which illustrates this is required. Thanks!

**Comment by seb3s** [comment]
Ok
I will do that tomorrow. Film time here 😀
Cheers
Sébastien

Le dim. 8 mars 2020 à 20:09, Chris McCord <notifications@github.com> a
écrit :

**Comment by seb3s** [comment]
Hi,
I had troubles reproducing it with the last samples site ! Coz it seems to be fixed with the latest 0.9.0 version.
Anyway, to show my case (maybe it can reveal something else as well coz to me it seems that is it due to some wrong diff sent back to the browser), I put something with 0.8.1 version in which I face the case.
So here it is :
https://github.com/seb3s/phoenix_live_view_example/tree/bug685
Cheers

**Comment by josevalim** [comment]
Thank you! I indeed could not reproduce it on master, so I will go ahead and mark it as closed. If the issue reappears, we now have a starting point with the example app. Many thanks!

**Comment by seb3s** [comment]
Hi,
I dig it a little bit further viewing the log to understand what could have solved it ;-)
It has been fixed by the following commit
https://github.com/phoenixframework/phoenix_live_view/commit/41549a5111090a6b39720bcc1d939c4c632134a8
Cheers
