### ISSUE TITLE
Invalid behaviour of mounted() JS callback

### ISSUE THREAD

**Issue by cichacz** [phoenixframework/phoenix_live_view#696]
Hello, I've noticed that behaviour of `mount()` callback has changed after upgrade from 0.8.1 to 0.9.0
In previous version things like this used to work:
```
mounted() {
        const el = this.el.parentNode;
        const inside = el.scrollWidth;
        console.log(inside); // would output some positive integer
},
```
**In 0.9.0 functionality changed when navigating between live views.**
Accessing url directly works perfectly fine, but when clicking on link (either live_path or live_redirect) it fires `mount()` too soon so the dimensions aren't there yet (setTimeout helps but before I didn't have to use it).

### Environment

* Elixir version (elixir -v): Elixir 1.9.2 (compiled with Erlang/OTP 22)
* Phoenix version (mix deps): phoenix 1.4.15
* Phoenix LiveView version (mix deps): phoenix_live_view 0.9.0
* NodeJS version (node -v): v10.18.1
* NPM version (npm -v): 6.13.4
* Operating system: macOS Catalina
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, Safari
* Does the problem persist after removing "assets/node_modules" and trying again?: Yes

### Actual behavior

The DOM in `mounted()` callback is present, but some attributes (for example width or height) aren't set up yet (probably because callback fires before the DOM paint)

### Expected behavior

Inside `mount()` one can easily read `width` of the element that has ben put into DOM

**Comment by josevalim** [comment]
Hi @cichacz, this has been fixed in master.

**Comment by cichacz** [comment]
Oh thanks, next time I'll also compare with master :)
