### ISSUE TITLE
Liveview mount triggers 3 times during page load on firefox

### ISSUE THREAD

**Issue by edgarmiadzieles** [phoenixframework/phoenix_live_view#700]
### Environment

* Elixir version (elixir -v): 1.9.2
* Phoenix version (mix deps): 1.4.15
* Phoenix LiveView version (mix deps): 0.9.0
* NodeJS version (node -v): v10.16.3
* NPM version (npm -v): 6.9.0
* Operating system: Linux
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox, Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:Yes

### Actual behavior

Setup new phoenix liveview project and set:
    plug :put_live_layout, {ProjectWeb.LayoutView, :app}
and call lvieview with
    live "/path" SomeLiveView

Render in :app with
`render @view_module, @view_template, assigns`

Triggers mount 3 times when javascript has:
```
const csrfToken = document
    .querySelector("meta[name='csrf-token']")
    .getAttribute("content");
  const liveSocket = new LiveSocket("/live", Socket, {
    params: { _csrf_token: csrfToken },
    hooks: Hooks
  });
  liveSocket.connect();
```
When debug is enabled in console I can see an error: 
`phx-FfvN1R0MebhHWgLF error: view crashed -  undefined`
before the actual connect.

The socket in liveview reports connected? to be:

- false
- true
- true

### Expected behavior

The view connects gracefully the first time or reports a better error message for debugging.

**Comment by josevalim** [comment]
Please update to master and try it again. Remember to remove `assets/node_modules` after upgrading. If it persists, please provide a sample application that reproduces the error, pointing to master. :)

Btw, what do you see logged in your application console? During these three loads?

**Comment by edgarmiadzieles** [comment]
Thank you for such quick reply!
A couple things:
I couldn't replace plug put_live_layout with put_root_layout in router (no such function) and tried to set a layout option in in my liveview file. This worked, however I had to replace all the @conn with @socket and convert my app.html.eex to app.html.leex which is not desired. Maybe I'm unaware of some changes and this is expected behaviour :)
In any case, previously described issue still persist in firefox.
I will be able to provide a link to the app later today.

**Comment by josevalim** [comment]
> I couldn't replace plug put_live_layout with put_root_layout in router (no such function) and tried to set a layout option in in my liveview file

You need to use phoenix in the v1.4 branch too. :)

**Comment by edgarmiadzieles** [comment]
Hey, small update

> You need to use phoenix in the v1.4 branch too. :)
Yup, I missed that, thank you! put_root_layout is working now.

For future reference: 
` {:phoenix, git: "https://github.com/phoenixframework/phoenix.git", branch: "v1.4", override: true},`

Now I'm getting:
```Firefox can’t establish a connection to the server at ws://localhost:3009/live/websocket?_csrf_token=JX0eAlkEBQwtCyxUDho9OwwlAgEiOWcAkJlxnkTHfgF1lcH_YjRtZIR4&vsn=2.0.0.```
But at least the mount will only be called twice during connected? false and then true.
Thank you very much!
