### ISSUE TITLE
Rendered view is not properly diffed when wrapping content in functions

### ISSUE THREAD

**Issue by schrockwell** [phoenixframework/phoenix_live_view#702]
### Environment

* Elixir version (elixir -v): 1.9.2
* Phoenix version (mix deps): master (commit 8762e84c8bf1a51a04bd832a39bf7ea070dbc4fc)
* Phoenix LiveView version (mix deps): 0.9.0
* NodeJS version (node -v): v12.12.0
* NPM version (npm -v): 6.11.3
* Operating system: macOS 10.14.6
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, Firefox, Safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

In this particular circumstance, assigns are updated and the LiveView `render/1` callback is called, but the diff fails to detect any changes, and so no changes are pushed to the client.

Here is a minimal reproduction repo (based on Phoenix master, run within the `installer` directory): https://github.com/schrockwell/phx_live_view_weird_render

### Expected behavior

Changes to the rendered view are detected and diffs are pushed to the client.

### More Information

This particular LiveEEx template structure appears to be the root cause.

```
# lib/my_app_web/templates/page/index1.html.leex
<%= div_tag do %>
    index 1
    <button phx-click="toggle">Toggle it!</button>
<% end %>

# lib/my_app_web/templates/page/index2.html.leex
<%= div_tag do %>
    index 2
    <button phx-click="toggle">Toggle it!</button>
<% end %>
```

`div_tag/1` is a view function that wraps up its contents with some outer HTML:

```
# lib/my_app_web/views/page_view.ex
  def div_tag(do: content) do
    ~E"""
    <div><%= content %></div>
    """
  end
```

A few observations:

* Probably related to #393 – i.e. maybe just my misunderstanding of how LiveView is able to detect changes
* `div_tag/1` does not reference any template assigns in its arguments - if any assigns are referenced in the arguments, the problem is resolved
* Any changes to static content of either index1 or index2 template OUTSIDE of `div_tag` block resolves the problem, e.g. adding a single character to index1
* When toggling between index1 and index2 templates, the fingerprint of the rendered view remains exactly the same

**Comment by azazel75** [comment]
I think you should use  the `~L` sigil instead of `~E` to get change tracking, see https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.Helpers.html#sigil_L/2
