### ISSUE TITLE
send(self(), xxx) does not trigger handle_info(xxx, socket) in live view

### ISSUE THREAD

**Issue by nocivus** [phoenixframework/phoenix_live_view#704]
Environment
Elixir version (elixir -v): 1.10.1
Phoenix version (mix deps): 1.4.15
Phoenix LiveView version (mix deps): 0.9.0
NodeJS version (node -v): v10.16.3
NPM version (npm -v): 6.9.0
Operating system: OSX
* Browsers you attempted to reproduce this bug on (the more the merrier): Opera
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

Sidenote: This started happening after migrating LiveView from 0.6.0 to 0.9.0 and Phoenix from 1.4.14 to 1.4.15.

### Actual behavior

Given the following code inside a LiveView:

```
  # def handle_info({:load_blueprints, _params}, socket) do
  #   {:noreply,
  #    assign(socket,
  #      loading: false,
  #      blueprints: Data.list_blueprints()
  #    )}
  # end

  def handle_params(params, _uri, socket) do
    IO.inspect("what?")
    send(self(), {:load_blueprints, params})
    {:noreply, assign(socket, loading: true)}
  end
```

I would expect to get an error that the handle_info is not defined. If i uncomment the handle_info function and put an inspect there, i also don't see it being triggered. "what?" however is printed out, so i'm suspecting that send() is not actually sending the message to the live view.

### Expected behavior

Get an error that handle_info is not defined.

Any advice appreciated, thanks!!!

**Comment by sfusato** [comment]
Make sure you don't forget to check if the socket is connected: `if connected?(socket)`

**Comment by nocivus** [comment]
Just realised i no longer have a layout. Weren't the put_root_layout breaking changes only supposed to be in 0.9.1? I wonder if related to that...

**Comment by nocivus** [comment]
Yep the layout missing was the culprit. Was missing this in my browser pipeline:

```
plug :put_live_layout, {MyAppWeb.LayoutView, "app.html"}
```

I'm an idiot but at least i hope this helps others dealing with the migration :)

**Comment by nocivus** [comment]
Could be worth it to change the `Add put_live_layout plug to put the root layout used for live routes` line in the changelog to `breaking changes`, though.
