### ISSUE TITLE
0.9.1 Issue with WebSocket connection

### ISSUE THREAD

**Issue by SebastianStroniewskiWojtczak** [phoenixframework/phoenix_live_view#705]
### Environment

* Elixir version (elixir -v): 1.9.4
* Phoenix version (mix deps): 1.4.16
* Phoenix LiveView version (mix deps): 0.9.1
* NodeJS version (node -v): 13.10.1
* NPM version (npm -v): 6.12.1
* Operating system: FreeBSD 12.1p2
* Browsers you attempted to reproduce this bug on (the more the merrier): Chromium/Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

With LiveView 0.9.1 I found that LiveSocket doesn't connect to WebSocket. I've dump "liveSocket" in JS and found that "this.main" is Null and this.socket didn't connect to WebSocket.

### Expected behavior
Connect to WebSocket by "this.socket.onOpen(()"  in class LiveSocket.
I've used example available in phoenix_live_view and modify mix.exs to use Git version for PhoenixLiveView. Another app I've tried was https://github.com/dwyl/phoenix-liveview-counter-tutorial where mix.exs has been modified and put_root_layout has been used instead of put_live_layout.
Another thing which comes to my mind is that, Live node in version 0.9.0 is expanded to "\<main\>\</main\>" while in 0.9.1 it remains '\<div id=main\>\</main\>"

Most interesting is that, If I use LiveView 0.9.0 and open WebBrowser everything works, then, I made changes to use LiveView 0.9.1 and clean deps/get. Afterward, once I run phx.server and go back to my web browser which I didn't refresh my browser establish connection back and all events starts working as expected, however, If I refresh that Browser -> JavaScript is unable to connect to WebSocket.

**Comment by josevalim** [comment]
Please remove assets/node_modules and compile again the client and server match. Thanks!

**Comment by SebastianStroniewskiWojtczak** [comment]
I've just removed assets/node_modules and 'npm install ; node node_modules/webpack/bin/webpack.js --mode development' and issue exist.

I've prepared fresh repo https://github.com/SebastianStroniewskiWojtczak/lvt.git

I'm trying to access : http://localhost:4000/countershare 
and play with -/+ buttons

**Comment by sfusato** [comment]
In your root layout you forgot to replace `@live_view_module.render(assigns)` with `@inner_content` needed for the 0.9.1 upgrade.

After this change, everything works.

**Comment by josevalim** [comment]
Thanks @sfusato!
