### ISSUE TITLE
HTTP Headers disappeared

### ISSUE THREAD

**Issue by pcarvsilva** [phoenixframework/phoenix_live_view#706]
### Environment

* Elixir 1.9.1 (compiled with Erlang/OTP 21)
* phoenix 1.4.16
* phoenix_live_view 0.9.0
* Node v12.11.1
* NPM 6.11.3
* Ubuntu
* Only tried in Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: YES

### Actual behavior

Just migrated to Live View's github version and the http header has disappeared 

### Expected behavior

The header should appear after sending then

**Comment by josevalim** [comment]
Can you please provide more information? How are you passing the headers to LiveView? How are you verifying them? Provide as much information as you can, otherwise there isn’t much we can do. Thanks.

**Comment by pcarvsilva** [comment]
Actually i've just found out the it's not rendenring the app.html.eex at all

**Comment by josevalim** [comment]
Yes, it needs to be opt-in now. Please see the CHANGELOG.
