### ISSUE TITLE
JavaScript question

### ISSUE THREAD

**Issue by yysun** [phoenixframework/phoenix_live_view#717]
Hi, I am the author of an event-driven JS library, called [AppRun](https://apprun.js.org).  I am interested in connecting AppRun apps to LiveView, similar to what I did [with nodejs](https://dev.to/yysun/create-a-phoenix-liveview-like-app-in-js-with-apprun-dc8). Does LiveView provide an API for JS libraries to connect?

**Comment by azazel75** [comment]
Hi, you can find a brief documentation of the "bridge" with JS here: https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#module-js-interop-and-client-controlled-dom

**Comment by yysun** [comment]
Thanks for the info.
