### ISSUE TITLE
Conditional child view errors when destroying

### ISSUE THREAD

**Issue by robinvdvleuten** [phoenixframework/phoenix_live_view#718]
### Environment

* Elixir version (elixir -v): 1.10.2
* Phoenix version (mix deps): 1.4.16
* Phoenix LiveView version (mix deps): 0.10.0
* NodeJS version (node -v): 10.15.1
* NPM version (npm -v): 6.14.2
* Operating system: Macos
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

When I conditionally render a nested child within a template;

```eex
<%= if @modal do %>
  <div phx-hook="Modal">
    <%= live_render(@socket, UserLive.Form, id: "user-form") %>
  </div>
<% end %>
```

When the child view is removed by toggling `@modal` from `true` to `false`, the LiveView's Javascript throws an error;

```
phoenix_live_view.js:733 Uncaught TypeError: Cannot read property 'id' of null
```

### Expected behavior

I expect the Javascript to handle the removed child correctly.

**Comment by josevalim** [comment]
Can you please try master? Make sure to remove assets/node_modules after updating. If that doesn't work, please provide a small application that reproduces the error. Thank you!

**Comment by robinvdvleuten** [comment]
@josevalim sure! I've created a minimal repository where you can reproduce the issue => https://github.com/robinvdvleuten/phoenix-liveview-issue

**Comment by sfusato** [comment]
For what it's worth, if you remove the `div` container inside the `if` statement, there won't be any error.

**Comment by robinvdvleuten** [comment]
@chrismccord thank you for fixing this so quickly!
