### ISSUE TITLE
Local changes done with JS hook are discarded when an event is fired

### ISSUE THREAD

**Issue by Softknobs** [phoenixframework/phoenix_live_view#719]
### Environment

* Elixir version (elixir -v):
Erlang/OTP 21 [erts-10.3] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]
Elixir 1.9.2 (compiled with Erlang/OTP 20)
* Phoenix version (mix deps):
phoenix 1.4.16 (Hex package) (mix)
* Phoenix LiveView version (mix deps):
0.10.0
* NodeJS version (node -v):
v12.13.0
* NPM version (npm -v):
6.12.0
* Operating system:
Windows 10 x64
* Browsers you attempted to reproduce this bug on (the more the merrier): 
Chrome

### Actual behavior

When doing changes to the DOM with JS, the changes are discarded when an event is fired (ex: phx-click, phx-windows-keydown).
Maybe this is intended or cannot be done otherwise but it would be limitating.

This means that if a listener, or anything else, displays results locally (that do not need to go to server for performance reasons for example), those are discarded once a LiveView event is fired.

Here is a simple example of a counter LiveView. When mounted, the "mounted" event in the hook set the color of one item to red. This color is reverted to black (the first rendered color) when "+" or "-" are clicked, or "Esc" is pressed

```
defmodule DemoWeb.Test do
  use Phoenix.LiveView

  def render(assigns) do
    ~L"""
    <div phx-window-keydown="monitor_escape" phx-hook="Test">
    <h1>The count is: <%= @val %></h1>
    <h1 id="text_id">This text should remain red</h1>
    <button phx-click="dec">-</button>
    <button phx-click="inc">+</button>
    </div>
    """
  end
  
  def mount(params, _session, socket) do
    socket = assign(socket, :val, 0)
    socket = assign(socket, :message, "hello")
    {:ok, socket}
  end

  def handle_event("inc", _, socket) do
    {:noreply, update(socket, :val, &(&1 + 1))}
  end
  def handle_event("dec", _, socket) do
    {:noreply, update(socket, :val, &(&1 - 1))}
  end

  def handle_event("monitor_escape", %{"code" => "Escape"} = keys, socket) do
    {:noreply, update(socket, :val, &(&1 - 1))}
  end

  def handle_event("monitor_escape", _, socket) do
    {:noreply, socket}
  end

end
```

app.js hook:
```
Hooks.Test = {
    mounted() {
        console.log("mounted_hook")
        var tst = document.getElementById("text_id")
        tst.style.color = "red"
    }
}
```

### Expected behavior

The changes should remain. If this is a technical limitation, it should be documented.

**Comment by chrismccord** [comment]
This is by design and well documented. Check the docs for `phx-update=ignore`. Thanks!

**Comment by Softknobs** [comment]
Sorry, I looked at the JS part of the doc, now it makes sense. Thank you.
