### ISSUE TITLE
Injected LiveView parent element breaks Flexbox layout

### ISSUE THREAD

**Issue by jamilabreu** [phoenixframework/phoenix_live_view#72]
### Expected behavior
Ability to modify / edit attributes (class, style, data-*, etc.) of the element injected by LiveView

### Actual behavior
Injected LiveView element breaks layout when it's the child of a flexbox element

**Comment by josevalim** [comment]
Generally speaking, if you change the class/style/data-* of any element injected by LiveView, that change will be lost when you get the next data from the server, because the whole point of LiveView is syncing the server and client.

**Comment by jamilabreu** [comment]
@josevalim Sorry for not being specific enough - I meant the parent element (not the elements rendered by the LiveView, but the element holding those rendered elements that is injected into the HTML). It looks like this:

`<div id="phx-/wom+Yo1AYU=" data-phx-view="AppWeb.ExampleLive" data-phx-session="..." class="phx-connected"></div>`

**Comment by chrismccord** [comment]
Phoenix wraps the LV in a parent div container, so your css rules must accommodate the container's presence

**Comment by jamilabreu** [comment]
@chrismccord I might not be understanding, but here's an example situation:

```
<div style="flex flex-column height-screen"> 
  <div style="flex-none">Nav Bar</div>
  <div style="flex-none">More Stuff</div>
  <div style="flex flex-grow">
    <div data-phx-view="AppWeb.ExampleLive" class="phx-connected">
      Elements in the render function appear here...
    </div>
    <div></div>
  </div>
</div>
```
At the moment, the only solution here is to make the LiveView render the entire page - which may not be the most desirable as the page gets more complex?

**Comment by chrismccord** [comment]
I'm not up to speed on flex box. What does the container element need specifically to make this work within flexbox? Is it simply an option of flex/flex-grow/flex-none? We s should be able to provide an extension point here for the container attrs if that's all it would take.

**Comment by snewcomer** [comment]
@jamilabreu Are you perhaps looking for a "widget" style component so you don't have to render the whole page?  I think there is an example in the phoenix_live_view_example repo, but not sure which one.

https://github.com/phoenixframework/phoenix_live_view/pull/43
https://github.com/chrismccord/phoenix_live_view_example

**Comment by jamilabreu** [comment]
@chrismccord In this specific case, container/parent element would need a class of "flex" and "flex-grow" - or a style attribute with "style='display: flex; etc...'". Generally speaking, a way to set custom attributes on the element (`class`, `style`, `data-*`, etc.) would be 💯 

@snewcomer I believe the example above is the "widget" style

**Comment by chrismccord** [comment]
@jamilabreu is it correct to say a single css rule would also fix this? If that's the case, I would prefer that route, and we can better document the container. If all you need is a css rule, then it avoids complecting the API when other solutions exist.

**Comment by jamilabreu** [comment]
@chrismccord That got me thinking! If `data-phx-view` doesn't change, adding this rule works:
```
div[data-phx-view="AppWeb.ExampleLive"] {
  display: flex;
  etc...
}
```
Tiny Caveat: Doesn't allow reusing the LiveView on a different page with different styling requirements. 
Tiny Caveat #2: Those using utility-first CSS frameworks like [Tailwind](https://tailwindcss.com/docs/what-is-tailwind/) usually prefer to style their elements strictly using utility classes, and not dive into a separate stylesheet

**Comment by Awlexus** [comment]
> Generally speaking, if you change the class/style/data-* of any element injected by LiveView, that change will be lost when you get the next data from the server, because the whole point of LiveView is syncing the server and client.

I currently have a bug where the navigation tabs with JQuery UI don't work/render incorrectly. Does that mean this bug occures, because the JS changes are overwritten by LiveView?

**Comment by josevalim** [comment]
Yes. LiveView can play fine alongside other tools but inside LiveView everything that changes will be undone on the next server push.

**Comment by Awlexus** [comment]
Would it be possible to make sections that are not overwritten after an update was pushed?

**Comment by jamilabreu** [comment]
@Awlexus not sure of your specific code, but two suggestions

- If you're rendering LiveView from the controller, use `<%= live_render... ` in your template instead, and move the static code out of your LiveView and into the template.

- I believe you can nest a LiveView inside another LiveView - and only update the nested one as needed. That way the parent LiveView stays the same, except for the nested view.

**Comment by Awlexus** [comment]
It is once again a js modification, that I want to perform. It's a drop-in payment component, which should not be server side rendered, but after looking how you have to implement it, I probably have to propose a different solution
