### ISSUE TITLE
phx-hook doesn't get triggered

### ISSUE THREAD

**Issue by seb3s** [phoenixframework/phoenix_live_view#722]
### Environment

* Elixir version (elixir -v): 1.10.0
* Phoenix version (mix deps): 1.4.16
* Phoenix LiveView version (mix deps): master
* NodeJS version (node -v): 10.15.3
* NPM version (npm -v): 6.4.1
* Operating system: debian stretch
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:

### Actual behavior
phx-hook doesn't get triggered on morphdom updates when sharing a similar dom structure 

### Expected behavior
should be triggered ;-)

**Comment by chrismccord** [comment]
Can you provide a minimal example project that recreates your issue? We need more information to be able to help here :)

**Comment by seb3s** [comment]
Yes, I've submitted a bit to quickly ;-)
I was missing some ids on the nodes that have the phx-hook as specified in the documentation. It gets properly triggered when I added these ids. 
At first it functions without the ids when the dom structure is not the same, so that's the reason why I get confused.
