### ISSUE TITLE
LiveView -> LiveComponent -> LiveView nesting throws an exception

### ISSUE THREAD

**Issue by ccapndave** [phoenixframework/phoenix_live_view#725]
### Environment

* Elixir version (elixir -v): 1.9.2
* Phoenix version (mix deps): 1.5.0-dev (afeffe8)
* Phoenix LiveView version (mix deps): 0.10.0 (fa668d1)

### Actual behavior

I have a top level `LiveView`, using the `live` router macro.  This contains a `LiveComponent`, which in turn contains another `LiveView`.

In this situation I get the following error:

```
** (exit) an exception was raised:
    ** (KeyError) key :conn_session not found in: %{}
        (phoenix_live_view) lib/phoenix_live_view/static.ex:228: Phoenix.LiveView.Static.disconnected_nested_render/6
        (alchemy_web) lib/alchemy_web/templates/manageable/selector.html.leex:37: anonymous fn/2 in AlchemyWeb.ManageableView."selector.html"/1
        (phoenix_live_view) lib/phoenix_live_view/diff.ex:221: Phoenix.LiveView.Diff.traverse/5
        (phoenix_live_view) lib/phoenix_live_view/diff.ex:452: Phoenix.LiveView.Diff.render_component/7
        (phoenix_live_view) lib/phoenix_live_view/diff.ex:401: anonymous fn/5 in Phoenix.LiveView.Diff.render_pending_components/5
        (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
        (stdlib) maps.erl:232: :maps.fold_1/3
        (phoenix_live_view) lib/phoenix_live_view/diff.ex:384: Phoenix.LiveView.Diff.render_pending_components/5
        (phoenix_live_view) lib/phoenix_live_view/diff.ex:95: Phoenix.LiveView.Diff.render/3
        (phoenix_live_view) lib/phoenix_live_view/static.ex:275: Phoenix.LiveView.Static.to_rendered_content_tag/4
        (phoenix_live_view) lib/phoenix_live_view/static.ex:137: Phoenix.LiveView.Static.render/3
        (phoenix_live_view) lib/phoenix_live_view/controller.ex:35: Phoenix.LiveView.Controller.live_render/3
        (phoenix) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (alchemy_web) lib/alchemy_web/endpoint.ex:1: AlchemyWeb.Endpoint.plug_builder_call/2
        (alchemy_web) lib/plug/debugger.ex:132: AlchemyWeb.Endpoint."call (overridable 3)"/2
        (alchemy_web) lib/alchemy_web/endpoint.ex:1: AlchemyWeb.Endpoint.call/2
        (phoenix) lib/phoenix/endpoint/cowboy2_handler.ex:42: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy) /Users/dave/Projects/Couloir/ctp/alchemy/deps/cowboy/src/cowboy_handler.erl:41: :cowboy_handler.execute/2
        (cowboy) /Users/dave/Projects/Couloir/ctp/alchemy/deps/cowboy/src/cowboy_stream_h.erl:320: :cowboy_stream_h.execute/3
        (cowboy) /Users/dave/Projects/Couloir/ctp/alchemy/deps/cowboy/src/cowboy_stream_h.erl:302: :cowboy_stream_h.request_process/3
```

**Comment by josevalim** [comment]
Thanks. This is not supported but we should definitely improve the error message.

**Comment by ccapndave** [comment]
Just to give some background, my application is structured as a top-level `LiveView` (with `live`) in the router, and then templates with a bunch of nested components.  In various bits of this structure I have bits - for example a search box and an import popup - whose errors I want to keep isolated so they don't bring down their parents.

I wonder if this might be a common(ish) situation once folks start using liveview more and more in the structure of their apps.

Is there anything I could do to help out implementing this feature, or is it going to be very complicated?

**Comment by josevalim** [comment]
To be honest I am not super sure of how much work it will be. Someone would have to give it a try. :)

**Comment by haseebeqx** [comment]
@ccapndave I believe your problem will be solvable using `phx-target` with an `id` in `live_component`.

**Comment by ccapndave** [comment]
The component won't even mount; the application crashes when it reaches `live_component` so it can't even get to a place where `phx-target` could be used.

**Comment by haseebeqx** [comment]
I Mean instead of the inner live_view, use a `live_component`. Since your requirement is to isolate error messages, setting a `phx-target`  will do it. See this example https://github.com/chrismccord/phoenix_live_view_example/blob/45e81edf15c32d480bcbd9ec84e767ba46cd466b/lib/demo_web/live/user_live/index_auto_scroll.ex#L13 . You can check how incrementing count on click is handled here and in `Email` and `Row`. I think you have a similar requirement.

**Comment by ccapndave** [comment]
Ah I see.  In this case I want the inner "thing" to have its own supervision tree, running in its own process so that a crash doesn't bring down the parent liveview, so a component won't work here.

**Comment by ccapndave** [comment]
The basic problem seems to be that the `parent` socket is the component's socket, but `live_render` expects the parent socket to be the liveview's socket with a few things in `private` and a `root_pid` (and maybe some other things).

If its any help I have made a test reproducing the issue in https://github.com/ccapndave/phoenix_live_view/tree/nested-live-view

**Comment by ccapndave** [comment]
I've made a change, also in this branch, which merges the existing `private` map with any new `private` map when creating a `Socket` for a component.  All the tests pass, including mine, but someone had better have a look at it :)

**Comment by josevalim** [comment]
Your changes actually look great except that, instead of passing the whole private, I would only pass the relevant parts. Also, can you please rename the fixture to "live_in_component" or similar? You can move the test itself integrations/live_view_test.exs. Thanks!
