### ISSUE TITLE
Move app.js inclusion into head of app.html.eex?

### ISSUE THREAD

**Issue by dbi1** [phoenixframework/phoenix_live_view#727]
Hello,

in the [installation guide for LiveView v0.10.0](https://hexdocs.pm/phoenix_live_view/0.10.0/installation.html#content) it says to 

"Ensure you have placed a CSRF meta tag inside the head tag in your layout (lib/my_app_web/templates/layout/app.html.eex), before app.js is included like so"...

I read this as meaning that in addition to adding a CSRF meta tag into the head, I also need to move the app.js inclusion from the bottom of the file into the head, correct? Phoenix 1.4.16 places it at the bottom of the file when generating a new project.

Or did you maybe mean app.css instead of app.js, since this is already in the head?

Thank you for the great work on Phoenix and LiveView!

**Comment by josevalim** [comment]
It just needs to be before app.js. If you want to have app.js at the top or at the bottom is your call. :)

**Comment by dbi1** [comment]
Got it, thanks :)

**Comment by aptinio** [comment]
See phoenixframework/phoenix#3656 for how it's done now in master.
