### ISSUE TITLE
Installation instrutctions missing put_root_layout

### ISSUE THREAD

**Issue by afs091** [phoenixframework/phoenix_live_view#732]
Hello,

In the installation instructions on hexdocs for LiveView 0.10.0 (https://hexdocs.pm/phoenix_live_view/installation.html#content),  is missing the `plug :put_root_layout` for `lib/my_app_web/router.ex` file. Also an instruction to add, `root.html.eex` and `live.html.leex` to `templates/layouts` will help setting up LiveView easly for new users.

Thank you all!

**Comment by josevalim** [comment]
Thanks @afs091! The latest version of the docs cover this, so as soon as we do a new release it will be better, thanks!
