### ISSUE TITLE
live_render inside of template conditional creates empty liveview div

### ISSUE THREAD

**Issue by carterbryden** [phoenixframework/phoenix_live_view#740]
### Environment

* Elixir version (elixir -v): 1.9.4
* Phoenix version (mix deps): 1.4.16
* Phoenix LiveView version (mix deps): 
phoenix_live_view 0.10.0  - pulling from latest master branch on github
(https://github.com/leandrocp/phoenix_live_view.git) (mix)
  locked at 88e94da (branch: master)
* NodeJS version (node -v): v8.12.0
* NPM version (npm -v): 6.4.1
* Operating system: Ubuntu 16.04
* Browsers you attempted to reproduce this bug on (the more the merrier):
Chrome Version 80.0.3987.149 (Official Build) (64-bit)
Firefox 74.0 (64-bit)
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior
See below. Only the outer test content div renders. The live_render call produces a liveview div with no html content inside at all.
```
#Ticket Liveview
<%= if(@ticket != false and @editing == false) do %>
    <div>Some outer test content that always renders when the conditional passes</div>
    <%= live_render(@socket, HotlineWeb.TicketNoteEditorLive, id: "ticket_editor_ticket_note_editor", session: %{"current_user" => @current_user}) %>
<% else %>
<% end %>
```
This **does** render the live_render properly when it's outside the conditional as below:
```
#live_render works just fine here, outside of the if statement
<%= live_render(@socket, HotlineWeb.TicketNoteEditorLive, id: "ticket_editor_ticket_note_editor", session: %{"current_user" => @current_user}) %>

<%= if(@ticket != false and @editing == false) do %>
    <div>Some outer test content that always renders when the conditional passes</div>
<% else %>
<% end %>
```

The ticket_note_editor.html.leex template, just for testing I put a single line of text:
```
<div>This content comes from inside the live_render!</div>
```

The outer test content always renders, I've made sure that `@ticket` and `@editing` are the right values to pass the conditional. But the live_render creates an empty div if it's inside that conditional, no matter what.

I get no JS errors and no elixir errors at all.

### Expected behavior
It renders the ticket note editor liveview template properly instead of an empty div.

**Comment by josevalim** [comment]
Can please provide a sample application that reproduces the error? Thank you very much!

**Comment by josevalim** [comment]
Please let us know if there is a way to reproduce this. Thanks!
