### ISSUE TITLE
Inconsistent behavior when using phx-target

### ISSUE THREAD

**Issue by D4no0** [phoenixframework/phoenix_live_view#741]
Currently when using `phx-target` from component, as stated in documentation can be used with query selector: `phx-target="#user-13"`.

When using it with query selector it works as expected, however I noticed a strange behavior when calling it without query selector: `phx-target="user-13"`. By using it this way, at least (seems it touches only the liveview component and the parent liveview) have the event triggered, if they have an element with such name like: `<user-13 />`

Is this the expected behavior?

**Comment by josevalim** [comment]
Yes. That's how query selectors work. :)
