### ISSUE TITLE
not type submit button of form_for on live component trigger submit

### ISSUE THREAD

**Issue by pojiro** [phoenixframework/phoenix_live_view#743]
### Environment

* Elixir version (elixir -v): 1.10.1
* Phoenix version (mix deps): 1.4.16
* Phoenix LiveView version (mix deps): 0.10.0
* NodeJS version (node -v): 12.14.0
* NPM version (npm -v): 6.13.4
* Operating system: Linux
* Browsers you attempted to reproduce this bug on (the more the merrier): chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes

### Actual behavior

I'm making a form on live component like below.

```
    <div id="<%= @id %>">
      <%= f = form_for @changeset, "#", [phx_target: "##{@id}", phx_submit: :save] %>
        <%= text_input f, :name %>
        <%= submit "Save" %>
        <button phx-click="cancel" phx-target="#<%= @id %>">Cancel</button>
      </form>
    </div>
```

Clicking cancel button triggers event "cancel" and "save" both.
I made reproduce branch [here](https://github.com/pojiro/lv_test)

Could you check the behavior? Reproduction page is root path, http://localhost:4000/

![Peek 2020-03-31 19-43](https://user-images.githubusercontent.com/4096956/78017931-fc5db400-7387-11ea-87f0-e5440464aa83.gif)

### Expected behavior

not type submit button should not trigger submit

.

**Comment by chrismccord** [comment]
The default type for a button in a form is "submit". Use `<button type="button">...` to get the behavior you want. Thanks!
