### ISSUE TITLE
Proper approach to 'form-less' inputs?

### ISSUE THREAD

**Issue by Qqwy** [phoenixframework/phoenix_live_view#744]
I am working on a GUI that is driven using LiveView.

A problem I am currently facing, is that this GUI contains many different fields, which control other parts of the app. Changing the GUI fields (consisting mostly of sliders, radio buttons, toggles) immediately has an effect on what happens elsewhere in the application.

As such, this is different from scenarios in which LiveView is used for validation of an (otherwise normal) HTML form.

The problem I am facing, is that LiveView prefers on using `phx-change` on a form tag surrounding the input elements, and will send the whole form to `handle_event` every time a change happens. 

This seems wasteful for this use-case.

Are there alternative approaches? One approach might be to wrap all input elements in their own form, but that also seems sub-optimal for obvious reasons.

Also, it seems like `phx-value-*` set on an input element are also not becoming part of the parameters sent whenever it changes. Is this related to the special treatment that input fields get?

**Comment by chrismccord** [comment]
phx-change is the way to go for now. Thanks!

**Comment by chrismccord** [comment]
In the future will will allow individual changes, but it will be opt in and you'll be required for tracking it on the server. In the meantime, you can add `phx-debounce` with a timer or `"blur"` to send less data.
