### ISSUE TITLE
Controlling the "loading spinner"

### ISSUE THREAD

**Issue by dbi1** [phoenixframework/phoenix_live_view#746]
Hello,

I was wondering if there is any way to suppress/control the loading spinner that blinks in quickly when loading a page that uses live_view, and also when navigating away from it?

Thank you!

**Comment by josevalim** [comment]
Yes. Simply do not copy the liveview.css and implement your own instead. Look at the LV .css for guidance. Also, please use the [ElixirForum](http://www.elixirforum.com) or StackOverflow for questions/help/feedback, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!

**Comment by dbi1** [comment]
Thank you, appreciate it, and will do!
