### ISSUE TITLE
Throwing phxlv error in the console.

### ISSUE THREAD

**Issue by ESP12** [phoenixframework/phoenix_live_view#748]
### Environment

* Elixir version (elixir -v): v 1.9.4
* Phoenix version (mix deps): v 1.4.16
* Phoenix LiveView version (mix deps):v 0.10.0
* NodeJS version (node -v): 12.14.1
* NPM version (npm -v): 6.13.4
* Operating system: Ubuntu 18.04
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, Mozilla 
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: no

### Actual behavior

I'm encountering this error in the console. What's causing it? I already tried updating my npm after installing the phoenix_live_view. This error shows whenever I trigger an phxlv event like phx-click, etc...
```
Uncaught TypeError: Cannot read property 'getDescendentByEl' of undefined
    at e.value (phoenix_live_view.js:712)
    at eval (phoenix_live_view.js:684)
    at K (phoenix_live_view.js:380)
    at e.value (phoenix_live_view.js:683)
    at e.value (phoenix_live_view.js:704)
    at eval (phoenix_live_view.js:990)
    at eval (phoenix_live_view.js:1034)
```

**Comment by chrismccord** [comment]
Please try master and let us know if this is still an issue you can recreate. Thanks!

**Comment by ESP12** [comment]
tried and still giving errors in the console
![Screenshot from 2020-04-01 10-45-53](https://user-images.githubusercontent.com/20061861/78093999-03c3a280-7406-11ea-80ad-db0678194be3.png)

**Comment by chrismccord** [comment]
Can you publish a minimal application that recreates this issue? That is the only way I would be able properly track this down as everything looks good on my end. Thanks!

**Comment by ESP12** [comment]
Hmmm... I just noticed something. The errors shows whenever I came from a main page of the app and after triggering a phx event in to the new page app...

**Comment by himrock922** [comment]
Hi Al.
same problem...

``` each envrionment
* Elixir 1.9.4
* phoneix_live_view 0.12.1
* phoenix 1.5.1
* npm 6.13.7
* nodejs 
```

### app.js

```app.js
import 'jquery/dist/jquery.slim.min';
import 'fuse.js/dist/fuse';
import 'popper.js/dist/popper.min';
import 'bootstrap/dist/js/bootstrap.min';
import 'bootstrap-select-dropdown/dist/bootstrap-select-dropdown.min';
import "phoenix_html"

import NProgress from "nprogress"
import {Socket} from "phoenix"
import {LiveSocket} from "phoenix_live_view"

$(window).on('load',function(){
  if(document.URL.match("daily_reports/new")) {
    let csrfToken = document.querySelector("meta[name='csrf-token']").getAttribute("content")
    let liveSocket = new LiveSocket("/live", Socket, {params: {_csrf_token: csrfToken}})
    
    // Show progress bar on live navigation and form submits
    window.addEventListener("phx:page-loading-start", info => NProgress.start())
    window.addEventListener("phx:page-loading-stop", info => NProgress.done())
    
    // connect if there are any LiveViews on the page
    liveSocket.connect()
    
    // expose liveSocket on window for web console debug logs and latency simulation:
    // >> liveSocket.enableDebug()
    // >> liveSocket.enableLatencySim(1000)
    window.liveSocket = liveSocket
  }
});
```

### new.html.leex

```
<button phx-click="add_articles" class="btn btn-success">#</button>
```

### new.ex

```
defmodule WeReportsWeb.DailyReports.New do
    use WeReportsWeb, :live_view
    use Phoenix.LiveView, layout: {WeReportsWeb.LayoutView, "live.html"}
    alias WeReports.UserManager
    require IEx

    @impl true
    def mount(_params, session, socket) do
      {:ok, user} = WeReportsWeb.Live.AuthHelper.load_user(session)
      group_lists = get_user_groups(user.id)
      socket = assign(socket, :current_user, user)
      socket = assign(socket, :groups, group_lists.groups)
      {:ok, assign(socket, query: "", results: %{})}
    end
  
...

    @impl true
    def handle_event("add_articles", _value, socket) do
      IEx.pry
    end
```

### capture

![test](https://user-images.githubusercontent.com/4998536/81027296-39055980-8eb8-11ea-8930-fdb13d034063.gif)
