### ISSUE TITLE
Show handle_event/3 errors in browser also?

### ISSUE THREAD

**Issue by dbi1** [phoenixframework/phoenix_live_view#752]
Hello,

while debugging a handle_event/3 call, I noticed that errors for handle_event/3 calls show up in my terminal only, but not in the browser.

No problem in general, easy to look the error up there, but  somehow I got so used to the really helpful and consistent Phoenix error reporting directly in the browser that I was wondering if it might make sense to show handle_event/3 errors in the browser also?

Thank you!

**Comment by chrismccord** [comment]
If you call `liveSocket.enableDebug()` you will get crash notifications, but this will not show any specific information about the server crash. Such a feature would be way down the road. Thanks!

**Comment by dbi1** [comment]
Got it, thanks!
