### ISSUE TITLE
Proposal: Add option to extend event attributes

### ISSUE THREAD

**Issue by haseebeqx** [phoenixframework/phoenix_live_view#753]
I would like to implement an option to add additional DOM events in liveview.

There will be two use cases to it. 
1. Support for new events.

Example:
```html
<a phx-onmouseover="showPreview" >link to issue</a>
```
2. send different data for existing events. 

Example: if someone wants to send only x and y positions of a click event. they can define a new event like `phx-onclick` globally.

### Proposal

Similar to hooks it will be passed as an option when initializing livesocket. 

```js
globalEvents = {
  mouseover: (el, callback)=>{
     el.addEventListner('mouseoveer', (event)=>{
          callback({current: event.target.id})
    })
  }
}

let liveSocket = new LiveSocket("/live", Socket, {additionalBindings: globalEvents, ...})
```

and in html 
```html
<p phx-mouseover="update_current" >Something</p>
```

Whatever passed to the `callback` function will be available in `handle_event("update_curent", ...`

It will be helpful for both 3rd party libraries and developers. Also it will provide a better js interop.

**Comment by chrismccord** [comment]
phx-hook has you covered for these use-cases. In the future please send feature proposals to the forums as we reserve the issue tracker for issues. thanks!
