### ISSUE TITLE
Proposal: Send `e.target.width/height` in `phx-click` params

### ISSUE THREAD

**Issue by Qqwy** [phoenixframework/phoenix_live_view#757]
When a `phx-click` event is triggered, a bunch of metadata about where the user clicked is sent as part of the `params` map.

One piece of information that is missing, is the current dimensions (width and height) of the targeted element that was clicked. This might be very useful information to translate between pixel coordinates to relative coordinates.

Currently we are limited to manually making sure that these sizes match between the used styling and the calculations on the back-end. This makes it difficult to create responsive elements (whose size/look change based on the client's screen dimensions).

If you agree, I'd love making a PR for this!

**Comment by chrismccord** [comment]
You can accomplish this with a hook today should you need it. In the future please keep feature proposals to the forums as we reserve the issue tracker for issues. Thanks!
