### ISSUE TITLE
feature request: support for dblclick event

### ISSUE THREAD

**Issue by ltd** [phoenixframework/phoenix_live_view#758]
There are still some good UX uses for double click.  

The obvious implementation would be phx-dblclick="", but an alternative might be to add a boolean flag  in the "click"  handle_event params,  marking a double click event.

**Comment by chrismccord** [comment]
You can accomplish this with a hook today should you need it. Thanks!

**Comment by sodapopcan** [comment]
Related: #427

I'm wondering if this is still a no-go.  Using a hook means that it cannot be tested with `LiveViewTest` which is unfortunate as I love `LiveViewTest`.  My use-case is double clicking a block of text to turn it into a `textarea` for editing.  There is certainly the argument to be made that this is generally bad UX, but in my case I'm making post-its where it's far too noisy to have an edit button.
