### ISSUE TITLE
Clarify how to communicate up and down the component tree

### ISSUE THREAD

**Issue by 1player** [phoenixframework/phoenix_live_view#764]
As a new user of this library, I think it would be great to document the correct and intended pattern to communicate from parent to child and viceversa.

## Parent to child communication

* Component -> Component: `send_update Component, ...`
* Component -> LiveView: ???
* LiveView -> Component: `send_update Component, ...`
* LiveView -> LiveView: ???

It is not clear how one is supposed to communicate with a child LiveView, except by setting one-time session data that's read on mount but cannot be updated.

Relevant unanswered discussion: https://elixirforum.com/t/communication-between-nested-liveviews-parent-child/30404/3 – in which I suggest exporting the PIDs of children liveviews so they can be communicated with, or alternatively, making `send_update` work with children LiveViews as well.

## Child to parent communication

* Component <- Component: `send_update Component, ...` – I don't think it's particularly clean for a child to update the parent data.
* Component <- LiveView: ???
* LiveView <- Component: `send self(), message`
* LiveView <- LiveView: `send socket.parent_pid, ...`

Sending data to a LiveView is easy, sending data to a parent component is a bit trickier, as AFAIK `send_update` is intended only for parent -> child communication and it feels like an anti-pattern to use it the other way.

And it does not seem to be possible to target a Component from a LiveView.

I think this library should, somehow, agree on a pattern that works with either Component or LiveView on both sides, perhaps inspired by the DOM model or React model: communication down the tree is done by setting parameters – making so that `send_update` works for both children Component and LiveViews – and communication up the tree with either messages or callbacks/lambdas.

The goal of this issue though is just to highlight the fact that a little documentation on the correct patterns, what's supported and what's not, might be a good idea to have.

**Comment by chrismccord** [comment]
Please keep feature discussions and proposals on the forums as we reserve the issue tracker for issues. The best parent/child communication patterns are something we are tracking but we aren't add the stage yet to write such documentation and the direction will largely be informed by what folks are doing in the wild. Thanks!

**Comment by josevalim** [comment]
Note there Are docs on LiveComponent talking about those.

**Comment by 1player** [comment]
Not really, I've read those docs a dozen times and the gist of it is summarised in my post. 

There are a few cases in my original post that are not mentioned in the docs, such as communication with a child LiveView, reason why I've created this issue.
