### ISSUE TITLE
LiveComponent do/end block inner content not updating

### ISSUE THREAD

**Issue by benwilson512** [phoenixframework/phoenix_live_view#766]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 22 [erts-10.6.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.10.0 (compiled with Erlang/OTP 22)
```
* Phoenix version (mix deps): 1.4.16
* Phoenix LiveView version (mix deps): 0.11.0
* NodeJS version (node -v): v10.4.1
* NPM version (npm -v): 6.10.3
* Operating system: OS X
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual Behavior

https://github.com/benwilson512/bug_example
LiveView:
```
    ~L"""
    <p>In live view</p>
    <p><%= @now %></p>

    <%= live_component(@socket, FooComponent) do %>
    <p>In component<p>
    <p><%= @now %></p>
    <% end %>
    """
```
Component:
```
    <div>
    <%= @inner_content.(assigns) %>
    </div>
```

Given some `@now` updated via the usual `send_after`, the assign live updates in the "in live view" bit but not for the part inside the component's `do end` block.

### Expected Behaviour

LiveView should either yell at me and tell me to put `@now` in the assigns of the component, or it should just automagically work. Working on the initial render but NOT capturing updates feels like a somewhat unintuitive middleground.

**Comment by josevalim** [comment]
Definitely a bug. Can you please check if the @inner_content line is being invoked at all? Wrapping it in IO.inspect should be enough.

**Comment by benwilson512** [comment]
It is, I see this every tick:

```
%Phoenix.LiveView.Rendered{
  dynamic: #Function<4.60138390/1 in DemoWeb.Bad.render/1>,
  fingerprint: 131263720852441055430768604737278977940,
  static: ["\n<p>In component<p>\n<p>", "</p>\n"]
}
```
Issue edited with a link to the full code.

**Comment by benwilson512** [comment]
By the way, which behaviour should I be expecting? Should it work automagically? Or should it tell me to pass it in as an explicit assign? If I do the latter by the way it works.

**Comment by benwilson512** [comment]
For posterity: it's supposed to work automagically.

**Comment by byronanderson** [comment]
I think I'm running into this one trying to implement a "transition" component like the one from react-transition-group: https://reactcommunity.org/react-transition-group/transition

What is the resolution of this issue?

Here is the relevant WIP component:

```elixir
defmodule Transition do
  use Phoenix.LiveComponent
  def mount(socket) do
    {:ok, socket |> assign(transition: [], ref: nil)}
  end

  def update(%{message: {:active, ref}}, socket) do
    if ref == socket.assigns[:ref] do
      {:ok, socket |> assign(:transition, socket.assigns[:transition] ++ [:active])}
    else
      {:ok, socket}
    end
  end

  def update(%{message: {:done, ref}}, socket) do
    if ref == socket.assigns[:ref] do
      {:ok, socket |> assign(:transition, socket.assigns[:transition] ++ [:done])}
    else
      {:ok, socket}
    end
  end

  def update(assigns, socket) do
    IO.inspect({"updating", assigns.inner_content.(transition: [:foo]).dynamic()})
    old_state = socket.assigns[:state]
    new_state = assigns[:state]

    if new_state != old_state do
      IO.inspect({"changed to ", new_state})
      ref = make_ref()

      # the parent live view uses the id to call `send_update` back to this component
      Process.send_after(
        self(),
        {:redirect_message, __MODULE__, assigns[:id], {:active, ref}},
        10
      )

      Process.send_after(
        self(),
        {:redirect_message, __MODULE__, assigns[:id], {:done, ref}},
        1000
      )

      {:ok,
       socket
       |> assign(assigns)
       |> assign(:ref, ref)
       |> assign(:transition, if(new_state, do: [:enter], else: [:exit]))}
    else
      {:ok, socket}
    end
  end

  def render(assigns) do
    ~L"""
      <%= @inner_content.([id: @id, transition: @transition]) %>
    """
  end
end

# in the parent liveview:
def handle_info({:redirect_message, module, id, message}, socket) do           
  send_update(module, id: id, message: message)                                
  {:noreply, socket}                                                           
end
```


With this example consumption:

```elixir
~L"""
<%= live_component(@socket, Transition, id: @card.id <> "-transition", state: transitionstate) do %>
  <%= live_component(@socket, PlayingCard, htmlClasses: @transition, card: @card %>
<% end %>
"""

I'm seeing that the `@transition` assign is updating to the client's web page correctly, but that the `@card` assign isn't.

**Comment by byronanderson** [comment]
For posterity: I found my issue ->

The transition component didn't accept the new inner_content assign in one of the `update` cases.

This is a different paradigm than I am used to -> in react a component can't simply refuse to receive new props - it would have to maintain the props in its separate state area.  I _had_ read that the assigns merging was just default implementation of update, so I think the docs don't need any more content, I think I just needed to make the mistake to internalize a different paradigm.

```elixir
  def update(assigns, socket) do
    old_state = socket.assigns[:state]
    new_state = assigns[:state]

    if new_state != old_state do
      # ...
    else
      {:ok, socket} # the bug is right here, the socket doesn't get assigned the new inner_content function that the parent view or component sent it
      # should have been: {:ok, socket |> assign(assigns)}
    end
  end
```
