### ISSUE TITLE
Targeting via myself breaks LiveViewTest

### ISSUE THREAD

**Issue by mcrumm** [phoenixframework/phoenix_live_view#767]
### Environment

* Elixir version (elixir -v): 1.10
* Phoenix version (mix deps): 1.5.0-dev
* Phoenix LiveView version (mix deps): 0.11.0
* NodeJS version (node -v): 12.16.1
* NPM version (npm -v): 6.13.4
* Operating system: MacOS
* Browsers you attempted to reproduce this bug on (the more the merrier): n/a
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: n/a

### Actual behavior

For instance, if I have a form in a component using `@myself`:

```eex
<form action="#" phx-submit="save" phx-target="<%= @myself %>">
</form>
```

and I want to exercise the "save" event in a test but my form no longer has an ID, so I try a different query selector:

```elixir
assert render_submit([show_live, "form"], "save", %{"widget" => @invalid_attrs}) =~ "Edit Widget"
```

Which leads to the following error:

```
14:52:39.607 [error] GenServer #PID<0.428.0> terminating
** (ArgumentError) could not find ID "form" in the DOM
    (phoenix_live_view 0.11.0) lib/phoenix_live_view/test/dom.ex:10: Phoenix.LiveViewTest.DOM.by_id!/2
    (phoenix_live_view 0.11.0) lib/phoenix_live_view/test/dom.ex:16: Phoenix.LiveViewTest.DOM.cid_by_id/2
    (phoenix_live_view 0.11.0) lib/phoenix_live_view/test/client_proxy.ex:582: Phoenix.LiveViewTest.ClientProxy.maybe_add_cid_to_payload/3
    (phoenix_live_view 0.11.0) lib/phoenix_live_view/test/client_proxy.ex:275: Phoenix.LiveViewTest.ClientProxy.handle_call/3
    (stdlib 3.11.2) gen_server.erl:661: :gen_server.try_handle_call/4
    (stdlib 3.11.2) gen_server.erl:690: :gen_server.handle_msg/6
    (stdlib 3.11.2) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.426.0>): {:render_event, "phx-FgNWR6vRe_AXDQFC", :form, ["form"], "save", "widget[name]="}
```

### Expected behavior

I can use a different query selector in conjunction with `@myself` to target a component in tests.

**Comment by mcrumm** [comment]
This came up using the `phx.gen.live` mix task on a Phoenix 1.5.0-dev project.

**Comment by andreaseriksson** [comment]
I can confirm this is an issue coming from here: 
https://github.com/phoenixframework/phoenix/commit/cd83fedf3bc842caaf850dedd05b65e4fe71bf0c#r38401004

**Comment by josevalim** [comment]
Fixed in master!
