### ISSUE TITLE
Failure rates for form recovery after server crash

### ISSUE THREAD

**Issue by dbi1** [phoenixframework/phoenix_live_view#768]
### Environment

* Elixir version (elixir -v): 1.9.4
* Phoenix version (mix deps): 1.4.16
* Phoenix LiveView version (mix deps): 0.10.0
* NodeJS version (node -v): 8.10.0
* NPM version (npm -v): 3.5.2
* Operating system: Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-64-generic x86_64)
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

Noticed fairly variable failure rates on form recovery following crashes, depending on how fast I restart the server after each crash.

Here are the stats (I ran at least 10 tests for each sleep length):

-Sleep 0 sec: 100% failure rate
-Sleep 1 sec: 50% failure rate
-Sleep 5 sec: 5% failure rate
-Sleep 10 sec: 0% failure rate
-Sleep 20 sec: 20% failure rate (a bit odd, tested with ca. 20 restarts)

My test looked as follows: I simply CTRL-C (x2) the server, and then manually triggered "sleep x; mix phx.server" as fast as I could (via arrow up on Mac). The server is remote, but liveview generally works super fast over that connection.

I noticed this while trying to figure out why my form recovery was so choppy. Two observations/thoughts:

1) In the case of failures, the ws connection ended up with a new csrf token
2) The highest failure rates occur when the ws "reconnect storm" (attempt frequency) is the highest. Might there be a conflict somehow?

Here is my liveview code:

```
def render(assigns) do
    ~L"""

    <form phx-change="type_live" phx-submit="submit">
      <input type="text" name="q" value="<%= @query %>" placeholder="Type something..."/>
    </form>

    """
  end

  def mount(_params, _session, socket) do
    {:ok, assign(socket, query: nil)}
  end

  def handle_event("type_live", %{"q" => query}, socket) do
    {:noreply, assign(socket, query: query)}
  end

  def handle_event("submit", %{"q" => query}, socket) do
    {:noreply, assign(socket, query: query)}
  end
```

### Expected behavior

I'd hope for essentially no form recovery failures when liveview reconnects to a server, independently of how quickly the restart happens :)

Thank you!

**Comment by josevalim** [comment]
Please try doing this with MIX_ENV=prod or disable code reloading in development and let us know. Many times the failures are because of the code reloading, because when you reconnect, the assets are often recompiled or manifest files are updated, and that causes the code reloading to reload the page, losing the form state.

**Comment by dbi1** [comment]
Great, thanks, that fixed it! Now it's recovering flawlessly with the 1 second sleep :)

(I set `code_reloader: false` in dev.exs)

**Comment by dbi1** [comment]
Awesome, thanks!
