### ISSUE TITLE
Add lazy_assign/recompute/changed

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix_live_view#771]
```elixir
def mount do
  socket
  |> lazy_assign(:posts, &assign_posts/1)
end

def handle_params(...) do
  socket
  |> assign(:dir, dir)
  |> recompute(:posts, changed?(socket, :dir) or changed?(socket, :limit))
end

defp assign_posts(socket) do
  %{dir: dir} = socket.assigns.direction

  socket
  |> assign(:posts, fetch_post())
  |> assign(...)
end
```

Notes:

* `recompute/2` accepts a boolean as second argument. It defaults to true. If false, it simply returns the socket.

* `recompute/2` needs to be idempotent. Calling recompute twice in the same "event" should not compute it twice. This can be done in to ways: 1. we only compute lazy assigns at the end of the event or 2. we compute lazy assigns immediately but we don't recompute it the assign is marked as `changed?` in the current loop

* the function given to `lazy_assigns` can compute multiple assigns. However, it MUST always compute the "titular" assign

**Comment by wrren** [comment]
Very useful feature! Would it be possible to allow both `lazy_assign/2` and `recompute/2` to accept a map so that multiple assigns can be quickly set up and refreshed in one go?

**Comment by josevalim** [comment]
For @wrren for `lazy_assigns` yes, but for `recompute/2` better not, to avoid coupling recomputation conditions accidentally.

**Comment by benwilson512** [comment]
What about an inverted model where instead of explicitly calling recompute you declare the other assigns a given assign depends on? EG:

```
socket
|> assign(:shipment, shipment)
|> assign(:current_user, user)
|> assign(:route, &compute_route/1, depends_on: [:shipment])
```

This lets you build a dependency graph as data instead of via functions full of conditionals. It also means you don't need to scatter explicit `recompute` calls everywhere.

**Comment by josevalim** [comment]
@benwilson512 we discussed this and our concern is that the dependency graph can actually be quite complex to be able to sum it up with a small DSL. For example, what if you just want to recompute in some transitions? For instance, in our generated code on phx.gen.live, we only want to recompute something if the live_view_action changes to :index but not to :new or :edit.

 So our focus is on the low-level primitives. With this, someone can build a "computed assigns" as you propose above.

**Comment by benwilson512** [comment]
> So our focus is on the low-level primitives. With this, someone can build a "computed assigns" as you propose above.

This makes sense.  I'm not really following the live_view_action stuff, reusing the the same socket on multiple pages makes my head hurt, but I think I just need to find the docs / general discussion on that feature.

**Comment by josevalim** [comment]
Closing this. We may not need it for now and if we need it, we can always revive this discussion.
