### ISSUE TITLE
deep nesting of dynamically rendered child

### ISSUE THREAD

**Issue by sfusato** [phoenixframework/phoenix_live_view#772]
### Environment
* Elixir version (elixir -v): 1.10.2
* Phoenix version (mix deps): 1.4.16
* Phoenix LiveView version (mix deps): Master
* NodeJS version (node -v): 13.12.0
* NPM version (npm -v): 6.14.4
* Operating system: Manjaro Linux
* Browsers you attempted to reproduce this bug on (the more the merrier):  Firefox, Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior
Not rendering a 3-level deep dynamically rendered child. Something like:
```elixir
# root
live_render(@socket, Child, id: "child")

# child
if @condition do
  live_render(@socket, GrandChild, id: "grandchild")
end
``` 

[DEMO](https://github.com/sfusato/phoenix_live_view_example) (`/` route; [weather_live.ex](https://github.com/sfusato/phoenix_live_view_example/blob/master/lib/demo_web/live/weather_live.ex))
### Expected behavior
Be able to render a dynamically rendered child 3 levels deep.

**Comment by chrismccord** [comment]
Thanks for the report! This was a client issue only, so your test case appears to only show that we do not re-render an already added child unless its ID changes, so I don't believe it is a valid test case. Thanks for the report and help tracking this down. The example repo was super helpful ❤️
