### ISSUE TITLE
Cannot read property `getAttribute` of null from phoenix_live_view.js

### ISSUE THREAD

**Issue by zkayser** [phoenixframework/phoenix_live_view#776]
### Environment

* Elixir version (elixir -v): 1.10.1
* Phoenix version (mix deps): 1.4.16
* Phoenix LiveView version (mix deps): 0.11.0
* NodeJS version (node -v): v12.6.0
* NPM version (npm -v): 6.9.0
* Operating system: macOS Catalina
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

I'm getting an error on `DOM.isPhxUpdate` from the `onBeforeNodeDiscarded` callback. The callback runs this line:
```javascript
if(DOM.isPhxUpdate(el.parentNode, phxUpdate, ["append", "prepend"])){ return false }
```
Which in turn does this:
```javascript
  isPhxUpdate(el, phxUpdate, updateTypes){
    return el.getAttribute && updateTypes.indexOf(el.getAttribute(phxUpdate)) >= 0
  },
```

The issue I'm running into is that `el.parentNode` is null, so `el.getAttribute` throws an Error when `isPhxUpdate` is run.

I've further found that this happens only when a node being removed has an identical dom ID to another node. I made a minimal example project that reproduces this issue [here](https://github.com/zkayser/live_view_issue_test_case)

My first thought was to add a check to ensure that `el` exists before calling `el.getAttribute`, but I'm not 100% certain if that could cause some unintended consequences, and I'm also not certain that is even the right place to handle the error.

### Expected behavior

Eliminate the error that gets thrown.

**Comment by chrismccord** [comment]
> I've further found that this happens only when a node being removed has an identical dom ID to another node. I made a minimal example project that reproduces this issue

It was my assumption that any DOM node will always have a parentNode (other than the HTML root), so this should not fail. If this can only be caused by a duplicate ID, then that is an invalid document and I don't know there is anything we should change in that case?

**Comment by chrismccord** [comment]
Note that we also detect and warn on duplicate ids if you have debug enabled on the client (`liveSocket.enableDebug()`), so first efforts to diagnose a client issue would produce this warning. I understand it would be easy for us to add a check for null parent, but I am hesitant because duplicate DOM ids is necessarily going to lead to undefined behavior.

**Comment by zkayser** [comment]
> Note that we also detect and warn on duplicate ids if you have debug enabled on the client (`liveSocket.enableDebug()`), so first efforts to diagnose a client issue would produce this warning. I understand it would be easy for us to add a check for null parent, but I am hesitant because duplicate DOM ids is necessarily going to lead to undefined behavior.

Thanks for pointing out `liveSocket.enableDebug()` -- it didn't occur to me to look for that. 

That all makes sense, and I completely understand the reluctance to add a null check just for this. It looks like the right answer is to fix this on our end by getting rid of the duplicate ids, so I'm going to go ahead and close.

Thanks
