### ISSUE TITLE
UI error state show up during redirect in Firefox

### ISSUE THREAD

**Issue by bruteforcecat** [phoenixframework/phoenix_live_view#779]
### Environment

* Elixir version (elixir -v): 1.9.1
* Phoenix version (mix deps): 1.4.16
* Phoenix LiveView version (mix deps): 0.11.1
* NodeJS version (node -v): 11.13.0
* NPM version (npm -v): 6.13.6
* Operating system: macOS Catalina
* Browsers you attempted to reproduce this bug on (the more the merrier):  Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior
When liveview is present as part of the page and a user click a normal `<a>` tag, Error UI state will appear during redirect. This problem only show up in Firefox and it should be introduced by this [commit](https://github.com/phoenixframework/phoenix_live_view/commit/0c8369e892e2d2baf93cd0eb6abd38b9b708e7da#diff-d4d7424e3b54ba50ca379d2944d59546).

After digging into this, it looks like the reason is because websocket close event is emitted earlier than unload event in Firefox and thus a error state show up during redirect. And this problem doens't exist if the redirect is triggered by `live_redirect` as this trigger pushing an event to client and the channel is set to leave gracefully before actually trigger redirect in browser.

### Expected behavior
No Error UI state should appear during redirect.

**Comment by josevalim** [comment]
Hi @bruteforcecat! As per the comment on #780, let us know if the issue still exists. If so, let us know so we reopen or this or the PR. Thank you! :heart:

**Comment by petejodo** [comment]
I'm seeing this while testing out phoenix `master` as of today. Generated a project in `installer/` and also included `mix phx.gen.auth --live Accounts User users` Took a screencast but gnome doesn't really do a great job recording seems, it's super laggy (apologies). I've confirmed it's firefox calling close callbacks on page changes and doesn't show up on chrome.

[Screencast from 10-05-2022 01:23:48 AM.webm](https://user-images.githubusercontent.com/1938892/193987489-46d9c4e6-a34c-412b-b45f-f52cf7294082.webm)
