### ISSUE TITLE
@myself does not work correctly with multiple live views

### ISSUE THREAD

**Issue by Harper04** [phoenixframework/phoenix_live_view#781]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 22 [erts-10.5.6] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [hipe]

Elixir 1.10.0 (compiled with Erlang/OTP 22)
```
* Phoenix version (mix deps):
```
* phoenix 1.4.16 (Hex package) (mix)
  locked at 1.4.16 (phoenix) 856cc1a0
  ok
```
* Phoenix LiveView version (mix deps):
```
* phoenix_live_view 0.11.1 (Hex package) (mix)
  locked at 0.11.1 (phoenix_live_view) 2408e31f
  ok
```
* NodeJS version (node -v):
```
node -v
v10.17.0
```
* NPM version (npm -v):
`6.13.2`
* Operating system:
`OSX Catalina 10.15.4`
* Browsers you attempted to reproduce this bug on (the more the merrier): 
`Chrome`
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:
`Yes`

### Actual behavior

Hi,
i LOVE the new `@myself` feature and had an amazing experience using it in a project with only live routes.
I tried using it in another project where i do have the following layout:
```
- view rendered by controller
 - live_view_a
    - live_component_a1
    - live_component_a2
 - live_view_b
    - live_component_b1
    - live_component_b2
```

Everything is using @myself. The problem is that events from `live_component_b1` are targeting `live_component_a1` and `live_component_b2` targets `live_component_a2`.
I tried to use ids at `live_render` for the live_views but no luck.

### Expected behavior
`@myself`-feature should be smart enough to handle multiple root live_views

Thanks a lot !

**Comment by chrismccord** [comment]
Can you provide a minimal example application that recreates your issue? It won't be possible for us to easily track down what's going on without it. Thanks!

**Comment by Harper04** [comment]
Sure thing!
minimal phoenix + live_view with latest packages / installation steps. The last commit adds the relevant code.
https://github.com/Harper04/myself_repro

![image](https://user-images.githubusercontent.com/31411/78935179-84406e00-7aac-11ea-9a58-f82e8a07d4bc.png)
If i click on the second button the first counter will be incremented.
