### ISSUE TITLE
phx-update="replace" should always patch the client

### ISSUE THREAD

**Issue by ltd** [phoenixframework/phoenix_live_view#782]
phx-update ignore/replace are great for one-time content, but if you have have the need to occasionally patch some "mostly static content" it's not optimal.

### Actual behavior

n |Server Sends | Client DOM| Result
---| ------------ | -------------|----------
1|phx-update="ignore" | empty| content patched, set phx-update="ignore"
2|phx-update="ignore" | phix-update="ignore"| content ignored, set phx-update="ignore"
3|phx-update="replace"|phx-update="ignore"| content ignored, set phx-update="replace
4|phx-update="replace"|phx-update="replace"| content patched, set phx-update="replace
5|phx-update="ignore" | phx-update="replace"| content patched, set phx-update="ignore"

state 3 requires two iterations to patch content
state 5 requires sending patches you really don't want

### Expected behavior

n |Server Sends | Result
---| ------------ |----------
1|phx-update="ignore" | content ignored
2|phx-update="replace" | content patched

# small test

defmodule DsfeWeb.Test do
  use Phoenix.LiveView

  def render(assigns) do
    states = {"ignore", "replace", "replace"}
    index = rem(assigns.counter, 3)
    state = elem(states, index)
    IO.inspect("rendering #{index} with state #{state}")

    ~L"""
      <div phx-click="click"> click me </div>

      <div id="counter" phx-update="<%= state %>" >
        <div> State is: <%= state %> </div>
        <div> Index is: <%= index %> </div>
      </div>
    """
  end

  def handle_event("click", _, socket) do
    IO.inspect(socket.assigns)
    {:noreply, assign(socket, counter: socket.assigns.counter + 1)}
  end

  def mount(_, _, socket) do
    {:ok, assign(socket, counter: 0)}
  end
end

**Comment by josevalim** [comment]
You must use assigns. Don't compute variables on render. If you use assigns, then you don't have to worry about ignore or replace, LV will do the correct thing and only send the data if it changed.

**Comment by ltd** [comment]
yes, example program had computes in the render(), but that's not my usecase.
say I have a large list I get from the database, put it in a temporary assign, and render it inside a phx-update="ignore". container.   When I want to update that list later on, I get new data, change the container to phx-update="replace".  This will not patch the client.

**Comment by josevalim** [comment]
Yes, once you set it to ignore, it will always ignore. What you can do, however, is to change the ID. If you use new IDs, then it works.

**Comment by josevalim** [comment]
At the same time, it feels you are reimplementing change tracking. If you make it a temporary assign, then the section where you use such assigns should not be re-rendered in the first place unless you re-use. You don't have to track it yourself.

**Comment by ltd** [comment]
I will retest, previous version without phx-update="ignore", my content was wiped when the temporary assign reverted to initial state.
