### ISSUE TITLE
LiveView modules do not support all :handle_info return values 

### ISSUE THREAD

**Issue by mtrudel** [phoenixframework/phoenix_live_view#784]
### Environment

* Elixir version (elixir -v): 
```
Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
Elixir 1.10.2 (compiled with Erlang/OTP 21)
```

* Phoenix version (mix deps): `locked at 1.4.16 (phoenix) 856cc1a0`
* Phoenix LiveView version (mix deps): `locked at 0.11.1 (phoenix_live_view) 2408e31f`
* NodeJS version (node -v): `v13.9.0`
* NPM version (npm -v): `6.13.7`
* Operating system: `macOS 10.14.6`
* Browsers you attempted to reproduce this bug on (the more the merrier): `Safari 13.0.4`
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

LiveView modules with a `handle_info` function returning a value other than `{:noreply, %Socket{}}` raise an error. For example, returning the tuple `{:noreply, socket, 10000}` results in the error:
```
[error] GenServer #PID<0.1140.0> terminating
** (ArgumentError) invalid noreply from XYZWeb.XYZ.XYZ.handle_info/2 callback.

Expected one of:

    {:noreply, %Socket{}}

Got: {:noreply, #Phoenix.LiveView.Socket<...>, 10000}
```

### Expected behavior

LiveView modules should be able to return a more complete set of return values from `handle_info` functions, specifically being able to return `{:noreply, %Socket{}, timeout}` tuples to be able to 'reset' UI state after an interval.

**Comment by mtrudel** [comment]
Looking at https://github.com/phoenixframework/phoenix_live_view/blob/master/lib/phoenix_live_view/channel.ex, it would seem that this should be a fairly simple bit of plumbing in `handle_result` and `handle_changed`. I'm quite happy to work up a PR for this if it's desired.

**Comment by josevalim** [comment]
Can you tell what is your goal with timeout? Timeouts seldomly work with channels, live views, etc because there are often pings and internal messages happening, which makes it so the timeout never triggers. GenStage has a similar issue. The root cause is that GenServer timeout does not really compose. Using Process.send_after with your own timeout handling is usually the best option.

**Comment by mtrudel** [comment]
Ah, that's a *very* good reason not to. I'd naively expected to be able to lean on the bare semantics of timeout being cancelled only by 'my' messages and neglected to consider that I'm actually sharing the mailbox with a bunch of LiveView / channel internal stuff. Your explanation makes perfect sense. 

Thanks for your speedy reply @josevalim!
