### ISSUE TITLE
Possible regression bug when calling `render_*` passing a path

### ISSUE THREAD

**Issue by leandrocp** [phoenixframework/phoenix_live_view#795]
I'm trying latest v0.12 and I got the following error when running a test that was working on v0.11

```
14:53:41.278 [error] GenServer #PID<0.235.0> terminating
** (FunctionClauseError) no function clause matching in MyAppWeb.MyComponent.handle_event/3
```

The test is a regular `render_submit([view, "#component-id"], action, args)`, and the issue is that the event is sent to the parent instead of being sent to the child component.

I've created this commit to show how to reproduce it: https://github.com/leandrocp/phoenix_live_view/commit/8fe6e6ae7a5bd8870493b956df61f18088feb7ad

Note in that commit the test `test "support calling render with a path and target on component element wrapper"` is passing green and the other test `test "support calling render with a path"` is causing the mentioned error. The only difference between them is on the template of the component, one has a `phx-target` on the outer div of the component template (`<div id="<%= @id %>" phx-target="#<%= @id %>">`) and the other one doesn't have it.

**Comment by josevalim** [comment]
@leandrocp yes, the path API now actually checks phx-target, while it didn't before. So before it would trigger the nearby component and now it requires phx-target and requires that you point to something with phx-target on it. Maybe we should have kept the path API intact, since it is deprecated, but this ship has sailed and my recommendation is to move to the much nicer elemtn based API. :)

**Comment by leandrocp** [comment]
We'll be moving to the element based API for sure and I understand it's the way to go (and actually I like it), but would be nice to provide some instructions on the CHANGELOG.md or display a warning on the tests. Something like:

```markdown
### Backwards incompatible changes
  - Stateful Component templates now requires a `phx-target="<%= @id %>"` on the wrapper div in order to support passing a path to the `render_*` test functions, eg:
    
    <div phx-target="<%= @id %>">
      ...
    </div>

    html = render_submit([view, "#component-id"], event, value)
    
  Note this API is deprecated and you should migrate to the new element based API.
```

Wdyt?

**Comment by josevalim** [comment]
It doesn't needd to be on the wrapper, it has to be on the #componend-id, no?

**Comment by leandrocp** [comment]
I'm not sure if I follow your question, but that's what I found:

Works:
```elixir
  def render(assigns) do
    ~L"""
    <div id="<%= @id %>" phx-target="#<%= @id %>">
      <p>name: <%= @name %></p>
      <form action="#" method="POST" phx-submit="rename" phx-target="<%= @myself %>">
        <input type="text" name="name">
      </form>
    </div>
    """
  end
```

Doesn't work:
```elixir
  def render(assigns) do
    ~L"""
    <div id="<%= @id %>">
      <p>name: <%= @name %></p>
      <form action="#" method="POST" phx-submit="rename" phx-target="<%= @myself %>">
        <input type="text" name="name">
      </form>
    </div>
    """
  end
```

See the `form` has a `phx-target` but it was not respected when calling `html = render_submit([view, "#rename-jose"], "rename", %{"name" => "jose-valim"})`

**Comment by josevalim** [comment]
Correct! I meant to say that your example in the changelog should do this:

```elixir
    <div id="<%= @id %>" phx-target="<%= @id %>">
      ...
    </div>
```

A PR is welcome!
