### ISSUE TITLE
Improve errors from LiveViewTest.live/2 & /3 ?

### ISSUE THREAD

**Issue by NikitaAvvakumov** [phoenixframework/phoenix_live_view#798]
LiveViewTest.__live__/2 checks the state and status of the conn but for anything other than `{:sent, 200}` or `{:sent, 302}` raises an ArgumentError whose message assumes that the state is unset. This can be confusing when the request has in fact been sent but returned e.g. a 404.

Would it be clearer to raise a different ArgumentError for a conn that's `{:sent, <anything other than 200 or 302>}`? Perhaps with a message like "request to #{conn.request_path} received an unexpected #{status} response"

**Comment by josevalim** [comment]
Yes, please send a PR!
