### ISSUE TITLE
html.leex + HTML comments

### ISSUE THREAD

**Issue by jamilabreu** [phoenixframework/phoenix_live_view#802]
1) Fresh install from master
2) Trying to use HTML comments (i.e. `<!-- HTML COMMENT HERE -->`) in `page_live.html.leex` renders the trailing comment tag `-->` on the page.

**Comment by chrismccord** [comment]
Can you put together an example repo that reproduces this, or at least the LiveView + leex template? I cannot recreate this on my side. Thanks!

**Comment by josevalim** [comment]
When opening up issues, please fill in the issues template, it helps us **a lot**.

**Comment by jamilabreu** [comment]
Played around with it and here's the culprit:

It only happens when commenting out the default code in live.html.leex, so:

live.html.eex
```
<!--
<main role="main" class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>
-->
<%= @inner_content %>
```

page_live.html.leex
```
<!--
HTML COMMENT
-->
```

Note:

Changing live.html.leex to just a regular HTML comment (no elixir code inside), works fine - and I'm commenting out elixir code in root.html.leex with no issue:
```
<!--
HTML COMMENT
-->
```

@josevalim Sorry! 🙈 I usually do, this one seemed straightforward at first. Will do

**Comment by jamilabreu** [comment]
The <%= @inner_content %> in the comment is causing it - not sure if this is by design. Definitely an edge case.

**Comment by josevalim** [comment]
It is never straight-forward. :)

So you cannot use HTML comments for this because the HTML comments do not know about EEx. So what would happen is that `@inner_content` would be injected twice and if `@inner_content` also has HTML comments, then it will close the upper HTML comment.

Either remove the content or also comment out the EEx tags with `<%# ... %>`.
