### ISSUE TITLE
Documentation issue with LiveComponent ID

### ISSUE THREAD

**Issue by shankardevy** [phoenixframework/phoenix_live_view#803]
Over here: https://github.com/phoenixframework/phoenix_live_view/blob/master/lib/phoenix_live_component.ex#L100-L101

the doc says

>  For example, if there is a `UserComponent` with `:id` of `13`, it
>   will have the DOM ID of `user-13`. Using a query selector, we can
>   send an event to it with:

but this is not true. It should be 

>  For example, if there is a `UserComponent` with 
>  the DOM ID of `user-13`, using a query selector, we can
>   send an event to it with:

Component `:id` of `13` has no implications on the DOM ID `user-13` and hence I suggest to remove it and also rephrase `will have the DOM ID` part as it gives a wrong message that LiveView sets this ID.

PS: I have a couple of other minor doc suggestions like this. Should I create issues like this here or do you prefer these over elixirforum or elsewhere? Let me know so that I don't unnecessarily flood the issue queue.

**Comment by josevalim** [comment]
Yes, good catch. Please send pull requests! Feel free to group the PRs per file or similar. :) I will close while we wait for the PR!
