### ISSUE TITLE
Opts syntax in form_for tripped me up

### ISSUE THREAD

**Issue by dbi1** [phoenixframework/phoenix_live_view#807]
Hello,

this is not really a bug, but something that took me a while to debug. Not sure where to post this other than here...

I have been writing my liveview forms as direct html so far, this feels natural and comfortable and is becoming part of muscle memory. Easy to understand and write.

Now I just tried the form_for approach instead, and got tripped up by the different syntax for the opts, which took me a while to debug (I overlooked it in the docs). Probably not a big deal for a more experienced developer, but it increases the cognitive load for me as I need to remember two different syntaxes now.

Opts in regular html:
`phx-change="validate"`

Opts in form_for:
phx_change: :validate

Issue 1: Hyphen vs underscore (phx-change vs phx_change)
Issue 2: css notation vs atom notation (="validate" vs :validate)

Any chance to add a way to pass the opts in form_for in syntax that is familiar to the direct html approach?

Thank you!

**Comment by josevalim** [comment]
Unfortunately there isn't much we can do. HTML and Elixir are different languages with different syntaxes and different conventions (underscore vs dash). `:` for key-values instead of `=` etc. Trying to make it look more like HTML would ultimately result in invalid Elixir. If you want to use `form_for`, then you need to familiarize with Elixir conventions for emitting HTML.

**Comment by wojtekmach** [comment]
Just to add on top of previous comment,

```elixir
iex> form_tag("/", phx-change: "validate")
** (SyntaxError) iex:17: syntax error before: change
```

however, currently both attribute names and values can be strings so you can do this:

```elixir
iex> form_tag("/", [{"phx-change", "validate"}]) |> safe_to_string()
"<form action=\"/\" method=\"post\" phx-change=\"validate\"><input name=\"_csrf_token\" type=\"hidden\" value=\"ZhAlDRMCEhxYPQwCQDZDJSIHGj8QEAAA6zqyqrhI9INHsurkJ6LoTA==\">"
```

I couldn't quickly find if passing strings as attribute keys is explicitly allowed or it just happens to work.

You can also do this (which generates atom key!)

```elixir
iex> form_tag("/", "phx-change": "validate") |> safe_to_string()
```

but in any case, as José mentioned I'd definitely recommend to either stick to Phoenix conventions when using the provided functions or generate the whole markup yourself.

**Comment by dbi1** [comment]
Got it, thanks to both of you, I really appreciate your time and thoughts on this.

I think I'll simply stick to the conventions of each language, and do a bit of muscle-memory training in the process.
