### ISSUE TITLE
Memory leak when using `put_root_layout`

### ISSUE THREAD

**Issue by syfgkjasdkn** [phoenixframework/phoenix_live_view#810]
### Environment

* Elixir version (elixir -v): 1.10.2
* Phoenix version (mix deps): 1.4.16
* Phoenix LiveView version (mix deps): 0.12.1
* NodeJS version (node -v): v13.13.0
* NPM version (npm -v): 6.14.4
* Operating system: macOS
* Browsers you attempted to reproduce this bug on (the more the merrier): chrome, safari, firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

The app never sends a response when [`put_root_layout` is in the pipeline](https://github.com/syfgkjasdkn/learning-live-view/blob/master/lib/citymonitor_web/router.ex#L10), both for static (`/login`) and live (`/dashboards/:id` and `/playbook`) routes. Observer shows growing memory in process started by `:cowboy_stream_h.request_process/3` with current function being `String.do_replace/4`.

If [router.ex#L10](https://github.com/syfgkjasdkn/learning-live-view/blob/master/lib/citymonitor_web/router.ex#L10) is commented out, everything works as expected.

Related files:

- [root.html.eex](https://github.com/syfgkjasdkn/learning-live-view/blob/master/lib/citymonitor_web/templates/layout/root.html.eex)

### Expected behavior

No memory leak.

**Comment by syfgkjasdkn** [comment]
Judging by the following trace

```
# 09:33:00 #PID<0.745.0> :cowboy_stream_h.request_process/3
# String.do_replace("method-param", [], "-", 0)

# 09:33:00 #PID<0.745.0> :cowboy_stream_h.request_process/3
# String.do_replace("charset", [], "-", 0)

# 09:33:00 #PID<0.745.0> :cowboy_stream_h.request_process/3
# String.do_replace("name", [], "-", 0)

# 09:33:00 #PID<0.745.0> :cowboy_stream_h.request_process/3
# String.do_replace("content", [], "-", 0)

# 09:33:00 #PID<0.745.0> :cowboy_stream_h.request_process/3
# String.do_replace("csrf-param", [], "-", 0)

# 09:33:00 #PID<0.745.0> :cowboy_stream_h.request_process/3
# String.do_replace("method-param", [], "-", 0)

# 09:33:00 #PID<0.745.0> :cowboy_stream_h.request_process/3
# String.do_replace("charset", [], "-", 0)

# 09:33:00 #PID<0.745.0> :cowboy_stream_h.request_process/3
# String.do_replace("name", [], "-", 0)
```

there is an infinite loop in `csrf_meta_tag()` which is called in the root layout.

**Comment by josevalim** [comment]
You need to use `@inner_content` insteadd of render here: https://github.com/syfgkjasdkn/learning-live-view/blob/master/lib/citymonitor_web/templates/layout/root.html.eex#L14

**Comment by syfgkjasdkn** [comment]
🤦‍♂️

Thank you!
