### ISSUE TITLE
"code_reloader: false" terminates GenServer

### ISSUE THREAD

**Issue by dbi1** [phoenixframework/phoenix_live_view#813]
Hello,

if I set `code_reloader: false` in dev.exs in a newly-generated Phoenix v 1.5.1 project (generated including LiveView), and then open http://localhost:4000/ I get the following error:

[error] GenServer #PID<0.620.0> terminating
** (RuntimeError) action disabled when not in development
    (my_app 0.1.0) lib/my_app_web/live/page_live.ex:30: MyAppWeb.PageLive.search/1
...etc...

The exact generation command I used is as follows:

`mix phx.new my_app --live`

Thanks for all the hard work on Phoenix 1.5, very excited about this new version :)

**Comment by chrismccord** [comment]
This is actually intentional if you check your code inside `page_live.ex`. We don't allow running the search on the homepage if you don't have the debug code reloader enabled, to prevent someone deploying this welcome to phoenix feature to prod. Thanks!

**Comment by dbi1** [comment]
Got it, thanks!
