### ISSUE TITLE
Add optional jitter parameter to the latency simulator

### ISSUE THREAD

**Issue by nickjj** [phoenixframework/phoenix_live_view#814]
Currently we can do `liveSocket.enableLatencySim(500)` to add a static 500ms of delay to every live view action and this is a great start for testing a delayed connection.

But most connections don't have a static amount of latency on every request. Sometime there might be 50ms of delay and other times there might be 2 seconds of delay.

So I'm proposing an optional second argument that defaults to 0 which controls the jitter rate. This will give randomness to the delay by X amount in either direction (more delay or less delay).

For example doing `liveSocket.enableLatencySim(500, 100)` would produce a final latency amount in between 400 and 600ms.

With it defaulting to zero, there's no backwards compatibility issues to think about.

**Comment by chrismccord** [comment]
This is a reasonable proposal, but we aren't accepting feature requests on the issue tracker. Best place to start the convo is slack/forums. Thanks!

**Comment by nickjj** [comment]
Oh. I saw https://github.com/phoenixframework/phoenix_live_view/issues/676 and other open issues that looked like feature requests / discussions.

**Comment by chrismccord** [comment]
phoenix-core team members have different privileges :)
