### ISSUE TITLE
Gettext and LiveView (uses default locale)

### ISSUE THREAD

**Issue by vermaxik** [phoenixframework/phoenix_live_view#815]
### Environment

* Elixir version (elixir -v): elixir 1.10.2
* Phoenix version (mix deps): 1.4.16
* Phoenix LiveView version (mix deps): 0.11.1
* NodeJS version (node -v): v12.15.0
* NPM version (npm -v): yarn 1.22.4
* Operating system: apline
* Browsers you attempted to reproduce this bug on (the more the merrier): all browsers
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Sure

### Actual behavior
I make multi-language support in our project, and moving all plain text to gettext. 
**The bug:**
Seems like locale from phoenix plug not passing to live_view socket, I can see rendering with correct locale and after it mounted it jumped to default locale. 

I'm changing locale though custom Plug using `locale` param:

```
  def call(conn, _opts) do
    case fetch_locale_from(conn) do
      nil -> 
        conn
      locale ->
        Gettext.put_locale(Web.Gettext, locale)
        put_resp_cookie(conn, "locale", locale, max_age: @max_age)
    end
  end
```

Phoenix config in Web project:
```
config :web, Web.Gettext,  locales: ~w(de en fr),  default_locale: "de"
```

For layout `live.html.leex` the locale works correctly, problem only in `render(assigns)` function.

### Expected behavior
The locale passes correct to `render(assigns)` from plug.

**Comment by chrismccord** [comment]
The locale is not pulled in from plug, but you can set the locale via put_session, and in your LiveView mount, use the session (from the 2nd arg) to restore it. If this is not clear, let me know. I'' open an issue to add an example to the docs. Thanks!

**Comment by vermaxik** [comment]
Thank you, @chrismccord !

**Comment by sanjibukai** [comment]
Hello,
I just noticed the same problem.
I'm using set_locale https://github.com/smeevil/set_locale and I was expecting that everything work out of the box.

> use the session (from the 2nd arg) to restore it.

@chrismccord Sorry if it's obvious but I don't get this part..
@vermaxik how did you fix that?

Thank you very much..

**Comment by josevalim** [comment]
See this guide: https://hexdocs.pm/phoenix_live_view/using-gettext.html#content

**Comment by sulphur** [comment]
The only downside is that when you have lots of live views ( in my case I use LV for navigation so all my routes are LV) you need to put it under each `mount`(which tends to repeat a lot) or write some custom module to make a _generic/global_ mount to set assigns and put gettext locale and after calls something like "after_mount" in each life to set up the specific LV assigns. I was searching for some more generic approach with Phenix but I found nothing for now.

**Comment by sulphur** [comment]
also, `assign_defaults` approach as explained in here : https://hexdocs.pm/phoenix_live_view/security-model.html#content  can be useful if you need to setup locale for each liveview.
