### ISSUE TITLE
live_view and live_reload seem to not play nicely together

### ISSUE THREAD

**Issue by chrisortman** [phoenixframework/phoenix_live_view#817]
### Environment

* Elixir version (elixir -v): 1.10.2
* Phoenix version (mix deps):
* temp 0.4.7 (Hex package) (mix)
  locked at 0.4.7 (temp) 2c78482c
  ok
* parse_trans 3.3.0 (Hex package) (rebar3)
  locked at 3.3.0 (parse_trans) 09765507
  ok
* mimerl 1.2.0 (Hex package) (rebar3)
  locked at 1.2.0 (mimerl) 67e2d3f5
  ok
* file_system 0.2.8 (Hex package) (mix)
  locked at 0.2.8 (file_system) f632bd28
  ok
* connection 1.0.4 (Hex package) (mix)
  locked at 1.0.4 (connection) a1cae722
  ok
* fs 6.1.1 (Hex package) (rebar3)
  locked at 6.1.1 (fs) 9d147b94
  ok
* metrics 1.0.1 (Hex package) (rebar3)
  locked at 1.0.1 (metrics) 25f094de
  ok
* unicode_util_compat 0.4.1 (Hex package) (rebar3)
  locked at 0.4.1 (unicode_util_compat) d869e4c6
  ok
* idna 6.0.0 (Hex package) (rebar3)
  locked at 6.0.0 (idna) 689c46cb
  ok
* gettext 0.17.4 (Hex package) (mix)
  locked at 0.17.4 (gettext) f13088e1
  ok
* jose 1.10.1 (Hex package) (mix)
  locked at 1.10.1 (jose) 16d8e460
  ok
* ranch 1.7.1 (Hex package) (rebar3)
  locked at 1.7.1 (ranch) 6b1fab51
  ok
* telemetry 0.4.1 (Hex package) (rebar3)
  locked at 0.4.1 (telemetry) ae271848
  ok
* decimal 1.8.1 (Hex package) (mix)
  locked at 1.8.1 (decimal) a4ef3f5f
  ok
* number 1.0.1 (Hex package) (mix)
  locked at 1.0.1 (number) a1017dc8
  ok
* jason 1.1.2 (Hex package) (mix)
  locked at 1.1.2 (jason) b03dedea
  ok
* libcluster 3.2.1 (Hex package) (mix)
  locked at 3.2.1 (libcluster) b2cd5b44
  ok
* comeonin 5.3.1 (Hex package) (mix)
  locked at 5.3.1 (comeonin) 7fe612b7
  ok
* ssl_verify_fun 1.1.5 (Hex package) (mix)
  locked at 1.1.5 (ssl_verify_fun) 6eaf7ad1
  ok
* gen_smtp 0.15.0 (Hex package) (rebar3)
  locked at 0.15.0 (gen_smtp) 9f51960c
  ok
* combine 0.10.0 (Hex package) (mix)
  locked at 0.10.0 (combine) eff8224e
  ok
* elixir_make 0.6.0 (Hex package) (mix)
  locked at 0.6.0 (elixir_make) 38349f3e
  ok
* bcrypt_elixir 2.2.0 (Hex package) (mix)
  locked at 2.2.0 (bcrypt_elixir) 3df902b8
  ok
* certifi 2.5.1 (Hex package) (rebar3)
  locked at 2.5.1 (certifi) 867ce347
  ok
* hackney 1.15.2 (Hex package) (rebar3)
  locked at 1.15.2 (hackney) 07e33c79
  ok
* tzdata 1.0.3 (Hex package) (mix)
  locked at 1.0.3 (tzdata) 73470ad2
  ok
* timex 3.6.1 (Hex package) (mix)
  locked at 3.6.1 (timex) efdf56d0
  ok
* db_connection 2.2.2 (Hex package) (mix)
  locked at 2.2.2 (db_connection) 3bbca41b
  ok
* ecto 3.4.2 (Hex package) (mix)
  locked at 3.4.2 (ecto) 6890af71
  ok
* phoenix_pubsub 2.0.0 (Hex package) (mix)
  locked at 2.0.0 (phoenix_pubsub) a1ae7671
  ok
* cowlib 2.8.0 (Hex package) (rebar3)
  locked at 2.8.0 (cowlib) fd0ff178
  ok
* cowboy 2.7.0 (Hex package) (rebar3)
  locked at 2.7.0 (cowboy) 91ed1001
  ok
* mime 1.3.1 (Hex package) (mix)
  locked at 1.3.1 (mime) 30ce04ab
  ok
* proper_case 1.3.0 (Hex package) (mix)
  locked at 1.3.0 (proper_case) aea76589
  ok
* mix_test_watch 1.0.2 (Hex package) (mix)
  locked at 1.0.2 (mix_test_watch) 34900184
  ok
* postgrex 0.15.3 (Hex package) (mix)
  locked at 0.15.3 (postgrex) 5806baa8
  ok
* ecto_sql 3.4.2 (Hex package) (mix)
  locked at 3.4.2 (ecto_sql) 3d842665
  ok
* plug_crypto 1.1.2 (Hex package) (mix)
  locked at 1.1.2 (plug_crypto) bdd18757
  ok
* plug 1.10.0 (Hex package) (mix)
  locked at 1.10.0 (plug) 6508295c
  ok
* phoenix_html 2.14.1 (Hex package) (mix)
  locked at 2.14.1 (phoenix_html) 7dabafad
  ok
* plug_cowboy 2.2.1 (Hex package) (mix)
  locked at 2.2.1 (plug_cowboy) fcf58aa3
  ok
* phoenix 1.5.1 (Hex package) (mix)
  locked at 1.5.1 (phoenix) 95156589
  ok
* phoenix_live_reload 1.2.1 (Hex package) (mix)
  locked at 1.2.1 (phoenix_live_reload) 274a4b07
  ok
* phoenix_live_view 0.12.1 (Hex package) (mix)
  locked at 0.12.1 (phoenix_live_view) 42f591c7
  ok
* guardian 2.1.1 (Hex package) (mix)
  locked at 2.1.1 (guardian) 1f02b349
  ok
* bamboo 1.4.0 (Hex package) (mix)
  locked at 1.4.0 (bamboo) 7b9201c4
  ok
* bamboo_smtp 2.1.0 (Hex package) (mix)
  locked at 2.1.0 (bamboo_smtp) 4be58f3c
  ok
* phoenix_ecto 4.1.0 (Hex package) (mix)
  locked at 4.1.0 (phoenix_ecto) a044d075
  ok

* Phoenix LiveView version (mix deps):
* NodeJS version (node -v): v10.16.0

* NPM version (npm -v): 6.14.2

* Operating system: **macOS  Catalina 10.15.4**
* Browsers you attempted to reproduce this bug on (the more the merrier): **Brave, FirefoxDeveloperEdition**
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

If I call `liveSocket.connect()` from my app.js

```
let csrfToken = document.querySelector("meta[name='csrf-token']").getAttribute("content");
let liveSocket = new LiveSocket("/live", Socket, {
  params: {_csrf_token: csrfToken},
  hooks: Hooks
});
liveSocket.connect()
```

Then live_reload no longer happens when I change something in a .html.eex or .leex file.

If I comment out `liveSocket.connect()` then the reload will happen

### Expected behavior

to reload

**Comment by josevalim** [comment]
Can you provide a sample application that reproduces the issue? I have both running locally just fine, so something else may be at plat.

Also please let us know your OS and browser. Thanks!

**Comment by chrisortman** [comment]
This is the application https://github.com/ui-icts/aptamer-web/tree/phx-1.5-upgrade
Sorry, I just pushed what I had at the moment. If it's more helpful I can try to put together a more isolated reproduction.

**Comment by chrisortman** [comment]
OS: Catalina 10.15.4
Browser: Brave, FirefoxDeveloperEdition

**Comment by chrisortman** [comment]
I had tried generating a new phoenix 1.5 app to compare config options but I realize I did not use `--live` looking at it now I suspect I'll find something missing because I am not doing `put_root_layout`

**Comment by josevalim** [comment]
That could be it. Without the root layout, you may not have a “body” tag, which is where we inject the live reloader script.

**Comment by chrisortman** [comment]
In the process of trying to extract out a more useful reproduction (I was not able to though) I did track it down to what I had wrong that was causing this behavior.

I had code like this

```
<div class="content">
  <%= link @file.file_name, to: Routes.file_path(@socket, :show, @file.id) %>
  <div class="description">Sequences: <%= Number.Delimit.number_to_delimited(@file.sequence_count) %>
  <div class="description">Uploaded <%= Timex.from_now(@file.uploaded_on) %></div>
  <div class="extra">
    <%= render "jobs.html", jobs: @file.jobs, socket: @socket %>
  </div>
</div>

```

 that the `div` with _Sequences_ in it is not closed. Fixing that fixes live reload. 
I will keep trying to plug away at creating an actual repro but thought I would update in case it sparks any ideas about what the root cause might be.

**Comment by josevalim** [comment]
Good catch! If the markup is invalid, I can see LiveView wrapping a larger area of your DOM and erasing the script tag injected by LiveReload. 

For example, imagine you have this:

```html
<html>
  <body>
    <div id="live-view">
      <div>YOUR DIV</div>
    </div>
    <iframe id="live-reload">
  </body>
</html>
```

But if you forget to close "YOUR DIV", then you end-up with this:

```html
<html>
  <body>
    <div id="live-view">
      <div>YOUR DIV
      </div>
      <iframe id="live-reload">
    </div> <!-- automatically injected by the browser before </body> -->
  </body>
</html>
```

Since the iframe is now accidentally inside the LiveView, the LiveView will override it once it gets connected to the server.

There is nothing we can do here but having the issue here will certainly help others in the future, thanks for following through!
