### ISSUE TITLE
Clear form event desn't work when trigger button is inside form

### ISSUE THREAD

**Issue by rjurado01** [phoenixframework/phoenix_live_view#821]
### Environment

* Elixir version (elixir -v): 1.10.2
* Phoenix version (mix deps): 1.4.16
* Phoenix LiveView version (mix deps): 0.12.1
* NodeJS version (node -v): 12.16.0
* NPM version (npm -v): 6.14.2
* Operating system: Ubuntu 18.04
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome 81.0.4044.92
* Does the problem persist after removing "assets/node_modules" and trying again? Yes

### Actual behavior

I'm trying to clear form using Phoenix Live View using this [example](https://github.com/chrismccord/phoenix_live_view_example/blob/master/lib/demo_web/live/user_live/new.ex).

I have added this code:

```elixir
  ...

  def handle_event("clear", _, socket) do
    changeset = Accounts.change_user(%User{})
    {:noreply, assign(socket, changeset: changeset)}
  end
```

```html
...

  <div>
    <%= submit "Save", phx_disable_with: "Saving..." %>
    <button phx-click="clear">Clear</button>
  </div>
</form>
```

### Expected behavior

Form inputs should be clear.

### Note

If I put clear button outside form it works:

```html
  <div>
    <%= submit "Save", phx_disable_with: "Saving..." %>
  </div>
</form>

<button phx-click="clear">Clear</button>
```

It blow my mind.

**Comment by sfusato** [comment]
I think this is because the default type for a button is `submit`. Add `type="button"` and see if that fixes it.

> 
> Definition and Usage
> 
> The type property sets or returns the type of a button.
> 
> Tip: Always specify the type attribute for the button. The default type for Internet Explorer is "button", while in other browsers (and in the W3C specification) it is "submit".

https://www.w3schools.com/jsref/prop_pushbutton_type.asp

**Comment by rjurado01** [comment]
@sfusato Yes, it works!
