### ISSUE TITLE
Documentation: Section on "Testing shutdowns and stopping views" is outdated

### ISSUE THREAD

**Issue by aptinio** [phoenixframework/phoenix_live_view#825]
Section on **Testing shutdowns and stopping views** in [live_view_test.ex](/phoenixframework/phoenix_live_view/blob/master/lib/phoenix_live_view/test/live_view_test.ex) is outdated since 9303aaf.

**Comment by josevalim** [comment]
Thanks! The whole section no longer makes sense. We now link the processes, so a failure in the view causes the test process to crash. And you are not supposing to be shutting down a LiveView anyway, only via redirects/patches. Therefore I have removed it.

**Comment by aptinio** [comment]
I wasn't sure if the section needed to be removed or updated. Thanks for clarifying that!
