### ISSUE TITLE
nprogress can interrupt application of CSS styles in Firefox on initial page load

### ISSUE THREAD

**Issue by oskarkook** [phoenixframework/phoenix_live_view#828]
### Environment
* Elixir version (elixir -v): 1.10.3
* Phoenix version (mix deps): 1.5.1
* Phoenix LiveView version (mix deps): 0.12.1
* NodeJS version (node -v): 13.13.0
* NPM version (npm -v): 6.14.4
* Operating system: Ubuntu 19.10
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox 75.0, Chromium 81.0.4044.122
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior
After creating a site created with `mix phx.new test_site --live` and loading it with Firefox, sometimes you can see that CSS styles are not applied on initial paint. There's an almost immediate layout reflow; first paint without styles, second paint with styles applied. This seems to be more pronounced with a bigger CSS file.

![paint1](https://user-images.githubusercontent.com/9250552/80319668-6009be80-881a-11ea-8b0e-f4dd1ef6b1fc.gif)

### Expected behavior
![paint2](https://user-images.githubusercontent.com/9250552/80319686-7152cb00-881a-11ea-9705-b2bfdf3f034c.gif)

This can be achieved by moving the `NProgress` lines after `liveSocket.connect()`:
```js
// connect if there are any LiveViews on the page
liveSocket.connect()

// Show progress bar on live navigation and form submits
window.addEventListener("phx:page-loading-start", info => NProgress.start())
window.addEventListener("phx:page-loading-stop", info => NProgress.done())
```

Can not reproduce on Chromium.

**Comment by josevalim** [comment]
You can modify nprogress CSS if you want to or remove it altogether. It is expected its default style won’t work on all scenarios. However, I wouldn’t move it after, otherwise if connecting is slow, the user would get no feedback. In any case, thanks for the report!

**Comment by oskarkook** [comment]
I would argue against advising bad defaults to the users who will be using the `--live` flag. It took me a while to figure this issue out. Not only did I spend my time on an issue that is totally unexpected, it also leaves a bad impression of the library.

**Comment by josevalim** [comment]
We will keep on listening to reports but I am a 100% sure that whatever we pick as a default style for loading animations won’t work on all cases. There is no choice we can make that will provide guarantee, given the variety of ways CSS can be used.

**Comment by oskarkook** [comment]
`nprogress` rather heavy-handedly just forces browser layout reflows:
https://github.com/rstacruz/nprogress/blob/master/nprogress.js#L74
https://github.com/rstacruz/nprogress/blob/master/nprogress.js#L89

This is horrible behaviour when doing animations like this. When I replace these forced reflows with `window.requestAnimationFrame()` instead, the issue is fixed.

Please re-open this issue as this is totally fixable. It would be sad to see LiveView to suffer from problems like this.

**Comment by aptinio** [comment]
For whatever it's worth, I'm also able to reproduce this issue. I've confirmed that the provided solution fixes the problem. I'd be happy to create a PR in Phoenix that applies the fix.

**Comment by oskarkook** [comment]
Thanks @aptinio. The provided snippet is more of a work-around than a full fix.

It should either be fixed in `nprogress` or the library should be replaced with something better (if the author does not accept PRs). As mentioned, the library aggressively forces reflows which is something you specifically do not want to do when animating something.

Until then, this issue should be kept open as it does not provide a good user experience to LiveView users. I'd even argue that until it is fixed, this issue should be mentioned and referenced in the [installation docs](https://github.com/phoenixframework/phoenix_live_view/blob/master/guides/introduction/installation.md) to avoid other users from wasting time on this.

**Comment by josevalim** [comment]
@oskarkook can you please send a pull request to nprogress so we get the author's input on this? Thanks!

**Comment by josevalim** [comment]
Another option is to use a different project, such as topbar: https://github.com/buunguyen/topbar

**Comment by oskarkook** [comment]
I'd honestly rather suggest using something like topbar over nprogress. Topbar just updates the bar on every frame through `requestAnimationFrame` until the bar is hidden, whereas nprogress seems to have some sort of internal queue mechanism for frame updates, which I'd remove anyway (i.e. my PR would be similar to how topbar works). Recursively calling `requestAnimationFrame` keeps the animation in sync with browser paints and topbar does this correctly, no internal queue is necessary.

The only significant difference is that topbar uses canvas, but I don't think it matters in LiveView case. There are two small issues that I can see in topbar's code, but PRs for those would be way simpler than a PR for nprogress.

I tested topbar in my application and can confirm that it does not display the same issue.

If you find other libraries like this, I can take a look at them too.

**Comment by josevalim** [comment]
I also tried topbar locally and it worked fine. So I am inclined to go in this direction too.

**Comment by chrismccord** [comment]
The phoenix generators will use topbar going forward, which fixes this issue. Thanks!

**Comment by oskarkook** [comment]
Thanks @chrismccord! The guides in this repository still reference `nprogress`.

https://github.com/phoenixframework/phoenix_live_view/blob/master/guides/client/js-interop.md#loading-state-and-errors
https://github.com/phoenixframework/phoenix_live_view/blob/master/guides/introduction/installation.md#progress-animation

**Comment by josevalim** [comment]
Can you please send a PR that updates the guides? Thank you.

**Comment by cw789** [comment]
One more thing. UX wise it is best practice to not show a progress bar for things < 100 ms.

```
// progress bar on live navigation & form submits w/ delay of 100 ms
let progressTimeout
topbar.config({barColors: {0: "#29d"}, shadowColor: "rgba(0, 0, 0, .3)"})
window.addEventListener("phx:page-loading-start", () => { clearTimeout(progressTimeout); progressTimeout = setTimeout(topbar.show, 100) })
window.addEventListener("phx:page-loading-stop", () => { clearTimeout(progressTimeout); topbar.hide() })
```

Taken from here: [thepugautomatic.com](https://thepugautomatic.com/2020/05/delaying-the-nprogress-indicator-in-phoenix-liveview/)

What do you think about having this as default?
