### ISSUE TITLE
LiveView macro generated routes are prepended with an underscore

### ISSUE THREAD

**Issue by beckler** [phoenixframework/phoenix_live_view#832]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 22 [erts-10.6.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.9.4 (compiled with Erlang/OTP 22)
```
* Phoenix version (mix deps): `phoenix 1.5.0`
* Phoenix LiveView version (mix deps): `phoenix_live_view 0.12.1`
* NodeJS version (node -v): `v13.6.0`
* NPM version (npm -v): `6.13.4`
* Operating system: `macOS 10.13.6 (High Sierra)`
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

I upgraded an application from phx 1.4 to phx 1.5, and when I started integrating live views, I started to experience a weird behavior with the Routes helper.

When I have routes listed like this:
```
 scope "/signals", ScannerWeb.Live.Signals do
    pipe_through [:browser, :authenticated]

    live "/", Dashboard, :index
    live "/scans", Scans, :index
  end
```

I get generated routes that look like this:
```bash
> mix phx.routes
_signals_dashboard_path  GET     /signals                                       Phoenix.LiveView.Plug :index
    _signals_scans_path  GET     /signals/scans                                 Phoenix.LiveView.Plug :index
```

I have a non-live-view header with a link to the page, and I can only reference the path with something like: `Routes._signals_scans_path(@conn, :index)`

Note that ONLY see this behavior with live routes, regular paths, and the live dashboard paths look normal.

### Expected behavior

I didn't expect routes to get generated with a prepended underscore, but if this is expected behavior, I just didn't know. I looked over the changelog and the migration docs and I didn't see this particular change mentioned anywhere.

**Comment by josevalim** [comment]
FWIW, this is happening because LiveView expects it to be `IndexLive.Signals` and so on, instead of a single ".Live." nesting. But I will fix it to also generate proper paths in this case too.
