### ISSUE TITLE
LiveComponent disappears when it handles a click that updates it's state

### ISSUE THREAD

**Issue by axelson** [phoenixframework/phoenix_live_view#843]
### Environment

* Elixir version (elixir -v): Elixir 1.10.3 (compiled with Erlang/OTP 22)
* Phoenix version (mix deps): 1.5.1
* Phoenix LiveView version (mix deps): 0.12.1 (tried master also)
* NodeJS version (node -v): 12.3.1
* NPM version (npm -v): 6.9.0
* Operating system: Arch Linux (and Mac OS X)
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox, Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

A LiveComponent that has a sub-render function with it's own `~L` and phx-click disappears when the component handles a phx-click that updates it's socket state. (possibly related to svg elements)

Full reproduction steps are in the repo:
https://github.com/axelson/reproduce_live_view_dissapearing

Link to most relevant code: https://github.com/axelson/reproduce_live_view_dissapearing/commit/3d958a26ce1708b26acd5de5f0087718f7058d96

### Expected behavior

The "menu" component should continue to be displayed

Or if I'm making some sort of LiveView implementation error, a relevant warning should be displayed.

### "workarounds"

If I do either of these then the bug doesn't manifest:
* Don't assign to the socket in the LiveComponent `handle_event`
* Don't use a secondary `render` function

**Comment by chrismccord** [comment]
This was a bug on the morphdom side and has been fixed on master. It only applies to SVG elements. Thanks for the report and keep an eye out for a new morphdom release!

**Comment by axelson** [comment]
Thanks for looking into/fixing it! Will look forward to the next morphdom release.
