### ISSUE TITLE
Using plural form with phx.gen.live generates broken views

### ISSUE THREAD

**Issue by Nicd** [phoenixframework/phoenix_live_view#847]
### Environment

* Elixir version (elixir -v): 1.10.3
* Phoenix version (mix deps): 1.5.1
* Phoenix LiveView version (mix deps): 0.12.1
* NodeJS version (node -v): 12.16.2
* NPM version (npm -v): 6.14.4
* Operating system: macOS
* Browsers you attempted to reproduce this bug on (the more the merrier): Any
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

Generating a live view with the generator and using a schema name that is plural will result in a broken view. When you go to the list view, you will get a crash _protocol Enumerable not implemented for nil of type Atom_.

Example generation:

```
mix phx.gen.live Spotting Series series test:string
```

When you have set up the router, go to `/series` and you will get a crash. It comes from the leex template's `<%= for series <- @series do %>`. Inspecting the assign, you can see that the data `[]` is assigned to `:series` (in fact you can just assign it manually), but in the template, the data is `nil` for some reason. If you change the assign name to `:series2` for example, it starts to work.

I presume this is related to some conventions over singular/plural forms of words. Unfortunately "Series" is a singular and plural and results in broken code.

### Expected behavior

It works out of the box.

**Comment by josevalim** [comment]
Good catch. Fixed in Phoenix master!
