### ISSUE TITLE
Inserting non-live on live view breaks

### ISSUE THREAD

**Issue by Jauny** [phoenixframework/phoenix_live_view#85]
### Environment

* Elixir version (elixir -v): Elixir 1.6.5 (compiled with OTP 20)
* Phoenix version (mix deps): phoenix 1.4.0
* NodeJS version (node -v): v8.15.1
* NPM version (npm -v): 6.4.1
* Operating system: macOS + Heroku

### Expected behavior
I changed part of my template to use live view. I expect it to not change anything else on the template.

### Actual behavior
The live view part actually works, but it breaks a non-live part of my template.
I have a loop that goes over DB elements with randomised order and render html for each ([this line](https://github.com/jonandjess/joeschmoe.io/blob/master/lib/avatar_web/templates/page/index.html.eex#L160)). 

With the template as a live view, the elements load twice (you can see them reload twice on page refresh) and the UI breaks. It's a "flex" dive with expected 4 elements per row. After the live view "reload", there is always a few rows that end up having 3 elements only, and some divs seem to suffer from race conditions (it renders svg and some divs have svg parts from another div).

You can see the working behavior here: https://joeschmoe.io/ (the live-view diff was reverted). The loop mentioned is at the bottom of the page "all the schmoes".

The diff to insert live view is here: https://github.com/jonandjess/joeschmoe.io/pull/1/files.

### What I've tried
Right now the data from the db is pulled directly from the template (using the `all_originals()` view helper).  
I've tried to change that and load the data from the LiveView directly and pass it into the session object, but the same issue happens.

Not sure if I'm doing something wrong of this is an issue.

### Screenshot
Here you can see a row has only 3 elements instead of 4, and "Jana" has 2 divs layered on top of each others (the teal behind is another character).
![Screenshot 2019-03-18 at 09 02 29](https://user-images.githubusercontent.com/1719552/54515561-b5f40d80-495c-11e9-8625-a43d8513a24d.png)

Cheers!

**Comment by Jauny** [comment]
So I'm trying to understand what is happening, and I'm a little lost as I'm pretty new to Phoenix, but looking into logs, I can confirm that what seems to be (at least part of) the issue is that the template is actually getting rendered a 2nd time once the socket is connected:

```
[... all regular request logs ...]
[info] Sent 200 in 904µs
[info] CONNECT Phoenix.LiveView.Socket
  Transport: :websocket
  Connect Info: %{}
  Parameters: %{"vsn" => "2.0.0"}
[info] Replied Phoenix.LiveView.Socket :ok
# following db request is the one loading the avatars in the list, done for the 2nd time
[debug] QUERY OK source="originals" db=5.1ms queue=0.1ms
SELECT o0."id", o0."gender", o0."name", o0."svg", o0."inserted_at", o0."updated_at" FROM "originals" AS o0 []
[info] Replied phoenix:live_reload :ok
```

Also if I add some IO.puts in my template I can confirm it's getting puts a 2nd time after the `[info] Replied Phoenix.LiveView.Socket :ok` line (right with the db request log).

**Comment by chrismccord** [comment]
Please see the `Life-cycle` section of the docs. The original HTTP requests calls your live view mount, renders it, and sends the response. After the browser gets the HTML, it connects back to the server, the LV is mounted again, but this time a process is started for it and then it continues on statefully. So your random example, would be two different random result sets. Also please see the section on LiveEEx, where you must use an assign, so instead of `all_originals()` your template should use `@all_originals`, which would be an assign you set on mount or in a callback. It's not clear the exact behaviour you're describing about the UI breaking and flexbox, but one thing we do is wrap the LV's in a container div, so this may be affecting your css scoping and layout.

**Comment by Jauny** [comment]
Looked a bit more into it, thanks for the hint, I wasn't sure if it was expected to have a re-render at socket connection!

So to avoid a re-render for the randomised list, I've had to push the `all_originals` function out of the template, and out of the LiveView, into the Controller, and pass in the list into the `session` opts of `live_render`.

Is that the right thing to do you think?

Additional question, sorry! In your examples, I see `live_rendered` called directly from ~L_sigil templates - is it possible to call it from a normal .eex template, or only from ~L_sigil and .leex?

I think in my case it would make more sense to have my page rendered through a normal controller with a normal .eex template, and only have a `live` route for the one part I need to be a LiveView and render it inside my .eex template with `<%= live_render %>`. 

Sorry for all the questions, I'm new to this and trying to grasp everything so I can start helping :)

**Comment by chrismccord** [comment]
The session should only be used for the minimal data necessary to fetch/build your data on mount, so you don't want to place entire records in there. What I would do for this case is pass your own seed value to the session from the controller, then in mount/2 call `:random.seed(session.seed)`. That way, you are guaranteed to get the same order. For `.leex` templates, yes, you can render a regular Phoenix.View with a `.leex` file, such as here: https://github.com/chrismccord/phoenix_live_view_example/blob/master/lib/demo_web/live/user_live/index.ex#L12

> Sorry for all the questions, I'm new to this and trying to grasp everything so I can start helping :)

No worries! I'm active on slack and IRC if you have questions :)

**Comment by Jauny** [comment]
Oh that's awesome, thanks for the random seed trick!

I just tried and am able to use `live_render` inside my .leex view, which seems to make things a bit cleaner. I'll clean it up soon and try to write something!

Thanks again!
