### ISSUE TITLE
formsForRecovery duplicated across the source code

### ISSUE THREAD

**Issue by bopm** [phoenixframework/phoenix_live_view#850]
I am experimenting with refactoring lib code to Typescript and that given me next issue:
There are two declarations of `formsForRecovery` across the file: [one](https://github.com/phoenixframework/phoenix_live_view/blob/5b9fe24ff1b2e91a97681259df993badcd4cd461/assets/js/phoenix_live_view.js#L1538) and [two](https://github.com/phoenixframework/phoenix_live_view/blob/master/assets/js/phoenix_live_view.js#L2026).
Obviously only second one is effective.

**Comment by chrismccord** [comment]
❤️❤️❤️🐥🔥

**Comment by bopm** [comment]
@chrismccord while we are here, I like to ask you a question about things I am experimenting on around TypeScript. How do you feel about possible PR that will convert codebase to TypeScript? I am seeing a lot of issues while experimenting here and there, that would be resolved by transition and will never return again due to strong typing and better linting.
