### ISSUE TITLE
LiveView needs a way to go back in browser history

### ISSUE THREAD

**Issue by jonleighton** [phoenixframework/phoenix_live_view#857]
### Environment

* Phoenix version (mix deps): 1.5.1
* Phoenix LiveView version (mix deps): 0.1.12

### Actual behavior

I have created a demo project to demonstrate this problem: https://github.com/jonleighton/phoenix_live_view-bug-demo

It was generated like so:

1. `mix phx.new demo --live`
2. `mix phx.gen.live Posts Post posts name:string`
3. [Add link to `/posts` from `/`](https://github.com/jonleighton/phoenix_live_view-bug-demo/commit/b3577e643bb77645cc514c851f8630de950c513f)

Steps to reproduce:

1. (Setup) Go to http://localhost:4000/posts and add a couple of posts
2. New we're starting the repro. Go to http://localhost:4000/
3. Click 'Posts' to go to http://localhost:4000/posts
4. Click 'Edit' on the first post to go to http://localhost:4000/posts/1/edit
5. Click 'X' to close the modal, we're now at http://localhost:4000/posts
6. Click 'Edit' on the second post to go to http://localhost:4000/posts/2/edit
7. Click 'X' to close the modal, we're now at http://localhost:4000/posts
8. Click the browser back button, we're now at http://localhost:4000/posts/2/edit

### Expected behavior

After clicking the browser back button, I expect to be at http://localhost:4000/.

This doesn't happen, because closing the modal only pushes new states onto the history stack, it never removes them. So at the 7th step, our history stack looks like:

```
http://localhost:4000/
http://localhost:4000/posts
http://localhost:4000/posts/1/edit
http://localhost:4000/posts
http://localhost:4000/posts/2/edit
http://localhost:4000/posts
```

I would expect it to actually look like:

```
http://localhost:4000/
http://localhost:4000/posts
```

Arguably this expectation could vary from one application to another, but I am making the case that LiveView ought to have a way to pop from the history stack (and that that is the sensible default behaviour for closing a `live_modal`).

Using `replace: true` doesn't solve the problem. In that case the history stack would end up like this:

```
http://localhost:4000/
http://localhost:4000/posts
http://localhost:4000/posts
http://localhost:4000/posts
```

A proposed solution could be to add a couple of new functions, perhaps `live_back` and `push_back` (similar to `live_patch` and `push_patch`) which would have the appropriate JS wiring to invoke `history.back()` in the browser. They would still need a `to:` option for the fallback case when there is no previous page (i.e. the user has navigated directly to the modal), in which case they would behave like `live_patch`/`push_patch` and add a new entry to the history stack.

**Comment by josevalim** [comment]
Perhaps a better option is to replace `replace: true` by an option like `history: :push | :replace | :pop`.

And of course, the issue with `history.back()` is that closing the modal could send you back to a complete separate page once you click the `X`. So if someone uses "pop", we would need to first detect if the current LV page pushed anything to the history and, if not, do a regular `:push` - as you proposed.

**Comment by jonleighton** [comment]
I like your API proposal.

> So if someone uses "pop", we would need to first detect if the current LV page pushed anything to the history

This made me ponder whether there might ever be a valid use case where someone really wants to pop back to a _different_ LiveView. I can't think of anything obvious right now, though, so probably the best answer is to do as you propose and then see if any problems emerge.

**Comment by chrismccord** [comment]
patch + `replace: true` works in this case, but you need to include `replace: true` on the links that show the modal, ie in index.html.leex:

```diff
<span><%= live_patch "Edit", to: Routes.post_index_path(@socket, :edit, post) %></span>
<span><%= live_patch "Edit", to: Routes.post_index_path(@socket, :edit, post), replace: true %></span>
```

Then, assuming your modal component uses `replace: true`, you get the behavior you're looking for :) So the solution is to not push the history state in the first place for things you don't want to remain when you patch back. Thanks!

**Comment by jonleighton** [comment]
@chrismccord Thanks for the reply, but that doesn't feel like a good solution to me.

I expect closing the modal via the 'X', or hitting escape, or clicking outside the modal, to behave exactly the same as hitting the browser back button.

With your proposed solution, hitting the browser back button would go back from e.g. `/posts/1/edit` all the way to `/`, (skipping `/posts`). That feels like worse behaviour than the status quo.

We can kind of get what I want by using `replace: true` on the 'Edit' link, _and_ the modal 'X' button, _and_ the `push_patch` in `ModalComponent`. This ensures that's there's only ever one history entry: `/posts` gets replaced with `/posts/1/edit`, which then gets replaced with `/posts` if we close the modal via the UI. It works fine until you actually use the browser back button - then it jumps back to `/` even with the modal open.

So, to restate, my assumption/opinion is that closing a `live_modal` via the UI should behave exactly the same as hitting the browser back button. Otherwise, I don't know what is the point of having separate URLs for the modal in the first place. And I don't see a way to achieve that with LiveView's current functionality. (Obviously it's probably possible to workaround in JS but I'm saying it should work like this out of the box.)

**Comment by josevalim** [comment]
@chrismccord good point.

If you think about modals outside of LiveView, I generally expect modals to not add states to the history when they are opened nor when they are closed. So for example, if I open up a modal and press back, I expect to go to the previous page altogether and to not simply close the modal. So if you want to replicate this behaviour, it seems replace is indeed the way to go.

**Comment by jonleighton** [comment]
Ok, on further consideration I accept this rationale @josevalim. I think the behaviour feels ok with `replace: true`. Would a patch to make `mix phx.gen.live` use `replace: true` for the modals be welcome then?

**Comment by josevalim** [comment]
I honestly don't know. :) I am fine with the current behaviour but you are not and I don't know where users would generally sit between these two. :)

**Comment by Gigitsu** [comment]
Is this feature not implemented? I could really use it. In my scenario, users can access an edit form from multiple places. Once submitted, I need to return the user to where they come from.
