### ISSUE TITLE
Typespec for params is map, however with phx-keyup params is a binary

### ISSUE THREAD

**Issue by skovmand** [phoenixframework/phoenix_live_view#86]
### Environment

* Elixir version (elixir -v): 1.8.1
* Phoenix version (mix deps): 1.4.2
* NodeJS version (node -v): -
* NPM version (npm -v): -
* Operating system: -

When using a `phx-keyup` binding, as in:

```
<input type="text" phx-keyup="new_query" />
```

... the `handle_event/3` callback in a live view will receive its 2nd parameter, `params` as a binary. However, according to the typespec of the `handle_event/3` callback in `phoenix_live_view.ex` (line 357), `params` should be a map:

```
@callback handle_event(event :: binary, unsigned_params, Socket.t()) :: {:noreply, Socket.t()} | {:stop, Socket.t()}
```

```
@type unsigned_params :: map
```

I will make a PR to change the type of `unsigned_params` in a moment, which would fix it. Let me know if the fix should be done in another way.

**Comment by josevalim** [comment]
I would probably make it a map for the keycode case too because if in the future we want to send more information, the map will support it.

**Comment by skovmand** [comment]
Okay. I think that is a good idea. 

After investigating a bit, I found that adding another `decode/2` function to `channel.ex` could match on the events with type `keyup`, `keydown` and `keypress` and return the value as a map instead of a binary:

```
  defp decode("form", url_encoded) do
    Plug.Conn.Query.decode(url_encoded)
  end

  # suggested addition
  defp decode(type, value) when type in ["keyup", "keydown", "keypress"], do: %{"key" => value}

  defp decode(_, value), do: value
```

Source: `channel.ex:136`

What do you think of this?
Should the map have string or atom keys? Since the output of `decode/2` for type `"form"` had string keys, I followed that example.

**Comment by josevalim** [comment]
I guess in this case it is better to change the JS to already send a map
instead of changing the backend. Chris would know better though!
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by jeremyowensboggs** [comment]
Using the phx-value attribute also sends the value as a binary, and not a map.

**Comment by dmitriid** [comment]
There's also currently a subtle bug where JS sends back keycodes, not value, when value is empty:

Code:

```
<input type="text" phx-keyup="filter" />

...

def handle_event("filter", value, state) do
   IO.inspect(value)

   {:noreply, state}
end
```

|Keys pressed | value received in handle_event| 
|---|---|
| Cmd + A | "Meta"|
| Backspace | "Backspace"|
| a | "a" |
| b | "ab" |
| Cmd + A | "ab" |
| Backspace | "Backspace" |

From now on all key presses send their codes as value: "Alt", "Meta", "Shift" etc. until you enter a value that can be displayed.

Switching to something like `{keyCode: "a", value: "aba"}` will definitely help with this

**Comment by jmbejar** [comment]
> There's also currently a subtle bug where JS sends back keycodes, not value, when value is empty:
> 
> Code:
> 
> ```
> <input type="text" phx-keyup="filter" />
> 
> ...
> 
> def handle_event("filter", value, state) do
>    IO.inspect(value)
> 
>    {:noreply, state}
> end
> ```
> 
> Keys pressed	value received in handle_event
> Cmd + A	"Meta"
> Backspace	"Backspace"
> a	"a"
> b	"ab"
> c	"abc"
> Backspace	"ab"
> Cmd + A	"ab"
> Backspace	"Backspace"
> From now on all key presses send their codes as value: "Alt", "Meta", "Shift" etc. until you enter a value that can be displayed.
> 
> Switching to something like `{keyCode: "a", value: "aba"}` will definitely help with this

I recently run into this limitation, and I was actually thinking of the same solution.

@chrismccord Do you agree this is the way to go? Just wondering if it is worth to work on a PR implementing this change at this time.

**Comment by chrismccord** [comment]
We now send a map payload of all standard event object literal key/values. Thanks!
