### ISSUE TITLE
Form fields with autofocus don't work when loaded with live_{patch,redirect}

### ISSUE THREAD

**Issue by jonleighton** [phoenixframework/phoenix_live_view#860]
### Actual behavior

When a LiveView has a form input with the `autofocus` attribute:

``` html
<input type="text" name="test" autofocus>
```

Loading the page view `live_patch` or `live_redirect` doesn't autofocus the field.

Hitting the browser refresh to reload the LiveView from scratch _does_ autofocus the field.

### Expected behavior

The field should be autofocused even when using `live_patch` or `live_redirect`.

**Comment by josevalim** [comment]
Hi @jonleighton! This should be doable, code wise:

```js
const autofocusedElements = document.querySelectorAll('input[autofocus]');
if (autofocusedElements.length) {
  autofocusedElements[0].focus();
}
```

However, the issue is that we only want to do this if live_patch/live_redirected was triggered. So some client side tracking is required. Doing it on all server pushes would be an issue because we can end-up removing the focus from the current element.

**Comment by chrismccord** [comment]
`autofocus` has different behavior in different browsers when a DOM patch with `autofocus` appears, so we have decided to wait on detecting this feature and focusing for you on the LV side. You can implement an AutoFocus hook yourself to handle it in the meantime. Thanks!

**Comment by jonleighton** [comment]
Thanks. Yes, on further inspection I realise I'm seeing this problem in Firefox (my usual browser) but it works fine in Chrome.
