### ISSUE TITLE
render_hook/3 can't target stateful components

### ISSUE THREAD

**Issue by orthodoX** [phoenixframework/phoenix_live_view#861]
Hi, I'd like to report a missing behaviour of `LiveViewTest.render_hook/3`. The documentation states `render_hook(view_or_element, event, value \\ %{})` but I was not able to use it with an element that has a custom hook which is handled by a stateful component, not the parent live view. Here's an example:

_home_live_view.leex_

```eex
<%= live_component(@socket, AppWeb.Sidebar, id: :sidebar) %>
```

_sidebar_component.leex_

```html
<ul id="user-products-list"  phx-hook="sortProducts">
  <li data-product-id="1"></li>
  <li data-product-id="2"></li>
  <li data-product-id="3"></li>
</ul>
```

_app.js_

```js
let Hooks = {}
Hooks.sortProducts = {
  mounted() {
    this.pushEventTo('#user-products-list', 'reorder_products', products_order)
  }
}
```

The `products_order` param looks like this:

```ex
[
  %{"order" => 1, "product_id" => 3},
  %{"order" => 3, "product_id" => 2},
  %{"order" => 2, "product_id" => 1}
]
```

which is also important to notice, since the current implementation requires the value param to be a map.

_sidebar_component.ex_

```ex
@impl true
def handle_event("reorder_products", new_products_order, socket) do
  {:ok, products} = App.reorder_products(new_products_order)

  {:noreply, assign(socket, products: products)}
end
```

And while this works like a charm in the app, in the test I'm struggling to reproduce this scenario.
If `reorder_products` would be handled by the parent live view that it is possible to do it.
Looks like I have two problems right now. One is that this is not working:

_home_live_test.exs_

```ex
home_live
  |> render_hook("reorder_products", reorder_param)
```

since it's expecting from the parent live view to handle it. And the following doesn't work as well:

```ex
home_live
  |> element("#user-products-list")
  |> render_hook("reorder_products", reorder_param)
```
It raises `** (BadMapError) expected a map` since the `reorder_param` is a list of maps as explained above.

So either I found an edge case or I just didn't figure out a proper way to deal with this situation 🙂

**Comment by josevalim** [comment]
`handle_event` actually expects the second argument to be a map, so I would suggest for you to wrap the list in a simple map. If you do so, the `element` version of it should work.

**Comment by orthodoX** [comment]
Thanks for a blazing fast reply @josevalim ! I've tried your suggestion right away, wrapped my js response as:

```js
{ products: products }
```
and pattern matched it the component:

```ex
def handle_event("reorder_products", %{"products" => products}, socket)
```

in the dev environment still works like a charm, but the test fails again:

```ex
reorder_param = %{
  "products" => [
     %{"order" => 1, "product_id" => product2.id},
     %{"order" => 3, "product_id" => product1.id},
     %{"order" => 2, "product_id" => product3.id}
  ]
}

home_live
  |> element("#user-products-list")
  |> render_hook("reorder_products", reorder_param)
```
throws `** (UndefinedFunctionError) function App.HomeLive.handle_event/3 is undefined or private`. It reverts to the scenario as if the element was not specified 🤔

**Comment by josevalim** [comment]
I see. That's because we make the decision based on phx-target. Does #user-products-list have phx-target pointing to a component? It sucks you need to add it for testing but I can't think of an alternative.

**Comment by orthodoX** [comment]
Yeah, that solved it! Adding a `phx-target="<%= @myself %>"` on the `#user-products-list` item made it work. I think my initial implementation had a phx-target attribute, but later I saw that if it's a custom hook, you can do a `pushEventTo` to any live view or component from js, so I thought that the attribute is necessary only for standard hooks like `phx-click`, etc.

I'm just curious now how come the `handle_params/3` accepted that list as an argument in the first place? Do you maybe think it's a good idea to enforce it, so the error is thrown if that argument is not a map?

**Comment by josevalim** [comment]
We should probably enforce that on the client, yes.

**Comment by orthodoX** [comment]
Awesome. I’ll close this issue then, but will make myself a reminder to open a new one for the handle_params/3 argument type enforce. Cheers! 🍻
