### ISSUE TITLE
Pass css classes to the main DIV

### ISSUE THREAD

**Issue by egze** [phoenixframework/phoenix_live_view#862]
### Environment

* Phoenix LiveView version (mix deps): 0.12.1

### Actual behavior

The div that is generated breaks my grid layout that I had before with class names. I can use the dom id to write the css rules, but I would rather prefer classes. I did not find a way how to add css classes to the main div.

### Expected behavior

Accept css classes that will be added to the other classes, that the LivieView is generating.

Happy to add a PR.

**Comment by josevalim** [comment]
It is already possible, search for the :container option in the docs.
