### ISSUE TITLE
IE 11: Missing Polyfill?

### ISSUE THREAD

**Issue by pehbehbeh** [phoenixframework/phoenix_live_view#864]
### Environment

* Elixir version (elixir -v): 1.10.2
* Phoenix version (mix deps): 1.5.1
* Phoenix LiveView version (mix deps): 0.12.1
* NodeJS version (node -v): 12.15.0
* NPM version (npm -v): 6.14.4
* Operating system: `bitwalker/alpine-elixir-phoenix:1.10.2` Docker Image
* Browsers you attempted to reproduce this bug on (the more the merrier): IE 11
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

We discovered some strange behaviour in IE 11. We are rendering some `live_component`s dynamically. The parent template looks like this:

```exs
[...]
<%= live_component @socket, current_step_component, id: current_step, customer: @customer %>
[...]
```

When `current_step_component` changes, the live component gets successfully replaced in all modern browsers. In IE 11 the old component gets removed but the new component does not get rendered. There is no error in the console to see, as you normally have with a missing polyfill.

But when I add the complete `core-js/stable` bundle (above all other polyfills), everything works just fine... so there must be a missing polyfill, right?

```js
import "core-js/stable";
import "regenerator-runtime/runtime";
```

**Comment by josevalim** [comment]
It is probably #863 .

**Comment by pehbehbeh** [comment]
#863 is also needed, but not the root of this problem. I already added the polyfill for that.

I tried to dig a little deeper with the [`create-polyfill-service-url`](https://www.npmjs.com/package/create-polyfill-service-url) tool, to list all polyfill wich are possibly needed. I'm sure, there is a better way to do this, but this is what I got:

```
npx create-polyfill-service-url analyse --file deps/phoenix_live_view/priv/static/phoenix_live_view.js
npx: installed 192 in 84.85s
https://cdn.polyfill.io/v3/polyfill.min.js?features=Array.from,Array.isArray,Array.prototype.entries,Array.prototype.filter,Array.prototype.find,Array.prototype.forEach,Array.prototype.indexOf,Array.prototype.keys,Array.prototype.map,Array.prototype.reduce,ArrayBuffer,console,CustomEvent,DataView,document,Function.prototype.bind,JSON,Map,Object.assign,Object.create,Object.defineProperty,Object.keys,Promise,Set,String.prototype.repeat,String.prototype.startsWith,String.prototype.trim,Symbol,Symbol.iterator,URLSearchParams,WeakMap,WeakSet,XMLHttpRequest
```

So I did a little research an all of these polyfills:

| Polyfill                    | Note                              |
| --------------------------- | --------------------------------- |
| Array.from                  | already documented                |
| Array.isArray               | supported as of IE 9              |
| Array.prototype.entries     | no IE support + undocumented      |
| Array.prototype.filter      | supported as of IE 9              |
| Array.prototype.find        | already documented                |
| Array.prototype.forEach     | already documented                |
| Array.prototype.indexOf     | supported as of IE 9              |
| Array.prototype.keys        | no IE support + undocumented      |
| Array.prototype.map         | supported as of IE 9              |
| Array.prototype.reduce      | supported as of IE 9              |
| ArrayBuffer                 | supported as of IE 10 (partially) |
| console                     | ?                                 |
| CustomEvent                 | already documented                |
| DataView                    | supported as of IE 10 (partially) |
| document                    | ?                                 |
| Function.prototype.bind     | supported as of IE 9              |
| JSON                        | supported as of IE 8              |
| Map                         | supported as of IE 11 (partially) |
| Object.assign               | already documented                |
| Object.create               | supported as of IE 9              |
| Object.defineProperty       | supported as of IE 9              |
| Object.keys                 | supported as of IE 9              |
| Promise                     | no IE support + undocumented      |
| Set                         | supported as of IE 11 (partially) |
| String.prototype.repeat     | no IE support + undocumented      |
| String.prototype.startsWith | already documented                |
| String.prototype.trim       | supported as of IE 9              |
| Symbol                      | no IE support + undocumented      |
| Symbol.iterator             | no IE support + undocumented      |
| URLSearchParams             | already documented                |
| WeakMap                     | supported as of IE 11 (partially) |
| WeakSet                     | no IE support + undocumented      |
| XMLHttpRequest              | supported as of IE 7 (partially)  |

So I tried adding the main suspects (partial support or undocumented by phoenix_live_view) one by one...

```js
import 'core-js/features/array/entries'
import 'core-js/features/array/keys'
import 'core-js/features/promise'
import 'core-js/features/string/repeat'
import 'core-js/features/symbol'
import 'core-js/features/symbol/iterator'
import 'core-js/features/weak-set'
import 'core-js/features/weak-map'
import 'core-js/features/set'
```

After adding the `Set` polyfill `core-js/features/set` everything works fine. In fact this is the only one which is needed.

**Comment by snewcomer** [comment]
@pehbehbeh Great find!  Since the only realistic Set implementation is from core-js, I think we can easily forgo the convenience and refactor the few places we use set to use features supported in IE11.  Is this something you would like to take on?

**Comment by chrismccord** [comment]
I'm fine with the set polypill for IE11. Can you send another PR with which includes `core-js/features/set` in the docs?

**Comment by kyleVsteger** [comment]
I believe this has cropped up again.
### Environment
Elixir (elixir -v)  `Elixir 1.11.3 (compiled with Erlang/OTP 21)`
Phoenix (npm) `1.5.7` 

### 
While trying to join a channel in IE11, I get: `error TypeError: Object doesn't support property or method 'find'`.
Adding `import "core-js/stable";` fixes the issue. I haven't done the dive to figure out which polyfill is missing yet —  will update if/when I do.
