### ISSUE TITLE
Security error in IE11 because of limited web socket connections

### ISSUE THREAD

**Issue by krns** [phoenixframework/phoenix_live_view#865]
### Environment

* Elixir version (elixir -v): 1.10.2
* Phoenix version (mix deps): 1.5.1
* Phoenix LiveView version (mix deps): 0.12.1
* NodeJS version (node -v): 12.15.0
* NPM version (npm -v): 6.14.4
* Operating system: bitwalker/alpine-elixir-phoenix:1.10.2 Docker Image
* Browsers you attempted to reproduce this bug on (the more the merrier): IE 11
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

While trying to make things work on IE11, @pehbehbeh and I got a `SecurityError` in the console. After some investigations we figured out that the IE11 only allows 6 web socket connection per page (see [Stackoverflow](https://stackoverflow.com/questions/52549799/securityerror-on-ie11-when-initializing-websocket/52657739#52657739)). After the browser is closed the web socket counter resets to 0.

To reproduce this you only have to open a LiveView application, reload six times and look in the console. Try out this one https://stormy-earth-96381.herokuapp.com/collaborative_canvas

We don't think there is much we can do about it, but want to write it down to help other IE11 fellow sufferers.

**Comment by chrismccord** [comment]
Can you expand on how the limit is reached? LiveView only opens a single websocket connection so a limit of 6 is not a problem. Thanks!

**Comment by krns** [comment]
You only have to make a simple reload of the page. We have tried multiple different LiveView applications..

Maybe the IE11 websocket counter is too lazy?

**Comment by chrismccord** [comment]
So you can trigger it by hard refreshing a tab six times? If that is the case, isn't this an IE11 bug for any website that opens a websocket connection? My only thought is we enter an aggressive reconnect state on page unload, so it's possible this is making IE angry, but we never open more than a single websocket connection. You can verify if this is the case by using the following option with a less aggressive reconnect:

```
let liveSocket = new LiveSocket("...", {reconnectAfterMs: () => 2000})
```

If you continue to get the error with the above, then I don't believe there is anything to be done here.

**Comment by chrismccord** [comment]
scratch that, the above won't work if we have unloaded the page, but you can verify by temporarily forcing a disconnect on unload:

in your app.js:
```
window.addEventListener("unload", e => liveSocket.disconnect())
```

Note that the above will cause issues when the browser restores from back/forward cache, but it will allow us to verify if there is something about our reconnect logic on unload, which attempts to reconnect every 100ms.

**Comment by krns** [comment]
> So you can trigger it by hard refreshing a tab six times? 

Exactly.

When I add your suggestion I also get the `SecurityError`.

**Comment by chrismccord** [comment]
If you added the disconnect code and it still exists, then there is nothing to be done here on our side. Every site that opens a websocket connection would have this same issue, so this is a bug on the IE11 side. Thanks!
