### ISSUE TITLE
Uncaught Error: no phx-target's found matching @myself of 2

### ISSUE THREAD

**Issue by syfgkjasdkn** [phoenixframework/phoenix_live_view#866]
### Environment

* Elixir version (elixir -v): lixir 1.10.3 (compiled with Erlang/OTP 22)
* Phoenix version (mix deps): phoenix 1.5.1
* Phoenix LiveView version (mix deps): phoenix_live_view 0.12.1
* NodeJS version (node -v): v14.0.0
* NPM version (npm -v): 6.14.4
* Operating system: macos
* Browsers you attempted to reproduce this bug on (the more the merrier): chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

`phx-target=<%= @myself %>` doesn't work in stateful components when component is not wrapped in an html element. I'm going to add a reproducible example based on https://github.com/phoenixframework/phoenix_live_view/issues/684:

```plain
~L"""
<%= live_component @socket, ComponentPicker, id: :component_picker, component: @component %>
<%= live_component @socket, @component, id: :component %>
"""
```
doesn't work, that is, the events are being sent to the root view instead of the component, and

```plain
~L"""
<%= live_component @socket, ComponentPicker, id: :component_picker, component: @component %>
<div><%= live_component @socket, @component, id: :component %></div>
"""
```
works, that is, the events are being sent to the stateful component (`@component`).

### Expected behavior

It works.

**Comment by syfgkjasdkn** [comment]
It seems due to the changes in https://github.com/phoenixframework/phoenix_live_view/commit/9a873b1ac5dfc650142a3b990837fb4a6354b7a4, 

https://github.com/phoenixframework/phoenix_live_view/commit/9a873b1ac5dfc650142a3b990837fb4a6354b7a4#diff-d4d7424e3b54ba50ca379d2944d59546L508 is always `null` when called from https://github.com/phoenixframework/phoenix_live_view/commit/9a873b1ac5dfc650142a3b990837fb4a6354b7a4#diff-d4d7424e3b54ba50ca379d2944d59546R2068 hence it always raises the exception in OP.

**Comment by chrismccord** [comment]
Let me know when you can provide a reproducible example and I will take a look. Thanks!

**Comment by syfgkjasdkn** [comment]
@chrismccord thank you! I've pushed the example to https://github.com/syfgkjasdkn/live-2

Steps to reproduce:

1. Go to `/form`
2. Pick `File Uploader` component
3. Choose any image in the file picker
4. And at this step I'm getting the error from the OP in the console
