### ISSUE TITLE
Allow DOM events to be prevented

### ISSUE THREAD

**Issue by robinvdvleuten** [phoenixframework/phoenix_live_view#872]
It would be a nice addition to `phx-click="trigger"` if it can be prevented by using something like `phx-click.prevent="trigger"`. My use case for example is a list of links that will be loaded through a LiveView event, but have a fallback if someone has Javascript disabled.

**Comment by josevalim** [comment]
Phoenix hooks are perfect for custom use cases like this, so please take a look at them instead. We need to find a good balance between having most needed attributes and have a surface API that is too large.
