### ISSUE TITLE
phx-page-loading attribute not trigging on form change

### ISSUE THREAD

**Issue by tomtaylor** [phoenixframework/phoenix_live_view#879]
### Environment

* Elixir version (elixir -v): 1.10.3
* Phoenix version (mix deps): 1.5.1
* Phoenix LiveView version (mix deps): 0.12.1
* NodeJS version (node -v): 10.19.0
* NPM version (npm -v): 6.14.4
* Operating system: MacOS
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, Safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

I have a form that acts as a dynamic search/filter interface for an admin system.

```
  <%= form_for @changeset, "#", [phx_change: :update_filter, phx_page_loading: true], fn f -> %>
    <div class="form__group form__group--inline">
      <%= text_input f, :name, class: "form__input form__input--narrow", placeholder: "Search for name…", phx_debounce: 300 %>

      <div class="form__select select-wrapper">
        <%= select f, :category_id, @category_options, prompt: "All categories", class: "form__input select-element" %>
      </div>

      <div class="form__select select-wrapper">
        <%= select f, :filter, @filter_options, prompt: "No filter", class: "form__input select-element" %>
      </div>

      <div class="form__select select-wrapper">
        <%= select f, :sort, @sort_options, class: "form__input select-element" %>
      </div>

    </div>
  <% end %>
```

On every form change the `update_filter` event handler takes the form params, does some stuff, then eventually fires `push_patch`, to update the URL. This all works fine, but the `phx-page-loading` attribute doesn't trigger the `phx:page-loading-start` window event, so no progress bar triggers.

Further down the same page I have some pagination buttons with a `phx-click` trigger. The `phx-page-loading` attribute works totally fine on these, firing the window event and the subsequent loading bar.

### Expected behavior

I'd expect the `phx-page-loading` attribute to work on a form change, not just on buttons.

**Comment by chrismccord** [comment]
`phx-page-loading` is only triggered on form submit, so phx-change (any form input changes) will not trigger the page loading event. You could implement a hook on the form and dispatch the event yourself in this particular case:

```
mounted(){
  this.el.addEventListener("input", () => NProgress.start())
}
```

We also place the `phx-change-loading` class on the form so you can provide feedback via css as needed. Thanks!

**Comment by tomtaylor** [comment]
OK, understood - thanks! Could I improve this in the docs?

**Comment by chrismccord** [comment]
Absolutely! Would love a doc PR to makes things clearer. Thanks!
