### ISSUE TITLE
Problem with polyfills on older Chrome (Chrome 41)

### ISSUE THREAD

**Issue by Tobi73** [phoenixframework/phoenix_live_view#880]
### Environment

* Elixir version (elixir -v): Erlang/OTP 21 and Elixir 1.8.2 (compiled with Erlang/OTP 20)
* Phoenix version (mix deps): 1.4.16
* Phoenix LiveView version (mix deps): 0.10.0
* NodeJS version (node -v): 12.2.0
* NPM version (npm -v): 6.9.0
* Operating system: CentOS 7
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome 41
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

Our team decided to implement simple CRUD for one of our entities using LiveView. Unfortunately we have encountered very weird live_redirect behaviour on Chrome 41 (implementation shown below). We already using polyfills that are mentioned in https://github.com/phoenixframework/phoenix_live_view#browser-support

```
 <%= live_redirect "New target group", to: Routes.live_path(@socket, TargetGroupsLive.New, "main"), class: "btn btn-primary" %>
```

When user clicks "New target group" button he gets this JavaScript error:

![image (11)](https://user-images.githubusercontent.com/13731148/81716156-1eb81680-948a-11ea-8942-6e5911d41440.png)

We tried to solve this problem by adding polyfills that were proposed by babel/corejs:
-  Copy phoenix.js  and phoenix_live_view.js from deps/phoenix*/priv/static/ to apps/our_application/assets/js
- Create .browserslistrc with chrome 41 support
- Install core-js: npm install --save core-js@3.6.5
- Edit .babelrc:
```
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "debug": true,
    	"useBuiltIns": "usage",
         corejs: { version: 3.6, proposals: true }
      }
    ]
  ]
}
```
- Build application for development: node node_modules/webpack/bin/webpack.js --mode development
- Copy and paste polyfills that were proposed by babel for phoenix.js and phoenix_live_view.js to our app.js
```
import 'core-js';
import 'core-js/es/symbol';
import 'core-js/es/symbol/iterator';
import 'core-js/es/symbol/description';
import 'core-js/es/array/concat';
import 'core-js/es/array/filter';
import 'core-js/es/array/find';
import 'core-js/es/array/for-each';
import 'core-js/es/array/from';
import 'core-js/es/array/index-of';
import 'core-js/es/array/iterator';
import 'core-js/es/array/map';
import 'core-js/es/array/reduce';
import 'core-js/es/array/slice';
import 'core-js/es/object/assign';
import 'core-js/es/object/to-string';
import 'core-js/es/regexp/constructor';
import 'core-js/es/regexp/to-string';
import 'core-js/es/set';
import 'core-js/es/string/replace';
import 'core-js/es/string/search';
import 'core-js/es/string/starts-with';
import 'core-js/es/string/trim';
import 'core-js/features/set/add-all';
import 'core-js/features/set/delete-all';
import 'core-js/features/set/difference';
import 'core-js/features/set/every';
import 'core-js/features/set/filter';
import 'core-js/features/set/find';
import 'core-js/features/set/intersection';
import 'core-js/features/set/is-disjoint-from';
import 'core-js/features/set/is-subset-of';
import 'core-js/features/set/is-superset-of';
import 'core-js/features/set/join';
import 'core-js/features/set/map';
import 'core-js/features/set/reduce';
import 'core-js/features/set/some';
import 'core-js/features/set/symmetric-difference';
import 'core-js/features/set/union';
import 'core-js/features/string/at';
import 'core-js/modules/web.dom-collections.for-each';
import 'core-js/modules/web.dom-collections.iterator';
import 'core-js/web/url';
import 'core-js/es/symbol/to-string-tag';
import 'core-js/es/array/includes';
import 'core-js/es/json/to-string-tag';
import 'core-js/es/math/to-string-tag';
import 'core-js/es/string/includes';
import 'core-js/es/string/match';
import "mdn-polyfills/Object.assign"
import "mdn-polyfills/CustomEvent"
import "mdn-polyfills/String.prototype.startsWith"
import "mdn-polyfills/Array.from"
import "mdn-polyfills/NodeList.prototype.forEach"
import "mdn-polyfills/Element.prototype.closest"
import "mdn-polyfills/Element.prototype.matches"
import "mdn-polyfills/Node.prototype.remove"
import "child-replace-with-polyfill"
import "url-search-params-polyfill"
import "formdata-polyfill"
import "classlist-polyfill"
import "@webcomponents/template"
import "shim-keyboard-event-key"
```

This solved our problem  with "New Target Group" button but now we are getting weird error while working with selects:
![image (12)](https://user-images.githubusercontent.com/13731148/81719031-90de2a80-948d-11ea-97c5-36b7644f5034.png)

**Comment by chrismccord** [comment]
The initial duplicate ID error is not polyfill related, you added duplicate IDs :) Can you verify that undoing the polyfills and simply fixing the duplicate DOM ID problem on your side fixes the issue?

**Comment by Tobi73** [comment]
> The initial duplicate ID error is not polyfill related, you added duplicate IDs :) Can you verify that undoing the polyfills and simply fixing the duplicate DOM ID problem on your side fixes the issue?

We have removed duplicating IDs and tried again with recommended polyfills (https://github.com/phoenixframework/phoenix_live_view#browser-support):
```
import "mdn-polyfills/Object.assign"
import "mdn-polyfills/CustomEvent"
import "mdn-polyfills/String.prototype.startsWith"
import "mdn-polyfills/Array.from"
import "mdn-polyfills/NodeList.prototype.forEach"
import "mdn-polyfills/Element.prototype.closest"
import "mdn-polyfills/Element.prototype.matches"
import "mdn-polyfills/Node.prototype.remove"
import "child-replace-with-polyfill"
import "url-search-params-polyfill"
import "formdata-polyfill"
import "classlist-polyfill"
import "@webcomponents/template"
import "shim-keyboard-event-key"
```

Unfortunately, we are still getting the same error:
![image](https://user-images.githubusercontent.com/13731148/81724302-d3ebce00-948c-11ea-81d0-609abd01f506.png)
![image](https://user-images.githubusercontent.com/13731148/81724332-dd753600-948c-11ea-90ea-ca4facb2ea0b.png)

**Comment by chrismccord** [comment]
Please remove all the polyfills and report back. The polyfills are only required for IE so let's make sure they are not causing other issues. If you continue to see issues without the polyfills, we'll need to see a minimal example repo that reproduces the issue as there is very little to go off of without it. Thanks!
