### ISSUE TITLE
Provide life-cycle CSS classes

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix_live_view#89]
Today, we have life-cycle classes only at the LiveView root: phx-disconnected and phx-loading. We should document those accordingly.

I also suggest to provide life-cycles for every event. For example, if a button is clicked, a phx-clicked class will be added until click "response" is received from the server. Similar for phx-change and phx-submit events on a form. This probably requires #569 to be implemented.

**Comment by sntran** [comment]
I'd second this. The various classes during the life cycle of an interaction would allow easier CSS animations. Some inspirations from Vue: https://vuejs.org/v2/guide/transitions.html#List-Move-Transitions

**Comment by suazithustra** [comment]
+

**Comment by brachialix** [comment]
+1
