### ISSUE TITLE
Does LiveComponent intercept "click" events?

### ISSUE THREAD

**Issue by Abat** [phoenixframework/phoenix_live_view#891]
I have an html element inside of LiveComponent. It's not "converted" to Phoenix LiveView or LiveComponent element yet, so still relies on class name and jQuery event listener.

` <a href="#" class="comment-control-reply"><%= gettext "reply" %></a>`

`$(commentControlReply).on("click", function(e) {
        console.info(e)
})`

This worked when it was not a child of LiveComponent.

**Comment by josevalim** [comment]
Hi @Abat! Please use the [ElixirForum](http://www.elixirforum.com) or StackOverflow for questions/help/feedback, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!

But generally speaking, if you want to have customJS code, you need to use phx-hooks.

**Comment by Abat** [comment]
Hi @josevalim !
