### ISSUE TITLE
@myself can work by accident

### ISSUE THREAD

**Issue by benwilson512** [phoenixframework/phoenix_live_view#895]
Hey folks,

Recently when attempting to use `send_update` on 0.12.1 I created something that worked by accident, and then later broke, which was very confusing.

The short version is that I was doing this inside a live component:

```
Task.async(fn ->
result = HTTP.get(url)

{:result, socket.assigns.myself, result}
end)
```

And then in the parent doing:

```
def handle_info({_, {:result, component_id, result}, socket) do
  send_update(FormComponent, id: component_id, result: result)
  {:noreply, socket}
end
```

This _shouldn't_ work. `@myself` is documented to be the "internal unique reference" to the component. However, it _did_ work because at the end of the day `@myself` is merely an integer counting up from 0. There were 2 components on the page, so it had a value of `1`. Also, I was editing the form component for product id 1, so voila, the value worked.

I _should_ have been doing `{:result, socket.assigns.id, result}`.

I propose that `@myself` should be namespaced in some way to make it very difficult for it to accidentally collide with a specific external component id.

**Comment by benwilson512** [comment]
Tangentially, a follow on proposal:

## send_update should raise if the component doesn't exist

Currently the behaviour is that nothing happens. This makes it difficult to sort out where the problem is. Is the problem that I'm not using the right component id? Or is the issue that I'm not doing the right thing in `update/2`? It's quite hard to say.

**Comment by josevalim** [comment]
For the first issue, maybe we can make `@myself` return `%Phoenix.LiveComponent.CID{cid: int}`. Then we implement `Phoenix.HTML.Safe` for said struct that simply returns the cid as a string.

For the second issue, there is #739. Note we should warn and not raise, as race conditions could make it so the component no longer is on the page. For example, imagine you do an async request that should "reply" to the component, but someone closes the component on the UI.

**Comment by benwilson512** [comment]
Good point about #739. A warning or even a debug level thing would all work fine for the purpose of debugging in development, so cool!

With respect to the main issue, if I see a CID (presumably Component ID) I guess I still don't have a strong sense that this is something internal vs something that the parent has. Can you elaborate on why @myself and @id could ever not be the same? That'd be another route here too.

**Comment by josevalim** [comment]
@benwilson512 the ID is something you control and it can be anything. The CID is completely internal to LV and is used to communicate between client/server.

**Comment by benwilson512** [comment]
OK great, makes sense.
