### ISSUE TITLE
Republish documentation for Module Doc Sections

### ISSUE THREAD

**Issue by davydog187** [phoenixframework/phoenix_live_view#908]
<img width="307" alt="Screen Shot 2020-05-21 at 12 44 51 PM" src="https://user-images.githubusercontent.com/1019721/82583127-e2a74480-9b60-11ea-8800-e06aca0ab326.png">

The latest version of `ex_doc` includes a feature for showing the sections in module docs. As shown above, this is really helpful for navigating `Phoenix.LiveView` as it has particularly long module documentation.

The version has already been updated, it just needs a republish. This would be greatly appreciated! :)

**Comment by josevalim** [comment]
We plan to ship a new version soon, when we do it it will be "fixed" too! Thanks!
