### ISSUE TITLE
render functions are inconsistently named

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix_live_view#917]
Today, the "render(view, element(...))" function synchronizes with the LV before looking up the element. All other `render_` functions do not synchronize.

We have two options: automatically synchronize or change the naming of the functions. I am thinking about automatically synchronizing, since synchronizing is simply a call which should be quite fast.

**Comment by leandrocp** [comment]
Auto sync has no side effects or breaking changes, besides a small performance penalty?
_Just asking out of curiosity_ :)

**Comment by josevalim** [comment]
Yes, even the perf is negligible. I pushed autosync to master. :)
