### ISSUE TITLE
Flash flickers

### ISSUE THREAD

**Issue by IvanRublev** [phoenixframework/phoenix_live_view#918]
### Environment

* Elixir version (elixir -v): Elixir 1.10.2 (compiled with Erlang/OTP 21)
* Phoenix version (mix deps): 1.4.16
* Phoenix LiveView version (mix deps): 0.12.1 (and 0.13.1)
* NodeJS version (node -v): v13.7.0
* NPM version (npm -v): 6.13.6
* Operating system: macOS
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

When putting flash into the socket with the following code:
```
socket
 |> put_flash(:error, "Still have the error.")
 |> redirect(to: "/")
```
... and make user to run it three times in a row after the first redirect the flash appears after the second redirect it disappears after the third one it appears again.

https://github.com/IvanRublev/phoenix_live_view_example/tree/evenly_flash

### Expected behavior

Flash appears after each `redirect` or `push_redirect` if it was explicitly put before the redirect.

**Comment by IvanRublev** [comment]
@chrismccord how can we address this issue?

**Comment by josevalim** [comment]
We will look into when we have time to look into it.

**Comment by josevalim** [comment]
Closing in favor of #1008.
