### ISSUE TITLE
Possible regression on live link behaviour

### ISSUE THREAD

**Issue by cichacz** [phoenixframework/phoenix_live_view#931]
### Environment

* Elixir version (elixir -v): 1.9.2
* Phoenix version (mix deps): 1.4.17
* Phoenix LiveView version (mix deps): 0.13.2
* NodeJS version (node -v): v12.16.3
* NPM version (npm -v): 6.14.4
* Operating system: macOS
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, Firefox, Safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

Changes from 75b0b5cfde9826e015927475ab51ad52efc8f6f1 introduced header `x-response-url` which I believe can be missing in some cases.
One of those is when using auth plug (pow 1.0.18 in my case).
If we have logged in and session has expired after some time and then we try to click some live link, then the router pipeline won't reach the code responsible for adding `x-response-url` header which will result in the following error in the browser's console:
```
phoenix_live_view.js:1265 Uncaught TypeError: Failed to construct 'URL': Invalid URL
    at o.n.onreadystatechange (phoenix_live_view.js:1265)
    at XMLHttpRequest.s.onreadystatechange (c611e91c421989e28042.js:54)
```
phoenix_live_view.js:1265 => https://github.com/phoenixframework/phoenix_live_view/blob/master/assets/js/phoenix_live_view.js#L918

I assume that there's way to add `x-response-url` to the pipeline somewhere before auth plug stops client from going further, but I think that this header should be checked for existence before using.

### Expected behavior

Ideally it should work like in `v 0.12` where on failed navigation website just refreshed itself which then triggered a redirect to login page for cases with protected paths.

**Comment by josevalim** [comment]
Yeah, if the header is not there we should treat it as a regular redirect.

**Comment by jodyalbritton** [comment]
Is there a temporary fix for this? Just updated my app and I am also having the issue.

I used phx_gen_auth for my authentication.
