### ISSUE TITLE
Add Typescript definitions for live view

### ISSUE THREAD

**Issue by germanjrd** [phoenixframework/phoenix_live_view#941]
I am trying to write my assets in Typescript, there are some types defined for Phoenix (up to 1.4) but none for LiveView

**Comment by chrismccord** [comment]
I have no plans for this but folks are welcome to maintain a typescript definitions in an external project. Thanks!

**Comment by pzingg** [comment]
I am submitting a definition pull request to DefinitelyTyped right now, based on 0.13.3.

**Comment by pzingg** [comment]
TS definition should be available now on DefinitelyTyped master branch. Add @types/phoenix_live_view to your node modules. Send me any issues or comments.

**Comment by ryanwinchester** [comment]
> TS definition should be available now on DefinitelyTyped master branch. Add @types/phoenix_live_view to your node modules. Send me any issues or comments.

`uploaders` missing from `SocketOptions` ;)
