### ISSUE TITLE
document.activeElement can be null in IE11 and live view doesn't expect that

### ISSUE THREAD

**Issue by breunigs** [phoenixframework/phoenix_live_view#948]
### Environment

* Elixir version (elixir -v): Elixir 1.10.3 (compiled with Erlang/OTP 21)
* Phoenix version (mix deps): 1.5.3
* Phoenix LiveView version (mix deps): 0.13.2
* NodeJS version (node -v): v10.16.0
* NPM version (npm -v): 6.9.0
* Operating system: Linux, but IE11 ran in the Microsoft provided IE11 Test Images on Windows 7 and Windows 10 (https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/)
* Browsers you attempted to reproduce this bug on (the more the merrier): IE11. Other browsers don't have this issue to my knowledge.
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes.

### Actual behavior

When `document.activeElement` is `null`, live view throws `Unable to get property 'type' of undefined or null reference` in `isTextualInput`. Unfortunately source maps don't seem to work (neither my production deploy, nor the more or less vanilla demo app) so I can't provide a decent stacktrace. I can spend the effort to produce one, if desired.

### Expected behavior

Swallow the error, or run the code in question on the `body` (this is how other browsers behave in that scenario).

### Steps to reproduce / demo app

To reproduce the error:
* user clicks a `live_patch` link
* link must not be present in the navigated-to page.
* observe that `document.activeElement` is now `null`
* without clicking anything, wait for a server push to update the page
* above error is triggered

I have a demo app (https://github.com/breunigs/plv-ie11-activeElement-null) that reproduces the issue. It's mostly vanilla except for the polyfills and the remains of reproducing this issue. To see the error with the demo app, try roughly:
* open IE11 on a blank page, and open the Inspector Console
* navigate to the running app
* it prints the active element to the console every second, it should not be `null` now
* click the "click me" link. It should be removed from the page. The active element should be `null` after loading finishes.
* wait for the server to update the clock variable, which happens every 30s.
Since the demo is timing dependent, you might need to open a fresh tab to reset the `%{assigns: %{hide: 1}}` state.

**Comment by breunigs** [comment]
I'm currently testing a patch for that on my production build. I will submit a PR once I've verified it stops the error from appearing in all the wild IE11 installations out there.

**Comment by chrismccord** [comment]
ping @breunigs ! Any luck with your patch?

**Comment by breunigs** [comment]
The patch is deployed and I have not seen this issue again. There has been IE11 traffic in the meantime, but the site itself is low traffic and IE11 is not exactly popular these days. 

The patch is pretty straight forward, though, I can prepare a PR in the next few days:

https://github.com/phoenixframework/phoenix_live_view/compare/master...breunigs:ie11-active-element

**Comment by chrismccord** [comment]
Great! Please do
