### ISSUE TITLE
Could static references point to static of dynamic part?

### ISSUE THREAD

**Issue by 50kudos** [phoenixframework/phoenix_live_view#949]
I found the recent enhancement "Share component statics" at https://github.com/phoenixframework/phoenix_live_view/pull/913 to be really promising.

A general use case is for recursive `live_component` 
```elixir
<%= live_component(@socket, __MODULE__, id: id + 1) %>
```
For example, CommentComponent. 

Here is my use case with example of duplicated static payload for each recursive call.

![Screen Shot 2020-06-04 at 12 52 51 AM](https://user-images.githubusercontent.com/2753398/83728101-94507600-a635-11ea-938b-38f1ed125b6d.png)

My question is, is it possible to improve `find_static/2` to traverse through dynamic part to nested static of recursive call, ~~given the list of recursive components is in flat shape  {c: {0:, .. 1:, .., 2: ..}}~~?

**Comment by josevalim** [comment]
See #950. It is still missing the client changes.

**Comment by 50kudos** [comment]
Oh this efficient Diff is a huge work. I really appreciate.
