### ISSUE TITLE
Unclear compiler error when attempting to use `sigil_L` in helper function

### ISSUE THREAD

**Issue by Qqwy** [phoenixframework/phoenix_live_view#954]
### Environment

* Elixir version (elixir -v):
* Phoenix version (mix deps):
* Phoenix LiveView version (mix deps):
* NodeJS version (node -v):
* NPM version (npm -v):
* Operating system:
* Browsers you attempted to reproduce this bug on (the more the merrier): 
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:

### Example:

```elixir
defmodule MyApp.SomeComponent do
  use MyApp, :live_component

  def render(assigns) do
    ~L"""
    Some text here
    <%= my_fun("Chris") %>
    """
  end

  def my_fun(name) do
    ~L"""
    Hello, #{name}!
    """
  end
end
```

Alternatively, try replacing the definition of `my_fun` with

```elixir
  def my_fun(name) do
    ~L"""
    Some static string
    """
  end
```

which has the same result.

### Actual behavior

```elixir
== Compilation error in file lib/my_app/live/some_component.ex ==
** (ArgumentError) argument error
```

### Expected behavior

A clear error telling me that it is not possible to use `sigil_L` this way, and pointing to the right direction on how to resolve it: `sigil_L` expects a variable named `assigns` to be in scope. C.f. issue #899 which talks about a similar situation.

To resolve this particular case, we might write `my_fun/1` as

```elixir
  def my_fun(name) do
    assigns = %{name: name}
    ~L"""
    Hello, <%= @name %>!
    """
  end
```

However, this situation does beg the more high-level question whether it is desireable to depend on an `assigns` variable when using the `sigil_L` inside a function. Maybe there is a better conceptual way to allow people to write LEEx-returning helper functions?

**Comment by josevalim** [comment]
We need to push people towards using assigns because we can perform change/diff tracking only with assigns. There is section in the docs explaining why using variables is a bad idea, so I recommend checking those out. On master the warning is now:

``` 
** (CompileError) test/support/live_views/components.ex:26: expected "assigns" to expand to an existing variable or be part of a match
```

**Comment by Qqwy** [comment]
That is indeed a much better error-message :+1: .
