### ISSUE TITLE
phx-click-loading class not removed

### ISSUE THREAD

**Issue by jfreeze** [phoenixframework/phoenix_live_view#956]
### Environment

* Elixir version (elixir -v): Elixir 1.10.3 (compiled with Erlang/OTP 21)
* Phoenix version (mix deps): 1.5.3
* Phoenix LiveView version (mix deps): 0.13.3
* NodeJS version (node -v): 13.12.0
* NPM version (npm -v): 6.14.4
* Operating system: Darwin Kernel Version 19.4.0
* Browsers you attempted to reproduce this bug on (the more the merrier):  Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

 Grab the sample project

    git clone https://github.com/jfreeze/click_load.git
 
* run the project
* browse to http://localhost:4000/dash
* inspect the page and go to Elements
* inspect "dash"
* click dash

You should see the `.phx-click-loading` class persist.

I was not able to reproduce this until I put this code into the `_event_dropdown_menu.html.leex` file.

### Expected behavior

`.phx-click-loading` class should be cleared from the link.

**Comment by chrismccord** [comment]
You are rendering your _user_menu template in the root layout *outside* of the `@inner_content`, which is your LiveView and live layout. The fix would be to either use regular links in your root layout or move the live links into your live layout. We could detect such links and undo the classes, but it's trickier so I would prefer to wait to see if this comes up more frequently. Thanks!
