### ISSUE TITLE
Improvement: Could have send_update/2 complain if given unknown module

### ISSUE THREAD

**Issue by henrik** [phoenixframework/phoenix_live_view#957]
It took me a while to debug an issue where I did `send_update(MyComponent, foo: "bar")` and nothing happened. Turned out I hadn't aliased the module, so I needed to do `send_update(MyAppWeb.MyComponent, foo: "bar")`.

It would have been supremely helpful if LiveView had raised an exception.

I'm thinking just [checking for module existence](https://stackoverflow.com/a/43881511/6962) and raising an error if the module does not exist (is not compiled). Any gotchas or concerns with that?

If this sounds like a good idea I'm happy to attempt a PR.

I assume it'd be best to catch it in Channel:
https://github.com/phoenixframework/phoenix_live_view/blob/32fcf054897fa3c21c9fa57dceee48fb58b60000/lib/phoenix_live_view/channel.ex#L27-L29

Which is called by the LiveView's `send_update`: https://github.com/phoenixframework/phoenix_live_view/blob/32fcf054897fa3c21c9fa57dceee48fb58b60000/lib/phoenix_live_view.ex#L2374-L2382
So that both benefit from this check.

**Comment by josevalim** [comment]
Dup of #739. PRs are welcome!

**Comment by henrik** [comment]
Hm, after looking into #739, I wonder if there might be two non-duplicate but related improvements we could make:

* The one I suggested here, where we raise if the module doesn't exist
* The one in #739, where we warn if there's no current component matching the module and ID

Trying to bake both situations into a single error message doesn't read well: "There is no active MyComponent with ID 123, or there is no MyComponent module available".

Or we could settle for a message like "There is no active MyComponent with ID 123", but this doesn't make it nearly as clear that there is no MyComponent module available.

So I'm thinking an exception like "Can't send_update to MyComponent (module MyComponent is not available)" when the module doesn't exist at all, and then (in #739) a warning like "There is no active MyComponent with ID 123" when the module exists but no component is active.

If you agree, I'd be happy to make a PR for the raise. I might look into the warning as well, but I suspect it requires a better grasp of the codebase than I currently have.

**Comment by josevalim** [comment]
If the ID does not exist, then we can check and raise if the module does it exist at all but the ID check has to come first for perf reasons.

**Comment by henrik** [comment]
That makes sense. Thanks for explaining!
