### ISSUE TITLE
Encoding strings with embedded spaces in data attribute of element fails

### ISSUE THREAD

**Issue by mindok** [phoenixframework/phoenix_live_view#966]
### Environment

* Elixir version (elixir -v): 1.9.4
* Phoenix version (mix deps): 1.5.3
* Phoenix LiveView version (mix deps): 0.13.3
* NodeJS version (node -v): 11.14.0
* NPM version (npm -v): 6.7.0
* Operating system: Windows :(
* Browsers you attempted to reproduce this bug on (the more the merrier):  Firefox, Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Minimal project to reproduce
https://github.com/mindok/encoding_bug

The file here reproduces:
https://github.com/mindok/encoding_bug/blob/master/lib/encoding_bug_web/live/encode_live.ex 

### Actual behavior

Strings with embedded spaces and quotes are not encoded correctly in data attributes in templates (e.g. `<div id="a" data-a=<%= @a %> .../>`) This results in an InvalidCharacterError in Firefox and a more useful error message in Chrome:
Uncaught DOMException: Failed to execute 'setAttribute' on 'Element': '0&quot;' is not a valid attribute name.

Any assigns referenced in the template following this are not updated.

### Expected behavior

No errors. Assigns in template updated appropriately.

### Why it's an issue in real life
Any map values with embedded spaces that are encoded with `Jason.encode` and embedded in a data attribute ready for a JS hook to access break the application.

**Comment by seb3s** [comment]
Hello,
I guess it should be :
```
<div id="a" data-a="<%= @a %>">a should update here: <%= @a %></div>
<div id="b" data-b="<%= @b %>">b should update here: <%= @b %></div>
```
cheers,
Sébastien

**Comment by josevalim** [comment]
This is expected. (L)EEx is a literal template engine, it doesn't have any understanding of HTML. You need to wrap it in quotes as suggested by @seb3s.

**Comment by mindok** [comment]
That would do it. Thanks!
