### ISSUE TITLE
Two <use> elements as siblings results in the second one not being visible

### ISSUE THREAD

**Issue by axelson** [phoenixframework/phoenix_live_view#968]
### Environment

* Elixir version (elixir -v): Elixir 1.10.3 (compiled with Erlang/OTP 22)
* Phoenix version (mix deps): 1.5.3 (phoenix) 8e16febe
* Phoenix LiveView version (mix deps): 0.13.3 (phoenix_live_view) c6309a7d
* NodeJS version (node -v): v10.4.1
* NPM version (npm -v): 6.1.0
* Operating system: Mac OS 10.14.6
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox, Safari, Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

A stateful LiveComponent that renders two svg `<use>` statements next to each other results with one of the `<use>` statements nested within the other (in the dev tools), resulting in the second `<use>` statement not being visible.

Full reproduction steps are in the repo: https://github.com/axelson/phoenix_live_view_repro2

gif:
![ezgif-4-cc860a8641c3](https://user-images.githubusercontent.com/9973/84220741-42618300-aa6f-11ea-9005-73735fc95606.gif)

livesocket debug:
![Screenshot 2020-06-09 16 31 04](https://user-images.githubusercontent.com/9973/84220770-5311f900-aa6f-11ea-886f-49489c748966.png)

Dev tools HTML:
![Screenshot 2020-06-09 16 28 18](https://user-images.githubusercontent.com/9973/84220807-6f159a80-aa6f-11ea-8e45-f8b7145a488e.png)

### Expected behavior

Both circles should continue to be visible

Workarounds:
* Wrap the first `use` with `<g>` (as in `render2`)
* Don't use a stateful component

**Comment by josevalim** [comment]
This is the same as the other issue. Wrapping it in `<svg>` fixes it. :) It boils down to LV parsing it as HTML and then weird rules being applied.
