### ISSUE TITLE
Set a css class on element that contains hook-binding on pushes from hook code using pushEvent() and pushEventTo()

### ISSUE THREAD

**Issue by clemensm** [phoenixframework/phoenix_live_view#972]
Hi there

I've recently stumbled upon the problem that I needed to clear some legacy loading overlay, even if no change was pushed so that the hook's `update` function was never called.

The proposed solution from Elixir Forums was to use the css classes that are set on binding events (e.g. `phx-click-loading` etc), but for legacy reasons I need to push the events manually from inside the hook. ([See here for proposed solution](https://elixirforum.com/t/get-js-notification-if-liveview-did-not-push-a-change/32284/2?u=clemensm).

Question: Would it be possible to add a class on the element that contains the hook? I've had a look at the code, it looks like something along the lines of this change (not to sure about the exact semantics here):

```
pushHookEvent(targetCtx, event, payload){
  this.pushWithReply(() => this.el.classList.add("phx-hook-loading"), "event", {
    ...
  })
}
```

would be sufficient already? What do you think?

**Comment by josevalim** [comment]
Hi @clemensm, since you are using the hook, you can add the class from within the hook itself. :)

**Comment by clemensm** [comment]
Hi @josevalim, the question is: would it be removed automatically once the server responds (with no changes to the element), like it is cleaned for .e.g the `phx-click-loading` calss?

**Comment by chrismccord** [comment]
In master, you can now do:

```
this.el.classList.add("my-class")
this.pushEvent("my-event", (reply) => this.el.classList.remove("my-class")))
```

Thanks!

**Comment by chrismccord** [comment]
Note: you will also need to maintain the class in `updated`, for example by checking some flag and swapping the flag on reply

**Comment by clemensm** [comment]
Cool, thanks!
