### ISSUE TITLE
Template does not render changes in nested templates if name of assign is changed on call to render function

### ISSUE THREAD

**Issue by clemensm** [phoenixframework/phoenix_live_view#973]
### Environment

* Elixir version (elixir -v): 1.10.2
* Phoenix version (mix deps): 1.5.3
* Phoenix LiveView version (mix deps): 0.13.3
* NodeJS version (node -v): v11.1.0
* NPM version (npm -v): 6.11.3
* Operating system: macos 10.15.5
* Browsers you attempted to reproduce this bug on (the more the merrier): 
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:

### Actual behavior

When rendering a template from LiveView using an existing View, and the template conatains a nested template where an assigned value from the LiveView is renamed, the nested template is not updated/rerendered on changes to the assign in the LiveView. This happens only if the nested template gets the `@socket` assign passed from the outer template.

### Reproduce

I've created a [sample project](https://github.com/phoenixframework/phoenix_live_view/files/4771165/bug_with_changed_name.zip) with `mix phx.new --live --no-ecto bug` to reproduce the issue, you can simply run it to see the problem (still needs to run `mix deps.get` and `npm install`).

The only things I've chnged from the generated project are:

1. Created a default `BugWeb.PageView`.
2. Moved the templates `page_live.html.leex` and `sub_template.html.leex` into the `templates/page` folder
3. Adjusted the `PageLive` module to change the assigned value on button click. 

So we've got these files:

**page_live.ex**
```
defmodule BugWeb.PageLive do
  use BugWeb, :live_view

  @impl true
  def mount(_params, _session, socket) do
    {:ok, assign(socket, value: :rand.uniform())}
  end

  @impl true
  def handle_event("click", _params, socket) do
    {:noreply, assign(socket, value: :rand.uniform())}
  end

  def render(assigns) do
    Phoenix.View.render(BugWeb.PageView, "page_live.html", assigns)
  end
end
```

**page_view.ex**
```
defmodule BugWeb.PageView do
  use BugWeb, :view
end
```

**page_live.html.leex**
```
<div>
  <button phx-click="click">Click me to change value</button>
  <p><%= @value %></p>
  <%# This fails to update when the button is clicked%>
  <%= render "sub_template.html", socket: @socket, other_name: @value %>
  <%# While this works just fine %>
  <%= render "sub_template.html", other_name: @value %>
  <%# And this works as well %>
  <%= render "other_sub_template.html", socket: @socket, value: @value %>
</div>
```

**sub_template.html.leex**
```
<p style="color: red"><%= @other_name %></p>
```

**other_sub_template.html.leex**
```
<p style="color: green"><%= @value %></p>
```

### Expected behavior

The inner template should be rerendered to reflect the changes in the assign.

**Comment by josevalim** [comment]
Ack. I understand why this but happens, but I need to figure out the best fix for it. Maybe we should pass the changes as a hidden assign instead of as part of the socket.
