### ISSUE TITLE
live_patch does not render page update (or crashes) 

### ISSUE THREAD

**Issue by jfreeze** [phoenixframework/phoenix_live_view#976]
### Environment

* Elixir version (elixir -v): 1.10.3
* Phoenix version (mix deps): 1.5.3
* Phoenix LiveView version (mix deps): 0.13.3
* NodeJS version (node -v): v13.12.0
* NPM version (npm -v): 6.14.4
* Operating system: macOS
* Browsers you attempted to reproduce this bug on (the more the merrier):  Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes:

### Actual behavior

On my project I have a Dashboard menu with a`live_patch` link. On that page I have a click action on a Create Event button that generates a page update via `push_patch`. If I click the Dashboard link, then click the Create Event button, then click the Dashboard button again, I get a liveview crash with the javascript error: `Uncaught TypeError: Cannot read property '0' of undefined`.

I have created a sample app at 
    https://github.com/jfreeze/prop_zero

This sample app does not yield the same error, but it does not fail to update the page on the third click?

On the sample app do the following:

* Browse to http://localhost:4000/
* Click Dashboard
* Click Create Event button
* Click Dashboard
=> Page does not update
* comment out the live_component in `control_panel_live.html.leex` to remove the bug

The difference with my actual app is that LV crashes with the error `Uncaught TypeError: Cannot read property '0' of undefined.`

**Comment by josevalim** [comment]
Fixed in 171c99e. Will be merged with #950.
