### ISSUE TITLE
In nested components, events get sent to wrong component

### ISSUE THREAD

**Issue by mveytsman** [phoenixframework/phoenix_live_view#977]
### Environment

* Elixir version (elixir -v): 1.10.3
* Phoenix version (mix deps): 1.5.3
* Phoenix LiveView version (mix deps): 0.13.3
* NodeJS version (node -v): 12.18.0
* NPM version (npm -v): 6.14.4
* Operating system: Linux
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Setup

Here's a sample nested component

```elixir
defmodule MyAppWeb.ParentComponent do
  use MyAppWeb, :live_component

  require Logger
  def handle_event("event", _, socket) do
    Logger.info("event called on parent")

    {:noreply, socket}
  end

  def render(assigns) do
    ~L"""
    <div>hello</div>
    <div>world</div>
    <%= live_component @socket, MyAppWeb.ChildComponent, id: :child %>
    """
  end
end

defmodule MyAppWeb.ChildComponent do
  use MyAppWeb, :live_component

  require Logger

  @impl true
  def handle_event("event", _, socket) do
    Logger.info("event called on child")

    {:noreply, socket}
  end
  def render(assigns) do
    ~L"""
    <a href="#" phx-click="event" phx-target="<%= @myself %>">Click me</a>
    """
  end
end
```

I load it with `<%= live_component @socket, MyAppWeb.ParentComponent, id: :test %>`

### Actual behavior
When I click the link in the child component, the parent component gets the event, and I see `event called on parent` in the logs.

### Expected behavior

My expectation is that since I used `phx-target="<%= @myself %>"` in the child component, I would capture the event in the child and see `event called on child` in the logs.

### Workaround

Strangely, I found a workaround. If I make the parent component contain only one root element, like below, I see the event in the child!

```elixir
def render(assigns) do
    ~L"""
    <div>
        <div>hello</div>
        <div>world</div>
        <%= live_component @socket, MyAppWeb.ChildComponent, id: :child %>
    </div>
    """
end
```

I find that part very confusing but I imagine it will be helpful in debugging!

**Comment by Ian-GL** [comment]
I'm not sure what causes the issue, but I do suspect the wrapping div is expected so the engine can determine where does the live component starts & end, since the component by itself does not introduce elements to the DOM. Again, no idea hot it exactly works but I do think the outer div you put in your workaround is expected.

**Comment by mveytsman** [comment]
@Ian-GL I suspect this but the problem is that I found this when I was using the auto-generated form component made by the built in generators.

If we need to have wrapping divs for every component we should update the generators to do so.

**Comment by josevalim** [comment]
Closing in favor of #990.
