### ISSUE TITLE
x-data/x-show being ignored on first page load with Alpinejs

### ISSUE THREAD

**Issue by jfreeze** [phoenixframework/phoenix_live_view#996]
### Environment

* Elixir version (elixir -v): 1.10.3
* Phoenix version (mix deps): 1.5.3
* Phoenix LiveView version (mix deps): Master
* NodeJS version (node -v): v13.12.0
* NPM version (npm -v): 6.14.4
* Operating system: macOS 19.5.0 Darwin Kernel
* Browsers you attempted to reproduce this bug on (the more the merrier):  chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

Add Alpinejs to root.html.leex
    &lt;body>
      <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
    &lt;/body>

On a live page with the markup

    <div x-data="{foo:false}" @click="foo =! foo">
       <div x-show="foo">Hide/Show me</div>
    </div>

The inner div should be hidden on page first load, but is not.
However, the following workaround will work.

    <div x-data="{foo:false}" @click="foo =! foo">
      <div x-show="foo" style="display:none;">Hide/Show me</div>
    </div>

Also, if the element doesn't need LV interaction, you can do

    <div x-data="{foo:false}" @click="foo =! foo" phx-update="ignore">
      <div x-show="foo">Hide/Show me</div>
    </div>

**Comment by chrismccord** [comment]
What does your app.js look like? Can you include a sample application? Note that alpine *will not* hide the x-show elements by default during page load, so on it's own without LV, you need to style all x-show's and display none via css to avoid page flicker. I'm wondering how you're initializing alpine as it may be lazily initialized with LV connects, but I don't believe this is a LV issue.

**Comment by jfreeze** [comment]
I created a sample project  `mix phx.new --live --no-ecto alpine`
I modified `page_live.html.leex`

      <section class="phx-hero">
        <h1>Alpine Test</h1>
      </section>

      <section class="row">
        <article class="column">
          <div x-data="{b1: false}">
            <button x-show="b1" @click="b1 = !b1">Button 1 (click to hide)</button>
          </div>
          Not sure why it takes 2 clicks
        </article>

        <article class="column">
          <div phx-update="ignore" x-data="{b2: false}">
            <span @click="b2 = !b2">click me to see button 2</span>
            <button x-show="b2" @click="b2 = !b2">Button 2 (click to hide)</button>
          </div>
        </article>

        <article class="column">
          <div x-data="{b3: false}">
            This is the work around
            <button x-show="b3" @click="b3 = !b3" class="red" style="background-color: green; display:none;">Button 3
              (click to hide)</button>
            <button x-show="!b3" @click="b3 = !b3">Button 3 (click to show)</button>
          </div>
        </article>
      </section>

and `root.html.leex`

    <body>
      <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>

**Comment by chrismccord** [comment]
remove the `liveSocket.connect()` call in your app.js. Does the behavior still happen? Also note that without the `onBeforeElUpdated` snippet in your `dom` options, alpine will not work after a patch.

**Comment by jfreeze** [comment]
Yes, commenting out the line `liveSocket.connect()` removes the problem. The button is hidden on page load.

**Comment by chrismccord** [comment]
Add liveSocket.connect() back and add the necessary alpine clone code and report back:

```javascript
let liveSocket = new LiveSocket("/live", Socket, {
  dom: {
    onBeforeElUpdated(from, to){
      if(from.__x){ window.Alpine.clone(from.__x, to) }
    }
  },
  params: {_csrf_token: csrfToken}
})
```

Thanks!

**Comment by jfreeze** [comment]
That code fixes all problems.

**Comment by jfreeze** [comment]
Will that code need to be added by the user or will it become part of the standard?

**Comment by josevalim** [comment]
It is alpine specific. You have to add it. :)

**Comment by przemekciacka** [comment]
I found a similar problem in my project, but adding the following doesn't help.
```js
dom: {
    onBeforeElUpdated(from, to){
      if(from.__x){ window.Alpine.clone(from.__x, to) }
    }
}
```

I guess it executes on the second render when the socket connection is established and on any LiveView DOM update. However, when I edit it as the following nothing is logged to the console nor alert displays.

```js
dom: {
    onBeforeElUpdated(from, to){
      console.log('onBeforeElUpdated');
      alert(1);
    }
}
```

Thus, the alpine.js doesn't handle properly the second render.

**Comment by josevalim** [comment]
It is never executed or it is executed only in over-the-wire updates? If it is never executed, please make sure you are on latest LiveView and that you nuked your `node_modules`.

**Comment by przemekciacka** [comment]
> It is never executed or it is executed only in over-the-wire updates?

It wasn't executed at all.
I've updated the `phoenix_live_view` hex package to version `0.13.3` and it's working like a charm right now 😃  Thanks!

**Comment by luopio** [comment]
Thanks for the fix, a slight variation was required with `phoenix 1.6.5 & phoenix_live_view 0.17.5 & alpinejs 3.7.1`:
```
let liveSocket = new LiveSocket("/live", Socket, {
    dom: {
        onBeforeElUpdated(from, to) {
            if (from._x_dataStack) {
              window.Alpine.clone(from, to);
            }
          },
    },
    params: { _csrf_token: csrfToken }
})
```

**Comment by alibeylinurlan** [comment]
here is a simple method and working for me.
---------------------------------------------------
In CSS
`.alpine-toggle-fix {
    width: 0 !important;
    height: 0 !important;
    overflow: hidden;
}`
In Js
`$(document).ready(function(){
    $(".alpine-toggle-fix").removeClass("alpine-toggle-fix");
});`
In HTML
`<div
       class="alpine-toggle-fix"
       x-show=".......
   >`
